### ISSUE TITLE
Time settings

### ISSUE THREAD

**Issue by jez** [darkreader/darkreader#10]
I recently switched to Dark Reader because I've found that it's generally better about inverting the colors consistently.

One feature I miss from the extension I had been using ([Night Reading Mode](https://chrome.google.com/webstore/detail/night-reading-mode/chcciiimjmlgcoabgfdhkfjdcgfpgndi)) was the ability to have dark mode "On", "Off", or "Auto", the last of which would turn dark mode on during a range of times (i.e., at night). It also let you override the above setting per-domain.

As an example, you could have it Night Reading Mode to "Auto" (so it'd become dark from maybe 7:00 p.m. to 7:00 a.m.), but have something like hslpicker.com be always regardless "Off".

**Comment by acarl005** [comment]
This app has similar appeals to [f.lux](https://justgetflux.com/). It would be nice if it could enable itself at night without intervention, as I often forget to enable it at night.

**Comment by ValentinDrean** [comment]
And even add a "enable on every websites" would be also super awesome!

**Comment by gsirvine** [comment]
I would very much like a simple time scheduler.  :)

**Comment by alexanderby** [comment]
This feature was released recently https://darkreader.org/blog/time-settings/

**Comment by addeps3** [comment]
Excellent that this was added, the only detail I would bring up is perhaps finding the time-setting a bit more intuitive. Thank you!

**Comment by majkinetor** [comment]
Yes, its almost invisible, I had to come here to find out it exists.

Anyway, I think it should still be enhanced. I keep ligth option during the day, and dark option during the night. It would be great if I could schedule this so it happens automatically. For that to happen I guess we need to save settings and schedule when it should be applied - I could apply dark settings from 18-06 and light settings from 06-18.

**Comment by MitchTalmadge** [comment]
I also had to come here to realize that it already exists. Definitely not intuitive. Why not keep the dots there at all times? Maybe change it to a gear icon even

**Comment by ooopscc** [comment]
Found this by search. Better add a larger area to exhibit the amazing feature.

**Comment by taprobane99** [comment]
This is a great feature but needs to be better advertised in the app itself. I only found it by searching google.

**Comment by GPPassos** [comment]
+1 had to come here to find out this exists
