### ISSUE TITLE
Remove Discord Support from Global Dark List

### ISSUE THREAD

**Issue by Galaxyzd** [darkreader/darkreader#1000]
https://support.discordapp.com/hc/en-us/articles/218449248-Permissions-Lockout

My eyes are burning and I can't fix it.

**Comment by alexanderby** [comment]
Oh, so many trouble with Discord. URL templates for avoiding this are still not implemented. Somebody adds it, somebody removes it. Feel free to remove it from the [Dark Sites list](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config#L36).
