### ISSUE TITLE
[Dynamic] Custom CSS doesn't apply automatically

### ISSUE THREAD

**Issue by aPosix** [darkreader/darkreader#1001]
When I set my custom CSS and INVERT for any page then close and open Chrome, the custom settings will not apply on any webpage, just the default dark settings. I have to go to dev tools and apply it again, so all the pages are using my custom settings.

**Comment by schrodog** [comment]
I face the same problem

**Comment by TTTPOB** [comment]
Same problem here, so it put the setting into stylus (

**Comment by alexanderby** [comment]
This is a known Dev Tools problem #540, still not fixed. Every 15 minutes Dark Reader synchronizes configs with GitHub.

By custom CSS I mean Static mode custom CSS, have a look https://darkreader.org/blog/stylish/
