### ISSUE TITLE
[Broken Website] make.powerapps.com table view font colour incorrect

### ISSUE THREAD

**Issue by josephharkins** [darkreader/darkreader#10018]
# Broken Website Report

## Website Address
https://make.powerapps.com/

## Steps To Reproduce
- Go to make.powerapps.com
- Click into Dataverse -> Tables -> Any table
- Incorrect font colour is visible now in the table view
- Additionally click the Edit button to open a new tab with full screen editor, where the same font colour will show

## Problematic Observation
The font colour chosen by Dynamic generation for table details is black. It should be white or off white for visibility.

## Screenshots
![image](https://user-images.githubusercontent.com/47038639/194167859-6662331a-ca17-4276-a1b1-27aa6485841b.png)

## System Information
- OS: Windows 10
- Browser: Firefox 105.0.2
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Adding `help wanted`, locked behind Microsoft enterprise/education:
![image](https://user-images.githubusercontent.com/25481501/194394008-7221d20b-0a36-44b2-b680-ef7e7c924451.png)

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 6 Okt 2022, 5:33 AM Joseph Harkins ***@***.***>
menulis:
