### ISSUE TITLE
[Feature Request] Ignore element matching selector on any webpage

### ISSUE THREAD

**Issue by realprogrammersusevim** [darkreader/darkreader#10024]
# Feature Request

## Is this feature request related to a problem?

Yes, I use a Chrome plugin called [Firenvim](https://github.com/glacambre/firenvim). It embeds an instance of [NeoVim](https://neovim.io) into any textbox in a browser (such as the one I'm editing with now) so I never have to leave my favorite text editor. The problem is that my lovely color scheme gets inverted by Darkreader. If Darkreader could get an option to leave elements matching a certain selector alone no matter the website that are in a special wildcard entry that would be great.

**Comment by Gusted** [comment]
Duplicate of #4144, it's not possible to technically implement this without seeing performance loss on sites with a lot of CSS and practically speaking, you cannot give it a selector for the element, it has to be the CSS selectors themselves.
