### ISSUE TITLE
YouTube TV PWA inverting from Dark Mode @ sunset

### ISSUE THREAD

**Issue by cableghost** [darkreader/darkreader#10037]
I want YouTube TV to display in Dark Mode permanently. I have excluded YTT PWA from Dark Reader, however, Dark Mode is turned off @ sunset.

I don't have this occur to other PWA's I have excluded... why is this?

**Comment by Gusted** [comment]
Please use [the issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug-report.md&title=%5BBug%5D+Replace+with+title).
