### ISSUE TITLE
BUG - Broke my Browser Themes

### ISSUE THREAD

**Issue by IplaygamesIhate** [darkreader/darkreader#10035]
# Bug Report

## Bug Description
It turned my entire browser theme to white and if I kept the option in custom it would revert it back to dark mode, but there was bright white layout on whatever i select all around the browser

## Steps To Reproduce
I faced this issue when I opened the extention, went to more > changed browser theme from Default to Custom 
-->

## Expected Behavior
I was just looking around the plugin to see what the feature does

## Actual Behavior
It turned my entire browser to white theme, can't revert back to dark mode even after removing the extention and reinstalling.

- OS: Win 10 Pro
- Version 10.0.19044 Build 19044
- Browser: Firefox 105.0.3 (64-bit_
- Dark Reader Version: The Latest version on the Firefox store - 4.9.58
![Firefox bright](https://user-images.githubusercontent.com/92145260/194723611-6d000fb7-2f9c-4998-bfb7-1821ce010d8a.png)
![Firefox header dark](https://user-images.githubusercontent.com/92145260/194723613-2eabec95-b561-48a2-aec4-26154941ccb2.png)

## Additional Context

I was just toggling everything to see what it does. 
In the more section where it says Change the Broswer theme I changed it from Default to Custom and it broke my browser theme on firefox as well as LibreWolf. Pls fix I really like the addon

**Comment by Gusted** [comment]
Hi @IplaygamesIhate,

This rather seems like a browser problem, an extension isn't able to cause this directly. Are you using a custom theme? This doesn't seem to be the default Firefox installation.

**Comment by IplaygamesIhate** [comment]
Sry for my late reply. 
I'm using FirefoxCSS themes on my browser and when I was using the Addon, I switched the Browser theme from default to custom and it broke my browser theme. Removing the add didn't help much, had to reset the addon and refresh Firefox multiple times to get it back to the way it was. I think it happened because of the CSS themes. 

Anyway, it's fixed and i'm still using Dark Reader. Thank you for the plugin.
