### ISSUE TITLE
Visiting mendeley.com breaks Dark Reader

### ISSUE THREAD

**Issue by ShaneKilkelly** [darkreader/darkreader#1004]
Steps to reproduce:

- Enable Dark Reader
- Visit mendeley.com (while signed in to an account)
- Wait for page to load
  - (Eventually loads, with dark theme)
- Open another tab
- Visit another site (let's say news.ycombinator.com)
- The other site will load without the dark theme
- Check a few other sites, same result
- Restart browser
  - Dark Reader works again

This problem doesn't happen if the user is not signed in to a mendeley account, only when they are signed in and the "dashboard" loads.

Notably, this problem doesn't happen if the user disables Dark Reader for mendeley.com, from the extension menu.

**Comment by Gusted** [comment]
Fixed.
