### ISSUE TITLE
[Feature Request] Add tooltip or scrolling text to Site list config UI

### ISSUE THREAD

**Issue by ngoclong19** [darkreader/darkreader#10050]
# Feature Request

## Is this feature request related to a problem?

Using Vietnamese language, some elements on the UI are overflow, and clipped.
The affected elements are 'Site list', 'Invert listed only', and 'Not invert listed' buttons.

So I would like a tooltip which shows the full text on mouse hover, or make the text scrolling.

## Screenshots

![ảnh](https://user-images.githubusercontent.com/2577653/194781922-778b72c9-20c6-4000-b396-60afb1cb090a.png)

## Additional Context

A scrolling text example: https://codepen.io/hubspot/pen/WNpgbBd

**Comment by Gusted** [comment]
Hi @ngoclong19,

That indeed doesn't look good. We are in the transition of moving to a new UI, which shouldn't have this problem(as it's less packed):
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.

Currently no new fixes are features are being added to the "old" UI.

**Comment by ngoclong19** [comment]
Close as `won't fix` per @Gusted comment.
