### ISSUE TITLE
[Broken Website] vermontamerican.com

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#10064]
# Broken Website Report

## Website Address
https://vermontamerican.com/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice how the entire website is blinding white and not affected by Dark Reader.

## Problematic Observation
The entire website is blinding white and not affected by Dark Reader.

## Screenshots
![vermontamerican](https://user-images.githubusercontent.com/95879668/194973882-38039359-d876-44cd-bd43-af95db508919.png)

## System Information

- OS: Windows 10
- Browser: Firefox 105.0.3
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
That's weird, Firefox doesn't allow injecting into this site... Other extension aren't able to modify the site as well. Chromium works fine. @bershanskiy Could you confirm that Dark Reader doesn't work on this site on Firefox? If so, I will proceed making a bugzilla, as other extension are affected as well. I couldn't find anything in the Firefox code base about this site...

**Comment by bershanskiy** [comment]
@q1800 Thanks for filing this issue, it is a known Firefox bug. Unfortunately, we are unable to work around it this bug without elevating permissions to get blocking `webRequest` permission. Previous instances of this bug did not affect content pages, so we never bothered to fix this. If you need help, I can provide you with a simple "companion" extension which will be ~30 lines of code and will fix this.

@Gusted 
>  will proceed making a bug report at Mozilla, as other extensions are affected as well.

This is already tracked in:
 - Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1411641
 - W3C disussion https://github.com/w3c/webextensions/issues/285

**Comment by bershanskiy** [comment]
> I just came across this site randomly and thought I would report it.

Thanks for reporting it, this helps a lot. If you find any other bug/issue with Dark Reader please open a ticket.

For reference, this browser bug appears very rarely (since very few websites use the CSP `sandbox` directive). However, this bug occurs in both Safari and Firefox and affects all extensions with content scripts (pretty much every single extension which modifies or inspects page contents).
