### ISSUE TITLE
[Broken Website] mtcradio.com

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#10063]
# Broken Website Report

## Website Address
https://www.mtcradio.com/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the whitish/grayish areas of the web page in the screenshot that need fixing to make a more uniform dark mode appearance and to make things easier to read.

**NOTE:** I tried to number the inconsistent sections 1 - 5 to help illustrate all the different areas in the screenshot.

## Problematic Observation
Whitish/Grayish Areas

## Screenshots
![mtcradio](https://user-images.githubusercontent.com/95879668/194971522-4f25e2e1-562c-4853-adce-a246a93bb476.png)

## System Information

- OS: Windows 10
- Browser: Firefox 105.0.3
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Old sites, they are using [background images](https://cdn10.bigcommerce.com/r-2f0310c7f1a16f167417815e193c159bd0a69dbc/themes/Bargains/images/red/BodyBg.gif), instead of normal background-colors. So even properly inverting the background-images would lead to problems. Won't fix.
