### ISSUE TITLE
[Broken Website] msn.com

### ISSUE THREAD

**Issue by Milky063** [darkreader/darkreader#10074]
# Broken Website Report

## Website Address
https://www.msn.com/

## Steps To Reproduce

I"m not a tech person so i dont know. 

## Problematic Observation
 Wont go dark

## Screenshots

https://ibb.co/QMvVNMC

## System Information
 I'm using firefox 105.0.3 (64-bit), and i just reinstalled the latest version of dark reader. 

- OS:  windows 11
- Browser:  Firefox 105.0.3 (64-bit)
- Dark Reader Version:     4.9.58

## Additional Context
 only happens on msn.com. all the other websites work fine.

**Comment by Gusted** [comment]
Duplicate of #9812
