### ISSUE TITLE
Github inline code background

### ISSUE THREAD

**Issue by ricab** [darkreader/darkreader#1007]
Inline code in github markdown renderings originally has light grey background. With dark reader, that background is lost: `some inline code`.

**Comment by Chekote** [comment]
Here's a couple of screenshots illustrating the problem:

<img width="799" alt="screen shot 2019-02-27 at 10 25 40 am" src="https://user-images.githubusercontent.com/550486/53483793-2f918d80-3a7a-11e9-80b7-0dc9076a4aa5.png">

<img width="800" alt="screen shot 2019-02-27 at 10 25 55 am" src="https://user-images.githubusercontent.com/550486/53483799-33bdab00-3a7a-11e9-835b-b7e6a5a6d867.png">
