### ISSUE TITLE
[Broken Website] LinkedIn

### ISSUE THREAD

**Issue by Pdzoc** [darkreader/darkreader#10083]
# Broken Website Report

## Website Address
https://www.linkedin.com/login

## Problematic Observation

Gray text on white background

## Screenshots

![linkedIssue](https://user-images.githubusercontent.com/71113600/195428011-485bcb14-befa-4709-b393-75bfc2dc4bff.png)

## System Information

- OS: Windows
- Browser: Chrome 106
- Dark Reader Version: 4.9.58

**Comment by bershanskiy** [comment]
Thanks for reporting this! This will be fixed by #10084.
