### ISSUE TITLE
Doesn't work on https://pypi.org/

### ISSUE THREAD

**Issue by nikitavoloboev** [darkreader/darkreader#1009]
The background is fully white for me and doesn't change. Using Safari Dark Reader extension.

[Example page](https://pypi.org/project/beautifulsoup4/)

**Comment by TTTPOB** [comment]
![image](https://user-images.githubusercontent.com/19909103/51369190-672d2180-1b2d-11e9-84cb-fc20f502e3ca.png)
seems work for me.



but I found that you have to turn it off and then on to make it work on [this following page](https://packaging.python.org/tutorials/installing-packages/)
first looks like:
![image](https://user-images.githubusercontent.com/19909103/51369268-d0ad3000-1b2d-11e9-9108-70e621d79b06.png)
after turn off and on:
![image](https://user-images.githubusercontent.com/19909103/51369277-dd318880-1b2d-11e9-9120-0c9fbeccb998.png)

**Comment by Cochonours** [comment]
Doesn't work for me either, even if I turn it off and on.

**Comment by jcrowgey** [comment]
Doesn't work for me in FF (even with turn-off, turn-on).

**Comment by krupenja** [comment]
works fine here with Chrome Dev 74.0.3710.0 on macOS 10.14.3

**Comment by IceflowRE** [comment]
4.7.12 
Firefox 67.0.4
Not working, gets black for a millisecond but switches back to white then.

**Comment by P1zz4br0etch3n** [comment]
Same behaviour here on Firefox 69.0.1 on Fedora 30

**Comment by pawamoy** [comment]
Same here, Mozilla Firefox 69.0.3. My eyes, please.

**Comment by jaymegordo** [comment]
pypi.org still doesn't work on safari macos

**Comment by 07416** [comment]
screenshot from my system (Firefox):

![image](https://user-images.githubusercontent.com/14923168/113504732-a1ced900-9542-11eb-9223-07588c9387b2.png)
