### ISSUE TITLE
[Broken Website] chromiumdash.appspot.com

### ISSUE THREAD

**Issue by saltedcoffii** [darkreader/darkreader#10118]
# Broken Website Report

## Website Address

https://chromiumdash.appspot.com/serving-builds?deviceCategory=Chrome%20OS

## Problematic Observation

The table on the page remains white, so the viewer sees a white table with white text on a black background

## Screenshots

![image](https://user-images.githubusercontent.com/55339220/196076283-7e16c98c-4988-4d73-a22c-a5d0d978b731.png)

## System Information

- OS:  Linux
- Browser:  105.0.3
- Dark Reader Version:  4.9.58

**Comment by Gusted** [comment]
Duplicate of #8850 (same underlying bug).
