### ISSUE TITLE
[Dynamic] Text color goes monochrome after a while

### ISSUE THREAD

**Issue by lfr** [darkreader/darkreader#1013]
Chrome 71.0.3578.98 (but has been happening for quite a bit of versions now) / Windows 10 x64
Sites impacted: all sites

I can fix it permanently by switching to Static, or I can fix it temporarily by switching to Static and back to Dynamic, but eventually it gets broken again.

By broken, I mean it remains dark, but all text colors disappear. I'll try to update with screenshot.

**Comment by lferrao** [comment]
Normal:
![image](https://user-images.githubusercontent.com/6348118/51394888-bb3f0280-1b3b-11e9-8e4f-d181883b9469.png)

Broken:
![image](https://user-images.githubusercontent.com/6348118/51394802-9480cc00-1b3b-11e9-831c-b8add7935851.png)

**Comment by alexanderby** [comment]
Are you sure there are no other styling extensions installed?

**Comment by Gusted** [comment]
Throttled has been added to fix this.
