### ISSUE TITLE
[Broken Website] https://www.linux-bg.org/cgi-bin/y/index.pl

### ISSUE THREAD

**Issue by gochev** [darkreader/darkreader#10135]
# Broken Website Report

## Website Address
[](https://www.linux-bg.org/cgi-bin/y/index.pl)

## Steps To Reproduce

- Go to linux-bg.org
- Turn on dark mode and you will see nothing is dark, more like grey

## Screenshots

![image](https://user-images.githubusercontent.com/5537142/196729227-a4cffd7d-b8fc-4c86-a9f9-ec0cebbaf1a0.png)

## System Information

- OS:  Windows 11
- Browser:  Chrome 106
- Dark Reader Version: latest

**Comment by Gusted** [comment]
The site is basically only using images to make the layout fixing this in the dynamic theme will result in a bad experience. Please use the Filter(+) theme for this site.
