### ISSUE TITLE
[Broken Website] Stripe login

### ISSUE THREAD

**Issue by aidalgol** [darkreader/darkreader#10155]
# Broken Website Report

## Website Address

https://dashboard.stripe.com/login

## Steps To Reproduce

- Go to https://dashboard.stripe.com/login
- Wait about 20 seconds

## Problematic Observation

The tab will crash with an error code of `SIGTRAP` or `SIGILL`.

## System Information

- OS: Linux
- Browser: Chromium 106.0.5249.119
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Duplicate of #6799
