### ISSUE TITLE
can't see picture

### ISSUE THREAD

**Issue by cris122** [darkreader/darkreader#1016]
could not show pictures in this web https://goo.gl/2HRFPn
windows 10 chrome

**Comment by TTTPOB** [comment]
![image](https://user-images.githubusercontent.com/19909103/51435287-4c82b600-1caf-11e9-8438-ac0eb8c40474.png)

**Comment by cris122** [comment]
I just closed all extensions but still not working...so sad...

**Comment by alexanderby** [comment]
@cris122 You are using Static mode :) Static mode is not very accurate, please switch to Dynamic or Filter mode. Static mode will be improved some day, but since it is static, it will still have many errors. https://darkreader.org/help/en/#more-tab
