### ISSUE TITLE
[Bug] uid.tests.ts test failure on Node.js 19

### ISSUE THREAD

**Issue by polyzen** [darkreader/darkreader#10162]
# Bug Report

## Bug Description

```
FAIL tests/unit/utils/uid.tests.ts
  ● Unique identifier generation

    expect(received).toEqual(expected) // deep equality

    Expected: false
    Received: true

      4 | test('Unique identifier generation', () => {
      5 |     // Make sure we are not messing up global context for somebody else
    > 6 |     expect('crypto' in globalThis).toEqual(false);
        |                                    ^
      7 |
      8 |     // Create a shim for crypto API
      9 |     // TODO: remove any cast once type declarations are updated

      at Object.<anonymous> (tests/unit/utils/uid.tests.ts:6:36)
```

## Steps To Reproduce

`npm test`

## System Information

- OS:  Arch Linux
- Browser: 
- Dark Reader Version:  Tested on 4.9.58 and 4.9.59

## Additional Context

Tests were passing on Node.js 18, and also pass with our nodejs-lts-gallium package (version 16.16.0).

Build script: https://github.com/archlinux/svntogit-community/blob/packages/dark-reader/trunk/PKGBUILD

**Comment by bershanskiy** [comment]
Thanks for reporting this.

This failure makes sense: I wrote this test before NodeJS introduced [`crypto` API](https://nodejs.org/api/crypto.html), so I explicitly checked for non-existence of this API. Tomorrow I'll update the test to be compatible with NodeJS 16 to 19.

**Comment by bershanskiy** [comment]
@polyzen I updated the tests and the CI passes on NodeJS 19 ([here](https://github.com/bershanskiy/darkreader/pull/9)). We probably won't tag yet another release, since the built output after this commit is identical to the output from the 4.9.59 tag, except for timestamps on zip archives. Will this work for you?

**Comment by polyzen** [comment]
That works, thank you. I'm just using nodejs-lts-gallium for our build script in the meantime.
