### ISSUE TITLE
Cannot scroll down on settings since upgrade to 4.9.59

### ISSUE THREAD

**Issue by 021kw497** [darkreader/darkreader#10178]
Cannot scroll down on Dark Reader's settings page since installed upgrade to (Dark Reader) V4.9.59.

Some of the settings at the bottom are not visible unless the font size is greatly reduced..  I have poor vision and it's a problem for me.

Running Dark Reader on Firefox 106.1.0 (Build #2015909131) and Android 10, Kernel 4.9.190.   

I'm a newbie on GitHub.  Hope my post is OK.

Thanks.
JD

**Comment by bershanskiy** [comment]
@021kw497 Thanks for this report, I managed to reproduce this on PC (in a wonky way) and just merged a revert for changes which caused this regression. I'm not sure when we will be able to publish a patch/hotfix release to AMO and when it will be approved by Mozilla, so if you need this fix immediately I recommend building extension on GitHub Actions and side-loading it. It's really easy after you do it once, ask me if you need help. I hope to get patch/hotfix release out this week.
