### ISSUE TITLE
[Feature Request] Compat Mode - Only for Non-Dark Pages

### ISSUE THREAD

**Issue by theAlexBR** [darkreader/darkreader#10189]
# Feature Request

## Is this feature request related to a problem?

No, but probably can prevent a bunch of them to happen, the idea is if the compatibility mode is enabled, the extension will ONLY darken the page IF the site don't support dark mode, idk if that is possible... maybe reading the predominant color of the page?

**Comment by Gusted** [comment]
Please take a look at https://github.com/darkreader/darkreader/discussions/9016
