### ISSUE TITLE
[Broken Website] www.msn.com

### ISSUE THREAD

**Issue by jaylay99** [darkreader/darkreader#10180]
# Broken Website Report

## Website Address
www.msn.com

## Steps To Reproduce
Simply going on the site or navigating have this issue

## Problematic Observation
Any filter makes the articles appear white and barely readable because the text is grey, Refreshing the site also disables Dark Reader for some reason. I need to enable/disable it to make it work again.

## Screenshots
![image](https://user-images.githubusercontent.com/76778450/198064525-e72c63a8-b5a1-485d-af9e-528004cc862e.png)
**when I refresh :** 
![image](https://user-images.githubusercontent.com/76778450/198064795-81cfd73f-2a83-48ac-87a7-1980c63e4412.png)

## System Information
tested on both Microsoft Edge, Google Chrome

- OS: Windows 10 21h2

## Additional Context
No additional context

**Comment by Gusted** [comment]
Duplicate of #9812
