### ISSUE TITLE
Dynamic style failing to apply consistently

### ISSUE THREAD

**Issue by narcolepticinsomniac** [darkreader/darkreader#1018]
Chromium 71.0.3578.98

Maybe not 100%, but seems to fail to apply the majority of the time when navigating from an external site, on the initial page load. Reloading works and I haven't seen the issue when browsing around if you're already on the site.

https://www.esumsoft.com/Forums/

**Comment by stevencohn** [comment]
I just wanted to add a couple of comments.

1. This is a fantastic extension.
2. The Dynamic engine is far better that the others even if it is slower to render.
3. I know the author has commented that he has other priorities but...
4. I would vote to concentrate on improving the Dynamic engine and addressing its bugs

OK, so I see similar behavior. The dynamic engine isn't always applied and I tend to keep open the Dynamic Theme Editor window in the corner of my screen just so I can hit the Apply button when it doesn't apply automatically.

Thanks!

**Comment by stevencohn** [comment]
Thanks, yes. However, I'm not sure it's a timing issue. I see it much sooner than 10-15 minutes. I'll add a comment to that ticket too :-) Cheers!

**Comment by MajorLift** [comment]
I've been struggling with what appears to be the same issue as this on Firefox Quantum up to 65.0.1, but not on Chrome. It's distinct from bug #540, as the failure to apply dynamic styling occurs regardless of whether I have rules set for the target webpage, and toggling Dark Reader off then on once fixes the issue for that page. However, this fix does not prevent the issue from recurring intermittently but consistently within any given browsing session, and pressing Alt+Shift+D twice gets old after the dozenth time. I'm also seeing white flash on initial loading of sites where the dynamic styling do get applied (I have Shadowfox installed, so it's not the browser), and I'm not seeing this problem either in Chrome.

**Comment by Gusted** [comment]
Seems doing fine. and should be completed fixed with next release for #3138
