### ISSUE TITLE
[Bug] Unloaded tabs that happen to be a window OR tab set's focus are reloaded without Dark Reader updates.

### ISSUE THREAD

**Issue by mjevans** [darkreader/darkreader#10195]
## Bug Description
Unloaded tabs that happen to be a window / tab set's focus are reloaded without Dark Reader updates.

I suspect this is a corner case not resolved in bug #10004

Context: I keep a _lot_ of tabs open (probably around 100-300); multiple windows loaded up with tabs, each of which might be several mental workspaces / topics of stuff.  My intent is that a smart web-browser should cache the data components of the page structure locally and keep them ready to see without a need to look things up again.  In recent versions Firefox has become less swappy and more 'discard not active pages'.  I hope it still caches the files and doesn't bother with network requests.

Some of those tabs are in minimized, background, or otherwise out of focus windows; but are the tab that's ''in focus'' for that window.

I will sometimes return to a (random) page and find that it's blindingly bright again, at a glance it might seem Dark Reader hadn't worked or had been turned off; but on other pages it's more clear that E.G. a solid background was still black from the treatment, but the content in the middle got re-rendered as if DR were disabled.  Neighboring tabs to affected pages will briefly display similar to this, but then update within a couple seconds to the corrected dark pattern.

## System Information
Dark Reader 4.9.60 (from Mozilla's extensions repository)
Firefox 106.0 64 bit (built by...)
Arch Linux (rolling release)

**Comment by bershanskiy** [comment]
Hi @mjevans do you use some extensions which claim to disable some APIs for privacy, specifically Page Visibility API?

I tried to reproduce this on Firefox and Chromium by "discarding" a tab by calling [`chrome.tabs.discard()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard), but the tab gets effectively reloaded and Dark Reader works fine.

I'll try opening 200 tabs and testing that way as well.

**Comment by mjevans** [comment]
It'd be nice if there were an easy way to copy/paste a list...

From what I know (which is why I didn't mention it in the report) none of my extensions does anything like that, but maybe Tabby or something else behaves differently from a reasonable guess.

    Dark Reader
    Decentraleyes
    Ghostery - Privacy Ad Blocker
    HTTPS Everywhere
    Ruffle
    SingleFile
    Stylus
    Tabby - Window and Tab Manager
    To Google Translate
    uBlock Origin

I also don't think any of these matter but...
    Firefox SHOULD be in GPU acceleration disabled mode.  At least I thought I set it that way years ago, because ~32GB real RAM and only 2GB GPU/VRAM.  I have not played any games during the last week that I've noticed the issue.
    KDE / Plasma desktop
    Steam (which is probably an Electron based app; the windows all rebuffer and resync when it opens or closes)

I try to update and restart every week or two, or if playing a game leaves the system feeling too swappy / unresponsive and it seems like a worthwhile time to update.

**Comment by mjevans** [comment]
I've had over a week of uptime and one update + restart since reporting this issue.

Some combination of updating the underlying software, Firefox, and/or Dark Reader has left me unable to reproduce the problem.

Hopefully it is fixed.
