### ISSUE TITLE
[Broken Website] samsung.com

### ISSUE THREAD

**Issue by Matr1x-101** [darkreader/darkreader#10192]
# Broken Website Report

## Website Address
[]
https://www.samsung.com/uk/smartphones/galaxy-a/galaxy-a52s-5g-awesomeviolet-128gb-sm-a528blvceua/#specs

## Steps To Reproduce
1. Go to the website 
2. Scroll down to reviews

## Problematic Observation
Grey text on grey background

## Screenshots
![Screenshot from 2022-10-27 13-55-57](https://user-images.githubusercontent.com/70490301/198290357-5b07500a-3e7d-4942-8bcc-24c2ca577a32.png)

## System Information

- OS: Arch Linux (rolling release)
- Browser: Vivaldi Snapshot (5.6.2829.3 (Official Build) snapshot (64-bit) )
- Dark Reader Version: 4.9.58

## Additional Context

n.a.

**Comment by Gusted** [comment]
Same fundamental/underlying issue as #4682
