### ISSUE TITLE
[Feature Request] Light mode option in npm package API

### ISSUE THREAD

**Issue by Jelmerro** [darkreader/darkreader#10215]
# Feature Request

## Is this feature request related to a problem?
There seems to be no way to change the scheme/mode to light mode in the npm package of darkreader. There is a `mode` option, but it is only for switching between dark and dimmed.

## Additional Context
If there somehow is an existing way to do this with the npm package I would really like to know it, but I could not find it nor similar issues in the issue tracker.

**Comment by Jaifroid** [comment]
I'm interested in this too. Can we have an API (or document an existing one) to switch to DarkReader's own "light mode" when `darkreader.js` is loaded on a Web page?

**Comment by Gusted** [comment]
This is already available, you would need to pass `mode: 0` as option, e.g:

```js
DarkReader.enable({
    mode: 0
});
```

**Comment by Jelmerro** [comment]
![image](https://user-images.githubusercontent.com/1696674/200314465-88fc2349-3ce6-45d7-959f-d73fc47fb548.png)
0 is "dimmed mode", not light mode though, and it certainly doesn't look "light" to me on github, but it does look lighter on other sites, so good to know that "dimmed" means "light" in darkreader.

**Comment by Gusted** [comment]
That's what Dark Reader offer, providing a "real" light mode like how "dark mode" works is out-of-scope.
