### ISSUE TITLE
[Broken Website] Arango docs

### ISSUE THREAD

**Issue by xeruf** [darkreader/darkreader#10211]
# Broken Website Report

## Website Address
https://www.arangodb.com/docs

## Steps To Reproduce
Visit the site

## Problematic Observation
Dark Reader detects a nonexistent dark theme

## System Information
Firefox

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016#discussioncomment-4070425
