### ISSUE TITLE
[Broken Website] annaaurora.eu, artemislena.eu, github.com

### ISSUE THREAD

**Issue by auroraanna** [darkreader/darkreader#10219]
# Broken Website Report

## Website Address
- https://annaaurora.eu
- https://artemislena.eu
- https://github.com

## Steps To Reproduce

- Enable the dark theme in Brave browser (Makes some websites e.g the websites listed respond to that and use dark colors)
- Go to one of the website adresses

## Problematic Observation
Dark Reader applies it's theme on already dark websites which often times makes them look worse.

## System Information

- OS: Linux
- Browser: Brave Browser 105.1.43.89
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Please look at https://github.com/darkreader/darkreader/discussions/9016
