### ISSUE TITLE
Corporate proxy rules causing issues with dark reader dark-list downloads

### ISSUE THREAD

**Issue by richardsavio** [darkreader/darkreader#1022]
Almost every website I visit seems to be part of a "global dark list". I couldn't find any documentation as to what this means. I have attached screenshots of my Dark Reader configuration. I have also tried uninstalling and then reinstalling the extension which did not change anything.

Google Chrome Version: 69.0.3497.100 (Official Build) (64-bit)
Windows: 10 1703
I am behind a corporate proxy (don't know if that's relevant though)

Dark Reader Settings:
![dr-more](https://user-images.githubusercontent.com/878118/51472031-5afbcb00-1d9e-11e9-991d-eb649353584d.png)
![dr-sites](https://user-images.githubusercontent.com/878118/51472032-5afbcb00-1d9e-11e9-9957-3eca76ba6769.png)
![dr-filter](https://user-images.githubusercontent.com/878118/51472033-5b946180-1d9e-11e9-91f1-24d02f931c64.png)

Google.com styling:
![image](https://user-images.githubusercontent.com/878118/51517502-f6de1300-1e40-11e9-90dd-d85d9e20fcb1.png)

**EDIT**: Changed the screenshot displaying google.com search results to also display dark reader settings.
**EDIT**: Changed the title to better reflect the issue

**Comment by richcocoa** [comment]
> When you open `google.com`, does it tell that the website is in Dark List? Could you share a screenshot?

I have updated the original issue description

I also checked my home computer later. I don't have this problem there. It runs an up-to-date Win 10 1809 and the latest Chrome stable. I also forcefully updated all the extensions I had installed. Couldn't reproduce it there.

Back at work (where I have this problem), I also tried creating a new Chrome profile to ensure that some other extension wasn't causing this issue. But I get the same issue with the new profile as well. I also checked some of my co-workers PCs (Chrome 67) and I am able to reproduce it. Auto-updates are disabled because of IT policy.

If you could provide me with some information as to what the Global Dark List means, and how it is fetched or generated, I may be able to help further in debugging this.

**Comment by alexanderby** [comment]
@richcocoa If you are familiar with JavaScript, you could debug the extension.
- Open `chrome://extensions` page.
- Enable Developer mode.
- Under Dark Reader click `background/index.html`. This will open dev tools.
- Open Sources tab and find `background/index.js` file.
- Put the breakpoint (click) on line `2579`.
```javascript
        getURLInfo(url) {
            const { DARK_SITES } = this.config;
            const isInDarkList = isURLInList(url, DARK_SITES);
            const isProtected = !canInjectScript(url);
            return {
                url,
                isInDarkList,
                isProtected,
            };
        }
```
- In browser open some website, e.g. `www.google.com`.
- The app should stop on line `2579` and you could read `url`, `DARK_SITES` and `isInDarkList` values (hover with mouse or enter variables names in Console and hit Enter). They should be, `https://www.google.com/...`, array with values like `darkreader.org`, and `false`.

**Comment by richcocoa** [comment]
I did some further digging, and it seems to me that a copy of dark sites (and other stuff) that is bundled with the extension is loaded in case the download from github fails. In my case, however, the download does not fail exactly. A URL redirection (to a proxy block page) happens and the request succeeds. And it doesn't really fail during parsing either, the input format seems to be some kind of plain text format.

Do you have any ideas on fixing this?

**Comment by richcocoa** [comment]
@alexanderby Do you think introducing a check to ensure no redirection happened after the load function (the part that handles the AJAX calls) is an acceptable solution?

**Comment by alexanderby** [comment]
@richcocoa Yes, some check should be added and also an option to disable syncing. As a quick fix you could locate the extension (usually it is `Chrome/Default/Extensions/eimadpbcbfnmbkopoojfekhnkhdbieeh`), find `background/index.js` file and add `local = true;` at line 883:
```javascript
        async load({ local } = { local: false }) {
            local = true;
            const loadDarkSites = async () => {
```
I'm not sure if browser restart is required.

**Comment by Gusted** [comment]
I'ts standard to load from local instead of fetching.
