### ISSUE TITLE
[Broken Website] baidu Logo color deviation

### ISSUE THREAD

**Issue by WangJincheng4869** [darkreader/darkreader#10223]
# Broken Website Report

## Website Address
https://www.baidu.com/

## Steps To Reproduce

- https://www.baidu.com/
- Look Logo

## Problematic Observation
Logo color deviation

## Screenshots
open
![image](https://user-images.githubusercontent.com/41162158/199193292-a2bf193e-5155-4183-8850-eeea3ba7dee1.png)

close

![image](https://user-images.githubusercontent.com/41162158/199193340-8f62be09-3c10-457a-aaca-4617fc68fa5b.png)

## System Information

- OS: Windows
- Browser: Microsoft Edge 107.0.1418.24
- Dark Reader Version:  4.9.58 

### Contrast gitee

open
![image](https://user-images.githubusercontent.com/41162158/199193542-70b38377-abeb-4307-9327-b63728b6b6b3.png)

close

![image](https://user-images.githubusercontent.com/41162158/199193601-375b0e78-9c6e-49e5-81d8-9160feb3762c.png)

**Comment by Gusted** [comment]
That's expected behavior, the logo color deviation is caused by a [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) rule being applied. Without the filter, the logo's wouldn't be visible when Dark Reader is active.

**Comment by WangJincheng4869** [comment]
> That's expected behavior, the logo color deviation is caused by a [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) rule being applied. Without the filter, the logo's wouldn't be visible when Dark Reader is active.

但这个logo并不需要filter进行处理，应与百度翻译的相同，不进行处理。https://fanyi.baidu.com/
![image](https://user-images.githubusercontent.com/41162158/200213478-c2cba2a8-307e-4ef5-884e-57272e2549ac.png)
