### ISSUE TITLE
[Dynamic Theme] Problems on Redcross course

### ISSUE THREAD

**Issue by Skribbles64** [darkreader/darkreader#10240]
On the redcross first aid course (and possibly others) there are problems with the dark mode not functioning properly, and causing difficulty with viewing text, and bright areas remaining.

Images included:
![image](https://user-images.githubusercontent.com/94587115/199811809-83e88523-18de-4a8b-84c9-1b525a0e6109.png)
![image](https://user-images.githubusercontent.com/94587115/199812067-7ab3af4a-e20b-412a-be37-1e25418c488c.png)
![image](https://user-images.githubusercontent.com/94587115/199812267-c69ce64c-db5f-45b8-ba75-d4e86582edeb.png)
![image](https://user-images.githubusercontent.com/94587115/199812360-26384063-e1e4-41aa-a9a1-f0912cb792df.png)

Firefox used.
Dark Reader preview used.
No extra settings were used (such as brightness, contrast, and grayscale)

**Comment by Skribbles64** [comment]
Here is another image:
![image](https://user-images.githubusercontent.com/94587115/199815280-6d5562de-69e9-42f1-a7b1-2134b486f310.png)

**Comment by Gusted** [comment]
Is this course available withing paying/login in?
