### ISSUE TITLE
[Broken Website] After dark mode is turned on, some texts are hard to read

### ISSUE THREAD

**Issue by sojey** [darkreader/darkreader#10244]
# Broken Website Report

## Website Address
[](https://mikanani.me/)

## System Information

- OS: win10 x64 newest
- Browser: edge beta newest
- Dark Reader Version:  4.9.58

## Additional Context

OFF
![2022-11-04_195501](https://user-images.githubusercontent.com/32351740/199967666-08816160-c4b7-42a8-9809-72428adbe56e.jpg)

ON
![2022-11-04_195522](https://user-images.githubusercontent.com/32351740/199967682-160eb882-dac8-4cdb-a0a1-3d928bada71e.jpg)

Expanded text portion is hard to read.

**Comment by Gusted** [comment]
What's the site you're experiencing this on?

**Comment by sojey** [comment]
Sorry, forgot the url https://mikanani.me/
