### ISSUE TITLE
[Bug] Canvas2 warning in console whenever dark reader turned on for website

### ISSUE THREAD

**Issue by RavenHursT** [darkreader/darkreader#10247]
# Bug Report

## Bug Description
When Dark Reader is applied to any website, I get the following warning in Chome's console:
```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

## Steps To Reproduce

- Open a website
- Open console
- Turn on Dark Reader for that site

## Expected Behavior

Should be able to apply Dark Reader to a site and not see the warning

## Actual Behavior

Applied Dark Reader to site and can see warning

## Screenshots

![dark-reader-bug](https://user-images.githubusercontent.com/496983/200054638-2dd1afee-902c-4e1e-83a7-564257cf453c.gif)

## System Information

- OS:  macOS
- Browser:  Chrome 107
- Dark Reader Version:  4.9.58

**Comment by bershanskiy** [comment]
Fixed by #10158 in version 4.9.59 and later.

**Comment by RavenHursT** [comment]
@bershanskiy When will 4.9.59 & 60 be available for update in Chrome?

I just mashed the "update" button and I'm still on .58 🤔

**Comment by bershanskiy** [comment]
We have a regression which is hard to reproduce and therefore it is hard to fix, we are still working on it. It's tracked as #10177.
