### ISSUE TITLE
White page while loading

### ISSUE THREAD

**Issue by thany** [darkreader/darkreader#1024]
Before a page is loaded, it is completely white. 

I've tried to remedy this by installing Shadowfox, but it seems too dodgy to proceed. The thing even triggers Smartscreen, which has never happened to me before.

I'm on Firefox stable, version 64.0.2, on Windows 10.

**Comment by alexanderby** [comment]
Let's consider it as a duplicate of #992

**Comment by thany** [comment]
Sort of, because it's not just Google where this happens. It happens for every website.
