### ISSUE TITLE
Skip Gliffy diagrams on Confluence pages

### ISSUE THREAD

**Issue by stevencohn** [darkreader/darkreader#1025]
Gliffy diagrams are not treated properly. Has anyone looked at a solution, possibly recognizing and skipping them altogether?

**Comment by alexanderby** [comment]
Could you please add some screenshot? If you click on a diagram and choose "inspect", does it appear to be an SVG image?

**Comment by stevencohn** [comment]
DIV, SPAN, and CANVAS elements

_This is what darkreader does to it_

<img width="655" alt="dark" src="https://user-images.githubusercontent.com/9964757/51534855-f16ad380-1e14-11e9-96bb-083f58a49a04.png">

_This is what it look like normally_

<img width="654" alt="light" src="https://user-images.githubusercontent.com/9964757/51534856-f16ad380-1e14-11e9-8b7d-f7fe45fa8d35.png">

_A snipet of one code, this is the "secondary port" box and its contents_

`<canvas id="gliffy_node_0" class="gliffy-graphic" width="284" height="174" style="transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 0px 0px 0px; top: 116.5px; left: -1px; pointer-events: none; visibility: visible; position: absolute; z-index: 0;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARwAAACuCAYAAADkgbIqAAAFLElEQVR4Xu3WwU3rUBRF0bgml0EriGIQrVCGawoiI8TIGXjr6Wb9MZ9jL19tsd38I0CAQCSwRTtmCBAgcBMcR0CAQCYgOBm1IQIEBMcNECCQCQhORm2IAAHBcQMECGQCgpNRGyJAQHDcAAECmYDgZNSGCBA4HZx93++4CBAg8FfgOI7TDfn9f6d/WHAcGgEC/wUuD8775zd1AgReXODr4+0hIDgvfghen0AhIDiFsg0CBB4CguMQCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBAQnozZEgIDguAECBDIBwcmoDREgIDhugACBTEBwMmpDBAgIjhsgQCATEJyM2hABAoLjBggQyAQEJ6M2RICA4LgBAgQyAcHJqA0RICA4boAAgUxAcDJqQwQICI4bIEAgExCcjNoQAQKC4wYIEMgEBCejNkSAgOC4AQIEMgHByagNESAgOG6AAIFMQHAyakMECAiOGyBAIBMQnIzaEAECguMGCBDIBLLgZG9kiACB5QWO49ieecjTP7zv+/2ZX+xnCRCYL3BZcObTeUMCBK4WOP0XztUP4vcTIDBfQHDmf2NvSGAZAcFZ5lN4EALzBQRn/jf2hgSWERCcZT6FByEwX0Bw5n9jb0hgGQHBWeZTeBAC8wUEZ/439oYElhEQnGU+hQchMF9AcOZ/Y29IYBkBwVnmU3gQAvMFfgAayxzrNY4+agAAAABJRU5ErkJggg=="></canvas>`

**Comment by alexanderby** [comment]
Dark Reader does not analyze canvas, I'm not sure if it should. You could open Dark Reader Dev Tools and add `INVERT canvas.gliffy-graphic` rule for your domain. If it is some local website, we could consider this rule to `*` section, so it will be added to all websites.

**Comment by stevencohn** [comment]
This worked:

`*

INVERT
div[class^="gliffy-text"]

CSS
.jfk-bubble {
    background-color: ${white} !important;
}
.gliffy-stage {
    background-color: white !important;
}`

**Comment by krishna81m** [comment]
Adding this via Dev Tools Dynamic Theme Editor on Confluence page and refreshing works for a brief second and resets itself again.

Could someone share the settings json for this fix please.

**Comment by sagunms** [comment]
> This worked, inverting gliffy-text and forcing white background on gliffy-stage
> 
> `*
> 
> INVERT div[class^="gliffy-text"]
> 
> CSS .jfk-bubble { background-color: ${white} !important; } .gliffy-stage { background-color: white !important; }`

This worked for me (but without the extra backticks `), thanks!

```
*

INVERT
div[class^="gliffy-text"]

CSS
.jfk-bubble {
background-color: ${white} !important;
}
.gliffy-stage {
background-color: white !important;
}
```
