### ISSUE TITLE
[Feature Request] Please include an exclusion list for website

### ISSUE THREAD

**Issue by pizofreude** [darkreader/darkreader#10262]
# Feature Request
Please include an option that enables user to exclude websites. This is important to let user choose which website should be turned into dark mode and vice versa. 
## Is this feature request related to a problem?

Description:
From my user experience, website that already implemented/has dark mode option looks better with their native dark mode. Applying darkreader filter ontop makes the dark mode experience a bit odd in aesthetic.
Solution Proposal:
A checking feature would be a better solution. For example, if the website already implemented/offer native dark mode, then dark reader automatically use this native dark mode instead of applying another filter ontop of it.
## Screenshots

Example of Google Keep with native dark mode + Dark Reader turned on:
![image](https://user-images.githubusercontent.com/108355948/200251945-6f3a7723-c0a3-4fbe-abaa-a66f51c7f602.png)

Example of Google Keep with native dark mode + Dark Reader turned off:
![image](https://user-images.githubusercontent.com/108355948/200252034-2a8d6e83-5cc1-4769-9e4d-f0c73ffcc5dd.png)

Example of exclusion list implementation by "Dark Mode" extension:
![image](https://user-images.githubusercontent.com/108355948/200250454-30948fb2-d418-4992-9e41-2967b0a375b5.png)
![image](https://user-images.githubusercontent.com/108355948/200250588-bb1bcd89-e8c7-45c8-ab55-3c00528ea48f.png)

Unfortunately I haven't found any Auto Checking of Native Dark Mode from other extensions that I've tried. It seems to be pretty complex feature to be implemented. Massive chapeau if you guys able to do it!

## Additional Context

This exclusion feature is available in another extension by the name "dark mode" See: https://mybrowseraddon.com/dark-mode.html
User can edit the exclusion list via:
a. Right-click the mouse on the designated website and choose an option of "Exclude from darkmode"
b. Option in comma-separated-list in its native settings

**Comment by Gusted** [comment]
Hi @pizofreude,

I'm sorry, but I must ask. Have you seen the site list button in the UI? 
![image](https://user-images.githubusercontent.com/25481501/200360780-7d1f7363-110a-457a-b5bb-f259f8d19bcc.png)

This feature is already implemented in Dark Reader and for a long time.

**Comment by Gusted** [comment]
> Is there anyway to import CSV file containing extensive listings? I tried C&P all the websites that I would like to include in my exclusion list, but it didn't work. It is too much hassle to do it one by one.

You can only export the site list by exporting all settings:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Go back to the popup
- Click on Settings.
- Click on Manage settings
- Click on Expert/Import settings.

**Comment by pizofreude** [comment]
Superb, thanks!
