### ISSUE TITLE
Youtube search in Channel does not invert inserted text

### ISSUE THREAD

**Issue by sotiris-bos** [darkreader/darkreader#1027]
Hello. Tried to search something on YT through the channel search (not global YT top search, the search field next to the "About" tab on every YT channel) and my inserted text was not inverted and thus could not be read when in Dark Mode. Thanks for your hard work!

Firefox 64.0.2
Fedora 29

**Comment by secf4ult** [comment]
You can fix it by adding the CSS below,

```
#input-1 {
    color: ${#0D0D0D} !important;
}
```

But I don't know how to fix the color of placeholder of that search box, it doesn't associated with `::placeholder` and `--yt-placeholder-text-color`.

**Comment by secf4ult** [comment]
You can fix it by adding the CSS below,

#paper-input-label-1, #input-1 {
    color: ${#0D0D0D} !important;
}

**Comment by Gusted** [comment]
Already fixed
