### ISSUE TITLE
Auto darkreader 

### ISSUE THREAD

**Issue by wetpretzel2** [darkreader/darkreader#10279]
# Feature Request

Not an issue, would be super cool if we could set an auto dark mode feature based on sunset-sunrise. 

## Screenshots
None

## Additional Context
Something similar to Automatic theme switching on macOS or mobileOS, have either a location based sunset-surise dark mode or a time based option. But this extension is amazing as is! Keep up the good work everybody :)

**Comment by Gusted** [comment]
See #72 + #1513
