### ISSUE TITLE
Switch color of about:blank in Microsoft Edge

### ISSUE THREAD

**Issue by hellodrsoul** [darkreader/darkreader#10292]
By default, the ''about:blank'' is white in Microsoft Edge as well as in Google Chrome. When switching between URLs while dark reader is on, the ''about:blank'' remains white in Microsoft Edge and becomes dark in Google Chrome. This gives a white flash before the actual URL is loaded in Microsoft Edge. Is it possible that dark reader suppress this white flash in Microsoft Edge? 
Of note, the ''about:blank'' is white when you put this (about:blank) into the address bar and hit enter both in Chrome and Edge, irrespective of whether dark reader is enabled or not. But when you are switching URL, it becomes dark in Google Chrome and remains white in Microsoft Edge if dark reader is on. Even enforcing dark mode via the built in flag (edge://flags/#enable-force-dark) has no effect on the color of about:blank in Edge. Not sure if it is a browser issue or dark reader can circumvent it in Microsoft Edge.
Have a nice weekend

**Comment by bershanskiy** [comment]
Hi @hellodrsoul do you have a specific site where this issue occurs and is disrupting to the user experience?

All browsers seem to struggle with extension injection into `about:blank` pages and frames. The APIs (especially in MV3) are not fully specified and standardized, the behavior is not consistent across browsers. Ideally, Edge would respect setting on `edge://settings/appearance` and make `about:blank` frames dark by default to avoid flash of white content, but we have no direct input into that. On Dark Reader's side we already have code which is supposed to be injected into these frames, but Edge does not do that. We likely will never be able to style top-level `about:blank` pages, but that is a very rare use case. We might be able to fix `about:blank` subframes (and I have a few approaches in mind), but the choice of the approach will depend on some real-world examples.

**Comment by hellodrsoul** [comment]
> Hi @hellodrsoul do you have a specific site where this issue occurs and is disrupting to the user experience?
> 

Thank you for the response. The white flash appears randomly. It appears whenever the about:blank is loaded when switching from one website to another. At times, it is missed. I am unable to understand any recognizable pattern. The two sites where this is consistent is when hitting a link from twitter.com timeline or reddit.com home feed. It may be prevenlent in other areas too, it is just that I don't use other sites much and don't know.
Cheers

**Comment by hellodrsoul** [comment]
> Two possible solutions are:
> 
> * use `matchOriginAsFallback` option (which is not documented or standardized at all as far as I know)
> * detect `about:blank` frames in parents and somehow style or even just hide them from the parent
> 
> Neither solution looks good and either solution will require lots of manual testing to ensure it works.

I am sorry I do not understand coding. I am just an average user. Thanks

**Comment by hellodrsoul** [comment]
Okay I think I've found the root cause of the problem and a work around/solution. If I change enhanced security to basic in MS Edge, the about:blank turns black in dark mode and hence there is no white flash when dark reader is on. It appears to be browser bug or slow system rather than issue with dark reader. Apologies and thank you for giving us a sweet dark reader. Cheers
