### ISSUE TITLE
ZenHub browser extension's modification are not darkened

### ISSUE THREAD

**Issue by rhuss** [darkreader/darkreader#1030]
I'm using ZenHub's browser extension for managing GitHub projects, however, it looks like that it doesn't play nicely with Dark Reader:

![grafik](https://user-images.githubusercontent.com/99080/51589463-5f7fcb00-1ee7-11e9-995d-fef1d829830b.png)

I'm not sure whether its something that ZenHub or Dark Read could fix, but for me it looks like that Dark Reader kicks in before ZenHub. 

Is there a way to influence the order of the execution of browser extensions? Or something to ensure that Dark Reader is always last in the chain ?

**Comment by alexanderby** [comment]
If stylesheet is injected by the extension (not created as a `<style>` element), it cannot be accessed by other extensions. Have a look at the solution for Google Translate extension https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config#L4

**Comment by rhuss** [comment]
Thanks for the heads-up.

For me its, enough to add .zhc-dependency to the invert list for the github.com config entry:

```
================================
github.com

INVERT
.octotree_sidebar
.octotree_toggle
.zhc-dependency
```

**Comment by rhuss** [comment]
would be cool if this could be taken over the default, but I can live with updating it on my own, too.

Thanks !
