### ISSUE TITLE
[Feature Request] Add Site to List should include URI scheme

### ISSUE THREAD

**Issue by marcusnewton** [darkreader/darkreader#10305]
# Feature Request

## Is this feature request related to a problem?

I've noticed that when I toggle a site, the address that gets added to the list does not include the scheme i.e. `http(s)`. For example, I may toggle on a bare domain such as `twitter.com`. I may later visit the subdomain `help.twitter.com`, and yes this is also affected by dark reader since `help.twitter.com` matches on `twitter.com`. 

The issue, however, is if I want to toggle off dark reader for `help.twitter.com` as it does not work. I need to open the list and update the entry for `twitter.com` to `https://twitter.com` to force it to only affect the bare domain.

I would love the default behavior to make Add Site to List include the scheme in the URI that it saves to the list, or otherwise provide an option to toggle this behavior.

## Additional Context

Firefox 106.0.5

**Comment by Gusted** [comment]
Hi @marcusnewton,

This has nothing to do with schemes, please follow #373 and #660 (it's currently a fundamental issue of the URL matching).
