### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by SebastianGrans** [darkreader/darkreader#10300]
# Broken Website Report

## Website Address
https://www.vy.no/

## Steps To Reproduce
1. Go to the website
2. Try to search for a city 
3. No search results/suggestions appear

If I set Dark Reader to Off, it works. 

## Screenshots
Expected to happen:
![image](https://user-images.githubusercontent.com/10030015/201621070-9da696b4-02e3-4707-b46b-d8bac8b458af.png)

## System Information

- OS: Ubuntu 22.04
- Browser: Firefox 106.0.1 (64-bit) (snap)
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
This is an interesting one,

So the site was going trough all elements of the DOM (constantly, at least that is what it was indicating to me). However browsers will error if the site tries to to touch an element that was inserted by a extension, which the browser did in this case. So it wasn't showing as the site wouldn't constantly error over the same element (which you might have noticed in CPU utilization).
