### ISSUE TITLE
[Broken Website] https://www.cnblogs.com/hackermi/p/9291087.html turn on text can't read

### ISSUE THREAD

**Issue by sojey** [darkreader/darkreader#10317]
# Broken Website Report
turn on text can't read

## Website Address
https://www.cnblogs.com/hackermi/p/9291087.html
[](https://www.cnblogs.com/hackermi/p/9291087.html)

## Screenshots
![2022-11-18_003727](https://user-images.githubusercontent.com/32351740/202504382-39cef44c-fbe0-4a49-ad8a-38426f16b98d.jpg)

## System Information

- OS: windows 10 22H2
- Browser: edge beta
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Hi @sojey,

I've tried fixing this site, but the usage of images is so "broken" it's not possible to fix it. I'd recommend disabling dark reader for this site.

**Comment by sojey** [comment]
ok, and thank you anyway. I konw it too hard to do such many website.
