### ISSUE TITLE
[Broken Website] Fix FakeUpdate.net

### ISSUE THREAD

**Issue by Myzel394** [darkreader/darkreader#10318]
# Broken Website Report

## Website Address
https://fakeupdate.net/

## Steps To Reproduce
1. Got o https://fakeupdate.net/
2. Select an update screen

## Problematic Observation
The update screens should be displayed correctly.

## Additional Context
Not sure how to do it, but the following urls need to be excluded:

* https://fakeupdate.net/xp/
* https://fakeupdate.net/vista/
* https://fakeupdate.net/win8/
* https://fakeupdate.net/win7/
* https://fakeupdate.net/apple/
* https://fakeupdate.net/win10/
* https://fakeupdate.net/win10ue/
* https://fakeupdate.net/steam/
* https://fakeupdate.net/wnc/
* (https://fakeupdate.net/windows98/) - Currently results in 404

**Comment by Myzel394** [comment]
@Gusted `fakeupdate.com` itself is not dark, just the paths I specified.

**Comment by Gusted** [comment]
🤦🏽 good find.
