### ISSUE TITLE
Only invert special site on domain

### ISSUE THREAD

**Issue by Bluscream** [darkreader/darkreader#1031]
I would like to only invert `domain.de/directory/*` but not `domain.de/*` while still leaving the mode on `not invert listed`. How would i do that?

**Comment by alexanderby** [comment]
Try add `domain.de$` into the list.

**Comment by Bluscream** [comment]
Can you explaint that a little bit better i don't seem to get it 😕

**Comment by alexanderby** [comment]
The `$` symbol means the end of URL, so the start page will not be inverted, but others will.
<img width="304" alt="screen shot 2019-01-25 at 14 42 20" src="https://user-images.githubusercontent.com/9638588/51744045-a4eef480-20af-11e9-9d1d-2d7b01115ca6.png">

**Comment by Bluscream** [comment]
But i only want one folder

**Comment by alexanderby** [comment]
Hopefully the pattern `domain.de/directory/$` should work as expected now.
