### ISSUE TITLE
[Broken website] Dark theme not detected on ProtonMail

### ISSUE THREAD

**Issue by clemlesne** [darkreader/darkreader#10322]
# Broken Website Report

## Website Address

https://mail.proton.me/u/0/inbox

## Steps To Reproduce

1. Connect to ProtonMail with an account
2. Configure a dark theme within the configuration menu
3. Reload the page

## Problematic Observation

Dark theme not detected. Dark theme is enforced, it breaks some images.

## System Information

- OS: macOS
- Browser: Firefox 108.0b3
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016#discussioncomment-4188199
