### ISSUE TITLE
[Bug] v5 preview no clear reason that the website is protected

### ISSUE THREAD

**Issue by barraIhsan** [darkreader/darkreader#10321]
# Bug Report

## Website Address
Protected website like :
addons.mozilla.org (firefox)
moz-extension:// (firefox)
chrome.google.com (chromium)
chrome-extension:// (chromium)

## Bug Description
In the v5 preview, it is not clear that the website is protected, it just says the dr is disabled on the website (but the button is still disabled)
![image](https://user-images.githubusercontent.com/57800056/202638886-933a75f2-5623-4464-bc6c-68f2c30bd0ab.png)
old design :
![image](https://user-images.githubusercontent.com/57800056/202639034-bf0b3dad-22a4-46bb-8578-eea357e3e6b8.png)

## Steps To Reproduce
Go to Dev Tools ⇒ Preview new design
go to one of the protected websites
see the bug

## Expected Behavior
It should say the same as the old design

## Actual Behavior
It just says like we disable dr on the website

## System Information
- OS: Windows 11
- Browser: Firefox 106.0.5
- Dark Reader Version: 4.9.60

## Additional Context
or maybe this is intentional because now there is enable on restricted page button?
![image](https://user-images.githubusercontent.com/57800056/202640131-6f81f85a-4be5-438b-b339-459f109500ad.png)

**Comment by Gusted** [comment]
Hi @barraIhsan,

Good find, that's a small oversight in Dark Reader. Really weird that nobody ever noticed this message missing.
