### ISSUE TITLE
[Broken Website] Google + Avast Online Security

### ISSUE THREAD

**Issue by Pdzoc** [darkreader/darkreader#10328]
# Broken Website Report

## Website Address
Results from google.com

## Steps To Reproduce

Firefox with Avast Online Security & Privacy. 
Google settings: default settings of device (with light/white mode is the same problem)

## Problematic Observation

Avast's marks before links are not visible.

## Screenshots
![googleIssue](https://user-images.githubusercontent.com/71113600/202797856-ab7dd5ff-b4a7-433a-8c7b-6e2133f13f01.png)

## System Information

- OS: Windows 10
- Browser: Firefox 107
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Hi @Pdzoc,

I'm not able to see these icons being added after installing the addon, does it require a setting being turned on?

**Comment by Pdzoc** [comment]
Hello @Gusted!

Yes, you need to allow using labels with warnings. It it first option in settings.
