### ISSUE TITLE
[Broken Website] Charts on WSJ are not visible

### ISSUE THREAD

**Issue by StevenLi-DS** [darkreader/darkreader#10332]
# Broken Website Report

## Website Address
https://www.wsj.com/articles/macys-m-q3-earnings-report-2023-11668688592?mod=itp_wsj&ru=yahoo

## Problematic Observation
Unable to see charts under dark mode

## Screenshots
![CS-UgVkI0Y9](https://user-images.githubusercontent.com/33796896/202879669-2fee9c31-bf88-440d-901a-0c80dca9d7f5.png)
![CS-mZFA0pP5](https://user-images.githubusercontent.com/33796896/202879672-4cc746a2-bfc0-4484-aa0f-81bafa3c9db8.png)
![CS-yif3fffM](https://user-images.githubusercontent.com/33796896/202879675-f28d8eb4-6abf-49ca-8b6f-efbee5b5a222.gif)

## System Information

- OS: macOS 13 
- Browser: Chrome Version 107.0.5304.110 (Official Build) (arm64)
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
I'm not able to reproduce this issue:

![image](https://user-images.githubusercontent.com/25481501/202904091-14247331-254a-44e3-981e-20b1dfd46927.png)

Are you using other addons?

**Comment by StevenLi-DS** [comment]
Not really, I also tried in Incognito.
![CS-mbC9JNuJ](https://user-images.githubusercontent.com/33796896/202925446-24698d2a-9e67-4047-8791-4742243313f4.png)

**Comment by StevenLi-DS** [comment]
I also tried with Firefox
![CS-JB644V4M](https://user-images.githubusercontent.com/33796896/203185882-684f03d5-abdd-49fb-af3e-dd4d4e85e21b.png)

**Comment by Gusted** [comment]
That's really weird, I'm still not able to reproduce this 🤷🏽, might be because I'm using the bypassing paywalls extensions.

**Comment by StevenLi-DS** [comment]
@Gusted After I restarted my mac and it's back to normal... so weird. Thanks for your help!
