### ISSUE TITLE
[Broken Website] Each product page on www.thermalright.com

### ISSUE THREAD

**Issue by cyatarow** [darkreader/darkreader#10368]
# Broken Website Report

## Website Address
Each product page on www.thermalright.com
e.g.
- http://www.thermalright.com/product/frozen-magic-360-white-argb/
- http://www.thermalright.com/product/assassin-king-120-plus/

## Steps To Reproduce

- Go to www.thermalright.com.

## Problematic Observation

The dark theme is not applied at all.

## Screenshots

![20221124a](https://user-images.githubusercontent.com/26016252/203768077-61588fb2-40ee-449f-bd48-5f369a5f42a7.png)

## System Information

- OS: Windows 11 Pro 22H2
- Browser: Firefox 107.0 x64
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Same underlying issue as #5937
