### ISSUE TITLE
Browser incompatibility

### ISSUE THREAD

**Issue by JoshOxley** [darkreader/darkreader#1036]
I am currently using Vivaldi 2.2.1388.37

Adding a site to the blacklist doesn't stop the extension from changing the colours. 

For example, discordapp.com is by default in a dark mode, so the dynamic changes by the darkreader aren't necessary, I add discordapp.com to the "not invert" list, swap tabs and come back, and there's a hang up while the extension changes all the colours.

I have spoofed the UA tags in Vivaldi using a separate extension, changing them to spoof as Chrome solves the issue, which leads me to believe it's merely incompatibility with Vivaldi.

**Comment by Gusted** [comment]
Vivialdi should work now.
