### ISSUE TITLE
[Feature Request] Daytime theme?

### ISSUE THREAD

**Issue by charakaSamawry** [darkreader/darkreader#10369]
Feature Request

**Is this feature request related to a problem?**
Im not sure if this is already a feature, i couldnt find it.
Id like to have a theme for daytime (mainly to reduce contrast on certain sites and to change fonts on specific sites where ive change the font)

Additional Context
I think this would make sense, especially the font thing - if ive changed a font on a site, which wasnt ideal, then surely id like that font change to be in the daytime as well as at night? I think it would be a welcome and good feature, Thanks!

**Comment by Gusted** [comment]
Hi @charakaSamawry,

This is already a feature, you're looking for the "light" theme. If you select that theme you can still change the filters(e.g. contrast).

**Comment by charakaSamawry** [comment]
For real? well arent i stupid.. lol Tysm!

**Comment by charakaSamawry** [comment]
hmm.. having tested wht i thought i understood of ur suggestion, it doesnt seem to work as i thought

**Comment by Gusted** [comment]
Hi @charakaSamawry,

Could you elaborate on why it doesn't meet your expectations.

**Comment by charakaSamawry** [comment]
jsut trying out firefox and noticed the extension is slightly different there. No 'auto'? and seems i can set options for light theme alternately, unlike in chrome. sorry should have mentioned the browser i was using

**Comment by charakaSamawry** [comment]
i see the auto options actually, hidden in the 3 dots on the side of off/on

**Comment by Gusted** [comment]
Hi @charakaSamawry,

You likely had the preview design enabled on of the browsers. You can enable it via the following steps:

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.

**Comment by charakaSamawry** [comment]
Yes, that was that. Forgot about that when installing firefox recently, thank you. 
Though i still dont see a way to set any settings for the daytime theme, regarding my original post.
Also, setting up firefox with dark reader, im seeing some slight errors in that version. When going to settings, there is no 'back' button, and, some text is turned blue for some strange reason on one site, I've noticed. Also the duckduckgo site looses its hyperlink colours (Blue/Purple) and link colours (Green), though this may be a firefox thing.

Thanks again though
