### ISSUE TITLE
[Bug] Dark Reader is slowing down Firefox

### ISSUE THREAD

**Issue by baptx** [darkreader/darkreader#10377]
# Bug Report

## Website Address
https://www.instagram.com/ but may happen on other websites also.

## Bug Description
On Instagram web version if we check the followers of someone, Firefox says Dark Reader is slowing down.
I noticed Instagram web version has a dark theme that can be enabled by adding `?theme=dark` in the URL (https://techweez.com/2021/03/12/instagram-for-the-web-gets-dark-mode/) but it would be nice to fix the issue since it may happen on other websites also.
The issue freezes the browser, which makes it unusable on my computer and sometimes I had to close the browser when the button to stop the script was not working. It happens with a fresh browser profile also.
This issue seems to appear only in dynamic mode.
There is an existing issue where I left a comment but I was asked to report a new issue: https://github.com/darkreader/darkreader/issues/7266#issuecomment-1326702643.

## Steps To Reproduce
- Go to instagram.com.
- Check the profile of someone like a celebrity (the issue happens even with accounts having 1 or 2 followers).
- Click on the followers button.

## Expected Behavior
The addon should not slow down and freeze the browser.

## Actual Behavior
The addon slows down and freezes the browser.

## System Information

- OS: Debian stable Linux 64-bit
- Browser: Firefox 107.0 (from Mozilla website)
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Hi @baptx,

This is a performance issue and thus needs to be opened via [the performance issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Performance+Issue&template=performance_issue.md&title=%5BPerformance+Issue%5D+Replace+with+title
).
