### ISSUE TITLE
[Broken Website] https://news.softpedia.com/ does not show dark theme with dynamic mode

### ISSUE THREAD

**Issue by Shaurya-Kalia** [darkreader/darkreader#10430]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dynamic theme does not work at all on the website. Static and filter work though

### Website Address

https://news.softpedia.com/

### Steps To Reproduce

1. Open website with dark reader enabled and theme set to dark

### Screenshots

![Screenshot_20221203_041947](https://user-images.githubusercontent.com/6441797/205402678-a4426f0b-61dc-41f4-bc5a-db6a3a881d5c.png)

### Operating System

Linux

### Web Browser name and version

firefox nightly 109.0a1 (2022-11-30) (64-bit)

### Dark Reader version

4.9.60

**Comment by Gusted** [comment]
Hi @Shaurya-Kalia,

I am able to reproduce this issue, but it's only shown briefly. After a fraction of a second it "fixes" itself. Does this issue persist?

**Comment by Shaurya-Kalia** [comment]
> I am able to reproduce this issue, but it's only shown briefly. After a fraction of a second it "fixes" itself. Does this issue persist?

Yes, the issue persists in my case. It does not turn dark even after 5 minutes after web page is loaded

**Comment by Gusted** [comment]
Is there any error in the console? Could you try disabling the other extension?

**Comment by Shaurya-Kalia** [comment]
> Is there any error in the console? Could you try disabling the other extension?

Strangely, on trying today in latest nightly, it works without issues on my main profile as well as a new profile with just dark reader installed. I guess it can be closed now
