### ISSUE TITLE
Change subsites in filters

### ISSUE THREAD

**Issue by TheSwerik** [darkreader/darkreader#1045]
I use the Dynamic theme and I want to use youtubes own dark mode.
the upload page https://www.youtube.com/upload does not have an own dark mode but I cannot find out how to only give the upload page dark mode and leave the rest of youtube alone with its own dark mode.

**Comment by Gusted** [comment]
#373

**Comment by TheSwerik** [comment]
this will be fixed, if #373 is fixed
