### ISSUE TITLE
[Broken Website] Almost no effect on the full page

### ISSUE THREAD

**Issue by Ali-hd** [darkreader/darkreader#10452]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The colors in the page don't get effected by the extension. The stay bright white/blue
https://hawamer.com/vb/f2/

But this page works fine as expected, dark theme
https://hawamer.com/vb/index.php

### Website Address

https://hawamer.com/vb/f2/

### Steps To Reproduce

1. load the website address

### Operating System

Windows 10 

### Web Browser name and version

Google Chrome - Version 108.0.5359.98 (64-bit)

### Dark Reader version

4.9.60

**Comment by Gusted** [comment]
Hi @Ali-hd,

This is indeed a bug, but this will not get fixed. The site is using images to style the webpage, Dark Reader's dynamic theme isn't that good with analyzing images(especially when used in this context). I would recommend using the Filter(+) theme.
