### ISSUE TITLE
[Broken Website] https://ris58h.github.io/validatekeymaps/

### ISSUE THREAD

**Issue by ris58h** [darkreader/darkreader#10451]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark Reader doesn't work for the site in both Auto and On modes.

### Website Address

https://ris58h.github.io/validatekeymaps/

### Steps To Reproduce

Open https://ris58h.github.io/validatekeymaps/

### Screenshots

![Screenshot_20221208_135425_Firefox](https://user-images.githubusercontent.com/511242/206429024-3c9de666-bb7f-4871-8303-5898774c6e48.jpg)

### Operating System

Android 12

### Web Browser name and version

Firefox for Android 107.2.0

### Dark Reader version

4.9.60

**Comment by Gusted** [comment]
Hi @ris58h,

Could you make a screenshot when you have dark reader open? Does it show that it's disabled?

**Comment by ris58h** [comment]
@Gusted thank you for quick response.
I have checked it and it was disabled. Sorry for bothering you.
