### ISSUE TITLE
[Broken Website] Ferris is possessed

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#10467]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Ferṙis iș possěșsεd

### Website Address

https://crates.io/crates/does-not-exist

### Steps To Reproduce

1. Cause an error page on crates.io
2. Ƒëŕřìṡ įŝ ṗőşśèšŝēď
3. **Go back. Go back. Go back. Go back. Go back. Go back.**

### Screenshots

Dark Reader on:  
![chrome_VXgIXWQLLy](https://user-images.githubusercontent.com/4723091/207014294-b2fa4a8f-7628-48b5-b616-873a0e1ce55a.png)

Dark Reader off:  
![image](https://user-images.githubusercontent.com/4723091/207023717-c4d48cc8-a668-47a5-ac8c-c749afb19482.png)

### Operating System

Windows 10 Home 2004 build 19041.572

### Web Browser name and version

Ungoogled Chromium version 107.0.5304.88

### Dark Reader version

4.9.60

### Additional Context

Ferrís is not threåtening me with æ knife, I swêar-

**Comment by Gusted** [comment]
Sorry for possessing Ferris! Dark Reader is seeking a new host for time being 😅
