### ISSUE TITLE
[Feature Request] Grey out extension icon, if extension is inactive.

### ISSUE THREAD

**Issue by qoomon** [darkreader/darkreader#10461]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

It would be super helpful, if you're able to recognize if the extension is active or not by just have a look at the extension icon.

My suggestion is to simply grey out the icon, if the extension is not active on current tab.

**Comment by Gusted** [comment]
Duplicate of #1671
