### ISSUE TITLE
[Feature Request] JavaScript for developers to perma convert their website to dark mode

### ISSUE THREAD

**Issue by a3y3** [darkreader/darkreader#10471]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

I have a [personal website](https://a3y3.dev) and I love how DarkReader makes it look. So much so that I want my website to look that way permanently - to whoever visits it, with or without DarkReader.
Currently, I'd have to painstakingly modify the CSS of my website to do this. However, DarkReader already has done the job for me - I just want a way to have it stick permanently. I'm imagining that there can potentially be a way to embed a DarkReader JS script that would auto convert the entire website to dark mode.

**Comment by bershanskiy** [comment]
Have you considered using [the official npm package](https://www.npmjs.com/package/darkreader)?

**Comment by a3y3** [comment]
That looks like exactly what I'm looking for, so I'll close this issue for now. Thanks @bershanskiy!
