### ISSUE TITLE
youtube fullscreen scrollbar in chrome

### ISSUE THREAD

**Issue by BennyFaust** [darkreader/darkreader#1050]
youtube now lets you scroll down even though youre watching a video in fullscreen mode. unfortunately the scrollbar is always on when in fullscreen now

**Comment by Stephenator0316** [comment]
Can we get a fix for this? Really annoying xD

**Comment by reseto** [comment]
Can confirm it's DarkReader issue, I'm using Win10, Chrome 72.0.3626.119 (Official Build) (64-bit) and DR 4.7.6 with dynamic theme (which is awesome btw).
When DR is off then scrollbar is not there.

**Comment by Bleuzen** [comment]
Same, hope it will be fixed soon.

For now I use the youtube dark theme and disabled dark reader for youtube.

**Comment by jslay88** [comment]
same

**Comment by jupiter104** [comment]
Yes, we really need a toggle for the scrollbar. Hope the devs will make it soon.

**Comment by reseto** [comment]
thanks so much for solving this in 4.7.10
