### ISSUE TITLE
[Bug] Browser's PDF reader's background is inverted from dark to white, when dark mode is enabled in the browser

### ISSUE THREAD

**Issue by jittrfunc** [darkreader/darkreader#10509]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

When using DarkReader on the pdf reader of a browser e.g. Microsoft edge, if the browser has its dark mode enabled, the pdf reader's background gets inverted from dark to white which is unexpected.

### Website Address

https://www.orimi.com/pdf-test.pdf

### Steps To Reproduce

1. Open Microsoft Edge
2. Go to Settings -> Appearance -> Overall Appearance -> Dark
3. Open the url https://www.orimi.com/pdf-test.pdf
4. The pdf reader's background becomes white (even though the pdf is darkened)

### Expected Behavior

For browsers having their dark mode enabled, their pdf reader's background should stay dark when using DarkReader on pdf files.

### Actual Behavior

When using DarkReader on the pdf reader of a browser e.g. Microsoft edge, if the browser has its dark mode enabled, the pdf reader's background gets inverted from dark to white.

### Screenshots
Before enabling browser's Dark mode

![image](https://user-images.githubusercontent.com/20995272/208626603-d2ab593b-88bf-4df5-b78b-435132833178.png)

After enabling browser's Dark mode (the browser's PDF reader's dark background gets inverted to white by DarkReader in Dark mode)

![image](https://user-images.githubusercontent.com/20995272/208545505-43f4c7e0-6377-4114-8ec0-2b29758c72fa.png)

### Operating System

Windows 10

### Web Browser name and version

Microsoft Edge, Version 108.0.1462.46 (Official build) (64-bit)

### Dark Reader version

4.9.60

**Comment by Gusted** [comment]
Duplicate(same underlying issue) of #3585
