### ISSUE TITLE
[Bug] Dark reader is able to modify protected browser pages on firefox 

### ISSUE THREAD

**Issue by randrrandr1** [darkreader/darkreader#10505]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Dark reader changes colors of protected pages

### Website Address

about:*

### Steps To Reproduce

turn on or of dark reader

### Expected Behavior

Dark reader should not change browser protected pages 

### Actual Behavior

It is changing even look of  browser tabs

### Screenshots

![Screenshot from 2022-12-18 08-57-11](https://user-images.githubusercontent.com/118778223/208284235-90b67b61-fc3b-4800-82d4-92415e465b94.png)
![Screenshot from 2022-12-18 08-57-00](https://user-images.githubusercontent.com/118778223/208284238-1f48c3f3-71b6-41bc-9b9e-b4bc2a630af6.png)

### Operating System

Fedora silverblue 37  mozilla-flatpak

### Web Browser name and version

firefox  	108.0.1

### Dark Reader version

4.9.60

**Comment by randrrandr1** [comment]
[firefox.txt](https://github.com/darkreader/darkreader/files/10253284/firefox.txt)

**Comment by Gusted** [comment]
The tab is a not a protected browser page, as it's not a page. This modification is due our custom dark theme [being applied](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/update) to Firefox. Which includes the modification of the tab colors.
