### ISSUE TITLE
[Feature request] Programmatically disable Dark Reader

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#10523]
Hello,

The global dark list's strict policy is to only include websites that are dark by default and even if `prefers-color-scheme` is unset or set otherwise.

Therefore, I would like to create a userscript that would programmatically disable Dark Reader when websites are dark but not by default, or even automating the activation of the website's dark theme.

For that to work, I'd need to be able to communicate with Dark Reader from my userscript. At first glance, I have two ideas :
- detect a `meta` tag that my userscript would inject
- expose an API to the `window` scope

In order to prevent abuse, I'd suggest generating an API key that the user would copy from Dark Reader.

Thanks

**Comment by KaKi87** [comment]
Up
Thanks

**Comment by kinghat** [comment]
theres this: https://github.com/darkreader/darkreader/pull/9181 using: `<meta name="darkreader-lock">`. it works, but on sites like github/reddit where i set this via user script, dark reader flashes dark initially still.

**Comment by KaKi87** [comment]
Thanks, I created a [Dark Reader dynamic blacklist](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/README.md) userscript based on this.
