### ISSUE TITLE
[Feature Request] Exclude images and video players

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#10521]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

Yes

### Feature Request Description

Setting to exclude images and video players from dark mode

### Screenshots

**Filter/Filter+**
![Screenshot 2022-12-22 183858](https://user-images.githubusercontent.com/121229410/209117017-85ea90f3-3edc-4116-9611-532b861e709b.jpg)

**Static**
![Screenshot 2022-12-22 183921](https://user-images.githubusercontent.com/121229410/209117028-43a0ea84-ce72-492a-9fbe-bd7704ce94c6.jpg)

**Comment by Gusted** [comment]
Static is "Bring your own CSS" and Filter is a bit tricky to get right with video players this usually requires manually fixing.
