### ISSUE TITLE
[Broken Website] Pinterest search page

### ISSUE THREAD

**Issue by vinibali** [darkreader/darkreader#10531]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The finds at Pinterest remain black, after I disable the plugin, the pictures became visible.

### Website Address

https://hu.pinterest.com/search/pins/?q=Firefox&rs=typed

### Steps To Reproduce

1. Open the mentioned page

### Screenshots

![Screenshot_20221224-205825_Firefox](https://user-images.githubusercontent.com/13108545/209449617-016cc3a5-06dd-463c-9dcb-3fbba7489807.png)

### Operating System

Android 

### Web Browser name and version

Firefox 108.1.0

### Dark Reader version

4.9.60

**Comment by thismoon** [comment]
I can confirm this issue in all Pinterest pages and not only search
changing the mode to filter seems to fix it (but can make it slower)

using firefox 108.0.1 on ubuntu
the dark reader version is 4.9.60

**Comment by vinibali** [comment]
I assume we cannot make an exception to use Pinterest with filter and all the other pages with dynamic mode :)

**Comment by thismoon** [comment]
:)
![image](https://user-images.githubusercontent.com/107642606/209583638-c81aa7d3-a798-4aec-868e-8df956e5ee4f.png)
but yeah this is just a work around it still should get fixed

**Comment by vinibali** [comment]
Great, thanks for the hint
