### ISSUE TITLE
Localization used, but default_locale wasn't specified in the manifest

### ISSUE THREAD

**Issue by iateadonut** [darkreader/darkreader#10548]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

I'd like to use darkreader in my browser tests.  So I've cloned darkreader and use a flag to start it on startup (--load-extension=darkreader/src), but I get a popup with this error message:

Failed to load extension from: /var/www/purecounsel/tests/browser_plugins/darkreader/src. Localization used, but default_locale wasn't specified in the manifest.

What's odd is that locale is clearly set in the manifest.

You can get the error message easily by running pack-extension from the command line:

> chromium --version
Chromium 108.0.5359.124 for Linux Mint

> chromium --pack-extension=./darkreader/src
[74035:74035:1230/224809.795096:ERROR:chrome_main_delegate.cc(481)] Localization used, but default_locale wasn't specified in the manifest.

I was able to pack a very simple extension as a test with no issue.

I also tried using replacing the manifest with `cp manifest-chrome-mv3.json manifest.json` to no avail.

### Website Address

none

### Steps To Reproduce

clone repo and then run:

> chromium --pack-extension=./src

### Expected Behavior

for chromium to pack the extension

### Actual Behavior

returns the error: Localization used, but default_locale wasn't specified in the manifest.

### Operating System

linux mint 21

### Web Browser name and version

Chromium 108.0.5359.124 for Linux Mint

### Dark Reader version

commit 4341c56a10dc40b4a84f57fefb9542f609ee39a1

**Comment by bershanskiy** [comment]
@iateadonut Thanks for detailed repro steps. Based on this command it appears you are loading the source directory:
> chromium --pack-extension=./darkreader/src

Instead, you should build the extension and load the built output:
Chrome MV2:
> npm run build -- --release --chrome
Chrome MV3:
> npm run build -- --release --chrome-mv3
All supported platforms:
> npm run build -- --release

Then load the relevant version from `build/release/chrome` or `build/release/chrome-mv3`.

Furthermore, when you run `chromium --pack-extension=...` you might see the following error:
> A private key for specified extension already exists. Reuse that key or delete it first.

This is because on first invocation Chrome packing will generate a signing key pair and you will either need to delete it or reuse it on subsequent invocations.

Does this help?

**Comment by iateadonut** [comment]
Yes, thanks!  It works perfectly.

After compiling in laravel_project_root/tests/browser_plugins/darkreader, my DuskTestCase file has this configuration:
$options = (new ChromeOptions)->addArguments(collect([
            $this->shouldStartMaximized() ? '--start-maximized' : '--window-size=1920,1080',
        ])->unless($this->hasHeadlessDisabled(), function ($items) {
            $plugin_dir = __DIR__ . '/browser_plugins/';
            return $items->merge([
                '--disable-gpu',
                '--load-extension='.$plugin_dir.'darkreader/build/release/chrome/',
                // '--headless',
            ]);
        })->all());
