### ISSUE TITLE
[Feature Request] Fast "Just Invert" Mode for Problematic Sites

### ISSUE THREAD

**Issue by matthewlloyd** [darkreader/darkreader#10561]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

Yes

### Feature Request Description

Dark Reader is fantastic and an eye-saver, and it does an amazing job preserving colors. However, this comes at the price of performance. For most sites, the performance is fantastic, but for a few problematic sites, the extension can render the entire site almost unusable. For example, the [Stripe Dashboard](https://github.com/darkreader/darkreader/issues/6799) can take upwards of 20-30 seconds to load with the extension enabled, yet the site itself does not offer a native dark theme; from the linked issue, it seems the issue may be difficult or impossible to fix given the overhead of the theme generation code.

This feature request is to add a lightweight alternative mode which simply inverts the entire website using a top-level filter on the root HTML element, like this:

```
html {
    -webkit-filter: invert(100%);
    -moz-filter: invert(100%);
    -o-filter: invert(100%);
    -ms-filter: invert(100%);
}
```

This mode could be enabled on a site-specific basis as needed. More eyes could then be saved. Thank you!

**Comment by dbstraffin** [comment]
I found something similar on [SO](https://stackoverflow.com/questions/40723277/fullscreen-inverted-luminance-filter-for-dark-themed-browsing-but-keeping-hues-i), but they also rotate the hue back 180 degrees.  So green is still green (instead of red) and it's only the luminance that's inverted.  `background: black` was suggested but not sure if its needed.  I'm it in the static filter and it seems to work well so far.
```
html {filter: invert(100%) hue-rotate(180deg); background:black;}
img {filter: invert(100%) hue-rotate(180deg) !important;}
video {filter: invert(100%) hue-rotate(180deg) !important;}
```

**Comment by alexanderby** [comment]
You won't believe this. We have Filter mode since 2014 https://darkreader.org/blog/filter-mode/
