### ISSUE TITLE
dark scrollbar on dark sites

### ISSUE THREAD

**Issue by lucasfernog** [darkreader/darkreader#1061]
Dark sites with the darkreader scrollbar instead of the default one would be nice 
e.g. letterboxd.com
a config for that would be a improvement

**Comment by alexanderby** [comment]
@lucasfernog Are you using Firefox on Windows?

**Comment by lucasfernog** [comment]
Chrome

**Comment by TheAlienDrew** [comment]
Oh I see what he means. So we have the Dark sites config, right? Where all the sites that are already dark, shouldn't be themed by Dark Reader. What he's asking is for all those dark sites to at least get themed a dark scrollbar. 

> Dark sites with the darkreader scrollbar instead of the default one would be nice
> e.g. letterboxd.com
> a config for that would be a improvement

As for a temporary fix, you can use something I've created, originally for myself, using the Stylish extension and my global theme (colors may need tweeking if you want exact colors from the Dark Reader) https://userstyles.org/styles/169873

**Comment by lucasfernog** [comment]
Thank you, I will take a look into that.

**Comment by TheAlienDrew** [comment]
> Thank you, I will take a look into that.

I don't think my original link was working for installs, so I recreated the theme, sorry about that.
https://userstyles.org/styles/170362

**Comment by TheAlienDrew** [comment]
UPDATE:

I created a Tampermonkey script that should know when you are on a website that Dark Reader deems as a dark website, and enables the dark scrollbar theme. :D

Have a look [here](https://github.com/TheAlienDrew/Tampermonkey-Scripts/blob/master/Any%20-%20For%20Dark%20Reader/Dark%20Scrollbar%20for%20Dark%20Websites.user.js)

P.S. The script won't need any updates ever as it directly grabs the scrollbar style from the same link I posted earlier

**Comment by alexanderby** [comment]
Hopefully fixed
