### ISSUE TITLE
[Bug] Page not dark when prerendered by Chrome with "Omnibox trigger for Prerender2" enabled

### ISSUE THREAD

**Issue by ivan** [darkreader/darkreader#10613]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

If a Chrome user is bucketed into having the "Omnibox trigger for Prerender2" flag enabled, Dark Reader will often fail to make the page dark when a URL is navigated from the omnibox.

### Website Address

https://example.com/

### Steps To Reproduce

1. Open a clean Chrome profile on Windows (others untested) with Chrome 108 or 109 (stable) or 110 (beta/dev)
2. Install Dark Reader from https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related?hl=en-US
3. Open chrome://flags and enable "Omnibox trigger for Prerender2" and restart Chrome.
   (note that this is _not_ necessary in all cases; Google has been bucketing users into having this flag enabled for them since November 2022: https://bugs.chromium.org/p/chromium/issues/detail?id=1351312)
4. Keep visiting https://example.com/ by typing `example.com` into the omnibox or accepting the autocompletion. Wait a second or two before pressing Enter to give Prerender2 a chance to prerender. Within a few dozen visits you should see Dark Reader failing to make the page dark.

### Expected Behavior

Dark Reader makes the page dark even Prerender2 prerenders the page.

### Actual Behavior

Dark Reader sometimes does not make the page dark; you have to reload to see a dark page.

### Screenshots

This GIF is kind of useless on the web, but it can be paused and seeked in mpv if necessary. It happens 20 seconds in when I wait a little bit before pressing Enter in the omnibox.

![prerender2](https://user-images.githubusercontent.com/4458/211991664-fed01e02-64ee-496e-b10a-22ae7c45eced.gif)

### Operating System

Windows 10 22H2

### Web Browser name and version

Chrome 109.0.5414.75 (Official Build) (64-bit)

### Dark Reader version

4.9.62

**Comment by ivan** [comment]
duped in #11276

**Comment by bershanskiy** [comment]
I am unable to reproduce this on Dark Reader 4.9.64 installed from Chrome Web Store. Could you please try 4.9.64 again?

**Comment by bershanskiy** [comment]
Hi @ivan, could you please build Dark Reader from `main` after applying the following patch and reproduce the bug? After this patch, I would expect page to be dark and the background console to have a single error message logged reading `M1`;

```diff
diff --git a/src/background/tab-manager.ts b/src/background/tab-manager.ts
index 0ba2dcae..b8459b16 100644
--- a/src/background/tab-manager.ts
+++ b/src/background/tab-manager.ts
@@ -233,15 +233,42 @@ export default class TabManager {
             //
             // More info: https://crbug.com/1455817
 
-            chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}).catch(() =>
-                chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId, documentId}).catch(() =>
-                    chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}).catch(() => { /* noop */ })
-                )
-            );
+            chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}).catch(() => {
+                console.error('M1');
+                chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId, documentId}).catch(() => {
+                    console.error('M2');
+                    chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}).catch(() => {
+                        console.error('M3');
+                    });
+                })
+            });
             return;
         }
         if (__CHROMIUM_MV2__) {
-            chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, documentId ? {documentId} : {frameId});
+            if (documentId) {
+                chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}, () => {
+                    if (chrome.runtime.lastError) {
+                        console.error('M1');
+                        chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId, documentId}, () => {
+                            if (chrome.runtime.lastError) {
+                                console.error('M2');
+                                chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {documentId}, () => {
+                                    console.error('M3');
+                                });
+                            }
+                        });
+                    }
+                });
+            } else {
+                chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId}, () => {
+                    if (chrome.runtime.lastError) {
+                        console.error('M1');
+                        chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId: 0}, () => {
+                            console.error('M2');
+                        });
+                    }
+                });
+            }
             return;
         }
         chrome.tabs.sendMessage<MessageBGtoCS>(tabId, message, {frameId});
```

**Comment by ivan** [comment]
Even with the Prerender2 flag enabled, I can no longer reproduce this issue with (unpatched) Dark Reader 4.9.64 in Chrome 114.0.5735.199 on Windows 10 22H2.
