### ISSUE TITLE
[Broken Website] bugs.chromium.org

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#10629]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Bug reports on bugs.chromium.org have dark on dark text in dynamic dark mode.

Example:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54461

### Website Address

https://bugs.chromium.org/

### Steps To Reproduce

1. Enable dynamic dark mode
2. Go to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54461
3. Notice most text on page is unreadable

### Operating System

Linux

### Web Browser name and version

Firefox 108

### Dark Reader version

4.9.62

**Comment by bbhtt** [comment]
Same as https://github.com/darkreader/darkreader/issues/8850

**Comment by Gitoffthelawn** [comment]
Close or leave open to track?

**Comment by Gusted** [comment]
Closing, as it's indeed a duplicate (with the same underlying darning issue).
