### ISSUE TITLE
[Performance Issue] iFixit store pages load slowly

### ISSUE THREAD

**Issue by masonmcelvain** [darkreader/darkreader#10658]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

iFixit's ecommerce pages are unusably slow with DarkReader installed on Firefox.

### Website Address

https://www.ifixit.com/Parts

### Steps To Reproduce

1. With DarkReader enabled, visit https://www.ifixit.com/Parts
2. Notice that everything above the fold renders, but nothing is interactive. Scrolling down reveals that most of the page below the fold is blank.

### Performance Profile

Firefox profile for https://www.ifixit.com/Parts
https://share.firefox.dev/3GWFbzY

### Operating System

Ubuntu 22.10

### Web Browser name and version

Firefox 109.0

### Dark Reader version

4.9.62

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

No

### Additional Context

I see that there are many existing Firefox performance issues for DarkReader. iFixit's dev team is interested in solving this problem for our customers, so if there's anything we can do on our end to help let us know.

**Comment by alexanderby** [comment]
Do you still have the problem? I cannot reproduce it.

**Comment by masonmcelvain** [comment]
I can't reproduce it anymore either. Thanks for taking a look!

**Comment by alexanderby** [comment]
It was probably fixed earlier for another website.
