### ISSUE TITLE
[Bug] No Auto Mode on Linux (Fedora Rawhide)

### ISSUE THREAD

**Issue by romulasry** [darkreader/darkreader#10694]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

No auto button on my Firefox 109.0.

### Website Address

https://github.com/darkreader/darkreader

### Steps To Reproduce

1. Click on dark reader to open it
2. No auto mode
3. No profit.

### Expected Behavior

Auto mode

### Actual Behavior

No auto mode showing

### Screenshots

![Screenshot from 2023-01-26 22-46-28](https://user-images.githubusercontent.com/19944656/215025793-fa056731-fe36-4a7e-a2b8-5482d2f0bfea.png)

### Operating System

Fedora Rawhide Linux

### Web Browser name and version

Firefox 109.0

### Dark Reader version

4.9.62

**Comment by bershanskiy** [comment]
Hello @romulasry, thanks for bug report.

Looks like you are using the old design. In the old UI design automation settings are here:
![215025793-fa056731-fe36-4a7e-a2b8-5482d2f0bfea](https://user-images.githubusercontent.com/45960703/216758312-8121da67-4813-4d5b-87be-bc3644e4f7f2.png)

If you would like to use the new design (the same one you see on Firefox Mobile), please use this guide:
https://darkreader.org/tips/activate-v5-preview/

**Comment by bershanskiy** [comment]
If this does not answer your question, please reopen.
