### ISSUE TITLE
"Loading, please wait..." message potential fix?

### ISSUE THREAD

**Issue by AndroidKitKat** [darkreader/darkreader#1070]
I recently switched browsers from Chrome to FireFox and I noticed that I could install Dark Reader, but it was always loading indefinetly.

My Computer is running the latest FF release (65) and I think I may have found some solution to the problem. I switched FireFox's language from the host language (Japanese) to English, and the extension works just fine. I have tested this with the same FireFox version on both my MacBook and my other Mac mini. 

I hope this information helps and if there's anything else you would like to know, please do not hesistate to ask.

**Comment by Gusted** [comment]
Fixed.
