### ISSUE TITLE
Bypassing cookie rules in Firefox

### ISSUE THREAD

**Issue by zng02** [darkreader/darkreader#1071]
DarkReader seems to be causing Firefox to save cookies when it shouldn't be able to. I had noticed that cookies for websites were staying on my system despite privacy settings, and disabling all add-ons fixed the problem. Re-enabling them one at a time, I found that DarkReader was the one allowing the cookies to be saved. I can verify this is happening on both Firefox 65.0 and Firefox Nightly, both on Ubuntu 64bit.

To replicate this bug, go into private browsing and use a cookie testing website like [html-kit ](http://www.html-kit.com/tools/cookietester/) or [whatarecookies](http://www.whatarecookies.com/cookietest.asp) . Private browsing shouldn't be able to save cookies normally, but will do so if DarkReader is enabled.

**Comment by alexanderby** [comment]
Didn't notice anything like this and cannot imagine how this could be possible. Was not able to reproduce on specified websites.
<img width="540" alt="screen shot 2019-02-04 at 19 06 51" src="https://user-images.githubusercontent.com/9638588/52220596-55c77180-28b0-11e9-8742-23fafed85f64.png">

**Comment by zng02** [comment]
Oddly enough, after re-enabling Dark Reader to test again, I can't replicate the bug either. For reference, the bug was encountered with Firefox Content Blocking set to Strict, not Custom with cookies fully disabled. However, it seems this was a weird problem isolated to my system. Sorry about the confusion, and thank you for the quick response.

**Comment by zng02** [comment]
I apologize for the confusion, but I have done more testing with my extensions and tracked the cookie leaking issue back to Dark Reader. The bug seems to be inconsistent, which is why I couldn't replicate it before and closed the issue. It doesn't happen all the time when Dark Reader is enabled, but it never happens without it. This made identifying the culprit difficult, but I can verify now that it is Dark Reader.

To be clear, it does not seem to bypass custom Firefox cookie rules to disable all cookies, but it allows cookies from Private Browsing to persist if cookies are enabled in any way. This has been most thoroughly tested using custom content blocking rules set to block all third-party cookies. The "Do Not Track" signal is also enabled, and trackers are blocked in all windows using the level 1 block list.

This has been tested on Firefox 66.0.1, running on 64 bit Ubuntu 18.10. I tested this bug by disabling all extensions, then testing them one at a time over a long period of time.

**Comment by Gusted** [comment]
I don't experience this bug. Also we don't have permissions to cookies so if this still persist it can't be dark reader.
