### ISSUE TITLE
[Broken Website] Flat UI Colors

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#10711]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Website is a color palette browser, when Dark Reader is enabled, colors are altered.

### Website Address

https://flatuicolors.com/

### Steps To Reproduce

1. Visit website
2. Select a palette

### Screenshots

| Disabled      | Enabled |
| ----------- | ----------- |
| ![screenshot-flatuicolors com-2023 01 30-18_39_36](https://user-images.githubusercontent.com/21284089/215552459-1c6a5e9e-19e5-4e31-b617-ae70f2f7b16d.png)      | ![screenshot-flatuicolors com-2023 01 30-18_39_18](https://user-images.githubusercontent.com/21284089/215552464-19361bea-e4b1-4851-a1f4-169eae47a3fc.png)       |

### Operating System

Linux Mint 21

### Web Browser name and version

Brave 1.47.186

### Dark Reader version

4.9.62

### Additional Context

None

---

Thanks

**Comment by bershanskiy** [comment]
Thanks for this report.

For the time being please either disable Dark Reader on the page or add the following fix to Dark Reader DevTools:
```
================================

flatuicolors.com

IGNORE INLINE STYLE
.color

================================
```
