### ISSUE TITLE
press ctrl+n in Dev Tool entire firefox crash

### ISSUE THREAD

**Issue by schrodog** [darkreader/darkreader#1072]
Environment: Ubuntu 18.10, Firefox 64

In firefox latest version 64, When the Dev Tools is opened as separate window and press `ctrl+n` with focus in dev tool, first a new blank window popup, then the whole firefox crash and also my linux desktop crash. Is it a problem with firefox itself or design of extension?

**Comment by alexanderby** [comment]
Doing so on mac opens new window, so I think this is a browser bug.

**Comment by Gusted** [comment]
Hi their!

I've tried this on a windows with Firefox Developer.
Does this issue still persist? So yes than it's most likely a linux bug with firefox.
