### ISSUE TITLE
Problem with Temporary Containers add-on in Firefox

### ISSUE THREAD

**Issue by SeriousHoax** [darkreader/darkreader#1073]
This a Firefox add-on that I use, 
https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/ 

This add-on set to load every website and new tab in a new container if the site doesn't match the domain of the current site. This is the settings, 
<img src="https://mnmlsv.net/images/8239af9b4ab455a5a02baeee49096866.png" alt="8239af9b4ab455a5a02baeee49096866.png" border="0" />

Suppose if I'm browsing a website on temporary container numbered 'tmp250' and click on a link on that site with middle mouse button that's of another domain then a new tab is opened in "tmp251". 
When I do this, most of the time with Dark Reader's default settings which is dynamic, it fails to turn the page dark. It loads in default theme of that particular site. This happens 9 out of 10 times for me. Reloading the page loads it in Dark Theme like it's supposed to do. Other theme generation mode works fine with that add-on. This only occurs with the Dynamic Theme. 

Edit: The same theme not changing problem just occurred multiple times within same "Firefox Multi-Account Containers" while opening a new tab via mouse wheel. Is this a common bug of the extension or only happens in containers? I only started to use this extension today so I'm a bit confused of the situation.

Edit2: It happened multiple times when I manually opened a container via Firefox Multi-Container and pasted a link and dark theme didn't work.

**Comment by Gusted** [comment]
LGTM.
