### ISSUE TITLE
Page element not affected by dynamic theme

### ISSUE THREAD

**Issue by win8linux** [darkreader/darkreader#1074]
On GamingOnLinux articles like [this one](https://www.gamingonlinux.com/articles/the-free-fps-urban-terror-resurgence-now-has-some-updated-footage.12911), the title header graphic is not affected by the dynamic theme:

![image](https://user-images.githubusercontent.com/11584387/52211918-2faccc00-28c6-11e9-96b4-d46bf31d977b.png)

**Comment by Gusted** [comment]
Fixed.
