### ISSUE TITLE
At around 30 tabs in chrome I begin to crash fairly often (Dynamic)

### ISSUE THREAD

**Issue by MostHated** [darkreader/darkreader#1075]
Hello there,
    I really love this addon, which is why it is quite saddening that I keep having a ton of issues with crashing, having to close chrome, reopen it, "out of memory", etc with only about 30 or so tabs open. Most of them are either Github, the [Unity forums](https://forum.unity.com), and then sometimes gmail, facebook, reddit, but I have been trying to only open them when I need them because of the issues.

My system is R5 2600, 32gb ram (I even check to make sure the standby list memory is cleared) and I still get "out of memory" and crashes quite often ever since I installed this addon, unfortunately. It seems it can happen no matter how much free memory I actually have on my system. The most recent crash I had 18gb of free memory.

If it helps any, I am using: 

Windows 10 Pro - 10.0.17763
Chrome - Version 71.0.3578.98 (Official Build) (64-bit)
I believe the most recent version of the addon from the Chrome addon store.

If anyone has any suggestions which may help, please do let me know!
I am not sure if using static instead might help? If it does, is there a way to take the style in which Dynamic creates and then save it and apply it permanently to sites I frequent?

**Comment by alexanderby** [comment]
Memory usage in Dynamic mode depends on how much stylesheets are used on the webpage (Gmail is an example of not optimal website). Static mode or Filter mode could reduce the memory usage.

**Comment by MostHated** [comment]
Is it possible to be in static mode and then just once use dynamic mode (which always ends up looking nice) then take the generated stylesheet at the time and have it save that for use as static and just use that from now on unless something changes and I manually refresh the dynamic stylesheet?

**Comment by echan00** [comment]
I love this extension, but the memory usage (i am on 16GB ram Macbook Pro 2018) slows down my laptop significantly after 30mins of surfing the web
