### ISSUE TITLE
Link privacy policy on AMO

### ISSUE THREAD

**Issue by rugk** [darkreader/darkreader#1076]
addons.mozilla.org (AMO) does have a way to set the privacy policy of your add-on.

In your case, you should at least enter a link to your website version of that policy there, or obviously directly include it.

**Comment by alexanderby** [comment]
I've just added privacy policy on the add-on's page, here you can also find a link to Privacy Policy from the extension 
![image](https://user-images.githubusercontent.com/9638588/52337357-73afe600-2a18-11e9-83ac-29682139904b.png)

**Comment by rugk** [comment]
Thanks, so as this is fixed, I'll close it. 😄
