### ISSUE TITLE
Incorrect background-image generated

### ISSUE THREAD

**Issue by DianaNites** [darkreader/darkreader#1077]
The https://www.musl-libc.org/how.html page has, by default, a `background-image: url(puzzle-a2.svg);` for .listpanel

But enabling the dynamic theme overrides that with `background-image: url(https://www.musl-libc.org/how.html/puzzle-a2.svg);`, which is incorrect. It should be https://www.musl-libc.org/puzzle-a2.svg, or even better don't change the link at all?

Untested with any other theme option.

Resolved locally by overriding the CSS back.

**Comment by Gusted** [comment]
Hey their!

I'm working on a fix for this, I only need to get working ../ for backwards folders(else it could going to break another urls) and than a PR will be made.
Thank you for reporting this issue!

**Comment by Gusted** [comment]
#2323 A Pull request has been made and will be merged soon(Somewhere next week)
