### ISSUE TITLE
[Feature request] Turn on-off site with double-click on icon

### ISSUE THREAD

**Issue by tylla** [darkreader/darkreader#1078]
I would like to suggest a feature when a double-click on the DarkReader icon would enable-disable it for the current site (a'la Alt-Shift-A only this could be used by those few who tend to forget shortcuts).

**Comment by BRA1L0R** [comment]
This is actually pretty cool, I think i will start to work on this

**Comment by Gusted** [comment]
Technically not possible.

**Comment by tylla** [comment]
Ohhh, really? :(
Any other way to not open the GUI, like middle click?

**Comment by Gusted** [comment]
> Ohhh, really? :(

Unfortunately :(, I tried some workarounds and hackery, but sadly most methods were unreliable.

> Any other way to not open the GUI, like middle click?
Nope, The icon was purely their to open the Pop-up current state isn't made for any other clicks.

**Comment by tylla** [comment]
I'm really sad.
Anyway, thanks for trying to solve it. And for dedicating your time to this nice little piece of software.

**Comment by Yash-Singh1** [comment]
@Gusted After doing a quick search, I found out that there is a way. Didn't test it: https://stackoverflow.com/questions/13804213/how-can-i-capture-events-triggered-on-an-extension-icon/32515512.

**Comment by Gusted** [comment]
> @Gusted After doing a quick search, I found out that there is a way. Didn't test it: https://stackoverflow.com/questions/13804213/how-can-i-capture-events-triggered-on-an-extension-icon/32515512.

I tried to get those working, either Firefox was being *aggressive* towards me or chrome just liked to not even open the pop-up any more. It's some trickery code that in might be possible in a further point with some optimizations.

**Comment by tylla** [comment]
Nice to see there is still some hope... :)
Sorry I can't really help with it (except with testing, naturally).
