### ISSUE TITLE
[Broken Website] New Bing Chat

### ISSUE THREAD

**Issue by bgiesing** [darkreader/darkreader#10782]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The brand new Bing with chatbot has a background image (https://www.bing.com/cdx/bg.jpg) that doesn't get inverted when Dark Reader is activated.

### Website Address

https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx

### Steps To Reproduce

1. Be off the whitelist for the new Bing with AI stuff
2. Open the Chat page

### Screenshots

![image](https://user-images.githubusercontent.com/7895463/218364971-038f99a7-b200-4179-94ab-e31f279d702c.png)

### Operating System

Windows 11 22H2 25290.1010

### Web Browser name and version

Microsoft Edge Dev 111.0.1660.12

### Dark Reader version

4.6.92

**Comment by coryginsberg** [comment]
Found a temporary work around for now. Go to the Dev Tools and under the `INVERT` section within `bing.com` add `div.image` and apply. It's not perfect (Bing's text color could do with being inverted) but it's good enough for me for now.
![image](https://user-images.githubusercontent.com/7117971/219073832-8ee8a04a-4b11-49a0-b645-dc037bc4e9fb.png)

**Comment by joosniz** [comment]
@bgiesing that's a nice workaround. The sidebar version of Bing has a dark mode so might be a good idea to match the bubble color of that instead of inverting the text, if anyone can figure out exactly how.

![bing chat dark colors](https://user-images.githubusercontent.com/11315995/219824685-a35fb650-ee42-465a-939a-f0f909031906.png)

Color for the bubble: `#414141`

**Comment by cheekysim** [comment]
> 
This was what I used to change the bubble color

```
cib-shared > div.content {
    background-color: #414141 !important;
    border-radius: 10px;
}
```

**Comment by Eletroclip** [comment]
Go to the Dev Tools and under the INVERT section within bing.com add this:

```
cib-serp
div.icon
div.item-body
div.item-title
div.ac-textBlock
button.chat-button
```

Temporary work around that I found for myself! 

Thx [coryginsberg](https://github.com/coryginsberg) for helping me discover how to make this work around. I did it based on your answer!

**Comment by DeFaLT-dj** [comment]
> Go to the Dev Tools and under the INVERT section within bing.com add this:
> 
> ```
> cib-serp
> div.icon
> div.item-body
> div.item-title
> div.ac-textBlock
> button.chat-button
> ```
> 
> Temporary work around that I found for myself!
> 
> Thx [coryginsberg](https://github.com/coryginsberg) for helping me discover how to make this work around. I did it based on your answer!

Thanks! that helped a lot!

**Comment by alexanderby** [comment]
Should work fine now.
