### ISSUE TITLE
Dynamic theme doesn't work on CMake documentation

### ISSUE THREAD

**Issue by DianaNites** [darkreader/darkreader#1079]
When changing the version of documentation via the top left dropdown on https://cmake.org/cmake/help/v3.13/, the the dynamic theme is partially/completely ignored/bypassed.

All the other theme engines persist such changes.(but don't look good)

It also randomly fails to apply on newly opened tabs, *but* only if you switch to that tab while it's loading.
It seems to apply fine if you let it finish loading in the background, or open the link in your current tab.

**Comment by alexanderby** [comment]
Looks OK to me. What browser are you using?
![image](https://user-images.githubusercontent.com/9638588/52338862-980dc180-2a1c-11e9-811d-7e0c1fc75bee.png)

**Comment by DianaNites** [comment]
Google Chrome 72.0.3626.81

As previously stated, it only fails in certain conditions, which i will repeat here for clarity.

If you change the version using the dropdown in the top left, most of the page will appear light again. It may take a few switches.

If you open a CMake page in a new tab, but switch to that tab before it finishes loading, the theme also will not be applied.
This does not appear to happen on other websites, or if you wait for the tab to finish loading.

I've made a gif to demonstrate the issue. 

![2019-02-06_07-21-53](https://user-images.githubusercontent.com/5275194/52341223-06805e80-29e0-11e9-8615-73b910100e3c.gif)

**Comment by alexanderby** [comment]
Great, I was able to reproduce.

**Comment by DianaNites** [comment]
Also applies to the [Python documentation](https://docs.python.org/3.6/index.html), same repro steps.

**Comment by Gusted** [comment]
going to merge it into the #835 issue.
