### ISSUE TITLE
[Broken Website] support.mozilla.org seems to be protected in Firefox

### ISSUE THREAD

**Issue by Ayx03** [darkreader/darkreader#10813]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark Reader don't work on [support.mozilla.org](support.mozilla.org) when using Firefox but works with Edge and Chrome, so I think it's protected by Firefox.
![image](https://user-images.githubusercontent.com/75155322/220183386-d026f2c7-7701-4efe-b131-67b6e191d1b9.png)

### Website Address

https://support.mozilla.org/

### Steps To Reproduce

Open Firefox, navigate to [support.mozilla.org](support.mozilla.org), Enable Dark Reader.

### Expected Behavior

Say this page is protected by browser like below
![image](https://user-images.githubusercontent.com/75155322/220183497-3d344626-aa9d-4a3a-8435-b6873d33e557.png)

### Actual Behavior

Can be toggled but don't do anything

### Operating System

unrelated but Windows 11 Pro 22H2

### Web Browser name and version

Firefox Version 110.0 (64-bit)

### Dark Reader version

4.9.62 (latest)

**Comment by Ayx03** [comment]
Seem to be influenced by uBlock Origin or other extensions, I'm sorry I didn't check in a new profile.

**Comment by bershanskiy** [comment]
Hi @Ayx03, Firefox restricts extensions from accessing Mozilla sites for security reasons. You can disable this restriction via an option, but it is not recommended.

**Comment by Ayx03** [comment]
> Hi @Ayx03, Firefox restricts extensions from accessing Mozilla sites for security reasons. You can disable this restriction via an option, but it is not recommended.

Sometimes it doesn't show up as protected, seems to be affected by other extensions, is there a way to fix that?

**Comment by domeniczz** [comment]
@bershanskiy I find the "option" is `extensions.quarantinedDomains.enabled`, after toggle it to false in about:config, darkreader still can't work on support.mozilla.org. How to fix it?

**Comment by AliceDTRH** [comment]
Some extensions seem to have an option to allow running on restricted sites now. Is this an option for darkreader?
![image](https://github.com/darkreader/darkreader/assets/57547425/458a2cde-1017-4df9-bdcd-f896881e6c67)

**Comment by Ayx03** [comment]
@domeniczz does it still refuse to work because it think the site is protected?

**Comment by AliceDTRH** [comment]
I am pretty sure it always would always refuse to run because I think it's hardcoded:
https://github.com/darkreader/darkreader/blob/414da538e8e3f719823380bbb0e323f483bc9449/src/background/utils/extension-api.ts#L13
