### ISSUE TITLE
google keep, update list settings button not visible

### ISSUE THREAD

**Issue by promeneur** [darkreader/darkreader#1082]
Version 72.0.3626.81 (Build officiel) (64 bits)

go to https://keep.google.com/

at the upper right corner 3 buttons briefly appears then are not visible.

you can overpass them with mouse cursor and see the mouse cursor becoming a hand.

the 3 buttons are:

update
list
settings

**Comment by promeneur** [comment]
hello

why do you close this report ?

thanks

**Comment by alexanderby** [comment]
Cause it should be fixed now.

**Comment by promeneur** [comment]
it works

thanks
