### ISSUE TITLE
[Feature Request] Toogle extension ON and OFF based on time schedule

### ISSUE THREAD

**Issue by andreclerigo** [darkreader/darkreader#10829]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

I was wondering if there would be a way to implement a feature that turns the extension ON and OFF based on a time schedule (defined by the user or the default sunrise to sunset).

**Comment by bershanskiy** [comment]
Hi, this feature is already available in the new UI. To view the new UI:
1. Open popup
2. Click "Dev Tools"
3. A popup will appear, click "Preview new design"
4. Open popup, click "Settings" > "Automation" > select the desired automation option
