### ISSUE TITLE
offline html support

### ISSUE THREAD

**Issue by shiftyshady** [darkreader/darkreader#1083]
screenshot of original page (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), with DarkReader enabled (version 4.7.5)
![original_page](https://user-images.githubusercontent.com/30387970/52365398-4aef1700-2a3f-11e9-92fa-83be60109847.jpg)

screenshot of saved page (saved with extension SingleFile or scrapbook or probably most other ways to save webpages, with DarkReader disabled, then viewed with DarkReader enabled)
![saved_page](https://user-images.githubusercontent.com/30387970/52365506-8db0ef00-2a3f-11e9-81f6-e06f4100ec9a.jpg)

The html code seems identical, same elements, same selectors, so the problem might be with how dark reader handles offline html documents.

Also, Dark reader "toogle" feature only takes drive letter as domain, so it's not usable. 
![offline_site](https://user-images.githubusercontent.com/30387970/52366213-15e3c400-2a41-11e9-877d-9dbb90c676d4.jpg)

**Comment by Gusted** [comment]
You can use #3120 as it's rather the browser that is not converting Dark reader styles right.

**Comment by Subfire** [comment]
![image](https://github.com/darkreader/darkreader/assets/16792880/85745aa0-7659-4924-a9ed-366d24d825ed)
