### ISSUE TITLE
docs.google completely inverted

### ISSUE THREAD

**Issue by SharkSheaker** [darkreader/darkreader#1088]
the whole website included the sheet itself is inverted. it makes no sense to invert all the columns and rows too

**Comment by SheepKid12** [comment]
If you go into the dev tools and find `docs.google.com`, you can add `div.kix-paginateddocumentplugin` to make the sheet white.

**Comment by SharkSheaker** [comment]
> If you go into the dev tools and find `docs.google.com`, you can add `div.kix-paginateddocumentplugin` to make the sheet white.

either im too stupid or it doesnt work

**Comment by SheepKid12** [comment]
I'm using dynamic. Here's what I have:

```
================================

docs.google.com

INVERT
.docs-icon
.punch-filmstrip-controls-icon
#docs-editor canvas
div.kix-paginateddocumentplugin
```

**Comment by SharkSheaker** [comment]
did a copy paste. doesnt work still

**Comment by SharkSheaker** [comment]
what browser are you using?

**Comment by Mhowser** [comment]
Send a screenshot with your issue, be sure to blur out anything personal/private.

**Comment by SharkSheaker** [comment]
![example wrong](https://user-images.githubusercontent.com/22985852/53302457-8cb0f780-385e-11e9-8daa-a30aa5def357.PNG)
![example right](https://user-images.githubusercontent.com/22985852/53302459-920e4200-385e-11e9-83a1-890578131a02.PNG)

**Comment by AndroidDeveloperLB** [comment]
Duplicate:
https://github.com/darkreader/darkreader/issues/490
?

**Comment by SharkSheaker** [comment]
@AndroidDeveloperLB the #490 is refering to the text inside the cells, but i am talking about the whole sheet tab. look at the two pictures then you see what i mean.

i forgot to mention @Mhowser that the second picture is photoshopped, so i can show more clearly what i mean.
No, i didnt solve that yet

**Comment by AndroidDeveloperLB** [comment]
@SharkSheaker I think it's related. People want it to be dark without the issues of text that becomes un-readable...

**Comment by Gusted** [comment]
Fixed.
