### ISSUE TITLE
[Feature Request] Add settings export/import

### ISSUE THREAD

**Issue by mrx23dot** [darkreader/darkreader#10903]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

All major apps have this, it saves a lot of time during installation.

**Comment by bershanskiy** [comment]
Dark Reader already supports settings export and import via the new UI. To use it:
 - enable new UI
   - open extension popup
   - click "developer tools"
   - click button to enable new design preview
 - export settings
   - open extension popup (it will look different)
   - open settings management
   - export settings (or import from file, using the same UI)

If you have a question, please comment below, I'll answer and reopen if needed.

**Comment by bershanskiy** [comment]
@uuqqzz The new UI is enabled by default on Firefox for Android and other mobile browsers (e.g., Kiwi). It is also available (can be enabled by the user) on desktop browsers.

**Comment by bershanskiy** [comment]
>Cool that works, when will the new design be official?

We do not have a set release date yet.

>There is no back button from settings window :)

The back button is at the bottom:
![image](https://user-images.githubusercontent.com/45960703/224704151-b9e442f6-500c-43a6-86a8-4e33e2a92d25.png)
