### ISSUE TITLE
Icons being converted to strings after page refresh

### ISSUE THREAD

**Issue by xr-dev** [darkreader/darkreader#1095]
I'm having issues with a page that renders correctly as soon as I enable Dark Reader, but turns icons on buttons (coded as backgrounds in CSS) into strings as soon as I refresh the page.

I tried using the Dev Tools but couldn't find a way to make the icons render, inverted or not. Happens with all the themes.

When Dark Reader is just enabled:
![1](https://user-images.githubusercontent.com/7648213/52565877-39b35b00-2def-11e9-9949-1ef6ec4358bb.PNG)

After a page refresh:
![2](https://user-images.githubusercontent.com/7648213/52565901-48017700-2def-11e9-84ff-e6c47bf3c1ae.PNG)

It happens with every button on the page.

Is this intended? If so, is there a way to make the extension ignore these icons? Also, since the page requires authentication, could I save the fixes without a pull request?

Thanks!

*Edit: after further inspection, it looks like the image is shown after enabling the extension only because it's cached or something of that sort, since the CSS is immediately replaced, as I assume the original images are at EventMonitor.scss (where there are full SVGs).*

![3](https://user-images.githubusercontent.com/7648213/52635203-67140d80-2eb0-11e9-9f36-7e78146741c3.PNG)

![4](https://user-images.githubusercontent.com/7648213/52635489-25d02d80-2eb1-11e9-9e3b-42524223e3a4.PNG)

**Comment by Gusted** [comment]
Fixed.
