### ISSUE TITLE
Building stuck at reload.js

### ISSUE THREAD

**Issue by maxloh** [darkreader/darkreader#1098]
After executing `npm run debug`, the building either stuck at `Auto-reloader started` or `Auto-reloader connected` and do not complete the building after a long time.

![image](https://user-images.githubusercontent.com/35831069/52706412-55ba2680-2fc0-11e9-84dc-7da6f9072347.png)

Remove reload in debug.js solve the problem and the semicompleted build also works
```
await runTasks([
    clean,
    bundleJS,
    bundleCSS,
    bundleHtml,
    bundleLocales,
    copy,
    foxify,
    reload, //remove this line
], options);
```

**Comment by alexanderby** [comment]
It is not stuck, it is waiting for file changes to rebuild and reload the extension in Chrome automatically. Rebuilding takes some time, because tasks were rewritten to not use vulnerable Gulp dependencies, and this process is not optimized (cached) yet.

**Comment by maxloh** [comment]
Thank you for your answer.
I am closing the issue.
