### ISSUE TITLE
[Broken Website] Atlassian.net - Confluence page stays white when `selection = Auto`, Jira looks terrible when `selection=Default`

### ISSUE THREAD

**Issue by alexdauenhauer** [darkreader/darkreader#11039]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I was noticing that when I am looking at Jira, it looked pretty bad because the cell edges were being rendered as fairly bright colored lines. It looks good and as I expect it to look (like a dark mode inverse of the original) when I change `See all options -> Colors -> Selection = Auto`. However, when I change this, then my Confluence pages won't go to dark mode. They basically half transition and some of the edges of the page go to the dark mode, but the part surrounding the text stays white (only the font has now transitioned to the dark mode color of font so it is even more difficult to read than in light mode). If I change `See all options -> Colors -> Selection = Default`, then Confluence looks good, but now Jira looks like garbage. I could probably get around this if I could set the settings for each subpage, but it looks like I can only set settings globally for atlassian.net

### Website Address

atlassian.net (internal pages)

### Steps To Reproduce

1. load a page in Jira with default Dark Reader settings
2. see that it doesn't look good because the lines are high contrast or something like this
3. change `See all options -> Colors -> Selection = Auto`
4. see that Jira looks good now
5. go to Confluence and see that it is all white and weird looking
6. change `See all options -> Colors -> Selection = Default`
7. see that Confluence looks ok now, but Jira looks terrible again

### Operating System

macOS

### Web Browser name and version

Chrome Version 111.0.5563.146 (Official Build) (arm64) - also on Firefox 111.0.1 (64-bit)

### Dark Reader version

4.9.62

**Comment by southrop** [comment]
Funnily enough, I've been having the opposite issue.

`Selection = auto` does this for me.
![image](https://user-images.githubusercontent.com/2568167/229667271-a4d8c399-8a3d-496a-9559-a5eb704b4992.png)

On a private Confluence that I use, `Selection = default` actually causes the page content to disappear for some reason.

In any case, here is a public demo Confluence from Atlassian for evaluation that can be used for repro/testing: https://templates.atlassian.net/wiki/spaces/RD/overview

**Comment by escote-tatari** [comment]
![image](https://user-images.githubusercontent.com/75756504/229889768-a3ae3faf-1df8-4f0b-8354-7e95def9bf38.png)
There is a broken tag in Confluence html causing the issue. They should fix that. We have filed a support ticket with them to do just that. However, it would be nice if Dark Reader could handle this more gracefully.

**Comment by K0smic** [comment]
To fix this (hopefully momentary) issue, I created a tampermonkey userscript that uses an observer to wait for the tag to exist and then remove the background property, It's not beautiful but it works:
```
(function() {
    'use strict';
    const observer = new MutationObserver((mutations) => {

        if (document.querySelectorAll('div[style="background-color: ; background-image: none; background-size: auto; padding: 0px; border-radius: 0px; width: 100%; box-sizing: border-box; --darkreader-inline-bgimage:none;"]')[0]) {
            console.log("JS ready");
            document.querySelectorAll('div[style="background-color: ; background-image: none; background-size: auto; padding: 0px; border-radius: 0px; width: 100%; box-sizing: border-box; --darkreader-inline-bgimage:none;"]')[0].style.removeProperty("background-color")
            observer.disconnect();
        }
    });
    observer.observe(document.body, {
        childList: true,
        subtree: true,
    });
})();
```
Only the `@match` header was modified with part of the url and /*

**Comment by wishx** [comment]
>  It's not beautiful but it works:

I couldn't get this to work in Tampermonkey as pasted. It says that $ is not defined. There seems to be a lot of previous commented code. Do I need to change something to make it work?
I use Confluence all day every day, and this issue is an eye-killer.
Thanks!

**Comment by southrop** [comment]
If you couldn't get that to work, another easy temporary solution is to switch the mode to Filter or Filter+. Not perfect because it does some things like inverting the color on image lightboxes (so you end up with a light grey bg instead), but at least the main pages are dark again with that.

![image](https://user-images.githubusercontent.com/2568167/230456333-dff22d96-6899-45d9-95b0-1df024a75152.png)

**Comment by escote-tatari** [comment]
We have an official public ticket for this with Atlassian: https://jira.atlassian.com/browse/CONFCLOUD-75644

**Comment by escote-tatari** [comment]
> (function() {
>     'use strict';
>     // window.addEventListener('load', function() {
>     //     console.log("JS ready");
>     //     document.querySelectorAll('div[style="background-color: ; background-image: none; background-size: auto; padding: 0px; border-radius: 0px; width: 100%; box-sizing: border-box; --darkreader-inline-bgimage:none;"]')[0].style.removeProperty("background-color")
>     // }, false);
>     const observer = new MutationObserver((mutations) => {
>         if($){
>             // $('div').filter(function() {
>             //     return ( $(this).css('background-color') == 'rgb(255, 255, 255)')
>             // }).css({'background-color': ''})
>             $('div[style^="background-color: ;"]').css({'background-color': ''})
>             // observer.disconnect()
>         }
>     });
> 
>     observer.observe(document.body, {
>         childList: true,
>         subtree: true,
>     });
> })();

I wasn't able to get this to work after I installed the Tampermonkey extension in Firefox. Keep in mind I am a code, but not JS.

**Comment by southrop** [comment]
Looks like the issue has been addressed by Atlassian, and Dark Reader is working great again for me, so this ticket can probably be closed now.

**Comment by alexdauenhauer** [comment]
yeah looks fixed to me now too
