### ISSUE TITLE
Google Translate Dark Theme has an issue with the buttons

### ISSUE THREAD

**Issue by Sid200** [darkreader/darkreader#1105]
The dark theme on Google Translate somehow messes with the mic and copy buttons and makes them larger.

Dark Theme Applied:

![12](https://user-images.githubusercontent.com/41021075/52784192-4a2b3600-307a-11e9-8106-316a01d6d92c.PNG)

Normal:

![21](https://user-images.githubusercontent.com/41021075/52784201-4e575380-307a-11e9-8c9f-9c7f03261fcf.PNG)

## Temporary Fix

Changing `background-size` to `contain` for `.jfk-image` helps but I am not sure what the problem is.

**Comment by Sid200** [comment]
Issue seems to be resolved (probably a long time ago). Closing this issue.

**Comment by FranklinYu** [comment]
It’s not resolved for me.

![image](https://user-images.githubusercontent.com/3153452/86232771-4e5dd380-bb49-11ea-842c-1aa111a888eb.png)

**Comment by Sid200** [comment]
That's weird. My one has no such issues:
![image](https://user-images.githubusercontent.com/41021075/86242488-70e00300-bbc2-11ea-9ee3-91c83a47a971.png)

**Comment by Sid200** [comment]
Is your extension updated?

**Comment by Gusted** [comment]
Yeah, is it update btw as this is the exact icon I had fixed.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/2112

**Comment by Chubjay** [comment]
Hi All.
Same with Opera...
Missing icon @ address bar (pic att) !
Help need,
Jay
