### ISSUE TITLE
High GitHub source line numbers obscured in filter modes 

### ISSUE THREAD

**Issue by orn688** [darkreader/darkreader#1107]
With Chrome, when viewing source code on GitHub in Filter+ or Filter mode, all of the line numbers after a certain point seem to be obscured by a black box. The exact point at which the black starts depends on the zoom level, but at 100% zoom it's around line 410.

For example, see [this file](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config#L410):

![image](https://user-images.githubusercontent.com/15459200/52824696-75a82380-306e-11e9-922c-f3b3eb26faa0.png)

**Comment by Gusted** [comment]
Fixed.
