### ISSUE TITLE
[Feature Request] Do not save sites disabled in incognito

### ISSUE THREAD

**Issue by bwc69151** [darkreader/darkreader#11075]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

Yes

### Feature Request Description

When I disable dark mode for a website that I am viewing in private mode, Dark Reader saves that option when I open the website in regular mode. But I would prefer if it was possible to clear the cache after leaving the incognito mode.

**Comment by bershanskiy** [comment]
Hi, could you please describe your use case in greater detail? Also, how would you expect the UI to look like?

It sounds like you would like browser to keep Dark Reader's data isolated between regular mode and incognito mode. This is called "split" extension mode. Extensions inherently can not change the mode they run in and supporting this feature seems too arbitrary and burdensome for official release. But I can offer few alternative solutions:
 - I can create a patch for you to apply and build from source, all entirely on GitHub Actions CI
 - I can create an extension/userscript which adds "Dark Reader lock" to desired page and manipulates Dark Reader into disabling itself. E.g., [see this](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/main.user.js).
 - you could just disable Dark Reader in incognito entirely
 - you could write down which site you would like to disable Dark Reader on and perhaps we could include it in the list of globally dark sites

**Comment by bwc69151** [comment]
Hi. I use your extension extensively to design dark mode for my websites. It seems this might be a complicated feature.

**Comment by bershanskiy** [comment]
> I use your extension extensively to design dark mode for my websites.

I have a few extensions I use rarely and do not want to have them permanently installed, so I just create separate profiles for them or enable them for a short period of time on `chrome://extensions/`. Would either option work in your case?
