### ISSUE TITLE
[Feature Request] option to turn off per site.

### ISSUE THREAD

**Issue by IMrCreepyI** [darkreader/darkreader#11110]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

add the option to turn off dark reader per site. for example i want it on on one site but off on the other. kinda like the only for option.

### Additional Context

sorry if it does not make sense English isn't my main language so explaining stuff can be difficult some times.

**Comment by bershanskiy** [comment]
Hi, Dark Reader already supports this feature. Just open the site you would like toggle Dark reader on, then open Dark Reader popup, then click site name in the left box/checkbox:
![image](https://user-images.githubusercontent.com/45960703/232154291-76f77619-d242-428a-8845-f94d30f632af.png)
