### ISSUE TITLE
[Broken Website] snaptik.app

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#11119]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The borders of the buttons are too white.

### Website Address

`https://snaptik.app/`

### Steps To Reproduce

Go to the site.

Use this test URL: `https://www.tiktok.com/@zachking/video/7141492497494117675` and click on "Download".

See the result.

### Screenshots

![image](https://user-images.githubusercontent.com/30274161/231967126-160faf4f-5767-429d-82ec-44f1021f0b6e.png)

### Operating System

Windows 11 Pro 64-bit

### Web Browser name and version

Firefox 112.0 (64-bit)

### Dark Reader version

4.9.63

**Comment by vince-vibin** [comment]
Hey,
unfortunately I was not able to reproduce your issue.
Running on:
- Firefox 112.0 (64-bit)
- Windows 11 Pro 64-bit
- Darkreader 4.9.63

Maybe this has been fixed 🤔

Could you check to see if you are still experiencing the same issue?
