### ISSUE TITLE
[Broken Website] Doesn't work on pkg.go.dev

### ISSUE THREAD

**Issue by rexagod** [darkreader/darkreader#11113]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Navigate to any page on `pkg.go.dev`, for eg., [this](https://pkg.go.dev/plugin), and try triggering the dark mode. The button is unresponsive and the website is always in light mode.

### Website Address

https://pkg.go.dev/

### Steps To Reproduce

1. Go to [`pkg.go.dev`](https://pkg.go.dev/).
2. Search for any package.
3. Go to it's dedicated page.
4. Dark mode not working throughout this website.

### Operating System

Fedora 37 (Workstation)

### Web Browser name and version

Chrome (Stable) (Version 111.0.5563.110 (Official Build) (64-bit)

### Dark Reader version

4.9.63

**Comment by bershanskiy** [comment]
I'm unable to reproduce this bug, could you please clarify repro steps/what you are observing? Thank you.

**Comment by rexagod** [comment]
Ah! Nevermind, it seems this was mistakenly added to the _don't invert list_ in the extension! Apologies!

**Comment by bershanskiy** [comment]
I'm glad you resolved the problem. Also, your report actually helped me find a different issue on the page.
