### ISSUE TITLE
[Feature Request] An app icon that conforms to Apple's standard for Dark Reader on Safari

### ISSUE THREAD

**Issue by Jerry23011** [darkreader/darkreader#11136]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Hi, it's been over two years since macOS Big Sur was released along with [Apple's Human Interface Standards for app icons](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons), would you like to consider designing an icon that meets these standards?

### Screenshots

The current icon looks a bit abrupt alongside other icons that meet Apple's standards.
<img width="671" alt="截屏2023-04-16 19 50 01" src="https://user-images.githubusercontent.com/89069957/232307883-53c8d4eb-15c3-4058-9f85-28b559329c16.png">

### Additional Context

There are some pretty good ones on [macOSicons](https://macosicons.com/#/darkreader) that may serve as good refereces.

**Comment by Zabriskije** [comment]
I already made one if you guys are interested:

<img width="128" src="https://github.com/darkreader/darkreader/assets/101254295/f5817cf9-9fb6-4eb9-85ce-90b92731fb7c">

**Comment by Jerry23011** [comment]
CC @alexanderby

**Comment by Jerry23011** [comment]
CC @alexanderby

**Comment by Jerry23011** [comment]
Duplicate of #5298
