### ISSUE TITLE
[Broken Website] Inverted images on Github Blog

### ISSUE THREAD

**Issue by MarcGuiselin** [darkreader/darkreader#11164]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Some images on the [GitHub blog](https://github.blog/2023-04-11-introducing-the-newest-github-shop-collection/) are inverted.

### Website Address

https://github.blog/2023-04-11-introducing-the-newest-github-shop-collection/

### Steps To Reproduce

1. Enable Dark Reader
2. Visit [page](https://github.blog/2023-04-11-introducing-the-newest-github-shop-collection/)
3. Scroll down to first embedded image in blogpost

### Screenshots

![Inverted image in blog](https://user-images.githubusercontent.com/24906387/233611960-c35ab14a-b34c-49dc-b60f-90a8b43a6ff1.png)

### Operating System

Win 10

### Web Browser name and version

Google Chrome 112.0.5615.138

### Dark Reader version

4.9.63

### Additional Context

I'll work on a pr

**Comment by MarcGuiselin** [comment]
This change reverts: #5270 

The blog had a major layout change a short while back. I did some back and forth using web archive and it looks like these inversions are unnecessary and now break some images on the site.

**Comment by fritx** [comment]
Is it able to invert/skip/ignore some CSS filters (while using the [sdk](https://github.com/darkreader/darkreader?tab=readme-ov-file#using-dark-reader-for-a-website)) from just api configuration,
instead of sending PRs to modify the centralized [src/config/dynamic-theme-fixes.config](https://github.com/darkreader/darkreader/pull/5270/files) ?
