### ISSUE TITLE
Arrow button on scroll bar, missing.

### ISSUE THREAD

**Issue by MrX-at-GitHub** [darkreader/darkreader#1117]
On Chrome, the arrow button on scroll bar disappears when going into dark mode. When I toggle back to light mode the arrow button reappears.

![arrow button](https://user-images.githubusercontent.com/16800851/53068018-670da200-349c-11e9-8dc2-88fa501c5f8b.gif)

**Comment by MrX-at-GitHub** [comment]
Bump. Sorry but this is a long issue since I started using Dark Reader almost a year ago.

**Comment by MrX-at-GitHub** [comment]
Bump. Sorry but I need this fixed. Thanks.

**Comment by Gusted** [comment]
This was on purpose.

**Comment by paradoxicallist** [comment]
> This was on purpose.

Could you elaborate further on this? 
Please.

**Comment by Gusted** [comment]
I wasn't the one who made the decision.
