### ISSUE TITLE
Strip credentials from URLs

### ISSUE THREAD

**Issue by Bluscream** [darkreader/darkreader#1119]
![image](https://user-images.githubusercontent.com/3318223/53224230-ebfae600-366b-11e9-9658-a653103c91a3.png)

**Comment by alexanderby** [comment]
Could you please provide a full address, or a sample that looks like it, so that I can understand which pattern should be used to avoid the problem?

**Comment by Bluscream** [comment]
https://user:pass@example.com

**Comment by EvanHahn** [comment]
Took a quick pass at this. It looks like this value comes from [`getURLHost`](https://github.com/darkreader/darkreader/blob/a30aec3446409e75766924fe2bc3d78d91fdaf7d/src/utils/url.ts#L3-L5), which would need to change to support this. Might look something like this:

```js
export function getURLHost(url: string) {
    return new URL(url).host;
}
```

Wrote a few tests for this too.

Unfortunately, that function seems to be used in other spots and I wasn't sure if I'd break anything without more familiarity with the code.

For what it's worth, the extension seems to be doing a lot of URL parsing with strings (or with `document.createElement('a')`, but perhaps [the standard `URL` object](https://developer.mozilla.org/en-US/docs/Web/API/URL) would be a better fit.
