### ISSUE TITLE
[Broken Website] www.g2a.com

### ISSUE THREAD

**Issue by avi12** [darkreader/darkreader#11207]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The background isn't recolored

### Website Address

https://g2a.com

### Steps To Reproduce

Enter the main page

### Screenshots

![image](https://user-images.githubusercontent.com/6422804/235390737-5a4d6169-245b-46f3-bceb-5033528d080f.png)

### Operating System

Windows 10 22H2

### Web Browser name and version

Edge 112.0.1722.64

### Dark Reader version

4.9.63

### Additional Context

Duplicate of #3640

**Comment by Nilmohon** [comment]
I can try it give me a chance

**Comment by Myshor** [comment]
Seems the site is working fine without any sitefixes now. Closing issue.
