### ISSUE TITLE
YouTube.com -  A couple buttons are not inverted properly in dynamic mode

### ISSUE THREAD

**Issue by Mhowser** [darkreader/darkreader#1121]
![dev-1](https://user-images.githubusercontent.com/24195572/53283970-61b19100-3702-11e9-9356-76b22bcc6384.png)
Using default rules
![ex-1](https://user-images.githubusercontent.com/24195572/53283953-45adef80-3702-11e9-879e-8d3eac98d03e.png)
#continuations > yt-next-continuation > paper-button
![ex-2](https://user-images.githubusercontent.com/24195572/53283956-49417680-3702-11e9-92d5-2ec396fdcf2e.png)
#continuations > yt-next-continuation > paper-button > yt-formatted-string
![ex-3](https://user-images.githubusercontent.com/24195572/53283959-4c3c6700-3702-11e9-9bdd-e6eed1306317.png)
#more-text
![ex-4](https://user-images.githubusercontent.com/24195572/53283964-4e062a80-3702-11e9-8567-d907b2d5fc2e.png)
#less-text
![ex-5](https://user-images.githubusercontent.com/24195572/53283965-4fcfee00-3702-11e9-8643-c0d4d889f5d8.png)
#continuation > yt-next-continuation > paper-button > yt-formatted-string

**Comment by oxguy3** [comment]
Just so you know @Mhowser, YouTube has its own dark theme that you can turn on. Click on your profile picture at the top right, and "Dark theme" will be an option in the menu. I personally use this and turn Dark Reader off for youtube.com (a hand-crafted official dark theme will always beat out a machine-generated one).

**Comment by Mhowser** [comment]
I am aware of YouTube's official dark theme, the original issue doesn't
occur anymore. Please feel free to close this issue.

**Comment by AAli107** [comment]
Wait, is that me in one of the screenshots!?

**Comment by Gusted** [comment]
> Wait, is that me in one of the screenshots!?

Congrats your famous

**Comment by Gusted** [comment]
Anyway closing this as it has been fixed.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/90312468-0500f200-df05-11ea-8cfb-0c662abdcfaa.png)
