### ISSUE TITLE
[Broken Website] bugs.chromium.org

### ISSUE THREAD

**Issue by jarretttai** [darkreader/darkreader#11236]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The dark mode doesn't work properly on chromium bug sites.

### Website Address

https://bugs.chromium.org/

### Steps To Reproduce

1. Turn on the dark mode
2. Open a tab to access [the website](https://bugs.chromium.org/)
3. The page doesn't seem to render properly

### Screenshots

![image](https://user-images.githubusercontent.com/58059997/236664525-d094313c-9c28-4fb9-b2e1-2dd9cb5d9eef.png)

![image](https://user-images.githubusercontent.com/58059997/236664891-b1fe1160-1237-422d-9785-121d6aff8148.png)

### Operating System

Fedora Linux

### Web Browser name and version

Firefox 112.0.2

### Dark Reader version

4.9.63

**Comment by NguyenASang** [comment]
I fixed this site at #11185, but maybe you haven't synced the site fixes, watch this video to enable it:

https://user-images.githubusercontent.com/87893636/236675920-d3955fb5-1fea-4059-ac26-8ae92933c3e0.mp4

**Comment by jarretttai** [comment]
> 

Thank you! Let me close this issue.
