### ISSUE TITLE
FF, gmail, performance issue, workaround proposal

### ISSUE THREAD

**Issue by grappas** [darkreader/darkreader#1123]
After refresh a page with gmail It's taking about 15 seconds to fully apply dark reader filters. By this time page is unusable. I've tested it on Chrome and it wasn't an issue (why It would be - if you know what I mean).
It seems that every refresh Dark Reader scans code from scrach. Is it possible to save values for page mannualy, that Dark Reader could reuse It?

**Comment by Gusted** [comment]
Has been fixed trough #535
