### ISSUE TITLE
checkForUpdate polling causes significantly increased CPU usage on some sites

### ISSUE THREAD

**Issue by DanielG** [darkreader/darkreader#1125]
#### Overview
I recently noticed a significant increase in Chromium's idle CPU usage and identified darkreader as the culprit. My methodology involves observing the relevan't Tab's CPU usage in the Chromium task manager before and after switching from the Dynamic theme to Static/Filter but also verified it by disabling the offending code, see below.

#### Impact
The CPU usage on Google Search/Youtube homepages goes up from about 2-4% in idle to 15-20% in idle (as seen in Chromium's task manager).

Due to the use of `requestAnimationFrame` to schedule polling this only seems to happen when the page is currently visible in a browser window limiting the impact somewhat.

#### Reproducing
I belive the polling of stylesheet changes in `checkForUpdate` is causing this high load. If I comment out the `requestAnimationFrame(checkForUpdate)` call in `src/inject/dynamic/style-manager.ts` the CPU usage reliably goes back to baseline levels.

#### Fix
I'm not really sure what kind of changes are being watched for here, is this only for first time load stuff or is this also intended to catch changes after the site finished loading? I would send a patch but my javascript foo is very rusty, but given some direction I would be happy to help implementing a fix.

Would it be possible to get notified of these stylesheet changes instead of polling? If not throttling the polling as the site reaches a steady state might be a decent fix.

Personally I might be happy just being able to set the theme engine per-site but that seems crude as a fix :)

**Comment by alexanderby** [comment]
Thanks for noticing that.

There is a need to check for updates, because some sites, like new Reddit, change style sheets dynamically, usually using styled components library or a similar hipster approach. When the app state changes (e.g. you start writing a comment on Reddit) they update style sheets not by adding class names for changed elements (the most popular and simple approach), but by changing properties in CSS rules dynamically.

The extension's script is executed in a parallel environment and it cannot substitute methods, that manipulate CSS rules, and there is no other API for detecting such changes. Dark Reader simply watches for rules count of every style sheet, it shouldn't downgrade the performance if nothing changes. `requestAnimationFrame` ensures that if change happens, colors will be properly inverted immediately and there would be no white flash. It shouldn't do anything when the tab is hidden.

**Comment by DanielG** [comment]
On Tue, Feb 26, 2019 at 03:23:09PM +0000, Alexander Shutov wrote:

> There is a need to check for updates, because some sites, like new
> Reddit, change style sheets dynamically, usually using styled
> components library or a similar hipster approach. When the app state
> changes (e.g. you start writing a comment on Reddit) they update style
> sheets not by adding class names for changed elements (the most
> popular and simple approach), but by changing properties in CSS rules
> dynamically.

Yup that sounds like hipster JS devs alright...

> The extension's script is executed in a parallel environment and it
> cannot substitute methods, that manipulate CSS rules,

I'm not 100% sure what you mean here? Do you mean there is no way to
hijack the code (for example) reddit uses to insert the style elements
in the first place?

> and there is no other API for detecting such changes. 

A quick googling suggests that while there is no API specifically for
watching stylesheet changes there is one for watching DOM changes as a
whole. That sounds promising to me I'll have a quick look to see if
this can catch style sheet changes.

> Dark Reader simply watches for rules count of every style sheet, it
> shouldn't downgrade the performance if nothing changes.

I added some more debugging code to look into this and it looks like
on the Google homepage there are at 33 different stylesheets that get
continously polled. So while a couple of stylesheets getting polled on
every animation frame might not be a significant impact this obviously
doesn't scale with more stylesheet elements.

Am I right in asuming an "animation frame" will happen at screen
refresh rate, so at like 60Hz or what have you? So times 33 that's
like 2000 events per second :)

> `requestAnimationFrame` ensures that if change happens, colors will
> be properly inverted immediately and there would be no white flash.

Yeah, I figured as much and that is very much appreciated ;)

> It shouldn't do anything when the tab is hidden.

Indeed I can observe that the CPU load goes away when the tab is not
visible, so that part seems to be working as intended.

**Comment by DanielG** [comment]
[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) sounds like it could do what we want here. Instead of polling the stylesheet elements just call `MutationObserver.observe()` on them and that'll give you a callback whenever those DOM nodes are modified in any way (as far as I understand).

**Comment by alexanderby** [comment]
Yes, Dark Reader uses Mutation Observer too. There are different ways for modifying CSS. Modifying text of `style` element (`styleElement.textContent = '...'`) is detectable by Mutation Observer. Modifying CSS rules using `styleElement.sheet.insertRule('...')` can be observed by changing `insertRule` method, but the extension's script has no access to JS objects of page context, only DOM nodes.

I haven't measured the performance yet, but comparing numbers is a very primitive operation. But the CPU usage could grow, if something is changing on page and Dark Reader recreates inverted style copy. Maybe something like cursor blinking in VS Code, that [used CPU even when idle](https://github.com/Microsoft/vscode/issues/22900).

**Comment by wmertens** [comment]
perhaps the polling could be reduced in frequency? RAF can run at 30-60Hz, and style changes can perhaps instead be applied at 5Hz? With a gradual sleep mode that goes down to 0.5Hz or so when nothing changes for a long time?
