### ISSUE TITLE
[Broken Website] pcmag

### ISSUE THREAD

**Issue by bwc69151** [darkreader/darkreader#11260]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Comments text is black on black background.

### Website Address

https://www.pcmag.com/how-to/the-3g-shutdown-how-will-it-affect-your-phone

### Steps To Reproduce

Go to the site and scroll down to comments box.

### Operating System

Windows

### Web Browser name and version

Firefox 111.0.1

### Dark Reader version

4.9.62

**Comment by Amnesiac9** [comment]
Are you able to use dynamic mode? Looks fine on Dynamic. I'm not sure how to fix it with the static mode, as none of my attempts to edit the config seem to have an affect.

**Comment by bwc69151** [comment]
I found disabling and enabling dark mode fixes the issue. But very weird.
