### ISSUE TITLE
Cursor is not visible when dark reader is enabled

### ISSUE THREAD

**Issue by warriorwizard** [darkreader/darkreader#11268]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/darkreader/darkreader/assets/73724518/d4f4112b-b3a4-48b5-b153-848af5540f07)
when i disable dark mode cursor is visible 
but when i enable it the cursor disappear

![image](https://github.com/darkreader/darkreader/assets/73724518/2dc022bd-fead-4633-9bb6-32e97f9118e0)

### Website Address

www.kaggle.com or any other coding website

### Steps To Reproduce

open any coding site 
enable dark reader
your cursor will automatically get hidden

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/73724518/ae013c16-2e24-49ec-b425-3009379fa00b)

### Operating System

windows

### Web Browser name and version

chrome 104

### Dark Reader version

4.9.63

**Comment by Amnesiac9** [comment]
Not able to reproduce this. Have you tried on a different PC with a fresh install of darkreader?

**Comment by Amnesiac9** [comment]
Not able to reproduce this, are you able to test on another PC? Are you sure you have tried on a fresh browser and dark reader install?

**Comment by warriorwizard** [comment]
> Not able to reproduce this, are you able to test on another PC? Are you sure you have tried on a fresh browser and dark reader install?
> 
> Edit: Can you test this in an updated version of Chrome?

maybe the issue is with my chrome
i have removed the extension and again added, still the problem persists

i have move to microsoft edge and it works fine there
so i am switching there
thanks for trying out :)
