### ISSUE TITLE
[Broken Website] erettsegitetelek.com act weird

### ISSUE THREAD

**Issue by Hulayki** [darkreader/darkreader#11270]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When I open the web page, it "turns off" Dark Reader, but when I turn it off and on again, it works fine as it should.

### Website Address

https://erettsegitetelek.com/

### Steps To Reproduce

1. go to the site
3. you see for a millisecond that it's in dark mode, but then the page "reloads" and everything goes white

### Operating System

Windows 10

### Web Browser name and version

Chrome 112

### Dark Reader version

4.9.63

**Comment by Pavelikgr** [comment]
У меня тоже самое

**Comment by Hulayki** [comment]
Somehow fixed.
