### ISSUE TITLE
Document outbound connections

### ISSUE THREAD

**Issue by joshuaks** [darkreader/darkreader#1129]
Safari displays a warning that Dark Reader is able to read sensitive information. I've also noticed that Dark Reader makes outbound connections that I catch with Little Snitch.

As an open source project I'm not too concerned, but some documentation on what types of outbound connections and why those outbound connections are made would be really nice.

For now I have completely blocked outbound connections without ill-effect (yet) on the app itself and the Safari extension.

If I can provide any more information/context please let me know.

**Comment by drduh** [comment]
Extensions which have full DOM access should not be making undocumented network connections. Please fix it.

**Comment by Gusted** [comment]
Hi!

We make external requests to external images and style-sheets, unfortunate we need to make those requested to see what the content is and based on that make a darken color-scheme for it.

> Extensions which have full DOM access should not be making undocumented network connections. Please fix it.

Wrong assumption and in cases it should.

Regards,
Gusted
