### ISSUE TITLE
Extension stopped working on chrome on all websites

### ISSUE THREAD

**Issue by everdimension** [darkreader/darkreader#1131]
I'm not sure what happened, I think I updated chrome approximately a week ago (current version is `72.0.3626.119`) and the extension just doesn't work without any indication for why.

In the extension widget the toggle is changing from a cross to a tick, but no styles are applied to the page (and to any pages).

I though this was a temporary bug but more than a week passed and still no changes.

I tried:

* toggling the "invert listed only" / "not invert listed" state in the site list
* visiting a completely new random website
* toggling the extension on and off

Still doesn't work ¯\\_(ツ)_/¯ 

What do you think might be the problem?

**Comment by alexanderby** [comment]
Hi, open Dark Reader's dev tools, see what is displayed there, click Reset.

The latest version don't overwrite your Dev Tools changes, but for some users the extension doesn't work with broken config.

**Comment by everdimension** [comment]
@alexanderby Hey, this worked!

Thanks a lot for the quick response and for the awesome extension.
