### ISSUE TITLE
when i type in google translate the translation tab becomes white

### ISSUE THREAD

**Issue by Littery1** [darkreader/darkreader#11312]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

when i type on the google translator tab that shows translation becomes white but if i delete what i typed it is gray again.

### Website Address

https://translate.google.com/ 

### Steps To Reproduce

1. open https://translate.google.com/ 
2. type whatever

### Screenshots

[Screencast from 24-05-23 20:32:42.webm](https://github.com/darkreader/darkreader/assets/93970315/be06617d-0877-4930-abc0-b4e13c4a0449)

### Operating System

ubuntu

### Web Browser name and version

brave

### Dark Reader version

4.9.63

**Comment by MatinSasan** [comment]
Same here, broken on Google Translate, with:

OS: Windows 10
Browser: Chrome
DR version: 4.9.63

**Comment by vocalir145** [comment]
+
And yet, if you open the list of languages, it is also white

**Comment by SomeDude77** [comment]
Same issue here, with the list, and after you translate.

**Comment by SixelAlexiS90** [comment]
Same here on Chrome.

**Comment by Littery1** [comment]
By the way I just noticed that when you change the engine under the more option google translate works well then and even other sites that are broken works okay now. The default setting was dynamic.

**Comment by Gitoffthelawn** [comment]
Nobody has mentioned Firefox, so I tested it.  Same issue on Firefox 114.0.1.

Also, as noticeable in the OP's GIF, the background of the left `textarea`  and its encompassing `c-wiz` have almost no contrast with the page's background.  It will be good to have some contrast for the backgrounds.

**Comment by alexanderby** [comment]
Works okay for me.
