### ISSUE TITLE
[Broken Website] Broken CSS on pixiv.net

### ISSUE THREAD

**Issue by Proxymiity** [darkreader/darkreader#11310]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The website appears like its stylesheet isn't loading when Dark Reader is in use.

### Website Address

https://www.pixiv.net

### Steps To Reproduce

1. Login to Pixiv (via any sort of account)
2. Go to the homepage
3. See that the page doesn't load correctly, and feels like a CSS stylesheet isn't loading

### Screenshots

With Dark Reader enabled:
![](https://m.iya.at/6gbx4Stf.png)
With Dark Reader disabled:
![](https://m.iya.at/YsswkBs.png)

### Operating System

macOS Ventura 13.3.1 (a)

### Web Browser name and version

Firefox Nightly 115.0a1 2023-05-22

### Dark Reader version

4.9.63

**Comment by SuperTux88** [comment]
This looks like the same issue as in #11321 and https://bugzilla.mozilla.org/show_bug.cgi?id=1834786

**Comment by Proxymiity** [comment]
Indeed. This was fixed in https://hg.mozilla.org/mozilla-central/rev/47f0f49b4036.
