### ISSUE TITLE
[Broken Website] https://gizmodo.com/

### ISSUE THREAD

**Issue by GNOMES** [darkreader/darkreader#11317]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Loading Gizmodo with Dark Reader enabled causes everything to appear to be left justified. 

### Website Address

https://gizmodo.com/

### Steps To Reproduce

Access Gizmodo with Dark Reader on. Disabled and refresh to have Gizmodo load properly

### Screenshots

<img width="1675" alt="Screen Shot 2023-05-25 at 08 19 11" src="https://github.com/darkreader/darkreader/assets/7462046/1cc09837-cfa5-433c-b655-a1940ff4729a">

### Operating System

MacOS Monterey

### Web Browser name and version

Firefox Nightly 

### Dark Reader version

115.0a1 (2023-05-25) (64-bit)

### Additional Context

Dark Reader set to all default settings with the exception of "sync site fixes" + "detect dark theme"

**Comment by SuperTux88** [comment]
This looks like the same issue as in #11321 and https://bugzilla.mozilla.org/show_bug.cgi?id=1834786

**Comment by bershanskiy** [comment]
Looks like this was indeed [FF Nightly bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1834786), as mentioned above. Please ping me or create a new ticket if issue occurs again.
