### ISSUE TITLE
[Broken Website] Twitch.tv

### ISSUE THREAD

**Issue by Highlander214** [darkreader/darkreader#11315]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Twitch CSS loads improperly, when Dark Reader is disabled everything is back to normal. Has been happening at least 2-3 days.

### Website Address

www.twitch.tv

### Steps To Reproduce

1. Go to Twitch.tv with Dark Reader enabled
2. Observe how broken the CSS is

### Screenshots

With Dark Reader enabled:
![YiJos5nA3c](https://github.com/darkreader/darkreader/assets/74523631/142b1935-c224-4eff-a68c-6ce8c9c3c8c1)
Without Dark Reader enabled:
![E9pL8MCRCK](https://github.com/darkreader/darkreader/assets/74523631/b5d9cc45-eee6-4f5a-98a0-c1f97554870d)

### Operating System

Windows 10 Pro 22H2

### Web Browser name and version

Firefox Nightly 115.0a1

### Dark Reader version

4.9.63

**Comment by SuperTux88** [comment]
This looks like the same issue as in #11321 and https://bugzilla.mozilla.org/show_bug.cgi?id=1834786

**Comment by bershanskiy** [comment]
Looks like this was indeed [FF Nightly bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1834786), as mentioned above, Please ping me or create a new ticket if issue occurs again.
