### ISSUE TITLE
[Broken Website] DuckDuckGo is white-themed once again

### ISSUE THREAD

**Issue by ghostid234856** [darkreader/darkreader#11325]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I've seen a closed issue for this back in 2018, and I've opened a new one to mention this because it seems to have been closed and may not be fully relevant. No present/recent open or closed issue reports seem to be mentioning this, surprisingly

Basically all of the DuckDuckGo site + the search engine results, images, other tabs, etc, are broken again. They are white themed permanently. 

Hope yalls can help. This has been tested both on my main Firefox browser and Chrome as well.

### Website Address

https://duckduckgo.com/

### Steps To Reproduce

1) Install the newest release freshly on Firefox or Chrome
2) Open up DuckDuckGo or choose it as your main browsing engine
3) Google something

### Screenshots

Example screenshots:

![image](https://github.com/darkreader/darkreader/assets/130872428/ebea6ab3-d67a-4a13-8b39-d7390070406b)

![image](https://github.com/darkreader/darkreader/assets/130872428/d66aeabf-01a1-4d18-8aaa-6aa984f6ede0)

### Operating System

Linux - 

### Web Browser name and version

Linux - Parrot OS 5.3 (Electro Ara) x86_64 latest, kernel 6.1.0-1parrot1-amd64

### Dark Reader version

4.9.63 release

**Comment by dioxias** [comment]
same thing for me

**Comment by partingscientist** [comment]
This is caused by the website using the `darkreader-lock` meta tag, which is why I asked for a solution to override this in #11320.

**Comment by puelp** [comment]
@bershanskiy, is there no way for the user to override the 'darkreader-lock' function?

Because of 'darkreader-lock', sites essentially have the ability to lie to Dark Reader about dark-themed when they aren't.

That would be fine if the user had the ability to override 'darkreader-lock' and manually enable dark mode, but toggling the filters did nothing for me.

Am I missing something?

**Comment by alexconstant9108** [comment]
@fusionneur that'd be my guess as well. Tracking purposes. Right now, if you browse anonymously, you always get the white theme (because your dark theme preferences aren't saved between sessions)

**Comment by alexconstant9108** [comment]
> Am I missing something?
We need an additional option to override this flag as @partingscientist has mentioned above

**Comment by rongil** [comment]
I also agree it would be nice to have an override for the lock built into Dark Reader itself for cases like this one where the lock is being used despite the site not being dark-themed.

As a workaround in the meantime, if you're already using uBlock Origin, you can add `duckduckgo.com##^meta[name=darkreader-lock]` as a static filter to remove the attribute (same for any other site you want to override).

**Comment by rongil** [comment]
> > As a workaround in the meantime, if you're already using uBlock Origin, you can add `duckduckgo.com##^meta[name=darkreader-lock]` as a static filter to remove the attribute (same for any other site you want to override).
> 
> The meta tag does indeed get removed but Dark Reader doesn't seem to care about that fact. My guess is that it detected the meta tag being there before uBlockO removed it... Should I restart DR after loading DDG or...?

That's odd. I did not restart anything after adding the filter. In fact, just refreshing a previously loaded light-themed DDG search page after adding the filter caused it to become dark-themed. I'm not sure what determines the execution order between the extensions. Maybe try uninstalling and reinstalling DR if you happened to have installed it before uBO originally?

**Comment by alexconstant9108** [comment]
Nah, DR got installed much later than oBO. It's a weird issue indeed.

**Comment by yegg** [comment]
This is only a temporary bandaid until https://github.com/darkreader/darkreader/issues/11047 is fixed, which is slowing down all DuckDuckGo searches and was causing a massive amount of complaints. We offer a dark theme which is a temporary solution and you can force it using https://help.duckduckgo.com/duckduckgo-help-pages/settings/params/, e.g., https://duckduckgo.com/?q=test&kae=d&ia=web. In any case, we could use your help getting that other bug fixed and are open to any other suggestions.

**Comment by alexconstant9108** [comment]
Is anyone now experiencing a similar issue on GitHub where if GH's dark theme is enabled, DR doesn't apply its settings?

**Comment by partingscientist** [comment]
> This is only a temporary bandaid until #11047 is fixed. .... We offer a dark theme which is a temporary solution and you can force it using URL params ....

Thank you for the clarification. I would still advocate for a native solution to solve #11320, considering what Gabriel suggested is not fully supported in Firefox at the moment ([1195005](https://bugzil.la/1195005)).

**Comment by partingscientist** [comment]
Here's a proper workaround for Firefox users (works also for other browser, but Gabriel's method is probably preferred):

If you are using uBlock Origin:
1. Install the latest uBO development build from [GitHub](https://github.com/gorhill/uBlock/releases) (version 1.50.1b6 at the time of writing).
2. Add the following to the `My Filters` tab:
   `duckduckgo.com##+js(trusted-set-cookie, ae, d)`

If you are using AdGuard:
1. Add the following to the `User rules` tab:
   `duckduckgo.com#%#//scriptlet("trusted-set-cookie", "ae", "d")`

**Comment by Micovec** [comment]
I can confirm it's working.
