### ISSUE TITLE
[Feature Request] exporting and importing configurations

### ISSUE THREAD

**Issue by back-lacking** [darkreader/darkreader#11363]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

what it says in the title. i would like to see a feature where you are able to export your site lists, custom css, and site-specific settings into one file, and then on a new installation of the extension, you are able to easily import that file. see ublock origin as an example. 
maybe an "import/export configuration file" button under the more tab?

**Comment by bershanskiy** [comment]
Dark Reader already supports exporting and importing settings. To do this:
 - enable new UI: click on Dark Reader icon, then on "Dev tools" and a window will appear, in which you should click "Preview new design"
 - Export settings: click on Dark Reader icon, and then "Settings", then "Manage settings", and "Export settings" (or "Import settings")

**Comment by awsms** [comment]
> Dark Reader already supports exporting and importing settings. To do this:
> 
> * enable new UI: click on Dark Reader icon, then on "Dev tools" and a window will appear, in which you should click "Preview new design"
> * Export settings: click on Dark Reader icon, and then "Settings", then "Manage settings", and "Export settings" (or "Import settings")

This is a bit clunky, OP is specifically asking for an import/export configuration button. I don't think the average user would consider opening the dev tools to save their current settings

**Comment by jmcken1** [comment]
This is indeed extremely clunky. Especially considering it’s not at all [what the Dark Reader website says here](https://darkreader.org/tips/reset-settings/), with completely different menu layouts. Took me a long time before I found this thread and finally figured out where the import/export buttons are.
