### ISSUE TITLE
Light reader: force white mode

### ISSUE THREAD

**Issue by NeoHuncho** [darkreader/darkreader#11376]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Hey,

There's a feature that I would find useful: being able **to force light mode on website even if they have a dark mode activated**. I mainly work with my computer in dark mode hence why i use this plugin, but I also like to work outside and this feature would come in very handy.

Let me know what you think!

(if it not something that you would find useful, i'll branch out and build it on my own branch)

**Comment by NguyenASang** [comment]
This feature are already included. Simply click `Scheme` and choose `Light` or simply choose `Light` on old UI.

**Comment by lolouthefox** [comment]
Hi, I agree with @tautology0, I think this should be a feature. I prefer light mode and the "light" feature of dark reader is just not light theme at all. It's just grey.

**Comment by scamidge** [comment]
I too agree

**Comment by McBruno712** [comment]
I think this should be reopened.
