### ISSUE TITLE
ESPN.com breaks when you click a link

### ISSUE THREAD

**Issue by oxguy3** [darkreader/darkreader#1137]
ESPN.com looks absolutely fantastic in Dynamic mode; however, if you click a link within ESPN to go to another page, the styles will be a little bit broken on the next page. For example, start on the home page, and click a link to a gamecast in the scores scroller at the top, or vice-versa. This only occurs in Dynamic mode; I've switched to Filter+ and everything seems fine now.

**Comment by Gusted** [comment]
LGTM
