### ISSUE TITLE
Feature request: prevent some elements from being recolored

### ISSUE THREAD

**Issue by oxguy3** [darkreader/darkreader#1141]
There are a number of sites where certain elements need to retain their original colors no matter what, and need to be exempt from recoloring. I am primarily talking about sites that are actually about color, e.g. resources for graphic designers. Some examples:

* [ColorHexa](https://www.colorhexa.com/) (color encyclopedia)
* [BrandColors](https://brandcolors.net/) (listing of official brand colors)
* [materialuicolors](https://materialuicolors.co/) (color palette for Material Design)

This is a big problem because there's no workaround -- either you turn Dark Reader entirely off for those sites, or it makes those sites useless.

It'd be nice if there were a way to configure Dark Reader to avoid recoloring certain elements. For example, in the config file, there could be a new section (i.e. in addition to INVERT, CSS, etc) called PRESERVE. You could create a list of CSS selectors in that section, and Dark Reader would leave those elements alone.

**Comment by Gusted** [comment]
`IGNORE INLINE STYLE` is the section. Their are some examples already.
