### ISSUE TITLE
[Bug] Avoid using the keyboard short cut alt-shift-a 

### ISSUE THREAD

**Issue by soegaard** [darkreader/darkreader#11410]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

On a mac computer with a US keyboard layout the shortcut alt-shift-a is used to produce the letter Å. When Dark Reader is enabled, it is no longer possible to write Å. 

The letter Å is a commonly used wovel in Danish, so Danish developers with US keyboards will disable Dark Reader. 

Note that even though Dark Reader is not used on a page, it still eats the keystroke. The only way to get the original behaviour back is to remove Dark Reader from the extention list. Recommandation: Use a different shortcut.

This bug is on Chrome macOS. The bug can be seen on everywhere: Facebook, Google, etc. so is not related to a single web page [probably to the key event handler].

### Website Address

All

### Steps To Reproduce

1. Buy a mac with a US keyboard layout.
2. Choose the US kyeboard layout in the System settings [the default for a US computer].
3. Go to a random web-site and enter alt-shift-a.

### Expected Behavior

I expected to see an Å.

### Actual Behavior

If Dark Reader is enabled, Dark Reader is activated.

If the option that says something like "only use Dark Reader when explicit enabled"
then pressing alt-shift-a has no effect at all. It's like the keyboard event handler ate the event.

### Operating System

macOS Ventura 13.3.1 (22E261)

### Web Browser name and version

Google Chrome  114.0.5735.106 (Official Build) (x86_64)

### Dark Reader version

Sorry. I uninstalled it. I presume it was the latest.

**Comment by bershanskiy** [comment]
Hi @soegaard thanks for the report!

You can change the shortcuts and un-assign them in Google Chrome on `chrome://extensions/shortcuts` (just open the page, find the section corresponding to Dark Reader and click the "pencil" icon and hit `Esc` to leave the shortcut empty).

Please re-open the issue if this does not answer your question.
