### ISSUE TITLE
[Bug] Night mode automatically turns off on sites like Google

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#11430]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Night mode automatically turns off when I have the mode enabled: "enable night mode with system theme" on sites like google.com or Gmail. 
Here is the video: https://github.com/darkreader/darkreader/assets/137397457/5e929a72-71ba-42e3-823f-bc31fa60cb6a

### Website Address

https://www.google.com/  https://mail.google.com

### Steps To Reproduce

1) Enable night mode in the Windows system theme.
2) Enable night mode with system theme on Dark Reader
3) Visit https://www.google.com/ and https://mail.google.com

### Expected Behavior

Night mode should remain active

### Actual Behavior

Night mode turns itself off

### Operating System

Windows 11

### Web Browser name and version

Firefox 114.0.2

### Dark Reader version

4.9.63

**Comment by bershanskiy** [comment]
Hi, thanks for the report! The upcoming AMO release 4.9.64 will contain a fix (#11254).
