### ISSUE TITLE
[Broken Website] Cambridge Dictionary

### ISSUE THREAD

**Issue by web8823** [darkreader/darkreader#11452]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Turning on dark mode raises the issue.

### Website Address

https://dictionary.cambridge.org/

### Steps To Reproduce

1. enable dark mode
2. go to the website
3. the page breaks after 1-2 second.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/93432430/41d10444-3a83-4bb3-83bb-0077234b7b8b)

### Operating System

Windows 10 (22H2)

### Web Browser name and version

Micorsoft Edge. Version 114.0.1823.58 (Official build) (64-bit)

### Dark Reader version

Version 4.9.64

**Comment by stevensland** [comment]
Same issue with Chrome and Arc but not Firefox

**Comment by domeniczz** [comment]
I have tested on my Chrome browser

It brokes only in "Dynamic" mode, in other 3 modes, the website works fine.

In "Dynamic" mode, no matter what the Scheme is, no matter what other settings are, the website always brokes.

**Comment by AoSankaku** [comment]
Same on Vivaldi Browser

**Comment by TilJungbluth** [comment]
Same for Opera GX.
Can confirm, it only breaks with the 'Dynamic' theme engine / generation mode. 
(Tested to see if the different engines would change anything, and they did, as described, but I don't like the way the other modes look.)

And just for good measure, some screenshots:

![Cambridge Dictionary (working)](https://github.com/darkreader/darkreader/assets/46138958/31a9b27c-d040-4248-ba3b-db01c8409d2a)
*Cambridge Dictionary how it should look like.*

![Cambridge Dictionary (broken)](https://github.com/darkreader/darkreader/assets/46138958/1ee9fd32-ca6e-4aac-95d4-81218401457c)
*Cambridge Dictionary how it looks like when it's broken.*

**Comment by Slient1802** [comment]
same on coc coc browser

**Comment by stevenlis** [comment]
It appears that the issue has been resolved.
