### ISSUE TITLE
[Performance Issue] Dynamic mode fetches unused background images and slows down tildes.net

### ISSUE THREAD

**Issue by ivan** [darkreader/darkreader#11459]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

https://tildes.net/ includes the CSS at https://tildes.net/css/site-icons.css, which has 4678 `background-image: url(...)`s for site icons.

With Dark Reader disabled, only about 30 of these icons are fetched when loading https://tildes.net/.

With Dark Reader Dynamic mode enabled, all (?) of these site icons are fetched. This significantly slows down the page load, the entire browser, and can hang the Chrome DevTools Network tab.

This was previously reported in https://github.com/darkreader/darkreader/issues/1158#issuecomment-734732998.

### Website Address

https://tildes.net/

### Steps To Reproduce

1. Visit https://tildes.net/ in Chrome with Dark Reader Dynamic mode enabled.
2. Observe slow page load, browser hanging briefly, and DevTools Network tab either hanging or showing hundreds of requests for the background-images referenced in https://tildes.net/css/site-icons.css.

### Performance Profile

https://ludios.org/tmp/tildes.net%20load%20with%20dynamic%20mode%20Trace-20230629T202548.json.zst

### Operating System

Windows 10 22H2

### Web Browser name and version

Chrome 114.0.5735.199 (Official Build) (64-bit)

### Dark Reader version

4.9.64

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

Yes

### Additional Context

I selected "Yes" because Firefox also seems to be slowed down (at least for the first page load), but the extra requests don't show up in the Network tab. So I am not sure the misbehavior is identical to that in Chrome.

**Comment by alexanderby** [comment]
Should be fixed now.
