### ISSUE TITLE
[Broken Website] All globo.com websites

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#11462]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Images don't load, but videos do.

Two examples below.

**Dark Reader ENABLED**

`https://g1.globo.com/politica/noticia/2023/06/30/tse-condena-bolsonaro-e-o-declara-inelegivel.ghtml`
[Image 1](https://github.com/darkreader/darkreader/assets/30274161/1d72e2a6-c643-44fd-a4c6-9cd10530bccd)

`https://gshow.globo.com/noticia/mudancas-no-encontro-e-no-papo-de-segunda.ghtml`
[Image 2](https://github.com/darkreader/darkreader/assets/30274161/1701e7e1-1292-4048-998f-141170a32653)

**Dark Reader DISABLED**

[Image 3](https://github.com/darkreader/darkreader/assets/30274161/e3295e0b-01a4-49b1-8d5f-710991e1905a)

[Image 4](https://github.com/darkreader/darkreader/assets/30274161/458ba036-76e2-41d6-b310-ad274e6fce4e)

It is not necessary to reload the page — just toggling Dark Reader ON to OFF fixes the issue.
Strangely, the issue does not persist when re-enabling the extension on the same page (without refreshing).

### Website Address

N/A

### Steps To Reproduce

1. Go to the website(s).
2. See the issue.

### Screenshots

Attached above.

### Operating System

Windows 10 Pro 22H2

### Web Browser name and version

Firefox 114.0.2 (64-bit)

### Dark Reader version

4.9.64

**Comment by bershanskiy** [comment]
Thanks for the report, I confirmed the bug on 4.9.64 and also confirmed that #11461 fixes this bug. The next release, 4.9.65, will be released within a few days and will contain the fix.

**Comment by RogerioTDS** [comment]
The same problem is noticed using Linux.
Operating System: Arch Linux
Web browser name and version: 116.0.2
