### ISSUE TITLE
[Broken Website] Google Maps

### ISSUE THREAD

**Issue by DUOLabs333** [darkreader/darkreader#11473]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

If dark mode is enabled, only the side bar becomes dark --- the map itself remains light.

### Website Address

google.com/maps

### Steps To Reproduce

1. Go to provided address.

### Screenshots

<img width="1440" alt="Screen Shot 2023-07-03 at 12 17 18 PM" src="https://github.com/darkreader/darkreader/assets/49244768/da5b1d2c-7401-4546-9f40-edd89cf27cfb">

### Operating System

MacOS

### Web Browser name and version

Chrome 101

### Dark Reader version

4.9.64

**Comment by MexHigh** [comment]
Works for me when using the "Dynamic" style engine. Only doesn't work when using "static".

Version 4.9.65

**Comment by zyvy11** [comment]
it was warking for some time, but for the last few days its not working anymore , at least for brave browser(chrome)
