### ISSUE TITLE
Dark mode don't work on reddit.com/r/tifu 's theme.

### ISSUE THREAD

**Issue by Gillwindy** [darkreader/darkreader#1147]
Url:https://www.reddit.com/r/tifu/
All the setting seems not able to make the background go dark (at least for me)
with Dark Mode:
![1](https://user-images.githubusercontent.com/3596447/53806780-e44f1180-3f88-11e9-8409-4cb9e7410b88.PNG)

without Dark Mode:

![2](https://user-images.githubusercontent.com/3596447/53806946-490a6c00-3f89-11e9-9b4a-689bc5c48231.PNG)

**Comment by Gusted** [comment]
They don't don't set any Color for the elements so we can't style on them if they don't have a `color: ` style

**Comment by suraj1609** [comment]
Hey I am Suraj Kanse. I am willing to contribute your project.
Can you assign me to work on it?
