### ISSUE TITLE
Medium's menu popover is black on black

### ISSUE THREAD

**Issue by LaikaFusion** [darkreader/darkreader#1148]
![image](https://user-images.githubusercontent.com/7572049/53840800-1486b800-3f69-11e9-920b-605af28f0fcc.png)

Basically the text and the background are the same color. This is in dynamic mode. If you change any setting with the menu open it will switch to an easier to read color.

Version: 4.7.7

**Comment by jacky-ttt** [comment]
as a workaround, you can modify the "medium.com" section to 
```
medium.com

INVERT
.svgIcon
.svgIcon-use
.u-resetSpectrum a
```

**Comment by Gusted** [comment]
Fixed.
