### ISSUE TITLE
[Broken Website] Allegro.pl shipping/returns/payments/seller panels load infinitely

### ISSUE THREAD

**Issue by rateforx** [darkreader/darkreader#11494]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

With dark mode enabled the slide-out panels containing shipping/returns/payments/seller info never "stops loading".

### Website Address

https://allegro.pl/oferta/koszyk-box-1s-na-ogniwo-akumulator-18650-li-ion-13629221853#

### Steps To Reproduce

1. Open an offer of **any** item
2. Click on on of the links in the second panel in the right column
3. Observe the perpetual loading wonder!

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/24194569/5529ed1d-3664-4170-a529-16b51a80cce6)
![image](https://github.com/darkreader/darkreader/assets/24194569/e7fd871b-dffd-4be5-aeab-fdb137992ef0)

This is how it's supposed to look like:
![image](https://github.com/darkreader/darkreader/assets/24194569/93ec177e-14c8-4b89-a760-ccbc273fbd24)

### Operating System

Windows 11

### Web Browser name and version

Firefox Developer 116.0b2 (64-bit)

### Dark Reader version

4.9.64

**Comment by PsychePone** [comment]
Same problem here

**Comment by KubaZ** [comment]
This problem is caused by `document.styleSheets` API override by darkreader extension.

With darkreader **disabled**, this code logs all styleSheets loaded onto the page correctly:
```js
for (const sheet of document.styleSheets) {
  console.log(sheet)
}
```
With darkreader **enabled** , it returns undefined.

**Comment by qarmin** [comment]
Cannot reproduce with latest version

**Comment by rateforx** [comment]
Seems to work fine right now.
