### ISSUE TITLE
[Broken Website] Canvas Grades

### ISSUE THREAD

**Issue by Menghini** [darkreader/darkreader#11503]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When using Canvas (instructure.com), I cannot load my Gradebook.

### Website Address

instructure.com

### Steps To Reproduce

Please note that you have to ben instructor in a class to see the grades page. When you go to the grades page (as shown in the video) it will start to load and then disappear before loading the entire thing. Note that this only happens on "Dynamic" mode for Dark Reader, and the page loads on the other types of modes.

### Screenshots

Video showcasing the Grades page loading and then disappearing https://photos.app.goo.gl/nbeD5izC5yA4qoNj9
Photo showcasing what the page is supposed to look like without dark reader (students names censored) https://photos.app.goo.gl/gkQ1tz3f6tr1T9Vm6

### Operating System

Windows and Mac

### Web Browser name and version

Brave and Chrome

### Dark Reader version

4.9.64

**Comment by larrydewey** [comment]
I can verify this behavior occurs, as well.
