### ISSUE TITLE
https://www.epicgames.com Account and Help section

### ISSUE THREAD

**Issue by xNxExOx** [darkreader/darkreader#1152]
![image](https://user-images.githubusercontent.com/1893229/53973007-3a929080-4100-11e9-929e-e6ae3c493388.png)
Can not be turned on https://www.epicgames.com/site/en-US/customer-service and https://www.epicgames.com/account/* because "page is in list of pages with dark motive", Store part for example have dark background and most of screen are bright pictures, but ok these are pictures, but these two sections (and subsections) are completely white, why there is no override option to turn it on on these pages?
Thanks for good work that is great on most white pages :)

**Comment by Gusted** [comment]
Resolved.
