### ISSUE TITLE
[Bug Report] Dynamic theme doesn't work on https://technews.tw/

### ISSUE THREAD

**Issue by spxt4928** [darkreader/darkreader#1154]
Extension version: 4.7.7
Browser version: Chrome 72.0.3626.121 (Official Build) (64-bit)
Operating system: Windows 7
Description:
When opening the webpages on https://technews.tw/, I can see that dark background applies to the webpages in a flash and suddenly disappears. Finally the webpages would look like this:
![technews1](https://user-images.githubusercontent.com/24370957/54003061-d1f0f580-418b-11e9-8167-924ac83ca613.PNG)
or
![technews2](https://user-images.githubusercontent.com/24370957/54003074-da493080-418b-11e9-8e71-d8d113712952.PNG)
But the webpages on https://ccc.technews.tw/ seem to work fine. 
![technews3](https://user-images.githubusercontent.com/24370957/54003101-f2b94b00-418b-11e9-98c7-ca4c34ced32f.PNG)
How come it would act this way?

**Comment by Gusted** [comment]
Should be fixed.
