### ISSUE TITLE
Reddit banner on top is white until you disable/re-enable dark reader

### ISSUE THREAD

**Issue by SomeDude77** [darkreader/darkreader#11583]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

As the title says, for about a week now the Reddit section on top of the site is white on first site load, until you disable dark reader and re-enable it. Sometimes though it is not white on first load.

### Website Address

reddit.com

### Steps To Reproduce

1. Load reddit.com
2. disable dark reader and re-enable to fix every time

### Operating System

Windows 11

### Web Browser name and version

Firefox  116.02

### Dark Reader version

4.9.6.4

**Comment by enzor00** [comment]
I have the same problem

**Comment by privacyguy123** [comment]
Still seeing this problem to this day - any update? @Gusted

**Comment by enzor00** [comment]
It is annoying to have to disable and reactivate the night mode. I hope a resolution will come soon @Gusted @alexanderby

**Comment by privacyguy123** [comment]
Sometimes happen and sometimes doesn't - not sure how to recreate exactly.

**Comment by Mennaruuk** [comment]
![Screenshot](https://github.com/darkreader/darkreader/assets/52135169/2b0d1f6f-3a66-4943-a04b-920fddc7a9ed)

**Comment by oeloo** [comment]
I can confirm I also have this issue, it is really annoying as it makes the dark mode from DarkReader not usable on Reddit:
![image](https://github.com/darkreader/darkreader/assets/98819304/094ac774-9cb1-40cc-a120-0e23dcc5dd1f)

And I really recommend to anyone to use DarkReader add for Reddit.com as it can automatically switch between light/dark mode according to Windows OS being in light or dark mode.

**Comment by privacyguy123** [comment]
No eyes on this? :/

**Comment by oeloo** [comment]
Could you fix it following your daily?

**Comment by jrouzies-fr** [comment]
Same issue here since a while, definitely looking forward for a fix

**Comment by oeloo** [comment]
Thank you to the team behind Dark Reader. I confirm it has been fixed.

**Comment by alexanderby** [comment]
Thanks @oeloo but the fix haven't been released yet.
