### ISSUE TITLE
[Broken Website] xavd.id is unreadable w/ Darkreader

### ISSUE THREAD

**Issue by xavdid** [darkreader/darkreader#11604]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I've gotten a few reports (https://github.com/xavdid/website/issues/154) that my personal website is hard to read when darkreader is installed. I tested in a fresh browser profile and can confirm.

My site already respects `prefers-color-scheme`, so I think we can safely disable the extension on my site. I can send a PR to `dark-sites.config` if you'd like.

Alternatively, is there any HTML I can put on my site that will clue Dark Reader into the fact that it doesn't work on the site? I'm happy to do that as well.

### Website Address

https://xavd.id

### Steps To Reproduce

1. Visit my website with the extension enabled
2. it looks bad

### Screenshots

broken:

<img width="826" alt="Screen Shot 2023-08-14 at 11 22 14 PM" src="https://github.com/darkreader/darkreader/assets/1231935/7a2c6991-145f-49d1-a35d-488382de1486">

normal:

<img width="814" alt="Screen Shot 2023-08-14 at 11 25 21 PM" src="https://github.com/darkreader/darkreader/assets/1231935/79eda6cc-df16-4aeb-b0f2-969ed725aaee">

### Operating System

macOS

### Web Browser name and version

Firefox 116.0.2 (64-bit)

### Dark Reader version

4.9.65

### Additional Context

It looks like the extension is taking a nearly-transparent SVG background and making the color much brighter.

**Comment by CoolSpy3** [comment]
[You can disable Dark Reader on your site by adding `<meta name="darkreader-lock">` to your html.](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#disabling-dark-reader-on-your-site). Hope this helps :D

**Comment by xavdid** [comment]
perfect, thanks!
