### ISSUE TITLE
[Performance] Export dynamic analyzed theme and as a static one

### ISSUE THREAD

**Issue by DoCode** [darkreader/darkreader#1161]
It would be very nice for some minor performance issues on heavyweight sites, like Jira, Confluence, etc. that we can export an already rendered, analyzed dynamic theme and used this as a static one.
Would this be possible?

**Comment by piotrbukalski** [comment]
I would love that possibility as well. Put an edit button next to dynamic theme button (sth similar to static edit). Then put "save as static" button and done! I know we can find them in dev tools and export them but it's too much to do.

**Comment by dotiful** [comment]
it would be great,  I'm also lacking this

**Comment by joshwand** [comment]
see also #604

**Comment by Gusted** [comment]
#3120  :tada:
