### ISSUE TITLE
Can't delete links from ninth one

### ISSUE THREAD

**Issue by PavanLuca** [darkreader/darkreader#11626]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Now that I want to remove my ninth link on **Don't invert only** list it never saves once I delete it. Also, I noticed that `Don't invert only` list is limited to only 9 links and now that I have 9 links I can't delete or add nothing now.

### Website Address

discord.com

### Steps To Reproduce

1. place 9 links on a list
2. delete the ninth
3. change selection, press esc, press Enter or anything else

### Expected Behavior

The extension should have removed the ninth link.

### Actual Behavior

Everything I do doesn't make Dark Reader remove the link.

### Screenshots

![Schermata da 2023-08-20 22-04-22](https://github.com/darkreader/darkreader/assets/123581658/55002a1f-65c8-4756-aeb6-32cb398d4e4f)

### Operating System

Zorin OS Core

### Web Browser name and version

Firefox 116.0 (64 bit) for Ubuntu canonical - 1.0

### Dark Reader version

4.9.65

**Comment by romiljain5** [comment]
This issue is not valid, As it keeps one box empty by default for having at least on text input box if all are deleted

**Comment by PavanLuca** [comment]
That's not the problem, when I remove or add a link now that I have 9 links there the changes aren't saved. Did you try adding 9 links and then deleting or adding 1?

**Comment by romiljain5** [comment]
Yes, I did tried adding 9th link, We just need to add it and click outside input box, it will auto save

**Comment by PavanLuca** [comment]
If it works for you and everyone else it's weird that only I have this problem, I tried both clicking outside the extension window and pressing Enter key but the ninth link is never saved. If it's not a problem of the extension despite it looks a saving failure it may be a browser issue, I'm using the version from ubuntu-focal-updates-main so I can report this bug to Launchpad if no one can reproduce it.

**Comment by andrewalexander** [comment]
I cannot delete links at all from either list in Firefox. This is the closest issue I've found describing my problem. 
I go to a website i previously added to the do not invert list, and the toggle button does not work to re-enable dark mode for that website. I go to the list and delete multiple entries - but none persist. There is no save button that I can see. When I click out of the extension to close the drop down, I see no change. I open it back up and see the entries I deleted still where they were before.

**Comment by PavanLuca** [comment]
Did you reach the ninth entry like me to have this problem?

**Comment by andrewalexander** [comment]
I have far more than 9 entries, so perhaps it is related.

**Comment by PavanLuca** [comment]
Then it's weird, I'm really unable to edit that list anymore. Now I'm thinking that's as I said, a problem of the updates of my Firefox version, because in fact since when I updated the browser recently I have another extension that it's keeping its data but not applying it, it's a nodes blocker and despite it shows that nodes are saved to block them at next page load it doesn't really block these nodes saved on its list. I opened the same page but the nodes don't get blocked. The difference with Dark Reader is that the dark theme is applied, I can't edit the list in any way.

**Comment by Slackwise** [comment]
There's a related bug I found while researching a fix:  #11615

My own site list is uneditable from the site list UI. I need to visit the site to turn it on/off.

But that same bug report offers a solution: **enable the new UI design**, which has a new site list UI, and that works.

Hope this helps for now, and maybe this issue should be merged into that issue as well.

**Comment by GonziHere** [comment]
Yeah, I can confirm that I've found this bug by being unable to delete lines, and that the new design has fixed it. The new design acts slightly differently, so maybe a somewhat broken interface happened.

**Comment by PavanLuca** [comment]
Yes, I tried and looks working fine now, thanks.
