### ISSUE TITLE
 [Bug] dark reader not show interface in safari 17 (macOS14)

### ISSUE THREAD

**Issue by h3lp404** [darkreader/darkreader#11672]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

macOS update beta14, dark reader isn't work and not interface in safari .

### Website Address

anywhere

### Steps To Reproduce

update macOS 14 beta5

open safari and click dark reader icon, isn't show interface 

### Expected Behavior

fix it ,please lol

### Actual Behavior

i don't use it in macOS14 safari 

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/112472696/33f516e3-6f60-4a69-a706-7fed8c6c103e)

### Operating System

macOS14

### Web Browser name and version

safari 17

### Dark Reader version

1.4.6

**Comment by EraserCN** [comment]
Same issue here

**Comment by Nosgoroth** [comment]
Same issue here. Tried reinstalling the app too, but it didn't help.

**Comment by OEverything** [comment]
Same issue here, it worked in previous betas but not recently, even in final release.

**Comment by gwcali** [comment]
Same issue on MacOS 14 RC2. Let's see tomorrow after the public release of MacOS.

**Comment by Coding4Coffee** [comment]
Same issue with public release of Sonoma (MacOS 14), making the extension unusable, as unable to disable on sites that currently causing issues. e.g virustotal.com

**Comment by mulpre13** [comment]
<img width="239" alt="image" src="https://github.com/darkreader/darkreader/assets/17809959/38df4bd8-c9d7-4b72-b390-b8154bb8bf71">
Same here, with macOS 14.0 / Safari 17.0(19616.1.27.211.1)

**Comment by alexanderby** [comment]
Thanks for reporting this. There will be an update shortly. Unfortunately your settings will be gone, but the new features will appear.

**Comment by alexanderby** [comment]
The update should be available starting from today. If you have any issues during the migration, please see some notes [here](https://darkreader.org/safari/).

**Comment by rafenden** [comment]
Is there a way to export settings?

**Comment by hypnosu** [comment]
Latest version feels laggy and slow compared to previous version.
