### ISSUE TITLE
banweb.pdx.edu Tab corners not colored right

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#1172]
Proposed code change to the tab (corners), that have a higher priority over the dynamic/static theming on the [banweb.pdx.edu](banweb.pdx.edu)

```
.tabon, .taboff {
    background-image: url("data:image/gif;base64,R0lGODlhCAAUAIABABcYHP///yH5BAEKAAEALAAAAAAIABQAAAIchI8Ykcu6YDzumSpt1fh2sHnd9pCiA5oks6ZbAQA7");
}

img[src="/wtlgifs/web_tab_corner_right.gif"] {
    content: url("data:image/gif;base64,R0lGODlhCAAUAIABABcYHP///yH5BAEKAAEALAAAAAAIABQAAAIdhG8RmMq6EIzNnSlh1tWCSYGX+JFgdHbaubClWAAAOw==");
}
```

**Comment by Richienb** [comment]
@TheAlienDrew Please add those changes to a file found [here](https://github.com/darkreader/darkreader#fixing-wrong-inversion).

**Comment by TheAlienDrew** [comment]
Not that simple @Richienb ... the fix doesn't work in the file, and it changes and image, not inverts it (if it inverts, the color will invert the entire element including the words and tabs, which is not what needs to be done). Trying to apply my fix in the "Dev Tools" doesn't work too, because the dynamic theme is overriding it.

**Comment by Gusted** [comment]
Already fixed.
