### ISSUE TITLE
[Broken Website] Allegro.pl 'my purchases' page

### ISSUE THREAD

**Issue by PatrykKuniczak** [darkreader/darkreader#11739]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

As you can see on the screen shot, text have wrong contrast to background.

### Website Address

https://allegro.pl/moje-allegro/zakupy/kupione

### Steps To Reproduce

1. Open page
2. Watch out, watch out *JOHN CENA* :)

### Screenshots

![Zrzut ekranu 2023-09-26 174742](https://github.com/darkreader/darkreader/assets/64608510/7f61d082-f528-4f60-be86-c4c95a10da02)

### Operating System

Windows 11

### Web Browser name and version

Google Chrome 117.0.5938.92

### Dark Reader version

4.9.65

**Comment by Jckpt** [comment]
It appears that the issue has been resolved
![image](https://github.com/darkreader/darkreader/assets/64931967/48044cf2-0387-4c68-98fa-2922aae374fc)

**Comment by PatrykKuniczak** [comment]
@Jckpt Yeah, works perfect :)
