### ISSUE TITLE
[Broken Website] https://www.elle.com/

### ISSUE THREAD

**Issue by xfq** [darkreader/darkreader#11747]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The ELLE logo is unclear.

### Website Address

https://www.elle.com/

### Steps To Reproduce

Go to https://www.elle.com/ with any DR settings unchanged.

### Screenshots

<img width="998" alt="elle" src="https://github.com/darkreader/darkreader/assets/2863444/0546c8ac-5bfc-41ea-98b3-069f8c093189">

### Operating System

macOS 12.6.9

### Web Browser name and version

Chrome 117 and Firefox 117

### Dark Reader version

4.9.65

**Comment by SAMURAii-7** [comment]
Seems like the ELLE logo remains dark only in the homepage, it is inverted on all other pages

**Comment by xfq** [comment]
Thank you for working on this!

**Comment by SAMURAii-7** [comment]
It was my pleasure! Also thank you because this was my first contribution in open-source 😄
