### ISSUE TITLE
[Broken Website] Volt Kandidatenlijst Tweede Kamer 2023

### ISSUE THREAD

**Issue by ericwj** [darkreader/darkreader#11744]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Absolutely everything turns purple from a certain width of the browser window onwards.

### Website Address

https://voltnederland.org/mensen/kandidatenlijst-tweede-kamer-2023

### Steps To Reproduce

1. Go to the page on a desktop machine (I used Windows 11 and Edge)
2. Try Windows+Left. It'll do the trick if the desktop monitor is narrow enough.
3. Try making the window wider. It'll do the trick long before the browser window is as wide as the full screen.

### Screenshots

Too wide
<img width="1920" alt="image" src="https://github.com/darkreader/darkreader/assets/9473119/06a93456-24ef-4d89-b72c-f56e1f5ef60f">

Small enough
<img width="1920" alt="image" src="https://github.com/darkreader/darkreader/assets/9473119/9afcc52b-5cca-4637-ac52-9be60fed07d4">

### Operating System

Windows 11 22H2 build 22621.2283

### Web Browser name and version

Edge 117.0.2045.41

### Dark Reader version

Dark Reader 4.9.66

### Additional Context

Don't read the text in the issue on the screenshot. I mixed it up ;)

**Comment by CodingArctic** [comment]
Looks like there's a breakpoint around ~1000px. I'll see if I can figure out what's changing to cause this and submit a PR.
