### ISSUE TITLE
[Broken Website] amazon images bug

### ISSUE THREAD

**Issue by ComfortableMilk4454** [darkreader/darkreader#11743]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

some images on amazon are darkened and glitched (see screenshot)

### Website Address

amazon.com

### Steps To Reproduce

go to amazon.com

### Screenshots

<img width="382" alt="Screenshot 2023-09-27 at 9 18 25 AM" src="https://github.com/darkreader/darkreader/assets/43555540/ca012ecc-486a-4a87-812d-34dc7fe2557f">

### Operating System

macos sonoma 14.0 (23A344)

### Web Browser name and version

chrome Version 117.0.5938.92 (Official Build) (arm64)

### Dark Reader version

4.9.65

**Comment by AIDaN80112** [comment]
bump

**Comment by AIDaN80112** [comment]
another bump. also happens on firefox.

**Comment by sek0n** [comment]
I've been having the same thing for a long time, and decided to look into it now. Saw a similar issue: #12087 

This was added to dynamic-theme-fixes.config in the amazon section:
```
img {
    mix-blend-mode: unset !important;
}
```

Then some time later, replaced with:
```
[class*="image-display"] {
    mix-blend-mode: unset !important;
}
```

I made a quick stylus style with the first one, and it fixes them for me.
