### ISSUE TITLE
[Feature Request] Support "Run on sites with restrictions" setting for Firefox extensions

### ISSUE THREAD

**Issue by notDavid** [darkreader/darkreader#11767]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Hi there,

would it be possible for Dark Reader to enable the new settings "Run on sites with restrictions", so it can work on websites like mozilla.org, etc. ?

(i see this setting for other Extensions, but not for Dark Reader.)

Thank you!

### Screenshots

![Screenshot_2023-10-01_at_07_44_23](https://github.com/darkreader/darkreader/assets/1530401/538587d9-7c8d-47d4-b31c-dd28f1388b83)

**Comment by sr66139p** [comment]
I second this. Not only will it prevent us from being flash-banged by Mozilla websites, but we'll be able to invert PDFs as well. This is the only reason I have to use a dedicated PDF app
![Screenshot from 2024-01-02 11-57-43](https://github.com/darkreader/darkreader/assets/144626133/2a5dc542-fdd7-416c-8392-daa374ae3e53)

**Comment by StormyIceLeopard** [comment]
Why has this still not been implemented yet?

**Comment by sr66139p** [comment]
I found two different pages from Mozilla, with different solutions, about how to disable this feature globally: https://mzl.la/3q5rMAW & https://mzl.la/3POXoWi. Unfortunately, I can't seem to find anything on how to add the setting to an extension from the developers side. I know some extensions have the option, but I haven't been able to figure out how they do it. `restricted_domains` is mentioned under ExtensionSettings in [Mozilla Policy Templates](https://mozilla.github.io/policy-templates/), but it's not entirely clear how one would implement it in their code. We might have better luck just trying to get Mozilla to add dark mode support to their websites

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
