### ISSUE TITLE
[Bug] Hotkey/Shortcut for "Toggle current website" is not working

### ISSUE THREAD

**Issue by Master2386** [darkreader/darkreader#11780]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Since the Update to Dark Reader 2.0.0 the Hotkey for "Toggle current website" ist not working anymore.

### Website Address

not related to a specific website

### Steps To Reproduce

- Set a Hotkey/Shortcut in the Settings of Dark Reader.
- Test the Hotkey/Shortcut

### Expected Behavior

If you press the Shortcut it should activate / disable Dark Reader for the current Website.

### Actual Behavior

Nothing happens.

### Operating System

macOS Venture 13.6

### Web Browser name and version

Safari 17.0

### Dark Reader version

2.0.0

### Additional Context

I tried different Shortcuts to prevent duplicate Shortcuts.
If i use my Shortcut for the "Toggle the Extension" it works perfectly fine.
But "Toggle current Website" is not doing anything at all.

**Comment by mapleroyal** [comment]
Can confirm this is happening on Safari, but not on firefox in macOS.

For me (in Safari obviously) neither hotkey will work, whether it's enabling/disabling the extension globally or just for the current website.

I'm on Ventura stable and up to date.

**Comment by OEverything** [comment]
Can confirm is happening for Safari in macOS Sonoma. Toggle current website hotkey doesn't work, but toggle extension hotkey works.

**Comment by mapleroyal** [comment]
> Can confirm is happening for Safari in macOS Sonoma. Toggle current website hotkey doesn't work, but toggle extension hotkey works.

What toggle extension shortcut are you guys using? Neither is working for me and I've tried setting several various shortcuts for either of them.

**Comment by OEverything** [comment]
I use Command+Shift+U for Toggle Extension, and Command+Control+U for Toggle Website. Same as I used a few weeks ago when both were working fine.
