### ISSUE TITLE
[Bug] ctrl shift T replaces default browser behavior

### ISSUE THREAD

**Issue by valn1** [darkreader/darkreader#11791]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

when i do ctrl + shift + T to reopen the last closed webpage, this addon opens the developer tools instead
i don't need a shortcut for something i can access in 2 clicks and will never use 

### Website Address

--

### Steps To Reproduce

do ctrl+shift+t

### Expected Behavior

reopen the last page

### Actual Behavior

opens a useless menu

### Operating System

linux

### Web Browser name and version

firefox nightly

### Dark Reader version

4.9.67

**Comment by mimuki** [comment]
`ctrl+shift+t` is working as expected for me, reopening the last closed tab just like it always has. that's on same dark reader version as you, with linux mint & non-nightly firefox, for the record.

it might be worth testing on your machine if it still happens to you in regular firefox?
