### ISSUE TITLE
Tends to forget settings.

### ISSUE THREAD

**Issue by ice-ivanov** [darkreader/darkreader#1183]
Hello darkreader devs.
The issue I'm experiencing in both FF and Chrome is that often I toggle darkreader off for a certain website or even globally, should I switch tabs, it returns to the previous option. So in other words, it ignores the exception list. And what's worse, that option appears as off although in actuality it's on (the website is still on the list). So I have to switch it on and back off again... just to find that it does the same thing again when I switch tabs.
As much as I like this extension, it is very unreliable and unstable. Please do something about it.

**Comment by Gusted** [comment]
Should be fixed
