### ISSUE TITLE
[Broken Website] GamersNexus.net article

### ISSUE THREAD

**Issue by ThibaultVlacich** [darkreader/darkreader#11889]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Top banner of GamersNexus.net articles is not showing

### Website Address

https://gamersnexus.net/news/valve-announces-steam-deck-oled-deck-2-works

### Steps To Reproduce

1. Open the link

### Screenshots

With Dark Reader enabled:
![Screenshot 2023-11-09 at 20-05-36 Valve Announces Steam Deck OLED Deck 2 in the Works GamersNexus](https://github.com/darkreader/darkreader/assets/334940/696296fd-8c47-4d8c-838d-3ca1f50a9493)

With Dark Reader disabled:
![Screenshot 2023-11-09 at 20-05-44 Valve Announces Steam Deck OLED Deck 2 in the Works GamersNexus](https://github.com/darkreader/darkreader/assets/334940/50710140-627d-41c6-b5eb-7139853fb481)

### Operating System

Windows 11

### Web Browser name and version

Firefox 119.0.1

### Dark Reader version

4.9.67

**Comment by Myshor** [comment]
Site added to global dark list. Closing issue.
