### ISSUE TITLE
[Broken Website] Slack Error code: STATUS_ACCESS_VIOLATION Caused by Dark Reader

### ISSUE THREAD

**Issue by MSBlueVn** [darkreader/darkreader#11908]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Recently, on app.slack.com, I get the error from the title.
I also got it from another website, but I do not remember which right now.
When I exclude Slack from Dark Reader, it loads correctly.

### Website Address

app.slack.com

### Steps To Reproduce

1. try to reach the website
2. get the error in the title
3. exclude the website and reload
4. the website loads correctly

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/100758741/817f329c-e8a9-41ad-a573-2b97cd800401)

### Operating System

Windows 11

### Web Browser name and version

Brave 1.60.114

### Dark Reader version

4.9.67

**Comment by MSBlueVn** [comment]
This is fixed on static.

**Comment by TheOptimisticFactory** [comment]
> This is fixed on static.

Opening a Slack huddle in full causes the crash despite having manually disabled the dark mode for Slack's website entirely.
The page shows `about:blank` in the URL bar.

I had to either completely disable the extension or disable the dark mode globally to avoid the page crash.

**Comment by MSBlueVn** [comment]
This is probably due to the fact the url is different. Try setting it to static, then go into a huddle and do a specific setting for that url.

On November 15, 2023 11:11:18 AM GMT+02:00, Romain GAGNAIRE ***@***.***> wrote:
>> This is fixed on static.
>
>Opening a Slack huddle in full causes the crash despite having manually disabled the dark mode for Slack's website entirely.
>The page shows `about:blank` in the URL bar.
>
>I had to either completely disable the extension or disable the dark mode globally to avoid the page crash.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/darkreader/darkreader/issues/11908#issuecomment-1812065166
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
--
NOTICE: This email and all attachments are confidential and may contain 
information that is privileged, confidential, or exempt from disclosure 
under law. If you are not the intended recipient, delete this message and 
notify the sender immediately. Any unauthorized use is strictly prohibited.

**Comment by TheOptimisticFactory** [comment]
@MSBlueVn I think it would be wise to include `Slack` in the title of this issue in order to avoid potential duplicates from being created

**Comment by ChinnoDog** [comment]
I had this problem today when trying to re-authorize my desktop Slack client for my company. Desktop app sends me to auth page for company Slack but tab immediately crashes. Works fine after disabling Dark Reader on that page. Win10, Chrome  119.0.6045.160, Dark Reader 4.9.68.

**Comment by MSBlueVn** [comment]
> Works fine after disabling Dark Reader on that page

As I mentioned, moving it to static also works.

**Comment by jbjhjm** [comment]
Confirming the issue on DR 4.9.70, Chrome 119.0.6045.160, Win 10.
Disabling dark reader for slack fixed the STATUS_ACCESS_VIOLATION for me, too.
Possibly the fault is on Chrome's side, I experienced multiple issues with current Chrome builds over last 2-3 weeks.

**Comment by packyg** [comment]
Slack crashes for me too, but with a different error - just `Error code: 11`

![image](https://github.com/darkreader/darkreader/assets/58449272/1e9d5068-c451-418a-86d7-438f32ca7d7c)


> This is fixed on static.
I'm not sure what this even means - I suppose it's referring to the theme generation mode?
Regardless of what the setting is, one ideally shouldn't have to fiddle with settings site-by-site to make them not crash

**Comment by MSBlueVn** [comment]
> I suppose it's referring to the theme generation mode?
Yes, instead of dynamic.

> one ideally shouldn't have to fiddle
You are correct, but this is a temp fix until this bug is solved.

**Comment by packyg** [comment]
> but this is a temp fix until this bug is solved.
👍🏻 Disabling for Slack also works, which I might recommend over this - it looks better to just use a Slack theme that's dark than the static Dark Reader theme

**Comment by TheOptimisticFactory** [comment]
If someone is trying to replicate the bug, it seems important to state that:
- the crash **`does not`** occur on the landing page of Slack (https://slack.com/) -- where one can select a workspace
- the crash occurs once connected to a workspace (https://app.slack.com/client/EXAMPLE)

**Comment by jpool-cf** [comment]
I tried setting to static for about:blank, but the extension won't let me select 'Theme for about:' in the dropdown?

I'm still having issues after disabling for slack.com, app.slack.com, about:, and about:blank

<img width="166" alt="image" src="https://github.com/darkreader/darkreader/assets/42589856/da0c3680-0808-40d6-9427-51a34eafc6a7">

**Comment by devSajan** [comment]
yes slack is crashing for me on brave browser, mostly when someone calls on huddle

**Comment by Akivas** [comment]
> yes slack is crashing for me on brave browser, mostly when someone calls on huddle

Same here, when in a huddle call if I switch tab or windows the Huddle pops up and the crash occurs.
It's the same if I use any link from slack's bots that pops up an authentification window.

**Comment by alexanderby** [comment]
It is a Chrome browser issue. I made a [fix](https://github.com/darkreader/darkreader/commit/1cc8018eefa732ba34800e177f04669d210ba8af) and will publish it next week.

**Comment by MSBlueVn** [comment]
can confirm this works on 71.

**Comment by TheOptimisticFactory** [comment]
@MSBlueVn @alexanderby This issue can be marked as resolved since fix has been published
