### ISSUE TITLE
[Feature Request] add new font for accessibility: OpenDyslexic

### ISSUE THREAD

**Issue by phpmoli** [darkreader/darkreader#11919]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

I tried to type in a custom font name into the font face combobox, but it seems that it is not a combobox, but a select box with fixed options.

If this is not true, please advise me in a reply comment, how to do that.

If this is true, then can you please add the font OpenDyslexic to the extension? It is an accessibility font for people with dyslexia. https://en.wikipedia.org/wiki/OpenDyslexic

It would help a lot. Thank you for considering.

**Comment by Rescue9** [comment]
It appears the only font included with Dark Reader is OpenSans (and variants). I believe the fonts in the dropdown are pulled from the fonts installed on your OS. I have some barcode fonts installed for work that are definitely not typical and those show up when I select the dropdown. Try installing OpenDyslexic inside your OS and you should be able to select it from the dropdown.

**Comment by phpmoli** [comment]
I had the font installed months before installing darkreader.

I also have other custom fonts manually installed, like: Hack, IntelOne Mono, Noto Emoji, Noto Sans, Noto Sans Mono, Noto Serif, none of these are listed in the select box.

**Comment by alexanderby** [comment]
@phpmoli What browser do you use? If Firefox, you will have to type the font name manually.

**Comment by phpmoli** [comment]
Yes, Firefox. Oh, there's no autocomplete, my bad, closing ticket, thanks for your time, sorry.

**Comment by alexanderby** [comment]
Unfortunately the API for retrieving the installed fonts is missing in Firefox.

**Comment by anarchopossum** [comment]
An New updates for this request?

**Comment by alexanderby** [comment]
@anarchopossum If you are using Firefox, you will have to type-in the font name manually.
