### ISSUE TITLE
YouTube's Own Dark Mode Needs Fix

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#1192]
YouTube has the option to turn on the sites' internal dark mode. Turning this on, Dark Reader screws it up. There needs to be a way for Dark Reader to "sense" the YouTube dark mode being on, before applying the Dark Reader changes (or having special changes for when it is in dark mode; e.g. fixing the like and save button colors when clicked)

Additionally, on pages that aren't dark themed, the YouTube logo needs the black text change (on the SVG's), or a full replacement of the image (for PNG's, color white to black for "YouTube").

**Comment by PsiPhiTheta** [comment]
Surely, users that have dark mode for youtube enabled should just toggle dark reader off for that site? 

An automatic detection seems like overkill, especially a site-specific detector...

**Comment by TheAlienDrew** [comment]
> Surely, users that have dark mode for youtube enabled should just toggle dark reader off for that site?
> 
> An automatic detection seems like overkill, especially a site-specific detector...

Well my reason being is, when the theme applies to YouTube when I am using YouTube's dark theme, some coloring don't work the same like the "Like" "Share" buttons when clicking them (colors don't change right).

**Comment by Abragus** [comment]
> > Surely, users that have dark mode for youtube enabled should just toggle dark reader off for that site?
> > An automatic detection seems like overkill, especially a site-specific detector...
> 
> Well my reason being is, when the theme applies to YouTube when I am using YouTube's dark theme, some coloring don't work the same like the "Like" "Share" buttons when clicking them (colors don't change right).

That issue happens with Youtube's light mode too, in my experience. I've tried finding the wrongly colored elements and fixing them, but I really am no pro when it comes to this stuff, so I couldn't solve the problem. 

However, as @PsiPhiTheta said, if it was a dark mode-only problem, the easiest solution would just be to use light mode.

**Comment by Gusted** [comment]
Fixed.
