### ISSUE TITLE
[Bug] Filter+ only inverts images in Firefox 120

### ISSUE THREAD

**Issue by KyodaiKen** [darkreader/darkreader#11930]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [ ] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

When opening any website in Firefox 120 using Filter+, the website stays as is, except the images are inverted.

### Website Address

regenwetter.org, dhl.de, ...

### Steps To Reproduce

1. Open website
2. Make sure Filter+ is enabled
3. Find out only images are inverted

### Expected Behavior

The websites are dark as it was before in Filter+ mode

### Actual Behavior

When opening any website in Firefox 120 using Filter+, the website stays as is, except the images are inverted.

### Screenshots

Filter+
![image](https://github.com/darkreader/darkreader/assets/32415256/68ca5ea3-175c-4000-af35-80a9a96aa243)

Filter
![image](https://github.com/darkreader/darkreader/assets/32415256/840616d3-cb6a-4eab-acdc-bd59787a4d92)

### Operating System

Manjaro Linux x86_64, Kernel: 6.6.1-1-MANJARO

### Web Browser name and version

Firefox 120

### Dark Reader version

4.9.68

**Comment by SunnyMoo** [comment]
I can confirm the filter+ mode is broken FF 120 + DR 4.9.68.

**Comment by Maruzeru** [comment]
I can confirm this is the case for me as well. Newest stable version FF.

**Comment by ptyork** [comment]
Issue remains as of now. FF 121.0 + DR 4.9.73. Windows 11 latest.

**Comment by KyodaiKen** [comment]
The issue has been fixed in DR Version 4.9.76!
