### ISSUE TITLE
[Bug] Dark reader causes websites to not load or freeze.

### ISSUE THREAD

**Issue by plundration** [darkreader/darkreader#11943]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Running on Fedora 39. Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

Using troubleshoot mode in firefox I have found out, that even simply having only dark reader enabled causes this problem. The problem, more precisely, is that opening websites such as [discord.com/app](https://discord.com/app) or others with presumeably a lot of javascript (also happens with slack, [alza.sk](https://alza.sk/), ...) causes them to either freeze after a while/immediately or just not load (circular loading symbol visible on gray background in the tab).

I have tried a clean install of firefox with dark reader, clearing caches, downgrading dark reader, but it didn't help. Only disabling dark reader helps for some reason.

After posting to the r/firefox sub-reddit, I have found another person with the same problem, however my friend on another PC using Fedora isn't able to reproduce the problem.

### Website Address

https://alza.sk

### Steps To Reproduce

1. Install firefox
2. Install Dark Reader extension
3. Go to [alza.sk](https://alza.sk) or [discord.com/app](https://discord.com/app)
4. Lag, freezing, etc

### Expected Behavior

Websites loading and functioning normally

### Actual Behavior

Some websites lagging, other freezing, crashing or not loading at all.

### Operating System

Fedora 39

### Web Browser name and version

Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

### Dark Reader version

4.9.68

**Comment by corngoblin** [comment]
I'm also having this issue.. took me a bit to figure out it was dark reader.
Disabling it fixes the issues instantly. I'm also on fedora 39.

I was getting this issue with amazon, https://shopgoodwill.com/  and ebay would also some times just freeze.

**Comment by arturquant** [comment]
The same here. Tested on two laptops with Fedora 38. After upgrade firefox to version 120.0 addon constantly keep freezing browser on multiple pages like:  [gmail](https://gmail.com), [discord](https://discordapp.com),  [aliexpress](https://aliexpress.com) and more. With dark reader extension disabled everything works like a charm, but eyes hurts... ;(
I'm switching myself to use chromium until issue has been solved.

**Comment by pkorba** [comment]
Could be duplicate of #11834

**Comment by nicolaasjan** [comment]
Experiencing the same here.
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0`

But it happened also on previous Firefox versions, though not as frequent.
Strange thing is, that I've not seen it on Firefox Developer and Nightly.

Indeed seems a duplicate of #11834.

**Comment by plundration** [comment]
Since it seems that downgrading dark reader doesn't help. Could it be writing some bad data to some cache that it then has problems with later on?

**Comment by gehuskic** [comment]
I am on Fedora 39, and I am also having this issue. For now I have the extension completely disabled so I can actually use my web browser as intended.

**Comment by JohnVeness** [comment]
I've been seeing the same, but only since upgrading Firefox from 119 to 120 (openSUSE Tumbleweed). Happens on Google Maps, and interestingly also on the seemingly simple Firefox release notes (https://www.mozilla.org/en-US/firefox/120.0/releasenotes/), for me.

**Comment by magicgoose** [comment]
> Since it seems that downgrading dark reader doesn't help. Could it be writing some bad data to some cache that it then has problems with later on?

Anyone knows for sure where it is stored? Surely not inside the xpi file?

**Comment by CBx86** [comment]
Same, and i report high use in some threads. 🤔

**Comment by scarlion1** [comment]
Seems everyone here is on Linux (Debian 12/13 for me), FF 120, and everyone who mention hardware is on laptops?  Me too, mine is literally ancient from 2012 and i swear at it more each day, but it has Intel i5-3210M integrated graphics and things like dark reader will eat up the cycles while content is loading... but I've been using it fine for years now.  I have a newer laptop been meaning to transition to but no time and it's been collecting dust instead :( 

Anyway, I had Webrender enabled in about:config and have reset those back to default, and also turned on Firefox Settings > General > Performance > Use recommended performance settings.  That didn't help here...

This is a grave bug, though, that is happening on a number of seemingly random sites, rendering Firefox useless.  Closing the affected tab doesn't help, and I need to check `about:performance` to kill the tab, or sometimes need to check `top` and `kill` the PID for the `Isolated Web Co` process using all the CPU.

Midnight Lizard add-on provides similar function for most sites and is somewhat of a workaround, but it doesn't work as good as Dark Reader on many sites and hasn't been updated in years.  Will be checking out other alternatives in the mean time.

If anyone out there knows any debugging steps we could take to help get this fixed ASAP, let us know.

Best,
Scar

**Comment by magicgoose** [comment]
> Seems everyone here is on Linux (Debian 12/13 for me), FF 120, and everyone who mention hardware is on laptops?

I'm on desktop (amd cpu and gpu)

**Comment by plundration** [comment]
I have experienced what everbody else here is saying too. Including having to manually kill the bugged process which was using 100% capacity.

**Comment by fakhraldin** [comment]
I can confirm that issue. Before i could leave dark reader to "dynamic" mode and i worked for all websites i use. Now i have to change the method to filter, filter+ and static on a case by case basis. The affected websites are google and wikipedia and many others.
Fedora Linux 39
Firefox 120.0
Dark Reader 4.9.68

**Comment by magicgoose** [comment]
There are also some websites (Discord) which break the browser no matter what, as long as DR is installed (and not disabled in browser settings). So, even if DR doesn't use dynamic mode, or if DR is disabled for this site in DR UI. (luckily this is even rarer)

**Comment by juliangrubio** [comment]
Same for me, fedora 39, Firefox 120, a web for example: https://developer.android.com. But i can say there's a lot of pages that is happen with this error.

**Comment by FooSoft** [comment]
Same problem as everyone else on Fedora 39. Tried resetting the browser problem still persists. Does not happen with perfect consistency on any given sites, but I have seen it trigger repeatedly on Amazon. Firefox gets pinned at 100% CPU usage and remains running after all of the tabs are closed.

**Comment by nicolaasjan** [comment]
Quoting @yjugl in the duplicate issue #11834:

> Based on the profiles, this issue has most likely the same root cause as: https://bugzilla.redhat.com/show_bug.cgi?id=2251202
> 
> Which will be fixed by: https://bugzilla.mozilla.org/show_bug.cgi?id=1866409

**Comment by globalexport** [comment]
I do not think this is soley a problem with Fedora. 
I am having the same issue on MacOS v13.4 (Ventura) with a Chrome-Browser on complex Statamic CMS pages.

**Comment by matthewstreeter** [comment]
Same issue for me trying to access the Slack admin portal with the extension enabled completely or at least enabled for the site. Fixed when disabling for the site or completely.

**Comment by crimsonfall** [comment]
Can confirm that the same issue occurs on Firefox 120 (RPM) in Fedora 39 when Dark Mode is enabled. Although interestingly, on macOS Ventura using the same Firefox version, the bug doesn't appear to occur and websites function just fine. I agree with the others above that this might be a Linux related issue.

**Comment by magicgoose** [comment]
Fedora (39) just rolled out an update to Firefox, I'm no longer seeing the problem with it so far :crossed_fingers:

**Comment by corngoblin** [comment]
> Fedora (39) just rolled out an update to Firefox, I'm no longer seeing the problem with it so far 🤞

This update seems to have fixed the issue for me so far.

**Comment by plundration** [comment]
I can confirm, that the newest update to firefox has solved this. I am closing this issue.

**Comment by darioseidl** [comment]
The [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1866409) says it will be fixed in 121.0b5 and 120.0.1, if I read that correctly.
It's still happening for me on Debian Sid with firefox 120.0-2 (but that's to be expected, that doesn't include the fix yet). So I think we'll just have to wait a bit until 120.0.1 or 121.0 are released.

**Comment by scarlion1** [comment]
@darioseidl Debian Maintainers dropped version 120.0.1-1 some hours ago.  So far so good, I went all over the place in google maps with Dark Reader enabled in Dynamic Mode...

**Comment by kanunnikau** [comment]
Unfortunately, for me the bug is still present :(
Firefox 120.0-5.1 on OpenSuse Tumbleweed, DarkReader 4.9.70.
I could even reproduce the issue as easily as:
- open browser,
- have previously opened tab with Wikipedia home page auto load and freeze.

Then I noticed that I have some package installed "MozillaFirefox-branding-openSUSE" with version 68-18.3. I switched from that to "MozillaFirefox-branding-upstream" (same version as FF itself, 120.0-5.1) — and Wikipedia started working with DarkReader.
Yet some sites (like Confluence) still freeze :(

**Comment by Gitoffthelawn** [comment]
An alternative may be to use Firefox ESR: https://www.mozilla.org/firefox/enterprise/

**Comment by kbkozlev** [comment]
I have the same issue, on Windows 11 and running edge

**Comment by TLengert** [comment]
Did some testing and this is an issue with "Dynamic" mode. Using Filter, Filter+, or Static does not cause extremely long load times on some sites. Switching to Dynamic, I can replicate this issue all day long.

**Comment by Gitoffthelawn** [comment]
If this bug is re-opened, these 2 links may be helpful to those investigating:

runtime.onPerformanceWarning - Mozilla | MDN
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onPerformanceWarning

1861445 - Add new hang warning event API for WebExtensions
https://bugzilla.mozilla.org/show_bug.cgi?id=1861445

**Comment by bigplayer-ai** [comment]
I have the same problem on safari macOS dark reader.

**Comment by Rafael-Ramblas** [comment]
Same issue here
Brave Version 1.70.123 Chromium: 129.0.6668.89 (Official Build)  (64-bit)
PopOs 22.04

**Comment by Gitoffthelawn** [comment]
Would it be best to reopen this issue?

**Comment by chamele0n1c** [comment]
Same issue here, took over a year to notice it was directly causes by Dark Reader. Running Firefox Stable Release 133.0 (64-bit) on Windows 11 Pro 23H2. I've disabled Dark Reader & now YouTube doesn't randomly hang/freeze nor do other websites.

**Comment by Gitoffthelawn** [comment]
@alexanderby Can you reopen this issue?

**Comment by PirateLemon** [comment]
This problem seems to still occur (134.0.2 (64-bit). Would it be possible to open the issue again? Thanks @alexanderby

**Comment by alexanderby** [comment]
If you have steps to reproduce the problem, you can report a new issue with the details provided.

**Comment by Gitoffthelawn** [comment]
@PirateLemon If you report a new issue strongly related to this issue, please add this issue as a reference to make it easier to connect the dots.  To do so, you can simply type "Related: #11943" (or "Possible Related: #11943", if you prefer) in the text for that new issue.
