### ISSUE TITLE
[Bug] Dark Reader Keyboard Shortcuts Don't Work

### ISSUE THREAD

**Issue by Arduinoz-R-Awsome** [darkreader/darkreader#11958]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Dark Reader ignores any hotkey that I set. (But it didn't in the previous version.)

### Website Address

Any

### Steps To Reproduce

1 Navigate to Settings --> Hotkeys
2 Set `Ctrl+Alt+Command+K` (Toggle the extension)
3 Set `Command+Shift+K` (Toggle current website)
4 Go to any website and press these keys
5 Nothing happenes

### Expected Behavior

I submitted the hotkey `CMD + SHIFT + K` to toggle the current website, and `CMD + ALT + SHIFT + K` to toggle the extension. These should toggle the extension and current website.

### Actual Behavior

Dark Reader ignores any keyboard shortcuts that I submit within the extension.

### Operating System

macOS Monterey Version 12.7

### Web Browser name and version

Safari Version 17.0 (17616.1.27.111.22, 17616)

### Dark Reader version

2.0.3

### Additional Context

This bug doesn't happen in chromium-based Brave Browser

**Comment by w-marco** [comment]
I am experiencing this issue as well using macOS 14.1.1 with Safari 17.1 and the newest extension version.

**Comment by bigplayer-ai** [comment]
I am experiencing the same issue as well.

**Comment by Arduinoz-R-Awsome** [comment]
UPDATE: I can't set the shortcut to `CMD + .` because the extension window closes when I press it when trying to set the shortcut. However, `CMD + J` works fine. SOLUTION: Update to Safari 17.2
