### ISSUE TITLE
建议搞一个可以设置晚上黑色，白天为明亮色

### ISSUE THREAD

**Issue by funsgang** [darkreader/darkreader#1197]
建议搞一个可以设置某一个时间段为黑色，另一个时间段为明亮色
It is recommended to set one to set a certain time period to black and the other time period to be bright.

**Comment by cvcore** [comment]
What OS are you using? On macOS this can already be done by keeping the Dark Reader switch to 'automatic', then DR can recognise the system design on its own. I'm currently trying to figure out how one can do this on Windows, though.

**Comment by p2635** [comment]
Thanks @cvcore , it wasn't very obvious to me as a new user but now I know :)

**Comment by Gusted** [comment]
Question was answered
