### ISSUE TITLE
[Broken Website] en.m.wikipedia.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#11972]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

There are no arrows to expand/collapse the sections.

### Website Address

https://en.m.wikipedia.org/wiki/France

### Steps To Reproduce

Go to https://en.m.wikipedia.org/wiki/France.
See no arrows in sections.

### Screenshots

Without Dark Reader:
https://i.imgur.com/8PVuuaM.png

With Dark Reader:
https://i.imgur.com/EdBXOIa.png

### Operating System

Windows 10 and Android

### Web Browser name and version

Firefox 120.0.1

### Dark Reader version

4.9.70

### Additional Context

Does not happen in Wikipedia's desktop website.

**Comment by alexanderby** [comment]
Should be fixed in v4.9.73, please check.
