### ISSUE TITLE
Guitar tableture on tabs.ultimate-guitar.com is not readable

### ISSUE THREAD

**Issue by FlameHorizon** [darkreader/darkreader#1199]
Examples:
![image](https://user-images.githubusercontent.com/23423558/54872595-a34b5f80-4dc6-11e9-9bd7-da4d2905745b.png)

![image](https://user-images.githubusercontent.com/23423558/54872598-b1997b80-4dc6-11e9-8523-8d48a828c9b5.png)

Link to the tableture: https://tabs.ultimate-guitar.com/tab/in_flames/we_will_remember_official_2630913

**Comment by Gusted** [comment]
Seems fixed.
