### ISSUE TITLE
[Bug] Dark Reader breaks MS Teams chat in Firefox

### ISSUE THREAD

**Issue by nicolamori** [darkreader/darkreader#11994]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

The extension prevents the chat panel of MS Teams to load properly in Firefox. The chat list loads fine, but then clicking on  a chat no messages are shown in the chat panel. Disabling the extension for the Teams website and reloading the page fixes the problem.

The same kind of problem (a UI component not showing up) happens on one of the web sites of my company, but I can't provide info about this since it happens in the restricted access area. Anyway I mention this to stress the fact that it's not just a matter of the MS Teams site.

### Website Address

https://teams.microsoft.com/

### Steps To Reproduce

1. Log in with your MS account
2. Click on the Chat icon on the left sidebar
3. Click on one of the chats on the left panel

### Expected Behavior

The messages of the selected chats should appear in the central panel

### Actual Behavior

No message is shown.

### Screenshots

![Screenshot_20231209_174844](https://github.com/darkreader/darkreader/assets/59166070/247ba73f-3e04-4fa4-bccc-be026ba8ea5e)
![Screenshot_20231209_174935](https://github.com/darkreader/darkreader/assets/59166070/781f5626-dc16-43af-abc1-da0e2d15e28a)

### Operating System

ArchLinux

### Web Browser name and version

Firefox 120.0.1

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
Reproduce will take some time.
Using Windows and Firefox ended with information that firefox is not supported.
As I have Manjaro installed on my other computer I will take a look what will happen there.

**Comment by Myshor** [comment]
First question:
Is it typo error or you really use Dark Reader 4.0.73 when the 4.9.73 is available? ;)

Second question:
How did you managed to run MS Teams in Firefox? Do you use some extension to change Agent string or something?
Even on Linux I ended with page that browser is unsupported and they recommend to download Chrome or Edge.

**Comment by nicolamori** [comment]
Sorry, as you guessed it's a typo: I'm using 4.9.73, I've corrected the first post.

I use Teams in Firefox with no issue, even in a private window with all the extensions disabled so no agent switcher under the hood. Furthermore, I tried with a brand new Firefox user with all the extensions disabled; the only thing I had to to is to consent the usage of cookies.

**Comment by Myshor** [comment]
I always end on https://teams.live.com/_#/unsupportedBrowser

Maybe someone else will reproduce this.

**Comment by chhajedji** [comment]
I have the same issue, but for me even the theme change does not work. It is simply nothing with any display settings.

**Comment by nicolamori** [comment]
@Myshor probably you need to setup Firefox as explained here:

https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop

**Comment by GlowingScrewdriver** [comment]
If I'm not wrong, MS Teams has a dark theme available. I use that on my Firefox with Dark Reader disabled.
You can enable it from [Settings] > [General] > [Theme]

**Comment by nicolamori** [comment]
@GlowingScrewdriver Nice catch, thank you. Nevertheless, DarkReader is breaking something in Teams and other web applications (see my first post), so even if it's very difficult to debug it's something that should be fixed at some point.

**Comment by MoskitoHero** [comment]
The provided fix does not take into account teams hosted at https://teams.microsoft.com (office365). The [PR above](https://github.com/darkreader/darkreader/pull/14260) should fix the situation.

**Comment by Myshor** [comment]
Small change which I can accept and merge. 😉
