### ISSUE TITLE
Is there a way to port this to iOS?

### ISSUE THREAD

**Issue by whatthehomepod** [darkreader/darkreader#1200]
Safari has support to enable extensions from third-party. It would be awesome if this is going to be ported to iOS. Anyways, thank you for this, keep up the good work!

**Comment by kfur** [comment]
@whatthehomepod you can use [https://itunes.apple.com/us/app/safari-snippets/id1126048257?mt=8](https://itunes.apple.com/us/app/safari-snippets/id1126048257) app for injecting `darkreader.js` manually

**Comment by whatthehomepod** [comment]
But there is no way to automate this for example with the content blocker?

**Comment by kfur** [comment]
@whatthehomepod  unfortunately no

**Comment by Gusted** [comment]
https://darkreader.org/safari/

**Comment by echiu64** [comment]
> @whatthehomepod you can use https://itunes.apple.com/us/app/safari-snippets/id1126048257 app for injecting `darkreader.js` manually

Do you have an example of this that would work on all websites?

**Comment by echiu64** [comment]
I figured this out (sort of using a gist from @kfur )
a) found your gist: https://gist.github.com/kfur/266c456dd69072eb7533f457ee5f18a0
b) downloaded to iPhone
c) open in files
d) share -> copy
e) create new snippet in Safari snippets, paste in code

(b)(c)(d) optional, but much faster to copy/paste a large amount of code into snippets
Optionally between (a) and (b), send it through a minifier

Works great so far!

**Comment by Gusted** [comment]
> I figured this out (sort of using a gist from @kfur )
> a) found your gist: https://gist.github.com/kfur/266c456dd69072eb7533f457ee5f18a0
> b) downloaded to iPhone
> c) open in files
> d) share -> copy
> e) create new snippet in Safari snippets, paste in code
> 
> (b)(c)(d) optional, but much faster to copy/paste a large amount of code into snippets
> Optionally between (a) and (b), send it through a minifier
> 
> Works great so far!

I personally think an userscript like https://github.com/darkreader/darkreader/issues/926#issuecomment-575893299 would be better due to having the `@require` which will be automatically updated to the latest version.

**Comment by tmpm697** [comment]
Is there a way to automatically load darkreader.js from Snippets for all sites?
