### ISSUE TITLE
[Firefox] Facebook chat window not fixed to bottom of window when in filter and filter+ mode

### ISSUE THREAD

**Issue by ccldd** [darkreader/darkreader#1201]
In firefox, the chat windows seems to be on the bottom of the page instead of being fixed to the bottom of the window. So when you open a chat message, facebook scrolls down to the very bottom. Since facebook implements infinite scrolling, chat is unusable. Static and dynamic seems to work fine aside from artifacts in the chat window.

In chrome, it works correctly.

**Comment by rgamici** [comment]
I also have this issue on firefox.
And there is also a problem that the whole page scroll together, when using filter or filter+.

**Comment by alexanderby** [comment]
The FB design has changed a lot since then. Please reopen if there's still an issue.
