### ISSUE TITLE
[Bug] Background cannot be shown properly when scrolling the website

### ISSUE THREAD

**Issue by Ptilopsis01** [darkreader/darkreader#12040]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

![image](https://github.com/darkreader/darkreader/assets/93318731/d1ea5b68-af71-4150-b4bc-4c2c942bce4d)
![image](https://github.com/darkreader/darkreader/assets/93318731/50b68681-6b8b-4a84-8fc4-5ad3880f9b7a)
The background was shown unproperly when scrolling the page down outside the original area. This also happens to some pages with pictures as background.

### Website Address

https://blog.csdn.net/fantasy_ARM9/article/details/128540612

### Steps To Reproduce

As shown above

### Expected Behavior

The background can be shown properly when dark mode is on.

### Actual Behavior

As shown above

### Operating System

Windows 11 22631.2861

### Web Browser name and version

Edge 120.0.2210.77

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
Pushed site fix.

To check the fix you need to have "Synchronize site fixes" option enabled, which is available in new design Settings => Manage Settings.
![289312788-39791691-bf5f-49f8-b35a-a8fbf2c891d4](https://github.com/darkreader/darkreader/assets/56877029/06669528-91e4-46be-8fb3-728bc0b72487)

To swich design you need to open Developer Tools and click the button to switch to new design.
![289312754-259ffb9b-9688-431d-850d-82596828b62d](https://github.com/darkreader/darkreader/assets/56877029/892a420a-9d97-40e1-b8dc-b23e9f56a1f3)

**Comment by Ptilopsis01** [comment]
> Pushed site fix.
> 
> To check the fix you need to have "Synchronize site fixes" option enabled, which is available in new design Settings => Manage Settings. ![289312788-39791691-bf5f-49f8-b35a-a8fbf2c891d4](https://private-user-images.githubusercontent.com/56877029/289669762-06669528-91e4-46be-8fb3-728bc0b72487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDM2OTMsIm5iZiI6MTcwMzA0MzM5MywicGF0aCI6Ii81Njg3NzAyOS8yODk2Njk3NjItMDY2Njk1MjgtOTFlNC00NmJlLThmYjMtNzI4YmMwYjcyNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAzMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYjU4MjU3ZTAzODhlOTFkNjE0MzVmMjk3YzRmYWZjMjBhZGE1ZTBjZTU2Y2M3YTJlYjM5ZjM2ZmE1NWZiYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._REx-EAQEYbYugdOgM9m1u5zTQBZ05ROGgp3np9Evfc)
> 
> To swich design you need to open Developer Tools and click the button to switch to new design. ![289312754-259ffb9b-9688-431d-850d-82596828b62d](https://private-user-images.githubusercontent.com/56877029/289669798-892a420a-9d97-40e1-b8dc-b23e9f56a1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDM2OTMsIm5iZiI6MTcwMzA0MzM5MywicGF0aCI6Ii81Njg3NzAyOS8yODk2Njk3OTgtODkyYTQyMGEtOWQ5Ny00MGUxLWI4ZGMtYjIzZTlmNTZhMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAzMzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZTY3YTg4OWViMWFiZTdhMDQ5M2FkYzA0NTZiNzkwY2E3MjhjNzY0MjUxMGQxYWE1MTYxY2IwMmI1MzkxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wyBd0c7YYlxnrWupgdu7N3-yNISHNahskZsC8A-5j0)

Thanks! By the way, I think it might be a common problem for some pages, for I've also met similar situation in another website. Though I can not tell you the URL, which is a personal forum, I guess it's the same problem with this one after checking the css.

**Comment by Myshor** [comment]
You can always add "alias" sites URL under the one that I fixed.
On the other hand I saw similar background in some other fixes in last few days where back-ground image was totally set to none as it makes site lighter than darker.

I just want to tell that if you would add your own fixes into Dark Reader developer tools and apply them then it can end with:
1) your applied fixes will be used as long as you reset them in developer tools (no new fixes will be synced) - at least it was working like that when I was not Member of Dark Reader but Contributor only. Now I don't use own applied fixes as I can merge them as soon as I fix something.
2) Your fixes will dissapear after new fixes update.

Still I can not confirm how it works right now 'cause like I mentioned I don't leave appled fixes in local Dark Reader too long. 😉

**Comment by Ptilopsis01** [comment]
> You can always add "alias" sites URL under the one that I fixed. On the other hand I saw similar background in some other fixes in last few days where back-ground image was totally set to none as it makes site lighter than darker.
> 
> I just want to tell that if you would add your own fixes into Dark Reader developer tools and apply them then it can end with:
> 
> 1. your applied fixes will be used as long as you reset them in developer tools (no new fixes will be synced) - at least it was working like that when I was not Member of Dark Reader but Contributor only. Now I don't use own applied fixes as I can merge them as soon as I fix something.
> 2. Your fixes will dissapear after new fixes update.
> 
> Still I can not confirm how it works right now 'cause like I mentioned I don't leave appled fixes in local Dark Reader too long. 😉

Got it. Thanks a lot.
