### ISSUE TITLE
[Broken Website] Action.com display black page on all pages

### ISSUE THREAD

**Issue by oeloo** [darkreader/darkreader#12047]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Hi, the website Action.com is display complete black page on every pages.

### Website Address

https://www.action.com/

### Steps To Reproduce

Just open this website https://www.action.com/

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/98819304/9f56e9a0-787c-43ec-8e70-97b35582b279)

### Operating System

Windows 11

### Web Browser name and version

Chrome (fully up to date)

### Dark Reader version

v4.9.73

**Comment by Myshor** [comment]
Fix is pushed. 😉

If you want to check the fix you need to use new desing and have "Synchronize site fixes" checked in Settings=>Manage settings:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/0aab43f2-c2ad-416e-bd20-180f32649b93)

To switch to new design open "Developer Tools" ("Narzędzia" in polish translation). There is button to switch design:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/87af477e-eb25-4c5d-b3d3-6d991eeb2553)

**Comment by oeloo** [comment]
I have just tested, the dark mode works great now. Thank you

**Comment by oeloo** [comment]
The dark mode is causing an issue: when you click on 'Produit' on the navigation bar: the navigation does not display.
When in day mode everything is Ok, the navigation menu for Produit is being displayed.

![image](https://github.com/darkreader/darkreader/assets/98819304/7613edc0-6aa0-49b3-9486-9220c95d084c)

**Comment by Myshor** [comment]
It will be other fix in a minute. 😉
