### ISSUE TITLE
[Broken Website] white subheadings on dev.to

### ISSUE THREAD

**Issue by sabirovrinat85** [darkreader/darkreader#12050]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

subheadings on dev.to got reversed to  white while using Light mode + Sepia

### Website Address

https://dev.to/izackv/running-a-docker-container-with-a-custom-non-root-user-syncing-host-and-container-permissions-26mb

### Steps To Reproduce

Open an article on dev.to
Switch Dark Reader on
Use Light mode, Sepia +65

### Operating System

Archlinux

### Web Browser name and version

Firefox 120.0.1

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
OK... I found the issue... there was some CSS color set for that element in sitefixes but someone didn't check how it will look ok light mode and not included that it should be different in that mode. I'll push the fix in the minute. 😉

**Comment by Myshor** [comment]
If you want to check the fix you need to use new desing and have "Synchronize site fixes" checked in Settings=>Manage settings:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/0aab43f2-c2ad-416e-bd20-180f32649b93)

To switch to new design open "Developer Tools" ("Narzędzia" in polish translation). There is button to switch design:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/87af477e-eb25-4c5d-b3d3-6d991eeb2553)
