### ISSUE TITLE
[Broken Website] GitHub.com - Markdown Code Blocks In Repositories does not scale correctly

### ISSUE THREAD

**Issue by Kreyren** [darkreader/darkreader#12062]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/darkreader/darkreader/assets/11302521/b949b967-d55d-4f58-8fe9-f0343949d763)

The codeblocks are behaving weird when dark reader is enabled for GitHub

### Website Address

https://github.com/ryantm/agenix#installation

### Steps To Reproduce

Open any github repository that is using codeblocks in the readme and expect it unwantedly scale as shown

### Operating System

NixOS 23.05

### Web Browser name and version

Firefox 121.0

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
I got what you submit and found solution. There will be a fix in a minute. 😉
