### ISSUE TITLE
[Broken Website] TipTap Editor freezes when another user starts to select text in the editor

### ISSUE THREAD

**Issue by kr1ke** [darkreader/darkreader#12066]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

With the dark theme enabled, when the second user in the Tap Tap editor starts highlighting text, the site page freezes, probably due to the fact that the background color of the text is constantly calculated for highlighting

adding class "darkreader" dont help
![image](https://github.com/darkreader/darkreader/assets/63511922/cfecd899-3a06-4432-8d5b-1b5b1a0a6dee)

### Website Address

https://tiptap.dev/docs/editor/examples/collaborative-editing

### Steps To Reproduce

1. [Go to https://tiptap.dev/docs/editor/examples/collaborative-editing with on DarkMode]
2. [Open the second tab of the same site in a light theme and start highlighting the text in the editor]
3. [The site page that was opened in the dark theme will freeze]]

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/63511922/83ec524b-4cbe-4a96-8a77-c0aa2b8c1205)

### Operating System

Windows 11

### Web Browser name and version

Chrome 120.0.6099.111 Official x64 (all browsers)

### Dark Reader version

4.9.73 (last)

**Comment by Myshor** [comment]
I checked scenario using Firefox with Dark Reader and second incognito tab without Dark Reader.

After second user changes the first tab ended with notification that Dark Reader is slowing down browser and suggest to disable Dark Reader for it.

So it will need more investigation - site fixes won't help.

**Comment by DanOrdant** [comment]
@Myshor I am having a similar issue and have investigated it a bit.
I lead on a project which has 100+ pages and some of them contain a TipTap editor.
Darkreader works fine on all of them, but when a page with TipTap editor is opened it enters an infinite loop.
The infinite loop is caused because the darkreader watcher for colors and the editor's watcher both try to change the color of an element in the editor back and forth.
So the only solution is to disable darkmode for inside the editor but you dont provide that feature?

**Comment by Myshor** [comment]
OK... I am a little bit more experienced in what I should check and I think I have some quick sitefix that will fix that freezes.
And you gave nice tip about that changing colors. I will just force to ignore injecting inline colors.

Some backgrounds can be now light (specially the one for showing active users) but at least the site is not freezing.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by DanOrdant** [comment]
> OK... I am a little bit more experienced in what I should check and I think I have some quick sitefix that will fix that freezes. And you gave nice tip about that changing colors. I will just force to ignore injecting inline colors.
> 
> Some backgrounds can be now light (specially the one for showing active users) but at least the site is not freezing.

Sorry I didn't quite get how that should work since the user might have selected a color for something.
Btw. When I switch the Darkreader -> More -> Theme from Dynamic to Filter it is working fine
