### ISSUE TITLE
[Broken Website] Only text changes on https://www.isharkieblanket.com/

### ISSUE THREAD

**Issue by LantashTheTokra** [darkreader/darkreader#12075]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The background of the website isn't changed

### Website Address

https://www.isharkieblanket.com/

### Steps To Reproduce

go there

### Screenshots

![Screenshot_20231229-103544](https://github.com/darkreader/darkreader/assets/84555704/12b7d972-18d3-4164-a1e0-15ab0f55fb51)

### Operating System

Android 14

### Web Browser name and version

Mull (firefox fork) 121.0.0

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
This site source code is ugly as ... 😝
But I managed to do some site fix that will work in light and dark scheme as it should. 😉

Just making Pull Request and merge in a minute. 😁
