### ISSUE TITLE
[Broken Website] deew.dev

### ISSUE THREAD

**Issue by pcroland** [darkreader/darkreader#12078]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Some of the white svg's turn black despite already on a dark background

### Website Address

https://deew.dev

### Steps To Reproduce

Open site

### Screenshots

![img1](https://telegra.ph//file/ed8577220169f2ab768c3.png)
![img2](https://telegra.ph//file/3ab33bec7ec72b6a2a17a.png)

### Operating System

Win 10

### Web Browser name and version

Latest Chrome

### Dark Reader version

Latest Dark Reader

### Additional Context

Each svg has `fill="#FFFFFF"` in both the svg element and all the paths aswell.

**Comment by Myshor** [comment]
Compared how it work in light and dark scheme and it worked fine in light so...
I forced the same fill color for Dark Reader's Light and Dark scheme in fix. 😉
