### ISSUE TITLE
Mi.com Text over top site images...

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#1208]
Sometimes the images at the top, the text above it is inverted when it shouldn't be.
Dynamic themes needs a fix to not allow inverting in the class `.home-top-slides`.

Example below:
![image](https://user-images.githubusercontent.com/19640692/55121947-1f40f280-50ba-11e9-998d-6570c169603f.png)

**Comment by Gusted** [comment]
Text are now integrated into images so it should be perfect now.
