### ISSUE TITLE
codecademy with dynamic mode makes blinking insertion point invisible 

### ISSUE THREAD

**Issue by LucasRTonin** [darkreader/darkreader#12093]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/darkreader/darkreader/assets/30559272/f2eb05f5-0ea5-4dda-98be-0413b11bc150)
using the dynamic mode, the blinking bar doesn't show up  since is the same color of the background
I don't have the knowledge to fix it, so please help 
thanks
edit:
![image](https://github.com/darkreader/darkreader/assets/30559272/a63cfaa2-6808-4793-9ee7-2416ac5c15ee)
i think it has to do with this input area being a simulation
### Website Address

https://www.codecademy.com/

### Steps To Reproduce

use dynamic mode 

### Operating System

windows 10

### Web Browser name and version

chrome latest

### Dark Reader version

latest

**Comment by LucasRTonin** [comment]
![image](https://github.com/darkreader/darkreader/assets/30559272/8e4b5989-9847-4b25-bf4a-e88f62b98530)

**Comment by Myshor** [comment]
I see cursor but is definitely dark in dark mode. 😉
Fix will be added in a minute.

**Comment by LucasRTonin** [comment]
thanks @Myshor
