### ISSUE TITLE
[Broken Website] humprog.org

### ISSUE THREAD

**Issue by coteeq** [darkreader/darkreader#12095]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

So the text appears to be blue, but website does not have anything bluish in its styles. In fact, the site has like 6 lines of css, so this behavior is quite strange.

What's even stranger is that css does not even have any mentions of color things - just layout things

### Website Address

https://www.humprog.org/~stephen/blog/2024/01/02

### Steps To Reproduce

1. You just activate dark reader with default settings

Alternatively:
1. `curl https://www.humprog.org/~stephen/blog/2024/01/02/ > 02.html`
2. edit the html, so it does not load the css and even the gif file
3. Launch something to serve the html, for example `python3 -m http.server`
4. open the url, where the server is running, e.g. `localhost:8000/02.html` if you ran python from the previous step
5. enable dark reader

### Screenshots

<img width="660" alt="image" src="https://github.com/darkreader/darkreader/assets/42947087/a8e72aa3-0493-4e52-b90e-60b2027d2a9c">

### Operating System

MacOS

### Web Browser name and version

Safari Version 17.2.1 (17617.1.17.11.12, 17617)

### Dark Reader version

2.0.3

### Additional Context

I could also reproduce the same issue in Firefox 121 and in Safari-on-iPad. Firefox also has other extensions and customizations, but Safari-on-iPad only has dark reader

**Comment by Myshor** [comment]
The problem that generate this lies inside the html code.

All blue text are between 
```
<a name="make-shell">
...
</a>
```
And Dark Reader change <a> links into blue.

**Comment by coteeq** [comment]
Oh, thanks, I did not notice that.
I guess that's not dark reader's fault and actually, browser is doing something sketchy (like scanning inner tags of an `a` tag and ignoring link markup if the link contains something like `p`). Idk, whether Dark Reader should follow this, but it would be consistent with the browser's behavior if it will.

Anyway, this feels like a very minor bug, if a bug at all, so feel free to just close the issue :)
Thanks again

**Comment by Myshor** [comment]
Ok. I'm closing.
