### ISSUE TITLE
[Broken Website] Unable to log in to `login.my.gov.au`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [darkreader/darkreader#12123]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When https://addons.mozilla.org/firefox/downloads/file/4205543/darkreader-4.9.74.xpi is *enabled* (installation status is irrelevant) I am unable to log into https://login.my.gov.au/las/mygov-login?execution=e27s2.

### Website Address

https://login.my.gov.au/las/mygov-login?execution=e27s2

### Steps To Reproduce

1.	Install https://addons.mozilla.org/firefox/downloads/file/4205543/darkreader-4.9.74.xpi.
1.	Enable it.
1.	Visit https://login.my.gov.au/las/mygov-login?execution=e27s2.
1.	Create an account. (https://github.com/webcompat/web-bugs/issues/131781#issuecomment-1881508357)
1.	Enter username and password.
1.	Enter security question (if asked).

It shall now return to the login page.

### Operating System

https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20240106-Media.iso?mirrorlist

### Web Browser name and version

https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-121.0-1.1.x86_64.rpm

### Dark Reader version

https://addons.mozilla.org/firefox/downloads/file/4205543/darkreader-4.9.74.xpi from https://github.com/darkreader/darkreader/releases/download/v4.9.74/darkreader-firefox.xpi

### Additional Context

https://github.com/darkreader/darkreader/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+login.my.gov.au returned 0 results at +2024-01-08T17:26:49+00:00.

**Comment by Myshor** [comment]
I can not reproduce in Firefox - however I don't use OpenSuse

**Comment by RokeJulianLockhart** [comment]
> https://github.com/darkreader/darkreader/issues/12123#issuecomment-1882742062

@Myshor, I likewise can't reproduce it on https://koji.fedoraproject.org/koji/rpminfo?rpmID=39668684 with https://addons.mozilla.org/firefox/downloads/file/4317971/darkreader-4.9.88.xpi, so it's probably not an issue any more.
