### ISSUE TITLE
[Feature Request] Always dark websites

### ISSUE THREAD

**Issue by nawordar** [darkreader/darkreader#12135]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

Yes

### Feature Request Description

There are some websites that, for some reason, hurt my eyes no matter how well lit the room is. One such website is [messenger.com](https://www.messenger.com). I would like to automatically set dark mode based on the system theme for most websites, except for these.

**Comment by Myshor** [comment]
Can you specify a little bit more?

As I understand you use light theme sometimes (or even always) but you want to have option to force dark theme even if light is enabled?

**Comment by nawordar** [comment]
I have Dark Reader set to "Follow system color scheme", so when I set the light theme in the OS, Dark Reader is essentially turned off. I would like to have an option to force dark mode on certain websites even when the OS theme is set to light.

**Comment by Myshor** [comment]
Ok... That makes a diiferent approach as you wrote - in Auto Dark Reader is disabled when light mode for system is set and no CSS injection is made at.

That will need some analysis how it could be done - would it be another site list to configure or something.
And  one more question:
How it should work when you have Dark Reader fully disabled - not set to auto. Should it force dark mode to the sites of the list too or not? 😉

@alexanderby you must see that and comment if we will consider to implement this or you have some other advice or workaround.

**Comment by nawordar** [comment]
Now I see that it this 'little' feature would require a whole UI overhaul. I can live without it, honestly
