### ISSUE TITLE
[Bug] Uncaught ReferenceError: __assign is not defined / Uncaught ReferenceError: __awaiter is not defined

### ISSUE THREAD

**Issue by cope** [darkreader/darkreader#12149]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

When enableDarkMode() is called, 2 errors are reported in the console:

```
VM11162:326 Uncaught ReferenceError: __assign is not defined
    at injectProxy (<anonymous>:326:25)
    at <anonymous>:399:9
    at createStaticStyleOverrides (darkreader.js?t=1705309604455&v=a3824c6c:6980:25)
    at createThemeAndWatchForUpdates (darkreader.js?t=1705309604455&v=a3824c6c:7252:9)
    at createOrUpdateDynamicThemeInternal (darkreader.js?t=1705309604455&v=a3824c6c:7501:11)
    at enable (darkreader.js?t=1705309604455&v=a3824c6c:7678:9)
    at Proxy.toggleDark (DarkMode.vue?t=1705310759856:15:4)

10:26:04.367 VM11162:277 Uncaught ReferenceError: __awaiter is not defined
    at HTMLDocument.checkBlobURLSupport (<anonymous>:277:11)
    at darkreader.js?t=1705309604455&v=a3824c6c:2641:30
    at new Promise (<anonymous>)
    at darkreader.js?t=1705309604455&v=a3824c6c:2626:19
    at step (darkreader.js?t=1705309604455&v=a3824c6c:122:25)
    at Object.next (darkreader.js?t=1705309604455&v=a3824c6c:69:20)
    at darkreader.js?t=1705309604455&v=a3824c6c:49:70
    at new Promise (<anonymous>)
    at __awaiter (darkreader.js?t=1705309604455&v=a3824c6c:30:16)
    at requestBlobURLCheck (darkreader.js?t=1705309604455&v=a3824c6c:2605:16)
```

### Website Address

localhost

### Steps To Reproduce

```
<template>
	<div>
		<span v-if="useDark" @click="toggleDark()" class="cursor-pointer">light</span>
		<span v-else @click="toggleDark()" class="cursor-pointer text-white">dark</span>
	</div>
</template>

<script setup>
	import {disable as disableDarkMode, enable as enableDarkMode} from 'darkreader';

	const useDark = ref(false);
	const toggleDark = () => {
		useDark.value = !useDark.value;
		if (useDark.value) enableDarkMode();
		else disableDarkMode();
	};
</script>
```

### Expected Behavior

no errors in console

### Actual Behavior

errors in console:

Uncaught ReferenceError: __assign is not defined
Uncaught ReferenceError: __awaiter is not defined

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/112515/ab74dbec-10e1-4892-9d95-ebd4ff76e2d6)

### Operating System

Windows

### Web Browser name and version

Chrome 120.0.6099.217

### Dark Reader version

"darkreader": "^4.9.75"

**Comment by cope** [comment]
looks like `setFetchMethod(fetch)` fixed the `__awaiter is not defined`, but `__assign is not defined` is still happening consistently 😞

**Comment by 3ldar** [comment]
I have the same issue, I think it comes from the option  : ` "noEmit": true` in the `tsconfig.`

**Comment by Lachee** [comment]
I have the same issue on `Firefox 121.0.1 (64-bit)`

**Comment by eviltik** [comment]
A fallback to 4.9.73 did the trick. What happened between .73 & .75 ?

**Comment by 3ldar** [comment]
In my case, I had to downgrade to 4.9.69 to make it work without errors in chrome Version 120.0.6099.225 (Official Build) (64-bit).

**Comment by tbl0605** [comment]
Hi,
I have the same problem since version v4.9.75 until the latest version v4.9.77 using Firefox and Chrome.
Any news on this issue?

**Comment by adhocore** [comment]
just had same issue in brave/chrome too (v >= 4.9.75)

**Comment by alexanderby** [comment]
Hey guys. I've just upgraded the bundle from ES6 to ES2020. Please download `darkreader@4.9.79` and check if it helps.

**Comment by tbl0605** [comment]
@alexanderby,
for me it solves the problem, thank you very much :)
