### ISSUE TITLE
Safari: Add hotkey to turn Dark Reader on/off for current website

### ISSUE THREAD

**Issue by nikitavoloboev** [darkreader/darkreader#1214]
I don't believe such functionality exists. Would be great to have it. Thanks.

**Comment by prohtex** [comment]
Yes, I am really hoping for this!

**Comment by josdyr** [comment]
I second this one!

**Comment by dmatora** [comment]
Yeah, hotkey would be really great.
Or at least getting rid of popup delay that exists on Safari but doesn't exists on chrome

**Comment by nikitavoloboev** [comment]
@alexanderby Can you point to a place where one could look to add this functionality and send PR?

**Comment by sponkydive** [comment]
+1 
love this function on chrome and firefox... please add it to safari as well ;)

**Comment by alexanderby** [comment]
Should be available already.
