### ISSUE TITLE
hongkongfp.com article looks terrible

### ISSUE THREAD

**Issue by divinity76** [darkreader/darkreader#1215]
url: https://www.hongkongfp.com/2019/04/01/china-warned-countries-not-attend-un-meeting-xinjiang-human-rights-violations/

the article text gets filled with white dots making the text very hard to read,

with Dark Reader:
![image](https://user-images.githubusercontent.com/1874996/55350926-70d3ed80-54bd-11e9-81a8-f9d26248d40f.png)

without Dark Reader:
![image](https://user-images.githubusercontent.com/1874996/55350977-86491780-54bd-11e9-9bfe-130997fff40f.png)

**Comment by daanhaitsma** [comment]
No idea why they'd do that, but they have a repeating [background with two white pixels](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAH0lEQVQIW2NkQAOMMP6HDx/+CwgIMMIFYBKMMBmYAADbZggFwoksMQAAAABJRU5ErkJggg==), which remains when dark mode is active

**Comment by Gusted** [comment]
Fixed.
