### ISSUE TITLE
[Broken Website] QR signin broken at Danish national identity provider MitID

### ISSUE THREAD

**Issue by kimsey0** [darkreader/darkreader#12159]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

MitID is the national identity provider of Denmark. It's used to sign into government websites, online banking, etc. The sign-in process includes scanning a QR code with a mobile app. Unfortunately, Dark Reader changes the background behind the QR code to a dark enough color that the app won't scan it.

### Website Address

https://www.mitid.dk/

### Steps To Reproduce

1. Go to any website using MitID sign-in, such as https://www.mitid.dk/, and clicking the sign-in button (_Log på_).
2. Entering a valid MitID username and clicking continue.
3. Opening the MitID app.

(See additional context for reproduction steps that does not require a Danish MitID account.)

### Screenshots

![Sign-in page with QR code](https://github.com/darkreader/darkreader/assets/984760/8cb78746-fe70-4bbc-9ac0-ca6aad07cdaf)

### Operating System

Windows 10

### Web Browser name and version

Firefox 121

### Dark Reader version

4.9.74

### Additional Context

Any fixes can be tested with the [MitID test tool](https://pp.mitid.dk/test-tool/frontend/#/create-identity) by:
1. Creating an identity by clicking _Autofill_ and _Create identity_.
2. Copying the identity claim.
3. Opening the app simulator by clicking _Open simulator_ at the bottom.
4. Starting a sign-in flow by going to the _Flows_ tab and clicking _Start client_.
5. Pasting the identity claim and continuing.
6. Waiting for the app simulator to load the sign-in request or clicking _Pull outstanding transactions_.

**Comment by Myshor** [comment]
It's working nice when you apply it in developer tools in browser however I tried to do that in Dark Reader developer tools and it's not working. QR code is displayed in iframe and even if I add white background to whole iframe the background around QR stays dark.

Spent too much time trying to fix this.

As a walkaround you just need to disable Dark Reader before loging in.

Maybe @alexanderby will think some solution. I am defeated by this site. 😞

**Comment by kimsey0** [comment]
Yeah, it looks like the iframe doesn't have a location (it's `about:blank` in the console), but instead has it's content set through JavaScript. I'm not sure Dark Reader has a way to apply fixes iframes like that.

I see there are some universal (`*` scoped) rules at the top of dynamic-theme-fixes.config. If we were to add a rule there, it could be scoped to the custom `<mitid-authenticators-code-app>` element they use to make sure it doesn't apply to any other sites. But I don't know what the requirements are to add something there when it only affect users from Denmark?

In any case, this works for me:

```css
mitid-authenticators-code-app > .code-app-container {
    padding-top: 1rem;
    background-color: white !important;
}
```

**Comment by Myshor** [comment]
I will merge your code from above as it is now the only solution. 😉

**Comment by kimsey0** [comment]
Thanks for the help!
