### ISSUE TITLE
[Broken Website] YouTube banner images gone

### ISSUE THREAD

**Issue by Hulayki** [darkreader/darkreader#12168]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Yes, this is what happening.

### Website Address

https://www.youtube.com/@markiplier

### Steps To Reproduce

1. click the link above
2. open the link
3. run the link
4. come on, man

### Screenshots

![dffdf](https://github.com/darkreader/darkreader/assets/97475801/e55fb111-3942-4699-9cce-a98226c113f6)

### Operating System

Windows 11

### Web Browser name and version

Chrome 120

### Dark Reader version

4.9.75

**Comment by Myshor** [comment]
There will be sitefix in a minute. 😉
