### ISSUE TITLE
[Broken Website] makes webVNC at www.servercontrolpanel.de useless

### ISSUE THREAD

**Issue by nanderer** [darkreader/darkreader#12166]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

while dark reader is enabled you think that your server is defective because you have only a black screen with the cursor, you then restart the server for no good reason and finally find out that the whole screen is black cause of that addon, and when you disable it you get bedazzled but remote console / web vnc is working fine

### Website Address

https://www.servercontrolpanel.de/SCP/VNCPopUp

### Steps To Reproduce

you have to order a vps there to try it out, ill try to make a singlefile shot of that page for you to reproduce

### Screenshots

![Screenshot from 2024-01-17 23-18-59](https://github.com/darkreader/darkreader/assets/45161625/bf42c59d-56f2-4ea1-bbb7-eeaa822ef84a)
blank screen but you should see sth

![Screenshot from 2024-01-17 23-19-33](https://github.com/darkreader/darkreader/assets/45161625/e97045d9-2643-4ca4-af09-9dee88ab413c)
after disabling dark reader

### Operating System

debian

### Web Browser name and version

firefox latest esr 115.6.0esr (64-bit)

### Dark Reader version

latest Version 4.9.75

### Additional Context

[VNC Console (1_17_2024 11_20_.zip](https://github.com/darkreader/darkreader/files/13969346/VNC.Console.1_17_2024.11_20_.zip)
here is some static save of that page, maybe you can find out the css problem through that, or if not tell me how to capture it for you so you can look into it without me revelaing my login data to you

**Comment by Myshor** [comment]
There was similar issue with different site few days ago. I hope the fix will work as I end with some error trying to open URL.

On the saved HTML it worked so only problem in fix can be related to URL used in it. 😉
