### ISSUE TITLE
[Bug] Dark reader injects a lot of error messages into forgejo

### ISSUE THREAD

**Issue by msrd0** [darkreader/darkreader#12169]
### Bug Description

The forgejo website (https://codeberg.org) lists all javascript errors on top of their website. Those however originate from dark reader, disabling it makes the problem go away.

### Website Address

https://codeberg.org/forgejo/forgejo/issues

### Expected Behavior

Dark Reader does nothing as the website already has a nice dark theme.

### Actual Behavior

Dark Reader tries to darken the website, injecting a lot of errors into it.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/7853372/46e1c535-12e3-4f93-87c3-e83171649f64)

### Operating System

ArchLInux

### Web Browser name

Firefox Developer Edition

**Comment by timabbott** [comment]
We're seeing this exception in Zulip and it looks like other web apps (https://github.com/datenanfragen/website/issues/1128) is seeing it as well, so I think this is important to fix as the exceptions get reported for every web app that has Dark Reader users that is investigating their browser exceptions.

**Comment by Myshor** [comment]
Confirmed in Firefox using Windows.

In Chromium (used Edge to check) browser this error does not occur.

(Just a comment to help someone who will do the fix in the future - I only do CSS fixes here 😉)

**Comment by alexanderby** [comment]
A fix hsas been release, please check.
