### ISSUE TITLE
conflict with bookmark sidebar extension

### ISSUE THREAD

**Issue by cleuton4k** [darkreader/darkreader#12175]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

dark reader changes the color of the mask

### Website Address

 (all)

### Steps To Reproduce

1.install extension https://chromewebstore.google.com/detail/barra-de-favoritos/jdbnofccmhefkmjbkkdkfiicjkgofkdh
![682](https://github.com/darkreader/darkreader/assets/90144967/d8047ff7-2712-44bc-aa88-ece9f57b02b3)
![683](https://github.com/darkreader/darkreader/assets/90144967/bdc3acfc-0f7b-433d-93d2-c4f85542b399)
![684](https://github.com/darkreader/darkreader/assets/90144967/3d9d793c-9f97-4379-b4f9-68ffdd533638)

https://github.com/darkreader/darkreader/assets/90144967/53eefc6b-3944-4d71-b804-3b7addd19879

### Expected Behavior

.

### Actual Behavior

.

### Screenshots

.

### Operating System

w10

### Web Browser name and version

edge 120

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
I can not see the movie but I checked comments for the mentioned extension that it injects some code into the site you are browsing (someone commented the bar is zooming with the rest of the site).

As it injects some code same as Dark Reader there could be some issues with that.
On video we can see it's making some darkened transparency depending on background color of the page and because of that it's dark.

Making fixes won't be easy or even not possible as it uses iframe to show the sidebar and it's not easy to make injections into iframes in Dark Reader.

One thing I can recommend now is to find some different bookmarks addon or contact this bookmarks addon author that and maybe he will change the way of displaying it that it could be managed by us and fix easier.

Last possibility - just live with that that background is fully dark for this extension when Dark Reader is enabled.

**Comment by cleuton4k** [comment]
-I contacted the developer and his response was this:
"The sidebar extension cannot influence when or if it will be changed by the Dark Reader extension. Without an option in Dark Reader to exclude certain elements from being changed, there is unfortunately little I can do about it."

-this other extension similar to the dark reader does not modify the "mask" preserving transparency, can you tell me why the dark reader didn't work?
https://chromewebstore.google.com/detail/modo-escuro/fpneimadkgmbkijjeomfgchpbjblepnp

https://github.com/darkreader/darkreader/assets/90144967/3fff44e2-710f-4174-80c7-0f778757a992

**Comment by Myshor** [comment]
Dark Reader is applying some colors to whole body in the page. When it's working nice it's nice but when the problem occurs like you have with this issue the main issue is that when we are doing CSS fixes for the sites we need to include specific selectors to make that fixes. When there is some iframe in the code (this means another page displayed in totally separate container) then it's not that easy to force changes for colors for that.

At least in this issue I was trying to firce some background with trasparency but iframe forced it's setting even above Dark Readers one.

One possibility I found was to make whole iframe opacity (transparency) set to 95% - this made backgroun page visible but whole left sidebar was transparent too. That would bring you with another complain it works totally different as it should.

**Comment by Myshor** [comment]
And one more thing - most of other Extensions with dark mode sets just background color and changes text color. We do some more analysis what should be inverted and changed + we do it on-the fly so if something new will be generated to the page code we try automaticly to make it dark to. Before Dark Reader I was trying other extensions and most of them made nice dark mode for the loaded page but when there was some new content displaye the new content was not touched and was light. So I bet the extension you mentioned works the same. It darkened the page but as sidebar was not loaded yet it didn't touch it as it is dynamicly loaded after opening it.

**Comment by Myshor** [comment]
I hope it will be understandable to you. I was trying to describe it as much as possible in easy way. 😉
