### ISSUE TITLE
[Broken Website] jegy.mav.hu introduction text and graphic seat planning

### ISSUE THREAD

**Issue by RozvM** [darkreader/darkreader#12173]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Introduction text is hard to read on the landing page and also the newly released _graphic seat plan_ has icons that are hard to distinguish from each other and text that is hard to read.

### Website Address

https://jegy.mav.hu/

### Steps To Reproduce

**For introduction text:**
1. Use Dark Reader with these options:
![image](https://github.com/darkreader/darkreader/assets/74600479/8ee0b872-1d6a-4859-b5dc-1184352ff37d)
2. Open https://jegy.mav.hu/

**For _graphic seat plan_:**
1. Visit https://jegy.mav.hu/jegy/reszletes-kereso
2. 1. Use Dark Reader with these options:
![image](https://github.com/darkreader/darkreader/assets/74600479/8ee0b872-1d6a-4859-b5dc-1184352ff37d)
3. (Optional) Change language to EN in the top right corner
4. Use these settings on the site:
![image](https://github.com/darkreader/darkreader/assets/74600479/76457afe-3a0e-4326-b78b-cb0c4f718c8e)
5. Click on _Search_
6. Choose from any of the InterCity trains (Railjet doesn't have this feature) and click on it's price
7. Continue as a guest
8. Fill out the passenger info and click _Next_
9. Choose _Graphic seat_ plan and click _Next_

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/74600479/722a6fa7-bf02-49cb-92a4-3ecf7c125ff4)
![image](https://github.com/darkreader/darkreader/assets/74600479/d432b7bd-ff21-494e-b07e-3c1ed97f63c5)
![image](https://github.com/darkreader/darkreader/assets/74600479/8fc8d231-24a6-4421-8af0-f304e00573ec)
![image](https://github.com/darkreader/darkreader/assets/74600479/3bf3a3bf-2fbc-42c4-8568-42a0c058645b)

### Operating System

Windows 10 Pro N | 22H2 | 19045,3803

### Web Browser name and version

Mozilla Firefox 121.0.1 (64-bit)

### Dark Reader version

4.9.75

**Comment by Myshor** [comment]
Fix is ongoing... I mean I already made it localy and will push it in some minutes.

Here are the results:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/00d09e62-8513-4297-9e75-033101a5f485)

![obraz](https://github.com/darkreader/darkreader/assets/56877029/6046bcfc-f5a0-426c-aaf5-268458c7182b)

**Comment by Myshor** [comment]
Aditionally added invert for that black icons. 😉

**Comment by RozvM** [comment]
> Aditionally added invert for that black icons. 😉

Thank you very much! Another minor problem that I encountered:

https://github.com/darkreader/darkreader/assets/74600479/3ac7ab10-3843-4358-be2e-008619ee2018

**Comment by Myshor** [comment]
I wil add small fix for that in a minute. 😉
