### ISSUE TITLE
[Bug] Gitea JavaScript errors in Firefox

### ISSUE THREAD

**Issue by SirCypher** [darkreader/darkreader#12180]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Gitea reports lots of JavaScript errors since the last DarkReader Update when using Firefox.
The same Gitea version worked fine before DarkReader extension updated itself.

Reproduced in Windows Sandbox with fresh browser installs and no other extensions.
No visible problems in Edge and Chrome.
Only Firefox seems affected.

Happens at least in Gitea v1.21.3 , v1.21.4 (current stable) and v1.22-dev (try.gitea.io).

### Website Address

https://try.gitea.io/explore/repos

### Steps To Reproduce

1. Open Firefox
2. Enable Dark Reader
3. Go to https://try.gitea.io/explore/repos
4. Observe JavaScript error reports

### Expected Behavior

No JavaScript errors.

### Actual Behavior

Lots of JavaScript Errors of this kind:
`JavaScript error: TypeError: WeakMap key undefined must be an object or an unregistered symbol (https://try.gitea.io/explore/repos @ 529:36). Open browser console to see more details.`

### Screenshots

![darkreadererrors](https://github.com/darkreader/darkreader/assets/77209279/ce1c999c-b093-4b0d-a13b-e405eb934181)

### Operating System

Windows 10

### Web Browser name and version

Firefox v121.0.1

### Dark Reader version

4.9.75

**Comment by Myshor** [comment]
Same issue was reported to other site too - #12169

**Comment by AaronFriel** [comment]
We're seeing a similar issue on Pulumi AI, pages such as this one report an error in the console, which shows up in our application monitoring tools: https://www.pulumi.com/ai/answers/vTvcDSa3cKj4vr25EGNycH/applying-kubernetes-manifests-on-aks

**Comment by violet4** [comment]
> the reactjs/nextjs app that I am developing

ditto that

**Comment by Mac15001900** [comment]
This also happens on a web game I'm working on: https://mac15001900.github.io/MotV/
It might be an interesting example, since being a canvas-based game means there aren't a lot of elements for Dark Reader to affect here.

**Comment by alexanderby** [comment]
The fix hasn't been released yet, I will push it next Monday and Firefox usually takes 3 days to review it.

**Comment by HellBri8nger** [comment]
Same issue here

**Comment by SedapnyaTidur** [comment]
Whats the status here? Im using 4.9.76 on Firefox. Ive being seen this kind of error everywhere, on every site. The error looks like this:
```
"TypeError: WeakMap key undefined must be an object or an unregistered symbol
Error in file: undefined on line 529:36"
```

**Comment by moritz-t-w** [comment]
> Whats the status here? 

Literally read one comment above you. It'll be there soon

**Comment by alexanderby** [comment]
A fix should be available now.
