### ISSUE TITLE
[Broken Website] windy.com : temperatures in graph

### ISSUE THREAD

**Issue by Morgan1er** [darkreader/darkreader#12185]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The temperatures line of the graph of windy.com doesn't show. 

### Website Address

https://www.windy.com

### Steps To Reproduce

1. Go to https://www.windy.com
2. Check the graph down the window

### Screenshots

<img width="1210" alt="Capture d’écran 2024-01-21 à 23 26 26" src="https://github.com/darkreader/darkreader/assets/92629032/03c97a80-9a6c-43b5-b829-7c863edc6cc9">
<img width="1206" alt="Capture d’écran 2024-01-21 à 23 26 05" src="https://github.com/darkreader/darkreader/assets/92629032/0af39714-8fa1-461d-bf79-7a9b30f26e85">

### Operating System

macOS Sonoma 14.2.1

### Web Browser name and version

Safari 17.2.1

### Dark Reader version

2.0.3

### Additional Context

An existing issue report has been made regarding this concern : [#6131](https://github.com/darkreader/darkreader/issues/6131)

It is marked as resolved and closed so I created this new one.

**Comment by Myshor** [comment]
Can  you give a tip how to enable the graph? I tried to make it visible but I can't find how.

**Comment by Morgan1er** [comment]
Well, I think if you click anywhere on the map shown when you get to the site, the graph appears. 

But if it helps, [here is the link I use](https://www.windy.com/48.650/-2.020?48.598,-2.020,11) for my location for example.

**Comment by Myshor** [comment]
I am adding shadow to the text so it will still be light in dark mode but more readable.
The result will be like on the screen below:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/e7e9f22a-0e72-4a19-af4a-b6947ccd87ea)

At least it will be more consistant than making temperature color dark. 😉

The site fix will be pushed in  a minute.
