### ISSUE TITLE
[Broken Website] Reddit search results text invisible while hovering

### ISSUE THREAD

**Issue by pallaswept** [darkreader/darkreader#12189]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When hovering search results on reddit, the text becomes invisible. Screenshots below.

I'm aware that reddit has it's own dark mode, but that doesn't take care of my needs as it doesn't do text colours etc like DR does, so I still prefer to run DR there. I haven't run into any other issues on the site aside from this one with search results.

### Website Address

https://www.reddit.com/search/?q=dark+reader

### Steps To Reproduce

1. Visit reddit.com
2. Run a search
3. Hover a search result

### Screenshots

Screenshot not hovering:

![image](https://github.com/darkreader/darkreader/assets/132128962/3c7a9027-7fbb-40bf-b9fe-3542f2104d5c)

Screenshot while hovering:

![image](https://github.com/darkreader/darkreader/assets/132128962/25d1456e-9cc4-4fb5-9ef5-47ac2e271ee8)

### Operating System

Linux

### Web Browser name and version

Firefox 121

### Dark Reader version

4.9.76

### Additional Context

Thanks!
Edit: better screenshots

**Comment by Myshor** [comment]
Site fix will be in a minute.

**Comment by pallaswept** [comment]
> Site fix will be in a minute.

That was FAST! Thanks so much :)

**Comment by pallaswept** [comment]
@Myshor since you were so kind as to fix this so quickly for me, I hope maybe I can save you some trouble...

It seems like reddit changed something today, because this is now fixed - and I haven't updated the DR addon, and as far as I can tell by inspecting the page, I don't have the properties you set in this change (the `a`nchor object has `background-colour` transparent - not the DR variable you set) - so I'm pretty sure something must have changed at reddit's end.

I'm concerned that this change at their end, might actually cause breakage with the new fix you've just added, or with old reddit code - I don't know, but there is the possibility they might have broken something for the future DR version. So, I thought I should mention to you that the change happened.

No pressure on you to do anything, just letting you know, just in case. If I do come across any problems after the DR upgrade, I'll file a separate issue.

I hope this helps, and thanks again.

**Comment by Myshor** [comment]
Maybe the sitefixes updated - they update with new design enabled without extension update.

And my fix didn't set something but removed forced background setting so it uses default actions used by extension.

And yeah... if there will be some more issue with reddit just make new issue and someone will look at it. 😉

**Comment by Katzenwerfer** [comment]
Hi. The deleted CSS rule was something I committed in a [previous PR](https://github.com/darkreader/darkreader/pull/12098) to fix the background color of some boxes in the Reddit sidebar.

I had already corrected the selectors to stop that fix from applying to unintended elements in [another PR](https://github.com/darkreader/darkreader/pull/12134/commits/1efe51f35fdb14ad006641f9b5d90f2eb1768678) I made. It is still not as specific as I would like it to be but those buttons are inside a shadow-root and I have yet to find to select it in a chain.

Here is a picture of said buttons and how they look now.
![image](https://github.com/darkreader/darkreader/assets/53267697/fc1fbc04-960a-4511-8171-f93481c6c28e)

**Comment by pallaswept** [comment]
Odd, I can't replicate that behaviour here: 
![image](https://github.com/darkreader/darkreader/assets/132128962/17e665ed-7aa3-4cb0-aa91-c7be0512b51d)

**Comment by pallaswept** [comment]
@Katzenwerfer I am concerned that in fixing my issue, we have broken something for you, and obvioualy that was not my intention and I would like to be sure it's truly fixed for everybody - perhaps it might serve you to re-open this case, until it is solved for us both? I'm not sure if you are able to re-open it, but if you need me to do so, please just @ me and I'll get right on it.

**Comment by Myshor** [comment]
I think no need... PR mentioned by @Katzenwerfer was already tested and merged so it should work fine. 😉
