### ISSUE TITLE
[Broken Website] Gathering.Tweakers.Net icons broken

### ISSUE THREAD

**Issue by Tycho-S** [darkreader/darkreader#12204]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

On https://gathering.tweakers.net the icons are messed up somehow. Strange enough, on the main site ( https://tweakers.net ) it works fine. Gathering is the forum of the same site.

### Website Address

https://gathering.tweakers.net

### Steps To Reproduce

Just load the webpage with Dark Reader on

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/11061880/1348b67f-b2a4-4e88-a3fb-be5c6a4ed650)

Should look like this:

![image](https://github.com/darkreader/darkreader/assets/11061880/f583c5f2-8bd8-4344-b08b-7f2e96139298)

### Operating System

Linux

### Web Browser name and version

Firefox 1.22.0

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
There was some changes in previous versions how subpages with prefixes are interpreted.

I will add alias *.tweakers.net to tweakers.net in site fixes and it will fix the issue. 😉

**Comment by Tycho-S** [comment]
Thank you for the quick fix!
