### ISSUE TITLE
The column title wasn't align with the column context when I trun on the drakrader.

### ISSUE THREAD

**Issue by c332030** [darkreader/darkreader#1221]
When i trun on the drakrader, the column title wasn't align with the column context.

Is it a bug? Maybe my easyui is out of date.If is a bug, I don't know is it necessary to fix it.

I should turn off the drakrader while develop this project, it will mislead me.

![dark](https://user-images.githubusercontent.com/15310784/55527805-26c15680-56cd-11e9-9426-c54b390a6bc0.jpg)
![light](https://user-images.githubusercontent.com/15310784/55527809-2b860a80-56cd-11e9-8f0e-11bff3002412.jpg)

My environment:

Chrome 73.0.3683.86
jQuery v2.0.0
jQuery EasyUI 1.3.5

**Comment by Gusted** [comment]
Fixed.
