### ISSUE TITLE
[Broken Website] messenger.com

### ISSUE THREAD

**Issue by RozvM** [darkreader/darkreader#12215]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Message bubbles are not properly displayed, there is a lighter colour layer around them.

### Website Address

https://www.messenger.com

### Steps To Reproduce

1. Open https://www.messenger.com
2. Login if required.
3. Open any chat

### Screenshots

![kép](https://github.com/darkreader/darkreader/assets/74600479/5a05f024-2841-41ef-b89f-a64261e2b03a)
![kép](https://github.com/darkreader/darkreader/assets/74600479/08f7ac5a-8277-4fa1-8387-deaf942045f5)

### Operating System

Windows 10 Pro N | 22H2 | 19045,3930

### Web Browser name and version

Mozilla Firefox 122.0 (64-bit)

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
Yeah... Saw this yesterday but didn't have time to make quick fix.
However fix will be pushed in the minute. 😉

**Comment by leftbones** [comment]
Messenger.com is still super broken, this should be re-opened.

**Comment by Myshor** [comment]
It's already fixed in #12272 

If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".

Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to include newest sitefixes.

With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by leftbones** [comment]
> It's already fixed in #12272
> 
> If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> 
> Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to include newest sitefixes.
> 
> With that enabled newest sitefixes will be updated every browser start. 😉

This is good information! Unfortunately it doesn't seem to have fixed the issue for some reason, even after a browser restart? The bubbles on Messenger.com are all just rectangles that are barely big enough for the text, rather than being bubbles. I'm wondering if maybe it's a theme on my friend chat.

**Comment by leftbones** [comment]
> It's already fixed in #12272
> 
> If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> 
> Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to include newest sitefixes.
> 
> With that enabled newest sitefixes will be updated every browser start. 😉

This is good information! Unfortunately it doesn't seem to have fixed the issue for some reason, even after a browser restart? The bubbles on Messenger.com are all just rectangles that are barely big enough for the text, rather than being bubbles. I'm wondering if maybe it's a theme on my friend chat.

**Comment by Myshor** [comment]
You sure you have this option enabled?
![obraz](https://github.com/darkreader/darkreader/assets/56877029/9c526aa9-8a8c-4bd4-b4b7-8f7663020292)

I had the problem with messenger after last Dark Reader update and I fixed that the same day.
added:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/0376745c-beca-4454-9281-6a1e16754e91)

and removed previous fix:
```
div[role="presentation"] {
  outline: 10px solid var(--darkreader-bg--messenger-card-background) !important;
}
```

If you still have issues then check that you have the option fir synchronizing sitefixes enabled.
Then go to Developer Tools where you can see all the sitefixes and click "Reset changes" button. That will force to set sitelist to default and with sitefixes synchro enabled it will get the newest version from github. 😉

with that I end with nice rounded bubbles without any cuts:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/5b4987a3-fc1b-4ff3-9d6b-c6abb1afda49)

**Comment by Myshor** [comment]
For themed chats it works fine too... There was totally cut of buuble and only text had background. With fix it works fine:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/9834bb62-087a-4c28-b843-c3d8c59e778d)

Censored to not see my stupid faces. 🤣

**Comment by leftbones** [comment]
@Myshor D'oh! It was the "Synchronize site fixes" option, I completely missed that. I'm going to blame my energetic toddler distracting me while reading your post for that one. Thank you!

**Comment by Myshor** [comment]
No problem. I wasn't to specific in my comment because I was writing it from phone. Now I sit before my PC so I could make screens and use the names as they are presented in Dark Reader. 😉
