### ISSUE TITLE
[Broken Website] Fyziklani - country `flag-icon`

### ISSUE THREAD

**Issue by rzehumat** [darkreader/darkreader#12214]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

A website using country flag icons is inconsistent -- some flags remain unchanged, some are with inverted colors. List of my observations below.

I would prefer if such icons rendered unchanged. Or, at least, if it was consistent -- either all changed or all unchanged. 

**Inverted flag icons:**
- Bulgaria
- Poland
- Slovakia

**Unchanged flag icons:**
- Austria
- Belgium
- Bosnia and Herzegovina
- Brazil
- Czech Republic
- Denmark
- Estonia
- Hungary
- India
- Italy
- Moldova
- North Macedonia
- Romania
- Spain
- Turkey
- United Kingdom
- Vietnam

### Website Address

https://fyziklani.cz/tymy

### Steps To Reproduce

1. Go to https://fyziklani.cz/tymy
2. With Dark Reader turner off, note that all country icons look ok
3. With Dark Reader turned on, Bulgaria, Poland and Slovakia are inverted, while others remain unchanged. Screenshot below is under "Kategorie B", numbers 50-54.

### Screenshots

Names are intentionally colored out. Green circle highlights incorrectly inverted flags of Poland and Slovakia.

![fykos_dark_fail](https://github.com/darkreader/darkreader/assets/49885819/de841480-09ed-4dc4-9102-a754e97a7ec1)

### Operating System

Linux Mint 21.2 Victoria - Desktop MATE 1.26.0

### Web Browser name and version

Brave 1.61.120

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
Fixing needs to include all broken flag as class. I added that three as they invert in Chromium browsers on this site.

I will push fix in a minute.

**Comment by rzehumat** [comment]
Thanks a lot for your help, @Myshor
