### ISSUE TITLE
[Bug] User interface only partly works in High Contrast themes - Windows 10

### ISSUE THREAD

**Issue by Andy2No** [darkreader/darkreader#12210]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

The user interface of Dark Reader only partially works, when the theme is set to a High Contrast one, in Windows 10.

The buttons and sliders appear the same regardless of their settings, so it's not possible to see which button is pressed (e.g. changing the filter mode, or selecting "only for github,com" on the More tab), or see the position of any of the slider settings.

Example Screenshot:

![Dark Reader UI problem in High Contrast themes](https://github.com/darkreader/darkreader/assets/8021302/b8ab296f-693d-4989-ae99-e2958972784c)

I have verified that switching to one of the standard Windows 10 themes makes the Dark Reader user interface behave as it should, and have tried several different High Contrast theme, including [nitschis ](https://github.com/nitschis)/ [GreyEveTheme](https://github.com/nitschis/GreyEveTheme) - all of which show the same problem.

This is on a recent fresh install of Windows 10 and a two day old fresh install of FireFox.  I've also verified that this doesn't happen on Windows 7, on a different PC.

### Website Address

Any website, any page.

### Steps To Reproduce

1. Change the theme to any High Contrast one, e.g. [nitschis ](https://github.com/nitschis)/[GreyEveTheme](https://github.com/nitschis/GreyEveTheme)

2.  Start FireFox and go to any website.

3. Click the Dark Reader icon to open the user interface.

### Expected Behavior

Expected to see the normal user interface, with all controls properly visible.

### Actual Behavior

See above.  Refer to screenshot.

### Screenshots

See above.

### Operating System

Windows 10 Pro 22H2

### Web Browser name and version

Firefox 122.0 (64-bit)

### Dark Reader version

Current.  Installed today, 2024-01-26

**Comment by Myshor** [comment]
Not sure if it can be fixed.
High contrast themes forces window background colors (as it can be seen on the opened page for example).

If you really want to have Dark Theme that won't mess that much I recommend to check Niivu's work.
https://www.deviantart.com/niivu

And for Windows 10 I was using https://github.com/niivu/Windows-10-themes/tree/main/BIB3 😉

**Comment by Andy2No** [comment]
Thanks.  I'll look into that.  I was hoping to be able to avoid hacking Windows just to be allowed to reduce eye strain, but I guess that may be the only way to avoid other problems from using High Contrast themes.

**Comment by Myshor** [comment]
If you want some tips:
Before using 3rd party themes you need to install OldNewExplorer - can be found using google.
For patching themes I use https://github.com/namazso/SecureUxTheme/releases (exe is the file that is what you need to download.
Run it as Admin and select 1,2:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/ff116474-39d7-4867-91c9-be3db677447b)
For patching and apply you select theme then 3,4.

I can share my edited BIB3 theme as I was darkening the text a little bit that should be readable on some install apps where was forced white background.

Just give me a reply you want BIB3. If not (I mean maybe you will choose different theme) then I won't share it.

**Comment by Andy2No** [comment]
Thanks.  I installed OldNewExplorer a couple of days ago, to get rid of the ribbon in Explorer that won't stay closed.  I can't claim to understand all it can do though.

Your modified theme would be good to have, if you don't mind sharing it.

**Comment by Myshor** [comment]
[BIB3.zip](https://github.com/darkreader/darkreader/files/14077485/BIB3.zip)

It's only Night (full dark) and my wallpaper I was using in Windows 10.
Hope you will like it. :)

**Comment by Andy2No** [comment]
Thanks very much.  I've got it working, now.

I like the BIB3 theme.  It would be good if I could add more definite borders on windows though - I'm getting confused about where the edges of windows are, especially when I have a few open, overlapping.  That tends to be a problem for me, with most dark themes.

Is there a good way to edit themes visually, or do we just have to edit the .theme with a text editor?  That's what I did for Windows 7 themes, but it was just trial and error and I only had a limited idea of how it worked.

**Comment by Myshor** [comment]
Most of the theme is .msstyles file. Some parameter can be changed by msstyleEditor (https://github.com/nptr/msstyleEditor) but it's not that user friendy.

First you need to know which exact parameter is responsible for the color you want to change (so it can take much time even to find correct place).
Second... Part of interface is done by Niivu by png images and that makes changes in them even harder.

In the .theme file is only settings already available in windows - so Wallpaper, dark mode enabled or not, etc.

Like I said look through different themes from Niivu - maybe you will find something what will make more satisfied. As you passed the process to enable 3rd party theme in Windows now you can try others. 😉

I recommended BIB3 as it is almost like original Windows 10 dark theme.

**Comment by Andy2No** [comment]
Yes.  I'll experiment some more.

Thanks again :)

**Comment by Myshor** [comment]
So my last question @Andy2No ... Can we close it as "wontfix"?

**Comment by Andy2No** [comment]
That seems reasonable, yes.  It is actually still possible to use DarkReader like that, if necessary - at least for someone who's already familiar with it.  I'd hoped there was a relatively simple fix, but if not, then it's probably not worth spending time on it.  

I guess not many people still use High Contrast themes in Win 10. I was only doing it because it's the only official way to get something like a proper dark mode that I could find.  I don't know if the same applies to Win 11, but I may never find out.  Being forced to learn a very different user interface every few years to stay current, has convinced me that it's not worth staying with Windows much longer.

**Comment by Myshor** [comment]
I'm closing issue.

There is possibility to change themes in Windows 11 too in the same way. There is only one more soft to use to make it always dark as Win 11 makes window title bar with minimize, maximize, close Dark if App uses orginal Dark Mode or White if it uses light mode.

For changing from Windows I have laptop with Manjaro Linux with KDE Plasma Desktop. In most linux distros if you set dark mode for apps all will have it so it's nice... But when you used some windows programs that are not available in Linux then sometimes finding alternative is hard or even there are no alternatives at all.

That's why I keep Windows on my Desktop where I do most of things daily and on laptop I use Linux (with Windows still available to boot if necessary).
