### ISSUE TITLE
[Broken Website] Dark Reader doesn't work on AirBnB website - produces a completely black page

### ISSUE THREAD

**Issue by DSiouffi** [darkreader/darkreader#12224]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Whenever I use Dark Reader on AirBnb, on any page whether is looking at houses/apartments or as a host and looking at my host listings, the whole page turns black and nothing appears.

I also tried to use a new browser profile to see if it does the same and I can confirm that it's the same issue with another fresh browser profile.

### Website Address

https://www.airbnb.com/

### Steps To Reproduce

1. go to airbnb
2. On the home page or any page of airbnb
3. Turn on Dark Reader
4. Whole page disappears and leaves a dark background

### Screenshots

Without Dark Reader
![AirBnB DR 01 ](https://github.com/darkreader/darkreader/assets/41664556/5f0b6574-4900-46de-b32d-518551ba8903)

With Dark Reader
![AirBnB DR 02 ](https://github.com/darkreader/darkreader/assets/41664556/d42b4428-d9f2-44e5-888f-52210de506c4)

It does this on any of AirBnB pages

### Operating System

Windows 10 Pro

### Web Browser name and version

Brave version 1.62.153

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
Fully reproduced on Chromium browsers.
Sometimes airbnb loads but as fully white.
Disabling and enabling DarkReader makes it totally dark.

Issue not reproduced in Firefox - page always load in dark mode and all is visible (not counting some dark icons).

Sitefix not possible to do as I tried to make some transparent background but it mess page when I scroll it down.

One thing what I found and it's different than in Firefox:
When Dark Reader is enabled this part of CSS is generated:
```
html, body, body :not(iframe) {
    background-color: #1a1b1a !important;
    border-color: #7d7363 !important;
    color: #f8efe1 !important;
}
```

And this background-color is messing around.
But like I mentioned - forcing this to transparent mess more:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/f397eb7f-8937-4693-a5e6-82589bc1378f)

Compared to Firefox where I do not touch anything:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/dbe5d117-014a-420b-8e18-4a14398e19b3)

**Comment by SrS2225a** [comment]
Can confirm as well. Opening the dev tools console revels these errors from the extension:

```
Error in event handler: Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.atm_4ymyr1_1bbsqr7_qj8o11.enter[class][class]::view-transition-new() { --view-transition_duration: 400ms; }'.
    at setRule (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:4970:24)
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5190:21
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5172:29
    at Array.forEach (<anonymous>)
    at iterateReadyRules (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5167:33)
    at buildStyleSheet (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5176:17)
    at Object.modifySheet (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5204:13)
    at buildOverrides (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5532:31)
    at Object.render (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:5545:13)
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:6928:21
```
    
```
    Uncaught TypeError: Cannot destructure property 'rule' of 'asyncDeclarations.get(...)' as it is undefined.
    at rebuildAsyncRule (index.js:5194:24)
    at index.js:5036:33
    at runTasks (index.js:118:17)
```

Taking a look at the error in closer detail, it looks like this occurring because the chrome version is trying to add styling on an invalid class resulting in the above error, but this is just a guess

**Comment by alexanderby** [comment]
I made a fix, it will be released soon.

**Comment by alexanderby** [comment]
A fix has been released.

**Comment by DSiouffi** [comment]
Works perfectly. Thanks for all the work everyone!
