### ISSUE TITLE
RAM Overload in Firefox [Bug] 

### ISSUE THREAD

**Issue by stnert** [darkreader/darkreader#12220]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Website Address

https://cybernews.com/personal-data-leak-check/

### Steps To Reproduce

When opening the Firefox browser, RAM consumption reached 6GB. I was unable to reproduce the warning that Dark Reader was slowing down Firefox.

### Expected Behavior

When opening the Firefox browser, RAM consumption reached 6GB/8GB. 

### Actual Behavior

After uninstalling and rebooting, the system returned to normal.

### Screenshots

![photo_2024-01-27_17-23-46](https://github.com/darkreader/darkreader/assets/48295298/0a33d6a9-9140-4377-bbcf-3012a0b26d12)

### Operating System

NixOS 24.05pre576254.ae5c332cbb58 

### Web Browser name and version

Mozilla Firefox 122.0 

### Dark Reader version

v4.9.76

**Comment by Kostrol** [comment]
Experiencing the same issue with excessive RAM hogging that was grinding system resources and all video playback to a halt in Librewolf with Piped, disabled Dark Reader with dynamic mode and it returned to normal levels. I noticed while watching a video it would rapidly consume up to 16gb just from one video tab at the worst.

[Kooha-2024-01-28-03-23-51.webm](https://github.com/darkreader/darkreader/assets/38816613/93e2e5f4-f9ee-41d4-a2bd-0e129fd5d7c0)
