### ISSUE TITLE
Conflict with the plugin Pinterest Save Button

### ISSUE THREAD

**Issue by jubyshu** [darkreader/darkreader#1222]
When I turn on Dark Reader, it will result in Pinterest Save Button failing to work.

**Comment by ForeverFloating** [comment]
I'm not a programmer, but when I was editing the Dev Tools and deleted the text "INVERT" and "CSS" from the first 15 lines, that seems to resolve the issue. However, this results in the entire lines of code from 1 to 15 being deleted after hitting "Apply."

**Comment by Gusted** [comment]
https://share.firefox.dev/3ik30EW 
Seems like we are chasing pintrest doing high CPU intensive things.

**Comment by Gusted** [comment]
Hi!

As I've tried to fix this on our side, I thought it was a good idea to reach over to Pinterest on their help. 
I've already narrowed down the issue and I'm the understanding how this bug is being triggered.
For now I've opened up a ticket with them with the following Information:

```
Hi reader!

I’m a main contributor of the extension Dark Reader.
It came to my attention a old issue in Dark Reader along side the Pinterest Save button extension.
I tried to gave it another try and narrowed down the issue in both Dark Reader and the Save button Extension, the inline-attribute observer and style/class observer. I already tried to implement some checks(e.g. Every 10 seconds only 10x the observer will do something)  to prevent this, but as it’s hard to cache a element that’s changes it’s attributes constantly. I thought about Pinterest Save Button extension implementing a check if the style has actually changed. As we only added `--darkreader-inline-border-top: initial; --darkreader-inline-border-right: initial; --darkreader-inline-border-bottom: initial; --darkreader-inline-border-left: initial;`(For this case whereby the iFrame was the target) and the other ones where still intact and the same and still had the `!important`(what seems to be the purpose of the observer).

If their are any ideas or plans I’m glad to hear!

Regards,
Gusted

```

I will let it know when something changes.

Regards,
Gusted

**Comment by Gusted** [comment]
Open up a PR to resolve this problem, #3865 its up for Review to be tweaked just right and than be merged. No ETA.

Regards,
Gusted
