### ISSUE TITLE
Unable to locate Project's Debug folder 

### ISSUE THREAD

**Issue by BhuvanViswanTrinity** [darkreader/darkreader#1223]
I am trying to install DarkReader using Drag and drop via Chrome extension by clicking Load Unpacked button on chrome and looking to navigate to Project's Debug version. But I am unable to locate it after unziping the download.  It says "Manifest file is missing or unreadable
Could not load manifest." when I point to any folder inside it, especially the src folder. Please help

**Comment by alexanderby** [comment]
Have a look at these instructions https://github.com/darkreader/darkreader#adding-new-features-or-fixing-bugs

**Comment by BhuvanViswanTrinity** [comment]
This is the instruction I followed.
Chrome

Open the chrome://extensions page. Disable the official Dark Reader version. Enable the Developer mode. Click Load unpacked extension button, navigate to project's debug/ folder.
