### ISSUE TITLE
Dynamic mode, Firefox: archlinux.org isn't always dark

### ISSUE THREAD

**Issue by linuunix** [darkreader/darkreader#1224]
If I navigate to[ archlinux.org](https://www.archlinux.org) the page is initially light, after reloading it turns dark (screenshot), but not the dark color used to be, which you can see in the sub-domain [aur.archlinux.org ](https://aur.archlinux.org).  ~~Sometimes the page and some of the subdomains like [archlinux.org/packages](https://www.archlinux.org/packages/?sort=-last_update) remains light color after reload.~~   
On chromium browser, it just works...    

Edit: What I mean is all [xyy].archlinux.org are correctly themed, but not the home page and "sub pages" archlinux.org/[xyz]/
![20190405_173747](https://user-images.githubusercontent.com/20864876/55642295-60c75100-57d0-11e9-8926-41f2de02cfb8.png)
![20190405_173827](https://user-images.githubusercontent.com/20864876/55642275-5442f880-57d0-11e9-89f7-278feb45b507.png)

**Comment by polyzen** [comment]
An alternative: https://userstyles.org/styles/155701/arch-linux-dark-2018

Unmaintained and might have issues (though none I can think of off the top of my head).

**Comment by L1pE** [comment]
I'd like to add, in my experience, dynamic mode is even finickier doesn't darken on the "packages" subpage after reloading, only after toggling the extension, same with the "security" page. Filter mode always works, filter+ turns the home, "packages" and "security" pages completely black but works on others, and static mode also works on all.

**Comment by ArielRosenfeld** [comment]
possibly firefox limitation see [bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) it also mentions the [contentScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) and 
[Sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) as fixes

**Comment by carloza** [comment]
february 2020, this problem not fixed

**Comment by Racle** [comment]
Probably related to https://github.com/darkreader/darkreader/issues/2065 

> possibly firefox limitation see [bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) it also mentions the [contentScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) 

And disabling CSP doesn't work (https://github.com/darkreader/darkreader/issues/1806#issuecomment-576125144), if disabling CSP even is related to that bug :)

**Comment by Gusted** [comment]
Did a simple diffrence 
red = a.html(darkreader on but didn't darken)
green = b.html(darkreader on and did darken)
![](https://i.imgur.com/igVbV6y.png)

**Comment by Gusted** [comment]
Seems some misplaced stylesheets from darkreader...

**Comment by Gusted** [comment]
![](https://i.imgur.com/ZWNb55d.png) 
Seems to do the trick
```
================================

archlinux.org

CSS
html, body, body * {
    background-color: #181a1b !important;
    border-color: #595959 !important;
    color: #e8e6e3 !important;
}

================================
```

**Comment by Gusted** [comment]
The fallback wasn't setted first time IDK Why. Will make a fix for it If chromium based browsers work along this fine.

**Comment by Gusted** [comment]
If someone can confirms this works than this issue can be closed as I can't make a global fix for this, as This fix will break chromium based browsers.

**Comment by linuunix** [comment]
What I don't understand is why it works as it is on [AUR](https://aur.archlinux.org) but not on the [home page](https://www.archlinux.org)?

**Comment by Gusted** [comment]
If I would know I would told you and provided a fix, but for now it's a mystery.

**Comment by linuunix** [comment]
IDK if it hat something to do with this but on the home page pressing F12 (dev tools) and under Style editor, clicking on the + for create and append a new style sheet, comes an error "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”)." Which doesn't happen on the sub domains.

**Comment by Gusted** [comment]
> IDK if it hat something to do with this but on the home page pressing F12 (dev tools) and under Style editor, clicking on the + for create and append a new style sheet, comes an error "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”)." Which doesn't happen on the sub domains.

Intresting but that won't explain why it's fixed after reload.

**Comment by Gusted** [comment]
After letting exceptions to pause darkreader I'm seeing some error's that don't persist in aur.archlinux.com Maybe a Fix will be created If I can get to the orgin of this error.

**Comment by linuunix** [comment]
Even after reload it is not really fixed, if you look at the top of the page, it is not as it should be, kind of broken...
For the moment I just took some code from the addon itself and put it in UserContent.css, which fixes the most part, but the top is not styled :(    
```
/* archlinux.org: Taken from Darkreader addon style */
@-moz-document url-prefix("https://www.archlinux.org") {
@media screen {
    
/* Leading rule */
html {
    -webkit-filter: invert(100%) hue-rotate(180deg) contrast(110%) sepia(10%) !important;
    filter: invert(100%) hue-rotate(180deg) contrast(110%) sepia(10%) !important;
}

/* Reverse rule */
img,
video,
:not(object):not(body)>embed,
object,
svg image,
[style*="background:url"],
[style*="background-image:url"],
[style*="background: url"],
[style*="background-image: url"],
[background],
twitterwidget {
    -webkit-filter: invert(100%) hue-rotate(180deg) !important;
    filter: invert(100%) hue-rotate(180deg) !important;
}
[style*="background:url"] *,
[style*="background-image:url"] *,
[style*="background: url"] *,
[style*="background-image: url"] *,
input,
[background] *,
img[src^="https://s0.wp.com/latex.php"],
twitterwidget .NaturalImage-image {
    -webkit-filter: none !important;
    filter: none !important;
}

/* Font */
* {
    -webkit-text-stroke: 0.5px !important;
    text-stroke: 0.5px !important;
}

/* Text contrast */
html {
    text-shadow: 0 0 0 !important;
}

/* Full screen */
:-webkit-full-screen, :-webkit-full-screen * {
    -webkit-filter: none !important;
    filter: none !important;
}
:-moz-full-screen, :-moz-full-screen * {
    -webkit-filter: none !important;
    filter: none !important;
}
:fullscreen, :fullscreen * {
    -webkit-filter: none !important;
    filter: none !important;
}

/* Page background */
html {
    background: rgb(0,0,0) !important;
}
    
}
    
}
/* archlinux.org */
```

**Comment by Gusted** [comment]
Firefox + sheets property = problem Probably

**Comment by Gusted** [comment]
The style taken from the addon is filter.

**Comment by Mukundan314** [comment]
Probably Related, same type of problem on https://pypi.org too
![20200422_22h38m59s_grim](https://user-images.githubusercontent.com/30190448/80012025-4dc21480-84ea-11ea-8380-13ea4f6c37dc.png)

**Comment by Gusted** [comment]
@Mukundan314 nope it's related to #2347

**Comment by Gusted** [comment]
Hi their, we had some progress on #2347 I saw and it was an CSP issue that has been solved :D 
And after taking a quick test it's working and if you can test it yourself with 4.9.7 darkreader :)
Why aur.archlinux.org worked? It had not setted any CSP

**Comment by linuunix** [comment]
Finally, it works!. Many thanks to anyone involved.
