### ISSUE TITLE
[Feature Request] Add a button for options

### ISSUE THREAD

**Issue by WiLuX-Source** [darkreader/darkreader#12258]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

I think the title is enough. add a options button for popup.html.

I have a friend who needed to export the sites but couldn't. After a little bit of digging up we saw exporting actually exist and it is in this url `moz-extension://uuid/ui/options/index.html`

We really struggled with this like about 1 or 2 hour.

**Comment by alexanderby** [comment]
You need to enable to use the design preview through Dev Tools and then you should see a button.

**Comment by WiLuX-Source** [comment]
Please add this button to old design as well. People forget this kind of stuff.
