### ISSUE TITLE
[Broken Website] OVH images not display well

### ISSUE THREAD

**Issue by Fr-Dae** [darkreader/darkreader#12267]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

as you can see on the ovh site, the images are not displayed correctly. 

### Website Address

https://www.ovh.com/manager/#/hub

### Steps To Reproduce

go to ovh

### Screenshots

![Capture d’écran du 2024-02-07 14-38-04](https://github.com/darkreader/darkreader/assets/23202421/a8f6a072-711d-4c1c-89b2-efea6efd2f2f)

### Operating System

Lubuntu 22.04

### Web Browser name and version

Firefox 122.0.1

### Dark Reader version

4.9.76

### Additional Context

**OS:** Ubuntu 22.04.3 LTS x86_64 
**Host**: GL552VW 1.0 
**Kernel:** 5.15.0-92-generic 
**Resolution**: 1920x1080, 1050x1680 
**DE:** LXDE 
**WM**: Openbox 
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz 
**GPU**: Intel HD Graphics 530 
**GPU**: NVIDIA GeForce GTX 960M 
**Memory**: 11144MiB / 15412MiB

**Comment by Myshor** [comment]
Not sure if we will be able to fix anything. This site needs login to use and there is no free option to create account.

Without analysing the page with deeper look into browser developer tools to check what can cause problems it's not possible to fix anything.

**Comment by Fr-Dae** [comment]
i see some free possibility.
https://www.ovhcloud.com/fr/public-cloud/mongodb/

and make a account should be free too.

**Comment by Myshor** [comment]
I managed to open dashboard without any project created and could not reproduce your problem:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/0b930941-878e-477c-bd55-6a2fc7e13d90)

The icons use specific font-family that can break if you force font in Dark Reader.

I will add this font to sitefixes to use it always for this kind of icons. 😉

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Fr-Dae** [comment]
![Capture d’écran du 2024-02-21 08-00-16](https://github.com/darkreader/darkreader/assets/23202421/f8acd4f6-2ec6-4b4e-9cfb-b78d6a3d94ba)
if i desable this checkbox, the website work fine

thanks you
