### ISSUE TITLE
[Bug] contrast for game pieces are very low with enabled dark reader

### ISSUE THREAD

**Issue by Frank-Buss** [darkreader/darkreader#12269]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

The contrast for game pieces are very low with enabled dark reader, nearly not distinguishable anymore.

### Website Address

https://frank-buss.de/tmp/darkreader.html

### Steps To Reproduce

Open the webpage and enable Dark Reader, with default settings.

### Expected Behavior

The contrast between the black and white pieces should be higher.

### Actual Behavior

The contrast between the black and white pieces is too low.

### Screenshots

Original page looks like this:
![Screenshot_20240208_003304](https://github.com/darkreader/darkreader/assets/55055211/127efc99-8879-4157-b667-a95742c7e9d1)
With Dark Reader it looks like this:
![Screenshot_20240208_003337](https://github.com/darkreader/darkreader/assets/55055211/bee860da-b934-4447-bb67-cb7daec32d4d)
Nearly no contrast anymore between the black and white pieces.

### Operating System

Linux

### Web Browser name and version

Google Chrome Version 121.0.6167.139 (Official Build) (64-bit)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
For the tmp page you gave URL the CSS fix will work:
```
.white-stone {
    background-color: white;
}
```
But to be sure it will work fine on the page I should go to the original URL with the game and check fix there.

**Comment by Frank-Buss** [comment]
@Myshor I tried it:
https://frank-buss.de/tmp/darkreader2.html
and doesn't work.

**Comment by strager** [comment]
Try this:
```css
background-color: var(--background-color);
--darkreader-bg--background-color: #ccc !important;
--background-color: white;
```

When Dark Reader is enabled, it overwrites the above with the following rules:
```css
background-color: var(--darkreader-bg--background-color);
--darkreader-bg--background-color: #ccc !important;

/* Untouched: */
--background-color: white;
``` 

I don't know if this is a supported workaround. 🤷‍♀️

**Comment by Frank-Buss** [comment]
thanks, works
