### ISSUE TITLE
highlight not displaying properly in safari

### ISSUE THREAD

**Issue by therealssj** [darkreader/darkreader#1226]
highlighted text on medium is not displayed properly unless you turn off and turn on the dark reader again

Here is a recording of the issue
http://recordit.co/bDpxSRoGJc

**Comment by avin-shum** [comment]
Same issue is happening in Chrome as well.
![image](https://user-images.githubusercontent.com/26566184/56549473-6802a300-65b5-11e9-93a2-cc0419310fd3.png)

**Comment by alexanderby** [comment]
Fixed some time ago.
