### ISSUE TITLE
Dark Reader stuck on "Loading... Please wait"

### ISSUE THREAD

**Issue by madlitch** [darkreader/darkreader#1227]
Same problem as #700, however on different browser and different OS. It worked fine for a while, yet stopped working today. Tried uninstalling/restarting browser/reinstalling, to no avail. 

I'm running Firefox 66.0.2 and macOS 10.14.1 (18B75).

In the console, the following errors show up when the extension is enabled, without loading a website:

`$sync is undefined index.js:1611
    loadSettingsFromStorage moz-extension://bba01475-5fcb-0841-b3eb-0977e83db085/background/index.js:1611
    apply self-hosted:4634
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:752
    withLastError resource://gre/modules/ExtensionCommon.jsm:676
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:744
`

`Unchecked lastError value: Error: An unexpected error occurred index.js:1609
    loadSettingsFromStorage moz-extension://bba01475-5fcb-0841-b3eb-0977e83db085/background/index.js:1609
`

After loading a site, these two show up:

`TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More] ExtensionContent.jsm:490:18
`

`port.sender.tab is undefined index.js:1443
    TabManager moz-extension://bba01475-5fcb-0841-b3eb-0977e83db085/background/index.js:1443
    apply self-hosted:4634
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2246
`

**Comment by Gusted** [comment]
Solved a long time ago....
