### ISSUE TITLE
[Bug] Dark Mode Doesn't Work Properly with Google Search AI Info Box

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [darkreader/darkreader#12288]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

![image](https://github.com/darkreader/darkreader/assets/63704404/ebb3f857-f7a3-48f2-9522-c599c208fff7)
Like the picture shows, everything other than this AI generated info box looks fine. Somehow this part just doesn't work.

### Website Address

https://www.google.com/search?q=photoshop+generative+fill+available+regions

### Steps To Reproduce

1. Open Google
2. Go to [Search Labs](https://labs.google.com/search/experiments?source=hp) and enable SGE
3. Search anything

### Expected Behavior

SGE box should be dark as well

### Actual Behavior

SGE box isn't rendered properly

### Operating System

Windows 11

### Web Browser name and version

Cent Browser, Version 5.0.1002.354 (Official Build) (64-bit) (Chromium 102.0.5005.167)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
There was something like that already submitted 2 days ago in #12275 

Someone who has access to Search Labs will need to take a look at this. I don't still have this option visible.

**Comment by Myshor** [comment]
And you can read comments in other issue. One about the code that has some personal info in it so not everyone would like to share it that we could analyse it.

Second comment is that you can enable Dark mode for google and then it will work fine.
