### ISSUE TITLE
[Broken Website] Missing icons for sharepoint.com

### ISSUE THREAD

**Issue by SJNBham** [darkreader/darkreader#12283]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

About sometime this week (Feb 5-9) or last, certain icons began being replaced with boxes when looking at SharePoint Online lists and editing pages. It's happening in different M365 tenants, different workstations, and different browsers (Edge/Chrome/Firefox).

### Website Address

https://*.sharepoint.com

### Steps To Reproduce

Log in to Office.com
Go to a SharePoint site
View a site list
Toggle the DarkReader extension on and off
The icons for the New button will be replaced with some kind of placeholder. 
You can also edit any SharePoint Online site page and you'll see many more instances where the icons are no longer working.

### Screenshots

![off](https://github.com/darkreader/darkreader/assets/11393597/33efb154-2116-48b0-b55a-9eccf628a3b3)
![on](https://github.com/darkreader/darkreader/assets/11393597/0f74394b-6806-4bfa-9f9f-c508fa7483ed)
![image](https://github.com/darkreader/darkreader/assets/11393597/c931a015-4dc5-40d8-b693-7000744bc0a1)
![image](https://github.com/darkreader/darkreader/assets/11393597/3c14fb2e-b16c-4bab-8487-d7654f259052)

### Operating System

Windows 10 (64-bit)

### Web Browser name and version

Microsoft Edge Version 121.0.2277.112 (Official build) (64-bit)

### Dark Reader version

Version 4.9.77

### Additional Context

Thanks for looking into this!

**Comment by Myshor** [comment]
As I presume you force your own font in Dark Reader.

The issue for changed font for icons was already mentioned in #12239 and I pushed fix for that in #12260 

How to get sitefixes faster:
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Myshor** [comment]
@SJNBham can you get latest site fixes and check if it's already fixed?

**Comment by SJNBham** [comment]
Hi @Myshor - Thank you for the quick response! We figured out what was going on here. We don't use a custom font but we do use multiple browser profiles in Edge. We needed to switch to the new design preview mode and turn the site fix sync on for each of our browser profiles. Once we did that, this issue was fixed. Thanks for the excellent support ;)

**Comment by ScottBeeson** [comment]
This is a problem on all MS admin sites, for instance I'm looking at https://compliance.microsoft.com/ and https://security.microsoft.com/ right now (after enabling sync site fixes as mentioned above). They still have blue squares for many of the icons. What should I do about this?

In the inspector, I can just disable the following CSS and they immediately are correct again. This happens across all MS sites I've found.

![image](https://github.com/darkreader/darkreader/assets/108358/2eb975e1-ba3a-4f64-9a97-4825cf7ab7fa)

**Comment by Myshor** [comment]
Ok... Microsoft uses different family fonts for their .ms-Icon on different sites.
I will move this font forcing to sharepoint only.

**Comment by Myshor** [comment]
Update to latest sitefixes. Now it should work fine as the forcing is moved from `*` section. 😉

**Comment by ScottBeeson** [comment]
Restarted my browser. Checked compliance.ms.com, security.ms.com, and even companyname-admin.sharepoint.com.  All have missing icons still.  Is there something else I need to do?

**Comment by Myshor** [comment]
Can you check what you have in Dark Readers Developer Tools in fixes under `*` section?

When you scroll dow it should not include .ms-icon part like this:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/40af6879-bb06-433b-9f8e-6ba14b813277)

**Comment by Myshor** [comment]
If it include then you don't have newest fixes and you need to check if you have "Synchronize sitefixes" option checked here (only in new design):
![obraz](https://github.com/darkreader/darkreader/assets/56877029/97170e8f-ffd6-4dfd-9517-77c048d02615)

Last thing is when nothing help is to click "Reset Changes" in Developer Tools. This will force to set default sitefixes for release (or get latest if above option is checked).

**Comment by ScottBeeson** [comment]
Yes, that is enabled and has been since yesterday when I first noticed this issue.

**Comment by ScottBeeson** [comment]
Okay something fixed it. It was like I was in the menus, I hadn't even clicked "Reset changes" yet. Not sure what I did but the icons showed up immediately. ¯\_(ツ)_/¯

**Comment by briangunther** [comment]
I am having this exact issue, and I have followed the advice in this thread, but to no avail. My icons are still missing in dark mode w/ dark reader. I have enabled every setting mentioned here, I have restarted the browser, restarted the computer, etc., but still no icons. Any other suggestions?

**Comment by Myshor** [comment]
@briangunther 

If you have new design enabled and sitefixes synchronization but still new fixes doesn't come then you can have something saved in Dark Reader's developer tools.

Go to Developer tools in New Design using Settings from Dark Reader popup showing when you click on extension icon.
Then in new tab with options go to advanced. There is the last button for Developer tools.

In Developer Tools window click "reset changes" button.

Just like in this comment => https://github.com/darkreader/darkreader/issues/12283#issuecomment-1961411269

You can check if .ms-icon is visible in `*` part of developer tools.

Just like this comment => https://github.com/darkreader/darkreader/issues/12283#issuecomment-1961405903

As there was already at leaset three versions of sitefixes for Sharepoint icons then before doing anything further I just want to be sure the newest sitefixes are included in your Dark Reader.

**Comment by Myshor** [comment]
OK... so you have newest fixes...

I don't have sharepoint access yet.
I think that microsoft changed their font-familiy to the .ms-Icons

Can you open problematic site with Dark Reader disabled then analyze the icons with right click on them and select "Analyze / Inspect" or something similar that will open browser Developer Tools.

Then in Styles section search for .ms-Icon and make a screenshot for that?

I just want to be sure I will see original font-family for the icons.
(Just like in example below for .google-symbols)
![obraz](https://github.com/darkreader/darkreader/assets/56877029/4cf23189-b57a-44da-9175-08c55dec5803)

**Comment by Myshor** [comment]
@briangunther change of plans... Check if icons works fine with newest sitefixes (it removes part from your second screen).

As this font force was done for people that using font change in Dark Reader then if removing force will help you then we will think about another solution how to not change icons when font is selected and enabled in Dark Readers options.

Just give back feedback if that fix with remove helps your problem.

**Comment by briangunther** [comment]
@Myshor yes, that did it! Icons are back with Dark Reader enabled for me. Thank you!!

**Comment by Myshor** [comment]
OK... I close the issue. Now when someone will tell that icons are not shown I will ask if custom font is used. 🙂
