### ISSUE TITLE
[Broken Website] GMail Compose Formatting Buttons are black on dark background

### ISSUE THREAD

**Issue by boris-bc** [darkreader/darkreader#12280]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/darkreader/darkreader/assets/63061368/24f736f1-5a05-4fd4-bfeb-388ef3855e61)

### Website Address

https://mail.google.com/

### Steps To Reproduce

1. Configure dark dynamic theme in Dark Reader.
2. Start composing a new email or a reply.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/63061368/68df4d88-b8ca-4f70-9475-8e90ae9a0df9)

### Operating System

macOS 14.3.1 (23D60)

### Web Browser name and version

Chrome Version 121.0.6167.160 (Official Build) (x86_64)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
Can you check other browser (i.e. Firefox) too? I think it will be MacOs related as I can not reproduce it on Windows 11 in Chrome and Firefox.

![obraz](https://github.com/darkreader/darkreader/assets/56877029/c6b62775-c71f-4e15-b6e2-7a0dbb3280d2)

**Comment by boris-bc** [comment]
Firefox 122.0.1 with Dark Reader 4.9.77 on the same laptop works fine. Maybe it's a Chrome on macOS issue.

<img width="742" alt="image" src="https://github.com/darkreader/darkreader/assets/63061368/37a1f199-a3be-4a9e-ad57-eb0eea298f99">

**Comment by boris-bc** [comment]
But wait... I just tested it on the latest Chrome again and it's fine:
<img width="808" alt="image" src="https://github.com/darkreader/darkreader/assets/63061368/c996e4cb-5a88-47cc-bc95-51bcda1885ed">

I don't know what changed...

**Comment by Myshor** [comment]
It could be that Dark Reader updated in your browser. Sometimes I have some strange issues just after update and everything goes to normal after browser is restarted with new version.

But in the end as it works fine... can we close it?

**Comment by Myshor** [comment]
And again I can not reproduce on my windows PC.

Maybe @alexanderby will be able to do something with this.

**Comment by boris-bc** [comment]
And again, I ran “check for updates”, the browser got updated and the issue disappeared.
