### ISSUE TITLE
Preply.com profile text is white on white background.

### ISSUE THREAD

**Issue by lantai5** [darkreader/darkreader#12293]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Can only read text in a profile if darkreader is off. 

### Website Address

https://preply.com/en/tutor/2465926

### Steps To Reproduce

Go to https://preply.com/en/tutor/2465926 (or any other of the thousands of profiles)
scroll down a little and look at the white box on the left where the profile text can't be seen. 

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/157572214/d6451e94-2bf4-4e51-80d5-201d0c730116)

### Operating System

Windows 10

### Web Browser name and version

Firefox 122.01

### Dark Reader version

4.9.77

**Comment by lantai5** [comment]
Same issue on Chrome.

**Comment by lantai5** [comment]
It's not fixed for me.

**Comment by lantai5** [comment]
I did as you said, restarted the browser, issues remains. I will check tomorrow. Thanks for your work on this. 💝

**Comment by Myshor** [comment]
If you have more than one profile in browser I got some feedback in other issue that every profile needs that changes about synchronizing site fixes set. Maybe that the problem.

Other possibility:
If you have already added your own site fixes with "Apply" button in Dark Reader's developer tools then all new updates can be overwritten by your version of fixes.
It works only with default sitefixes which means you need to "Reset changes" in developer tools with button to fetch newer ones.

And to be sure - here you can read what is needed to set with pictures => https://github.com/darkreader/darkreader/issues/12215#issuecomment-1937078454

**Comment by lantai5** [comment]
I'm so happy!! It works. :))
