### ISSUE TITLE
[Broken Website] https://voltdeutschland.org/

### ISSUE THREAD

**Issue by PlexSheep** [darkreader/darkreader#12292]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When turned on, the whole website just becomes purple only

### Website Address

https://voltdeutschland.org/

### Steps To Reproduce

1. Go to the website
2. Enable DarkReader

### Screenshots

Without DarkReader (regular website)
![Screenshot_20240211_020122](https://github.com/darkreader/darkreader/assets/58274330/c7a85188-d3ae-4fbf-ac84-496a36c0d09f)

With DarkReader enabled
![Screenshot_20240211_020431](https://github.com/darkreader/darkreader/assets/58274330/278811dd-9b64-4a04-b67c-ecb24923559a)

### Operating System

GNU/Linux (LMDE6) and windows 10

### Web Browser name and version

Firefox 122

### Dark Reader version

4.9.77

### Additional Context

I'm on LMDE 6, a friend has the same issue on windows 10.

**Comment by CodingArctic** [comment]
i actually fixed this issue on the voltnederlands site a while back, let me find the fix and open a PR to fix

**Comment by Myshor** [comment]
@CodingArctic it's still partial fix as I compared page with DarkReader disabled and enabled and I still see some background on right-top missing and one photo missing:
Without Dark Reader:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/09f1a6ca-3e7a-4d17-b36f-84cca71680f4)

With Dark Reader:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/af5c4e84-9d43-42b8-b059-0746dbbf8177)

If you will find solution for this push new changes to your PR. If not I will try to figure it out but tomorrow. 😉

**Comment by Myshor** [comment]
I fixed all not shown things on page and merged all changes.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
