### ISSUE TITLE
[Broken Website] ScienceDirect.com

### ISSUE THREAD

**Issue by rzehumat** [darkreader/darkreader#12295]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When viewing papers (the one mentioned is a random open-access pick) in dark mode, the text does not invert colours, making the article unreadable.

### Website Address

https://www.sciencedirect.com/science/article/pii/S0001691824000490

### Steps To Reproduce

1. Go to the website
2. With Dark Reader disabled, the article should be readable, with black text on a white background.
3. With Dark Reader enabled, the article becomes black text on a black background (the exact shade being slightly different), making the text almost impossible to read.

### Screenshots

![science_direct_darkreader_fail](https://github.com/darkreader/darkreader/assets/49885819/421d4cd9-bf87-4f5e-bf08-5dfd1aae5c32)

### Operating System

Linux Mint 21.2 Victoria - Desktop MATE 1.26.0

### Web Browser name and version

Brave 1.62.162 (Chromium 121.0.6167.164 64-bit)

### Dark Reader version

4.9.77

### Additional Context

I remember it used to work correctly with Dark Reader (light text on a dark background) back in the days. 
If it's possible to install different versions of Dark Reader, I could try "bisecting" to the version where it broke. 
However, there is also an option that something changed on the website appearance (i.e. the bug not being caused by Dark Reader).

**Comment by Myshor** [comment]
As it's working fine in Firefox I could not use inverts.

But I managed to make some CSS sitefix and I will push it in a minute. 😉
It will just force colors so even in Firefox it will be fine.

**Comment by rzehumat** [comment]
> As it's working fine in Firefox I could not use inverts.

Good observation. I've tried in Firefox and confirm it indeed works fine there.

**Comment by rzehumat** [comment]
Hi @Myshor, thanks for the changes in #12299. I'm sorry for digging this up again; I forgot about it.

As of Brave 1.70.123 + Dark Reader 4.9.95 I observe
1. paper title and text displays correctly, that's greatly appreciated,
2. authors and some parts of the header (e.g. text "What do these dates mean?" and buttons' text "Add to Mendeley",...)  are still hard to read (black-ish text on dark background),
3. table captions - same as above.

Is there anything else that could be done for Brave regarding observations 2 and 3? 

Thanks for any comments on this

**Comment by Myshor** [comment]
Still I can not use INVERT so will add some CSS fixes in a minute to have it visible in both browsers.

**Comment by rzehumat** [comment]
Thanks for quick response.

**Comment by Myshor** [comment]
As I could confirm on the previous URL and using MS Edge then I was able to make some fixes. 😉
