### ISSUE TITLE
[Broken Website] messenger.com chat bubbles and photos

### ISSUE THREAD

**Issue by mxr** [darkreader/darkreader#12303]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

* Chat bubbles are cut off on one or more sides, depending on "bubble style" (lone message, top message, middle message, bottom message). See screenshots
* Photos are also cut off at the bottom

### Website Address

messenger.com

### Steps To Reproduce

* Go to messenger.com and chat with people
* Observe chat bubbles

### Screenshots

* Chat bubbles are totally or partially cut off, depending on chat colors

| DarkReader Disabled | DarkReader Enabled |
|--------|--------|
| <img src="https://github.com/darkreader/darkreader/assets/252209/42569805-7c87-454d-8741-c0b8ff391abb"> | <img src="https://github.com/darkreader/darkreader/assets/252209/c44c5c1f-58a2-4e21-939a-4ac9f051f084"> |
| <img src="https://github.com/darkreader/darkreader/assets/252209/41c80bd5-ae1c-44e8-9c6e-6b3c36563b80"> | <img src="https://github.com/darkreader/darkreader/assets/252209/942f9913-6617-4592-8d2c-15726a24351a"> | 

### Operating System

mac OS Sonoma 14.3.1 (23D60)

### Web Browser name and version

Chrome Version 121.0.6167.160 (arm64)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
Already fixed some days ago with #12273 

How to get sitefixes faster:
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by mxr** [comment]
Thank you!

**Comment by RozvM** [comment]
Problem surfaced again. ☹️
![image](https://github.com/darkreader/darkreader/assets/74600479/b8207d46-2544-446d-9176-695a80321879)

**Comment by RozvM** [comment]
Yep, sorry, I rarely restart my browser and sometimes I forget to manually sync site fixes in the menu. 😅
![image](https://github.com/darkreader/darkreader/assets/74600479/31a451ed-86be-4698-bafa-14d47ee5d6e9)
