### ISSUE TITLE
[Bug] Memory Leak

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#12308]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

On rare occasions, Dark Reader will consume all memory.  I was able to find a concrete and reproducible example of this behaviour.

### Website Address

https://lottiefiles.com/lottie-editor

### Steps To Reproduce

1. Create new Firefox profile
2. Launch Firefox
3. Go to https://lottiefiles.com/lottie-editor
4. Using whatever tool you prefer, notice that memory use is stable
5. Close the tab created in step 2
6. Exit Firefox
7. Launch Firefox
8. Install Dark Reader
9. Go to https://lottiefiles.com/lottie-editor
10. Using whatever tool you prefer, notice that all available memory quickly gets consumed

### Expected Behavior

No memory leak

### Actual Behavior

Memory leak

### Operating System

Linux

### Web Browser name and version

Firefox 115.7.0 ESR

### Dark Reader version

4.9.77

### Additional Context

Additional note: Even after closing the tab created in Step 9, memory will continue to be consumed for a period of time (duration dependent on test system configuration).

**Comment by lumynou5** [comment]
I'm not sure, but memory leak seems also happening on YouTube.

**Comment by alexanderby** [comment]
The problem with Lottie Files that all the frames for animations are defined in CSS, and Dark Reader tries to analyze them all. I made a fix for this particular website.

I will try analyzing only those images that are found on the page. Hopefully it will not cause other performance issues.

The other question is why Firefox allows the tab to consume 10GB of memory and doesn't kill the tab.
