### ISSUE TITLE
[Broken Website] Bing Math Solver

### ISSUE THREAD

**Issue by Ek2100** [darkreader/darkreader#12307]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Bing Math Solver occasionally flashes white before going dark again. I saw a report open about this however it has been untouched since Nov 30, 2023 https://github.com/darkreader/darkreader/issues/11961

### Website Address

https://mathsolver.microsoft.com/

### Steps To Reproduce

1. Open https://mathsolver.microsoft.com/
2. Type an equation

### Operating System

MacOS: 14.3.1

### Web Browser name and version

Arc For MacOS: Chromium version 121.0.6167.160

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
How to get sitefixes faster:
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
