### ISSUE TITLE
[Broken Website] kelkoo.it freezes with Dynamic theme

### ISSUE THREAD

**Issue by R4ygen** [darkreader/darkreader#12317]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The website [kelkoo.it](https://www.kelkoo.it/cerca?richiesta=test) will freeze when Dynamic theme is used.
After a while, Firefox will pop-up the error message "this website is slowing down Firefox" with a button to stop the loading.
I did test it in Edge, same thing, the page will freeze and Edge will ask you if you'd like to terminate the unresponsive page.

### Website Address

https://www.kelkoo.it/cerca?richiesta=test

### Steps To Reproduce

1. Turn on Darkreader with the Dynamic theme on
2. Go to the www.kelkoo.it website
3. Search for anything

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/49517480/f4b22598-f301-4880-a82f-b773dfef935e)

### Operating System

Windows 11

### Web Browser name and version

Firefox 122.0.1 - Microsoft Edge 121.0.2277.112

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
Same issue as #12208 

I will push the same sitefix to this page as it fixes this one too. 😉

**Comment by Myshor** [comment]
How to get sitefixes faster:
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
