### ISSUE TITLE
[Broken Website] Linux's mirror of Understanding the Linux Virtual Memory Manager

### ISSUE THREAD

**Issue by PizzasBear** [darkreader/darkreader#12315]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The various graphs' outline and text haven't been inverted by the extension while the background was. The graphs became unreadable.

### Website Address

https://www.kernel.org/doc/gorman/html/understand/understand008.html

### Steps To Reproduce

1. Install Dark Reader
2. Open the website
3. Scroll until you see a graph with black or unreadable text.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/43722034/c1dc9748-d0f9-40b6-8004-f6a263ddf89f)
![image](https://github.com/darkreader/darkreader/assets/43722034/3bcd2659-acf3-4494-bcaf-741c1f6f9662)
![image](https://github.com/darkreader/darkreader/assets/43722034/c85db83a-2ee5-4fdf-bd71-271a17eae4c2)

### Operating System

Fedora Linux 39

### Web Browser name and version

Firefox 122.0

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
First of all... I tried this page with Dark Reader disabled and it ended with dark mode and dark pictures too... So it's not Dark Reader's problem but that documentation.

I made site fix for that it will work for current state - at least with Dark Reader it will be readable.

How to get sitefixes faster:
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
