### ISSUE TITLE
Google maps does not invert canvas

### ISSUE THREAD

**Issue by kiralex** [darkreader/darkreader#1232]
Hi, 

I have an issue with google maps : the canvas does not invert correctly. I have done a fix and I will open a pull request. 

Brefore: 
![Before](https://user-images.githubusercontent.com/3044771/55825273-f8e17500-5b05-11e9-9048-9e07c63a5784.png)

After:
![After](https://user-images.githubusercontent.com/3044771/55825302-0434a080-5b06-11e9-9271-e0eb3387a1e8.png)

Hope this will helps :smile:

**Comment by kiralex** [comment]
The CI seems to not pass. I'll fix that :wink

**Comment by alexanderby** [comment]
Hi, do you think that markup differs on Linux from other operating systems?

There is already `#app-container.vasquette:not(.app-imagery-mode):not(.app-globe-mode) .widget-scene-canvas` selector that does the job, inverts scheme and doesn't invert globe or street views.

**Comment by StraggleCraft** [comment]
Any update on this issue?

**Comment by Gusted** [comment]
@StraggleCraft If you have darkreader 4.9.9 It should be fixed.

**Comment by Gusted** [comment]
#2497
