### ISSUE TITLE
[Performance Issue] Can't use the shortcut to toggle dark mode when automatic selected

### ISSUE THREAD

**Issue by lucifermickelson** [darkreader/darkreader#12325]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

Dark mode toggle shortcut is disabled when automatic mode is chosen.
<img width="285" alt="SCR-20240216-pcfe" src="https://github.com/darkreader/darkreader/assets/81559076/7a3b6864-5e44-4c9c-97a7-16745f97a9ab">

### Website Address

google.com

### Steps To Reproduce

<img width="285" alt="image" src="https://github.com/darkreader/darkreader/assets/81559076/66b16352-3cb4-4e7a-b4cb-f246d12d03ba">

### Performance Profile

<img width="285" alt="image" src="https://github.com/darkreader/darkreader/assets/81559076/b4bdc16a-0be1-40a4-afce-5938e2e3b45e">

### Screenshots

<img width="285" alt="image" src="https://github.com/darkreader/darkreader/assets/81559076/b64c1231-3c1f-46e9-9f95-6c01bbaefab9">

### Operating System

mac os 14.2.1

### Web Browser name and version

All chromium browser chrome edge arc 

### Dark Reader version

4.9.77

### Does this happen when Dark Reader is disabled?

Yes

### Does this happen in other web browsers?

Yes

### Additional Context

Please fix it asap, in the earlier version when auto selected, we can still use shortcut to specially switch between theme on a website

**Comment by Myshor** [comment]
Same on Windows. I can not confirm it was working earlier as I never used keyboard shortcut.

I can only add that enabling/disabling manually from Darkreader panel enables the shortcut (as it disables auto).

**Comment by alexanderby** [comment]
The fix will be published soon.
