### ISSUE TITLE
[Broken Website] utas.hu

### ISSUE THREAD

**Issue by RozvM** [darkreader/darkreader#12334]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The map is in bright colours.

### Website Address

https://utas.hu

### Steps To Reproduce

Open the website, optionally you can click on buses and stations/stops.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/74600479/d7349b72-dc0a-4e7a-b3cb-c8c7f6de9e50)
![image](https://github.com/darkreader/darkreader/assets/74600479/326cd423-d8eb-4cc1-bd6f-ce1e18d940b3)
![image](https://github.com/darkreader/darkreader/assets/74600479/bee01cef-2a1e-42c1-a61c-a3b36eb7d3c7)

### Operating System

Windows 10 Pro N | 22H2 | 19045,4046

### Web Browser name and version

Mozilla Firefox 122.0.1 (64-bit)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
