### ISSUE TITLE
[Broken Website] futar.bkk.hu

### ISSUE THREAD

**Issue by RozvM** [darkreader/darkreader#12333]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The map is in bright colours.

### Website Address

https://futar.bkk.hu

### Steps To Reproduce

Open the website and optionally click on vehicles or stations/stops.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/74600479/bcf06338-c712-4eb0-97f8-de684b2cd6cd)
![image](https://github.com/darkreader/darkreader/assets/74600479/a3b83d6f-6c9b-41b6-8bf9-90782c707727)
![image](https://github.com/darkreader/darkreader/assets/74600479/e7eaa6af-d7d1-4690-a165-fc220d33d624)
![image](https://github.com/darkreader/darkreader/assets/74600479/0c027ba9-3e4e-407f-b001-c5a6cac21031)

### Operating System

Windows 10 Pro N | 22H2 | 19045,4046

### Web Browser name and version

Mozilla Firefox 122.0.1 (64-bit)

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
