### ISSUE TITLE
[Broken Website] https://www.netlify.com/pricing/

### ISSUE THREAD

**Issue by flexxgaad** [darkreader/darkreader#12345]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White text on white background in the "Netlify Core Feature List" section

### Website Address

https://www.netlify.com/pricing/

### Steps To Reproduce

Just visit the site and scroll down to Netlify Core Feature List

### Operating System

Windows 10

### Web Browser name and version

Firefox Latest

### Dark Reader version

Dark Reader Latest

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
