### ISSUE TITLE
[Broken Website] tailwindcss.com

### ISSUE THREAD

**Issue by abinoda** [darkreader/darkreader#12343]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Navigation links are not shown on desktop because Tailwind's [responsive styles](https://tailwindcss.com/docs/responsive-design) seem to break with darkreader enabled. Specifically, this means that classes prepended with `sm:`, `md:`, `lg:`, etc. do not work.

### Website Address

https://tailwindcss.com/

### Steps To Reproduce

1. Visit https://tailwindcss.com

### Screenshots

<img width="1427" alt="CleanShot 2024-02-19 at 09 57 27@2x" src="https://github.com/darkreader/darkreader/assets/50083/1031dc92-ffec-4199-891a-ac5b4a67d2dc">

### Operating System

MacOS

### Web Browser name and version

Chrome v121

### Dark Reader version

1.4.10

### Additional Context

Another way to reproduce the issue is to go to https://play.tailwindcss.com and enter the following HTML. This works when darkreader is disabled but not when it is enabled:

```
<div class='hidden sm:block'>
  hi
</div>
```

**Comment by abinoda** [comment]
This same issue is affecting all websites that use tailwindcss, for example:

- https://planetscale.com/
- https://cloudcannon.com/
- https://getdx.com/

**Comment by Myshor** [comment]
Can you try it with Firefox too? Cause I can not reproduce neither in Chrome or Firefox using Windows 11.

![obraz](https://github.com/darkreader/darkreader/assets/56877029/ac81a7a6-6640-4e74-bd68-fa3fabd60a56)

I just want to confirm if this is MacOS issue or just Chrome in MacOS.

**Comment by abinoda** [comment]
@Myshor I tested the Firefox extension and was not able to reproduce the issue there. So could be only Chrome and other browsers that use the same engine.

**Comment by Myshor** [comment]
I have one more question.

You mentioned: 

> ### Dark Reader version
> 
> 1.4.10

What version is this? There should be later version in chrome web store: https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by abinoda** [comment]
That's very interesting. I just installed it on a different computer's Chrome browser and I see the latest version is 4.9.77 and I'm not seeing the issues I reported.

This is weird because I just installed the extension earlier this week on my other computer, too. Let me go check that again.

**Comment by abinoda** [comment]
Ok this is very odd - on my laptop, where I installed the extension earlier this week, I somehow ended up with v1.4.10. How's this possible?

<img width="697" alt="CleanShot 2024-02-21 at 07 59 04@2x" src="https://github.com/darkreader/darkreader/assets/50083/996fcde8-8c91-4f00-8dec-95ec3bc09889">

**Comment by Myshor** [comment]
As you can see looking on the icon. It's not our official extension - someone made his own and included "Dark Reader" in the description.

So yes... We can't do anything with any other "Dark Readers" 🙂
