### ISSUE TITLE
[Broken Website] Excel sharepoint is no longer dark mode 

### ISSUE THREAD

**Issue by Fanatiikon** [darkreader/darkreader#12350]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The cells are no longer dark mode in most sharepoint excel sheets i use for work.

### Website Address

Can't provide as I don't want to dox myself.

### Steps To Reproduce

1. Proceed to sharepoint excel sheet
2. Observe the cells are white

### Operating System

Windows 10

### Web Browser name and version

Chrome 121.0.6167.185

### Dark Reader version

4.9.77

**Comment by Fanatiikon** [comment]
Updated chrome to latest version 122.0.6261.58 and issue still occurs.

**Comment by Myshor** [comment]
I tried to open some excel file in office365 and it opens with white cells but after refresh of the page it makes cells black.

So one more request. Can you check how that excels will look like after page refresh?

**Comment by Fanatiikon** [comment]
The refresh used to be the fix. But as of now if I refresh once (even on newly made workbooks by me) the cells turns black but the writing is grey(barely visible) and the custom colored cells are all grey instead of the set color of the cells. A second refresh fixes the colors but makes it so the cells are all white mode.

**Comment by Fanatiikon** [comment]
First refresh
![image](https://github.com/darkreader/darkreader/assets/76494177/75fc6aef-b456-42c7-85cf-75b4a0a2910e)|

Second/Third refresh
![image](https://github.com/darkreader/darkreader/assets/76494177/2e1ecf94-b527-4d1b-863a-e89135909898)

**Comment by Myshor** [comment]
One more question to be sure... When you open excel file from Sharepoint the url shows office.com as Office 365 or some sharepoint URL? Because if it uses Office URL then I can do some investigations as I have some access to that but if Sharepoint I will need to leave it to someone who has sharepoint access or wait a while when I will have access in my new job. 😉

**Comment by Fanatiikon** [comment]
It's xxxxxxxx-my.sharepoint.com/etc

**Comment by Fanatiikon** [comment]
Just to make sure the xxxxxxx is replaced with the company ID i can't really post that without doxing the company but I know for a fact that it worked before.

**Comment by Myshor** [comment]
The fixes for sharepoint goes to *.sharepoint.com so everything before sharepoint.com will count in.

**Comment by Fanatiikon** [comment]
Closing as Fixed as the issue no longer occurs on version 4.9.78

**Comment by luisccgoncalves** [comment]
Hello, there's a regression 4.9.80.
If I load 4.9.78 as a temporary add-on it works fine. If I restart firefox and load 4.9.80 I get a grey background with a slightly darker text, and refreshing doesn't change anything.

**Comment by Saibamen** [comment]
Now it is dark when it should not and has broken color formatting: https://github.com/darkreader/darkreader/issues/13235
