### ISSUE TITLE
Feature Request: image should not be overridden in any of the theme generating modes.

### ISSUE THREAD

**Issue by PranavBhattarai** [darkreader/darkreader#1235]
My favorite eye comfortable theme mode is: Dynamic 
By it override image in Wikipedia... 
And Wikipedia is not a small site a student/teacher can ignore.

This is how it looks on Dynamic mode in Wikipedia:
![Screenshot from 2019-04-10 10-03-13](https://user-images.githubusercontent.com/32763112/55851474-6cbc6580-5b78-11e9-8de1-444b11d40175.png)

But the original pic is:
![Screenshot from 2019-04-10 10-04-32](https://user-images.githubusercontent.com/32763112/55851492-8067cc00-5b78-11e9-9519-6d881fd2c423.png)

As u can see the image is covered and disappeared when we try all other modes except Filter and Filter+. Filter and Filter+ are not that good to look because it also makes things ugly but in a more visible way. 

![Screencast from 04-10-2019 09_56_04 AM](https://user-images.githubusercontent.com/32763112/55852391-7f389e00-5b7c-11e9-8b45-a58fce823577.gif)

**Comment by Gusted** [comment]
And this has fixed in latest version of darkreader @PranavBhattarai

**Comment by PranavBhattarai** [comment]
@Gusted That was a significant improvement. I can clearly [see that]( https://en.wikipedia.org/wiki/Proxy_server).
But still, hope problems like [this](https://en.wikipedia.org/wiki/Fourier_transform) also get solved in the future.

_Are u sure about closing this issue? I think u have fixed a big part of the problem but there another one still left._

**Comment by Gusted** [comment]
Well your specefic bug Was Wikipedia that has been fixed for other sites we are working on that

**Comment by PranavBhattarai** [comment]
@Gusted I when said, " But still, hope problems like [this](https://en.wikipedia.org/wiki/Fourier_transform) also get solved in the future."  the word "this" includes a link of Wikipedia where Dark Reader overrides something which has shouldn't have been overridden. A part of Wikipedia is the problem is solved but another one still remains unsolved.

**Comment by Gusted** [comment]
Woops.... Seems like I had a too quick look

**Comment by PranavBhattarai** [comment]
Now that u have seen the problem, shall I reopen this issue or let it remain closed?! 
@Gusted

**Comment by Gusted** [comment]
Part of the issue still persist will have a look ASAP

**Comment by Gusted** [comment]
Well, seems like it's impossible to target those while not targetting other icons etc. Who placed that image their haven't setted it the good way...

**Comment by PranavBhattarai** [comment]
@Gusted Isn't there a way to bypass images/graphs/icons? A logic where everything else's is colored except images/graphs/icons because they don't one.

> Well, seems like it's impossible
If programming is ever considered easy or taken for granted, many people would have chosen the developer profession. Sometimes things are hard to interpret and solve. 

This issue impact basically every website not just Wikipedia. If this issue is solved, the advancement of "Dark mode" will reach toward perfection. I would still not call it perfect. But toward next-level perfection indeed. 

_On the other hand, I am thinking of creating another GitHub issue which is probably impossible like you said. Basically, this concept is about, "Dark reader converting all image's white blank pages/area particularly in the manga/comic website". If u have a habit of reading mangas/comics on a laptop or mobile, you will definitely understand what I am trying to say and why this is so important. But this is hard and probably won't be implemented. Because Dark Reader should recognize image scripts that don't require any colorization and unwanted white pages/areas which should have been dark. For this, we might need AI in Dark Reader. This is a bit nut idea will certainly help millions of manga reader for sure. The dark reader will be officially declared as "medicine for eyes". Because, right now, its a big torture to read mangas/comic in a dark environment (night)._

**Comment by Gusted** [comment]
Just for knowledge we first analyze images to see if they need any invert. Mostly it's goes good but not every algorithm is good.

But if the site just make it practical the image work like icons it's hard to just target that image.

**Comment by PranavBhattarai** [comment]
"Blows people's minds, right!" - Programming.
That's all I can say. 
Leave the issue open until the times. Until someone knows who to do the trick.

**Comment by Gusted** [comment]
That's right.
I will hold this issue open and think about it. 
The whole image thing of darkreader already needed a good rewrite so I will see.

**Comment by nathanielcwm** [comment]
This image is also inverted where I believe it shouldn't
https://en.wikipedia.org/wiki/Acura_MDX#/media/File:2022_Acura_MDX_(United_States)_front_view_02.png

![image](https://user-images.githubusercontent.com/22572406/122223128-7b83cd00-cee5-11eb-8d19-6ca5655adec5.png)

**Comment by Gusted** [comment]
> This image is also inverted where I believe it shouldn't
> https://en.wikipedia.org/wiki/Acura_MDX#/media/File:2022_Acura_MDX_(United_States)_front_view_02.png
> 
> ![image](https://user-images.githubusercontent.com/22572406/122223128-7b83cd00-cee5-11eb-8d19-6ca5655adec5.png)
> 
> Actual image:
> ![i](https://camo.githubusercontent.com/9f576a2c198eba795394d591e93db544be8415f4ae9e90844fc79b71ff1c16e0/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f382f38632f323032325f41637572615f4d44585f253238556e697465645f5374617465732532395f66726f6e745f766965775f30322e706e672f3235363070782d323032325f41637572615f4d44585f253238556e697465645f5374617465732532395f66726f6e745f766965775f30322e706e67)

Has been fixed already, see: https://github.com/darkreader/darkreader#site-fixes how to get the latest fix

**Comment by artisticfox8** [comment]
> That's right. I will hold this issue open and think about it. The whole image thing of darkreader already needed a good rewrite so I will see.

When I go to https://de.wikipedia.org/wiki/Haut#/media/Datei:Schemazeichnung_haut.svg the backround is black so I can't see the black arrows describing the image

**Comment by alexanderby** [comment]
Hopefully this is fixed. If you spot an issue on a website, please report an issue or try using Dev Tools and submit a PR with a fix. Try using Dynamic mode instead of Filter.
