### ISSUE TITLE
[Broken Website] onepeterfive.com

### ISSUE THREAD

**Issue by devren-y** [darkreader/darkreader#12351]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When I visit https://onepeterfive.com/ with Dark Reader enabled, the large images disappear by each article on the home page.  I have used Dark Reader with this site for years with no problem. It works fine with Dark Reader 4.9.74, but it is broken in more recent versions (4.9.77 at time of writing).

### Website Address

https://onepeterfive.com/

### Steps To Reproduce

1. Visit https://onepeterfive.com/ with Dark Reader enabled, either in "Not invert listed" mode, or in "Invert listed mode" with this site added to the list.
2. No images are loaded with the article titles, or else they disappear after a few moments.
3. Disable Dark Reader, and all the images re-appear.
4. Re-enable Dark Reader, and all the images stay there for the time being!
5. Then scroll down the page until more articles are auto-loaded, and all the images disappear again throughout the page.

### Operating System

MacOS and Ubuntu

### Web Browser name and version

Firefox 122.0.1 and Brave 1.62.165

### Dark Reader version

4.9.77

### Additional Context

The site works fine if the extension is downgraded to Dark Reader 4.9.74, but later versions are broken.

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by devren-y** [comment]
Thanks, you guys are great!
