### ISSUE TITLE
[Broken Website] Comment text areas on canvas.*.edu sites don't invert properly

### ISSUE THREAD

**Issue by charmarkk** [darkreader/darkreader#12354]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When using Canvas sites for a given institution, it looks like some of the `textarea` elements aren't inverting properly. The font is, but the actual background of the textbox does not. 

### Website Address

canvas.*.edu (if you have an accessible instance of Canvas)

### Steps To Reproduce

1. Log into an instance of Instructure's Canvas platform
2. Navigate to a grade section, where you can enter a grade and leave comments.
3. Observe that the textarea elements' backgrounds are white with a very light gray font.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/22264269/a670cb94-eb56-4d69-a685-8cb3693b0b38)
![image](https://github.com/darkreader/darkreader/assets/22264269/228786ad-0610-41ea-bf58-2b70832b9f2e)

### Operating System

Windows 10

### Web Browser name and version

Firefox 122.0.1

### Dark Reader version

Version 5 Preview (4.9.77)

### Additional Context

I can provide CSS info if need be, as this might be a tricky place to get to.

**Comment by Myshor** [comment]
> ### Additional Context
> 
> I can provide CSS info if need be, as this might be a tricky place to get to.

That can be helpfull... if you have some CSS for that elements from developer tools. Because any fixes will need to have idea what exactly we need to INVERT or set background color.

**Comment by charmarkk** [comment]
> That can be helpfull... if you have some CSS for that elements from developer tools. Because any fixes will need to have idea what exactly we need to INVERT or set background color.

Sure thing - if what I have isn't enough let me know!

It looks like the class the comment boxes use is `.css-vrgbjj-textArea`.

Below are all the rules being applied to that particlar element, and the computed styles.

[canvas textbox computed styles.txt](https://github.com/darkreader/darkreader/files/14389588/canvas.textbox.computed.styles.txt)
[canvas textbox rules.txt](https://github.com/darkreader/darkreader/files/14389589/canvas.textbox.rules.txt)

**Comment by Myshor** [comment]
Thanks... I will do the fix from that as I see where is the problem.

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Myshor** [comment]
BTW if the fix will work for some text areas and for some not I will try to make a different selector basing on a part of class name.

**Comment by charmarkk** [comment]
That was fast!! I'll check it out!

**Comment by charmarkk** [comment]
Looks to be good in the couple places I noticed it - rock on! Will reopen if I find anywhere else that seems wonky. Thanks so much @Myshor!

![image](https://github.com/darkreader/darkreader/assets/22264269/dddef553-f7b3-4a2e-8e77-ecdb75a0d992)
![image](https://github.com/darkreader/darkreader/assets/22264269/bc085f28-eed9-40e3-beca-52a5509bf3e6)

**Comment by Myshor** [comment]
I thank you for help with CSS... Sometimes it's hard to do fixes if you don't have access to the site and explain what exactly person who submit the bug must check for us. Here it was fast look and fast try to fix. 😁

**Comment by charmarkk** [comment]
It appears that this is also a problem with the late assignment textbox (didn't notice it last time as I didn't have any late assignments 😊).
![image](https://github.com/darkreader/darkreader/assets/22264269/ffddd07f-1d7b-453e-8cfe-e5e7d9d1c504)

The class for the input element itself is `css-1tc2h4f-numberInput_input`, and its parent `span`'s class is `css-71vpxj-numberInput_inputContainer`.

**Comment by charmarkk** [comment]
It's looking good now (again) @Myshor! Thanks so much. :)

![image](https://github.com/darkreader/darkreader/assets/22264269/7778c657-fe9d-48b7-947d-2798cf9ba409)

**Comment by charmarkk** [comment]
One more area! The assignment comment textarea has the same issues. :)

The textarea's class: css-1e593au-textArea
and its parent div's class: css-18zvyld-textArea__layout

![image](https://github.com/darkreader/darkreader/assets/22264269/e8542ddf-6a44-4ce6-9419-f20aa36b046e)

**Comment by Myshor** [comment]
Changed selectors for textArea to more general... should work fine in all places where class contains '-textArea' text :)

**Comment by charmarkk** [comment]
Another new, tricky problem with these: 

on.Focus, the text seems to turn black/the same color as the inversion, but when not focused, the text inverts properly. It looks like these are the rules that get added for .focus:

```
textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
  outline-color: currentcolor;
  border-color: var(--darkreader-border--ic-link-color-lightened-10);
}
textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
  border-color: var(--ic-link-color-lightened-10);
  outline: 0;
    outline-color: currentcolor;
```

Is there anything else we should add? Maybe something for font color in the new darkreader rule?
```
[class*="-textArea"], [class*="numberInput_input"] {
  background-color: var(--darkreader-neutral-background) !important;
}
```

**Comment by Myshor** [comment]
I don't see anything in this rules that would set color of text so it hard to say...

Can you check how it will work wen you apply this change?
```
CSS
[class*="-textArea"],
[class*="numberInput_input"] {
    background-color: var(--darkreader-neutral-background) !important;
    color: var(--darkreader-neutral-text) !important;
}
```

If this will help I will merge that one more line into sitefixes.

**Comment by charmarkk** [comment]
Aha think I found it:

I tried that fix and it didn't work. BUT!

After disabling the ` --darkreader-neutral-background: #131516; ` rule, alllllll the way at the bottom in :root rules, that fixed it! With and without the `color` fix we just tried.

![image](https://github.com/darkreader/darkreader/assets/22264269/b7b9404c-49bb-486a-8dbf-be4a267a4651)
![image](https://github.com/darkreader/darkreader/assets/22264269/21898aa7-cfcb-483a-b788-995b3faeb243)

However, the `background-color` rule is still needed or else we go back to the white textarea with grayish text. If there's any files I can give you that'd be helpful let me know! Maybe just something weird with Canvas...

**Comment by Myshor** [comment]
OK... then I have different proposal to check:
```
CSS
[class*="-textArea"]:not(:focus),
[class*="numberInput_input"] {
    background-color: var(--darkreader-neutral-background) !important;
}

```
This may help or break it more (I mean set background to light one) but at least won't force this neutral background on focused textareas.

**Comment by charmarkk** [comment]
Hmm, that doesn't seem to work either. And disabling the rule at the very bottom of the stylesheet then makes the textbox white and font gray, but it does not automatically disable the --darkreader-neutral-background rule. That's the only rule I can find that's causing the problem though, and the only rule that has that color (131516).

**Comment by charmarkk** [comment]
Another development:

I think it might be the textarea's parent `div` that's casing the issue.

Here is the code inclusive of that `div`:

```
<div style="max-height: 50rem; min-height: 77px;" class="css-18zvyld-textArea__layout">
     <textarea data-selenium="criterion_comments_text" style="resize: vertical; max-height: 50rem; height: 77px; overflow-y: hidden;" id="TextArea_4" aria-required="false" class="css-1e593au-textArea">aaaa</textarea>
     <span aria-hidden="true" class="css-1r76rxr-textArea__outline" style="transition: 0.2s; width: calc(584.6px + 2.125rem); height: calc(51px + 2.125rem);"></span>
</div>
```

Removing the class from the `div` fixes the problem! So, maybe the rule is only slightly too vague. Apply it to `textarea.*textarea`s maybe?

**Comment by Myshor** [comment]
So it seems you made a fix 😁
You want to make pull request with it or I should make the changes? 😉

**Comment by charmarkk** [comment]
Got it! Github always kinda baffles me but I figured it out! Thanks for the chat and help. :)
