### ISSUE TITLE
[Broken Website] Dark Reader on ea.com RAM issue

### ISSUE THREAD

**Issue by PouekDEV** [darkreader/darkreader#12352]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

While being on ea.com and clicking on "Forgot your password, or need to create a new one?" a new tab opens, and RAM usage starts rising. Firefox reports that the Dark Reader extension is slowing it down.

### Website Address

https://ea.com

### Steps To Reproduce

1. Got to ea.com
2. Click on the profile icon and sign in. 
![obraz](https://github.com/darkreader/darkreader/assets/64737924/c824ded5-9aa6-4a6e-beb1-fc78fd43e985)
3. Click on "Forgot your password, or need to create a new one?"  
![obraz](https://github.com/darkreader/darkreader/assets/64737924/de6f627e-8ec6-434d-97bd-5faf6f1c7e32)
4. RAM usage starts rising and the page becomes unresponsive.
![obraz](https://github.com/darkreader/darkreader/assets/64737924/945eaee9-2e24-4785-b486-984f2847e2d5)

### Operating System

Windows 10

### Web Browser name and version

Firefox 123.0

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
The quick sitefix will be in a minute...

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
