### ISSUE TITLE
[Broken Website] 1.next.westlaw.com

### ISSUE THREAD

**Issue by IssueSolver1000** [darkreader/darkreader#12361]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

In Darkreader's site-specific settings, the entry for "westlaw.com" needs to be changed to "1.next.westlaw.com". The wrong URL was used when creating that site-specific setting in the earlier issue report (#9688). I have tested in my Dark Reader developer settings to ensure this is the correct fix. Right now, the fix is not being applied to the correct site.

### Website Address

1.next.westlaw.com

### Steps To Reproduce

Visit 1.next.westlaw.com

### Operating System

All

### Web Browser name and version

All

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
Ok... I add aliases *.westlaw.com and *.*.westlaw.com to sitefixes.

This sould fix the problem. 😉

**Comment by Myshor** [comment]
- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
