### ISSUE TITLE
Please update/release for firefox legacy versions (not WebExtensions version)

### ISSUE THREAD

**Issue by DarKWinGTM** [darkreader/darkreader#1237]
Please update/release for firefox legacy versions (not WebExtensions version)

Like a uBlock can choose WebExtension versions or not WebExtension versions (legacy)
https://github.com/gorhill/uBlock/releases

**Comment by DarKWinGTM** [comment]
Am using waterfox base on firefox 56 for keep using extensions not working in new versions of firefox

**Comment by Gusted** [comment]
Waterfox Legacy should work.
