### ISSUE TITLE
[Broken Website] Bad influence on the QR code

### ISSUE THREAD

**Issue by palandovalex** [darkreader/darkreader#12386]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Using dark reader affects the QR code on passport.yandex.ru

in my case, oddly enough, this did not destroy the readability of the code. Which I only found out about after I started writing this countdown. If there is time, it is worth correcting this - all you need to do is exclude the processing of the div element with the "MagicField-qr" class. 
<s>Or if you really bother, you can invert the colors, the inverse qr codes are read as well as the usual ones.</s>

### Website Address

https://passport.yandex.ru/auth/list

### Steps To Reproduce

Enter to yandex password, with previously used sessions - yandex will offer to log in using a QR code and a camera in your phone

### Screenshots

![Снимок экрана от 2024-02-28 10-08-32](https://github.com/darkreader/darkreader/assets/75374436/4be185a3-838a-4ea4-93b3-44b5b27b7c90)

### Operating System

Linux 6.5 22.04.1-mint

### Web Browser name and version

yandex browser 24.1.1.940 stable (64-bit)

### Dark Reader version

4.9.77

### Additional Context

I got div element with QR Code:

```html
<div class="MagicField-qr" data-track="24169c7056962df79caff204543809c227" style="background-image: url(&quot;data:image/svg+xml;base64,YOUR_QR_CODE_IMAGE_IN_BASE_64_FORMAT=&quot;);"><span class="MagicField-icon MagicField-icon_yandex3-ru"><span class="PasspIcon PasspIcon_yandex3-ru PasspIcon_size_l" data-t="icon:yandex3-ru"></span></span></div>
```

**Comment by Myshor** [comment]
I forced white background for QR code in sitefixes.

The fix will be available in next release.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
