### ISSUE TITLE
[Broken Website] Some text (lower portions, reviews) on Meijer websites does not invert correctly

### ISSUE THREAD

**Issue by charmarkk** [darkreader/darkreader#12402]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Simply the title. The text on the lower areas/review areas of Meijer product pages does not invert correctly, and is difficult to read. The classes used on the text seem to vary wildly/are autogenerated per element, so that might be less than ideal.

### Website Address

https://www.meijer.com/shopping/product/meijer-garlic-texas-toast-14-oz/71928365698.html

### Steps To Reproduce

1. Navigate to a Meijer product page (see example URL here)
2. Observe improperly inverted text near the bottom of the pages.

### Screenshots

<img width="1295" alt="image" src="https://github.com/darkreader/darkreader/assets/22264269/4534b4d6-1d8e-4f01-bad1-a85ea2acce07">

### Operating System

Windows 10/macOS

### Web Browser name and version

Firefox 122.0.1

### Dark Reader version

Version 5 Preview (4.9.77)

**Comment by charmarkk** [comment]
There are some issues on the checkout pages too:
<img width="676" alt="image" src="https://github.com/darkreader/darkreader/assets/22264269/a2571ccf-8b33-45c0-9035-cd32eadb7e4d">

**Comment by Myshor** [comment]
I end with:
Access Denied
You don't have permission to access "http://www.meijer.com/failover/sitedown.html?" on this server.

Reference #18.1df95568.1709639519.92a1f298 

Maybe someone else will confirm.
