### ISSUE TITLE
[Broken Website] important graphics on website (supercoach.heraldsun.com.au/afl/) not rendered correctly

### ISSUE THREAD

**Issue by U99c** [darkreader/darkreader#12417]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

website: 
fantasy sport site Supercoach

issue: 
Team icons, accessible once logged into an account, are not rendered correctly when Dark Reader is enabled.  Given the purpose of this site, having wonky team graphics is not ideal.  

### Website Address

supercoach.heraldsun.com.au/afl/

### Steps To Reproduce

1. direct browser to website
2. create account
3. log in
4. select classic
5. a pop up menu appears.  follow prompts, agree to terms and conditions,  and click 'start creating my team'.  if a phone number is required, providing any 10 digit number should suffice.
6. click the 'x' to skip the welcome to supercoach menu
7. switch dark reader on and off.  when enabled, we can see the icons next to players' names do not look like they should.  

### Screenshots

![Untitled](https://github.com/darkreader/darkreader/assets/64569655/60c46b1b-a586-434c-b3d2-29abb34804ae)

### Operating System

Windows 10 & 11

### Web Browser name and version

Firefox 123.0

### Dark Reader version

4.9.77

### Additional Context

attempted fixes:
using another browser installation on another PC - same issue arises.
using filter, filter+, static and dynamic modes - provides no acceptable positive result.

**Comment by Myshor** [comment]
The fix will be available in next release.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
