### ISSUE TITLE
[Bug] Installing 4.9.78 on Firefox: "This add-on could not be installed because it has not been verified."

### ISSUE THREAD

**Issue by R8s6** [darkreader/darkreader#12422]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

4.9.78 wasn't available on FF add-on store, so I tried to install 4.9.78 from github release page, I got this error:
```
about:addons
This add-on could not be installed because it has not been verified.
```

When I tried to build it myself, I got this:
```
$ npm run build -- --firefox --version=4.9.78

> darkreader@4.9.78 build
> node --max-old-space-size=3072 tasks/cli.js build --release --firefox --version=4.9.78

Could not find signature files for version 4.9.78
```

Is it because there's no signature files under `/integrity/firefox`  in the source files?

### Website Address

N/A

### Steps To Reproduce

1. Download 4.9.78 release tarball
2. Extract
3. Drag darkreader-firefox.xpi to firefox, or select "install add-on from file" in the add-on page

### Expected Behavior

Add-on installed

### Actual Behavior

Add-on not installed with error "This add-on could not be installed because it has not been verified."

### Operating System

Archlinux

### Web Browser name and version

Firefox 123

### Dark Reader version

4.9.78

**Comment by alexanderby** [comment]
Probably yes, but even with those tokens another build is required. The add-on has finally been reviewed today, please check once again.

**Comment by nv6** [comment]
This is still a problem with 4.9.123, not sure why this is closed.

**Comment by alexanderby** [comment]
@nv6 What is your Firefox version?

**Comment by nv6** [comment]
148.0.2
