### ISSUE TITLE
[Broken Website] White boxes and white text in Gmail

### ISSUE THREAD

**Issue by sc22als** [darkreader/darkreader#12428]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Hey :)

I'm currently using the Dark Reader extension on MS Edge. Whenever I'm using Gmail and I wanna compose a new email, in the "To", "Cc", "Bcc" sections white boxes appear and the text inside them is white and close to illegible. Same goes with starting a new chat in google chat.

I've tried uninstalling and reinstalling the extension and resetting my MS edge settings.

It wasn't like this before, the extension was working fine with no white boxes; I haven't changed any settings to do with my browser nor anything to do with my gmail settings.

Can anyone help? I've attached some photos for reference.

Thanks :)

### Website Address

mail.google.com

### Steps To Reproduce

1. Open the website address
2. Try and compose an email
3. Click in “To”, “Cc” or “Bcc” section
4. White box appears

### Screenshots

![white-box-4](https://github.com/darkreader/darkreader/assets/124596080/73edd7b7-83e1-4bc5-b0b2-b1d1421380ad)
![white-box-2](https://github.com/darkreader/darkreader/assets/124596080/e62c3d6c-5f4e-4ac3-8641-23e30e5e2b69)
![white-box-1](https://github.com/darkreader/darkreader/assets/124596080/5c053150-c2b2-4373-b4c1-2714bf6c2676)
![white-box-3](https://github.com/darkreader/darkreader/assets/124596080/fb6e6524-9214-4e68-91ce-014a655ba19e)

### Operating System

Windows 10

### Web Browser name and version

MS Edge 122.0.2365.80

### Dark Reader version

Latest as of 08/03/2024

**Comment by Myshor** [comment]
I fixed TO, CC, BCC in #12443 

Still don't know how to create chat to check if this will fix this part to.
If it won't fix chats then give some steps how to make new chat.

P.S.
The fix will be available in next release.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by sc22als** [comment]
> I fixed TO, CC, BCC in #12443
> 
> Still don't know how to create chat to check if this will fix this part to. If it won't fix chats then give some steps how to make new chat.
> 
> P.S. The fix will be available in next release.
> 
> * If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> * Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
> * With that enabled newest sitefixes will be updated every browser start. 😉

Hey :) !

Thank you for your response and fix.

Unfortunately chat is still white.

The steps to create a new google chat is as follows:

1. Go to [mail.google.com](url) (assuming you're already signed in to a google account).
2. On the left side, in the navigation bar, click "Chat" / the speech bubble icon.
3. Then click where it says "New chat".
![Steps-2-3](https://github.com/darkreader/darkreader/assets/124596080/d62549b9-f623-40c2-b1a7-682be1e8e621)

4. The white box for a new chat should appear.
![Step-4](https://github.com/darkreader/darkreader/assets/124596080/4ade65e9-eea6-41e7-9f5d-c1a444fe181e)

Appreciate your hard work ! 🥰

**Comment by Myshor** [comment]
That part can be harder to fix as whole chats are iframe in gmail and iframes are not that easy to fix.
Maybe @alexanderby will think some solution for this chat issue.

**Comment by alexanderby** [comment]
That was something to do with CSS variables, I made a temporary fix and need to figure out later.

**Comment by bbinet** [comment]
I don't know if gmail chats are now fully dark for you @sc22als with @alexanderby patch?
Personally, I still experience white messages, but only for the messages that I've posted myself (messages from the recipient are correctly dark).

**Comment by Myshor** [comment]
@bbinet your issue was already submitted in #14591 

Check all comments  there because the sitefix is already added. 😉

**Comment by bbinet** [comment]
Ok, sorry for the noise, and thank you for the fix! I confirm it works perfectly for me 👍
