### ISSUE TITLE
[Broken Website] bigberthaoriginal.com Images covered

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#12430]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Images are covered by Darkreader

### Website Address

https://www.bigberthaoriginal.com/collections/bean-bag-chairs

### Steps To Reproduce

Just see

### Screenshots

![Screenshot_20240308_212246-1](https://github.com/darkreader/darkreader/assets/6344099/42a43431-5244-4b76-801e-e836ebaef54b)
![Screenshot_20240308_212233-1](https://github.com/darkreader/darkreader/assets/6344099/4f177577-516b-47db-b1af-7ad76194456f)

### Operating System

Linux / NixOS

### Web Browser name and version

Brave v1.63.165

### Dark Reader version

4.9.78

**Comment by Myshor** [comment]
The fix will be available in next release.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
