### ISSUE TITLE
[Broken Website] Intercom completely freezes with callouts

### ISSUE THREAD

**Issue by brawaru** [darkreader/darkreader#12435]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When attempting to edit an article on Intercom website, adding a callout freezes the tab completely and keeps the processor busy at ~20%.

### Website Address

https://app.intercom.com/

### Steps To Reproduce

1. Sign in to Intercom panel
2. Go to Articles
3. Create a new article
4. Attempt to add a Callout element to the article

### Screenshots

N/A

### Operating System

Windows 11 Version 23H2

### Web Browser name and version

Chromium 122.0.6261.95 (Official Build)

### Dark Reader version

4.9.78

### Additional Context

It's impossible to pause the JS execution using the DevTools.

**Comment by alexanderby** [comment]
There is a conflict with the app's script, that watches for inline style changes. I made a temporary fix it will be published soon.
