### ISSUE TITLE
[Broken Website] Dark Reader Doesn't Work for Google Play Books' PDF-like eBooks

### ISSUE THREAD

**Issue by PBHDK** [darkreader/darkreader#12434]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark Reader doesn't get applied to PDF-like eBooks on Google Play books.

### Website Address

https://play.google.com/store/books/details/Adnan_Aziz_Elements_of_Programming_Interviews?id=y6FLBQAAQBAJ

### Steps To Reproduce

1. Go to https://play.google.com/store/books/details/Adnan_Aziz_Elements_of_Programming_Interviews?id=y6FLBQAAQBAJ
2. Click on "Sample"
3. Observe

### Operating System

macOS

### Web Browser name and version

Google Chrome 122.0.6261.112 (Official Build) (arm64)

### Dark Reader version

4.9.78

### Additional Context

For anyone else facing this issue, I'm currently using the "invert" extension as an alterantive for Google Play Books: https://chromewebstore.google.com/detail/invert/heidajcpkemganilmhockdniaknoojih

**Comment by Myshor** [comment]
What I found is that whole book is preneted in iframe and iframe is always problematic for Dark Reader.

**Comment by alexanderby** [comment]
@Myshor The iframes should request fixes for their own URLs (books.googleusercontent.com in this case).
