### ISSUE TITLE
[Feature Request] dark reader is not picking layered css

### ISSUE THREAD

**Issue by ymg2006** [darkreader/darkreader#12449]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Hello, 
Dark reader is not picking css defined with layers. All of them is getting ignored.
An example could be component of primeng which css is layered in new versions. ([https://primeng.org/autocomplete](https://primeng.org/autocomplete))
I have attached screenshot for this example.

### Screenshots

![Screenshot 2024-03-14 104636](https://github.com/darkreader/darkreader/assets/844238/11c142b6-7acf-478a-9f91-a273b821b42e)

### Additional Context

[https://developer.mozilla.org/en-US/docs/Web/CSS/@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)

**Comment by alexanderby** [comment]
Thanks for the report. I recently came across these @layer rules and wondered if there are any live examples. The fix will be published in the next release.

**Comment by ymg2006** [comment]
@alexanderby thank you for the timely response.
I downloaded latest release v4.9.80 from [https://github.com/darkreader/darkreader/releases/tag/v4.9.80](https://github.com/darkreader/darkreader/releases/tag/v4.9.80) and tested it with [https://primeng.org/autocomplete](https://primeng.org/autocomplete) but I got the very same result.
Maybe second refactoring has affected it (commit 59a755f), I will be grateful if you consider testing it again.
![image](https://github.com/darkreader/darkreader/assets/844238/3784c2ae-bf75-43e8-9e02-a9b0b5bbb9bc)
