### ISSUE TITLE
[Broken Website]  http://webdav.org/projects/

### ISSUE THREAD

**Issue by LantashTheTokra** [darkreader/darkreader#12442]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Website has a light background. Darkreader changes text to light color without changing background.

### Website Address

http://webdav.org/projects/

### Steps To Reproduce

Go to website with default darkreader settings

### Operating System

OS: Fedora Linux 39 (Workstation Edition) Kernel: 6.5.6-300.fc39.x86_64  DE: GNOME 45.4 

### Web Browser name and version

LIbreWolf  123.0-1 (Firefox fork)

### Dark Reader version

4.9.78

**Comment by Myshor** [comment]
The fix will be available in next release.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
