### ISSUE TITLE
Using Dark Reader on www2.calstate.edu triggers "sign in" prompt

### ISSUE THREAD

**Issue by kevin-he-01** [darkreader/darkreader#1244]
## System Information
**Browser:** Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
**OS:** Microsoft Windows \[Version 10.0.17763.437\]

## Steps to Reproduce
1. Install Dark Reader in the browser and make sure it is correctly setup and enabled for www2.calstate.edu
2. Go to https://www2.calstate.edu/ (Main page of California State University)

### Expected Result
No sign in prompt shown
### Actual Result
A "Sign in" prompt is shown every time one visit any page under the domain www2.calstate.edu. If one click "Cancel" button, one will see `Failed to load resource: the server responded with a status of 401 (Unauthorized)` errors in the Dev Tools (Press `Ctrl+Shift+I` to show) showing that a GET request to https://www2.calstate.edu/_catalogs/theme/Forms/AllItems.aspx?RootFolder=%2f%5fcatalogs%2ftheme%2fThemed%2f7F6465EB&FolderCTID=0x00E8944B30412EDC46BF9B84F9FCB9F549 was unauthorized.

## Screenshot of The Bug
![CSU Darkreader bug](https://user-images.githubusercontent.com/32375681/56097585-41ed4c80-5eab-11e9-95a3-e2970bc99091.png)

## Workarounds
The easiest workaround would be to disable Dark Reader on that specific site by clicking "Toggle Current Site" in the Dark Reader menu (or alternatively use the keyboard shortcut, which is `Alt+Shift+V` by default) However, that means the website will not be dark.

**Comment by Gusted** [comment]
Use filter for those sites.
