### ISSUE TITLE
[Broken Website] fonts.google.com

### ISSUE THREAD

**Issue by Copy05** [darkreader/darkreader#12448]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

It seems like Google's Material Design Icons have issues displaying with dark reader on Google Fonts. to make sure that it's not just Chrome i also managed to reproduce the same issue with Edge. Instead of the Icons it displays the text.

### Website Address

https://fonts.google.com/

### Steps To Reproduce

1. Just by visiting fonts.google.com

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/71971770/a3b108bf-eb66-4e0d-b3f9-c805b6e80769)

### Operating System

Windows 10 22H2

### Web Browser name and version

Chrome Version 119.0.6045.160 & Edge Version 122.0.2365.80

### Dark Reader version

Version 4.9.78

**Comment by alexanderby** [comment]
Thanks for reporting, I noticed that recently on some Google website too. The fix will be published soon.
