### ISSUE TITLE
[Broken Website] Lots of text on Expedia does not invert correctly

### ISSUE THREAD

**Issue by charmarkk** [darkreader/darkreader#12464]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Title. Much text and content backgrounds on Expedia pages don't invert correctly.

### Website Address

expedia.com

### Steps To Reproduce

1. Go to Expedia's site
2. Observe several spots with light gray text on white backgrounds.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/22264269/2ab099a3-ca3b-41db-a004-a7f4ca62d95e)
![image](https://github.com/darkreader/darkreader/assets/22264269/59eacf33-212f-4c59-96ab-5c2f415b68e0)
![image](https://github.com/darkreader/darkreader/assets/22264269/1d3f6462-141f-4036-b375-b34e0de706fb)

### Operating System

Windows 10

### Web Browser name and version

Firefox 123.0.1

### Dark Reader version

Latest (not sure how to find it)

**Comment by charmarkk** [comment]
As ever, super impressed with the fixes and haste of implementing them! All the screenshotted areas and others that I've seen in the past look much better now, @Myshor, thank you very much! Will reopen if I see any others.

**Comment by alexanderby** [comment]
Thanks for the fix, I'm trying to find a JS solution, something is wrong with fallback CSS variables...
