### ISSUE TITLE
[Broken Website] Gitbook page is not work

### ISSUE THREAD

**Issue by mirumirumi** [darkreader/darkreader#12463]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

example: https://docs.renzoprotocol.com/docs

![image](https://github.com/darkreader/darkreader/assets/88871226/4950d0d3-10ff-4bb6-a8ef-2be3079c901b)

![image](https://github.com/darkreader/darkreader/assets/88871226/34c6b318-082a-4bc5-856e-f2094ce2e433)

### Website Address

https://docs.renzoprotocol.com/docs

### Steps To Reproduce

1. Go to page
2. Enable DarkReader

### Operating System

Windows 11

### Web Browser name and version

Chrome Latest

### Dark Reader version

4.9.80

### Additional Context

Thank you!

**Comment by Insprill** [comment]
I can confirm with Firefox v124.0 & Dark Reader Version 5 Preview (4.9.80) on this GitBook page
https://cfsamsonbooks.gitbook.io/explaining-atomics-in-rust

**Comment by mirumirumi** [comment]
Thanks, I can confirm with Chrome too.

**Comment by alexanderby** [comment]
I fixed the issue for this website, but the work need to be continued for similar cases.

The fix will be published soon.
