### ISSUE TITLE
[Broken Website] www.reddit.com mobile

### ISSUE THREAD

**Issue by fxzxmicah** [darkreader/darkreader#12473]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The popup does not turn dark.

### Website Address

https://www.reddit.com/

### Steps To Reproduce

Tap the profile picture in the upper right corner.

### Screenshots

![Screenshot_20240320_114733](https://github.com/darkreader/darkreader/assets/48860358/387dd032-534f-4ea3-ba2d-db6af964c027)

### Operating System

Android 13

### Web Browser name and version

Firefox Android 123.1.0

### Dark Reader version

4.9.80

**Comment by alexanderby** [comment]
The fix will be published soon, but Mozilla's review may take long because of upcoming holidays.

**Comment by fxzxmicah** [comment]
But I have received the change.😂
Anyway, thank you.
