### ISSUE TITLE
[Broken Website] https://my.home-assistant.io/faq/

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#12474]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

https://my.home-assistant.io/faq/ looks bad

### Website Address

https://my.home-assistant.io/faq/

### Steps To Reproduce

1. open https://my.home-assistant.io/faq/

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/14617699/471ef0d2-3722-4daa-87b1-ad94507ef4f9)

### Operating System

debian sid

### Web Browser name and version

firefox 123.0.1

### Dark Reader version

4.9.80

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
