### ISSUE TITLE
How to handle sites with official themes?

### ISSUE THREAD

**Issue by cglong** [darkreader/darkreader#1247]
If I have a site with a built-in user-selectable dark theme (like [Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/rest-api-walkthrough)), which of the following should I do:

1. Add the domain to `dark-sites.config`
2. Look for some class that gets dynamically applied in that theme and add a rule to `inversion-fixes.config`

Could the README be updated to better clarify this?

**Comment by yannickvandervleuten** [comment]
Personally wouldn't add it to `dark-sites.config`. As a user I want dark reader to automatically make any page dark if it's white, even when the site offers the option to make it dark. If I later decide to use the built-in theme then I will enable it on the site and disable dark reader for that site. 

Why?
- I don't want to be flashed with a white light if the theme defaults to white on their page
- Can be a hassle to find the theme option on some sites
- Theme sometimes sucks compared to dark reader

**Comment by Gusted** [comment]
Disable dark reader, use them 🤷🏽‍♀️
