### ISSUE TITLE
[Bug] Extreme CPU usage after wake from sleep on Mac

### ISSUE THREAD

**Issue by ElhemEnohpi** [darkreader/darkreader#12489]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

After waking the Mac from sleep, with Firefox already running, after about a minute, certain pages will cause extreme amounts of CPU usage when they are being displayed. Many different websites cause it, including Wikipedia, Reddit, or StackExchange, while some others don't, like Duck Duck Go. Switching away to another tab stops the CPU usage, but it starts again when switching back. Reloading the page, or restarting Firefox, stops it until the next sleep/wake. Uninstalling Dark Reader resolves the problem.

There are no messages in the browser console. I tried doing a profile of one of the pages from about:performance, but I'm not quite sure how to read it. It looked like it was spending all the time in "Style Computation". This started happening at some time in the last few weeks or so.

### Website Address

en.wikipedia.org, reddit.com, apple.stackexchange.com, many (but not all) others

### Steps To Reproduce

1. Create a new profile in Firefox for Mac, and install only Dark Reader. Leave all other settings at default.
2. Navigate to e.g. apple.stackexchange.com
3. Put the Mac to sleep, and wait 30 seconds
4. Wake the Mac, and wait up to one minute

### Expected Behavior

CPU usage shown in Activity Monitor for the "Firefox CP Isolated Web Content" process stays at about 3%.

### Actual Behavior

CPU usage shown in Activity Monitor for the "Firefox CP Isolated Web Content" process at first shows about 3%. After a minute or so, it shoots up to nearly 300%, or more if multiple windows are open. The about:performance page also shows hundreds of percent CPU for the web site.

### Operating System

macOS 14.4 on Apple Silicon M1

### Web Browser name and version

Firefox 124.0.1

### Dark Reader version

4.9.80

**Comment by alexanderby** [comment]
Should be fixed by https://github.com/darkreader/darkreader/commit/caf0ad23897a2b4f530f5ec5c3902eaa32fb2545

The next release is planned after Easter.

**Comment by alexanderby** [comment]
The fix should be available now.
