### ISSUE TITLE
[Broken Website] google

### ISSUE THREAD

**Issue by UnknownWitcher** [darkreader/darkreader#12487]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The font color for some of the links are unreadable.

### Website Address

https://www.google.com/search?q=tng+s06e15

### Steps To Reproduce

1. Go to google.com
2. Enter a tv show, movie or define a word.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/82295355/af797468-3811-4203-a017-4ca9e38d2923)

### Operating System

Windos 10

### Web Browser name and version

Firefox 124.0 (64-bit)

### Dark Reader version

4.9.80

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
