### ISSUE TITLE
Can't turn off dark reader on ip addresses and some subdomains 

### ISSUE THREAD

**Issue by CtrlShiftEscape** [darkreader/darkreader#1249]
When I click toggle current site it doesn't turn it off on my network router web page, 127.0.0.1, and some subdomains like labs.tineye.com and blogs.msdn.microsoft.com

**Comment by NobleUplift** [comment]
Did you already have `tineye.com` or `msdn.microsoft.com` in your `Not invert listed`?

**Comment by Gusted** [comment]
F i x ed

**Comment by AbdesamedBendjeddou** [comment]
I'm having the same issue on 127.0.0.1, can't toggle off
