### ISSUE TITLE
[Broken Website] Messy pixels instead of black on kwyk.fr

### ISSUE THREAD

**Issue by Enyrox** [darkreader/darkreader#12496]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Hello, 
I'm using Dark Reader on kwyk.fr and I have an issue: the white background turns into a mess or red, green and blue pixels instead of turning completely black. 
I know that Dark Reader can properly show the right black because it does it for half a second before turning into the colored mess. 

### Website Address

https://www.kwyk.fr/

### Steps To Reproduce

1. Go on kwyk.fr and see the perfectly white background
2. Enable Dark Reader
3. See for 0.5 seconds a perfectly fine black background
4. See the mess of pixels (Increase contrast to 110% to see it more)

### Screenshots

White version :
![image](https://github.com/darkreader/darkreader/assets/74433752/fca90cbb-6692-458b-b2a8-cf30e0d1c513)

Loading (working) version: 
![image](https://github.com/darkreader/darkreader/assets/74433752/296ecf50-3658-4d0a-8aaa-9b9cdb3ed538)

Broken version: 
![image](https://github.com/darkreader/darkreader/assets/74433752/abfe4c94-4571-4a63-9911-37867516260d)

### Operating System

Windows 11

### Web Browser name and version

Firefox 124.0.1 (64-bit)

### Dark Reader version

Version 5 Preview (4.9.80)

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Enyrox** [comment]
> Added sitefix for that.
> 
>     * If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> 
>     * Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
> 
>     * With that enabled newest sitefixes will be updated every browser start. 😉

Thanks!
