### ISSUE TITLE
[Broken Website] https://stats.arp242.net/

### ISSUE THREAD

**Issue by broughtupsy** [darkreader/darkreader#12497]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Charts background remains white

### Website Address

https://stats.arp242.net/

### Steps To Reproduce

Turn on dark reader on the site

### Operating System

Windows 10

### Web Browser name and version

Firefox Latest

### Dark Reader version

Dark Reader Latest

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by broughtupsy** [comment]
That bottom section is missing in Firefox
