### ISSUE TITLE
[Broken Website] copytonotion.com

### ISSUE THREAD

**Issue by IDrissAitHafid** [darkreader/darkreader#12494]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I've encountered an issue with my website's styling when Dark Reader is enabled. The website uses Tailwind CSS for styling, and the colors they become inverted and incorrect upon enabling Dark Reader.

### Website Address

https://copytonotion.com/

### Steps To Reproduce

1. Open the website with Dark Reader OFF.
2. Turn Dark Reader ON - at this point, the website looks fine with Dark Reader's dark mode styles applied.
3. Refresh the website with Dark Reader still enabled.
4. Observe that the colors are now incorrect, with some elements becoming invisible or hard to read.

### Screenshots

Here's how the website looks like when Dark Reader is enabled:

![Screenshot from 2024-03-24 06-41-40](https://github.com/darkreader/darkreader/assets/31975500/b8379697-ec61-4339-b93d-6b551ffe1292)

### Operating System

Linux Debian 11

### Web Browser name and version

Chrome: Version 123.0.6312.58 (Official Build) (64-bit)

### Dark Reader version

4.9.80

### Additional Context

The website also has a component rendered within an iframe from an extension, which becomes disrupted when Dark Reader is enabled, making also the select dropdowns transparent and invisible.

![image](https://github.com/darkreader/darkreader/assets/31975500/38b11db6-3e3f-4501-94f1-7c86360b461b)

**Comment by Myshor** [comment]
I made partial sitefix for that background.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Myshor** [comment]
For the extension on iframe I won't help. Maybe @alexanderby will take a look and check if there would be possibility to make it better with Dark Reader.

**Comment by IDrissAitHafid** [comment]
Thank you @Myshor for the quick fix :pray:
