### ISSUE TITLE
Inject theme-color to adapt address bar color on Android

### ISSUE THREAD

**Issue by kiwibrowser** [darkreader/darkreader#1250]
Hello,

This is only a suggestion;
Dark Reader is now compatible with Kiwi Browser for Android (a Chrome-fork).

Dark Reader is running perfectly, except that the address bar is always white. The color of the address bar is determined by a meta attribute called theme-color:

https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

If you inject the theme-color attribute, you can change the color of the address bar.

I can implement a workaround on our side, but it'd be the easiest I guess.

**Comment by alexanderby** [comment]
Thank you for the extensions support! I will have a look if this attribute can be modified and have effect dynamically.

**Comment by kiwibrowser** [comment]
My pleasure to see it running on Android! If you need an example:

```
function changeThemeColor(targetColor) {
    var metaThemeColor = document.querySelector("meta[name=theme-color]");
    metaThemeColor.setAttribute("content", targetColor);
    document.getElementById('ntpOverlay').style.backgroundColor = targetColor;
}

```

**Comment by alexanderby** [comment]
Version 4.7.11 should change the meta theme color.
