### ISSUE TITLE
Issue with code cell in .ipynb file on Github

### ISSUE THREAD

**Issue by poojan-solanki** [darkreader/darkreader#12500]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The code cells of .ipynb file on Github doesn't gets dark but fonts get white. This makes white fonts on white background of code cell.

### Website Address

https://github.com/krishnaik06/Machine-Learning-in-90-days/blob/master/Section%201-%20Python%20Crash%20Course/EDA.ipynb

### Steps To Reproduce

1. Open any .ipynb file on GitHub repository
2. Turn on dark reader

### Screenshots

Dark Reader off
![Screenshot 2024-03-25 195629](https://github.com/darkreader/darkreader/assets/91563387/5b7b6e39-c6b1-457c-96bf-7cda1e44c58e)

Dark reader onn
![Screenshot 2024-03-25 195644](https://github.com/darkreader/darkreader/assets/91563387/739ef486-ace1-475f-82d1-bea8f188dc21)

### Operating System

Windows 11

### Web Browser name and version

Chrome 123.0.6312.58

### Dark Reader version

4.9.80

**Comment by Myshor** [comment]
Can you find other link to share?

I end with: 
![obraz](https://github.com/darkreader/darkreader/assets/56877029/fe078e30-277c-4c36-b6dc-c1a7cc4b3974)

**Comment by alexanderby** [comment]
I was able to open the file. I'm trying to figure out why the CSS variables are not changed there.

**Comment by poojan-solanki** [comment]
> Can you find other link to share?
> 
> I end with: ![obraz](https://private-user-images.githubusercontent.com/56877029/316882172-fe078e30-277c-4c36-b6dc-c1a7cc4b3974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzgxNDAsIm5iZiI6MTcxMTQ3Nzg0MCwicGF0aCI6Ii81Njg3NzAyOS8zMTY4ODIxNzItZmUwNzhlMzAtMjc3Yy00YzM2LWI2ZGMtYzFhN2NjNGIzOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE4MzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmUxZGRjM2RjNmViNjBhYjUyMmU2NDFhZTRjNDVlNmE4OTkwMTY0YWM5YWQyNzBlNGJkNmRjNGZkYTljOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FiSMqd91wDZvc2FWUoi_oUwOuQCjYlPy2t3fLcvsy6g)

Yeah Sure:
https://github.com/krishnaik06/Machine-Learning-in-90-days/tree/master/Section%201-%20Python%20Crash%20Course

This folder has various .ipynb files.

**Comment by alexanderby** [comment]
I made one fix for this. Another one for some other parts of the document will follow...
