### ISSUE TITLE
[Broken Website] Number of papers still in black font in InspireHEP

### ISSUE THREAD

**Issue by quarkquartet** [darkreader/darkreader#12518]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

In the HepInspire, people can search for papers and it will show the number of papers at the top of bars. For example,
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=deep%20learning%20gravitational%20wave&ui-citation-summary=true

The screenshot under the dark reader is here.
<img width="1724" alt="image" src="https://github.com/darkreader/darkreader/assets/26316540/3fff6633-2aba-4fe1-b2eb-cab37afff0b9">

Look at the numbers I'm circling out. These numbers are black under the normal light theme. However under the dark reader they are still black, making it difficult to read.

### Website Address

https://inspirehep.net/

### Steps To Reproduce

1. Visit https://inspirehep.net/
2. Randomly search for something in their search bar.
3. Make sure turning on the 'citation summary' button, otherwise there is no such a bar graph.
4. You will see the number on top of the bar is black.

### Screenshots

<img width="1724" alt="image" src="https://github.com/darkreader/darkreader/assets/26316540/c74caa71-f8d2-4de8-9727-e935a25f0371">

### Operating System

MacOS 14.2

### Web Browser name and version

Firefox 124.0.1

### Dark Reader version

4.9.80

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by quarkquartet** [comment]
An update: in the new version, the axis of the plot on this website is black. See the screenshot.
<img width="913" alt="image" src="https://github.com/darkreader/darkreader/assets/26316540/ea5ed96c-53c5-4bfe-8855-a2b76fc54c6d">

This problem did not exist before, as can be seen from the screenshot of the first paragraph of this issue.

**Comment by Myshor** [comment]
My bad... didn't catch it.

Changing fix to fill all text in SVG with white color.

**Comment by Myshor** [comment]
It should be OK when newest sitefixes will update in your Dark Reader. 😉
