### ISSUE TITLE
[Broken Website] MkDocs doc sites - dynamic theme engine

### ISSUE THREAD

**Issue by daviehh** [darkreader/darkreader#12519]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Different color after scrolling

### Website Address

https://nlopt.readthedocs.io/en/latest/

### Steps To Reproduce

1. Go to `https://nlopt.readthedocs.io/en/latest/`
2. Scroll down a bit
3. Notice the color is different for the scrolled-up part (screenshot: part 1 and 2 are different colors, more noticible on some displays)

### Screenshots

<img width="1426" alt="Screenshot 2024-03-28 at 18 58 42" src="https://github.com/darkreader/darkreader/assets/25255906/cf70261e-131f-4e29-90e6-049db8a4a151">

### Operating System

macos

### Web Browser name and version

Chrome 124, Firefox 125

### Dark Reader version

4.9.80

**Comment by CodingArctic** [comment]
should be resolved - just need this issue to be closed

**Comment by daviehh** [comment]
thank you!
