### ISSUE TITLE
Wikipedia diff pages

### ISSUE THREAD

**Issue by terrorist96** [darkreader/darkreader#1252]
Diff pages on Wikipedia are very hard to decipher when using dynamic theme. [Example](https://en.wikipedia.org/w/index.php?title=GitHub&type=revision&diff=892854891&oldid=892275331&diffmode=source). The removed text on the left (yellow) is easy to see, but the added text on the right (blue) is very hard to see the highlight.

**Comment by Gusted** [comment]
Hi @terrorist96 

![](https://i.imgur.com/Ghue7o7.png) Will this be a better color?
```
.diff-addedline .diffchange {
    background-color: ${#d8ecff} !important;
}
```

**Comment by terrorist96** [comment]
Hi. No, the text that is highlighted is even less visible in your screenshot. This is what it currently looks like:
![image](https://user-images.githubusercontent.com/12802056/82155052-343d8f80-9840-11ea-969b-7e918ca3c1bf.png)

**Comment by Gusted** [comment]
Will this be a more visible color?

![](https://i.imgur.com/aIDFiDN.png)

**Comment by terrorist96** [comment]
Yes, that is much better. Thanks.
