### ISSUE TITLE
[Broken Website] OpenWeatherMap.org

### ISSUE THREAD

**Issue by ryspace** [darkreader/darkreader#12539]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The hourly forecast chart renders with colors that are unreadable, and the temperature axis still shows with a white background.

### Website Address

https://openweathermap.org

### Steps To Reproduce

1. Load openweathermap.org
2. Have DarkReader installed and enabled

### Screenshots

![screenshot-20240402185654](https://github.com/darkreader/darkreader/assets/102413892/a9ef7788-fb33-4c71-ab40-cbe17427421d)

### Operating System

Arch Linux

### Web Browser name and version

Firefox 123.0.1

### Dark Reader version

4.9.80

### Additional Context

I use this site constantly, and it's blinding to look at without DarkReader. However, without being able to read the precipitation information, disabling DR for the website becomes necessary.

**Comment by alexanderby** [comment]
The fix will be available soon.
