### ISSUE TITLE
[Broken Website] Firefox crashes beyond recovery with Dark Reader on 'Freecommander.com'

### ISSUE THREAD

**Issue by GunnarBernsteinHH** [darkreader/darkreader#12530]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Trying to open the url results in high cpu load, the website stops loading and Firefox cannot be exited (it ends, but the process still has 100% on one CPU).

### Website Address

https://freecommander.com/en/summary/

### Steps To Reproduce

1. open website

That is it.

### Screenshots

![dark_reader_crash](https://github.com/darkreader/darkreader/assets/57716100/5f62baa2-929a-463b-8d64-455d516a8d49)

### Operating System

Windows 10

### Web Browser name and version

Firefox 124.0.1 

### Dark Reader version

4.9.80

**Comment by alexanderby** [comment]
Yay, finally some challenging bug report, thank you.

**Comment by alexanderby** [comment]
So, this website uses the exact copy of Dark Reader, but it is called darkmoder. I will try figuring out what the hell is that.

**Comment by alexanderby** [comment]
So they use a WP plugin, that basically uses Dark Reader's script with renamed "darkreader" into "darkmoder". The two scripts conflict with each other. Not very nice of them.

<img width="507" alt="Screenshot 2024-04-03 at 14 44 02" src="https://github.com/darkreader/darkreader/assets/9638588/4027f0c1-4659-4917-9120-fc21519ff6a4">

**Comment by alexanderby** [comment]
The fix will be published soon.

**Comment by GunnarBernsteinHH** [comment]
Thanks, works fine now.
