### ISSUE TITLE
Work on protected pages

### ISSUE THREAD

**Issue by KOLANICH** [darkreader/darkreader#1254]
There are 2 prefs controlling access of webextensions to protected domains:

* `extensions.webextensions.restrictedDomains`
* `privacy.resistFingerprinting.block_mozAddonManager`

But the addon doesn't work on these tabs even if it is configured not to restrict access to these tabs. For example uMatrix works fine on these tabs.

**Comment by irvinm** [comment]
I was wondering about the same thing.  By default addons will not work on these sites, but with the changes you mention they will definitely work.  (I've used addons that interact with AMO for example, once the preferences are updated)
