### ISSUE TITLE
[Performance Issue] Dynamic Mode on Stack Exchange Websites

### ISSUE THREAD

**Issue by tunaflsh** [darkreader/darkreader#12551]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

With dynamic mode, some elements take up to 10 seconds to properly load. Sometimes the whole website takes a long time to load.

### Website Address

https://unix.stackexchange.com/questions/181425/can-we-print-the-last-word-of-each-line-in-linux-using-sed-command

### Steps To Reproduce

1. Enable Dark Reader
2. Switch to new design
3. Set "Scheme" to "Dark" and "Mode" to "Dynamic"
4. Load the website, or reload it

### Performance Profile

https://share.firefox.dev/3xqFXUT

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.11.2 (64-bit)

### Dark Reader version

Version 5 Preview (4.9.81)

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

Yes

### Additional Context

Tested on Floorp, but is observed on Firefox and Edge too.

**Comment by alexanderby** [comment]
@AmperAndSand Do you use Firefox? The fix is still under review there.

**Comment by alexanderby** [comment]
Please check if updating to 4.9.82 helps.

**Comment by tunaflsh** [comment]
Seems to be resolved on my end too.
