### ISSUE TITLE
[Broken Website] Bandcamp subdomains wont invert

### ISSUE THREAD

**Issue by DesperatePea** [darkreader/darkreader#12555]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I have darkreader set to make every website dark by default. However, bandcamp have a bunch of subdomains for their artist pages. Example: Havukruunu.bandcamp.com or slayer.bandcamp.com

While www.bandcamp.com does not invert, since i have it on the excluded list, all the subdomains always invert, and no matter what i put in the "not invert" list, nothing seems to work. Very annoying. What can i do? I tried the various ^ and ` and * in front of bandcamp.com but nothing seems to work.

### Website Address

https://bandcamp.com/

### Steps To Reproduce

1. Go to bandcamp.com and click on the website button on darkreader, so it excludes the site.
2. Go to any artist's bandcamp page. Example: https://havukruunu.bandcamp.com
3. The site is not excluded, and is still dark. Dark reader also never detects dark themes on the ones that have a dark color. 

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/73502428/f8a1b2df-2063-4bd9-99bc-44809e3eaacc)
![image](https://github.com/darkreader/darkreader/assets/73502428/44f7e056-86ef-4e74-bb16-87479fb670ce)

### Operating System

MacOS Sonoma 14.3.1 (23D60)

### Web Browser name and version

Firefox 124.0.2 (64-bit)

### Dark Reader version

4.9.81

**Comment by Myshor** [comment]
To have main bandcamp.com and all prefix subpages disabled you need to have two etries in your site list section:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/560a7655-d6af-416b-80df-df5d0d7ebb67)

**Comment by DesperatePea** [comment]
thank you, finally solved this!
