### ISSUE TITLE
[Broken Website] Rakuten.com - Selected checkbox hardly visible in dark mode

### ISSUE THREAD

**Issue by oeloo** [darkreader/darkreader#12550]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Selected checkbox in this website are very hard to see in dark mode, almost invisible. Could you please make them more visible in dark mode? thank you

### Website Address

https://fr.shopping.rakuten.com/search/geox#ft=u&nav=Mode_chaussures&f14=40

### Steps To Reproduce

1. Go to https://fr.shopping.rakuten.com/search/geox#ft=u&nav=Mode_chaussures&f14=40
2. You will see that the selection mark is very hard to see in dark mode.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/98819304/2928f86f-5017-4186-b82b-4392b8208dbb)

### Operating System

Windows 11

### Web Browser name and version

Chrome fully up to date

### Dark Reader version

4.9.81

**Comment by oeloo** [comment]
Thank you, it works perfectly.

**Comment by oeloo** [comment]
The problem is coming back;
![image](https://github.com/darkreader/darkreader/assets/98819304/200cea4a-1e42-4ade-aaea-1dbff885a1a8)

**Comment by Myshor** [comment]
They use generated class names so I need to change fix to use static part of the class to check.

Fix will be in a minute. ;)
