### ISSUE TITLE
[Performance Issue] Significant increase in time taken for  Dark Reader to take effect

### ISSUE THREAD

**Issue by Jamess-Lucass** [darkreader/darkreader#12554]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

The latest version of dark reader introduced a significant increase in time taken to apply.

I am able to produce this when using `tailwindcss@v2`, I am going to assume it occurs whenever there is a considerable amount of css on a site, this is because it occurs in `tailwindcss@v2` but not `tailwindcss@v3` and v3 introduced their JIT compiler which removes unused css from the final build.

### Website Address

http://localhost:8080 (Run from the repo in the [Steps To Reproduce](#steps-to-reproduce) section)

### Steps To Reproduce

1. `git checkout https://github.com/Jamess-Lucass/darkreader-reproduction`
2. `cd darkreader-reproduction`
3. `docker compose up -d --build`
4. visit `http://localhost:8080`

### Performance Profile

Profiling build off: https://github.com/darkreader/darkreader/commit/59a755f69857b294cfc78df27973885c8ab4e8c8

https://share.firefox.dev/49qIg7M

Profiling build off: https://github.com/darkreader/darkreader/commit/ed819d6153638a962cf2d9a46fc76ef6541d0351

https://share.firefox.dev/3POHYAE

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/23193271/8348abf9-b511-42be-8c64-7a40b2e0e14e)

### Operating System

Windows 11

### Web Browser name and version

Firefox 125

### Dark Reader version

v4.9.81

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

Yes

### Benchmarks:
Firefox: (Disable Cache: checked)
- No dark reader: `145 milliseconds`
- Dark reader v4.9.80: `1.38 seconds`
- Dark reader v4.9.81: `2.84 minutes`

### Commit
I was able to track it down to https://github.com/darkreader/darkreader/commit/59a755f69857b294cfc78df27973885c8ab4e8c8 using git bisect.

### Tailwind CSS file
When using `tailwindcss@v2` this is the bundled css file
[tailwindcss-v2.txt](https://github.com/darkreader/darkreader/files/14876401/tailwindcss-v2.txt)

When using `tailwindcss@v3` this is the bundled css file
[tailwindcss-v3.txt](https://github.com/darkreader/darkreader/files/14876413/tailwindcss-v3.txt)

This is why, even though I have only replicated it with tailwindcss specifically, due to the large content of css in v2, compared to v3, is why I think this will be apparent on any site that has a similar amount of css

**Comment by alexanderby** [comment]
Hi, could you please share some live URL?

**Comment by alexanderby** [comment]
Thank you for finding the exact commit. Indeed the `cssText` property appears to be slow for some websites. I will push the fix next week.
