### ISSUE TITLE
[Performance Issue] nba.com very slow to open (Firefox)

### ISSUE THREAD

**Issue by Wassss** [darkreader/darkreader#12562]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

Noticeable slowdown in page loading : 30 seconds

### Website Address

nba.com

### Steps To Reproduce

1. Install Dark Reader on Firefox.
2. Open nba.com
3. Page loading..
4. 30 seconds later page finishing loading.
5. Disable Dark Reader.
6. Open nba.com
7. Page load instantly.

### Performance Profile

https://share.firefox.dev/3J6vqkg

### Operating System

Windows 11

### Web Browser name and version

Firefox 124

### Dark Reader version

4.9.81

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

?

### Additional Context

https://github.com/darkreader/darkreader/issues/10403#issuecomment-2040715434

**Comment by Co3co** [comment]
I am having the same problem on Librewolf 124.0.1. I also get a message saying "dark reader is slowing down Librewolf"

**Comment by Loki-101** [comment]
The issue appears on Brave as well. Tested on nba.com and pterodactyl.io

**Comment by airfortech** [comment]
same on opera

**Comment by quarkquartet** [comment]
This problem happened suddenly at that time. I've been using dark reader on nba.com for more than a year until this issue happened a few days ago.

**Comment by Jamess-Lucass** [comment]
Possibly related to #12554

**Comment by Wassss** [comment]
I can confirm 4.9.82 fixed this issue on nba.com
