### ISSUE TITLE
[Broken Website] kilimall.co.ke

### ISSUE THREAD

**Issue by saikadaramakaisosjupita** [darkreader/darkreader#12588]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Images, menus and links are broken with dark reader enabled.

### Website Address

https://www.kilimall.co.ke/

### Steps To Reproduce

Visit the site with dark reader enabled. Also try to click any links on the left sidebar.

### Operating System

Windows 10

### Web Browser name and version

Firefox 124,0.2

### Dark Reader version

4.9.82

**Comment by Myshor** [comment]
I tried without Dark Reader disabled and in private session without any plugins and this site doesn't load pictures and submenus as well so it seems that problem is on their side.

**Comment by broughtupsy** [comment]
I tried with a new browser and the site operates. It is only when this plugin is enabled when everything breaks.

**Comment by yaardie** [comment]
Are you sure you posted in the right repo? This issue is due to ublock origin from my tests.

**Comment by Myshor** [comment]
Closing as mentioned above.
