### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by cmurtheepic** [darkreader/darkreader#12594]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

makes the drop down menu unreadable

### Website Address

FAAsafety.go

### Steps To Reproduce

use the website drop down menu bar

### Operating System

windows 11

### Web Browser name and version

Chrome  123.0.6312.122 (Official Build) (64-bit)

### Dark Reader version

4.9.82

**Comment by Myshor** [comment]
Added sitefix for that + fixed white footer and removed that light image from background.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
