### ISSUE TITLE
[Broken Website] chat.openai.com

### ISSUE THREAD

**Issue by mak448a** [darkreader/darkreader#12606]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The colors look a little off.
![image](https://github.com/darkreader/darkreader/assets/94062293/c5dffb2e-104b-422c-b6e9-41daa90985c6)

### Website Address

chat.openai.com

### Steps To Reproduce

Go to chat.openai.com and send a message

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/94062293/c5dffb2e-104b-422c-b6e9-41daa90985c6)

### Operating System

Windows 10

### Web Browser name and version

Brave Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)

### Dark Reader version

Latest (I don't know where to find it)

**Comment by alexanderby** [comment]
Hi, could you describe the problem with more details?

**Comment by mak448a** [comment]
The profile icon is extra dark
