### ISSUE TITLE
[Broken Website] Pure VPN

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#12615]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Only parts of the website are darkened

### Website Address

https://www.purevpn.com/download/android-vpn

### Steps To Reproduce

1. Visit webpage

### Screenshots

![Screenshot_20240419_144759](https://github.com/darkreader/darkreader/assets/6344099/c8143c00-9ca2-49e2-920a-ffc5e20f093e)

### Operating System

Linux

### Web Browser name and version

Vivaldi

### Dark Reader version

current

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by ShalokShalom** [comment]
Thanks

Why is this disabled by default? Sounds like a no-brainer to activate that. 🙂

**Comment by Myshor** [comment]
The problem there was background white image used instead of color background. Fix just remove this image.

**Comment by ShalokShalom** [comment]
I mean, why not enabling the updates by default 😄

**Comment by Myshor** [comment]
There are two reasons:
1. This option is added as new and available for new preview only. (which will be as default in Dark Reader version 5.x)
2. Some people prefers stable fixes released every plugin update. 😉
