### ISSUE TITLE
[Bug] Extension inverts site color scheme rather than just darkening the bright parts

### ISSUE THREAD

**Issue by justin-hackin** [darkreader/darkreader#12610]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Peamble: I'm light-sensitive and dark themes are a huge ergonomic improvement for me so I'm very thankful for this extension.  I switched away from `darkreader` recently. I really liked the re-theming but it messes with websites' themes even when you disable it on the site 😞 I really like how there are different approaches to re-theming with this because sometimes the defaults make the site pretty garrish.

One thing I've noticed about this plugin is that when I enable it on a dark-themed site, it sometimes inverts the mode so that the site is light-themed. There's a little bit more friction about specifying which sites use the extension than with my darkreader experience and I have to decide what is worse: light body text or light code snippets.

It would be really nice if the extension only darkened the light parts of a site. 

### OS
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66

### Browser
Chrome
Version 123.0.6312.123 (Official Build) (arm64)

### Extension 
Version 4.9.83

### Website Address

https://www.digitalocean.com/community/tutorials/how-to-scrape-a-website-using-node-js-and-puppeteer

### Steps To Reproduce

Go to site and enable/disable plugin

### Expected Behavior

All dark everywhere

### Actual Behavior

Dark parts become light

### Screenshots

<img width="1111" alt="Screenshot 2024-04-17 at 10 34 17 AM" src="https://github.com/darkreader/darkreader/assets/4888331/729d0496-1f68-49ae-a2a2-56a8dbf66b73">
<img width="1163" alt="Screenshot 2024-04-17 at 10 33 49 AM" src="https://github.com/darkreader/darkreader/assets/4888331/bab30ba7-0de2-4099-8741-fef3ae854609">

### Operating System

see description

### Web Browser name and version

see description

### Dark Reader version

see description

**Comment by justin-hackin** [comment]
Dark mode is so important to me that I'm thinking about switching to Firefox as default browser because the addon does not have this feature/bug. Sometimes I switch over to Firefox on mobile for long reads because of this extension.

### Browser
Firefox 124.0.1 (64-bit)

**Comment by Myshor** [comment]
Looking on the screens it seems you have some of filter mode enabled instead of Dynamic.
Check it and if mode is not set to dynamic change it manually to dynamic.

There was a time (long time ago) when Filtering was default mode but we mostly base on Dynamic right now which will work like you can see it works when new instance of Dark reader was installed on Firefox.

**Comment by justin-hackin** [comment]
> Looking on the screens it seems you have some of filter mode enabled instead of Dynamic. Check it and if mode is not set to dynamic change it manually to dynamic.
> 
> There was a time (long time ago) when Filtering was default mode but we mostly base on Dynamic right now which will work like you can see it works when new instance of Dark reader was installed on Firefox.

You're right, I had a site that lacked enough contrast on Dynamic so I switched on the filter mode but I didn't use the "only for [site]"  🤦‍♂️
