### ISSUE TITLE
[Broken Website] Microsoft Teams V2

### ISSUE THREAD

**Issue by aurelienizl** [darkreader/darkreader#12639]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I got this error when the page loads. I cannot launch the app. Using Firefox with Ubuntu 24.04 LTS. 

![Screenshot from 2024-04-26 19-12-54](https://github.com/darkreader/darkreader/assets/32246187/28286892-ecd0-4bf7-8e49-dbe4c156cb2e)

### Website Address

https://teams.microsoft.com/v2/

### Steps To Reproduce

Just launch teams, when the popup tells you to use the new version, accept it. Then the page reload and crashes. 
If I disable dark reader, everything works. 

### Operating System

Ubuntu 24.04 LTS

### Web Browser name and version

Firefox 125.0.2

### Dark Reader version

4.9.83

**Comment by jweickm** [comment]
I can confirm this broken website on 

**OS**
Fedora Linux 40 Workstation

**Browser**
Firefox 126.0

**Dark Reader version**
4.9.65

**Comment by daviewales** [comment]
Not sure if this is relevant. If I load the page with Dark Reader disabled (so it works), then enable Dark Reader, I get the following errors in the console:

```
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'nonce-SQe/eyGOHZEaQTDsPPVxkA==' 'report-sample' 'self' https://statics.teams.cdn.office.net https://browser.events.data.microsoft.com https://local.teams.microsoft.invalid 'wasm-unsafe-eval' https://c1-powerpoint-15.cdn.office.net https://c4-powerpoint-15.cdn.office.net https://c5-powerpoint-15.cdn.office.net https://cdn.dev.fluidpreview.office.net https://cdn.fluidpreview.office.net https://ch5.fluidpreview.office.net https://dev.loop.microsoft.com https://powerpoint.cdn.office365.us https://res.cdn.office.net https://res-1.cdn.office.net https://res-2.cdn.office.net https://res-gcch.cdn.office.net https://res-sdf.cdn.office.net https://statics.teams.cdn.office.net https://staticsint.teams.cdn.office.net https://www.bing.com https://r.bing.com https://t.ssl.ak.dynamic.tiles.virtualearth.net https://dev.virtualearth.net https://whiteboard.office.com https://app.whiteboard.microsoft.com https://az725175.vo.msecnd.net https://lpcres.delve.office.com https://midgardbranches.blob.core.windows.net https://web.vortex.data.microsoft.com” index.js:7410:27
Content-Security-Policy: (Report-Only policy) The page’s settings would block an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'nonce-SQe/eyGOHZEaQTDsPPVxkA==' 'report-sample' 'self' https://statics.teams.cdn.office.net https://az725175.vo.msecnd.net https://browser.events.data.microsoft.com https://local.teams.microsoft.invalid https://lpcres.delve.office.com https://midgardbranches.blob.core.windows.net https://web.vortex.data.microsoft.com https://c1-powerpoint-15.cdn.office.net https://c4-powerpoint-15.cdn.office.net https://c5-powerpoint-15.cdn.office.net https://cdn.dev.fluidpreview.office.net https://cdn.fluidpreview.office.net https://ch5.fluidpreview.office.net https://dev.loop.microsoft.com https://powerpoint.cdn.office365.us https://res.cdn.office.net https://res-1.cdn.office.net https://res-2.cdn.office.net https://res-gcch.cdn.office.net https://res-sdf.cdn.office.net https://www.bing.com https://r.bing.com https://t.ssl.ak.dynamic.tiles.virtualearth.net https://dev.virtualearth.net” index.js:7410:27
```

It looks like it only allows scripts to run from designated sources.

Also, if I enable the 'Detect Dark Mode' option in Dark Reader settings, and I have Teams set to use dark mode, then I can load Teams, even with Dark Reader enabled. I guess this is because it notices the enabled Dark Mode and doesn't do whatever it would normally do.

Note also that it doesn't matter which Dark Reader filter I use, I always get the 'app failed to init' error when Dark Reader is enabled.

**Comment by Coder-256** [comment]
I just experienced this as well. I was unable to connect to a meeting, but disabling Dark Reader for `teams.microsoft.com` resolved it. Seems other people are experiencing this as well; there is [a thread on the Microsoft Teams forums](https://answers.microsoft.com/en-us/msteams/forum/all/cannot-launch-teams-meeting-in-firefox-browser-get/2ddeaafe-3093-4855-867b-2a575f846c56) and another issue, #11994.

This isn't a graphical glitch, the site actually shows an error message and refuses to connect. I was several minutes late to a meeting while troubleshooting the problem. @alexanderby please consider looking into this issue.

Tested on Firefox 129.0.2, Dark Reader 4.9.89

**Comment by Dragodraki** [comment]
Please: Someone really should escalate this ticket to a higher priority!

This bug (or maybe it's an intended prevention by Microsoft itelsef) still persists. As soon Dark Reader is enabled on Teams either Teams is blocked at all (please see this picture from my computer) or several Teams feartures are just blank and without buttons (like https://github.com/darkreader/darkreader/issues/11994 and on my PC with e.g. the "calendar" module)
<img width="634" alt="Teams Error" src="https://github.com/user-attachments/assets/73475c89-1bb3-4cb7-a164-86a8f50d9535">

From my tests I did with browser settings, there are only two culprits left: Either DarkReader really create a conflict with MS Teams or microsoft.com uses an Javascript blocking feature exclusively for DarkReader. Switching color shouldn't be a security risk so the javascript searches explicit for an label from DarkReader or something like that - it might sound weird but would fit to my experience with Microsoft so far.

A few days ago I wrote a letter to DarkReader mail address, so far without any response.

Of course, disabling Dark Reader would be a temporary workaround, but half a year passed by now and I'd rather not care an increasing exception list.

Is there still no announcement for an update or statment from the contributors yet after so many months?

**Comment by alexanderby** [comment]
There is no issue in Chrome and Edge, you can use those browsers. You can also try using Dark Theme Detection in Firefox version until this is fixed.

**Comment by Dragodraki** [comment]
But Firefox is my preferred browser for several reasons. Also "until this is fixed" seems rather like "if it ever will be fixed" to me. Please, don't misunderstand me: I highly honor the work of an Open-Source project Dark Reader belongs to, it's free and comes with no warranty.

I don't know what you mean by "Dark Theme Detection", if you speak of the dark mode theme by FF settings, then it is enabled already (but don't covers correct website inversion).

For now I excluded "https://teams.microsoft.com/v2/" to the "Website List" (exclusions).
But I still hope it will become fixed by the devs.

**Comment by alexanderby** [comment]
<img width="269" alt="Screenshot 2024-10-23 at 13 01 59" src="https://github.com/user-attachments/assets/e3461b44-d19e-4040-8694-1e055139cba5">

**Comment by Dragodraki** [comment]
That's what you meant. I didn't get that before, sorry.
Yes, that's a workaround too.
But I think, I'll stick with my exclusion entry for this one page then because often Dark Readers dark theme is even better than the website's own (especially for eyes with heavy myopia).

It's a good idea for now, but anyway a real fix would be appreciated.

**Comment by Dragodraki** [comment]
Excuse me, I said it's a workaround - not that the issue is fixed by it's term of meaning.
If there was an update, I didn't get if so far.
If you really have to close this issue before the issue is solved, you should do this as not planned or for another reason.

**Comment by daviewales** [comment]
@Dragodraki, did you miss the commit which closed this issue? https://github.com/darkreader/darkreader/commit/1794aaf16a44968a7ad11f9ddd8f9586cfd936b7

It was not closed for no reason, but because a real change which is supposed to fix the issue was merged into the main development branch.

**Comment by Dragodraki** [comment]
@daviewales
@alexanderby

Thanks, it wasn't comprehensible for me before.

**Comment by itaranto** [comment]
This is still happening, I think this should be re-opened.

In my case it's not enough to disable DarkReader on the Teams URL, I had to disable the whole extension for Teams v2 to work.

**Comment by alexanderby** [comment]
I submitted an update for a review. Last time it took a week.

**Comment by itaranto** [comment]
It seems https://github.com/darkreader/darkreader/commit/1794aaf16a44968a7ad11f9ddd8f9586cfd936b7 it's not in the v4.9.96 release. Is that intentional?

**Comment by alexanderby** [comment]
Does it still happen to you? The v4.9.96 has just finished being reviewed yesterday. What's your teams URL? The fix will only work for teams.microsoft.com.

**Comment by itaranto** [comment]
> Does it still happen to you? The v4.9.96 has just finished being reviewed yesterday. What's your teams URL? The fix will only work for teams.microsoft.com.

I'm using https://teams.microsoft.com/v2/ and I still see the error message with v4.9.96.

I tried disabling the extension and restarting the browser but I sill see the "Oops, app failed to init!" message.

If I remember correctly, disabling the extension in v4.9.94 worked as a workaround.

I'm on Firefox BTW.

**Comment by itaranto** [comment]
OK, I disabled all my extensions and now it works.

So, this doesn't seem to be a Dark Reader issue then.
