### ISSUE TITLE
youtube dark issue

### ISSUE THREAD

**Issue by volapiik** [darkreader/darkreader#1264]
dark reader seems to be unable to apply to youtube 
![image](https://user-images.githubusercontent.com/49888056/56543522-b5442d80-653f-11e9-8e7f-3633cff92cbf.png)

**Comment by MrX-at-GitHub** [comment]
Same here. It seems to be a new change from Google.

**Comment by Yannickvdv** [comment]
For anyone having this problem, you can still use the standard dark theme for youtube. See here:
https://support.google.com/youtube/answer/7385323

> 1. Select your profile picture. 
> 2. Select Dark theme.
> 3. Go to “Activate Dark theme” and toggle on or off.

**Comment by MrX-at-GitHub** [comment]
> For anyone having this problem, you can still use the standard dark theme for youtube. 
I know Youtube's dark theme. I want dark reader to do the job as usual.

**Comment by Yannickvdv** [comment]
> I know Youtube's dark theme. I want dark reader to do the job as usual.

I am only stating it so that people have a temporary fix until it's fixed inside dark reader.

**Comment by alexanderby** [comment]
Thanks for noticing. Unfortunately now I see this too, though it was OK in the morning. They decided to put stylesheets inside isolated web components, so I'm afraid no quick fix is possible. The extension cannot read such stylesheets. The issue doesn't happen in Firefox and Safari, as far as YouTube shows old page version for them.

**Comment by alexanderby** [comment]
A static fix for YouTube was just published in version 4.7.11.

**Comment by MrX-at-GitHub** [comment]
Thanks for the static fix @alexanderby 
Btw what does "static fix" mean?

**Comment by alexanderby** [comment]
@MrX-at-GitHub It means that Dynamic mode is totally useless on YouTube, as far as all style sheets are inside custom components (a new browser feature that Google forces to become a standard). Also they are using a new custom CSS properties feature that is hard to handle. So I had to [list](https://github.com/darkreader/darkreader/commit/6ce34e3f2eadee6b4c068bc77d7a90d212d736a5) all the colors, applying filter values to them. But when color names will change, the fix will stop working.

**Comment by MrX-at-GitHub** [comment]
Many thanks @alexanderby
