### ISSUE TITLE
[Broken Website] The checkboxes on soulsplanner.com are incorrect when dark reader is active

### ISSUE THREAD

**Issue by Salvaju29ro** [darkreader/darkreader#12653]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Hi, on the soulsplanner.com website the boxes (left) are all checked even when they are not checked

### Website Address

https://soulsplanner.com/darksouls/weaponatk

### Steps To Reproduce

I uncheck a box, but it's still checked with dark reader active

### Screenshots

[Screencast_20240430_111703.webm](https://github.com/darkreader/darkreader/assets/10899871/186c022b-621f-492e-8d1e-020d7608ba3e)

### Operating System

Arch Linux

### Web Browser name and version

Google Chrome 124.0.6367.91

### Dark Reader version

4.9.83

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Salvaju29ro** [comment]
> Added sitefix for that.
> 
> * If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> * Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
> * With that enabled newest sitefixes will be updated every browser start. 😉

Thanks, it worked

![Schermata_20240502_123010](https://github.com/darkreader/darkreader/assets/10899871/3f9c7abc-ae29-460c-9898-7daf35d79008)
