### ISSUE TITLE
[Bug] TypeError: this.sendRequest is not a function

### ISSUE THREAD

**Issue by shifoc** [darkreader/darkreader#12662]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

TypeError: this.sendRequest is not a function

### Website Address

n/a

### Steps To Reproduce

open dev tools
inversion fix editor
click apply

### Expected Behavior

no error messages

### Actual Behavior

be able to apply changes

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/32818143/1f7670a9-9d81-41f7-86fa-99ccae2f51df)

### Operating System

windows 10

### Web Browser name and version

chrome

### Dark Reader version

4.9.84

**Comment by alexanderby** [comment]
Oops, my bad. The fix will be published soon.
