### ISSUE TITLE
[Broken Website] generatepress.com

### ISSUE THREAD

**Issue by yaardie** [darkreader/darkreader#12677]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

In the Site Library section, most images are missing and being replaced by a dark background. See same behaviour on gpsites.co/chef

### Website Address

https://generatepress.com/site-library/

### Steps To Reproduce

Visit the link. Then select the Blog option and scroll down. Additionally, check a site like gpsites.co/chef

### Operating System

Windows 10

### Web Browser name and version

Firefox 125.0.3

### Dark Reader version

4.9.84

**Comment by Myshor** [comment]
I can not reproduce in my firefox:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/721facc0-3ffc-43b0-a23c-40b5d52fa959)

**Comment by yaardie** [comment]
I will investigate further. Could be a cl
