### ISSUE TITLE
unable to login to reddit when I use darkreader

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#1270]
Hi, I'm on Debian 9, all updated, firefox quantum 60.6.1esr 64bit. I installed darkreader using firefox addons website. 
The only way I can login to reddit is turning off darkreader plugin. I tried to disable reddit from the built-in list but I can use reddit only when I turn off the plugin.
![fff](https://user-images.githubusercontent.com/26788174/56807890-5a0c8680-6830-11e9-9a45-a22f395b8c21.png)

**Comment by Gusted** [comment]
Fixed.
