### ISSUE TITLE
[Broken Website] Blank space on Last.fm

### ISSUE THREAD

**Issue by jupiterine** [darkreader/darkreader#12723]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Today, this section of the Last.fm website appears to be complete blank, and the text on it is illegible. Yesterday it was working fine. It appears it all started with the new extension update.

### Website Address

https://www.last.fm/

### Steps To Reproduce

I'm not an expert, so I don't know how to reproduce it

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/71471560/2ea9aa1e-7b00-40bb-b1fe-caba4396603f)

### Operating System

Windows 10

### Web Browser name and version

Chrome version 124

### Dark Reader version

4.9.85

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
