### ISSUE TITLE
[Broken Website] Roland

### ISSUE THREAD

**Issue by Insprill** [darkreader/darkreader#12739]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The main body of the site doesn't get themed. Most other pages are themed correctly, except for some which have white bars running down both sides

### Website Address

https://www.roland.com/us/

### Steps To Reproduce

1. Go to https://www.roland.com/us/ (main body isn't themed)
3. Go to https://www.roland.com/us/products/gopodcast/ (white bars)

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/52843537/655ddc54-f1b1-45c1-9650-b44797c9cd80)

![image](https://github.com/darkreader/darkreader/assets/52843537/ab1c56a8-9fe1-4c96-9b78-5e69b41820f1)

### Operating System

Windows 11

### Web Browser name and version

Firefox v126.0

### Dark Reader version

Version 5 Preview (4.9.85)

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
