### ISSUE TITLE
[Broken Website] reebok.eu/en-gb/legal/returns-and-refunds

### ISSUE THREAD

**Issue by Matr1x-101** [darkreader/darkreader#12749]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Text shows up as black on black background

### Website Address

https://www.reebok.eu/en-gb/legal/returns-and-refunds

### Steps To Reproduce

1. Go to website
2. See error

### Operating System

Windows

### Web Browser name and version

Firefox 126.0

### Dark Reader version

4.9.85

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
