### ISSUE TITLE
Ellie

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1275]
Darkreader breaks this page: https://ellie-app.com/new

Thanks

**Comment by ShalokShalom** [comment]
Have you fixed it? It works now. Here is also an instance: https://ellie-app.com/new

**Comment by ShalokShalom** [comment]
And here is a second instance: http://elchemy.neontree.pl/new

**Comment by ShalokShalom** [comment]
You are golden - so many pages repaired ^^

**Comment by Gusted** [comment]
I had nothing to do and im trying to sweep aal issue if you have noted the issue count.

**Comment by ShalokShalom** [comment]
Well, you commit and fix a lot of the pages, thats what counts

**Comment by Gusted** [comment]
😊

**Comment by ShalokShalom** [comment]
It still fails to load, if Darkread is on. When you switch to Darkreader off and load the page, you can then turn on Darkreader without any problems. But as soon as you reload the page with Darkreader on, it breaks.

**Comment by Gusted** [comment]
This seems a issue on their side of not removing the right elements I guess opening up a issue at their github should do it 🤷🏽‍♀️. Getting familiair with another codebase is not effective.
