### ISSUE TITLE
https://www.leroymerlin.es

### ISSUE THREAD

**Issue by scascalesp** [darkreader/darkreader#12761]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

https://www.leroymerlin.es/productos/banos/platos-de-ducha/platos-de-ducha-rectangulares/plato-de-ducha-kioto-120x70-cm-gris-piedra-82476200.html

HEllo. bottom images are hide

### Website Address

https://www.leroymerlin.es/productos/banos/platos-de-ducha/platos-de-ducha-rectangulares/plato-de-ducha-kioto-120x70-cm-gris-piedra-82476200.html

### Steps To Reproduce

Only load the web and enable plugin

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/89306506/9c2a6de8-1acd-422f-a1f4-fd3b8f3f9406)

### Operating System

WIn 10

### Web Browser name and version

Chrome last

### Dark Reader version

Last in 26-05-2024 (where is version number?)

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
