### ISSUE TITLE
[Broken Website] realmeye.com

### ISSUE THREAD

**Issue by 8Times** [darkreader/darkreader#12787]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Sometimes the character pictures are inverted when looking at players and other similar pictures.
![image](https://github.com/darkreader/darkreader/assets/13020561/efb48fd0-dc5c-4700-8579-d4c454529270)
Latex pictures are hard to read.
![image](https://github.com/darkreader/darkreader/assets/13020561/76164988-2e41-42e4-b8ad-98b27c437945)

### Website Address

https://www.realmeye.com/

### Steps To Reproduce

Open a user like https://www.realmeye.com/player/Drakonnnit and you will see it. Open a wiki article like https://www.realmeye.com/wiki/polarity-poison and you will see it.

### Operating System

Windows 10

### Web Browser name and version

Firefox 126.0.1

### Dark Reader version

Version 5 Preview (4.9.85)

### Additional Context

A very simple solution I use is:
```
realmeye.com

INVERT
img[src*="latex"]

IGNORE IMAGE ANALYSIS
.character
```

**Comment by Myshor** [comment]
I confirm... As you already mentioned how to fix it then maybe you want do the honors and make fix for that? 😉

**Comment by Myshor** [comment]
As there is no response I merged your proposed fix by myself. 😉
