### ISSUE TITLE
[Broken Website] Catit

### ISSUE THREAD

**Issue by quarkquartet** [darkreader/darkreader#12796]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

www.catit.com is broken. Some of the font are not visible. e.g. 
<img width="1587" alt="image" src="https://github.com/darkreader/darkreader/assets/26316540/fc5d314a-8dea-49e9-8096-9301b1bacd1c">

The specific page of this web I'm taking the screenshot is https://www.catit.com/products/cat-litter/go-natural-pea-husk-clumping-cat-litter/

### Website Address

www.catit.com

### Steps To Reproduce

Install darkreader (I'm using firefox 126.0.1), and open www.catit.com.

### Screenshots

<img width="1587" alt="image" src="https://github.com/darkreader/darkreader/assets/26316540/c7351405-1775-4be6-ba1a-de92fb4af90b">

### Operating System

MacOS

### Web Browser name and version

Firefox 126.0.1

### Dark Reader version

4.9.86

**Comment by Myshor** [comment]
Added sitefix for that.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

I just black shadow to the text for the places with background images.
![obraz](https://github.com/darkreader/darkreader/assets/56877029/62d60880-6966-4616-a515-45f003afe61f)
![obraz](https://github.com/darkreader/darkreader/assets/56877029/85c374b5-9f14-4ae1-942c-9dfe4999ba7b)
