### ISSUE TITLE
[Bug] ReferenceError: __spreadValues is not defined

### ISSUE THREAD

**Issue by PabloLamuno** [darkreader/darkreader#12799]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Angular 17 error when .enable is used, on a clean unused angular.

### Website Address

localhost

### Steps To Reproduce
HTML:
```
<div>
  <button (click)="activarDarkReader()">Dark mode</button>
  <button (click)="desactivarDarkReader()">Light mode</button>
</div>
```

TS:
```

  activarDarkReader() {
    if (DarkReader.isEnabled()) return;
    DarkReader.enable({
      brightness: 100,
      contrast: 100,
      grayscale: 0,
    });
  }

  desactivarDarkReader() {
    if (!DarkReader.isEnabled()) return;
    DarkReader.disable();
  }
```

1. Click dark mode
2. Check console

### Expected Behavior

No errors

### Actual Behavior

Uncaught ReferenceError: __spreadValues is not defined
    at overrideProperty (<anonymous>:18:33)
    at override (<anonymous>:29:11)
    at injectProxy (<anonymous>:72:9)
    at <anonymous>:360:9
    at createStaticStyleOverrides (darkreader.js:6924:27)
    at createThemeAndWatchForUpdates (darkreader.js:7168:9)
    at success (darkreader.js:7398:17)
    at ready (darkreader.js:7409:17)
    at createOrUpdateDynamicThemeInternal (darkreader.js:7413:13)
    at Object.enable (darkreader.js:7755:9)

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/116727014/30c7f57a-4637-4ab9-abef-14388859e2a3)

### Operating System

Windows 10 

### Web Browser name and version

Edge 

### Dark Reader version

4.9.86

### Additional Context

Clean Angular 17

**Comment by alexanderby** [comment]
Probably your TS compiler options need adding some flag. Dark Reader bundle uses ES2020. Maybe you need `target: 'es2020'` or higher. Maybe `tslib` should be added as a dependency 🤷‍♂️

**Comment by PabloLamuno** [comment]
> Probably your TS compiler options need adding some flag. Dark Reader bundle uses ES2020. Maybe you need `target: 'es2020'` or higher. Maybe `tslib` should be added as a dependency 🤷‍♂️

tsLib is installes, '"tslib": "^2.6.3",' and the target ES is set to 2022     "target": "ES2022",

**Comment by achromial** [comment]
Hi @alexanderby and @PabloLamuno I opened a PR for this as it was affecting me too. #13279

**Comment by alexanderby** [comment]
Thank you, I will publish it soon and we will see if this fix helps.

**Comment by achromial** [comment]
Thanks for publishing @alexanderby! 

For some reason I'm still seeing the issue in Angular. It appears to be transpilation in Angular for the spread operator where {...oldDescriptor} becomes the function `__spreadValues({}, oldDescriptor)` and is not defined in the browser after Darkreader is injected, at runtime.

I suspect the Angular or TSConfig internals re: CommonJS config and how DarkReader gets transpiled in an Angular project.

The ternary in 4.9.94 is applied before the code runs, so in the example `oldDescriptor ? {...oldDescriptor} : {}` during transpile, `oldDescriptor` exists so what gets injected in all cases at runtime is the spread operator.
