### ISSUE TITLE
Dark Reader overrides Facebook dark mode

### ISSUE THREAD

**Issue by paradoxicallist** [darkreader/darkreader#12815]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Dark Reader overrides Facebook dark mode.
My FB account has its own dark mode enabled. 
When I open FB page, sign in page shows up in dark mode while Dark Reader says «Enabled for the current website».
After sign in, Dark Reader keeps saying «Enabled for the current website».
I've have checked my FB account settings and again, native dark mode is enabled.
Dark Reader's "Detect dark theme" setting is enabled.

### Website Address

https://www.facebook.com/

### Steps To Reproduce

My FB account has its own dark mode enabled. 
When I open FB page, sign in page shows up in dark mode while Dark Reader says «Enabled for the current website».
After sign in, Dark Reader keeps saying «Enabled for the current website».
I've have checked my FB account settings and again, native dark mode is enabled.
Dark Reader's "Detect dark theme" setting is enabled.

### Expected Behavior

I expect Dark Reader not overriding Facebook native dark mode.

### Actual Behavior

Dark Reader overrides Facebook dark mode.
My FB account has its own dark mode enabled. 
When I open FB page, sign in page shows up in dark mode while Dark Reader says «Enabled for the current website».
After sign in, Dark Reader keeps saying «Enabled for the current website».
I've have checked my FB account settings and again, native dark mode is enabled.
Dark Reader's "Detect dark theme" setting is enabled.

### Operating System

Windows 11 

### Web Browser name and version

Google Chrome 125.0.6422.142

### Dark Reader version

Version 5 Preview (4.9.85)

**Comment by Myshor** [comment]
Yes... last update included some changes to facebook detector hints to detect if dark is set when dark or auto is selected. And I already found it was not working - I will push back original detector which works only if Dark Mode is set to ON.

However detector-hints can not be fetched other way than with new version of Dark Reader, so we need to wait as new version will be released.
