### ISSUE TITLE
[Broken Website] beny-devices.eu

### ISSUE THREAD

**Issue by mrx23dot** [darkreader/darkreader#12827]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Background isn't dark.

### Website Address

https://beny-devices.eu/pages/using-templates

### Steps To Reproduce

turn on auto mode
open website

### Operating System

win10

### Web Browser name and version

Firefox 115

### Dark Reader version

4.9.76

**Comment by Myshor** [comment]
There are newer versions of Firefox and Dark Reader and I can not reproduce white background on the page with them.
