### ISSUE TITLE
[Broken Website] Tab with techhut.tv hangs

### ISSUE THREAD

**Issue by Kojoley** [darkreader/darkreader#12829]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Site is unresponsive and/or tab hangs with enabled Dark Reader.

### Website Address

https://techhut.tv/

### Steps To Reproduce

1. Open https://techhut.tv/.
2. Browser tab hangs.

### Operating System

Windows 10.0.19045

### Web Browser name and version

Chrome 125.0.6422.142 / Firefox 126.0.1

### Dark Reader version

Version 5 Preview (4.9.85) / 4.9.86

**Comment by alexanderby** [comment]
Ah, these annoying guys again, who use Dark Reader without our license, and cause a conflict. I will try finding a workaround.

**Comment by alexanderby** [comment]
<img width="686" alt="Screenshot 2024-06-11 at 20 23 07" src="https://github.com/darkreader/darkreader/assets/9638588/79ad62a1-5ec7-4bf8-afa3-bac51abd3208">
They replaced `darkreader` with `darkmoder` and charge money for this.

**Comment by alexanderby** [comment]
The fix will be published soon.
