### ISSUE TITLE
Wikipedia SVG Images don't invert

### ISSUE THREAD

**Issue by andre-fu** [darkreader/darkreader#1283]
SVG images used in formulas etc on Wiki (or all SVGs? Haven't tested fully) don't invert properly

https://imgur.com/a/ijzDO7v

Earlier it did though, so I assume some prod push made this bug

**Comment by or-toledano** [comment]
![dark_reader_bug](https://user-images.githubusercontent.com/49984106/56920127-f1ccd780-6ab1-11e9-8fe8-822b1910a2be.png)

Weird different behaviour for .svg, . .svg.png?? and .png (as shown in the screenshot, ordered up-bottom)
Taken from en.wikipedia.org/wiki/Commutative_diagram

**Comment by krupenja** [comment]
This is a duplicate of https://github.com/darkreader/darkreader/issues/59
