### ISSUE TITLE
[Performance Issue] The UI takes a long time to load and is unresponsive until the page finishes loading.

### ISSUE THREAD

**Issue by air2921** [darkreader/darkreader#12842]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

When Dark Reader is enabled, certain websites experience significantly longer loading times. During this period, the UI becomes unresponsive and users cannot interact with the page until it is completely rendered.

### Website Address

https://hh.ru/

### Steps To Reproduce

1.Open Google Chrome
2.Turn Dark Reader on
3.Browse some pages of hh.ru

### Performance Profile

N/A

### Operating System

Win10

### Web Browser name and version

Google Chrome 125.0.6422.142

### Dark Reader version

4.9.86

### Does this happen when Dark Reader is disabled?

No

### Does this happen in other web browsers?

No

**Comment by alexanderby** [comment]
Fixed by https://github.com/darkreader/darkreader/commit/66d700a46f05912aef5bdc08935a18248ac8df47

The fix will be available soon.
