### ISSUE TITLE
[Bug] Extension randomly becomes completely unresponsive

### ISSUE THREAD

**Issue by Igetin** [darkreader/darkreader#12854]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Sometimes, when browsing any given website with Dark Reader installed, I notice that the styles look very incomplete. I then try to access the extension popu menu by clicking it in the browser top bar. The menu does not activate, however (nothing happens). Additionally, the keyboard shortcuts (such as Alt+Shft+D for toggling Dark Mode) do nothing. Every page is stuck with the weird styles, even after a refresh.

I have no exact reproduction steps, it happens on any website and at seemingly random times. This only started happening fairly recently (within the last six months, I think). The only way to recover from the bug is to restart the browser, or restart the extension from Chrome's extension page.

All other extensions work fine.

The bug seems similar if not the same as in [issue 8368](https://github.com/darkreader/darkreader/issues/8368) (now closed).

### Website Address

–

### Steps To Reproduce

 1. Have Dark Reader enabled in the browser
 2. Browse the web normally
 3. Perceive a sudden unresponsiveness of the extension

### Expected Behavior

The extension should keep working normally.

### Actual Behavior

The extension stops responding.

### Operating System

Fedora 40

### Web Browser name and version

Chrome 126.0.6478.55 (Official Build) (64-bit)

### Dark Reader version

4.9.85

**Comment by alexanderby** [comment]
Hi, please double check your Dark Reader version. 4.9.85 is MV2 version, and the latest 4.9.86 is MV3 but published only for 1% of users to catch unpredictable errors. To update to the latest version please go to chrome://extensions page, enable Developer Mode, click Update, then disable Developer mode. Please let me know if you see this pub again.
