### ISSUE TITLE
[Broken Website] HexOS

### ISSUE THREAD

**Issue by Insprill** [darkreader/darkreader#12852]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White sections don't turn dark, causing text to be unreadable

### Website Address

https://hexos.com/

### Steps To Reproduce

1. Go to https://hexos.com/
2. Scroll down. There's three white sections with unreadable text.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/52843537/14c77178-b5d2-4069-a5e0-3faed15dfdf7)
![image](https://github.com/darkreader/darkreader/assets/52843537/6aa9b141-f400-41da-84e9-d8a557826df1)
![image](https://github.com/darkreader/darkreader/assets/52843537/0f41d23f-f3ca-420a-b0cb-58427a039323)

### Operating System

Windows 11

### Web Browser name and version

Firefox v127.0

### Dark Reader version

Version 5 Preview (4.9.86)

**Comment by Myshor** [comment]
As it is is part of background the only one possible fix is to be done...
I will add shadow to the text.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
