### ISSUE TITLE
Why this "https://forum.snapcraft.io/" don't get dark in Firefox?

### ISSUE THREAD

**Issue by PranavBhattarai** [darkreader/darkreader#1286]
Just in case details:

> Firefox version: 66.0.3 (64-bit) (latest stable)
> OS version: Ubuntu 19.04 (64-bit) (latest stable)
> Add-on version: 4.7.11 (latest (stable))

**Comment by Richienb** [comment]
@PranavBhattari The problem only seems to affect you. Try reinstalling the addon.

![Screenshot of forum.snapcraft.io](https://user-images.githubusercontent.com/29491356/57980617-cbcb9f00-7a81-11e9-8d7e-96da29fca15e.png)

**Comment by Gusted** [comment]
Remove snapcraft.io from your site list.
