### ISSUE TITLE
Is there a way to take this and use it to make a dark mode for my website?

### ISSUE THREAD

**Issue by DaBomber60** [darkreader/darkreader#1287]
Is there a way that we can pull the dark-mode formula and apply it in a website being developed?

**Comment by ford04** [comment]
I am also curious to know, if there is some sort of API available to dynamically invert styles for a website/ a DOM node?
Would be willing to dig in, if you could provide some entry point in the code for further investigation.

**Comment by alexanderby** [comment]
Dark Reader API was published, see how to use it https://www.npmjs.com/package/darkreader#using-for-a-website
