### ISSUE TITLE
[NOT DARK READER RELATED][Feature Request] To expand or collapse a tab group

### ISSUE THREAD

**Issue by enamulkhanbd** [darkreader/darkreader#12877]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

The new “Tidy” feature is fantastic for organizing folders, as it automatically categorizes tabs based on content. However, the automatically created tab folders cannot be collapsed, which can hinder organization.

It would be great if we had the ability to expand or collapse these folders, allowing for a more streamlined view of organized tabs.

We kindly request that this feature be implemented, as it would greatly improve the functionality and usability of the browser. Thank you for considering our feedback!

### Screenshots

![arc-feature-request](https://github.com/darkreader/darkreader/assets/13956148/1d546c36-d93e-4504-a4ff-7bedf10f7fd7)

**Comment by Myshor** [comment]
I think this is another feature request created in wrong project. 🤔

**Comment by enamulkhanbd** [comment]
@Myshor Yeah, I did a mistake.
