### ISSUE TITLE
[Broken Website] Buttons disappear behind image

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#12887]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

This webpage has buttons that are hidden behind the bright images: 

Normal
![Screenshot_20240623_221150](https://github.com/darkreader/darkreader/assets/6344099/abd3b6d8-ff10-420a-8758-e500a70823a6)

Darkreader
![Screenshot_20240623_221128](https://github.com/darkreader/darkreader/assets/6344099/e3edc5f3-fa4d-4b2d-a861-49c114b6ec68)

### Website Address

https://gutrad.com/en

### Steps To Reproduce

1. Visit the homepage

### Operating System

Garuda 

### Web Browser name and version

Vivaldi current

### Dark Reader version

4.9.85

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
