### ISSUE TITLE
Attempting to load material.io/tools/icons/ with dark mode enabled causes browser to freeze

### ISSUE THREAD

**Issue by lbenedetto** [darkreader/darkreader#1288]
Page and extension become completely locked up if you load the page with dark mode enabled.

https://material.io/tools/icons/

I'm using Dynamic mode.

**Comment by Richienb** [comment]
@lbenedetto It works for me. It seems like the lag is client side so you will need a relatively modern computer to avoid the browser from handing.

![Screenshot of material.io/tools/icons](https://user-images.githubusercontent.com/29491356/57980537-f5d09180-7a80-11e9-8838-e9bc9b4ca3e7.png)

**Comment by lbenedetto** [comment]
My laptop has 16GB RAM, and an i7-7700HQ. My OS is installed on an SSD.

Don't think it's my hardware that's at fault.

Though now that I'm checking again it does work, it's just very laggy for the first 15 seconds while it processes everything.

**Comment by Richienb** [comment]
@lbenedetto I'm getting the same loading experience - it works but it's really laggy. I don't think there's anything that can be done about that seeing as it's just an extension. You can close this issue now.

**Comment by lbenedetto** [comment]
Well the site loads fine when the extension is disabled. So the bottleneck is in the extensions code somewhere. So something can probably be done in the extension to fix the loading.

**Comment by Gusted** [comment]
Fixed.
