### ISSUE TITLE
[Broken Website] gnu.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#12894]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/darkreader/darkreader/assets/30274161/cfd43e01-fb35-4195-9d61-fe805f4a89f8)

![image](https://github.com/darkreader/darkreader/assets/30274161/9dbcf5d8-8127-4cdd-871c-7d798de30d7f)

Logo should not be inverted (see https://www.gnu.org/graphics/heckert_gnu.transp.small.png).

### Website Address

https://www.gnu.org/

### Steps To Reproduce

Go to site.
See the problem.

### Screenshots

Attached above.

### Operating System

Linux

### Web Browser name and version

Firefox 127.0.2

### Dark Reader version

4.9.86

**Comment by Myshor** [comment]
So you want to tell us that it should look like this?
![obraz](https://github.com/darkreader/darkreader/assets/56877029/77a2dc16-b4cf-40dd-a61d-2107617a3678)

I must be inverted to be visible on dark background.
