### ISSUE TITLE
[Broken Website] Hi On Nature

### ISSUE THREAD

**Issue by cmurtheepic** [darkreader/darkreader#12897]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

makes text at bottom of page barely distinguishable from the background in dark mode

### Website Address

https://hionnature.com/

### Steps To Reproduce

1. goto website
2. observe hard to read text all over the website

### Operating System

Windows 11 Home

### Web Browser name and version

Chrome  123.0.6312.122 (Official Build) (64-bit)

### Dark Reader version

4.9.85

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by cmurtheepic** [comment]
> Sitefix added.
> 
> * If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
> * Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
> * With that enabled newest sitefixes will be updated every browser start. 😉

I will give this a try
