### ISSUE TITLE
[Broken Website] support.mozilla.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#12914]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Icons are black and should be inverted.

### Website Address

https://support.mozilla.org/en-US/kb/quarantined-domains

### Steps To Reproduce

Go to site.
See the problem.

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/30274161/1144ec44-5207-4ece-9f40-95cf7a260610)

### Operating System

Linux

### Web Browser name and version

Firefox 127.0.2

### Dark Reader version

4.9.86

### Additional Context

This site is a restricted page by default.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Myshor** [comment]
I just add this formula to every sitefix I made as someone else could have the same issue and want to have fix earlier. 😝
