### ISSUE TITLE
Dark reader could not be verified for use in Firefox and has been disabled

### ISSUE THREAD

**Issue by schrodog** [darkreader/darkreader#1292]
As title presented, the extension is disabled today (4/5), not sure what happened

**Comment by alexanderby** [comment]
This is a fatal Firefox error, expired certificate https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by alexanderby** [comment]
Here is more info and temporary solution (set system date a day earlier) https://www.reddit.com/r/firefox/comments/bkfte9/if_you_have_issues_with_your_addons_being_marked/

**Comment by schrodog** [comment]
I also found temporary workaround by setting 'xpinstall.signatures.required' to false in about:config
