### ISSUE TITLE
[Broken Website] IMDB, chosen page number does not show

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12933]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Selected page number does not show, and therefore unable to know on which page I am.

### Website Address

https://www.imdb.com/title/tt2467372/episodes/?season=8

### Steps To Reproduce

1. Go to above mentioned website
2. Find a series
3. Go to episodes
4. See if you can see the selected page number

### Screenshots

With Dark Reader ON:

![image](https://github.com/darkreader/darkreader/assets/81376423/4c88f2f9-4c47-4311-af88-fdf78203e407)

With Dark Reader OFF:
![image](https://github.com/darkreader/darkreader/assets/81376423/8aa6b0dd-1339-4ce4-aeae-d6061ade589b)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
