### ISSUE TITLE
[Broken Website] archwiki.org, wikipedia.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#12934]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Recently, two wiki websites have presented wrong-colored elements.

https://wiki.archlinux.org/title/Frequently_asked_questions
On left corner, it's possible to see a white bar.
![image](https://github.com/darkreader/darkreader/assets/30274161/dc8da036-6941-41e9-9497-8a1d4e768cbb)

Wikipedia (click on image):
https://en.wikipedia.org/wiki/Lolcat#/media/File:Cat_crying_(Lolcat).jpg
![image](https://github.com/darkreader/darkreader/assets/30274161/2a577502-bee0-4a0c-b64c-345140ca9176)

### Website Address

Provided above.

### Steps To Reproduce

Provided above.

### Operating System

Linux

### Web Browser name and version

Firefox 127.0.2

### Dark Reader version

4.9.87

### Additional Context

As for ArchWiki, there have been no changes (as far as I've seen) on that site, and it didn't have this problem before, so I believe it's something related to some technical change in the extension. (CC @alexanderby)

For ArchWiki, the problem and the fix are probably the same as https://github.com/darkreader/darkreader/issues/12383.

----------------------------

Wikipedia: CC @Myshor

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by Myshor** [comment]
I know you have it already enabled. 😁

**Comment by Myshor** [comment]
Hmmm... I had your issue but when I opened options and went to advanced settings to open sitefixes then it started to work fine. Maybe there was some problem with fetching the newest fixes and when I went into this section it fetched them.

I reopened issue but I am closing it back as there is nothing to fix. 😝

**Comment by Myshor** [comment]
I won't even reopen as the fix is already included in sitefixes as you mentioned.
It fix itself when page is refreshed.

Seems like archwiki sometimes doesn't allow to inject fixes by Dark Reader.
I managed to fix it like other similar "fix" - reset all settings in Dark Reader. Set back on all you need. (I switch sitefixes, detecting dark theme and enable on restricted pages... After the reset it started to work fine even without any refresh.
