### ISSUE TITLE
[Broken Website] No arrow showing on Computer Universe

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12940]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Arrow does not show in sorting list and therefore missing it each time.

### Website Address

https://www.computeruniverse.net/en/c/hardware-components/solid-state-drives-ssd?refinementList%5Bmanufacturer%5D%5B0%5D=SAMSUNG&range%5Bfacets.Gesamtkapazit%25c3%25a4tMassenspeicher.valuesDisplayOrder%5D=36%3A36

### Steps To Reproduce

1. Go to the above website, try to see if you can find the sort

#### <ins>With Dark Reader ON:</ins>

![image](https://github.com/darkreader/darkreader/assets/81376423/d85477f8-0041-4d7b-8201-64e3f7a37483)

#### <ins>With Dark Reader OFF:</ins>

![image](https://github.com/darkreader/darkreader/assets/81376423/79e92528-767d-4616-8843-03e7ae8c9cda)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
