### ISSUE TITLE
[Broken Website] Keychron whole webpage broken

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12947]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Most of the elements are not dark mode and the ones which are, are messed up and are barely readable.

### Website Address

https://www.keychron.com/products/keychron-v6-max-qmk-via-wireless-custom-mechanical-keyboard

### Steps To Reproduce

1. Just go to the site and turn on dark reader

### Screenshots

With Dark Reader:

![image](https://github.com/darkreader/darkreader/assets/81376423/8c06826a-1839-4e6c-9478-745ec18e38bc)

Without Dark Reader:

![image](https://github.com/darkreader/darkreader/assets/81376423/98b19646-4bf7-4774-9699-c5b334b22dc5)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by vikingnope** [comment]
@Myshor, would you be able to apply the same fix to this site too: https://keychron.de/products/keychron-v6-max-qmk-via-wireless-custom-mechanical-keyboardus-ansi-layout

**Comment by Myshor** [comment]
I will change URL alias to keychron.* and add invert to not transparent logo with white background. 😉

**Comment by vikingnope** [comment]
Oh great, thanks a lot mate :)
