### ISSUE TITLE
[Broken Website] Speedtest bar not appearing

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12952]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

On the speedtest gov mt website the speedtest bar is not appearing colored like usual.

### Website Address

https://speedtest.gov.mt/

### Steps To Reproduce

1. Go to site
2. Run a speedtest

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/9b675066-f1e0-4610-8bc8-92b4e9db382a)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/1eaa6bee-dd7a-42a9-8a7d-14613663aeea)

### Operating System

WIndows 11

### Web Browser name and version

Chrome 126

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
This page used wrapper for the results (something simillar as iframe) so I needed to add fix to the original URL instead of mentioned in issue but it's working nice after fixes.

![obraz](https://github.com/user-attachments/assets/94c4d30c-391b-49af-ba0e-6aab4646b8cb)

**Comment by Myshor** [comment]
I bet you have it already enabled but this I copy/paste for people who would have same issue and would have fix earlier. 😉

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
