### ISSUE TITLE
Cached dynamic theme

### ISSUE THREAD

**Issue by Marocco2** [darkreader/darkreader#1295]
Hi!
I've got a suggestion: dynamic theme can slow down layout loading a lot compared to static filter due to CPU working in background, so I think Dark Reader could store cached dynamic filter for recurring elements of website (top bar, navbar etc.). 
It would help performance and battery life.

**Comment by theLMGN** [comment]
I think storing and retrieving and comparing the previous page and the current page would be hard to implement, would be buggy and wouldn't necessarily be faster

**Comment by hakkikaancaliskan** [comment]
I think there shouldn't be a comparing between two pages because while comparing them it should do the same thing as it did before. We should store that theme and there should be a button to compare pages. Darkreader should create static themes for visited apps and should compare if button pressed. Why there should be a button? Because for example github, how many times does they change their theme in a year?
I think there should be implemented like this.

**Comment by theLMGN** [comment]
@hakkikaancaliskan Elements may be changed, removed or added between pages and this would still need to be updated

**Comment by hakkikaancaliskan** [comment]
Oh, I meant darkreader could save dynamic style as a custom theme like in screenshot.

**Comment by hakkikaancaliskan** [comment]
@theLMGN dark reader could save created dynamic themes as a static theme for site.
For example https://addons.mozilla.org/tr/android/addon/dark-mode-webextension/?src=search this extension using static styles. Dark reader could create like this based on dynamic theme.

**Comment by Allmeta** [comment]
Bump. This would make sites like google docs etc not crash your computer.
If a site has changed one would simply update the cache with a button or something.

**Comment by tombh** [comment]
I agree there are drawbacks and difficulties to caching, but I think they're less than the drawback of high CPU usage. The styles generated by dymanic mode are by far the best dark themes I've ever found. People take hours to manually generate such styles, which are never as good, and soon go out of date. I think the idea here to have a button to re-generate cached styles could be a great optional feature for those that suffer from high CPU.

I imagine the button would regenerate and merge any new or updated styles found for the domain. I think the first run of any domain will generally capture 90% or more of all the elements that will be found on a domain. Maybe another way to think of this button is a step-by-step automated theme maker.

**Comment by Geobert** [comment]
I agree, it's a pity to see that a website I visit often still have a delay before the theme being applied.

**Comment by Geobert** [comment]
this https://github.com/darkreader/darkreader/issues/1161 is related

**Comment by expelledboy** [comment]
@Geobert duplicate.

What would be nice is a style lists, similar to how you have filter lists in uBlock Origin.

Users of DarkReader could render a site using the dynamic style engine, tweak the settings if needed, and save that you into their personal list. Other users could then pick from the most popular static style from a list of all available styles for the current website, or pick at installation community lists composed from the top most used / rated etc.

So just to clarify you would install DarkReader, pick the most popular style lists, and most of your websites would then be statically rendered. When the styling is broken on a particular website you can re-render dynamically and commit this to your personal list to override the community maintained style locally. These stats would also be sent back to the style list maintainers to assist their efforts.

**Comment by Gusted** [comment]
Hi their!

With #3120 you can export for a site all generated theme to a CSS file and re-use it in static theme or a extension like stylus.

Regards,
Gusted

**Comment by Marocco2** [comment]
@Gusted Which should be the minimum version to get that feature?

**Comment by Gusted** [comment]
4.9.16
Aka the next release of dark reader.

**Comment by hakkikaancaliskan** [comment]
> 4.9.16
> Aka the next release of dark reader.

Can't use on fenix, is there a work going on for them?
Pressing "export dynamic theme" does nothing.
Also pressing "static theme edit icon" does nothing.

**Comment by Gusted** [comment]
> Can't use on fenix, is there a work going on for them?
> Pressing "export dynamic theme" does nothing.
> Also pressing "static theme edit icon" does nothing.

Fenix is running some problems #3272 #3273 It's rather hard to debug on mobile but will have a chance today to give it a look

**Comment by Gusted** [comment]
4.9.16 has been released 🎉
