### ISSUE TITLE
[Broken Website] Corsair White colour not showing correctly

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12953]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When choosing colors for products, white shows as grey.

### Website Address

https://www.corsair.com/us/en/p/pc-cases/cc-9011213-ww/icue-5000x-rgb-tempered-glass-mid-tower-atx-pc-smart-case-white-cc-9011213-ww

### Steps To Reproduce

1. Go to site
2. Check the color options of the products

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/1780cad4-dc83-47fb-852e-3dbf11832a03)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/23f8facb-77f6-4e0c-b79f-3023300bf9a3)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Adding invert for broken white color selector.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
