### ISSUE TITLE
[Broken Website] Hides euro image on inibuilds

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12955]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark Reader hides Euro flag image on inibuilds website, and Australian flag is also not good

### Website Address

https://inibuilds.com/

### Steps To Reproduce

1. Go to site
2. Select drop down of currencies (top right)

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/8118aa5f-de68-4c7a-af1b-1d3e352d4f9f)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/41ff0024-e67c-42f8-9380-68062f00d812)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
This page could be used without Dark Reader with it's own dark mode. 😋

However I will add fix for EUR and AUD + some logos and icon inverts which will work nice even when site dark force will be enabled.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by vikingnope** [comment]
> This page could be used without Dark Reader with it's own dark mode. 😋
> 
> However I will add fix for EUR and AUD + some logos and icon inverts which will work nice even when site dark force will be enabled.

Yep knew about that, just wanted to let you know :)
