### ISSUE TITLE
[Broken Website] dc.sourceafrica.net

### ISSUE THREAD

**Issue by yaardie** [darkreader/darkreader#12956]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Background image and text blurred

### Website Address

https://dc.sourceafrica.net/

### Steps To Reproduce

Just open the site with dark reader enabled and see.

### Operating System

MX Linux

### Web Browser name and version

Firefox 128.0

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
The problem was white background-image which was almost invisible on default white bacground.

Fix removes background-image.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
