### ISSUE TITLE
[Broken Website] Text unreadable on bambulab store

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12967]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White text unreadable due to image, should be made black

### Website Address

https://eu.store.bambulab.com/pages/bambu-filament

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/e3e2c16a-3ba4-4a0f-a627-a9b199953f48)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/9341c020-13ec-4e03-9f16-9205c5a5b87c)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Adding text shadow:
![obraz](https://github.com/user-attachments/assets/d143165d-a767-4942-a844-deb691456242)

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
