### ISSUE TITLE
[Broken Website] webstatus.dev

### ISSUE THREAD

**Issue by Araxeus** [darkreader/darkreader#12968]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The official web status website (see https://web.dev/blog/web-platform-dashboard) has some elements that stay white, like the sidebar or column header

### Website Address

https://webstatus.dev/

### Steps To Reproduce

go there

### Screenshots

![image](https://github.com/user-attachments/assets/839b9004-0247-464c-a074-03241d7e567a)

### Operating System

Windows 10

### Web Browser name and version

Chrome 126.0.6478.127

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
