### ISSUE TITLE
Facebook chat looks ugly when converted to black (after a messenger update) Chrome

### ISSUE THREAD

**Issue by alphatwins** [darkreader/darkreader#1296]
![ZietTNs](https://user-images.githubusercontent.com/44755289/57196942-db1afa80-6f61-11e9-9ccc-35bcf1ba8105.png)

I've had this error for a couple of months now i think, after facebook chat got updated to a new design. would like to have it all black and not black and gray :D Maybe at least have the other persons message background colour as gray or something

**Comment by pkpn** [comment]
I have the exact same experience. And the ugly bars to the left and right of the chat bubbles.

![download](https://user-images.githubusercontent.com/7557704/59960308-fec0e280-94c6-11e9-88d3-2c53324f3e9c.png)
(Don't mind the language, it's in Danish :P )

**Comment by alexanderby** [comment]
Should be fixed already.
