### ISSUE TITLE
[Broken Website] Forced Light Mode on Cloudflare Community

### ISSUE THREAD

**Issue by itsTKRaz** [darkreader/darkreader#12972]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

I'm forced to see light mode on the Cloudflare Community Forum and there's NO WAY to toggle light/dark mode, the option is disabled. Why?
It's blinding, hurts my eyes. Why is the option even disabled?

### Website Address

https://community.cloudflare.com/

### Steps To Reproduce

1. Visit https://community.cloudflare.com/
2. See light mode on the website
3. See that Dark Reader does not allow you to toggle between light/dark
4. 🎉 

### Screenshots

![FmbKK](https://github.com/user-attachments/assets/706d2d31-0fdf-4e54-8b59-0b8577a7f9f4)
![i7AQX](https://github.com/user-attachments/assets/138d5a87-27e0-4fc3-a361-b4e45bbfff25)
![yED9n](https://github.com/user-attachments/assets/65fa723d-2bf4-4ff2-847f-068f95b5efb5)

### Operating System

Linux

### Web Browser name and version

Firefox 128.0

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
First check with newer DR version 4.9.88.
Because I can not reproduce problem.

If it will still be problematic. Go to Settings -> Site list and remove `community.cloudflare.com` from there manually.

**Comment by itsTKRaz** [comment]
I see, it appears that `*.cloudflare.com` was broadly whitelisted for some reason.
Removing that explicitly has fixed the problem. Thanks.
