### ISSUE TITLE
[Broken Website] AliExpress [aliexpress.com]

### ISSUE THREAD

**Issue by Bluetinity** [darkreader/darkreader#12986]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Star ratings are hard to see on aliexpress.com home page or when browsing/searching for products with any of the filter modes enabled

`Image Nr. 1 "Product Card"`
![image](https://github.com/user-attachments/assets/939c500f-fada-4e21-b597-61c5bb9ef87f)

`Image Nr. 2 "Big Save Section"`
![image](https://github.com/user-attachments/assets/2a99fade-cd1e-43d1-8e3a-b331706cc961)

I have nearly no css knowledge, but i was able to make a sort of fix for the normal product card star ratings trought the dynamic filter dev tool:
```
div[class^="_2E4Wz"] {
    background-color: rgb(255, 176, 75) !important;
}
```
`Like this:`
![image](https://github.com/user-attachments/assets/8a72e98d-515e-40d7-8192-ece524b6845f)

`Result`
![image](https://github.com/user-attachments/assets/219b09ed-5288-4424-9d0a-b9b9d121090b)

It's not perfect, but i don't have enough knowledge to make a better solution.

### Website Address

aliexpress.com

### Steps To Reproduce

1. Go to aliexpress.com with darkreader enabled or search for a product from the home page [aliexpress.com]
2. Normal product ratings (as shown in Image Nr. 1) are completely dark. The star ratings are made by coloring the backgound and using an image as a mask.
3. Product ratings in the "Big Save" section (as shown in Image Nr. 2) are all white. The stars are made with SVGs and color is replaced by dark reader with --darkreader-inline-fill

### Operating System

Windows 11

### Web Browser name and version

Firefox 128.0 (64-bit)

### Dark Reader version

Version 4.9.88

**Comment by Myshor** [comment]
I will add sitefix in a while.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design". (no need from version 4.9.88)
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
