### ISSUE TITLE
[Broken Website] bibleref.com

### ISSUE THREAD

**Issue by LegitGreenBoi** [darkreader/darkreader#12984]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When enabling DarkReader on this site, it properly adjusts most of the page however, the middle section of most pages will remain largely white.

### Website Address

https://www.bibleref.com/

### Steps To Reproduce

1. Visit the site.
2. Toggle DarkReader on.
3. Site fails to fully adjust to dark.

### Screenshots

DarkReader toggled off
![Screenshot_20240718_234107](https://github.com/user-attachments/assets/0b7e9fb8-541d-44aa-88f8-9b5191c8ab5a)

DarkReader toggled on
![Screenshot_20240718_234047](https://github.com/user-attachments/assets/d926b863-2907-4605-8380-3d783791a9ab)

### Operating System

Arch Linux

### Web Browser name and version

Firefox 128.0

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design". (no need from version 4.9.88)
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
