### ISSUE TITLE
[Broken Website] Maltapost tracking progress bar not showing

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12999]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Progress bar not showing due to same colour. This will be a bit harder to test due to needing a tracking number.

### Website Address

https://www.maltapost.com/tracking#/tracking

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/139b5564-0e74-4885-b72e-b3b09444614f)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/330174b7-bfbb-4ffa-98ee-f1d070b58352)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
I see a very little lighter color on the screenshot but it's hard to make fixes without tracking number for package that is still not delivered.

I managed to google some tracking number but it's already delivered and even if I force some lighter color to all that already is done I can not confirm it won't affect colors for the circles that are not done yet.

So... If you can share the track number I can check what I can do with the issue. 😉

**Comment by vikingnope** [comment]
> I see a very little lighter color on the screenshot but it's hard to make fixes without tracking number for package that is still not delivered.
> 
> I managed to google some tracking number but it's already delivered and even if I force some lighter color to all that already is done I can not confirm it won't affect colors for the circles that are not done yet.
> 
> So... If you can share the track number I can check what I can do with the issue. 😉

Here you go: BF230504736MT

**Comment by Myshor** [comment]
This page is baaaad... 🙄

As I thought - I can change color to all and it will not fix anything.

Or set the lighter color to last activity. Which will work like that:
![obraz](https://github.com/user-attachments/assets/daeca7fc-7d6b-45fc-b98d-885114b011cc)

And for already delivered:
![obraz](https://github.com/user-attachments/assets/cf672469-d9d1-4a81-bae6-83fbbae343ae)

If this kind of fix would be enough for you I will push it to sitefixes.

Below I paste the sitefix code (that I could just copy paste into fixes).
```
maltapost.com

CSS
.multi-steps > li.is-active::before {
    background-color: gray !important;
}

================================

```

**Comment by vikingnope** [comment]
Oh ye that's better than nothing.

Who would've guessed that my countries national postage website is bad, surely not me... :face_exhaling: (***cries in sarcasm***)

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
