### ISSUE TITLE
[Broken Website] Ring logo broken on login page

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12998]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

'g' of the ring logo is missing

### Website Address

https://ring.com/users/sign_in

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/c02e45f6-a951-4db7-82d2-b9717ed58e9c)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/1379a8ac-e891-4e28-954a-f30a0f983f63)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
