### ISSUE TITLE
Dropbox Paper - checkbox disappearance 

### ISSUE THREAD

**Issue by chekoopa** [darkreader/darkreader#1299]
The extension works here pretty neatly, but any checkboxes get wiped while it's active.
Problem is that the checkbox element is elusive, I couldn't find it in a DOM tree.

Actually, it tries loading some kind of black checkbox but fails with the next message:

``` 
326a13f44ce6494e2385.eLR3NRhSjfdAlk7CWv1Qbhp_V1XmC5BXXQ50PbBr-Fg.js.br:2178 
Refused to load the image 'blob:https://paper.dropbox.com/50dfe5aa-a005-4089-b967-68607974a78b' because it violates the following Content Security Policy directive: "img-src https: http: data:".
```

I don't even know, how is it loaded, so just leaving it here.

### How to reproduce

 * Open any Dropbox Paper document with TODO list
 * Turn on Dark Reader
 * Look for checkboxes. There aren't any.

**Comment by NorthIsUp** [comment]
I am also seeing this issue in safari.

**Comment by Gusted** [comment]
Fixed.
