### ISSUE TITLE
[Broken Website] Google subscriptions text stays black

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12991]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Text stays black, should be white I believe

### Website Address

https://play.google.com/store/account/subscriptions?pli=1

### Steps To Reproduce

1. Go to link

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/8caa99c1-7b33-4e59-8535-b7b94ee8d5ba)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/a3c6c5f0-5a04-431a-b02b-05b3d7eac6b8)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Seems like some part of elements doesn't have any color set (they set it to inherit and it set black).

I managed to make quickfix and I will push it in a while.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design". (no need from version 4.9.88)
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
