### ISSUE TITLE
Google Docs: attachments not visible with Filter+

### ISSUE THREAD

**Issue by cryptotester** [darkreader/darkreader#1301]
Hi, this is not a duplicate.

I've seen people reported already Google Spreadsheets problems and the fix/workaround to use Filter+.

However, Filter+ makes Google Docs attachments unreadable (this is the issue). I made a video to demonstrate it:

https://www.youtube.com/watch?v=Ft7TgoSRCn4

In my video I suggest to allow rules not just per host, but per regex (so to allow single pages to have a different filter or to be disabled) but this seems an overkill.
Ideally, since Google Docs is a famous suite, it would be nice to have a solution so that both Spreadsheets and Docs work. For now I have to choose either to make one or the other work.

Thanks for checking it out. Cheers

**Comment by alexanderby** [comment]
What a wonderful video. Hope this is already fixed. There is now another problem: the images are always inverted in Chrome. But visible.
