### ISSUE TITLE
[Broken Website] Gradient text seems to be broken 

### ISSUE THREAD

**Issue by quick007** [darkreader/darkreader#13016]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The gradient text (specifically the `coming soon` and `superpowers` text) disappears when in dark mode.

### Website Address

https://getsuperpowers.app/

### Steps To Reproduce

1. Go to website
2. See issue

### Screenshots

![image](https://github.com/user-attachments/assets/0476cdf4-d864-4ec9-bc3b-5e16898e524b)
vs. 
![image](https://github.com/user-attachments/assets/1de5d95b-7e15-4693-8d6a-98b01c4fa2c9)

### Operating System

Windows 11

### Web Browser name and version

Chrome Version 126.0.6478.182

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee site fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
-- (Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
-- (New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
