### ISSUE TITLE
[Broken Website] wiktionary.org with ?useskin=vector

### ISSUE THREAD

**Issue by noobworth** [darkreader/darkreader#13032]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White bar across the top of the page that should dark.

### Website Address

https://en.wiktionary.org/wiki/Wiktionary:Main_Page?useskin=vector

### Steps To Reproduce

1. Add *.wiktionary.org to the site list
2. Visit https://en.wiktionary.org/wiki/Wiktionary:Main_Page?useskin=vector
3. See the white bar 

### Screenshots

![image](https://github.com/user-attachments/assets/ee2baa80-b64d-456a-9fd8-a19c79d3f69c)

### Operating System

Windows 10 22H2 (OS Build 19045.3693)

### Web Browser name and version

Firefox 115.13.0esr (64-bit)

### Dark Reader version

Version 4.9.88

**Comment by Myshor** [comment]
Will be easy fix... Just adding wiktionary to the list of wikimedia pages in sitefixes. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee site fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
