### ISSUE TITLE
[Dynamic] Disqus comments are still unreadable

### ISSUE THREAD

**Issue by EdHartHub** [darkreader/darkreader#1304]
The title is self self explanatory. I know there is another thread back to May 4, closed now, but it isn't solved yet so i start another one.

One note to take; when I refresh those pages (F5) after the initial load, it becomes readable! I'm using Firefox if that makes a difference. I've attached to screenshots;

----------

![Screenshot_2019-05-08 Could an engine have triple overhead cams ](https://user-images.githubusercontent.com/35639317/57423816-5f6fb680-71ca-11e9-8f5a-9ab25b7cd5b8.png)

----------

![Screenshot_2019-05-08 Manchester United's Alexis Sanchez Offered To Inter By Agent](https://user-images.githubusercontent.com/35639317/57423823-65659780-71ca-11e9-8b64-540c5d17cd45.png)

https://www.revzilla.com/common-tread/could-an-engine-have-triple-overhead-cams
https://sempreinter.com/2019/05/09/manchester-uniteds-alexis-sanchez-offered-to-inter-by-agent/

These pages are just examples, any pages within these two domains with Disqus have sthe same issue. Generally speaking, majority of the websites that I've encountered with Disqus have the same issue.

Great addon regardless, thanks for your hard work!

**Comment by lance8765** [comment]
This issue is still happening as of today, and in Chrome, too.

**Comment by Gusted** [comment]
Fixed

**Comment by Jgr9** [comment]
Could the Like/Dislike buttons be fixed?
