### ISSUE TITLE
[Broken Website] Aftership tracking not dark

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#13063]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Should be dark yet does not always work

### Website Address

https://www.aftership.com/track

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/4db69efe-4753-45e8-a19a-1973aa1a070f)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/022d678e-2377-4cd6-9f99-95bcc0ba9f40)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
