### ISSUE TITLE
Enhancement: Add color map function

### ISSUE THREAD

**Issue by HsunGong** [darkreader/darkreader#1307]
Could you please add a `color map` settings to support more color settings while convert to dark mode?
> Problem: I found `figure 1` with dark reader is not friendly to read (This color doesn't match the best color with the background) 

> May fix: give the `Permission` to set convert color from the color detected. This may look better.

![Figure 1](https://user-images.githubusercontent.com/32933986/57493909-97c1e280-72f9-11e9-86d1-7b4d911edbef.png)

**Comment by Gusted** [comment]
https://darkreader.org/blog/v4-9/
