### ISSUE TITLE
[Broken Website] OLX delivery/seller-confirmation

### ISSUE THREAD

**Issue by PatrykKuniczak** [darkreader/darkreader#13087]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The check boxes aren't visible

### Website Address

https://www.olx.pl/delivery/seller-confirmation/

### Steps To Reproduce

1. Somebody need to buy sth from you (You need to have account and try to sell sth with OLX Delivery option)
2. You need to open seller confirmation page
3. Fill in the form
4. On the last step you will see this 2 checkboxes

### Screenshots

![image](https://github.com/user-attachments/assets/c541f8c8-fc73-4efd-beec-287bf1ec5f80)
![image](https://github.com/user-attachments/assets/cb72652a-10e8-418b-b534-679b53abbec2)

### Operating System

Windows 11

### Web Browser name and version

Google Chrome 127.0.6533.89

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
Can you save this page as full page?
I tried to open it with my account logged in and ended with:
![obraz](https://github.com/user-attachments/assets/962c5b73-654c-403b-ae22-259cf6ae9141)

Or at least use developer tools and make screenshot with inspector selected on that checkbox that I could see the selectors and CSS part set on it.

Without that it will be hard to fix as I do not have possibility to make fixes.

**Comment by Myshor** [comment]
I was able to find something similar on: https://www.olx.pl/kyc/verification/ but it seems to work fine on Firefox and on my MS Edge (no - i do not use Chrome and I don't won't install it as it's chromium and one chromium browser in my system which is not set as default is enough) 😆

So you can check if checkbox is working fine on this URL - if not then it can be used as alternative to make fixes.

**Comment by PatrykKuniczak** [comment]
> I was able to find something similar on: https://www.olx.pl/kyc/verification/ but it seems to work fine on Firefox and on my MS Edge (no - i do not use Chrome and I don't won't install it as it's chromium and one chromium browser in my system which is not set as default is enough) 😆
> 
> So you can check if checkbox is working fine on this URL - if not then it can be used as alternative to make fixes.

There's no checboxes.

As i write above.

You need to create an sale announcement (With OLX delivery) in 1 account, and then on second account try to buy this item, then you can open this page, without this error

**Comment by PatrykKuniczak** [comment]
@Myshor 

https://github.com/user-attachments/assets/e7b3332e-cf5e-42f5-b91b-9615927d35aa


https://github.com/user-attachments/assets/0be517c1-6864-4037-b78e-4833865ccd00

I was forgot to turn off music 😆

**Comment by Myshor** [comment]
Still tried the steps shown in your movie and both Firefox and MS Edge is showing me checkboxes without any problems.

So I do not know what to fix. 😕

Screen from MS Edge:
![obraz](https://github.com/user-attachments/assets/b40f3dec-0f48-49d8-b108-0f46ef17c925)

Can you try MS Edge to confirm it's totally one browser issue related to Chrome?

**Comment by PatrykKuniczak** [comment]
@Myshor Yeah, it's occuring only on Chrome

MS Edge:
![image](https://github.com/user-attachments/assets/02f1a3fe-907a-4990-b47d-35292451c30e)

**Comment by Myshor** [comment]
Specially installed Chrome for a while and I can not reproduce it too.

![obraz](https://github.com/user-attachments/assets/27b161bc-20c1-4819-9061-28874e58a690)

Try to reset all settings in Dark Reader. With fresh installed Chrome and fresh installed Dark Reader I can not reproduce.

**Comment by PatrykKuniczak** [comment]
@Myshor Ok, mate ok

After reinstall it works properly. Thanks for help and quick response 😄
