### ISSUE TITLE
[Broken Website] Lyx cant read menu bar

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#13095]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Menu bar is white when it should be black

### Website Address

https://www.lyx.org/

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/3f9cd06d-6b04-4e25-8205-3f4438e879fb)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/d1996ff7-ed21-4347-80b2-aa22abbc6488)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
The whole background is an image which Dark Reader inverts...
First I removed the invert and ended with this result:
![obraz](https://github.com/user-attachments/assets/e8b560f5-6a54-4f56-8852-400bcb216cda)

So in the end I think it's better to remove it totally even if the color on the left and on the right side will be the same:
![obraz](https://github.com/user-attachments/assets/545a6c13-46db-4de0-b24f-d63e6d9678a9)

Pushing the fix.

**Comment by Myshor** [comment]
Update... Making right part darker with dark reader natural background.
![obraz](https://github.com/user-attachments/assets/3d3ec3e9-53aa-47ac-bf41-8c5bfbca94f6)

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by vikingnope** [comment]
Amazing work thanks
