### ISSUE TITLE
Add option to 'go dark' between specific hours (i.e. night only), as in toggle on/off

### ISSUE THREAD

**Issue by Zireael** [darkreader/darkreader#1312]
Hi,
Would it be possible to add an option to go dark only between specified hours?
Better yet, if you could sync with operating system, i.e. Windows Night Light mode (or f.lux program).

Also, option to toggle darkreader on/off, or until sunset/sunrise would be great.

I like darky a lot, but when in the office during the day it can be distracting. I also do some web development and would like to preview what i'm doing in my browsers.

Thanks a lot!

**Comment by Andrew5569** [comment]
You can currently set specific hours by hovering over the on/off switch and clicking the 3 dot icon that shows up

For the sunset/sunrise feature see /issues/72

**Comment by Zireael** [comment]
Whoa, thanks!
Not very intuitive having to know you have to hover over one menu element to show another menu element. But now I know it's there I can make use of of it.
I would suggest putting this setting  in [More] tab instead so it's easier to find.

Thank you

**Comment by Andrew5569** [comment]
Making the UI more intuitive was briefly discussed in the pull request that added the schedule feature https://github.com/darkreader/darkreader/pull/878#issuecomment-456397978. The maintainer said he had plans to redesign the UI. So hopefully, it will get updated.
