### ISSUE TITLE
Archlinux.org headerbar is blacked out

### ISSUE THREAD

**Issue by Tazeki** [darkreader/darkreader#1313]
When Darkreader is active on either light or dark mode, the headerbar on https://www.archlinux.org is mostly blacked out.
![image](https://user-images.githubusercontent.com/33498917/57645723-4b92ce80-7595-11e9-9e44-1b8dff8af562.png)

**Comment by Richienb** [comment]
@Tazeki What mode are you using? In dynamic mode, the problem doesn't persist.

![Screenshot of www.archlinux.org](https://user-images.githubusercontent.com/29491356/57980657-2a911880-7a82-11e9-8eac-1a8d02d21cd7.png)

**Comment by Tazeki** [comment]
@Richienb I'm using dynamic mode, and am also having an odd issue where loading the page (or refreshing it) causes it to show up as if Darkreader wasn't active.  Toggling Darkreader on and off, or changing any of the colour settings fixes it.

**Comment by semeion** [comment]
Yaah, same problem here with archlinux website...

**Comment by ShalokShalom** [comment]
In my dynamic mode happens nothing at all.

**Comment by Gusted** [comment]
F i x e d.
