### ISSUE TITLE
[Bug] input type="date" calendar icon does not invert

### ISSUE THREAD

**Issue by mtbayley** [darkreader/darkreader#13139]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Anytime I visit a site with the input type="date" element, the calendar icon is always dark. The colour should be inverted

### Website Address

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date

### Steps To Reproduce

Toggle dark mode on and off

### Expected Behavior

Calendar icon should be white when in dark mode

### Actual Behavior

Calendar icon is black in dark mode

### Screenshots

![image](https://github.com/user-attachments/assets/01bc74c5-05a7-46c5-91d7-8c9c00855dea)

![image](https://github.com/user-attachments/assets/1caaadcf-a683-4785-b56e-fcfc8eb7ca1e)

### Operating System

Windows

### Web Browser name and version

Edge 127.0.2651.98

### Dark Reader version

4.9.88

### Additional Context

Removing `::-webkit-calendar-picker-indicator` from the Dynamic Theme Editor solves the issue for me. The default config should have this removed.

https://github.com/darkreader/darkreader/blob/bc5f420cbc466b3bca08bce827d2c327356507d6/src/config/dynamic-theme-fixes.config#L8

**Comment by Myshor** [comment]
Checked if removing will break it in Firefox and it seems that firefox works fine when it's added or removed drom config file.
As you already found solution I propose that you will do PR 😉
