### ISSUE TITLE
[Enhancement] Divide project into API and Browser-Extension (API sample repository included)

### ISSUE THREAD

**Issue by ford04** [darkreader/darkreader#1315]
Hi there,
Dark Reader is a great extension for endusers. IMO, its style algorithms could also be very useful for (web) application developers in form of a NPM package, e.g. to quickly create a dark theme for simple sites or rapid prototypes. Most sites look already really well with the dynamic theme mode. And directly integrating a dark reader theme in a website could reach endusers that do not utilize the browser extension.

My suggestion is to divide darkreader project into API and Browser-Extension subprojects/repos. API should incorporate all style algorithms and otherwise be independent, whereas Extension uses API and is dependent on all the browser details like global variables `chrome.runtime` etc.

For some web project of my own I already prototyped a darkreader API repo ([repo link](https://github.com/ford04/darkreader-api)). Currently, it supports the [dynamic theme mode](https://github.com/ford04/darkreader-api/blob/master/index.d.ts) and invokes `createOrUpdateDynamicTheme` from [here](https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts#L312). So it should support custom `FilterConfig` (brightness, contrast, ...) and CSS fixes as well. 
Due to the nature of darkreader extension, some things like used global variables had to be [stubbed out](https://github.com/ford04/darkreader-api/blob/master/init.ts). Those are the reason for this refactoring suggestion. The API sample otherwise works well though.

I can offer some contribution here as well, if you need assistance. Currently I am not familiar with extension programming and all project implementation details yet though...

Would be interesting to hear your thoughts on this topic.

Cheers,
ford04

**Comment by alexanderby** [comment]
See how to use it https://www.npmjs.com/package/darkreader#using-for-a-website
