### ISSUE TITLE
Extension not working correctly on Vivalvi browser

### ISSUE THREAD

**Issue by Condoriot** [darkreader/darkreader#1316]
At this time it seems the extension does not remember websites individual settings.
Setting an address as an exception > switching to another tab and then back again to the first one will turn the page to black mode while the in the exception the button still shows Off.

Vivaldi | 2.5.1525.40 (Stable channel) (64-bit)
-- | --
Revision | 5309247574c10e1673d1207a16506a253f2ba8dc
OS | Windows 10 OS Build 17134.677
JavaScript | V8 7.4.288.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.134 Safari/537.36 Vivaldi/2.5.1525.40

**Comment by Gusted** [comment]
Fixed/
