### ISSUE TITLE
[Broken Website] fallout.wiki

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13173]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

https://fallout.wiki/wiki/Fallout_Wiki

Main page image loses its effect with Dark Reader enabled (lines in its background).

DR OFF
![image](https://github.com/user-attachments/assets/9cf35a96-57ea-4c93-9a68-bc7b4c120c55)

DR ON
![image](https://github.com/user-attachments/assets/55d0653d-b213-4908-9ba0-674e87e9250e)

--------------

Subpages lose background image and transparent effects.
And also, the cut line in the top looks strange with DR enabled.

![image](https://github.com/user-attachments/assets/01931cfa-c381-407e-8d9d-144033e53416)

![image](https://github.com/user-attachments/assets/b364d17b-5860-441f-b1ab-2fccd201fb0f)

![image](https://github.com/user-attachments/assets/5b77bb81-8ad1-4a0a-9af0-739d07a7a1ad)

![image](https://github.com/user-attachments/assets/dcf9c14d-3cfd-4c3c-9c27-26bb06127878)

### Website Address

Provided above.

### Steps To Reproduce

Provided above.

### Operating System

Linux

### Web Browser name and version

Firefox 129

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
What could be fixed is fixed... Not possible to touch anything in player.

**Comment by Myshor** [comment]
Some "Effects" like you mentioned won't be visible on dark background as they are gray transparent in original picture so with white background they are visible but with dark they are not and inverting whole image will break it.

**Comment by Myshor** [comment]
P.S. I managed to make player darker but it removes whole background image for it.

![obraz](https://github.com/user-attachments/assets/c39ac0a4-f918-480b-800e-8caec1833e95)

Code:
`.k-player .control-bar {
    background: var(--darkreader-neutral-background) !important;
}`

So if you prefer have it like presented above give reply here. 😉

**Comment by Myshor** [comment]
The background of player controls which are gradient picture like you showed on screenshot:
![image](https://github.com/user-attachments/assets/987df11c-0597-4056-8856-b05af7f4c012)

**Comment by Myshor** [comment]
OK... I'll push the fix in a sec... and I'm off from my PC for today. 😋
