### ISSUE TITLE
Reduce contrast with real black background

### ISSUE THREAD

**Issue by csandanov** [darkreader/darkreader#1317]
It's good for eyes to have a real black background color (especially for OLED displays). Now it can be achieved by changing a contrast from default to +30 but in this case, the contrast with the white fonts is unbearable. Do you have any suggestion on how to fix that? 

Below is the example: on top – my drop-down terminal with some text, bottom – github page with the enabled dark reader, both have a real black background. As you can see it's much better to have grayish font color (RGB 199,199,199) with the real black background.

![Screenshot 2019-05-14 at 17 14 00](https://user-images.githubusercontent.com/1058233/57690357-b282b700-766b-11e9-9b98-32286645dd38.png)

**Comment by Gusted** [comment]
```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.

**Comment by erig303** [comment]
Thanks for the advice
