### ISSUE TITLE
[Feature request or glitch?] Whatsapp web - Either readable smileys or a working QR code, not both

### ISSUE THREAD

**Issue by juanriccio** [darkreader/darkreader#13188]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this performance issue to avoid opening a duplicate.
- [X] I have restarted the web browser to check if that resolved this performance issue.
- [X] I can reproduce this performance issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Performance Issue Description

WhatsApp web's smileys (emoticons) only show clearly using the Dynamic mode. With the others, I get either nothing at all (Static) or negative images, which are hard to make out. The Dynamic mode shows them crisply. Perfect!
Except, when I try to link WhatsApp web from the phone, and the web page shows the QR code for linking, the telephone can't read the QR code correctly if it's in Dynamic mode, maybe because the black pixels aren't really black.
Can this be fixed with an ad-hoc workaround for the QR code page?

If necessary, I can provide more info, screenshots etc., but I hope the problem is easy to understand and reproduce from what I wrote here.

Thanks for reading!

### Website Address

https://web.whatsapp.com/

### Steps To Reproduce

1. Set DarkReader mode to "Dynamic"
2. (smileys are easy to recognize)
3. Log out from WhatsApp web
4. Try to re-link the web page by issuing the appropriate command from the phone
5. The QR code shown on the web page isn't recognized by the phone camera

Alternatively:
1.  Set DarkReader mode to "Filter" or "Filter+"
2. (smileys are hard to recognize)
3.  Log out from WhatsApp web
4. Try to re-link the web page by issuing the appropriate command from the phone
5.  The QR code shown on the web page is properly recognized by the phone camera

### Performance Profile

None - wrong category sorry

### Operating System

Windows 10

### Web Browser name and version

Firefox

### Dark Reader version

4.9.89

### Does this happen when Dark Reader is disabled?

Yes

### Does this happen in other web browsers?

Yes

**Comment by Myshor** [comment]
Problem with QR is dark border around it... there was some fix to that already in dynamic themefixes but the classes in site code changed and it stopped working as it should. I will push new sitefix in a sec. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
