### ISSUE TITLE
[Broken Website] amazon.it white section

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#13190]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White section with non readable text

### Website Address

https://www.amazon.it/-/en/b/?node=17751879031

### Steps To Reproduce

1. Go to site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/f8e319fe-81e1-48a3-881d-5cfa64a877e4)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/3f8407e8-a8c9-404b-a7ae-990602965dc8)

### Operating System

Arch Linux

### Web Browser name and version

Floorp 11.17.8

### Dark Reader version

4.9.89

**Comment by Myshor** [comment]
Analyzed that and it forces background as image in html style tags so it will be easier to just force original dark text in that part than trying to remove that picture background (I spent 20 minutes trying) 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
