### ISSUE TITLE
[Bug] Edge extension causing "STATUS_BREAKPOINT" errors in browser

### ISSUE THREAD

**Issue by SugarD-x** [darkreader/darkreader#13197]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

I'm currently using the Edge extension of Dark Reader, version 4.9.89, and as of recently I have been experiencing random "STATUS_BREAKPOINT" errors in the browser with the extension enabled. When disabling it, the errors don't appear, however re-enabling it brings them back. Other extensions do not cause this issue, and it started happening fairly recently after the recent extension update.

### Website Address

https://www.google.com/

### Steps To Reproduce

1. Install the extension on Microsoft Edge.
2. Enable the extension.
3. Browse normally and the errors are caused randomly. Alternatively, it can be triggered most often by completing a normal search on Google, and after receiving results, add text to the search query and submit it. Upon attempting to load the page with the results, the "STATUS_BREAKPOINT" error will instead appear. This does not happen with the extension disabled, and the extension appears to be at fault for the errors being triggered.

### Expected Behavior

Not be redirected to any error pages.

### Actual Behavior

The browser redirects to a "STATUS_BREAKPOINT" error page.

### Screenshots

![vindlkvndfkvndfkv](https://github.com/user-attachments/assets/8f1a466c-5cbf-4870-a6fc-33a010130407)

### Operating System

Windows 10 Pro, Version 22H2, Build 19045.4717

### Web Browser name and version

Microsoft Edge, Version 128.0.2739.54 (Official build) (64-bit)

### Dark Reader version

Version 4.9.89

### Additional Context

The bug appears to trigger randomly, albeit often, however it is almost completely reproduceable for me using the steps above referencing the Google search method. Other websites are also affected, but not all. I was unable to find any other bug reports regarding this issue when using the search function in the issues section of this repository. I have also been an avid user of Dark Reader for many years, so this is a new issue for me.

**Comment by alexanderby** [comment]
Could you please share your computer model? Unfortunately I was unable to reproduce the problem. Any search queries or direct links you could share? Do you use Filter or Dynamic mode? Do you have the other extensions installed?

**Comment by alexanderby** [comment]
I mean your CPU, RAM, GPU information, if it's not some specific device.

It would be useful if you could disable Dark Reader for the problematic page, save the whole page (not as a single file, but all the style sheets and images etc, when you press CTRL+S) and share the archive.

**Comment by alexanderby** [comment]
Do you have anything set in `edge://flags/` or `chrome://flags/`? Does the problem go away if you click "Reset all"?

**Comment by StarrPhysics** [comment]
Hey, I wanted to participate in this conversation since I've been having the same issue. It's really tricky, and very inconsistent. I use edge like @SugarD-x does, and I've been getting the same issue recently. Often this error happens when I'm looking things up on google and it's not always repeatable. I turned on the plugin again just to see if it was still an issue, and it was even after resetting my browser flags. When this specific crash happens, a report is compiled in `edge://crashes/`. Here is a screenshot of that directory. As you can see, it's been happening a lot to me recently, which is why I've had to turn it off since Thursday.
![Screenshot 2024-08-31 121549](https://github.com/user-attachments/assets/30bdf412-293f-4f4e-a7fb-3530bd0ca6db)

**Comment by alexanderby** [comment]
Hi @StarrPhysics! Could you please tell what is your operating system and Edge version? What's your CPU, RAM and GPU? Do you usually have many tabs open?

**Comment by StarrPhysics** [comment]
> Hi @StarrPhysics! Could you please tell what is your operating system and Edge version? What's your CPU, RAM and GPU? Do you usually have many tabs open?

Yes. Here's all the information:

Edition:        Windows 11 Home
Version:       23H2
OS build:     22631.4112
Experience:  Windows Feature Experience Pack 1000.22700.1034.0
CPU:            Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
RAM:           32.0 GB
GPU:            NVIDIA GeForce RTX 2060 
Driver version:	32.0.15.6094 
Driver date:	8/14/2024

**Comment by alexanderby** [comment]
@StarrPhysics That sounds like a powerful machine.

Do you have Dark Reader installed from Microsoft Edge Add-ons or Chrome Web Store?

Could you please disable Dark Reader, open some problematic URL, press CTRL+S to save the full page, pack it to a ZIP file and send to support@darkreader.org? (At least a screenshot to see if the page looks the same for you).

You said you have flags reset. Do you have anything enabled in Accessibility or Performance browser Settings?

**Comment by StarrPhysics** [comment]
@alexanderby 

The Dark Reader is installed from Microsoft Edge Add-ons.

I will attempt to find a URL which is problematic. From what I found this morning; it might be the case that certain URLs will cause the crash with "temporary" consistency. That is, will cause the crash over and over again, and then all this sudden be okay with no trouble. I'll have to do some random web searches to see if I can find a problematic link, but I might also record a video of it in case I am unable to reproduce it after it occurs. I'll upload it to my personal youtube and send you a link to that. In addition, I'll send you the website data.

As for Accessibility and Performance settings, I have various settings enabled. I'm not sure which ones are default or manually adjusted, but here are all of my settings.

![Screenshot 2024-08-31 131956](https://github.com/user-attachments/assets/4ae95450-b83f-442e-a47c-314a3d9798fe)
![Screenshot 2024-08-31 131948](https://github.com/user-attachments/assets/76bf7d25-920b-486d-81e9-21b758e76aeb)
![Screenshot 2024-08-31 131930](https://github.com/user-attachments/assets/e616784b-0a15-4f32-8660-4c3359a1d71e)
![Screenshot 2024-08-31 131910](https://github.com/user-attachments/assets/b7a7c23d-b576-4dad-bf13-96191400fc17)
![Screenshot 2024-08-31 121549](https://github.com/user-attachments/assets/2b774b41-5fa2-4772-aafe-0aef2795efcd)

**Comment by alexanderby** [comment]
Thank you for the screenshots. Could you make one of the Google Images and some query so that I can see how it looks for you? Maybe there's some country-specific doodle? It just started happening on August 29.

**Comment by StarrPhysics** [comment]
I am attempting to find a link which causes the issue, but I'm struggling to reproduce it. 

In the crash files that I mentioned before, I found that they contain the web searches which caused the crash. I've tried researching those links, with no issues. I'm not sure if my problem is fixed or if the issue is really that inconsistent. If I can reproduce it, I'll send you a screenshot as well as the link. @SugarD-x original image is exactly what it looked like for me. Sorry for struggling to repeat the bug.

**Comment by alexanderby** [comment]
I mean, I want to see how Google Search (or Image search) looks for you with Dark Reader enabled, if there's anything specific I can see.

**Comment by StarrPhysics** [comment]
Oh, I see. Here's a screenshot of a random search.

![Screenshot 2024-08-31 135330](https://github.com/user-attachments/assets/adfdeced-f2e1-4bd9-ae02-0579247f6956)

**Comment by alexanderby** [comment]
Thank you. It's totally fine if it doesn't crash anymore. Just share a link and steps you used when it crashed.

**Comment by alexanderby** [comment]
I was finally able to reproduce the error in the latest Edge and Chrome on Windows with Dev Tools open. Do you guys normally browse with Dev Tools open? Does it happen with closed dev tools?

**Comment by StarrPhysics** [comment]
I was getting the error without the dev tools open. I can check later if using the dev tools also causes me trouble, but my issue was independent of the state of the dev tools.

**Comment by polheydrik** [comment]
go to edge://flags
disable "viewTransition API for navigations"

**Comment by SugarD-x** [comment]
Hey there! So sorry for coming back to this so late.

I don't have DevTools open when the error occurs. I apologize, I should have clarified that I included it in the screenshot just for the sake of showing that no console errors were being reported.

The symptoms described by others when this occurs appears to be identical to mine.

My specs on the affected system:
Edition: Windows 10 Pro
Version: 22H2
OS build: 19045.4717
CPU: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz   2.70 GHz
RAM: 16.0 GB
GPU: Intel(R) HD Graphics 4000

I have not checked on my system at home yet to see if it is also affected, (it has much higher specs), but given the specs from the others here, I'd imagine it doesn't matter much in this particular case.

So far with the flag change made you mentioned, I'm not able to manually reproduce the crashes again via the Google search method.

**Comment by alexanderby** [comment]
Thank you guys for the information. This browser bug is triggered by changing a scrollbar color. Back in the days those Windows scrollbars were white, and we forced them to be of a different color for Windows users.

The temporary solution is:
1. Click Dark Reader icon.
2. Right-click the popup, click "Inspect".
3. Open "Console" tab.
4. Copy-paste the following code after `>` sign and press "Enter".
```js
chrome.storage.sync.get(['theme'],x=>chrome.storage.sync.set({theme:{...x.theme,scrollbarColor: '#ff0000'}},()=>chrome.runtime.reload()))
```
6. Reload the problematic page.

**Comment by alexanderby** [comment]
I've submitted a patch in version 4.9.90 for the review. The issue happens on small window sizes, that's why it acted so unpredictable. It is related to scrollbars changing their width when Dark Reader changed their color on Windows (they used to be white in previous Chrome and Edge releases).

**Comment by StarrPhysics** [comment]
Hey, I finally was able to replicate the error. You are totally correct; in that it depends on the dimensions of my window. Thanks again for all your help, and I'm glad we could help you find the issue!
