### ISSUE TITLE
Google Docs highlighting contrast problems

### ISSUE THREAD

**Issue by ylluminate** [darkreader/darkreader#1320]
I'm finding that highlighting is problematic on Google docs. For example, when text is selected I find it hard to really see / identify the selection readily:
![selection example](https://dqdpzeak1aol0.cloudfront.net/items/44342W2T320x0y1X0v12/Image%202019-05-14%20at%207.28.22%20PM.png?X-CloudApp-Visitor-Id=1270994)

Any ideas of how this could be resolved or how I could help contribute a PR to address this?

**Comment by Gusted** [comment]
```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.
```
Change the selection color.
