### ISSUE TITLE
[Bug] Scrollbar always stuck as default!

### ISSUE THREAD

**Issue by HarpreetUbhi7688** [darkreader/darkreader#13216]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

The scrollbar won't change from default no matter what. This is for all websites in Microsoft Edge, on Windows 11.

I have a custom theme created called "Theme 1" and I changed the scrollbar from default to a specific colour(#fbb245). It's always been working, but I think the latest Windows update did something as it's only stuck as the default now.

I tried it with the "Theme for all websites" and it didn't work. I turned off my "Adguard" and "A-Blocker" extensions and it still shows the default scrollbar.

I tried this in Firefox, and it's working fine. But I tried it in Chrome, and it's not working there either. Maybe it affects all Chromium-based browsers? 

I've attached 3 screenshots. 
- "DarkReader_ScrollBar_Issue_Screenshot_1.png" is the custom theme, "Theme 1". 
- "DarkReader_ScrollBar_Issue_Screenshot_2.png" is the default dark theme on "https://www.mediafire.com" with the scrollbar changed to a random colour(#8cff00). I'm not sure if you can see it, but the "Adguard" and "A-Blocker" extensions are turned off.
- "DarkReader_ScrollBar_Issue_Screenshot_3.png" is the same as "DarkReader_ScrollBar_Issue_Screenshot_2.png", but in Firefox this time.

DarkReader_ScrollBar_Issue_Screenshot_1.png:
![DarkReader_ScrollBar_Issue_Screenshot_1](https://github.com/user-attachments/assets/1ecfa982-69f0-46ed-a648-a379dce95fad)
DarkReader_ScrollBar_Issue_Screenshot_2.png:
![DarkReader_ScrollBar_Issue_Screenshot_2](https://github.com/user-attachments/assets/ac95a545-bc55-4c8a-9a2d-6571b9039a1f)
DarkReader_ScrollBar_Issue_Screenshot_3.png:
![DarkReader_ScrollBar_Issue_Screenshot_3](https://github.com/user-attachments/assets/509bd1ea-6e75-4e9f-9917-c6b58a889d9a)

As you can see, the scroll bar is always stuck as the default one no matter what. How can I fix this? I tried going into the dark reader's dev tools but that was only for specific websites. I'm not sure how to edit it for custom themes. 

Also, it's my first time posting anything here, so let me know if I did something wrong or missed something.

### Website Address

https://www.mediafire.com/

### Steps To Reproduce

1. [Try changing the scrollbar colour from default to a custom one in a Chromium-based Browser like Chrome/Microsoft Edge].

### Expected Behavior

The scrollbar should change to the DarkReader's custom scroll bar (Which looks pretty cool), and then change to the custom colour selected.

### Actual Behavior

For Chromium-based browsers like Chrome and Microsoft Edge, the scrollbar is the default Windows scrollbar, with the default Windows dark/light colours.

In Firefox, the scrollbar is the default Windows scrollbar, but the colour changes properly.

### Screenshots

![DarkReader_ScrollBar_Issue_Screenshot_1](https://github.com/user-attachments/assets/189db47d-3f7b-4846-ad6c-3ad98aac601c)
![DarkReader_ScrollBar_Issue_Screenshot_2](https://github.com/user-attachments/assets/3bb09047-abe5-4096-8484-d4a7c028856a)
![DarkReader_ScrollBar_Issue_Screenshot_3](https://github.com/user-attachments/assets/6bf6eb87-3ad9-4bf8-8b0b-b02fda97286f)

### Operating System

Windows 11

### Web Browser name and version

Microsoft Edge - Version 128.0.2739.63 (Official build) (64-bit)

### Dark Reader version

Version 4.9.90

### Additional Context

Not sure if this helps but I just updated Microsoft Edge when I was checking the version, so it's the latest one, but the issue is still there.

**Comment by alexanderby** [comment]
We had to temporary disable the scrollbar color change due to a Chromium bug that chashes websites like Google Search https://issues.chromium.org/issues/363544341

**Comment by alexanderby** [comment]
The good news: the same method as Firefox can be used in Chrome 121+, so we will implement it in the next release (unless we see more crashes).

**Comment by HarpreetUbhi7688** [comment]
Oh, that's good. Thanks for the reply. Do you have an estimated time for when the next update will be released? 

I did some further digging and found this: https://github.com/darkreader/darkreader/issues/13197

When I was trying to look for scrollbar bugs using the issues section's search bar, I only searched the word 'scrollbar' as I didn't know that there was a crashing issue before. 

I'm just adding the link to issue #13197 here in case someone reads this bug report and wants to see how you guys dealt with the Chromium bug for now.

I'm glad it still works on Firefox and, hopefully, it shouldn't be too hard to find a fix for Chromium browsers.

By the way, I got a little confused when I was reading #13197. Was the issue because of a colour and width change, or only a colour change? I'm asking because I noticed that on Firefox, currently, only the scrollbar's colour changes, not the width. I haven't used Firefox for a while, so I don't remember if it originally changed the scrollbar's width too.

Anyway, thanks again for everything!

**Comment by alexanderby** [comment]
Hopefully this week.

Yes, changing the scrollbar color in Chromium used to affect the scrollbar size.

**Comment by steviator** [comment]
Has this been released yet? If so it doesn't work.
