### ISSUE TITLE
Dark Reader doesn't alter theme initially sometimes on load of a site, requires refresh

### ISSUE THREAD

**Issue by ylluminate** [darkreader/darkreader#1321]
When I use some sites I find that Dark Reader doesn't initially manipulate the theme properly. Often I have to reload the page after it initially loads in order to get Dark Reader to activate.

One site that seems to do this semi-regularly is iCloud with "Find My iPhone" via an Epichrome instance. When this happens I must reload the site and then upon reload it seems to activate fully (most of the time).

Is this a known issue or an area that needs to be addressed? Can I help in some way to isolate this further and to issue a PR to help resolve this?

**Comment by pranavburnwal** [comment]
+1

happens on tested on Firefox and Firefox Developer Edition (Both latest builds)

**Comment by ssanders** [comment]
There’s a page of white text on transparent !important white that is unreadable by itself.
Dark Reader static or dynamic fixes it.

Dynamic looks amazing but is unreadable on page load as things are still loading.
Toggling manually fixes that.

In such case, I think it could simply theme again once everything has loaded.

**Comment by qbadothu** [comment]
+1
The problem occurs on Firefox 73.0.1 (64-bit) and Dark Reader 4.8.9. Disabling/reenabling Dark Reader for the tab works as a workaround, but it is very inconvenient.

The problem does NOT occur on Chrome 80.0.3987.122 and Dark Reader 4.8.9.

Both on the same Mac OS 10.14.6.

**Comment by Gusted** [comment]
Example Links?

**Comment by Gusted** [comment]
#835 dup

**Comment by PavanLuca** [comment]
This still happens, I opened Gmail and mails containers were white while they were supposed to be black.
![Schermata da 2023-08-05 00-17-28](https://github.com/darkreader/darkreader/assets/123581658/37e9a3f0-9e14-4d63-86da-e6be0b15179f)
![Schermata da 2023-08-05 00-17-57](https://github.com/darkreader/darkreader/assets/123581658/0a0fe7e0-c413-462b-9f48-8e1d4ac84862)
I didn't refresh the page, I tried adding mail.google.com to **Don't Revert Only** list and removing it and it worked, but it's anyway not normal to have to fix manually.
![Schermata da 2023-08-05 00-22-35](https://github.com/darkreader/darkreader/assets/123581658/7435652e-805d-42e8-8d45-604182c2f59e)
![Schermata da 2023-08-05 00-22-47](https://github.com/darkreader/darkreader/assets/123581658/37513429-63ba-4b9c-b2db-b2c62c698d49)
In this case, it happened after opening Gmail tab from a previous Firefox session, I have **Open existing windows and tabs** enabled.

**Comment by AlphaHasher** [comment]
This is still a present issue
