### ISSUE TITLE
Feature: Site specific theme ENGINE option (per site)

### ISSUE THREAD

**Issue by ylluminate** [darkreader/darkreader#1322]
I'm running into trouble where I frequently need to use different Theme Engines on a per site basis. Right now Dark Reader only allows one theme engine to be selected per site, but this somehow needs to be extended so as to allow each site to use a different theme engine. There are just too many exceptions to the rule and so it would probably be beneficial to have a singular engine, so to speak, that has different filter application styles that could be saved on a per site basis.

Any idea of how to implement this?  Is it currently possible or does some refactoring need to occur first?  Can we help in any way?

**Comment by robmonte** [comment]
Absolutely this. I can't believe it isn't implemented already given that it remembers ON/OFF per site already. So many sites need different theme engine choices that it's an immense pain to have to keep toggling back and forth between them depending on the site I'm looking at.

**Comment by ylluminate** [comment]
Thank you so much for implementing this!!!!
