### ISSUE TITLE
Scroll bar won't show with contrast all the way up

### ISSUE THREAD

**Issue by dwlsalmeida** [darkreader/darkreader#1323]
Scroll bar won't show with contrast all the way up, so it is impossible to know where we're at in a page.
![Here's an attached picture for reference.](https://user-images.githubusercontent.com/11738710/57781255-2d95ad00-7700-11e9-83db-755fb5486814.png)

**Comment by hamdyl052** [comment]
The workaround is to set the theme engine non-Dynamic, e.g. Filter, Filter+, or Static. Go to tab More, then select a theme engine.
Another workaround is use Light instead of Dark. It's better than glaring white background.

**Comment by Gusted** [comment]
#2402
