### ISSUE TITLE
Toggling on/off reset on switching tabs in Firefox

### ISSUE THREAD

**Issue by Isopod** [darkreader/darkreader#1326]
When DarkReader was on and I turn it off and then switch tabs, the resulting tab is initially displayed correctly, but after a few ms it automatically goes dark. The DarkReader popup says the extension is off. Switching DarkReader on and off again doesn't fix it. I have to reload the tab.

(The same thing can happen the other way around, when DarkReader was off and I turn it on)

This only happens in some tabs, seemingly at random. Could it be related to multiprocess? I use Firefox 65.0.2 and DarkReader 4.7.12.

**Comment by NginUS** [comment]
I came here to report a similar behavior, so I'll add it as a comment here. If it needs to be its own issue let me know & I'll rewrite it.

In my case, I have DarkReader on all the time, & on a few pages in particular the delay between either not rendering at all, or rendering as if it were off- & when it applies the darkening, is consistently several ms later.

In particular nextdoor.com, old.reddit.com, news.ycombinator.com are always doing this.

OS is Linux Mint 18.3 (Ubuntu 16.04 LTS)
Firefox 67.0 (Launched with "-5" nice on all 'max 8' multithreading)

**Comment by Gusted** [comment]
Should be fixed.
