### ISSUE TITLE
[Broken Website] Just Join IT

### ISSUE THREAD

**Issue by PatrykKuniczak** [darkreader/darkreader#13269]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

As you can see on screen, texts aren't shown

### Website Address

https://justjoin.it/

### Steps To Reproduce

1. Open page, click link :)

### Screenshots

![image](https://github.com/user-attachments/assets/43cd8e64-b9e3-493c-8b5d-701e798a19e3)
![image](https://github.com/user-attachments/assets/355c0b53-032d-420b-a1c5-9dc439cee6d3)

### Operating System

Windows 11

### Web Browser name and version

Chrome 129.0.6668.59

### Dark Reader version

4.9.92

**Comment by jan-ale** [comment]
cannot reproduce

**Comment by PatrykKuniczak** [comment]
> cannot reproduce

I've reinstalled browser and set off all other plugins, and it's still happend

**Comment by jan-ale** [comment]
works just fine with firefox (+ ubuntu :) ) in a new profile

**Comment by Myshor** [comment]
Yeah... In Firefox it works fine.

In Chrome based browsers (screen from MS Edge in Windows 11) it adds some strange unusable scrollbars which I can not even remove:
![obraz](https://github.com/user-attachments/assets/9e30106e-b403-4e4b-b528-0e5da3b47d24)

For the fix I will use CSS fix to raise height of the class used in chrome based browsers (which is different than in Firefox 🫤)
The result will be like below:
![obraz](https://github.com/user-attachments/assets/f9a821fb-c38e-49c7-a8bf-00ccf9c5f45f)

I will push the fixes in a minute.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
