### ISSUE TITLE
[Broken Website] Google Calendar Scrollbars

### ISSUE THREAD

**Issue by calvinhurlbert** [darkreader/darkreader#13261]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When Dark Reader is enabled on Google Calendar, it adds scroll bars surrounding the all-day events. When Dark Reader is disabled, they go away. This happens on multiple browsers, as well as on incognito.

### Website Address

calendar.google.com

### Steps To Reproduce

1. Go to calendar.google.com
2. Turn on Dark Reader
3. Suffer

### Screenshots

![image](https://github.com/user-attachments/assets/4dcf2400-b66b-401b-a6a7-b953a207c552)
![image](https://github.com/user-attachments/assets/78019f77-8bdb-42e3-a227-283023418a17)

### Operating System

Windows 10

### Web Browser name and version

Google Chrome 129.0.6668.59 and OperaGX LVL6 (core: 113.0.5230.108, with Chromium version:127.0.6533.120)

### Dark Reader version

4.9.86

**Comment by dsbe-ak** [comment]
Seems to be fixed now?!
