### ISSUE TITLE
[Broken Website] www.naiveui.com

### ISSUE THREAD

**Issue by DeepChirp** [darkreader/darkreader#13272]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The website is in dark mode, but DarkReader doesn't seem to detect that the website is in dark mode.

### Website Address

https://www.naiveui.com/en-US/dark

### Steps To Reproduce

1. Turn on Detect Dark Mode
2. Open this website

### Screenshots

![图片](https://github.com/user-attachments/assets/1ff19257-b7ee-4f3b-89ce-c4a6fdeb957a)

### Operating System

Windows 11 23H2

### Web Browser name and version

Firefox 130.0.1

### Dark Reader version

4.9.92

**Comment by DeepChirp** [comment]
> First I checked and it loaded in light mode for me. So it was good that dark reader was enabled. Then I changed the site theme to dark. Refreshed the tab. Checked Dark Reader and: ![obraz](https://private-user-images.githubusercontent.com/56877029/369977021-20962103-f769-4346-8e2c-e999e6909caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzc3ODgsIm5iZiI6MTcyNzEzNzQ4OCwicGF0aCI6Ii81Njg3NzAyOS8zNjk5NzcwMjEtMjA5NjIxMDMtZjc2OS00MzQ2LThlMmMtZTk5OWU2OTA5Y2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAwMjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZmEwNzI4ZThhYmQ5OGRiNTFlYzM1ZmRjMjIyODg0ZTU4MDliODNkNjg2YTgxY2YxZGZhZDhhNDhhMmQ1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wAsQNEJWScbhh3xEIQOvF1J4ijxBViOJQ6iAl_32yik)
> 
> So I can not reproduce.

I found that if the system theme is dark and the automation task is turned on, the dark mode of the website can be detected. However, if the system theme is light and the automation task is turned on, I turn off the automation task and manually enable Dark Reader, then the dark mode of the website cannot be detected.

**Comment by Myshor** [comment]
Maybe I don't understand it right then correct me.

You have light system theme and you have disabled Dark Reader by default.
You open this page with disabled Dark Reader and then turn it on.

If yes then it works as expected.

When Dark Reader is not applying anything to the page and then you enable it then it will apply what it can to the page.
Same situation when dark theme on the page is detected. As sometimes it can false detect detect dark theme on the white page so you can always enable Dark Reader manually to force it's Dark Mode.

Summarizing. Enabling manually Dark Reader on a page with dark mode detected won't trigger detecting dark theme. This works only when Dark reader is already enabled.

**Comment by DeepChirp** [comment]
OK. Thank you for your detailed explaination!
