### ISSUE TITLE
[Broken Website] Some inverts to add (multiple websites)

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13276]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Some inverts to add.

https://www.pcgamingwiki.com/wiki/Resident_Evil_4_Ultimate_HD_Edition#Availability
![image](https://github.com/user-attachments/assets/aa5ced61-bb00-4d90-83d2-45b292bacb0f)

https://en.wikipedia.org/wiki/Radeon_400_series
![image](https://github.com/user-attachments/assets/cabf0f55-168e-44d0-83e8-5b989aa31e30)
Not sure if this one is feasible, as it would also invert the red color.

https://en.wikipedia.org/wiki/Radeon_RX_6000_series
![image](https://github.com/user-attachments/assets/7186ac4c-0adc-4f10-a630-fd737da6cc0d)

https://en.wikipedia.org/wiki/Radeon_RX_7000_series
![image](https://github.com/user-attachments/assets/d11cc5df-e304-4d9b-bca6-a41a9a43d33b)

### Website Address

Provided above.

### Steps To Reproduce

Provided above.

### Screenshots

Provided above.

### Operating System

Linux

### Web Browser name and version

Firefox latest

### Dark Reader version

Latest

**Comment by Myshor** [comment]
Sitefix added.

Not adding the formula how to enable latest sitefixes because you already have it enabled. 😋

**Comment by Myshor** [comment]
Give the exact URL I can check 😝
