### ISSUE TITLE
[Bug] Broken firefox snapshot functionality

### ISSUE THREAD

**Issue by sergxerj** [darkreader/darkreader#13271]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

When activating the firefox-native screenshot functionality it creates a visible overlay in an iframe with id "firefox-screenshots-preselection-iframe". Darkreader tries to style this and the overlay (and the screenshot) becomes blank, making the functionality unusable. This breaks in all sites the addon is enabled when the functionality is invoked.

### Website Address

www.example.com

### Steps To Reproduce

1. Install extension on firefox
2. Invoke firefox screenshot by ctrl+shift+s or context menu
3. Overlay becomes blank instead of transparent

### Expected Behavior

Screenshot overlay should not be styled by darkeader, remaining transparent.

### Actual Behavior

Screenshot overlay is styled by darkeader, becoming opaque white.

### Screenshots

![image](https://github.com/user-attachments/assets/1e58c658-b5ba-4288-a782-4a792acfb577)
Site with extension disabled
![image](https://github.com/user-attachments/assets/a22d5460-d183-4854-a8f3-345bb25527e5)
Overlay with extension disabled.
![image](https://github.com/user-attachments/assets/2081040a-043a-4ee4-883a-e95e03ff1a08)
Snap region with extension disabled

![image](https://github.com/user-attachments/assets/3896e543-ece4-4393-b7b1-46a23c4de7fd)
Site with extension enabled
![image](https://github.com/user-attachments/assets/5aa91fb5-5708-403c-b767-f69edb55d637)
Overlay with extension enabled
![image](https://github.com/user-attachments/assets/a1303fc8-fe41-41b6-ae2c-bea364736668)
Snap region with extension enabled

### Operating System

Windows 10

### Web Browser name and version

Firefox 123.0.1

### Dark Reader version

4.9.92

**Comment by sergxerj** [comment]
It's apparently an autogenerated sheet from the dynamic style. When I disable it via the devtools styles tab it goes back to normal. Contents are:

```
@layer {
html {
    background-color: #181a1b !important;
}
html {
    color-scheme: dark !important;
}
iframe {
    color-scheme: dark !important;
}
html, body {
    background-color: #181a1b;
}
html, body {
    border-color: #736b5e;
    color: #e8e6e3;
}
a {
    color: #3391ff;
}
table {
    border-color: #545b5e;
}
mark {
    color: #e8e6e3;
}
::placeholder {
    color: #b2aba1;
}
input:-webkit-autofill,
textarea:-webkit-autofill,
select:-webkit-autofill {
    background-color: #404400 !important;
    color: #e8e6e3 !important;
}
::selection {
    background-color: #004daa !important;
    color: #e8e6e3 !important;
}
::-moz-selection {
    background-color: #004daa !important;
    color: #e8e6e3 !important;
}
}
```
Of all the inlined sheets the one matching this content is ```html head style.darkreader.darkreader--user-agent```. the ```darkreader--user-agent``` string can be found in the files:
*/src/inject/dynamic-theme/css-collection.ts
*/src/inject/dynamic-theme/index.ts

It's apparently interacting with the ```#firefox-screenshots-preselection-iframe``` element that the screenshot functionality injects for the overlay. The element gets darkreader inline styles that immediatly reapply themselves if disabled, if the extension has been run in the page.

-------------------------------------------
Updating firefox to version 127.0.0 solves the issue on firefox's side, given the screenshot functionality no longer injects the ```#firefox-screenshots-preselection-iframe``` element and the screenshot overlay seems to be part of the browser's UI now (notice the UI difference in the "Save full page | Save visible" widget between my comment and the cannot-reproduce second comment). 
https://www.mozilla.org/en-US/firefox/127.0/releasenotes/#note-790169

The incompatibility is probably still present in the extension code, but I guess the issue may be closed at dev's discretion with "update at least to version 127.0.0" as a forward-facing fix.

**Comment by Myshor** [comment]
Ok. Closing.
