### ISSUE TITLE
Dark theme not detected in MalwareTips.com

### ISSUE THREAD

**Issue by paradoxicallist** [darkreader/darkreader#13297]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Dark Reader does not detect native dark theme

### Website Address

https://malwaretips.com/

### Steps To Reproduce

Sign in the website

### Operating System

Windows 10 x64

### Web Browser name and version

Chrome 129.0.6668.71 (Official Build) (64-bit)

### Dark Reader version

4.9.94

**Comment by Myshor** [comment]
Can not reproduce:
Before login (so default light theme).
![obraz](https://github.com/user-attachments/assets/67d188eb-b3f9-49f9-b068-1d092d9834c9)

After login (with enabled dark theme in profile settings):
![obraz](https://github.com/user-attachments/assets/b747a9e0-9d0f-4dc9-a44f-3070ada2be3a)

**Comment by paradoxicallist** [comment]
OK, it's working but I always need to refresh the page.
Anyway thanks.

**Comment by paradoxicallist** [comment]
OK, it's working but I always need to refresh the page.
Anyway thanks.
