### ISSUE TITLE
[Broken Website] Webhallen.com broken elements

### ISSUE THREAD

**Issue by Squtzy** [darkreader/darkreader#13307]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When using dark mode on Webhallen.com some elements are broken. (As can be seen in provided screenshots). Some are affected more than others making them completely invisible when using dark mode.
Examples of broken elements:
Certain product category elements.
Upvote markers on product pages.
"Supply Drop" Timer.

### Website Address

https://www.webhallen.com/

### Steps To Reproduce

Go to Webhallen.com
Enable Dark Mode
See mentioned elements broken
Disable Dark Mode 
Elements are working/visible again.

### Screenshots

![Broken Elements 1](https://github.com/user-attachments/assets/c995e90d-fcf8-4faa-83a3-70c96be84f55)
![Broken Elements 2](https://github.com/user-attachments/assets/1ca0ead8-786a-44a8-bd9d-37ff426e9fb5)
![Broken Upvotes Dark Mode](https://github.com/user-attachments/assets/cf0b8453-2f1d-41a1-aed5-d282ad11b15f)
![Upvotes DarkMode Disabled](https://github.com/user-attachments/assets/19163d55-2a7b-482e-a6b4-b41c598d0e93)
![Broken Timer Supply Drop](https://github.com/user-attachments/assets/8313c2fb-2e2b-4d9d-8856-e8d4e72ce809)
![DarkMode Disabled Timer](https://github.com/user-attachments/assets/870df465-a845-4eb2-a333-c35d987ca1cd)

### Operating System

Windows 11

### Web Browser name and version

Firefox 130.0.1

### Dark Reader version

4.9.92

### Additional Context

"Supply Drop" Timer can be found only when having a members account, under profile -> Supply Drops -> Weekly Drop.
Upvote Markers on reviews for any product with a review.
Product panels/elements as show in screenshot.

**Comment by Myshor** [comment]
I will add sitefixes in a minute but there will be one thing I can not do without account:
"Supply Drop" Timer can be found only when having a members account, under profile -> Supply Drops -> Weekly Drop.

So... Can you Save this page with Dark Reader disabled as complete page and send the zipped to my email (which can be find in my Github profile). With it I could analyse how the page is created and what will be needed to be fixed with that timer. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by Myshor** [comment]
I will reopen this when I recieve the "Supply Drop" page on email. 😉
