### ISSUE TITLE
How to detect if darkreader is active?

### ISSUE THREAD

**Issue by Richienb** [darkreader/darkreader#1330]
Is there a way to detect if **darkreader** is active so my website can adjust accordingly?

If there isn't such a way, I suggest that a variable should be defined and an event like `themechanged` on the document element should be triggered when the theme changes.

**Comment by alexanderby** [comment]
My opinion is that website should not rely on extensions. I'm not sure if the extension can store it's own global objects and trigger it's own events. The content script runs in a sandbox.

**Comment by Gusted** [comment]
```javascript
document.querySelector('meta[name="darkreader"]');
```

**Comment by milahu** [comment]
see also #4342
