### ISSUE TITLE
[vinted.fr] Information icon is not visible in dark mode with Dark Reader

### ISSUE THREAD

**Issue by oeloo** [darkreader/darkreader#13321]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

On Vinted , in the infox, the Information icon is not visible in dark mode with Dark Reader.

### Website Address

https://www.vinted.fr/inbox/12753454775

### Steps To Reproduce

1. Go to Vinted.fr (and certainly Vinted in any other country)
2. Log on
3. Go to the message inbox and open a thread

### Screenshots

Here is the webpage with Dark Reader enabled: the 'i' icon is not visible
![image](https://github.com/user-attachments/assets/2aab7c00-291a-4ca0-891c-03821645e437)

Here is the same webpage with Dark Reader disabled: the 'i' icon is visible
![image](https://github.com/user-attachments/assets/14355e36-9bf7-4499-b369-a472231946b8)

### Operating System

Windows 11 fully uptodate

### Web Browser name and version

Chrome browser fully uptodate

### Dark Reader version

Fully up to date

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
