### ISSUE TITLE
[Broken Website] Washington Post comments have white background

### ISSUE THREAD

**Issue by StevenSchifter** [darkreader/darkreader#13324]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Upon loading the comments section of a Washington Post article, that section appears to be unmodified by Dark Reader. The space around the comments is dark as expected though.

Toggling Dark Reader off and then back on for the website (or re-applying site fixes from the developer tools) will fix the comments section.

### Website Address

https://wapo.st/3Y77Rjx

### Steps To Reproduce

1. Open a Washington Post article.
2. Scroll to the comments section (or click the comment button at the top of the article).
3. Notice how the comments section loads with dark text on a white background, instead of light text on a dark background (as expected).
4. Toggle Dark Reader off and then back on for the website (or re-apply site fixes from the developer tools).
5. Notice how the comments section is now dark as expected.

### Screenshots

![image](https://github.com/user-attachments/assets/55237cfe-c174-4c60-afc2-cfb66ee18cf7)
![image](https://github.com/user-attachments/assets/3203a547-c3ee-4a73-be84-f0db345de008)

### Operating System

Windows 11 Home

### Web Browser name and version

Brave Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

### Dark Reader version

Version 4.9.94

### Additional Context

This issue may be similar to #11466, but @Myshor recommended in my PR (#13316) that I open a separate issue and mention @alexanderby in it, so that is what I am doing.

**Comment by Myshor** [comment]
I just give the other link which doesn't ask for email to read and go down for comments section:
https://www.washingtonpost.com/advice/2024/10/02/carolyn-hax-boyfriend-obsessed-ex/

**Comment by StevenSchifter** [comment]
I have an idea for a workaround to this issue: Add a shortcut to the function provided by the "Apply" button in Dark Reader's Developer Tools to the context menu and/or the extension pop-up. This would allow quick manual fixing of page styles without having to endure the page flashing caused by turning Dark Reader off and then back on. Perhaps it could be called "Reapply site fixes".

**Comment by alexanderby** [comment]
No worries, I'm trying to find ways to detect styles on those strange Shadow DOM elements.
