### ISSUE TITLE
bugs.chromium.org: Default settings => unreadable

### ISSUE THREAD

**Issue by wmertens** [darkreader/darkreader#1333]
![image](https://user-images.githubusercontent.com/54934/58007952-a7a4a800-7aeb-11e9-9b40-920602d1ca06.png)

Example url: https://bugs.chromium.org/p/boringssl/issues/detail?id=9&q=&colspec=ID%20Type%20Status%20Pri%20Owner%20Summary%20Modified

Using the dynamic engine. The landing page of that site works fine.

**Comment by deathtrip** [comment]
Same problem here. For me it's the only page that is unreadable with the dynamic engine. Would be nice to get this fixed.

**Comment by yisonPylkita** [comment]
Same problem for me

**Comment by Gusted** [comment]
#2892

**Comment by FranklinYu** [comment]
Hi, thank you very much for the PR. It works for most elements on the page, but the text of search bar is still too dark to be legible.

**Comment by Gusted** [comment]
Hi @FranklinYu 

Unfortunate is the black search test part of the input that's bein overruled from the standard useragent style, I've tried to override this, but unfortunate it won't let me.
