### ISSUE TITLE
[Broken Website] fitgirl-repacks.site

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13333]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

White background.

![image](https://github.com/user-attachments/assets/990c37ee-e610-4ae1-ae5e-2761d0981215)

### Website Address

https://fitgirl-repacks.site/

### Steps To Reproduce

Go to site.

### Operating System

Linux

### Web Browser name and version

Firefox latest

### Dark Reader version

DR latest

**Comment by Myshor** [comment]
sitefix added

**Comment by Myshor** [comment]
Fix in a minute. 😝

**Comment by Myshor** [comment]
And one more selector update for that white background images on lists

this time the paw list was ugly 😋

**Comment by Myshor** [comment]
It was pushed yesterday... Forget to mention the issue in fix. 😅
#13339
