### ISSUE TITLE
Chat window in Slack's web app not darkened in Chrome.

### ISSUE THREAD

**Issue by jmrossy** [darkreader/darkreader#1334]
Firstly thank you for this great extension!!

I noticed that the support for Slack's web client stopped working in Chrome recently. The Slack app used to darken fine but now it's unaffected by DarkReader. It still works in Firefox.

Any ideas what the problem might be? Suggestions for fixes?

Tested in Chrome Version 74.0.3729.157 (current latest version)

**Comment by Gusted** [comment]
Fixed.

**Comment by jmrossy** [comment]
@Gusted Verified fixed. Thanks Gusted!!
