### ISSUE TITLE
[Broken Website] docs.nestjs.com

### ISSUE THREAD

**Issue by lerethel** [darkreader/darkreader#13345]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Some elements on https://docs.nestjs.com/ are invisible with Dark Reader turned on. Reloading the page sometimes fixes the issue. The issue occurs with the dark theme as well as the light theme of the website. Moreover, the sidebar sometimes becomes white with the light theme.

### Website Address

docs.nestjs.com

### Steps To Reproduce

1. Go to the website
2. Enable Dark Reader
3. If there's no problem, try reloading the page
4. Also try turning on the light theme of the website

### Screenshots

Dark Reader is on, website's dark theme:
![image](https://github.com/user-attachments/assets/e30c0336-a17e-4c1f-8199-cc14734e36a2)

Dark Reader is off, website's dark theme:
![image](https://github.com/user-attachments/assets/4514d855-b60c-4ca4-9cbd-b273799be0ff)

Dark Reader is on, website's light theme:
![image](https://github.com/user-attachments/assets/168edc17-c2c0-422f-8a82-809c005209a3)

### Operating System

Windows 11

### Web Browser name and version

Firefox 131.0

### Dark Reader version

4.9.94

**Comment by Myshor** [comment]
The fix for the red vanishing elements will be in a minute. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
