### ISSUE TITLE
[Broken Website] DoorDash.com Active Order Map Not Displayed In Dark Mode

### ISSUE THREAD

**Issue by SugarD-x** [darkreader/darkreader#13343]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Due to yet another change to DoorDash.com, (because they are constantly making them), they have recently switched to Mapbox's GL JS map feature on pages showing active delivery orders. While DarkReader properly darkens the website, this map is not changing to dark mode at all, resulting in a light mode map on a darkened page.

### Website Address

https://www.doordash.com/orders/Any_Accessible_Order_Number_Here

### Steps To Reproduce

1. Make an order on DoorDash.com with DarkReader enabled.
2. Be redirected to the page showing the active order pending delivery.
3. The webpage shows itself in dark mode, however the map is still in light mode.

### Screenshots

![doordashlightmodemap](https://github.com/user-attachments/assets/c7853a3a-a05e-4de1-a155-cace8d64fb91)
(For privacy reasons, much of the page was intentionally hidden from the screenshot, however you can see the page being on dark mode along the top and right edges, while the map in the center is in light mode).

### Operating System

Microsoft Windows 11 Pro x64 23H2 Build 22631.4249

### Web Browser name and version

Microsoft Edge Version 129.0.2792.79 (Official build) (64-bit)

### Dark Reader version

Version 4.9.95

### Additional Context

This issue has been present ever since DoorDash switched map vendors again. As the issue is specific to an order delivery page that is not accessible outside of the applicable account, nor is the map shown after an order is delivered and a user leaves the page, I am not able to provide a full test URL for this.

From basic research, I did locate the following information page regarding the map vendor that is used in case that helps debug it. I wouldn't be surprised if other websites using this map vendor were affected too.

https://docs.mapbox.com/mapbox-gl-js/api/map/

**Comment by Myshor** [comment]
Sorry but without available page with order (I bet the finished and delivered should work too) it would be hard to make a fix. Specially when we are not in United States and not using this site.

To make some fixes (if possible) we need to analyze the site how it is built and then we can apply some CSS fixes to it. Without it we won't be able to do anything.

**Comment by SugarD-x** [comment]
Unfortunately these map pages are only accessible during certain points and are account-specific. I don't have any knowledge of it myself, but since it is a third-party embedded map, I'd be willing to bet that it probably affects every website using it.

After a little research, I did find this page that has an example world map. After zooming it, it appears to possibly use the same resource, (although I'm not sure if it is actually the same form of the map or not), but it is also affected by the dark mode bug where it only shows in light mode on the actual map. Hopefully fixing that one would fix the DoorDash one too, and presumably any others that use the same map. It does have an option that can be changed from "globe" to "satellite-v9", (which the latter is likely what I've seen on DoorDash's website).

https://docs.mapbox.com/mapbox-gl-js/guides

**Comment by Myshor** [comment]
The maps are embedded in most sites and it's needed to make inverts to specific parts of the page.

Sometimes it's canvas. Sometimes iframe. Really there is no possibility to guess how the map is embedded into the site and make fix for all.

As I wrote earlier. I tried to make the step with the map but I ended with order where I needed to enter full adress and give my payment details. So I ended in this point and removed whole order.

For the page `https://docs.mapbox.com/mapbox-gl-js/guides` it's canvas based with nicely used class `.mapboxgl-canvas` which can be inverted and whole map goes to "Dark Mode" but even if I will add some sitefix to doordash including this class I can not guarantee it will work.

You can test if that will work:
Go to Dark Reader's Settings.
In settings click Advanced Tab.
Then on the right click "Developer Tools"

When the new window open click CTRL + F and find `doordash.com`

Then Add one more line in INVERT section:
`.mapboxgl-canvas`

it should look like this
![obraz](https://github.com/user-attachments/assets/7057f813-119b-4160-a236-7f464a1d2f87)

Click apply button and check if the map will be working nice with Dark Mode.

If not then it's different solution used on doordash than on docs.mapbox.com
If yes then I can push the fix I proposed to test into Dark Reader sitefixes. 😉

**Comment by SugarD-x** [comment]
That does appear to be working so far for me! You are awesome for that :)

**Comment by Myshor** [comment]
Ok. As you confirm it works I will push the fix.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by Myshor** [comment]
One more info... As you tried the fix and used "Apply" button in developer tools it's recommended to Reset changes:
![obraz](https://github.com/user-attachments/assets/4cf00cd3-fcb4-4be9-91da-815b698d0afb)

After this step the new sitefixes will be added without any problems.

**Comment by SugarD-x** [comment]
Awesome, thank you! All appears to be working now.

Just for the record, I absolutely love this extension. I use it on all my personal systems, and it has been integrated on all of our computers at my work too, as well as one of my personal websites. Thank you for all the effort you put in to make it the #1 dark mode extension out there! <3
