### ISSUE TITLE
[Broken Website] Pickleheads News Preferences

### ISSUE THREAD

**Issue by nik312123** [darkreader/darkreader#13362]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

- If you have a Pickleheads account, when going to the news preferences, the toggles to the right of Newsletter, Tutorials, and Local News disappear with Dark Reader enabled.

### Website Address

https://news.joinpickleheads.com/subscribe/[account-specific-id]/preferences

### Steps To Reproduce

1. Create a Pickleheads account by clicking the "Join for free" button at https://www.pickleheads.com/ and follow their steps for creating an account.
2. Go to https://news.joinpickleheads.com.
3. Click the profile image (or default profile image) in the upper-right corner of the website, and click Manage Subscription.
4. On the left-hand sidebar, click Preferences.
5. The toggles to the right of Newsletter, Tutorials, and Local News disappear when Dark Reader is enabled and reappear when disabled.

### Screenshots

Enabled:
![enabled](https://github.com/user-attachments/assets/8e5bc2db-68ff-4380-912d-19ce040a2ee1)

Disabled:
![disabled](https://github.com/user-attachments/assets/7cd832a6-476a-40b9-ac0e-71743717520f)

### Operating System

macOS Sonoma 14.6.1

### Web Browser name and version

Brave 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64) 

### Dark Reader version

4.9.95

**Comment by Myshor** [comment]
It will be a little bit different colors than on original page without Dark Redader enabled but I will push a sitefix to make it visible in a minute.

**Comment by Myshor** [comment]
Results will be:
![obraz](https://github.com/user-attachments/assets/e1230384-7e1b-4ab4-bd1b-14a13acd5487)

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by nik312123** [comment]
Awesome! I also didn't realize there was an option to enable on restricted pages, or I would have done so long ago. I hate being blinded by the chrome webstore every time.

**Comment by nik312123** [comment]
Oh... It didn't work on the Chrome web store despite the `Extensions on chrome:// URLs` flag being enabled for me. :(

**Comment by Myshor** [comment]
Restricted pages works fine on Firefox for sure. Not even tried to check it on Chrome based browsers.
https://github.com/darkreader/darkreader#enable-dark-reader-on-restricted-pages-on-mozilla-firefox
