### ISSUE TITLE
Firefox Mobile "could not be installed because it appears to be corrupt"

### ISSUE THREAD

**Issue by ashrafhadden** [darkreader/darkreader#1336]
- PIxel 1st gen.
- Android OS v9 (May 5th security patch)
- Firefox Mobile v66.0.2

![image](https://user-images.githubusercontent.com/32565770/58151874-0deb1100-7c39-11e9-9bb3-cf0608b03754.png)

**Comment by Gusted** [comment]
Officially support, fixed.
