### ISSUE TITLE
Long loading time with insane HDD I/O

### ISSUE THREAD

**Issue by Silur** [darkreader/darkreader#1337]
## Issue
First (after bootup) launch of firefox (66.0.5, x86_64 arch linux) with **only** darkreader enabled takes ~3 minutes to pass the `Loading please wait` stage which drains my HDD with 100% read usage.

## Steps to reproduce
Reboot linux (Linux  5.1.2-arch1-1-ARCH #1 SMP PREEMPT Wed May 15 00:09:47 UTC 2019 x86_64 GNU/Linux), start firefox with all but darkreader addon disabled

**Comment by Gusted** [comment]
Should be fixed.
