### ISSUE TITLE
[Broken Website] Webhallen.com Checkout 

### ISSUE THREAD

**Issue by Squtzy** [darkreader/darkreader#13380]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When attempting to submit an order on Webhallen.com using the "Klarna Payments" payment method the customer info box is broken using dark mode. (See screenshots)
Other payment methods are working fine. I think this might be a "general issue" with the Klarna Payments boxes but I am not fully certain about this. 

### Website Address

https://www.webhallen.com

### Steps To Reproduce

Go to Webhallen.com
Put something in your cart
Go to checkout
Choose something random for the steps
When at payment methods select KLARNA
The info box that appears is broken with Dark Reader enabled for the website.

### Screenshots

![image](https://github.com/user-attachments/assets/ba0aafdc-f606-4b62-a866-08b94b2a8bca)
![image](https://github.com/user-attachments/assets/4e6c1970-4e5a-45b0-b4ce-597cdcf392f0)

### Operating System

Windows 11

### Web Browser name and version

Firefox 131.0.3 (64-bit)

### Dark Reader version

4.9.94 (Latest at the time on Mozilla Store)

### Additional Context

As I said earlier, this might be something related to the Klarna Payment boxes, which could be a general fix for Klarna Payment boxes globally if that is possible (?) (klarna.com)

**Comment by Myshor** [comment]
Fix will be in a minute.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
