### ISSUE TITLE
[Bug] Icon missing in Firefox address bar

### ISSUE THREAD

**Issue by RaphTronic** [darkreader/darkreader#13385]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

After installing the DR extension on Firefox, the dark reader icon never showed up on the address bar next to the usual icons (history, account, settings, etc). However it is active and successfully applying a dark theme to the pages visited. But can't turn it on / off and change its setting from its icon like with other extensions.

Steps tried:
* uninstalled DR, reinstalled it
* disabled all extensions except DR
* closed Firefox, reopened it

### Website Address

any

### Steps To Reproduce

1. install DR
2. disabling all the other extensions, reinstalling dark reader, closing and reopening firefox: made no difference

### Expected Behavior

Expected DR icon to show up on the address bar next to the other firefox icons.

### Actual Behavior

no DR icon showing in address bar next to the firefox icons (history, account, settings, etc)

### Screenshots

![image](https://github.com/user-attachments/assets/e360693a-2d01-47dd-9b7c-6311b18065b7)

### Operating System

windows 10 Version	10.0.19045 Build 19045

### Web Browser name and version

Firefox 131.0.3 (64-bit)

### Dark Reader version

4.9.94

**Comment by Myshor** [comment]
It's not a Dark Reader's bug.

It's normal thing in Firefox.

You need to:

1. Click this icon. 
![obraz](https://github.com/user-attachments/assets/ad394e70-3e30-4d98-b010-7e46ae1d8be9)
It will show all installed extensions.
2. Click on the cogwheel:
![obraz](https://github.com/user-attachments/assets/ad394e70-3e30-4d98-b010-7e46ae1d8be9)
3. There you will see "Pin to toolbar" or similar option that will move icon to the bar.

**Comment by Myshor** [comment]
Just confirm it will work then we can close the "issue"

**Comment by RaphTronic** [comment]
Hi Myshor,

Thanks for coming back to me on this.

Indeed, I have been looking for this "Pin to Toolbar" menu after searching for help. But I could not find such a setting. 

Below are the menus showing under this extension. (_note that although the 3rd pic shows other extensions enabled, I had also initially done a test without any other extension_)

Did I miss looking somewhere else ?

Thanks,
Raph.

![image](https://github.com/user-attachments/assets/cdc94b41-f156-4068-8566-0eda145e9225)

![image](https://github.com/user-attachments/assets/67ebec69-9182-4a98-83df-aaecfe87ff43)

![image](https://github.com/user-attachments/assets/dfef9703-5f4a-4b1d-829f-dfccd7ac816b)

**Comment by RaphTronic** [comment]
My apologies !

I always accessed the extension settings via FF's App Setting Menu > Add-ons and Themes > Extensions (which shows the same icon as in your post). No pin to toolbar menu there.

But clicking directly on the icon in the toolbar does show pin to toolbar. It worked !

Extremely confusing that depending on the path taken one gets different menus.

Anyway will close this issue.

Thanks for the help,
Raph

**Comment by RaphTronic** [comment]
Closed per the update above (menu showing only if directly clicking on icon instead of from within Setting > Extensions)
