### ISSUE TITLE
[Broken Website] order.mandarake.co.jp - dark reader not working there

### ISSUE THREAD

**Issue by AxelTerizaki** [darkreader/darkreader#13390]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Only input boxes seem to change when using Dark Reader. Once on the main page, every other background stays white.

### Website Address

https://order.mandarake.co.jp

### Steps To Reproduce

1. Go to Website
2. When arriving on the website, click "Earth" to get to the english version of the site.

### Screenshots

![firefox_wPQit8Y30m](https://github.com/user-attachments/assets/879473be-2365-4872-88c0-285418d27fc5)

### Operating System

Windows 11

### Web Browser name and version

Firefox 131.0.3

### Dark Reader version

4.9.94

**Comment by Myshor** [comment]
I can not reach the URL. Maybe someone else will be able to take a look on this.

**Comment by alexanderby** [comment]
I was able to open it with VPN. The fix will be published soon.
