### ISSUE TITLE
[Broken Website] zed.dev

### ISSUE THREAD

**Issue by mak448a** [darkreader/darkreader#13394]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The text on the top says "The editor for what's next," but you can't see it if dark reader is enabled.

### Website Address

zed.dev

### Steps To Reproduce

Open zed.dev with dark reader enabled

### Screenshots

![image](https://github.com/user-attachments/assets/272e5fe4-55eb-451b-a6b6-54eeb7f3df85)
![image](https://github.com/user-attachments/assets/280d4382-5080-4ce8-be50-2509320fd32f)

### Operating System

Fedora Linux 40 KDE

### Web Browser name and version

Chromium

### Dark Reader version

4.9.95

**Comment by Myshor** [comment]
I will add sitefix in a few minutes.
