### ISSUE TITLE
[Broken Website] Bad image contrast on pronote

### ISSUE THREAD

**Issue by loulou64490** [darkreader/darkreader#13467]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Just doesn't work well, particularly the background image

### Website Address

https://demo.index-education.net/pronote/eleve.html

### Steps To Reproduce

1. Login to the demo

### Operating System

Windows 11, Fedora 41

### Web Browser name and version

Brave Version 1.71.121 Chromium: 130.0.6723.91 (Build officiel) (64 bits)

### Dark Reader version

Version 4.9.96

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
