### ISSUE TITLE
[Broken Website] Casas Bahia site don't work

### ISSUE THREAD

**Issue by eliottmusk** [darkreader/darkreader#13464]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The Casas Bahia and Americanas sites don't work well, the products images is fully black! Both are huge stores in Brazil.

https://www.americanas.com.br
https://www.casasbahia.com.br

### Website Address

.

### Steps To Reproduce

.

### Screenshots

.

### Operating System

.

### Web Browser name and version

.

### Dark Reader version

Last version

**Comment by Myshor** [comment]
One sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by eliottmusk** [comment]
Thank you! About Casas Bahia maybe a proxy can help.

**Comment by Myshor** [comment]
OK... found some VPN I could use for free for a while and was able to touch https://www.casasbahia.com.br/

Second sitefix will be in a minute. 😉
