### ISSUE TITLE
[Broken Website] igraal.com website has white background when you are logged on this website

### ISSUE THREAD

**Issue by oeloo** [darkreader/darkreader#13466]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

On https://igraal.com/ website, the background is plain white when you are logged on (when you are not logged on the background is black as expected)

### Website Address

https://fr.igraal.com/

### Steps To Reproduce

1. Go to igraal.com
2. Log on with any account (you can create one for free) (!: It is imperative to log in because the white background issue ONLY happens when you log on)
3. you can then notice the background color is mainly white instead of dark when Dark Reader is enabled

### Screenshots

![image](https://github.com/user-attachments/assets/eded3a50-7729-4a35-8a57-3fe1330a84b3)

### Operating System

Windows 11 (up to date as of 20241104)

### Web Browser name and version

Google Chrome (up to date as of 20241104)

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
