### ISSUE TITLE
[Broken Website] https://one.one.one.one/ bars very barely visible

### ISSUE THREAD

**Issue by Copy05** [darkreader/darkreader#13477]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The Bars are barely visible with dark mode (see image). A great idea would be to give it a brighter color.

![image](https://github.com/user-attachments/assets/74c7f537-73e7-4f7d-96bf-b3c84cbaadf2)

### Website Address

https://one.one.one.one/

### Steps To Reproduce

https://one.one.one.one/

### Screenshots

![image](https://github.com/user-attachments/assets/74c7f537-73e7-4f7d-96bf-b3c84cbaadf2)

### Operating System

Windows 10 22H2

### Web Browser name and version

Chrome Version 119.0.6045.160 & Edge Version 122.0.2365.80

### Dark Reader version

Version 4.9.96

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
