### ISSUE TITLE
[Broken Email] imap: Dark text on dark background

### ISSUE THREAD

**Issue by ngoclong19** [darkreader/darkreader#13474]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The security warning email that I get from Google when I sign in to my Google account on a new device.
With Dark Reader disable, it has dark text on light background.
With Dark Reader enable, it has dark text on dark background.

### Website Address

imap:

### Steps To Reproduce

1. Sign in to your Google account on a new device, or a private browser window.
2. Open the warning email from Google in Thunderbird.

Or use the email source below, I removed irrelevant headers and personal information.
Save it as `email.eml` then open it with Thunderbird, or upload to your mailbox and view in Thunderbird.

<details>
<summary>Security warning email source</summary>

```eml
Subject: =?UTF-8?B?Q+G6o25oIGLDoW8gYuG6o28gbeG6rXQ=?=
From: Google <no-reply@accounts.google.com>
To: username@example.com
Content-Type: multipart/alternative; boundary="00000000000071d0a30626381e29"
Content-Length: 7497

--00000000000071d0a30626381e29
Content-Type: text/plain; charset="UTF-8"; format=flowed; delsp=yes
Content-Transfer-Encoding: base64

W2ltYWdlOiBHb29nbGVdCk3hu5tpIMSRxINuZyBuaOG6rXAgdHLDqm4gQW5kcm9pZAoKCnVzZXJu
YW1lQGdtYWlsLmNvbQpDaMO6bmcgdMO0aSBwaMOhdCBoaeG7h24gdGjhuqV5IGPDsyBt4buZdCB5
w6p1IGPhuqd1IMSRxINuZyBuaOG6rXAgbeG7m2kgdsOgbyBUw6BpIGtob+G6o24gR29vZ2xlCmPh
u6dhIGLhuqFuIHRyw6puIG3hu5l0IHRoaeG6v3QgYuG7iyBBbmRyb2lkLiBO4bq/dSDEkcOieSBs
w6AgecOqdSBj4bqndSBj4bunYSBi4bqhbiwgdGjDrCBi4bqhbgpraMO0bmcgcGjhuqNpIGzDoG0g
Z8OsIHRow6ptLiBO4bq/dSDEkcOieSBraMO0bmcgcGjhuqNpIGzDoCB5w6p1IGPhuqd1IGPhu6dh
IGLhuqFuLCB0aMOsIGNow7puZwp0w7RpIHPhur0gZ2nDunAgYuG6oW4gYuG6o28gbeG6rXQgdMOg
aSBraG/huqNuLgpLaeG7g20gdHJhIGhv4bqhdCDEkeG7mW5nCjxodHRwczovL2FjY291bnRzLmdv
b2dsZS5jb20vQWNjb3VudENob29zZXI+CkLhuqFuIGPFqW5nIGPDsyB0aOG7gyB4ZW0gaG/huqF0
IMSR4buZbmcgYuG6o28gbeG6rXQgdOG6oWkKaHR0cHM6Ly9teWFjY291bnQuZ29vZ2xlLmNvbS9u
b3RpZmljYXRpb25zCkNow7puZyB0w7RpIGfhu61pIGVtYWlsIG7DoHkgxJHhu4MgdGjDtG5nIGLD
oW8gY2hvIGLhuqFuIGJp4bq/dCB24buBIG5o4buvbmcgdGhheSDEkeG7lWkgcXVhbgp0cuG7jW5n
IMSR4buRaSB24bubaSBUw6BpIGtob+G6o24gR29vZ2xlIHbDoCBk4buLY2ggduG7pSBj4bunYSBi
4bqhbi4KwqkgMjAyNCBHb29nbGUgTExDLCAxNjAwIEFtcGhpdGhlYXRyZSBQYXJrd2F5LCBNb3Vu
dGFpbiBWaWV3LCBDQSA5NDA0MywgVVNBCg==
--00000000000071d0a30626381e29
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html lang=3D"en"><head><meta name=3D"format-detection" cont=
ent=3D"email=3Dno"/><meta name=3D"format-detection" content=3D"date=3Dno"/>=
<style nonce=3D"Qste3B11_LHootrv7n_rCw">.awl a {color: #FFFFFF; text-decora=
tion: none;} .abml a {color: #000000; font-family: Roboto-Medium,Helvetica,=
Arial,sans-serif; font-weight: bold; text-decoration: none;} .adgl a {color=
: rgba(0, 0, 0, 0.87); text-decoration: none;} .afal a {color: #b0b0b0; tex=
t-decoration: none;} @media screen and (min-width: 600px) {.v2sp {padding: =
6px 30px 0px;} .v2rsp {padding: 0px 10px;}} @media screen and (min-width: 6=
00px) {.mdv2rw {padding: 40px 40px;}} </style><link href=3D"//fonts.googlea=
pis.com/css?family=3DGoogle+Sans" rel=3D"stylesheet" type=3D"text/css" nonc=
e=3D"Qste3B11_LHootrv7n_rCw"/></head><body style=3D"margin: 0; padding: 0;"=
 bgcolor=3D"#FFFFFF"><table width=3D"100%" height=3D"100%" style=3D"min-wid=
th: 348px;" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" lang=3D"en"><t=
r height=3D"32" style=3D"height: 32px;"><td></td></tr><tr align=3D"center">=
<td><div itemscope itemtype=3D"//schema.org/EmailMessage"><div itemprop=3D"=
action" itemscope itemtype=3D"//schema.org/ViewAction"><link itemprop=3D"ur=
l" href=3D"https://accounts.google.com/AccountChooser"/><meta itemprop=3D"n=
ame" content=3D"Xem l=E1=BA=A1i ho=E1=BA=A1t =C4=91=E1=BB=99ng"/></div></di=
v><table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"padding-=
bottom: 20px; max-width: 516px; min-width: 220px;"><tr><td width=3D"8" styl=
e=3D"width: 8px;"></td><td><div style=3D"border-style: solid; border-width:=
 thin; border-color:#dadce0; border-radius: 8px; padding: 40px 20px;" align=
=3D"center" class=3D"mdv2rw"><img src=3D"https://www.gstatic.com/images/bra=
nding/googlelogo/2x/googlelogo_color_74x24dp.png" width=3D"74" height=3D"24=
" aria-hidden=3D"true" style=3D"margin-bottom: 16px;" alt=3D"Google"><div s=
tyle=3D"font-family: &#39;Google Sans&#39;,Roboto,RobotoDraft,Helvetica,Ari=
al,sans-serif;border-bottom: thin solid #dadce0; color: rgba(0,0,0,0.87); l=
ine-height: 32px; padding-bottom: 24px;text-align: center; word-break: brea=
k-word;"><div style=3D"font-size: 24px;">M=E1=BB=9Bi =C4=91=C4=83ng nh=
=E1=BA=ADp tr=C3=AAn Android </div><table align=3D"center" style=3D"margin-=
top:8px;"><tr style=3D"line-height: normal;"><td align=3D"right" style=3D"p=
adding-right:8px;"><img width=3D"20" height=3D"20" style=3D"width: 20px; he=
ight: 20px; vertical-align: sub; border-radius: 50%;;" src=3D"https://lh3.g=
oogleusercontent.com/a/ACg8ocIO9PEVHg5sZ5iEhQBuuBmyMtPdpj9VzGcoUEkaedXKSEQ-=
WPt7=3Ds96-c" alt=3D""></td><td><a style=3D"font-family: &#39;Google Sans&#=
39;,Roboto,RobotoDraft,Helvetica,Arial,sans-serif;color: rgba(0,0,0,0.87); =
font-size: 14px; line-height: 20px;">username@gmail.com</a></td></tr></tabl=
e> </div><div style=3D"font-family: Roboto-Regular,Helvetica,Arial,sans-ser=
if; font-size: 14px; color: rgba(0,0,0,0.87); line-height: 20px;padding-top=
: 20px; text-align: center;">Ch=C3=BAng t=C3=B4i ph=C3=A1t hi=E1=BB=87n th=
=E1=BA=A5y c=C3=B3 m=E1=BB=99t y=C3=AAu c=E1=BA=A7u =C4=91=C4=83ng nh=
=E1=BA=ADp m=E1=BB=9Bi v=C3=A0o T=C3=A0i kho=E1=BA=A3n Google c=E1=BB=A7a b=
=E1=BA=A1n tr=C3=AAn m=E1=BB=99t thi=E1=BA=BFt b=E1=BB=8B Android. N=
=E1=BA=BFu =C4=91=C3=A2y l=C3=A0 y=C3=AAu c=E1=BA=A7u c=E1=BB=A7a b=
=E1=BA=A1n, th=C3=AC b=E1=BA=A1n kh=C3=B4ng ph=E1=BA=A3i l=C3=A0m g=C3=
=AC th=C3=AAm. N=E1=BA=BFu =C4=91=C3=A2y kh=C3=B4ng ph=E1=BA=A3i l=C3=A0 y=
=C3=AAu c=E1=BA=A7u c=E1=BB=A7a b=E1=BA=A1n, th=C3=AC ch=C3=BAng t=C3=B4i s=
=E1=BA=BD gi=C3=BAp b=E1=BA=A1n b=E1=BA=A3o m=E1=BA=ADt t=C3=A0i kho=
=E1=BA=A3n.<div style=3D"padding-top: 32px; text-align: center;"><a href=3D=
"https://accounts.google.com/AccountChooser" target=3D"_blank" link-id=3D"m=
ain-button-link" style=3D"font-family: &#39;Google Sans&#39;,Roboto,RobotoD=
raft,Helvetica,Arial,sans-serif; line-height: 16px; color: #ffffff; font-we=
ight: 400; text-decoration: none;font-size: 14px;display:inline-block;paddi=
ng: 10px 24px;background-color: #4184F3; border-radius: 5px; min-width: 90p=
x;">Ki=E1=BB=83m tra ho=E1=BA=A1t =C4=91=E1=BB=99ng</a></div></div><div sty=
le=3D"padding-top: 20px; font-size: 12px; line-height: 16px; color: #5f6368=
; letter-spacing: 0.3px; text-align: center">B=E1=BA=A1n c=C5=A9ng c=C3=
=B3 th=E1=BB=83 xem ho=E1=BA=A1t =C4=91=E1=BB=99ng b=E1=BA=A3o m=E1=BA=
=ADt t=E1=BA=A1i<br><a style=3D"color: rgba(0, 0, 0, 0.87);text-decoration:=
 inherit;">https://myaccount.google.com/notifications</a></div></div><div s=
tyle=3D"text-align: left;"><div style=3D"font-family: Roboto-Regular,Helvet=
ica,Arial,sans-serif;color: rgba(0,0,0,0.54); font-size: 11px; line-height:=
 18px; padding-top: 12px; text-align: center;"><div>Ch=C3=BAng t=C3=B4i g=
=E1=BB=ADi email n=C3=A0y =C4=91=E1=BB=83 th=C3=B4ng b=C3=A1o cho b=
=E1=BA=A1n bi=E1=BA=BFt v=E1=BB=81 nh=E1=BB=AFng thay =C4=91=E1=BB=95i quan=
 tr=E1=BB=8Dng =C4=91=E1=BB=91i v=E1=BB=9Bi T=C3=A0i kho=E1=BA=A3n Google v=
=C3=A0 d=E1=BB=8Bch v=E1=BB=A5 c=E1=BB=A7a b=E1=BA=A1n.</div><div style=3D"=
direction: ltr;">&copy; 2024 Google LLC, <a class=3D"afal" style=3D"font-fa=
mily: Roboto-Regular,Helvetica,Arial,sans-serif;color: rgba(0,0,0,0.54); fo=
nt-size: 11px; line-height: 18px; padding-top: 12px; text-align: center;">1=
600 Amphitheatre Parkway, Mountain View, CA 94043, USA</a></div></div></div=
></td><td width=3D"8" style=3D"width: 8px;"></td></tr></table></td></tr><tr=
 height=3D"32" style=3D"height: 32px;"><td></td></tr></table></body></html>
--00000000000071d0a30626381e29--
```
</details>

### Operating System

Windows 10 Pro 22H2 19045.5073 64-bit

### Web Browser name and version

Thunderbird 128.3.3esr 64-bit

### Dark Reader version

4.9.68

### Additional Context

In Thunderbird developer console, there's an error:

```log
Unchecked lastError value: Error: URL constructor: //fonts.googleapis.com/css?family=Google+Sans is not a valid URL. index.js:4210
    sendDocumentMessage moz-extension://2396db4e-0d67-49e7-b431-bf5735ada042/background/index.js:4210
```

---

It works fine when saving the email as HTML and viewing it in Firefox.

**Comment by Myshor** [comment]
I confirm however I am not sure how and where all thunderbird functionality works in Dark Reader.
Maybe @alexanderby can take a look and give more info.

Maybe there could be some update for Thunderbird version. :)

**Comment by Myshor** [comment]
I am back... I managed to find how to fix it. 😉

The "sitefix" is added.

To have this fix you need to have "Synchronize site fixes" option enabled.
You can find it in Thunderbird version of Dark Reader opening Dark Reader's popup and then click "Settings -> Manage settings".
![obraz](https://github.com/user-attachments/assets/dc72112f-1ea6-41bf-99a4-34d445207e0c)

**Comment by ngoclong19** [comment]
I confirm that the fix works. Thank you, Myshor!

However, I have a little concern. I still have that JavaScript error, mentioned in the issue description, in Thunderbird browser console:
`URL constructor: //fonts.googleapis.com/css?family=Google+Sans is not a valid URL`.

**Comment by ngoclong19** [comment]
I confirm that the fix works. Thank you, Myshor!

However, I have a little concern. I still have that JavaScript error, mentioned in the issue description, in Thunderbird browser console:
`URL constructor: //fonts.googleapis.com/css?family=Google+Sans is not a valid URL`.

I think the root cause is that due to the exception above, Dark Reader stops before it can finish calculating the text color.

When I save the email as HTML, then open it in Firefox, and viewing the page source, I can see that the URL is also doesn't have any protocol.
Firefox automatically adds `http`/`https` protocol, so Dark Reader doesn't complain here.

I'm not sure if this is a Firefox quirk or we can do anything in Thunderbird.

**Comment by Myshor** [comment]
I will comment as much as I can.

First thing - Dark Reader for Thunderbird was released as modified version of Dark Reader for Firefox. Even trying to import Firefox addon into Thunderbird will end with no working Dark Mode. As we can see the version of Dark Reader for Thunderbird is a little bit (nicely said 😝) outdated compared to browser version and we need to consider it as totally different product (similar as Dark Reader for Safari).
Second thing - I found that if some colors are included in html tags in email then Dark Reader for Thunderbird doesn't apply it's own colors for that part of email. Comparing to Dark Reader for browsers it does apply it's colors even when color is included in some part of html code (there is some exceptions when developer of html code will use `!important` in his code but this we can fix with our `!important` in sitefixes in most cases).
Third thing (last but not least) - as the Dark Reader for Thunderbird was released as moddified browser one it won't be easy (at least in my humble opinion) to make some upgrades to it so the only thing which I could do i to make some style sitefixes for `:imap` and `:pop3`

Summarizing... Until @alexanderby would add his comment saying there will be some fixes and new version od Dark Reader for Thunderbird then only thing I can do is doing sitefixes for it if possible. 😉

**Comment by ngoclong19** [comment]
As the option "Synchronize site fixes" is not enabled by default, so there is this unrelated news.
Mozilla Thunderbird 136 has native support for dark mode, and it is compatible with the Google email mentioned in this issue report. This feature is not perfect yet.
https://www.thunderbird.net/en-US/thunderbird/136.0/releasenotes/

> Messages are automatically adapted to dark mode with a quick toggle in the header.

**Comment by Myshor** [comment]
I installed newest Thunderbird and removed Dark Reader from it.

Dark Mode made in it sometimes makes more things black compared to dark reader but at least I did not have issues with light text on light background yet.

For any new issues related to Thunderbird I will suggest to try newest Thunderbird with default dark mode for emails. 😁
