### ISSUE TITLE
[Broken Website] Kivra.se Dark Theme

### ISSUE THREAD

**Issue by Squtzy** [darkreader/darkreader#13483]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When using Auto Detect or just dark theme, parts of the kivra.se website goes invisible unless you turn off dark theme for the website. Can be see in submitted screenshots

### Website Address

https://kivra.se/

### Steps To Reproduce

Enable auto detect theme in dark reader or enable dark theme once opening website.
Go to kivra.se
See elements broken when using dark theme

### Screenshots

![image](https://github.com/user-attachments/assets/93e004ed-6140-4e0b-b851-deb2eeb52d80)
![image](https://github.com/user-attachments/assets/65f42515-5520-46ea-9c23-22c4531d0777)

### Operating System

Windows 11 24H2

### Web Browser name and version

Firefox 132.0.1 (64-bit)

### Dark Reader version

4.9.96

### Additional Context

Issue is not strictly when using dark theme detection but dark theme in general for the website.

**Comment by Myshor** [comment]
Dark reader hides everything on the page with z-index smaller than 0 when applying it's CSS.

I will add sitefix to show that picture and make it a little darker so white text will be readable on it.
