### ISSUE TITLE
DarkReader Makes Video Rendering Choppy

### ISSUE THREAD

**Issue by k4yt3x** [darkreader/darkreader#1349]
## Issue

Watching YouTube or some other video sites with DarkReader turned on makes the video **framerate drop** and causes video **tearing**.

This only seems to apply to **Filter** and **Filter+** mode when the video is under the filter.

## Browser and System Information

|Component|Version|
|-|-|
|OS|Windows 10 1809|
|Browser|Firefox 67.0|
|DarkReader|4.7.12|

**Comment by luuknieuwdorp** [comment]
+1, experiecing the same issue. Does not seem to be happening on chromium based browsers for me.

**Comment by Gusted** [comment]
This is a issue to take up with browsers. They have for each frame after decoding it apply a filter over it. Also it should be fixed.
