### ISSUE TITLE
[Broken Website] Webhallen.com completely broken again

### ISSUE THREAD

**Issue by Squtzy** [darkreader/darkreader#13517]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

After the "Black Week" sale started 2024-11-15 00:00 UTC+1 time dark mode has completely broken the website.
Used a random product page to showcase that this issue is global across this website.

### Website Address

https://www.webhallen.com

### Steps To Reproduce

Install Dark Reader
Go to Webhallen.com
Enable dark mode
Entire website broken

### Screenshots

![image](https://github.com/user-attachments/assets/4da18e52-bed5-46ad-b69b-6afffe53791b)
![image](https://github.com/user-attachments/assets/0d736692-6323-4daa-bd53-3d77c2b6dd7a)

### Operating System

Windows 11 24H2

### Web Browser name and version

Firefox 132.0.2 (64-bit)

### Dark Reader version

4.9.96

### Additional Context

Not specific to "front page" or a specific product page. This issue is across the entire website no matter the page. A lot of

**Comment by Myshor** [comment]
I checked on Firefox and MS Edge and on both I have no problems and page is displayed in dark.
![obraz](https://github.com/user-attachments/assets/004f86de-0575-4348-905c-315ea2b6742a)

**Comment by Squtzy** [comment]
> I checked on Firefox and MS Edge and on both I have no problems and page is displayed in dark. ![obraz](https://private-user-images.githubusercontent.com/56877029/386995881-004f86de-0575-4348-905c-315ea2b6742a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzI3NTEsIm5iZiI6MTczMTg3MjQ1MSwicGF0aCI6Ii81Njg3NzAyOS8zODY5OTU4ODEtMDA0Zjg2ZGUtMDU3NS00MzQ4LTkwNWMtMzE1ZWEyYjY3NDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE5NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNGNhMmQzMzY2YmY5NWY3NGMwYTlmM2NhOGMyZjJlNTA2OGY2ZDAwYTE5NjAxMDgyMmFjOTQ3MDc1MDM0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3QCaxv_R9tb8ryS9GehQjAVbbGriKGiI2G30ds56tXQ)

Hm okay, I'll try reinstalling Dark Reader and see if that changes anything. I cleared the site cookies and tried private windows in Firefox and it didn't do the dark theme.

**Comment by Myshor** [comment]
Maybe try to go to Dark Reader Developer Tools and there click "Reset changes" to be sure the sitefixes that was added in #13313 are included.

**Comment by Squtzy** [comment]
> Maybe try to go to Dark Reader Developer Tools and there click "Reset changes" to be sure the sitefixes that was added in #13313 are included.

I reinstalled Dark Reader, no change. Disabled UBlock Origin and Enhanced Protection in Firefox. No change, also tried in private window and still broken.
I will try this suggestion and report back if it does anything

**Comment by Squtzy** [comment]
> Maybe try to go to Dark Reader Developer Tools and there click "Reset changes" to be sure the sitefixes that was added in #13313 are included.

I tried this and also reset Dark Reader settings and no change. I really don't know why it isn't working for me. Nothing has changed on my system since it stopped working.

**Comment by Myshor** [comment]
It looks like it does not even apply Dark Reader to it.
Check one more thing if it's not listed here:
![obraz](https://github.com/user-attachments/assets/73b16be6-06f9-425b-88a6-a291d1541e0d)

Is Dark Reader working for other sites normally?

**Comment by Squtzy** [comment]
> It looks like it does not even apply Dark Reader to it. Check one more thing if it's not listed here: ![obraz](https://private-user-images.githubusercontent.com/56877029/386996789-73b16be6-06f9-425b-88a6-a291d1541e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzM1NjgsIm5iZiI6MTczMTg3MzI2OCwicGF0aCI6Ii81Njg3NzAyOS8zODY5OTY3ODktNzNiMTZiZTYtMDZmOS00MjViLTg4YTYtYTI5MWQxNTQxZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDE5NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YjU5YzNjYzcxNmUxMGFkMzE2MDQ0N2FhZWE3MDc4Y2QwNmEzMmFhMDk0Nzc1YWJiZjY4ZmM1MmQzOTU4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pbwDf0mRmivQO50-7MEzffSwEf7DH-cXebUtdvGMYbU)
> 
> Is Dark Reader working for other sites normally?

Only website in that is Github after I reset Dark Reader. Works on other sites no issue. It enables some dark mode on Webhallen like you could see in my screenshots. But it doesn't do it the right way and not in the elements in should.

**Comment by Squtzy** [comment]
![image](https://github.com/user-attachments/assets/3570313f-b00c-48e4-9b78-80523fa1044e)
Here is another screenshot to show. I logged out so you can see that it enabled Dark Mode in the username and password box but it doesn't convert the text color to be visible when it does. And the side panels where you would have black week ads if you don't use adblockers change but not the main parts of the website

**Comment by Myshor** [comment]
Can you share what exact addons you have added except Dark Reader?
That ad blocking is what I suspect. I use uBlock Origin with default settings and I still can not confirm but as you could see it showed me the black week "ads".

**Comment by Squtzy** [comment]
Private Window, only Dark Reader Addon. No Dark mode:
![image](https://github.com/user-attachments/assets/f481f063-9aee-4f50-8b7d-651def1eb96b)

Private Window, only Dark Reader Addon, with dark mode forced enabled:
![image](https://github.com/user-attachments/assets/c6fa5cd6-ea14-45d5-8efb-f325d7503f2f)

**Comment by Squtzy** [comment]
As you can see in the outlined part Dark Reader "enabled" dark theme on the search bar text, also the power rating shown next to the samsung tv product image is also changed. 
![Skärmbild 2024-11-17 212255](https://github.com/user-attachments/assets/5f6eb761-2fae-4a7d-8dfc-1e4ab51e5ea4)

**Comment by Myshor** [comment]
Tried again... removed all cache. Made account on the page. Still can not make it white. I am out of ideas what can cause the problem.

**Comment by Squtzy** [comment]
Thats so weird. I’ll just see if it goes away eventually then. Sorry for
the inconvenience

mån 18 nov. 2024 kl. 10:36 skrev Patryk Łachan ***@***.***>:

**Comment by Squtzy** [comment]
Hi again, just wanted to let you know that I randomly got the dark theme working again. I cleared my browser cache which I had already done a few times to test if it helped and now it worked randomly. Sorry for the inconvenience yet again. This doesn't seem to be a issue any longer. @Myshor

**Comment by Myshor** [comment]
Can you close the issue? If you close it then I think you will be able to re-open if it will come back. When I close then you won't be able to do that. 😉

**Comment by Squtzy** [comment]
> Can you close the issue? If you close it then I think you will be able to re-open if it will come back. When I close then you won't be able to do that. 😉

Sorry I missed your reply. I will close it :)
