### ISSUE TITLE
Odd colour scheme at drafts.csswg.org

### ISSUE THREAD

**Issue by heydojo** [darkreader/darkreader#1354]
https://drafts.csswg.org/css-color-adjust-1/#color-scheme-meta

An interesting document and Dark reader isn't handling it very well.
The proposal is about the dark and light CSS color schemes proposed by the guys developing webkit.

In Firefox the page renders the left sidebar without dark colours.

**Comment by aaronth07** [comment]
Switching the site to "Filter+" makes it look better.

**Comment by Gusted** [comment]
`VM27 index.js:8 DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules` We litteraly can't access the CSS Rule.

**Comment by Gusted** [comment]
Fixed.
