### ISSUE TITLE
[Broken Website] notesnook.com

### ISSUE THREAD

**Issue by mak448a** [darkreader/darkreader#13546]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Notesnook.com is already in dark theme. It doesn't need to have dark reader applied to it.

### Website Address

notesnook.com

### Steps To Reproduce

1. Open notesnook.com on a fresh chromium profile with dark reader installed.
2. The website has dark reader toggled on. It should be off, since the website is dark.

### Operating System

Fedora Linux 41 KDE

### Web Browser name and version

Chromium 130.0.6723.116

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Adding site to dark-sites.config

This will automatically disable Dark Reader for this site.

However fix will be available with new release of Dark Reader.
