### ISSUE TITLE
[Broken Website] https://journals.aps.org

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#13553]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Recently the website https://journals.aps.org underwent a CSS change which seems to have messed up the colors in dark mode.

### Website Address

https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.133.216002

### Steps To Reproduce

1. Go to the link.
2. Colors in front of you.

### Operating System

Linux

### Web Browser name and version

Firefox 132.0.2-1

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Without screenshots there was only guessing what you think is bad or good.

I will push some sitefixes that I found it would be nice to have in a minute. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by paniash** [comment]
Hi! Thanks for the quick fix and apologies for not sharing the screenshots. There are certain elements in the page that are blinding white.

![image](https://github.com/user-attachments/assets/1ad1c54c-a52f-4865-b93d-0733f3e592db)

**Comment by Myshor** [comment]
It was ugly to fast fix as it has different color untouched and different on hover. INVERT was breaking it so I didn't touch it.

Today I looked at this again and I will add the fix for that buttons in a minute. 😉

**Comment by paniash** [comment]
Thanks! Could you also fix the figure section which is white?

![image](https://github.com/user-attachments/assets/370639b7-4f37-450c-844a-c041333e40d2)

**Comment by Myshor** [comment]
Can you share the url? I did not saw this in the main page and shared link.

**Comment by paniash** [comment]
It's the same link: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.133.216002

**Comment by Myshor** [comment]
OK. I know why I didn't touch it.
It's locked to me... subscription needed.
![obraz](https://github.com/user-attachments/assets/12de3a06-dc9c-49d9-8ca6-36dba515f833)

**Comment by paniash** [comment]
Ah okay. That's unfortunate. Thanks anyway.

**Comment by paniash** [comment]
Thanks but I meant inverting the figure heading only. Not the images.

> Thanks! Could you also fix the figure section which is white?
> 
> ![image](https://private-user-images.githubusercontent.com/59497618/391356701-370639b7-4f37-450c-844a-c041333e40d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzk5MTYsIm5iZiI6MTczMzMzOTYxNiwicGF0aCI6Ii81OTQ5NzYxOC8zOTEzNTY3MDEtMzcwNjM5YjctNGYzNy00NTBjLTg0NGEtYzA0MTMzM2U0MGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE5MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOTU2Y2Y3MmIxNzI3ZmJkODU4ZWJhMjJjZjQwODRjNDhiZDMxNzU2YTkyNWQ1M2UzM2M5NGU3ZWJmMzA4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9WPNkyy4v8eoRaQ_W8b_eZ6pJ0uYA267B3VbebYKl40)

Basically the white heading which says "Fig 1.". Thanks for your help!

**Comment by Myshor** [comment]
Small missunderstanding... 🙄

I will add selector for this into sitefixes in a minute and still leave the invert for figures pictures as you did not complain about that. 😁

**Comment by paniash** [comment]
> Small missunderstanding... 🙄
> 
> I will add selector for this into sitefixes in a minute and still leave the invert for figures pictures as you did not complain about that. 😁

Thank you very much! If you could just make the images non-inverted, that'd be great!

**Comment by Myshor** [comment]
Revert for that invert will be in a minute. 😉

**Comment by paniash** [comment]
Thank you so much! One last thing: could you perhaps increase the contrast of the caption text under the images? i.e. they're currently gray. Making the text color a bit lighter would improve contrast against the dark background.

![image](https://github.com/user-attachments/assets/d5ab27b0-d65d-492c-babc-9ea0bc4da078)

**Comment by Myshor** [comment]
One more fix before going to sleep. 😉

**Comment by paniash** [comment]
Thank you so much!
