### ISSUE TITLE
[Broken Website] Updated nightbot.tv pages have issue with application on pages until refresh

### ISSUE THREAD

**Issue by nik312123** [darkreader/darkreader#13550]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

An issue occurs with the new nightbot.tv UI when accessing some pages, usually fixed upon an additional refresh.

This primarily occurs with the left-hand sidebar not having the coloration correctly applied, but it did also occur with the main content itself once for me. Though, I was unable to replicate it.

### Website Address

https://nightbot.tv/dashboard (and other pages you can select from the sidebar)

### Steps To Reproduce

1. Visit https://nightbot.tv/dashboard
2. Log in
3. See the problem described above

### Screenshots

![nightbot](https://github.com/user-attachments/assets/558c5ee8-4a42-4bab-99b4-fd0ecd9d9ef8)

Note: Hid username in above graphic. Otherwise, the image is unchanged.

### Operating System

macOS

### Web Browser name and version

Brave 1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64)

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
