### ISSUE TITLE
Darklang

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1356]
https://darklang.com/

Seems a bit off, especially on the button.

**Comment by aaronth07** [comment]
That is because the site was created with specific colors for the background in mind and the PNG files were colored for that reason. Switching the site to "Filter" makes it look a lot better.

**Comment by ShalokShalom** [comment]
Can we use that default?

**Comment by aaronth07** [comment]
Dynamic is best in 90% of the cases, you can however change it to filter for that site only.

**Comment by ShalokShalom** [comment]
I mean to adjust the dynamic theme so that it works more like the filter in this case.

**Comment by aaronth07** [comment]
Oh. No, I don't think you can adjust the dynamic theme. The developer may
be able to add an exception to that site specifically though.

**Comment by ShalokShalom** [comment]
Yes, I report sites here on Github since quite a while and this is how it happens. :smiley:

**Comment by Gusted** [comment]
LGTM
