### ISSUE TITLE
[Broken Website] https://tinte.railly.dev/shadcn

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#13572]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Cant see or preview the themes

### Website Address

https://tinte.railly.dev/shadcn

### Steps To Reproduce

1. Go on the website

### Screenshots

![Bildschirmfoto_20241201_094145](https://github.com/user-attachments/assets/e072f0ea-c632-469a-a4b0-3c89327a4b02)
![Bildschirmfoto_20241201_094133](https://github.com/user-attachments/assets/8deb27c3-54d4-412f-a785-5ea2f0611192)

### Operating System

Linux

### Web Browser name and version

Brave

### Dark Reader version

current

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
