### ISSUE TITLE
[Broken Website] https://multilingual.com/magazine/

### ISSUE THREAD

**Issue by xfq** [darkreader/darkreader#13578]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The color of the logo is very dark and can't be seen clearly.

### Website Address

https://multilingual.com/magazine/

### Steps To Reproduce

Go to https://multilingual.com/magazine/ with any DR settings unchanged.

### Screenshots

<img width="1060" alt="Screenshot 2024-12-03 at 22 20 03" src="https://github.com/user-attachments/assets/63914011-c0f6-4077-b2e6-d7a3513d6399">

### Operating System

macOS 14.7.1

### Web Browser name and version

Chrome 131

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by xfq** [comment]
Thank you!
