### ISSUE TITLE
[Broken Website] Kipling website - Dark reader is slowing down firefox

### ISSUE THREAD

**Issue by noamkush** [darkreader/darkreader#13582]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When entering the Kipling USA website, the website does (mostly) load but then a warning appears saying that dark reader is slowing down Firefox and advising to stop dark reader.

### Website Address

https://www.kipling-usa.com/

### Steps To Reproduce

Navigate to https://www.kipling-usa.com/ and start scrolling

### Screenshots

![image](https://github.com/user-attachments/assets/36af2cf2-cb09-4350-96bc-9b28994d0993)

### Operating System

Windows 11

### Web Browser name and version

Firefox 133.0

### Dark Reader version

4.9.96

**Comment by neorai** [comment]
same problem, slow all websites, uninstall

**Comment by PavleSap** [comment]
Issues here too. Browser freezes until I disable the extension.

**Comment by bush911** [comment]
same here 
also borken for reddit.com starting from today.

**Comment by alexanderby** [comment]
If you could share more URLs where you see the error, it could be useful.

**Comment by privacyguy123** [comment]
> same here also borken for reddit.com starting from today.

I found this too - opened a seperate issue for it. Glad to see it's not just me I guess?

**Comment by alexanderby** [comment]
It is important to understand, if this is some problem with an update on Reddit.com website only. The latest Dark Reader update was published around a month ago, and the latest Firefox update was last week. I understand there is an issue with the Kipling website, but it could be there long before.

Until this is fixed I would suggest to disable Dark Reader for Reddit or enable dark theme detection (click under website toggle button) and use the Reddit's built-in dark theme or use Filter mode for Reddit/Kipling.

**Comment by alexanderby** [comment]
The problem with the Kipling website happens in Chrome too. The other one with Reddit was fixed.

**Comment by alexanderby** [comment]
There is a problem with a weird script from some Pixlee library, that removes the element when its inline color changes, and recreates it from scratch. This is what causes an infinite loop.

The fix will be available in the next release.
