### ISSUE TITLE
[Broken Website] learnyouahaskell.com

### ISSUE THREAD

**Issue by l0f3n** [darkreader/darkreader#13599]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Darkreader only makes the website slightly darker, but the text is still black. Seems to work better on the landing page but is broken once you go to /chapters or any specific chapter.

### Website Address

https://learnyouahaskell.com/chapters

### Steps To Reproduce

Visit, for example, https://learnyouahaskell.com/introduction.

### Screenshots

Off: 
![image](https://github.com/user-attachments/assets/e9bc21a1-a516-4390-a04f-89938a2124c3)

On:
![image](https://github.com/user-attachments/assets/8b0ec66a-40e2-4b99-86d8-e48b38c0882a)

### Operating System

Arch Linux

### Web Browser name and version

Firefox 133.0 

### Dark Reader version

4.9.96

### Additional Context

The transparency effect is due to my WM, please disregard that.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by l0f3n** [comment]
Thanks for the quick fix and instructions! Looks a lot better now! 

These code excerpts are stil white and the contrast on these extra explanation blocks have quite low constrast so its hard to read. Should probably have mentioned that in my earlier screenshot...

https://learnyouahaskell.com/making-our-own-types-and-typeclasses#typeclasses-102

![image](https://github.com/user-attachments/assets/2ebb0b48-4b0b-4d4d-a9a2-2ecf563696c6)

**Comment by Myshor** [comment]
I can fix the yellow hintboxes to look like this:
![obraz](https://github.com/user-attachments/assets/72c26284-6f5a-485e-9752-77cca18386f0)

 but I tried to confirm that code with white background and I can not cofirm it neither on Firefox or MS Edge (Chromium based browser).

**Comment by l0f3n** [comment]
Thanks! The yellow looks great! If you could make the code stick out from the rest of the text in some way that would be great, but if you just make it the same color its fine too. Thanks for being so attentive :)

**Comment by l0f3n** [comment]
Oh, I just noticed the margin seems to be gone below the code in the image you sent. That does not look nice :(

**Comment by Myshor** [comment]
Little longer as I choose color for code background. 😝

**Comment by Myshor** [comment]
![obraz](https://github.com/user-attachments/assets/c5357d17-15b9-46f7-bf29-c895bf5a0bcb)

The result should be fetched with new sitefixes after browser restart as you already have the option to synchronize enabled. 😉

**Comment by l0f3n** [comment]
Im starting to feel quite annoying, but it still doesnt work for me. Yellow looks good though.

![image](https://github.com/user-attachments/assets/4d248962-8384-492e-8663-cae7023aa654)

I can manually disable this inline css at the bottom to make it look quite nice.

![image](https://github.com/user-attachments/assets/b8af067a-3b30-4690-803e-d1d4316ff6d0)

**Comment by Myshor** [comment]
OK... this is second INVERT from old sitefix that my browser doesn't even found on page... OK... Last changes. I will remove forcing background for code and remove that INVERT. Then you can share the results here. 😉

**Comment by Myshor** [comment]
You can try now. I hope it will be good now.

**Comment by l0f3n** [comment]
It looks great now, thanks! <3

![image](https://github.com/user-attachments/assets/67015c2e-062f-4a87-a8f6-9890e966650b)
