### ISSUE TITLE
Add option to not filter text

### ISSUE THREAD

**Issue by g2bb** [darkreader/darkreader#1361]
This isn't so much an issue, but a suggestion, or more like a plea. Please give us the option to turn off the filtered text color. I really can't stand the brown/tan text and I've tried modifying everything I can find, but I'm just not smart enough to know what to change to make everything normal colors.

*EDIT* I am referring to the Dynamic theme here. I'm not sure how the other themes fair, but I do know, apart from the tan text, the Dynamic theme looks much nicer and closer to the original.

**Comment by Gusted** [comment]
Fixed. You can modify the color.
