### ISSUE TITLE
[Bug] Firefox - DR dark theme turns everything completely black

### ISSUE THREAD

**Issue by bencetuzson** [darkreader/darkreader#13612]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

After the last update (to v4.9.97), I experienced full-black text and UI elements, making the menus, tab titles, icons, etc., unreadable. Please find the screenshots attached.

### Website Address

any

### Steps To Reproduce

1. Plugin update
2. Launch Firefox

### Expected Behavior

A readable theme

### Actual Behavior

An unreadable theme

### Screenshots

Theme off:
![image](https://github.com/user-attachments/assets/68afc972-5193-40ce-ab09-ba513b287035)

Theme on:
![image](https://github.com/user-attachments/assets/1adb7737-6fe1-41b5-84ac-52de6a4234eb)

### Operating System

Windows 11

### Web Browser name and version

Firefox - 134.0b9 (64-bit)

### Dark Reader version

4.9.97

**Comment by alexanderby** [comment]
Did this option work before?

**Comment by bencetuzson** [comment]
Yes, it did. The extension was updated today, and it was working perfectly prior to that.

**Comment by bencetuzson** [comment]
After reinstalling the extension, the issue remains

**Comment by alexanderby** [comment]
I've submitted a fix for a review. The last time I requested an expedited review it took them 2 days to respond. So the only way is to disable this option.

**Comment by bencetuzson** [comment]
Thank you!

**Comment by Artim96** [comment]
In my experience, it only happens when you enable that feature. When you close firefox and open it again, it's gone.

**Comment by Artim96** [comment]
Edit: this also affects e.g. the history side bar. @alexanderby could you please check if your fix also fixes this?

**Comment by bcutter** [comment]
It breaks really everything (in system dark mode) as nothing is visible (everything black) except some tab or extension icons. Workaround is to disable "Change browser theme":

![grafik](https://github.com/user-attachments/assets/b040bb81-e020-416c-b280-6017764e65ea)

**Comment by 3clypse** [comment]
> It breaks really everything (in system dark mode) as nothing is visible (everything black) except some tab or extension icons. Workaround is to disable "Change browser theme":
> 
> ![grafik](https://private-user-images.githubusercontent.com/13799156/395822483-b040bb81-e020-416c-b280-6017764e65ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMjYxNzAsIm5iZiI6MTczNDIyNTg3MCwicGF0aCI6Ii8xMzc5OTE1Ni8zOTU4MjI0ODMtYjA0MGJiODEtZTAyMC00MTZjLWIyODAtNjAxNzc2NGU2NWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDAxMjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YTFmMGViMWFiZGJlYWFlMDk2MmQ5OTcyZDMzOGE5OWQyYjYyNTQ5ZDcwMjlhYmZjYTRiMzZiNzhhZjg5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YyKYqluXqvuJvtHNg3D1FxKQdKlkxKqUAs9VVMsYMRI)

Thank you!! It worked! :DD

**Comment by CaptainFrosty** [comment]
I also have this bug on FF 133.0.3 even when 'style system controls' is off. It turns my browser UI and new tab page black.

**Comment by Wizardling** [comment]
I also experience this with Dark Reader Version 4.9.97 in Firefox 134.0b10 on Windows 11 24H2.
It began two days ago. The above workaround works for me, also. I miss the DR theme, but I'll make do without till it is sorted.

**Comment by alexanderby** [comment]
The version 4.9.99 has been finally reviewed.
