### ISSUE TITLE
[Broken Website] "GESTIS-Stoffdatenbank" broken in dynamic

### ISSUE THREAD

**Issue by Artim96** [darkreader/darkreader#13618]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

in dynamic mode, pretty much nothing of the website is turned dark. You need to use Filter or Filter+

### Website Address

https://gestis.dguv.de/

### Steps To Reproduce

1. visit page

### Screenshots

![image](https://github.com/user-attachments/assets/a543825a-44a2-4b6e-80e6-a6ff3a9c9a62)

### Operating System

Debian Testing

### Web Browser name and version

Firefox Nightly 135, Firefox Beta 134 and Firefox 133

### Dark Reader version

4.9.97

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
