### ISSUE TITLE
[Broken Website] alza.sk (but also domains cz/at/hu/de) broken by Version 4.9.97

### ISSUE THREAD

**Issue by Juraj-Masiar** [darkreader/darkreader#13619]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Only first row of products has dark mode, everything below is now light.
Additionally, even the dark part has wrongly computed colors so text is not readable.
This got broken only a day ago and on all my PC, including blank new profile.

### Website Address

https://www.alza.sk/

### Steps To Reproduce

1. open any sub-category, for example:
https://www.alza.sk/mini-pc/18851862.htm
2. scroll below first row

### Screenshots

![image](https://github.com/user-attachments/assets/d20b21fc-bc66-40ca-8577-1da3f3e2863f)

In Chrome it looks fine:
![image](https://github.com/user-attachments/assets/94e6bfa0-39a1-41c4-b4a4-2b60a08a186a)

### Operating System

Windows 11 24h2

### Web Browser name and version

Firefox ESR 128.5.1, but also 134.0b9

### Dark Reader version

4.9.97

**Comment by Juraj-Masiar** [comment]
I've just tried to install previous version 4.9.96 and it fixes the issue.
So this is a 100% regression.

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by Juraj-Masiar** [comment]
Also, if you click any of the products, it's broken too, including background, for example:
https://www.alza.sk/gaming/asus-rog-ally-d7744312.htm
![image](https://github.com/user-attachments/assets/e128ea3f-634b-4e1c-b4c5-c028d18c8045)

**Comment by Myshor** [comment]
It won't be exactly like on screens from Chrome but I tried to darken as much as possible or light the text. 😉

The changes will affect both kind of browsers (so it will be the same in Chromium and Firefox 😝)

The sitefix is prepared I am starting to push it here. 😁

**Comment by Myshor** [comment]
New fixes added.

**Comment by alexanderby** [comment]
@Myshor I found the reason for the error. It is because of a misuse of variables, e.g. they have `color: rgb(var(--x)); --x: initial;` and it produces `color: rgb(initial)` which is invalid and ignored by a browser, but breaks our script.

If you see such regressions or differences between Chrome's 4.9.96 and Firefox's 4.9.97 (4.9.99), please let me know.

**Comment by Juraj-Masiar** [comment]
Hello again :), and happy Christmas holiday!

I've just noticed the page is still broken when using from "Firefox for Android" (alza redirects phones/tablets to "m.alza.sk").

STR (can be reproduces also on desktop):
1. open mobile version page: 
https://m.alza.sk/mini-pc/18851862.htm
(see the "m.alza.<domain>")

2. observe:
![image](https://github.com/user-attachments/assets/726296a3-e355-4a52-934b-9eb74b753c9b)

Thank you!

**Comment by Myshor** [comment]
I will add m.alza.* alias to the fixes... it seem it should be enough. 😉
