### ISSUE TITLE
[Broken Website] https://bugzilla.opensuse.org

### ISSUE THREAD

**Issue by pallaswept** [darkreader/darkreader#13622]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Background is white. If I disable DR for this site and then re-enable it, it works as expected.

### Website Address

https://bugzilla.opensuse.org

### Steps To Reproduce

1. Visit https://bugzilla.opensuse.org
2. Note white background

### Screenshots

![image](https://github.com/user-attachments/assets/b11627c1-5708-4030-a233-fd46662e861c)

### Operating System

OpenSUSE Tumbleweed

### Web Browser name and version

Firefox 133

### Dark Reader version

4.9.97

### Additional Context

This was OK yesterday. I was running 4.9.96. I updated to 4.9.97 to test it out, and it was still OK. I rebooted a few hours later, and it was like this. Not sure if it's the new version, or just a change to the CSS.

Thanks!

**Comment by Myshor** [comment]
What I can propose to check:
1. Be sure you have Synchronize Sitefixes enabled. (to be sure we won't force default sitefixes for release)
2. Open DR's Developer Tools and click "Reset changes". (to be sure no other sitefixes than original one are in use)

Any broken entry in Dark Reader's Developer Tools can disable whole fixes. Reseting changes should fix that.
And not worry to click "Reset Changes" - with "Synchronize sitefixes" enabled it will fetch latest sitefixes.

If this won't help then I will need exact steps to reproduce as I can not confirm it breaks with my try of creating bug there:
![obraz](https://github.com/user-attachments/assets/97ab23a4-d223-46f9-a3e1-16d197431822)

**Comment by Myshor** [comment]
What I think of is some cache related issue that sometimes it loads picture from cache.

Can you try to check how it will work with private window using Dark Reader as only one addon there?

P.S. I do not reopen this as I still can not reproduce anything that I could fix.

**Comment by Myshor** [comment]
> Then, if I double-click this checkbox:
> 
> ![image](https://private-user-images.githubusercontent.com/132128962/396267819-bde9cedd-a42b-4542-bd07-24334dcef133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTEyNzIsIm5iZiI6MTczNDM5MDk3MiwicGF0aCI6Ii8xMzIxMjg5NjIvMzk2MjY3ODE5LWJkZTljZWRkLWE0MmItNDU0Mi1iZDA3LTI0MzM0ZGNlZjEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQyMzE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjIyNTkxZGJiYWU4NjU2NjQ3NGQyYWUxOGJmM2UzM2JkMDU0MzdmNDIxYTBkNzU5OWUwNDMyZjRmYzhkYjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.60Gkakjee5kUs9DXHOCzCJcla915XgXcLdv-VRJ2pTc)

Maybe this is the problem... Fix is for `bugzilla.opensuse.org` and the ULR here says `bugzilla.suse.org`

**Comment by Myshor** [comment]
that other URL is the issue... I will add `bugzilla.suse.com` as alias to previous fix 😉

**Comment by Myshor** [comment]
As you can see updated sitefix is merged. You can check if it helps.

**Comment by Myshor** [comment]
No worries... After last Dark Reader update I had many issues related to wrong rendering in Firefox so I was feeling similar. 😂 At least I catched that different URL and checked that it's needed to be included in fix here too. 🙂
