### ISSUE TITLE
[Already dark] https://www.patreon.com/

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#13638]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Patreon is already dark. With Darkreader applied, is the CVE number of the credit card invisible in the checkout. 

### Website Address

https://www.patreon.com/ 

### Steps To Reproduce

1. Visit homepage
2. Optional: Attempt to subscribe to a service and go to the checkout 

### Operating System

Linux

### Web Browser name and version

Brave

### Dark Reader version

current

**Comment by Myshor** [comment]
I checked 3 different scenarios.
1. Opened https://www.patreon.com/ without loggin in.
It has problems with background videos but it's not easy peasy thing to fix.
2. Logged into patreon and ended on https://www.patreon.com/home
As my system and browser theme is set to dark it opened in dark version.
As my Dark Reader has option to detect dark theme enabled - it nicely detected Dark theme.
3. Switched my system (and browser as it is based on system setting) theme to light.
Patreon after login using light theme - so it's not always dark and can not be added to darksites.

For now I can only propose to enable "Detect Dark Theme" in options.

**Comment by ShalokShalom** [comment]
2 is not true for my case. What browser are you using?

**Comment by Myshor** [comment]
Check if you have Detect Dark Theme enabled - just to be sure:
![obraz](https://github.com/user-attachments/assets/276cb9a7-09a6-4dd3-a810-b523909d8c35)

**Comment by ShalokShalom** [comment]
It was disabled for some reason 😲
