### ISSUE TITLE
[Broken Website] support.mozilla.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13637]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/user-attachments/assets/c0b96021-e781-47b4-81bb-73a7f69fe191)

Bad visibility (right side of the page).

### Website Address

https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature

### Steps To Reproduce

N/A

### Operating System

Linux

### Web Browser name and version

Firefox latest

### Dark Reader version

Latest

**Comment by Myshor** [comment]
I needed to check what was fixing the selector `.card--icon-sm`

And found it related to this site: https://support.mozilla.org/en-US/products/firefox
As it had the same icon darkened it was even easier to compare how to exclude it from inverting.

New sitefix will be pushed in a minute. 😉

**Comment by Myshor** [comment]
I know you have it enabled already but for the people that would look here to check... 😝

Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
