### ISSUE TITLE
[Already dark] https://play.teleporthq.io/

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#13636]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

This site is already dark

### Website Address

https://play.teleporthq.io/

### Steps To Reproduce

1. Enter the website

### Operating System

Linux

### Web Browser name and version

Brave

### Dark Reader version

current

**Comment by ShalokShalom** [comment]
Oh, probably only when you are in editing mode already

![Bildschirmfoto_20241216_212553](https://github.com/user-attachments/assets/1c3a7470-a26d-457a-9592-1601833d9013)

**Comment by Myshor** [comment]
As mentioned already. Not always dark. Rejecting submission.
