### ISSUE TITLE
[Broken Website] NHL.com broken since 4.9.97

### ISSUE THREAD

**Issue by kaanelloed** [darkreader/darkreader#13644]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

First of all, thank you for this amazing project. Since 4.9.97, parts of almost all pages are white in Dynamic mode on NHL.com. For most of them, disabling and enabling the site in Dark Reader results in a dark page. But for pages such as scores and statistics, it remains mostly white.

### Website Address

NHL.com

### Steps To Reproduce

1. Go to NHL.com

### Screenshots

![Screenshot 2024-12-17 at 10-25-46 Official Site of the National Hockey League NHL com](https://github.com/user-attachments/assets/f6e74680-fdfb-45e5-89c4-0b0e917c8a5c)
![Screenshot 2024-12-17 at 10-25-57 NHL Scores Dec 16 2024 NHL com](https://github.com/user-attachments/assets/2260a047-3e41-4725-b707-dc8cc53785f2)
![Screenshot 2024-12-17 at 10-26-10 Schedule Dec 16 2024 NHL com](https://github.com/user-attachments/assets/9e3081b8-7f2b-4a86-a9d1-6314dc77fcda)
![Screenshot 2024-12-17 at 10-26-20 NHL Stats NHL com](https://github.com/user-attachments/assets/acd044fe-4606-4a97-ae74-c3628fe368f4)
![Screenshot 2024-12-17 at 10-26-29 NHL Hockey Standings NHL com](https://github.com/user-attachments/assets/85b43b41-dc88-48c8-8cf8-357f0ed2731b)

### Operating System

Linux Mint 22

### Web Browser name and version

Firefox 133.0.3

### Dark Reader version

4.9.99

**Comment by alexanderby** [comment]
Already fixed it today, but the problem is it will take Mozilla ages to review the fix.

**Comment by kaanelloed** [comment]
Nice, thank you! Since you've been getting a lot of bad reviews lately, I'd like to say that I've been contributing monthly for many years and I think you're doing a wonderful job!
