### ISSUE TITLE
Gitea Docs

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1364]
https://docs.gitea.io/en-us/install-with-docker/

This page seems to have unreadable fonts. I think they deserve to be a bit brighter or so?

Thanks

**Comment by Gusted** [comment]
I don't see the issue anymore 🤷🏽‍♀️

**Comment by ShalokShalom** [comment]
Seems like some commit(s) solved quite a lot of issues, thanks!

**Comment by Gusted** [comment]
No problem and thank you for reporting!
