### ISSUE TITLE
[Broken Website] blog.stevezmt.top didnt show correctly

### ISSUE THREAD

**Issue by SteveZMTstudios** [darkreader/darkreader#13669]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

~~(Shamefully thats my web)~~
this is a blog with hexo framework. and its theme has already built the dark mode.

However, Darkreader still affect this page and make it looks more strange.

### Website Address

blog.stevezmt.top; blog-preview.stevezmt.top

### Steps To Reproduce

1. Switch the browser's layout to dark mode or edit in F12 developer settings.
2. install darkreader
3. refresh

### Screenshots

Before:
![image](https://github.com/user-attachments/assets/1e148046-77be-49a6-8704-eace794aacb1)
After:
![image](https://github.com/user-attachments/assets/21bb3eec-ab1b-4f8f-a8c5-507651caf734)

### Operating System

Kubuntu 24.10 x86_64 Kernel: 6.11.0-13-generic 

### Web Browser name and version

Google Chrome: 131.0.6778.204 Release x64

### Dark Reader version

4.9.96

### Additional Context

however i am a noob for the web development.
this blog is a first try to design a web.

Maybe there are some mistakes about my web and is my wrong. Please point out thx.
Please forgive the poor english cause it is not my original lang.

web source code: github.com/stevezmtstudios/articles

**Comment by Myshor** [comment]
As it checks the system/browser theme I can not push it into darksites.

But I found it adds .mdui-theme-layout-dark class to body so I would add detector hint for this page. 😉
