### ISSUE TITLE
Feature Idea: dynamic dark/light mode derived from Firefox/Chrome via Windows 10

### ISSUE THREAD

**Issue by ThraaxSession** [darkreader/darkreader#1366]
Hi together,

Windows 10 has meanwhile a dark/light mode which will apply to FF. It might be possible that the extensions retrieves an event, when FF changes the mode. So it would be nice, if the extensions switch with FF/Windows automatically. 

Best regards
Gino

**Comment by aaronth07** [comment]
It would be a great idea. I personally have dark mode on Windows 10 enable/disable at a certain time (created through Task Scheduler), so darkreader detecting whether Chrome/Windows has dark mode enabled (and disabling/enabling the extension accordingly) would be an amazing option. Or at the very least, a time scheduler.

**Comment by ThraaxSession** [comment]
@aaronth07 did you take a look at this nice project?
https://github.com/Armin2208/Windows-Auto-Night-Mode

**Comment by aaronth07** [comment]
No, but it does look good. I already have the schedules in task scheduler
though, so no need for me to use that. I will keep it in mind for other
devices though.

**Comment by awtrimpe** [comment]
#1285 Is the best way of achieving this

**Comment by mydexterid** [comment]
AFAIK #1285 is only set if browser.in-content.dark-mode set to true. Which is not yet available in settings, but available in about:config.

**Comment by Gusted** [comment]
https://darkreader.org/blog/automation/

**Comment by yazan1107** [comment]
i use windynamicdesktop for that automation
