### ISSUE TITLE
[Broken Website] Google scholar - no abstract in article view

### ISSUE THREAD

**Issue by daviehh** [darkreader/darkreader#13660]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Example link: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C31&q=%22Information+theoretical+analysis+of+quantum+optimal+control%22&btnG=

The abstract part is not visible with dark reader on

### Website Address

https://scholar.google.com/scholar?hl=en&as_sdt=0%2C31&q=%22Information+theoretical+analysis+of+quantum+optimal+control%22&btnG=

### Steps To Reproduce

turn on dark reader
go to https://scholar.google.com/scholar?hl=en&as_sdt=0%2C31&q=%22Information+theoretical+analysis+of+quantum+optimal+control%22&btnG=

abstract part is invisible

### Screenshots

<img width="1233" alt="Screenshot 2024-12-19 at 18 11 09" src="https://github.com/user-attachments/assets/bf9768c7-dcea-4be6-8bed-3dbb6a784d87" />

### Operating System

maocs

### Web Browser name and version

firefox 134.0b10 and chrome 132.0.6834.57 / latest

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
This is the problem with z-index - all things with z-index <0 Dark Reader is hiting under his "background".

I will push the sitefix in a moment. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by daviehh** [comment]
thanks for the quick fix and detailed explanations!
