### ISSUE TITLE
[Broken Website] rimworldwiki.com - Has Built-in Dark-mode

### ISSUE THREAD

**Issue by Timberfang** [darkreader/darkreader#13680]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

The [wiki](https://rimworldwiki.com) for the game RimWorld has a built-in dark-mode which is inverted by Dark Reader. Disabling Dark Reader on this website seems to fix it.

### Website Address

https://rimworldwiki.com

### Steps To Reproduce

1. Connect to rimworldwiki.com.
2. Observe that the website has a light background when Dark Reader is *on*, and a dark background when it is off.

### Screenshots

**Dark Reader On**
![Rimworld Wiki - Dark Reader On](https://github.com/user-attachments/assets/51fee932-d1ae-4d74-a883-4c6d1a3a8e74)
**Dark Reader Off**
![Rimworld Wiki - Dark Reader Off](https://github.com/user-attachments/assets/b703f0fb-8d32-418c-ba7b-8c7540919082)

### Operating System

Windows 11 Pro 24H2

### Web Browser name and version

Firefox 133.0.3

### Dark Reader version

4.9.99

**Comment by Myshor** [comment]
The problem is that the site is not fully dark... it uses prefers-color-scheme - so it's light in light mode and dark when dark mode is enabled in system/browser so it can not be added to dark-sites.

I managed to force some sitefixes that works with dark and light scheming of the page. I will push it in a minute. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)
