### ISSUE TITLE
[Dynamic] Twitter intent tweet page is white.

### ISSUE THREAD

**Issue by SephirothWS** [darkreader/darkreader#1369]
https://twitter.com/intent/tweet?text=TWEETHERE

As an avid Twitch viewer, I get requests to "Click to tweet" which redirects me to a twitter page similar to the above. With dynamic enabled, the contents of the textbox is black on black, with a blindingly white body element around it.

Firefox 67 on Windows 10 Pro 1803 with Dark Reader v4.7.12

![Image](https://i.imgur.com/RCLqChw.png)

**Comment by SephirothWS** [comment]
This issue continues to persist in Dark Reader v4.7.12

**Comment by nobitagit** [comment]
Just chiming in to say that this looks to be working for me on:

- MAC Mojave, FF 68.0.2 and Dark Reader 4.7.16

![image](https://user-images.githubusercontent.com/2051152/63160882-23e15580-c01f-11e9-9eb9-9fab65fee87f.png)

**Comment by SephirothWS** [comment]
![Image](https://i.imgur.com/o7fADdk.png)

Windows 10; Firefox 75 and Dark Reader v4.9.4

Issue continues to persist. The comment by nobitagit shows how it looks when logged out of Twitter, be logged in and load the page, you get a different look and feel.

**Comment by Gusted** [comment]
![](https://i.imgur.com/2ROjYE3.png) Can't reproduce. allow Darkreader to be operate in icognito and test if darkreader Is really the issue.

**Comment by Gusted** [comment]
Make sure lower the values of privacy & security they are being the problem with Firefox.

**Comment by SephirothWS** [comment]
> 
> 
> Make sure lower the values of privacy & security they are being the problem with Firefox.

This statement doesn't make any sense. What do you mean by that?

**Comment by Gusted** [comment]
> What do you mean by that?

![](https://i.imgur.com/1Hn31tB.png) 
A lot problems occur when people have strict privacy & security rules.
