### ISSUE TITLE
web.whatsapp.com/ Double check

### ISSUE THREAD

**Issue by OmarSandovalPaz** [darkreader/darkreader#1372]
Please fix the double check color, it doesn't change while setting the grayscale to 100

**Comment by Gusted** [comment]
Screenshot?

**Comment by Gusted** [comment]
You can add this

```
.a5DO0 {
    color: var(--icon-ack);
}
``` 

Under 
```
web.whatsapp.com

CSS
```

As of you are using grayscale 100% every color except images are grayish.
