### ISSUE TITLE
[request] whitelist/blacklist should not save in same list

### ISSUE THREAD

**Issue by bluelovers** [darkreader/darkreader#1374]
1. whitelist/blacklist should not save in same list, this make if we wanna switch to another mode, will need delete all list
2. list can't be easy delete more clear, need a multi select and delete

**Comment by hammypants** [comment]
Agree 100% on this: I was trying to experiment with modifying the dynamic setup a bit to just enable better support for native dark themes, so I might use a blacklist setup and default to dark mode "on", but effectively had nowhere I could usefully/trivially test actual cases without a bunch of re-adding & removing-- but then when it came time to swap, it would take a near-century to fix the list...

**Comment by Gusted** [comment]
#28
