### ISSUE TITLE
[Dynamic] Reverses Images

### ISSUE THREAD

**Issue by EMREOYUN** [darkreader/darkreader#1380]
Only Happens in Dynamic Filter.

Example on WhatsApp Web:
Filter Off | Dynamic Filter
![image](https://user-images.githubusercontent.com/35144629/59550835-9fb81680-8f78-11e9-942e-9ba32bf69890.png)

**Comment by Gusted** [comment]
I just checked this issue again, I cannot reproduce this anymore has this been fixed for you also?

**Comment by EMREOYUN** [comment]
Yes, it is fixed with update earlier.
Closed #1380
