### ISSUE TITLE
Salesforce Lightning: Selecting text in a textbox not visible

### ISSUE THREAD

**Issue by SalesforceBobLightning** [darkreader/darkreader#1381]
When using Salesforce and DarkReader, I select text inside a textbox, It's not possible to tell if text in a textbox has been highlighted or not.

How can I fix this?

**Comment by Gusted** [comment]
Hi @SalesforceBobLightning!

Have a look how to change the selection at [the blog](https://darkreader.org/blog/v4-9/)

Regards,
Gusted
