### ISSUE TITLE
Why does it connect to darkreader.github.io ?

### ISSUE THREAD

**Issue by gerroon** [darkreader/darkreader#1385]
Hi

Can you please tell me why this addon connects to darkreader.github.io everytime I start my browser on mobile and desktop?

thanks

**Comment by alexanderby** [comment]
[This](https://darkreader.github.io/blog/posts.json) is a list of available articles in Dark Reader's [blog](https://darkreader.org/blog/).

In recent past it used to load [fixes](https://github.com/darkreader/darkreader/tree/master/src/config) for websites, but since the number of users has grown, this started causing issues for GitHub: approximately 1 terabyte was downloaded every day.

**Comment by gerroon** [comment]
Ok thanks for clarifying

**Comment by SeriousHoax** [comment]
So, is this a must for Dark reader to function properly? My host based adblocker is blocking this site. Should I whitelist it?

**Comment by DRSDavidSoft** [comment]
@SeriousHoax The same domain was also found in my hosts-based adblocker; let me know if you ever whitelisted this domain

**Comment by kajlando** [comment]
Now it connects to "darkreader.org", why?

**Comment by Gusted** [comment]
> Now it connects to "darkreader.org", why?

No? It shouldn't. At least not automatically all links in the pop-up will direct to this domain but fetching the blog post is still `darkreader.github.io` and only still happens on start-up. 

Do you have any specifier URL?

**Comment by kajlando** [comment]
I used this:
sudo netstat -anp | grep ESTABLISHED on browser start
curl [IP]
and then my firewall showed which site this IP wanted to connect to.
IPs:
185.199.110.153
185.199.108.153
185.199.109.153
185.199.111.153

**Comment by Gusted** [comment]
```
185.199.110.153
185.199.108.153
185.199.109.153
185.199.111.153
```
These are under the ip-range of github.io AFAIK darkreader.org is just a CNAME for the darkreader.github.io

@alexanderby ?

**Comment by kajlando** [comment]
After blocking access to darkreader.org news don't appear anymore.

**Comment by Gusted** [comment]
> After blocking access to darkreader.org news don't appear anymore.

Expected behavior. 

> Maybe extensions connects to check news?

Yes? See https://github.com/darkreader/darkreader/issues/1385#issuecomment-503503500

**Comment by Gusted** [comment]
> So, is this a must for Dark reader to function properly? My host based adblocker is blocking this site. Should I whitelist it?

Feel free to block it. It's pure to check up on the blogs/news. Not a must to have it function and never should be.
