### ISSUE TITLE
Complete breaks website

### ISSUE THREAD

**Issue by Programatic** [darkreader/darkreader#1390]
Hi, just here to report that the dark reader extension entire breaks the website toornament.com. It makes the site quite unusable because the site will not load and repeatedly crashes.

**Comment by kunjan343** [comment]
@Programatic I check this website and its working fine. I ran it for about 30 minutes.

![screenshot-www toornament com-2019 06 26-19-04-28](https://user-images.githubusercontent.com/8202667/60220942-bc403280-9845-11e9-81ee-65c2eddad7f4.png)
