### ISSUE TITLE
[Dynamic] chokes to death on www.nodemailer.com

### ISSUE THREAD

**Issue by d53dave** [darkreader/darkreader#1392]
Firefox 67.0.4
Darkreader 4.7.12
MacOS 10.14.5

**Comment by junkntrash** [comment]
Can confirm the bug with Dark Mode on.
The same problem applies for https://sushivesla.by/ 
CPU usage goes up to 80% and RAM depletes in a matter of seconds.
OS: Manjaro stable, with all updates installed
Browser: Firefox 67.0.4
Darkreader 4.7.12
CPU: i5 6600k
RAM: 16GB

**Comment by Gusted** [comment]
Fixed by #2550
