### ISSUE TITLE
It's posible build Dark Reader working on WaterFox ?

### ISSUE THREAD

**Issue by DarKWinGTM** [darkreader/darkreader#1400]
Have anyway to make this extensions working on Alternate Mozila Firefox - Waterfox ?. This browser is not full support WebExtensions for add-on. It's base on firefox 57.

**Comment by ElhemEnohpi** [comment]
@DarKWinGTM Dark Reader works well for me on Waterfox "classic". It's based on Firefox 56, not 57. Waterfox supports many Web Extensions, not only legacy Addons. Have you tried it? Is there some specific problem? Otherwise maybe you can close this issue, as well as #1237

**Comment by Gusted** [comment]
We did a lot of things to make Waterfox Classic compatible.
