### ISSUE TITLE
[Dynamic] Google Sheet, how to change text color 

### ISSUE THREAD

**Issue by Mellielyons** [darkreader/darkreader#1406]
How do I go into Dev Tools and change the text color in Google Sheets? I don't mind that it's not white, I just need it to not be such a dark grey. I can't use a different theme since I use both sheets and docs for work and dynamic works the best. Any help would be appreciative. Thank you.

**Comment by gibfahn** [comment]
Dup of https://github.com/darkreader/darkreader/issues/490

**Comment by Gusted** [comment]
Dup has been closed and fixed.
