### ISSUE TITLE
Todoist Subdomain Issue

### ISSUE THREAD

**Issue by Rakleed** [darkreader/darkreader#1407]
Dark Reader is automatically disabled on todoist.com/app, since you can enable the dark theme for it - this is correct.

But in the settings (todoist.com/prefs) with the dark Todoist theme turned on, the background remains white, as on the Templates page (todoist.com/templates). Screenshots: https://tlgur.com/d/g31DN3O8, https://tlgur.com/d/GVQV9pa8

So please make Dark Reader disable only to todoist.com/app.

**Comment by insipidlight** [comment]
This seems to still be an issue? I had to manually add the `app` after creating a new exclusion in the sites list.
