### ISSUE TITLE
Enable Darkreader in daylight and disable it at night.

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1410]
Hi there :hugs: 	

Darkreader is very useful at night and superflous in bright sunlight.

[You can use such a library to enable/disable Darkreader once the sun is down.](
https://github.com/mourner/suncalc) :crescent_moon:

**Comment by ShalokShalom** [comment]
Woah, I just this feature already exists: 

![Screenshot_20190724_145527](https://user-images.githubusercontent.com/6344099/61795180-191e1100-ae23-11e9-9849-45640e09d472.png)

This is super hidden

**Comment by Gusted** [comment]
Hi in the new UI

```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.
```
We have more visible under Settings -> Automation.
