### ISSUE TITLE
Changes done with developer tools aren't saved

### ISSUE THREAD

**Issue by schumi2004** [darkreader/darkreader#1414]
I wanted to make some minor adjustments for top menu bar for this website https://tweakers.net
I was trying a few things with Developer tools but when i add a new section for this site and click Apply it resets instantly and removing my changes.
I'm using Firefox as browser and runnig it on a Win10 system.

How should you you add changes to Developer tools and could someone put me in the reight direction on how to excluden certain parts or the whole menu bar?

**Comment by Gusted** [comment]
`Ctrl + f` and search `tweakers.net` also make sure it was the right format.

#2052
