### ISSUE TITLE
{ Important } Firefox extension gets reported as corrupt

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1415]
![Bildschirmfoto zu 2019-07-08 20-31-13](https://user-images.githubusercontent.com/6344099/60835305-0f5da200-a1c3-11e9-849f-3de6d461cf95.png)

**Comment by alexanderby** [comment]
Hi, are you using old Firefox version? There used to be a problem with expired certificates.

Also, the extension was picked for Firefox Recommended Extensions program, and I have to publish an update, what I'm going to do soon.

**Comment by ShalokShalom** [comment]
Thanks a lot. Works probably fine on a current version. Did overwrite this installation
