### ISSUE TITLE
Apply dark theme to Ctrl +P (print/export)

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#1416]
Hello,

While printing or exporting a web page (PDF), dark theme doesn't work.

I'm looking forward to a fix for that situation.

Thanks

**Comment by Rult** [comment]
I think that the extension shouldn't make pages black when user want to print it.
However, it would be nice feature to have an option to save a copy of dark themed page in PDF.

**Comment by KaKi87** [comment]
Optional, maybe.
However, black paper exists :p

**Comment by KaKi87** [comment]
Hey, any news on this ? Thanks

**Comment by KaKi87** [comment]
up

**Comment by Gusted** [comment]
You bassicly mean you want a WEB PAGE be printed with the current dark mode on?
Or do you mean you want the ctrl + p page be dark
Or do you mean you want the PDF to be dark mode and than print that

**Comment by KaKi87** [comment]
I mean the PDF to be in dark mode. It's not for paper printing at all actually, just for reading PDFs on my screen offline.

**Comment by Gusted** [comment]
It is possible but darkreader blocks some sites like chrome://print so it doesn't mess up the global sites, I will try to make a bypass with a button etc

**Comment by Gusted** [comment]
Nope can't be done so far I see Chrome blocks extension that try to modify chrome:// and chrome extension store because security reasons?

**Comment by KaKi87** [comment]
What about a "save as dark PDF" option directly embedded into Dark Reader  available on the extension popup ?

**Comment by Gusted** [comment]
I think this is possible.... But I will look into this On 11 Mar 2020 23:09, KaKi87 <notifications@github.com> wrote:
What about a "save as dark PDF" option directly embedded into Dark Reader  available on the extension popup ?

**Comment by Gusted** [comment]
Not possible. No workarounds.

**Comment by KaKi87** [comment]
Actually, yes there is : it's CSS media query print : https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by Gusted** [comment]
Hmm it seems like the print preview is loading very very slow 
I'm just getting this
![](https://i.imgur.com/Mvi3eoO.png)
Without the preview loaded, it can't be printed.

**Comment by goyalyashpal** [comment]
> ou bassicly mean you want a WEB PAGE be printed with the current dark mode on?
> Or do you mean you want the ctrl + p page be dark
> Or do you mean you want the PDF to be dark mode and than print that

for me, it would be the first option: "web page to be printed with current dark mode on"
