### ISSUE TITLE
Wrong display on apollographql.com

### ISSUE THREAD

**Issue by Haltarys** [darkreader/darkreader#1422]
Hi,

I would like to report an issue on this website : [www.apollographql.com/docs](www.apollographql.com/docs).
When this page is loaded, darkreader renders it dark (as it is supposed to), except for certains part (like the upper navbar). However, pressing Alt + Shift + A twice (disabling and enabling the extension) fixes the bug and the page is rendered correctly. The problem reappears as soon as you refresh the page.

This is a minor issue, but I wanted to report it.

PS: this is the first time I'm reporting an issue, don't be mad at me :)

**Comment by Gusted** [comment]
Fixed.
