### ISSUE TITLE
steamdb.info on global list?

### ISSUE THREAD

**Issue by camobiwon** [darkreader/darkreader#1424]
In the past, steamdb.info has always displayed as dark, and had no issues doing so.
I checked it today, and it said that it was on the global dark list, and was stuck on light, and couldn't be changed.
I've tried going to other sites to make sure it wasn't just my extension in particular, but it seems like it's only that.
Any idea what may have happened? And how to fix it if it's a clientside thing?

**Comment by MonolithOrchids** [comment]
Yes, they added to the global list few days ago and it's a bad change.

It should be removed from the global list or at least let us edit the global list on client-side.
