### ISSUE TITLE
Kotlin docs messed up

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#1426]
![image](https://user-images.githubusercontent.com/4723091/61172426-2391fe00-a539-11e9-8625-7f207b5020d7.png)

I have to toggle the extension off, then on again to fix it, every single time I load a page. Also, sometimes the extension can't disable or reenable itself and I need to reload and try to ninja it...

https://kotlinlang.org/docs/reference

**Comment by Gusted** [comment]
Is fixed #3004 :)
