### ISSUE TITLE
Dark Reader overwrites Firefox Themes

### ISSUE THREAD

**Issue by Metazolid** [darkreader/darkreader#1430]
Whenever I enable and disable Dark Reader, it overwrites the function of the previously enabled Firefox theme. I have to manually disable and reenable it for it to work, OR activate Dark Reader before the theme, which I then have to reenable again.
It would be great if the Addon wouldn't interfer with the installed themes.

**Comment by zacharytyhacz** [comment]
What version of firefox are you using? When you say theme, are you talking about the top area ( URL, search, and tabs area ) ?

**Comment by gibfahn** [comment]
(hopefully the same issue as above)

If I disable Dark Reader on Firefox Nightly (macOS version `70.0a1 (2019-07-23) (64-bit)`) and restart Firefox, this page looks like this:

![image](https://user-images.githubusercontent.com/15943089/61779245-40abb400-adf8-11e9-90f2-aabe4638374d.png)

If I then enable Dark Reader (in `about:addons`) it looks like this:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/15943089/61779267-4c977600-adf8-11e9-8681-bc3984752cad.png">

This persists even after I restart Firefox. I can fix it by disabling and then enabling the current theme (in my case Default as I have Dark Mode in my system preferences), but I have to do that on every restart.

**Comment by gibfahn** [comment]
I worked around this by:

1. Running `shadowfox` and choosing `Uninstall Shadowfox` (I previously had it installed but it no longer seems necessary).
2. Going to about:profiles and clicking `Restart with Add-ons Disabled`
3. Then I clicked `Refresh Firefox` at the popup:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/15943089/61780710-eb24d680-adfa-11e9-9261-325afed4bb7d.png">

**Comment by gibfahn** [comment]
The quickest workaround I've found is to go to `about:addons`, click `Themes`, and either `Enable` or `Disable` the `Dark Theme`. Whether it's enabled or disabled doesn't matter if you have Dark Mode enabled systemwide, but the switch fixes the colour issues.

**Comment by zacharytyhacz** [comment]
Interesting, I didn't think this extension would affect the actual browser theme. I'm using the default Mozilla Firefox theme ( version `68.0.1 (64-bit)` ) on macos high sierra `10.13.6`.

However, I'm confident this can be an easy fix if someone were to make create a pull request. I may take a look, though I'm busy.

**Comment by Naheulf** [comment]
I use Firefox `68.0.1 (64 bit)` on Windows 8.1 and I also have the bug described above

**Comment by Cerberuschan** [comment]
firefox 68.0.2 with win 10 and have this same problem, if i disable the default dark theme all comes back to normal but as the rest already said, you have to do it every time you restart firefox. really think it's a easy fix, can someone take a look at this plz?

**Comment by msrd0** [comment]
This problem also appears on Firefox Developer Edition 70.0b5:

![scrot](https://user-images.githubusercontent.com/7853372/64699217-9a4d6800-d4a4-11e9-977a-c1895d53312a.png)

Disabling and enabling the dark theme fixes the issue for the current session, but not permanently.

**Comment by ThisIsABug** [comment]
It gets worse if you use your browser through an remote desktop connection (screenshot)
The original firefox theme had this problem a long time ago too, but it could be fixed through disabling hardware accleration. This "fix" does not work under those circumstances.
It would be nice to disable styling of the browser-theme in the whole, this extension is awesome for web-content, the local Firefox-Application has a nice dark-theme already.
![image](https://user-images.githubusercontent.com/19193534/65336310-6ec62e00-dbc6-11e9-9aa5-29df4acf2f5b.png)

**Comment by ogpvp** [comment]
I am having the same issue. It should not be changing the UI of Firefox, only the pages. So annoying to have to change the theme every restart. Please fix this.

**Comment by gibfahn** [comment]
Took a look at this and raised a PR: https://github.com/darkreader/darkreader/pull/1608

Turns out the fact that Dark Reader changes the Firefox theme is a feature, it was added in darkreader@181ec06 and can be disabled as a workaround.

## Workaround

1. Open Darkreader preferences in the extensions toolbar
2. Click `More`
3. Toggle `Change the browser theme` to `Default`

<img width="282" alt="Darkreader preferences" src="https://user-images.githubusercontent.com/15943089/66277696-00f25580-e89a-11e9-8105-de6ccc87131c.png">

**Comment by ogpvp** [comment]
> 
> 
> Took a look at this and raised a PR: #1608
> 
> Turns out the fact that Dark Reader changes the Firefox theme is a feature, it was added in [181ec06](https://github.com/darkreader/darkreader/commit/181ec06) and can be disabled as a workaround.
> ## Workaround
> 
>     1. Open Darkreader preferences in the extensions toolbar
> 
>     2. Click `More`
> 
>     3. Toggle `Change the browser theme` to `Default`
> 
> 
> <img alt="Darkreader preferences" width="282" src="https://user-images.githubusercontent.com/15943089/66277696-00f25580-e89a-11e9-8105-de6ccc87131c.png">

Thank you so much!
