### ISSUE TITLE
Hide scroll bar when flags overlay scrollbar is on

### ISSUE THREAD

**Issue by Hanif1601** [darkreader/darkreader#1431]
Can you hide the scroll bar while Dark Reader on? Because my browser is enable flag for overlay scroll bar on Chrome. Screenshot:

![image](https://user-images.githubusercontent.com/46013833/61213007-07a37d80-a72e-11e9-8736-dfc2a33f6c0a.png)

**Comment by Gusted** [comment]
We have no way to detect's flags in chrome to extensions.
