### ISSUE TITLE
remote: Permission to darkreader/darkreader.git denied to UchihaSR. 

### ISSUE THREAD

**Issue by UchihaSR** [darkreader/darkreader#1432]
![darkreader ](https://user-images.githubusercontent.com/52357560/61213365-7aa6f700-a722-11e9-92b2-98dd35413a81.png)

**Comment by alexanderby** [comment]
Hi, are you trying to push to `darkreader/darkreader`? You should create your own fork first.

**Comment by UchihaSR** [comment]
thanks for your reply. i forked this repo and then updated the hi.config file and have send PR
