### ISSUE TITLE
Toggling is disabled on some sites (not in global dark list)

### ISSUE THREAD

**Issue by realnc** [darkreader/darkreader#1441]
When I go to:

https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/index.html

The toggle function does not make the site dark. Normally, when I click the toggle button, it goes from "x" to "✓". But on some sites, like the LLVM one, it stays "x". It refuses to activate. The site is not on the global dark list or anything. It just doesn't work. Normally, Dark Reader displays a message under the toggle button when a site can't be toggled, like "site is in global dark list" or "this page is protected by browser". But in this case, it doesn't say anything about why the button can't be toggled.

Dark Reader v4.7.13. Firefox 68.0 (64-bit) on Linux.

**Comment by realnc** [comment]
OK, figured out something. To make toggling DR on many sites like that, I have to go to the root URL:

https://llvm.org

and toggle that. Then, and only then, does the toggle button work on the other pages on that site.

**Comment by realnc** [comment]
Why was this closed? :-/

**Comment by Gusted** [comment]
Not sure how I ended up closing

**Comment by gregsdennis** [comment]
https://docs.aws.amazon.com/ is another one.  I don't understand how this page would be "protected."  It's just another website.

**Comment by Gusted** [comment]
> https://docs.aws.amazon.com/ is another one. I don't understand how this page would be "protected." It's just another website.

You most likely have aws.amazon.com or amazon.com in the sitelist.

**Comment by gregsdennis** [comment]
Nope. It just doesn't want to work.
![image](https://user-images.githubusercontent.com/2676804/150698477-5c4aeb59-4dfd-4ffe-967e-1020eed89f4d.png)
