### ISSUE TITLE
travis  ci build failed

### ISSUE THREAD

**Issue by UchihaSR** [darkreader/darkreader#1445]
i updated the hi.config file. the pull request is showing "all checks have failed, 1 failing check. it is 
related to locales test.
![travis](https://user-images.githubusercontent.com/52357560/61555926-1e273d00-aa7e-11e9-8028-b46fa2178ee7.png)

**Comment by Gusted** [comment]
This means you don't have the same line count than the others. 
Maybe you used a extra white space somewhere?
