### ISSUE TITLE
[Dynamic Theme] Unreadable white text on the white background on https://www.aif.ru

### ISSUE THREAD

**Issue by Kerrung** [darkreader/darkreader#1447]
Hi! Look at this, please:

https://www.aif.ru/society/people/sudba_razoblachitelya_kak_zhivyot_edvard_snouden

![Screenshot from 2019-07-20 10-42-53](https://user-images.githubusercontent.com/36989404/61574583-295c8600-aadb-11e9-9903-f531f8b1f1ae.png)

**Comment by Hanif1601** [comment]
Well, that's really sucks.

**Comment by Gusted** [comment]
F I X E D
