### ISSUE TITLE
Please add a Content Security Policy to Dark Reader

### ISSUE THREAD

**Issue by tareqak** [darkreader/darkreader#1452]
I would like to use Dark Reader at my workplace, but the lack of a Content Security Policy in this extension is a cause for concern for my workplace's cybersecurity team.

Here is a document from Google about implementing strict CSP: https://csp.withgoogle.com/docs/strict-csp.html

I found an example of a Content Security Policy in a Google Chrome extension here: https://github.com/deanoemcke/thegreatsuspender/blob/master/src/manifest.json#L47 .

Thank you

**Comment by ArielRosenfeld** [comment]
implementing a Content Security Policy could possibly fix the many dark reader not working on website on firefox

**Comment by SuperSandro2000** [comment]
Bump. As this causes weird errors when implementing CSP that can't really be traced to anything.

**Comment by Gusted** [comment]
Yeah, this extensions works globally on every site adding a Content Securty Policy would be *stupid*.

If your cybersecurity team may have concerns tell them that it's a extension and adding a Content Security Policy into this will affect nothing as external parties don't have connections with the extension as how the browser behave.
