### ISSUE TITLE
Doesn't work on https://rubygems.org/gems

### ISSUE THREAD

**Issue by davidchoo12** [darkreader/darkreader#1454]
![image](https://user-images.githubusercontent.com/7817101/61689019-a2b0de80-ad50-11e9-853e-8a9b10e01227.png)

I inspected that the white part is `<main class="main--interior">` and `main--interior` has `background-color: white;`

**Comment by Gusted** [comment]
![](https://i.imgur.com/QEty6wN.png) Not anymore!
