### ISSUE TITLE
Fix the BG of "reacted" buttons under GH issue comments

### ISSUE THREAD

**Issue by spikespaz** [darkreader/darkreader#1456]
Just to make the fact that it's already been clicked a little more noticeable, I lightened it in the DevTools.

Add this for CSS under `github.com`.

```css
.btn-link.reaction-summary-item.user-has-reacted {
    background: ${rgba(0, 0, 0, 0.1)} !important;
}
```

### Before

![image](https://user-images.githubusercontent.com/12502988/61843839-1e468480-ae52-11e9-808d-18cbfece9c3a.png)

### After

![image](https://user-images.githubusercontent.com/12502988/61843931-77161d00-ae52-11e9-9439-b7c3f20835cb.png)

I know I'm making a lot of suggestions for these small stylistic changes, I'm just trying to do my part. Do you prefer these via email or GH issue?

**Comment by Gusted** [comment]
[Pull requests](https://github.com/darkreader/darkreader/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
