### ISSUE TITLE
Synology Router Manager login page is extremely slow to load

### ISSUE THREAD

**Issue by jl91569** [darkreader/darkreader#1457]
This page is pretty much a worst-case scenario with over 18,000 CSS rules (that's not a typo, one stylesheet has 5000 rules alone). The login page appears to render correctly, but once logged in the graphs in the Network Center status page have a pure white background.

I'm not sure whether it's the same for Synology NAS logins, but I can't test it as I don't have access to one.

Dark Reader on Dynamic mode freezes Firefox 68.0.1 stable for 55s+ before rendering some of the page, and another 7s to finish rendering the content. Firefox without Dark Reader takes around 3s to display the page (served from the LAN so there's no extra network time penalty). WebRender is enabled.

With Dark Reader, Chrome takes ~10s to display initial content and around another 10s to fully render the page. Chrome also takes 3s to fully display the page without Dark Reader.

Specs: 
Intel Core i5-6200U@2.7GHz
8GB LPDDR3 dual-channel RAM
Intel HD 520
Windows 10 1803, Firefox 68.0.1 stable, Chrome 75.0.3770.142, Dark Reader 4.7.14
I used a strong, stable Wi-Fi connection, so I don't expect the results to be different when using Ethernet.

**Comment by Gusted** [comment]
#535 
18K rules should be flawless with Dark Reader v4.9.15

**Comment by hypercodex** [comment]
I am experiencing this issue for the latest build of Chrome and the latest Synology DSM. Was hard to trace down to Darkreader but have confirmed that it indeed is the cause of extreme rendering delays.

**Comment by Gusted** [comment]
Hi @hypercodex!

Could you open up another issue?
It might be possible that the issue is not being #535 or #2550 and I would like to investigate any Performance problems.

Regards,
Gusted

**Comment by hypercodex** [comment]
@Gusted sure thing! Opened this issue to report #3529
