### ISSUE TITLE
White, bright flash between page loads on safari (potential workaround)

### ISSUE THREAD

**Issue by jpuris** [darkreader/darkreader#1458]
Coming back to Safari from Firefox, which has the same problem and has a workarounds described in https://github.com/darkreader/darkreader/issues/1219, figured I would open an issue on same Safari issue.

**Problem**
White brief flashes of bright / white page load.

**Workaround**
Create a text file named something like `safari-darkreader-fix.css`.
Paste following in it and save it.
```css
html body { background-color: #212426; }
```
Now go to `Safari => Preferences... => Advanced => Style sheet` and choose the file you had created.

#212426 is the grey you'd get from dark reader darkening the page with default brightness and 
-10 contrast. Feel free to adjust it to whatever your settings are, to eliminate any kind of transition.

Is there a better workaround or any plans on releasing dark reader fix ?

**Comment by Jax0rz** [comment]
Same Problem

**Comment by jpuris** [comment]
While this workaround fixes some pages, most other are still having issues.
Granted, the issue does not happen for vast majority after first time loading it after starting safari.

**Comment by Gusted** [comment]
Their's plans to convert safari to the current codebase which already has the fix #2927

**Comment by jpuris** [comment]
I have not been able to reproduce this on Safari Technology Preview `Release 110 (Safari 14.0, WebKit 15610.1.21.0.2)`

**Comment by josep-b** [comment]
I started using the brave search engine, and it does not occur like clicking links through Google. weird.

**Comment by lothar-cell** [comment]
How come Dark Reader still has not solved this since 2018? Especially because it is closed source for Safari and costs 5$ in the App Store.
