### ISSUE TITLE
The news from www.ithome.com, the comments below often fail to work properly and need to be refreshed once.

### ISSUE THREAD

**Issue by eefan000** [darkreader/darkreader#1465]

**Comment by eefan000** [comment]
![image](https://user-images.githubusercontent.com/19683667/62015449-4df0e600-b1de-11e9-98db-3a469613b8e3.png)
![image](https://user-images.githubusercontent.com/19683667/62015498-a9bb6f00-b1de-11e9-9624-f8150ad3682d.png)

**Comment by Gusted** [comment]
Should be fixed.
