### ISSUE TITLE
DarkRead dosnt work on local files

### ISSUE THREAD

**Issue by hasezoey** [darkreader/darkreader#1482]
Background info: in my projects i use typedoc to generate documentation, where no theme can be applied

File Access is checked (enabled)
System: Linux
Browser: Vivaldi (Version 75.0.3770.145 (Offical Build) (64-Bit))

Error:
`Fetch API cannot load file:///projects/typegoose/doc/assets/css/main.css. URL scheme must be "http" or "https" for CORS request.`

**Comment by Gusted** [comment]
Should work from Dark reader 4.9.15
