### ISSUE TITLE
Can't see totals in Ally Bank on dashboard

### ISSUE THREAD

**Issue by nitrocode** [darkreader/darkreader#1485]
https://secure.ally.com/dashboard

**Comment by annoying258** [comment]
A screenshot would be nice, can't see the totals without an account. Remove any sensitive information in screenshot.

**Comment by nitrocode** [comment]
![ally](https://user-images.githubusercontent.com/7775707/64967834-2da0e780-d86f-11e9-939e-9c9d351b119b.png)

**Comment by Gusted** [comment]
Use Filter Or static for this site.
