### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by Youdaman** [darkreader/darkreader#1492]
Added a script tag as per "Using for a website" instructions https://github.com/darkreader/darkreader#using-for-a-website but got the following error in console:
```
unpkg.com/darkreader@4.7.14/darkreader.js:945 Uncaught TypeError: Cannot read property 'addListener' of undefined
    at unpkg.com/darkreader@4.7.14/darkreader.js:945
    at unpkg.com/darkreader@4.7.14/darkreader.js:9
    at unpkg.com/darkreader@4.7.14/darkreader.js:10
```

**Comment by alexanderby** [comment]
Hi, what browser are you using?

**Comment by alexanderby** [comment]
Ah, I see the error in Chrome, `chrome.runtime` is present for some websites, and for others not.

**Comment by alexanderby** [comment]
There was an update, please try again.
