### ISSUE TITLE
Exception occur when accessing "tieba.baidu.com"

### ISSUE THREAD

**Issue by liyfi** [darkreader/darkreader#1493]
There will be a problem when browsing the content, do not display the content of the post, the test is as follows

enabled darkreader：
![20190813141725](https://user-images.githubusercontent.com/38422514/62919405-2486ab80-bdd5-11e9-89a4-8e6d19c1a9f0.png)

disabled darkreader and refresh
![20190813141632](https://user-images.githubusercontent.com/38422514/62919410-28b2c900-bdd5-11e9-83f3-9683f1dc7132.png)

**Comment by Gusted** [comment]
Should be fixed.
