### ISSUE TITLE
Use a highlight color for links so they can stand out

### ISSUE THREAD

**Issue by scottrepreneur** [darkreader/darkreader#1495]
When reading I'll frequently miss links because they're tucked into sentences neatly. It'd be great to have them in another color so they are easy to pick up.

Some color options to complement the dark mode might be
- Bright green
- Pink
- Bright blue
- Yellow

Check out the dark mode on Medium. The links are harder to see because they're the same color as the text, where on the light theme they are opposites and links include the underline generally. 

https://medium.com/coinmonks/is-storing-encrypted-files-on-ipfs-good-enough-21e050d9de0
<img width="500" alt="Screen Shot 2019-08-13 at 12 22 46 PM" src="https://user-images.githubusercontent.com/1778380/62962814-50019a00-bdc5-11e9-9913-46802a8a5508.png">

**Comment by twhite46** [comment]
Now Medium comments are underlined. I've tried fixing it in the DevTools but I can't seem to target the comments specifically. They are anchors.
