### ISSUE TITLE
Day and nightcycle doesnt work

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1496]
Hi there :hugs: 

![Screenshot_20190814_090822](https://user-images.githubusercontent.com/6344099/63001148-3a4aae00-be73-11e9-9165-6f9069272ea1.png)

This does not work as you can see according to my clock.

**Comment by ShalokShalom** [comment]
It does work from 18:00 to dark mode, just the other way around (making it white again) seems to do not work properly. 

And yes, I tried to reload

**Comment by Gusted** [comment]
ngplus.net is already dark ^-^

**Comment by Gusted** [comment]
#3438
