### ISSUE TITLE
Background texture of askubuntu.com too bright

### ISSUE THREAD

**Issue by cole8888** [darkreader/darkreader#1498]
The background texture of askubuntu.com is too bright and makes viewing the page quite difficult. I've attached an image of the page.

![image](https://user-images.githubusercontent.com/32819560/63063183-f9ce4d00-bed1-11e9-9382-a31e4f4b857e.png)

The texture is loaded with a URL which references an image, so I was unable change it's colour using developer tools from the extension or the browser. Removing this element does not cause any issues, so blocking it may be the most simple solution.

This is probably the same as #1476, except they only mention the left sidebar in their issue. 
I am using the dynamic theme generator.

**Comment by FranklinYu** [comment]
One more site: https://dba.stackexchange.com

**Comment by cole8888** [comment]
Fixed :+1:

**Comment by jtraub** [comment]
@FranklinYu well, the issue is related to askubuntu. I haven't noticed your report until today.

Anyway, I sent a PR which removes the background on all StackExchange sites.
