### ISSUE TITLE
Provide shortkey to toggle "Activate extension" in Firefox like in Chrome.

### ISSUE THREAD

**Issue by PranavBhattarai** [darkreader/darkreader#1500]
We do have shortkey for:

- Toggle current site

- Toggle extension

But we don't have:

- Activate extension

**I wonder why? Why not in Firefox?**
![Screenshot from 2019-08-16 12-34-35](https://user-images.githubusercontent.com/32763112/63148896-432db200-c022-11e9-9815-d9685108ada1.png)

**Comment by Gusted** [comment]
This is was added by chrome itself
