### ISSUE TITLE
4.7.16 breaks on a number of sites

### ISSUE THREAD

**Issue by fluffynuts** [darkreader/darkreader#1501]
I'm seeing a lot of sites where it's as if Dark Reader executes too quickly or something similar? Basically, a bunch of light components are left in, or the site is not themed correctly. FastCompany.com is one. Jenkins is another -- toolbars top and bottom stay white.

Rolling back to 4.7.14 makes sites display properly again.

**Comment by LoganDark** [comment]
https://kotlinlang.org/docs/reference/

**Comment by alexanderby** [comment]
Please, provide some websites, that stopped working.

**Comment by LoganDark** [comment]
> FastCompany.com is one. Jenkins is another

> https://kotlinlang.org/docs/reference/

Please, read the issue, before commenting..

**Comment by alexanderby** [comment]
I see no issues for the provided websites (except sun-tanned mascot of Jenkins).
<img width="1392" alt="Screen Shot 2019-08-17 at 17 14 33" src="https://user-images.githubusercontent.com/9638588/63212823-8ebf8900-c112-11e9-84be-ab2fa0be9d4c.png">

**Comment by fluffynuts** [comment]
I just had firefox update me again, in the background, and I had jenkins with white bars all over the place. I see this screenshot is from osx -- not sure what browser, but looks a lot like chrome? -- please retest with FF, and perhaps under Windows, since I think this might be a timing issue for some.

**Comment by LoganDark** [comment]
No, Chrome on macOS has this issue.

**Comment by wdspider** [comment]
I just starting using this extension yesterday, so I'm not sure if LinkedIn was broken prior to v4.7.16 but the plugin basically doesn't do anything:
![image](https://user-images.githubusercontent.com/5971649/63218457-24a5e480-c110-11e9-8ffc-b9934fe26f53.png)

FF on Windows

**Comment by fluffynuts** [comment]
just a heads-up that this behavior persists to 4.7.17. I really wish I could lock just one extension to not auto-update -- 4.7.14 works so well )':

**Comment by Gusted** [comment]
Kotlin issue has been fixed and twitter has a separate issue and has to due with custom privacy settings in Firefox.
