### ISSUE TITLE
Firefox can't scroll this website: https://source.android.com/devices due to Darkreader.

### ISSUE THREAD

**Issue by PranavBhattarai** [darkreader/darkreader#1510]
Steps to reproduce:
1. Use firefox (68.0.2 64 bit, in Ubuntu 19.04)
2. Visit this website: https://source.android.com/devices/tech/dalvik/
3. Try to scroll down, but Darkreader won't let u.

I even made a bug report on [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1575452) in issue in Bugzilla. But clearly, this seems like the extension is not perfect. You can even see the video in action which i have uploaded in that website.

**Comment by jtraub** [comment]
I believe that Firefox itself is at fault in this case. I have observed the problem with Filter+ mode in Firefox on several other websites.

**Comment by PranavBhattarai** [comment]
@jtraub If it's so, then why the side is scrollable when this extension is disabled/deactivated?
Doesn't that mean, that's dark reader fault?

**Comment by jtraub** [comment]
@PranavBhattarai why is this site scrollable in Chrome even if you enable DarkReader with Filter+ mode?

I don't have time to dig into this, but DarkReader in Filter+ mode basically applies a single 'filter' to `html` element. This also makes me believe that the extension has nothing to do with the problem.

**Comment by PranavBhattarai** [comment]
@jtraub u might be right. TC

**Comment by jtraub** [comment]
It is a Firefox issue indeed. Firefox devs have acknowledged this in response to the OP's report https://bugzilla.mozilla.org/show_bug.cgi?id=1575452

**Comment by Gusted** [comment]
Firefox Bug and dark reader can't do anything to prevent this. Also it let's you scroll now?
