### ISSUE TITLE
An option to change the color of the text.

### ISSUE THREAD

**Issue by zk-g** [darkreader/darkreader#1514]

**Comment by jtraub** [comment]
Isn't it a duplicate of #650?

**Comment by annoying258** [comment]
from https://github.com/darkreader/darkreader/issues/650#issue-346465289

>and text tone/color selector

---

Yep, it is a duplicate. 

The title of #650 is vague, title of #1514 is clear.  I had to read https://github.com/darkreader/darkreader/issues/650#issue-346465289  twice to realise that since its poorly worded.

**Comment by Gusted** [comment]
Dup of #650 and has been resolved.
