### ISSUE TITLE
element.style within an email

### ISSUE THREAD

**Issue by niczoom** [darkreader/darkreader#1518]
In a particular email dark reader inserts " --darkreader-inline-color: #86b2f0; " trying to overide the original css property  " color: rgb(17, 34, 136) !important; " but it seems because its using !important dark readers property doesnt overide it. As the tag is a generic 'element.style' I dont know how to target this? Or can I force dark reader to insert !important on its injected property?

![gif1](https://user-images.githubusercontent.com/17034812/63633259-a05ddf00-c684-11e9-881b-a4598aa3cb64.gif)

I tried to edit 'inject.js' inside the extensions install folder to add !important to color tags but then learnt chrome uses 'Extension Content Verification' which detects changes to extension code !

**Comment by Gusted** [comment]
> I dont know how to target this

`.ii a[href]`

Also I recommend using Stylus to make changes as we prevent the styles from that extension to darken them.
