### ISSUE TITLE
Font Resizing

### ISSUE THREAD

**Issue by ptoump** [darkreader/darkreader#1523]
Hello,

Great extension, thank you for your efforts!

Is there a possibility to add the ability to change the font size of the text, without resulting to CSS?

Thank you

**Comment by ptoump** [comment]
Just a clarification, this is especially usefully for **Android** **Firefox** where many websites become unreadable due to tiny fonts and no resizing / reflowing when zooming in.

**Comment by ptoump** [comment]
@ #1868 same suggestion.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/3066#discussion_r458785239
