### ISSUE TITLE
I want use it on new Microsoft Edge Brownser！

### ISSUE THREAD

**Issue by MoConWu** [darkreader/darkreader#1526]
You know, The new Edge Brownser use Chromium, I believe that you can do it, 
I want use it on new Microsoft Edge Brownser!
I love it on Chrome, 

I see it can use [Microsoft Edge Extension Toolkit] to do it!
Good job!

**Comment by underlineGalaxy** [comment]
Lmao who even uses edge

**Comment by kenkit** [comment]
There was a time when the same could be said about Microsoft Security Essentials.
Right now I find that edge is much more faster than other browsers, I have a feeling Microsoft is playing it low so as not trigger problems with other browsers.
If I could get Raindrop.io and Darkreader I'll be using Edge. After all it was made for windows.

**Comment by Wutname1** [comment]
Just for those who do not know you can install this in edge via the chrome webstore you just have to click the bit mutton that says allow 3rd part app stores

https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

But it would be nice to see it listed in the edge store! Get in there while it's still filling out, it's a great opportunity for new users.

**Comment by alexanderby** [comment]
Finally Dark Reader was released for Edge (Chromium) https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc

Please, if you already have Dark Reader installed from Chrome Web Store, disable it before installing from Microsoft Store.
