### ISSUE TITLE
youtube banners dont show up in dynamic mode on firefox

### ISSUE THREAD

**Issue by kamrangojira** [darkreader/darkreader#1530]
![Untitleddf](https://user-images.githubusercontent.com/54599351/63801235-0e283600-c925-11e9-8100-c2595981b677.jpg)

**Comment by Gusted** [comment]
Hey, sorry for the late fix!
I never noticed it or any other person that knows How to fix this Sorry for the inconvicent.

**Comment by Gusted** [comment]
Hey! I'm gonna close this issue. #2221 has been merged and will be avaible in the next update of Darkreader. Thank you for reporting this issue!
