### ISSUE TITLE
error on xml page

### ISSUE THREAD

**Issue by simon1tan** [darkreader/darkreader#1538]
index.js:2437 Uncaught TypeError: Cannot read property 'cssRules' of undefined
    at buildStyleSheet (index.js:2437)
    at Object.render (index.js:2550)
    at index.js:2882
    at Map.forEach (<anonymous>)
    at createDynamicStyleOverrides (index.js:2881)
    at runDynamicStyle (index.js:3014)
    at createThemeAndWatchForUpdates (index.js:3020)
    at MutationObserver.<anonymous> (index.js:3094)
buildStyleSheet @ index.js:2437
render @ index.js:2550
(anonymous) @ index.js:2882
createDynamicStyleOverrides @ index.js:2881
runDynamicStyle @ index.js:3014
createThemeAndWatchForUpdates @ index.js:3020
(anonymous) @ index.js:3094
childList (async)
prepareWebKitXMLViewer @ VM447:26
(anonymous) @ VM447:383

Line 2436:
     const sheet = syncStyle.sheet;
                for (let i = sheet.cssRules.length - 1; i >= 0; i--) {
                    sheet.deleteRule(i);
                }
syncStyle.sheet is not defined. 

Perhaps change to:
if (syncStyle.sheet){
     const sheet = syncStyle.sheet;
                for (let i = sheet.cssRules.length - 1; i >= 0; i--) {
                    sheet.deleteRule(i);
              }
}

**Comment by jtraub** [comment]
This happens because `document.createElement` in an XML creates an `Element` instead of `HTMLElement`.

I would personally just check if `document` is an instance of `HTMLDocument` before actually running any of darkreader's code on a page.

**Comment by Gusted** [comment]
Fixed
