### ISSUE TITLE
Would it be possible for the extension to follow the browser's Dark Mode?

### ISSUE THREAD

**Issue by saadhsnain** [darkreader/darkreader#1545]
So, I've been using Microsoft Edge Dev, which automatically switches to Dark theme when the system wide dark theme is enabled. I was wondering if there could be a snippet of code in dev tools that'd enable the Dark Reader the same way.

**Comment by jtraub** [comment]
I don't think there is such a snippet.

See #745 to track support of system dark mode detection.

**Comment by Gusted** [comment]
https://darkreader.org/blog/automation/
