### ISSUE TITLE
Changing description for "Only for *website*"

### ISSUE THREAD

**Issue by marcospb19** [darkreader/darkreader#1546]
I always wondered how could i choose different themes modes for different sites, then i red #551, it was right on my face!

Maybe @Alkasul did not noticed it (just like me) because the description is a bit confusing.

I would like to suggest changing `Only for github.com` to `Apply to github.com`
What do you think?

(I was about to make an Pull-Request, but it wasn't that trivial and simple)

**Comment by marcospb19** [comment]
`Apply for github.com`
`Always use this configuration on github.com`
`Keep configuration for github.com`

Any other suggestions?

Extra: I was just talking to a friend about this issue, and he also didn't knew that this functionality existed, he complained that Dark Reader broke the layout of some sites on specifics Theme Modes, but this can absolutely be avoided already by changing specific configurations for specific sites!

**Comment by Gusted** [comment]
New UI is already doing this 
![](https://i.imgur.com/TEH7ltV.png)

**Comment by marcospb19** [comment]
Thanks, the new UI looks awesome!
