### ISSUE TITLE
Dark Reader inverts photos if Wikiwand Chrome extension is installed

### ISSUE THREAD

**Issue by BananaFrappe** [darkreader/darkreader#1547]
Wikiwand (v 8.2.10) modifies the formats of Wikipedia pages. On Chrome (v 76.0.3809.132 (Official Build) (64-bit)), Dark Reader (v 4.7.17) inverts the pictures embedded in any Wikiwand-modified article. If the same article is viewed in "unmodified" Wikipedia, then the pictures appear normal.

Windows 10 (v 1903, OS build 18362.267)

Wikiwand-modified:
![dark reader wikiwand](https://user-images.githubusercontent.com/43716656/64219945-71155200-ce7c-11e9-82c2-ee53c09937d5.png)

unmodified-Wikipedia:
![dark reader wikipedia](https://user-images.githubusercontent.com/43716656/64219949-74a8d900-ce7c-11e9-82e4-199fa3ac842f.png)

**Comment by FaultyFunctions** [comment]
Hey I know this was a while ago but if anyone else stumbles upon this here is the fix:

1. Go to wikiwand.com
2. Open Dark Reader and click DevTools on the bottom
3. Ctrl + F search for img.immediate.ntmb

The section should look like this:
`wikiwand.com

INVERT
img.mwe-math-fallback-image-inline
img.immediate.ntmb
img.logo_img
td.icon
li.menu-tooltip:not(.lang_btn)`

4. Just delete the `img.immediate.ntmb` line and click apply.

**Comment by Gusted** [comment]
Closed by #2545
