### ISSUE TITLE
Feature Request: Option to re-theme websites to light mode

### ISSUE THREAD

**Issue by jhdfjhaergjipo** [darkreader/darkreader#1549]
Hello,

I use an inverted color filter on windows, as word processing programs don't usually have a dark mode. It'd be great if the extension had an option to re-theme websites to a light theme so they're dark when the inverted color filter is active. (If there's already an extension that does this please let me know and I'll delete the issue) Thanks

**Comment by Gusted** [comment]
Use the light scheme option in order to achieve this.
