### ISSUE TITLE
Change hidden timetable option 

### ISSUE THREAD

**Issue by 001101** [darkreader/darkreader#1553]
The option for the timetable is extremely hidden and now on a 5.97" device even not clickable. 

Using yandex browser beta with the latest Chrome extension on a xiaomi mi a2 lite

I know it is pretty uncommon usage, but I also could not find the option by myself on desktop and it is such a elementary option which should be jump in right in your eye. 

![Screenshot_20190909-143604](https://user-images.githubusercontent.com/8197408/64531512-021e7a00-d310-11e9-95df-3c4acb9a3372.png)

**Comment by Gusted** [comment]
Resolved in the new UI.
