### ISSUE TITLE
bug: time schedule gets disabled

### ISSUE THREAD

**Issue by 001101** [darkreader/darkreader#1555]
If you disable darkreader in the time you scheduled it then it completely disables the schedule, makes no sense at all.

**Comment by mspeace** [comment]
Well.
if user set the schedule, and then manually powering on this plugin, the schedule disappear.

its disturb so much 
i can't even tell you

why can't i still use schedule if i decided to turn it ON earlier?

**Comment by Gusted** [comment]
> why can't i still use schedule if i decided to turn it ON earlier?
As that don't make sense and would use overcomplicated functions in the background and that would decrease performance.

**Comment by 001101** [comment]
> > why can't i still use schedule if i decided to turn it ON earlier?
> 
> As that don't make sense and would use overcomplicated functions in the background and that would decrease performance.

really, performance for that?

the one thing a program should do is serving the user.

**Comment by Gusted** [comment]
> > > why can't i still use schedule if i decided to turn it ON earlier?
> > 
> > 
> > As that don't make sense and would use overcomplicated functions in the background and that would decrease performance.
> 
> really, performance for that?
> 
> the one thing a program should do is serving the user.

Than your very wrong if we will add features without optimizing it and some features not adding to make it balanced for performance and features than we will have a lot of more issues with other users

**Comment by mspeace** [comment]
its just stupid

**Comment by Gusted** [comment]
I will have a look what I can do.

**Comment by Gusted** [comment]
Hi @mspeace 
In darkreader V5 the UI will solve this problem

Regards,
Gusted
