### ISSUE TITLE
bug: evernote web saves opposite text color of notes when using dynamic dark mode

### ISSUE THREAD

**Issue by JerryGoyal** [darkreader/darkreader#1556]
Issue is evernote saves opposite color of the text when you type something in a note.

How to produce:
1. enable dynamic dark mode for https://www.evernote.com/client/web
2. open any note and type something.
3. disable the dark mode for evernote and reload the page
4. open that note and you will see the **color of the text** you entered is **light grey** instead of black.

(problem occurs only in dynamic dark mode but not in filter mode)

**Comment by Gusted** [comment]
Because if we don't darken the color it will not be visible. Just like google documents, you type white text in order to see the text but when disabling dark reader the color is now dark in order to see it on a white background.
