### ISSUE TITLE
Adding IP to to Site List wild cards the last 2 digits of the last octet of the IP

### ISSUE THREAD

**Issue by ChaosBlades** [darkreader/darkreader#1566]
If you add a local IP and it doesn't have a triple-digit last octet you are basically adding that whole IP range. For example, you add 192.168.1.1 (pfSense has a dark theme) then all sites within the 192.168.1.1 to 192.168.1.19 and 192.168.1.100 to 192.168.1.199 range will also apply to that exclusion. Adding a trailing / to the IP does not resolve the issue.

**Comment by ChaosBlades** [comment]
Anybody working on this? Seems like a pretty simple thing to fix and a really annoying bug.

**Comment by Gusted** [comment]
what about `192.168.1.*`

**Comment by Gusted** [comment]
> what about `192.168.1.*`

Helped this your issue?

**Comment by ChaosBlades** [comment]
No that would not help my issue. I don't think you're understanding what I'm saying due to a translation issue.

**Comment by Gusted** [comment]
Well, you want to have 192.168.1.1 to 192.168.1.19  In he sitelist and 192.168.1.100 to 192.168.1.199
But so far with current #373 Sorry not

**Comment by ChaosBlades** [comment]
No I don't.

Expected result of only 192.168.1.1 in exclusion site list
- Dark Theme not applied to only 192.168.1.1

Actually Get:
- Dark Theme not applied to 192.168.1.1 to 192.168.1.199

**Comment by Gusted** [comment]
> No I don't. Actually the opposite.
> 
> Expected result of only 192.168.1.1 in exclusion site list
> - Dark Theme not applied to only 192.168.1.1
> 
> Actually Get:
> - Dark Theme not applied to 192.168.1.1 to 192.168.1.199
> 
> Edit: I exclude 192.168.1.1 and 192.168.1.101 also gets excluded. Even though 192.168.1.101 is NOT on the exclusion list

Type $ before it in the site list

**Comment by ChaosBlades** [comment]
Still, same issue. Adding $ didn't seem to change anything. $192.168.1.1 still affects 192.168.1.101

**Comment by Gusted** [comment]
> Still, same issue. Adding $ didn't seem to change anything. $192.168.1.1 still affects 192.168.1.101

I'm sorry!!! It's need to be at the end so darkreader can recognise it.

**Comment by ChaosBlades** [comment]
That Works!
