### ISSUE TITLE
YouTube Channel Page

### ISSUE THREAD

**Issue by norsehealer** [darkreader/darkreader#1568]
the main body of youtube's channel page isn't turning dark. https://i.imgur.com/J0sbo8o.png (second example: https://i.imgur.com/gN0leWE.png)

note the massive amount of white space where the videos are displayed and the white text (which seems to be following DR theme.

**Comment by jtraub** [comment]
This has been addressed in c62d08bdb3352ad1069066059b00957a1e80a313

Just update your extension
