### ISSUE TITLE
Dev Tools changes not saving

### ISSUE THREAD

**Issue by ckizziar** [darkreader/darkreader#1572]
Greetings all, first of all thanks for all the amazing contributions to DarkReader, it's truly a game changer. Now I'm running into an issue, and it's probably my own lack of understanding, but on a particular site a logo disappears and when I try various changes using the DarkReader dev tools, after I hit apply they just disappear.

My CSS attempt is probably wrong, but I can't seem to make it that far because hitting apply just makes any changes I entered disappear in the dev tools. Any advice on what I'm doing wrong?

Browser: Vivaldi 2.7.1628.33 (Chromium 76.0.3809.137)
OS: MacOS 10.14.6
Site Affected: https://cloud.tenable.com
Asset affected: ```#nosession <h1> background-image```

Attempted Change in Dev Tools:

```
================================

cloud.tenable.com

CSS
#nosession  h1 {
    background-image: url(data:image/svg+xml;charset=UTF-8,%3c?xml version='1.0' encoding='utf-8'?%3e…l.12,0-.49-1.36A5.73,5.73,0,0,1,8.58,85.7Z'/%3e%3c/g%3e%3c/g%3e%3c/svg%3e ) !important;
    background-color: initial !important;
}
```

**Comment by imminiman** [comment]
happens to me as well

**Comment by Alpha-Cineris** [comment]
I have tried the same and encountered the same issue.

Browser: Firefox 71.0
OS: Windows 10 version 1903
Site affected: https://www.thehealthy.com/
Asset affected: `body`

Attempted change :
```
================================

thehealthy.com

CSS
body {
    background-image: none;
}
```

**Comment by Gusted** [comment]
![](https://i.imgur.com/FhY9hNz.png)

After hitting apply use ctrl + f to find it again as it's automaticlly in alphabetic order.

**Comment by Neptilo** [comment]
Still doesn't save after quitting and reloading the browser - Firefox in my case.

**Comment by dpichot** [comment]
please re-open it

**Comment by eqoffical** [comment]
Same, I tried changing the font size on a site (I know, that's not what <u>Dark</u>Reader is for). That worked, but it didn't save my fix after relaunching Firefox.
