### ISSUE TITLE
Problems with Google Sheets if activated

### ISSUE THREAD

**Issue by MartinL0815** [darkreader/darkreader#1573]
If the dark reader is activated and I enter text in a Google sheet, the text entered has another color, than the rest of the already existing text.
The color of the text is dark (nearly black), so I assume, it is the original text color of the Google sheet web page.

**Comment by TheColtron** [comment]
Change the theme generation on docs.google.com to Filter+.

**Comment by gibfahn** [comment]
Dup of https://github.com/darkreader/darkreader/issues/490

**Comment by Gusted** [comment]
Fixed...
