### ISSUE TITLE
NO INVERT tag not recognized

### ISSUE THREAD

**Issue by Vortetty** [darkreader/darkreader#1575]
using the developer tools to try to prevent the color picker on google.com from being inverted (so i see the correct color) does not work, i can add any other tags to the file, but heaven forbid i use NO INVERT. any idea why this is broken, my guess is it is the extension as when i add it in through file explorer (im on windows), the extension is recognized as corrupted. if you want to try to fix this, you need to prevent google from recoloring ".rnt3Ze" . i have tried the invert tag however that also does not work, makes the color too light.

**Comment by Gusted** [comment]
Hi their!

Which mode you use?

**Comment by Vortetty** [comment]
I believe it is calked dynamic, not at my pc rn so I can't check

**Comment by Gusted** [comment]
NO INVERT is not available for dynamic. Use IGNORE INLINE STYLE

**Comment by asianboii-chen** [comment]
Hey!

I'm now facing a similar issue where I'd like to force to not invert a part of a website. Did you find a workaround to this issue, i.e., is there a way to do this inside the Dynamic Theme Editor?

Thank you so much!

**Comment by Gusted** [comment]
> Hey!
> 
> I'm now facing a similar issue where I'd like to force to not invert a part of a website. Did you find a workaround to this issue, i.e., is there a way to do this inside the Dynamic Theme Editor?
> 
> Thank you so much!

Due to the nature of the code-base it's not possible to just ignore an part of the website it's either fully of the website or it's none of the website to be styled, it's because like every other similar extension out their we use CSS Selectors and have no way of knowing to which element it would be styled.
