### ISSUE TITLE
Fix Performance Issues

### ISSUE THREAD

**Issue by deadmeu** [darkreader/darkreader#1576]
I've been using this extension for several months on Firefox, but I'm going to have to remove it purely because of the crippling performance issues I experience on a daily basis.

Currently, there are too many instances where visiting a new site, that is not optimised for Dark Reader's Dynamic filtering mode, causes the entire window to hang, and takes me up to several minutes before I can finally enter the Dark Reader settings and disable it for the page.

I can think of a couple of ways to mitigate this issue, though I'm not sure if they're possible given the current extension APIs:
- Implement performance monitoring, and throttle the extension when it goes beyond a certain threshold
  - Could be implemented using timers and regular checks to ensure the logic isn't taking too long to process?
  - Alternatively, throttle the logic itself, applying limits to the number of iterations/function calls
- Move the processing logic onto a separate background thread or process, to avoid hanging the UI

Without an improvement to this issue, I don't think I will be able to re-enable this extension.

**Comment by legolasdimir** [comment]
I am seeing the same type of thing but ONLY for one site in firefox. I use salesforce for my job and in salesforce in firefox dark reader freezes up the page. It works just fine everywhere else. I am not a dev but would love to contribute to getting the information that is needed to fix this for the dev. Let me know what you need

**Comment by Gusted** [comment]
#535 < Duplicate

**Comment by Gusted** [comment]
BTW We got recently onto this we are making some good progress see the latestest comments on the issue
