### ISSUE TITLE
How do I restore fonts to default🧐

### ISSUE THREAD

**Issue by d1y** [darkreader/darkreader#1578]
yo.

This plug-in is great, but some websites use font icons🤪
![image](https://user-images.githubusercontent.com/45585937/65501342-6dad3d80-def3-11e9-8d5f-b8439e3c5824.png)
ooops..

![image](https://user-images.githubusercontent.com/45585937/65501510-b107ac00-def3-11e9-9097-f1f07982cce3.png)

Do not know how to restore the default font :3

**Comment by Gusted** [comment]
Disable the font also it's the font that is not supporting the icons.
