### ISSUE TITLE
Firefox Dev/Nightly 70 won't load Dark Reader

### ISSUE THREAD

**Issue by matux** [darkreader/darkreader#1586]
Dump
```
$sync is undefined index.js:2111
    loadSettingsFromStorage moz-extension://58beb84f-d6a9-4645-a903-355aa29f422e/background/index.js:2111
    apply self-hosted:2018
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:824
    withLastError resource://gre/modules/ExtensionCommon.jsm:743
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:812
```
From
```
Unchecked lastError value: Error: An unexpected error occurred index.js:2107
    loadSettingsFromStorage moz-extension://58beb84f-d6a9-4645-a903-355aa29f422e/background/index.js:2107
```

Started happening on 4.8. 4.7 works fine.

I don't know how to *JS* nor plugin *FF*. Attempted switching `$` for a `_` on the dumb hope it may be something easy but I don't know how to sign these `xip` files to make FF happy.

Sounds like this is either a bug in 4.8 w/FF70 or a race deriving from an unrelated setting/plugin/addon/thing in my FF profile. Ideas? I'd hate to reset my profile.

But I will if I have to. A browser without Dark Reader is... just... not a browser.

**Comment by Gusted** [comment]
Solved a long time ago....
