### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1590]
All instances of this Python markup tool completely fail: 

http://docutils.sourceforge.net/
http://docutils.sourceforge.net/rst.html

My poor eyes. :D 
Thanks a lot ^-^

**Comment by Gusted** [comment]
Not sure what the problems was, but seems fixed.

As for your poor eyes (ɔ◔‿◔)ɔ ♥

**Comment by ShalokShalom** [comment]
Yeah, thanks a lot ^-^
