### ISSUE TITLE
Every page shows a light/white background before loading [Firefox]

### ISSUE THREAD

**Issue by extricator** [darkreader/darkreader#1593]
Every page shows a light/white background before loading using Dynamic dark mode. This happens even when Firefox's default dark theme is being used and after the default "blank page" background color has been changed.
![image](https://user-images.githubusercontent.com/47222935/65888401-75df0000-e36d-11e9-9d46-82f730e34aac.png)

I don't know if this behavior is beyond the addon's control but is there a way to workaround this using this extension?

**Comment by lb-d** [comment]
Don't know if this extension can do anything about it, but there is a workaround using a userChrome.css file. 

https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/
https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/

The code you want in userChrome.css:  

/* Loading tab background color */
browser { background-color: #282A33 !important; } 

Set #282A33 to any color you like.

**Comment by extricator** [comment]
> The code you want in userChrome.css:
> 
> /* Loading tab background color */
> browser { background-color: #282A33 !important; }
> 
> Set #282A33 to any color you like.

I tried that and didn't work. I ended up doing the shadowfox scripts.

**Comment by heitorPB** [comment]
I can confirm this behaviour in 69.0.3 (64-bit, Linux).

> I tried that and didn't work. I ended up doing the https://overdodactyl.github.io/ShadowFox/ scripts.

@extricator those scripts work well together with darkreader?

**Comment by extricator** [comment]
> @extricator those scripts work well together with darkreader?

Yes, it's working very well. Fully dark firefox :smile: Even the white bar that appears at the top of firefox in full screen mode it's now gone (dark).

**Comment by yuval-k** [comment]
working for me as well; as per instructions here https://github.com/overdodactyl/ShadowFox/wiki/Installation I had to enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`

**Comment by heitorPB** [comment]
Awesome! now with shadowFox my FF is also all dark!

**Comment by Gusted** [comment]
#1219
