### ISSUE TITLE
Math in wikipedia is is not easily readable

### ISSUE THREAD

**Issue by fbertoli** [darkreader/darkreader#1600]
In wikipedia pages, the math formulas are in black, therefore they are quite hard to read. Is it possible to make them appear white as the rest of the text? (Maybe I'm missing some kind of obvious options setting)
Thanks

**Comment by mxsrv** [comment]
I have the same problem

**Comment by RandoNandoz** [comment]
Me too, the LaTeX markup is black on black.

**Comment by happyangry** [comment]
Same problem. I think it is probably because these formulas are pictures in png format, not LaTeX equations.

**Comment by Gusted** [comment]
Closed by #1805
