### ISSUE TITLE
Disable on sites with toggleable dark mode

### ISSUE THREAD

**Issue by danteissaias** [darkreader/darkreader#1610]
Some sites, such as twitter have a dark mode enabled when system dark them is enabled. Other apps like youtube have a dark mode toggle. Is there any way for Dark Reader to be automatically disabled in these cases?

**Comment by glynn-bit** [comment]
hmmmm they could work on that, but i doubt that they would bother. You can easily add an exception or modify the developer options

**Comment by glynn-bit** [comment]
use dev tools

**Comment by cglong** [comment]
Related to #1247

**Comment by Gusted** [comment]
#1327 Dup
