### ISSUE TITLE
Uninstalling Dark Reader does not delete configuration

### ISSUE THREAD

**Issue by NobleUplift** [darkreader/darkreader#1611]
Where is the configuration for Dark Reader located? I uninstalled it because I wanted to change my site list from a "Not inverted list" to an "Inverted list", without going through the manual effort of deleting each and every single site.

Where is the Dark Reader configuration located? I could go into my profile and delete this manually so that no change on behalf of Dark Reader is required.

**Comment by yawnston** [comment]
It's located in either [chrome.storage](https://developer.chrome.com/extensions/storage) or [firefox storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage). You can refer to [this question on Super User](https://superuser.com/questions/451129/is-it-possible-to-reset-all-google-chrome-extension-settings) for some help with clearing it in chrome, and I'm sure you can find some way to do the same for firefox.

**Comment by birdie-github** [comment]
At least in my case it's stored in `storage-sync.sqlite` in your firefox profile directory.

You can use any SQLite editor to remove the darkreader configuration.

**Comment by NobleUplift** [comment]
I was going to remove my entire list as an attempt to fix #935. Now that I know what the bug is, I don't have to delete the list anymore. Thank you very much for the responses guys!
