### ISSUE TITLE
Dynamic Dark Mode Theme reapplied on tab switch when turned off for a given site

### ISSUE THREAD

**Issue by tustin2121** [darkreader/darkreader#1614]
Since Discord has its own dark mode theme which I'm used to (and this plugin gave its server icons a washed out makeover that made them barely visible), I toggled discord off on the extension. However, whenever I switch away to another tab and then switch back, the dark mode theme returns after a second or two. But it doesn't apply to the images for some reason. It's like half-applied.

The extension shouldn't even be touching the site at all. That's what that current site toggle is for, right? I have to toggle it enabled again for the current site (the images go weird again) and then disable it again for the site to return to normal. Switching between light and dark mode also re-disables the theme again.

Chrome 77, Windows 10.
I'm using the extension in the default blacklist mode, with the default dynamic theme.

**Comment by Gusted** [comment]
Should be fixed.
