### ISSUE TITLE
[Safari] Always Dark mode on macOS Catalina 10.15

### ISSUE THREAD

**Issue by DasBlatz** [darkreader/darkreader#1616]
In macOS Catalina 10.15 when the appearance of OS is set to automatic, DarkReader would not recognise if setting is light in Safari 13.x.

DarkReader uses always the Dark mode in Safari when set to „Auto“, also when it should use light mode.

Please fix this soon for Safari, thanks

**Comment by hologerry** [comment]
same issue.

**Comment by cybacolt** [comment]
Initially had this problem with Catalina and Chrome, but updating Chrome to Version 77.0.3865.120  (latest) and restarting seems to have resolved the issue. Sites do /not/ default to dark once added to the light list.

**Comment by hologerry** [comment]
Dark reader cannot get the system appearance correctly...
The dark mode is actually off, but the dark reader still think it is on.
<img width="435" alt="Screen Shot 2019-11-01 at 12 44 10" src="https://user-images.githubusercontent.com/11660168/68002751-59ecb800-fca5-11e9-9065-36acad76f4a3.png">
<img width="207" alt="Screen Shot 2019-11-01 at 12 44 22" src="https://user-images.githubusercontent.com/11660168/68002763-5fe29900-fca5-11e9-882d-b739e3a59827.png">

**Comment by alexanderby** [comment]
Hi, I've published an update but there seems to be a macOS bug, I haven't found a solution yet. Please, try the following workaround: Go to System Preferences, General, select Light appearance, then select Auto. This way the extension will receive the right system appearance value.

Please, if you see the issue with Sepia tone, go to theme settings and reduce it. Sorry for the error.

**Comment by alexanderby** [comment]
So, it should be fixed for Catalina now (version 1.3.2). But now it's broken in High Sierra, I will provide a fix soon.
