### ISSUE TITLE
"Toggle current site" shortcut duplicates when clicking another button.

### ISSUE THREAD

**Issue by SethX3** [darkreader/darkreader#1621]
When using the extension on Firefox and interacting with the extension overlay there is a visual bug when clicking the "Toggle current site" shortcut which causes it to duplicate.

![Peek 2019-10-10 07-17](https://user-images.githubusercontent.com/22801583/66540999-08319180-eb2e-11e9-8ba9-c66092b2308e.gif)

**Comment by RyanWils** [comment]
Hi I would like to solve this issue
