### ISSUE TITLE
Scary Women on Java.com

### ISSUE THREAD

**Issue by erayerdin** [darkreader/darkreader#1623]
Dark Reader on Java.com

![scary woman](https://user-images.githubusercontent.com/2399084/66591129-c29eb400-eb81-11e9-8a33-741630a35836.png)

nope nope nope

**Comment by LoganDark** [comment]
LOL

**Comment by RsPlayer** [comment]
dark web :rofl:

**Comment by RyanWils** [comment]
Hi I would like to solve the issue with the scary images on java.com
