### ISSUE TITLE
It is possible to add support for css conversion?

### ISSUE THREAD

**Issue by PROgramJEDI** [darkreader/darkreader#1630]
Hello, I'm not so familiar with js to build that, and I'm more concentrated in Python, but it is possible to add a feature that would pull the css converted data to a .css file?

Features:

1.  method that would create a .css document from a given URL, that the DarkReader plugin would manipulate his CSS?

**Comment by Gusted** [comment]
#2538

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted
