### ISSUE TITLE
wikipedia.org: bullets in lists are invisible for dynamic/static themes

### ISSUE THREAD

**Issue by birdie-github** [darkreader/darkreader#1631]
Example: https://en.wikipedia.org/wiki/Intel_(disambiguation)

![dynamic](https://user-images.githubusercontent.com/4958603/66709285-6fc72700-ed50-11e9-8583-93288a436544.png)
![static](https://user-images.githubusercontent.com/4958603/66709286-6fc72700-ed50-11e9-88da-c65bebd88b16.png)

They are perfectly visible for filter/filter+.

**Comment by ewoksama** [comment]
if you inspect element and uncheck the following code:
ul {
    list-style-image: url(/w/skins/Vector/images/bullet-icon.svg?872f1);
}

ul {
    /* list-style-image: url(/w/skins/Vector/images/bullet-icon.svg?872f1); */
}

This fixes it, but I don't know how to add this to the dynamic filter config...

**Comment by Gusted** [comment]
> if you inspect element and uncheck the following code:
> ul {
> list-style-image: url(/w/skins/Vector/images/bullet-icon.svg?872f1);
> }
> 
> ul {
> /* list-style-image: url(/w/skins/Vector/images/bullet-icon.svg?872f1); */
> }
> 
> This fixes it, but I don't know how to add this to the dynamic filter config...

Dont worry I have maked a Pull request to fix this.
For static tho I couldn't make a fix for it.

#2150

**Comment by Wim-o-weh** [comment]
> Dont worry I have maked a Pull request to fix this.
> 
> #2150
@Gusted  Can you please fix that for wikiquote.org too?

**Comment by Gusted** [comment]
> @Gusted  Can you please fix that for wikiquote.org too?

@Wim-o-weh any example URL for wiki quote.org I will than look into it for tomorrow

**Comment by Wim-o-weh** [comment]
@Gusted https://en.wikiquote.org/wiki/Albert_Einstein
