### ISSUE TITLE
Some album covers are inverted on rateyourmusic.com

### ISSUE THREAD

**Issue by Raptorneutron** [darkreader/darkreader#1636]
Hi, I saw there was an issue about this from a couple of months ago but nobody answered so here I am. 
Some album covers (specially ones with white background) are inverted using Dynamic filter and they look horrible. Here's an example:
![imagen](https://user-images.githubusercontent.com/23237379/66844335-74692680-ef6e-11e9-991e-3d47adb7ed98.png)
when it should look like this
![imagen](https://user-images.githubusercontent.com/23237379/66844410-8cd94100-ef6e-11e9-846c-74ecbd1b1560.png)

I'm not familiar with CSS, but I tried to Invert the .coverart_img class and it doesn't seem to work. Any help is appreciated, thanks

**Comment by italodirenzo93** [comment]
It appears that the `<img>` element has its visibility set to `hidden` and the image is actually set as the `background-image` property of the parent `<div>`.
