### ISSUE TITLE
Adding colorshift to dynamic mode

### ISSUE THREAD

**Issue by leaty** [darkreader/darkreader#1641]
Hi,

I was wondering if it's possible to incorporate a form of colorshift next to constrast/sepia etc. It's amazing how well dark reader works, but I would just like to incorporate a slightly blueish tint instead of just pure darkness.

If anyone could point me in the right direction I'll add it myself.

**Comment by Gusted** [comment]
https://darkreader.org/blog/v4-9/ Try preview 5
