### ISSUE TITLE
Monospace font converted (e.g. on github.com)

### ISSUE THREAD

**Issue by kbakk** [darkreader/darkreader#1643]
Steps to reproduce:

1) Enable Dark Reader for github.com
2) Navigate to a file in github.com - e.g. https://github.com/darkreader/darkreader/blob/master/package.json

Expects: Code is monospace

Actual: Code is variable-width font (Helvetica or similar)

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/24817039/67087546-6a7c3900-f1a3-11e9-876a-c93a4f91af32.png">

Also visible in: Jenkins, GitLab.com

**Comment by AndydeCleyre** [comment]
I wanted to use my system/browser mono theme for code, so hit the `Dev tools` button and dropped this into the `github.com` section, but it still seems to get overwritten by the other configured font style:

```css
.markdown-body code,
.blob-code,
.blob-code-inner,
.blob-num {
    font-family: mono !important;
}
```

**Comment by Gusted** [comment]
If you didn't setted any font settings in Dark Reader, Dark Reader won't touch it.
![](https://i.imgur.com/8G92g85.png) < Default by Github.

**Comment by Gusted** [comment]
Does it work with darkreader toggled off?

**Comment by AndydeCleyre** [comment]
> If you didn't setted any font settings in Dark Reader, Dark Reader won't touch it.

I think the expectation here (at least from @kbakk and me, is that a custom font for normal text will not de-mono intentionally mono text.

I'm just trying out darkreader for the first time now, I usually (and think I will continue to) use [a stylish script](https://github.com/StylishThemes/GitHub-Dark) for github in particular.

**Comment by Gusted** [comment]
> I'm just trying out darkreader for the first time now, I usually (and think I will continue to) use [a stylish script](https://github.com/StylishThemes/GitHub-Dark) for github in particular.

https://github.com/openstyles/stylus

**Comment by AndydeCleyre** [comment]
> https://github.com/openstyles/stylus

Yes, that's the extension I use.

**Comment by AndydeCleyre** [comment]
Alright, here's another example: https://plumbum.readthedocs.io/en/latest/local_commands.html

When we set our preferred font with something like DarkReader, we would still hope that different classes of font are maintained -- most of all mono vs proportional, and secondarily sans- vs serif.

**Comment by Gusted** [comment]
Different classes of font's are maintained? AFAIK the font's are fetched from the system we just push them to text.

**Comment by AndydeCleyre** [comment]
> Different classes of font's are maintained? AFAIK the font's are fetched from the system we just push them to text.

Sorry, I'm not sure what you mean, and now can't even find a place in DarkReader to set a custom font via the UI, though I really thought I did so (to `sans-serif` as determined by Firefox/fontconfig).

If I enable the default DarkReader theme at [that readthedocs page](https://plumbum.readthedocs.io/en/latest/local_commands.html), both the normal `<p>` text and the intentionally fixed-width `<pre>` text gets rendered in my proportional sans-serif font. Is it different for you?

**Comment by Gusted** [comment]
> If I enable the default DarkReader theme at [that readthedocs page](https://plumbum.readthedocs.io/en/latest/local_commands.html), both the normal `<p>` text and the intentionally fixed-width `<pre>` text gets rendered in my proportional sans-serif font. Is it different for you?

That's right both are setted to another font and get another width, but every font have different sized for an example Segoe UI 16px is not the same as sans-serif 16px. Why? blame the one who made the font's.

**Comment by AndydeCleyre** [comment]
The issue isn't the size of the fonts, it's the character width within each font. The text within `pre` tags should always be rendered with a fixed width (monospace) font.

**Comment by Gusted** [comment]
> The issue isn't the size of the fonts, it's the character width within each font. 

Character size is partial font size. Each font have another character width

> The text within `pre` tags should always be rendered with a fixed width (monospace) font.

Not everyone is waiting on that when they specific a font. As <pre> also can be used for other things(I thought)

**Comment by AndydeCleyre** [comment]
> Their is no suchs thing to set fixed width for a font.

I don't know what this means, but as I can't find a way to undo the custom font setting which is now breaking mono text, my trial of this particular tool is over. Thank you for fighting the good fight for readable website colors, and good luck with the project.

**Comment by Gusted** [comment]
> I don't know what this means, but as I can't find a way to undo the custom font setting which is now breaking mono text.

Disable the font setting
![](https://i.imgur.com/aekbjtg.png)
to 
![](https://i.imgur.com/yHD9F4r.png)

>my trial of this particular tool is over. Thank you for fighting the good fight for readable website colors, and good luck with the project.

You asking something impossible to do.

**Comment by AndydeCleyre** [comment]
> Disable the font setting

OK, I reinstalled to have a look.

That's a nice screenshot of the font selection combobox which I can't find.

![image](https://user-images.githubusercontent.com/1787385/82363577-042af380-99dc-11ea-92c3-9c6de9523b01.png)

![image](https://user-images.githubusercontent.com/1787385/82363618-1016b580-99dc-11ea-9356-d4d6f05d79b7.png)

> You asking something impossible to do.

I'm not sure if we're talking about the same thing here. All I'm wondering about is to either have the `pre` elements set to the generic `monospace` or not overridden at all when setting a custom font through this tool. For example, at Firefox settings > Language and Appearance > Fonts and Colors > Advanced, you can uncheck the box at the bottom ("Allow pages to choose their own fonts, instead of your selections above") and achieve this for all pages.

**Comment by Gusted** [comment]
That's the new UI in Beta it doens't have font's yet... It will be added in darkreader V5 release...
But I will open a PR to ignore pre elements when setting a custom font Will that solve this problem?

**Comment by Gusted** [comment]
#2555 Their you go.

**Comment by AndydeCleyre** [comment]
Yes I think that will solve the problem. For bonus points, you could add selections for each class of font (so I user could have their preferred mono font for all `pre` items), or instead offer an option to use the fonts already specified by the user in `about:preferences`.

**Comment by Gusted** [comment]
1. Not possible with current UI
2. Firefox don't give that option only Chromium based one.

**Comment by AndydeCleyre** [comment]
To be clear, you mean this extension will not add user preferred font choice to the firefox extension?

**Comment by Gusted** [comment]
Sadly not. Firefox dont have any exposed API for addons to get font settings.

Chromium has https://developer.chrome.com/extensions/fontSettings

**Comment by AndydeCleyre** [comment]
FWIW, at least on linux, I think all it would take to use Firefox/fontconfig's user-preferred fonts would be to use CSS to set the `font-family` to one of `sans`, `serif`, or `monospace`. I don't think you need to access Firefox's settings at all.

**Comment by mythio** [comment]
The workaround is particularly simple. You need to...
1. Clear any fonts setting in dark reader
2. Open devtools inside dark reader
3. Find `github.com`
4. Add
```css
* {
  font-family:  XXX
}
```
at the top of the github.com section

5. Apply and profit!

I am pretty sure this method applies to sites other than github.

**Comment by Gusted** [comment]
But this will override the Monospace font and than you will be back with OP's issue 🤷
