### ISSUE TITLE
Doesn't work well on Git's website

### ISSUE THREAD

**Issue by AndyL964** [darkreader/darkreader#1644]
Everything becomes light grey instead.
Firefox stable 69.03.
![image](https://user-images.githubusercontent.com/22827982/67136615-75ec5600-f1dd-11e9-830b-78f7f600561d.png)

**Comment by aerob1t** [comment]
I made it work by toggling the Theme Generation mode to "Filter" for that specific site. I hope it helps!

![theme_fix_toggle](https://user-images.githubusercontent.com/54596177/67186258-66912680-f3f0-11e9-8f1b-2401ae08eaab.png)

**Comment by AndyL964** [comment]
> 
> 
> I made it work by toggling the Theme Generation mode to "Filter" for that specific site. I hope it helps!
> Tried and tested on Firefox 69.0.3
> 
> ![theme_fix_toggle](https://user-images.githubusercontent.com/54596177/67186258-66912680-f3f0-11e9-8f1b-2401ae08eaab.png)

Thanks for letting me know! But, I'll leave it here as it's still worth reporting since Dynamic is still in development according to the help page.

**Comment by AndyL964** [comment]
Oh, wait, didn't mean to close this.
