### ISSUE TITLE
Does Dark Reader support changing colors in SVG image text elements?

### ISSUE THREAD

**Issue by StewAlexander-com** [darkreader/darkreader#1648]
simonemainardi over with [Ntopng](https://github.com/ntop/ntopng/) asked the following:

![image](https://user-images.githubusercontent.com/48565067/67203869-3048ac80-f3da-11e9-96be-935c6b3f48f5.png)

I'd like to see if ntopng could work with darkreader ....

**Comment by StewAlexanderACC** [comment]
See ntopng ticket [#2913](https://github.com/ntop/ntopng/issues/2913) for reference

**Comment by StewAlexanderACC** [comment]
@nikolay / @CyBot / @cglong / @amrtn - Can any of you please respond? thanks

**Comment by Gusted** [comment]
Yes. If you set into the text fill: white or color: white dark reader changes the style that's how we work.

Sorry for 0 response, issues were never really taken care of. I'm just as maintainer going trough old issues.

Regards,
Gusted.

**Comment by StewAlexander-com** [comment]
I wanted to do this to provide a dark theme for NTOPNG, they went ahead and integrated their own.

Apparently this isn't getting much attention, so dumped it
