### ISSUE TITLE
Issues with Google Docs

### ISSUE THREAD

**Issue by Roadhog360** [darkreader/darkreader#1650]
Hey, I've been loving Dark Reader so far. In fact, I am using it right now while typing this. My dream has been Google Docs being dark and not a pain to look at, and this finally comes true! ... Almost.

Highlighting is almost invisible when selecting text, and it seems to actually invert my images in a spreadsheet, making it really awkward to look at. The spreadsheet itself actually looks exactly how I'd want it to with Dark Reader on, but unfortunately I had to turn it off for Docs due to these issues. 
I was wondering if either a fix for Docs could be applied, or if I'd be allowed to exempt specific elements on sites.

**Comment by fascistutopia** [comment]
Google Docs doesn't get dark at all for me.

**Comment by Gusted** [comment]
Hello their! 

Can you check with the latest version of Darkreader this issue? And also provide some screenshot :-)
