### ISSUE TITLE
Firefox 70: Only background color is changed on Twitter

### ISSUE THREAD

**Issue by jujar** [darkreader/darkreader#1654]
I'm using Firefox 70 and Dark reader 4.8.2. On Twitter, only the background color is changed to dark colors, everything else stays bright. Messing with the settings makes no difference with foreground colors.

**Comment by jujar** [comment]
Update: the problem persists in Firefox 70.0.1 and DR 4.8.4.

**Comment by linsui** [comment]
For me, even the background is white.

**Comment by jujar** [comment]
That problem came with version 4.8.4, I think. When the page loads, the background flashes briefly as dark and then something overrides it, and everything is bright again.

**Comment by Gusted** [comment]
Should be fixed.
