### ISSUE TITLE
Firefox 70 broke DR

### ISSUE THREAD

**Issue by Isolationismyfriend** [darkreader/darkreader#1657]
Every site I visit I have to push toggle current site so that dark reader can work properly. When before by default it was already in night mode upon visiting any site. Pretty sure it has to do with the recent update. Or maybe it's just me?

**Comment by alexanderby** [comment]
Please, open **Site List** tab and click **Not Invert Listed**.

**Comment by Isolationismyfriend** [comment]
> 
> 
> Please, open **Site List** tab and click **Not Invert Listed**.

Facepalm* Thank you so much. That did it!
