### ISSUE TITLE
Changes color of text on Google Sheets

### ISSUE THREAD

**Issue by Ogi22po** [darkreader/darkreader#1659]
Unwanted changes color of text format in Google Sheets.
When i type text and tap enter, font collor is not black, allso after i dissabled addon,

Google Chrome V 77.0.3865.120 (64-bit)

Before start typing
<img width="288" alt="2019-10-24 16_41_18-01" src="https://user-images.githubusercontent.com/36459820/67496913-770a0100-f67d-11e9-9129-61badff30eb1.png">

After typing and hit enter
<img width="284" alt="2019-10-24 16_42_22-02" src="https://user-images.githubusercontent.com/36459820/67496924-7a04f180-f67d-11e9-8a58-3521d1da7b95.png">

While typing
<img width="97" alt="2019-10-24 16_40_48-03" src="https://user-images.githubusercontent.com/36459820/67496934-7cffe200-f67d-11e9-8208-7945ae6ce5f0.png">

**Comment by gibfahn** [comment]
Dup of https://github.com/darkreader/darkreader/issues/490
