### ISSUE TITLE
[Feature Request] All Sites Mode, in addition to Invert/Non-invert List

### ISSUE THREAD

**Issue by archaik** [darkreader/darkreader#1661]
Would be nice to have a 3rd button for "All Sites" next to "Invert listed only" and "Not invert listed" under the Site List tab.

Use case:
1. You want to keep some sites dark all the time.
2. At certain times, you want all sites to go dark, for example at night.

This button would turn all sites on/off, without having to remove them from the Invert list.

Currently, if you switch from "Invert" to "Not Invert," your usual dark sites goes light, which would not be ideal for reading at night.

**Comment by Gusted** [comment]
Checkout the new UI along side Automation
