### ISSUE TITLE
Unable to activate dark mode on website on non standard ports

### ISSUE THREAD

**Issue by dumbasPL** [darkreader/darkreader#1663]
If i have some kind of website on a nonstandard port like 8080 or 5000 then i'm not able to activate dark mode. 
![image](https://user-images.githubusercontent.com/29180158/67559615-96ef0280-f719-11e9-97d6-7532694c22be.png)

When i click the button to toggle current website nothing happens.

Browser: Google Chrome 77.0 x64
Os: windows 1903
Extension version: 4.8.3 installed from chrome store

Extension has permission to access site

**Comment by Gusted** [comment]
Fixed :D
