### ISSUE TITLE
Can I override styles from this plugin in my websites?

### ISSUE THREAD

**Issue by Committing** [darkreader/darkreader#1665]
I run some popular websites and some don't convert well with darkreader.

Can I wrap some styles with something to fix how it looks when darkreader is enabled for the user?

Maybe a specific stylesheet I can add to my site that will be used with darkreader if it exists? `example.com/darkreader.css`

**Comment by alexanderby** [comment]
Hi, the idea of Dark Reader is that everybody can configure web pages to look comfortable for eyes. If something is wrong, you can use Dev Tools and then submit a fix on GitHub, see the instructions https://github.com/darkreader/darkreader#how-to-contribute

**Comment by ncodefun** [comment]
uh... didn't know an extension could just nuke any attempt by a dev to protect it's own styling from over-reaching / misbehaving extensions. 🙄 ...Unless I add a 115KB script, or request a fix. UGH! And those "fixes" files, won't they become super large files with time and popularity?? This is not futur proof at all, and look to me as a serious anti-pattern for web devs.

**Comment by ncodefun** [comment]
# What I do with the dark force...
```javascript
/// SUBJUGATING THE DARK FORCE (DARK READER EXTENSION)
/// -> the MF doesn't want anything to touch it (seems it observes us), 
/// 	 but we are the main one; let's look and act before it can see... (the power of now!)
const observer = new MutationObserver( mutations => {
	mutations.forEach( mutation => {
		for( let node of mutation.addedNodes){
			if( !(node instanceof HTMLElement)) 
				continue
			if( node.classList.contains('darkreader')){
				/// if we don't remove, it injects 45 nodes...
				node.remove() 
				/// -> injects 175 nodes?? (we're prob too fast, should wait one by one, stop and reobserve, maybe.)
			}
		}
	})
})
observer.observe( document, { childList:true, subtree: true })
/// Note: there's most certainly a perf. cost to fight the dark side...
```
