### ISSUE TITLE
Dark Reader does not work under some web sites(such as tfs) in firefox

### ISSUE THREAD

**Issue by thornfieldhe** [darkreader/darkreader#1666]
![Snipaste_2019-10-28_15-04-35](https://user-images.githubusercontent.com/10624419/67658369-59e27480-f994-11e9-9cf6-ca5571ecc701.png)

**Comment by thornfieldhe** [comment]
firefox version 70.0(x64)

**Comment by thornfieldhe** [comment]
os version win 10 1903

**Comment by thornfieldhe** [comment]
tfs is called team foundation server

**Comment by dumbasPL** [comment]
its caused by the non-standard port used by the website. see #1663

**Comment by aksappy** [comment]
@dumbasPL This problem exists in other websites as well, such as **LinkedIn**

**Comment by AAnzel** [comment]
Can confirm that this is still an issue for LinkedIn, as @aksappy indicated.
```
Mozilla Firefox 73.0.1 (64-bit)
```

**Comment by 037g** [comment]
Can confirm, still an issue under FF 76.0

**Comment by Gusted** [comment]
Any errors in console or background script?
