### ISSUE TITLE
[HELP] How to find UI elements names of popup for userContent.css ?

### ISSUE THREAD

**Issue by xerta555** [darkreader/darkreader#1669]
Hi,

I'm trying to edit this addon on my Firefox by using my userContent.css file.
I have edit `background-color` and `color` css properties, and some others, but i can't inspect all the popup UI because 95% of the UI stuff is writed in the js files in the popup folder.

There is a way to find/pick the UI specific item to overright them in my css file?

**Comment by xerta555** [comment]
No answer?

**Comment by Gusted** [comment]
Could you provide a gif or screenshot to show this issue.

**Comment by xerta555** [comment]
> Could you provide a gif or screenshot to show this issue.

How to get the CSS names of theses UI elements to be allow to change background color and colors of them through the userContent.css for Firefox ?
![HELP  How to find UI elements names of popup for userContent css  · Issue #1669 · darkreaderdarkreader - Mozilla Firefox](https://user-images.githubusercontent.com/20888017/77249500-b7c47100-6c41-11ea-9d23-92132249deb2.jpg)

**Comment by Gusted** [comment]
https://extensionworkshop.com/documentation/develop/debugging#debugging-popups and than debugging popups sections this will guide you trough to use the inspector to get the CSS of the elements. Goodluck with CSS the UI would love to see the final result if you are done :)

**Comment by xerta555** [comment]
> extensionworkshop.com/documentation/develop/debugging#debugging-popups and than debugging popups sections this will guide you trough to use the inspector to get the CSS of the elements.

As i don't have skills in js, i can't deduce the CSS names of UI elements i want to edit.
And as all UI elements of this modules are declarated by JS, i can't get it by drag and drop any popup.html file in a tab of the browser.
So if you have any other idea........

**Comment by Gusted** [comment]
What about installing ungoogled-chrome or any other chromium based where you can inspect a popup

**Comment by xerta555** [comment]
> What about installing ungoogled-chrome or any other chromium based where you can inspect a popup

How can Chromium or similar help me more than Firefox?

**Comment by Gusted** [comment]
In a chromium based browser you can right click the popup and inspect all the elements and get the CSS names

**Comment by Gusted** [comment]
![](https://i.imgur.com/2Qtrq2h.png) Right click on the popup

**Comment by xerta555** [comment]
I have found the way, i works on that.
This module being rather complex in its functioning, I get some quirks as a result, I work on it.
![HELP  How to find UI elements names of popup for userContent css  · Issue #1669 · darkreaderdarkreader - Mozilla Firefox](https://user-images.githubusercontent.com/20888017/77253099-9ae76800-6c58-11ea-946c-44c22f52c94a.jpg)
