### ISSUE TITLE
New Tab blinding white

### ISSUE THREAD

**Issue by privacyguy123** [darkreader/darkreader#1677]
How do you fix this?

![image](https://user-images.githubusercontent.com/50337995/67892125-f307bb80-fb4b-11e9-96a7-22949d1eab64.png)

**Comment by vv7v7** [comment]
Check your theme of your browser(trying changing it to anothers(i.e. dark)) and type the result.

**Comment by rja907** [comment]
@vv7v7 Same here. (I have a dark chrome theme on Chrome)

**Comment by privacyguy123** [comment]
Browser is in dark mode - new tab still blinding white.

**Comment by Gusted** [comment]
#1219 dupe
