### ISSUE TITLE
The latest version does not work ESR

### ISSUE THREAD

**Issue by wvxwxvw** [darkreader/darkreader#1683]
4.8.1 works everywhere. Updated to 4.8.3 and the style is not automatically picked up when the page loads, but picked up when you manually switch. I roll back the version to 4.8.1 and everything works again.
Fix the work or minimum allowed version.

**Comment by Niubbo** [comment]
I have this issue too with firefox esr, and the android version too
it's really annoying since i disabled the extension, i hope you could fix it asap

**Comment by Gusted** [comment]
s h o u l d  b e  f i x e d
