### ISSUE TITLE
Slow Down the Web Loading

### ISSUE THREAD

**Issue by L1cardo** [darkreader/darkreader#1685]
This will slow down the wedsite [https://www.douyu.com](https://www.douyu.com)
10 more seconds slower when the DarkReader is on.

**Comment by alazymeme** [comment]
1. The URL is wrong in your message
2. I cannot reproduce, can you pls provide instructions tks

**Comment by L1cardo** [comment]
> 1. The URL is wrong in your message
> 2. I cannot reproduce, can you pls provide instructions tks

sorry for the wrong URL, the url is www.douyu.com, please have a look

**Comment by alazymeme** [comment]
I still cannot reproduce, can you pls provide instructions? What browser are you using? What version, etc...
https://i.nuuls.com/9k-ge.gif

**Comment by L1cardo** [comment]
This is one of most popular streaming web site in China.
The main page looks fine, but when you go into one specific room , you can set the difference.
Please try this:  https://www.douyu.com/699689 

before
https://i.nuuls.com/z4-jl.gif
after
https://i.nuuls.com/9qqoK.gif

**Comment by alazymeme** [comment]
Takes a decent amount longer, I see what you mean now.

**Comment by Gusted** [comment]
#2550
