### ISSUE TITLE
Protonmail 4.0 Beta

### ISSUE THREAD

**Issue by geeknik** [darkreader/darkreader#1686]
ProtonMail recently announce the beta version of their new 4.0 web client. Sadly, there is still no word about a long-promised dark mode. When using Dynamic mode, it is very hard to tell which mesages are selected, etc.  Here is how it looks with Dark Reader:

Dynamic:
![tdr-dynamic](https://user-images.githubusercontent.com/466878/68043153-a4b90080-fca2-11e9-903a-db0557ccea1e.png)

Dynamic + Compose: 
![tdr-dynamic-compose](https://user-images.githubusercontent.com/466878/68043169-b0a4c280-fca2-11e9-89df-59cc904285fc.png)

Static:
![tdr-static](https://user-images.githubusercontent.com/466878/68043225-cc0fcd80-fca2-11e9-819a-5b9a487e5b6b.png)

Filter+:
![tdr-filter+](https://user-images.githubusercontent.com/466878/68043233-d205ae80-fca2-11e9-98ae-78eac620bc8c.png)

Filter: 
![tdr-filter](https://user-images.githubusercontent.com/466878/68043248-d8942600-fca2-11e9-9c7a-d6e3d2e3d3ac.png)

Disabled:
![tdr-disabled](https://user-images.githubusercontent.com/466878/68043514-77208700-fca3-11e9-9e52-dc1a43abbc05.png)

**Comment by Gusted** [comment]
Should be fixed.
