### ISSUE TITLE
remove support.discordapp.com from global dark list

### ISSUE THREAD

**Issue by leumasme** [darkreader/darkreader#1689]
![image](https://user-images.githubusercontent.com/29953391/68086425-55aecf00-fe4c-11e9-9526-77575081f526.png)
it isnt dark.

**Comment by alazymeme** [comment]
No it'd be discord.com that is in the global list, the subdomain needs to be removed

**Comment by irvnriir** [comment]
please fix this

**Comment by DominykasPetke** [comment]
status.discordapp.com is also globally listed even though it's absolutely blinding

**Comment by KaKi87** [comment]
Same for blog.discordapp.com

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by Gusted** [comment]
Hello, I just got it working I will make a Pull Request soon after testing if all CSS is good or Of If it need modification

**Comment by Gusted** [comment]
Fixed.
