### ISSUE TITLE
Minecraft Site not supported

### ISSUE THREAD

**Issue by WilsontheWolf** [darkreader/darkreader#1693]
the [minecraft](https://minecraft.net) site has the logo incorrectly inverted. There are some other small faults to, like the background being replaced. 
![](https://jwiggs.is-ne.at/69kGeP.png)
![](https://jwiggs.is-ne.at/n6XhPq.png)

**Comment by alazymeme** [comment]
Logo does not invert, but the background changes: https://i.nuuls.com/Z0WhQ.png

**Comment by Gusted** [comment]
New layout not more the problem
