### ISSUE TITLE
Not working for bridges.torproject.org?

### ISSUE THREAD

**Issue by simulacr4m** [darkreader/darkreader#1694]
Whenever I go to [Tor's bridge database](https://bridges.torproject.org/), the site isn't converted to dark mode. I'm using Firefox 70.0 BTW.

Thanks

**Comment by Gusted** [comment]
Hello Their! 

Can you check this issue with the latest version of Darkreader and Provide a screenshot if the issue still persist? Couldn't reproduce the issue.

**Comment by simulacr4m** [comment]
It seems to be working now. I think we can close this issue.
