### ISSUE TITLE
Didn't activate immediately when navigating with Vimium

### ISSUE THREAD

**Issue by FranklinYu** [darkreader/darkreader#1696]
This is a bug report.

Scope:
* It can be reproduced only when opening a link *in a new tab* with [Vimium](https://vimium.github.io/) (triggered by <kbd>F</kbd>).
* It seems to affects Chrome only.
* It seems to only affect internal navigation within Debian Wiki, such as https://wiki.debian.org/systemd. Internal links in Debian Wiki are not prefixed with icons, such as "systemd/Services".
* Refreshing the page can force dark mode.

For easier testing, I created a separate [Chrome profile](https://support.google.com/chrome/answer/2364824) where only Vimium and Dark Reader are installed.

**Comment by Gusted** [comment]
Should be fixed.
