### ISSUE TITLE
Invert IFrames

### ISSUE THREAD

**Issue by zegab1** [darkreader/darkreader#17]
Hi Alexender,

Thank you for this great extension :).

My issue is, that I would like to read a site in dark, where are sub-pages are loaded on the fly to several iframes. As the content is loaded, it won't be inverted, but stays in light colours.

If I load the sub-pages standalone, they rendered in dark, correctly.
Is this a bug or feature, and is there anything I can do about this?

regards,
Gabor

**Comment by alexanderby** [comment]
This is technically possible, if your IFrames and source page are in the same domain, that is follow [Same Origin Policy](http://javascript.info/tutorial/same-origin-security-policy).

**Comment by ershov** [comment]
Hi,
I have an opposite issue here: the iframe is inverted by the topmost page's filter and after that the content of iframe gets inverted once more, thus becoming bright again.

If I go 'inspect element' and disable the Dark Reader's inverting style, the iframe goes black.

So I guess the solution is _not_ inverting iframes.

Thanks!

**Comment by ershov** [comment]
Seems like a problem with filters in Chrome.
I noticed that not all combinations of filters are supported by Chrome.

Maybe it's worth disabling 'contrary rule' for iframes.

---
## DarkReader is off
<img width="987" alt="screen shot 2016-08-19 at 14 48 20" src="https://cloud.githubusercontent.com/assets/449936/17799273/a2419080-661c-11e6-80b3-17a0663cd911.png">

---
## DarkReader is on
<img width="990" alt="screen shot 2016-08-19 at 14 48 56" src="https://cloud.githubusercontent.com/assets/449936/17799278/abe8714e-661c-11e6-83f7-383d744d9840.png">

---
## DarkReader is on, and 'contrary rule' disabled.
<img width="988" alt="screen shot 2016-08-19 at 14 49 11" src="https://cloud.githubusercontent.com/assets/449936/17799280/b0bc1522-661c-11e6-84d7-7e399b039d48.png">

**Comment by DanRathbun** [comment]
Bump!

All YARD generated documentation pages have index iframes (in the same domain) that are not inverted.

Examples:

* http://www.rubydoc.info/gems/yard/0.9.5/index
* http://ruby.sketchup.com/index.html

... or any other Ruby language gem documentation listed at:
http://www.rubydoc.info/gems/

Many of the code for these gems are hosted on GitHub, and a GitHub project can be set to automatically generate YARD documentation.

**Comment by ershov** [comment]
For myself, the solution is to 'fork' the extension and delete 'contrary rule' at all so that everything gets inverted without any exception.
In a rare condition when I want to see something in original color I just use hotkey to disable Dark Reader for for a while and then enable it back again.

Cheers,

**Comment by DanRathbun** [comment]
> ... delete 'contrary rule' at all so that everything gets inverted without any exception.

everything ? as images, thumbnails,... EVERYTHING ? If so, **no**, I do not want this.

> ... the solution is to 'fork' the extension ...

I already have enough forks, and "things on the fire." I do not need to be learning how to fix "one more someone else's" project. (Ie, I am already in the midst of doing this several times currently, and it has taken me away from my own projects.)

Lastly, I do not have an account for the Chrome store, so I'd be having to run Chrome in Dev mode, to use the extension (I think.) I am tired of receiving the warning about dev mode, so no, this is not a solution.

The solution is to add the enhancement to the original extension so all benefit.

**Comment by DanRathbun** [comment]
> @alexanderby This is technically possible, if your IFrames and source page are in the same domain, that is follow Same Origin Policy.

**Can we do this now with some special selectors ?**

ie: `"iframe#nav #document li.clicked > div.item"` ? ... _does not seem to work_

**Comment by RalphLesch** [comment]
An alternative way to handle iframes (for cross domain iframes, too) could be to just treat the iframe as its own window, that is inject DarkReader consten script / style into the frame (child) window, too:
- top window: white = invert
  iframe: reinvert = no change
  -  iframe child window: white = invert (threat like top window)
   ...

This should be simply possible with `chrome.tabs.executeScript(..., {allFrames: true})`, which works for cross site frames, too.
I see only one problem with this method: Instead of the the background script, the injected content script would need to determine the injected style (or whether not to invert anything) via the window/frame URL or request the relevant code / style by via message (sending URL and iframe state) from the background script (returning js / css source).

For more control, an iframe detection within the injected script (`window.self !== window.top`) together with a iframe option/subgroup for the inversion fixes (`fix_inversion.json`) could be added, to support different style fixes for iframes.

**Comment by arthurblake** [comment]
Just started using this plugin. It's awesome! Noticed right away, one common site that uses iframes is https://gitter.im - the left frame shows in dark and the right will not go dark no matter what you do. Just adding my 2c here that a simple out of the box solution would be much appreciated.

**Comment by ershov** [comment]
Removing any exception rules works fine. There is a clone extension doing that.

**Comment by alexanderby** [comment]
Recently I've found out that extension can have access to IFrames, so the fix should be simple. I will fix it after publishing Dynamic Theme mode.

**Comment by KaffeMyers** [comment]
Using dark reader have made me realize that I browse a few websites actually using iframes... Glad to see you have a fix planned!

**Comment by DanRathbun** [comment]
Iframes are inverted in FILTER mode but _**not**_ DYNAMIC mode.

**Comment by alexanderby** [comment]
They are fully inverted in Filter mode, inverting images too. I've already successfully experimented with inverting content inside IFrames, but need some more time to fix message passing between tabs, IFrames and the extension.

**Comment by DanRathbun** [comment]
Looking forward to the fixes.

BTW, Dynamic Mode is working quite well (except for the IFRAMES.) 
* Another [forum site](https://sketchucation.com/forums/) running phpBB looked poor in Filter mode, but **very nice** in Dynamic Mode.

**Comment by alexanderby** [comment]
Version 4.3.3 should now invert IFrames in all modes

**Comment by filips123** [comment]
@alexanderby Is it also possible to invert sandboxed iframes that aren't on the same origin? It currently doesn't work.

**Comment by matso167** [comment]
Does not work on ZeroNet websites
ZeroNet websites are basically iframes. I think the iframe URL is changed with javascript.
While the main page <head> has darkreader <style>s added, iframe does not.

Iframe is initially like that (page source):
<iframe src='about:blank' id='inner-iframe' sandbox="allow-forms allow-scripts allow-top-navigation allow-popups allow-modals allow-presentation allow-pointer-lock " allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true"></iframe>

And looks in inspector like this:
<iframe src="/Talk.ZeroNetwork.bit/?wrapper_nonce=xyz" id="inner-iframe" sandbox="allow-forms allow-scripts allow-top-navigation allow-popups allow-modals allow-presentation allow-pointer-lock " allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true"></iframe>
