### ISSUE TITLE
Status.im 

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#1702]
Not working at all (here) https://status.im/research/

Firefox 70

**Comment by alazymeme** [comment]
Can you pls define what you mean by "not working"? Like a screenshot? It's working just fine for me: https://i.nuuls.com/Z4FS7.png

**Comment by ShalokShalom** [comment]
Oh, I thought its not working for everyone. 

Here a screenshot:

![Screenshot_20191109_111331](https://user-images.githubusercontent.com/6344099/68526969-fdf7e400-02e1-11ea-8787-9745b1dc8737.png)

**Comment by Gusted** [comment]
Have another look.
