### ISSUE TITLE
the pop-up will display "Loading, please wait" and there will be no change.

### ISSUE THREAD

**Issue by tnira** [darkreader/darkreader#1703]
macOS 10.15.1 Catalina
Firefox 70.1
Dark Reader 4.8.4

After clicking the add-on's icon, the pop-up will display "Loading, please wait" and there will be no change.

I checked the console with the Firefox add-on debugging tool.

RangeError: invalid language tag: ja-JP-mac index.js: 2177: 30
    ValidateAndCanonicalizeLanguageTag self-hosted: 5984
    CanonicalizeLocaleList self-hosted: 6067
    InitializeDateTimeFormat self-hosted: 6522
    toLocaleTimeString self-hosted: 943
    <Anonymous> moz-extension: //1dbffb98-8f69-8e4c-a693-569114064895/ui/popup/index.js: 2177
    <Anonymous> moz-extension: //1dbffb98-8f69-8e4c-a693-569114064895/ui/popup/index.js: 3682

 Because of the above display, when the Firefox language setting is changed from Japanese to US, the pop-up appears to be displayed normally.
Would you please help me get the popup to work with the language set to Japanese?

**Comment by Tatsuki5274** [comment]
I'm facing the same problem in my Environment.
The Extension can work on Google Chrome, but it can't work on Firefox at my Mac.
Previously I tried to fix it, turn off my firewall, turn off virus security, etc...
But I could not resolve it. 

RangeError: invalid language tag: ja-JP-mac index.js line 1946 > scriptElement:2177:30
    ValidateAndCanonicalizeLanguageTag self-hosted:5984
    CanonicalizeLocaleList self-hosted:6067
    InitializeDateTimeFormat self-hosted:6522
    toLocaleTimeString self-hosted:943
    <匿名> moz-extension://3b048fe6-da75-d146-aa2d-1fe63237064c/ui/popup/index.js line 1946 > scriptElement:2177
    <匿名> moz-extension://3b048fe6-da75-d146-aa2d-1fe63237064c/ui/popup/index.js line 1946 > scriptElement:3682
    enter resource://devtools/server/actors/utils/event-loop.js:79
    enter self-hosted:1017
    _pushThreadPause resource://devtools/server/actors/thread.js:248
    _pauseAndRespond resource://devtools/server/actors/thread.js:795
    pauseAndRespond resource://devtools/server/actors/thread.js:993
    _makeOnStep resource://devtools/server/actors/thread.js:922
    TabManager moz-extension://3b048fe6-da75-d146-aa2d-1fe63237064c/background/index.js:1946
    apply self-hosted:2018
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2424

When I checked the code,  I found that related the problem possibly.
[Screenshot shot (Dropbox)](https://www.dropbox.com/s/qbmbb01sw2eqc0j/Screen%20Shot%202019-11-08%20at%2015.36.43.png?dl=0)
"tab" is not exit in "sender" object ... why?

**Comment by Tatsuki5274** [comment]
I didn't know to able to upload photo.
The Screenshot is same above one.

<img width="1280" alt="Screen Shot 2019-11-08 at 15 36 43" src="https://user-images.githubusercontent.com/42799529/68455927-dea87a80-023f-11ea-85e1-1f8ae33da3fd.png">

**Comment by alexanderby** [comment]
Thank you for detailed errors. The problem happens not in `background/index.js`, but in `ui/popup/index.js`. It seems like Firefox bug, `chrome.i18n.getUILanguage()` returns incorrect language code, which is not recognized by `new Date().toLocaleTimeString(LANGUAGE_CODE)`. I will think what to do with this.

**Comment by alexanderby** [comment]
By the way, did it worked before? Did it stop working after macOS update or Firefox update?

**Comment by tnira** [comment]
In my environment, it worked normally when using FIrefox69. Probably this seems to have happened after updating to Firefox 70.1.

**Comment by Tatsuki5274** [comment]
@alexanderby 
Thank you for replying!

> did it worked before?
No, it didn't worked before.
I've never seen it working at Firefox.

**Comment by alexanderby** [comment]
@tnira Could you please open Console (on any tab press F12) and run `navigator.languages`? What do you get?

**Comment by tnira** [comment]
By all means.

![スクリーンショット 2019-11-12 2 51 16](https://user-images.githubusercontent.com/3020006/68609059-b64aa580-04f7-11ea-97ff-08c43b06ee6f.png)

**Comment by c33s** [comment]
this bug still exists on waterfox classic 2020.04
