### ISSUE TITLE
Auto mode in Safari 13 (Catalina)

### ISSUE THREAD

**Issue by SimonAB** [darkreader/darkreader#1706]
Auto mode not fixed yet in Safari (Catalina): no transition to Catalina's 'Auto' appearance setting, whether from Light or from Dark, is picked up. (Other browsers work as expected, so this seems to be Safari and macOS 15.1-specific...).

_Originally posted by @SimonAB in https://github.com/darkreader/darkreader/issues/1684#issuecomment-549119626_

**Comment by alexanderby** [comment]
Hi, it should be fixed now in version 1.3.2 (though broken for High Sierra now).
