### ISSUE TITLE
[Feature Request] Apply dark image overlay which gets transparent upon hovering

### ISSUE THREAD

**Issue by ShogunExecutioner** [darkreader/darkreader#1707]
Thanks a lot for your work.

I once saw a stylish theme that was making a dim, semi-trasparent overlay which applys to all website images that goes full transparent when you hover over any image you'd like to see.

Could you please make this in a future update ?
Thanks again.

**Comment by akkk33** [comment]
Well, I've done that with adding these few lines in `Dev tool`:
```
img{
opacity: 0.3;
transition: 0.3s ease;
}
img:hover{
opacity: 1;
}
```

**Comment by Gusted** [comment]
Specific user case. Use Stylus btw ;)
