### ISSUE TITLE
Automatic toggle Dark/Light, NOT full extension

### ISSUE THREAD

**Issue by zsiegel92** [darkreader/darkreader#1713]
Hello,

I LOVE this extension. I am a graduate student and am on my computer 10+ hours per day. This is so helpful.

I rarely turn *off* the extension, but I very frequently toggle it from "Dark" to "Light" modes. Can you add a checkbox/radio element to the "Automation" controls that controls whether "Automation turns on/off extension" or "Automation toggles Dark/Light Mode"?

Thank you!!!

**Comment by katoquro** [comment]
Hello! It's already done but it's difficult to find))) 

see this post https://darkreader.org/blog/time-settings/

**Comment by zsiegel92** [comment]
Hi there,

I see that Automation can control whether the extension is on or off. I want a way to automate toggling whether the extension is in Dark/Light mode.

I never want the extension OFF, but I want it to automatically toggle Dark <-> Light.

This is because during the day I use this extension for a light Sepia filter in Light mode, and at night I have more aggressive blue-light reduction and color inversion.

**Comment by aokeelin** [comment]
I would also like to see an option for Automation to toggle between Dark and Light modes, rather than altogether turning off the extension during the daytime. 
Just like @zsiegel92 says, it would be Daytime -> Light mode, Nighttime -> Dark mode. Or vice versa.

**Comment by Gusted** [comment]
![](https://i.imgur.com/7cDu1kO.png) This maybe you want?

**Comment by aokeelin** [comment]
Since I can't see the context of your image, I can't say a definite yes or no. But if what you're showing me is a toggle between Light & Dark for Dark Reader (rather than turning the extension off), then that would be on the right track.
However, That still doesn't address the automation portion. It would be more helpful to be able to define what automation switches to at the sunrise and sunset triggers, with options such as Off, Light Theme, and Dark Theme. If it helps I made a very quick mockup to demonstrate what I'm looking for.
![automation_mockup1](https://user-images.githubusercontent.com/50714774/79371260-f24fbf80-7f08-11ea-9462-8ac1c43a2b91.png)
![automation_mockup2](https://user-images.githubusercontent.com/50714774/79371270-f4b21980-7f08-11ea-8c16-827444b45de4.png)

**Comment by Gusted** [comment]
Ah that way, New UI is coming will not be that hard to implement I think..

**Comment by harshil15999** [comment]
I donot have any dark mode on the system so I feel the part of depending on system settings should be optionally toggled

**Comment by harshil15999** [comment]
Hey @Gusted is this issue assigned to anyone?

**Comment by harshil15999** [comment]
Hey I was thinking of doing this and here is how i was thinking of appraching it 
- [ ] convert the mockup to html and css
- [ ]  find the part of code repsonsible for controlling the automation 
- [ ] create a variable to toggle the dark/light mode

**Comment by harshil15999** [comment]
> Since I can't see the context of your image, I can't say a definite yes or no. But if what you're showing me is a toggle between Light & Dark for Dark Reader (rather than turning the extension off), then that would be on the right track.
> However, That still doesn't address the automation portion. It would be more helpful to be able to define what automation switches to at the sunrise and sunset triggers, with options such as Off, Light Theme, and Dark Theme. If it helps I made a very quick mockup to demonstrate what I'm looking for.
> ![automation_mockup1](https://user-images.githubusercontent.com/50714774/79371260-f24fbf80-7f08-11ea-9462-8ac1c43a2b91.png)
> ![automation_mockup2](https://user-images.githubusercontent.com/50714774/79371270-f4b21980-7f08-11ea-8c16-827444b45de4.png)

In this I think it should be named **Use custom themes** instead of   **Use system color themes**

**Comment by Gusted** [comment]
> Hey @Gusted is this issue assigned to anyone?

Not really, #2860 should fix this issue, but a new redesign of the UI is coming so it's bit pointless for anyone including me to work on the UI atm. @alexanderby could enlighten this a bit by considering this new UI element into the new redesign. 

Regards,
Gusted
