### ISSUE TITLE
A few issues with www.deutschegrammophon.com/en/

### ISSUE THREAD

**Issue by AndyL964** [darkreader/darkreader#1718]
- The buttons and navigation bar text have contrast issues for the text.
- For track list overviews, clicking on a track will cause the colors of the site to invert.
![image](https://user-images.githubusercontent.com/22827982/68561925-69ce6f80-03fc-11ea-8710-f6da5802ccb5.png)
![image](https://user-images.githubusercontent.com/22827982/68561928-6d61f680-03fc-11ea-9bb1-2601eb1ab7b5.png)

**Comment by Gusted** [comment]
new layout
