### ISSUE TITLE
firefox - apz.allow_zooming causes settings dialog to not show

### ISSUE THREAD

**Issue by NickVanderPyle** [darkreader/darkreader#1719]
Setting `apz.allow_zooming` in [about:config](about:config) causes Dark Reader to show an empty dialog when the icon is clicked.

Browser: 71.0b8 (64-bit)
OS: MacOS 10.15.1

Tried reinstalling Dark Reader and restarting FireFox.

I could collect more info, but I'm uncertain how to go about doing that.

![darkreader](https://user-images.githubusercontent.com/96394/68605795-06375700-047b-11ea-9699-c45e797950fe.gif)

**Comment by NickVanderPyle** [comment]
This happens to all my extensions, not just Dark Reader. Icons that come with Firefox, such as profile and bookmarks menu, are unaffected and show as expected. Not sure this is an extension issue or a firefox issue.

**Comment by MentalGear** [comment]
Thank for noting this ! The same issue happened to me after activating mac mative zoom on Firefox. Even a restart of FF didn't make it show again.

**Comment by Gusted** [comment]
Browser bug
