### ISSUE TITLE
support.mozilla.org is not inverted properly

### ISSUE THREAD

**Issue by sshawarma** [darkreader/darkreader#1745]
[Mozilla Support](https://support.mozilla.org) is almost completely white. If you have any questions, feel free to ask me.

Thanks.

**Comment by asd-collab** [comment]
yep, it is on all filters.

I suspect the browser protects that page. just like all pages like `x.mozilla.org`, Firefox needs to fix this.

---

**Comment by Gusted** [comment]
Should be fixed.
