### ISSUE TITLE
filter+: full page is black on https://bugs.chromium.org/p/chromium/issues/list

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#1757]
other modes  show the webpage contents.

surprisingly, 'inspect element' can still be used and it leads to different elements.

----

latest Firefox stable
dark reader extension version 4.8.4
uBlock origin extension is also active.

---

asd-collab

**Comment by asd-collab** [comment]
aside:
though in Dynamic mode, the bar containing the search bar, is all white.


in Filter mode, most elements are converted to dark mode.

in Static mode, on the top bar, only the image and the search bar break dark theme.

---

asd-collab

**Comment by asd-collab** [comment]
also tested opening an issue page https://bugs.chromium.org/p/chromium/issues/detail?id=1026046&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

only mode I could use was **Filter** mode, all other modes suck(are white).

---

asd-collab

**Comment by ElhemEnohpi** [comment]
For me, Github pages (including this one) are completely black in Filter+ mode.

macOS 10.14.6, Firefox 72.0.2, Dark Reader 4.8.7
