### ISSUE TITLE
WashingtonPost.com logo

### ISSUE THREAD

**Issue by azuryst** [darkreader/darkreader#1761]
I have not been able to find how to style the small washingtonpost.com logo that trails at the top of the page when scrolling down the site. Part of the SVG gets inverted, while the other part remains unchanged (or maybe double-inverted?).

The site seems to use different id's/classes for the logo on different pages, even though the logo looks and acts the same on each page. The two selectors I have been able to find are #TWP_logo_svg and .db, and I have added the following rules in the Dynamic Theme Editor:

================================

washingtonpost.com

INVERT
svg.wplogo
#TWP_logo_svg
.db

================================

I am on Firefox 70.0.1 on macOS. You can reproduce the issue when scrolling down the main page.

![Screen Shot 2019-11-19 at 8 34 34 AM](https://user-images.githubusercontent.com/6332446/69166066-7b241580-0aa7-11ea-930f-fa36bf92785b.jpg)
![Screen Shot 2019-11-19 at 8 20 08 AM](https://user-images.githubusercontent.com/6332446/69165547-9e01fa00-0aa6-11ea-90b9-dd1df52813d8.jpg)

**Comment by yawnston** [comment]
I modified your code a little bit and this seems to look alright:

```
INVERT
svg#Layer_1

CSS
svg#TWP_logo_svg > path {
    fill: ${black }!important;
}
```

Was this what you were looking for?

**Comment by azuryst** [comment]
Yes, thank you! The only thing I needed to add was .db to INVERT. The site uses that selector for article pages, it seems, and the logo would appear black using your code on those pages. I now have this, and everything seems to be working fine:

```
INVERT
svg#Layer_1
.db

CSS
svg#TWP_logo_svg > path {
   fill: ${black }!important;
}
```

Thanks so much : )

**Comment by yawnston** [comment]
Make sure to open a PR with these changes so others can benefit from this as well 👍
