### ISSUE TITLE
Site loading in dark, reverts back to light after 2 seconds

### ISSUE THREAD

**Issue by MrWido** [darkreader/darkreader#1766]
A couple of sites do not work well with dark reader (my hosting dash and cpanel among them). They are set to dark in the settings, and whenever a page loads, it loads with the dark theme. But after about 2 or 3 seconds it goes light again. I check the settings, but the dark option is still selected even though the page is now light. If I switch the settings to light and back to dark, the page goes dark again, only to have the same issue on the next page load. 
Anybody else had this experience? 
(I'm using latest version Firefox. I disabled all the other addons and themes, but the issue persists)

**Comment by Gusted** [comment]
Example URL?

**Comment by Gusted** [comment]
Should be fixed.
