### ISSUE TITLE
Doesn't work on some page of reddit

### ISSUE THREAD

**Issue by vv7v7** [darkreader/darkreader#1767]
Dear Developers,

Somewhy an extension doesn't work on this [page](https://www.reddit.com/r/LineageOS/comments/5rarac/).

![](https://i.imgur.com/SVsvmil.png)

Thank you

**Comment by Gusted** [comment]
Dear @vv7v7 

Sorry for the late reactions, but could you please check with 4.9.9(Latest dark reader version) If this issue still persist?

**Comment by vv7v7** [comment]
> Sorry for the late reactions, but could you please check with 4.9.9(Latest dark reader version) If this issue still persist?

Works well on `4.9.9`! Thank you very much!
Although, found some another:
![](https://i.imgur.com/YN0XdW0.png)

**Comment by Gusted** [comment]
That's edxposed as a image and can't target the lower white 😬

**Comment by vv7v7** [comment]
> That's edxposed as a image and can't target the lower white 😬

Is it possible to lower these rates for some website?

**Comment by vv7v7** [comment]
Just some interesting thing that logo barely visible:
![](https://i.imgur.com/kAqeJQE.png)

**Comment by Gusted** [comment]
#2737 < Next update of Dark Reader fixes this.

**Comment by vv7v7** [comment]
> Next update of Dark Reader fixes this.

Roger that. Thank you very much! Be healthy! 😃

**Comment by Gusted** [comment]
You too!
