### ISSUE TITLE
The add-on breaks the pages on uhunt

### ISSUE THREAD

**Issue by merajmasuk** [darkreader/darkreader#1769]
```
OS: Microsoft Windows [Version 10.0.18363.476]
Browser: Firefox 70.0.1
```

Website: https://uhunt.onlinejudge.org/

**You need to reload the page each time toggling dark theme to see complete changes**

Before:

![image](https://user-images.githubusercontent.com/34513961/69435657-29f77880-0d6a-11ea-86db-faf8b2bb753c.png)

After:

![image](https://user-images.githubusercontent.com/34513961/69435784-6b882380-0d6a-11ea-8a3a-f7e21c091808.png)

**Comment by Gusted** [comment]
Fixed.
