### ISSUE TITLE
Editing gist in firefox doesnt work even when site is excluded 

### ISSUE THREAD

**Issue by majkinetor** [darkreader/darkreader#1782]
In Firefox 70 (but it happens since I use it from v60), when I edit gist I have empty screen where file content should be:

![image](https://user-images.githubusercontent.com/85767/69495303-ceda9880-0ec5-11ea-9250-88f1cd42cec6.png)

This is a gist content:

![image](https://user-images.githubusercontent.com/85767/69495316-f7fb2900-0ec5-11ea-8ae1-0b890b59a880.png)

I have to put it to 'Off' to make it work, if I dissable it via _Toggle current site_ option it still doesn't work.

**Comment by Gusted** [comment]
Hey their! 

Could you check with the latest Darkreadr version 4.9.4 If this issue still persist?

**Comment by majkinetor** [comment]
Looks like it works now. 
Thanks.

**Comment by Gusted** [comment]
Thank for reporting this issue!
Feel free to open more issues if you find some.
