### ISSUE TITLE
Delete multiple items from white/black list quickly?

### ISSUE THREAD

**Issue by ScottBeeson** [darkreader/darkreader#1784]
I've used DarkReader for a long time (Great work, btw).  I've accumulated quite a long "site list".  Most of them I'll probably never visit again. I'm wondering if there is a way to delete all (or many) of them at once? The main UI is not convenient for doing bulk operations.

**Comment by Gusted** [comment]
Hi!

It's now a TextArea instead of seperate items.
It should be easier to select mulitple sites at once and remove them.
![](https://i.imgur.com/sgAtP1x.png)

Regards,
Gusted
