### ISSUE TITLE
Shouldn't there be a way to make websites load faster on dynamic mode?

### ISSUE THREAD

**Issue by ars4l4n** [darkreader/darkreader#1800]
I've upgraded my i5 3570k to an i7 8700k and the differences in loading speed were only marginal
Recently, I've used someones css script(?) to load pages where they also did more than just a simple inversion and the pages loaded faster so I wondered why dynamic mode on this extension takes the pages so long to load

**Comment by yawnston** [comment]
Could you provide an example of some sites which are performing poorly for you?

**Comment by WebMechanic** [comment]
I suppose a handcrafted CSS tied to a specific site (type) will always be much faster than any external script/extension doing fancy analysis to parse every CSS rule and property to determine if a change is required and if so which one.
And some website load some pretty heavy stylesheets with thousands of superflous rules.

**Comment by Gusted** [comment]
#3120 Export the file and use it in static mode or something like Stylus.
