### ISSUE TITLE
darkreader how to work on view-source:

### ISSUE THREAD

**Issue by samshuai** [darkreader/darkreader#1803]
in view-source dont work.
pls support it. 
thx

**Comment by yawnston** [comment]
Seems like it's not possible to do this in Chrome currently according to [this StackOverflow answer](https://stackoverflow.com/questions/59219381/is-it-possible-to-run-content-scripts-from-a-chrome-extension-on-the-view-source).

**Comment by WebMechanic** [comment]
This probably won't work for the same reasons DM doesn't work in other "native" (built-in) browser pages like settings. The extension simply isn't loaded.

**Comment by KaKi87** [comment]
What about binding the *view source* keyboard shortcut to Dark Reader ?

**Comment by AlphaComposite** [comment]
For dark mode in view source mode, create a bookmark with this script as the link:

javascript:(function(){ var h=document.getElementsByTagName('head')[0],s=document.createElement('style');s.setAttribute('type','text/css'); s.appendChild(document.createTextNode('html{-webkit-filter:invert(100%) hue-rotate(180deg) contrast(70%) !important; background: #fff;} .line-content {background-color: #fefefe;}'));h.appendChild(s); })()

**Comment by Gusted** [comment]
> What about binding the _view source_ keyboard shortcut to Dark Reader ?

That will most likely give us a rejection into the chrome webstore as chrome:// and view-source: and related protected paged aren't allowed to be modified in any way(We can't read the DOM structure)





> For dark mode in view source mode, create a bookmark with this script as the link:
> 
> javascript:(function(){ var h=document.getElementsByTagName('head')[0],s=document.createElement('style');s.setAttribute('type','text/css'); s.appendChild(document.createTextNode('html{-webkit-filter:invert(100%) hue-rotate(180deg) contrast(70%) !important; background: #fff;} .line-content {background-color: #fefefe;}'));h.appendChild(s); })()

Good workaround!

**Comment by KaKi87** [comment]
Hey @Gusted, as you said, it is a workaround, not a solution. Therefore, the issue should stay open. Thanks

**Comment by Gusted** [comment]
Hey @KaKi87 it's also the solution as view-source: are protected page to read/write as extension and no real solution should be could make so long chromium wouldn't change it of the behavior with protected pages. Just like chrome webstore is also a protected page and we can't touch it as extension in no matter what, if we would provide an workaround in our extension I'm for 95% sure the extension will get a rejection wil the next update.

**Comment by KaKi87** [comment]
Why can a script run from a bookmark can be executed on _projected_ pages if extensions cannot ?

**Comment by Gusted** [comment]
As of extension can do a lot more harm to the browser, if you have problems with this please open a chromium issue with describing this as I've never made the call to add view-source: to the protected pages and why bookmarks can run them.

**Comment by AlphaComposite** [comment]
Why not create your own tab and push the source HTML there? You can name the tab, style the tab, etc. 

So you'd have your own "view source" button independent of the browser's view source button(s) that would initiate this.

**Comment by WebMechanic** [comment]
@AlphaComposite your nifty workaround could be **cross browser** and shortened into sth along
```js
javascript:(function(){ var d=document,h=d.documentElement,s=d.createElement("style");s.innerText="html{filter:invert(1) hue-rotate(180deg) contrast(.7)} html *{background-color:#fefefe}";h.appendChild(s); })()
```
(tripple click the code to select the whole line)

No need for: -webkit- prefix, !important, percentages (use decimals), style attribute, and using shortcuts like `d.documentElement` instead of `document.getElementsByTagName('head')[0]`

**Comment by AlphaComposite** [comment]
Thanks for the cleanup, @WebMechanic. I'm mostly a backend guy, so my client-side scripting isn't as strong as it could be.

**Comment by WebMechanic** [comment]
@AlphaComposite you're very welcome. 
I didn't even know one can style the view-source window or use DevTools on it :)

**Comment by KaKi87** [comment]
While both CSS codes works fine in `view-source:`, the result is different on Chrome Web Store :

@AlphaComposite's CSS | @WebMechanic's CSS
--- | ---
![2020-04-25 12_50_04-Chrome Web Store - Extensions and 11 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/21284089/80278041-7f59fc00-86f3-11ea-933d-a027a76961a8.png) | ![2020-04-25 12_50_33-Chrome Web Store - Extensions and 11 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/21284089/80278040-7ec16580-86f3-11ea-8793-aa3d31ec676e.png)

Here's my version :
```js
javascript:document.firstElementChild.appendChild(Object.assign(document.createElement('style'), { innerText: 'html { filter: invert(1) hue-rotate(180deg) contrast(.7) !important; background: #FFF; }' }))
```
Made with the best of both, with only one instruction (no function declaration nor semicolons), but with more spaces (better readability), and with the same length as the second.

**Comment by WebMechanic** [comment]
well, it was **supposed** to be used in viewsource only for _that's the subject of this post_ right? **not** Chrome Store which uses a buttload of CSS that naturally has a higher specificity. It likely fails on a gazillion other public websites for the same reason.
That's why `html * {}` was sufficient, and the lack of !important.

Doesn't Chrome Store has a built in dark mode by now?

**Comment by KaKi87** [comment]
> well, it was **supposed** to be used in viewsource only for _that's the subject of this post_ right? 

Yes, but I did also made tests on Chrome Web Store because @Gusted talked about it too, and it gives interesting results.

> Doesn't Chrome Store has a built in dark mode by now?

It does, but there's no blacklist feature, so it is incompatible with already dark websites and renders badly in general.

**Comment by Gusted** [comment]
> Why not create your own tab and push the source HTML there? You can name the tab, style the tab, etc.
> 
> So you'd have your own "view source" button independent of the browser's view source button(s) that would initiate this. You could call the button "View Dark Reader Source" to alleviate any confusion and sticky areas around the Chrome webstore restrictions. You're technically not touching the Chrome "view source" with this approach.
> 
> Please see my comment here, @Gusted.

Bypassing protected pages is any way illegal to be uploaded to the chrome webstore and would be rejected.

> Yes, but I did also made tests on Chrome Web Store because @Gusted talked about it too, and it gives interesting results.

Their are multiple sites that has been protected by chrome, an good global script for them all is a good workaround and it gives intresting results.

**Comment by WebMechanic** [comment]
I guess @Gusted mentioned the Chrome Store simply as a well-known example of a protected website extensions are not allowed to touch or run on _for security and privacy reasons_. Just like Firefox extensions do not run on Mozilla's Add-on site or any of its many `about:` pages. Those pages and the limitatioins exposed on them by browser verndors have nothing to do with the original issue of darking view-source - incidently a proteced internal page.

Hence there's no need for a blacklist either, if the only intended target of this workaround is view-source and has always been. @AlphaComposite's `filter:invert(1) hue-rotate(180deg)` basically deals with browser's typical light style of that very internal page.
If you don't like to click a bookmarlet you can still resort to buil-in and usually superior DevTools that provide a live view of the markup and DOM unlike the static output of view-source.

The APIs available to and used by extensions are intentionally different from the API "used" by a user created bookmarklet - different scopes, grants, features. And bookmarklet don't have access to APIs available to extensions.
So it's technically very, very unlikely to get the "global solution" you're aiming for.
Sometimes life just sucks.

**Comment by Gusted** [comment]
I was talking about a good style that is in your bookmark that works fine with the most popular protected pages.
