### ISSUE TITLE
Firefox requires toggle on some pages as in Chrome everything works

### ISSUE THREAD

**Issue by Racle** [darkreader/darkreader#1806]
Dark reader doesnt work on firefox unless I toggle dark mode. On chrome I've had zero issues.
This is huge block as I'm heavy dark reader user (I use that even on my phone with Kiwi Browser). Current state on firefox is unusable for me..

Tested on
OS: Windows 10 / Pop!_os 18.04/19.04/19.10 (basically ubuntu)
Firefox: Developer edition (72.0b1) AND "stock" 71.0
Chrome: latest

Example sites: https://bridges.torproject.org/ and https://status.im/research/ 
(+ site what I develop what I cannot mention here)

And status.im seems to be randomly working when toggling dark mode.

Left side: `Firefox`. Right side: `Chrome` (both browsers have dark reader enabled)
![image](https://user-images.githubusercontent.com/759091/70061820-a3565d00-15ed-11ea-8b6f-faf6ce670e9d.png)
![image](https://user-images.githubusercontent.com/759091/70061849-ad785b80-15ed-11ea-9a5a-e9134185c4bf.png)

**Comment by pexxie** [comment]
I sort of found a "risky" work-around for this after checking the console and doing some Googling.

1. Go to "about:config"
2. Search "security.csp.enable"
3. Set it to false
4. Restart browser

Hope it works for you. Works for me. Win7 SP1 64bit, Firefox v72.0.1, Dark Reader v4.8.7.

**Comment by Racle** [comment]
> I sort of found a "risky" work-around for this after checking the console and doing some Googling.
> 
> 1. Go to "about:config"
> 2. Search "security.csp.enable"
> 3. Set it to false
> 4. Restart browser
> 
> Hope it works for you. Works for me. Win7 SP1 64bit, Firefox v72.0.1, Dark Reader v4.8.7.

Tested, works on those sites.

But web app what I develop (and cannot share link) still has the issue :/

One public site I found is https://www.investing.com/ which is still borken even with that fix. Site works perfectly on chrome.

**Comment by pexxie** [comment]
Yeah, I realized that soon after. Sorry for the false hope. I was also disappointed to see it was a niche fix. I was using "Dark Background and Light Text" before Dark Reader came to Firefox. It looks like I might have to go back to it. It's not as good but at least things stay dark.

**Comment by SuperSandro2000** [comment]
Disabling CSP is a really bad advice and a potential security risk. I would rather burn my eyes than globally disabling CSP everywhere.

**Comment by Gusted** [comment]
Hey their I just tested with
Firefox Nightly 77.0a1 (2020-04-15) (64-bit) 
Darkreader 4.9.4
This issue with both sites. It's seems I can't reproduce it anymore can you check if you still persist this issue or else otherwise close this isse?

Regards,
Gusted

**Comment by Racle** [comment]
Hey,
those are fixed.

Site what I'm developing still shows issues on initial load, even when changing views. Too bad I cannot show this, as there is no public access to this.

On chome everything works just fine.

After toggling everything works just fine even when changing views (they change dynamically as it's made with React)

**Comment by Gusted** [comment]
Hmm aka It display incorrect darkened display on inital load but when retoggling it works fine. 
Hmm React Seems like a new maybe problem starter as I don't cant find any logical reasons but if sites are made with React their could be built something on top of it to work again. But Speculation.

But as the retoggling is the issue solver #2065 and the incorrect content. Please post their some details of the private site without giving any private information away like the dynamic loading I've already taught of that but React Isn't a langauge I can write or know. So if you can post details of how that sites load and wich version of firefox you use etc. Thank you

As the public sites are fixed I need to close this issue.

Regards,
Gusted
