### ISSUE TITLE
Slow switching between new loaded tabs

### ISSUE THREAD

**Issue by lluke777** [darkreader/darkreader#1809]
Great plugin, but:
There is problem with delay at new website that was just loaded to new tab.
Reproduce:
1. Go to any any websie with lot of content: ex: amazon.com
2. Open 3 links with right mouse clik-> " Open link in new tab"
3. Wait till 3 websites are fully loaded.
4. Switch tabs: CTRL+TAB.
5. Observe that there is like 2sec delay between switching.

There is no this effect with Extension disabled. Also this effect is not visible with similar plugin like Lunar Reader.

Tested with uptodate few Chrome based browsers.
Windows 10 64bit 1903

**Comment by Gusted** [comment]
It's recalculating style's you enter it again. It's necessary for some website that needs this to re-render the styles when entering the site again.
