### ISSUE TITLE
firefox for android doesn't detect osdark mode

### ISSUE THREAD

**Issue by Yajo** [darkreader/darkreader#1810]
I use the extension for android firefox. I Configured it automatic with system colors. However, when I switch system to night mode, the extension remains switched off... 😪

**Comment by slanglade** [comment]
Same here, on a Samsung s8 (latest OTA OS version) with latest Firefox. I even tried to give all available permissions to the browser, to no avail.

Sounds like the extension can't read the "night mode" status of my Samsung.

Tell me if you want me to do some additional testing of this.

**Comment by Gusted** [comment]
#2280
