### ISSUE TITLE
Auto switch doesn't automatically work in Firefox on macOS

### ISSUE THREAD

**Issue by Yoshi2889** [darkreader/darkreader#1816]
Changing the macOS theme to dark, for instance in the system settings, doesn't enable Dark Reader automatically if the respective setting is enabled.

To reproduce:
1. Set Dark Reader to use the system color scheme.
2. Open Firefox and load a website.
3. Change the theme to dark in macOS's system settings.
4. Observe that the Firefox theme did change, but Dark Reader did not toggle.

EDIT: I thought restarting Firefox had an effect on this issue, turns out it does not. Updated the issue to reflect this.

**Comment by jackbravo** [comment]
@Yoshi2889 seems like this does work, is just not easy to find. Check #2247 .

![Screen Shot 2020-05-07 at 22 11 29](https://user-images.githubusercontent.com/15214/81366233-c2cb4780-90af-11ea-9137-498b337e7838.png)

**Comment by Yoshi2889** [comment]
That’s the setting I mean with step 1. This bug report revolves around this setting. Thanks though :)

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/81411458-ab896a00-9142-11ea-9452-3d8940967076.png)

The new UI will also contain a better button for this and a better visibility for the automation settings.
