### ISSUE TITLE
Some retouchings for next updates

### ISSUE THREAD

**Issue by xzj8b3** [darkreader/darkreader#1817]
Istagram Web you see only post title but the rest almost can not read should be replaced font color

Chrome 

the color of the link selection in the address bar should be a bit revised because when you select to copy links to an article in a group it is difficult to distinguish if you have selected the whole link!!!!

For the rest wonderful extension we thank you very much!!!!

**Comment by Gusted** [comment]
1. Fon't color isn't a thing.
2. We can't touch that we are just a simple extension and you should look into userChrome.css
