### ISSUE TITLE
website keeps swiching back to normal after comeing in dark at frst. 

### ISSUE THREAD

**Issue by reflexwolf** [darkreader/darkreader#1820]
when I first load this page http://www.isfdb.org/cgi-bin/index.cgi it comes in as dark, it will some times some times not switch to dark mode then switch right back or stay its very confusing for me, and I'm using this page quite a lot at the moment. 

any help or fixes that I missed for this would go a long way! 
also thank you for your great and wonderful add-on it makes my eyes happy!

**Comment by Gusted** [comment]
Fixed.
