### ISSUE TITLE
Image made bright when dark mode is on

### ISSUE THREAD

**Issue by itrombley** [darkreader/darkreader#1831]
This is what https://code.visualstudio.com looks like when Dark Reader is turned off:

![Screenshot from 2019-12-13 10-12-27](https://user-images.githubusercontent.com/23219827/70821837-f0c28f00-1d90-11ea-8dde-39ff9726daac.png)

Here's what it looks like when Dark Reader is on:

![Screenshot from 2019-12-13 10-12-32](https://user-images.githubusercontent.com/23219827/70821845-f4eeac80-1d90-11ea-8f6b-a9bba3c346e3.png)

I suggest examining the average brightness of an image and then decide if altering it is appropriate.

**Comment by Gusted** [comment]
Fixed.
