### ISSUE TITLE
Not sure if this is an "issue" but someone told me that you can enable "dark mode" in firefox without installing this extension. Is this true?

### ISSUE THREAD

**Issue by junkwes** [darkreader/darkreader#1832]

**Comment by junkwes** [comment]
There is a brief time during which you can see a white "flash" upon loading a website, which i am trying to avoid.

**Comment by brazenvoid** [comment]
Try installing a new tab plugin which displays an image in it. 

The white flash is a technical limitation as an empty window is white when it is first drawn. One can change the color to something else globally by changing browser style profile. But it then interferes with sites that utilize that as the default value for background color. So its best that you replace the new tab with a plugin which then draws a picture instead (black otherwise).

**Comment by ElhemEnohpi** [comment]
No, it's not true. There are dark themes for the browser theme, elements and controls, but there is no built-in "dark mode" that will change the content of websites you visit.

There are other extensions like Stylus that can change websites' look with CSS, or you can put your own CSS into userContent.css.

There are several different things that can cause a "white flash", and how bad it is can depend on your browser and in part on the speed of your computer. You can search other issues here, or the web, to find various methods to try to reduce it, like changing the colour of a blank tab in userContent.css:
```
@-moz-document url("about:blank") {html {background-color: #202223;}}
```
And/or setting a default browser background colour in userChrome.css:
```
browser { background-color: #202223 !important; }
```
etc.

On some systems, some pages (often Google) will render in their normal colours with a short delay before switching to dark. I haven't found any solution to that. In my experience it's not possible to get rid of all white flashes completely, but yours may differ.

**Comment by WebMechanic** [comment]
The "dark mode" in firefox only applies to the browser window not to website contents. Ther's a separate dark mode for its dev tools.

You can either edit `userContent.css` as you noted and spent your life hacking every possible site's CSS variation individually and restart the browser every time to test the result or simply install this browser extension.

Many modern sites and web-apps use CSS frameworks or JS applied styling that use pretty harsh specificity rules that are hard to override even in `userContent.css`.

**Comment by Gusted** [comment]
Uhm why asking here?
