### ISSUE TITLE
Formulae on Stack Exchange sites are rendered black on black.

### ISSUE THREAD

**Issue by kindaro** [darkreader/darkreader#1834]
See for example [math.stackexchange.com](https://math.stackexchange.com). I also attach a picture.

![math-black](https://user-images.githubusercontent.com/2599460/70925235-f4c60980-203b-11ea-8ab9-8e012f246957.png)

**Comment by WebMechanic** [comment]
This display depends on their Math renderer. The default is using a very intrusive JS library.

Right click a formular ans select "Math Settings `>`Math Renderer `>` "MathML" or "SVG" and dark mode will work. The setting is stored in your browser so it should work if you revisit the site.

**Comment by kindaro** [comment]
Awesome, thanks!
