### ISSUE TITLE
[Question] Config syncing

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#1838]
Hello,

> ~~Please note, that merged changes to these files are automatically delivered to all users **within 15 minutes**.~~
Config syncing was disabled, cause the GitHub team doesn't allow using GitHub as a CDN. Storing these files and making requests to other resources will be expensive and look suspicious.

How does it work now then ? Is it required for you to publish a new version of the plugin to update the list ?

I'm not particularly interested in speeding it up for my personal needs, however I created this issue to tell you that there's a solution for that if it isn't convenient enough for you : [RawGit](https://raw.githack.com/)

**Comment by stevennyman** [comment]
There’s also https://fast.io, which also works with GitHub and may be more suited to the amount of traffic.

**Comment by KaKi87** [comment]
Well, in that case there's also jsDelivr, which is FOSS.

**Comment by rxliuli** [comment]
Is there any progress on this issue?

**Comment by alexanderby** [comment]
Previously the RawGit was used, but the amount of traffic was several TB/month.

Currently the config is distributed with the app. It also prevents different compatibility issues. The only problem is long Chrome Web Store review time. I will try to persuade the team to review Dark Reader faster.

**Comment by KaKi87** [comment]
What about hosting it on another git server ? For instance, I have my own.

**Comment by sigewuzhere** [comment]
Not sure if it helps, but I have a project aimed to serve config files via CDN.
https://configcat.com
You can create a config file on a UI and your applications can pull the new values repeatedly.

**Comment by theg00s3** [comment]
jsDeliver works well. For example [this link](https://cdn.jsdelivr.net/gh/darkreader/darkreader@master/src/config/dynamic-theme-fixes.config) will serve the latest copy of dynamic-theme-fixes.config, and similarly [this link](https://cdn.jsdelivr.net/gh/darkreader/darkreader@master/src/config/inversion-fixes.config) will serve the latest copy of inversion-fixes.config . The best part is that jsDeliver is 100% free for everyone

**Comment by Gusted** [comment]
If you all know darkreader have in combination from chromium 2.5-2.8m? and firefox 500k from which 95+ % is active daily that's a huge amount to server. If we would do this we would need a reliable services and probably paid as of the huge amount of traffic that would come.

**Comment by theg00s3** [comment]
jsDeliver is sponsored by Cloudflare and fastly, so it'll definitely be able to handle darkreader's traffic

**Comment by lewisje** [comment]
> Previously the RawGit was used, but the amount of traffic was several TB/month.
> 
> Currently the config is distributed with the app. It also prevents different compatibility issues. The only problem is long Chrome Web Store review time. I will try to persuade the team to review Dark Reader faster.

I was about to recommend [gitcdn.xyz](http://gitcdn.xyz/) because I know at least that Nano Adblocker uses it.

**Comment by Pwnulatr** [comment]
It is also possible to use Github Pages as a CDN. It's literally a 2 click process to create a generated page utilizing master branch.

**Comment by Gusted** [comment]
Well it's hard as let's make this a theoritical question.

We have around 3 million active users(Private numbers trough Extension dashboard).
And for sakes just let use the dynamic theme fixes and not even the other fixes as well to make this a simple answer.
Currently at writing the fully dynamic theme fixes is 112Kb so multiple it by 3 million.
 You got 336000000kb Convert it to a Gb and you got 336 GB. So imagine we let it sync it every 24 hours(That also means every second aprox 35 users syncs it config with a server) This means in a `normal` month(31 days) a server needs to server 10.416TB of data. Not sure if services can handle this/allow this on a bandwith limit/Don't think it's a DDOS as theoritical every second a users is requesting the data from the server.

Imagine this and than think about a good solution for this issue.

**Comment by theg00s3** [comment]
Again, jsDelivr can and does handle larger traffic loads for free

**Comment by Gusted** [comment]
I will have a discussion with the owner about the avaible options and will report back.

**Comment by Gusted** [comment]
```
CEO - Alexander Today at 18:50
I think we can add an option to auto-update config from remote source for some users (I guess it's 1/10000 who wants this) when the user clicks a button or starts the extension or once a day. Because syncing the config for 2000000 users is an overkill, the large bandwidth and will cost too much, and requires some time to manage yet another server, and privacy evangelists will not like remote requests, and also there can be an error due to incompatible config for different app versions.

So, I think it can be just stored on GitHub, if more than 100 users will enable this feature and the GitHub team will complain, we can start thinking about another solution.
```
I will open up a PR to enable a sync now feature to click on a button and sync with the latest config.
