### ISSUE TITLE
color: initial not inverting

### ISSUE THREAD

**Issue by lbischof** [darkreader/darkreader#1841]
The following test page does not work correctly. The text stays black and doesn't invert.
```
<html>
    <p>test</p>
</html>

<style>
    p {
        color: initial;
    }
</style>
```

**Comment by WebMechanic** [comment]
I'm afraid that's not how `initial` works.

Check https://developer.mozilla.org/en-US/docs/Web/CSS/initial
and https://drafts.csswg.org/css-cascade-3/#initial-value

The "property’s definition table" mentioned at csswg.org refers to the value any CSS property has "built in" according to its specification, ,i.e. the _initial value_ for the `display` property is "inline", even for `<p>` 'cos that's what the spec for `display` dictates.

The browser's own default styles for _HTML documents_ then overrides this property value to become `display:block` - 'cos that's what the _HTML5 spec_ tels us a `<p>` should look like. 
CSS is used by and suitable for many other document types than just HTML that have very different styling requirements for their default elements.

So "initial" is not what styles have been applied "initially" by the ua/author/website stylesheet.

The keyword is misleading and I fell for the same trap.

**Comment by Gusted** [comment]
This was intended.
