### ISSUE TITLE
[Feature request] Change theme based on firefox theme

### ISSUE THREAD

**Issue by igoro00** [darkreader/darkreader#1845]
I've got two little scripts that changes wallpaper and gnome theme from light to dark and vice versa. Lucky enough Firefox respects that gnome theme and automatically changes its own ui. However darkreader(the most important piece of the "dark mode puzzle") does not do that. It would be awesome if darkreader could automatically change its theme based on Firefox theme/Gnome theme. Or even if it would be possible to change darkreader theme using some command from terminal.

Is it doable? Or even possible at all? Thanks in advance!

**Comment by xmha97** [comment]
It's not posable, not you can use this option.
Change theme based on System theme
![image](https://user-images.githubusercontent.com/23485114/86028513-343bcc80-ba47-11ea-8db0-fe9a83b581aa.png)

**Comment by Gusted** [comment]
Not possible we have another issue tracking for command line
