### ISSUE TITLE
Dynamic mode inverts thumbnails in Gmail search bar

### ISSUE THREAD

**Issue by devanshuDesai** [darkreader/darkreader#1855]
<img width="658" alt="Screen Shot 2019-12-23 at 11 42 53 AM" src="https://user-images.githubusercontent.com/37163544/71377585-16624c00-257a-11ea-9f65-11ae6d39e5bb.png">

**Comment by Gusted** [comment]
Hey could you check with the latest version of darkreader if this issue still persist?

**Comment by devanshuDesai** [comment]
Are you referring to version 4.9.2?

**Comment by Gusted** [comment]
4.9.4 actually

**Comment by devanshuDesai** [comment]
yes I can confirm it is fixed now
