### ISSUE TITLE
Dark reader has trouble in dynamic mode with slow/throttled internet

### ISSUE THREAD

**Issue by kkoomen** [darkreader/darkreader#1865]
Somtimes it takes a bit for a page to load for me and the page gets dark but not everything gets dark and I have to turn Dark Reader off and on. I think the thing here is caching, since it seems to work better if the page is already visited once and thus received from the cache.

This has happened to me on multiple websites, but I stumbled upon a Wikipedia article and decided to create the issue from here as I always have it with articles on Wikipedia that I haven't visited yet.

Initial load (this was a page I never visited)
![Screenshot_2019-12-31 Robust statistics - Wikipedia](https://user-images.githubusercontent.com/10693490/71622579-a6a32f80-2c11-11ea-9b99-03de7c88befa.png)

After turning Dark Reader off and on
![Screenshot_2019-12-31 Robust statistics - Wikipedia(1)](https://user-images.githubusercontent.com/10693490/71622584-ad31a700-2c11-11ea-887e-82deb2b508f2.png)

**Comment by Gusted** [comment]
Could you share the link it also seems like it just target Math images. It has been fixed in that latest version of Dark Reader

**Comment by kkoomen** [comment]
The link is: https://en.wikipedia.org/wiki/Robust_statistics#Empirical_influence_function although as you mentioned it seems to be fixed. I'll close this and re-open it whenever it happens again.
