### ISSUE TITLE
[Suggestion] Adjusting font size

### ISSUE THREAD

**Issue by Archilyte** [darkreader/darkreader#1868]
Since there is a way to change font styles, it would be cool to adjust their overall sizes as well, because some fonts are scaled too big

Here's a comparison

Normal font google:
![normal google](https://user-images.githubusercontent.com/39607601/71702696-ef3c2380-2d9e-11ea-9342-521dfd373e67.png)

When I change the font to [Minecraftia](https://www.dafont.com/minecraftia.font):
![Changed google](https://user-images.githubusercontent.com/39607601/71702806-6d002f00-2d9f-11ea-8219-8449dd845576.png)

**Comment by Archilyte** [comment]
Also note that this issue depends on websites, as the font scaling works perfectly on some websites like Google Translate.

**Comment by WebMechanic** [comment]
might also heavily depend on the actual quality (metrics) of the replacement font is use.

**Comment by ptoump** [comment]
Very much needed in **Firefox for android**, where in tablets font scaling sucks..

**Comment by forivall** [comment]
font weight adjustment also could be included.

**Comment by designercreativo** [comment]
yes I tried here on github to modify the p indicating a different font-size, with inspection element it works, with the editor it seems to me not.

```
================================

01net.com

CSS
html, body {
    color: ${#090702} !important;
font-size: 50px !important;
}

================================
```

**Comment by Archilyte** [comment]
so ill have to inspect element it everytime i click something on github or reload the page?

**Comment by Gusted** [comment]
You can paste it in the devtools or make a custom CSS with something like [stylus](https://github.com/openstyles/stylus)

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/3066#discussion_r458785239
