### ISSUE TITLE
Suggestion: Disable for "content" in Google Docs

### ISSUE THREAD

**Issue by NielsPT** [darkreader/darkreader#1869]
When using dark reader in Google Docs, the menus and background are dark as expected, but it would be an awesome addition if it was possible to have the actual document not being affected, just like when viewing PDFs. This way, you can as a user actually see what the document looks like when printet or exported in any way, and the issues #1515 and #1320 would be fixed by the change. 
I know that this is quite specific for one page, and I don't know how to generalise it (an option to disable for specific elements on a page maybe?), but it would still make a huge difference for me, and probably others.
See image below for an example:
![Google_docs_idea](https://user-images.githubusercontent.com/44494681/71719496-d7a47f80-2e1e-11ea-989a-025cffc0c8fa.png)

**Comment by Kurtoid** [comment]
It's do-able if you use the Dev Tools button. Search for the docs.google.com entry and add the line
`.kix-page-content-wrapper`
or
`.kix-page`

**Comment by NielsPT** [comment]
That is great, except I'm using Safari and there is no dev-tools button in the Safari version...

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by Gusted** [comment]
Any example page for this behavior. Also safari is a other code source, as this shouldn't be happening on Chrome and Firefox.

**Comment by KaKi87** [comment]
Well, I'm actually interested in a global implementation, not a local one ^^

**Comment by Gusted** [comment]
Huh a global one would be to extra the generated CSS and than simply remove the CS that darkens the content one. As we prefer not to make anything in code specific to site wide also global one wouldn't be possible due to what's content yeah I guess for docs it's the document itself but what's for Google or Facebook and how to detect it.

**Comment by KaKi87** [comment]
What ? I'm only talking about Google Docs here.

**Comment by Gusted** [comment]
Ah that you meant with global. Anyway in my previous comment their is a way to do it. As we don't make any site specific code, I will close this issue.

**Comment by KaKi87** [comment]
What about [those fixes](https://github.com/darkreader/darkreader/commits/master/src/config/fix_inversion.json) ? Why wouldn't it possible to make one like those but for Google Docs, to not invert document content ?

**Comment by Gusted** [comment]
You can make one for yourself but the general idea of Invert is still to get a dark mode effect.

**Comment by KaKi87** [comment]
I see, but editing a document with inverted colors can be a problem when sharing the said document with other users not using Dark Reader or exporting the document in PDF/etc.

**Comment by KaKi87** [comment]
Also, since it is actually possible to set a document background to dark for everyone, doing so while Dark Reader is active will actually make it white.

**Comment by Gusted** [comment]
If you need to share your document than just disable dark reader. Or don't use colors, I never had a problem with sharing my documents while I made them with dark reader active.

**Comment by KaKi87** [comment]
> If you need to share your document than just disable dark reader

That's not an answer.

> Or don't use colors

That's not an answer either.

**Comment by Gusted** [comment]
The answer is, just remove the Selector personal. But we are not adding a option for this in our UI.

**Comment by KaKi87** [comment]
I was not talking about an option but just a definitive fix for it

**Comment by Gusted** [comment]
> just remove the Selector

I saw the Selector was already shared here. So a simple remove of it in dev tools and click apply should do the job.

**Comment by KaKi87** [comment]
Yes but again that's local.

**Comment by Gusted** [comment]
Yes because some people want have it inverted and some not. It's rather easier than removing it than adding it.

**Comment by NielsPT** [comment]
I don't mide suing the dev-tools, except I can't in the browser I'm using. How about just enablinging dev tools in Safari? It seems strange to me that since I've payed for this extension, I'm getting less functionality than people who download it for free. The fix using dev-tools works fine-ish in Firefox. Only fine-ish since the colors in the printet pdf is not exactly the same as in the browser, just a lot closer.

**Comment by Gusted** [comment]
I hope safari will get a port to webextension for the newer version of safari but I'm not on that development.

**Comment by KaKi87** [comment]
So I can't find any `.kix-page` or `.kix-page-content-wrapper` element on the page but it seems that the right selector is `#docs-editor-container`

**Comment by KaKi87** [comment]
So I'm trying to add
```
NO INVERT
#docs-editor-container
```
But, after clicking *Apply*, the added lines disappear ?

**Comment by Gusted** [comment]
> So I'm trying to add
> 
> ```
> NO INVERT
> #docs-editor-container
> ```
> 
> But, after clicking _Apply_, the added lines disappear ?

You made sure you on invert mode?

**Comment by KaKi87** [comment]
I wasn't, because I thought I could edit the configuration before enabling it, thus saving me the dazzling.
So I've just tried enabling before then editing the configuration but it the outcome was the same.

**Comment by Gusted** [comment]
Try to go to another mode and than back to Filter mode and try again.

**Comment by BillCipher345** [comment]
um idk if its still relevant but i searched for a fix for some time now, and i figured out adding the lines
`.kix-page-paginated`
in Dev Tools to the INVERT section fixes it for me. I hope it helps somebody
