### ISSUE TITLE
MMB New Tabs not opening

### ISSUE THREAD

**Issue by Liipski** [darkreader/darkreader#1874]
Issue Type: <b>Bug</b>

While Dark Reader is turned on, after middle mouse button click on the links to open them in new tabs, they do nothing. Like the add-on was overlaying them. 

After switching Dark Reader off Alt+Shift+D things went back to normal and I'm able to open links this way again.

Sometimes they do work but i have to spam my middle mouse button to get them to react.

Firefox version I'm using: 71.0 64 bit
Extinsions I'm using:
![obraz](https://user-images.githubusercontent.com/23154359/71765258-92ea1880-2ef2-11ea-9557-5be62a264a6a.png)
<details><summary>Extinsions Links</summary>

**Duck Duck Go**
https://addons.mozilla.org/pl/firefox/addon/duckduckgo-for-firefox/
https://duckduckgo.com/app

**Facebook Container**
[https://github.com/mozilla/contain-facebook](url)
[https://addons.mozilla.org/pl/firefox/addon/facebook-container/](url)

**Simple Translate**
[https://addons.mozilla.org/en-US/firefox/addon/simple-translate/](url)

**uBlock Origin**
[https://github.com/gorhill/uBlock#ublock-origin](url)
[https://addons.mozilla.org/pl/firefox/addon/ublock-origin/](url)

</details>

**Comment by Gusted** [comment]
Fixed
