### ISSUE TITLE
Stackexchange formulas not handled properly

### ISSUE THREAD

**Issue by JackBluff** [darkreader/darkreader#1878]
Firefox 71.0
Manjaro Linux

Formulas on Stackexchange are totally darked, see screenshots attached.

<img width="456" alt="dark" src="https://user-images.githubusercontent.com/42998751/71781600-efbc0080-2fd0-11ea-8ee4-34cebf03c152.png">
<img width="456" alt="light" src="https://user-images.githubusercontent.com/42998751/71781601-f0549700-2fd0-11ea-8d13-c3bc86591125.png">

<img width="560" alt="on" src="https://user-images.githubusercontent.com/42998751/71781631-445f7b80-2fd1-11ea-85aa-4571b45e4993.png">
<img width="560" alt="off" src="https://user-images.githubusercontent.com/42998751/71781641-504b3d80-2fd1-11ea-9973-545359d68203.png">

**Comment by Kurtoid** [comment]
Huh, for some reason, undoing ceb808346bc558c31e894d37136b02fa3c5dc2b0 fixes it

**Comment by gabsens** [comment]
I can confirm what Kurtoid wrote.

**Comment by Gusted** [comment]
![](https://i.imgur.com/JLtLqVh.png)
