### ISSUE TITLE
Toggle Current Site is not working, only Toggle extension

### ISSUE THREAD

**Issue by sebastin25** [darkreader/darkreader#1881]
Website for testing: https://www.webnovel.com/

"Toggle current site" is not working at all, only for to enable or enable the dark mode is with "toggle extension", until now is the only website in which i have this problem. Also, sometimes you can only disable or enable dark mode after a lot of tries and reload.

Web Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
OS Windows 10 Home

**Comment by amanhigh** [comment]
I have same issue on investing.com. I am using firefox browser.

**Comment by Gusted** [comment]
Should be fixed.
