### ISSUE TITLE
Inspector not inverting colors in FF71

### ISSUE THREAD

**Issue by flxai** [darkreader/darkreader#1883]
I'm using Firefox 71 and when opening the inspector or another one of the developer tools by pressing <kbd>F12</kbd> the window is still white. I could not find anything about it in the [help](https://darkreader.org/help/en/) or in the [issues](https://github.com/darkreader/darkreader/issues?utf8=%E2%9C%93&q=inspector).

Can the inspector be set to use dark mode in any way?

Sorry if this is the wrong channel. I am very happy with Dark Reader, so thanks everybody!

**Comment by WebMechanic** [comment]
in Firefox with the dev tools / inspector open **press F11**. 
The Dark mode setting is right there in the middle of the DevTools settings page.
https://developer.mozilla.org/en-US/docs/Tools/Settings

In Chrome DevTools **press F1**.

**Comment by flxai** [comment]
Thank you @WebMechanic. This solves my issue. I think you meant to type **F1** for Firefox.

**Comment by WebMechanic** [comment]
ya, that was a typo, sorry.
Always at your service!
