### ISSUE TITLE
Feature request: invert the browser devtools

### ISSUE THREAD

**Issue by davenquinn** [darkreader/darkreader#1892]
At least for Firefox and Chrome, there is now a dark theme for the Dev Tools/Web Inspector. However, the setting used to enable these is buried in the Dev Tools settings. It'd be nice to sync this preference with the Dark Reader mode if possible, so that the dark theme could be enabled when the page is also dark.

**Comment by WebMechanic** [comment]
> buried in the Dev Tools settings
**Seriously?**
It's a simple, set and forget setting that **literaly takes TWO clicks** to enable/disable.
How often do you switch dark theme for the Dev Tools/Web Inspector anyway?

**Comment by davenquinn** [comment]
I switch from dark to light theme in OS X daily depending on the time of day.

Dark Reader makes it easy to follow this global setting in my browser, but the Dev Tools is not included in that. It isn't difficult to set, certainly, but it is a separate setting that has to be toggled – I would imagine most users of both the Dev Tools and Dark Reader would like the option to keep it synced with the page appearance.

**Comment by WebMechanic** [comment]
ok. I was really wondering :))

well, I don't fall under the "most users" category then :=)
I don't mind to occasionally look at light websites, **but coding** on a light background hurts my eyes any time of the day. All coding tools (editors, IDE, devtools, whatnot) or image editors are configured to permanently use whatever dark mode (e.g Darcula) they support.

It's still not "buried away". 
Inside DevTools:
 - Firefox: F11 
 - Chrome: F1 {*}
then click to switch theme.

Cheers

{*} possible Opera and Edgium, too

**Comment by Gusted** [comment]
No. Not possible
