### ISSUE TITLE
Colors are not good for https://app.grammarly.com/ correction highlights

### ISSUE THREAD

**Issue by Orionsg** [darkreader/darkreader#1901]
The base and initial view in the Grammarly web app is all fine. However, when one starts to check text and Grammarly points out corrections, these are shown in highlighted text, which Darkreader does not convert well. The background is white and the letters of the word to be corrected are in a very light grey and therefore almost not readable.

**Comment by Gusted** [comment]
Hello their! 

I just want to inform you that this has been fixed with the lasted version of Darkreader If their are more. I would be happy to hear!

**Comment by Orionsg** [comment]
Thanks, I just checked it and the highlights are now fully readable!

**Comment by Orionsg** [comment]
Unfortunately, I was a bit to fast in closing this issue. 

The problem has been fixed when it comes the Chrome browser. However, in the Firefox browser the highlighting in Grammarly still has the same problem of the font and background color both being very light, so one cannot read the text.

**Comment by Gusted** [comment]
Ah okay Will look into it

**Comment by Gusted** [comment]
Little bit weird it's not fixed for firefox..

**Comment by Orionsg** [comment]
Well, I commented on another issue on Dark Reader not working at all for LinkedIn.com. Also there, it works just fine in Chrome, but not at all for Firefox. Don't know if it is related in the sense that something else or extra has to be done for Firefox, but just wanted to mention it.

**Comment by Gusted** [comment]
Yeah we Use some API that Firefox don't understand so their could be cause a issue or the website loaded another Style for Firefox that could be also the case.

**Comment by Orionsg** [comment]
Ok, I see

**Comment by Gusted** [comment]
Okay Got the fix Chrome and Firefox apparently have other CSS for highlighted stuff pretty weird

**Comment by Gusted** [comment]
Made a PR #2180

**Comment by Orionsg** [comment]
Looks good!
