### ISSUE TITLE
7-Eleven Account doesn't theme

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#1905]
When going to https://www.7-eleven.com/account, for example, the dynamic theme doesn't apply.

**Comment by Kurtoid** [comment]
It seems ok for me, with default settings. Can you post a screenshot?

**Comment by TheAlienDrew** [comment]
It's variable, sometimes it happens, sometimes it doesn't. I think it might
be related to the loading bug when you load a webpage in a new tab (but
don't click on it).

**Comment by Gusted** [comment]
Seems also ok to me. 
Have another look.

**Comment by TheAlienDrew** [comment]
Yeah it looks fine now, maybe an update fixed what I was talking about.
