### ISSUE TITLE
Investing.com not working on Initial Load.

### ISSUE THREAD

**Issue by amanhigh** [darkreader/darkreader#1914]
Steps to reproduce issue

1.  Open https://www.investing.com/ , dark theme is not applied.
2. Toggle Dark Reader Off and back On from extension Menu.
3. Dark Theme is now applied correctly.

Expected Result: https://www.investing.com/ should have dark theme applied on initial Load and Toggle should not be necessary.

Using Latest Firefox Browser Ver. 72.0.1

**Comment by prg318** [comment]
This is happening for me on a lot of sites.  For example, https://archlinux.org loads white until I reload the DarkReader extension.

I also experience this on the OP referenced investing.com and many other sites.

Can't directly pinpoint when this started happening but I've been often having this issue for many websites over the past month.

FIrefox 72.0.2

**Comment by amanhigh** [comment]
Agree some recent change could have broken it for multiple sites. But i can see its not more than 1-2 months old. It was working fine.

Is there a way by which i can get older version of extension to test it out ?

**Comment by counterbeing** [comment]
I have another site that seems to be doing the exact same thing: https://www.apollographql.com/docs/apollo-server/monitoring/metrics/
This is just for portions of the page. On page refresh it's bad, on  toggling dark reader everything looks great all of a sudden.

**Comment by Gitoffthelawn** [comment]
> 
> 
> Agree some recent change could have broken it for multiple sites. But i can see its not more than 1-2 months old. It was working fine.
> 
> Is there a way by which i can get older version of extension to test it out ?

You can get older versions from:
https://addons.mozilla.org/firefox/addon/darkreader/versions/

Hope that helps you. :)

**Comment by amanhigh** [comment]
Thanks !! Recently in past few weeks it has been working. If problem re-appears would use older version link.

**Comment by Gitoffthelawn** [comment]
You're welcome.

I'm not sure whether or not this issue should be closed.  Is it still affecting others?  If so, on what sites?

**Comment by counterbeing** [comment]
I see this one regularly, including the site i listed above.

**Comment by amanhigh** [comment]
I thought since its resolved for site i was observing its redundant. We can create a dedicated issue tracking all sites that have this issue and track at single place if required.

**Comment by counterbeing** [comment]
That sounds like a great idea, i'm going to start taking notes of sites that I see with screen captures, and I'll link a new issue unless someone does it first.

**Comment by prg318** [comment]
archlinux.org shows the same behavior

dark mode through darkreader doesn't take effect until its toggled off and on

**Comment by counterbeing** [comment]
I've added the issue, please add anything that fits the description with any other information you have.
https://github.com/darkreader/darkreader/issues/2065
