### ISSUE TITLE
colon does not work in attribute selector

### ISSUE THREAD

**Issue by MikeMazz23** [darkreader/darkreader#1919]
If you use an attribute selector with a colon for namespacing, like div[foo:bar="value"], the override won't work. You should be able to escape it, like div[foo\\:bar="value"], but that's not recognized either. I tested the escaping in chrome browser on jsfiddle and it worked, so I'm thinking the issue is the colon is messing up the parsing of the overrides. I also tried the \ encoding, like div[foo\3Abar="value"], and this did not work either.

**Comment by Gusted** [comment]
Have a look at valid CSS4 Selectors
https://www.w3schools.com/css/css_attribute_selectors.asp
