### ISSUE TITLE
DR slows down gitea pages like 10x when it is in filter mode

### ISSUE THREAD

**Issue by gerroon** [darkreader/darkreader#1922]
Hi

I am using it with Gitea, since GItea does not have many themes. It workswell but one thing that seems to be an issue is that the `dynamic` mode makes Gitea pages incredibly slow to load. GItea is actyually super snappy. I can get fast load speeds if I just disable DR on Gitea pages. The page loads goes to like 10 secs if I enable the addon again.

thanks

**Comment by christianfl** [comment]
I have the same issue, tested on Firefox desktop and mobile. https://codeberg.org for example is totally unusable with Dark Reader. On mobile sometimes I got an unresponding script error for Dark Reader.

**Comment by Gusted** [comment]
First Are you using Chromium based browser Or Firefox? And which version are you using from your browser It Could related to be

#2256 Firefox has know to have performance issue because of their garbage collector and their memory handling #535

**Comment by gerroon** [comment]
I use Firefox 74 on Linux

**Comment by Gusted** [comment]
> I have the same issue, tested on Firefox desktop and mobile. [codeberg.org](https://codeberg.org) for example is totally unusable with Dark Reader. On mobile sometimes I got an unresponding script error for Dark Reader.

Script error? Could you or post it in #535 or if neccesary make a seprate issue with posting a screenshot of the error.

**Comment by Gusted** [comment]
Dynamic theme is know for Firefox to have some bad performance issues. Described here #535

**Comment by Gusted** [comment]
Duplicate as of #535
