### ISSUE TITLE
GitHub "Tree" Image In "Forks" Page Isn't Dark

### ISSUE THREAD

**Issue by BananaManCJ** [darkreader/darkreader#1924]
![image](https://user-images.githubusercontent.com/47013513/72869458-2ca71900-3c9a-11ea-81e1-1cb99faa07c2.png)

**Comment by Mertyn** [comment]
Fixed it [here](https://github.com/darkreader/darkreader/pull/2047) :)
Waiting to be approved and updated now

**Comment by Gusted** [comment]
Fixed in latest version of darkreader
