### ISSUE TITLE
How to Ignore SVG elements?

### ISSUE THREAD

**Issue by skccccc** [darkreader/darkreader#1925]
darkreader is changing color of highchart elements (svg elements). I want darkreader to ignore svg elements to change stroke and fill color.

Please check the attached snapshot [link](https://i.ibb.co/kSqHdM8/dark.png)

**Comment by WebMechanic** [comment]
If you created this SVG using the Highcharts® library, you might want to set the SVG's inline CSS properties to prevent changes from outside the SVG document or change the inheritance.

The charts at https://www.highcharts.com/demo/line-basic look fine in Darkmode and as they should be: dark :)

**Comment by Gusted** [comment]
`IGNORE INLINE STYLE` rule will prevent inline style analysis of matched elements (e.g. for `<p style="color: red">` element's `style` attribute will not be changed).
