### ISSUE TITLE
when dark mode enabled SCP site is still white on the top of the page

### ISSUE THREAD

**Issue by apektos1000** [darkreader/darkreader#1929]
http://www.scp-wiki.net/scp-001-d
when the white mode is enabled everything looks fine, its just white, but when you enable dark mode the site looks wayyy better, the only problem is that for some reason a part on the top of the page is still white, can you guys fix it?
this also happens in the main page http://www.scp-wiki.net/
![image](https://user-images.githubusercontent.com/33524507/73121523-75551f80-3f83-11ea-8b92-e31a4066e568.png)
Thank you.

**Comment by Myshor** [comment]
Made fix for that:
![image](https://i.ibb.co/y69scdM/screencapture-www-scp-wiki-net-1581199613481.png)

Waiting for acceptance. ;)

**Comment by apektos1000** [comment]
in the first second its just like as the photo you uploaded but then it because just like I mentioned.

**Comment by Myshor** [comment]
Well... It's not merged yet. Fix will be included in official darkreader after merge.

**Comment by Johnny998** [comment]
When will this be fixed?

**Comment by Gusted** [comment]
> 
> 
> When will this be fixed?

Now(#3612)

**Comment by Johnny998** [comment]
> 
> 
> > When will this be fixed?
> 
> Now(#3612)

Thanks!
