### ISSUE TITLE
Google Translate plugin dark mode problem

### ISSUE THREAD

**Issue by rxliuli** [darkreader/darkreader#1931]
![image](https://user-images.githubusercontent.com/24560368/73132392-676fcf00-4055-11ea-9d02-18e0d8a78abb.png)

Using the official Google Translate plugin: <https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb>

**Comment by rxliuli** [comment]
Similar to the previous issue <https://github.com/darkreader/darkreader/issues/625>, but the problem is that the text is difficult to see in dark mode

**Comment by chuntangwang** [comment]
Same issue here.

My solution is modifying CSS config `.jfk-bubble` in **Dynamic Theme Editor**.

1. Click extension icon of **Dark Reader** > **More**
2. Check Theme engine is `Dynamic` by default
3. Click button `Dev Tools`.

Default
```css
.jfk-bubble {
    background-color: ${white} !important;
}
```
Replacing `white` with `dark`.
```css
.jfk-bubble {
    background-color: ${dark} !important;
}
```
then click button `Apply`.

Maybe it will effect some websites using class `.jfk-bubble`, but at least it works for me now.

**Comment by rxliuli** [comment]
> Same issue here.
> 
> My solution is modifying CSS config `.jfk-bubble` in **Dynamic Theme Editor**.
> 
> 1. Click extension icon of **Dark Reader** > **More**
> 2. Check Theme engine is `Dynamic` by default
> 3. Click button `Dev Tools`.
> 
> Default
> 
> ```css
> .jfk-bubble {
>     background-color: ${white} !important;
> }
> ```
> 
> Replacing `white` with `dark`.
> 
> ```css
> .jfk-bubble {
>     background-color: ${dark} !important;
> }
> ```
> 
> then click button `Apply`.
> 
> Maybe it will effect some websites using class `.jfk-bubble`, but at least it works for me now.

Okay, this did solve my problem, but hopefully the official can give a better solution (dark mode, but a more recognizable way of text)

**Comment by FranklinYu** [comment]
Styling things in shadow DOM is very difficult. Maybe we can look at how Stylus team is trying to tackle it: openstyles/stylus#739

**Comment by alexanderby** [comment]
@FranklinYu Interesting solution, thanks.

Currently I've made a fix here https://github.com/darkreader/darkreader/commit/811cefb36e0adc734f05dd5f5534157ad1dc190c

But Chrome Web Store update reviews have become too long, so maybe you could try copying the fix in Dark Reader Dev Tools.

**Comment by rxliuli** [comment]
> @FranklinYu
> 
> Currently I've made a fix here [811cefb](https://github.com/darkreader/darkreader/commit/811cefb36e0adc734f05dd5f5534157ad1dc190c)
> 
> But Chrome Web Store update reviews have become too long, so maybe you could try copying the fix into Dark Reader Dev Tools.

Yes this solution does work!

**Comment by alexanderby** [comment]
Also there used to be an auto-update of these config files from GitHub, but the GitHub team started to complain about huge amount of traffic.

**Comment by rxliuli** [comment]
> Also there used to be an auto-update of these config files from GitHub, but the GitHub team started to complain about huge amount of traffic.

I think this can be bypassed by CDN + periodic (daily) updates. . .

**Comment by rxliuli** [comment]
I have done this before (updated once a day), and it looks like there should be no problem at this time. If the number of users is really large, then you can use cdn jsdelivr as a relay. . .

> An oil monkey script that does this：<https://greasyfork.org/zh-CN/scripts/391193-%E8%A7%A3%E9%99%A4%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6>

The key code is as follows

```js
  /**
   * 兼容异步函数的返回值
   * @param res 返回值
   * @param callback 同步/异步结果的回调函数
   * @typeparam T 处理参数的类型，如果是 Promise 类型，则取出其泛型类型
   * @typeparam Param 处理参数具体的类型，如果是 Promise 类型，则指定为原类型
   * @typeparam R 返回值具体的类型，如果是 Promise 类型，则指定为 Promise 类型，否则为原类型
   * @returns 处理后的结果，如果是同步的，则返回结果是同步的，否则为异步的
   */
  function compatibleAsync(res, callback) {
    return res instanceof Promise ? res.then(callback) : callback(res)
  }
  /**
   * 在固定时间周期内只执行函数一次
   * @param {Function} fn 执行的函数
   * @param {Number} time 时间周期
   * @returns {Function} 包装后的函数
   */
  function onceOfCycle(fn, time) {
    const get = window.GM_getValue
    const set = window.GM_setValue
    const LastUpdateKey = 'LastUpdate'
    const LastValueKey = 'LastValue'
    return new Proxy(fn, {
      apply(_, _this, args) {
        const now = Date.now()
        const last = get(LastUpdateKey)
        if (last !== null && now - last < time) {
          return safeExec(() => JSON.parse(get(LastValueKey)))
        }
        return compatibleAsync(Reflect.apply(_, _this, args), res => {
          set(LastUpdateKey, now)
          set(LastValueKey, JSON.stringify(res))
          return res
        })
      },
    })
  }
```

**Comment by FranklinYu** [comment]
Yes CDN can help. In addition to https://www.jsdelivr.com mentioned above, https://statically.io is another famous option.
