### ISSUE TITLE
Dark mode doesn't work properly on reddit-archived-post page.

### ISSUE THREAD

**Issue by Vinigas** [darkreader/darkreader#1932]
Issue occurs in this page: https://www.reddit.com/r/csharp/comments/6byapa/why_are_extension_properties_not_a_thing/
Then reddit white theme enabled and DarkReader black mode enabled

**Comment by Myshor** [comment]
I can not reproduce in Chrome and/or Firefox. Can you tell what browser you are using?

**Comment by Vinigas** [comment]
[Latest] Chrome Beta Version 80.0.3987.87 (Official Build) beta (64-bit) 
Dark Reader 4.8.8
[Latest preview] Windows 10 Pro Insider Preview Build 19555.rs_prerelease.200127-0900

![image](https://user-images.githubusercontent.com/6695244/74134299-fa327100-4bf2-11ea-8992-2757a04029f1.png)
Night mode is turned off on the site
While Dark reader turned on
![image](https://user-images.githubusercontent.com/6695244/74134371-1fbf7a80-4bf3-11ea-911d-ec9090d55f73.png)
Here is current result:
![image](https://user-images.githubusercontent.com/6695244/74134402-2ea62d00-4bf3-11ea-9649-1c0459643c2b.png)

**Comment by Myshor** [comment]
Ok... With brightness +50 it may be like that. With default brightness it's nice gray.
Still I have it little darker than shown on the screen. One more question.

Are you see this just after clicking URL you shared?
or maybe you end on this site after browsing reddit from other place?

I ask this 'cause DR 4.8.8 version has some issues with not switching dark on some pages if not whole page was reloaded.

P.S. How it looks for me when I open it (even with this +50 brightness):
![image](https://user-images.githubusercontent.com/56877029/74144793-b09b5380-4bfd-11ea-8377-e158e566e3d3.png)

**Comment by Vinigas** [comment]
Yes, it occurs directly opening link I specified.

Issue occurs on bigger screen than yours. Downscalling with Ctrl + Minus should also work for you.

Also I am logged in.

**Comment by Vinigas** [comment]
Closing because issue not replicable anymore. (Fixed?)
