### ISSUE TITLE
Underlined links are not visible

### ISSUE THREAD

**Issue by naoliv** [darkreader/darkreader#1938]
At https://www.uol.com.br/tilt/noticias/redacao/2020/01/26/coronavirus-site-mostra-contagio-pelo-mundo-siga-em-tempo-real.htm we can see that the links have an underlined style, like this:
![](https://user-images.githubusercontent.com/982338/73357543-56080c00-427b-11ea-9022-0c65d38d6997.png)

But with darkreader enabled we can't differentiate what is a link and what is not:
![](https://user-images.githubusercontent.com/982338/73357552-5a342980-427b-11ea-9d35-f098c58be845.png)

Everything seems to be plain text only (and makes us unaware that there are links in the page).

Is there anything that can be done about this, please?

I am using version `4.8.7` on Firefox and didn't change anything in darkreader.

**Comment by Myshor** [comment]
Created fix for that:
![image](https://user-images.githubusercontent.com/56877029/74065982-6e53f580-49f6-11ea-8e33-d3332909b4cb.png)

Waiting for acceptance. ;)

**Comment by naoliv** [comment]
Great, thanks!
