### ISSUE TITLE
New Tab Site White in Dark Mode after Restart

### ISSUE THREAD

**Issue by BrokoliMC** [darkreader/darkreader#1940]
The Darkmode works fine for the about:newtab Site, after a restart all sites are as normal,
but the New Tab site is completely White, and I can only change it, when I reapply the Firefox Dark Theme. Without Dark Reader the Problem doesnt exists.

For now, you can change this Behavior, if you install the Addon "New Tab Override", there you can set a Dark Color for the New Tab.

**Comment by julikaiba** [comment]
can confirm, as soon as I activate the Dark Reader Addon, the firefox theme changes to the default one. If I change the theme after having dark reader active it works for a few seconds or minutes but after some time it reverts to the default theme again (in the theme settings it still shows as dark mode though)
When I leave the dark reader addon disabled, the problem doesnt occur.

**Comment by mas-co** [comment]
This just started happening to me yesterday.  about:newtab was set to dark theme and appeared as expected.  Then, suddenly, the about:newtab appears as it would in a light theme.  Checked Dark Reader settings, but about:newtab is "protected by browser".
However, if I go to change the theme for about:newtab (via the customize menu) to default and then back to dark, it will remain in the dark theme until the browser is restarted.

**Comment by mas-co** [comment]
Is this related to [Firefox] about:newtab #406

**Comment by julikaiba** [comment]
It's most likely the same issue. The problem seems to be fixed, if you set the option "Change the browser theme" (found under "More") to "default" instead of "custom".

**Comment by mas-co** [comment]
> 
> 
> It's most likely the same issue. The problem seems to be fixed, if you set the option "Change the browser theme" (found under "More") to "default" instead of "custom".

Well, that did work, but I had not changed that setting.  Is the browser theme mode set to "custom" by default (i.e. "out of the box") as I had not changed it.

Anyhow, I seem to be back to normal for now.

**Comment by julikaiba** [comment]
Well as someone mentioned in #406 the setting was added only recently because of this bug. It seems to have been "set" to custom the whole time, just some error must have lead it to cause issues.

**Comment by AlexGuo1998** [comment]
> It's most likely the same issue. The problem seems to be fixed, if you set the option "Change the browser theme" (found under "More") to "default" instead of "custom".

Hi sorry for bothering you. Could you please give me a hint of where to find the option "Change the browser theme"? I just can't find the option anywhere!
I'm using Firefox 77.0.1, Dark Reader 4.9.9.
This is what I see on "See all options" and "Settings"
!["See all options" page](https://user-images.githubusercontent.com/25975864/84474373-500c4800-acbd-11ea-9ba9-958cd4910c4f.png)
!["Settings" page](https://user-images.githubusercontent.com/25975864/84474387-54d0fc00-acbd-11ea-8403-ecc1303d137e.png)

**Comment by julikaiba** [comment]
What browser are you using and have you updated to the latest version?

**Comment by AlexGuo1998** [comment]
> I'm using Firefox 77.0.1, Dark Reader 4.9.9.

Surely the latest version, both Dark Reader and Firefox. What version are you using?
BTW I download Dark Reader from here: https://addons.mozilla.org/en-US/firefox/addon/darkreader/

**Comment by Gusted** [comment]
It's technically protected page.

I suggest we will change our custom theme to be disabled by default. So it won't change the theme out of the box. < Will resolve the problem as for some reason we override the current theme(Dark). When we just override some settings for tab appearance.

**Comment by Gusted** [comment]
Can't do much about it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1415267

**Comment by julikaiba** [comment]
![asdfasdf](https://user-images.githubusercontent.com/56001937/84531735-4eef1100-ace5-11ea-8a11-0d04f9741d6f.jpg)
This is what it looks like to me, just updated to 4.9.9, Firefox 77.0

**Comment by julikaiba** [comment]
and putting the bottom option to default instead of custom (might have to toggle it twice to register or something) enables the firefox theme to take over where it can (I think thats how it works)

If your theme is the normal bright theme then of course it will still show a white new tab.

**Comment by julikaiba** [comment]
> It's technically protected page.
> 
> I suggest we will change our custom theme to be disabled by default. So it won't change the theme out of the box. < Will resolve the problem as for some reason we override the current theme(Dark). When we just override some settings for tab appearance.

isnt that exactly what was already done and supposedly fixes this issue?

**Comment by Gusted** [comment]
I think we have a bug on our side not sure.

**Comment by julikaiba** [comment]
for me its working perfectly at least, so maybe check if firefox changed your selected theme or if reinstalling the addon helps.
Other than that I'm out of ideas.

**Comment by major-mayer** [comment]
I'm also affected by this problem.
I use Firefox x, Darkreader x and Ubuntu 20.04.
When i disable this addon the newpage works just fine and is dark as it should.

I think this bug can be fixed, because for example using Sauron (another dark mode extension) I don't have this problem (i like this addon more tho).

**Comment by Gusted** [comment]
> When i disable this addon the newpage works just fine and is dark as it should.

You should disable the custom browser theme in the old design, to get the new tab as dark. I'm not even sure how this happens.



> because for example using Sauron (another dark mode extension) I don't have this problem (i like this addon more tho).

Because for example this extension doesn't set any Firefox Theme and by that the problem will never exist in the first place.

**Comment by major-mayer** [comment]
> You should disable the custom browser theme in the old design, to get the new tab as dark. I'm not even sure how this happens.

I'm not sure if i understood you correctly, but when I disable the pre-shipped dark theme of Firefox and enable the standard theme, the new page tab is still light.
This is the same case for any other theme that i enable (the ones of firefox and others from the store).

**Comment by Gusted** [comment]
After having a quick look at the [colors documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors) It seems like we had missed some extra colors to give it a more dark experience which included the about:home(alias ntp) page and the sidebar(e.g. bookmark). So I've opened a pr(#3634) to fix this issue.

Regards,
Gusted
