### ISSUE TITLE
Firefox: Dark Mode Persists after Uninstall Darkreader

### ISSUE THREAD

**Issue by HaLudata** [darkreader/darkreader#1941]
Hello,

In some sites, the dark mode persists even after I have uninstalled Darkreader.

I'm using Firefox 72.0.2 on Windows 10 Pro Build 1909.

"Help > Restart with Add-ons Disabled" makes no difference.

Also, it's specific to this profile (I have other profiles who were unaffected).

I believe the sites that remain in dark mode were those out of my "exception list", though not sure (some URLs I don’t recall ever entered before seems to be OK).

Any ideas?

Thank you, very much!

![Evernote Darkmode](https://user-images.githubusercontent.com/60233507/73464238-57aa0080-435d-11ea-8777-9599935d0fa1.png)

**Comment by alexanderby** [comment]
Hi @HaLudata. The extension cannot do anything once uninstalled. Please check if you have any other dark mode extension installed. Also check if you modified userChrome.css file or Preferences -> Language and Appearance -> Colors.

**Comment by HaLudata** [comment]
@alexanderby Ty for you reply, this solved:

> Preferences -> Language and Appearance -> Colors.

Cheers!

**Comment by tomillie** [comment]
I had the same issue after the uninstallation. This should be fixed, the colours should be reverted to default values when the extension is uninstalled.

Firefox 76.0.1
Dark reader 4.9.8

**Comment by Gusted** [comment]
> Hi @HaLudata. The extension cannot do anything once Uninstaller. @tomillie we can't fix it
