### ISSUE TITLE
Broken Website

### ISSUE THREAD

**Issue by pitchzer0** [darkreader/darkreader#1945]
Hey there,
I found a website, that is not working properly. The main font is light yellow on white Background with darkreader. Since i don't have the slightest Idea about webdesign i can just post the link to a random article on the website. hth
https://www.br.de/nachrichten/deutschland-welt/liveticker-zum-coronavirus,RoxMtok

**Comment by Myshor** [comment]
Made some fixes for this site:
![image](https://user-images.githubusercontent.com/56877029/74064574-3eefb980-49f3-11ea-9890-d656424fdb5f.png)

Fix is awaiting for acceptance. ;)

**Comment by fsfyx** [comment]
it work, but you should turn off the darkmode, and then turn on it ...

**Comment by Myshor** [comment]
Look here:
#1970 
untill it's open it's still not fixed in official release.
