### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by uniartisan** [darkreader/darkreader#1952]
I am a user of a new version of the edge browser, and now this browser already supports switching the white and dark theme with the system. Can the plugin automatically switch between night / day mode based on the theme of the browser? In this way, the Windows system cooperates with an application that automatically switches the system theme to achieve global switching.

**Comment by alexanderby** [comment]
Hi, I'm sorry for current design. Click little three dots near On/Off button, you will see several automation options.
