### ISSUE TITLE
Dark Reader 4.8.8 doesn't appear on Firefox 68.2.0esr (64-bit)

### ISSUE THREAD

**Issue by tedfp** [darkreader/darkreader#1956]
When using Debian bullseye/sid with 5.2.0-2-amd64, I notice that Dark Reader doesn't appear on the right hand side of search bar. Also pressing short cut Shift + Alt + A or Shift + Alt + D doesn't work either - neither website being toggled nor extension gets toggled. Not sure if this is bug or anything.

**Comment by alexanderby** [comment]
Hi. Have a look at about:addons page, maybe it is disabled for some reason.
