### ISSUE TITLE
Toggling the extension should not reset my settings.

### ISSUE THREAD

**Issue by anohren** [darkreader/darkreader#1958]
Actual behavior:
My settings is to use the system's color scheme to decide whether pages are light or dark. Sometimes I need to override this, so I naturally turn the extension off with the most prominent toggle switch in the popover. This resets the mentioned system color setting, which is not expected given that I have not requested any settings to change.

Expected behavior:
My settings are preserved and the extension continues to react to external color change events as soon as it's switched back on again. My preferences do not change regardless of how many times I use the toggle switch to force pages to render normally.

Forgot to mention: big fan of this project. Can't live without it now.

**Comment by anohren** [comment]
Looking more closely there seems to be some overlap in perceived functionality in the popover. Maybe it's actually the _Mode_ that should be automated based on system color scheme, and not the enabled state of the extension. 

Combine that change with separate brightness, contrast, [...] settings for each Mode, move the extension toggle switch to the bottom, and put the Mode switch in its place, and it would make for an easier mental model; I generally want the extension to be enabled all the time, just in different Modes of operation depending on the environment (system settings). The Light Mode would then instead show the untouched page by default. That I want my Light Mode to deliver an untouched page should reasonably be a subpreference for that mode.

As long as the two modes are configured correctly there is then no need for the user to have to distinguish the Mode from the extension's enabled state, or to to even think about disabling the extension, other than in the rare cases where the extension delivers undesired results in its current mode. This would lighten the mental load when configuring the extension.

Did I miss anything?

**Comment by Gusted** [comment]
Try the new User Interface, it should fix this.
```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.
```

**Comment by tbrodbeck** [comment]
Hi! I have the same feature request as the OP!
And I tried the new UI, but it still has the same issue: I enable the theme following the system theme, but when I press <kbd>Option</kbd><kbd>Shift</kbd><kbd>D</kbd> this setting is disabled.

**Comment by anohren** [comment]
I don't think you have the same feature request as me, since it's inapplicable to the new design with a three-state switch.

**Comment by tbrodbeck** [comment]
Okay sorry if I did not get your point. But thanks @Gusted for the quick fix :)

**Comment by anohren** [comment]
Upon closer look you might be right that I'm describing your problem. I wasn't very clear in my first post at any rate.
