### ISSUE TITLE
Baidu.com becomes white when switching page

### ISSUE THREAD

**Issue by luo-chuan** [darkreader/darkreader#1960]
dark reader version：4.8.8
Firefox version: 72.0.2(64bit)
OS: Win10 1909

Only in version of 4.8.8 in Firefox, when I search something in baidu.com, the page 1 is in currect dark mode(dynamic mode), but when I switch to page 2, something wrong happened, the page looks like in light mode. If I refresh the website, the dark mode comes back.

The version 4.8.7 do not have this bug.
 
![image](https://user-images.githubusercontent.com/33930736/73832126-8e42b800-4842-11ea-8b9e-895971ba5315.png)  

![image](https://user-images.githubusercontent.com/33930736/73832180-a7e3ff80-4842-11ea-8512-64d46a5c2cd0.png)

**Comment by luo-chuan** [comment]
The version 4.8.7 do not has this bug.

**Comment by alexanderby** [comment]
I've submitted a new version with a fix, wait for updates.

A tricky situation is happening in Chrome. An update, that includes Baidu bug, is pending review and I will be only able to submit a bug fix after it, and it will be reviewed for another week.

**Comment by Kotoki1337** [comment]
this is also a problem in chrome.
everything is normal before the search. the same error as the second picture will occur after the search.

**Comment by alexanderby** [comment]
Hi, please check that you have the latest 4.8.9 installed. It was reviewed by Chrome Web Store today.

**Comment by Kotoki1337** [comment]
its work, thx

**Comment by dunkeng** [comment]
dark reader version:　4.9.13
Chromium version:　80.0.3987.163
I encountered the same problem.

**Comment by Gusted** [comment]
Oh no not again baidu
