### ISSUE TITLE
regex101.com

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#1961]
On [Regex101](https://regex101.com/), highlighted text is unreadable using the dynamic filter while filter+ makes the page very slow.

![Capture d'écran du 2020-02-05 18 24 15@2x](https://user-images.githubusercontent.com/21284089/73866208-c0edb000-4844-11ea-8a1d-cca4d6ea3a82.png)

Thanks

**Comment by Myshor** [comment]
Go to Regex Settings and change theme style to dark. I think it's no need to fix dark reader if it has it's own dark mode ready to use. ;)
![image](https://user-images.githubusercontent.com/56877029/74041348-c7576580-49c5-11ea-8a0a-46bfb0bcfa82.png)

**Comment by KaKi87** [comment]
Wow, where did you found that "settings" link ?

**Comment by Myshor** [comment]
O the left of the page... "Wrench" icon. ;)

**Comment by KaKi87** [comment]
OMG thanks
