### ISSUE TITLE
Version 4.8.8 white flash on page loads on Firefox

### ISSUE THREAD

**Issue by AggelosM** [darkreader/darkreader#1965]
Dark Reader version: 4.8.8
Firefox version: 72.0.2 (64-bit)

**How to reproduce:**

1. Go to google.com
2. Refresh page

**What is expected to happen:**

Dark mode should load automatically.

**What actually happens:**

Non-dark mode blinds you for some milliseconds, before dark mode takes place.

**Comment by AggelosM** [comment]
Version 4.9.0 and still the same issue. Any info?

**Comment by Gusted** [comment]
Hi!

Dark reader v4.9.17 has been released that has the fix that fixes this issue 🎉.
To make sure you are on the latest version to make sure this is the case.
First, we should make sure your on the new user interface of Dark reader, by doing:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

This should have activated the new user interface and should look like this: ![](https://i.imgur.com/cJJwSrY.png). Make sure to pay attention to the bottom text that says the current version. If it states an older version e.g. 4.9.16 I suggest to remove the extension and re-install it trough https://darkreader.org/ so it will be forced to download the latest version.
If this fix still indicates this issue let me know and hopefully improvements can be made!

Regards,
Gusted
