### ISSUE TITLE
Diappears from address bar.Stops working.

### ISSUE THREAD

**Issue by IRBrainiac** [darkreader/darkreader#1966]
After a few minutes Dark Reader disappears from address bar and stops working.It wont uninstall so I cant reinstall it.
Start Firefox again and it is back for a few minutes then disappears again.
Both Firefox and Dark Reader updated themselves on Feb 4.

Thank you from Michael...Dark Reader is an indispensable addon.

**Comment by IRBrainiac** [comment]
Wont stay disabled either.Cant use any other dark mode plugins.Seems to be interfering with Tranquility reader as well.
I will try uninstalling Firefox.Dark Reader is in my permanent profile that I load from another drive after an install of Firefox.

**Comment by IRBrainiac** [comment]
If I click update addons Firefox disables DR and moves it to disabled.It is still switched on but not working and not on the adress bar.
Switching it off and on again reactivates it.

**Comment by IRBrainiac** [comment]
Hmmmm...I cant remove or disable other addons either.I tried to remove Firefox Color because I thought it possibly was interfering with DR but it just comes right back after a restart.

**Comment by IRBrainiac** [comment]
I think this is all a Firefox screwup.It forced me to setup a new profile.I hate setting up new profiles.It is a LOT of work and defeats the whole purpose of moving my profile to a separate drive.

**Comment by IRBrainiac** [comment]
So far so good on new profile.
Dark Reader is essential. :)

**Comment by Gusted** [comment]
Can you close the issue?

**Comment by IRBrainiac** [comment]
Yes of course...thank you.
