### ISSUE TITLE
Proxmox 6 web UI  broken with Chrome 80

### ISSUE THREAD

**Issue by whiskerz007** [darkreader/darkreader#1967]
I have recently updated Google Chrome to version 80 on Windows 10 1909. I was running Chrome 79 before and had no issues running this extension to modify Proxmox UI. Since updating to Chrome 80, the Proxmox UI fails to function. I am not able to manage the VMs or use the web console.

Looking at the browser log, when I enable this extension for the site over one hundred errors are generated with most of them ending with `net::ERR_CERT_AUTHORITY_INVALID` for various resources hosted on the Proxmox server. Errors are generated continually after enabling the site styling until I disable site styling and refreshing the webpage. The webpage is using a self-signed certificate since this is only internally accessed.

Please advise.

**Comment by Kynolin** [comment]
I just started getting the same error in a proprietary webapp (extjs/php/fcgi) with Chrome 80, Dark Reader 4.8.8, and Windows 10 1803. It's also using a self-signed certificate and being accessed directly from a Linux VM running Debian 9 & apache2 2.4.25-3+deb9u9 on my own laptop. The page works for maybe 30 seconds to a minute, then I get the error and all further connections fail.

* All extensions are disabled except Dark Reader.
* If I reload the page, it starts working but then breaks again. This includes emptying cache and hard reload, or closing/reopening the browser.
* The app is making very frequent requests to fcgi which updates the page with a lot of json data. Disabling fcgi doesn't help.
* The app is also using php with session cookies but php calls are less frequent.
* I have not noticed errors on the webserver. The errors are in the Chrome developer console and network tab.
* I do have Symantec, but it was not a problem before, and from what I can tell, I don't see issues in the logs or Windows logs.
* Putting the same app on http/80 works with styling enabled.

Here are some of the combinations I've tried with HTTPS:

* Dark Reader extension enabled but turned off in the settings: ok
* Dark Reader turned on with styling disabled: ok
* Toggling dark reader while styling is kept disabled for the page: ok
* Styling turned on before loading the page: errors
* Styling turned on after loading the page: errors
* Styling turned on, then quickly turned back off: errors
* Styling turned on, then after the errors: disable, turn off, or disable extension: requires reload to fix

Dark Reader settings:
Dark
Brightness: off
Contrast: -10
Sepia: +10
Grayscale: off
More:
Font: Open Sans (unchecked)
Text stroke: off
Mode: Dynamic

**Comment by Kynolin** [comment]
@whiskerz007 could you see if this is still a problem on Chrome 80.0.3987.100..80.0.3987.106?

Mine updated today, and I noticed this in the changelog. I checked again, and the web app that had issues for me is able to run normally via https while in dark mode.

[chromium 80.0.3987.100..80.0.3987.106 changelog](https://chromium.googlesource.com/chromium/src/+log/80.0.3987.100..80.0.3987.106?pretty=fuller&n=10000
)
[commit: 43a932d061321222494c560d51beaa5ba3c841ff](https://chromium.googlesource.com/chromium/src/+/43a932d061321222494c560d51beaa5ba3c841ff)

> This CL reverts r716451.  The revert is needed because r716451 caused
> every blob load (blobs see no certificate errors) to call
> RevokeUserAllowExceptions.

**Comment by whiskerz007** [comment]
I can confirm that Chrome Version 80.0.3987.106 (Official Build) (64-bit) on Windows 10 1909 is not experiencing the problem. Since this was a problem with Chrome, I'm closing this issue.
