### ISSUE TITLE
Linkedin Invitation message  issue

### ISSUE THREAD

**Issue by UchihaSR** [darkreader/darkreader#1976]
when I typed a message, it has same color as of background of the message box. if you decrease the contrast and brightness then you can see your typed message but if both are off then it is difficult. ![linkedin_issue](https://user-images.githubusercontent.com/52357560/74097792-597e7b80-4b36-11ea-9a27-4a005bef691e.png)

**Comment by Myshor** [comment]
Nice catch. 👍 
Made fix for that:
![image](https://user-images.githubusercontent.com/56877029/74108460-fd8a1600-4b7a-11ea-9c5d-8b75187e17eb.png)

Waiting for acceptance. ;)

**Comment by Myshor** [comment]
Other fix done by @alexanderby. So wait for new version. ;)
