### ISSUE TITLE
"Activate after sunset at location" broken

### ISSUE THREAD

**Issue by apparle** [darkreader/darkreader#1989]
The feature to automatically activate after sunset at specified GPS coordinate seems to be broken. I tried different coordinates like San Franscisco (37.7749°, 122.4194°) or Santa Clara (37.3541°, 121.9552°), and dark reader gets activated at 1pm afternoon. 

I'm using Dark Reader on Firefox.

**Comment by DaSandman** [comment]
Not sure why this issue was closed, but @apparle was correct.  The Firefox version of DarkReader is unable to correctly use  coordinates to activate after sunset.
