### ISSUE TITLE
darkreader for Safari not working in lodash documentation page

### ISSUE THREAD

**Issue by kuige** [darkreader/darkreader#1992]
macOS Catalina 10.15.2 

dark reader extension is enabled, but the lodash documentation page is still light.

https://lodash.com/docs/4.17.15

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/8212800/74347620-53192980-4dec-11ea-889c-2895a8abe702.png">

**Comment by Gusted** [comment]
Should be fixed.
