### ISSUE TITLE
Dynamic mode regression on WhatsApp Web

### ISSUE THREAD

**Issue by redfellow** [darkreader/darkreader#1997]
Emojis started to get reversed. Would be nice if there was a toggle for dynamic mode to leave images unreversed.

**Comment by Myshor** [comment]
My investigation ends with one conclusion.
All reversed icons in emoji selector change from normal image link to blob: when dark mode is enabled.

It would not be easy fix in dynamix-theme-fixes. I think it needs some main code analysys and fixes there.
