### ISSUE TITLE
Spotify/WebApp is not working properly when Dark Reader is on

### ISSUE THREAD

**Issue by dbautistav** [darkreader/darkreader#2]
The Spotify's webapp has a div with id=main which is all dark and no content is displayed when DarkReader is on; "main-nav" and "now-playing" divs are working just fine.

**Comment by alexanderby** [comment]
Unfortunately Spotify is not available for my country and I can't see it. I've added some fixes for some pages and for the #main block. But some parts of their pages are dark, some are bright, so I will have to return to it later. If I had broken something you can add "spotify.com" into the ignore list.

**Comment by dbautistav** [comment]
Ok, thanks Alex!

I'll wait for your next release in order to test the tunned features.
Just in case you want to play/test with spotify you can use a [free vpn](https://www.frootvpn.com/).


& happy new year    ;)

**Comment by dbautistav** [comment]
One more question, where is the option to *"add "spotify.com" into the ignore list"*?
Thanks in advance.

**Comment by alexanderby** [comment]
Click on Dark Reader's icon, then open "Ignore list" tab and add web-site address there. Also you may be able to edit this inner ignore list and add totally dark sites there (so they will be ignored in the next release by default) https://github.com/alexanderby/darkreader/blob/master/src/DarkReader/generation/ignore.json

**Comment by dbautistav** [comment]
Ok, I see. Thanks!

**Comment by risualiser** [comment]
@alexanderby Try to visit [this](http://spotify.com/us) address.
Also, I think it needs only one sub-domain for music player - #377.

**Comment by krupenja** [comment]
Spotify Webplayer works well in Dynamic Mode without any issues at my end. Other areas of the Spotify website are also OK. I think this can be closed now?
