### ISSUE TITLE
Provide immediate rendering with smooth transition

### ISSUE THREAD

**Issue by alexherbo2** [darkreader/darkreader#2003]
Related to #535.

**Comment by mohe2015** [comment]
As far as I understand your proposal I don't really like it as that is really uncomfortable for your eyes. I would rather prefer optimizing existing modes. Maybe a simple darkening could be applied first and then a second pass would improve on that.

**Comment by alexherbo2** [comment]
How about adding support for static, sharable (site-specific) theming, that could be integrated, and for externals, just away from a copy-paste URL?

**Comment by mohe2015** [comment]
> How about adding support for static, sharable (site-specific) theming, that could be integrated, and for externals, just away from a copy-paste URL?

That would also be an option but I think this is a totally separate idea.

**Comment by Gusted** [comment]
Fxied fixed and fixed. All linked issues
