### ISSUE TITLE
YouTube cards are broken

### ISSUE THREAD

**Issue by lucasdondo** [darkreader/darkreader#2013]
Well, not a lot more to talk about, just that.

**Comment by Gusted** [comment]
Well talk more about it I cannot reproduce the issue. Or did I misunderstand you? 
The youtube cards are working for me or did you mean another thing?

**Comment by lucasdondo** [comment]
> Well talk more about it I cannot reproduce the issue. Or did I misunderstand you?
> The youtube cards are working for me or did you mean another thing?
> https://i.imgur.com/tYJwqpI.gifv

From what I understand cards are the "links" that appear in the top-right corner of the videos. Cards are that?

**Comment by Gusted** [comment]
Oh the Info button That aren't cards.....
But what is broken about it?

**Comment by Gusted** [comment]
Because so far I see this is working perfectly fine https://i.imgur.com/vnxhr2m.gifv the Info button you talking about
