### ISSUE TITLE
[Request] Export site list

### ISSUE THREAD

**Issue by Qsefawd** [darkreader/darkreader#2014]
Hello there,

Thank you for such a great extension! I believe having an export option for site list will be useful. If not able to implement this, please guide me on a way to export the list.

Have a great day everyone!

**Comment by Gusted** [comment]
`chrome.storage.sync.get("siteList", function(items) {
    console.log(items["siteList"]);
});`

Paste this in the console when inspecting on the extension pop-up

**Comment by Gusted** [comment]
https://i.imgur.com/HPYsfBN.gifv

**Comment by Qsefawd** [comment]
> https://i.imgur.com/HPYsfBN.gifv

Thanks for your help, Guested. May I ask if the steps are the same for import?

**Comment by Gusted** [comment]
Pfff ehm gonna look into that when i'm home
It's possible it's a array but if you could pass the list you want I will make the code for it

**Comment by Qsefawd** [comment]
Thank you so much for looking into this.

Here's my list,

(7) ["shopee.sg", "google.*", "en.wikipedia.org", "www.instagram.com", "www.gamespot.com", "www.patreon.com", "www.pixiv.net", "web.whatsapp.com"]
0: "shopee.sg"
1: "google.*"
2: "en.wikipedia.org"
3: "www.instagram.com"
4: "www.gamespot.com"
5: "www.patreon.com"
6: "www.pixiv.net"
7: "web.whatsapp.com"
length: 7
__proto__: Array(0)

I'm still new in using this extension hence the low number. If I need to add a new website to the list in the future, is your code able to add it on the fly?

**Comment by Gusted** [comment]
I actually mean the list you wanted to import

**Comment by Qsefawd** [comment]
Oh, I get what you mean now. I do not have any list. It was an idea I thought that's missing.
By export/import, I mean a function that works like a browser's bookmark. Essentially to backup the extension's settings.

Hope you're able to get what I'm driving at.

**Comment by Gusted** [comment]
Yeah I get what you mean like a new button at the sitelist to export it as a list I will defintely look into when I know how Typescript works.

**Comment by Qsefawd** [comment]
Appreciate your kind help in this matter. Have a great weekend ahead! :)

**Comment by PinkDev1** [comment]
Any progress on this? ^^'

**Comment by Gusted** [comment]
Darkreader v5 is in the make. I will try to implement this

**Comment by evlsmurf** [comment]
how do we export on firefox i dont have the inspect right click when doing it

**Comment by Gusted** [comment]
Their will be a supported option to do this.

**Comment by evlsmurf** [comment]
> 
> 
> Their will be a supported option to do this.

any idea of time frame for release

**Comment by Gusted** [comment]
4.9.10 just released so me going to add it this week, so.... I'm not sure

**Comment by Gusted** [comment]
In the next update of Dark Reader this will be a function.

**Comment by ajason08** [comment]
> In the next update of Dark Reader this will be a function.

You mean version 5?
current is v4.9.16
Thanks a lot

**Comment by Gusted** [comment]
Current version that your on should contain the feature.

**Comment by ajason08** [comment]
I could not find it!
I thought I checked every corner of the extension, such as:
- Site list tab
- 3 dots (for automation)
- dev tools (I did not find a place for copying or pasting my custom list)
What does I missing?
Thank you in advance :)

**Comment by Gusted** [comment]
Go to devtools and enable preview new design. Than check every corner again.

**Comment by PinkDev1** [comment]
@Gusted thank you so much <3

**Comment by anthonymag** [comment]
Thanks so much! This is what I was looking for and didn't realize it was on the new design preview.

Steps to export -> import (I did it from Chrome to Brave)
1. Enable new design as stated above
2. Click Vader icon
3. Settings
4. Manage settings
5. Export settings (if old browser), or Import on new browser and select the JSON file
