### ISSUE TITLE
Can't disable DarkReader on some websites

### ISSUE THREAD

**Issue by gregk-git** [darkreader/darkreader#2026]
I can't disable DarkReader on several specific websites, but toggling DarkReader off gets the issue to stop happening, but then DarkReader doesn't work for other websites.

I am using chrome `Version 79.0.3945.130 (Official Build) (64-bit)`, and just updated to `Version 80.0.3987.116 (Official Build) (64-bit)` and still have the same issue
I've noticed this issue for a while.
A specific websites that comes to mind is the environments/workspaces page for Visual Studio Online:
https://online.visualstudio.com/environments
It doesn't have the issue with the page *about* the service:
https://visualstudio.microsoft.com/services/visual-studio-online/

I previously had an issue with [The Amazon Web Services console ](https://us-east-2.console.aws.amazon.com/console/home?nc2=h_ct&region=us-east-2&src=header-signin#) when signed in, but the most recent Chrome update (80.0.3987.116) appears to have fixed that.

**Comment by forivall** [comment]
I'm having a similar issue, but I think i know what the issue is:

https://getpocket.com/explore/ doesn't have a dark mode, so i toggled dark reader on.

However, https://app.getpocket.com/ does have a dark mode built-in, but once i turned on dark reader for getpocket.com, i couldn't turn it off for app.getpocket.com .

getpocket.com/explore also needs
```
================================

getpocket.com

INVERT
.persistent-actions-container
```
in the dev tools.

**Comment by gregkolodny** [comment]
Yeah this does look similar to 935 , but I'm on Windows.

**Comment by gregkolodny** [comment]
@forivall Yeah this does look similar to 935 , but I'm on Windows.

**Comment by ysoftman** [comment]
I'm having a same issue.

**Comment by Gusted** [comment]
You can't toggle subdomains that's a know issue

**Comment by GalaxySH** [comment]
Should make it a feature. I also have the same issue on *some* websites.

**Comment by Gusted** [comment]
> Should make it a feature.

I'm just waiting until all bugs are fix and can proceed with breaking changes like #2517 That could fix this. As it's more focussed on subdomains

**Comment by narfanar** [comment]
Related:
Some websites, not all, show as `PDF` when opening a PDF page on them. This causes:
1. Can't use the keyboard shortcut to enable/disable Dark Reader for current "website"
2. Can't use flyout to enable/disable Dark Reader for current "website"

**Comment by xcjs** [comment]
I know this issue is from February 7th, but as of today I'm having the same issue.

It will seemingly randomly activate on sites I've previously disabled it on. It even shows DarkReader as being disabled for a particular domain, but when I inspect the page, the DarkReader style has been injected.

**Comment by Gusted** [comment]
> I know this issue is from February 7th, but as of today I'm having the same issue.
> 
> It will seemingly randomly activate on sites I've previously disabled it on. It even shows DarkReader as being disabled for a particular domain, but when I inspect the page, the DarkReader style has been injected.

 #3709

**Comment by xcjs** [comment]
@Gusted Thanks! I should have looked at more recent bugs.

**Comment by Yash-Singh1** [comment]
Looks like #3715 already fixed this. All the given links on the original issue work for me.

**Comment by Gusted** [comment]
> 
> 
> Looks like #3715 already fixed this. All the given links on the original issue work for me.

Nope, The fallback is been in their for a couple of weeks. And this issue dates from a lot of months back. It probably was temporary bug with our sitelist Logic.
