### ISSUE TITLE
High temperature cpu. (Macbook Pro 2019 13")

### ISSUE THREAD

**Issue by Arthvr96** [darkreader/darkreader#2029]
I am using this extension at google chrome on the two platforms (windows and macbook).
On the platform with windows i don't have any problems but on the macbook yes.

Istats menus shows that Cpu does't have high percent usage(10-30%)
but after 1-2 minutes of using google chrome, Cpu reaches 85-90 degrese.

I made test, because of the beginning i thought that is the problem with computer but after turn off dark reader, Cpu temp returned to normal status.
When i was using google chrome without this extension - cpu 45-55 degrees

I checked it on the two same models of macbook. The problem occurred in two cases.

**Comment by alexanderby** [comment]
Hi, are you using Filter mode?

**Comment by Arthvr96** [comment]
hi, yes

**Comment by alexanderby** [comment]
It used to be default 2 years ago.

**Comment by alexanderby** [comment]
The problem is that Filter mode requires GPU resources, and an older MacBook (or other device) with weak GPU and higher process of CPU can cause heating.

**Comment by Arthvr96** [comment]
I changed Filter Mode to another one and now the CPU temperature is slightly higher than without the dark reader turned on, so I can use it now without worrying about the cpu temp. 
Big thanks for the help!
