### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by shugo83** [darkreader/darkreader#203]
No way to easily reset to initial values of brightness, contrast etc

**Comment by orschiro** [comment]
Hi all, 

I agree. I have done a lot of testing and fiddling and now wish to revert everything back to default settings. 

A reset button would be much welcomed. :-) 

Yours

**Comment by alexanderby** [comment]
Until this is implemented, you can execute the following script in extensions debugger to clean all the settings:
```javascript
chrome.storage.sync.clear(() => chrome.runtime.reload());
```

**Comment by CollinChaffin** [comment]
This will NOT work if you are a power user who has exceeded the 8k sync and auto-switched to local storage.

## Instructions for Restoring Default Sliders/Engine (GLOBAL) _If Using LocalStorage_

1. Install the following Chrome extension (**I am not affiliated with this extension nor do I take any responsibility**):
a. https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb
2. Right-click the DarkReader toolbar button and click `Inspect Popup`
3. Click the new tab in the devtools window labeled `Storage Explorer`
4. There you will see ~10 key/value pairs including the `siteList`, `customThemes`, and current theme
5. Click the `notepad/pen icon` at the right of the key `theme`
6. Paste the following to replace current with these initial defaults (BACKUP CURRENT FOR SAFETY FIRST)
```json
{
	"brightness": 100,
	"contrast": 90,
	"engine": "svgFilter",
	"fontFamily": "Segoe UI",
	"grayscale": 0,
	"mode": 1,
	"sepia": 10,
	"stylesheet": "",
	"textStroke": 0,
	"useFont": false
}
```
7. Click `Save`
8. Either disable/re-enable the DarkReader extension by...
a. Right clicking DarkReader button, selecting `Manage Extensions` and toggling off/on or...
b. Restart Chrome
8. Refresh any open pages to see new setting

**Comment by BRA1L0R** [comment]
I know this is old and all, but since it is on the roadmap I fully implemented this feature, only problem is that I don't know where to put the button. I tried to fit it in the "More" tab but it's too big, I tried with the main tab but it looks awful / it doesn't fit in there... Where should I put it?

**Comment by BRA1L0R** [comment]
![Screenshot_20200409_212626](https://user-images.githubusercontent.com/17928339/78933066-f1ea9b00-7aa8-11ea-8471-565df5d0f2c3.png)

Here's how I implemented it

**Comment by Gusted** [comment]
Hi their!

I want to inform you all that I'm working on a reset button for the new UI as of darkreader V5
Current changes: https://github.com/darkreader/darkreader/compare/Reset-Button
Branch: https://github.com/darkreader/darkreader/tree/Reset-Button

**Comment by NatoBoram** [comment]
So... where's the reset button?

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then under Settings > Manage Settings.
