### ISSUE TITLE
Doesn't show automation menu on Yandex Browser (Android)

### ISSUE THREAD

**Issue by lanewu** [darkreader/darkreader#2036]
as shown in the snapshot, it's missing three dots on the right side
![zruwe](https://user-images.githubusercontent.com/9734453/75130169-d8afaa00-5707-11ea-99f7-8f4a12364624.jpg)

**Comment by Gusted** [comment]
Mobile browsers have a newer UI where by the automation settings in assecable without the 3 dots.
