### ISSUE TITLE
Stops working randomly, after latest Vivaldi update.

### ISSUE THREAD

**Issue by ktpx** [darkreader/darkreader#2039]
Not even sure if its supported on this browser, but its been working fine for a long time. It seems after the latest vivaldi update, Darkread stops working after a short while.  Only way to fix
is to restart browser, until it breaks again.  Have tried this on two different distros (fedora 31 and archlinux).   Vivaldo 2.11.1811.41 (Stable channel) (64-bit)

**Comment by Gusted** [comment]
Knowing from future Issues of you that this most likely had been resolved.
