### ISSUE TITLE
Dynamic mode - TypeError: syncStyle is null

### ISSUE THREAD

**Issue by senpl** [darkreader/darkreader#2041]
Dark Reader version 4.8.9
Tested in two browsers (vivaldi and firefox) on page:
https://m.autobid.de
it produce TypeError: syncStyle is null
in line 2633 const shouldRestore = syncStyle.sheet == null;
syncStyle is not checked if it is null before this line.
In vivaldi stacktrace is bigger:
`Uncaught TypeError: Cannot read property 'sheet' of null
    at Object.restore (index.js:2633)
    at index.js:3092
    at Set.forEach (<anonymous>)
    at index.js:3092
    at MutationObserver.handleMutations (index.js:2773)`
If more details is needed let me know.

**Comment by Gusted** [comment]
Hey their!

Could you try to check with the latest version of Darkreader (4.9.4) If this issue still persist I cannot reproduce this anymore.

**Comment by senpl** [comment]
It looks like in current version it works. Thanks for great work.
