### ISSUE TITLE
Light mode in STACK EXCHANGE COMMUNITIES turns to dark

### ISSUE THREAD

**Issue by Ynjxsjmh** [darkreader/darkreader#2048]
[StackOverflow](https://stackoverflow.com/) for example:

![image](https://user-images.githubusercontent.com/40143136/75517250-3bbb7c80-5a39-11ea-8e83-e1d336c355b8.png)

In fact, light mode works wrong in sites among https://stackexchange.com/sites

**Comment by Gusted** [comment]
![](https://i.imgur.com/fsFoRfc.png)
