### ISSUE TITLE
Icons replaced on office.com (Office 365)

### ISSUE THREAD

**Issue by iSnackyCracky** [darkreader/darkreader#2049]
On the Office 365 Dashboard page (logged in to https://www.office.com with an Office 365 business account) the Excel and SharePoint icons are "replaced", but this isn't necessary.

darkreader enabled:
![image](https://user-images.githubusercontent.com/20481463/75537141-c76fe180-5a16-11ea-9ef4-92a8fb0538ea.png)

darkreader disabled:
![image](https://user-images.githubusercontent.com/20481463/75537231-ecfceb00-5a16-11ea-9ecc-551c755791d8.png)

darkreader enabled, but default icon restored:
![image](https://user-images.githubusercontent.com/20481463/75537297-0b62e680-5a17-11ea-9434-0478876338a3.png)

Seems like the background-image `of span.ms-ohp-svg-Icon.ms-ohp-Icon.ms-ohp-Icon--excelLogo.ms-ohp-Icon--excelLogoFill.ng-star-inserted::before` and `span.ms-ohp-svg-Icon.ms-ohp-Icon.ms-ohp-Icon--sharepointLogo.ms-ohp-Icon--sharepointLogoFill.ng-star-inserted` gets "replaced".

Unfortuantely I wasn't sure how to fix this, in chromium dev-tools it looks like the change comes from an empty style-object:
![image](https://user-images.githubusercontent.com/20481463/75539240-37339b80-5a1a-11ea-8a34-c8db9bd43d8d.png)
`<style class="darkreader darkreader--sync" media="screen"></style>`

And I didn't find the stated `blob:https://www.office.com/85fb` anywhere.

**Comment by Gusted** [comment]
`office.com

CSS
.ms-ohp-svg-Icon.ms-ohp-Icon--excelLogo:before {
    background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PGcgZGF0YS1uYW1lPSJTVFlMRSA9IENPTE9SIj48cGF0aCBkPSJNMjAgMkg5LjMzM0ExLjMzMyAxLjMzMyAwIDAwOCAzLjMzM1Y5bDEyIDcgNiAyLjUzMkwzMiAxNlY5eiIgZmlsbD0iIzIxYTM2NiIvPjxwYXRoIGZpbGw9IiMxMDdjNDEiIGQ9Ik04IDloMTJ2N0g4eiIvPjxwYXRoIGQ9Ik0zMC42NjcgMkgyMHY3aDEyVjMuMzMzQTEuMzMzIDEuMzMzIDAgMDAzMC42NjcgMnoiIGZpbGw9IiMzM2M0ODEiLz48cGF0aCBkPSJNMjAgMTZIOHYxMi42NjdBMS4zMzMgMS4zMzMgMCAwMDkuMzMzIDMwaDIxLjMzNEExLjMzMyAxLjMzMyAwIDAwMzIgMjguNjY3VjIzeiIgZmlsbD0iIzE4NWMzNyIvPjxwYXRoIGZpbGw9IiMxMDdjNDEiIGQ9Ik0yMCAxNmgxMnY3SDIweiIvPjxwYXRoIGQ9Ik0xNi42NjcgN0g4djE5aDguNjY3QTEuMzM3IDEuMzM3IDAgMDAxOCAyNC42NjdWOC4zMzNBMS4zMzcgMS4zMzcgMCAwMDE2LjY2NyA3eiIgb3BhY2l0eT0iLjEiLz48cGF0aCBkPSJNMTUuNjY3IDhIOHYxOWg3LjY2N0ExLjMzNyAxLjMzNyAwIDAwMTcgMjUuNjY3VjkuMzMzQTEuMzM3IDEuMzM3IDAgMDAxNS42NjcgOHoiIG9wYWNpdHk9Ii4yIi8+PHBhdGggZD0iTTE1LjY2NyA4SDh2MTdoNy42NjdBMS4zMzcgMS4zMzcgMCAwMDE3IDIzLjY2N1Y5LjMzM0ExLjMzNyAxLjMzNyAwIDAwMTUuNjY3IDh6IiBvcGFjaXR5PSIuMiIvPjxwYXRoIGQ9Ik0xNC42NjcgOEg4djE3aDYuNjY3QTEuMzM3IDEuMzM3IDAgMDAxNiAyMy42NjdWOS4zMzNBMS4zMzcgMS4zMzcgMCAwMDE0LjY2NyA4eiIgb3BhY2l0eT0iLjIiLz48cGF0aCBkYXRhLW5hbWU9IkJhY2sgUGxhdGUiIGQ9Ik0xLjMzMyA4aDEzLjMzNEExLjMzMyAxLjMzMyAwIDAxMTYgOS4zMzN2MTMuMzM0QTEuMzMzIDEuMzMzIDAgMDExNC42NjcgMjRIMS4zMzNBMS4zMzMgMS4zMzMgMCAwMTAgMjIuNjY3VjkuMzMzQTEuMzMzIDEuMzMzIDAgMDExLjMzMyA4eiIgZmlsbD0iIzEwN2M0MSIvPjxwYXRoIGQ9Ik0zLjUzMyAyMWwzLjIzNi01LjAxNEwzLjgwNSAxMUg2LjE5bDEuNjE4IDMuMTg3cS4yMjMuNDUzLjMwNy42NzZoLjAyMXEuMTYtLjM2Mi4zMzUtLjcwNEwxMC4yIDExaDIuMTg5bC0zLjA0IDQuOTU4TDEyLjQ2NiAyMWgtMi4zM2wtMS44NjktMy41YTIuOTIyIDIuOTIyIDAgMDEtLjIyMy0uNDY4aC0uMDI4YTIuMjA3IDIuMjA3IDAgMDEtLjIxNi40NTNMNS44NzcgMjF6IiBmaWxsPSIjZmZmIi8+PHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgzMnYzMkgweiIvPjwvZz48L3N2Zz4=) center no-repeat !important;
    color: transparent !important
}

.ms-ohp-svg-Icon.ms-ohp-Icon--excelLogoFill:after {
    color: transparent !important
}

================================`
This will fix excel I don't have sharepoint so I can't really fix that logo 

I just basicly clicked on :before 
![](https://i.imgur.com/MoIiXnc.png) Clicked on right aboce the staticstyle 
Formatted it and copy pasted the 2 :before and :after into the dev tools and putted !important after it and it was fixed

**Comment by iSnackyCracky** [comment]
Yup, this works - did the same for SharePoint, so the full fix for both should be this:

```
office.com

CSS
.ms-ohp-Icon--excelLogo:before {
    background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PGcgZGF0YS1uYW1lPSJTVFlMRSA9IENPTE9SIj48cGF0aCBkPSJNMjAgMkg5LjMzM0ExLjMzMyAxLjMzMyAwIDAwOCAzLjMzM1Y5bDEyIDcgNiAyLjUzMkwzMiAxNlY5eiIgZmlsbD0iIzIxYTM2NiIvPjxwYXRoIGZpbGw9IiMxMDdjNDEiIGQ9Ik04IDloMTJ2N0g4eiIvPjxwYXRoIGQ9Ik0zMC42NjcgMkgyMHY3aDEyVjMuMzMzQTEuMzMzIDEuMzMzIDAgMDAzMC42NjcgMnoiIGZpbGw9IiMzM2M0ODEiLz48cGF0aCBkPSJNMjAgMTZIOHYxMi42NjdBMS4zMzMgMS4zMzMgMCAwMDkuMzMzIDMwaDIxLjMzNEExLjMzMyAxLjMzMyAwIDAwMzIgMjguNjY3VjIzeiIgZmlsbD0iIzE4NWMzNyIvPjxwYXRoIGZpbGw9IiMxMDdjNDEiIGQ9Ik0yMCAxNmgxMnY3SDIweiIvPjxwYXRoIGQ9Ik0xNi42NjcgN0g4djE5aDguNjY3QTEuMzM3IDEuMzM3IDAgMDAxOCAyNC42NjdWOC4zMzNBMS4zMzcgMS4zMzcgMCAwMDE2LjY2NyA3eiIgb3BhY2l0eT0iLjEiLz48cGF0aCBkPSJNMTUuNjY3IDhIOHYxOWg3LjY2N0ExLjMzNyAxLjMzNyAwIDAwMTcgMjUuNjY3VjkuMzMzQTEuMzM3IDEuMzM3IDAgMDAxNS42NjcgOHoiIG9wYWNpdHk9Ii4yIi8+PHBhdGggZD0iTTE1LjY2NyA4SDh2MTdoNy42NjdBMS4zMzcgMS4zMzcgMCAwMDE3IDIzLjY2N1Y5LjMzM0ExLjMzNyAxLjMzNyAwIDAwMTUuNjY3IDh6IiBvcGFjaXR5PSIuMiIvPjxwYXRoIGQ9Ik0xNC42NjcgOEg4djE3aDYuNjY3QTEuMzM3IDEuMzM3IDAgMDAxNiAyMy42NjdWOS4zMzNBMS4zMzcgMS4zMzcgMCAwMDE0LjY2NyA4eiIgb3BhY2l0eT0iLjIiLz48cGF0aCBkYXRhLW5hbWU9IkJhY2sgUGxhdGUiIGQ9Ik0xLjMzMyA4aDEzLjMzNEExLjMzMyAxLjMzMyAwIDAxMTYgOS4zMzN2MTMuMzM0QTEuMzMzIDEuMzMzIDAgMDExNC42NjcgMjRIMS4zMzNBMS4zMzMgMS4zMzMgMCAwMTAgMjIuNjY3VjkuMzMzQTEuMzMzIDEuMzMzIDAgMDExLjMzMyA4eiIgZmlsbD0iIzEwN2M0MSIvPjxwYXRoIGQ9Ik0zLjUzMyAyMWwzLjIzNi01LjAxNEwzLjgwNSAxMUg2LjE5bDEuNjE4IDMuMTg3cS4yMjMuNDUzLjMwNy42NzZoLjAyMXEuMTYtLjM2Mi4zMzUtLjcwNEwxMC4yIDExaDIuMTg5bC0zLjA0IDQuOTU4TDEyLjQ2NiAyMWgtMi4zM2wtMS44NjktMy41YTIuOTIyIDIuOTIyIDAgMDEtLjIyMy0uNDY4aC0uMDI4YTIuMjA3IDIuMjA3IDAgMDEtLjIxNi40NTNMNS44NzcgMjF6IiBmaWxsPSIjZmZmIi8+PHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgzMnYzMkgweiIvPjwvZz48L3N2Zz4=) center no-repeat !important;
}
.ms-ohp-Icon--sharepointLogo:before {
    background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PGcgZGF0YS1uYW1lPSJTVFlMRSA9IENPTE9SIj48Y2lyY2xlIGN4PSIxNSIgY3k9IjkuNSIgcj0iOS41IiBmaWxsPSIjMDM2YzcwIi8+PGNpcmNsZSBjeD0iMjMuODc1IiBjeT0iMTcuODc1IiByPSI4LjEyNSIgZmlsbD0iIzFhOWJhMSIvPjxjaXJjbGUgY3g9IjE2IiBjeT0iMjUuNSIgcj0iNi41IiBmaWxsPSIjMzdjNmQwIi8+PHBhdGggZD0iTTE2LjY2NyA3SDUuODMzQTkuNTA2IDkuNTA2IDAgMDAxNSAxOWMuMjc3IDAgLjU1MS0uMDEzLjgyMy0uMDM2bC4wMDUuMDM4QTYuNSA2LjUgMCAwMDkuNSAyNS41cTAgLjI1Mi4wMTkuNWg3LjE0OEExLjMzNyAxLjMzNyAwIDAwMTggMjQuNjY3VjguMzMzQTEuMzM3IDEuMzM3IDAgMDAxNi42NjcgN3oiIG9wYWNpdHk9Ii4xIi8+PHBhdGggZD0iTTE1LjY2NyA4SDUuNjE3QTkuNTA1IDkuNTA1IDAgMDAxNSAxOWMuMjc3IDAgLjU1MS0uMDEzLjgyMy0uMDM2bC4wMDUuMDM4QTYuNTA1IDYuNTA1IDAgMDA5LjY3NCAyN2g1Ljk5M0ExLjMzNyAxLjMzNyAwIDAwMTcgMjUuNjY3VjkuMzMzQTEuMzM3IDEuMzM3IDAgMDAxNS42NjcgOHoiIG9wYWNpdHk9Ii4yIi8+PHBhdGggZD0iTTE1LjY2NyA4SDUuNjE3QTkuNTA1IDkuNTA1IDAgMDAxNSAxOWMuMjc3IDAgLjU1MS0uMDEzLjgyMy0uMDM2bC4wMDUuMDM4QTYuNSA2LjUgMCAwMDkuNTE4IDI1aDYuMTQ5QTEuMzM3IDEuMzM3IDAgMDAxNyAyMy42NjdWOS4zMzNBMS4zMzcgMS4zMzcgMCAwMDE1LjY2NyA4eiIgb3BhY2l0eT0iLjIiLz48cGF0aCBkPSJNMTQuNjY3IDhoLTkuMDVBOS41MDUgOS41MDUgMCAwMDE1IDE5Yy4yNzcgMCAuNTUxLS4wMTMuODIzLS4wMzZsLjAwNS4wMzhBNi41IDYuNSAwIDAwOS41MTggMjVoNS4xNDlBMS4zMzcgMS4zMzcgMCAwMDE2IDIzLjY2N1Y5LjMzM0ExLjMzNyAxLjMzNyAwIDAwMTQuNjY3IDh6IiBvcGFjaXR5PSIuMiIvPjxwYXRoIGRhdGEtbmFtZT0iQmFjayBQbGF0ZSIgZD0iTTEuMzMzIDhoMTMuMzM0QTEuMzMzIDEuMzMzIDAgMDExNiA5LjMzM3YxMy4zMzRBMS4zMzMgMS4zMzMgMCAwMTE0LjY2NyAyNEgxLjMzM0ExLjMzMyAxLjMzMyAwIDAxMCAyMi42NjdWOS4zMzNBMS4zMzMgMS4zMzMgMCAwMTEuMzMzIDh6IiBmaWxsPSIjMDM3ODdjIi8+PHBhdGggZD0iTTUuNjcgMTUuODI1YTIuNjQ1IDIuNjQ1IDAgMDEtLjgyMi0uODcgMi4zNjEgMi4zNjEgMCAwMS0uMjg3LTEuMTkgMi4yOSAyLjI5IDAgMDEuNTMzLTEuNTQxQTMuMTQyIDMuMTQyIDAgMDE2LjUxIDExLjNhNS45ODIgNS45ODIgMCAwMTEuOTM1LS4zIDcuMzU0IDcuMzU0IDAgMDEyLjU0OS4zNTd2MS44YTMuOTg2IDMuOTg2IDAgMDAtMS4xNTMtLjQ3MSA1LjU5NiA1LjU5NiAwIDAwLTEuMzQ5LS4xNjIgMi45MjYgMi45MjYgMCAwMC0xLjM4Ni4yOTMuOTEuOTEgMCAwMC0uNTQ5LjgzMy44NDQuODQ0IDAgMDAuMjMzLjU5IDIuMTIyIDIuMTIyIDAgMDAuNjI3LjQ0OHEuMzk0LjE5NiAxLjE3Ni41MmExLjIzMiAxLjIzMiAwIDAxLjE2OS4wNjcgOS42OTcgOS42OTcgMCAwMTEuNDgzLjczMiAyLjY1NCAyLjY1NCAwIDAxLjg3Ny44ODMgMi41NTggMi41NTggMCAwMS4zMTcgMS4zMzIgMi40OCAyLjQ4IDAgMDEtLjQ5OSAxLjYwNSAyLjc4OSAyLjc4OSAwIDAxLTEuMzM1Ljg5NkE2LjA0OSA2LjA0OSAwIDAxNy43MDMgMjFhMTAuMDI4IDEwLjAyOCAwIDAxLTEuNzIyLS4xNDIgNS45MTIgNS45MTIgMCAwMS0xLjQtLjQwNHYtMS45MDJhNC41IDQuNSAwIDAwMS40MTYuNjc1IDUuNTEzIDUuNTEzIDAgMDAxLjU1OC4yNSAyLjY4IDIuNjggMCAwMDEuNDEzLS4zLjk0Ny45NDcgMCAwMC40NzUtLjg0Ny45MDQuOTA0IDAgMDAtLjI2Ni0uNjQ4IDIuNzA0IDIuNzA0IDAgMDAtLjczNS0uNTEycS0uNDY5LS4yMzYtMS4zODYtLjYyYTcuODYgNy44NiAwIDAxLTEuMzg2LS43MjV6IiBmaWxsPSIjZmZmIi8+PHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgzMnYzMkgweiIvPjwvZz48L3N2Zz4=) center no-repeat !important;
}
```

But I still think this isn't the best way to solve this, as there is no reason to replace the icon in the first place, I guess.

**Comment by Gusted** [comment]
> But I still think this isn't the best way to solve this, as there is no reason to replace the icon in the first place, I guess.

Ehm actually we do + we add those  `center no-repeat` add the end that orginially also use in the css only dark reader removes those? idk why and than with some icons it doesn't show anymore/not correct

**Comment by iSnackyCracky** [comment]
Hey guys,

not exactly sure why this got closed already, as the now merged pull request first of all only addresses the Excel logo (SharePoint still "broken"), and second replaces the logo with a kind of "quick and dirty" css "hackery".

Not to blame you for creating this logo. With css only, respect for that! It's probably a good choice to not put images into the fixes-file. But I don't think this is a proper solution to the issue.

Again, I'm not exactly sure why and how (as the referenced style-tag is just empty) the original icons get replaced by a URL to the SVG which then has the darkreader-image-filter applied to it.

**Comment by Gusted** [comment]
I didn't create the image I just copy paste the css from how Microsoft loads te images and putted the no-repeat and center behind it

**Comment by alexanderby** [comment]
@iSnackyCracky Thanks for pointing out about the Sharepoint logo, it didn't show up to me, I will make a similar fix.

Dark Reader decided, that it is a dark icon, so it inverted it to look good on dark background. I think I will adjust a threshold for colorful icons. Another problem is that `background-size` CSS property was needed for some reason. There is a common issue, when `background-image` property includes `background-position` and `background-repeat`, icons can shift. I will try to find a solution.

**Comment by Gusted** [comment]
Hey their I just saw their was an sharepoint fix in the latest darkeader 4.9.4 
```.ms-ohp-svg-Icon.ms-ohp-Icon--sharepointLogo::before {
    background-color: #03787c !important;
    content: "s" !important;
}`` Could you check if this is the same for you?

**Comment by iSnackyCracky** [comment]
Hi, the Office / Microsoft 365 Startpage got a redesign and the fix is not longer needed:

![image](https://user-images.githubusercontent.com/20481463/89886101-5e4ae780-dbcc-11ea-9864-94b489462c85.png)

**Comment by Gusted** [comment]
👍🏽
