### ISSUE TITLE
firefox search engine icon issue. omnibox and preference 

### ISSUE THREAD

**Issue by fazlul101** [darkreader/darkreader#2053]
search engine icon issue
![Annotation 2020-02-28 225007](https://user-images.githubusercontent.com/40009952/75570435-2bc58c00-5a7d-11ea-8c79-08b3342094e1.png)

Wikipedia Logo issue
![Annotation 2020-02-28 225432](https://user-images.githubusercontent.com/40009952/75570522-50b9ff00-5a7d-11ea-99c9-5cba6dd7ba29.png)

**Comment by Gusted** [comment]
The wikipedia Logo would look like this

![](https://i.imgur.com/Kpi4I0b.png)

**Comment by AndrewDaGuy** [comment]
> search engine icon issue
> ![Annotation 2020-02-28 225007](https://user-images.githubusercontent.com/40009952/75570435-2bc58c00-5a7d-11ea-8c79-08b3342094e1.png)

I'm pretty sure that "Search engine icon issue" is on your side, from what I remember dark reader cannot do things to settings, addons page, etc. .
