### ISSUE TITLE
youtube comment like isnt changing color after liking the comment

### ISSUE THREAD

**Issue by fazlul101** [darkreader/darkreader#2054]

**Comment by Gusted** [comment]
Could only reproduce when:
1. Like comment
2. Still hover it 

Than it won't update the color, after not more hovering above it. It would update. Will make a fix for this.

**Comment by Gusted** [comment]
("https://i.imgur.com/nhMl7wY.gifv") Fixed

**Comment by Gusted** [comment]
Resolved trough #2058

**Comment by fazlul101** [comment]
Issue are in Firefox

**Comment by Gusted** [comment]
Can you confirm that you have the newest version and have the patch used else I'm gonna take a look trough Firefox if it have it installed somewhere

**Comment by fazlul101** [comment]
Yes I’m using Firefox 73 the latest version

**Comment by fazlul101** [comment]
working thank man

**Comment by Gusted** [comment]
Fixed
