### ISSUE TITLE
SubDomains unable to work if main Domain is disabled

### ISSUE THREAD

**Issue by Freeplayg** [darkreader/darkreader#2055]
Example: If the plugin is disabled on https://yagpdb.xyz, it is unable to work on its subdomains like https://docs.yagpdb.xyz.

Video: 
https://streamable.com/nhjyq

**Comment by truesilver92** [comment]
Also settings per site effect all subdomains. bandcamp.com is a good example of wanting different mode/filter settings on each subdomain. They are different sites altogether

**Comment by Gusted** [comment]
![](https://i.imgur.com/meAh8va.png)

**Comment by alexanderby** [comment]
Should be fixed already.
