### ISSUE TITLE
Currently possible to see all sites with changes from defaults?

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#2057]
I gave Dark Reader a try recently.  _**Great job!  It's very impressive!**_ :)

In certain ambient light conditions, I felt the need to temporarily modify the brightness, sepia level, or other parameters of certain sites.

When I would return to these sites on another day with different ambient light conditions, I didn't like the changes I made, and would have to reset them.

What I really want is **some way to see all the sites for which I have configured custom settings**, and be able to reset specific sites to default.

This similar extension does a good job at accomplishing this task:   
https://addons.mozilla.org/firefox/addon/dark-background-light-text/

Is this currently possible in Dark Reader?  If not, is there a guesstimate as to when it might be implemented?

BTW, for the time being I uninstalled Dark Reader because of this issue and because it felt like it was making Firefox much less responsive, even when not using the Dynamic Mode.  I didn't run any tests to confirm this observation, so I consider my findings uncomfirmed.

**Comment by Gusted** [comment]
A reset button for the Filter Settings has been added in the new UI.

```
Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.

```
