### ISSUE TITLE
Red Hat website issue

### ISSUE THREAD

**Issue by UchihaSR** [darkreader/darkreader#2067]
when i went to red hat officiak website to chck the ex-200 exam objective. i encountered this situation

 
![rhcsa_darkreader](https://user-images.githubusercontent.com/52357560/75856423-58c9c400-5e1a-11ea-86e3-c95f63eaa863.jpg)

**Comment by Gusted** [comment]
https://www.redhat.com use for some elements like the panels #shadow-root (open) [More info](https://stackoverflow.com/questions/34119639/what-is-shadow-root) and that means the have their own DOM and I think when darkreaders gets all element. It won't detect whats in shadow root. I will take a look a make CSS fix for redhat what probaly gonna make it little bit better. A lot of the elements have same classes....

**Comment by Gusted** [comment]
I have now got just this

`
================================

redhat.com

CSS
p, li {
   color: ${black}
}
.PFElement {
    background-color: ${white};
}

================================`

**Comment by Gusted** [comment]
Hi their! 
Could you please try to get the latest version of Darkreader 4.9.4 and check if this issue still persist?

**Comment by UchihaSR** [comment]
yes, it is solved now. Thanks
