### ISSUE TITLE
[Bug] DR causes massive CPU issues when active on inspected pages (Chromium devtools)

### ISSUE THREAD

**Issue by narcolepticinsomniac** [darkreader/darkreader#2070]
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
DR 4.8.9
Win 8.1

This has been a problem I've been running into for a long time, and I finally got around to troubleshooting. To my surprise, seems like DR was the problem.

Basically, when you inspect most pages DR is active on, once you hover the DOM tree, CPU spikes through the roof, at least an additional 50-70%, often more, and never releases. I made a [screen record](https://streamable.com/vjd48) to demo, first without DR enabled, then with it enabled. CoreTemp is active in the system tray, and the green indicator is CPU. Bear in mind, OBS is running which averages about 5-10% CPU.

As you'll see, without DR active, hovering the DOM in devtools will very briefly spike ~5-10% when the mouse is active, and almost immediately normalize once the mouse stops. When DR is active, hovering the DOM tree causes CPU to skyrocket and never release. OBS actually throws an encoding warning, the CPU spikes so dramatically.

This is not true for every page DR is active on. In my testing, a few seemed unaffected (Github for example), but the vast majority are affected.

Steps to repro:

* New Google Chrome profile

* New DR install

* Visit:  https://example.com/

* Open devtools and hover DOM tree nodes while observing CPU

**Comment by narcolepticinsomniac** [comment]
Apparently, this is a Chromium bug, which DR triggers for whatever reason. It also occurs without DR being active, just nowhere near as consistently. I filed a bug report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1062574).

**Comment by Gusted** [comment]
Bug report seems fixed

**Comment by narcolepticinsomniac** [comment]
@Gusted If you read that bug report, you'll see that the Chromium team's idea of "fixed" is delusional. Unnecessary CPU consumption when elements are highlighted via devtools was 50-80%. They've reduced that to ~20% and given themselves a pat on the back for a job well done. This is still gonna be problematic for the foreseeable future.

As mentioned in the report, this doesn't occur on all pages. Wild guess is maybe 20%, and there is the known trigger of active animations. Problem is, the bug is present on every page on which DR is active. I realize this isn't DR's fault, but if there's any chance you could pinpoint what's triggering it, and it isn't essential, it'd improve devtools performance dramatically in Chromium, when they're used alongside DR.

**Comment by Gusted** [comment]
@narcolepticinsomniac 
I really don't know where to pinpoint as we don't do anything to devtools directly.
Also it's directly into the devtools itself the high power usage. I first thought it could be the page itself but Ending the sub-process(Windows 10 open the collapsed chromium) causing the high power-usage ends the devtools. Also weird that when hovering over non-elements(e.g. elements in head) that doesn't show up on the page it's being high power-usage. 


Also it's pure rendering issue as my GPU(RTX 2060 SUPER) usage is spiking. So could it be simply the animation(blue thingy) the problem? You know about the animations of discord typing causing a high usage.

**Comment by Gusted** [comment]
EDIT: It seems like using the arrows(up and down) is causing it to be constant high-power usage, well going with the mouse is harder to get high power-usage. Oh for me it really doesn't matter dark reader enabled or disabled it shows the same behavior.

![](https://i.imgur.com/5xVNlOU.gif)

**Comment by narcolepticinsomniac** [comment]
> Oh for me it really doesn't matter dark reader enabled or disabled it shows the same behavior.

Regardless of DR, this bug is triggered on many pages, but not the majority. Like I said, maybe 1/5. I can repro on every page when DR is active though. It's twice as bad in v80, which I'm still currently using, but I see the same exact issue in Canary, only instead of 50-80%, it's 20-30%.

Take [this example](https://torrentfreak.com/). If DR is active, CPU spikes high and never releases while hovering DOM nodes. If you exclude the site from DR applying style to it, the behavior immediately normalizes. We know that certain properties like animations can trigger this bug, so DR obviously applies something which triggers it on every page which it applies styles to.

I haven't worked out what DR does, which triggers this bug so consistently, but it's definitely something. My money would be on something CSS related.

**Comment by Gusted** [comment]
> My money would be on something CSS related.

I really don't know, I'm not a browser developer that can attach some native debugging.
Il open up another chromium bug report, however this time Nothing related to the previous so it can be marked as *duplicate*(Something they like to do even when it's totally not even the same issue)

**Comment by Gusted** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1123324 🤷🏽‍♀️ Now we can wait.

**Comment by narcolepticinsomniac** [comment]
>Il open up another chromium bug report,

Cool, somebody needed to. It's absolutely mind-boggling to me that they think constant 20-30% CPU usage when hovering DOM nodes is acceptable. I have zero faith that they'll actually do anything more though. The response in the original issue was that they improved it as much as they could without completely redesigning highlighting. If highlighting is that flawed, redesigning it entirely is exactly what they need to do.

In the meantime, I asked tophf to take a look and see if he can't shed any light on what DR does which triggers this bug so consistently. Depends whether or not it piques his curiosity, but he's pretty great at debugging in Chromium.

**Comment by Gusted** [comment]
Wow, even the native devtools of the devtools window can easily be reproduced with this issue when I tried to find what's happening on the Javascript/CSS side.
![](https://i.imgur.com/Iscygdx.gif)

**Comment by narcolepticinsomniac** [comment]
Here's [what tophf found](https://github.com/openstyles/stylus/issues/883#issuecomment-683376145). Not what I expected, but he seems to think it could be resolved on your end.
