### ISSUE TITLE
[Feature Request] Dark Mode for PDF's

### ISSUE THREAD

**Issue by ylax** [darkreader/darkreader#2074]
Would be awesome to add this! Happy to contribute.

**Comment by Gusted** [comment]
Did you mean like this *Inverting the PDF* 
Before
![Before](https://i.imgur.com/xbGpFYp.jpg)

After
![After](https://i.imgur.com/9Qup0gt.jpg)

**Comment by ylax** [comment]
Yes...

**Comment by Gusted** [comment]
It could be a nice feature but not everyone wants It... That's why it's not implemented yet

**Comment by Gusted** [comment]
Add the highlighted line to the dev tools in dark reader extension 
!(https://i.imgur.com/prFqGFe.png)

**Comment by absorber** [comment]
For those that prefer to copy text instead of doing manual OCR from an image:

`*[type="application/pdf"]`

**Comment by ylax** [comment]
Didn't seem to work. Did that work for you @absorber ?

**Comment by Gusted** [comment]
@ylax did you pressed on apply?

**Comment by absorber** [comment]
@ylax yes, it worked for me.

**Comment by Qsefawd** [comment]
Weird. I've inputted the code and hit apply. There's an "!" on the dev tools button and I couldn't get the same result.

Where did I go wrong? I was testing a pdf file on my desktop in chrome.

**Comment by ylax** [comment]
@Qsefawd , ya I'm starting to think that the problem lies with the fact that I'm viewing a local PDF. However, I did make sure, I think, that Dark Reader is set to trigger on my local drive. Hm...

Well, here are my settings:

![image](https://user-images.githubusercontent.com/10964019/76110376-0ddbb800-5fa4-11ea-874a-6a2210a903ab.png)

I think it's supposed to work for files on my local drive:

![image](https://user-images.githubusercontent.com/10964019/76110529-4b404580-5fa4-11ea-82e6-7620be3073a7.png)

And, this:

![image](https://user-images.githubusercontent.com/10964019/76110733-a7a36500-5fa4-11ea-9590-ec516d7b60b3.png)

I also did these:

- Hit 'Apply'
- Restarted Chrome
- Ensured changes to settings were still there after restart

**Comment by Gusted** [comment]
Dark reader won't work on local files.
If you have python you can setup a local server than it will work

**Comment by Gusted** [comment]
> Weird. I've inputted the code and hit apply. There's an "!" on the dev tools button and I couldn't get the same result.
> 
> Where did I go wrong? I was testing a pdf file on my desktop in chrome.

That's means you have a modified version because you putted pdf in the invert thingy

**Comment by ylax** [comment]
> Dark reader won't work on local files.
> If you have python you can setup a local server than it will work

Thanks @Gusted ! Just tried it with a web-based PDF and it worked fine.

**Comment by Gusted** [comment]
Due to how chromes handles extension the cannot modify local files or access them because yeah than it will be easy to make malicious code for them

**Comment by absorber** [comment]
I'm on Linux. I simply copied the directory where the PDF resides (or copied the full path to the PDF using `readlink -f <file>`), then I pasted that into my Chromium URL bar. I was able to view the PDF with DarkReader's color inversion / darkening being applied to it.

**Comment by Gusted** [comment]
Hmm weird in brave also chromium based wouldnt work on Windows 10

**Comment by Qsefawd** [comment]
> That's means you have a modified version because you putted pdf in the invert thingy

I didn't modify any of dark reader other than trying this. Didn't put pdf in either of the invert listed too.

how do I use it through python? I really like to have my pdfs in dark mode.

**Comment by Gusted** [comment]
Then press reset and then apply than the ! Will go away

For the python part:
1. Go to the folder where you pdf is in 
2. Copy the path to that folder 
3. Open command prompt
4. Type 'python -m http.server 8080'
5. Open in your browser 'localhost:8080'
6. Click on the pdf file on the site

Note make sure you have  *[type="application/pdf"] in the Invert list of *

**Comment by Qsefawd** [comment]
How did you manage to enter *[type="application/pdf"] into the invert listed of? It doesn't save when I hit enter.

**Comment by Gusted** [comment]
> Add the highlighted line to the dev tools in dark reader extension
> ![](https://camo.githubusercontent.com/bd399c099f2f4d7066b58c11261ff6bbd6fb2a5e/68747470733a2f2f692e696d6775722e636f6d2f707246714746652e706e67)

Youneed to open the dev tools on the right low button

**Comment by Qsefawd** [comment]
oh my gosh. i've never been so dumb in doing computer stuff before. could you do a short gif on the whole process inc. the python? totally can't get it to work on my end. argh.

**Comment by Gusted** [comment]
Yea sure give me 2 minutes

**Comment by Qsefawd** [comment]
> Yea sure give me 2 minutes

Take your time. No rush. :)

**Comment by Gusted** [comment]
Woops the gif was never encoded in ShareX lemme do it now right I'm sorry

**Comment by Gusted** [comment]
Just found out you don't need to host it onto a localhost to be darken very weird but you just need to have the '*[type="application/pdf"]' in the invert section and than it will be alright

**Comment by McSpooder** [comment]
> Just found out you don't need to host it onto a localhost to be darken very weird but you just need to have the '*[type="application/pdf"]' in the invert section and than it will be alright

Tried it today with the following chrome version: Version 80.0.3987.163.

PDF is hosted on local C:\ drive.

It didn't work. :(

**Comment by Gusted** [comment]
Nope you need to host it on a local host server to work it or read Darkreader faq how to enable it for local files chrome://extensions > darkreader > toggle Local files? Or something in that direction

**Comment by McSpooder** [comment]
@Gusted 

Thanks, you're right.

To make it work on local files just go to setting>extensions>dark reader > more info > toggle local files.

**Comment by bric3** [comment]
Is there a similar setting for Firefox ?

**Comment by Gusted** [comment]
> Is there a similar setting for Firefox ?

Don't know 1 2 3. But Their was a setting for it. Search it up

**Comment by ylax** [comment]
Thanks, @Gusted! Finally got this to work.

**Comment by Gusted** [comment]
The authar has it's issue been fixed! That means this Issue going to be closed If any of the other participants have issues, feel free to open an issue with details!

Regards,

Gusted

**Comment by Gusted** [comment]
> Thanks, @Gusted! Finally got this to work.
> 
> You guys think this issue should be closed since it seems to be resolved/the feature already exists?

Be patient xD

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
