### ISSUE TITLE
YouTube video upload date is white instead of gray

### ISSUE THREAD

**Issue by Perkzitos** [darkreader/darkreader#2082]
All elements near the upload date are gray. I already disabled YouTube's Dark Mode.
Screenshot proof (Brazilian Portuguese language):
![image](https://user-images.githubusercontent.com/30274161/76118895-041a7a80-5fcd-11ea-9104-d9bf288eadb1.png)

**Comment by Gusted** [comment]
`#date yt-formatted-string.ytd-video-primary-info-renderer {
    color: var(--yt-spec-text-secondary) !important;
}`
Will make a pull request for it :)

![](https://i.imgur.com/JXWgT3C.png)

**Comment by Gusted** [comment]
#2085 Fix this issue :)

**Comment by Perkzitos** [comment]
Thanks @Gusted! I do not know how to mess with this things.

**Comment by Gusted** [comment]
#2085 has been merged. Long long time ago.
