### ISSUE TITLE
How can I add more fonts?

### ISSUE THREAD

**Issue by josezulu** [darkreader/darkreader#2088]
I'm using Firefox, and it only has 6 fonts available. How can I add more fonts? It doesn't seem to be picking up fonts I added to my system (Win 10).

Thanks, great extension!

**Comment by Gusted** [comment]
Will look into it. This is probaly a bug with firefox and how darkreader/typescript fetch fonts With a chromium based browser is theren't a issue with it.

**Comment by Gusted** [comment]
I think so far I see now Firefox hasn't a function for it yet...
As you can see [here](https://github.com/darkreader/darkreader/blob/master/src/background/utils/extension-api.ts#L34)
Only chromium based browsers have support for fonts but I will dig around in firefox documentation to look if there is a workaround.

**Comment by josezulu** [comment]
Thanks for looking into it.
Somehow darkreader had selected "Segoe UI" font, which is what I usually choose. Now, I don't know if that is a coincidence, or perhaps it was supported in a previous version of Firefox and the setting stayed there? (though it doesn't display that font type)

**Comment by Gusted** [comment]
Segoe UI is the default font that Dark reade use
BTW firefox doesn't fetch a font list.. not vanilla or natively

**Comment by alexanderby** [comment]
Firefox doesn't have an API to list all installed fonts, so you can type-in any manually.

**Comment by josezulu** [comment]
@alexanderby thanks.
Indeed, typing "Segoe UI" worked.
