### ISSUE TITLE
LinkedIn - black badges color since 4.8.10

### ISSUE THREAD

**Issue by Myshor** [darkreader/darkreader#2089]
After 4.8.10 release I see that all circle badges on linkedin.com have dark background.
![image](https://user-images.githubusercontent.com/56877029/76143613-2d90e000-6079-11ea-95e9-01ad25df81c2.png)
And I found there is some !important setting for background-color for whole body when dark mode is enabled.

I don't see that !important entries when I disable dark mode.
And yes... It was working fine before 4.8.10. ;)

**Comment by Gusted** [comment]
What is the real issue here?
Do you mean that you want a white background-color?

The !important are their to overwrite the current style so the dark style will overwrite all the current CSS. They wont show up when it's disabled because the dark style isn't injected and the normal linkedin CSS is used that don't use !Important.

**Comment by Myshor** [comment]
Real issue is that notification badges on upper icons have red background - as it can be seen on the right in the developers tool when you inspect element. (striked through)

Down badges are full green if someone is online and outline green if away.
![image](https://user-images.githubusercontent.com/56877029/76150137-4fa15700-60a7-11ea-97a1-71609848497a.png)

I could make CSS fixes in dynamic-theme-fixes for that but it wasn't necessary earlier.
I think there was some changes regarding linkedin inside main extension code.

@alexanderby Give some reply if there should be CSS fix done or there will be other fixes in the code. ;)

**Comment by Myshor** [comment]
One more thing... comparing to light mode there are more elements that background is broken now with this forcing background in dark mode:
![image](https://user-images.githubusercontent.com/56877029/76150348-dbb47e00-60a9-11ea-979f-06b0ebf8a31f.png)
In light:
![image](https://user-images.githubusercontent.com/56877029/76150351-e4a54f80-60a9-11ea-9c52-802557949dc7.png)

**Comment by alexanderby** [comment]
There is such a `<style>` element with class `darkreader--fallback`. It prevent white flashes until all `<link rel="stylesheet">` elements finished loading and their `sheet` property is available. Maybe there is some network error, I don't know, what could happen, the Dynamic mode algorithm was not changed

**Comment by Myshor** [comment]
So question: Should I make CSS fixes for this elements to have correct background / border colors or not yet? ;) It even makes search box almost invisible (only placeholder gives a tip you can enter something there).

**Comment by alexanderby** [comment]
I think I've found the issue, there's such a `<link rel="stylesheet" href="https://static-exp1.licdn.com/sc/h/br/2cad6qk5ldigg0y6fm26l36k" disabled="">`, and this `disabled` attribute makes `sheet` property to be `null`. I will provide some fix.
