### ISSUE TITLE
Code blocks dissapear when dark reader is turned on. 

### ISSUE THREAD

**Issue by theairbend3r** [darkreader/darkreader#2091]
Code blocks on blogs such as medium.com and elsewhere disappear when dark mode is turned on.

## Light mode - 
![image](https://user-images.githubusercontent.com/60727948/76158644-ffc19f00-613d-11ea-8608-6c9138815e9a.png)

## Dark mode - 
![image](https://user-images.githubusercontent.com/60727948/76158650-136d0580-613e-11ea-8020-3ee6ede1aa94.png)

**Comment by Gusted** [comment]
Could you provide an exemple link?

**Comment by theairbend3r** [comment]
https://towardsdatascience.com/pytorch-basics-how-to-train-your-neural-net-intro-to-rnn-cb6ebc594677

**Comment by Gusted** [comment]
`================================

towardsdatascience.com

CSS
.kd {
    background: ${rgba(0, 0, 0, 0.05)} !important
}

================================`

I cannot make a global fix for the site every page use another selector for the background :(

**Comment by Gusted** [comment]
https://i.imgur.com/nLp0LCt.jpg
