### ISSUE TITLE
Is there a practical way to globally disable Dark Reader except for some specific sites?

### ISSUE THREAD

**Issue by zetapulse** [darkreader/darkreader#2093]
Clicking it OFF disables all the options in the box so I can't, say, click it ON "Only for this site".

**Comment by Gusted** [comment]
Duplicate of #2017

**Comment by Xerus2000** [comment]
Yep, exists: Site List > Invert listed only

**Comment by Gusted** [comment]
#2017 and https://github.com/darkreader/darkreader/issues/2093#issuecomment-611449556
