### ISSUE TITLE
Allow an option to switch dark/light themes based on time period.

### ISSUE THREAD

**Issue by roket1428** [darkreader/darkreader#2102]
The idea of having "active hours" in DarkReader is great, but having an option to switch themes for the rest of the time would be a greater idea. Like in the morning, you can have some sort of Sepia theme, and at the night, you can have a darker variant, or you can add some sort of "In this time period, I want a light theme, in this time period, I want a darker theme, in this period, I want completely black theme.", you get the idea.

**Comment by rickstaa** [comment]
@roket1428 I came here to request exactly the same feature. I just found out that is already a feature request for this feature (see #10 ) and it is also on the current [roadmap](https://github.com/darkreader/darkreader/projects/1) :rocket:.

**Comment by roket1428** [comment]
> @roket1428 I came here to request exactly the same feature. I just found out that is already a feature request for this feature (see #10) and it is also on the current [roadmap](https://github.com/darkreader/darkreader/projects/1) rocket.

I couldn't find it, can you please give an exact issue number?

**Comment by Gusted** [comment]
> I couldn't find it, can you please give an exact issue number?
https://github.com/darkreader/darkreader/issues/10

**Comment by roket1428** [comment]
> > I couldn't find it, can you please give an exact issue number?
> 
> [THIS ISSUE](https://github.com/darkreader/darkreader/issues/10)

No need to scream, this guy's talking about having an "active hours" feature. Mine is different as far as I can see.

**Comment by Gusted** [comment]
Ah I see.

**Comment by rickstaa** [comment]
@roket1428 I see thanks for pointing that out. I assumed the functionality you described would fall under the 'active hours' roadmap item. Meaning that it would have a [flux like](https://justgetflux.com/) transition period between the two themes.

**Comment by roket1428** [comment]
> @roket1428 I see thanks for pointing that out. I assumed the functionality you described would fall under the 'active hours' roadmap item. Meaning that it would have a [flux like](https://justgetflux.com/) transition period between the two themes.

Not just between *two" themes, like having a spreadsheet kinda thing to decide between *saved themes*.
