### ISSUE TITLE
YouTube Subscribe button is Pink instead of Red

### ISSUE THREAD

**Issue by Perkzitos** [darkreader/darkreader#2106]
The YouTube Subscribe button is Pink instead of Red, and that makes it very ugly. Could you make him Red again?

**Comment by Gusted** [comment]
Like this colour 
![](https://i.imgur.com/Te0SQys.png)

**Comment by r00ta** [comment]
I think the quick fix is to disable the darkreader for youtube.com and enable the native dark theme on youtube :)

**Comment by Gusted** [comment]
The native one is semi dark its shows a lot of dark gray

**Comment by Gusted** [comment]
Somehow I didn't mentioned it but it has been merged long long ago.
