### ISSUE TITLE
Google translator icons are displayed incorrectly when page zoom is above 100.

### ISSUE THREAD

**Issue by dunhao** [darkreader/darkreader#2111]
How to reproduce:
- Enable dark reader extension
- Go to translate.google.com
- Ctrl + = to zoom page level to 125%
- See mic icon, star icon, copy icon has glitch

- Also happens when system scale is enabled to 125% and chrome page level is 100%, which chrome will technically set page level to 125% and just display it as 100%. In this case, zoom out page level to 80% (which is same as 100% for 100% scale) to see icons are displayed correctly and error gone.

System:
- Windows 1909 Pro
- Chrome 80.0.3987.132
- Display FHD 1980 x 1020

ScreenShot:
- System scale 100%, chrome 125%
![image](https://user-images.githubusercontent.com/26085551/76640250-e068ae80-654f-11ea-9c92-f4e7ee2e480c.png)

- System scale 125%, chrome 100%
![image](https://user-images.githubusercontent.com/26085551/76638488-cc6f7d80-654c-11ea-858f-c179cf001f1a.png)

**Comment by Gusted** [comment]
Can confirm on 1366x768
125% zoom
I will look into this.
![](https://i.imgur.com/TYk5H2D.jpg)

**Comment by Gusted** [comment]
Created A fix for the issue :) #2112
