### ISSUE TITLE
Website broke with dark reader on

### ISSUE THREAD

**Issue by Prajwal-Koirala** [darkreader/darkreader#2120]
Hello,
So I have the dark reader on, on the website `upwork.com` and it quite broken.

![Capture](https://user-images.githubusercontent.com/16564273/76685097-64ba4080-65e7-11ea-947f-4efad56a5d81.PNG)

**Comment by Gusted** [comment]
Are you using dynamic Thema?

**Comment by Prajwal-Koirala** [comment]
> Are you using dynamic Thema?

yes

**Comment by Kyr4loO** [comment]
i have the same problem 
![image](https://user-images.githubusercontent.com/24955106/77852379-a0a3f700-71de-11ea-8df2-09ec6e61b8e0.png)

**Comment by Gusted** [comment]
Make a sperate issue that is youtube.com

**Comment by Gusted** [comment]
Extension bug couldn't fix upwork.com

**Comment by Gusted** [comment]
Should be fixed.
