### ISSUE TITLE
Octotree header is not dark for the default theme

### ISSUE THREAD

**Issue by hologerry** [darkreader/darkreader#2128]
<img width="324" alt="Screen Shot 2020-03-16 at 02 47 35" src="https://user-images.githubusercontent.com/11660168/76708274-883cd280-6730-11ea-9c69-9ad53fc17da3.png">

**Comment by Gusted** [comment]
The whole octotree is just been inverted it would be some 200 or more likes of code to make it perfect dark.

**Comment by hologerry** [comment]
Looking forward to it.
😊

**Comment by hologerry** [comment]
Any updates?
Thanks a lot!

**Comment by Gusted** [comment]
Well they use Injected stylesheet and I don't know any current API to get all injected Stylesheets and override them.

**Comment by hologerry** [comment]
Both the Github and Octotree have nice dark mode now, there is no need to remain this open~
Thanks.
