### ISSUE TITLE
[Feature Request] Support port 80

### ISSUE THREAD

**Issue by lonix1** [darkreader/darkreader#2131]
I want
- `www.example.com` to be normal (i.e. port 80)
- `www.example.com:5000` to be dark
- `foo.example.com` to be dark

So I use the blacklist ("Not invert list"), and add `www.example:com:80`.

I expect that everything will be dark, except port 80.

But it doesn't work - the `:80` port is ignored. Therefore `www.example.com` is dark.

I think `www.example.com:80` is treated the same as `www.example.com`. But they are different - if port 80 is specified it should take precedence.

**Comment by Gusted** [comment]
#373

**Comment by lonix1** [comment]
@Gusted Yes I agree a regex approach would be great, and cover all cases.

But keep in mind this is port 80 we're talking about. Until something complex like that issue is implemented (if ever), it would be a good to at least cover the basics.

**Comment by Gusted** [comment]
I will look into the code to handle ports a little better cannot guarantee anything

**Comment by Gusted** [comment]
Okay after taking some time to test. Because of browsers URL behaviours most common ports like 443(https) and 80(http) are be treated as just the url without the port therefor darkreader cannot see if it's port 80 or port 443 or just the normal URL.

**Comment by lonix1** [comment]
That is really unfortunate! So I assume we need to be patient and wait for the generic regex solution then?

**Comment by Gusted** [comment]
> That is really unfortunate! So I assume we need to be patient and wait for the generic regex solution then?

Oh so sorry for the late reaction I think this is problem/feauture that Can't be added or the way that URL behave needs to change but as this is how browsers handles with common ports, I close this feature request as it for right now to possible. If you think otherwise as their might be an extension API I didn't know of Feel free to comment.

Thank you for your contributions to Darkreader :D
