### ISSUE TITLE
bug:some picture turn dark in dynamic mode

### ISSUE THREAD

**Issue by Aragamiz** [darkreader/darkreader#2132]
like this site：https://item.jd.com/100006461093.html

**Comment by Gusted** [comment]
Could you provide a screenshot to show which picture turns dark?

**Comment by Aragamiz** [comment]
> Could you provide a screenshot to show which picture turns dark?

like this https://imgur.com/cSDbdjl
and this https://imgur.com/djyCGtR
thk a lot~

**Comment by Gusted** [comment]
This very very strange

Darkreader just sets the background-image to none

![](https://i.imgur.com/SzqrzSP.png)

**Comment by Aragamiz** [comment]
> This very very strange
> 
> Darkreader just sets the background-image to none
> 
> ![](https://camo.githubusercontent.com/ce1375b094a2e0d4c7204afef74277286ad76606/68747470733a2f2f692e696d6775722e636f6d2f537a71727a53502e706e67)

in this web : https://item.jd.com/100008383638.html#crumb-wrap
picture turn dark random, no some rule.
i just turn off all ex and by use chrome or edge chrome ver.
but still
and thk u reply me!

**Comment by norsehealer** [comment]
There are quite a few websites where the images just disappear.  I know Reddit had the top banner disappear too.

**Comment by Gusted** [comment]
Hmm I will try to look into it. Typescript is not my best language

**Comment by tete1030** [comment]
Is there any progress? I tried "IGNORE IMAGE ANALYSIS", but it did not work.

![image](https://user-images.githubusercontent.com/4312115/94932865-373dd180-04fc-11eb-8a75-0a90ebd211aa.png)

**Comment by Gusted** [comment]
> Is there any progress? I tried "IGNORE IMAGE ANALYSIS", but it did not work.

It seems that IGNORE IMAGE ANALYSIS is broken with it's new logic.

**Comment by tete1030** [comment]
Just came across an issue comment about setting background-image to `none`. I'm not sure if it is related.
https://github.com/darkreader/darkreader/issues/469#issuecomment-388567591

And according to @alexanderby, "similar approach was added in v4.5.0."
