### ISSUE TITLE
Release 4.9.0 breaks dynamic mode in Firefox 56 / Waterfox

### ISSUE THREAD

**Issue by ElhemEnohpi** [darkreader/darkreader#2136]
Dynamic mode has stopped working correctly since the 4.9.0 update. Everything is just white on black, there are no colours for links etc. Reverting to 4.8.10 fixes it.

Steps to reproduce:
1. Create a new clean profile in Waterfox Classic (a fork of Firefox 56).
2. Install Dark Reader 4.9.0
3. Visit a website, e.g. Wikipedia

I expected the website, as in the past, to first render in white on black, then, after a very short delay, for colours to appear like blue links etc. Instead, the colours never appear, all the text stays monochrome. The Wikipedia logo has white text on an almost-white background.

![screenshot_347](https://user-images.githubusercontent.com/23618559/76810355-0c08c480-67ee-11ea-9fb1-8328cc6be962.png)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3

**Comment by alexanderby** [comment]
Hi, do you see any errors in Console?

**Comment by ElhemEnohpi** [comment]
Ok, with 4.9.0 I see this:
```
"Creating CSS for url: https://en.wikipedia.org/wiki/Main_Page"  index.js:2500:21
SyntaxError: ':host link[rel*="stylesheet" i]:not([disabled]), :host style, :host link[rel*="stylesheet" i]:not([disabled]), :host style' is not a valid selector  (unknown)
JQMIGRATE: Migrate is installed with logging active, version 3.1.0  load.php:255
```

With 4.8.10, the second line with "SyntaxError" isn't there.

**Comment by alexanderby** [comment]
Thanks. I was thinking to drop support for Firefox below 63 (because of lack of Shadow DOM it becomes hard to test it on all versions), but added a patch, that I didn't check. I will publish a fix soon, hope there are no other issues.

**Comment by ElhemEnohpi** [comment]
Thank-you! There are probably hundreds of thousands if not millions of Waterfox users, so anything you can do to keep it going on 56 would be appreciated...
