### ISSUE TITLE
Howto change background color of all pages to specific color?

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#2137]
I use firefox and want to change background-color of all pages, I check "Dev tools" and try to change `background-color ` of `github` portion and refresh but nothing changed.

Is that all colors settings are in "Dev tools"? and how to change all background color of pages to my wanted color? I find it pretty dark with current background color and want it more material-dark.

**Comment by Gusted** [comment]
The background color you probably changed was for a element that you don't see like for refined github anothrt extension

You could use dev tools and than select a element you would like to make it less dark. Add it into the CSS of github with the attribute
