### ISSUE TITLE
Can we please close issues that have already been fixed?

### ISSUE THREAD

**Issue by Mertyn** [darkreader/darkreader#2139]
It would be really helpful if i didn't have to read over all the issues that are already fixed.
I don't completely know how the permissions for closing issues work, but it would really please my eyes if the number of issues would actually go down.

**Comment by alexanderby** [comment]
Hi, sorry, I'm drowned in these issues. Switching between them takes up much energy. Maybe some day I will clean them up. I've given you triage permissions for this repository, feel free to close any issue you see is already fixed.

**Comment by Gusted** [comment]
I would be glad to help with closing issues

**Comment by Mertyn** [comment]
No worries, I can totally understand that @alexanderby :)
Thank you very much for giving me the permissions and I'm glad to be able to help with this, but can i only close issues that are newly opened after i got the permissions?
I tried to close an issue that i've fixed a while ago, but the "close issue" button didn't show up.

**Comment by Gusted** [comment]
Still counting 😌 ![](https://i.imgur.com/EOZIl1z.png)
