### ISSUE TITLE
Only activate on a specific website

### ISSUE THREAD

**Issue by wuniversales** [darkreader/darkreader#2140]
Would it only be possible to activate it on a specific website?

For mobile phones, this function is useful, so as not to saturate firefox

**Comment by hoomanist** [comment]
I agree it will be helpful

**Comment by Gusted** [comment]
Open the extension -> Site list -> Inverted Listed only -> Type your sites you want to be dark in that list

**Comment by wuniversales** [comment]
Ahh, okay, it seems to work, thanks, I close this.
