### ISSUE TITLE
[Request] Make an exception for Stylus user styles when enforcing style order

### ISSUE THREAD

**Issue by narcolepticinsomniac** [darkreader/darkreader#2141]
The race to last place is an understandable objective for specificity, but DR was much more useful when it could be used in combination with user styles. Obviously, DR is the most popular option for global dark theming, and for good reason - it's pretty damn good. It's impossible to be perfect though, so the ability to override any minor issues with a user style is really useful. 

I realize you provide an option for user CSS, but it's nowhere near as convenient. Stylus' editor has far more functionality by default, supports usercss format with preprocessor support, and also provides the ability to easily share and update styles automatically.

I'm a member of Openstyles. I'm also a long time user of DR. For sites I visit most often, I mostly have custom themes with DR disabled. Some others, I use DR with a few customizations in user styles. Pretty much every other random site where I rely on DR, I still always appreciated the ability to override certain aspects with global styles, particularly scrollbar styling.

You guys recently improved your style order enforcement, which is great, but user styles are collateral damage, which shouldn't be the case. We can't very well have some ridiculous battle of mutation observers, if the goal is compatibility. The only sane way DR and user styles can coexist is if you guys recognize the value, and make an exception. I would suggest you do the same for Stylish, since it's the most popular, but it's so poorly managed and maintained that they don't even try to win the specificity contest. 

DR and user styles are better together. Overriding them is an unfortunate recent development which I hope you'll reconsider.

**Comment by Gusted** [comment]
Hey their!

I added so that if the element is been styled with Stylus it will ignore the element complety, so mostly it work so far I have tested it.
[darkreader.zip](https://github.com/darkreader/darkreader/files/4362848/darkreader.zip)
If this work or have any issue let me know so I can make a pull request for it

**Comment by Gusted** [comment]
For the developers 

https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/style-manager.ts#L51

https://pastebin.com/gnLEywSJ

**Comment by narcolepticinsomniac** [comment]
>If this work or have any issue let me know

LGTM.

>...I can make a pull request for it

Please do, @Gusted , much appreciated!

**Comment by Gusted** [comment]
> > If this work or have any issue let me know
> 
> LGTM.
> 
> > ...I can make a pull request for it
> 
> Please do, @Gusted , much appreciated!

Alright if this fixes the issue I will make a pull request when I get home and test some more about it.

**Comment by Gusted** [comment]
Btw thank you for informing about this fork of stylish +1 user :)

**Comment by Gusted** [comment]
Opened a Pull request #2152
