### ISSUE TITLE
Github Sticky Headers keep moving on Firefox with Filter mode

### ISSUE THREAD

**Issue by paulodiovani** [darkreader/darkreader#2142]
This happens on GitHub Pull Requests _Files Changed_ tab and it is pretty annoying.
The Sticky headers keep jumping during scroll. 

It happens with the following elements:

- `.notifications-shelf.notifications-v2`
- `.pr-toolbar`
- `.sticky-file-header`

## GIF Screencast

![Peek 2020-03-18 11-53](https://user-images.githubusercontent.com/1295197/76974513-0f946c80-6910-11ea-97f0-76508e603bd5.gif)

## Other modes

- Filter+ is known to not work in Firefox
- Static doesn't render the diffs properly in Github
- Dynamic renders fine, but is less stable - sometimes it doesn't work - and it is a lot slower

I often switch to Dynamic for websites that Filter doesn't look good, but it is too unstable and slow to use widely. Filter is still by far the best option.

## Notes

I tried some other Dark Mode extensions for firefox, some of them presents the same issue I mentioned here.

**Comment by Gusted** [comment]
Should be fixed
