### ISSUE TITLE
Dark Reader turn every image into black with Facebook New Design F8

### ISSUE THREAD

**Issue by KimiNoNaWaGithub** [darkreader/darkreader#2146]
Ok, Dark Reader makes some icons in new Facebook design disappear. Can you fix this?
This is with Dark Reader:
![image](https://user-images.githubusercontent.com/62417238/77141235-bd3d8200-6aae-11ea-8289-11448fe0a277.png)
This is without Dark Reader
![image](https://user-images.githubusercontent.com/62417238/77141269-d7776000-6aae-11ea-8633-2c135ecf5abe.png)

**Comment by FranklinYu** [comment]
Wait you have dark mode for Facebook? Are they still rolling it out?

**Comment by Gusted** [comment]
I'm still getting the old design..

**Comment by KimiNoNaWaGithub** [comment]
Yes, now you can switch to new Facebook design with Dark Mode : (available for anyone)

**Comment by KimiNoNaWaGithub** [comment]
![image](https://user-images.githubusercontent.com/62417238/77550762-0ee97080-6ee4-11ea-8c23-abc9d6cd24ab.png)

**Comment by KimiNoNaWaGithub** [comment]
![image](https://user-images.githubusercontent.com/62417238/77550844-232d6d80-6ee4-11ea-9615-8863895920ff.png)

**Comment by KimiNoNaWaGithub** [comment]
![image](https://user-images.githubusercontent.com/62417238/77550910-37716a80-6ee4-11ea-8629-4715697465ee.png)

**Comment by Gusted** [comment]
Seems like I still don't got the new design so just wait for who got the new design and know how to fix CSS

**Comment by KimiNoNaWaGithub** [comment]
Back to the main reason:
The Dark Mode of new Facebook design have something not clearly right. That's the timing popup .

![image](https://user-images.githubusercontent.com/62417238/77552584-4ce79400-6ee6-11ea-8136-74bcd6ed6270.png)

So I use Dark Reader, and wow it's work, but it's also broke image to black.

![image](https://user-images.githubusercontent.com/62417238/77552859-a51e9600-6ee6-11ea-8174-82566c133042.png)

So I posted here.

**Comment by Gusted** [comment]
That's very weird behavior..

**Comment by FranklinYu** [comment]
@Gusted You need to opt-in; it’s off by default. When you activate new design you can choose light/dark theme.

**Comment by Gusted** [comment]
Where could I find the opt in button?

**Comment by alexanderby** [comment]
Unfortunately I see no way to enable this new design. It seems to be rolled out to a limited set of users.

**Comment by FranklinYu** [comment]
Not sure whether it works for everyone, but for me it’s

1. In the right of the top blue bar there is a small triangle pointing down. Click it.
2. A drop-down menu should appear. One of the options should be “See New Facebook”.

FYI: https://www.theverge.com/2020/3/19/21187118/facebook-desktop-redesign-more-available-starting-today

**Comment by Athanasius** [comment]
Unfortunately I don't want to use the New Facebook yet as I also use the Social Fixer extension/script to make FB use actually bareable.

So, any hints on a tweak that could allow Dark Reader use, without blacking out the icons, on 'old' Facebook ?  I'm looking at CSS for those elements and nothing's jumping out at me as the culprit.

**Comment by Athanasius** [comment]
Of course now it's decided to work *anyway* after some toggling.  Probably a race condition between what Dark Reader does and other FB/SFx stuff running and tweaking things ?

**Comment by Athanasius** [comment]
One reload later ... if I toggle this bit off for an affected element (list of Like/Love icons on a post):

`.sp_CL8JpzlXVjW_1_5x {
    background-image: url("https://static.xx.fbcdn.net/rsrc.php/v3/yd/r/OR1DCQlFvIn.png");
`
Then the icons re-appear.

**Comment by Athanasius** [comment]
> 
> 
> One reload later ... if I toggle this bit off for an affected element (list of Like/Love icons on a post):
> 
> `.sp_CL8JpzlXVjW_1_5x { background-image: url("https://static.xx.fbcdn.net/rsrc.php/v3/yd/r/OR1DCQlFvIn.png"); `
> Then the icons re-appear.

The weird thing being that doing so means this next bit then works, but the URL is very similar, just relative instead of absolute:
`.sp_CL8JpzlXVjW_1_5x {
    background-image: url(/rsrc.php/v3/yd/r/OR1DCQlFvIn.png);
    background-size: 98px 1432px;
    background-repeat: no-repeat;
    display: inline-block;
    height: 16px;
    width: 16px;
}`

Toggling the background-image off in the above does hide the icons again.

**Comment by Gusted** [comment]
Someone with a good experience of CSS need to take look at it, but so far I know the maintainers of darkreader including me. Doesn't have the new design

**Comment by Athanasius** [comment]
Yup, this in a Stylus (NOT Stylish!) script seems to have fixed it:

```
/* Fix icons to actually show under Dark Reader, 'Old' Facebook */
.sp_CL8JpzlXVjW_1_5x {
    background-image: url(/rsrc.php/v3/yd/r/OR1DCQlFvIn.png) !important;
}
```

**Comment by Gusted** [comment]
[build.zip](https://github.com/darkreader/darkreader/files/4533173/build.zip)
For someone who has the new design, with this build for chromium based browsers, does it still persist?

**Comment by Gusted** [comment]
[build-firefox.zip](https://github.com/darkreader/darkreader/files/4533176/build-firefox.zip)
A build for firefox if anyone like to test it out and have firefox.

**Comment by Athanasius** [comment]
> 
> 
> [build-firefox.zip](https://github.com/darkreader/darkreader/files/4533176/build-firefox.zip)
> A build for firefox if anyone like to test it out and have firefox.

Trying to "Install add-on from file..." on Firefox with this says it's corrupt, although it opens fine in Windows Explorer window.  How am I meant to install this to test ?

**Comment by Gusted** [comment]
Debug addons -> install temporary addon

**Comment by Athanasius** [comment]
> 
> 
> Debug addons -> install temporary addon

I ended up having to extract the files out of the .zip and then point the debug FF install at the manifest.json. It now shows the usual DR extension as disabled, and the temporary debug one.  Reloaded FF tab (reminder, this is NOT the 'New Facebook'), disabled my Stylus script, and the icons do appear to work properly again now.

**Comment by Gusted** [comment]
Good to know! Darkreader v5 will contain a CSP fix for a lot of sites including Facebook's one

**Comment by Myshor** [comment]
I can add from my side that fixes for dynamic filtering are done by me in #2395 
I was testing them with old design and new native light. Seems to work fine. I still need to test them with new native dark to be sure they work there too but if you want to check them before you can add them in DarkReader devtools earlier. 😉

I hope I'll do all fixes for Dynamic config before next release.
