### ISSUE TITLE
[Feature Request] Add a time to automatically turn on

### ISSUE THREAD

**Issue by mikrodotnet** [darkreader/darkreader#2147]
I was just thinking it'd be a nice feature to have a time of day to automatically turn on, or a time range to turn on automatically at a set time and turn off at a set time. Something similar to Windows 10 night light.

**Comment by Gusted** [comment]
https://darkreader.org/blog/automation/

**Comment by Juraj-Masiar** [comment]
Oh man! Do I understand this correctly that in order to access these options you need to click that barely visible 3-vertical-dots icon? It's like 4px wide and dark, no one will ever find this! 😮 

BTW I was just about to request this feature because I was not able to find this option.

**Comment by Gusted** [comment]
It's fine! @alexanderby is working a rework of the UI and I also hope that It will be better one So I also could add some more buttons.

**Comment by Gusted** [comment]
If the issue is been resolved could you close the issue

**Comment by enricorotundo** [comment]
Took me a while to find https://darkreader.org/blog/automation/, I'd suggest @alexanderby to give better visibility to Automation in the new UI. Thanks! 🙏

**Comment by mikrodotnet** [comment]
Finally was able to see the 3 dots after viewing that automation url. I'll close this now, thanks
