### ISSUE TITLE
Confirmation before resetting custom css

### ISSUE THREAD

**Issue by BlueGreenMagick** [darkreader/darkreader#2158]
For Static mode, you can specify your own css. So for websites that I go to frequently, I designed my own css. But one misclick and it resets to default, no way to get it back. So could anyone consider adding a confirmation box before reset? 

I could probably use some other custom css injecting addon for my use case, but I don't trust it with the permission to access all my data.

**Comment by BlueGreenMagick** [comment]
The dev tool reset button should also have a confirmation popup as well

**Comment by Gusted** [comment]
Will look into it even Darkreader v5 will have a new UI...

**Comment by Gusted** [comment]
#2411 Contains an confirmation pop-up

**Comment by Gusted** [comment]
#4887
