### ISSUE TITLE
(MAC) Ctrl based shortcuts don't work in Firefox

### ISSUE THREAD

**Issue by luiza177** [darkreader/darkreader#2164]
I have the extension installed on my MacBook Pro in both Firefox and Chrome. I've set the enable/disable site and extension to Ctrl+A and Ctrl+D, respectively. In Chrome, everything works as expected, but in Firefox, any Ctrl + shortcuts don't get responded to, I've tried switching to other Cmd and/or Opt based shortcuts, but unfortunately, that tends to conflict with other shortcuts in web apps like the G Suite.
One thing I noticed is that Ctrl gets represented by a ^ character in Chrome, and just by the letters in Firefox, as the screenshots show. Not sure if that's related to anything.

<img width="285" alt="chrome" src="https://user-images.githubusercontent.com/40475976/77408447-03992680-6db8-11ea-86bf-ebeb9cbe3f12.png">
<img width="281" alt="firefox" src="https://user-images.githubusercontent.com/40475976/77408453-06941700-6db8-11ea-951e-ddeb3b31f0ba.png">

**Comment by Gusted** [comment]
Could this been that you have the wrong keyboard layout for your MacBook?

**Comment by luiza177** [comment]
I don't think so? I'm using the "US International - PC", I don't have any alternate layouts.

**Comment by Gusted** [comment]
What about if you add alt into the shortcut?

**Comment by luiza177** [comment]
The only other modifier it'll accept along with Ctrl is Shift, so Ctrl+Opt or Ctrl+Cmd don't get detected (and neither does Cmd+Opt, for that matter). This applies to the Chrome version as well, which states it's an "invalid combination".

Is it possible that Firefox itself doesn't "see" (Mac) Ctrl as a modifier for a shortcut?

**Comment by Gusted** [comment]
I think so ctrl is mainly used for shortcuts like ctrl + w ctrl + t so I think this is more of MacBook problem than darkreader. I will test it on my windows machine I always use like alt to make ctrl combinations that always work

**Comment by luiza177** [comment]
The mac equivalent of the window Ctrl+T and Ctrl+W are simply Cmd+T and Cmd+W, so it's not conflicting with those. In my Windows machine, I use the default Alt+Shift+A or D, which work as expected.

**Comment by Gusted** [comment]
I just tested and ctrl shortcuts don't work on windows too even for other extension this is probably browser thingy

**Comment by Gusted** [comment]
Browser - blocks this
