### ISSUE TITLE
How-to implement darkreader using css?

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#2165]
I want to use userChrome.css / userContent.css solution to bring complete dark mode as currently goal of darkreader. I find darkreader glitchy as report in this issue: https://github.com/darkreader/darkreader/issues/2095 - especially when slow pages load or opening firefox (I have restore previous session enabled) (it can be how firefox engine load pages)

I only have uBlock Origin add-on and darkreader. I believe the `glitch` issue still happens even using darkreader only.

Archlinux and firefox latest.

What's complexity to use css solution? and how to implement that way?

**Comment by Gusted** [comment]
What about using stylus #2152 so far I know darkreader will try to ovveride every css

**Comment by tmpm697** [comment]
Stylus still an addon with ability to export/import file, is there away to hardcode in like userChrome.css?

**Comment by Gusted** [comment]
Not into stylus that hard if I was you open a issue to ask this

**Comment by Chidhambararajan** [comment]
I don't know why , but the color issue gets fixed by toggling between dark and light mode in the plugin repeatedly

I.e when the page loads the dark theme looks very bad with a lot of issues, but if I toggle light mode and again dark mode , everything becomes normal

**Comment by Gusted** [comment]
Hi their @tmpm697 https://github.com/darkreader/darkreader/issues/2095 has been solved maybe you can take another look at the issue and see If this will resolve your issue.

**Comment by tmpm697** [comment]
@Gusted Thanks #2095 solved but still my question if I can implement this add-on as css. Honestly I depend on this ad-on too much and I need a way that I can modify it easily the way I want.

Can you generate the code? I think shadowfox is very good example of extracting all into css file. I can't live without this ad-on that the case.

**Comment by Gusted** [comment]
Pffffff... I've already tried this on youtube.com to use it along side another theme. But most are inline colors into the element.style of the element and modyfing the source code will take a long time to get all the generated css...

**Comment by tmpm697** [comment]
@Gusted : So this ad-on will dynamically generate general style for elements of all pages?

If yes I wonder if we can do the generics with css file too?

**Comment by Gusted** [comment]
No not really as each <style> in the DOM structure is being computed to be which color etc. For all elements for the remaning css property's making this into a CSS will be a big mess and with current code not possible as their isn't a console.log(theAlmightyStyleVariable) Their are splitted up in a lot of stylesheets. A possible solution is to open a site with firefox and open the Styles or CSS tab in the devtools

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted
