### ISSUE TITLE
Scrollbar theme?

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#2172]
Dark reader forces scrollbar theme when use it, and I like it. I want to force scrollbar theme of dark reader for my default gtk-3.0/gtk.css setting, how-to?

Like this [picture](https://i.imgur.com/ApyqooN.png)

**Comment by Gusted** [comment]
I will give you the script in a minute

**Comment by Gusted** [comment]
https://pastebin.com/raw/vXQYQucE

**Comment by tmpm697** [comment]
I added to gtk.css but nothing changed. `webkit` looks strange to add to `~/.config/gtk-3.0/gtk.css`

**Comment by Gusted** [comment]
That's very weird it doesn't work... It's probably to do how GTK apply thema's. Search on the internet how to Thema scrollbars you have the colors and stuff already
