### ISSUE TITLE
Hanging / Stop working 

### ISSUE THREAD

**Issue by AllanDaemon** [darkreader/darkreader#2181]
I'm a long time user of the extension, and lately it becomes to hang in chrome (now I'm on Chrome Beta (81) on Fedora Linux).

After using, it stops answering. The shortcut doesn't work anymore and when I click on the extension icon, it got the circle os clicked but does nothing (expected: open the options popup), and after a while it clicked effect on the icon disappears.

If you turn the extension off and on again it regains some control but soon it becomes irresponsive again.

I don't know what else could I do to investigate this. But this extension is really important for my eyes health, and the way it is turns the use impossible.

Issue #2039 sounds a little with this.

Extension version: 4.9.2
Google Chrome: Version 81.0.4044.69 (Official Build) beta (64-bit)

**Comment by AllanDaemon** [comment]
I'm a long time user of the extension, and lately it becomes to hang in chrome (now I'm on Chrome Beta (81) on Fedora Linux).

After using, it stops answering. The shortcut doesn't work anymore and when I click on the extension icon, it got the circle os clicked but does nothing (expected: open the options popup), and after a while it clicked effect on the icon disappears.

If you turn the extension off and on again it regains some control but soon it becomes irresponsive again.

I don't know what else could I do to investigate this. But this extension is really important for my eyes health, and the way it is turns the use impossible.

The issue #2039 sounds a little with this.

Extension version: 4.9.2
Google Chrome: Version 81.0.4044.69 (Official Build) beta (64-bit)

**Comment by AllanDaemon** [comment]
If I open the DR developer tools, and let it open, when the extension becomes unresponsive, the windows of dev tools also does it. Is I click on the window, a page unresponsive dialog shows.

![image](https://user-images.githubusercontent.com/607994/77720036-86430100-6fc5-11ea-9093-3cdbe9cf660d.png)

**Comment by alexanderby** [comment]
Hi, sometimes such errors happen with unstable builds. Maybe you could try using a stable Chrome release for a while?

**Comment by AllanDaemon** [comment]
The same issue happens also on Chromium browser stable. I suspect that this was also happening in Chromium 79 as well.

`Version 80.0.3987.149 (Developer Build) Fedora Project (64-bit)`

is there idea or direction of what to do to help figuring It out?

**Comment by AllanDaemon** [comment]
This showed now on Chromium Stable

![image](https://user-images.githubusercontent.com/607994/77814872-d4bed100-7093-11ea-8f16-7e60f7e23f20.png)

**Comment by alexanderby** [comment]
I haven't seen such messages for 5 years. Does it happen with any other extension? I will have to install Linux, maybe in a virtual machine, to have a look. It would be great if you could narrow down the issue too.

**Comment by AllanDaemon** [comment]
> Does it happen with any other extension?

Nope. I suspect that it could have something related to new Chrome rules for extensions?

I'll try to install it from the git repo using a older version.

**Comment by alexanderby** [comment]
No issues seem on macOS and Windows. Maybe you will notice some common steps before the extension hangs. Also, try observing it in Filter mode.

**Comment by Mhowser** [comment]
I have this problem as well. Using Brave Browser version 1.11.97 Chromium: 84.0.4147.89 and Dark Reader 4.9.15 on Linux

**Comment by AllanDaemon** [comment]
I have forgotten it, but for me, it's now solved.

First I installed it from git as unpacked and I began to test it with bisect. The latest version on that time did have the same problem in different versions of chromium/chrome. At the time, the latest version (master branch) was bad (with the problems. I tried a version from Dec 2019 and that was working ok.

But after a while, I don't remember why, I have to change this, and now it's working fine with the chrome store version, So I would close the issue if wasn't by @Mhowser  facing the same issue.

**Comment by Gusted** [comment]
Mhowser could have a try as #2550

**Comment by AllanDaemon** [comment]
The original issue that motived to open this is gone for me, so I'm closing. If needed, it may be reopened.

**Comment by Mhowser** [comment]
I still have this problem even after the update. I have to manually stop
darkreader via the browser's task manager and restart it.

**Comment by null-dev** [comment]
Heads up that this still happens for me on Linux. The issue is extremely strange in that it seems as if the Chrome's JavaScript runtime itself freezes.

It's also incredibly difficult to debug as the debugging tools themselves crash when I try to use them on the extension's background page.

Also, observer how when this happens, Dark Reader's JS memory field dips to 0:
![image](https://user-images.githubusercontent.com/9571936/101268321-a23f9a80-372f-11eb-96b3-9e591aa329af.png)

I've never had this happen with any other extension.

@Gusted Can you re-open this issue? It seems like a couple others are experiencing this as well.

I can reproduce this bug regularly so I'm going to run my browser in debug mode and see if I can catch anything suspicious in the logs.
