### ISSUE TITLE
Incorrect coloring of map legends on wikipedia

### ISSUE THREAD

**Issue by shodanx2** [darkreader/darkreader#2185]
Please see the following colored map legend on wikipedia with dark reader on and then off

https://i.imgur.com/2Um4ToF.png

https://i.imgur.com/ocp4HFu.png

As you can see, with dark reader on, some of the colors get darkened when they shouldn't 

The source page is 
https://en.wikipedia.org/wiki/2019–20_coronavirus_pandemic

**Comment by Gusted** [comment]
Needs to be fixed within the code couldn't fix it with CSS

**Comment by Gusted** [comment]
A fix is on his way
