### ISSUE TITLE
Invisible scroll slider when viewing PPTX files in Google Drive

### ISSUE THREAD

**Issue by dronewizard** [darkreader/darkreader#2195]
Please see my screenshots for comparison. Dark mode is disabled in the first image.

![Dark mode disabled](https://user-images.githubusercontent.com/39130713/77925238-3e90d380-726a-11ea-9478-1968b59cfc43.jpg)

![Dark mode enabled](https://user-images.githubusercontent.com/39130713/77925076-0c7f7180-726a-11ea-8edc-573af021dfc9.jpg)

**Comment by Gusted** [comment]
![](https://i.imgur.com/b3jqX8i.jpg) Weird cannot reproduce the issue...

Do you use firefox?

**Comment by dronewizard** [comment]
No I use the latest Chrome beta (81.0.4044.83).

**Comment by Gusted** [comment]
Could you try another pptx? And try not get it zoomed in, because I notice the scrollbar get white? while viewing a PPTX maybe that's the problem

**Comment by dronewizard** [comment]
I just tried it on a few more, both zoomed in and at normal zoom. The issue persisted. Only the static filter showed it.

**Comment by Gusted** [comment]
Okay ehm do you know if this issue was in v80? I'm trying to get this reproduced

**Comment by dronewizard** [comment]
The issue persists on the latest stable Chrome release (now version 81.0.4044.138) and the latest Chrome beta (Version 83.0.4103.56).

**Comment by Gusted** [comment]
Darkreader v5 will have an option to change the color of the scrollbar and that way you can bright it a little bit up to make it visible :)
