### ISSUE TITLE
The auto on/off feature (based on time or location) dissapeared from Firefox for Android

### ISSUE THREAD

**Issue by veverone** [darkreader/darkreader#2197]
I just noticed that a very useful feature is gone... on Firefox for Android. 

Version is 4.9.3

Is this a bug?

It used to be like this >>
![2020-03-30 21_33_32-](https://user-images.githubusercontent.com/16813709/77948638-66b21e00-72ce-11ea-9367-6e83856ba947.png)

But now it looks like this >>
![Screenshot_20200330_213646_org mozilla firefox](https://user-images.githubusercontent.com/16813709/77948900-c8728800-72ce-11ea-8ccf-c4db0792bcf4.jpg)

**Comment by Gusted** [comment]
Yes that's right! Darkreader have a new Mobile ui 
https://github.com/darkreader/darkreader/tree/mobile-ui
Be patient it will come back at a later time. 
But I don't know how to get a older version working for Firefox Mobile.

**Comment by Gusted** [comment]
If you want go back to the old UI 
Go to [Darkreader addon](https://addons.mozilla.org/en-US/firefox/addon/darkreader/versions/) and download version 4.9.2 however you will miss the fixes and improvements.
