### ISSUE TITLE
Occasionally forgets to invert text color

### ISSUE THREAD

**Issue by Ahazuarus** [darkreader/darkreader#2200]
Bing search results is where I see this issue most often.  Refreshing the page causes the same page to be rendered correctly. 

This behavior can also be seen in OneDrive.

**Comment by Gusted** [comment]
Screenshot? and a Bing link to reproduce.

**Comment by Gusted** [comment]
> Screenshot? and a Bing link to reproduce.

**Comment by AllanChain** [comment]
<https://cn.bing.com/search?q=chrome%20android%20theme>

Only happens on Bing's top result. Dark reader works fine first a few seconds (about 10s) when page open. As the page done loading, text turns black. 

Works fine again on current page when:
- Turn off dark reader and reenable it
- Hit search again

I am using chrome with dark reader version 4.9.8.

(search result may be different in different regions)

![image](https://user-images.githubusercontent.com/36528777/82410100-c6909e00-9aa1-11ea-8425-95d2431c9d72.png)

**Comment by Gusted** [comment]
Oh wow that's not good

**Comment by sprinkledcheese** [comment]
Can't reproduce. Fixed?

**Comment by Gusted** [comment]
#2065 < Pretty sure this was the origin
