### ISSUE TITLE
Browsing apple website memory usage is increasing

### ISSUE THREAD

**Issue by zeisscai** [darkreader/darkreader#2203]
after update dark reader 4.9.4 for firefox, I found when browsing https://www.apple.com.cn/ Memory usage is increasing. But everything works fine when I stop dark reader. here is detail
windows 10 Pro 1909
Firefox version 74.0 (x64)
dark reader for firefox 4.9.4
![firefox.jpg](https://i.loli.net/2020/04/01/QeK6w9runxkU8m4.png)

**Comment by Gusted** [comment]
Hmm seems like their need some optimazation in the code this was very easy to reproduce. Got 1.2GB memory with darkreader and and 300MB off....

**Comment by Gusted** [comment]
Hi their after taking another look the apple website is already dark. You simply disable the extension as their already is an pull Request for apple websites(by default they take huge memory on non-apple devices for some reason) They optimized probably just for safari and their MacOs
