### ISSUE TITLE
Inverts the label colours on GitHub

### ISSUE THREAD

**Issue by resindrake** [darkreader/darkreader#2204]
Can potentially lead to confusion when black labels become white and vice-versa

**Comment by Gusted** [comment]
Screenshot?

**Comment by resindrake** [comment]
![image](https://user-images.githubusercontent.com/62374268/78118475-c9ccbd80-7452-11ea-9967-88e16c7e7aa1.png)

**Comment by Gusted** [comment]
Could you give the repo link?

**Comment by resindrake** [comment]
It's a private repo. The label is the default wontfix label that all new repos get.

**Comment by Gusted** [comment]
I don't really know to give it what color but Could like this a little bit more gray a good alternative?
![](https://i.imgur.com/cLWfuXv.png)

**Comment by resindrake** [comment]
I personally think the labels should be the same colour on both dark mode as they are on light mode, for consistency - they're not really that much of an eyesore and it eliminates any confusion. But that's just my two cents.

**Comment by Gusted** [comment]
Yeah I don't know about it giving it a white color doesn't match with DR and The labels colors are dynamic so Cannot just say it should stay same color :/

**Comment by Gusted** [comment]
![](https://i.imgur.com/OMhzqYf.jpg) The original background color is in the element style..

**Comment by resindrake** [comment]
I guess a fairly light grey would do then. Something that makes it at least vaguely obvious that the label would be white if you viewed it as a non-DR reader.

**Comment by Gusted** [comment]
Yeah, I'm gonna make a Pull request and let the owner decide if it a good move or not.

**Comment by Gusted** [comment]
#2208

**Comment by Gusted** [comment]
Has been resolved by github's new way of labeling.
