### ISSUE TITLE
知乎(zhihu.com)上回答的公式，不能反转颜色

### ISSUE THREAD

**Issue by Fred-Qhin** [darkreader/darkreader#2207]
![批注 2020-04-01 114406](https://user-images.githubusercontent.com/39523950/78097186-2e195e00-740e-11ea-9c4c-30ed3e3c8cbc.png)

**Comment by Gusted** [comment]
Hi their Could you provide the site this is on?

**Comment by Fred-Qhin** [comment]
> Hi their Could you provide the site this is on?

www.zhihu.com（知乎，有点像 quora ）
如果有人问一些数学问题
其他人写回答的时候，有时候会插入公式，但是使用 dark reader 这些公式完全是黑色的
四个模式我都试过了，静态完全看不见

**Comment by Gusted** [comment]
Help Wanted -> Behind loginwall & Chinese
寻求帮助 -> 登录墙和中文的背后

It would really help if you know how to use the Devtools of Chrome/Firefox.
如果你知道如何使用Chrome/Firefox的Devtools，那真的会有帮助。

Sorry for the bad chinese.

**Comment by yuezk** [comment]
Hi, @Fred-Qhin Can you provide the post you visited? Maybe I can give help.

**Comment by Fred-Qhin** [comment]
The website is www.zhihu.com<http://www.zhihu.com>. That language is Chinese and you need an account.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kevin Yue<mailto:notifications@github.com>
发送时间: 2020年5月22日 13:51
收件人: darkreader/darkreader<mailto:darkreader@noreply.github.com>
抄送: lalala-I love free<mailto:fred-qhin@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [darkreader/darkreader] 知乎(zhihu.com)上回答的公式，不能反转颜色 (#2207)


Hi, @Fred-Qhin<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFred-Qhin&data=02%7C01%7C%7C874ea1c8fbe6478a036808d7fe14285b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637257234832314455&sdata=hM4QiibJB2Yulzz%2B8PI0liSUyNRPhZ9u2FSkG5U5JEo%3D&reserved=0> Can you provide the post you visited? Maybe I can give help.

―

**Comment by Fred-Qhin** [comment]
What do you need?
The source code of the web?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kevin Yue<mailto:notifications@github.com>
发送时间: 2020年5月22日 13:51
收件人: darkreader/darkreader<mailto:darkreader@noreply.github.com>
抄送: lalala-I love free<mailto:fred-qhin@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [darkreader/darkreader] 知乎(zhihu.com)上回答的公式，不能反转颜色 (#2207)


Hi, @Fred-Qhin<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFred-Qhin&data=02%7C01%7C%7C874ea1c8fbe6478a036808d7fe14285b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637257234832314455&sdata=hM4QiibJB2Yulzz%2B8PI0liSUyNRPhZ9u2FSkG5U5JEo%3D&reserved=0> Can you provide the post you visited? Maybe I can give help.

―

**Comment by yuezk** [comment]
包含公式的的知乎帖子发一下，我找了一下，这种帖子我在知乎上还没有找到。

**Comment by Fred-Qhin** [comment]
You can visit this site https://www.zhihu.com/question/286269519
This site like quora. If you answer someone's question and write a mathematical formula.
It will be black

**Comment by Myshor** [comment]
There was some fix done but I updated it and now it shows inverted formulas even on https://www.zhihu.com/question/286269519
