### ISSUE TITLE
Dark mode won't work at microsoftedge.microsoft.com

### ISSUE THREAD

**Issue by Frozty4628** [darkreader/darkreader#2210]
Dark mode won't work at microsoftedge.microsoft.com on Edge Chromium, either this addon is from google web store nor edge store.

**Comment by Gusted** [comment]
This could be because each browser has protected pages like for chromium based browser the chrome webextension store, so extension can't block it or modify it for malicious reasons. It could be that `microsoftedge.microsoft.com` is a protected page, but I'm not sure. 

Does it work on other pages?

**Comment by Gusted** [comment]
Protected page.
