### ISSUE TITLE
JupyterLab: inactive tabs are not correctly inverted in dark mode

### ISSUE THREAD

**Issue by kamenevdn** [darkreader/darkreader#2216]
**Description**
If several tabs are open in JupyterLab, inactive tabs are not properly inverted with dark dynamic filter.

**Screenshots**
Appearance:
![chrome_IXsMvs0sin](https://user-images.githubusercontent.com/54708166/78230013-72bdfb80-74d9-11ea-96c7-9d64b47a7663.png)
Settings:
![GVMZYMH5b1](https://user-images.githubusercontent.com/54708166/78230196-b0bb1f80-74d9-11ea-8ec3-ae8a164c18a8.png)
![wMa9JWLsLY](https://user-images.githubusercontent.com/54708166/78230208-b6186a00-74d9-11ea-955c-70f5d06a9a52.png)

**Desktop info:**
 - OS: windows 10
 - Browser: chrome
 - Version: 80.0.3987.149

**Comment by Gusted** [comment]
Local hosted so It's mean I cannot really make a fix for it I mean Make it public.. The fix should be easy. Because it's localhost and can be runned on any port you want

**Comment by Gusted** [comment]
wontfix as this is an localhost website you only could make a fix at your own. Feel free to open another issue if you feel this could be fixed or comment if you need help with a local fix.

**Comment by YatinAdityaT** [comment]
@Gusted I am working with Jupyter notebook, it runs on local host too... I need help fixing it for localhost

**Comment by Gusted** [comment]
1. Download Stylus that's going to help a lot more
2. Will see what I can do into the codebase to fix this permanently
