### ISSUE TITLE
Wiktionary's collapsible header is wrongly inverted.

### ISSUE THREAD

**Issue by HubKing** [darkreader/darkreader#2220]
Such as translations or inflexions. For example, https://en.wiktionary.org/wiki/deplore I think the background should be a darker colour.

![image](https://user-images.githubusercontent.com/10900489/78294669-b6f6dd80-7565-11ea-9c28-dd5c4eabca82.png)

![image](https://user-images.githubusercontent.com/10900489/78294700-c5dd9000-7565-11ea-8642-db9b4a89b963.png)

PS: This did not happen on FireFox but happens on Vivaldi. On FireFox, DR's version was 4.9.4, and on Vivaldi, which uses Chrome's extension, DR's version was 4.9.2 (I checked the store, and it was the latest version). If this is not a problem of the Chrome version, but is a problem fixed in 4.9.4, disregard this issue.

**Comment by Gusted** [comment]
Running Chromium based browser and running with the latest version of darkreader 4.9.2
![](https://i.imgur.com/aiERccF.png)
I will look into it and Provide a fix

**Comment by Gusted** [comment]
#2222 Has been merged and will be avaible in the next update of Darkreader, as for this I close this issue, Thanks for reporting this issue!
