### ISSUE TITLE
Activated like / dislike buttons on Youtube not changing to blue color anymore

### ISSUE THREAD

**Issue by Maxxiii** [darkreader/darkreader#2229]
When you click on like or dislike button on Youtube video, it's not changing color to blue anymore. Only text description near icons (liked/disliked) change color. Same thing for like / dislike for comments section, but it's even worse there, because there is no text for this buttons, so "activated" / (pressed) likes indistinguishable from "not activated"

**Comment by Gusted** [comment]
Seems like youtube updated css selectors like usual :/ Will look into it and provide a fix.

**Comment by Gusted** [comment]
Provided a fix #2230

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/2230#issuecomment-613969547
