### ISSUE TITLE
Apply dark on "The connection has timed out" page?

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#2234]
There're several pages that darkreader hasn't applied `dark` mode to it, e.g: "The connection has timed out" page when we have connection issue or `addons.mozilla.org` page when we want to search/install addons.

How to have those pages complies dark mode?

**Comment by Gusted** [comment]
Not. Those are protected pages by the browser, for safety/privacy reasons.

**Comment by tmpm697** [comment]
Is there a workaround solution? I don't want to protect those pages :)

**Comment by Gusted** [comment]
Ehm not really darkreader also don't dark them in the code. So if the browser will allow it darkreader has them also in a protect page list

**Comment by Xerus2000** [comment]
@tmpm697 you can use some Firefox tricks to achieve that, see for example here: https://superuser.com/questions/603218/how-to-make-the-aboutblank-page-black-or-any-other-color-in-firefox

That way you can also have loading background and other browser-owned things be dark.

**Comment by tmpm697** [comment]
@Xerus2000 It's protected pages by firefox not about:blank.

**Comment by xerus2000** [comment]
@tmpm697 yes, this was just a pointer for further research - I am pretty sure it can be done with custom userCss

**Comment by Gusted** [comment]
wontfix - as it can't be fixed. A possible workaround was given https://github.com/darkreader/darkreader/issues/2234#issuecomment-611451542
