### ISSUE TITLE
Dynamic mode makes resources loading errors

### ISSUE THREAD

**Issue by senpl** [darkreader/darkreader#2235]
Version 4.9.4

Resources that loads without extension in dynamic mode produce JS errors. This is problematic, coz extension should not colide with loaded resources.

https://m.autobid.de/?action=login 
Error present:
404 (Not Found) (but their are found in other mode, so dynamic mode is making problem).
https://m.autobid.de/_css/themes/images/ajax-loader.gif
https://m.autobid.de/images/ajax-loader.gif
https://m.autobid.de/images/icons-18-white.png

**Comment by senpl** [comment]
problem might be releated to _ sign in paths.

**Comment by Gusted** [comment]
I don't think it could be the _ 
I think because it use ../../ in the html source code to load it and darkreader don't handle it that well..

**Comment by Gusted** [comment]
jQuery loads those external idk how darkreader interfere with them.

**Comment by Gusted** [comment]
Resolved by #3055
