### ISSUE TITLE
QR code, inverted !

### ISSUE THREAD

**Issue by promeneur** [darkreader/darkreader#2236]
With your PC with Chrome go to web.whatsapp.com
get a QR code.

QR code is inverted then when you scan QR code you can't connect to your account !

You must disable darkreader to scan the good QR code.

**Comment by Gusted** [comment]
To make a fix it will look like this..
![](https://i.imgur.com/ql67ZXd.jpg)

**Comment by Gusted** [comment]
https://pastebin.com/Rgyz0gHU

**Comment by Gusted** [comment]
I close this issue as #2209 has been merged and will be avaible in the next update of Darkreader. Thank you for reporting this issue!
