### ISSUE TITLE
Dracula mode

### ISSUE THREAD

**Issue by samyak039** [darkreader/darkreader#2244]
I recently came around [Dracula Theme](https://github.com/dracula/dracula-theme/) as my mind was blown.

So i was wondering if by changing some settings I can apply Dracula mode to all my sites using your application.

it is possible..?

**Comment by Gusted** [comment]
https://darkreader.org/blog/dr-5-announcement/ Their is coming Theme presents.

**Comment by Samyak039** [comment]
sounds cool...!!!

**Comment by Gusted** [comment]
#931 
https://darkreader.org/blog/v4-9/

It's not pre-setted yet, However it should hopefully be implemented by #2876
