### ISSUE TITLE
Extension no longer runs on Google web pages

### ISSUE THREAD

**Issue by stytch16** [darkreader/darkreader#2245]
Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Dark reader version: 4.9.4

Sites I tried:
https://www.google.com/
https://www.google.com/maps
https://developers.google.com/
https://docs.google.com/

I ran Devtools to get console logs from the Dark Reader extension. I don't see any log statements like "Creating CSS for url: ..." when I open google.com for instance.

**Comment by Gusted** [comment]
Does it work on any other site fine?

**Comment by stytch16** [comment]
Yes, I haven't found any non-Google web pages that don't work.

**Comment by stytch16** [comment]
Here's a screenshot of my browser session with devtools running for Dark Reader.
![Screen Shot 2020-04-08 at 4 20 27 PM](https://user-images.githubusercontent.com/13952658/78842767-ce92f380-79b5-11ea-80f4-a60eacaf5c1b.png)

**Comment by Gusted** [comment]
That is very weird can you check if Static and Filter work

**Comment by stytch16** [comment]
Yes they work. It's definitely weird and I would expect other users to see this behavior. I reinstalled the chrome extension. The build and data should be clean so I'm not sure what reasons could there be for dark reader to not compute css for a particular site?

**Comment by bunge12** [comment]
It doesn't work for me either.  Google.com not bein inverted. Google.ca, however, works

**Comment by helpme1** [comment]
Dark mode suddenly fail to work properly on wall street journal.

https://www.wsj.com/

**Comment by Gusted** [comment]
Could it been after a new Chrome Update?

**Comment by Gusted** [comment]
![](https://i.imgur.com/H8JADmR.png)
I recommend for now to update to the lastest chrome Update with Chromium 81 And check if the issue still persist

**Comment by stytch16** [comment]
I think I know the problem. My Chrome is managed by an admin organization which has security and privacy regulations around *.google.com domains. It's essentially blocking Dark Reader from reading site data on Google websites. 

Feel free to close this. I'm very confident this is the issue for me but I'm not sure about the others who have commented so far. Thanks for the help!

**Comment by Gusted** [comment]
Well use Filter and Static theme for *.Google dynamic relies in site data to view the html of the site and make the best changes possible.

**Comment by stytch16** [comment]
How about site URLs? I think it's also blocking reading those too and that might explain why no dark reader filters had worked.

**Comment by Gusted** [comment]
Url is acces been activeTab permission while whe use <all_urls> and that triggers site data reading permission

**Comment by Gusted** [comment]
> I think I know the problem. My Chrome is managed by an admin organization which has security and privacy regulations around *.google.com domains. It's essentially blocking Dark Reader from reading site data on Google websites.
> 
> Feel free to close this. I'm very confident this is the issue for me but I'm not sure about the others who have commented so far. Thanks for the help!

wontfix(actually can't fix) I'm sorry we can't help you but the main issue had been found and maybe you can contact the admin to resolve this issue if you need any more help feel free to open another issue.
