### ISSUE TITLE
Do not enable on websites with already dark theme

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#2248]
On sites that already have their own dark themes could you add a feature to not enable Dark Reader?  Example on Youtube if you selected night mode. Or if you have multiple Gmail account and one of the accounts has a dark theme, or Pornhub site.

**Comment by Xerus2000** [comment]
You can easily disable it per site. But what I would actually appreciate is if I could switch the dark mode on these pages on/off with DarkReader, that way I don't have to do it manually all the time...

**Comment by Xerus2000** [comment]
Also, you can add these sites to https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config
The Readme is there to be read ;)

**Comment by Gusted** [comment]
Hello Their! 

What I'm hearing are Native dark Theme from the site itself. What are mostly not by default Like youtube/Gmail are by default White theme. For so far of now If you want Use the native from the site itself just disable Darkreader for that current site. A solution for your multiple gmail account is adding
`mail.google.com/mail/u/1/` this to the Not Inverted List and Make sure you have the 1 replaced with the good account number that has the dark Theme.

Regards,
Gusted

**Comment by leodoi3** [comment]
> 
> 
> Hello Their!
> 
> What I'm hearing are Native dark Theme from the site itself. What are mostly not by default Like youtube/Gmail are by default White theme. For so far of now If you want Use the native from the site itself just disable Darkreader for that current site. A solution for your multiple gmail account is adding
> `mail.google.com/mail/u/1/` this to the Not Inverted List and Make sure you have the 1 replaced with the good account number that has the dark Theme.
> 
> Regards,
> Gusted

Doesn't the number changes if you sign out of all google accounts or clear cookies?

**Comment by Gusted** [comment]
The number change when you switch account your primary account the first you logged into with that computer will be 0 the second one you logged into will be 1 etc

**Comment by Gusted** [comment]
#1327 Duplicate
