### ISSUE TITLE
Darkreader makes unselected checkboxes look selected on grubhub.com

### ISSUE THREAD

**Issue by eiriksn** [darkreader/darkreader#2249]
## Issue
When darkreader is enabled, every unselected checkbox on grubhub.com appears with a checkmark. See attached screenshots of the same page with darkreader enabled and disabled.

I've only seen this issue on grubhub.com. 

## Steps to reproduce
With darkreader enabled, open https://www.grubhub.com/restaurant/harrys-italian-pizza-bar-225-murray-st-new-york/294544/menu-item/17745394 

If above link is unreachable:
1. Open grubhub.com
2. Select any restaurant
3. Select any menu item and look at modal screen that opens.

## Browser and System Information 
Component  | Version
----------- | ------------
OS | Windows 10 1909 (18363.752)
Browser | Firefox 74.0.1 (64-bit)
DarkReader | 4.9.4

## Attachments
**1: Darkreader enabled**
![1 darkreader enabled](https://user-images.githubusercontent.com/3651296/78844606-30625600-79d4-11ea-8c72-f9f90a825dc8.PNG)

**2: Darkreader disabled**
![2 darkreader disabled](https://user-images.githubusercontent.com/3651296/78844608-32c4b000-79d4-11ea-874e-5adc81995b34.PNG)

**Comment by Gusted** [comment]
1. I don't get it even working to get to a restaurent. The Zip Code/Streets button doesn't do anything
2. ![](https://i.imgur.com/hXIehkq.png)

**Comment by eiriksn** [comment]
@Gusted Is there anything I can add to help in terms of logs, source, etc?

**Comment by Gusted** [comment]
when on the site 
Press ctrl + S 
Zip the .html and the folder into 1 zip file and drag it into the comment section where You typed the comment.

**Comment by eiriksn** [comment]
@Gusted 
[2020-04-20 2249.zip](https://github.com/darkreader/darkreader/files/4504124/2020-04-20.2249.zip)

**Comment by Gusted** [comment]
I got the 404 error pag, I meant the exact page where the checkboxes are.

**Comment by eiriksn** [comment]
This is the output Firefox gives me when using ctrl+S viewing https://www.grubhub.com/restaurant/harrys-italian-pizza-bar-225-murray-st-new-york/294544/menu-item/17745394 , I'm not sure why the contents doesn't match what's rendered by the browser. 

Using inspection tool seems more fruitful, but there's a whole lot of html here. I'm not sure which parts will be useful, so I saved all three threads in the inspection tool separately and attached them as a zip file:
![image](https://user-images.githubusercontent.com/3651296/79765651-e131f480-82f4-11ea-8fcd-a7a138133d9b.png)
[2020-04-20 2249 Inspector tool dump.zip](https://github.com/darkreader/darkreader/files/4504274/2020-04-20.2249.Inspector.tool.dump.zip)

**Comment by Gusted** [comment]
I will try to render it this time with Firefox.

**Comment by Gusted** [comment]
![](https://i.imgur.com/rFdFId7.png) It's getting weirder with a second but I got the checkboxes and will make a fix for this.

**Comment by eiriksn** [comment]
Glad it worked. Thanks! 👍

**Comment by Gusted** [comment]
I hope you know how to paste this into the devtools section of darkreader
```
grubhub.com

CSS
.s-checkbox-filler {
    color: rgb(24, 26, 27) !important;
}

================================
```
But this should work I just need you to test it on the site of it really works

**Comment by eiriksn** [comment]
![image](https://user-images.githubusercontent.com/3651296/79769958-c2366100-82fa-11ea-914c-12febebd144c.png)

![image](https://user-images.githubusercontent.com/3651296/79769857-a29f3880-82fa-11ea-9676-ff77ac869325.png)

Looks like it worked!

**Comment by Gusted** [comment]
That's right! I will open a PR for it to fix

**Comment by Ares9323** [comment]
This issue is still present on many websites (Including [Udemy](https://www.udemy.com/), screenshot below), it's pretty frequent to me and it's really annoying!
(in this case it's pretty visible because the checked ones have a different color, but before I watched a video I was really confused)

![Image](https://github.com/user-attachments/assets/5dc99b04-5624-46a0-b01d-46a8b62af768)

On [DnD Beyond](https://www.dndbeyond.com/homebrew) it creates many issues because you don't see the checkboxes at all:

![Image](https://github.com/user-attachments/assets/b4ad4899-5d6b-4cff-b9df-18c5bc633a10)

![Image](https://github.com/user-attachments/assets/9a4152ed-a293-49e3-90e2-57e57865bf41)
