### ISSUE TITLE
Dark Reader locks up Firefox chrome (rainbow spinner) for ~30 seconds on some pages

### ISSUE THREAD

**Issue by sagz** [darkreader/darkreader#2253]
On pages like hangouts.google.com on Firefox v77.0a1 (2020-04-08) (64-bit) on MacOS 10.15.4 (19E266), Dark Reader locksup the whole browser chrome while the site is still loading.

I'm happy to provide logs etc to help repro/debug this if you can give me instructions.

**Comment by Gusted** [comment]
This could be most likely a fault bug in the Niglty release of Firefox. Firefox 75.0 (64-bit) Is working fine with normal render time

**Comment by Gusted** [comment]
Just tested on 77.0a1 (2020-04-09) (64-bits) for hangouts Still normal Render time. First try to update to the lastest Nightly version And try Temportaly Disable any other Extension to see If this is really a Darkreader Bug I cannot reproduce this Issue.

**Comment by Gusted** [comment]
Hello their! 

Did you already looked into the info I gave you?

**Comment by Gusted** [comment]
#2550 Should fix this issue.
