### ISSUE TITLE
Placement of the Reset button

### ISSUE THREAD

**Issue by BRA1L0R** [darkreader/darkreader#2254]
![Screenshot_20200409_212626](https://user-images.githubusercontent.com/17928339/78933066-f1ea9b00-7aa8-11ea-8471-565df5d0f2c3.png)

I know this is old and all, but since it is on the "roadmap" I fully implemented this feature, only problem is that I don't know where to put the button. I tried to fit it in the "More" tab but it's too big, I tried with the main tab but it looks awful / it doesn't fit in there... Where should I put it?

_Originally posted by @BRA1L0R in https://github.com/darkreader/darkreader/issues/203#issuecomment-611705242_

**Comment by Gusted** [comment]
Theirs a new UI coming in Darkreader V5 https://darkreader.org/blog/dr-5-announcement/
So Far I can see now in the branch Their will be enough room for buttons.

**Comment by Gusted** [comment]
For References THis is how the Mobile UI of the new Design looks like https://github.com/darkreader/darkreader/tree/mobile-ui It will probaly the same but compatibly with Laptop/PC Screens
