### ISSUE TITLE
Active hours is a little wierd

### ISSUE THREAD

**Issue by sleeplife** [darkreader/darkreader#2258]
Hi
let me explain it complete

Its **11:44AM** right now

the Active hours [11:00PM] - [9:00AM]
but
its active right now 8O

so lets change it
I set active hours to [11:00PM] - [**6**:00AM]
It goes off 8P ( I didnt test but I think it will be ON at 11:00PM

FireFox

thanks

**Comment by Gusted** [comment]
Could it maybe that you have the wrong time set into your PC?

**Comment by Gusted** [comment]
Could this maybe relate to this issue https://github.com/darkreader/darkreader/issues/1903 ?

**Comment by sleeplife** [comment]
> Could it maybe that you have the wrong time set into your PC?

no,, its not....

> Could this maybe relate to this issue #1903 ?
thats it.... thanks
