### ISSUE TITLE
darkreader fails to darken roll20 compendium

### ISSUE THREAD

**Issue by jgkamat** [darkreader/darkreader#2262]
Example page: https://roll20.net/compendium/dnd5e/Chill%20Touch#content

It seems like the darkening is applied, then suddenly the page reverts the styling. When js is disabled, the page no longer does this, so I'm guessing there is some script on the page disabling the style.

I can reproduce on both chrome and firefox.

Toggling the extension on and off in the extension's menu restores coloring.

Some colors are applied for some reason, for example the text color is correctly applied, but the background color is reverted.

Before toggle:
![1586555351](https://user-images.githubusercontent.com/4349709/79025404-789b8880-7b3a-11ea-9718-3f3d227f9fc8.png)

After toggle:
![1586555359](https://user-images.githubusercontent.com/4349709/79025412-7b967900-7b3a-11ea-8b5d-ec4af04a9e52.png)

**Comment by Gusted** [comment]
#835 Duplicate The Style is on the wrong place placed.

**Comment by Gusted** [comment]
Closed - as duplicate
