### ISSUE TITLE
let scroll bar is excluded (at least as an option)

### ISSUE THREAD

**Issue by furkanunluturkk** [darkreader/darkreader#2270]
when i adjust the "Dark Read" to my needs (increasing the contrast - in my case), the scroll-bar is also effected by this configuration and it becomes almost hard to see the scroll bar on right side of the screen.
it would be great to (at least) have an option to exclude scroll-bar from the effect of "Dark Read".

**Comment by Gusted** [comment]
Duplicate #2108 #858 #1729

**Comment by furkanunluturkk** [comment]
> Duplicate #2108 #858 #1729

this seems to solved my problem. thank you!
https://github.com/darkreader/darkreader/issues/858#issuecomment-467411405
