### ISSUE TITLE
gerrit 3.1.3 is not available

### ISSUE THREAD

**Issue by intgyl** [darkreader/darkreader#2271]
It is not avaiable when update gerrit to 3.1.3.
Reopen the darkreader it works, but if refresh the page, it does not work again.

![image](https://user-images.githubusercontent.com/8155573/79084231-2c805c00-7d65-11ea-8128-e6a7f419d7fd.png)

**Comment by Gusted** [comment]
Are you using filter theme?

**Comment by intgyl** [comment]
1. I am using the  default gerrit theme, and darkreader  is default settings
2. It is okay when I use gerrit 3.0.0, maybe gerrit modified some theme settings.
![image](https://user-images.githubusercontent.com/8155573/79172269-d2e06600-7e26-11ea-9f73-dfaae74002ba.png)
<img width="290" alt="WX20200414-081212@2x" src="https://user-images.githubusercontent.com/8155573/79172571-b133ae80-7e27-11ea-8c69-4e7c56b2e93f.png">

**Comment by Gusted** [comment]
IDK how this could happend :/ For now Stick with their native Dark mode

**Comment by Gusted** [comment]
Could you provide a link where I can test out gerrit myself?

**Comment by FranklinYu** [comment]
Yes, this is known issue. Currently Dynamic mode won’t work with Gerrit because they are using Web Component; see https://github.com/darkreader/darkreader/issues/1264#issuecomment-486229677. Please switch to filter mode, or use the dark theme shipped with Gerrit (requires log-in).

**Comment by Gusted** [comment]
They used adoptedStylesheets which has now for a while been supported by Dark Reader.
