### ISSUE TITLE
Gmail View sections cannot display.

### ISSUE THREAD

**Issue by TheCGDF** [darkreader/darkreader#2277]
First, turn off dark reader.

Then,
Gmail -> Settings -> Display density

It will be:

![vivaldi_5EEXdCmuj0](https://user-images.githubusercontent.com/17256673/79182401-ae49b580-7e49-11ea-9394-3214501d6f7d.jpg)

But if turn on dark reader, it will be:

![vivaldi_ucnQKqtm0d](https://user-images.githubusercontent.com/17256673/79182374-9b36e580-7e49-11ea-8aff-236bfe123a6f.jpg)

**Comment by Gusted** [comment]
![](https://i.imgur.com/rteo5n8.png) You need to wait, so it can load/render I Guess.

**Comment by TheCGDF** [comment]
It's so strange. I tried to wait for a long time, but it still be blank.

Here is my config:

![vivaldi_JscQLkSncU](https://user-images.githubusercontent.com/17256673/79286993-52d8ff80-7efd-11ea-8458-136f84c8d4c4.jpg)
![vivaldi_TTCkLkEcuA](https://user-images.githubusercontent.com/17256673/79286999-55d3f000-7efd-11ea-8df5-c3fb017c4bd9.jpg)

Is it different from yours?

And My Gmail theme is "Dark".

**Comment by Gusted** [comment]
> It's so strange. I tried to wait for a long time, but it still be blank.
> 
> Here is my config:
> 
> ![vivaldi_JscQLkSncU](https://user-images.githubusercontent.com/17256673/79286993-52d8ff80-7efd-11ea-8458-136f84c8d4c4.jpg)
> ![vivaldi_TTCkLkEcuA](https://user-images.githubusercontent.com/17256673/79286999-55d3f000-7efd-11ea-8df5-c3fb017c4bd9.jpg)
> 
> Is it different from yours?
> 
> And My Gmail theme is "Dark". I tried "Default" too, also didn't work.

Got the same config, I'm gonna investigate it and see why it worked for me...

**Comment by Gusted** [comment]
Hmm right now It's even instant! Can you try to check it one more time on a new tab? Maybe this was a one time issue.

**Comment by TheCGDF** [comment]
I found the reason. My Windows system's DPI is 225%. When I set it to 100%, it works correctly.
I confirmed it again with a virtual machine.
This can explain why I sometimes encountered display problems.

**Comment by TheCGDF** [comment]
![vmware_2VRP3iORyl](https://user-images.githubusercontent.com/17256673/79329129-30bd9c80-7f52-11ea-9aee-76d5aabf95ed.jpg)
You can set Chrome's DPI to 250% or higher. You may be able to reproduce it.

**Comment by Gusted** [comment]
Ah yes modifed DPI + Darkreader + Google apps for some reason is always buggy. See #2112 
Probaly a faulty image property will look into it.

**Comment by Gusted** [comment]
![](https://i.imgur.com/4UbhtM1.png) Yes 200% zoom and got it reproduced lemme fix this real quick

**Comment by Gusted** [comment]
#2285
