### ISSUE TITLE
Weird bar displayed in Hadoop web page.

### ISSUE THREAD

**Issue by dozaza** [darkreader/darkreader#2278]
Hi,

First of all, I'm using Chrome Version 80.0.3987.163 (Official Build) (64-bit) on OSX 10.15.4.

A weird bug displayed in a very simple web page on Dyanmic mode which contains only some td/tr tables. When I change to FIlter/Filter+ mode, it worked fine, but I don't like the color in this 2 modes.
![image](https://user-images.githubusercontent.com/5456801/79184499-e3083d80-7e46-11ea-8915-cd398e8bd0b6.png)

You could find web page complete file in the following zip file.
[web_page.zip](https://github.com/darkreader/darkreader/files/4473011/web_page.zip)

Hope you guys could figure out how to fix it.

Thanks a lot for working on this magnificant browser plugin!

**Comment by Gusted** [comment]
#2256 Filter/Filter+ Has been bugged since Chromium v81

**Comment by Gusted** [comment]
![](https://i.imgur.com/vcaimVu.png) I'm not getting the bar....... Could you open the inspector tools and hover over the bar? (If hovering doens't work press ctrl + shift + c)

**Comment by dozaza** [comment]
> ![](https://camo.githubusercontent.com/596eb5b1665c288298dc3a093e7e51d71b140a72/68747470733a2f2f692e696d6775722e636f6d2f766361696d56752e706e67) I'm not getting the bar....... Could you open the inspector tools and hover over the bar? (If hovering doens't work press ctrl + shift + c)

Hi,

Did you try it in Dynamic mode? Cause I found your page didtn't look like mine, and if I opened the page in Filter+ mode, it was fine and the color seemed same as yours.

Furthurmore, I tried to inspect the page, but I couldn't hover over the bar(see screenshot below). 

At first I was wondering if other plugins might cause the problem, so I oepned the page under incognito mode and without other plugins , the bug was still there.

![image](https://user-images.githubusercontent.com/5456801/79289927-4d7bb500-7efd-11ea-92b7-40f78f6428b2.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/Qvf3Dyy.png) Nope using Dynamic still can't reproduce....  Very weird how their without any element some kind of gray

**Comment by Gusted** [comment]
BTW I'm seeing some Darkreader in the HTML could you give me the site as ctrl + s when toggling darkreader off.

**Comment by dozaza** [comment]
> BTW I'm seeing some Darkreader in the HTML could you give me the site as ctrl + s when toggling darkreader off.

Plz check the following zip file.
[web_page_without_dark.zip](https://github.com/darkreader/darkreader/files/4480209/web_page_without_dark.zip)

Besides, I found something interesting.

I tried to open the web page by python http server on localhost:80, the dark reader worked fine and nothing strange, but in original web page, the grey bar appeared... The styles of dark mode in this 2 pages were also different.

I'm sure I pressed command+s and saved the compeleted page.

![image](https://user-images.githubusercontent.com/5456801/79320896-1af1ac80-7f3d-11ea-9f73-b4e01d5c4328.png)
![image](https://user-images.githubusercontent.com/5456801/79320910-1e853380-7f3d-11ea-9ee4-a5169a18e950.png)

**Comment by dozaza** [comment]
I think I figure out the reason.

I found in CSS class "ui-state-default" or "ui-widget-content", there are some background image which won't be saved. So you will find some requests are 404. 

To solve this problem, I downloaded theses images manually and move to "image" folder. Plz check the zip file below which could reproduce the problem.

[no_dark_web_page_with_images.zip](https://github.com/darkreader/darkreader/files/4480348/no_dark_web_page_with_images.zip)

**Comment by Gusted** [comment]
I've already saw the 404 images hmm weird it didn't saved with ctrl s but will look into it after squashing  the pull requests

**Comment by dozaza** [comment]
At last, I set following css in Dev tool to hide the useless image...

CSS
.ui-widget-content {
    background-image: url() !important;
}

Et voila, problem solved...

So if you think no need to fix  this stuff, you could close the issue. Thx a lot!

**Comment by Gusted** [comment]
Well I can fix it in the config. But I need a link so it can be globally used.

```
.ui-widget-content {
background-image: none !important;
}
```
Using none is a better option to avoid any possible issues.

**Comment by dozaza** [comment]
> Well I can fix it in the config. But I need a url so it can be globally used.
> 
> ```
> .ui-widget-content {
> background-image: none !important;
> }
> ```
> 
> Using none is a better option to avoid any possible issues.

I'm not good at frontend, thx for css tips.

It is a company internal service's web page, so there is no global domain for it. Sorry.

Anyway, still apreciate for your answers!

**Comment by Gusted** [comment]
Ah That's fine just make sure if one of your collega's are using Darkreader to make sure have this fix :eyes:
