### ISSUE TITLE
Auto mode doesn't work on Android

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [darkreader/darkreader#2280]
When I choose auto option it doesn't switch with the system dark mode
My device is realme xt stock rom android 10

**Comment by Gusted** [comment]
Easily reproduced with a Huawei P Smart 2019. Seems like their is some faulty code

**Comment by xcffl** [comment]
Probably because `privacy.resistFingerprinting` is set to `true`.

**Comment by Gusted** [comment]
> Probably because `privacy.resistFingerprinting` is set to `true`.

Just checked it was by default `false`

**Comment by xcffl** [comment]
Interesting. But on my phone after switching `privacy.resistFingerprinting` to `false` and restarting Fenix, google.com and duckduckgo.com will be dark.

**Comment by xcffl** [comment]
BTW, why not use `theme.getCurrent()`?

**Comment by Gusted** [comment]
> BTW, why not use `theme.getCurrent()`?

Becuase it isn't a function?

**Comment by xcffl** [comment]
> Becuase it isn't a function?

Maybe I'm wrong, but isn't it an API? https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent

**Comment by Gusted** [comment]
![](https://i.imgur.com/Z5Zze6e.png) Only for PC/Laptop

**Comment by xcffl** [comment]
> ![](https://camo.githubusercontent.com/2056bb4396b1cdd5622ebcd319d4b1f55b3a9f5d/68747470733a2f2f692e696d6775722e636f6d2f5a355a7a6536652e706e67) Only for PC/Laptop

Ok that's fair.

**Comment by Gusted** [comment]
> Ok that's fair. But it reminds me that we can leverage it to cover situation with `privacy.resistFingerprinting` turning `true`. Anyway, maybe off-topic.

Will hold it in mind

**Comment by Gusted** [comment]
![](https://i.imgur.com/am4iy2F.png)

**Comment by xcffl** [comment]
> ![](https://camo.githubusercontent.com/11c0abcf287bb07690a02e3a484ba3b9d06b13d6/68747470733a2f2f692e696d6775722e636f6d2f616d34697932462e706e67)
> Firefox Mobile hasn't support to detect System Prefferec Color scheme but as It's in Beta and are coming major changes to the mobile-ui I think the owner of Darkeader already has noticed this and already had fix on his copy of darkreader.

Oh, no wonder mine copy on Fenix works well.

**Comment by Gusted** [comment]
> > ![](https://camo.githubusercontent.com/11c0abcf287bb07690a02e3a484ba3b9d06b13d6/68747470733a2f2f692e696d6775722e636f6d2f616d34697932462e706e67)
> > Firefox Mobile hasn't support to detect System Prefferec Color scheme but as It's in Beta and are coming major changes to the mobile-ui I think the owner of Darkeader already has noticed this and already had fix on his copy of darkreader.
> 
> Oh, no wonder my installation on Fenix works well.

Yep that make sense for so yeah maybe another way but for now I will look how Alexander gonna release darkreader v5 with good improvement and probably has a workaround for this

**Comment by axeltrinidade** [comment]
Hi. I had the same issue but for automated set time until I just read about privacy.resistFingerprinting having to be false for it to work. Could anyone help me understand why is that so?

**Comment by Gusted** [comment]
Hi @axeltrinidade!

They do this so you can't be fingerprinted if you have a dark/light mode setting on your phone.

Also Firefox Beta/Nightly seems to work with this the auto feature.
