### ISSUE TITLE
Get some collaborators

### ISSUE THREAD

**Issue by FranklinYu** [darkreader/darkreader#2281]
Hi @alexanderby I think this project might benefit from some collaborators. We have many Pull Requests pending merge. I see that recently @Myshor and @Gusted contributed a lot; maybe they can review some of the Pull Requests? So that you can focus on important changes and the overall plan.

As always, great thanks for this awesome extension.

**Comment by Myshor** [comment]
I do sometimes some review if I see some PR connected to something I was changing earlier... Still I think Alexander merges all reviewed PRs just before doing new release so they will be in pending state even after my review. :)

**Comment by alexanderby** [comment]
That's a great idea. I have to switch between coding, tech support, marketing, legal stuff and other work, so the PRs stay without the attention for a long time.

I can give @Myshor and @Gusted write permissions to the repository. You will be able to merge your Pull Requests without my review. Also, we have a monthly budget about $500, so your contributions can be supported financially.

**Comment by Gusted** [comment]
> That's a great idea. I have to switch between coding, tech support, marketing, legal stuff and other work, so the PRs stay without the attention for a long time.

You can focus on that it's good to have multiple people maintaining darkreader everyone on their own level. 

> I can give @Myshor and @Gusted write permissions to the repository.

That will be great.

**Comment by Myshor** [comment]
In code we trust. 👌

**Comment by Gusted** [comment]
> In code we trust. 👌

That's right don't trust myself yet. To accepts PR that changes codebsse yet like last time with empty shadow Dom handling 👀

**Comment by Myshor** [comment]
I can check CSS... I mess with CSS so I can check it. Maybe I will learn something new. 😄

**Comment by Gusted** [comment]
Seeming like @alexanderby need to configure some permissions
![Screenshot_20200415_094139](https://user-images.githubusercontent.com/25481501/79311254-73a15500-7efd-11ea-8cd1-bdecd64b7356.jpg)


> I can check CSS... I mess with CSS so I can check it. Maybe I will learn something new.

Don't worry you always learn new tricks if you mess with CSS of a lot of different sites.

**Comment by alexanderby** [comment]
Here I posted some guidelines for merging Pull Requests https://github.com/darkreader/darkreader/wiki/Merging-Pull-Requests

**Comment by Gusted** [comment]
> Here I posted some guidelines for merging Pull Requests [darkreader/darkreader/wiki/Merging-Pull-Requests](https://github.com/darkreader/darkreader/wiki/Merging-Pull-Requests)

Clearly Guidelines. No issues working with 👍

**Comment by Myshor** [comment]
I'll do my cleaning little later. Now I need to finish my home office work.

**Comment by Gusted** [comment]
> we have a monthly budget about $500, so your contributions can be supported financially.

*My email is on my profile*

**Comment by carocad** [comment]
Just stop by to add my two cents. Github has the option to "register" people as [code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners). Such that when opening a PR github will automatically add the owners as reviewers.

Furthermore it is possible to create [issue and pull request templates](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests). From the conversation above you have already done some work in that direction, so you can also let github do more work for you. 

Hope it helps

**Comment by Gusted** [comment]
> Furthermore it is possible to create [issue and pull request templates](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests). From the conversation above you have already done some work in that direction, so you can also let github do more work for you.

Templates :eyes: Gonna make a pull-request for it with some requirements like screenshot. Very annoying if you don't post screenshot or something else

**Comment by FranklinYu** [comment]
I slightly updated formatting of the guideline (see its revision history). Glad to see 2/3 Pull Requests closed over night! I’m closing this issue since the problem is solved. Folks are more than welcome to continue commenting here. (Or reopen the issue if necessary; I think collaborators have privilege for that.)
