### ISSUE TITLE
Doesn't work on support.mozilla.org

### ISSUE THREAD

**Issue by xerus2000** [darkreader/darkreader#2290]
It works fine on https://www.mozilla.org but on https://support.mozilla.org nothing happens when I enable DarkReader :/

**Comment by Gusted** [comment]
support.mozilla.org is a protected sited by Firefox. Extension can't modify the site.

**Comment by Gusted** [comment]
https://darkreader.org/help/en/#faq

**Comment by xerus2000** [comment]
Oh, I didn't expect a normal https site to be protected, okay, thanks

**Comment by Gusted** [comment]
No support.mozilla.org is a protected page by Firefox for security reasons other https sites work fine
