### ISSUE TITLE
Got notice about spyware, how do I know I don't have it? 

### ISSUE THREAD

**Issue by dang102** [darkreader/darkreader#2293]
got notice spyware how do I know I don't have it?

**Comment by alexanderby** [comment]
## How to check where did you install extensions from

### Chrome (Chromium)

- Open [chrome://extensions](chrome://extensions) page.
- For each extension click **Details**.
- Click **View in Chrome Web Store**.
- Dark Reader has 2,000,000+ users, extension ID is `eimadpbcbfnmbkopoojfekhnkhdbieeh`.

### Firefox

- Open [about:addons](about:addons) page.
- Click on each extension's tile.
- At the bottom click **reviews** and remove `reviews/` from the URL.
- Dark Reader has 447,538 users at the moment of writing.

### Edge

- Same steps as for Chrome, click **View in Microsoft Store**.
- Dark Reader has 51 reviews at the moment of writing,
extension ID is `ifoakfbpdcdoeenechcleahebpibofpc`.

### Opera

- Open [opera://extensions](opera://extensions) page.
- Enable **Developer mode**.
- For each extension click **Details**.
- Compare extensions' IDs.
- Dark Reader's extension ID is `eimadpbcbfnmbkopoojfekhnkhdbieeh`.
- Disable **Developer mode**.

**Comment by Gusted** [comment]
For more info about the spyware [check Darkreaders blog about it](https://darkreader.org/blog/attention/)

**Comment by brxck** [comment]
Was this a notice about spyware or an advertisement for Honey...? Because it seems like the latter.

**Comment by Gusted** [comment]
> Was this a notice about spyware or an advertisement for Honey...? Because it seems like the latter.

Biggest part is about the Spyware notice honey is just An afflation link and represents as a trusted company. But to be honest its both

**Comment by alexanderby** [comment]
@brxck It is 3 in 1: a notice about spyware, an advertisement for Honey, and a begging for donations.

**Comment by brxck** [comment]
At the very least, I would think the information actually about spyware should take priority and appear above the other two.

**Comment by alexanderby** [comment]
You can download and install the malware right now for Edge https://microsoftedge.microsoft.com/addons/detail/efhbekcgdnfcakddgllfondiaijpncol

But make sure that you have no tabs (other than protected Edge tabs) opened. Locate the profile folder (same way as for Chrome). See this `charlie.png`.

**Comment by alexanderby** [comment]
> At the very least, I would think the information actually about spyware should take priority and appear above the other two.

I think it is.

**Comment by yeeeeeet224** [comment]
Bitdefender is a pretty great firewall/antivirus/malware detector/malicious site blocker/anti tracker/password manager. Here are their extensions for Chrome:
[Anti-Tracker](https://chrome.google.com/webstore/detail/bitdefender-anti-tracker/khndhdhbebhaddchcgnalcjlaekbbeof)
[Password Manager](https://chrome.google.com/webstore/detail/bitdefender-wallet/gannpgaobkkhmpomoijebaigcapoeebl)
[Malicious Site Blocker](https://chrome.google.com/webstore/detail/trafficlight/cfnpidifppmenkapgihekkeednfoenal)
It might be the case that you need a Bitdefender subscription to use these, but we do, and I can tell you that the only reason our hard disk has not been wiped or overwritten or worse is because of Bitdefender. Check them out!

**Comment by BananaManCJ** [comment]
> You can download and install the malware right now for Edge https://microsoftedge.microsoft.com/addons/detail/efhbekcgdnfcakddgllfondiaijpncol
> 
> But make sure that you have no tabs (other than protected Edge tabs) opened. Locate the profile folder (same way as for Chrome). See this `charlie.png`.

That link 404's now, I think they removed it

**Comment by alexanderby** [comment]
@BananaManCJ Yes, I told them to scan all PNGs. But they didn't respond how many extensions did they remove and what are their next steps.

People are asking how they could be affected. [Here](https://www.dropbox.com/s/5a4sfovbjwrv5ys/MALWARE_Edge_efhbekcgdnfcakddgllfondiaijpncol.zip?dl=0) is the archive with the malware for Edge, just in case somebody wants to solve the puzzle and try understanding, what the app is exactly doing. Start digging from `XmlHTTPRequest`.

**Comment by Gusted** [comment]
> > @BananaManCJ Yes, I told them to scan all PNGs. But they didn't respond how many extensions did they remove and what are their next steps.
> > 
> > People are asking how they could be affected. [Here](https://www.dropbox.com/s/5a4sfovbjwrv5ys/MALWARE_Edge_efhbekcgdnfcakddgllfondiaijpncol.zip?dl=0) is the archive with the malware for Edge, just in case somebody wants to solve the puzzle and try understanding, what the app is exactly doing. Start digging from `XmlHTTPRequest`.
> 
> So the malware is probably hidden in one of the pngs?

If I see it like that way probably yes but I'm going to dig a little bit deeper this weekend into that malware.

**Comment by dang102** [comment]
Ok all I want to know should I stop using dark reader ? and what do u think they got already If I have the virus?

**Comment by Gusted** [comment]
You should NOT stop using darkeader if you are using the official one. If you have the virus I'm still researching what it does
________________________________

**Comment by BananaManCJ** [comment]
Do you know if the virus persists after uninstallation?

**Comment by Gusted** [comment]
> Do you know if the virus persists after uninstallation?

It isn't possible to persist after uninstall action with any extension due how Chromium extensions works. Just uninstall the current one, navigate to https://github.com/darkreader/darkreader scroll down until you see chrome webstore and Firefox webstore and download it again to be sure you have the correct one. The settings will be synced back when installing the official one.

**Comment by BananaManCJ** [comment]
That's good, thankfully I never had the fake one

**Comment by Gusted** [comment]
> That's good, thankfully I never had the fake one

It was pretty tricky to get a fake one. Don't know how some even managed to download or even get their

**Comment by Gusted** [comment]
Not longer pinned, everyones knows about it.
