### ISSUE TITLE
Text in black on google docs

### ISSUE THREAD

**Issue by Noobyprogrammer** [darkreader/darkreader#2296]
When working on Google Docs, I usually activate Dark reader because too much white is frustrating and stressful for the eyes. Anyway, when I need to work with anyone who doesn't have Dark Reader or I need to deliver the work, there is black portions of text scattered around the document. Changing the highlight doesn't do anything and the only way to delete them is to "Erase Formatting". It isn't hard to do but it sure isn't convenient.
 
Thx for all the hard work!

**Comment by Myshor** [comment]
I think all depends how text is saved in document. If something is forced to be black by user who was creating it you can't do anything. I saw similar situations in MS Office with full dark theme set in win10 (all cells default black and text white). Some older xls was "empty" because of font color set to black not automatic.

**Comment by Gusted** [comment]
Could try to provide an screenshot describing this situation as I always works with darkreader and with students that doesn't have darkreader and don't had any big issues with it.

**Comment by Noobyprogrammer** [comment]
Also the problem is VERY less frequent from the past updates. I don't have any screenshots (bc easy to fix issue), but its not the text that is highlighted in black but more like parts of the document. Deleting the text in the box doesn't do anything, bc the text underneath will be in the black box.  Finally, last time I got this issue, I was pasting text from another website (so maybe from that?).

**Comment by Gusted** [comment]
> Also the problem is VERY less frequent from the past updates. I don't have any screenshots (bc easy to fix issue), but its not the text that is highlighted in black but more like parts of the document. Deleting the text in the box doesn't do anything, bc the text underneath will be in the black box.  Finally, last time I got this issue, I was pasting text from another website (so maybe from that?). 


That's very strange I will try try to reproduce but in my 6 months of using this extension alongside Google docs I never got anything similar

**Comment by Myshor** [comment]
I would be nice to have some porblematic document or at least part of document to compare it in desktop office. I don't want to change all forced black color in documents to white. Specially when it happens less frequent.

**Comment by Gusted** [comment]
> I would be nice to have some porblematic document or at least part of document to compare it in desktop office. I don't want to change all forced black color in documents to white. Specially when it happens less frequent.

Yeah this ☝️ 
Even tho because I wouldn't know even any CSS selectors that google docs, that implement sections into the doc.
