### ISSUE TITLE
Unsupported on Firefox for Android (beta)

### ISSUE THREAD

**Issue by ashthespy** [darkreader/darkreader#2303]
Just updated the Firefox for Android (beta) to the following version, and unfortunately found the add on marked as incompatible.

```
75.0.0-beta.5 (Build #2015734507)
37.0.4, 5288e1e91
GV: 75.0-20200403064004
AS: 0.55.2
```
Any ideas?

**Comment by Gusted** [comment]
It seems like mozzila changed some things. Don't accept that darkreader will be installed for beta verion as I also can't right now for my nightly firefox. Normal Firefox It installed with no problems.

**Comment by ashthespy** [comment]
Not sure what's going on, but it works fine with the Firefox nighty.

```
Nightly 200417 06:01 (Build #21080611)
39.0.20200416130123, a8ddaba97
GV: 77.0a1-20200415092524
AS: 0.57.0
```

**Comment by Gusted** [comment]
That's weird can you check with the beta one if you can download any other addons?

**Comment by ashthespy** [comment]
> 
> 
> That's weird can you check with the beta one if you can download any other addons?

Nope, and only ublock Origin survived, I can no longer install/see any other addons from the beta, thought nightly seems to have.
Looking at the release notes (https://support.mozilla.org/en-US/kb/whats-new-firefox-preview) I see:
>* uBlock Origin is now supported.

**Comment by alexanderby** [comment]
As far as I know that was done intentionally by Mozilla. Dark Reader works for Nightly though.

**Comment by Gusted** [comment]
> As far as I know that was done intentionally by Mozilla. Dark Reader works for Nightly though.

But for (Beta) versions of firefox don't work, seem's like Mozilla than decided something without telling you and probably other extension as well...

**Comment by alexanderby** [comment]
Beta is now Firefox Preview, I don't remember where I've seen that.

**Comment by Gusted** [comment]
> Beta is now Firefox Preview, I don't remember where I've seen that.

'Firefox Preview marks a release of the early version for an experimental Firefox browser for Android. Built on Geckoview, Firefox is a pilot for early adopters` Straight from their play store details.

**Comment by Gusted** [comment]
Firefox has cleaned most of it's version. All `new` edition is supported by dark reader otherwise open up a Issue if there are troubles.
