### ISSUE TITLE
All icons in links disappear in all sites

### ISSUE THREAD

**Issue by Ahmed0425** [darkreader/darkreader#2314]
Watch this!
https://imgur.com/a/WFpIAaX
As you can see, all icons in the top bar, comments number icon, the icon beside the phone finder and search links and many other countless sites
The website used for this test is gsmarena.com

**Comment by Gusted** [comment]
Do you use dynamic theme?

**Comment by Ahmed0425** [comment]
Yes

**Comment by Gusted** [comment]
Did you used Firefox or chromium based browser as I couldn't reproduce it in a chromium based browser

**Comment by Ahmed0425** [comment]
Firefox

**Comment by Gusted** [comment]
![](https://i.imgur.com/GsV6WSJ.png) Can you check this one more time please as I can't reproduce this issue. Maybe an adblocker is causing this.

**Comment by Ahmed0425** [comment]
Well, I have 2 points to say

- The dynamic mode doesn't appear like this with me, It appears exactly like the picture above
- Did you test it on firefox? or one of its forks? Surprisingly, at least for me, The addon worked fine with icedragon

**Comment by Gusted** [comment]
I've tested it with Firefox nightly

**Comment by Gusted** [comment]
Do you use any sepia or contrast or any of the Filter settings as I just can't reproduce this issue.

**Comment by Ahmed0425** [comment]
As said, the problem was reproduced only when I enforced custom font and all other features work fine even with static mode so, it might be a problem related to fonts (Like missing fonts or something)
https://imgur.com/Vt6bsrT
These are all fonts appeared in the extension .. Should they be different? and how do I figure what the problem with fonts is?

**Comment by Gusted** [comment]
> As said, the problem was reproduced only when I enforced custom font and all other features work fine even with static mode so, it might be a problem related to fonts (Like missing fonts or something)
> https://imgur.com/Vt6bsrT
> These are all fonts appeared in the extension .. Should they be different? and how do I figure what the problem with fonts is?

Font's? That caused the issue with Static ah Just use for the site default one Segoe UI or use another extension that may be more specialized in Font's changing

**Comment by Gusted** [comment]
> > As said, the problem was reproduced only when I enforced custom font and all other features work fine even with static mode so, it might be a problem related to fonts (Like missing fonts or something)
> > https://imgur.com/Vt6bsrT
> > These are all fonts appeared in the extension .. Should they be different? and how do I figure what the problem with fonts is?
> 
> Font's? That caused the issue with Static ah Just use for the site default one Segoe UI or use another extension that may be more specialized in Font's changing

Does this reaction resolves your issue?

**Comment by Ahmed0425** [comment]
https://imgur.com/Gy5Q2nw
Disabling the entire feature works!

**Comment by Gusted** [comment]
> https://imgur.com/Gy5Q2nw
> Disabling the entire feature works and this is what I did when I wrote the 7th comment
> 
> > EDIT
> > After some additional tests, It worked after disabling the force custom font feature and this problem was reproduced in both Icedragon and Firefon

That's right custom fonts caused this... So far I see the site implementation of the icons was not the greatest. If you can live withour the don't than I can call this a resolved issue
