### ISSUE TITLE
CSS property 'background' with 'background-clip: text'

### ISSUE THREAD

**Issue by SanmayJoshi** [darkreader/darkreader#2318]
## Problem
In Dynamic theme, text with gradient (using `background: linear-gradient()` and `background-clip: text`) is not readable.

## Possible cause/solution
I do not fully understand how Dark Reader works but maybe, in Dynamic theme, Dark Reader treats CSS property `background` the same whether or not it is used with CSS property `background-clip: text;`. This results in making the color of text darker rather than lighter.
Treating CSS property `background` with `background-clip: text` in the same way as CSS property `color` may help solve the problem.

## Example
I am working on a project named [Softorage](https://softorage.com/). You may visit it with Dark Reader set to `on` (Dynamic theme), to see the issue in action.

Thanks for this awesome extension!

**Comment by Gusted** [comment]
Darkreader don't have a parser for linear-gradient.
Background-clip? give me an exact URL and which element as I know background-clip is supported in darkreader...

**Comment by SanmayJoshi** [comment]
Thanks for reply.

On the given link (Softorage), brand name on navbar (fixed on top) uses `background-clip: text;` (see for class `.tg`), as also the text on the hero section. Also, on the footer, brand name uses the same.

In any case, as you pointed out, it may be because of linear gradient, and not `background-clip`. Will update here, after a few experiments.

**Comment by SanmayJoshi** [comment]
Seems like Dark reader is adding `background-image: linear-gradient(36deg, rgb(115, 33, 42), rgb(29, 40, 101));` in respective class (here `.tg`), for `background: linear-gradient(36deg, rgb(252, 70, 107), rgb(63, 94, 251));`

**Comment by Gusted** [comment]
![](https://i.imgur.com/ySNGM7T.png) Is this sussposed to be?

**Comment by Gusted** [comment]
> Seems like Dark reader is adding `background-image: linear-gradient(36deg, rgb(115, 33, 42), rgb(29, 40, 101));` in respective class (here `.tg`), for `background: linear-gradient(36deg, rgb(252, 70, 107), rgb(63, 94, 251));`

After taking a look darkeader darkens linear-gradient so it's darken the color like darkreader needs to do.

**Comment by SanmayJoshi** [comment]
> Is this supposed to be?

I'm sorry. I didn't understand the question. The class `.tg` is correct, if that is what you're asking.

> After taking a look darkeader darkens linear-gradient so it's darken the color like darkreader needs to do.

Should darkreader be darkening a linear-gradient when there is CSS property `background-clip: text;` with it (where 'it' is `background: linear-gradient(...);`)? I was under the impression that `background-clip: text;` makes the background color (linear-gradient or not) appear as if it is text color (subject to `color: transperant;` being set). Please correct me if wrong.

---
I appreciate your efforts.

**Comment by Gusted** [comment]
> I'm sorry. I didn't understand the question. The class `.tg` is correct, if that is what you're asking.

nvm figured it out

> Should darkreader be darkening a linear-gradient when there is CSS property `background-clip: text;` with it (where 'it' is `background: linear-gradient(...);`)? I was under the impression that `background-clip: text;` makes the background color (linear-gradient or not) appear as if it is text color (subject to `color: transperant;` being set). Please correct me if wrong.

After taking a good look at [this documentation from Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip) background-clip is just being used to define/extend where hte background-color should be as color: don't support linear gradient. It use background-clip: text so the background-color is being used as the color.


> I appreciate your efforts.

I'm just doing my job

**Comment by SanmayJoshi** [comment]
> After taking a good look at this documentation from Mozilla background-clip is just being used to define/extend where hte background-color should be as color: don't support linear gradient. It use background-clip: text so the background-color is being used as the color.

I don't understand. If darkreader understands that CSS property `background: linear-gradient(...)` is used to color text, when used with `background-clip: text`, then why would darkreader darken the colors in gradient. Text colors turn from black(ish) to white(ish), right? 

> I'm just doing my job

Blive me, u r good 8 it! 😄

**Comment by Gusted** [comment]
> I don't understand. If darkreader understands that CSS property `background: linear-gradient(...)` is used to color text, when used with `background-clip: text`, then why would darkreader darken the colors in gradient. Text colors turn from black(ish) to white(ish), right?

As of it will be used to color the foreground of the logo, that's why it's being darken. Why it turns from blackish to whiteish That could be solved with a manual CSS fix. 

> Blive me, u r good 8 it! 😄

Ty!

**Comment by Gusted** [comment]
I've created a fix for this #2336

**Comment by SanmayJoshi** [comment]
> I've created a fix for this #2336

Thanks, but I hope you don't mind if I take discussion to a bit general case. 

> Why it turns from blackish to whiteish(IDK) That could be solved with a manual CSS fix.

No, I am not saying that text color turning from dark to lighter is a problem. I am saying that it is my observation that generally 
1. darkreader turns black colored text to white, and it is perfect
2. darkreader darkens the background color, and it is perfect.

What I am trying to say is that: 
Why would darkreader darken the colors in CSS property `background` when used with CSS property `background-clip: text`, if darkreader understands that when CSS property `background` is used with `background-clip: text`, value specified for CSS property `background` is used to color text. I believe (as stated above in point 1) that text color changes from black(darker) to white(lighter).

**Comment by Gusted** [comment]
@alexanderby 
He created the function to darken the colors, he can explain it the best

**Comment by Gusted** [comment]
> Thanks, but I hope you don't mind if I take discussion to a bit general case.

No problem
 
> No, I am not saying that text color turning from dark to lighter is a problem. I am saying that it is my observation that generally
> 
> 1. darkreader turns black colored text to white, and it is perfect
> 2. darkreader darkens the background color, and it is perfect.
> 
> What I am trying to say is that:
> Why would darkreader darken the colors in CSS property `background` when used with CSS property `background-clip: text`, if darkreader understands that when CSS property `background` is used with `background-clip: text`, value specified for CSS property `background` is used to color text. I believe (as stated above in point 1) that text color changes from black(darker) to white(lighter).

I think as it like you said it's turns dark to lighter is a bit of a problem as just resetting the inital value of the CSS works and looks fine. The function could get some improvements for this and as Darkreader V5 will be released hopefully soon it may or may not have.
