### ISSUE TITLE
How to ignore a class?

### ISSUE THREAD

**Issue by sibbngheid** [darkreader/darkreader#2322]
Hi, I'm using DarkReader on figma.com. It'is converting colors pickers color to darker. Color pickers uses inline background-color for colors.

I tried INVERT and CSS but didnt get success. INVERT helps to get close color but not exact.
CSS and background-color rule is didn't help too. Because i can't get its original color.

Is there someting like:

IGNORE
selector

**Comment by Gusted** [comment]
> Hi, I'm using DarkReader on figma.com. It'is converting colors pickers color to darker. Color pickers uses inline background-color for colors.
> 
> I tried INVERT and CSS but didnt get success. INVERT helps to get close color but not exact.
> CSS and background-color rule is didn't help too. Because i can't get its original color.
> 
> Is there someting like:
> 
> IGNORE
> selector

Hey their!

Their is in the dynamic theme not such section for ignore it could be a feature to be honest if you don't mind making another issue for that.
But if you mind sharing which css you want to change, I will take a look at it

**Comment by sibbngheid** [comment]
https://www.google.com/search?&q=color+picker

![image](https://user-images.githubusercontent.com/19991745/79783234-03556200-8349-11ea-98fb-d0650249c352.png)

**Comment by Gusted** [comment]
Hmm the bgcolor is dynamic not static. THis can't be fixed with CSS

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/tree/Ignore-Section We are working on a new section for this as google sheets also can be improved trough this

**Comment by Gusted** [comment]
Darkreader v5 Will have
IGNORE INLINE STYLE (Patch has been merged)
Thank you for the suggestion
