### ISSUE TITLE
restore To default setting

### ISSUE THREAD

**Issue by minutesinch** [darkreader/darkreader#2326]
i make a lot of change for darkreader and make my browser slow and firefox say darkreader may slow down browser speed in yellow(when i disable darkreader my browser work normaly), so i ave 2 choice, first remove and reinstall darkreader or restore to default setting but there is no option like this please add, thank you.

**Comment by Gusted** [comment]
#203

**Comment by minutesinch** [comment]
Why you closing issue??

**Comment by Gusted** [comment]
Duplicate
