### ISSUE TITLE
Ugly background color on news.ycombinator.com

### ISSUE THREAD

**Issue by jamy015** [darkreader/darkreader#2331]
With the dynamic theme, the main table of news.ycombinator.com has a kind of ugly green background. I tried to fix it with this CSS:

```
CSS
#hnmain {
    background-color: #181a1b !important;
}
```

...but then it doesn't change along with the background of the rest of the page when changing brightness, contrast, sepia, or grayscale. Please let me know how to fix this.

**Comment by Gusted** [comment]
Well, as the orignal page has yellow colors onto the background-color darkreader just darkens the background color and everything is visble. So you say 'green background' Can you show your filter config as I just get a darken yellow background color.

**Comment by jamy015** [comment]
Dynamic mode with no brightness, contrast, sepia or grayscale adjustments.

As far as I can tell, the original page does not have yellow backgrounds. The background of the main table is `#f6f6ef`, which is [definitely a shade of gray](https://www.color-hex.com/color/f6f6ef). When I turn Dark Reader on, this seems to change into `#272716` , which to me seems like a [dark/'army' green](https://www.color-hex.com/color/272716). _Note: When viewing the colors, switch off Dark Reader, otherwise you see both colors as #272716 😄_

For reference, this is what the page looks like for me when switching on Dark Reader:
<img src="https://user-images.githubusercontent.com/3188721/79702170-2594a480-82a3-11ea-99ac-1f9164dcae8d.png" width="300px">

**Comment by Gusted** [comment]
> ```
> CSS
> #hnmain {
>     background-color: #181a1b !important;
> }
> ```

With this fix you are just removing the background-color what isn't susspose to be.

as Of the colors I still thinks darkreaders darken this correctly as for MY opinion the main background-color when switching darkreader of have a tint of yellow.

**Comment by jamy015** [comment]
Ok, I understand that your opinion is different. In that case, can you help me with a 'fix' that I can apply locally using the dev tools? As far as I'm concerned, the fix then doesn't necessarily have to be merged into the project.

**Comment by Gusted** [comment]
> Ok, I understand that your opinion is different. In that case, can you help me with a 'fix' that I can apply locally using the dev tools? As far as I'm concerned, the fix then doesn't necessarily have to be merged into the project.

Use stylus for that, I don't recommend darkreaders dev tools to do this.
