### ISSUE TITLE
discuss.atom.io impossible to enable

### ISSUE THREAD

**Issue by yairopro** [darkreader/darkreader#2333]
![image](https://user-images.githubusercontent.com/8110568/79699220-caf54b80-8296-11ea-8ece-cbc4529c1e8f.png)

**Comment by Gusted** [comment]
Could you describe your issue as first I just can toggle it without any issues.

**Comment by yairopro** [comment]
First, thank you so much for this extension as i use it all the time (love dark).

[See screen record here](https://photos.google.com/share/AF1QipOR9gvuegBY7VFiq_bpRyQ-4JeFMlOxz-OO6qP7q8ctbc8np6eI3IFmm9Aw45agkQ/photo/AF1QipNbV_j-IpBYiJFGAOn7dxhJq7bgE9acquoVQEu_?key=ZTZNOUJZVElrbWdWUzRVM25qQjlPWU5KT2ZzUWFB) (for a better quality if you cannot see well, you can download the video)

**Comment by Gusted** [comment]
That's some weird shit, Do you got any errors on the site? (Ctrl + shift + i) and than go to the console?

**Comment by yairopro** [comment]
Sorry I should have done that first.
![image](https://user-images.githubusercontent.com/8110568/79750394-8e1e6880-8319-11ea-868c-a6166148d4d2.png)

**Comment by Gusted** [comment]
> Sorry I should have done that first.
> ![image](https://user-images.githubusercontent.com/8110568/79750394-8e1e6880-8319-11ea-868c-a6166148d4d2.png)
> 
> Clicking on the button doesn't log anything

Just warnings from atom itself... 
Can you open chrome://extension and click on background/index.html or background page to make sure their are also no errors.

**Comment by yairopro** [comment]
he.. `background/index.html` in chrome extensions ? I don't get it ... sorry

![image](https://user-images.githubusercontent.com/8110568/79754192-d04aa880-831f-11ea-97db-3e35eeba6bc8.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/fhqgOC4.png)
The orange link

**Comment by Gusted** [comment]
Hi their! @yairopro

Do you had atom.io toggled.

**Comment by yairopro** [comment]
> Do you had atom.io toggled.

No I don't.

> Can you open chrome://extension and click on background/index.html or background page to make sure their are also no errors.

Sorry for the time to reply.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8110568/81532498-246c0a00-936d-11ea-976f-a76d972f7f3f.gif)



Here are the logs
[discuss.atom.io-darkreader.log](https://github.com/darkreader/darkreader/files/4607946/discuss.atom.io-darkreader.log)

**Comment by Gusted** [comment]
Maybe resetting your settings and site list will help as no errors are found....

Devtools -> preview new design
Settings - > reset

**Comment by yairopro** [comment]
> Here are the logs
discuss.atom.io-darkreader.log

I updated the log files . I closed all other tabs and opened the logged object.

> Maybe resetting your settings

Doesn't help.

**Comment by Gusted** [comment]
Hi @yairopro 

You have currently atom.io in your sitelist that caused this bug in darkreader V5 Subdomain control will be a think and resolve this

Regards,
Gusted

**Comment by Yash-Singh1** [comment]
@yairopro 
1. Is this specific to discuss.atom.io?
2. Reset all the settings
3. Check the automation section under settings
4. Make sure that discuss.atom.io is not in the site list
5. Go to chrome://extensions, and go to Details under Dark Reader and toggle on Collect Errors
6. Try reinstalling chrome

Also, @Gusted, looks like the following error is appearing for discuss.atom.io, don't know if it is related:
```
Access to fetch at 'https://sjc3.discourse-cdn.com/business6/stylesheets/poll_1352a6876d4e077243c660a6efde2b4a35e0e21b.css?__ws=discuss.atom.io' from origin 'chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled
```
![Screenshot from 2020-09-26 16-09-42](https://user-images.githubusercontent.com/53054099/94351818-b752cb80-0012-11eb-9c6e-ca248a721e8b.png)

**Comment by Gusted** [comment]
> Also, @Gusted, looks like the following error is appearing for discuss.atom.io, don't know if it is related:

Not sure, what you have been doing. But all fetches are being redirected to background-scripts. By any chances you have stack trace?

**Comment by yairopro** [comment]
Hi
I've forgotten about this issue.
I don't go to the website anymore.
We can close it.
Thanks for your support.

PS: I love your extension !
