### ISSUE TITLE
Gitea will be render much slow when DarkReader is on.

### ISSUE THREAD

**Issue by sometao** [darkreader/darkreader#2338]
When turn DarkReader ON, 

Click `repositories` `users` `organizations` links on page https://gitea.com/explore/users, page render mush slower.

**Comment by Gusted** [comment]
Which theme are you using
Which browser are you using?

**Comment by sometao** [comment]
> 
> 
> Which theme are you using
> Which browser are you using?

Both firefox(75.0 64bit) and chrome(80.0) much slower when DarkReader is On, on the Gitea Pages.
Custom theme and Default them on Firefox are both slow.
Dynamic theme on Chrome is slow.

But, I found that: 
Filter/Filter+/Static themes on Chrome are not slow.

DarkReader version:
4.9.4 on firefox.
4.8.10 on Chrome.

**Comment by Gusted** [comment]
Yes I get the long loading time on Chrome very weird.
Dynamic theme is know for the whatl onger loading time but this long it's for sure a bug or something.
Yeah Filter/Filter+/Static Are semi-premade styles so Darkreader just fills the right values into and give them to the elements and poof you got the theme.
Dynamic calculates and computes the best option for each element and that cause the long time but this long Is a bit ridiculos I agree I will try to profile it..

**Comment by nerd** [comment]
For me it seems that after visiting Gitea with any Chromium-based browser equipped with Dark Reader 4.9.4 on Linux, the Dark Reader extension will stop functioning until I restart my browser.

**Comment by Gusted** [comment]
I'm trying to profile the site but the site crash the f*ck out with when profiling...

**Comment by Gusted** [comment]
Has been resolved by #2550
