### ISSUE TITLE
isbgpsafeyet.com

### ISSUE THREAD

**Issue by jamy015** [darkreader/darkreader#2342]
https://isbgpsafeyet.com/ is fairly broken in dynamic mode. It works pretty well in filter mode, though.

**Comment by Gusted** [comment]
![](https://i.imgur.com/x1hyBSI.png)
They have like a whole list of this color so... ![](https://i.imgur.com/pogE0WB.png)

**Comment by Myshor** [comment]
Quickfix done with removing problematic background:
![image](https://user-images.githubusercontent.com/56877029/79912191-ed67a000-8421-11ea-9b19-8ae3151ce7e5.png)

Will it be acceptable?

**Comment by Gusted** [comment]
All the titles and h3 h4 etc are not visible

**Comment by Myshor** [comment]
I'll do more fixes to the branch tomorrow. I turned off PC already. 😉

**Comment by Myshor** [comment]
Added fixes for headers and button color.
![image](https://user-images.githubusercontent.com/56877029/79951129-6e518680-8478-11ea-8e07-774640c08078.png)

**Comment by Gusted** [comment]
#2348 has been merged
