### ISSUE TITLE
I am getting  404 for multiple-arrow.png

### ISSUE THREAD

**Issue by KhalilMohammad** [darkreader/darkreader#2343]
getOKResponse is querying my server for this image (multiple-arrow.png)

I am getting a bunch of 404 each time, I visit site.
Problem is we keep track of 404s, We have zero internal 404 except this thing.

**Comment by Gusted** [comment]
Hmm could you give the site link?

**Comment by KhalilMohammad** [comment]
Site is behind login, I cannot share login credentials.

Also, One other thing.
I do not get 404 on all pages.

Also, I only get 404 from this plugin.
I mean site it self does not request this image.

**Comment by Gusted** [comment]
Does the site you go to like end with a .html or .htm or .php instead of no extension behind it.

**Comment by Gusted** [comment]
example:

https://somesite.com/login/pagethathave/404errors.html

**Comment by KhalilMohammad** [comment]
[image: image.png]

**Comment by Gusted** [comment]
> [image: image.png] 

Drop the image in the github comment section

**Comment by Gusted** [comment]
@KhalilMohammad

**Comment by KhalilMohammad** [comment]
https://mmcapp001.azurewebsites.net/images/multiple-arrow.png

**Comment by Gusted** [comment]
That's weird, what's the original url()

**Comment by KhalilMohammad** [comment]
I did not fully debug, I will give you original url in a day or two.

**Comment by KhalilMohammad** [comment]
For some reason, we did not need the image anymore and I deleted it from the server.
After dark reader made about 200 tries to get the image in 10 minutes.
It was doing it like an endless loop.

I added the image again and reloaded the page.

I got sidetracked in other projects.
I will try to provide you more information as soon as possible.

**Comment by KhalilMohammad** [comment]
I have added a screenshot of the request call stack.

![Annotation 2020-07-25 010830](https://user-images.githubusercontent.com/17926533/88431260-686e9700-ce13-11ea-94a5-bf7f484adcec.png)

**Comment by Gusted** [comment]
#2543 check the linked PR. It will be pushed next released(ETA next week)

**Comment by Gusted** [comment]
You could build darkreader from source and have a look if it has been fixed.

**Comment by KhalilMohammad** [comment]
I debugged dark reader and found that I do have a URL for the above image in the CSS file.
So it's actually not a 404 error.

The last error that I had was it was trying to download multiple times like 200 tries in 10 minutes.
If this is also fixed. You can close the ticket.
