### ISSUE TITLE
Generate a light theme for inherently dark websites

### ISSUE THREAD

**Issue by pranjlp** [darkreader/darkreader#2345]
Would it be possible, if the site, like spotify, that natively implements a dark color scheme, could be toggled to light? 
Maybe its not in the scope of this project, given the name. However, this is my go to addon for switching to dark mode during low light. It would be great if it works other way round.

**Comment by Gusted** [comment]
This is with the current code not possible and it will most likely not/never implemented as this is darkreader and not lightordarkreader
