### ISSUE TITLE
Dynamic mode is not working

### ISSUE THREAD

**Issue by oshanz** [darkreader/darkreader#2347]
for this site dynamic mode is not working, but static mode is not bad

https://rubygems.org/gems/rails

- Dynamic mode
![image](https://user-images.githubusercontent.com/5364479/79898619-2a836080-8429-11ea-973c-23fdbabff367.png)

- Static mode

![image](https://user-images.githubusercontent.com/5364479/79898665-44bd3e80-8429-11ea-9b58-d2dfcb052856.png)

**Comment by Myshor** [comment]
Can you tell us what browser is used and what dark reader extension version?

I can not reproduce it in my Chrome on Windows 10 (screen from Dynamic Mode):
![image](https://user-images.githubusercontent.com/56877029/79910969-e17ade80-841f-11ea-9549-9151ca56d7a3.png)

**Comment by oshanz** [comment]
@Myshor Firefox Developer Edition 76.0b5 (64-bit)
Dark Reader version 4.9.4

**Comment by Gusted** [comment]
This really weird it's seems like the site tried to override any external stylesheet but I will look for a workaround.

**Comment by Gusted** [comment]
Firefox is like usual being Firefox

**Comment by Gusted** [comment]
Hello their can you check with darkeader 4. 9.6 if this issue has been resolved @oshanz

**Comment by oshanz** [comment]
yup looks good. Thanks @Gusted :1st_place_medal:
