### ISSUE TITLE
Filter mode suddenly became slow on loading dark background

### ISSUE THREAD

**Issue by ballII** [darkreader/darkreader#2351]
![image](https://user-images.githubusercontent.com/7100993/80016856-4a3c8680-8506-11ea-803a-23c07ce21d98.png)

(Dear Reader 4.9.4)

When a page is newly loaded in the Filter mode, it takes a while for a white background to turn dark, which creates a disturbing white-flash effect every time when I open a new page. The problem did not exist until minutes ago when I restarted my browser. Before that the background always started with a dark color.

The problem does not exist in the Dynamic mode.

**System Information:**
 - OS: macOS 10.10.5
 - Browser: Chrome 81.0.4044.113 (Official Build) (64-bit)

**Comment by Gusted** [comment]
Switch for now to dynamic/static as this isn't the behaviour it should be.

**Comment by Gusted** [comment]
Which version of darkreader do you use?

**Comment by ballII** [comment]
> Which version of darkreader do you use? 4.9.5 Should fix this

Mine is 4.9.4, which is the present version provided in the Chrome web store. I will wait for 4.9.5 to come out. Thank you.

**Comment by Gusted** [comment]
> > Which version of darkreader do you use? 4.9.5 Should fix this
> 
> Mine is 4.9.4, which is the present version provided in the Chrome web store. I will wait for 4.9.5 to come out. Thank you.

If you want to I can make a compiled version with the patch as of the extension can take up to 2 weeks before chrome accepts it

**Comment by ballII** [comment]
> > Mine is 4.9.4, which is the present version provided in the Chrome web store. I will wait for 4.9.5 to come out. Thank you.
> 
> If you want to I can make a compiled version with the patch as of the extension can take up to 2 weeks before chrome accepts it

I would appreciate it! Looking forward to trying 4.9.5 to see if it works normally on my computer.

**Comment by Gusted** [comment]
[build.zip](https://github.com/darkreader/darkreader/files/4522525/build.zip)
I hope you know how to sideload this.
PS this build contains a preview of the new UI.
Open Devtools in the popup
Click on New Design

**Comment by ballII** [comment]
> [build.zip](https://github.com/darkreader/darkreader/files/4522525/build.zip)
> I hope you know how to sideload this.
Thank you! It's working. The white-flash problem no longer exists.

**Comment by ballII** [comment]
> Good to hear! Make sure you switch to the webstore version over around 2 weeks when the new update has been accepted.

And I did not understand the ["Building for use"](https://github.com/darkreader/darkreader#building-for-use) section until you generated the build.zip for me. Now I can do it, too! Glad I've learned something. Thank you. :D

**Comment by Gusted** [comment]
> And I did not understand the ["Building for use"](https://github.com/darkreader/darkreader#building-for-use) section until you generated the `build.zip` for me. Now I can do it, too! Glad I've learned something. Thank you. :D

No problem 😅 Have a good day
