### ISSUE TITLE
Side banners not rendering when scrolling (on chrome) [BUG]

### ISSUE THREAD

**Issue by arealuser** [darkreader/darkreader#2352]
Thank you very much for creating this extension. It is extremely useful :)

**Describe the bug**
Over the past week or two, I noticed a lot of sites don't get properly inverted (I attached pictures from Wikipedia and Quora as examples, but this has been happening to me on a lot of sites).

When I open the site, it seems to be properly inverted, but the side banners of the background are only inverted as far as the original window was opened, so when I scroll down, the sides are only partially inverted.
I doubt that this is a deliberate change of the site, since I saw this change in a lot of sites at the same time, and when darkreader is turned off there is nothing "weird".

**Screenshots:**

Wikipedia as it should look:
![image](https://user-images.githubusercontent.com/34215440/80018382-9a9fee00-84de-11ea-8eee-724161b5bb8f.png)

After scrolling down:
![image](https://user-images.githubusercontent.com/34215440/80018462-b7d4bc80-84de-11ea-9e57-e80a26ec8b96.png)
(notice the left hand side of the screen is now off-white instead of black and the text is barely legible)

Quora as it should look:
![image](https://user-images.githubusercontent.com/34215440/80018574-dc309900-84de-11ea-9c41-863c5a6d2c6f.png)

Quora after scrolling down:
![image](https://user-images.githubusercontent.com/34215440/80018630-f5394a00-84de-11ea-87df-353e41e7074d.png)

The height of the unrendered area is determined by the window:
![image](https://user-images.githubusercontent.com/34215440/80018772-39c4e580-84df-11ea-92bd-f4866ca11dc0.png)

**System Information:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 81.0.4044.113 (Official Build) (64-bit)

Thanks in advance!

**Comment by Myshor** [comment]
Some questions:
1. What type of filter you use?
2. I see many addons... It may be related to one of them. Can you share what you use?

I could not reproduce this behavior on my Win10 and the same Chrome.

**Comment by Myshor** [comment]
I won't edit previous comment.
I managed to reproduce.
Happens when filter mode enabled and page opened.
Not possible to catch when switching to filter on already opened page.

**Comment by arealuser** [comment]
The bug doesn't seem to depend on add-ons:

![image](https://user-images.githubusercontent.com/34215440/80091852-7db0fc80-856a-11ea-95a1-abce084edf6c.png)


I am using Filter, Segoe UI, Text stroke (the default settings).

**Comment by Gusted** [comment]
open chrome://extension 
Which version of darkreader do you use? If 4.9.4, than this issue has already been fixed and the 4.9.5 version is now in review at the chrome webstore.

**Comment by Gusted** [comment]
Update has been widely pushed
