### ISSUE TITLE
[Broken Website] Visual Studio Code

### ISSUE THREAD

**Issue by Barugon** [darkreader/darkreader#2353]
**Website**
https://code.visualstudio.com/

**How to Reproduce**
Just navigate to the site.

**Expected behavior**
I expect something like this:

![expected](https://user-images.githubusercontent.com/16503728/80020583-22114100-848e-11ea-8af2-ebd77ff6e84b.png)

**Actual behavior**
This is what I get:

![actual](https://user-images.githubusercontent.com/16503728/80020655-3d7c4c00-848e-11ea-96c1-532fe3b113eb.png)

**System info:**
 - OS: Linux - Fedora 31
 - Browser: Firefox 75
 - Darkreader Version: 4.9.5

**Comment by Myshor** [comment]
Can be related to Linux version of Firefox.
I checked that page on Firefox 75 with Darkreader: 4.9.5 but in Windows 10 and this pic is displayed as dark.

**Comment by Barugon** [comment]
Now the image doesn't show up at all.

**Comment by Gusted** [comment]
Does it have any errors in console?

**Comment by Barugon** [comment]
![Screenshot from 2020-04-27 15-19-11](https://user-images.githubusercontent.com/16503728/80426419-81aa8a80-889a-11ea-957a-a5b5d718e76b.png)

**Comment by Gusted** [comment]
Could you check if you use 4.9.6 of darkreader.

**Comment by Barugon** [comment]
Yes, that's the version.

**Comment by Gusted** [comment]
> Yes, that's the version.

Than it's quite stressing me as this should trigger our CORS to load the blob from our background script, that doens't have any restrictions... And as me and myshor can't reproduce it.

**Comment by Gusted** [comment]
```
code.visualstudio.com

CSS
.home.linux .jumbotron .screenshot {
 background-image:url("/assets/home/home-screenshot-linux.png");
 padding-bottom:82.65802%
}
@media only screen and (min-width: 1200px) {
 .home.linux .jumbotron .screenshot {
  background-image:url("/assets/home/home-screenshot-linux-lg.png");
  padding-bottom:68%
 }

================================
```

Pasting this into the right format, in devtools does that solves the problem?

**Comment by Barugon** [comment]
Hmm... I set it to preview the new format and now it won't load the dev tools.

![Screenshot from 2020-04-27 15-29-14](https://user-images.githubusercontent.com/16503728/80427086-de5a7500-889b-11ea-99a2-60bcecb1e211.png)

**Comment by Gusted** [comment]
Ah yes.... 
![](https://i.imgur.com/3pKAx5k.png)
Unfortunate.....
[build-firefox.zip](https://github.com/darkreader/darkreader/files/4542288/build-firefox.zip) Latest build with latest commits. Use it temporary

**Comment by Barugon** [comment]
Where do I put it?

**Comment by Gusted** [comment]
about:addons -> Debug addons -> Install temporary addon

**Comment by Barugon** [comment]
`File /home/barugon/Downloads/build-firefox.zip does not contain a valid manifest`

**Comment by Barugon** [comment]
I got it to work by re-zipping the files without the build-firefox folder....

**Comment by Barugon** [comment]
> ```
> code.visualstudio.com
> 
> CSS
> .home.linux .jumbotron .screenshot {
>  background-image:url("/assets/home/home-screenshot-linux.png");
>  padding-bottom:82.65802%
> }
> @media only screen and (min-width: 1200px) {
>  .home.linux .jumbotron .screenshot {
>   background-image:url("/assets/home/home-screenshot-linux-lg.png");
>   padding-bottom:68%
>  }
> 
> ================================
> ```
> 
> Pasting this into the right format, in devtools does that solves the problem?

This works.

**Comment by Barugon** [comment]
We're back to this.

![actual](https://user-images.githubusercontent.com/16503728/80020655-3d7c4c00-848e-11ea-96c1-532fe3b113eb.png)

**Comment by Gusted** [comment]
Is this always?

**Comment by Barugon** [comment]
Yes. Version is 4.9.7.

**Comment by Gusted** [comment]
Could you try to remove the code.visualstudio.com section in devtools

**Comment by Barugon** [comment]
I still have the same issue where I can't access devtools.

**Comment by Gusted** [comment]
Older version?

**Comment by Barugon** [comment]
4.9.7

**Comment by Gusted** [comment]
Can you revert to an older version and remove the CSS

**Comment by Barugon** [comment]
> Can you revert to an older version

How?

**Comment by Barugon** [comment]
I deleted the .firefox folder, reinstalled dark reader and there's no section in devtools for code.visualstudio.com.

**Comment by Gusted** [comment]
Does the issue still persit?

**Comment by Barugon** [comment]
Yes.

**Comment by Gusted** [comment]
That's unfortunate still the same errors in consols?

**Comment by Barugon** [comment]
Doesn't look like it.

![Screenshot from 2020-04-28 13-43-40](https://user-images.githubusercontent.com/16503728/80535942-71f07c00-8956-11ea-8834-026eadc7481e.png)

**Comment by Gusted** [comment]
Welp seems like it's an Browser bug than.. I cannot get another logical reason..

**Comment by Barugon** [comment]
If I add this to devtools then it works:
```CSS
code.visualstudio.com

CSS
.home.linux .jumbotron .screenshot {
 background-image:url("/assets/home/home-screenshot-linux.png");
 padding-bottom:82.65802%
}
@media only screen and (min-width: 1200px) {
 .home.linux .jumbotron .screenshot {
  background-image:url("/assets/home/home-screenshot-linux-lg.png");
  padding-bottom:68%
 }

================================
```

**Comment by Gusted** [comment]
That code has been added and would be release with darkreader V5.
