### ISSUE TITLE
Filter + has been changed? I provide screenshots of the problem.

### ISSUE THREAD

**Issue by anoldmaninthesea** [darkreader/darkreader#2355]
**Describe the bug**
Today, my dark reader started having some issues with several pages, where previously pages appeared correctly black, now major sections appear white.
Also, if I leave a chrome tab, for example in youtube, inactive for 5 min, and then come back, all the page is white, instead of black.

**Screenshots**
![Dark Reader](https://user-images.githubusercontent.com/39698530/80025168-1c404d80-84d8-11ea-970c-2cfe85ef166e.png)

![Dark Reader 2](https://user-images.githubusercontent.com/39698530/80025352-6a555100-84d8-11ea-8973-72cc3ce1107f.png)

**Comment by Gusted** [comment]
Wait for new update this would fix this problem

**Comment by anoldmaninthesea** [comment]
I use Chrome, and Dark Reader 4.9.4.

**Comment by Gusted** [comment]
> I use Chrome, and Dark Reader 4.9.4.

Wait for update it can take up to 2 weeks before chrome accept the extension..... This bug has already been fixed in the newest version. If you want to I can make a compiled version with the fix.

**Comment by anoldmaninthesea** [comment]
I can wait for two weeks, I think. Thanks. After chrome accepts the extension, and I confirm it's been solved, I'll close the thread. Thanks.

**Comment by Gusted** [comment]
> I can wait for two weeks, I think. Thanks. After chrome accepts the extension, and I confirm it's been solved, I'll close the thread. Thanks.

Okay! That's fine to hear, if their are sites like https://wsj.com you mainly use I suggest to sideload the 4.9.5

**Comment by Gusted** [comment]
Update had been pushed5
