### ISSUE TITLE
[Broken Website]  Dev.to texts are unreadable.

### ISSUE THREAD

**Issue by gluons** [darkreader/darkreader#2356]
**Website**
https://dev.to/catalinmpit/colorize-your-console-log-11l6

**How to Reproduce**

Go to that **dev.to** link. And you will see black text

**Expected behavior**
Text of the article should be readable.

**Actual behavior**
Texts are unreadable.

**Screenshots**
![ภาพ](https://user-images.githubusercontent.com/4688092/80056082-8d6e1800-854d-11ea-8314-869a80999a74.png)

**System info:**
 - OS: Windows 10 Pro version 1909
 - Browser: Firefox Developer Edition 76.0b7
 - Darkreader Version: 4.9.5

**Additional context**
None

**Comment by gluons** [comment]
They use CSS variable. I'm not sure if it's related.

![ภาพ](https://user-images.githubusercontent.com/4688092/80056514-9ca19580-854e-11ea-9432-b207f6a79e3f.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/80056559-b93dcd80-854e-11ea-8a5a-c607a9c71fac.png)

**Comment by Myshor** [comment]
Made fixes comparing how it looks without DarkReader enabled.
The result will be:
![image](https://user-images.githubusercontent.com/56877029/80084112-bcd55280-8556-11ea-9ac9-ebfe92aab148.png)
