### ISSUE TITLE
Edge extension doesn't list extension store as protected

### ISSUE THREAD

**Issue by BananaManCJ** [darkreader/darkreader#2361]
In the Edge version of the extension, https://microsoftedge.microsoft.com/addons is not listed as "protected by browser." Usually it would say "This page is protected by browser."

System Information:
 - OS: Windows 10
 - Browser: Edge Chromium
 - Version: 80.0.361.69

You should also investigate if Edge protects https://chrome.google.com/webstore so it could possibly be themed.

**Comment by Gusted** [comment]
Chromium so most likely webstore of google has also been flagged as protected page
