### ISSUE TITLE
[Feature Request] Configure contrast/brightness per website

### ISSUE THREAD

**Issue by prmichaelsen** [darkreader/darkreader#2363]
**Is your feature request related to a problem? Please describe.**
Some website's contrast/brightness settings render page unreadable. I used to be able to change this on a per-website basis but it seems in a recent update that feature was removed.

**Describe the solution you'd like**
I'd like to be able to change brightness and contrast on a website per website basis as in the old UI.

**Additional context**

**Old**: feature described exists
![old](https://s3.us-east-2.amazonaws.com/com.parm.public/Screen+Shot+2020-04-23+at+4.45.42+PM.png)

**New**: feature described removed
![new](https://s3.us-east-2.amazonaws.com/com.parm.public/Screen+Shot+2020-04-23+at+4.44.47+PM.png)

**Comment by prmichaelsen** [comment]
I should note that I did indeed find this feature, although I would argue that the UI is not intuitive. I only found it by chance, clicking random UI elements until I made some progress towards my objective.

![img](https://s3.us-east-2.amazonaws.com/com.parm.public/Screen+Recording+2020-04-23+at+4.56.08+PM.mov)

**Comment by Gusted** [comment]
This is a preview of the new UI, we are working on making this better. I don't know exactly if 4.9.6 have the switch but if you open Devtools you can switch to the old UI if you want to.

**Comment by alexanderby** [comment]
@prmichaelsen Did you enable the new UI in Dev Tools, or did it activate itself?

**Comment by alexanderby** [comment]
It is planned to add more Presets there, so you will be able to assign multiple websites for one preset.

**Comment by prmichaelsen** [comment]
It activated itself.

**Comment by prmichaelsen** [comment]
Thanks again for working on this tool guys. I couldn’t live without it. Let me know if you need any more info from me.
