### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by mkrier** [darkreader/darkreader#2364]
**Website**
https://www.dailymail.co.uk/femail/article-8240717/Mens-rights-activist-mother-murdered-abusive-husband-thinks-feminism-problem.html?fbclid=IwAR3iQztP9_hF2Jy-iOBbfbn2kOt7hajsFyP-EAJNR3h2zRgLHK6aRhiHox4

**How to Reproduce**
https://www.dailymail.co.uk/femail/article-8240717/Mens-rights-activist-mother-murdered-abusive-husband-thinks-feminism-problem.html?fbclid=IwAR3iQztP9_hF2Jy-iOBbfbn2kOt7hajsFyP-EAJNR3h2zRgLHK6aRhiHox4

**Expected behavior**
It's not inverting the background.  This is only happening as of today. 

**Actual behavior**
I just did.

**Screenshots**
If you need them let me know. But if you use dark reader at all then all you have to do is go look at it.  Also this is using the standard filter. I know there's others and you added one, but why change the standard filter?  

**System info:**
Linux, Ubuntu
Chrome.
Where do I find the DR version? It's whatever you just did today, the 04/23/20

**Additional context**
This is happening on tons of sited today.

**Comment by Gusted** [comment]
chrome://extension
chrome://version

I need darkreader version. 
I need Chromium version.
If you are using Filter than this issue has already been fixed in the next update.

**Comment by Gusted** [comment]
@mkrier

**Comment by mkrier** [comment]
Ok , it's Chrome (not Chromium), Version 81.0.4044.113 (Official Build) (64-bit)

As for hte DR version, like I said above, I don't know how to get it, I asked you.

But it looks like this morning the problem is fixed thanks!

**Comment by mkrier** [comment]
Oh it looks like you meant "chrome://extensions/". It's 4.9.5.
