### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by mkrier** [darkreader/darkreader#2365]
**Website**
https://www.theatlantic.com/magazine/archive/2020/06/underlying-conditions/610261/?fbclid=IwAR1Aze3_LGPahTgEJn6e_UW7wR4w3n6Nar8AlZjZ043Ms8groLIi5rPJybs

**How to Reproduce**
https://www.theatlantic.com/magazine/archive/2020/06/underlying-conditions/610261/?fbclid=IwAR1Aze3_LGPahTgEJn6e_UW7wR4w3n6Nar8AlZjZ043Ms8groLIi5rPJybs

**Expected behavior**
It's not inverting the background.  This is only happening as of today. 

**Actual behavior**
I just did.

**Screenshots**
If you need them let me know. But if you use dark reader at all then all you have to do is go look at it.  Also this is using the standard filter. I know there's others and you added one, but why change the standard filter?  

**System info:**
Linux, Ubuntu
Chrome.
Where do I find the DR version? It's whatever you just did today, the 04/23/20

**Additional context**
This is happening on tons of sited today. I'm only just providing two, but I could go on and on.

**Comment by Myshor** [comment]
You need to turn on developer mode on chrome://extensions/ to see extension version.
![image](https://user-images.githubusercontent.com/56877029/80258438-877a5300-8683-11ea-889b-68c5c4549567.png)

However I can not reproduce in Windows 10, DR 4.9.5, Dynamic.

What type of filter do you use?

**Comment by mkrier** [comment]
It's the same question as #2364 so you can close the ticket.   (btw I said I'm using the standard filter in the bug description. )
