### ISSUE TITLE
gmail issue

### ISSUE THREAD

**Issue by UchihaSR** [darkreader/darkreader#2366]
**Website**
gmail 

**How to Reproduce**
An example for this is
> 1. if you have Gmail account, login to gmail
> 2. open any mail 
> 3. and the options like delete archive back to inbox are in dark.

**Expected behavior**

the options like delete, archive should be visible when you open the mail 

**Actual behavior**
the options like delete, archive are not  visible when you open the mail 

**Screenshots**
![gmail_darkreader_issue](https://user-images.githubusercontent.com/52357560/80224134-ed0c1680-8666-11ea-8b93-9bc0a039b765.png)

**System info:**
 - OS:  Linux
 - Browser : Firefox
 - Darkreader Version : na

**Additional context**

**Comment by Myshor** [comment]
Technical info: black PNGs stays instead as background image instead of white blob (to investigate more)

**Comment by Gusted** [comment]
4.9.7 will fix this issue.
