### ISSUE TITLE
[Broken Website] Soundcloud 

### ISSUE THREAD

**Issue by MurMa** [darkreader/darkreader#2368]
**Website**
https://soundcloud.com/discover

**How to Reproduce**
> 1. Go to https://soundcloud.com/discover
> 2. Play any song
> 3. The controls (play/pause, next song, etc.), which should be located at the bottom of the window, are not visible

**Expected behavior**
A few days it worked perfectly fine: 
- The control buttons were light grey

This is with Dark Reader deactivated (sorry for the bright image):
![Annotation 2020-04-24 200754](https://user-images.githubusercontent.com/30857765/80243424-83d8d300-8667-11ea-94e3-bfe905ce1e1f.png)

**Actual behavior**
I assume that soundcloud has updated their page. The control buttons are now not visible / have the same color as the background.
This is with Dark Reader activated with Dynamic styling:
![Annotation 2020-04-24 200633](https://user-images.githubusercontent.com/30857765/80243239-22b0ff80-8667-11ea-92c6-607aacea2297.png)

**System info:**
 - OS: Windows
 - Browser: Firefox 75.0
 - Darkreader Version 4.9.6

**Thanks**
Thanks for working on Dark Reader, I absolutely love it!

**Comment by Myshor** [comment]
Confirmed on Firefox... Still using 4.9.5 in Chrome so hard to say but propably browser bug.

**Comment by Gusted** [comment]
4.9.7 will fix this issue.
