### ISSUE TITLE
[BUG] Switching Back to New/Old Style of Dark Reader Fails 

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#2374]
I have firefox. I switched to old style of Dark Reader. Now I can't access the dev tools. How do I switch back to new style?

**Comment by alexanderby** [comment]
Hi, as a workaround, when the Dev Tools window pops up, press F12, open Console tab, type `location.href`, remove `ui/popup/` from the URL and open it in new tab or type `location.href = location.href.replace('ui/popup/', '')` and press Enter.

**Comment by Gusted** [comment]
#2378

**Comment by koolx** [comment]
Thanks man.

**Comment by koolx** [comment]
Thanks Alex. Your addon is my fav dude. Keep up the excellent work!!!!

- David
