### ISSUE TITLE
[question] How does "use systemcolors" work in chrome?

### ISSUE THREAD

**Issue by l0drex** [darkreader/darkreader#2377]
So I realized there is this settings to enable DarkReader using system settings. But how does it work?

In Firefox it seems like it reads the settings from `ui.SystemUsesDarkTheme`, but in chrome I couldn't find this. How does it work in chrome?

**Comment by Gusted** [comment]
Chrome & Firefox use both the same way to detect system settings.

For the detection whe use [this class](https://github.com/darkreader/darkreader/blob/master/src/utils/media-query.ts)
