### ISSUE TITLE
[Broken Website] AskUbuntu Accepted Answers look the same as Unaccepted to OP

### ISSUE THREAD

**Issue by UndarkAido** [darkreader/darkreader#2384]
**Website**
https://askubuntu.com/

**How to Reproduce**
An example for this is
> 1. Go to Ask Ubuntu
> 2. Click on "Ask a Question"
> 3. Create and submit a question
> 4. Create and submit an answer to said question
> 5. Accept said answer with the check mark on the left

**Expected behavior**
The check on the accepted answer should turn green

**Actual behavior**
The check on the accepted answer stays gray

**Screenshots**
Unaccepted:
![Unaccepted](https://user-images.githubusercontent.com/7421794/80312551-5c8b1e80-87ab-11ea-8415-93d15b3ba1db.png)
Accepted:
![Accepted](https://user-images.githubusercontent.com/7421794/80312562-6745b380-87ab-11ea-9bd0-7a1988c1c620.png)

**System info:**
 - OS: Windows 10
 - Browser Chrome
 - Darkreader Version 4.9.5

**Comment by Gusted** [comment]
https://i.imgur.com/yPn7dgc.png For a normal user it is green.

**Comment by Gusted** [comment]
Do you have changed your grayscale?

**Comment by UndarkAido** [comment]
Grayscale is set to 'off'

**Comment by Gusted** [comment]
Should be fixed by https://github.com/darkreader/darkreader/pull/2196
