### ISSUE TITLE
Fingerprinting concerns with usage of darkreader

### ISSUE THREAD

**Issue by Kreyren** [darkreader/darkreader#2385]
Browser fingerprinting is the collection of large amount of diverse and stable information from web browsers is possible thanks for most part to client-side scripting languages, which have been introduced in the late '90s. [wiki](https://en.wikipedia.org/wiki/Device_fingerprint#Browser_fingerprint)

---

The issue is about being able to blend into tor user crowd even with usage of this extension assuming Tor IP visible to the website.

I was recently doing research in using [Tor Browser Bundle (TBB)](https://www.torproject.org/download/) which is privacy oriented fork of Mozilla's Firefox where it is highly discouraged to use extensions (https://support.torproject.org/faq/#tbb-14) for browser fingerprinting concerns.

Is there something darkreader upstream can do to make usage of this extension saner to use on privacy oriented systems using TBB and other browsers in general?

See fingerprinting tests:
- https://fpcentral.tbb.torproject.org/
- https://panopticlick.eff.org/
- https://www.amiunique.org/
- https://browserleaks.com/
- https://github.com/Valve/fingerprintjs / https://github.com/Valve/fingerprintjs2
- https://github.com/jonaslejon/tor-fingerprint (website 404)
- https://www.browserleaks.com/firefox
- https://github.com/ghostwords/chameleon (deprecated)

Resources:
- Resource from torproject (needs updating) https://2019.www.torproject.org/projects/torbrowser/design/
- Relevant research on fingerprinting http://hackerfactor.com/
- Article from torproject about fingerprinting https://blog.torproject.org/browser-fingerprinting-introduction-and-challenges-ahead
- Article from Mozilla (inaccurate) https://blog.mozilla.org/firefox/how-to-block-fingerprinting-with-firefox/
- Wiki from mozilla on fingerprinting safety https://wiki.mozilla.org/Security/Fingerprinting
- Article from whonix about fingerprinting https://www.whonix.org/wiki/Fingerprint
- Advanced Deanonymization Attacks https://www.whonix.org/wiki/Advanced_Attacks
- Tor Entry guards https://www.whonix.org/wiki/Tor_Entry_Guards
- Tor Browser Basics https://www.whonix.org/wiki/Tor_Browser
- The Origination and Evolution of Radio Traffic Analysis: The World War I Era https://www.nsa.gov/Portals/70/documents/news-features/declassified-documents/cryptologic-quarterly/trafficanalysis.pdf

Relevants:
- Organization dedicated to privacy https://www.whonix.org/
- FWIW TBB is also using letterboxing (https://support.torproject.org/tbb/maximized-torbrowser-window/) to help (is not very efficient on my system) with fingerprinting based on windows size.
- SecBrowser https://www.whonix.org/wiki/SecBrowser

---

Also relevant: TBB is identifiable via torproject's released IP addresses so the idea is currently to use TBB without any changes to blend with other Tor users.

**Comment by Gusted** [comment]
Concerns you say?
Well, first making darkreader undetectable would be very hard overriding protypes functions of javascript and potentially breaking it. 
As of the fetch() functions we use should be so far I know from TOR handled by the browser and giving it's IP etc.
The only thing that they can fingerprint you on is using darkreader by a simple `document.querySelector('style.darkreader.darkreader--fallback') != null { darkreaderuser = true}` making it undetectable would be for many users unnecessary.
Let's be honest fingerprint that your a darkreader user wouldn't be a huge deal, I know I know fingerprinting that and on another site having kinda the same results and the darkreader fingerprint could be the final decision.

Hiding it? Well unless you want to have javascript a good make-over and making it not fast as inteded by the browser, the browser could do this 100% better by masking on the site what a content script of an extension does. However if you have a good article or documentation from TBB or something else with some good tips about hiding it in general etc, I'm intrested. Privacy first.

**Comment by Kreyren** [comment]
> As of the fetch() functions we use should be so far I know from TOR handled by the browser and giving it's IP etc.

True tor has list of IPs public and provides the IP to the web that it is using. So for website it is easy to fingerprint tor users. The idea here is to blend with other tor users.

> The only thing that they can fingerprint you on is using darkreader by a simple `document.querySelector('style.darkreader.darkreader--fallback') != null { darkreaderuser = true}` making it undetectable would be for many users unnecessary.

I would say that any effort agains fingerprinting is a good thing. What do you propose in this scenario? Renaming the extension or? (would be interested in making user-patch)

> Let's be honest fingerprint that your a darkreader user wouldn't be a huge deal, I know I know fingerprinting that and on another site having kinda the same results and the darkreader fingerprint could be the final decision.

Afaik one element that makes you unique is enough for website to make a trackable fingerprint which sacrifices security.

> Hiding it? Well unless you want to have javascript a good make-over and making it not fast as inteded by the browser, the browser could do this 100% better by masking on the site what a content script of an extension does.

Researching..

> However if you have a good article or documentation from TBB or something else with some good tips about hiding it in general etc, I'm intrested. Privacy first.

Found https://blog.torproject.org/browser-fingerprinting-introduction-and-challenges-ahead, updated OP with more references

**Comment by Gusted** [comment]
We could at least try to request fetch with different user-agents.
As of the elements, giving random names would be make us jib as developer harder as we use that kind of certain elements a lot and caching the name would take up more memory especially with some sites know to have a lot of <style>

Like I said earlier, the best way to solve this problem if TBB created an RealDOM and a FakeDOM and everything that the site does only access the FakeDOM and thinks that's is the real DOM but in fact extension interact with the RealDOM and add styles etc that effect the FakeDOM without knowing(so far as it's possible)

**Comment by Kreyren** [comment]
> We could at least try to request fetch with different user-agents.
As of the elements, giving random names would be make us jib as developer harder as we use that kind of certain elements a lot and caching the name would take up more memory especially with some sites know to have a lot of <style>

Note that following:
> EDIT: Possibly doing something to hide the tor IP from the website and randomizing the user-agent and elements alike might help, but is generally considered as bad idea due the lack of known practices used to fingerprinting (thus provided the one that we know about atm)

is a theory i didn't do the required research to know if this is a viable option.

In general from what i understand TBB tries to use the most common values across systems.

> Like I said earlier, the best way to solve this problem if TBB create

noted, i try to propose it to tor ppl
