### ISSUE TITLE
[Broken Website] Standard background color

### ISSUE THREAD

**Issue by hiukky** [darkreader/darkreader#2386]
**Expected behavior**
Full standard background color application on pages.

**Actual behavior**
At the moment I'm creating some custom themas for my environment and I realized that my system backgroud color applies in the initial tab but not the loaded pages ... I tried to change the background color I inspected but it did not work ... which selector is responsible for this application? I don't know if it's a bug because it applies in one place and in others so my doubt at the moment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26740246/80314035-22c71180-87c5-11ea-8749-668cf7dcda21.png)

**System info:**
 - OS: Linux
 - Browser: Chrome
 - Darkreader Version:  81.0.4044.122 (Official Build) (64-bit)

**Additional context**

**Comment by Gusted** [comment]
Does this works when darkreader is disabled?

**Comment by hiukky** [comment]
Yeah! It works when it's disabled.

**Comment by Gusted** [comment]
Does it inject an <style> into style or ho does the injector works

**Comment by hiukky** [comment]
has how to set a default color in devtools? I tried to apply there but it didn't work

**Comment by Gusted** [comment]
I'm getting a bit clueless what your trying to achieve...

**Comment by hiukky** [comment]
Sorry if I was not clear .. the problem is as follows the background color defined in my system theme is injected in the new tab .. with the darkreader active or not .. I believe it is a problem with the theme .. I will try to take the time to try to fix it .. but for now i thought i could define a custom background color to be consistent with the color of the system theme .. i changed some styles by the darkreader devtools but when applying the changes they have no effect so the problem could be I am not using the extension the right way lol.

**Comment by Gusted** [comment]
> Sorry if I was not clear .. the problem is as follows the background color defined in my system theme is injected in the new tab .. with the darkreader active or not .. I believe it is a problem with the theme .. I will try to take the time to try to fix it .. but for now i thought i could define a custom background color to be consistent with the color of the system theme .. i changed some styles by the darkreader devtools but when applying the changes they have no effect so the problem could be I am not using the extension the right way lol.
> 
> There are a lot of options to control brightness, contrast and etc ... this works well .. I thought I could have something to define a global body color.

For editing styles I recommend Stylus than the darkreader dev tools

**Comment by Gusted** [comment]
> There are a lot of options to control brightness, contrast and etc ... this works well .. I thought I could have something to define a global body color.

Hi @hiukky!

Please [read this carefully](https://darkreader.org/blog/v4-9/).

Regards,
Gusted
