### ISSUE TITLE
[Broken website] Soundcloud

### ISSUE THREAD

**Issue by HJAZ93** [darkreader/darkreader#2388]
Soundcloud media buttons are not changing color, so are indistinguishable from mediabar in dark mode.

![image](https://user-images.githubusercontent.com/51090968/80319095-d99baf80-880e-11ea-8ad2-8b60cac17780.png)

**Comment by Myshor** [comment]
Clone of #2368 
Closing this one. ;)

**Comment by HJAZ93** [comment]
My bad!
