### ISSUE TITLE
[Broken Website] Facebook icons and reaction emoticons

### ISSUE THREAD

**Issue by Storm-Engineer** [darkreader/darkreader#2392]
**Website**
http://facebook.com

**How to Reproduce**
> 1. Go to facebook
> 2. Enable Dark mode

**Expected behavior**
Facebook used to work properly with every element readable until maybe a week ago.

**Actual behavior**
Icons at the right side of the header bar (Friend requests, Messages, Notifications, Help, down arrow) as well as the emoticons from Likes/Reactions under posts/comments are now missing/invisible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9753164/80322379-fa6eff80-8824-11ea-9f4c-4d7752ee9f8b.png)
![image](https://user-images.githubusercontent.com/9753164/80322393-09ee4880-8825-11ea-8ddf-9cb9c55d190d.png)

![image](https://user-images.githubusercontent.com/9753164/80322415-2ab69e00-8825-11ea-989b-ee5c056556ce.png)
![image](https://user-images.githubusercontent.com/9753164/80322420-373af680-8825-11ea-95d3-a47082661244.png)

**System info:**
 - OS: Arch Linux + Plasma 5
 - Browser Firefox 75
 - Darkreader Version 4.9.6

**Comment by pingje** [comment]
I can recreate this issue on Windows 10 with Firefox 75, Dark Reader 4.9.6

**Comment by Myshor** [comment]
I think there was some Firefox issue causing that and it will be fixed in 4.9.7.

@Gusted Can you confirm?

**Comment by Gusted** [comment]
Ah, CSP error for facebook yes Alexander has created an patch and send it to review so It's waiting for Mozilla to accept the review of the extension.

**Comment by pingje** [comment]
Thanks, look like 4.9.7 resolved the issue for me.

**Comment by Gusted** [comment]
@Storm-Engineer Can you check again if 4.9.7 resolved the issue for you as well?

**Comment by Storm-Engineer** [comment]
Sorry, I kinda forgot to check this ticket. Yes, it is solved. Thank you!

**Comment by Gusted** [comment]
> Sorry, I kinda forgot to check this ticket. Yes, it is solved. Thank you!

That's good to hear :D have a nice day
