### ISSUE TITLE
[Broken Website] Dev.to text follows dark colorization 

### ISSUE THREAD

**Issue by DimitrisKapoulas** [darkreader/darkreader#2393]
**Website**
https://dev.to/

**How to Reproduce**
> 1. Go to dev.to
> 2. Pick any article in the news feed 
> 3. See that text isn't in a readable status

**Expected behavior**
In the past, using the Dark Reader addon, created a contrast of a kinda greenish text to the dark background.

**Actual behavior**
Currently, the behavior of the up-mentioned website, is to blend the text also in a dark colorized way. Only hyperlinks still seem to work fine.

**Screenshots**
![Screenshot from 2020-04-27 09-22-23](https://user-images.githubusercontent.com/35511933/80340170-d33a2180-8868-11ea-8d7c-db27ce1c030a.png)

**System info:**
 - OS: Ubuntu 18.04
 - Browser Firefox 75
 - Darkreader Version 4.9.6

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/2357
