### ISSUE TITLE
[Feature Request] Default Background on Server / browser Error pages

### ISSUE THREAD

**Issue by ktpx** [darkreader/darkreader#2396]
First off, thanks for a great addon.  It has made my life on the web bearable, as I have extreme light sensitivity.

I would like however, to know if its possible to get darkreader to override the extremely white error pages, which seems to be default in web browsers/servers.  Those are quite painful when they suddenly appear.  

Thanks for listening,

**Comment by Gusted** [comment]
Hi their!

As an extension we have 0 control over those pages, however I think installing an dark theme would solve this or have an browser that support dark style in settings for that kind of pages.

**Comment by ktpx** [comment]
Gotcha.   Using vivaldi, but it surprisingly has no setting for that, even with dark mode.

Thanks,

**Comment by Gusted** [comment]
I'm using Brave it's supported after chaning an setting

**Comment by Gusted** [comment]
![](https://i.imgur.com/LjuU8Wd.png)

**Comment by ktpx** [comment]
Exactly what im looking for, but hoping this can be achieved in Vivaldi (do not want to switch browser atm).  What was the setting called, in Brave?

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/80477186-cf330000-894b-11ea-937f-cb4cdb08cc79.png)

**Comment by ktpx** [comment]
I guess vivaldi just forgot about that background, a got dark checked everywhere possible :/

**Comment by Gusted** [comment]
https://vivaldi.com/bugreport/ Goodluck filling out I think 😅

**Comment by ktpx** [comment]
heh, thanks.  I see its already reported for windows, but not linux, so indeed did report it.
