### ISSUE TITLE
[BUG] Facebook Messenger - videos not showing media keys

### ISSUE THREAD

**Issue by aha999** [darkreader/darkreader#2398]
**Describe the bug**
On Facebook's [Messenger website](https://www.messenger.com/), media keys disappear from videos when dark mode/dark reader is turned on.

**To Reproduce**
> Go to https://www.messenger.com/
> Click on video with darkreader turned on
> Media keys disappear (play, volume etc.)
> Turn off dark reader - buttons reappear

**Expected behavior**
Media buttons on the video should be visible when dark reader is turned on

**Screenshots**
![slika](https://user-images.githubusercontent.com/50620416/80372344-b2d38c80-8893-11ea-983d-42655da18d6d.png)
![slika](https://user-images.githubusercontent.com/50620416/80372451-d7c7ff80-8893-11ea-95d2-706d92de36d5.png)

**System Information:**
 - OS: Windows 10
 - Browser: Mozilla Firefox 
 - Version: 75.0

**Additional context**
I personally think facebook could be preventing mods like darkreader from working properly.  All websites work perfectly with it, but facebook starts lagging with everything you do and elements disappear from screen etc.

**Comment by Myshor** [comment]
I tried messenger in Firefox... and I could not reproduce it. The buttons flickers after enabling Darkreader but stays there even if movie is played.
