### ISSUE TITLE
[BUG]Does not work with 3rd Party Input Color Pickers

### ISSUE THREAD

**Issue by gooeyideas** [darkreader/darkreader#2399]
**Describe the bug**
We use Spectrum.js https://bgrins.github.io/spectrum/ in our project and we also support Darkreader for our darkmode. Darkreader changes the colors displayed in the picker and I cannot think of a way to prevent this from happening using the overrides Darkreader supports

**To Reproduce**
> Go to https://bgrins.github.io/spectrum/
> Enable Darkreader Dark Mode
> Click on one if the example pickers

**Expected behavior**
 The colors should not be modified by darkreader

**Screenshots**
![image](https://user-images.githubusercontent.com/6644447/80398878-f4593d00-887d-11ea-8a19-9a4e279b73f3.png)

![image](https://user-images.githubusercontent.com/6644447/80398852-e7d4e480-887d-11ea-949a-023134d3dff3.png)

**Additional context**
> Adding a `IGNORE` section for dynamic-theme-fixes could work

**Comment by gooeyideas** [comment]
Note that the swatches shown can be configured and are dynamic so hardcoded overrides for each default pallet color will not work. Darkreader needs some sort of dynamic override...

**Comment by Gusted** [comment]
For darkreader v5 we have introduced a new Section

IGNORE INLINE STYLE

That ignore dynamic styles. You can build darkreader yourself and try it yourself out an patch for it.

**Comment by Gusted** [comment]
^ wikipedia.org already use an IGNORE INLINE STYLE for references

**Comment by gooeyideas** [comment]
Awesome! Thanks for the quick response. Do you know when v30 might be made available via npm as a beta version?

**Comment by Gusted** [comment]
> Awesome! Thanks for the quick response. Do you know when v30 might be made available via npm as a beta version?

We don't use BETA, v5 will Next month maybe released else over 2 months we still need a lot to do.

**Comment by Gusted** [comment]
And the latest update of darkreader contains the new section :)
