### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mvrck19** [darkreader/darkreader#2400]
Every time I turn Dark Reader on it changes my theme on Firefox to a light theme.

Screenshots
-My theme
![εικόνα](https://user-images.githubusercontent.com/45789298/80421293-ebe81d00-88e4-11ea-8b71-83780d11163c.png)
-Theme after I turn Dark Reader on
![εικόνα](https://user-images.githubusercontent.com/45789298/80421417-1fc34280-88e5-11ea-9dff-6c8553874e75.png)
-Theme after I turn Dark Reader off
![εικόνα](https://user-images.githubusercontent.com/45789298/80421479-39648a00-88e5-11ea-83f1-e8bbf876e567.png)

System Information:
 - OS: Windows 10
 - Browser: Firefox
 - Version: 75.0 (64-bit)

**Comment by Gusted** [comment]
Is this the same behaviour for about:blank ?

**Comment by Gusted** [comment]
Is their BTW any way to download this theme and use it? @mvrck19

**Comment by mvrck19** [comment]
> 
> 
> Is this the same behaviour for about:blank ?

No it doesn't seem to be.
about:blank shows my default theme

> 
> 
> Is their BTW any way to download this theme and use it? @mvrck19

When I go to customization it doesn't show up as a new theme, it shows that I'm using my selected theme. What I do is I select another theme from the list and then I select the one I want and it comes back.

**Comment by Gusted** [comment]
That's some weird behaviour I need to say.

**Comment by mvrck19** [comment]
Here you can see I have a GitHub tab, a Firefox starting tab and an about:blank tab, in that order. You can see that it changes my theme and the Firefox start page becomes white but about blank does not.
![github2](https://user-images.githubusercontent.com/45789298/80484744-e6c8b380-8960-11ea-96e7-5ad0d51988bf.gif)

**Comment by Gusted** [comment]
Ah 
https://github.com/darkreader/darkreader/blob/master/src/background/window-theme.ts#L61
Found the code what causes this. It was on purpose, for Darkreader V5 It will be an option you can turn off.

**Comment by Gusted** [comment]
You can go to the tab Settings and disable Custom browser theme to fix this.
