### ISSUE TITLE
[BUG] Cannot access dev tools after update to 4.9.6

### ISSUE THREAD

**Issue by wyphan** [darkreader/darkreader#2405]
**Describe the bug**
After (automatic) update to Dark Reader v4.9.6, I can no longer access the dev tools. Firefox gives a "File not found" error (please see screenshot).

**To Reproduce**
> Click on Dark Reader button on the toolbar
> Click on "Settings" and then "Dev tools"
> See error

**Expected behavior**
I can access the dev tools and edit my patches, so I can test them and commit it to GitHub

**Screenshots**
![Screenshot from 2020-04-27 18-45-43](https://user-images.githubusercontent.com/50928756/80428562-212a4600-88b8-11ea-9253-412c7524a7ab.png)

**System Information:**
 - OS: Ubuntu 18.04 LTS 64-bit (x86_64), Linux kernel 5.3.0-46
 - Browser: Firefox
 - Version: 75.0

**Additional context**
I wonder if this is because Dark Reader is now a "Recommended" extension on the Firefox Add-ons Website, such that the xpi file is now referred by name (`addon@darkreader.org.xpi`) instead of a long add-on ID string (as shown in the screenshot)?
(Congrats, btw!)

**Comment by Gusted** [comment]
> **Describe the bug**
> After (automatic) update to Dark Reader v4.9.6, I can no longer access the dev tools. Firefox gives a "File not found" error (please see screenshot).
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> > Click on Dark Reader button on the toolbar
> > Click on "Settings" and then "Dev tools"
> > See error
> 
> **Expected behavior**
> I can access the dev tools and edit my patches, so I can test them and commit it to GitHub
> 
> **Screenshots**
> ![Screenshot from 2020-04-27 18-45-43](https://user-images.githubusercontent.com/50928756/80428562-212a4600-88b8-11ea-9253-412c7524a7ab.png)
> 
> **System Information:**
> 
> * OS: Ubuntu 18.04 LTS 64-bit (x86_64), Linux kernel 5.3.0-46
> * Browser: Firefox
> * Version: 75.0
> 
> **Additional context**
> I wonder if this is because Dark Reader is now a "Recommended" extension on the Firefox Add-ons Website, such that the xpi file is now referred by name (`addon@darkreader.org.xpi`) instead of a long add-on ID string (as shown in the screenshot)?
> (Congrats, btw!)

Nope we forgot to make it Firefox compatible.....

**Comment by Gusted** [comment]
Darkreader v5 would have this patch as 4.9.7 was a little bit too early to have this patch :(

**Comment by yurikus** [comment]
Is there a workaround for this?

**Comment by alexanderby** [comment]
@yurikus Press F12, type `location.href` in Console. Copy the URL, remove `ui/popup/` and paste in new tab.

**Comment by alexanderby** [comment]
Should be fixed now.
