### ISSUE TITLE
Respect existing theme 

### ISSUE THREAD

**Issue by ZiluTian** [darkreader/darkreader#2408]
**Is your feature request related to a problem? Please describe.**
Enabling dark reader overwrites existing browser theme

**Describe the solution you'd like**
Include an option to preserve the current theme and only invert the web pages

**Additional context**
Observed on Firefox

**Comment by Gusted** [comment]
Example theme? As for some theme's this only is being affected.

**Comment by ZiluTian** [comment]
Hello,

Thanks for the response!

I am referring to theme “Energy line”. Here is what it looks:


When dark reader is on, it looks like (light mode):


I would like the theme to stay the same.


Regards,
Zilu

**Comment by Gusted** [comment]
More tab -> ![](https://i.imgur.com/1aExoqT.png)

**Comment by ZiluTian** [comment]
Hello,

I tried but it didn’t work. “Default” reset the theme back to the default of Firefox, not any existing theme installed through extension.


Regards,
Zilu

**Comment by Gusted** [comment]
You would need to reinstall the theme.... To get it work again, seems like a Bug would investigate it.

**Comment by ZiluTian** [comment]
Hello,

Thanks! It works now. Thanks for your help!


Regards,
Zilu
