### ISSUE TITLE
[BUG] [EDGE] Dark Reader plugin turned off by Edge for suspicious malware

### ISSUE THREAD

**Issue by sugobudo** [darkreader/darkreader#2415]
In Microsof Edge, Dark Reader is automatically turned off and I can't turn it on againg for suspicious malware.
OS Windows 10 1903 (build SO 18362.418)
Edge Version 81.0.416.64 (Offical Build) (64 bit)

![image](https://user-images.githubusercontent.com/64518629/80565755-9483a300-89f1-11ea-8339-6bfcbea2d974.png)

**Comment by Gusted** [comment]
Congrats you installed the wrong extension
https://github.com/darkreader/darkreader/issues/2293

**Comment by sugobudo** [comment]
I downloaded the only extension that the Microsoft Store had!

**Comment by Gusted** [comment]
https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc 
https://darkreader.org/ <- click on edge
