### ISSUE TITLE
Force inverting about:home

### ISSUE THREAD

**Issue by soum91** [darkreader/darkreader#2417]
As far as I know Dark Reader has no access to about:home but some how it still force inverting about:home. I am using NoSquint to turn the home in black which only works when Dark Reader is turned off. When Dark Reader is turned on, it force inverts the about:home. I don't know how is this happening!

Here are the screenshots

With Dark Reader on
<img width="1440" alt="Screen Shot 2020-04-29 at 2 57 12 PM" src="https://user-images.githubusercontent.com/3830681/80578788-d715a180-8a2a-11ea-8dac-e7c8ef6fc2d1.png">

Without Dark Reader
<img width="1440" alt="Screen Shot 2020-04-29 at 2 57 35 PM" src="https://user-images.githubusercontent.com/3830681/80578722-c1a07780-8a2a-11ea-82fb-cad5291d6c86.png">

**Comment by Gusted** [comment]
More -> browser theme -> custom

**Comment by soum91** [comment]
> More -> browser theme -> custom
> Than reinstall the theme....

Thanks for the hint @Gusted. Well, settings are different on macOS so I couldn't reinstall theme. Also I only have default themes so that's probably the reason those can't be reinstalled. But what did the trick was to change theme from Dark to Default theme.

**Comment by soum91** [comment]
Apparently the my own solution is not permanently fixing it. And sometime even re-selecting the default theme doesn't fix unless you change it to new theme and then back to default. Also @Gusted's solution doesn't work on Firefox macOS since there is no option to reinstall default themes. Someone needs to look into this issue.

**Comment by Gusted** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415267 They are looking into this for a veryy long time

**Comment by Gusted** [comment]
> Apparently the my own solution is not permanently fixing it. And sometime even re-selecting the default theme doesn't fix unless you change it to new theme and then back to default. Also @Gusted's solution doesn't work on Firefox macOS since there is no option to reinstall default themes. Someone needs to look into this issue.

You can simply go to about:addons and than select themes from the left sidebar menu and click on theme you want. That's called reinstall :)

**Comment by Gusted** [comment]
No response guess it's resolved.
