### ISSUE TITLE
[Broken Website] RunKit code box broken

### ISSUE THREAD

**Issue by metehus** [darkreader/darkreader#2420]
**Website**
Any page from RunKit for testing npm modules, like [this one](https://npm.runkit.com/uuid)

**How to Reproduce**
An example for this is
> 1. Make sure to have Dark Reade enabled
> 2. Go to the website with npm testing, [like this one](https://npm.runkit.com/uuid)
> 3. The code embed will disappear

**Expected behavior**
This code bar for testing should be shown
![image](https://user-images.githubusercontent.com/22124518/80645566-b442b780-8a41-11ea-9113-2f0f9177ba26.png)

**Actual behavior**
The code box is not shown on the page
![image](https://user-images.githubusercontent.com/22124518/80645604-c3296a00-8a41-11ea-951c-657126876591.png)

**System info:**
 - OS: Windows 10 1909 (build 18363.778)
 - Browser: Chrome 81
 - Darkreader Version 4.9.5

**Additional context**
If you go to the page with darkreader enabled, the box wont show, but if you go to the same page with darkreader disabled, and when it loads, enable again, the box will continue there with dark mode

**Comment by Gusted** [comment]
No errors from our side and can't fix it.

**Comment by Gusted** [comment]
The scripts that loads the iframe etc seems like does nothing when something has been added, like from darkreader sides some <script>

**Comment by metehus** [comment]
Oh, ok then. Thanks.

**Comment by Revadike** [comment]
Not sure why it needs closing when the issue is unresolved.

**Comment by Gusted** [comment]
> No errors from our side and can't fix it.

Because of this.

**Comment by SpineEyE** [comment]
Are you kidding me? You found the reason and **can** fix this by not inserting any `script`s? And you just decide to break the website? Your addon makes the website completely useless, I don't need darkmode when I cannot use the website. Can you please disable Darkreader for Runkit or show a warning or don't insert any scripts? There is no indication to the user that your addon breaks this website.

**Comment by Gusted** [comment]
> Are you kidding me? You found the reason and **can** fix this by not inserting any `script`s? And you just decide to break the website? Your addon makes the website completely useless, I don't need darkmode when I cannot use the website. Can you please disable Darkreader for Runkit or show a warning or don't insert any scripts? There is no indication to the user that your addon breaks this website.

I'm sorry, but that's not correct. I didn't found the reason and have revisited this site a few times and still cannot come up why it's broken. There are not errors/indications of why this happens, the code of runkit is at "fault" here and they are the only ones who can fix this.
