### ISSUE TITLE
What about DarkReader for Thunderbird?

### ISSUE THREAD

**Issue by i-am-ecc** [darkreader/darkreader#2422]
I've been using DarkReader on Firefox and it helped me a lot to browse in a much more comfortable way. So, what about a Thunderbird extension, so it could be possible to render e-mail messages dark as well?

**Comment by Gusted** [comment]
No intention to port to external applications as that gives more work more bugs etc etc.

**Comment by Myshor** [comment]
You can set "dark" emails in Thunderbird by yourself without DarkReader.
Check => https://support.mozilla.org/en-US/questions/1271598

I was able to set something like this:
![image](https://user-images.githubusercontent.com/56877029/80700916-d1799380-8ade-11ea-8c89-f3445f095c8d.png)
