### ISSUE TITLE
[Broken Website] Facebook profiles images extremely dark in Dynamic,Filter+ defaults

### ISSUE THREAD

**Issue by elig0n** [darkreader/darkreader#2424]
**Website** : https://www.facebook.com/

**Actual behavior** & **How to Reproduce**:
Brightness, contrast, sepia and grayscale are "off" (medium balanced)
Text stroke off.
Mode is Dynamic - facebook profile pages top person picture (the circle) is very dark.
In Filter+ it is completely dark. In others it is normal.

[Screenshot](https://ibb.co/VvktYGQ)

**Expected behavior** : Balanced settings should show brighter picture.

**System info:**
 - OS: Windows 10
 - Browser: Chrome
 - Darkreader Version: 4.9.5

**Comment by Myshor** [comment]
Dyamic filtering fix for new FB design is merged today and will be included in next release. #2395 
For Filter+ what I can say. Facebook developers did many tricks related to new/light mode.

For now I recommend disabling filtering on facebook and use native dark mode if you want to use new design. Then wait for 4.9.8 release. 😉

**Comment by Gusted** [comment]
PR has been merges
