### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by ZiluTian** [darkreader/darkreader#2427]
**Website**
Give the link to the website
www.coursera.org

**How to Reproduce**
An example for this is
> 1. Go to x site
> 2. Hover over login button 
> 3. The login window is stretched, and the field for specifying password is invisible (unreachable) from the screen. Can't even scroll down the page.  

**Expected behavior**
The login window centers at the screen with all fields visible 

**Actual behavior**
The login window is stretched and shifted down significantly, hiding the password field. The entire screen is also non-scrollable, which renders the password enter unaccessible. 

**Screenshots**
Expected behaviour: (with dark reader off) 
![Screenshot 2020-04-30 at 14 40 37](https://user-images.githubusercontent.com/28329737/80711443-a5ffa480-8af0-11ea-9cdb-f224158ddf74.png)

Actual behaviour: 
![Screenshot 2020-04-30 at 14 40 20](https://user-images.githubusercontent.com/28329737/80711486-b57eed80-8af0-11ea-8eb5-8262ff47117b.png)

**System info:**
 - OS: MacOS
 - Browser: Chrome
 - Darkreader Version: latest

**Additional context**

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/80745052-f6422b00-8b1f-11ea-8832-62478ec52752.png)
Please check if darkreader is really the problem.

**Comment by ZiluTian** [comment]
Hello,

Thanks for the response!

I did check, as the screenshots I attached were obtained with Dark Reader enabled and disabled. I am using Firefox on MacOS Catalina 10.15. The problem remains, for both dark and light mode (light mode was the one attached before, and the dark mode is shown here)



Regards,
Zilu

**Comment by Gusted** [comment]
Can't reproduce it even on light mode

**Comment by Gusted** [comment]
Hi @ZiluTian!

It seems like you were on Filter(+) mode. Unfortunate this is common practice in combination with Firefox and filter mode. Please use static or dynamic for such sites!

Regards,
Gusted
