### ISSUE TITLE
[Feature Request] Add preferred fallback fonts

### ISSUE THREAD

**Issue by wmertens** [darkreader/darkreader#2428]
This is maybe a sad workaround, but on Linux, Chrome doesn't use a color emoji font if it's installed. I have Noto Color Emoji, and if I go to a website with emoji, and there's no font from the website, it will use the Chrome fallback which is a black-and-white version of the Hangouts emojis. 

If I edit the style to have `Noto Color Emoji` as the fallback, I get color emoji.

So, it would be cool if I could misuse DarkReader to inject favorite fonts :sweat_smile:

**Comment by Gusted** [comment]
Under more tab we have an font setting where you can type manually a font in...

**Comment by wmertens** [comment]
Yes but that overrides the font, instead of providing a fallback.
In the meantime, however, I found a solution for me: configure fontconfig to override fonts and provide the fallbacks. So I'll close this.
