### ISSUE TITLE
[BUG] NO INVERT doesn't applies

### ISSUE THREAD

**Issue by arbitrary-dev** [darkreader/darkreader#2435]
**Describe the bug**

1. Dark reader → Dev tools
2. Add following:
   ```
   NO INVERT
   img[role="presentation"]
   ```
3. Press "Apply"
4. Added lines disappear and no changes applied

**System Information:**
 - OS: Gentoo
 - Browser: Chromium
 - Version: 4.9.5

**Comment by Gusted** [comment]
Isn't made for dynamic theme
