### ISSUE TITLE
[BUG] "White flash" when opening the browser (or a new tab)

### ISSUE THREAD

**Issue by i-am-ecc** [darkreader/darkreader#2436]
I've been using Dark Reader on Firefox for a long time and, since then, I noticed something weird: every time I either launch the browser or open a new tab, the extension takes a while to apply the dark theme, giving a "white flash" of less than a second. It only happens with the home page, or when I open the tab with the home page, not if I open a bookmark on a new tab.

> Open Firefox (or create a new tab)

**Expected behavior**
Home page should be dark from start.

**Actual behavior**
Home page goes dark after about 0.5 seconds, with a noticeable white screen before that.

**System Information:**
 - OS: Ubuntu 20.04 LTS amd64
 - Browser: Firefox
 - Version: 75.0

**Additional detail:**
I set Google as home page.

**Comment by Gusted** [comment]
We are doing so fast possible to make it dark and prevent white flashes. But Firefox allows us only from a certain point when DOM has been loaded and not when DOM hasn't loaded yet thats part is white flash.

**Comment by Gusted** [comment]
Duplicate #512 #469

**Comment by vext01** [comment]
I suppose this is why when you open a new tab (ctrl+t) you get a white page?

I was going to raise an issue, but sounds like nothing can be done.

Really excellent plugin by the way. Thank you!

**Comment by Gusted** [comment]
> but sounds like nothing can be done.

Their are multiple issues on chromium, but they are just leaving it if it's not a big deal.

**Comment by vext01** [comment]
Ah, I mean on Firefox, sorry.

**Comment by Gusted** [comment]
> Ah, I mean on Firefox, sorry.

You tried shadowfox?

**Comment by vext01** [comment]
I have not.

Will do.
