### ISSUE TITLE
[BUG] Clicking the website toggle button should toggle PDF too

### ISSUE THREAD

**Issue by alexanderby** [darkreader/darkreader#2439]
Clicking the website toggle button (in the top left corner) should toggle PDF files too.

**Steps to reproduce the behavior**
- Open a PDF document.
- Click Toggle button.

**Expected behavior**
Extension stops inverting PDF file (or inverts if was disabled before).

**Actual behavior**
PDF is still inverted.

**Screenshots**

**Comment by Gusted** [comment]
Problem is that when clicking on the toggle it doens't toggle even. renderBody() method is kind of broken?

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/tree/PDF-Patch
