### ISSUE TITLE
YouTube like buttons are white, even if they're supposed to be blue.

### ISSUE THREAD

**Issue by werymanen** [darkreader/darkreader#2442]
https://youtube.com/

**How to Reproduce**
> 1. Go to random YouTube video, for example, https://www.youtube.com/watch?v=h9j89L8eQQk
> 2. Like the video
> 3. You can see that the text changed colors, but the button itself didn't.

**Expected behavior**
I expected it to be blue, just like the text.

**Actual behavior**
The button stayed white.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/49951816/81069933-dffeeb00-8ee2-11ea-82b7-30c99d936917.png)

**System info:**
 - OS: Ubuntu 20.04 (it's the same for 19.10 and 18.04)
 - Browser: [Brave](https://brave.com/)
 - Darkreader Version: 4.9.8

The comment like button has the same behavior, by the way.

**Comment by Gusted** [comment]
Thank you for reporting this issue 😄

**Comment by werymanen** [comment]
Umm, hey, it's been months, and it still looks bad.

**Comment by Gusted** [comment]
I had a fix but it's being to a cat and mouse game they are changing it perhabs for like bots and stuff :/

**Comment by Gusted** [comment]
I've now made a more `globally` selector and `color` `fill` Just to be sure for next time. So it will hopefully last a lot longer. If you see it again(After next update) Don't hesitate to report.

**Comment by Gusted** [comment]
Their you go #3097 has been merged.
