### ISSUE TITLE
[Feature Request Instagram] The "timer" bar on insta stories should be white

### ISSUE THREAD

**Issue by DiegoChiari** [darkreader/darkreader#2446]
The bar on the stories carrousel should be white. Now it's black and is difficult to see

**Comment by DiegoChiari** [comment]
The bar on the stories carrousel should be white. Now it's black and is difficult to see

**Comment by Myshor** [comment]
Quick question... Do you mean stories shown from Facebook or pure Instagram?

If it's for facebook stories then I checked stories in all designs, made fix for new design now as it was darker with DarkReader enabled.

Fix for facebook is in #2448

**Comment by Gusted** [comment]
#3327
