### ISSUE TITLE
[Feature Request] PDF toggle button

### ISSUE THREAD

**Issue by Ant0ine64** [darkreader/darkreader#2450]
I use chrome and dark reader 4.9.8.
Dark reader randomly (between PC) toggles or not the dark mode on online pdf documents, I can't find any button for toggling off this.

I know there exist `enableForPDF: true` at lines 2215 and 2255 of `%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\Extensions\eimadpbcbfnmbkopoojfekhnkhdbieeh\4.9.8_0\background\index.js`
But if i change this value to `false`, chrome entirely disable the extention, thinking it had been corupted

**Comment by anirekhj** [comment]
> I use chrome and dark reader 4.9.8.
> Dark reader randomly (between PC) toggles or not the dark mode on online pdf documents, I can't find any button for toggling off this.
> 
> I know there exist `enableForPDF: true` at lines 2215 and 2255 of `%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\Extensions\eimadpbcbfnmbkopoojfekhnkhdbieeh\4.9.8_0\background\index.js`
> But if i change this value to `false`, chrome entirely disable the extention, thinking it had been corupted

@Ant0ine64 see https://github.com/darkreader/darkreader/issues/374#issuecomment-480556661
Not exactly what you're asking but similar functionality.

**Comment by chazzireno** [comment]
I started getting this problem after i updated chrome yesterday, but basically despite the site having dark reader toggled off in it, the pdf still has inverted colors, and honestly it looks terrible, please fix.

**Comment by Gusted** [comment]
Open te new design

Devtools -> preview new design

Settings > PDF Enabled

**Comment by Gusted** [comment]
> I use chrome and dark reader 4.9.8.
> Dark reader randomly (between PC) toggles or not the dark mode on online pdf documents, I can't find any button for toggling off this.
> 
> I know there exist `enableForPDF: true` at lines 2215 and 2255 of `%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\Extensions\eimadpbcbfnmbkopoojfekhnkhdbieeh\4.9.8_0\background\index.js`
> But if i change this value to `false`, chrome entirely disable the extention, thinking it had been corupted

The values you changed were for default settings so it wouldn't affect it at all. The real values are stored in the sync(Google chrome) and in localstorage

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/2367
