### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by hmble** [darkreader/darkreader#2451]
**Website**
https://codepen.io

**How to Reproduce**

> 1. Go to codepen.io
> 2. Open any pen ( popular content )
> 3. It shows code editor but doesn't show but only a blank preview .

**Expected behavior**

**Actual behavior**
It should show preivew and not blank preview

**Screenshots**
![2020-05-05-192005_1366x768_scrot](https://user-images.githubusercontent.com/16825207/81182052-f3858100-8fca-11ea-8a1d-c2c23ca55152.png)

**System info:**
 - OS: Linux
 - Browser: Firefox Developer Edition 74
 - Darkreader Version latest.

**Additional context**
I talked to codepen.io support and there was no issue from their side.
When I removed Darkreader everything seems to work fine.
I also checked with other extension. But problem lies with Dark Reader.

**Comment by Gusted** [comment]
Hi their!

Could check 3 things 
1. When opening the addon does it say that codepen.io is in dark global list.
2. Does the issue still persist if you click on off in the addon.
3. What's your current config

I can't reproduce this issue or get near it.

**Comment by hmble** [comment]
Sorry I might to close this issue. I reinstalled addon. Now everything seems to work
