### ISSUE TITLE
make new release

### ISSUE THREAD

**Issue by kolokd** [darkreader/darkreader#2452]
last release was about 2 years ago.

**Comment by alexanderby** [comment]
Why do you need it? You can build the extension from the source code.

**Comment by kolokd** [comment]
i don't want to build it form source code and also don't want to download from chrome store(i use ungoogled chromium)

**Comment by Gusted** [comment]
https://crxdown.com/ (1 Tracker to https://www.googletagmanager.com/gtag/js ) But asuming you value privacy you have already installed adblockers and Google Analytics Opt-out

Use this link to download it:
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

![](https://i.imgur.com/hoRHEuP.png) It downloads trough their own site(proxy) 

**Disclamer: no auto-updates** Building it from source is and will be the best option still.

**Comment by kolokd** [comment]
i don't have much to say, its your decision. I hope you will make a release of every minor version.
I really don't want to go to chrome store and i also don't want to install the dependency to create a build. (nodejs, ts)

**Comment by Gusted** [comment]
> i don't have much to say, its your decision. I hope you will make a release of every minor version.
> I really don't want to go to chrome store and i also don't want to install the dependency to create a build. (nodejs, ts)

I'm pretty sure npm install doesn't log anything it's just add an count into total download. Else npm --proxy is also an option. Those all are developer tools they don't focus on collection data as much as you think(In comparision to regular websites and tools with closed source).

**Comment by kolokd** [comment]
why you can't make a release?

**Comment by alexanderby** [comment]
Because it requires time and effort. At the same I can't remember that anybody needed this. Why can't you install it from Chrome Web Store? There are several ways to simply download CRX from there.

**Comment by kolokd** [comment]
how do you release to chrome store? does it happen automatically?

**Comment by kolokd** [comment]
answer my question.

**Comment by Gusted** [comment]
> Because it requires time and effort. At the same I can't remember that anybody needed this. Why can't you install it from Chrome Web Store? There are several ways to simply download CRX from there.

> how do you release to chrome store? does it happen automatically?

By hand

**Comment by KaKi87** [comment]
With all due respect, using GitHub without creating tags is pointless.

You don't necessarily have to upload the CRX file (even if everyone else does, which should mean it's somewhat feasible), but at least create a simple tag.

**Comment by Gusted** [comment]
Will discuss with the owner of Darkreader to have this from on Darkreader v5 and future releases. I don't mind updating it etc

**Comment by kolokd** [comment]
@Gusted yes i know. that it is done by hand. And that's why i don't understand why there is no release  on github. 
how ublock, singlePage do this? 

As i told that i don't use the regular chromium. I use ungoogled chromium. you may know why.
I have no idea about what's in his mind. This is not how it works.

**Comment by Gusted** [comment]
> @Gusted yes i know. that it is done by hand. And that's why i don't understand why there is no release on github.
> how ublock, singlePage do this?

I don't know if they gave on privacy they will hosted their repo on gitlab perhabs.

> As i told that i don't use the regular chromium. I use ungoogled chromium. you may know why.
> I have no idea about what's in his mind. This is not how it works.

If he decides not to that's fine, their aren't some rules on how to manage an extension on github.

**Comment by kolokd** [comment]
you do what you want. I will not use this

**Comment by KaKi87** [comment]
What do you use then ?
How can we check if we're running the latest version, how can we check the changelog, how can we find the latest commit matching a release ?

**Comment by kolokd** [comment]
@KaKi87 Nothing. If a website doesn't have dark mode i will not force it.
Stop using shit software, whose write is dumb, fucking shit. This type of people don't do open source for fighting for freedom.
Bye.

**Comment by Gusted** [comment]
Is open source equal to fighting for freedom? No good everyone have so their own thing and opnion.
If we decides not to than cursing wont help. I'm sorry I can't help you guys any further


> How can we check if we're running the latest version

Have auto-update? 


>  how can we check the changelog, how can we find the latest commit matching a release ?

https://github.com/darkreader/darkreader/commits/master/package.json
![](https://i.imgur.com/P6Rji7q.png)

**Comment by kolokd** [comment]
@Gusted you are doomed. I can't help you. Go kill yourself.

**Comment by Gusted** [comment]
Leading to cursing and nonsense

**Comment by Gusted** [comment]
https://tenor.com/view/really-oh-jeremy-renner-tell-me-more-gif-4792238
