### ISSUE TITLE
希望增加跟随系统主题自动切换

### ISSUE THREAD

**Issue by mengchenchen** [darkreader/darkreader#2454]
在 Win10 下面是否可以增加跟随系统主题色自行切换网页颜色（当然还手动配置），直接继承系统级别的，这样使用 edge 的时候就属于无感操作了。

**Comment by Gusted** [comment]
你能不能多解释一下你的问题，并提供一些截图，谢谢你!

**Comment by weiyideai520** [comment]
同样希望能支持 跟随系统主题颜色变化，比如win10 设置颜色为“深色”就打开。
如果做不到的话，是否可以考虑加入时间段，比如晚上自动打开
![Snipaste_2020-05-10_20-53-02](https://user-images.githubusercontent.com/2784569/81499735-4a0efa00-9300-11ea-9cbf-c8ce57e6dcc3.png)

**Comment by chsbuffer** [comment]
![image](https://user-images.githubusercontent.com/33744752/83057486-89bc3c80-a089-11ea-8208-ee7b8fc89de5.png)

**Comment by Gusted** [comment]
不是的，我们只是在您的系统颜色是深色的情况下启用暗读器。对于不继承您的系统颜色的网站，我们会把它变暗。

**Comment by chsbuffer** [comment]
> 不是的，我们只是在您的系统颜色是深色的情况下启用暗读器。对于不继承您的系统颜色的网站，我们会把它变暗。

此 系统配色方案 指的是 应用程序白/黑
而不是 主题色

**Comment by Gusted** [comment]
我们所说的系统颜色是指Win10设置下的按钮外观。 你说的主题颜色是什么意思？

**Comment by chsbuffer** [comment]
> ![image](https://user-images.githubusercontent.com/33744752/83122566-6e434700-a106-11ea-9663-91e3176d6566.png)
主题色

> ![image](https://user-images.githubusercontent.com/33744752/83123195-38eb2900-a107-11ea-8cc3-5e2f906b3a40.png)
亮/暗 主题色, 暗读器 使用系统的配色方案 所指的设置

我重新看了一遍问题 , 
@mengchenchen 说的 **主题色** 似乎并没有说明到底是 **主题(颜)色** 还是 **亮/暗 主题色**

暗读器 是用来让网站变暗的
所以我按 **亮/暗 主题色** 回答了

如果是说 **主题色**, 这不是暗读器该去做的

不论是哪种都应关闭问题

**Comment by Gusted** [comment]
哦，那个主题色，好吧，从我们的角度来说，我们无法检查。 如果你想得到支持的话，我建议打开一个chrome bug和/或Firefox bug来添加支持。
