### ISSUE TITLE
[BUG] Inverting all PDFs regardless of settings

### ISSUE THREAD

**Issue by PyroGenesis** [darkreader/darkreader#2455]
**Describe the bug**
The colors of any PDF opened in Chrome are inverted even though the site is not part of the whitelist.

**To Reproduce**
1. After a fresh installation, simply turn on "Invert listed only"
2. Go to any PDF file. [Example](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)
3. You'll find that the PDF colors are inverted.

**Expected behavior**
No website, including the PDF, should have been inverted as we simply have an empty whitelist

**Screenshots**
![image](https://user-images.githubusercontent.com/17806916/81266467-9ead2f00-8ff9-11ea-8851-81c2a8149cb6.png)

**System Information:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Comment by Gusted** [comment]
4.9.8 of darkreader contains new code for invert PDF. 
Open the new design to disable it.
Dev tools -> Preview new design 
Settings -> Invert PDF

**Comment by therealmarv** [comment]
I think it's still a (ux) bug. I use DarkReader for **only** two sites and using it in site list mode for this two sites. Now all my PDFs where black suddenly without warning.

I could turn it off with turning on preview new design (but then I could not find the site list mode) and then turning off preview new design again.

Not every DarkReader user prefers dark for everything.

**Comment by Gusted** [comment]
> I think it's still a (ux) bug. I use DarkReader for **only** two sites and using it in site list mode for this two sites. Now all my PDFs where black suddenly without warning.
> 
> I could turn it off with turning on preview new design (but then I could not find the site list mode) and then turning off preview new design again.
> 
> Not every DarkReader user prefers dark for everything.

It's a bit unfortunate as when we release a new update for a bug that is 'critical' in a way, an update will be pushed. And now the code for dark PDF already was in it and only in new design... Darkreader v5 will force the new design as default, I agree not every user prefer dark

**Comment by rvcjew** [comment]
Using the New UI and having setting of invert PDF's to OFF it will show it as off but still invert when extension is set to ON and not Auto or Off. 

Can reproduce by going to Laptop Manual: https://dlcdnets.asus.com/pub/ASUS/nb/X550CC/E_eManual_X550CC_X550VB_X550VC_VER7926.pdf?_ga=2.258036172.795294428.1590511432-1605495602.1579949424 and checking the main page setting showing PDF option greyed out like it should be off but is still inverted.

10 1903 x64
Chrome
83.0.4103.61 (Official Build) (64-bit)

**Comment by alexanderby** [comment]
@rvcjew Could you please post a screenshot like this?
<img width="746" alt="Screen Shot 2020-05-26 at 20 36 04" src="https://user-images.githubusercontent.com/9638588/82932133-9dd04300-9f90-11ea-8040-c122310d1a12.png">

Do you have custom Dev Tools changes? Try click Reset.

**Comment by rvcjew** [comment]
> @rvcjew Could you please post a screenshot like this?
> <img alt="Screen Shot 2020-05-26 at 20 36 04" width="746" src="https://user-images.githubusercontent.com/9638588/82932133-9dd04300-9f90-11ea-8040-c122310d1a12.png">
> 
> Do you have custom Dev Tools changes? Try click Reset.

Ah, that reset worked thanks a lot! Did this also reset what sites I had it set to not invert and I should go set those again?

**Comment by alexanderby** [comment]
@rvcjew I was talking about Dev Tools Reset button, it only resets Dev Tools config.
<img width="564" alt="Screen Shot 2020-05-26 at 22 50 37" src="https://user-images.githubusercontent.com/9638588/82944203-72a31f00-9fa3-11ea-92dc-5775db3cb23d.png">
