### ISSUE TITLE
[BUG] Github progress bar

### ISSUE THREAD

**Issue by Kuboczoch** [darkreader/darkreader#2460]
**Describe the bug**
Progress bug is always green because .progress class have a property `background-color` set to `green!important`

**To Reproduce**
Go to GitHub project page with some issues in the todos, in progress and done

**Expected behavior**
Each part in that progress bar should be in a different color

**Screenshots**
With:
![image](https://user-images.githubusercontent.com/20823919/81322766-b84f8480-9094-11ea-8f3f-4339bc59ce9f.png)
Without:
![image](https://user-images.githubusercontent.com/20823919/81322940-f482e500-9094-11ea-8789-bccee3d5dce3.png)

**System Information:**
 - OS: Windows 10
 - Browser: chrome
 - Version  81.0.4044.138

**Comment by Gusted** [comment]
Aha I'm seeing I taught it would only target the green part

**Comment by Gusted** [comment]
#2462
