### ISSUE TITLE
[BUG] Donate link doesn't do anything on Fenix

### ISSUE THREAD

**Issue by agi90** [darkreader/darkreader#2464]
**Describe the bug**

**To Reproduce**
- Install Dark Reader on Fenix
- Open popup
- Click on "Donate"

**Expected behavior**
Donate page opens

**Screenshots**
Nothing happens

**System Information:**
 - OS: Android 10
 - Browser: Fenix
 - Version: tip from master

**Additional context**
I'll submit a fix soon :) Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1626356

**Comment by Gusted** [comment]
#2466
