### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by theairbend3r** [darkreader/darkreader#2467]
**Website**
https://tailwindcss.com/

**How to Reproduce**
An example for this is
> 1. Go to x site

**Expected behavior**
Navbar and sidebar, along with some other components do not invert colours.

**Actual behavior**
Navbar and sidebar should invert colours.

**Screenshots**
![image](https://user-images.githubusercontent.com/60727948/81374422-d660c780-911c-11ea-8980-32afa8d3afdd.png)

**System info:**
 - OS: Ubuntu 18
 - Browser: Firefox
 - Darkreader Version: 4.9.8

**Comment by Myshor** [comment]
I made fixes for that white backgrounds + headers texts will be more readable.
![image](https://user-images.githubusercontent.com/56877029/81437718-ed7ad600-916b-11ea-9327-569e8bc25c97.png)

**Comment by theairbend3r** [comment]
Amazing! Thanks for the speedy PR! :)
