### ISSUE TITLE
[BUG] Top section with Enable\Disable buttons dissapeared

### ISSUE THREAD

**Issue by omfgnuts** [darkreader/darkreader#2468]
**Bug Description:**

The top part of the extension with functionality to disable dark mode on current website disappeared, see attached screenshot

**To Reproduce**

> Go to 'Chrome Web Store'
> Click on Install Extension'
> No way to disable on current website

**Expected behavior**

I could disable dark reader on current website until just recently

**Screenshots**

![image](https://user-images.githubusercontent.com/845482/81409890-97486b80-9148-11ea-9dff-f77953d25871.png)

**System Information:**
 - OS: ChromeOS
 - Browser 84.0.4137.0 canary

**Comment by Gusted** [comment]
Can you make sure you using the official dark reader extension 
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/
Else reinstall as My fresh copy of the chrome web store doesn't have this behaviour.

@omfgnuts

**Comment by omfgnuts** [comment]
> Can you make sure you using the official dark reader extension 
> https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/
> Else reinstall as My fresh copy of the chrome web store doesn't have this behaviour.
> 
> @omfgnuts 

I lived like this for almost a week, and I posted here just right after reinstalling it from store :(

**Comment by Gusted** [comment]
> I lived like this for almost a week, and I posted here just right after reinstalling it from the store :(

You can try to reinstall it one more time or close chrome fully and open chrome. Maybe chrome had a bad day today

@omfgnuts

**Comment by ev-dev** [comment]
Also starting seeing this bug on macOS both dev & canary channels, not happening in beta or stable tho so issue might not persist in next builds.

Versions at time of posting:
- Stable: 81.0.4044.138
- Beta: 83.0.4103.44
- Dev: 84.0.4136.7
- Canary: 84.0.4140.0

**Comment by Gusted** [comment]
> Also starting seeing this bug on macOS both dev & canary channels, not happening in beta or stable tho so issue might not persist in next builds.
> 
> Versions at time of posting:
> 
> * Stable: 81.0.4044.138
> * Beta: 83.0.4103.44
> * Dev: 84.0.4136.7
> * Canary: 84.0.4140.0

Hmm macos and dev canary build I will have a look.  Know that they are unstable build etc I'm using beta chromium so bugs in newer version like v83 v84 wil be not that fast fixed as mostly are browser bugs. But seeing your both are on v84 it will be an easy reproduce

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/81467189-5481a480-91d7-11ea-8600-ec4734af2628.png)

Hmm Chrome Canary 84.0.4141.0 Windows 10....

**Comment by MrT3chGuy** [comment]
I just got an update for Chrome Canary, Version **84.0.4142.0** which fixes the issue for me!

**Comment by Gusted** [comment]
@omfgnuts @ev-dev 

> I just got an update for Chrome Canary, Version **84.0.4142.0** which fixes the issue for me!

**Comment by omfgnuts** [comment]
I'm on 84.0.4140.0, as it's the latest Canary ChromeOS atm, so the bug is still here for me.

I'll report back once I receive another update

**Comment by ev-dev** [comment]
No longer seeing issue in 84.0.4143.2 macOS

(although after 4 days without the visual toggle, I finally have muscle memory on the key shortcut so now I don't even want to click a dang button ✌)

**Comment by Gusted** [comment]
@ev-dev :joy:

Than this was a browser bug that already got fixed and only was for canary and dev
