### ISSUE TITLE
[V5] New UI - Sitelist

### ISSUE THREAD

**Issue by Gusted** [darkreader/darkreader#2477]
![](https://cdn.discordapp.com/attachments/701878965933178901/701881505626062908/Screen_Shot_2020-04-20_at_22.38.41.png)

Sitelist is not added yet 👀

**Comment by narfanar** [comment]
Please include searching for the sitelist :D

**Comment by Gusted** [comment]
Sitelist has been merged #3202 and will me released in next update(no ETA)
