### ISSUE TITLE
[BUG] Embedded PDFs invert with PDF toggle off

### ISSUE THREAD

**Issue by kiriya-aoi** [darkreader/darkreader#2478]
**Describe the bug**
Embedded PDFs (page url not ending in .pdf) ignore PDF settings.

**To Reproduce**
Have the PDF toggle switched off and come across a PDF has been embedded in some form.
For an example, https://www.npaschools.org/embedded-pdf-test or https://www.horiba.com/scientific/testing-area/pdf-embedded/.
The PDF will be inverted per the site settings.

**Expected behavior**
PDFs would invert only if the PDF toggle says they should.

**System Information:**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 3.1

**Comment by StevenLi-DS** [comment]
@kiriya-aoi Is there a pdf toggle that lets darkreader not change pdf reader to dark mode?

**Comment by kiriya-aoi** [comment]
https://github.com/darkreader/darkreader/issues/2455#issuecomment-625208032

**Comment by Gusted** [comment]
Working on it... Our code wasn't based on embedded pdf's

**Comment by Gusted** [comment]
Fixed and shipped
