### ISSUE TITLE
[BUG] PDF files systematically inverted, despite unwanted

### ISSUE THREAD

**Issue by Chomchaum** [darkreader/darkreader#2480]
All my PDF are getting inverted since a few days.
I have no way to block it as there is no PDF toggle option.
The addon just shows itself enabled on the PDF without being able to click on the toggle button.

Expected result :

No inversion of PDF without activating the PDF/website (I'm using the only inverted system)
Having the ability to toggle with the button in extension menu
(Mandatory.gg isn't activated in usual pages)

![2020-05-10_19-02-25](https://user-images.githubusercontent.com/47415310/81505607-d3b6cb80-92f0-11ea-9319-b10ca09d4ce3.png)
![2020-05-10_19-04-07](https://user-images.githubusercontent.com/47415310/81505636-0cef3b80-92f1-11ea-8189-2a991e7abd10.png)

**System Information:**
- **OS:** Windows 10
- **Browser:** Chrome
- **Version:** 81.0

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/2455#issuecomment-625208032
