### ISSUE TITLE
[Broken Website] Builder.io

### ISSUE THREAD

**Issue by bherila** [darkreader/darkreader#2484]
**Website**

https://www.builder.io/

**How to Reproduce**

1. Go to https://www.builder.io/
2. Observe the page is still light
3. Disable Dark Reader for this site then Re-enable. 

Miraculously, the site is now dark! However, upon navigating to another page, the site is no longer dark again. It appears the site keeps resetting its CSS for some reason.

**Expected behavior**

Dark mode works properly

**Actual behavior**

1. Dark mode doesn't work for the site unless it's disabled and re-enabled on that page.
2. Have to disable and re-enable every time you navigate on this site.

**Screenshots**

Expected: 
![image](https://user-images.githubusercontent.com/1422004/81511827-d86b8780-92d0-11ea-987d-981c82cfc56d.png)

Actual: 
![image](https://user-images.githubusercontent.com/1422004/81511784-95111900-92d0-11ea-9298-afdd95bc2556.png)

**System info:**
- Mac OSX
- Chrome  Version 81.0.4044.138 (Official Build) (64-bit)
- Dark Reader version 4.9.8

**Additional context**

Thank you for looking into this!

**Comment by Gusted** [comment]
Could be a possible duplicate of #2065

**Comment by bherila** [comment]
I think you're right @Gusted . Will close this issue. Also found another site today, added it to that issue.
