### ISSUE TITLE
[Feature Request] Invert black favicons for dark browser themes

### ISSUE THREAD

**Issue by Mertyn** [darkreader/darkreader#2489]
There are many websites that have a favicon that is just a black logo graphic, which is hard to see when using a dark browser theme and sometimes is a hindrance when trying to quickly find a tab. My idea is to have a list of those websites (like there already is for dark websites) and invert their favicon.

I already know this is possible to do, because I made a little test extension that does exactly what I described. You can find it [here on Github](https://github.com/Mertyn/favicon-invert), try it out for yourself and take a look at the code to see how it works internally
Here's a little before and after screenshot:
![favicon-invert](https://user-images.githubusercontent.com/22528516/81560374-95251d80-9391-11ea-9096-8c90679751ac.jpg)

The function can still be improved upon, like making it not just completely invert the whole image but only make black parts white for example.
I also tried to implement this functionality in darkreader myself, but I find the code pretty hard to understand since I am not an active developer here and have never really worked with typescript before.
I hope you think this could be a useful feature aswell and this helped make darkreader just that little bit better than it already is. If there is no interest at all in adding this to darkreader just let me know and I will break this off as my own extension project.

Thanks for reading and I am looking forward to hearing back :)

**Comment by Gusted** [comment]
Hi Mertyn :D 

I get that the code is hard especially in the begin.
We have code for analyzing if an image is black or not. 

Right here https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/image.ts#L52
It returns isDark isLight isTransparent isLarge.

For the placement of the code it's the best to call the function here
https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts#L125
and make an export function in image.ts of that folder. 

If you need any help, ask it and make sure you ping me :)

**Comment by Mertyn** [comment]
Thank you so much for your help @Gusted :)
I'm gonna look into implementing it soon. Some comments would really help understanding the code I think, but I think I also get why there aren't any. Alternatively someone could maybe write some documentation detailing the inner workings of the code.
Tanks again, Cheers :)

**Comment by Gusted** [comment]
Don't worry I'm almost done implementing this :) @Mertyn
I agree documentation would a good thing but that would cost someone probably a day or maybe even 2. But it will attract new users to add code and understanding darkreader better.

**Comment by Mertyn** [comment]
Great, I already noticed the new branch :) @Gusted 
I would love to make some documentation, but as I said before I sadly don't completely understand it :/

**Comment by Gusted** [comment]
@Mertyn Only me also understand it half 😅 It's a big code base and a lot of function where I simply don't get what it's doing or even how it's working, if you have an idea to come up with an documentation I will love to help write it about how functions works and also add some short description in the code itself :)

**Comment by Gusted** [comment]
@Mertyn if you like to you can open an seperate issue for the documentation :)
