### ISSUE TITLE
[Broken] Vim Vixen overlay breaks DarkReader

### ISSUE THREAD

**Issue by xerus2000** [darkreader/darkreader#2491]
**Website**
https://learnvimscriptthehardway.stevelosh.com/chapters/21.html

**How to Reproduce**
Dark Reader On with Dynamic Dark mode

**Actual behavior**
Site turns completely dark

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/81590587-4e4c1d80-93bb-11ea-8ef7-4cbec77a2d6f.png)
I don't reproduce this. Can you give some more explainition @xerus2000

**Comment by xerus2000** [comment]
![image](https://user-images.githubusercontent.com/13354331/81609979-0cca6b00-93d9-11ea-8163-6f4c0e127667.png)
Literally blank for me. Only thing I'd say is worth mentioning is that I use Firefox 75.0 with the Default theme with system dark mode on.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/81614976-2079cf80-93e1-11ea-854a-3cb203ce2333.png)
Nope.... Is their any error in console?

**Comment by xerus2000** [comment]
Now that is weird: When I open the page with DarkReader on, it turns blank. When I open it with DarkReader off and then turn it on, all is fine.

**Comment by Gusted** [comment]
Do you know how to use the dev tools in Firefox? @xerus2000

**Comment by xerus2000** [comment]
Yes, I am also a developer, just tell me what you need ;)
A thing I just found out
![image](https://user-images.githubusercontent.com/13354331/81914202-482f8a00-95d1-11ea-80b3-b07a96121739.png)
Notice how I _only_ changed the background-color
![image](https://user-images.githubusercontent.com/13354331/81914222-4f569800-95d1-11ea-8eab-04a21709d4bb.png)

**Comment by xerus2000** [comment]
Aha, found the culprit!
[vim-vixen](https://github.com/ueokande/vim-vixen) adds a frame over the whole page which is then colored by DarkReader!
![image](https://user-images.githubusercontent.com/13354331/81914645-dc015600-95d1-11ea-87c9-80a03bf3b654.png)

**Comment by Gusted** [comment]
> Aha, found the culprit!
> [vim-vixen](https://github.com/ueokande/vim-vixen) adds a frame over the whole page which is then colored by DarkReader!
> ![image](https://user-images.githubusercontent.com/13354331/81914645-dc015600-95d1-11ea-87c9-80a03bf3b654.png)

Ah iframes we handle them kinda but overlaying the whole page is a no go for darkreader

**Comment by Gusted** [comment]
seems like `body *` -> `body :not(iframe)` Would resolve this issue
