### ISSUE TITLE
[BUG] Dev tools "Apply" button discards changes?

### ISSUE THREAD

**Issue by NSExceptional** [darkreader/darkreader#2495]
**Describe the bug**
Whenever I try to open DarkReader's Dev Tools, I am unable to apply changes. Hitting "Apply Changes" seemingly discards whatever changes I made.

**Expected behavior**
Upon clicking "Apply Changes" my changes are saved and the page updates with my changes.

**Screenshots**
[Here is a screen recording](https://streamable.com/g93yfo) demonstrating the issue. I'm trying to invert a logo at the top of `mod.reddit.com`

**System Information:**
 - macOS 10.15
 - Chrome 80
 - Not sure what version of DarkReader I'm on, but doesn't Chrome keep extensions up to date?

**Comment by Gusted** [comment]
Is this just with reddit and than a subdomain changing.

**Comment by NSExceptional** [comment]
No, this happens everywhere as far as I can tell

**Comment by Gusted** [comment]
ctrl + f - > mod.reddit.com
It's changed order as alphabetic order :)

**Comment by Gusted** [comment]
Woops

**Comment by Gusted** [comment]
![](https://i.imgur.com/kiWq06M.gifv)

**Comment by NSExceptional** [comment]
No, yeah, you were right to close this, I didn't realize that's what was happening.

I guess from a user perspective this is just unexpected behavior. Rarely do you save a document and have your changes completely rearranged.

**Comment by Gusted** [comment]
>I guess from a user perspective this is just unexpected behavior. Rarely do you save a document and have your changes completely rearranged.

That's correct. Moving to the current site is a good idea.

**Comment by NSExceptional** [comment]
@Gusted No, I don't think rearranging stuff at all is a good idea. What if I add multiple rules, etc.

Anyway, regarding the original issue, I have found an example of it _actually_ discarding some changes. When trying to add this to `github.com`, it is removed:

```
NO INVERT
a > img[src^="https://camo.githubusercontent.com/"]
```

**Comment by Gusted** [comment]
rearranging is unfortunate a think we need to do in the devtools to hold it organize and don't make potential bugs with fetching Fixes and updating extension. If we want to add a settings menu in devtools I will add this for sure.

> ```
> NO INVERT
> a > img[src^="https://camo.githubusercontent.com/"]
> ```

On which mode are you? e.g. Dynamic Static Filter(+)

**Comment by Gusted** [comment]
If it's good it will reoder it just above CSS. Just another rule to stop any mess 😬 
![](https://i.imgur.com/qoz8Ogv.png)

**Comment by NSExceptional** [comment]
[It is completely removed.](https://streamable.com/etsb6x) What determines whether it is "good" or not? Some errors or other diagnostic information would be helpful as a user

**Comment by Gusted** [comment]
'Dynamic Theme Editor' you need to have filter mode enabled to edit the config of Filter. A error is implemented but That is for other diagnostic.

**Comment by NSExceptional** [comment]
I'm using Filter+, is that not a dynamic theme?

**Comment by Gusted** [comment]
![](https://darkreader.org/help/en/#theme-generation-modes) 
More -> ![](https://i.imgur.com/XbhR6bX.png)

**Comment by NSExceptional** [comment]
Yeah, gotcha.

Filter+ looks so much better than the dynamic theme, is there no way you could add a feature to make it ignore some tags like this?

**Comment by Gusted** [comment]
`Uncaught ReferenceError: this is not defined
    at <anonymous>:1:1`

Please define `this`

**Comment by NSExceptional** [comment]
Huh?

**Comment by Gusted** [comment]
Define `to Ignore tags`

And so we are on the same line you want to make a edit for the Filter+![](https://i.imgur.com/yOR7vqs.png) And not dynamic

**Comment by NSExceptional** [comment]
I basically just want theme editor support for Filter+, like you have for Dynamic. I want to be able to provide custom `CSS`, and I want to be able to `NO INVERT` some CSS selectors like you can in the dynamic theme editor 😄

Correct, I want this for Filter and Filter+, not Dynamic

**Comment by Gusted** [comment]
>

**Comment by NSExceptional** [comment]
When I do that it still says [dynamic theme editor](https://streamable.com/ug0y0z)

**Comment by Gusted** [comment]
Refresh the page? Or re-open the browser maybe.

**Comment by NSExceptional** [comment]
No dice. It has always been like this for me. It has never said anything but "dynamic theme editor"

**Comment by Gusted** [comment]
Than reinstall the extension I guess....

**Comment by NSExceptional** [comment]
Huh, that did the trick. Weird. Thank you, sorry about that!

**Comment by Gusted** [comment]
No sorry about that, I'm happy to help users instead of letting users sitting with errors. Just let me know if adding the rule works.

**Comment by Gusted** [comment]
In Inversion fix editor ^

**Comment by NSExceptional** [comment]
Okay, after some digging around I actually know what the problem is. The Dev Tools button opens the editor for whatever the "default" is, instead of what the current page is using.

If the page I'm on is using the Filter/+ theme, that button should open the "inversion fix editor," and if the page is using dynamic then it should open "dynamic theme editor."

**Comment by Gusted** [comment]
Ah, will make a patch for that tomorrow

**Comment by NSExceptional** [comment]
Hey @Gusted, didn't wanna make a new issue for this since I just have a question you can probably answer.

About the Inversion Fix Editor. I'm trying to make it not invert the "Languages breakdown" part of a repo. [Example page](https://github.com/NSCake/nscake.github.io), on the right side at the bottom.

I put this in the inversion fix editor:

```css
NO INVERT
.Progress span
```

but it is still inverted? I also tried just `.Progress`, which is the parent element of each of the segments of the "progress" bar.

What am I doing wrong?

**Comment by Gusted** [comment]
![](https://i.imgur.com/b7Lxb37.png) The invert does nothing It's inline styling

**Comment by NSExceptional** [comment]
I'm confused, I just want to keep DarkReader from changing the colors inside that element, is there a way to do that?

**Comment by Gusted** [comment]
Oh it's necessary for some elements even in dark reader to invert colors. I don't think their suchs way for invert to ignore inline styling

**Comment by NSExceptional** [comment]
Hey, I'm coming back to this with another example. Filter+, trying to make it not invert the toolbar on [developer.Apple.com](https://developer.apple.com/documentation/foundation/nsurlsession) since the toolbar is already dark.

I added this and it is saved, so it parses correctly:

```
================================

developer.apple.com

NO INVERT
.localnav-wrapper

================================
```

But it is still inverted. I still don't really understand your last answer, so I assume this may be the same issue as before. Can you elaborate on why DarkReader does not/cannot avoid inverting this element and it's children?

**Comment by Gusted** [comment]
Change `NO INVERT` into `INVERT` and it should work.

**Comment by NSExceptional** [comment]
Weird, NO INVERT started working all of a sudden. I didnt change anything

Sorry!
