### ISSUE TITLE
[BUG] Cannot toggle current site on local PDF

### ISSUE THREAD

**Issue by JasonMan34** [darkreader/darkreader#2498]
**Describe the bug**
Cannot use 'Toggle Site' on local PDF files  
This applies only to PDFs, as local text files opened with chrome behave as expected

**To Reproduce**
> Open any local PDF file with Chrome
> Click on 'Toggle Current Site'
> Nothing happens

**Expected behavior**
The extension is disabled for the 'current site' (in this case, the local drive)

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/13543641/81692794-9c1e5f80-9467-11ea-8f10-ff15f8e19ff2.png)
Clicking
![image](https://user-images.githubusercontent.com/13543641/81692831-a6d8f480-9467-11ea-950c-5b78a6e8ce2c.png)
After
![image](https://user-images.githubusercontent.com/13543641/81692794-9c1e5f80-9467-11ea-8f10-ff15f8e19ff2.png)

**System Information:**
 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Version** Latest

**Comment by Gusted** [comment]
Devtools - > preview new design
Settings - > PDF
