### ISSUE TITLE
[BUG] My PDFs are being converted now Chrome

### ISSUE THREAD

**Issue by JakeQuinn77** [darkreader/darkreader#2501]
PDF links are getting converted now, just a few days ago pdf files were not being converted which is the way i like it as i prefer pdf to be unconverted. As i like to read datasheets in their original color

And I cannot find a setting to make it back the way it was, Whitelisting the pdf also is kinda annoying because, its domain based and every time i visit their website i have to toggle it back again

I am not sure if it a bug or a new update

![image](https://user-images.githubusercontent.com/62618765/81712903-c3951c80-94a7-11ea-9016-b61fd446ede7.png)

**Comment by Gusted** [comment]
Hi @JakeQuinn77!

I'm happy to help you with this.
Open devtools.
Click on Preview new design.

Click on settings in the new UI
And their you can toggle the pdf inverting.

**DISCLAMER: New UI is still in BETA**

**Comment by JakeQuinn77** [comment]
> Open devtools.
> Click on Preview new design.
> 
> Click on settings in the new UI
> And their you can toggle the pdf inverting.
> 
> **DISCLAMER: New UI is still in BETA**

There it is !! Thank you very much  good sir,  there was no warning that it updated and the setting was moved there.

**Comment by Gusted** [comment]
>There was no warning that it updated and the setting was moved there.

Thats right.....
