### ISSUE TITLE
[BUG] [Firefox] Toggling 'change the browser theme' to 'custom', then back to 'default' sets the browser theme to light.

### ISSUE THREAD

**Issue by jonohewitt** [darkreader/darkreader#2509]
**Describe the bug**
Toggling from default to custom and back to default in the Dark Reader preferences panel in Firefox Beta 77.0b4 with dark theme enabled turns the top bar white until restarting Firefox.

**To Reproduce**
> • Open any website in Firefox with dark theme enabled. 
> • Open the Dark Reader dashboard by clicking the add-on logo in the top right
> • Underneath 'On Off', in the 'Filter, Site List, More' menu,  click 'More'
> • Towards the bottom, click 'Custom'
> • Toggle back to 'Default'

**Expected behavior**
The browser UI turns back to dark mode

**Observed behaviour**
The browser UI turns to light mode

**Screenshots**
<img width="1040" alt="Screenshot 2020-05-13 at 18 32 18" src="https://user-images.githubusercontent.com/47791294/81845231-3524a780-9548-11ea-9d19-94b0b43a45a1.png">

**System Information:**
 - OS: MacOS Catalina 10.15.4 (19E287)
 - Browser: Firefox 
 - Version: Beta 77.0b4

**Comment by Gusted** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415267
