### ISSUE TITLE
[Broken Website] Wikipedia projects

### ISSUE THREAD

**Issue by zoranzoki21** [darkreader/darkreader#2523]
**Website**
Wikimedia wikis like Wikipedia

**How to Reproduce**
1. Register account on Wikipedia
2. Open incogito window and open Wikipedia and edit your talk page as IP and save it
3. You will get notification, click on icon to see it

**Expected behavior**
New notification should have black color always, not white.

**Actual behavior**
New notification have white color, instead of black. When I mark it as read, and open menu again, it is normally black as should be. See screenshots down.

**Screenshots**
**Current behaviour**
![echo notification](https://user-images.githubusercontent.com/28963303/82118061-f293e280-9774-11ea-8e47-b8233dfb296a.png)

**Expected behaviour**
![echo notification - 2](https://user-images.githubusercontent.com/28963303/82118059-f162b580-9774-11ea-8058-a1014069e3a6.png)

**System info:**
 - OS: Kubuntu 20.04
 - Browser: Google Chrome - Version 81.0.4044.138 (Official Build) (64-bit)
 - Darkreader Version: 4.9.8

**Additional context**
Originally reported on Wikimedia's Phabricator: https://phabricator.wikimedia.org/T252862

**Comment by zoranzoki21** [comment]
I'm not sure how to make this fixed:
![image](https://user-images.githubusercontent.com/28963303/82119103-0d1d8a00-977c-11ea-9138-e8225a31dc86.png)

**Comment by Gusted** [comment]
Hmm weird behaviour I will have a look
