### ISSUE TITLE
[Broken Website] old.reddit.com comment replies have poor readability and essentially lack dark mode

### ISSUE THREAD

**Issue by 07416** [darkreader/darkreader#2527]
**Website**
https://old.reddit.com/r/Games/comments/gj0m4b/unreal_engine_5_revealed_nextgen_realtime_demo/

The comment replies are highlighted in white, the text color is grey and poorly visible against the background

![Screenshot_2020-05-16 Unreal Engine 5 Revealed Next-Gen Real-Time Demo Running on PlayStation 5](https://user-images.githubusercontent.com/14923168/82125170-e297f500-97ac-11ea-8dcf-6d53a0f41644.png)

**Comment by Gusted** [comment]
Are you using dynamic theme?

**Comment by Gusted** [comment]
Are you using dynamic theme?

**Comment by vadash** [comment]
Use RES 
![image](https://user-images.githubusercontent.com/1397582/82131008-46381780-97d9-11ea-8922-296cd17d5aa6.png)

**Comment by 07416** [comment]
> 
> 
> Are you using dynamic theme?

Sorry, I tested with a fresh profile and the issue is no longer present. [RES](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/) causes this conflict and I haven't consciously changed any style or theme settings from the defaults.
