### ISSUE TITLE
[Feature Request] Shades of grey instead of 100% Black

### ISSUE THREAD

**Issue by DwarfFighterCleric** [darkreader/darkreader#2536]
Would be neat if there was a color selector for the background instead of making it 100% Black. I feel like 100% is also damaging to the eyes due to the constant re-focusing when reading. I just want to make page "less white" for lack of a better term.  
Reporting that simply downloading the source and loading into Chromium version 71.0 does not work ("Could not find manifest") but when I go to Releases and download the ZIP there it works. (throws errors at loading but the functionality works)  
edit: formatting

**Comment by Gusted** [comment]
> Would be neat if there was a color selector for the background instead of making it 100% Black. I feel like 100% is also damaging to the eyes due to the constant re-focusing when reading. I just want to make page "less white" for lack of a better term.
> Reporting that simply downloading the source and loading into Chromium version 71.0 does not work ("Could not find manifest") but when I go to Releases and download the ZIP there it works. (throws errors at loading but the functionality works)
> edit: formatting

The release tab is old and not maintained versions use addon store or chrome webstore

**Comment by DwarfFighterCleric** [comment]
Yeah but the updated version inside of the ZIP don't even load, it says it "lacks manifest file"

**Comment by Gusted** [comment]
Can you send the zip file, does it actually contain a manifest.json file or just another folder with in that a manifest.json?

**Comment by DwarfFighterCleric** [comment]
It's the ZIP file which is downloaded when I enter this Github page right here and click on the green button to download. It's the very same procedure I did for installing other extensions. Maybe it's something related to this "old" version I'm using, Chromium version 71.0 (December 2018) Anyway, thanks, I have solved my problem. Would still be great to see as a feature the possibility of replacing the "Black" for "Dark Grey" or any other color. (like the youtube website does)

**Comment by Gusted** [comment]
Well as you see we don't use the the release tab anymore for publishing the extension, so far I know it's been fixed in the newest version of darkreader 4.9.8

**Comment by DwarfFighterCleric** [comment]
Ok let's take some steps back. Let me type this again:
1) The version listed on the "Release" tab (you said is an older one?) WORKED OK here.
2) Downloading the "main" version (NOT Release tab) was the one that DID NOT work.

**Comment by Gusted** [comment]
Hmm let me have quick look

This with 4.9.8 ![](https://i.imgur.com/6SBbYOo.png) background = rgb(24, 26, 27); pretty `shade of grey` in my eyes.

Do you maybe have Filter mode on? ![](https://i.imgur.com/R2KkVQs.png)

**Comment by DwarfFighterCleric** [comment]
Yes, that gray tone is perfect. But here's the thing:
Dude, I have said 2 times now that I'm using the version downloaded from the Release tab, because the main updated one doesn't work here. It shows this error message when I try to load the unpacked extension (I will never use the chrome store, I will only load unpacked extensions)
![FailedToLoad](https://user-images.githubusercontent.com/53971674/83226529-bc416480-a171-11ea-87cd-c86b42638c63.png)
For now, I'm using Dark Reader version 3.5.4
Could you guide me through the steps of making the Manifest file work here? Chromium version 71.0 (I'm not updating anything too, don't come here recommending that...)

**Comment by DwarfFighterCleric** [comment]
Why did you stop updating the Release tab anyway?

**Comment by DwarfFighterCleric** [comment]
Ok, I tried manually removing the Locales line from the Manifest and removing the directory manually, another error appeared.
I'm trying to find the portion of the code in this older version that I have to try changing to grey myself.
Is this the section that specifies color?
`    invert += 'invert(100%) hue-rotate(180deg) ';`
Let's say that I want to change Dark mode to #4F4F4F or RGB 79,79,79 how would I do it? In the old version.

**Comment by Gusted** [comment]
> Why did you stop updating the Release tab anyway?

Not my job I'm just a maintainer.

But you can build dark reader yourself if you feeel to.

**Comment by Gusted** [comment]
> Let's say that I want to change Dark mode to #4F4F4F or RGB 79,79,79 how would I do it? In the old version.

Hi @DwarfFighterCleric!

We never implemented a option in the old version of dark reader to change the background color.
However for the newer/maintained version we [have implemented this since v4.9](https://darkreader.org/blog/v4-9/)

Regards,
Gusted
