### ISSUE TITLE
Extract custom dark CSS in use

### ISSUE THREAD

**Issue by poopingpenis** [darkreader/darkreader#2538]
Is there a way to extract the dark CSS the add-on generated for a page?

**Comment by Gusted** [comment]
Depends on which mode you want.

**Comment by poopingpenis** [comment]
@Gusted What do you mean?

**Comment by Gusted** [comment]
The current mode.
Dynamic Static Filter Filter+

**Comment by poopingpenis** [comment]
@Gusted I have it on Dynamic

**Comment by Gusted** [comment]
#3120

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted

**Comment by AbelLykens** [comment]
Hi @Gusted  -- I tried to follow these steps (tested in Edge + FF) but I don't get a pop-up after clicking "Preview in new design" (which should have settings??). Hope you can tell me how to export the generated CSS. Much appreciated.

**Comment by fakhamatia** [comment]
> In the next update of Dark Reader 4.9.16 you can export it to CSS File 🎉 This can trough the following steps:

How can I extract CSS of some site in Version 4.9.87 ? 
I want all CSS injected to [specific](https://www.openstreetmap.org/) site
