### ISSUE TITLE
[BUG] Stackoverflow upvote not colored

### ISSUE THREAD

**Issue by r3a1d3a1** [darkreader/darkreader#2546]
Dark Reader version: 4.9.8
(Built from source two days ago)

**To Reproduce**
Upvote any post in Stackoverflow. It doesn't show as orange. Although if you open the same page in the future, it correctly shows the up-arrow as orange.

**System Information:**
 - OS: MacOS 10.15.4
 - Browser: Chrome
 - Version: 81.0.4044.138

P.S. I know Stackoverflow has dark mode builtin, but I prefer to use this extension to easily toggle it on & off. Hence, I keep the builtin dark mode always set to off.

**Comment by Gusted** [comment]
Did you had enough karma to upvote post. I thought you needed 15 points/karma to viable upvote the post

**Comment by r3a1d3a1** [comment]
😂 of course! It's well colored in normal mode.

**Comment by Gusted** [comment]
Well, do you know how to use the Devtools as I don't have enough reputation yet 👀

**Comment by r3a1d3a1** [comment]
I haven't faced this issue for a while now. Updating Chrome to 83 may have solved it 🤷‍♂️
