### ISSUE TITLE
facebook.com [old design] using firefox 

### ISSUE THREAD

**Issue by mrturkmen06** [darkreader/darkreader#2547]
**Website**
- facebook.com

Normally, there  is no problem in general for facebook.com and I guess more fixes are coming up to with #2531. 

However, it seems that the unexpected behavior is happening on only firefox, as you can follow through the conversation on #2531.

**How to Reproduce**
An example for this is
> 1. Go to facebook.com site
> 2. Click on liked button (-to see who liked-)
> 3. See that name and surnames are not correctly inverted. 

I have included a screenshot. 

**Expected behavior**
Expected field (name and surname) should be inverted correctly. 

**Actual behavior**
No quite easy to see names and surnames. 

**Screenshots**

<img width="489" alt="Screenshot 2020-05-18 at 20 51 22" src="https://user-images.githubusercontent.com/13614433/82250887-f7af8800-9954-11ea-9292-f5086b613811.png">

**Browser Info**
- Firefox 76.0.1 (64-bit) 

**Darkreader info** 

<img width="663" alt="Screenshot 2020-05-18 at 22 18 48" src="https://user-images.githubusercontent.com/13614433/82251271-8f14db00-9955-11ea-8ecc-42aefaa5a1d9.png">

**Comment by Gusted** [comment]
@Myshor Their you go, goodluck having headache fixing facebook again smh.

**Comment by Myshor** [comment]
@mrturkmen06 Tried to reproduce and I can't :(

I have 2 questions:
1. What system do you use? Windows/Linux?
2. Check if you have default config for fixes on facebook. Do you see "!"?
![image](https://user-images.githubusercontent.com/56877029/82490408-7df9d480-9ae3-11ea-9e42-e8bada396c4f.png)
If yes then go to Dev tools, reset them and Apply.
Then check facebook again.

I checked this part of facebook with clean config, then with my all new fixes using firefox and I can not reproduce it on my Windows 10.

**Comment by Gusted** [comment]
@Myshor 

This was the config as of 4.9.8 release https://github.com/darkreader/darkreader/blob/d93d61f9a9cc376fea7261f4d82f26a8ef28d561/src/config/dynamic-theme-fixes.config

Can you also check with this config maybe it's already fixed but not published yet.
```
================================

facebook.com

INVERT
._2o89
._2q08
.sx_af7fe0
.sx_7ed17e
.sx_a4a936
.sx_4d607f
.sx_aca067
.sx_77228a
.sx_51302f
._2yu5
._3iiv
._3pao
.kv0qyzoi
.sx_426ea6
.sx_b77acf
._2gb3
._7sjb
.sx_b9f33b
._3w97
.sx_2e7846
.sx_6d18f4
.monochrome
.repliedLast
.sx_73ef60
._81u_ .img
._3ffs li
#profile_intro_card_bio i
.uiScrollableAreaWrap .uiList button[type="submit"] i._3-8_
.editPhoto i._3-8_
.sx_08856a
.sx_ac12f7
.sp_hk4DJV_EEeW
.sp_V53xxlprDHX_1_5x
.sp_V53xxlprDHX_2x
#pagelet_ego_pane button .img._3-8_
#homepage_panel_promote_footer_pagelet button .img._3-8_
#event_tabs #reaction_units span img
.fbPlaceFlyoutWrap img
img[src*="map"]
[style*="map"]

CSS
.fbNubButton {
    background-image: none !important;
}
.jewelItemNew ._33e {
    background-color: ${#d0d1d3} !important;
}
._5qxm {
    background-color: rgba(0, 0, 0, 0.25);
    background-blend-mode: color;
}
.sx_cf4e6b {
    filter: brightness(250%) !important;
}
._34k2 {
    filter: brightness(1000%) !important;
}
._3hx- ._4tdt,
._3hx- ._5wd4,
._3hx- ._6vu5 ._5w-5,
._3hx- ._1aa6::after,
._3hx- ._6vu5 ._31o4,
._3hx- ._2cnu:only-of-type ._5wdf,
._3hx- ._5w0o,
._3hx- ._5z-5,
._3hx- ._16ys._3e7u,
._3hx- ._49or .__6j,
._3hx- ._324d .__6j,
._llj {
    border-color: ${#eee} !important;
}
._3hx- ._ua1,
._3hx- ._40qi,
._3hx- ._5ye6,
._3hx- ._llj,
._3hx- ._1a6y,
._31o4,
._3_bp,
._4gd0,
._49or,
._40fu {
    background-color: ${#eee} !important;
}
.fbNub._50mz .fbNubFlyoutFooter::after {
    background-color: ${rgba(0, 0, 0, .15)} !important;
}
.fbNub._50mz .fbNubFlyoutInner,
._4cd8 ._69pt,
._4mq3 .fbNubFlyout,
._4mq3 .fbNubButton {
    box-shadow: 0 0 0 1px ${rgba(0, 0, 0, .15)} !important;
}
#goodwill_throwback_permalink_header i {
    background-image: url(/rsrc.php/v3/yW/r/1swgd2xJasB.png) !important;
}
:root, .__fb-light-mode {
    --filter-disabled-icon: invert(100%) opacity(30%) !important;
    --filter-placeholder-icon: invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%) !important;
    --filter-primary-icon: invert(100%) !important;
    --filter-secondary-icon: invert(62%) sepia(98%) saturate(12%) hue-rotate(175deg) brightness(90%) contrast(96%) !important;
    --filter-warning-icon: invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%) !important;
    --filter-blue-link-icon: invert(73%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(103.25%) hue-rotate(189deg) brightness(101%) contrast(101%) !important;
    --filter-positive: invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%) !important;
    --filter-negative: invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%) !important;
}
g > rect {
    --darkreader-inline-fill: none !important;
}
mask > rect, mask > circle {
    --darkreader-inline-fill: white !important;
}
div[role=article] div.k4urcfbm[aria-hidden="true"] {
    background-color: rgba(0, 0, 0, 0.25);
    background-blend-mode: color;
    --darkreader-inline-bgcolor: none !important;
}
.ha302278 {
    background-color: var(--fds-white-alpha-40) !important;
}
.r4vyqqch {
    background-color: var(--fds-white-alpha-50) !important;
}
.lyi53s4r {
    background-color: rgba(88,144,255,.9) !important;
}
.sp_mWYnHXJ55SW {
    background-image: url(/rsrc.php/v3/y9/r/yO1o43KF209.png) !important;
}
.q2y6ezfg {
    background-color: rgb(128,128,128) !important;
}
.tdjehn4e, .oo1teu6h {
    background-color: rgba(255, 255, 255, 0.1) !important;
}
.tdjehn4e:hover, .ovq5dppa: hover {
    background-color: rgba(255, 255, 255, 0.2) !important;
}
.k19f6yf2 {
    background-color: var(--press-overlay) !important;
}
.cxbav39q {
    background-color: rbga(0, 0, 0, 0.8) !important;
}
.rnr61an3 {
    background-color: var(--hover-overlay) !important;
}
.qbubdy2e {
    fill: none !important;
}
.s1i5eluu {
    background-color: var(--primary-button-background);
}
.q66pz984 {
    color: var(--accent);
}
.esnais5j, ._8bb_ img, ._8bb_ i {
    filter: none;
}
.sp_Jc8OKpJq5NW {
    background-image: url(/rsrc.php/v3/yV/r/RO526ka7f9m.png) !important;
}
.sp_C8jQ3Z1xUrS {
    background-image: url(/rsrc.php/v3/yC/r/XFTwSywolOp.png) !important;
}
```

**Comment by Myshor** [comment]
Had the same. :)

But checked with pasted from here. Not reproduced.
One thing I was able to see using old design in Firefox:
Main page loading time is slow as f..k. 😛

**Comment by Gusted** [comment]
Well good luck troubleshoot 😛

**Comment by mrturkmen06** [comment]
> @mrturkmen06 Tried to reproduce and I can't :(
> 
> I have 2 questions:
> 
>     1. What system do you use? Windows/Linux?
> 
>     2. Check if you have default config for fixes on facebook. Do you see "!"?
>        ![image](https://user-images.githubusercontent.com/56877029/82490408-7df9d480-9ae3-11ea-9e42-e8bada396c4f.png)
>        If yes then go to Dev tools, reset them and Apply.
>        Then check facebook again.
> 
> 
> I checked this part of Facebook with clean config, then with my all new fixes using Firefox and I can not reproduce it on my Windows 10.


 - Info regarding to my env; 
   -  MacOs Catalina 10.15.4 (19E287)
   - Dark reader: Version 4.9.8 , Last Update: May 16, 2020 
   - Firefox: 76.0.1 (64-bit) MacOS 

 - I have checked it, seems there is no difference between the config which you have posted and the one that I have. 

@Myshor

**Comment by Myshor** [comment]
That reminds me some bug that no-one from devs could not reproduce on their firefox 'cause they had macs and I found it on windows. This won't be easy either for me to check. I don't own anythig with MacOS to check and because of COVID I even won't have possibility to "borrow" for a while MAC from devs to check it there and confirm.

Maybe you can try to make a screenshot from Firefox DevTool after analyzing that broken part.
If it breaks with DR I bet it's some DarkReader inline changes, but hard to check which one on my own.

**Comment by Gusted** [comment]
@alexanderby owns one ^ If you want to annoy him spam him in his DM's :)

**Comment by mrturkmen06** [comment]
I see, I am going to check it and trying to give more information about it. 

@Myshor

**Comment by mrturkmen06** [comment]
I realized something weird, when I do  **ON/OFF** from DarkReader, while I am on facebook page, it works, but if I open facebook page in new tab, if gives back same result invisible names and surnames as I mentioned earlier. 
While checking different things on facebook, I realized that  this part of facebook.com does not work as well  for my situation. See SS. 

<img width="259" alt="Screenshot 2020-05-21 at 00 01 49" src="https://user-images.githubusercontent.com/13614433/82497216-91fb0180-9af6-11ea-809b-77ded494b6b7.png">

But as I mentioned when I make "ON/OFF" without refreshing page, here is the result. 

<img width="251" alt="Screenshot 2020-05-21 at 00 04 58" src="https://user-images.githubusercontent.com/13614433/82497317-b951ce80-9af6-11ea-9a0f-0050cc2e3603.png">

If I refresh the page it becomes invisible again. @Myshor, I hope, these information could be useful somehow.

**Comment by mrturkmen06** [comment]
No problem with version 4.9.9. Thanks a lot Darkreader team !

**Comment by Gusted** [comment]
Closing this as of https://github.com/darkreader/darkreader/issues/2674#issuecomment-639790315

**Comment by Gusted** [comment]
Oh you was faster 😅
