### ISSUE TITLE
[BUG] Some websites are only partly styled or go back to their original style

### ISSUE THREAD

**Issue by Hawpe** [darkreader/darkreader#2549]
**Describe the bug**
Some websites are only partly styled. Some containers will stay in or go back to their original color, either until I toggle the site, or until I change the brightness when toggling doesn't work.

**To Reproduce**
- Go to https://www2.yggtorrent.se/engine/search?name=test&do=search
- Or to https://www2.yggtorrent.se/forum/index.php

**Expected behavior**
Search results should be darkened.
Forum should be darkened.

**Screenshots**
What happens on first load:

![firefox_2020-05-18_22-24-40](https://user-images.githubusercontent.com/26039652/82256639-0008c280-9957-11ea-8d52-0cb6ef7d0ef6.png)

What happens after triggering the "darkening":

![firefox_2020-05-18_22-24-59](https://user-images.githubusercontent.com/26039652/82256666-0dbe4800-9957-11ea-9ed4-49cd5d230284.png)

**System Information:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: v76

**Additional context**
This isn't the only website it happens on, just one I have noticed it on the most because it happens on many other pages.
Another example of a site that gets darkened then goes back to the original style is [http://mobile.free.fr](http://mobile.free.fr) as can be seen [here](https://giant.gfycat.com/DependentAgitatedAquaticleech.webm). This is on a fresh installation of Firefox.

**Comment by Gusted** [comment]
Hi their!

After you reload the page(F5) is it fixed or does it still display white?

**Comment by Hawpe** [comment]
Reloading gives the same results every time, so it displays white. Only toggling or changing brightness, contrast, etc. fixes it for the current page - until the next reload.

**Comment by Gusted** [comment]
Than I have good news, that it already has been fixed in the current commit somewhere :eyes:

To just be sure you can download the current build of the extension

[build-firefox.zip](https://github.com/darkreader/darkreader/files/4652202/build-firefox.zip) Unzip after downloading.

Sideload it trough about:addons -> Extension tab -> Settings Icon -> Debug Addons -> Load temporary addon -> Select the .xpi you have downloaded

**Comment by Hawpe** [comment]
Well, now it seems weirdly inconsistent: https://giant.gfycat.com/DefensiveDistinctDwarfrabbit.webm

**Comment by Gusted** [comment]
That's not the expected behaviour....

**Comment by Gusted** [comment]
Hi @Hawpe could you check with darkreader 4.9.9 if their are still issues with this?

**Comment by Hawpe** [comment]
It does seem fixed, I've tried refreshing the pages mentioned multiple times for a few minutes and it's correctly styled every time. Thank you!

**Comment by Gusted** [comment]
No problems!
