### ISSUE TITLE
Improve background colors gamma

### ISSUE THREAD

**Issue by RaghavRao** [darkreader/darkreader#255]
I have a chrome black theme (matte black on app store), this extension, and windows high contrast black theme applied

I will add more sites and poke around with dev tools but two main issues:

1) Gmail's reply and more options next to each email in a thread are hidden (black text on black background)

2) Github's <code> blocks should be a little gray to stand out but are black like the rest of the page.

**Comment by alexanderby** [comment]
I've just fixed GMail icons. What about a gray color, I think it depends of the gamma of your screen. Try to increase or decrease Contrast filter.

**Comment by alexanderby** [comment]
I think the GMail issue was fixed, so I'm renaming this issue.

**Comment by Gusted** [comment]
Hey @RaghavRao!

The color algorithm changed a lot over the time of 2 years. Mind have a look at this issue and see if it how you wanted?

Regards,
Gusted
