### ISSUE TITLE
API to disable dark reader on your site

### ISSUE THREAD

**Issue by Jonatino** [darkreader/darkreader#2552]
It would be nice to be able to let darkreader know your site already handles dark theme. That way darkreader can whitelist your site. Saves a lot of cpu time on large sites.

**Comment by Gusted** [comment]
Add them to https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config

**Comment by Gusted** [comment]
@Jonatino ^

**Comment by Jonatino** [comment]
I feel like that list is unpractical and will quickly get out of hand with the growing amount of sites supporting dark theme out of the box.

I think adding some sort of known html meta tag that darkreader looks for or even a javascript api to disable it manually is a better solution than hardcoding a list of urls.

**Comment by Gusted** [comment]
Well that would be also unpractical as not all dark sites want to add some meta into their html.

**Comment by Jonatino** [comment]
Less impractical than keeping a list though.

**Comment by Gusted** [comment]
I'm sure if we replace the list and ask all sites to add meta only 5% will do it

**Comment by Jonatino** [comment]
I never suggested replacing the list, I simply want another way to do it rather than rely on a third party project to merge a pull request, wait for them to push their next update, and wait for that update to propagate to all installs of dark reader. Vs just adding a known tag that I know will work right away across any darkreader version that supports it.

**Comment by Gusted** [comment]
Adding this feature to the code base also will be pushed to next update and I'm certain that owner of darkreader will simply close the pull request. We are the first party we determine if the site is actually dark theme to be sure and than just merge it its not an external party does it.

**Comment by Gusted** [comment]
Hi @Jonatino 

I've been rethinking about this, it should be a pretty good idea.
How do you suggest the `tag` to be look be?

Regards,
Gusted

**Comment by Jonatino** [comment]
Eh I was just thinking using a metatag.
```
<meta name="darktheme_supported" content="true">
```

or having some sort of javascript alternative.

**Comment by Gusted** [comment]
I will think about the name.

**Comment by Gusted** [comment]
`<meta name="darkreader" instance="someUIDhere">` 
#2855

**Comment by swrobel** [comment]
@Gusted what you've presented is an invalid meta tag. There is no `instance` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Attributes) ... did you mean `content="UID"`?

**Comment by Gusted** [comment]
> 
> 
> @Gusted what you've presented is an invalid meta tag. There is no `instance` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Attributes) ... did you mean `content="UID"`?

Yep I did mean that.... Seems like I made a typo.

**Comment by odhs** [comment]
I desire so much a meta tag for this!
May be 

`<meta name="color-scheme" content="dark">. `

If your website already in dark mode there is no necessary transformation. Of if the theme-color is a dark color:

`<meta name="theme-color" content="#000000">`

**Comment by Gusted** [comment]
@odhs #3902

**Comment by liqube** [comment]
> `<meta name="color-scheme" content="dark">. `

Bump.

100% and generic enough.
Should be provided by any website that is natively running in dark mode. Would implement into all projects.

Additionally, check if a darkreader JS object exists (if the extension is loaded), if so, call a func like .setDarkSite() or whichever name you find suitable. This way it can be done in a dynamic way.

**Comment by Gusted** [comment]
> Additionally, check if a darkreader JS object exists (if the extension is loaded), if so, call a func like .setDarkSite() or whichever name you find suitable. This way it can be done in a dynamic way.

Sites cannot access extension's content script. 

Dynamic way? Hmm no.
This could imply new security issues by accepting input from any website. At the moment there isn't a good way of secure transmissions from a site to content script without any handshake and even that could be vulnerable. We are working on our site to dynamically detect dark webpages #5719 and otherwise adding a site into the [dark-sites.config](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config) should be good enough.

Regards,
Gusted

**Comment by liqube** [comment]
> Sites cannot access extension's content script.
Ok, now I know that.

> We are working on our site to dynamically detect dark webpages
Nice, that would be the cleanest solution.

**Comment by hadialqattan** [comment]
Hi, If anybody is still interested, I've created `no-darkreader` plugin to accomplish this task elegantly:

REPO: https://github.com/hadialqattan/no-darkreader
NPM: https://www.npmjs.com/package/no-darkreader

**Comment by Algoinde** [comment]
This is a first result in Google and I cannot find any APIs on the website. Was such tag to kill Darkreader added at any point? I would like to disable dark reader on my site, as my users come with bug reports that I have no control over.

**Comment by Gusted** [comment]
@rendomnet This feature is already implemented.

**Comment by Mechite** [comment]
What about a detection for ``color-scheme: dark`` in CSS on any root element? ie, if the ``:root``, ``html``, ``body`` selectors, or any element nested only 1 deeper than body is styled with this, dark reader would be disabled.

**Comment by Gusted** [comment]
Hmm `color-scheme: dark` doesn't necessarily imply that the site has implemented a dark mode(or that the dark mode is actually enabled). Unfortunately sites are "abusing" these kind of features.

**Comment by Mechite** [comment]
> Hmm `color-scheme: dark` doesn't necessarily imply that the site has implemented a dark mode(or that the dark mode is actually enabled). Unfortunately sites are "abusing" these kind of features.

It implies where an element can be rendered but on a root node it makes total sense to set this property to define the active color scheme.
