### ISSUE TITLE
[Feature Request] Stop inverting .leaflet-interactive in dynamic

### ISSUE THREAD

**Issue by austinhuang0131** [darkreader/darkreader#2560]
**Is your feature request related to a problem? Please describe.**
Sorta. Leaflet is the map library => https://leafletjs.com, which usually displays OpenStreetMap. However, since OSM itself is not dark-mode-friendly, it would make sense to not invert any lines drawn on it as well. Example: https://austinhuang.me/ogf-route-relations.html?map=C/15/37.33365/103.45317 (in this case I'm using OpenStreetMap standard layer for a different website; The thin bus lines were supposed to be #1F3D0C but was replaced with an invisible grey-ish color)

**Describe the solution you'd like**
Have an option to disable `--darkreader-inline-stroke`

**Additional context**

**Comment by Gusted** [comment]
```
austinhuang.me

IGNORE INLINE STYLE
.leaflet-zoom-animated g path
```

Refresh the page after pressing apply

**Comment by austinhuang0131** [comment]
Didn't realize `IGNORE INLINE STYLE` is a feature. I would suggest documenting it. But anyways, thanks.

**Comment by Gusted** [comment]
Will make an PR with IGNORE INLINE STYLE but owner of Dark reader said it won't have a real world usage case but I will try to convience! Goodluck on fixing this site!
