### ISSUE TITLE
[BUG] Can't toggle in PDF view

### ISSUE THREAD

**Issue by Avamander** [darkreader/darkreader#2561]
**Describe the bug**
PDFs are always inverted, toggling site override doesn't work

**To Reproduce**
> Open any PDF

Every PDF is inverted on all pages, ignoring rules.
Only disabling the extension reverts the PDF reader.

**Expected behavior**
PDFs aren't inverted if the website itself isn't inverted. Site override can be toggled when viewing a PDF.

**Screenshots**
![inverted PDF reader](https://user-images.githubusercontent.com/5392141/82390962-cc0dca00-9a48-11ea-9306-0f45d1ed35fc.png)

**System Information:**
 - OS: Kubuntu
 - Browser: Chromium
 - Version: 81.0.4044.138 

**Additional context**

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/2455#issuecomment-625208032
