### ISSUE TITLE
[Broken Website] Chrome Web Store

### ISSUE THREAD

**Issue by shruti170901** [darkreader/darkreader#2563]
**Website**
https://chrome.google.com/webstore/

**Expected behavior**
Dark reader should invert colours of the website.

**Actual behavior**
Nothing is observed on toggling the button.

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader chrome extension

**Comment by Gusted** [comment]
We can't inject anything to webstore as well...
![](https://i.imgur.com/Wv0aURZ.png)
