### ISSUE TITLE
[BUG] listed sites are still being darked

### ISSUE THREAD

**Issue by amatosg** [darkreader/darkreader#2576]
**Describe the bug**
I have added a few sites that the dark reader makes them amazingly slow (mainly gmail) to the "please do not change the style in this webpages, pretty please" list. For instance, I have `*.google.com/mail/u/*`, when I entered the domain, it changed to its normal style. When I changed tab forth and back, Gmail was styled again. I tried this with other websites and it keeps happening.

**To Reproduce**
> Go to gmail
> Click on activate dark reader
> Add gmail to the _Not invert listed_
> See the magic and gmail is white again
> Change tabs, wait for a few seconds.
> See the magic go away and gmail is dark again.

**Expected behavior**
Listed websites should retain its original style.

**Screenshots**
Not applicable

**System Information:**
 - OS: macos
 - Browser chrome
 - Version 81.0.4044.138 (Build oficial) (64 bits)

Thank you for this awesome extension

**Comment by Gusted** [comment]
Just use mail.google.com

Using * is not supported yet

**Comment by Gusted** [comment]
Woops wrong button

**Comment by amatosg** [comment]
Thank you!

Even if not using * the websites go back to dark mode :(

As you can see, I have mail listed but is still dark.
![image](https://user-images.githubusercontent.com/42916953/82611576-6fb0c480-9b86-11ea-8c71-f6510b6d710e.png)

**Comment by Gusted** [comment]
Use the site toggle to get the correct site into the site list

**Comment by amatosg** [comment]
I did and the behaviour is the same. I'm even having an issue in which I deactivate dark reader and some websites are still having the dark mode activated, I have to activate and deactivate again to get rid of the dark mode.

**Comment by Gusted** [comment]
Reinstall dark reader  to be sure as hearing that you enabled and disabled and still had dark mode isnt a good thing

**Comment by amatosg** [comment]
I deactivated and activated the extension and now is working properly. I also try to play with macos' dark mode just in case. It looks like _now_ is working. But weird though, right?

**Comment by Gusted** [comment]
Very weird. I know that I sometimes had this but that is only when Im running 20 other applications in the background and my laptop is lagging out.

**Comment by Chnossos** [comment]
Came here thinking I had the same problem. Turns out I had modified the `browser.display.background_color` property from `#FFFFFF` to `#212121` (to have about:blank in new tabs be dark and not white) and it was messing up with a lot of pages when DR was disabled or when the site was in the not inverted list.

**Comment by Gusted** [comment]
Congrats you found the issue.
I will hold it in mind for issues that have similar issue.
