### ISSUE TITLE
How does this compare with Midnight Lizard?

### ISSUE THREAD

**Issue by popey456963** [darkreader/darkreader#2577]
The two most popular options for an extension to make webpages dark are currently [Dark Reader](https://github.com/darkreader/darkreader) and [Midnight Lizard](https://midnight-lizard.org/home).  What are the major differences and which is the best to use?

[Sibling over at Midnight Lizard](https://github.com/Midnight-Lizard/Midnight-Lizard/issues/273)

**Comment by Gusted** [comment]
Well, I have never used Midnight Lizard but I tried it 10 minutes in comparing with Dark reader on some sites I regual use.

First the compare

# Youtube.com
Midnight Lizard
![](https://i.imgur.com/e14bifu.jpg)
Dark reader
![](https://i.imgur.com/J7QZZvG.jpg)

As seeing here we can see the youtube logo in Midnight Lizard being inverted that is unnecarry if you look at Dark reader's one who try to preserve original colors or darken them to blend in with all other darken colors.

# Github.com
Midnight Lizard
![](https://i.imgur.com/qoxyqdd.png)
Dark reader
![](https://i.imgur.com/VFD63lM.png)

Well no words for it. Midnight Lizard use some custom CSS to make some text purple? and don't have everywhere matching background color, where you can see at Dark reader we simply just darken color don't do anything to it and try to preserve the original colors.

# Google.com
Midnight Lizard
![](https://i.imgur.com/xJYVfXw.png)
Dark reader
![](https://i.imgur.com/5miDoCA.png)

Well just some color difference it's what you prefer


I notice with Midnight Lizard that over the whole site is being litteraly darken. What get some colors also being darken like you can see in Google's logo.
Overal It's what you prefer and which extension matched the best with and how the extension style sites. And I see on https://github.com/Midnight-Lizard/Midnight-Lizard 0 PR's open and 9 issues open. That can indicate on a low community and the recen't commits are only by 1 person. For long term? Dark reader. But I'm not a marketing person **Your choice!**

Regards,
Gusted

**Comment by Myshor** [comment]
I used Midnight Lizard for a while and stopped when It totally locked out my browser on dark site and Dark Reader managed to work flawless. :)
