### ISSUE TITLE
[BUG] colors with CSS variables not inverted in Dynamic mode

### ISSUE THREAD

**Issue by hyperfekt** [darkreader/darkreader#2583]
When a color includes a CSS variable, DarkReader in Dynamic mode fails to invert it.

**To Reproduce**
- Set DarkReader to Dynamic Mode
- Go to data:text/html;base64,PHNwYW4gc3R5bGU9Ii0tcmFuZG9tLXZhcmlhYmxlOiAxOyBjb2xvcjogcmdiYSgwLDAsMCx2YXIoLS1yYW5kb20tdmFyaWFibGUpKTsiPlRoaXMgdGV4dCBzaG91bGQgYmUgdmlzaWJsZSE8L3NwYW4+
- (Try to) observe black text

**Expected behavior**
The text is inverted and easily readable on the dark background.

**Screenshots**

**System Information:**
 - OS: NixOS 20.03
 - Browser: Firefox 76
 - Version: 4.9.8

**Comment by alexanderby** [comment]
At the moment Dark Reader doesn't analyze the variables in inline style sheets (`style` attribute) (except `<html>` element).

**Comment by hyperfekt** [comment]
Good to know! The issue should still be valid, the test case just isn't any good then.

**Comment by hyperfekt** [comment]
This seems to be resolved. Thanks a lot @Gusted.
