### ISSUE TITLE
So unusable, but is it updated every now and then?

### ISSUE THREAD

**Issue by xzj8b3** [darkreader/darkreader#2591]
If you update it seriously, okay, otherwise I'll remove it.
Panic services etc. ..Facebook,Istagram doesn't work properly and many others have problems ...on Firefox especially continues to generate only problems.... Really not very usable and it's more the misunderstandings you create that the functionalities perform very well....

On chrome maybe partially better!! But do you update it every now and then?

**Comment by Gusted** [comment]
We doing great improvements but releasing it now will contain bugs. Darkreader v5 is being planned. 4.9.9 will be probably the next release I agree its 3 weeks since our release but we only do it when critical changes and so far their's none yet that need an immediate release.

**Comment by Gusted** [comment]
If you want all the optimization I suggest to build darkreader yourself

**Comment by BenceSzalai** [comment]
This is a joke, right?
Level of entitlement people can exhibit when using free software is mind blowing.

**Comment by Gusted** [comment]
@BenceSzalai Little did you know where thousand of developers deal with everyday 😝 Sometimes I actually think who is the reall boss 😅

**Comment by xzj8b3** [comment]
> We doing great improvements but releasing it now will contain bugs. Darkreader v5 is being planned. 4.9.9 will be probably the next release I agree its 3 weeks since our release but we only do it when critical changes and so far their's none yet that need an immediate release.

It did not want to be a criticism mine is that it gives problems, several delays and hangs with some platforms, I know they are updating graphics too and it is certainly not easy to keep up with them, but often sends Firefox into the ball ... especially with PHP ...

With our forum often goes into crisis, especially with dark theme of the portal if you forget active extension!!

https://www.openresource.it/

**Comment by Gusted** [comment]
> With our forum often goes into crisis, especially with dark theme of the portal if you forget active extension!!
> 
> https://www.openresource.it/

Explain this a little more.

**Comment by xzj8b3** [comment]
If it happens again I'll make some screens or if I succeed in videos, now
has been changed dark theme of that portal and we'll see how it goes or
maybe I had a little too many pages open ... but I do not think so, I often
see is slow FBK access with active extension, ditto our portal ... Istagram
sometimes gives problems ... But I will keep it under observation a little
bit and see!!! cmq I left links to the portal in case you want to check for
yourself given certainly has more skills than I am on the subject without a
doubt!


OpenResource.it <http://openresource.it/>     OpenResource su Flipboard
<https://flip.it/WbNCjH>


Il giorno dom 24 mag 2020 alle ore 16:06 Gusted <notifications@github.com>
ha scritto:

**Comment by xerus2000** [comment]
> With our forum often goes into crisis, especially with dark theme of the portal if you forget active extension!!
> 
> https://www.openresource.it/

I just tried it on your site - apart from the fact that the site itself lagged even without DarkReader and was not properly secured with https, everything worked seamlessly. Turning on DarkReader worked great as always :)

**Comment by Gusted** [comment]
Update will come today and pushed this week to users by your brower's extension/addon store.
