### ISSUE TITLE
[Broken Website] deno.land

### ISSUE THREAD

**Issue by CallumWatkins** [darkreader/darkreader#2596]
**Website**
https://deno.land/

**How to Reproduce**
Visit any page of the site.

**Expected behavior**
Should be dark.

**Actual behavior**
Is not dark, or text is not visible.

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.8

**Comment by Gusted** [comment]
![](https://i.imgur.com/crNJMze.png) 
Need to add support for variables inside colors
