### ISSUE TITLE
[Feature Request] darkreader for surf browser?

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#2600]
**Is your feature request related to a problem? Please describe.**
Thought I would give `surf` browser a try but  can't do that without dark mode and darkreader is the easiest way to achieve that.

**Describe the solution you'd like**
Would be nice if darkreader support `surf` but I'm ok if it's not dues to minimalism of it.

**Additional context**
Nope.

**Comment by Gusted** [comment]
It's very minimalism I don't think it's even have support for extensions.
