### ISSUE TITLE
[Broken Website] Upvote/Downvote/Accept button colours on StackOverflow

### ISSUE THREAD

**Issue by cyqsimon** [darkreader/darkreader#2602]
**Website**
StackOverflow, with site dark mode enabled.

**How to Reproduce**
An example for this is
> 1. Go to StackOverflow and enable both Darkreader and site dark mode.
> 2. Go to a question that you asked (so that you have permissions to accept/unaccept answers)
> 3. The upvote & downvote buttons do not change to orange on pressed.
> 4. The accept button does not change to green on accepted.

**Expected behavior**
Upvote and downvote buttons chnage colour to orange and back to gray when the answer is upvoted/downvoted or un-upvoted/un-downvoted, respectively.
Accept button changes colour to green and back to gray when the answer is accepted or unaccepted, respectively.

**Actual behavior**
All three buttons are gray, regardless of what you do.

**Screenshots**
| Expected | Actual |
| ---------- | ------- |
| ![Screencap-001-20200525-153750](https://user-images.githubusercontent.com/28627918/82790295-68e3c380-9e9e-11ea-91e8-4e35eab7892d.png) | ![Screencap-001-20200525-153738](https://user-images.githubusercontent.com/28627918/82790287-67b29680-9e9e-11ea-83e4-6bc3abf6c270.png) |

**System info:**
 - OS: Windows 10 1909
 - Browser: Chrome 83
 - Darkreader: 4.9.8

**Additional context**
The reason I'm using both StackOverflow's built in dark mode and Darkreader together, is as follows:

1. Using SO's dark mode alone causes text contrast to be too high. I need Darkreader to tune it down.
2. Using Darkreader alone causes some titles and some SVGs to be nearly unreadable against the dark background.

Therefore I enabled SO's built in dark mode to make all the logos and titles look nice, and then use Darkreader to reduce brightness and add sepia, so that the text don't hurt my eyes. Hopefully this use case makes sense.

**Comment by cyqsimon** [comment]
I changed a bit of CSS to get a preliminary fix. Not sure about whether this has other side effects.

Change this
```
.c-pointer {
    color: grey !important;
}
```
to this
```
.c-pointer.c-pointer {
    color: gray;
}
```
The `clicked button` look seems to be styled using `!important` already. So I simply duplicated `.c-pointer` class to hoist specificity, so that it overrides the normal style, but not `!important`.

Please check if this solution has any unintended side-effects.

**Comment by Gusted** [comment]
Does it work with stackoverflow dark mode off? So yes it will require a bit other solution I guess

**Comment by cyqsimon** [comment]
Without my CSS modification, Darkreader has the same problem handling the colours when SO is in light mode. This modification seems to fix the colours as well in light mode.

Fundamentally it comes down to using `!important` too willy-nilly, so I'm pretty sure this preliminary solution works. What I'm not sure about, is whether `!important` was used for some other reason unknown to me. In other words, using my preliminary solution might break something else, somewhere.

**Comment by Gusted** [comment]
Woops....

But its kind of a rule to use !important to override the fix

**Comment by cyqsimon** [comment]
I don't understand.

In SO with DarkReader turned off, `!important` is used to show the buttons in colour when pressed. So the fix simply needs to not override `!important` with yet another `!important` right?

**Comment by Gusted** [comment]
> I don't understand.
> 
> In SO with DarkReader turned off, `!important` is used to show the buttons in colour when pressed. So the fix simply needs to not override `!important` with yet another `!important` right?

Woops never saw the reply, but yes.

**Comment by Gusted** [comment]
Hi @cyqsimon!

This issue should be resolved by https://github.com/darkreader/darkreader/pull/2196

Regards,
Gusted
