### ISSUE TITLE
[Broken Website] eff.org

### ISSUE THREAD

**Issue by B0pol** [darkreader/darkreader#2611]
**Website**
Give the link to the website
https://eff.org
**How to Reproduce**
1. Go to eff.org
2. Look at the logo

**Expected behavior**
The "electronic frontier foundation" part of the logo is white, so that it's readable 
**Actual behavior**
A clear and concise description of what actual happen.
It's dark, and hardly readable
**Screenshots**
![Screenshot_20200525-202211_Firefox_Preview](https://user-images.githubusercontent.com/58657617/82835985-dfe08280-9ec5-11ea-8f89-fca6beb0e4cc.png) ![Screenshot_20200525-202219_Firefox_Preview](https://user-images.githubusercontent.com/58657617/82835987-e2db7300-9ec5-11ea-885f-eccecab25b66.png)

**System info:**
 - OS: android, linux
 - Browser firefox preview, firefox
 - Darkreader Version 4.9.9, 4.9.8

**Additional context**

**Comment by Gusted** [comment]
![](https://i.imgur.com/AJPnG2F.png)
Potential Fix

**Comment by Yash-Singh1** [comment]
Looks like this is fixed:
![Screenshot from 2020-09-25 16-21-55](https://user-images.githubusercontent.com/53054099/94323603-4c8a8d00-ff4b-11ea-83fa-709e6fb5ce4c.png)
The logo is inverted with a white background.

**Comment by Gusted** [comment]
Seems to be fixed.
