### ISSUE TITLE
Not fully working with Office Online

### ISSUE THREAD

**Issue by sirtb** [darkreader/darkreader#2623]
![image](https://user-images.githubusercontent.com/59457756/82966156-23a3bc80-9f98-11ea-859f-f5ed9b39ffe4.png)

Office Online loads slowly and looks horrible with Dark Reader 4.9.9 with Firefox 76.0.1 (64-bit) Win 10. Here is an example of how it is currently.

**Comment by Gusted** [comment]
![](https://i.imgur.com/bHWBRL1.png) Styles are not progressed.

**Comment by alexanderby** [comment]
As a workaround try using Filter mode for Office Online.

**Comment by Gusted** [comment]
Microsoft moves the styles a lot and we simply won't progress that to prevent high CPU usage.

**Comment by Gusted** [comment]
Has been fixed.
