### ISSUE TITLE
[Feature Request] Chrome and darkreader: custom (text) highlight options

### ISSUE THREAD

**Issue by 5georgeK** [darkreader/darkreader#2632]
**Is your feature request related to a problem? Please describe.**
Problem: Bad contrast when highlighting text on dark background with darkreader

![Clipboard01](https://user-images.githubusercontent.com/66057987/83114834-cb6cd780-a0c9-11ea-9783-1011311d3077.jpg)

**Describe the solution you'd like**
Advanced options to manipulate highlight- and text color.

There exists an addon called "Custom Highlight" where you can change highlight and text color, but this doesn't work with darkreader together:
https://chrome.google.com/webstore/detail/custom-highlight/bmhaflbnleckffaacepbbbonfookcedm

![5](https://user-images.githubusercontent.com/66057987/83115356-872e0700-a0ca-11ea-8a4a-bc22c129e822.JPG)
**Additional context**
.

**Comment by Gusted** [comment]
Devtools -> Preview New design
See all options -> Selection

**Comment by 5georgeK** [comment]
> Devtools -> Preview New design
> See all options -> Selection

wow, thank you very much!
