### ISSUE TITLE
[Broken Website] Femto.dev

### ISSUE THREAD

**Issue by popey456963** [darkreader/darkreader#2635]
**Website**
https://femto.dev/

**How to Reproduce**
Visit the site multiple times, observe that sometimes the main accent colour (used for the header, underlines, etc) are sometimes `rgb(140, 58, 0);` and on other refreshes are `rgb(23, 109, 56);`

**Expected behavior**
A continuous browsing experience.

**Actual behavior**
Switching between pages / refreshing changes the colour scheme.

**Screenshots**
![image](https://user-images.githubusercontent.com/1338129/83146125-bd30b280-a0ed-11ea-98a2-898570e4dd57.png)
![image](https://user-images.githubusercontent.com/1338129/83146143-c3bf2a00-a0ed-11ea-9699-78927598a086.png)

**System info:**
 - OS: Windows
 - Browser: Firefox
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
Can not reproduce this but it will be added to the dark config site so that will fix any potential issues.
