### ISSUE TITLE
[BUG] (Waterfox Classic) 4.9.9 makes everything greyscale and removes most images.

### ISSUE THREAD

**Issue by JohnEdwa** [darkreader/darkreader#2647]
**Describe the bug**
Updating from 4.9.8 to 4.9.9 on Waterfox Classic caused every page to become black and white, and most images are simply removed. Waterfox Current on the left, Classic on the right both running 4.9.9 with identical settings.

![currentclassic](https://user-images.githubusercontent.com/5417183/83193502-d3fff500-a13f-11ea-87a7-c5bffa03a56c.PNG)
![currentclassic2](https://user-images.githubusercontent.com/5417183/83193811-54bef100-a140-11ea-8a2b-d0d58752f305.PNG)
![currentclassic23](https://user-images.githubusercontent.com/5417183/83194148-dc0c6480-a140-11ea-8a9e-aae0f29c7a1d.PNG)

**System Information:**
 - OS: Windows 10
 - Browser Waterfox Classic
 - Version 2020-05

**Comment by alexanderby** [comment]
Hi, please, check if there are errors in browser console.

**Comment by JohnEdwa** [comment]
No errors on Google.com or Github.com for example, both show clean consoles. If I enable CSS warnings, they seem to show mostly the same ones for both, so it doesn't at least seem that Classic should be more broken: Google.com search for "Nettimoto" on the [working Current](https://pastebin.com/raw/x64Tigbt) vs [broken Classic.](https://pastebin.com/raw/weMPaSMu)

**Comment by Gusted** [comment]
I recognise the second image for when I tried to maked some changes in the dynamic theme. Seems like waterfox don't support some code?

**Comment by TheRealPSV** [comment]
I'm seeing this issue too with the dynamic theme. One really big example is this page: https://support.google.com/youtube/thread/20280265?hl=en becomes a completely blank dark gray page when using the dynamic or static theme. Filter and Filter+ work totally fine though.

Also using Waterfox Classic 2020.05 on Win10

There are a few console errors but I'm not sure they're related to the DarkReader, as they appear even when it's toggled off:
```
Content Security Policy: Couldn’t parse invalid host 'report-sample'  (unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  (unknown)
Empty string passed to getElementById().  20280265:552:17
uncaught exception: [object Object]  (unknown)
```

**Comment by Gusted** [comment]
Welp that will mostly filling a bug report by them about CORS and how they handle it incorrectly but not sure I will also download waterfox and see the exact problem.

**Comment by Gusted** [comment]
Yep https://github.com/darkreader/darkreader/blob/master/src/utils/array.ts#L2 Sometimes a .length wil return `undefined` I will see If I can fill in a bug report for it or we should make a workaround in our code.

**Comment by TheRealPSV** [comment]
Just for clarification, Waterfox is treating `null` and `undefined` as different values, when TS should treat them as equal?

So a workaround if WF doesn't fix the bug would be something like this?
`return (items as ArrayLike<T>).length != null && (items as ArrayLike<T>).length != undefined;`

**Comment by Gusted** [comment]
I Will see what I can do... I need to hold in mind that it also still need to work with all modern browsers.

**Comment by TheRealPSV** [comment]
@Gusted I tried digging into it myself and I couldn't reproduce the `undefined` bug. That code seemed to work fine, I think it's the generated CSS that's causing problems.

It seems like it might have to do with the fallback theme: when I took out the `body :not(iframe)` generated by https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L169, it reverted to looking a lot like the issue described in #2065.

**Comment by TheRealPSV** [comment]
Side note, I tried reverting to the 4.9.8 release, and cherry-picking your PR #2535, and it worked perfectly in WF Classic.

**Comment by Gusted** [comment]
That's weird I will see what went wrong - with the coee

**Comment by TheRealPSV** [comment]
@Gusted if it helps, I just did some bisecting on the commits, and here's the PR with the change where the gray screen starts happening: #2550

**Comment by TheRealPSV** [comment]
Could it be ShadowRoot https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot ? Since ShadowRoot wasn't implemented at all in Firefox until v59, and Waterfox Classic is a fork of v56, it's possible Waterfox doesn't implement ShadowRoot, and that it's what's causing the problem.

**Comment by Gusted** [comment]
I will see if that is the problem, but we have already a long time a Shadowroot Implementation....

**Comment by TheRealPSV** [comment]
After some more digging, the exact commit from within the PR/merge where DarkReader breaks is this one: https://github.com/darkreader/darkreader/tree/6136c436a07859ebea395672ce9f4b320473bdea

**Comment by TheRealPSV** [comment]
@Gusted changing the line here: https://github.com/darkreader/darkreader/blob/d30b6d53c3f05f7458675bac34b696e7d82afaee/src/inject/dynamic-theme/style-manager.ts#L57
From `} else if (node instanceof Element || node instanceof ShadowRoot || node === document) {`
To `} else if (node as Element || node instanceof ShadowRoot || node === document) {`
Seems to get the extension to work in WF again, but also results in a ton of warnings about DOM Exceptions popping up in the console like below:
```
DOMException [IndexSizeError: "Index or size is negative or greater than the allowed amount"
code: 1
nsresult: 0x80530001
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:1397]  index.js:8:23

DOMException [IndexSizeError: "Index or size is negative or greater than the allowed amount"
code: 1
nsresult: 0x80530001
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:1397]  index.js:8:23

DOMException [IndexSizeError: "Index or size is negative or greater than the allowed amount"
code: 1
nsresult: 0x80530001
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:1397]  index.js:8:23

DOMException [InvalidAccessError: "A parameter or an operation is not supported by the underlying object"
code: 15
nsresult: 0x8053000f
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:2570]  index.js:8:23

DOMException [InvalidAccessError: "A parameter or an operation is not supported by the underlying object"
code: 15
nsresult: 0x8053000f
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:2570]  index.js:8:23

DOMException [InvalidAccessError: "A parameter or an operation is not supported by the underlying object"
code: 15
nsresult: 0x8053000f
location: moz-extension://8d2407ea-ae6b-4e04-9eaf-94e47402a670/inject/index.js:2570]
```

**Comment by Gusted** [comment]
Seems like a lot of code changing has to be made to make this work again 😬

**Comment by TheRealPSV** [comment]
@Gusted 
> Seems like a lot of code changing has to be made to make this work again 😬

Maybe not! Check out my PR here: #2731

I think I figured out the actual bug in WF. For some reason when getting `allStyles` in index.ts, the check for `node === document` fails inside `getManageableStyles` even though the `document` is what's passed in. I figured out how to work around it by passing in `document.documentElement` instead and it works perfectly, and I didn't see a problem in other browsers when I tested it out.

**Comment by TheRealPSV** [comment]
@Gusted #2688 didn't fix the issue, I just tested it. You left out my change, so the check is still failing because the node isn't recognized as the document.

**Comment by Gusted** [comment]
Tested with Firefox v56 it worked didn't tested it with Waterfox. Your change returns a HTMLElement and not a document so the condition will always fail.

**Comment by TheRealPSV** [comment]
It's still not working in Waterfox though. My change worked in both Waterfox and in current versions of Firefox and Chrome. I don't know why passing an HTMLElement works, but it seems to be the only thing that makes it work in Waterfox.

**Comment by Gusted** [comment]
I will check it out.

**Comment by TheRealPSV** [comment]
@Gusted this is super weird, but I think I fixed it without changing much at all, look here: #2738 
Literally all I did was move the `node === document` check to before the `ShadowRoot` check, and it all just works perfectly now, no need to pass HTMLElements or anything weird. It's working in Waterfox with that small change.

**Comment by Gusted** [comment]
Some sites will be broken trough this as they have on `document` manageable styles

**Comment by TheRealPSV** [comment]
@Gusted Ah, I figured it out! Turns out your PR should fix it, but you had a small bug that flipped the Shadow DOM support flag. Take a look at my PR here: #2739
That should fix the issue!
