### ISSUE TITLE
Scrolling lag with Filter mode on Firefox for Android

### ISSUE THREAD

**Issue by serovar** [darkreader/darkreader#2649]
When using Filter (or Filter+) mode on Firefox for Android there is a lot of scrolling lag. I recorded some screencasts to give an idea of what I am talking about, even if it can be seen much more clearly trying it directly (it's evident with every website, I used leganerd.it as an example in the screencasts). In particular, I did a screencast of Filter mode with Firefox (very laggy), of Dynamic mode with Firefox (same scrolling as Firefox without Dark Reader) and of filter mode with Kiwi browser (Chromium-based with extension support, normal scrolling):

[Screencasts on my Dropbox](https://www.dropbox.com/sh/5e14td4mlclgxpr/AACFfgv3IpwXwFn2RRHJ9UdOa?dl=0)

I know that Filter and Filter+ are not the default modes, but they are blazing fast on mobile and do not have the sub-pixel rendering problem of their desktop browser counterparts.

P.S.: Just out of curiosity and not related to this issue, there isn't any way to enable sub-pixel rendering with these modes on desktop, isn't there?

**System Information:**
 - OS: Android 10 on a Google Pixel 2 XL
 - Browser: Firefox for Android
 - Version: In the screencasts I am using the Nightly version, but every version applies.

**Comment by Gusted** [comment]
Filter & Filter+ Relies on GPU and Mobile's ones aren't really made for this tasks.

Sub-Pixel. So far I know not :( Maybe time to open a bug at Chromium & Firefox

**Comment by serovar** [comment]
> Filter & Filter+ Relies on GPU and Mobile's ones aren't really made for this tasks.
> 
Even if the lag appears when the pages are fully loaded, like in my examples? I recorded the screencasts after having loaded and scrolled the websites to have every content loaded, and the lag was still there (it is that that I found strange, I understand that you can have the lag when the page is not fully loaded, but maybe I don't understand something).

Moreover if it were a GPU related problem, the issue should be present also with Chromium-based browsers, but as you can see with Dark Reader in filter mode with Kiwi browser the scrolling is perfect.

> Sub-Pixel. So far I know not :( Maybe time to open a bug at Chromium & Firefox
>

**Comment by Gusted** [comment]
So far I know Filter does everything in 1 thing we don't do anything like dynamic step for step. It could be something browser bug. I will investage the performance later today.

**Comment by serovar** [comment]
Thanks, very gentle of you :)

**Comment by Gusted** [comment]
Only If I don't forget :) Else this weekend for sure.

**Comment by Gusted** [comment]
Well I tried it out and didn't needed a profiler before I realized the problems with android.
Filter/Filter+ relies on GPU and as Android knower, for all 2D Rendering only CPU usage is used. So after allowing my GPU to render 2D Application most performance was back Only some slow loading but that could be my poor phone :).

As explaining it without any screenshot is a bit hard I will link a Guide to the first website I found https://appuals.com/how-to-force-gpu-rendering-on-android/

GPU: Mali-G51

**Comment by Gusted** [comment]
Note that this can decrease Battery over time as GPU is quite heavy on Battery by some phones.

**Comment by serovar** [comment]
Unfortunately the option to force GPU rendering for 2D applications has been removed in Android 10, so I can't test it. That said, if the problem was that, why does it work smoothly in a Chromium-based browser like Kiwi?

**Comment by Gusted** [comment]
I reallly need to stop clicking wrong buttons.

Ehm I'm using EMUI 10(Huawei :/) Based on Android 10 I didn't knew that they removed that function Isn't their something similair.
For Kiwi? I don't know maybe they force GPU in android for rendering It should be something under the hood we don't use seperate instructions for Firefox.

**Comment by serovar** [comment]
I'll ask the Kiwi developer and report back. If this is indeed what's happening I think we can close this issue since there would be nothing to do, unfortunately.

**Comment by Gusted** [comment]
Let's hold this issue open if needed a Firefox bug always can be filled in why Kiwi is fast. :)

**Comment by serovar** [comment]
I contacted the dev via several channels but it is not answering, so I think the issue could be closed, and maybe with Firefox future updates the scrolling will get better. Thanks as always for the support, I'll write if something changes.

**Comment by Gusted** [comment]
That's sucks, we don't do anything with the scoll. We can't change anything in our code.
I'm sorry I can't help any further I hope the dev will respond, you always can try opening a Firefox bug.

Regards,
Gusted
