### ISSUE TITLE
Facebook gets extremely laggy with dark reader on

### ISSUE THREAD

**Issue by Methanol-Ethanolowicz** [darkreader/darkreader#2659]
Recently, Facebook has gotten painfully slow with dark reader on. In the worst cases, there is a long delay (sometimes up to 10 seconds) before the site responds to anything I do and completely freezes in the meantime. Turning DR off fixes the issue almost immediately. I haven't encountered this behavior on any other website. Is anyone else using Chrome having these issues?

**Comment by Gusted** [comment]
Are you having the new Facebook 'layout'?

**Comment by Methanol-Ethanolowicz** [comment]
Nope, I'm still using the old one. I thought about using the built-in dark theme instead, but FB won't let me switch to the new layout for whatever reason...

**Comment by Gusted** [comment]
They release mostly in parts I also don't have it yet. As I don't use Facebook nor a account. So let's do some simple trouble shooting.

Operating System?
Which `Mode`(Dynamic etc.)?

**Comment by LooneytunesH** [comment]
It's definitely the new **Chrome 83** causing the issue. Added security may be a factor. I have had to turn Darkreader off and everything is running ok now. Other Facebook users have the same issue too

**Comment by Gusted** [comment]
Why do you think Chrome 83? And which version of chrome are you runing e.g. Stable, Beta.

**Comment by LooneytunesH** [comment]
> Why do you think Chrome 83? And which version of chrome are you runing e.g. Stable, Beta.

Stable was released last week and I think this as the problem started straight away making Facebook crawl to a stop and freeze in most cases. Felt like I was using the old dial up  internet

**Comment by Gusted** [comment]
1. Do you feel if darkreader is also slow on other websites?
2. Do you use Facebook new design?
3. Which mode do you use? e.g. Dynamic, Filter

As Chrome stable is a majority of our users it could be a bigger problem and should take immediate investigation.

**Comment by Methanol-Ethanolowicz** [comment]
I'm also at the latest stable Chrome build. I was using the dynamic mode. Switching it to filter seems to help a bit, but it still feels sluggish. As I said, I haven't encountered this on any other website (but I also have dark reader off by default and only use it on websites I visit frequently that don't have their own dark mode). 
Also, I have just received a message from my brother, saying that he has the exact same issues.

**Comment by Gusted** [comment]
Is it still laggy with darkreader off?

**Comment by Dohmanlechx** [comment]
> Is it still laggy with darkreader off?

No. I have to disable it for Facebook which is a paaaain.

**Comment by Gusted** [comment]
Can you share load time with Darkeader On and Darkreader Off
I will also try to check for it.

**Comment by Dohmanlechx** [comment]
> Can you share load time with Darkeader On and Darkreader Off
> I will also try to check for it.

I don't know how to, but Chrome version is 83.0.4103.61 and according to Chrome Web Store, the latest version of Dark Reader (4.9.9) was released on May 25th. I would believe those issues started to occur around that time. Maybe that version caused this? If I knew how to downgrade and try, I'd happily.

**Comment by Gusted** [comment]
Hmm 4.9.9 was exactly about performance etc.

**Comment by Lorixis** [comment]
I would like to add on that issue. I have been noticing the exact same slowdowns for about a week now (Chrome, Win10, old Facebook design, etc). If that can help, I realised my CPU usage was getting comically high when browsing FB with the extension turned on (30-40% usage compared to 5-10% when the extension is off on a 8th gen Core i5). I also have that issue on two different computers.

**Comment by Gusted** [comment]
I'm really scratching my head I will go active my Facebook account and run a profiler on it and see what my results are...

**Comment by LooneytunesH** [comment]
I'm finding that I have to use "filter" and not "dynamic" which is
something I shouldn't have to do as it makes some things hard to see and my
Facebook reactions all have brown faces :-O

**Comment by GEbb4** [comment]
+1 for this, I'm having the same issue. 
Chrome version 83.0.4103.61
Dark Reader version ? (the latest one I think, but I can't see an obvious version number)

Steps to reproduce:
1. Open facebook.com, with Dark Reader set to "Dynamic" theme engine.
2. Scroll past a few posts.
3. Click on an image to open it - the process will lag for of the order 10 seconds.
4. Close the image, this too will lag.
5. Turn off Dark Reader and repeat - it will respond near instantly.

I did try it with the Chrome profiler to get some idea what was going on, but I'm not a web developer so I was struggling to understand what I was reading. It looks like it's getting caught up in swapping the CSS entries, whilst in function "RunMicrotasks"? Not sure if that's meaningful.

**Comment by Gusted** [comment]
If you all could post your OS and current chrome version I can have a better understanding of this issue.

**Comment by GEbb4** [comment]
Just added my OS

**Comment by Gusted** [comment]
Seems like you all are using v83 that could cause this issue. 
2 More question to understand this better.
1. Do you use old or new design?
2. If using new design do you have facebook's native dark mode enabled?

**Comment by Lorixis** [comment]
I have this issue with the old design, my account still doesn't have access to the new one.
I tested the new design on a throwaway account, and there aren't any noticeable slowdowns with the extension enabled (with or without the native dark mode). CPU usage is ~10% higher with the extension enabled, but scrolling and navigation between pages seems smooth.

**Comment by Myshor** [comment]
I can confirm that old design started to work slow as snail...
First tought: It could be related to many fixes included for new design in dynamic-theme-fixes.config 
I removed all fixes related to new design and checked old style... still slow.
Need more investigation if it's browser or our extension related.

And yes - with extension disabled it loads faster - that I can confirm.

**Comment by LooneytunesH** [comment]
I still strongly believe it is because of the Chrome update with Darkreader
as the lagging and freezing were instant. I'm still using the old FB and my
OS is Windows 10 version 2004 OS build 19401.264

**Comment by Gusted** [comment]
I'm going to get a v83 version and see what Chrome is doing I saw a lot of Chrome v83 updates and news. They did big things with skipping v82(For obvious health reasons)

**Comment by privacyguy123** [comment]
I notice page load times on FB insane on Dynamic mode with FB on new layout with their built in Dark Mode off.

**Comment by Gusted** [comment]
Use Static of Filter for this. New layout on itself(without dark reader) Is know to have some good time.

**Comment by isurugiu** [comment]
Not only FB. For a couple of months I have experienced really slow loading times both on Firefox and Chrome. I have also noticed that if Dynamic is on and if I'm dealing with a site which dynamically generates content like FB, Flashscore.com even Gmail (so practically a lot of JS) the loading time increases dramatically and also that tab will be slow.

If it helps I can say that I am using at any given time 2 Firefox browser instances and one Chrome. Each instance pins around 10 tabs and I have 10-15 others open in each instance. With DM on using the Dynamic setting I'm looking at around 10seconds loading time on FB and Gmail. With static or DarkMode off page load is under 2 seconds.

**Comment by Gusted** [comment]
> any given time 2 Firefox browser instances and one Chrome. Each instance pins around 10 tabs and I have 10-15 others open in each instance.

This litterly stress testing your hardware.
But as we need to observe style changes we have a MutationObserver in every tab. It shouldn't do much harm unless if the browser is now lagging the tab. I can't so much about Gmail and Facebook tho as from wha to see their doing some inefficient things of style and Dom placement they both quite heavy site :/

**Comment by isurugiu** [comment]
> 
> 
> > any given time 2 Firefox browser instances and one Chrome. Each instance pins around 10 tabs and I have 10-15 others open in each instance.
> 
> This litterly stress testing your hardware.
> But as we need to observe style changes we have a MutationObserver in every tab. It shouldn't do much harm unless if the browser is now lagging the tab. I can't so much about Gmail and Facebook tho as from wha to see their doing some inefficient things of style and Dom placement they both quite heavy site :/

@Gusted
Yeah I thought this issue mostly impacts websites that are mutilating DOM in the background.

**Comment by privacyguy123** [comment]
Strangely I also get this lag especially in a group chat (???) - lag goes away when DR is off. I'm using Dynamic mode.

**Comment by alexanderby** [comment]
Should work well now.
