### ISSUE TITLE
[Enhancement] Cloudflare DDoS Protection

### ISSUE THREAD

**Issue by sprinkledcheese** [darkreader/darkreader#2661]
Way to check weather a site uses cloudflare ddos protection. This will help in darkening only that ddos page while excluding the main site if it already dark.

**Comment by Gusted** [comment]
Not usable in current codebase of dark sites usage. Maybe Cloudflare could support custom CSS to sites can style them who support dark mode.

**Comment by sprinkledcheese** [comment]
Yea, hope so.
