### ISSUE TITLE
[Broken Website] Wikipedia SVG

### ISSUE THREAD

**Issue by Inspirateur** [darkreader/darkreader#2666]
**Website**
[https://en.wikipedia.org/wiki/Shortest_path_problem](https://en.wikipedia.org/wiki/Shortest_path_problem)
or any math related wiki

**How to Reproduce**
find any math svg on wikipedia

**Expected behavior**
text should be white

**Actual behavior**
it's dark instead, also when I disable dark reader the math svg turns white (on white background) so I can't read them, this stays even with a CTRL+F5 reload.

**Screenshots**
![image](https://user-images.githubusercontent.com/22746898/83303194-9f854b00-a1ca-11ea-8fa3-e9f42a3c21c9.png)
![image](https://user-images.githubusercontent.com/22746898/83303358-ec692180-a1ca-11ea-85d9-37b88003b082.png)

**System info:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Darkreader Version: 4.9.9

**Additional context**
aside from that thanks for this wonderful extension :heart:

**Comment by Gusted** [comment]
![](https://i.imgur.com/reXtP9Q.png) Chromium-based browser.

**Comment by Gusted** [comment]
Do you have ![](https://i.imgur.com/8gsqSu5.png) ?

**Comment by Gusted** [comment]
@Inspirateur ^

**Comment by Gusted** [comment]
Fixed.
