### ISSUE TITLE
[Broken Website] [Filter+] github.com

### ISSUE THREAD

**Issue by B0pol** [darkreader/darkreader#2667]
**Website**
https://github.com
**How to Reproduce**
Open github and set filter+ mode
**Expected behavior**
I can see GitHub
**Actual behavior**
Black screen
**Screenshots**
![image](https://user-images.githubusercontent.com/58657617/83312436-915b1d00-a212-11ea-86f0-446b340b5d89.png)

**System info:**
 - OS: Fedora 32, android 9
 - Browser: Firefox 76, Firefox preview 5.0
 - Darkreader Version: 4.9.9

**Additional context**

**Comment by Gusted** [comment]
This a long issue with Firefox and Filter(+)
