### ISSUE TITLE
[Broken Website] lkml.org is blindingly white

### ISSUE THREAD

**Issue by roblabla** [darkreader/darkreader#2668]
**Website**
Give the link to the website
https://lkml.org/lkml/2020/5/29/1038

**How to Reproduce**
An example for this is
> 1. Go to https://lkml.org/lkml/2020/5/29/1038 in dynamic mode
> 2. Get blinded by how bright everything looks

**Expected behavior**
I expect the website to be significantly darker. Currently, the text is white on almost white, which is borderline unreadable.

**Screenshots**
![image](https://user-images.githubusercontent.com/1069318/83313057-ea2bb500-a214-11ea-8172-b8a273f435a8.png)

**System info:**
 - OS: Windows
 - Browser: Firefox
 - Darkreader Version 4.9.9

**Comment by Gusted** [comment]
Not modern website so was expected....
But after some CSS fixes 
![](https://i.imgur.com/4KlZmGG.png)

BTW great to hear that Linus Torvalds is doing fine.
