### ISSUE TITLE
[Broken Website]  www.apimatic.io

### ISSUE THREAD

**Issue by mrturkmen06** [darkreader/darkreader#2674]
**Website**
https://www.apimatic.io/

**How to Reproduce**
An example for this is
> 1. Go to https://www.apimatic.io/ site

**Expected behavior**
Should convert into dark mode. 

**Actual behavior**
Nothing is happening. 

**Screenshots**

<img width="1678" alt="Screenshot 2020-05-31 at 02 18 39" src="https://user-images.githubusercontent.com/13614433/83340790-0eef5d80-a2e5-11ea-999e-264db92229c4.png">

Just to mention, re-enabling and refreshing the page did not work as well.

**Comment by Gusted** [comment]
![](
![image](https://user-images.githubusercontent.com/25481501/83451601-89d88580-a457-11ea-9a5f-568e2e72dd11.png)) Works for me.... 
Are their any errors in console?
Which OS do you use?
Which browser do you use?

**Comment by Gusted** [comment]
@mrturkmen06 ^

**Comment by mrturkmen06** [comment]
No error on console.
 ****** 
MacOs Catalina 10.15.4 (19E287)
Dark reader: Version 4.9.8 , Last Update: May 16, 2020
Firefox: 77.0.1 (64-bit) MacOS
@Gusted

**Comment by Gusted** [comment]
What if you disable and than enable the site?

**Comment by mrturkmen06** [comment]
Nothing happens.

**Comment by mrturkmen06** [comment]
It just make this part dark, 


<img width="1633" alt="Screenshot 2020-06-05 at 21 31 22" src="https://user-images.githubusercontent.com/13614433/83910844-e8fa0b00-a773-11ea-9f8c-800e3bdd536b.png">

**Comment by Gusted** [comment]
If you switch to FIlter Or Static?

**Comment by Gusted** [comment]
![](https://i.imgur.com/jmlUbwY.png) Even on Firefox it works for me.

**Comment by mrturkmen06** [comment]
<img width="1611" alt="Screenshot 2020-06-05 at 21 32 51" src="https://user-images.githubusercontent.com/13614433/83910967-1f378a80-a774-11ea-8f88-3a0369764ebd.png">


When I do static, it works like this, however it swaps some icons.

**Comment by Gusted** [comment]
Try to reinstall the add-on maybe Dark Reader is having a bad day.

**Comment by mrturkmen06** [comment]
Nope, i have tried it several times and this issue has some common parts with #2547

**Comment by mrturkmen06** [comment]
Thank you very much for your responses, by the way.

**Comment by Gusted** [comment]
Define `Common parts`

**Comment by mrturkmen06** [comment]
I mean, it has some similar parts, like when I try to do dark mode in facebook.com, I am unable to see some parts defined in issue #2547 , and it is somehow valid for apimatic.io, it turns some parts into dark but not all properly. Although seems the extension is working for everyone except me, why I did not get it although I tried to, no idea. I have checked all extensions that I am using and disable them for prevent any unseen problems related to other extensions' effects i to darkreader extension. However, nothing fixed that issue, seems it will be using darkreader for some websites.

**Comment by Gusted** [comment]
Hmm

**Comment by Gusted** [comment]
Okay this mostly determines the problem.
I hope you know how to create a new Firefox Profile(Alongside your current one)
And download Darkreader and test on the same site. It could be that something in your Profile Settings is modified that caused this.

**Comment by mrturkmen06** [comment]
I am going to try ...

**Comment by mrturkmen06** [comment]
Nothing is changed :(

**Comment by Gusted** [comment]
`Version 4.9.8` Can you check this again? The latest should be 4.9.9

**Comment by mrturkmen06** [comment]
oh nice, I have just updated and it started to work both on facebook and this website, I think, it is ok to close the issue. 

Thank you very much @Gusted .

**Comment by Gusted** [comment]
No problems! Have a nice weekend.

**Comment by mrturkmen06** [comment]
You too !
