### ISSUE TITLE
[BUG] Extensions 4.9.9 crashes on Firefox/Waterfox 55.

### ISSUE THREAD

**Issue by SylwesterZarebski** [darkreader/darkreader#2678]
**Describe the bug**
On Firefox/Waterfox 55 extension crashes after update to 4.9.9 (despite addon compatiblity set to Firefox 54):
```
SyntaxError: missing ( before catch  index.js:1853:14
```

**To Reproduce**
> Install Firefox or Waterfox 55
> Install Dark Reader 4.9.9
> Click on icon, there is only `Loading, please wait`.
> See above error in browser console.

**Expected behavior**
Dark Reader working.

**System Information:**
 - OS: Windows
 - Browser: Firefox and Waterfox
 - Version: 55

Downgrading to 4.9.8 works.
~~Apparently old Firefox/Waterfox do not accept catch without exception definition.~~
Please fix current bug (maybe there are more) and then maybe set compatibility to newer browsers to prevent older ones of updating.

**Comment by Gusted** [comment]
Waterfox classic or current?

**Comment by SylwesterZarebski** [comment]
Neither, 55 is version before Classic naming, but you can call it classic.

**Comment by Gusted** [comment]
Hmm classic was based on old codebase I will see which code causing it. For now but unfortunately stay on 4.9.8.

**Comment by SylwesterZarebski** [comment]
Thanks, 4.9.8 is working good :-).

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L412 Broken code will look into tomorrow.

**Comment by Gusted** [comment]
I found 2 broken code, so let me explain simply what the bug was.


BEFORE
```
try {
        parse(props.value);
        isPickerVisible = true;
    } catch {
        isPickerVisible = false;
    }
```

AFTER
```
try {
        parse(props.value);
        isPickerVisible = true;
    } catch (err) {
        isPickerVisible = false;
    }
```

Back in the day you had to specify a argument for the error.
Will make patch for it.

**Comment by SylwesterZarebski** [comment]
Thanks a lot for fix and for a great work :-)

**Comment by Gusted** [comment]
I will close this issue as This is a issue as same from #2647 So we won't track multiple issues about the same underlaying bug. You can comment any further info their.
