### ISSUE TITLE
[Feature Request] Implement Automatic Switch to Dark/Light Mode at Sunrise/Sunset

### ISSUE THREAD

**Issue by harshaface** [darkreader/darkreader#2690]
**Is your feature request related to a problem? Please describe.**
It would be convenient if I didn't have to manually click On/Off every time at sunrise/sunset to change between light or dark modes.

**Describe the solution you'd like**
I'd like an option in the settings which automatically takes care of this hassle so that I can only be worried about which website the dark reader filters don't do a good enough job on and not having to open the extension everytime to change themes.

**Comment by Gusted** [comment]
![](https://i.imgur.com/UqVExIe.png) Notice the 3 dots

And than fill here in the location in
![image](https://user-images.githubusercontent.com/25481501/83515798-3d805a80-a4d6-11ea-8586-129f73e113b2.png)

**Comment by Th3Whit3Wolf** [comment]
This should be made more visible or have a button. I was about to file the same issue.

**Comment by Gusted** [comment]
New UI has a better improvement to make if more visible
Dev tools - Preview new Design
Settings - Automation
