### ISSUE TITLE
Toggle shortcut opens ad popup/window?

### ISSUE THREAD

**Issue by jbjhjm** [darkreader/darkreader#2694]
Hi, for some time using the shortcut alt shift D to toggle dark mode opens a window showing ads.
Is this known behavior or did I catch some malware? Please confirm, thank you :)

**Comment by Gusted** [comment]
**MALWARE** https://darkreader.org/blog/attention/

**Comment by Gusted** [comment]
Remove your current one and replace it with the original.
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

If you need to install it again you can go to https://darkreader.org and click on the browser you are currently using.

**Comment by jbjhjm** [comment]
Thanks @Gusted . I was truely sure I did install it via official channel... but a reinstall fixed it. Thank you!

**Comment by AKasera** [comment]
Yeah I installed via the official channel too and I checked the ID's on the one I have currently and the one you guys said it should be and they were the same. I think there is a bug somwhere because I have experienced this issue as well
