### ISSUE TITLE
[BUG] Dark Reader broken when network.file.disable_unc_paths is set to true in Firefox

### ISSUE THREAD

**Issue by unab0mb** [darkreader/darkreader#2700]
**Describe the bug**
When turning on the setting "network.file.disable_unc_paths" to "true" in Firefox, Dark Reader is stuck on "Loading... Please Wait."

**To Reproduce**
I have installed a fresh copy of Firefox 77.0 64-bit and copied a user.js file containing the above referenced setting over to the Firefox profile that I'm using. When I start Firefox, Dark Reader is broken. If I delete the profile and start with another fresh one again, Dark Reader works until I try to apply this setting again. 

**Expected behavior**
Dark Reader should be showing the main UI instead of a blank window with "Loading...Please wait." that never goes away.

**System Information:**
 - OS: Windows 10 May 2020 Update (Version 2004) x64
 - Browser: Firefox 77.0 x64
 - Dark Reader: 4.9.9

**Additional context**

**Comment by Gusted** [comment]
Can you try update to `v77.01` I saw some noted that they had some updates about config etc.

**Comment by unab0mb** [comment]
> 
> 
> Can you try update to `v77.01` I saw some noted that they had some updates about config etc.
I tried with 77.01 and I have the same issue.

**Comment by Gusted** [comment]
Seems to be fixed in 82.0.3
