### ISSUE TITLE
[BUG]Keyboard positions doesn't show up in Google Slides

### ISSUE THREAD

**Issue by dragonBall561** [darkreader/darkreader#2707]
**Describe the bug**
When I use Google Slides, the white typing bar turns the same color as the background of the Slideshow, making it impossible to see. I am using Dynamic mode, always did, and for some reason, this didn't happen in previous versions. I have attached screenshots to clarify

**To Reproduce**
>Go to [Google Slides](https://slides.google.com) and open a new slideshow
>Turn on Darkreader in Dynamic Mode

**Expected behavior**
I would like the white typing bar to become white instead of staying black

**Screenshots**
![old](https://user-images.githubusercontent.com/61358474/83642770-40825600-a57d-11ea-9cc2-2d6aab0ca337.png)
![new](https://user-images.githubusercontent.com/61358474/83642725-35c7c100-a57d-11ea-81c7-2603bb678e52.png)

**System Information:**
 - OS: [Linux Mint 19.3 Cinnimon]
 - Browser [Chromium]
 - Version [81(Can't update for some reason)]

**Additional context**
Again, this used to work perfectly in previous versions.

**Comment by dragonBall561** [comment]
If you Zoom in on the second screenshots you might just barely see the black line.

**Comment by Myshor** [comment]
Fix done will be included in next release ;)
![image](https://user-images.githubusercontent.com/56877029/83672124-127d3000-a5d6-11ea-99b0-b19f26885bdf.png)

**Comment by dragonBall561** [comment]
Okay, thanks
