### ISSUE TITLE
[Feature Request] Set dynamically generated theme as basis for static theme

### ISSUE THREAD

**Issue by lostgeek** [darkreader/darkreader#2708]
**Is your feature request related to a problem? Please describe.**
There are some sites, where only small adjustments to the dynamically generated theme would be neccessary.

**Describe the solution you'd like**
Add an option to "export" the dynamically generated theme as a static theme for subsequent manual tweaking.

**Comment by Gusted** [comment]
Inline styles won't work. 
`<p style="color: red">Hello I will be red and not modified</p>` < Than that kind of elements won't be styled trough export.

**Comment by Gusted** [comment]
Hi @lostgeek!

We've added a option to export the dynamic theme [please check here how](https://darkreader.org/blog/v4-9-16/).
However making the integration to set it as a basis would be complicated as each subdomain/site have another Generated CSS etc.

Regards,
Gusted
