### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by unbeatable-101** [darkreader/darkreader#2710]
**Website**
https://support.mozilla.org/en-US/kb/accessibility-services

**How to Reproduce**
Steps to reproduce the behaviour:
An example for this is
> 1. Go to https://support.mozilla.org/en-US/kb/accessibility-services
> 2. The site is white

**Expected behaviour**
The site is dark

**Actual behaviour**
The site stays white with any filter

**Screenshots**
![Screen Shot 2020-06-03 at 12 08 05 PM](https://user-images.githubusercontent.com/58151048/83660540-f6a46a80-a592-11ea-830b-1e34a5827720.png)
![Screen Shot 2020-06-03 at 12 08 10 PM](https://user-images.githubusercontent.com/58151048/83660551-f906c480-a592-11ea-8e5a-ffad47b281f4.png)
![Screen Shot 2020-06-03 at 12 08 13 PM](https://user-images.githubusercontent.com/58151048/83660554-f99f5b00-a592-11ea-80f4-bfc176349296.png)
![Screen Shot 2020-06-03 at 12 08 17 PM](https://user-images.githubusercontent.com/58151048/83660556-fa37f180-a592-11ea-8438-3a35b4c10a29.png)

**System info:**
 - OS: MacOS
 - Browser: Firefox 77
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
It could be that's it's from now on a protected page...

**Comment by sprinkledcheese** [comment]
![firefox_yJ3FtSMc3X](https://user-images.githubusercontent.com/65959962/83677507-ea072d00-a5f9-11ea-93f2-0e2999c2b0d7.png)
Yes, close this.
