### ISSUE TITLE
[Broken Website] wiki.mozilla.org

### ISSUE THREAD

**Issue by sprinkledcheese** [darkreader/darkreader#2716]
White background image
![chrome_T2r0HKd08o](https://user-images.githubusercontent.com/65959962/83677354-aad8dc00-a5f9-11ea-8e1d-3a7bb64e6bf1.png)

**Comment by Gusted** [comment]
We bassicly do with this kind of background-image we do `body { background-image: none !important; }` You can open a PR for it.

**Comment by sprinkledcheese** [comment]
Done.
