### ISSUE TITLE
[Broken Website] w.atwiki.jp/guide/  (a Japanese site)

### ISSUE THREAD

**Issue by cyatarow** [darkreader/darkreader#2717]
**Website**
https://w.atwiki.jp/guide/

**How to Reproduce**
1. Go to https://w.atwiki.jp/guide/
2. See that the background is not black but white

**Expected behavior**
The background color will turn black.

**Actual behavior**
The background color does not turn black, although the text color turns white.

**Screenshots**
![20200604a](https://user-images.githubusercontent.com/26016252/83711190-857db980-a65d-11ea-94d8-113bbe7f9aa2.png)

**System info:**
 - OS: Windows 10 1909 x64
 - Browser: Firefox 76.0.1
 - Darkreader Version 4.9.9

**Comment by Gusted** [comment]
Those not styled elements don't have a `color` property.

**Comment by cyatarow** [comment]
So, can it be fixed?

**Comment by Gusted** [comment]
Uh not really with out current codebase.

**Comment by mezeraj** [comment]
I fixed it, submitting a pull request momentarily

**Comment by cyatarow** [comment]
![image](https://user-images.githubusercontent.com/26016252/113419045-9de76d80-9401-11eb-8044-f30f4fb3fef3.png)

It worked fine. (v4.9.30)
Thank you.
