### ISSUE TITLE
[BUG] “Warning: Unresponsive script”

### ISSUE THREAD

**Issue by irodrigomiele** [darkreader/darkreader#2718]
**Describe the bug**
In Android 8.0, when I'm using Firefox 68.8.1, with Dark Reader extension installed, I always got a message "Warning: Unresponsive add-on script", and even I choose to resume, I get the same message again and again, no matter what I do. 

**To Reproduce**
> Go to Some sites in Firefox
> Click on Nowhere
> Scroll down to Nowhere
> See error It simply popup when I'm accessing some sitea

**Expected behavior**
I expect not to be warned anymore about Dark Reader extension issues inside Firefox. 

**Screenshots**
![Screenshot_20200604-044659_Firefox](https://user-images.githubusercontent.com/66409452/83732351-4e3de700-a622-11ea-8231-7da9acfdc630.jpg)

![20200604_142903](https://user-images.githubusercontent.com/66409452/83791776-93890580-a670-11ea-8902-73fbd4af7e17.jpg)

**System Information:**
 - OS: Android 8.0 Oreo
 - Browser: Firefox
 - Version 68.8.1

**Additional context**
I observed that it happens with  other dark mode extensions.

**Comment by Gusted** [comment]
1. Try to update your browser? If that is possible
2. Android Oreo it was released in August 2017, that's quite old system.

You can try to use Static or Filter mode. Maybe your system can't handle all the code for dynamic.
