### ISSUE TITLE
[Broken Website] songsear.ch doesn't darken on page load?

### ISSUE THREAD

**Issue by Committing** [darkreader/darkreader#2729]
songsear.ch

**How to Reproduce**
An example for this is
> 1. Go to the website
> 2. No dark backgrounds, fully white.
> 3. Enable and then disable the darkness and it works again.

This is the first website I actively go to which has had this problem for me.

**Expected behavior**
Darkness to be there on pageload. 

**Actual behavior**
No dark background on pageload.

![Image of Yaktocat](https://i.gyazo.com/ebf586c72198df6f3340046f1fd95b7a.gif)

**System info:**
 - OS: W10
 - Browser Chrome

**Comment by Gusted** [comment]
They inject their CSS but it's not showed up in the DOM. 
We can't modify CSS that don't show anywhere.

**Comment by peterbe** [comment]
> They inject their CSS but it's not showed up in the DOM.
> We can't modify CSS that don't show anywhere.

That’s my site. It uses a rather common technique for making the initial HTML include only the critical CSS all inlined, and then the full external .css files are loaded after onload. 
Same technique is used on https://www.peterbe.com

I’m not sure how I can help. But the CSSOM is there. It’s just lazy loaded.

**Comment by Gusted** [comment]
https://peterbe.com is showing up right for me on page load with Dark Reader.

**Comment by Gusted** [comment]
nvm Opened them first in a new tab before visiting that worked?

**Comment by Gusted** [comment]
Can I ask how the bootstrap.css is loaded? We only darken things from .css that show up in the DOM as I thought that was the only way besides adoptedStyleSheets.

**Comment by Committing** [comment]
Thanks so much @peterbe for responding to my email 😀 In terms of your two websites under DarkReader for me:

**Peterbe.com** - loads correctly with a dark theme for me no matter how many times I refresh.

**SongSear.ch** - Randomly has white or dark theme, doesn't stay consistent for me when refreshing.

@Gusted It seems as though the plugin _sometimes_ gets it right (?) Do you get the same thing?

**Comment by Gusted** [comment]
I get the same thing. It's very weird.
Like he said it's lazyloaded so later, If dark reader is `slow` It will darken the page as the CSS is than already lazyloaded. If dark reader is `fast` It will not see the CSS and will not darken that CSS

**Comment by F8ER** [comment]
Worked here. Has anything changed? Just opened the website and pressed shortcut for Dark Reader.

**Comment by Committing** [comment]
> Oh, you are about `songsear.ch` ... yes, this issue is quite common here. I've just created some script which reloads Dark Reader's styles after 1-2 seconds for any website to ensure they set(aka fast workaround).

May you share a Gist?

**Comment by Gusted** [comment]
@F8ER Not anymore #2065 most are fixed.

**Comment by prg318** [comment]
This issue seems to have resurfaced in a recent update.

Pages on the archwki are no longer readable (black text on black background) at first.  The darkreader extension must be reloaded for it to render correctly (ie: https://wiki.archlinux.org/index.php/List_of_applications#Terminal_emulators)

**Comment by Gusted** [comment]
> Pages on the archwki are no longer readable (black text on black background) at first. The darkreader extension must be reloaded for it to render correctly (ie: https://wiki.archlinux.org/index.php/List_of_applications#Terminal_emulators)

First wrong issue.
Second #3547

**Comment by prg318** [comment]
Passive aggressiveness noted :)  I hope to see the fix included in a release in the future.  Thanks!

**Comment by Gusted** [comment]
> Passive aggressiveness noted :)

No I prefer to write each time when not starting a new issue

```
Hi @prg318!

I think you are commenting on the wrong issue. 
I think you are looking for #3547 which goes about this behavior.

```
Not everyone is 24/7 in a good mood to type a whole essay.

**Comment by F8ER** [comment]
> Not everyone is 24/7 in a good mood to type a whole essay.

Oh, dear @Gusted. No worries ... your project is magnificent. I might literally can’t thank you enough, but please ...  I truly appreciate these efforts and commitments to this project's success. Thank you for taking time out of your personal time to achieve such, really ...

**Comment by Gusted** [comment]
> your project is magnificent.

It's actually @alexanderby, I'm just the main contributor handling the issues and adding features(Even Alexander always catch out the bugs and possible errors etc. etc.)

 

> I might literally can’t thank you enough, but please ... I truly appreciate these efforts and commitments to this project's success. Thank you for taking time out of your personal time to achieve such, really ... 🌟

No problems! Every day dark reader will become better and better.

**Comment by prg318** [comment]
Just wanted to also shout out @Gusted  and @alexanderby - I really appreciate the continued effort and work into this great plugin

**Comment by F8ER** [comment]
> It's actually @alexanderby,

Oh, understood. Then, dear @alexanderby ... I personally, ... very appreciate your effort ... really ... 💖 ...

> I'm just the main contributor handling the issues and adding features

I wouldn't used the word "just" there, though. That's the main hardness of every project ...

---

Please, dear @Gusted and @alexanderby, I hope you have a pleasant time out there, especially these quite hard times ...

**Comment by Committing** [comment]
Agreed, great project!

Not to be a drag but songsear.ch is still white for me everyday 😜

**Comment by Gusted** [comment]
> I wouldn't used the word "just" there, though. That's the main hardness of every project ...

Oh please, I try to not get all the attention to my head. I'm 1 of the [many contributers](https://github.com/darkreader/darkreader/graphs/contributors) but I give my dedication every day to this project. As for a little fun fact. Gusted isn't my real name, but a nickname. I don't need to get real world attention(LMAO 2M users never going to happen) :P. Just like my profile picture. Tries to stay as anonymous as possible.



> I hope you have a pleasant time out there, especially these quite hard times ...

This one is for Alexander. I'm doing fine, this is basically my job spend a lot of good and fun time into this while this hard times(Thanks for @alexanderby for the opportunity and @FranklinYu for opening issue #2281 <3 Will never forget that)




> Not to be a drag but songsear.ch is still white for me everyday 😜

I will have another look over a couple of minutes as soon I'm ready tomorrow for my first school day again this school year.

**Comment by Gusted** [comment]
> Not to be a drag but songsear.ch is still white for me everyday 😜

#3665 Hopefully not for long anymore.

**Comment by Committing** [comment]
So much better now, my eyes are very thankful!
