### ISSUE TITLE
Conflict between the extension and the js script on Linux

### ISSUE THREAD

**Issue by n-peugnet** [darkreader/darkreader#2730]
I'm still having this problem with Firefox and Chrome on 4.9.9 so I made an issue for this specific problem as requested.
I am using the min version of the script from jsdeliver. You can check the problem with <a href="https://mers.club1.fr/film-copy" rel="nofollow">this page</a>.

With the extension disbled both firefox and chromium renders the page without any issue.
![Screenshot from 2020-04-06 16-19-13](https://user-images.githubusercontent.com/23519418/78569117-67ddd080-7823-11ea-9db6-3b326b9f1057.png)

With the extension enabled:
- On chromium the page loading never ends and there is only a dark background. After some time.
  ![Screenshot from 2020-04-06 16-20-14](https://user-images.githubusercontent.com/23519418/78568593-9c9d5800-7822-11ea-9479-f8136ef5d5ae.png)

- On firefox the page loading never ends and I get a strange render
  ![Screenshot from 2020-04-06 16-16-16](https://user-images.githubusercontent.com/23519418/78568621-a6bf5680-7822-11ea-82a5-f95fb3e3ec12.png)

_Originally posted by @n-peugnet in https://github.com/darkreader/darkreader/issues/2227#issuecomment-609825503_

**Comment by Gusted** [comment]
This definitely a Linux issue when I profiled this on the original issue what you have linked. Both for Firefox and chromium didn't showed any slowdown on Windows 10 on a rather poor system specification. Guess I going to install Linux. Which Distribution do you currently use?

**Comment by n-peugnet** [comment]
I am using Linux Mint 19.3 Cinnamon 64 bits with kernel version 5.3.0-51-generic

**Comment by Mahanotrahul** [comment]
@n-peugnet Did you try this solution https://github.com/darkreader/darkreader/issues/2227#issuecomment-620218136
I had the similar problem. Detecting if the dark reader extension is on before enabling the darkreader via script on the website solves the problem it seems.

**Comment by Gusted** [comment]
#2855
