### ISSUE TITLE
[Broken Website] Firefox about:home not being darkened

### ISSUE THREAD

**Issue by Magicool-1** [darkreader/darkreader#2742]
**Website**
Firefox about:home

**How to Reproduce**
Visit about:home in Firefox

**Expected behavior**
- About:home will not be inverted if really "protected by Firefox" and stay dark by default theme
- When adding about:home to "do not invert" in settings site stay dark by default theme
- Website will be darkened by Dark Reader.

**Actual behavior**
- Website will be brightened no matter the settings
- Adding about:home to "do not invert" does nothing
- Addon says "Website protected by Firefox"

**Screenshots**
Dark Reader activated:
https://i.imgur.com/fliHs1b.jpg
Dark Reader activated:
https://i.imgur.com/sKHqDYG.jpg

**System info:**
 - OS: Windwos 10
 - Browser Firefox 77
 - Darkreader Version 4.9.9

**Comment by Gusted** [comment]
That's right it's protected, But we use for a theme API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme that changes. This it's a bug with Firefox Itself https://bugzilla.mozilla.org/show_bug.cgi?id=1415267 that causes to disable all other themes. You can enable it back trough.
about:addons -> Themes -> Dark theme -> Enable

**Comment by Magicool-1** [comment]
I see thanks for the info. 
I guess I will close this ticket since it's a bug with Firefox.
