### ISSUE TITLE
[Feature Request] exceptions css rules

### ISSUE THREAD

**Issue by ylantron** [darkreader/darkreader#2751]
**Is your feature request related to a problem? Please describe.**
I sometimes use this extension with also custom css created with Stylish, and I often have a problem, in the menu, if I want disabled menu item font color to be more black I can't because the extension overrides my css in order to make it white

**Describe the solution you'd like**
A css file blacklist/whitelist that contains rules (or class names) that tells the extension to ignore certain classes or other elements

**Comment by Gusted** [comment]
We have done this for **Stylus** and not **Stylish** as I personally [don't recommend stylish for obvious reasons](https://www.bleepingcomputer.com/news/software/chrome-and-firefox-pull-stylish-add-on-after-report-it-logged-browser-history/). Please move to [stylus](https://github.com/openstyles/stylus) and all your CSS to stylus. If you use Stylus you will see we don't modify any CSS of it. As of PR #2152

**Comment by ylantron** [comment]
oh, didn't know about the Stylish thing, thank you for telling and for answering :)

**Comment by Gusted** [comment]
No problem, make sure to unistall stylish after moving all CSS styles

**Comment by ylantron** [comment]
already done and reported with the link you posted

**Comment by Gusted** [comment]
I'm unsure how they track people these days but quite sure it's still track not related info to the extension/addon.
