### ISSUE TITLE
"global Dark List" doesn't work with Invert Listed Only

### ISSUE THREAD

**Issue by irvnriir** [darkreader/darkreader#2752]
I use your awesome extension not only to add dark mode to websites, but also to make even dark pages more readable/comfortable. For example `https://steamcommunity.com/` in some places, has horrible foreground to background contrast.

Make the Dark List define only the initial on/off state, and allow to change it regardless of the list.

**Comment by Gusted** [comment]
Hi @irvnriir 
Just press on the site button ![](https://i.imgur.com/0a3X91P.png) that always override the global dark site :)

**Comment by irvnriir** [comment]
@Gusted
https://yadi.sk/i/CYbay9Ae5F9_5g

**Comment by Gusted** [comment]
That's weird. Do you have anything in site list? Restart browser? Reload page?

**Comment by bmcminn** [comment]
I found that I hated using the "Not inverted List" option because it would dark mode EVERY website instead of letting me choose when to dark mode the site.

So switching to "Invert list only" solved that, however I had to go through and prune my list :P

It works great now.

**Comment by Gusted** [comment]
Good to hear!

**Comment by irvnriir** [comment]
@Gusted . Technically, it transformed from feature request into a bug report, but not solved .
Is it possible to empty the list not 1by1 ? (i have like ~200 items there)

**Comment by Gusted** [comment]
Devtools -> Preview new design
Settings -> Manage Settings -> Reset Settings. 

Will clear EVERY data stored. To default.

**Comment by Gusted** [comment]
DarkReader Is having a bad day with Firefox I guess.... Try just to uninstall the addon restart firefox and install dark reader

**Comment by irvnriir** [comment]
@Gusted .
The new interface is 1000+ times worse X) .
I also wish there would be a way to export my per-site settings .

Restart didn't change anything .

**Comment by Gusted** [comment]
Export settings contain all settings including per-site.

It works for me.... It's just a little bit of delay to switch.

**Comment by irvnriir** [comment]
@Gusted for me it doesn't even after resetting the settings, i don't see Export anywhere .

**Comment by Gusted** [comment]
In the new design
Settings - > manage settings > export settings.

**Comment by irvnriir** [comment]
Settings :
![Screenshot 06-08-2020 01 52 20](https://user-images.githubusercontent.com/13949704/83985998-c8c07c80-a92a-11ea-8429-cf4892bcc361.png)

**Comment by Gusted** [comment]
Woops it wasn't released yet. 
![](https://i.imgur.com/D72XsbY.png) But it's already added and will be included in the next version.

**Comment by irvnriir** [comment]
Firefox still has some CPU performance and page loading issues, so i've used the Invert Listed Only to probe pages . Also, the issue persist to "Enable by default" in the new interface .

**Comment by Gusted** [comment]
That's for another issue :-) I was in Firefox indeed.

**Comment by irvnriir** [comment]
Why closed?

**Comment by Gusted** [comment]
As it's unnecessary to ask every question in the same issue while the main issue is resolved.

**Comment by irvnriir** [comment]
it never was

**Comment by Gusted** [comment]
Well I don't see any issues, tell me what's now the issue with the list?

**Comment by irvnriir** [comment]
you can't change the color of item in GDList with ILOnly .

**Comment by Gusted** [comment]
Define color

**Comment by irvnriir** [comment]
Light / Dark

**Comment by irvnriir** [comment]
it can't be enabled for item in GDList with ILOnly .

**Comment by Gusted** [comment]
![](https://i.imgur.com/6ltPJMr.png) I just can enable a dark site with adding it to the Inverted Listed Only

**Comment by irvnriir** [comment]
well, i still can't, after reinstall and with the only extension up . are you using the version from Firefox add-ons site ?

**Comment by Gusted** [comment]
Chrome(Shouldn't make any difference) And the latest Commit(But site logic wasn't touched since 4.9.11)

**Comment by Gusted** [comment]
Try to give a fresh Firefox profile a try/another edition of the browser to be sure. I heard that does wonders

**Comment by irvnriir** [comment]
I seem to be fixed with the new version of extension or browser.

**Comment by Gusted** [comment]
👍🏽
