### ISSUE TITLE
Cloudflare.com

### ISSUE THREAD

**Issue by irvnriir** [darkreader/darkreader#2776]
**Website**
https://dash.cloudflare.com/

**Actual behavior**
Their login system doesn't work while DR enabled.

**System info:**
 - OS: Windows
 - Browser Firefox

**Comment by Gusted** [comment]
Which error do you get?

**Comment by irvnriir** [comment]
"Code: 9302" at register and "Reload page" at login .

**Comment by Gusted** [comment]
#1173

**Comment by irvnriir** [comment]
What a hell, i did search for "cloudflare" . Now it does find that, sorry .
