### ISSUE TITLE
[Feature Request] apply to only part of a page

### ISSUE THREAD

**Issue by Geobert** [darkreader/darkreader#2783]
**Is your feature request related to a problem? Please describe.**
I'm using protonmail as my email provider and it already has a dark theme. But the emails are not darkened so I use DR on top of the dark theme just for the email part.

**Describe the solution you'd like**
A way to specify a part of the page to be processed (= the root of the tree to be processed), with an element picker in the same manner as ublock origin for example.

**Comment by Gusted** [comment]
Nope not possible with current codebase and shouldn't be at all possible.

**Comment by Gusted** [comment]
I suggest using light theme for protonmail and than use dark reader or use combination.

**Comment by Geobert** [comment]
Dark reader works fine on protonmail dark theme, it was a matter of making DR works less on the page :)

**Comment by Gusted** [comment]
We analyze all stylesheets not individually elements

**Comment by Geobert** [comment]
I see :) Thank you for the precision!
