### ISSUE TITLE
[BUG]Text Line Appears Black When Typing in Bigger Text Under Some Conditions

### ISSUE THREAD

**Issue by dragonBall561** [darkreader/darkreader#2784]
Before You read this, I want you to know that this is not a duplicate of my first bug report. It _is_ very similar though

**Describe the bug**
This bug is very complicated. I recorded my screen in a video. Basically what happens is that the white text line appears black with BIGGER TEXT (Not CAPS, not **Bold**) under some conditions. I attached a video in a zip:
[Video.zip](https://github.com/darkreader/darkreader/files/4746882/Video.zip)

**To Reproduce**
> Go to 'Google Slides'
> Turn on Dynamic Theme
> Give it a blank layout
> make a text box. Write some text in the black font color
> Make another one. Write some text in bigger font size, with black font color
> Click on the text on the first text box
> Click on the text on the second text box
> The line that indicates where the text is being typed is black and is impossible to be seen.

**Expected behavior**
The line is white so you can see it

**Screenshots**
I added a video [Video.zip](https://github.com/darkreader/darkreader/files/4746882/Video.zip)

**System Information:**
 - OS: [Linux Mint 19.3 Cinnamon (Based on Ubuntu 18.04 LTS)]
 - Browser [Chromium 83]
 - Version [Darkreader Version: 4.9.9. Chromium Version: 83. OS Version: 19.3]

**Additional context**
It is all in the video.zip file which has a screen recorded video inside.
[Video.zip](https://github.com/darkreader/darkreader/files/4746882/Video.zip)
Sorry for misspellings and slow typing.

**Comment by Myshor** [comment]
What I can reproduce is black line when entering text. But with second blink it's white again.

Other thing. There is some confirmed slowdowns with dark reader in chrome(ium) 83 so I changed my browser to Opera (Chromium 81) where it works as described.

**Comment by dragonBall561** [comment]
Ok, that's weird. I ran `chromium-browser --version` and it gives:
```
Using PPAPI flash.
Chromium 83.0.4103.61 Built on Ubuntu, running on LinuxMint 19.3
```
When I go to the chrome://version page, it gives:
```
**Chromium**:	81.0.4044.138 (Official Build) Built on Ubuntu, running on LinuxMint 19.3 (64-bit)
```
This is the _weirdest_ thing ever! But I guess it is Chromium 81 though.

**Comment by dragonBall561** [comment]
So I guess I better find a way to update
