### ISSUE TITLE
Investing.com Login Page Broken

### ISSUE THREAD

**Issue by amanhigh** [darkreader/darkreader#2792]
**Website**
https://www.investing.com/members-admin/login

**How to Reproduce**
* Go to https://www.investing.com/members-admin/login, Dark Theme won't be applied.
* Toggle Extension on and off. Now Dark theme would be applied.

**Expected behavior**
Dark theme should be applied on first load.

**Actual behavior**
Dark theme doesn't get applied until we toggle extension. First load doesn't apply the theme.

**Screenshots**
* First Load (Theme Not Applied)
![SNAG--2020-06-09-042](https://user-images.githubusercontent.com/409973/84114347-d587c200-aa49-11ea-9493-af549f034c65.jpg)

* Toggle Extension Off
![SNAG--2020-06-09-043](https://user-images.githubusercontent.com/409973/84114401-ed5f4600-aa49-11ea-9022-25a778b534a4.jpg)

* Toggle Extension Back On (Theme Applied)
![SNAG--2020-06-09-044](https://user-images.githubusercontent.com/409973/84114419-f18b6380-aa49-11ea-81a2-1939fa9eb916.jpg)

**System info:**
 - OS:  Windows
 - Browser : Firefox 77
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
#2749 < Already tracking investing.com login page

**Comment by amanhigh** [comment]
@Gusted Any updates for this ?

**Comment by Gusted** [comment]
It's been on the backlog as other bugs has come around and features but I will have a look now.

**Comment by Gusted** [comment]
You should use Filter for this site they are blocking our requests to see external stylesheets(to darken them)
