### ISSUE TITLE
[BUG] Firefox Nightly "Loading, please wait"

### ISSUE THREAD

**Issue by yashjahit-21705201** [darkreader/darkreader#2793]
### **Describe the bug**

Dark Reader not working on Firefox Nightly, when trying to access add-on options, it keeps showing a "Loading, please wait" message

### **Steps to reproduce**

- Download Firefox Preview Nightly 
- Install Dark Reader add-on
- Browse to any page
- Try to access add-on options

### **Expected behavior**

To be able to access add-on options, and change settings like turn on dark Reader, change brightness, etc.

### **Actual behavior**

A "Loading, please wait" message appears and doesn't change even if I leave it for some time

### **Screenshots**

![Screenshot_20200609-085921](https://user-images.githubusercontent.com/34451870/84121832-8896f200-aa2f-11ea-86ea-1d2776eb6ecc.jpg)

### **System Information:**
 - OS: Android 10.0
 - Browser: Firefox Preview Nightly for Developers Nightly 200608 06:00 (Early Access)
 - Dark Reader version: 4.9.9

**Comment by Gusted** [comment]
Reproduced 😬 I will see what the origin of this is.

**Comment by B0pol** [comment]
It also does not darken websites.

**Comment by Gusted** [comment]
That's was most likely to be expected if the UI is broken than somewhere in the background Script a error is occured and can't inject any scripts.

**Comment by B0pol** [comment]
Is it related to #2700 ?

**Comment by Gusted** [comment]
Hadn't time to look in both, I only know Firefox pushed some updates that didn't make people happy and broke also stuff.

**Comment by sprinkledcheese** [comment]
https://old.reddit.com/r/firefox/comments/gzgx9m/dark_reader_on_firefox_preview_nightly_android/

**Comment by joshbowyer** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1644297

Firefox broke some stuff, don't think anything needs to be fixed in DarkReader itself

**Comment by Gusted** [comment]
Hmm it broke storage.sync good to know a bug report had been acknowledged.

**Comment by danielzgtg** [comment]
Fenix bug: mozilla-mobile/fenix#11336

**Comment by Gusted** [comment]
Update to latest nightly it's been fixed.
