### ISSUE TITLE
[Broken Website] theregister.com home page

### ISSUE THREAD

**Issue by J-Siu** [darkreader/darkreader#2798]
**Website**
https://www.theregister.com/

**How to Reproduce**
1. go to https://www.theregister.com/

**Expected behavior**
Head line block with dark background and light text

**Actual behavior**
Head line block with white background and light text

**Screenshots**
![Screen Shot 2020-06-09 at 10 52 48 AM](https://user-images.githubusercontent.com/3171920/84163715-cac82f80-aa3f-11ea-8b57-9f567f7458ee.png)

**System info:**
 - OS: MacOS, Android
 - Browser: Firefox
 - Darkreader Version 4.9.9

**Additional context**
Only affect the home page, not seeing issues in article pages so far.

**Comment by sprinkledcheese** [comment]
Fixed in the master: [https://github.com/darkreader/darkreader/pull/2676](url)

**Comment by J-Siu** [comment]
> Fixed in the master: [#2676](https://github.com/darkreader/darkreader/pull/2676)

So fix will be in 4.9.11?

**Comment by Gusted** [comment]
Next update ^
