### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by F8ER** [darkreader/darkreader#2803]
**Website**
The [link](https://bugs.chromium.org/p/chromium/issues/detail?id=239401)

**How to Reproduce**
Turn on DarkReador on the page

**Expected behavior**
A dark website colors, at least, removed white colors

**Actual behavior**
The a bunch of white elements which melt eyes

**Screenshots**
![](https://i.imgur.com/reUI0iD.png)

**System info:**
 - OS: Windows 64 bit Pro, latest updates.
 - Browser, Version 83.0.4103.97 (Official Build) (64-bit)
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
#2892
