### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by Gian-Marco-Del-Freo** [darkreader/darkreader#2819]
**Website**
https://www.html.it/pag/15594/lereditarieta/

**How to Reproduce**
> 1. I open the site with the plug-in already active

**Expected behavior**
Part of the page is not changed when I enter the website

**Actual behavior**
Part of the page remains light in color

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/39838172/84327466-ad9a7a80-ab7f-11ea-9749-8986d3ca5386.png)

**System info:**
 - OS: [Windows 10]
 - Browser: [e.g. chrome Version 83.0.4103.97 (Official Build) (64 bit)]
 - Darkreader Version: [4.9.9]
 
**Additional context**
When I open the site itself with the extension already active, a gradne part of the page is not changed by the extension making it impossible to read the text

**Comment by Gusted** [comment]
Can't seem to reproduce it?

**Comment by sprinkledcheese** [comment]
Turning Dark Reader Off and On makes it dark.

**Comment by sprinkledcheese** [comment]
Works fine on firefox.

**Comment by sprinkledcheese** [comment]
I get this in firefox Browser Console: "Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content". Not sure if it's related to the chrome issue.

**Comment by Gusted** [comment]
Lazyloading, so the style element is loaded but the content not.
