### ISSUE TITLE
When I open a new web page, even in dark mode. It will also show failure. You need to refresh it[BUG]

### ISSUE THREAD

**Issue by RQinwm** [darkreader/darkreader#2820]
### **Steps to reproduce**

- Go to '...'
- Click on '...'
- Scroll down to '...'

### **Actual behavior**

A clear and concise description of what actually happened.

### **System Information:**
 - OS: [e.g. iOS 11]
 - Browser: [e.g. Chrome 73, Safari 13]
 - Dark Reader version: [e.g. 4.9.9]

**Comment by Gusted** [comment]
Use the template
