### ISSUE TITLE
[Broken Website] Math on github ipython notebooks is not readable

### ISSUE THREAD

**Issue by Mukundan314** [darkreader/darkreader#2834]
**Website**
https://github.com/microsoft/QuantumKatas/blob/master/tutorials/Qubit/Qubit.ipynb

**Expected behavior**
Math expressions to be readable 

**Actual behavior**
Math expressions were not readable

**Screenshot**
![Screenshot_2020-06-12 microsoft QuantumKatas](https://user-images.githubusercontent.com/30190448/84511177-c6bc3c00-ace3-11ea-9e60-2e98914ca16d.png)

**System info:**
 - OS: Arch Linux
 - Browser: firefox
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
Wait for next release, PR #2804 has fixed this issue with ipynb.
