### ISSUE TITLE
Scrollbar is not identifyable

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [darkreader/darkreader#2843]
dynamic theme scrollbar messes with the background on some sites.

**Comment by PradeepSinghMakwana** [comment]
Here is more of what I have for this fix

**Comment by PradeepSinghMakwana** [comment]
[Here](https://github.com/darkreader/darkreader/pull/2846#issue-433960165) is the fix I proposed

**Comment by Gusted** [comment]
Hi @PradeepSinghMakwana!

Can you give some more information, as I see the propsed fix is just some more cosmetic CSS that we aren't meant for as Dark Reader.
You also indicate that messes with the backgroung on some sites, could you indicate some of those sites so I can have a look at them and see if we can anticipate our codebase on it?

Regards,
Gusted

**Comment by PradeepSinghMakwana** [comment]
Ya, Sure @Gusted , Thanks for taking interest. Here are some. 

- https://www.investopedia.com/terms/b/brexit.asp
- https://www.tcs.com/careers/graduate-hiring/en-uk
- https://www.mediawiki.org/wiki/New_Developers
- https://www.quora.com/What-do-you-mean-by-introducing-non-linearity-in-a-neural-network
... list is very long

Surprised to see your interest, how many can we mention like this, and how many can you correct individually(one by one). What is the way we are using to make this work, I mean is that dynamic thing coming from AI - data driven approach?

**Comment by PradeepSinghMakwana** [comment]
I also found https://accounts.spotify.com/en/login logo missing when using darkmode with dynamic theme. I also want you to take a look at how images are transformed by Fourier Transform. The higher frequency part of an image can give a lot of information of edges, and we can use it instead of hidding images all the way.

**Comment by PradeepSinghMakwana** [comment]
Are we using opacity on scrollbar or scrollbar-thumb?

**Comment by Gusted** [comment]
I suggest something else,

If your monitor brightness is low, I think it's better to set a more color for your scrollbar like `red` or  `#959799` or anything else you would like. I made a GIF But it will look like a bit different for you as you don't have the Colors+ Dropdown yet, just use the Scrollbar: Dropdown. https://i.imgur.com/j1nq7oX.gifv

**Comment by PradeepSinghMakwana** [comment]
how about #0000ff color on the border. No one wants to see a bright coloured filled bar, it shines and distracts the user.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/84594316-a27e6d80-ae51-11ea-8ee6-a153064a9813.png)
In my opinion this isn't shiny and distact the user.

**Comment by PradeepSinghMakwana** [comment]
will it be easy to catch with a mouse or touchpad?

**Comment by Gusted** [comment]
I don't see where you are going.

**Comment by PradeepSinghMakwana** [comment]
Altough your image looks great.

**Comment by PradeepSinghMakwana** [comment]
Thanks, I think we should go with it. What's your thoughts?

**Comment by Gusted** [comment]
Specific usercase, I think you should change the color of your scrollbar.

**Comment by PradeepSinghMakwana** [comment]
what about others who have the same issue? Please understand, I intensionally made my screen brightness low. Most of the developers working all night feel the white light killing their eyes. Most of them would also make there screen brighteness lowest possible.

**Comment by Gusted** [comment]
Than they should change the color of scrollbar too. Making it global for everyone isn't a good suggestion.

**Comment by PradeepSinghMakwana** [comment]
what should be the normal behaviour of scrollbar for everyone? I am just asking for a border with everything in scrollbar same as before. What could be problematic in this?

**Comment by Gusted** [comment]
Change the scrollbar color in the options, where it was made for. no need to add fancy scrollbar changes.

**Comment by PradeepSinghMakwana** [comment]
would it do only for the border?

**Comment by Gusted** [comment]
I will see but like I said just change the color, the whole purpose of this was made to add a custom color.

**Comment by PradeepSinghMakwana** [comment]
Ya, thanks. I didn't knew that option. Thanks Closing the issue

**Comment by PradeepSinghMakwana** [comment]
Not applicable in Filter or Filter+ themes.
