### ISSUE TITLE
[Broken Website] Wikipedia PDFs

### ISSUE THREAD

**Issue by Rummskartoffel** [darkreader/darkreader#2856]
**Website**
https://en.wikipedia.org/wiki/File:ExtIPA_chart_(2015).pdf or any other PDF file on Wikipedia.

**How to Reproduce**
Open the *File:* page of any PDF on Wikipedia.

**Expected behavior**
Darkreader changes the page style the same way as on other *File:* pages, e.g. https://en.wikipedia.org/wiki/File:Molecular_Modeling.png.

**Actual behavior**
Darkreader does not change the page style, instead displaying *This is page is protected by browser* in its popup.

**Screenshots**
On PDFs:
![Image 041](https://user-images.githubusercontent.com/20257197/84579067-145fa400-adcb-11ea-9cd2-fc47fea7395c.png)
On other file pages:
![Image 042](https://user-images.githubusercontent.com/20257197/84579106-8c2dce80-adcb-11ea-90c2-f468fcb5d733.png)

**System info:**
 - OS: Windows 10 x64 version 2004 build 19041.329
 - Browser: Firefox 77.0.1 x64
 - Darkreader Version: 4.9.9
 
**Additional context**
May be related to #373, but I'm not sure.
At first, I interpreted the message in Darkreader's popup as a problem with Firefox' extension permissions, so I wrote [this question](https://support.mozilla.org/en-US/questions/1291091) on the Mozilla support forums. However, I was told that the problem must be caused by Darkreader. One of the replies there mentions finding references to a setting regarding PDFs in Darkreader's code, but I could not find any setting of the sort in Darkreader's popup.

**Comment by Gusted** [comment]
Sigh. It got detected as PDF as anything really ending with .pdf should be a real pdf and not a site. They played me with my PDF detection 😄. Will provide a fix of this shouldn't be hard.
For a quick workaround,
Dev Tools -> Preview New Design
Settings -> Enable for PDF Files.

**Comment by Rummskartoffel** [comment]
Regarding your workaround, the only thing enabling the new design did was make an exclamation mark appear on the dev tools button, but there is no PDF option in the new design's settings, either 🤷

**Comment by Gusted** [comment]
Quick one https://i.imgur.com/dm13jgE.gifv

**Comment by Gusted** [comment]
#2857 Fix will be shipped next release.

**Comment by Rummskartoffel** [comment]
> 
> 
> Quick one https://i.imgur.com/dm13jgE.gifv

nope 😂 
![image](https://user-images.githubusercontent.com/20257197/84580307-095e4100-add6-11ea-86ac-b6f014bff5f7.png)

**Comment by Gusted** [comment]
Uh, oh yeah PDF is for Firefox disabled as they already don't allow us to style any .pdf

**Comment by Gusted** [comment]
That's why we restricted it ^ To prevent errors.

**Comment by Rummskartoffel** [comment]
gotcha
