### ISSUE TITLE
[Feature Request] Detect barcode or do not switch for barcode

### ISSUE THREAD

**Issue by SabrinaSimao** [darkreader/darkreader#2858]
Similar to https://github.com/darkreader/darkreader/issues/2783

**Is your feature request related to a problem? Please describe.**
it's very common in Brazil to make payments through bank slips, and most pages generate barcodes for payments. Dark Reader switches the black and white from the barcode, making it impossible to scan with cameras

**Describe the solution you'd like**
A solution that applys to https://github.com/darkreader/darkreader/issues/2783 could also apply to this, maybe switching off everything _but_ the area around the barcode

**Comment by Gusted** [comment]
Switch black light? It's about Bank this but if you could provide more explanation?

**Comment by SabrinaSimao** [comment]
if barcodes and qr codes could be detected in the page, preventing them from switching to negative, would save time from the user scanning them. Some people might not understand that they are unscannable because of the swap and could keep trying until they give up

**Comment by Gusted** [comment]
Can I ask you which mode you use? E.g. Dynamic, Static, Filter, Filter+

**Comment by SabrinaSimao** [comment]
> Can I ask you which mode you use? E.g. Dynamic, Static, Filter, Filter+

Dynamic

**Comment by Gusted** [comment]
Hmm weird dynamic only invert background images and not normal images.

**Comment by SabrinaSimao** [comment]
Oh i don't think it was an image, it was embedded in the page iirc

**Comment by Gusted** [comment]
Embedded? Can you explain more

**Comment by SabrinaSimao** [comment]
I can try to replicate the output i got originally :)

**Comment by Gusted** [comment]
Sounds good to me

**Comment by SabrinaSimao** [comment]
![Screenshot (236)](https://user-images.githubusercontent.com/18487855/84973656-fa3e0280-b0f7-11ea-9318-4286aa1dba6b.png)
![image](https://user-images.githubusercontent.com/18487855/84973666-0033e380-b0f8-11ea-8854-b39833c03ecb.png)

These are some examples that I had problem with. I see now that the problem was not with the barcode itself, but with the page behind that was dark, making it impossible for the scanner to read.

**Comment by Gusted** [comment]
Ah I see. Dark reader and banking sites are not a good match. Only thing is do to make a manual CSS fix

**Comment by Gusted** [comment]
Report broken sites.
