### ISSUE TITLE
Can you fix white screen please?

### ISSUE THREAD

**Issue by Sungwoo-JEON** [darkreader/darkreader#2885]
Hello I am using your extension very well.

I would like to make a suggestion for the function.

Whenever I go to a webpage via clicking Favorites on Bookmark Bar, it always goes through a white screen until the webpage finishes loading.

Also, the page provided by Chrome (setting, download, ERR_CONNECTION_RESET, etc.) is not applicable at all.

This white screen hurts my eyes when I use the extension.

Can you solve this problem?

Thank you.

Sincerely Yours

**Comment by Gusted** [comment]
Blame your browser we don't have access to those pages and the white screen is loading the web page(getting the data)

**Comment by Sungwoo-JEON** [comment]
> Blame your browser we don't have access to those pages and the white screen is loading the web page(getting the data)

wow very fast reply. Thank you.

**Comment by Gusted** [comment]
I have notifications on for new issues ^-^ I think I can do some research on this as #1219 it's a more global problem.
Which browser do you use?

**Comment by Sungwoo-JEON** [comment]
> I have notifications on for new issues ^-^ I think I can do some research on this as #1219 it's a more global problem.
> Which browser do you use?

So the answer was so quick.

Thanks for the link. I'll read it now.

I'm using Chrome.

**Comment by Gusted** [comment]
Okay open chrome://flags/ and search for `flash` and make a screenshot of your current screen which flags do you see?

**Comment by Sungwoo-JEON** [comment]
> Okay open chrome://flags/ and search for `flash` and make a screenshot of your current screen which flags do you see?

![123](https://user-images.githubusercontent.com/43665331/85110957-9ed25880-b24e-11ea-857c-183032f98b2d.PNG)

Here you are.

**Comment by Gusted** [comment]
Yep that one you can enable it. That hopefully should prevent most flashes try to test it.

**Comment by Gusted** [comment]
Please note it can seems like it's slower because it will now wait on the current page until the first 'navigated page loading' but in fact it has not a impact on performance

**Comment by Sungwoo-JEON** [comment]
> Please note it can seems like it's slower because it will now wait on the current page until the first 'navigated page loading' but in fact it has not a impact on performance

Ok. I'll try it now. Thank you!

**Comment by Gusted** [comment]
Merging into #1219
