### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nou4r** [darkreader/darkreader#2890]
If there is `[]` in the url, darkreader simply breaks.
/market/steam/?game[]=594650&rt=no&order_by=price_to_up

If i remove  `[]`  from the url, the page is not functional of course but pagereader works fine again.

**Comment by Gusted** [comment]
`[]` never should be available in the url.
#2517 resolves this

**Comment by Nou4r** [comment]
What do you mean by "never should"? You are not to decide what websites should or should not, even if what they are doing is not "smart".

**Comment by Gusted** [comment]
Web security 101 never put unescaped characters into url's.
We already pushed 4.9.11 with a fix for this.
With never should I meant it's just not smart and we didn't expect that website actually used it
