### ISSUE TITLE
[Feature Request] custom colors?

### ISSUE THREAD

**Issue by hackaholic5069** [darkreader/darkreader#2897]
**Is your feature request related to a problem? Please describe.**
So, i have my entire desktop themed with Qogir, and short of most webpages, everything follows this theme. google blinding me is an issue, but your dark theme also does not quite fit my system.

**Describe the solution you'd like**
the ability to define custom themes in some form would fix this issue

**Additional context**
![image](https://user-images.githubusercontent.com/37553921/85216684-0c0be980-b334-11ea-9e89-f85307b9e8e5.png)

**Comment by Gusted** [comment]
Wait for the next update :) #931 for some screenshot of how it could look like
