### ISSUE TITLE
Create better UI option for automatic day/night

### ISSUE THREAD

**Issue by StraggleCraft** [darkreader/darkreader#2905]
As noted by [2690 ](https://github.com/darkreader/darkreader/issues/2690), automatic day / night scheduling is accessible by clicking on the three menu dots seen next to ON / OFF... I would have never found this UI element without browsing the issues looking to see if someone had requested the feature.   I suspect more users would utilize the feature if the option was more visible in the UI.  Please create a more visible element to allow users to configure this option.  Maybe a clock icon.

**Comment by Gusted** [comment]
Devtools -> Preview New design
Settings -> Automation
