### ISSUE TITLE
[BUG]When the URL contains square brackets, the dark mode cannot be turned off

### ISSUE THREAD

**Issue by tanghengvip** [darkreader/darkreader#2906]
### **Describe the bug**

When the square brackets are included in the URL, it will be forced into the dark mode, and the day mode I set for the URL will not take effect

### **Steps to reproduce**
For example:
https://www.baidu.com/s?wd=[]

### **Expected behavior**

I could make it daymode.

### **Actual behavior**

I can't make it daymode.

### **System Information:**
 - OS: [WIN10]
 - Browser: Edge(based on Chromium 83.0.478.54)
 - Dark Reader version: [4.9.9]

**Comment by Gusted** [comment]
#2660
