### ISSUE TITLE
[Feature Request] Additional font configuration for code

### ISSUE THREAD

**Issue by mattalexx** [darkreader/darkreader#2909]
**Is your feature request related to a problem? Please describe.**
When I set a custom font, it is applied to code blocks as well.

**Describe the solution you'd like**
I would like to view code using a fixed-width font.

**Additional context**
The code in this GitHub commit was changed by the Font setting in Dark Reader:
https://github.com/torvalds/linux/commit/25d21ad6e799cccd097b9df2a2fefe19a7e1dfcf

**Comment by Gusted** [comment]
Github is evil and don't use something like 'pre' element if you can open devtoosl you can see for yourself

**Comment by Gusted** [comment]
Will make a fix for it
