### ISSUE TITLE
[BUG] Screen flashes BRIGHT WHITE for several seconds

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#2917]
### **Describe the bug**

The first five seconds of page load turns the screen into a glaring lashlight.

Not sure if this a darkreader glitch or a Firefox glitch.

### **Steps to reproduce**

- Go to Google.

### **Expected behavior**

The background remains perfectly dark until specific DOM elements override this.

### **Actual behavior**

My eyes!!!

### **System Information:**
 - OS: Android 10
 - Browser: Firefox latest stable
 - Dark Reader version: Latest stable

**Comment by Gusted** [comment]
https://discordapp.com/channels/700258399702482945/700258399702482948/725053088486129684 Reproduced. It seems like more as a browser issue.

**Comment by Gusted** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1647817 Opened up a bug report and will see what they have to say.

**Comment by B0pol** [comment]
See the issue tracked on firefox preview github repository: https://github.com/mozilla-mobile/fenix/issues/6313

**Comment by ktpx** [comment]
I have this problem in vivaldi as well, but not for that long., But almost any page will "flash" white for a second, then it will go dark.  It's really tough on my eyes, and now i actually close them every time I click a link, for a few seconds. Not sure if this is a similar bug, or j ust browser issue.

**Comment by Gusted** [comment]
Browser bugs, we do what we can.

**Comment by NicoWeio** [comment]
Without testing myself, it looks as if it should be fixed by now: 
https://github.com/mozilla-mobile/fenix/issues/11884#issuecomment-748871856

**Comment by Gusted** [comment]
Their are more issues about this and has been fully fixed a couple of version ago. I haven't experienced once since.
