### ISSUE TITLE
[BUG] Dark style lag

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#2918]
### **Describe the bug**

The original light mode style displays for several seconds on page load.

### **Steps to reproduce**

- Go to Google

### **Expected behavior**

Pages are 100% dark mode.

### **Actual behavior**

The original website style renders for several seconds.

### **System Information:**
 - OS: Android 10
 - Browser: Firefox latest stable
 - Dark Reader version: Latest stable

**Comment by Gusted** [comment]
Use Firefox preview and test it again.

**Comment by Gusted** [comment]
Firefox Nighly has this issue fixed alongside the latest Dark Reader version.
