### ISSUE TITLE
[Broken Website] github.com/*/*/graphs/commit-activity

### ISSUE THREAD

**Issue by Rakleed** [darkreader/darkreader#2919]
**Website**
https://github.com/darkreader/darkreader/graphs/commit-activity

**How to Reproduce**
1. Go to https://github.com/darkreader/darkreader/graphs/commit-activity
2. Look at the names of the days of the week at the bottom of the second graph

**Expected behavior**
The names of the days of the weeks at the bottom of the second graph will be white and clearly visible

**Actual behavior**
The names of the days of the weeks at the bottom of the graph second are dark and very poorly visible

**Screenshots**
![image](https://user-images.githubusercontent.com/19418601/85445645-4677bf80-b59c-11ea-91f8-a1ea96b96b56.png)

**System info:**
 - OS: Windows 10 v. 2004 b. 19041.329
 - Browser: Chrome 83.0.4103.116
 - Darkreader Version: 4.9.9
 
**Additional context**
I tried to invert the `.day` and `.axis` classes, but that didn't help.

**Comment by Gusted** [comment]
It's wrapped in a SVG if you invert `svg.viz` You will see it will be affected but it's unfortunate that it has no affect inside a svg? Will see with Firefox if this is a bug or not.

**Comment by Gusted** [comment]
```
svg.viz {
    fill: white !important;
}

```
And because it's wrapped inside a SVG element you need to use `fill` 🤦 Forgot that lol. Take the credits and open a PR for it.
