### ISSUE TITLE
[Broken Website] Some elements of Wikimedia's Zuul don't fit in the dark theme

### ISSUE THREAD

**Issue by zoranzoki21** [darkreader/darkreader#2921]
**Website**
https://integration.wikimedia.org/zuul

**How to Reproduce**
1. Go on https://integration.wikimedia.org/zuul
2. If tests for patches on Wikimedia's Gerrit (https://gerrit.wikimedia.org) aren't running when you visit page, try later.

**Expected behavior**
In dark mode, circles shouldn't have background, and the elements on page should fit into the dark theme.

**Actual behavior**
With enabled dark mode, circles aren't transparent, they have white background.

**System info:**
 - OS: Kubuntu 20.04
 - Browser: Chrome 83.0.4103.116
 - Darkreader Version: 4.9.9
 
**Additional context**
Already reported on Wikimedia's Phabricator (https://phabricator.wikimedia.org/T256132).

**Comment by Gusted** [comment]
Kind of a problem on their side we can't fix with CSS. Not sure if it will help as it's Closed and declined....

**Comment by Gusted** [comment]
![](https://i.imgur.com/0mG3JQX.png) Stats will look like this. Only option to make it dark it's also a static image... 
It's seems like the page is a bit intranet and can use some modernizer.

**Comment by zoranzoki21** [comment]
Stats looks better :smile:

What about circles?

**Comment by Gusted** [comment]
See my comment on the issue over https://phabricator.wikimedia.org/T256132 it's explained their.

**Comment by zoranzoki21** [comment]
Yes, thanks for great work!

**Comment by Gusted** [comment]
We can't track the issue(We can't do anything about it) I resolved the stats for now and will be pushed by next release.

**Comment by Gusted** [comment]
No problems!

**Comment by Gusted** [comment]
Not sure if you need to open another issue to get it accepted you can copy paste my message to get it resolved, it explained also how to fix this. I consider it as a small task to fix this on their side.

**Comment by zoranzoki21** [comment]
> Not sure if you need to open another issue to get it accepted you can copy paste my message to get it resolved, it explained also how to fix this. I consider it as a small task to fix this on their side.

You mean to open another task on Wikimedia's Phabricator?

**Comment by zoranzoki21** [comment]
I've reopened task on Wikimedia's Phabricator.

**Comment by Gusted** [comment]
I saw, I will hold a eye in it and provide any resources/info if needed from our side.

**Comment by zoranzoki21** [comment]
OK, thanks again! :smiley:
