### ISSUE TITLE
[Slightly Broken Website] Discord guilds navbar issue using darkified light theme

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#2925]
**Website**
https://discord.com/channels/@me

**How to Reproduce**
1. Go to Discord
2. Login
3. Enable light theme
4. Enable dark reader darkify

**Expected behavior**
It should be awesome as always !

**Actual behavior**
It is actually awesome ! There's only a slight (opacity ?) issue with the guilds navbar.

**Screenshots**

![image](https://user-images.githubusercontent.com/21284089/85486429-e8160580-b5ca-11ea-9273-cfa164147e25.png)

**System info:**
 - OS: Windows 10.2004.19631.1
 - Browser: Chrome
 - Darkreader Version: 4.9.9
 
**Additional context**
Honestly I'm surprised no one tried that ever before, it's awesome.
Just truly dark instead of gray :)

**Comment by Gusted** [comment]
I have the application that's why I never tried it :-) I will have a look soon and see what the fix should be

**Comment by Gusted** [comment]
Idk how but it's somewhere broken in a parent element not sure which as discord is pretty heavy on uneccassry elements.

**Comment by Gusted** [comment]
![](https://i.imgur.com/ciEZs77.png) 
Got potential fix but you see they have a mask that make it cirlcy & Dim it..... So removing it will make it not more roundy

**Comment by KaKi87** [comment]
What about fixingt the mask color ?

**Comment by Gusted** [comment]
Not sure if that works as the mask is also includes transition? I'm making now a workaround in CSS to recreate it without any mask.

**Comment by KaKi87** [comment]
Nice work, thanks !

**Comment by Gusted** [comment]
Fully fix with transition so the mask is now uneccasry

Not sure if I have the right value with transition and border-radius but close enough :-)
