### ISSUE TITLE
[BUG] Wikipedia color examples are changed

### ISSUE THREAD

**Issue by votlu** [darkreader/darkreader#2926]
### **Describe the bug**

Color examples (as shown on the right side of https://en.wikipedia.org/wiki/Olive_(color) ) are changed from the expected listed color.

### **Steps to reproduce**

- Go to https://en.wikipedia.org/wiki/Olive_(color)
- Enable Dark Reader
- Colors on the right will no longer match the color information below it

### **Expected behavior**

The colors in the example boxes should not be changed by Dark Reader

### **Actual behavior**

Dark Reader modifies the colors based on user settings.

### **Screenshots**

![Annotation 2020-06-23 230641](https://user-images.githubusercontent.com/25809479/85494497-c7d44f80-b5a6-11ea-81de-8c267fc203fe.png)

### **System Information:**
 - OS: Windows 10 2004
 - Browser: Firefox 77.0.1
 - Dark Reader version: 4.9.9

**Comment by Gusted** [comment]
Oh that will be easy fix will make a quick fix when home
