### ISSUE TITLE
[Broken Website] Stripe

### ISSUE THREAD

**Issue by kkoomen** [darkreader/darkreader#2928]
**Website**
https://stripe.com/blog/official-nodejs-support

**Expected behavior**
Code block must contain white text when darkreader is on.

**Actual behavior**
The code blocks don't change color and are still black.

**Screenshots**
<img width="958" alt="Screen Shot 2020-06-24 at 16 18 33" src="https://user-images.githubusercontent.com/10693490/85521165-6f4c9300-b636-11ea-9933-ff9c5f07df49.png">

**System info:**
 - OS: MacOS
 - Browser: Firefox
 - Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
![](https://i.imgur.com/48CFPcX.png) Windows & Chromium

**Comment by kkoomen** [comment]
I have this not on my personal laptop, which is weird since my work laptop has almost no extensions besides darkreader. I'll close it for now since it's not darkreader I guess.

**Comment by kkoomen** [comment]
My bad, reopening. Issue still occurs after the page was fully loaded.

**Comment by Gusted** [comment]
![](https://i.imgur.com/nsA7Zy9.png) Firefox?

**Comment by GalaxySH** [comment]
Not on chrome (os), or firefox (w and mobile).

**Comment by kkoomen** [comment]
I still have it. Still not fixed yet.

**Comment by Gusted** [comment]
![](https://i.imgur.com/8jEsbsK.png) It's being set to inherit that if it just is correct should be the white-ish color. Could be something due MacOs :/

**Comment by GalaxySH** [comment]
Wouldn't that make it a problem with MacOS Firefox, not DR?

**Comment by Gusted** [comment]
Could be. Maybe other factors like another extension that change the color.

**Comment by kkoomen** [comment]
> Maybe other factors like another extension that change the color.

No it is darkreader. I created a new firefox profile with nothing but the darkreader extension and I still have the problem. Hence it's darkreader.

**Comment by Gusted** [comment]
It has to be. Could you open the devtools and check what the `color:` is?

**Comment by kkoomen** [comment]
<img width="1581" alt="Screenshot 2020-07-13 at 20 29 32" src="https://user-images.githubusercontent.com/10693490/87304559-892a1900-c504-11ea-8c39-16b452c5c86d.png">

Apparently `inherit`.

**Comment by Gusted** [comment]
What if you click on computer and click on the little arrow beside 'color'

**Comment by kkoomen** [comment]
<img width="1555" alt="Screenshot 2020-07-13 at 20 36 43" src="https://user-images.githubusercontent.com/10693490/87305152-88de4d80-c505-11ea-91e9-323423a6227b.png">

**Comment by Gusted** [comment]
Hmm that's weird it's showing the right color in computed but it isn't displayed as that color... Browser bug :(

**Comment by kkoomen** [comment]
<img width="753" alt="Screenshot 2020-07-13 at 21 14 42" src="https://user-images.githubusercontent.com/10693490/87308479-d4472a80-c50a-11ea-880f-4053a347485b.png">

This is my browser version. Test it if you like.

**Comment by Gusted** [comment]
Could you have a look how the site looks in Firefox Developer Edition? It's on v79

**Comment by kkoomen** [comment]
You can do that by yourself. I don't use that.

**Comment by Gusted** [comment]
For me it looks good. I'm currently working with a older version of normal Firefox due some compatibility issues I need to check for dark reader. Could simply browser bug that's been fixed.

**Comment by Gusted** [comment]
Should be fixed in 4.9.23
