### ISSUE TITLE
[BUG] "Use system colour scheme" doesn't work?

### ISSUE THREAD

**Issue by JaneSmith** [darkreader/darkreader#2935]
### **Describe the bug**

Firstly, I'm not entirely sure how the "Use system colour scheme" setting is supposed to work, so it's possible that I'm misunderstanding the feature. I couldn't find any explanation or documentation for this specific feature.

That said, I'm assuming it's supposed to work either by my operating system's colour scheme, or the Firefox colour scheme. If that's the case, then it isn't working for me. Both my OS and Firefox are set to dark mode, and yet if I tick "Use system colour scheme", the extension immediately turns off dark mode and goes to light mode.

### **Steps to reproduce**

- Open the Dark Reader UI menu via the toolbar button.
- Click on the "⋮" button near the top-right corner of the UI.
- Tick "Use system colour scheme".

### **Expected behavior**

Dark Reader should stay in dark mode, while my OS and Firefox are set to dark mode. Later, when my OS and/or Firefox are set to light mode, Dark Reader should switch appropriately.

### **Actual behavior**

Dark Reader immediately disables dark mode, despite my OS and Firefox being set to dark mode.

### **System Information:**
 - OS: Fedora Silverblue 32
 - Browser: Firefox 77.0.1 via Flathub
 - Dark Reader version: 4.9.9

### **Additional context**

Again, I'm not sure what "system colour scheme" is actually referring to, so it's possible that I'm misunderstanding this feature. I'd appreciate any explanation. I'm running Fedora Silverblue as my OS, and I switch to the `Adwaita-dark` theme when I'm in a dark environment. I'm also switching Firefox to its dark theme (via the "Customise" section).

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/2722

Seems like same bug make sure to read it trough and come back with info you found out. Aka most likely fedora.
Auto mode watch for your Systems color

**Comment by JaneSmith** [comment]
Thanks for the quick reply. The `matchMedia('(prefers-color-scheme: dark)').matches;` test was handy. I'm not quite sure what was going on, as it's actually working fine now, so I apologise for wasting your time. I am absolutely certain that it wasn't working when I submitted the bug report, but I had since then restarted Firefox - perhaps that was necessary to get it to work right?

So just to clarify for future reading, with Fedora/Linux and Firefox 77, the "Use system colour scheme" setting *is* working, and it updates automatically when the system theme changes between "Adwaita" and "Adwaita-dark".

Thanks.

**Comment by Gusted** [comment]
Oh restart Firefox heard that one a lot that's a common bug. It seems like Firefox cache the result if your system is dark when opening it(Just Linux?)

**Comment by Gusted** [comment]
Btw no problems! Never hesitate to open up a bug report

**Comment by Gusted** [comment]
Yes
