### ISSUE TITLE
[Broken Website] Lowes.com Product Page

### ISSUE THREAD

**Issue by norsehealer** [darkreader/darkreader#2936]
**Website**
example page https://www.lowes.com/pd/Whirlpool-7-cu-ft-Electric-Dryer-White-While-Supplies-Last/50354426
any of the product pages have this issue.

**How to Reproduce**
An example of this is
> 1. Go to Lowes.com site
> 2. Keep clicking products until you see the product page
> 3. See that the product image isn't shown.

**Expected behavior**
I expect to see a normal image like I do on Home Depot's website. 
https://www.homedepot.com/p/Whirlpool-7-0-cu-ft-240-Volt-White-Electric-Vented-Dryer-with-Wrinkle-Shield-Plus-WED5000DW/205541551 
posting a quick link to a product where the images are visible.

**Actual behavior**
when viewing a product page on lowes.com, i dont see an image. when turning DR off, I can see the image. (see screenshot)

**Screenshots**
https://i.imgur.com/1FTQ3eY.png
left is with Darkreader; right is without

**System info:**
 - OS: Windows 10
 - Browser: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
 - Darkreader Version: 4.9.9

**Additional Information**
I double checked and I dont believe the Lowes website is using transparent background images.

**Comment by Gusted** [comment]
Any errors in console?

**Comment by norsehealer** [comment]
> notice:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
satellite-5ca42c7a64746d2d090097bd.js:19 
> Uncaught ReferenceError: UET is not defined
    at f (satellite-5ca42c7a64746d2d090097bd.js:19)
    at HTMLScriptElement.n.onload.n.onreadystatechange (satellite-5ca42c7a64746d2d090097bd.js:19)
those are the 2 errors but i'm not sure what i'm looking for.

**Comment by Gusted** [comment]
Those by brave ad-blockers it self nothing special, IL have a look soon

**Comment by norsehealer** [comment]
Is there a way to copy my Darkreader settings to see if that's the problem?  I use Dynamic for most sites.

**Comment by Gusted** [comment]
No I think i know the error already

**Comment by Myshor** [comment]
I found the problem... They bend background of the page color with picture.

Only fix for this is to disable this bending.

Fix PR is ongoing. ;)

**Comment by Gusted** [comment]
Had the wrong Issue number 😅

**Comment by Myshor** [comment]
Yea... I make fix and find it already. 🤣
