### ISSUE TITLE
[BUG] Twitter invisible / slow

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#2946]
### **Describe the bug**

Twitter is invisible / slow, depending on which mode is selected.

### **Steps to reproduce**

- Go to Twitter

### **Expected behavior**

Twitter is fast and fully visible.

### **Actual behavior**

Twitter is slow and/or invisible.

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox latest stable
 - Dark Reader version: Latest stable

### **Additional context**

As a workaround, I disable Dark Reader for twitter.com, and use the website's built-in dark theme.

**Comment by Gusted** [comment]
Hi!

I was unable to reproduce this.
It costed 4 seconds to load it and another second(By Twitter itself we don't touch that part)  to load the rest & images.
You also mentioned that twitter is invisble, do you have any other add-on installed? Or do you know you had modified firefox settings?
I used dynamic mode, which specific mode caused this for you?

Regards,
Gusted
