### ISSUE TITLE
[BUG] Gmail slow

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#2947]
### **Describe the bug**

Dark Reader makes Gmail slow.

### **Steps to reproduce**

- Go to Gmail

### **Expected behavior**

Gmail is fast.

### **Actual behavior**

Gmail is slow.

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox latest stable
 - Dark Reader version: latest stable

### **Additional context**

As a workaround, I am disabling the extension for Gmail, and using Gmail's built-in dark theme.

**Comment by Gusted** [comment]
Please please blame gmail for this, it is just a big big website use built-in's dark theme for this site.
I'l close this issue as previous debugging showed it's just small optimization's that we can push but ill not improve that much to get this issue not anymore.
