### ISSUE TITLE
[Broken Website] geizhals.at : images not visible in dropdown menu

### ISSUE THREAD

**Issue by 5georgeK** [darkreader/darkreader#2948]
**Website**
Give the link to the website
https://geizhals.at

other domains from this company:
https://geizhals.eu/
https://geizhals.de/
https://skinflint.co.uk/
https://cenowarka.pl/

**How to Reproduce**

> 1. Go to site
https://geizhals.at/2132300

> 2. Hover over button
"11 weitere Varianten mit Angeboten"

**Expected behavior**
icons should be visible while hovering over the button

**Actual behavior**
no icons visible

**Screenshots**

![ssdsdsd](https://user-images.githubusercontent.com/66057987/85836146-78547600-b796-11ea-8475-921212271add.jpg)

**System info:**
OS: Windows 10 Pro 64bit
Browser: Chrome 64bit 83.0.4103.106
Darkreader Version: 4.9.9

**Comment by Gusted** [comment]
It's known issue with their site let me know if you find any others :D
