### ISSUE TITLE
Dragging should be prohibited

### ISSUE THREAD

**Issue by dnknn** [darkreader/darkreader#2959]
![0627044837](https://user-images.githubusercontent.com/10995302/85900049-b488e480-b831-11ea-854f-48edb8c0b974.png)

Just like CSS `{-webkit-user-drag:none;}`

**Comment by Gusted** [comment]
Uh what? I don't understand what you trying to mena.

**Comment by dnknn** [comment]
> Uh what? I don't understand what you trying to mena.

Sometimes such an operation is triggered unintentionally👇 
![2](https://user-images.githubusercontent.com/10995302/85902776-6080fe80-b837-11ea-9d44-ab5680a3624c.gif)

**Comment by Gusted** [comment]
which browser

**Comment by dnknn** [comment]
> which browser

[CentBrowser](https://www.centbrowser.com/) (the latest version) (Chromium⁸⁰ kernel)

**Comment by Gusted** [comment]
![](https://i.imgur.com/s9qfZmq.png)

That should be a bug with the browser itself.
`user-select: none` prevents that `dragging` 
Can you select the text and see selection?
Like this
![](https://i.imgur.com/IvLalfA.png)

**Comment by dnknn** [comment]
> Can you select the text and see selection?

no.

`user-select: none` is no problem. 
The problem of dragging is not 100% reproducible.
I don't know what happened, it may be a bug in the browser itself.
![111](https://user-images.githubusercontent.com/10995302/85952063-78709380-b999-11ea-9ca7-7a39ea43f41d.gif)

**Comment by Gusted** [comment]
Yeah I guess so the user-select should prohibit any selection and by that any `dragging`
