### ISSUE TITLE
[Broken Website] Pinterest browser extension

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#2965]
**Website**

The Pinterest browser extension is unusable as long as Dark Reader is enabled.

**How to Reproduce**

> 1. Pin a website.

**Expected behavior**

Able to pin the website.

**Actual behavior**

The Pinterest view is either invisible or stalls forever, depending on Dark Reader mode configuration.

**System info:**
 - OS: Windows 10
 - Browser: Firefox latest stable with Pinterest extension
 - Darkreader Version: Latest stable
 
**Additional context**

Most websites can find a suitable view by tweaking the per-domain Dark Reader mode. However, even when Dark Reader is disabled for both amazon.com and pinterest.com, somehow Dark Reader still screws up the Pinterest extension, rendering it unusable.

**Comment by Gusted** [comment]
#1222 Uhm will have a look later today?
