### ISSUE TITLE
[BUG] Darkreader has stop working on multiple sites (like Twitter and Twitch)

### ISSUE THREAD

**Issue by SixelAlexiS90** [darkreader/darkreader#2969]
All of the sudden Darkreader doesn't work anymore on multiple sites like Twitter.com, Twitch.tv and ResetEra.com

### **System Information:**
 - OS: [Windows 10 Pro, Version 1909]
 - Browser: [Chrome  83.0.4103.116]
 - Dark Reader version: [4.9.11]

**Comment by Gusted** [comment]
Did you had any site-specific options for those site?
Do other sites still work?

**Comment by SixelAlexiS90** [comment]
> Did you had any site-specific options for those site?
> Do other sites still work?

Yes, I have specific filters for all the sites that doesn't work anymore ("Only for ####" selected). The general filter works tho.

**Comment by Gusted** [comment]
Ah it's has been fixed a hotfix will be pushed. For now see this for a workaround https://github.com/darkreader/darkreader/issues/2966#issuecomment-650746341
Sorry for the inconvenience!

**Comment by SixelAlexiS90** [comment]
> Ah it's has been fixed a hotfix will be pushed. For now see this for a workaround [#2966 (comment)](https://github.com/darkreader/darkreader/issues/2966#issuecomment-650746341)
> Sorry for the inconvenience!

Yep, that's the bug! I'll use the workaround for more use intensive sites while I'll wait for the hotfix. Thank you very much for your hard work <3!!!
