### ISSUE TITLE
[BUG] Not longer working for gmail

### ISSUE THREAD

**Issue by StevenLi-DS** [darkreader/darkreader#2972]
The extension is no longer working for gmail and it seems like there is an update for gmail since I saw some new settings

![demo](https://user-images.githubusercontent.com/33796896/85966460-dc8d5a80-b98d-11ea-95af-4a5bc3d61bed.gif)

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
 - Dark Reader version: 4.9.11

**Comment by eldorel** [comment]
I want to confirm this, and add that it seems to be an issue with the 'Dynamic' rendering mode on the new update.

I'm seeing dynamic mode not working correctly on most google pages, cisco's meraki UI, and a handful of other pages.

**Comment by scaomath** [comment]
I have the same problem as well for gmail if the mode is chosen to be "Dynamic", in addition to several other pages.

**Comment by Gusted** [comment]
#2969

**Comment by Gusted** [comment]
![](https://i.imgur.com/S8IdtlD.png) NVM we are not detecting the style

**Comment by Gusted** [comment]
Hmm found related errors
![](https://i.imgur.com/LxAyg21.png)

**Comment by alexanderby** [comment]
We will fix it soon. As a workaround try disabling custom built-in Gmail theme, choose a default one.
<img width="265" alt="Screen Shot 2020-06-29 at 16 45 15" src="https://user-images.githubusercontent.com/9638588/86013650-0bf0a580-ba28-11ea-8d55-74c4d92d5da7.png">

**Comment by leumasme** [comment]
@alexanderby does this only fix for gmail with background or also
> most google pages, cisco's meraki UI, and a handful of other pages.

**Comment by alexanderby** [comment]
@leumasme I haven't seen the problem in Google pages. Maybe it's related to another bug with custom themes, that is already fixed. You had to click "Only for ..." to reset a custom theme for a website.

**Comment by leumasme** [comment]
Ah yup, changing from custom to default (and back) fixed it, thanks.

**Comment by eldorel** [comment]
I want to confirm that the hotfix/update pushed out today does fix the issue on all of  the pages I've tested so far. 

As a note: it wasn't exclusively the custom gmail themes (or even just google-owned pages), as the issue was also affecting the Meraki system manager site, our office unifi controller management page, the google hangouts site,  and a few other random sites that I encountered yesterday. 

I don't even see that these pages share a common library or anything, so I'm not sure what the issue was.

**Comment by scaomath** [comment]
> We will fix it soon. As a workaround try disabling custom built-in Gmail theme, choose a default one.
> <img alt="Screen Shot 2020-06-29 at 16 45 15" width="265" src="https://user-images.githubusercontent.com/9638588/86013650-0bf0a580-ba28-11ea-8d55-74c4d92d5da7.png">

I want to confirm that the hot fix as of I am writing the comment works for the custom themes as well (only not for the Matrix theme, dark bg with green texts).
