### ISSUE TITLE
[Feature Request] Enable permanently on specific websites (even if it's turned off)

### ISSUE THREAD

**Issue by sn0wyfall** [darkreader/darkreader#2975]
Hi! 

I'm wondering if there could be a way to keep this enabled for specific websites, even when the extension is disabled. The reason is that I like the way it looks on specific sites and want it to stay like that on those sites. 

Thank you :)

**Comment by Gusted** [comment]
Don't disable the extension.
Use.
Sitelist -> Inverted Site only
Type here the specific websites you want.

**Comment by sn0wyfall** [comment]
Thank you for the reply! I actually like using the other option, so unfortunately I don't know if that workaround would work for me. So when I turn the extension on it darkens all websites except the sites on the exceptions list. What I wanted is that, even when I turn it off, specific sites would stay dark. Would that be a possible setting?

**Comment by Gusted** [comment]
No, tuned off is turned off. The exception list is the only option

**Comment by Gusted** [comment]
Their's a ON/OFF for a specific reason
