### ISSUE TITLE
[Question] Is there a way to see what CSS DarkReader is injecting?

### ISSUE THREAD

**Issue by sn0wyfall** [darkreader/darkreader#2976]
I want to permanently enable dark mode for a particular website, irrespective of my Dark Reader setting. I figured the best way to do this would be to find out what CSS Dark Reader was injecting into the website. Then, I could create a custom style in Stylish that themes the website as such. 

So is there a way to tell how Dark Reader is changing the CSS of the website? I tried using the inspect element tool, but I don't think the CSS there is being updated with the modified CSS.

**Comment by alexanderby** [comment]
Hi, try using this script:

```javascript
Array.from(document.querySelectorAll('.darkreader:not(.darkreader--cors):not(.darkreader--fallback):not(.darkreader--inline)'))
  .map(s=>Array.from(s.sheet.cssRules)
    .map(r=>r.cssText)
    .join('\n')
  )
  .join('\n')
```

But there can be issues, because inline style sheets (stored in "style" attributes) will be ignored and the order of the stylesheets can be wrong.

**Comment by sn0wyfall** [comment]
Thanks a lot! This is super cool, pretty much what I wanted! You're right, it doesn't work on sites like YouTube, but it's good enough. Thanks!
