### ISSUE TITLE
[Broken Website] (Waterfox Classic) developer.mozilla.org Dynamic Theme will not load

### ISSUE THREAD

**Issue by TheRealPSV** [darkreader/darkreader#2984]
**Website**
https://developer.mozilla.org/en-US/

**How to Reproduce**
An example of this is
> 1. Make sure DarkReader is set to Dynamic theme
> 2. Go to https://developer.mozilla.org/en-US/
> 3. Site will not darken

**Expected behavior**
Site should darken.

**Actual behavior**
Dark theme is not applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/6434386/86203131-34fd5d00-bb32-11ea-95ad-b07a6d95426f.png)

**System info:**
 - OS: Win10 x64
 - Browser: Waterfox Classic v2020.06
 - Darkreader Version: 4.9.13
 
**Additional context**
Only the Dynamic theme is broken. Filter, Filter+, and Static all work fine. Toggling to other modes and back to Dynamic or toggling DR off and back on doesn't work, site goes back to being light after reenabling.

Checked in Firefox and Chrome, bug doesn't apply to those browsers.

**Comment by Gusted** [comment]
Any errors in console?

Waterfox Classic is based on a old Firefox. Dark reader & Waterfox Classic = Not best combination.

**Comment by TheRealPSV** [comment]
No, no errors unfortunately.

Yeah I'd switch to the newer one but I really don't want to lose the status/addon bar I have with Classic.

**Comment by TheRealPSV** [comment]
After trying to narrow it down, I think it's from this commit: https://github.com/darkreader/darkreader/commit/e878fdd1908c80ccdeff2a5076e4c336fd460a1c

**Comment by Gusted** [comment]
Hmm, I don't see 123 that should break compatability.

**Comment by TheRealPSV** [comment]
I'm pretty sure it's related to that commit somehow. In `src/generators/modify-colors.ts`, the `getBgPole()` function (and other functions too) are returning 'auto', when they used to return hex colors. It might be an underlying issue with something else that's incompatible that was exposed when the 'auto' check was removed.

**Comment by TheRealPSV** [comment]
Now this is weird, while trying to debug things it suddenly started working perfectly.

I'm wondering if Waterfox was somehow caching the old "auto" values for some reason. I must have cleared it out somehow while debugging. I probably should've started by testing a clean profile, sorry for wasting your time with this @Gusted.

Feel free to close the issue; unless someone else runs into the same thing, there's probably not much left to mention here, unless you want to set something to clean those "auto" values out on a new update. But if no one else's brought it up since the update it likely isn't enough of a problem to bother with it anyway.

**Comment by Gusted** [comment]
We will see 
/shrug didn't saw any other user with it. It could be the case it still was caching it's weird issue.
