### ISSUE TITLE
[Broken Website] pub.dev

### ISSUE THREAD

**Issue by jpnurmi** [darkreader/darkreader#2990]
**Website**
https://pub.dev/

**How to Reproduce**
> 1. Go to https://pub.dev/

**Expected behavior**
Dark background.

**Actual behavior**
White background.

**Screenshots**
![image](https://user-images.githubusercontent.com/140617/86270261-3fb80080-bbcb-11ea-9a71-582632762cd0.png)

Usually it helps to refresh a few (~5) times, but while taking taking these screenshots, I had to refresh 16 times to get dark mode:
![image](https://user-images.githubusercontent.com/140617/86270424-8148ab80-bbcb-11ea-82b3-3be1fd514daf.png)

**System info:**
 - OS: Debian 11
 - Browser: 83.0.4103.116 (Official Build) (64-bit)
 - Darkreader Version: 4.9.13
 
**Additional context**
The problem appeared recently, probably the latest update.

**Comment by Gusted** [comment]
Hmm, I couldn't reproduce it so the let's go trough the basic troubleshoot test.

1. Any other extension active on this site?
2. Try it on a private tab(With Dark Reader allowed on Private tab's)
3. Any errors in console when it's not darkened?

**Comment by jpnurmi** [comment]
Ha, thanks for opening my eyes! Looks like a conflict with uBlock Origin, should've guessed... :)

**Comment by Gusted** [comment]
No problems!

**Comment by jpnurmi** [comment]
It must be something else, after all. It still happens occasionally whilst Dark Reader is the only enabled extension. Furthermore, it turns out that I'm actually able to reproduce the problem in incognito mode too, if I just keep refreshing the front page.

1. No other extensions enabled besides Dark Reader
2. Happens in a private tab too
3. No errors appear in console

The front page, occasionally, when something goes wrong:
![Screenshot from 2020-07-03 18-33-03](https://user-images.githubusercontent.com/140617/86486761-783b1400-bd5c-11ea-9723-d28ca48713bd.png)

Same thing for a package page:
![Screenshot from 2020-07-03 18-40-03](https://user-images.githubusercontent.com/140617/86486862-bc2e1900-bd5c-11ea-980d-60a12b6c8e45.png)

For reference, the same pages when dark mode works:
![Screenshot from 2020-07-03 18-41-54](https://user-images.githubusercontent.com/140617/86486904-ea135d80-bd5c-11ea-9631-549f9d5bbcc2.png)

![Screenshot from 2020-07-03 18-40-12](https://user-images.githubusercontent.com/140617/86486863-bd5f4600-bd5c-11ea-8a2f-7ec747f9e265.png)

**Comment by Gusted** [comment]
Yeah, I still can't reproduce this.

Reinstall Dark Reader?

**Comment by jpnurmi** [comment]
Re-installing Dark Reader didn't seem to change anything.

When the background remains white, there's a section in <head> that looks like:
```html
<style class="darkreader darkreader--sync" media="screen"></style>
  <link href="/static/css/style.css?hash=mjg80dt7337a29qajcacli6ar8mjf47t" rel="stylesheet" type="text/css"><style class="darkreader darkreader--cors" media="screen">*{box-sizing:border-box}body{background-color:#fff;... lots of css...}</style><style class="darkreader darkreader--sync" media="screen"></style>
```

When dark mode loads fine, the same section looks like:
```html
<style class="darkreader darkreader--sync" media="screen"></style>
  <link href="/static/css/style.css?hash=mjg80dt7337a29qajcacli6ar8mjf47t" rel="stylesheet" type="text/css"><style class="darkreader darkreader--sync" media="screen"></style>
```

Does that ring any bells?

**Comment by Gusted** [comment]
See the odds I'm running stock
![](https://i.imgur.com/2MV6813.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/gyFrlP0.png)
Running latest commit....

**Comment by Gusted** [comment]
Pretty sure #3004 Had something to do with it.
[build.zip](https://github.com/darkreader/darkreader/files/4871365/build.zip)
Please test if this build works for you.

**Comment by jpnurmi** [comment]
Awesome, I think it works now! Thank you!
