### ISSUE TITLE
[Broken Website] Mixcloud.com

### ISSUE THREAD

**Issue by thinker5555** [darkreader/darkreader#2995]
**Website**
[mixcloud.com](https://www.mixcloud.com/)

**How to Reproduce**

1. Go to mixcloud.com
2. Select any song to play.  For example [this one](https://www.mixcloud.com/ChillSpace/botanikal-fire-psytology-mix/)
3. Click the play button to the left of the song name and above the sound wave display.  Play button will go invisible.
4. Player bar will appear at the bottom of the window and start playing music.  Play/Pause button, back arrow, forward arrow, and duration/progress line will be invisible.

**Expected behavior**

All controls should be visible, such as play, forward and back buttons, and the duration/progress line.

**Actual behavior**

- The play button on the song page goes invisible once play starts, leaving only the circle around it.  
- The player bar at the bottom of the window has a completely invisible play button (both in play and pause status), and the arrows above the back-30-seconds and forward-30-seconds buttons are invisible.  Also, the duration/progress line will only show the played portion rather than the full line and the circle indicator of the current play time.

**Screenshots**

Note: the pink arrows note the spots where the controls go invisible.

Darkreader disabled for mixcloud.com:
<img width="1779" alt="mixcloud_light" src="https://user-images.githubusercontent.com/31991986/86281537-b3e2ac00-bbab-11ea-8fb8-b2ec15cc8af4.png">

Darkreader enabled for mixcloud.com
<img width="1788" alt="mixcloud_dark" src="https://user-images.githubusercontent.com/31991986/86281535-b218e880-bbab-11ea-8caf-840b6ac991b4.png">

**System info:**

 - OS: MacOS Catalina 10.15.5
 - Browser: Firefox 78.0.1
 - Darkreader Version: 4.9.13
 
**Additional context**

This has been going on at least since the middle of March, if not earlier.  I've also noticed it on Chrome, before I switched to Firefox a little over a month ago.

I also tried this in private mode with only Darkreader allowed, and the same behavior occurred.

**Comment by Gusted** [comment]
Fixed!

**Comment by thinker5555** [comment]
Dang you're fast!  :-)  Thanks!

**Comment by Gusted** [comment]
I'm used to it :)
