### ISSUE TITLE
[BUG] Settings panel open only once every four clicks

### ISSUE THREAD

**Issue by Vanille-N** [darkreader/darkreader#3000]
### **Describe the bug**

Settings fail to open on the first click on the Dark Reader icon, and instead open only on the third click.

They then open once every 4 clicks instead of every other click.

### **Steps to reproduce**

Click on the Dark Reader icon (Firefox menu bar)

### **Expected behavior**

*click* settings open
*click* settings close
*click* settings open
*click* settings close
*click* settings open
etc...

### **Actual behavior**

*click* weird arrow appears
*click* weird arrow disappears
*click* settings open
*click* settings close
*click* weird arrow appears
etc...

### **Screenshots**

Put mouse on icon
![image](https://user-images.githubusercontent.com/58042063/86334395-7171ab80-bc4d-11ea-902f-7072fd846af2.png)
Click once
![image](https://user-images.githubusercontent.com/58042063/86334455-82bab800-bc4d-11ea-8ac9-eaca90ea89d0.png)
Click again
![image](https://user-images.githubusercontent.com/58042063/86334485-8d754d00-bc4d-11ea-9f52-3504157b5f3a.png)
Click again
![image](https://user-images.githubusercontent.com/58042063/86334342-5f900880-bc4d-11ea-9afc-8b52f47eca3d.png)

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 77.0.1
 - Dark Reader version: 4.9.13

### **Additional context**

Frequency: 100%, even if I wait a long time between the first two clicks and the next one.

Workaround: triple click to open settings.

**Comment by Gusted** [comment]
You can have a try reinstall the add-on as this is something we can't control and can rely to a browser bug.

**Comment by Vanille-N** [comment]
Will try reinstalling. Thanks anyway.
