### ISSUE TITLE
[Broken Website] The Rust Programming Language Book

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#3001]
**Website**
https://doc.rust-lang.org/book/

**How to Reproduce**
Visit the site

**Expected behavior**
![image](https://user-images.githubusercontent.com/4723091/86360236-eda4c880-bc26-11ea-9294-4f04346bb6c6.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/4723091/86360254-f4334000-bc26-11ea-82d7-d2f3ef1cc504.png)

**System info:**
 - OS: macOS 10.14.6
 - Browser: Google Chrome 83.0.4103.97 (Official Build) (64-bit)
 - Darkreader Version: 4.9.13

**Comment by Gusted** [comment]
![](https://i.imgur.com/ND5YrQt.png)
1. Any other extension that could interfere?
2. Which mode are you on Dark Reader?
3. Try on a private tab with Dark Reader acces to it.

**Comment by LoganDark** [comment]
1. I don't know
2. Dynamic
3. Funnily enough the glitch didn't happen until the second time I loaded the page, but it still does happen in incognito

**Comment by Gusted** [comment]
![](https://i.imgur.com/AaXLQn7.png) Their your go. Blame the website devs

**Comment by LoganDark** [comment]
> Their your go. Blame the website devs

Uhhh, what? That's it?

Could you add a setting to disable that please?

**Comment by Gusted** [comment]
It means it's moving it's position very fast and analyzing it over and over again can cause high CPU Usage and lagg.

We will not add a setting to disable instead we will fix it

**Comment by LoganDark** [comment]
> We will not add a setting to disable instead we will fix it

Your last reply made it seem like you wouldn't fix it. Did you change your mind?

**Comment by Gusted** [comment]
No, the owner of Dark Reader will had a look so big changes it will be fixed.
