### ISSUE TITLE
[Feature Request] Dynamic/filter mode settings per-site

### ISSUE THREAD

**Issue by sn0wyfall** [darkreader/darkreader#3008]
**Is your feature request related to a problem? Please describe.**
Sometimes some websites don't work at all with Dynamic mode, so I have to enable Filter mode even though I prefer Dynamic mode. However, this changes the setting globally. 

**Describe the solution you'd like**
It would be nice to make the dynamic/filter mode setting site-specific, and move the current (global) setting to the global settings page.

**Comment by Gusted** [comment]
https://darkreader.org/help/en/#custom-site-settings
Thank you for reading the help page

**Comment by sn0wyfall** [comment]
Sorry, the Safari version doesn't have it so I didn't realize
