### ISSUE TITLE
[BUG] Dark Reader Updates Wipe Out Custom CSS in Dev Tools - Why???

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#3012]
I got the latest firefox. DR updates wipes out all my custom CSS in its dev tools. Why the hell is this happening?? Now I cant recover what I saved. Why is this happening???

**Comment by Gusted** [comment]
Custom CSS?

**Comment by koolx** [comment]
> 
> 
> Custom CSS?

Uhhh yeah.. duhhh

**Comment by Gusted** [comment]
Define Custom CSS on your words everyone have their own version of it with different meanings

**Comment by koolx** [comment]
> 
> 
> Define Custom CSS on your words everyone have their own version of it with different meanings

Youre kidding me.

**Comment by Gusted** [comment]
No I'm not kidding and you take this not even serious

**Comment by koolx** [comment]
> 
> 
> No I'm not kidding and you take this not even serious

You dont know what css is?? Youre not taking this seriously. I think youre trolling.

**Comment by Gusted** [comment]
I know what CSS is.
but you are talking about Custom CSS

**Comment by koolx** [comment]
> 
> 
> I know what CSS is.
> but you are talking about Custom CSS

Custom css can be placed in DR's dev tools.

**Comment by Gusted** [comment]
Okay than we on the same line
1. Did you accidentally press reset
2. Did you lost other saved settings?
3. For real CSS not related to dark reader use Stylus

**Comment by koolx** [comment]
> 
> 
> Okay than we on the same line
> 
>     1. Did you accidentally press reset
> 
>     2. Did you lost other saved settings?
> 
>     3. For real CSS not related to dark reader use Stylus

No i didnt click reset, no i only lost custom css. My css got erased from the updates. Css is related to DR as custom css can be pasted in its dev tools like I repeatedly told you. If you dont know this you dont know DR.

**Comment by Gusted** [comment]
I know the in and outs of Dark Reader.
It got lost thst isn't suspossed to happen their is no way to recover? why? CUSTOM CSS is not removed at update

**Comment by koolx** [comment]
> 
> 
> I know the in and outs of Dark Reader.
> It got lost thst isn't suspossed to happen their is no way to recover? why? CUSTOM CSS is not removed at update

It got lost a few times though updates. You really dont know DR at all. Seriously stop trolling. Its childish.

**Comment by Gusted** [comment]
I'm done with you
