### ISSUE TITLE
[Broken Website] frankerfacez.com

### ISSUE THREAD

**Issue by alazymeme** [darkreader/darkreader#3013]
**Website**
https://www.frankerfacez.com/

**How to Reproduce**
1. Go to the website
2. Navigate to any other page aside from the homepage
3. Enjoy the flashbang

**Actual behavior**
the homepage should be in the global dark list, but other parts of the website should not

**Screenshots**
Homepage: https://i.alazymeme.com/EnergeticGivenImage.png
About: https://i.alazymeme.com/AliveFancyImage.png
Donate: https://i.alazymeme.com/FairActiveImage.png

**System info:**
 - OS: Windows 10 Pro 2004
 - Browser: Microsoft Edge (Chromium) Version 83.0.478.58
 - Darkreader Version: 4.9.13

**Comment by Gusted** [comment]
Welp. That's always a bit unfortunate as we can't check every subdomain.
