### ISSUE TITLE
[BUG] Dark Reader Updates Wipe Out Custom CSS in Dev Tools - Why???

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#3014]
I got the latest firefox. DR updates wipes out all my custom CSS in its dev tools. Why the hell is this happening?? Now I cant recover what I saved. Why is this happening???

**As a side note... to the dev of this addon please be aware theres a troll trolling the threads here. I ask that you be aware of that since I'm sure you or a mod closed the thread due to that.

**Comment by Gusted** [comment]
Remaking a issue will not make a point.
