### ISSUE TITLE
[Broken Website] barclaycardus.com

### ISSUE THREAD

**Issue by kimpurcell** [darkreader/darkreader#3025]
**Website**
barclaycardus.com

**How to Reproduce**
1. Go to FICO https://www.barclaycardus.com/servicing/ficoScore

**Expected behavior**
FICO score and graphic should not be touched.

**Actual behavior**
FICO score and graphic is not visible / messed up.

**Screenshots**
![Screenshot 2020-07-05 04 51 33](https://user-images.githubusercontent.com/17389179/86530080-4371ae80-be7b-11ea-9619-c23d35382f32.png)

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.13
 
**Additional context**

**Comment by Gusted** [comment]
![](https://i.imgur.com/a9pvdXl.png) 

Yeah-
