### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by acalinescu-pentalog** [darkreader/darkreader#3031]
### **Describe the bug**

AWS console can't use dark reader, it worked a long time ago but since a few months it doesn't work. 

I didn't created a bug report before because I tought I can handle the white part of the site but now my eyes are crying lol.

### **Steps to reproduce**

You should just have an AWS account and to be logged in to be able to reproduce this.

https://aws.amazon.com/console/   -> login

bug reproduced.

### **Expected behavior**

I expect to have the control whether to enable or disable dark reader on AWS console.

### **Actual behavior**

You can see in the below screenshot that the dark reader is disabled for the AWS console.

The issue is that if I click on enable, nothing happens ! It just stays disabled and there's no dark mode.

### **Screenshots**

![image](https://user-images.githubusercontent.com/63298403/86574835-1ad2dd00-bf7f-11ea-96df-79d1fc45ac8d.png)

### **System Information:**
 - OS: Windows 10 May 2020
 - Browser: Firefox 78.0.1
 - Dark Reader version: 4.9.11

### **Additional context**

After fixing this, I'll gladly donate $5.

**Comment by alexanderby** [comment]
Hi, try updating to 4.9.13.

**Comment by acalinescu-pentalog** [comment]
Hello, I just upgraded to 4.9.13 but unfortunately it still does not turn my AWS console background into dark mode.

It's still the same bug happening.

**Comment by Gusted** [comment]
Hi @acalinescu-pentalog!

Can you show how your sitelist looks like?

**Comment by acalinescu-pentalog** [comment]
This was not a bug, this was just something I overlook, thanks to @Gusted for pointing that out!

As promised, I'll gladly donate $5.

Thank you @Gusted once again !

**Comment by acalinescu-pentalog** [comment]
Just donated under the name of Shobu Alex.

Thank you again ! 👯

**Comment by Gusted** [comment]
![](https://i.imgur.com/uevverH.png) Received :D

**Comment by ageddawi** [comment]
Would anyone be willing to share the fix for this? I have the same problem. The site on the extension drop down menu has a little x on it compared to all other sites. Tried resetting the CSS settings from the Developer Options but no luck :(

**Comment by Gusted** [comment]
Well @acalinescu-pentalog said that it was something in the SiteLIst so asume either `amazon.com` or `aws.amazon.com` is on it. That causes to be disabled.

**Comment by acalinescu-pentalog** [comment]
Hey @ageddawi, I was using only the new version. Related to the sitelist and I think the extension default to one behavior, either make an exception for those or only be active on those sites...

I totally cleared out my site list as it was full of crap because I was using the only for .... behaviour when I wanted to use the except behaviour...

The extension started to work flawlessly afterwards...

**Comment by ageddawi** [comment]
Ya'll are amazing, thank you so much for the prompt response! My eyes are happy because of you

**Comment by Gusted** [comment]
> Ya'll are amazing, thank you so much for the prompt response! My eyes are happy because of you

No problems! Have a great day.

@acalinescu-pentalog Thanks for the additional information!

**Comment by acalinescu-pentalog** [comment]
@ageddawi no worries, I wish you have happy eyes for as long as possible!

@Gusted It's the least I can do, I saw someone needing help for something that I needed help and since you helped me first I felt like this might be my turn to help someone haha :D
