### ISSUE TITLE
[Feature Request] Leave automatic scheduling turned on if user manually toggles dark mode

### ISSUE THREAD

**Issue by phoenixeliot** [darkreader/darkreader#3039]
**Is your feature request related to a problem? Please describe.**
I really like the feature of scheduling the extension to enable/disable at certain times, or to match the OS. However, sometimes I want to override this and set it to dark early. I find it frustrating that **manually changing the enabled state of the extension disables the automatic scheduling**, and when I use my computer the next day I realize I have to go back to dig into the settings to turn back on automatic scheduling.

This also comes up when sometimes I just need to disable the extension for 5 minutes to do some color-specific work in my browser, and I turn the whole thing off instead of turning it off for just one site.

**Describe the solution you'd like**
Automatic scheduling should stay active even if the user manually toggles the extension. Whenever the automatic trigger (time, or OS color setting) changes, it should still set the extension to match whatever the trigger says, even if this doesn't change what mode the extension is in.

When the user manually changes the enabled state, it should _stay_ that way until an automatic trigger would change it.

So, if it's daytime, and I set it to dark:
- it should stay dark until the next trigger
- the dark trigger should leave it in dark mode
- then the light trigger in the morning should turn it back to light mode, and it should be back on its automatic schedule until/unless I change the state manually again.

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Have a look at how the new buttons works and their behavior
