### ISSUE TITLE
[Feature Request] Make automatic scheduling menu more visible

### ISSUE THREAD

**Issue by phoenixeliot** [darkreader/darkreader#3040]
**Is your feature request related to a problem? Please describe.**
I love this extension, and was hoping that someday it might have automatic scheduling. I almost even started filing a feature request for it, but then I found that it _does_ have it, it's just incredibly well hidden. I didn't notice the "..." menu at all before finding someone describe it by searching for this feature.

**Describe the solution you'd like**
The automatic scheduling menu should be much more visible to someone who is looking for automatic scheduling.
Some ideas:
- use a text link like "automatic" or "schedule" above or below the on/off toggle.
- perhaps have a much more visible gear icon (the universal "settings" icon) somewhere in the extension window.
- add a full size button or toggle to the right of "On | Off" for the Auto settings

**Additional context**
The current hidden tiny low-contrast menu button:
<img width="281" alt="Screen Shot 2020-07-07 at 1 46 02 PM" src="https://user-images.githubusercontent.com/491376/86834802-8472ea00-c058-11ea-95ad-1c5e563cb2aa.png">

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Their you go
