### ISSUE TITLE
[BUG] it says: "Loading, please wait" forever

### ISSUE THREAD

**Issue by rumpumpel1** [darkreader/darkreader#3044]
### **Steps to reproduce**

- click on the Dark Reader symbol

### **Expected behavior**

The theme changes into dark

### **Actual behavior**

it says "Loading, please wait" forever

### **System Information:**
 - OS: Windows 10 Enterprise (2004)
 - Browser: Firefox 60.9.0 esr
 - Dark Reader version: 4.9.14

### **Additional context**

Unclear what it is loading, it's a theme and it has been installed, so why loading?

**Comment by Gusted** [comment]
It's loading as a error occur. Probably someting due compatabilty.

**Comment by Gusted** [comment]
The latest ESR is 68.10.0esr 
I can't get my hands on older ones. Please update to the latest version (of ESR)
