### ISSUE TITLE
[BUG] negative z-index does not work with dark reader

### ISSUE THREAD

**Issue by elleven11** [darkreader/darkreader#3047]
### **Describe the bug**

The dark reader extension makes sites with z-index<0 not show the element with that attribute, e.g. https://projectstream.it/ (the div with class name: "video-container" is replaced by a dark grey background.

### **Steps to reproduce**

- Go to https://projectstream.it/
- A background video should appear'
- It does not appear with the extension activated because of the negative z-index of the div

**Comment by Gusted** [comment]
Yeah but we don't do any- any- anything related with z-index or that logic.
