### ISSUE TITLE
[BUG] it says "Loading, please wait" forever

### ISSUE THREAD

**Issue by rumpumpel1** [darkreader/darkreader#3051]
### **Steps to reproduce**

- Click on Dark Reader

### **Expected behavior**

The theme changes

### **Actual behavior**

a windows appears which says: "Loading, please wait"
this window stays forever

### **System Information:**
 - OS: Windows 10 Enterprise (2004)
 - Browser: Firefox 60.9.0 esr (64 bit)
 - Dark Reader version: 4.9.14

**Comment by Gusted** [comment]
Don't open another https://github.com/darkreader/darkreader/issues/3044#issuecomment-655605754
