### ISSUE TITLE
[Broken Website] techpowerup.com

### ISSUE THREAD

**Issue by anubis-genix** [darkreader/darkreader#3053]
Link: https://www.techpowerup.com/
OS: Windows 10 x64
Browser: Firefox 78.0.1
Dark Reader: 4.9.14 and 5.0 Preview

Problem: Bright borders

![grafik](https://user-images.githubusercontent.com/40500650/87022952-7697a300-c1d7-11ea-88ba-d8ad99b01207.png)

**Comment by Gusted** [comment]
Their site is overriding us, nothing we can do.
