### ISSUE TITLE
[BUG] DarkReader does not work on any page and widget fails to load. 

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#3054]
### **Describe the bug**

Darkreader does not work anymore and the widget does not load. 

### **Steps to reproduce**

I dont know how to reproduce on another machine. 

### **Expected behavior**

Widget loads, DarkReader converts webpages. 

### **Actual behavior**

None of that happens. 

### **Screenshots**

![Screenshot_20200709_113651](https://user-images.githubusercontent.com/6344099/87023770-81066c80-c1d8-11ea-8210-3d5d0ebf9fda.png)

### **System Information:**
 - OS: KaOS
 - Browser: Firefox current
 - Dark Reader version: current

### **Additional context**

None of the sites work.

**Comment by Gusted** [comment]
Using current isn't a valid versiongivebit a tryb
To reinstall the addon and reopen Firefox.

**Comment by ShalokShalom** [comment]
I did so multiple times.

**Comment by alexanderby** [comment]
Gi, try open [about:devtools-toolbox?type=extension&id=addon%40darkreader.org](about:devtools-toolbox?type=extension&id=addon%40darkreader.org), do you see any errors in Console?

**Comment by ShalokShalom** [comment]
![Screenshot_20200709_171226](https://user-images.githubusercontent.com/6344099/87057620-613a6d00-c207-11ea-92ad-9c0734ca326b.png)

**Comment by alexanderby** [comment]
Try click ">" at one of these "Quota" errors, so I can see the stack trace.

**Comment by ShalokShalom** [comment]
![Screenshot_20200709_215317](https://user-images.githubusercontent.com/6344099/87084492-9d34f880-c22e-11ea-80f4-dd0b7a827ba5.png)

**Comment by ShalokShalom** [comment]
Here is what I get, when I click on it: 

view-source:moz-extension://4b14f30f-4e72-49a4-98a9-6967633528e5/public/js/background.js

**Comment by alexanderby** [comment]
First I should ask, where did you install Dark Reader from? Our background script is `background/index.js`, but here it is `public/js/background.js`.

Second, are you using custom CSS themes? The size limit is 5MB in Chrome, Firefox don't tell the limit and has no API to check. We can also add "Unlimited storage" permission.

Try running `chrome.storage.local.get(null, s => console.log(new Blob([JSON.stringify(s)]).size, 'bytes'))` to get the used size in bytes.

**Comment by alexanderby** [comment]
False alarm, that might be Facebook Container extension by Mozilla. I don't know what it does here. These errors are not related to Dark Reader.

Try run `chrome.tabs.create({url: location.href.replace('background', 'ui/popup')})` and press F12. Do you see errors in console?

**Comment by ShalokShalom** [comment]
This is not running in Firefox, the command just gets sent into the default search engine. 
chrome.tabs.create is a feature only found in Chrome and Chrome-based browsers, I believe.

**Comment by Gusted** [comment]
replace `chrome` with `browser` and it should be able to run in Firefox

**Comment by ShalokShalom** [comment]
Does not work.
