### ISSUE TITLE
[BUG] Where has the font-change option gone in version 5 preview settings?

### ISSUE THREAD

**Issue by Momoske** [darkreader/darkreader#3058]
### **Describe the bug**

The new v5 preview settings panel looks and feels great, more modern and nicer to use.
However, I cannot find any way to access the font-change options in the new settings page. Please, I really hope this doesn't mean the feature is getting removed - it's awesome! Please bring the settings option back in the actual v5.0 update.

### **Steps to reproduce**

- Enable v5 settings preview
- Cannot find font-change feature anywhere

### **Expected behavior**

I should be able to find the option to toggle the font-change feature on/off, either for all website or just the current one, just like in v4.9.x

### **Actual behavior**

I have to revert back to the old design just to be able to use the font-change option.

### **System Information:**
 - OS: Windows 10 v2004
 - Browser: Edge v86.0
 - Dark Reader version: v4.9.14

**Comment by Gusted** [comment]
Not implented yet.

**Comment by Momoske** [comment]
> Not implented yet.

Awesome to hear it's not going away, as far as I understand. Thanks a lot for the quick reply (definitely the quickest I've ever witnessed, lol), best of luck for the next updates!

**Comment by Gusted** [comment]
We will only add features :)
