### ISSUE TITLE
[BUG?] How to overlay all the styles?

### ISSUE THREAD

**Issue by ProgrammingLife** [darkreader/darkreader#3065]
I'm trying to overlay all the styles of https://duckduckgo.com
So I've come with the simple manual settings like this:
```
*

CSS
* {
    background-color: #222 !important;
    border-color: #666 !important;
    color: #666 !important;
}
```
So this setting can't overlay the description text. Only a title and some other text on the page. But why? What to do for overlaying all the styles?
I think it might work like this because my CSS-style works before the DuckDuckGo's styles. But how can I execute my CSS after website's css?

ENV:
**Firefox:** 78.0.1

**Comment by Gusted** [comment]
How is this related to Dark Reader?

**Comment by ProgrammingLife** [comment]
@Gusted This is the feature of Dark Reader called "Dynamic theme editor".

**Comment by Gusted** [comment]
Yes, I know. But it's to **FIX** a site when Dark Reader didn't did it's job.

**Comment by ProgrammingLife** [comment]
@Gusted I just want to change all the styles of any website with Dark Reader. Is that possible to get with Dark Reader?

**Comment by Gusted** [comment]
What are you trying to achieve? Dark reader darkens every style that is what it's been build for.

**Comment by ProgrammingLife** [comment]
@Gusted I'm trying to manually set background-color and color to some fixed values for simplicity.

**Comment by Gusted** [comment]
Use static theme.

**Comment by ProgrammingLife** [comment]
@Gusted How to do it with Static Theme? I've been trying to change **background-color** and the font **color** using statis theme editor but it seems too complicated for me. Can you provide me with a little example on how to change **background-color** and **color** for all the styles?

**Comment by Gusted** [comment]
https://darkreader.org/blog/v4-9/

**Comment by Gusted** [comment]
![](https://i.imgur.com/wreJDJi.png)
