### ISSUE TITLE
[BUG] Ugly Yellow Color on Headers of Text - Please Fix

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#3068]
Very strange. I have 2 issues. First, every update of DR breaks my custom css in its dev tools. Never had that happen before until new updates about 3 weeks ago. 

2nd, on sites I notice yellow color on headers of text. I can understand why thats done to make headers stand out.. But in so doing, it does 2 things.. 1) is makes that text dull and ugly, and 2) it removes any customized css from overriding it. 

Below are screen shots circled in red. Please dont mess with this anymore. DR is perfect without it. 

![1](https://user-images.githubusercontent.com/8130105/87206933-a7abcc80-c2d8-11ea-89c1-9aa1c77e868e.png)

![2](https://user-images.githubusercontent.com/8130105/87206938-ad091700-c2d8-11ea-9873-a7e7603ada38.png)

**Comment by Gusted** [comment]
Custom CSS isn't meant for the devtools, it could be that it was interfering with a incoming change. 

Yellow color??? That is something we don't.

**Comment by koolx** [comment]
Dev tools has css so what are you talking about? I was able to modify elements on webpages by adding css to dev tools. You dont know how DR works.

The yellow color is present on headers and subheaders. I turned off stylus and the yellow is still present so the only way it affects it is through DR.

Are you the same dude harassing us here before? If you are I suggest you stop disrupting the forum.

**Comment by Gusted** [comment]
Yes, CSS to use fix sites. Not to personalize sites. I know very good how Dark Reader works.

Is the `yellow` color still present when you turn of dark reader? If so applicable a screenshot how it looks like without the yellow-ish.

No I'm a new maintainer that fixs bugs and tries to resolves issue and help users. For the other guy however he wasn't harrassing he was simply trying to help people and he still active around this platform and not forum.

Regards,
Gusted

**Comment by koolx** [comment]
You said css cant be added to dev tools. It actually can as I proved before. If youre "very good how Dark Reader works" why dont you know this? 

Then you said the other guy (which I think is YOU) wasnt harassing and trolling others which he/you was. 

For these reasons I dont believe you at all. 

I already uploaded 2 screen shots.. thats more than enough.

**Comment by Gusted** [comment]
> CSS to use fix sites. Not to personalize sites. I know very good how Dark Reader works.

I never stated you can't add CSS :)

Oh you didn't meant Myshor. Oh the other person was me I totally forgot 😅 I have a lot issues to handle.

The 2 screenshot you apply are darkreader on and where I can't see any yellow within the red circle.

**Comment by koolx** [comment]
Uhhhh... thats what i used it for and updates still erased all my css. 

If you cannot discern the yellow in my pics but everyone else I've showed it to can I dont know what to say.

**Comment by Gusted** [comment]
Move your CSS to Stylus instead of the dev tools from now on. 

Could you give me the color code for both elements where the yellow is?

**Comment by alexanderby** [comment]
@koolx You had a week to delete your abusive comments, but instead you keep commenting in a toxic manner. By the power vested in me by GitHub, I put a permanent ban on your activity in our repository.
