### ISSUE TITLE
[BUG] Line Separator in Notion

### ISSUE THREAD

**Issue by stankovictab** [darkreader/darkreader#3069]
**Website**
https://www.notion.so/

**How to Reproduce**
> Create a page in Notion
> Turn on Dark Reader

**Expected behavior**
The line separator element should be visible.

**Actual behavior**
The line separator element isn't visible.

**Screenshots**
Added.

**System info:**
Chrome on Windows, Dark Reader version 4.9.15
 
**Additional context**
I know it's a small issue but I'm impressed with how the extension is handling the site. 🥇

This is the default dark mode on the site with the line separator visible.
![Annotation 2020-07-11 030418](https://user-images.githubusercontent.com/62820268/87213157-3cd3b300-c323-11ea-93d1-1f785504e707.jpg)
This is it with dark reader.
![Annotation 2020-07-11 030359](https://user-images.githubusercontent.com/62820268/87213168-4d842900-c323-11ea-811b-03881d2fe752.jpg)

**Comment by Gusted** [comment]
![](https://i.imgur.com/4BhAFA6.png)
