### ISSUE TITLE
Modal window on Firefox appears with system scrollbars and black areas

### ISSUE THREAD

**Issue by risualiser** [darkreader/darkreader#307]
![main_settings](https://user-images.githubusercontent.com/35914376/37864947-8d6559a0-2f86-11e8-8f41-18630e9535f2.png)
![sites_list](https://i.imgur.com/E5AWjRK.png)
![dev_tools](https://i.imgur.com/Z8702Le.png)

**Comment by alexanderby** [comment]
It should have gone in next release. There is no built-in ability to customize scrollbar color in Firefox, so grey color will stay.

**Comment by risualiser** [comment]
Scrollbars are gone and black areas appear only when switching popup menu tabs.

**Comment by alexanderby** [comment]
I think it's a browser bug.

**Comment by alexanderby** [comment]
I've made a patch for that black regions.

**Comment by risualiser** [comment]
Great, there are gone.
