### ISSUE TITLE
[Broken Website] spy-cards.lubar.me

### ISSUE THREAD

**Issue by BenLubar** [darkreader/darkreader#3070]
**Website**
https://spy-cards.lubar.me/

**How to Reproduce**

1. Go to https://spy-cards.lubar.me/
2. Click any card to flip it face-up
3. Note that the text on the card is white-on-white

**Expected behavior**
The site uses `<meta name="color-scheme" content="dark light">` to notify browsers that it supports both dark and light mode natively and prefers dark mode if the user has no preference. The extension shouldn't be touching the site.

**Actual behavior**
The extension attempts to turn the already-dark-mode page dark, resulting in some oddities (the titles of the cards are inverted) and unreadable text on the cards.

(I'm not personally a darkreader user, so I don't have screenshots or metadata to provide, but a user asked me about this.)

**Comment by Gusted** [comment]
AFAIK their isn't a official meta for color-scheme and could be any developer interpret a other way. However it's dark by default so I will add it to the Dark by default list.
