### ISSUE TITLE
[Broken Website] Github commit is broken for custom background color

### ISSUE THREAD

**Issue by kevinhwang91** [darkreader/darkreader#3072]
**Website**
https://github.com/darkreader/darkreader/commit/e6ebf3f335a6ebef2ab6e4ca5b2ea188a8d448ce

Purple syntax highlighting is difficult to distinguish.

**How to Reproduce**

1. Set custom background color to #282c34
2. Go to the website of github commit

**Expected behavior**
The default setting for darkreader:
![image](https://user-images.githubusercontent.com/17562139/87222548-ee67f800-c3a6-11ea-97f6-9c2d54f66c78.png)

**Actual behavior**
Custom background color:
![image](https://user-images.githubusercontent.com/17562139/87222423-1a36ae00-c3a6-11ea-88b2-b06b4980b5fd.png)

**System info:**
 - OS: ArchLinux
 - Browser: Chromium
 - Darkreader Version: 4.9.15
 
**Additional context**

**Comment by Gusted** [comment]
Do you have custom filter settings?

**Comment by kevinhwang91** [comment]
In addition to the custom background color, the other is the default configuration.

**Comment by Gusted** [comment]
We can't fix anything that involves not standard configuration as we can't fix anything specific for a specific background color

**Comment by kevinhwang91** [comment]
Thanks, I think I should custom github myself.
