### ISSUE TITLE
[BUG]is there a way to get the top banner of the popup longer

### ISSUE THREAD

**Issue by alpha1one** [darkreader/darkreader#3074]
top banner of the app is too narrow on the real tip. is there a way to smooth it out and make its thing longer?

**Comment by Gusted** [comment]
Which banner? Next time fill out the format else we are unable to help

**Comment by alpha1one** [comment]
the banner on top of the app. oh you mean the format of my browser. its arial font and normal font.

**Comment by Gusted** [comment]
No I mean the format which you not sticked to but made up 2 sentences without any clue or context whatsoever.

**Comment by alpha1one** [comment]
oh i see what you sayin. I mean when you click on the app the app pops ups and then you see on the top of it the box is rectanglualr but its like too narrow so wanna make that longer on the real.

**Comment by Gusted** [comment]
This is more like a feature request which will not be implemented.
