### ISSUE TITLE
[BUG]thread was closed but someone said its a feature request for the future

### ISSUE THREAD

**Issue by alpha1one** [darkreader/darkreader#3075]
hi yall. someone in my post about making the app longer said is a feature request. does that mean that we have to wait for it to be out on in the future or do it mean that it has to be enuf people on here to support it?

**Comment by Gusted** [comment]
Hey could you stop opening useless issues? First this is a issue not a post. Second this is not a forum where users react just a platform for developers to manage their issues etc. I already said this WILL NOT BE IMPLEMENTED.
