### ISSUE TITLE
[BUG]is it possible to add a background pics on sites with dr?

### ISSUE THREAD

**Issue by alpha1one** [darkreader/darkreader#3076]
hi yall. i was wondering if it was possible to add a background image or pics to some sites or all sites using dr. i mean like a pic i find on the net or a pic from my harddrive. how would that be possible

**Comment by Gusted** [comment]
Not dark reader related very off-topic.

**Comment by alpha1one** [comment]
what does you mean off topic. are you saying it cant be done

**Comment by Gusted** [comment]
It can be done but you don't need dark reader for that.
btw your thinking this is a forum idea something that Koolx(blocked user) also hadded and funny enough your thinking the same and had your account created today. So stop block evasionm
