### ISSUE TITLE
Make the new design a toggle and don't force it, it honestly looks worse than the current one

### ISSUE THREAD

**Issue by hichemfantar** [darkreader/darkreader#3077]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Gusted** [comment]
Opinions... We will force it probably when everything is implemented and fixed. I'm not sure if we hold the old UI in our codebase on a later moment. 1 thing for sure our new code changes and features will not get placed in the old UI.

**Comment by alpha1one** [comment]
i does agree with hichemfantar. you need to make a new design.

**Comment by GalaxySH** [comment]
Does that mean there will be opportunity to alter the new UI at all? I also liked the toggle.
