### ISSUE TITLE
Is there any fix of w3schools' try it yourself?

### ISSUE THREAD

**Issue by agwEgamE** [darkreader/darkreader#3082]
Some site like this
https://www.w3schools.com/cssref/tryit.asp?filename=trycss_background-color
Dark reader darken the result which affected user to know what is the actual result.
So is there any solution that let Dark reader not affect the result?
I have tried IGNORE INLINE STYLE but not working.
```
================================
w3schools.com

IGNORE INLINE STYLE
iframe
iframe *
#iframeResult
#iframeResult *
body[contenteditable="false"]
body[contenteditable="false"] *

================================
```
Am I misuse the  IGNORE INLINE STYLE ?
Also could I just target the tryit.asp something like 
```
================================
w3schools.com/*/tryit.asp?=*
...
```
Sorry that those questions look silly and maybe wrong, newbie here.

Toggling the Dark Reader to know the actual result seem like a silly move, therefore I look forward to receive any suggestion. Thank you.

**Comment by Gusted** [comment]
Nope no solutions to this other than I don't know if ignoring it is a good idea. I use the tryout personally to fast get a reproduce case of a bug with it(about a specific css property)

**Comment by agwEgamE** [comment]
> 
> 
> Nope no solutions to this other than I don't know if ignoring it is a good idea. I use the tryout personally to fast get a reproduce case of a bug with it(about a specific css property)

You mean something like this?
```
CSS
#iframeResult{
background-color: white !important;
}
body[contenteditable="false"]{
background-color: initial;
color: initial;
border-color:  initial;
}

body[contenteditable="false"] * {
background-color: initial;
color: initial;
border-color:  initial;
}
```

Also is `IGNORE INLINE STYLE` not work for all element? and what is the proper way to use this?
I have read the ubuntu example and it work, but not work for iframe?

Moreover, what is the match patterns for URLs? Is this same as this https://developer.chrome.com/extensions/match_patterns?

Thanks for reply.

**Comment by Gusted** [comment]
No it's more the get something like https://www.w3schools.com/cssref/pr_list-style-image.asp and use their tryout the get a working/valid idea how it works that help me made to this #2488 For that kind of purpose.

Oh the IGNORE INLINE STYLE is special section it was more made for some specific use cases like color-pickers that use inline style `<p style="color: red" class=".color-picker">Hi If their is a .color-picker under IGNORE INLINE STYLE I will be red else I will be a darker red chosen by Dark Reader</p>`. 

The Match pattern is now very specific and doesn't work with * that easily however I already have a open PR for this #2517 But we first need to proceed with 'smaller' breaking changes before we proceed pushing the new URL patterns.

**Comment by agwEgamE** [comment]
> 
> 
> No it's more the get something like https://www.w3schools.com/cssref/pr_list-style-image.asp and use their tryout the get a working/valid idea how it works that help me made to this #2488 For that kind of purpose.
> 
> Oh the IGNORE INLINE STYLE is special section it was more made for some specific use cases like color-pickers that use inline style `<p style="color: red" class=".color-picker">Hi If their is a .color-picker under IGNORE INLINE STYLE I will be red else I will be a darker red chosen by Dark Reader</p>`.
> 
> The Match pattern is now very specific and doesn't work with * that easily however I already have a open PR for this #2517 But we first need to proceed with 'smaller' breaking changes before we proceed pushing the new URL patterns.

So is this possible that provide a attribute such as `dark-reader-bypass` and use :not(dark-reader-bypass) to bypass darken them.
And maybe add the attribute to target after load the page via js? Something like this?
```
var bypass= document.createAttribute("dark-reader-bypass");
window.addEventListener('DOMContentLoaded', (event) => {
document.querySelector('#iframeResult').attributes.setNamedItem(bypass);
});
```

**Comment by Gusted** [comment]
No. 
I actually think people will fill bug files that we don't dark readerify the tryout of w3 schools when we do this.

**Comment by agwEgamE** [comment]
It is possible that provide element picker just like how adblocker let user to pick what to block, and dark reader can provide some option ui for user to cutomize selected element such as invert it, custom style like background-color:${white}; or ignore this element?

**Comment by Gusted** [comment]
I've been thinking about a element pucker but unfortunately it's on a low priority and it will recuire a lot of logic to make all thinks work how it should.

**Comment by Gusted** [comment]
Answer to Issue `No and their won't be`.
