### ISSUE TITLE
[Broken Website] yandex.*/maps

### ISSUE THREAD

**Issue by Rakleed** [darkreader/darkreader#3087]
**Website**
https://yandex.ru/maps/

**How to Reproduce**
1. Go to https://yandex.ru/maps/ site
2. Wait 2–5 seconds

**Expected behavior**
The map stays with a dark background.

**Actual behavior**
After 2–5 seconds, the map changes the background to light.

**Screenshots**
![image](https://user-images.githubusercontent.com/19418601/87234990-6f42e600-c3df-11ea-9cf3-b0097efc9f34.png)

**System info:**
 - OS: Windows 10 v. 2004
 - Browser: Google Chrome 83
 - Darkreader Version: 4.9.15
 
**Additional context**
This has been discussed here at https://github.com/darkreader/darkreader/pull/2837#discussion_r439621297.

**Comment by Gusted** [comment]
What if you try `.map-container ymaps` Instead of the > > >

**Comment by Rakleed** [comment]
Still not working.

**Comment by Gusted** [comment]
![](https://i.imgur.com/ccCsPUZ.png) Does your devtools looks like this?

**Comment by Rakleed** [comment]
No. I can’t even find the classes that are displayed by you.
![image](https://user-images.githubusercontent.com/19418601/87235207-76b7be80-c3e2-11ea-8e56-61c702a5f933.png)

**Comment by Gusted** [comment]
Oh a canvas.
`.map-container > ymaps > ymaps > canvas`

**Comment by Rakleed** [comment]
Yes, it works. Thanks!
