### ISSUE TITLE
[BUG] Can't Make Certain Changes To Sites

### ISSUE THREAD

**Issue by HaajPaaj** [darkreader/darkreader#3089]
While on Urban Dictionary to give an example of this issue, I'm not sure if this happens on other sites, but I cannot like a post with the extension enabled, regardless of font changes. 
Settings: Dark Mode
Brightness: Off
Contrast: +5
Sepia and Greyscale: Off
Font: Comic Sans MS
Theme Engine: Dynamic
Edit: This Also Affects Timers on Sites

**Comment by Gusted** [comment]
Define make certain changes?

**Comment by HaajPaaj** [comment]
Well just the fact that changes to sites, mostly relating to numbers increasing and decreasing will not happen while the extension is active. This doesn't happen on all sites, and it is unknown if it is just me, but you are welcome to try urban dictionary as an example.

**Comment by Gusted** [comment]
Maybe you just don't notice the change +5 is small and could be unnoticeable easily what if you try a higher value?

**Comment by HaajPaaj** [comment]
Nope, nothing to do with that sadly. Upped mine all the way to 50 and i could see it even clearer than before.

**Comment by Gusted** [comment]
Could it be that you monitor calibration is setted so that you just don't see what's changed? We also could have a heck into the code if the certain changes had been pushed.

**Comment by HaajPaaj** [comment]
I use a laptop, and I wouldn't know how to view that information. Sorry if it seems obvious.

**Comment by Gusted** [comment]
Hmm make sure the brightness of your laptop is al the way up. And give it another try I guess you just can't see the difference but it's their because some sites work.

**Comment by HaajPaaj** [comment]
That's awfully weird. Brightness has nothing to do with it as the issue had just resolved itself. The Timers are back to normal as well.

**Comment by Gusted** [comment]
Uhm okay weird lol.

**Comment by Gusted** [comment]
Uhm okay weird lol.
