### ISSUE TITLE
[Feature Request] Microsoft Edge Device Synchronization

### ISSUE THREAD

**Issue by Salil999** [darkreader/darkreader#3092]
**Is your feature request related to a problem? Please describe.**
In Google Chrome, I see an option to synchronize options between devices as seen here:
![Screen Shot 2020-07-12 at 1 42 38 PM](https://user-images.githubusercontent.com/8891729/87254079-a0ee9800-c445-11ea-85d2-3befdd6b170c.png)

However, I don't see this option in Microsoft Edge:
![Screen Shot 2020-07-12 at 1 42 56 PM](https://user-images.githubusercontent.com/8891729/87254085-ab109680-c445-11ea-844b-d7d104a71570.png)

**Describe the solution you'd like**
I would like to have settings synchronization across devices for any DarkReader supported browser. I'd like to see it in Microsoft Edge (personal bias there), but ideally support for every browser should exist.

**Comment by Gusted** [comment]
It's syncing by default. I just added a option to disable it. Microsoft edge isnt updated yet.
