### ISSUE TITLE
[Broken Website] Old Reddit.com 

### ISSUE THREAD

**Issue by tophercullen** [darkreader/darkreader#3095]
**Website**
Old Reddit site style *while* logged in. https://ww.reddit.com/r/all with appropriate preferences set.  

**How to Reproduce**
> 1 Go to https://www.reddit.com
> 2. Log in.
> 3. Go to 'preferences'
> 4. Uncheck 'Use new Reddit as my default experience'
> 5. Open https://www.reddit.com/r/all in a *background tab*. (e.g. ctrl or center click the link)
> 6. Wait for the page to finish loading in the background tab
> 7. Foreground that tab. 
> 8. Reload the tab.
> 9. Background the tab again by returning to the first tab, or opening a new tab.
> 10. Reload the now back-grounded tab.
> 11. Wait for the page to finish loading in the background tab
> 12. Foreground that tab. 

**Expected behavior**
Pages (re)loaded in background tabs are in dark mode.

**Actual behavior**
Pages (re)loaded in background tabs are not fully dark mode, or not at all.

**Screenshots**
![Screenshot (41)](https://user-images.githubusercontent.com/11668155/87297977-96281780-c4c6-11ea-98d2-1572442b24d9.png)
![Screenshot (43)](https://user-images.githubusercontent.com/11668155/87297981-97594480-c4c6-11ea-92b9-bfdd2c051b02.png)

**System info:**
 - OS: Windows
 - Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
 - Darkreader Version: 4.9.15
 
**Additional context**
 > 1. you can do this without logging in and using the the base url of https://old.reddit.com. However it seems to be a lot less consistent, resulting in a ~40%-50% failure rate compared to logging in, which is almost 100%.  I have no idea why this is the case..
> 2. Screenshots show additional extensions enabled. I also tested incognito with all extensions disabled. The results where the same.  
> 3. I've been using Darkreader for years without issue. Suddenly, a week or two ago, this has started happening on multiple sites including but not limited to slack, github and reddit. I'm not sure what is causing it (chrome or darkreader). So far the only place I've been able to create a consistent reproducer is Reddit. Everything else is seemingly at random. If I'm able to create a consistent reproducer for them I'll open additional issues.

**Comment by Gusted** [comment]
Step 4 to 10 litterly sounds like stress testing dark reader.

**Comment by tophercullen** [comment]
I don't follow this logic at all. How is the process outlined anything but a normal use case?

 I think perhaps you are misunderstanding the reproducer. Step 7 shows the page is broken when load in the background. Step 8 shows a reload of the same page in the foreground is correct. Step 9 and 10 show the page breaking again if reloaded in the background. So the reproducer is not a stress this, its trying to very clearly highlight an issue while loading or reloading pages in background tabs. 

Still even if that were the case, see 'Additional context' point 3. Countless times, I've open several tabs in the background, in quick succession and I've *never*, not once, seen this issue before.

**Comment by Gusted** [comment]
Hmm we have a function that was actually made for this case that it's reloaded in the background. So I don't have a clue how this happened I will see if I can have a reproduce on this. Btw do you have any extension for reddit?

**Comment by tophercullen** [comment]
>  Btw do you have any extension for reddit?

Yes, normally I do. However, see 'Additional context' point 2,

**Comment by Gusted** [comment]
could you make a recording? I'm unable to reproduce this case. As of few weeks back we switched some things that could be related I will hold it in mind.

**Comment by tophercullen** [comment]
Screen cap below
[screen-capture.zip](https://github.com/darkreader/darkreader/files/4912717/screen-capture.zip)

For the purposes of the test, I created brand new reddit user. The only thing change was the redesign opt out.

**Comment by Gusted** [comment]
Hmm doing the exact thing i just couldn't reproduce it.

**Comment by tophercullen** [comment]
> Hmm doing the exact thing i just couldn't reproduce it.

I've been able to replicate it on 3 completely different computers. 2 laptops and one desktop each with different generations of hardware, and both linux and windows. I even setup a portable version of chrome fresh with *only* darkreader (no sync, no other extensions, apps etc), to eliminate any unknowns. They *all* reproduce the issue with the brand new Reddit test user I created. 

> On the white sites, do you see any errors?

What kind of errors? In the dev console there appear to be 17 additional errors on the white pages. Here's the console dump for each to compare.

[www.reddit.com-dark.log](https://github.com/darkreader/darkreader/files/4914168/www.reddit.com-dark.log)
[www.reddit.com-white.log](https://github.com/darkreader/darkreader/files/4914169/www.reddit.com-white.log)

**Comment by Gusted** [comment]
Hmm intresting dark reader is generating Bugs :D That's something I can work with. I will have a quick look where the error proceeds and give some steps to see what's happening in your envirement as I just can't reproduce it.

**Comment by Gusted** [comment]
Okay so to able to get debug info.
Is their in any case that after you visited the site and than go back to another site and go reload that site it still will be white?

**Comment by tophercullen** [comment]
> Is their in any case that after you visited the site and than go back to another site and go reload that site it still will be white?

Only if the reload is in a background tab. If the reload happens in the foreground, everything appears to dark mode correctly and it is never white

**Comment by Gusted** [comment]
[2020-07-14 00-08-37.zip](https://github.com/darkreader/darkreader/files/4915434/2020-07-14.00-08-37.zip)
Exact steps like you did.

**Comment by tophercullen** [comment]
The steps look correct. A few things came to mind watching the video:

> 1 Are you using Google Chrome? The browser in the video looks like Firefox or possibly Vivaldi. I've tried Firefox and it does *not* reproduce this issue. It also exhibits the same style changing/reloading after foregrounding the tab seen in your video, which Chrome does not do. As noted before, I was able to reproduce the issue using a new install of chrome (using a portable Chrome installer such as this: https://portableapps.com/apps/internet/google_chrome_portable). 
> 2 The browser itself looks to be affected by a dark mode. Are you using a dark mode setting in the browser and/or the underlying OS? Some applications can detect the presence of an OS dark mode setting, and it changes the style. As noted above, I can replicate this issue on both Linux and Windows. But none of the OS or browsers have any other dark mode setting enabled.

**Comment by Gusted** [comment]
Brave chromium forked. I will have a check with Google Chrome portable.

**Comment by Gusted** [comment]
[2020-07-17 14-19-47.zip](https://github.com/darkreader/darkreader/files/4937696/2020-07-17.14-19-47.zip)
Portable.
And light mode.
Did some more `stress testing` but just still nothing

**Comment by tophercullen** [comment]
Looking for a common environment, I spun up and Sever 2019 EC2 instance, which is more or less windows 10.  I was able to replicate what *you* are seeing on it (e.g. unable to reproduce)

It also demonstrated the same extreme delayed rendering/loading that your videos showed, where it shows a blank screen for nearly 3s after clicking a tab, before it actually showed anything. This delayed behavior is *not* present on the windows 7 or Fedora machines I tested. The pages are displayed in <1s upon clicking the tab.  

Further, I've successfully reproduced this on OSX. This also does *not* have the delayed rendering/loading. 

I'm not sure if that delayed loading is relevant at all. Again, in the search of a common environment, I setup Fedore 32 in a VMware virtual machine. Not only does it reproduce the issue *with* a similar looking delay (because low performance), but the slow performance actually shows the page loading dark initially and then *changing* to white.

[linuxvmscreencap.zip](https://github.com/darkreader/darkreader/files/4939809/linuxvmscreencap.zip)
  
In any case, so far the *only* OS I've tested that is unable to reproduce this issue is, in fact, the one you are testing on: Windows 10.

**Comment by Gusted** [comment]
Sigh I guess I need to find my old Linux installation.

**Comment by tophercullen** [comment]
As I said before,  I replicated using Fedora 32 on a VMware (player, which is free) virtual machine. You should be able to do that as well. Given the nature of VMs, I presume it should replicate if the hypervisor is windows 10.

**Comment by Gusted** [comment]
Not for. My special laptop
1.1gHz Pentium N4200
4Gb DDR3

**Comment by tophercullen** [comment]
D-;

**Comment by tophercullen** [comment]
It appears to be working now. I have no idea what changed. Both dark reader and chrome versions are unchanged. I haven't restarted my computer, browser or anything either.....

**Comment by Gusted** [comment]
Maybe dark reader had a bad day 🤷🏽‍♀️

**Comment by Speedy2662** [comment]
This is closed but I'm still having this problem to this day, and it's not just a hiccup on a random day.

Dark Reader + RES is almost impossible to use no matter what mode you use - it'll either invert images, emojis, and other things it shouldn't - or it'll work partially with the exception of highlighted content (eg. when you click on a post, that highlight will be completely white)

This is on Dynamic mode:

![](https://i.imgur.com/e4OwSsS.png)
