### ISSUE TITLE
[Broken Website] manjaro.org

### ISSUE THREAD

**Issue by werymanen** [darkreader/darkreader#3096]
**Website**
https://manjaro.org/

**How to Reproduce**
An example of this is
> 1. Go to the [Manjaro](https://manjaro.org/) site
> 2. Turn dark reader off
> 3. See that there's an image that dark reader hides

**Expected behavior**
I expected the image to stay visible

**Actual behavior**
It was replaced with a dark background

**Screenshots**
Dark reader on: 
![manjaro_dr_on](https://user-images.githubusercontent.com/49951816/87311349-68bb8800-c51f-11ea-9f5b-d0cd3397b014.png)

Dark reader off: 
![manjaro_dr_off](https://user-images.githubusercontent.com/49951816/87311376-707b2c80-c51f-11ea-8db2-c41af28aec3b.png)

**System info:**
 - OS: Linux
 - Browser: Firefox 78.0.1 (64-bit)
 - Darkreader Version: 4.9.15

**Comment by Gusted** [comment]
Has something to due with `z-index` being applied to the image and how we set a background-color..... :(
