### ISSUE TITLE
[Feature Request] Add a delay to applying DarkReader Stylizations

### ISSUE THREAD

**Issue by Sylk** [darkreader/darkreader#3101]
**Is your feature request related to a problem? Please describe.**
On Jira, there's an issue with Dark Reader restyling components repeatedly that seem to be an alternating flashing color. My current solution is to disable Dark Reader, and then re-enable it after about 7 seconds have passed and jira is done loading. This resolves the issue with the components re-rendering repeatedly.

**Describe the solution you'd like**
A timer to delay the amount of seconds that need to pass before making any stylization changes.

**Comment by Gusted** [comment]
That will give you a good bright white flash into your eyes. I'm not sure implementing this into Dark Reader will make sense. (Specific use case)

**Comment by Sylk** [comment]
I use the light theme to make a solarized theme with Dark Reader. While it's not a default feature, it'd be something you could enable that would deal with strange component rendering.

**Comment by Gusted** [comment]
If their is a public demo of this example I could have a look. But so far I know Jira is enterprise

**Comment by Gusted** [comment]
Could you have a look at #3128 and see if could possible have the same bug with Jira?

**Comment by Sylk** [comment]
This is definitely the same error. Mark this as a duplicate and perhaps that's a Dark Reader general problem.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Gusted** [comment]
Make sure to subcribe to the other issue.

Merging into #3128
