### ISSUE TITLE
[Broken Website] Every Wix website has scrambled layouts and missing elements

### ISSUE THREAD

**Issue by CathodeRayBlues** [darkreader/darkreader#3116]
I have ran into problems when viewing several websites which were made on Wix.
Many objects were scrambled out of alignment, some were scaled incorrectly, and some disappeared entirely.
And because of the subdomain structure of Wix sites, I have to manually disable the darkreader on every individual site, and not just all sites made on the platform.

OS: Windows & Linux
Browser: Firefox
(probably reproduceable on other browsers/OSes but I have not tested)

**Comment by Gusted** [comment]
Example url's would be great

**Comment by CathodeRayBlues** [comment]
> Example url's would be great

https://www.cathoderayblues.com/
https://havronimorama.wixsite.com/boaz
https://www.catherinelevine.com/

You can take a look at the sites that my colleagues and I were building when we discovered the problem, then. 
Typically, background elements such as the black boxes on my page dissapear, and the "social media links" preset item has icons shifted around, usually resulting in one sitting beneath another.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/87865130-97978b00-c971-11ea-9ef7-22ab57f8948f.png)
Seems good to me?
I don't see scrambled layouts or any missing elements. As I get the same result without dark reader.

**Comment by CathodeRayBlues** [comment]
> ![image](https://user-images.githubusercontent.com/25481501/87865130-97978b00-c971-11ea-9ef7-22ab57f8948f.png)
> Seems good to me?
> I don't see scrambled layouts or any missing elements. As I get the same result without dark reader.

Try turning it off and refreshing, then look carefully. There are supposed to be social media icons at the footer of the page.

**Comment by CathodeRayBlues** [comment]
> > ![image](https://user-images.githubusercontent.com/25481501/87865130-97978b00-c971-11ea-9ef7-22ab57f8948f.png)
> > Seems good to me?
> > I don't see scrambled layouts or any missing elements. As I get the same result without dark reader.
> 
> Try turning it off and refreshing, then look carefully. There are supposed to be social media icons at the footer of the page.
Additionally, the behavior of the plugin appears to be slightly different, because you are not using Firefox like I was for testing. Interesting to see that Brave appears to handle the background boxes properly, though.

**Comment by Gusted** [comment]
![](https://i.imgur.com/xkOn3Bc.png) This is showing up for chromium for a social media icon.
![](https://i.imgur.com/hq39B6p.png) While Firefox Is showing correct.
Intresting we don't touch <img> due to performance....

Also noticed after couple of seconds Wix changes some elements(I checked and we didn't triggered this) and this seems where on Firefox some scrambled layouts come from.

**Comment by CathodeRayBlues** [comment]
> This is showing up for chromium for a social media icon.
> While Firefox Is showing correct.
> Intresting we don't touch due to performance....
> 
> Also noticed after couple of seconds Wix changes some elements(I checked and we didn't triggered this) and this seems where on Firefox some scrambled layouts come from.

Very curious. I think it might have to do with loading in the background image which is quite large, but don't quote me on that. Lord knows what else Wix has to load that we never see.

**Comment by Gusted** [comment]
Idk Wix Is changing the styles after it's loaded(and several seconds without any logical reason). and somehow in Firefox that messes up certain styles even all CSS property's are right their. Could be browser bug, but I don't see any logical reason to explain it into a bug report neither a Test case because Joost knows what Wix is doing in their obfuscated javascript files.(Joost is the name we use in Dutch for this :P)

**Comment by CathodeRayBlues** [comment]
Hmm, well if there's nothing we can do to fix it, I'll start searching for other website creation tools/hosting platforms. Wix has been troublesome to work with in more ways than this, after all.
