### ISSUE TITLE
https://js.org/ background isn't showing

### ISSUE THREAD

**Issue by werymanen** [darkreader/darkreader#3122]
**Website**
https://js.org/

**How to Reproduce**
An example of this is
> 1. Go to [the js.org](https://js.org/) site
> 2. Turn off darkreader
> 3. See that there's a background which darkreader has hidden.

**Expected behavior**
I expected the background image to still be visible

**Actual behavior**
The background was dark

**System info:**
 - OS: Linux
 - Browser: Firefox
 - Darkreader 4.9.15

**Comment by Gusted** [comment]
I think your talking about the woodish background, am I right?

**Comment by werymanen** [comment]
yes, the yellow woodish background with an iron bar

*you're
sorry

**Comment by Gusted** [comment]
Yes, it's shining in my eyes not sure why it was removed but my opinion I don't want it back either.

**Comment by werymanen** [comment]
yes, it is pretty bright.

Does inverting make it any better?

**Comment by Gusted** [comment]
Nope we don't use inverting for realistic photos it's make them not look good

**Comment by werymanen** [comment]
Okay, then just keep it dark, right?

**Comment by Gusted** [comment]
Yeah, better for the eyes.

**Comment by werymanen** [comment]
Okay
