### ISSUE TITLE
[BUG] Extension changing page layout even if I remove this page from list 

### ISSUE THREAD

**Issue by venglas** [darkreader/darkreader#3126]
### **Macbook Catalina newest chrome**

Extension changing page layout even if I remove this page from list and if i set change only from list and this page is not existing in list.

**Comment by Gusted** [comment]
Could you post a screenshot of your site list?

**Comment by venglas** [comment]
Hi @Gusted, I was removed the extension cuz it was bothering me a lot. But If you want I can add it one more time and make you full raport from this - if You want take care about this.

**Comment by Gusted** [comment]
Hi @venglas 

This perhabs caused by a misconfiguration, I will be more than happy to take care of this issue.

**Comment by venglas** [comment]
Okay. I will try to do it today - if not you can remind me at week.

**Comment by Gusted** [comment]
👍

**Comment by Gusted** [comment]
Reminder
