### ISSUE TITLE
[Broken Website] patreon.com (creator post editor)

### ISSUE THREAD

**Issue by ManlyMarco** [darkreader/darkreader#3128]
Here's a fairly obscure website bug. Since it requires a creator account on patreon it might be difficult to reproduce, I can help test things if necessary.

**Website**
https://www.patreon.com

**How to Reproduce**
> 1. Go to patreon.com and log in (needs to be a creator account)
> 2. Go to your main page (post view)
> 3. Click the edit button on one of your existing posts

**Expected behavior**
Dark mode should work fine in the post editor like on the rest of the website.

**Actual behavior**
Dark mode keeps switching off and on every second or so (so you get alternating white/dark theme).

**System info:**
 - OS: Windows 10
 - Browser: Opera 68.0.3618.173
 - Darkreader Version: 4.9.15
 
**Additional context**
The bug doesn't always happen. It seems to always trigger when you refresh the post editor page.
The switching seems to be correlated to the fade-in effect that the editor uses. When the fade-in completes the dark mode is toggled to the opposite (on/off), which triggers the fade-in effect to happen again. This seems to cause an infinite loop of dark mode being toggled triggering the fade-in effect, which when finished triggers the dark mode to be toggled.

**Comment by Gusted** [comment]
Could you create a GIF of this behaviour?

**Comment by ManlyMarco** [comment]
Looks like this also happens on the "New post" page. There seems to be the same animation on the "Need some ideas" buttons as in the post editor.
![asd2](https://user-images.githubusercontent.com/39247311/87702020-22715d80-c799-11ea-9423-27bf89122812.gif)

**Comment by Gusted** [comment]
Not sure how comfort you are with Devtools but do you see any animation or changing elements in it? That relates to the element that is quite flashing.

**Comment by ManlyMarco** [comment]
The entire page is flashing. There are two animations like this 
![image](https://user-images.githubusercontent.com/39247311/87702919-5436f400-c79a-11ea-97f8-f8b56ae748b2.png)
I also noticed this happening
![asd2](https://user-images.githubusercontent.com/39247311/87702938-5b5e0200-c79a-11ea-86ae-6ea930457c4f.gif)

**Comment by Gusted** [comment]
Hmmm this isn't good news. could you find what the animation does? and if you disable the animation does this behaviour stop?

**Comment by ManlyMarco** [comment]
It does stop when I remove this block

```html
<style data-styled="iECmZH cKQAif" data-styled-version="4.2.0">
  /* sc-component-id: sc-keyframes-iECmZH */

  @-webkit-keyframes iECmZH {
    0% {
      -webkit-transform: rotate(0deg);
      -ms-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    100% {
      -webkit-transform: rotate(360deg);
      -ms-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  @keyframes iECmZH {
    0% {
      -webkit-transform: rotate(0deg);
      -ms-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    100% {
      -webkit-transform: rotate(360deg);
      -ms-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  /* sc-component-id: sc-keyframes-cKQAif */

  @-webkit-keyframes cKQAif {
    0% {
      stroke-dashoffset: 162;
      -webkit-transform: rotate(0deg);
      -ms-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    50% {
      stroke-dashoffset: 90;
    }
    100% {
      stroke-dashoffset: 162;
      -webkit-transform: rotate(360deg);
      -ms-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  @keyframes cKQAif {
    0% {
      stroke-dashoffset: 162;
      -webkit-transform: rotate(0deg);
      -ms-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    50% {
      stroke-dashoffset: 90;
    }
    100% {
      stroke-dashoffset: 162;
      -webkit-transform: rotate(360deg);
      -ms-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }
</style>
```
I'm not too knowledgeable in html/css so let me know what to look for if you need more info.

**Comment by Gusted** [comment]
If you disable dark reader can you see if this still is deleting and than adding itself or something in that way?

**Comment by ManlyMarco** [comment]
It's hard to tell but it looks like it's the dark reader script that's being removed and recreated, not the website's own script.

**Comment by Gusted** [comment]
Hmm weird that only should behave if the own script also change. Hmm could you sideload our debug extension.

[debug.zip](https://github.com/darkreader/darkreader/files/4933988/debug.zip)

And check reload the site and check in the console for any warnings that the style is restored or anything related and make a screenshot of it. That could give me more insight in it.

**Comment by ManlyMarco** [comment]
Here's the console log from the debug version. It's from the flashing new post page after letting it run for a couple loops.
[www.patreon.com-1594934364129.log](https://github.com/darkreader/darkreader/files/4934224/www.patreon.com-1594934364129.log)

**Comment by Gusted** [comment]
Like I thought it's re-adding and re-moving itself But you mention after turning it off and than on it's fixed?

**Comment by ManlyMarco** [comment]
If I disable darkreader and wait until it stops flashing, then re-enable it works fine until I refresh the page.

**Comment by Gusted** [comment]
If you re-enable it, does it in console stop saying retrying in 2000ms?

**Comment by ManlyMarco** [comment]
Yes, nothing gets logged after doing that.

**Comment by Gusted** [comment]
Than I think I might created a bug with #3004 Instead of fixing one :eyes: Btw does it flash every 2 seconds or something in that direction.

**Comment by ManlyMarco** [comment]
Yes, it's flashing around every 1-2 seconds.

**Comment by Gusted** [comment]
Fixed a bug got a bug in return 😥

**Comment by Gusted** [comment]
[debug.zip](https://github.com/darkreader/darkreader/files/4937893/debug.zip)
Could you have a look how it looks with this?

**Comment by ManlyMarco** [comment]
This build works fine.

**Comment by Gusted** [comment]
Hmm weird some sites like word online with kind of the same problem isn't fixed by this. Anyway I will open a PR and see what happens.

**Comment by LoganDark** [comment]
![do blink](https://user-images.githubusercontent.com/4723091/88140892-71f3c700-cba7-11ea-9d9b-010f8968c42b.gif)

**Comment by TURBODRIVER** [comment]
Has this fix been released yet? I'm running version v4.9.16 on Firefox and Patreon is still blinking like explained above.

**Comment by TURBODRIVER** [comment]
@Gusted Has this fix been released yet? I'm running version v4.9.16 on Firefox and Patreon is still blinking like explained above.

**Comment by Gusted** [comment]
Unfortunate the fix didn't work as expected. I think I found a trace but vacation. So I hopefully can have a look later this day when I get home. It's complicated bug so far I can see.

**Comment by Gusted** [comment]
#3692 Download latest Dark Reader Version 4.9.23

**Comment by ManlyMarco** [comment]
4.9.23 works well, thanks! It looks like it's not up on chrome store yet.

**Comment by Gusted** [comment]
Woops 4.9.23 was exlusively for Firefox for some weir bug, I meant 4.9.22

**Comment by ManlyMarco** [comment]
I just compiled from source but I guess it doesn't matter :)
