### ISSUE TITLE
[Broken Website] The Daily WTF

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#3130]
**Website**
https://thedailywtf.com/

**How to Reproduce**
Visit the site and view a few articles, occasionally the page will be white and you need to toggle Dark Reader to fix it

**Expected behavior**
dark theme every time

**Actual behavior**
mix of dark/not dark themes

**Screenshots**
![image](https://user-images.githubusercontent.com/4723091/87714657-efab7300-c760-11ea-8291-ec2ce2612553.png)

I had to spamclick the next article button to get this, it only happens occasionally

**System info:**
 - OS: macOS 10.14.6
 - Browser: Google Chrome 83.0.4103.97 (Official Build) (64-bit)
 - Darkreader Version: 4.9.15

**Comment by Gusted** [comment]
![](https://i.imgur.com/0pWKe2R.png) Found the issue. Seems like we don't get the good css?

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/87736482-141d4480-c78d-11ea-82c0-563618fa1fac.png)

I think the characters at the beginning are the problem... maybe there is some malformed tag name?

**Comment by Gusted** [comment]
No, I think somehow the CSS we receive needs some formatting? I'm not even sure how we get this will all those spaces but the 2 characters seems having no problems :shrug:

**Comment by Gusted** [comment]
Doesn't seem to be reproduce anymore.
