### ISSUE TITLE
[Broken Website] Expo Snack QR code

### ISSUE THREAD

**Issue by danielzgtg** [darkreader/darkreader#3140]
**Website**
https://snack.expo.io/
(used by react native official docs)

**How to Reproduce**
An example of this is
> 1. Go to https://snack.expo.io/
> 2. Make sure the "My device | iOS | Android | Web" button group is set to "My device"
> 3. Try scanning the QR code with the [Expo mobile app](https://play.google.com/store/apps/details?id=host.exp.exponent)

**Expected behavior**
The QR code scans properly. The white border around the QR code is required for this to work.

**Actual behavior**
The Expo app is not even aware there is a QR code. This is because Dark Reader darkened the white border, breaking the QR code.

**Screenshots**

![image](https://user-images.githubusercontent.com/25646384/87863750-9abc5800-c92c-11ea-8cbe-021be238ecd7.png)
![Screenshot_20200718-192822](https://user-images.githubusercontent.com/25646384/87863779-ff77b280-c92c-11ea-83ae-c0649d12763e.jpg)

**System info:**
 - OS: `Ubuntu 20.04 Desktop`
 - Browser: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`
 - Darkreader Version: `4.9.15`

**Additional Context**
- Using Expo app `2.16.1` on Android 10
- The QR code is drawn on a `<canvas>` with the position markers flush to the edges
- The 2nd level of wrapping `<div>` has a `4px` rounded border, and that needs to stay white

**Comment by sprinkledcheese** [comment]
Does this work?
CSS
._1rs24yq {
    background-color: rgb(255, 255, 255) !important;
}

**Comment by danielzgtg** [comment]
Yes

**Comment by Simsimpicpic** [comment]
I've been make a pull request to resolve your issue 😉👍🏻 (#3145)

**Comment by danielzgtg** [comment]
Today, the fix for this website reached me and it works now

**Comment by Simsimpicpic** [comment]
The pull request has been merged 15 days ago 😄👍🏻

**Comment by Gusted** [comment]
Update was released 1 week ago should be distributed to everyone by now.
