### ISSUE TITLE
[Feature Request] Make dynamic-fixes.config and other config files served by cdn.

### ISSUE THREAD

**Issue by Mertyn** [darkreader/darkreader#3169]
I think the .config files for website fixes could be served over the internet (or somehow autoupdate, without needing to update the whole extension in the stores), so that the website fixes get to the user faster.
I don't know how viable/possible a solution like this is, so the contributors, who are more in the code of the extension, need to have a look if it actually is possible to do how i imagined it.
Thank you for reading.

**Comment by Gusted** [comment]
#1838
