### ISSUE TITLE
[Broken Website] Recoll website yellow highlights are unreadable in Dynamic mode

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#3184]
**Website**
https://www.lesbonscomptes.com/recoll/

**Actual behavior**
`yellow` became `rgb(198, 195, 58)` while the more darker variant is more readable (`rgb(92, 92, 61)`)

**Screenshots**
![image](https://user-images.githubusercontent.com/11363215/87993446-35ff2a00-caf3-11ea-9f3e-4db2dd354423.png)
![image](https://user-images.githubusercontent.com/11363215/87993433-2bdd2b80-caf3-11ea-8556-15d0eded9bc7.png)

**System info:**
 - OS:  Linux
 - Browser:  chrome 83
 - Darkreader Version:  4.9.15

**Comment by Gusted** [comment]
![](https://i.imgur.com/vDMSNLo.png) What do you think about this?
