### ISSUE TITLE
[Broken Website] Github User Page - Contribution Calender

### ISSUE THREAD

**Issue by cyqsimon** [darkreader/darkreader#3197]
**Website**
[Any active user page](https://github.com/egoist)

**How to Reproduce**
Steps to reproduce the behaviour:
1. Go to the user page of any active Github user
2. Make sure DarkReader is in Dynamic mode
3. Scroll to the contributions calender
4. The colour markings are mixed up

**Expected behavior**
The colour markings should go from black to a vibrant green linearly and consistently.

**Actual behavior**
The colour markings do not follow a logical linear progression.

**Screenshots**
Oringinal: ![Original](https://user-images.githubusercontent.com/28627918/88143472-d3f51080-cc29-11ea-8614-0b95575e999c.png)
Actual: ![Actual](https://user-images.githubusercontent.com/28627918/88143465-d22b4d00-cc29-11ea-8227-412ec9fbcabe.png)
Expected: ![Expected](https://user-images.githubusercontent.com/28627918/88143476-d5263d80-cc29-11ea-9182-9c9e5bafa388.png)

**System info:**
 - OS: Windows 10 Pro N Version 2004
 - Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
 - Darkreader Version: 4.9.15
 
**Additional context**
N/A

**Comment by Simsimpicpic** [comment]
Hello !
Your issue is already resolved with #3162 Pull Request 😄
This pr has been make the 20/07/2020, and you must wait new release of Dark Reader.

> ([**README.MD**](https://github.com/darkreader/darkreader/blob/master/README.md#fix-a-wrong-inversion)) Automatically syncing the above files to every Dark Reader user was disabled because the GitHub team doesn't allow using GitHub as a CDN. Storing these files and making requests to other resources would be expensive and look suspicious. As such, changes are included with each new Dark Reader release.

Thank you !
Simon.

**Comment by cyqsimon** [comment]
That's good to know. Thanks!
