### ISSUE TITLE
[BUG] Python documentation broken on first load

### ISSUE THREAD

**Issue by Mertyn** [darkreader/darkreader#3214]
When I open the python documentation in Chrome ([docs.python.org](https://docs.python.org/)) the darkreader styling is not applied everywhere. Once I turn darkreader on the particular url off and then on again it works. I have also found out that opening the site from a link into a new tab it works just fine, but when I open it directly or reload it, it is broken.
So the problem isn't that the styling is wrong, it just does not always get applied everywhere for some reason.

Short demonstration GIF:
![ezgif-4-9be4d1dc0cf6](https://user-images.githubusercontent.com/22528516/88299069-3ae5f880-cd02-11ea-8912-53caa35255a0.gif)

**Comment by Gusted** [comment]
#835 Will have another look at the issue as well.
