### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3220]
**Website**
https://web.archive.org/web/20090506113128/http://www.lib.noaa.gov/china/fishing.htm

**How to Reproduce**
An example of this is
> 1. Go to https://web.archive.org/web/20090506113128/http://www.lib.noaa.gov/china/fishing.htm

**Expected behavior**
Dark background with white font color

**Actual behavior**
White background with white font

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.15

**Comment by Gusted** [comment]
Unfortunate we can't make for a specific fix for a web.archive.org due to their url structure.
However I can recommend using Static theme for this kind of sites.
