### ISSUE TITLE
[Feature Request] please make it work for QUTEBROWSER.

### ISSUE THREAD

**Issue by samyak039** [darkreader/darkreader#3226]
I have come across a damn cool browser, [QuteBrowser](https://qutebrowser.org/).
And there's only one thing I am missing, that's **DARK READER** :wink: 

So is there any way you can implement Dark Reader for that browser ?? or if any workaround..??

**Comment by Gusted** [comment]
I'm not familiar with the browser and browsing their documentation doesn't five much info about third party extension/addon just some thst are supported.
If you could point me out how it works and how current addons/extension are used in the browser I can have a look. No guarantees.

**Comment by samyak039** [comment]
The information which I am able to gain up till now:
- there is a [thread](https://github.com/qutebrowser/qutebrowser/issues/30) for the work in progress for implementing **extension**
- browser currently supports **userscripts**, and [this](https://qutebrowser.org/doc/userscripts.html) is how one can write a userscript for it.
- there's a config option to imply CSS stylesheet, `content.user_stylesheet`
  - but at a time only one stylesheet can be applied for all wesbites
  - and i coudn't find any stylesheet as good as DarkReaders mode
- it also supports [Greesemonkey](https://www.greasespot.net/) and here's a [thread](https://github.com/qutebrowser/qutebrowser/pull/3854#issuecomment-660980508) explaining how one can implement Greesemonkey to load specific stylesheet for specific sites.

I don't know much about coding, and how a browser works so don't know if this information is relevant or garbage. But am learning, I am a CSE student, so would love to help if someone is trying to apply this.

**Comment by Gusted** [comment]
Due to our codebase we can't convert it into a greesemonkey script I will follow the extension issue and see where it will lead to.

**Comment by samyak039** [comment]
great !!!

Thanks :)

**Comment by Gusted** [comment]
Woops I just saw a old issue about Greesemonkey :)

https://github.com/darkreader/darkreader/issues/926#issuecomment-575893299 Maybe it works. It should auto-update to the latest version of Dark reader/

**Comment by stjornandi** [comment]
Would be really nice to have this feature in the qutebrowser.

**Comment by Gusted** [comment]
@stjornandi Checkout https://github.com/darkreader/darkreader/issues/926#issuecomment-575893299 this comment. But so far I see their can't be one natively for now.

**Comment by stjornandi** [comment]
Ok, thanks anyway for darkreader

**Comment by samyak039** [comment]
@Gusted this worked, thanks for it.

**Comment by The-Compiler** [comment]
qutebrowser maintainer here - FWIW, it would likely be possible (but a major effort) to port the full extension to a qutebrowser extension after https://github.com/qutebrowser/qutebrowser/issues/30.

Also note that Chromium has its own dark mode which can be configured via the `colors.webpage.darkmode.*` settings - the major problem with that is that it requires a restart and doesn't have a way to exclude websites which aren't working well.

**Comment by Gusted** [comment]
I will have a look out for issue.
And btw another major problem it seems like https://www.androidpolice.com/2020/07/01/chrome-86-removes-the-last-remaining-website-forced-dark-mode-flag/ the flag is removed(actually expired as configured in the files)

**Comment by The-Compiler** [comment]
@Gusted Works fine for me, looks like the expiry was pushed back: https://bugs.chromium.org/p/chromium/issues/detail?id=1100139

**Comment by Gusted** [comment]
*Chuckles* competition. Anyway we have more options and customization.
