### ISSUE TITLE
[Bug] Dark Reader breaks MaximizeVideo add-on 

### ISSUE THREAD

**Issue by BubiBalboa** [darkreader/darkreader#3232]
I'm on Firefox Beta v79.0 and Windows 10. Dark Reader 4.9.15 and Maximize Video 0.0.14

**How to Reproduce**
Have both add-ons active. Try to use Maximize Video. When you click on the video the browser slows down and displays the message "A script in the extension "Dark Reader is causing Firefox to slow down." When I choose "Stop it" Maximize Video will complete its action. When I disable Dark Reader for a page Maximize Video works without a problem.

Maximize Video is also here on Github. Maybe you can figure something out to make the add-ons play nicely with each other.

https://github.com/ettoolong/MaximizeVideo

**Comment by Gusted** [comment]
Chrome same issue. I couldn't get the code that causes this really so I will have a look over some days with a fresh mindset and support from the Firefox Profile team(They are awesome).

**Comment by Gusted** [comment]
https://github.com/ettoolong/MaximizeVideo/pull/31
https://github.com/ettoolong/MaximizeVideo/issues/15

**Comment by Gusted** [comment]
Going to close this, you can subscribe to the other issue over MazimizeVideo.
