### ISSUE TITLE
[BUG] Text boxes and drop-down menus look like Win98 style when addon enabled

### ISSUE THREAD

**Issue by romhacks** [darkreader/darkreader#3239]
### **Describe the bug**

When the dark reader add-on is enabled, drop-down menus and text boxes that have not been stylized by the website change from their normal, rounded look that is the OS default, to squared ones that look to be from Windows 98. See screenshots, the website I used as an example was the AUR page for anaconda.

Add-on disabled:
![Screenshot_20200726_104031](https://user-images.githubusercontent.com/42524580/88482113-3b160c00-cf2d-11ea-82d3-bac2b20bc637.png)

Add-on enabled:
![Screenshot_20200726_104048](https://user-images.githubusercontent.com/42524580/88482119-4b2deb80-cf2d-11ea-86bd-dd7e13824889.png)

You can see how the Keywords text box and the Search By drop-down are changed to look different from how they do originally.

### **Steps to reproduce**

- Go to any website with unstylized drop-down menus or text boxes (I used [AUR's page on anaconda](https://aur.archlinux.org/packages/anaconda/) as an example)
- Enable/Disable Dark reader and look at the difference in the boxes

### **Expected behavior**

The drop-down menus and text boxes should stay the same shape/style, just darker.

### **Actual behavior**

The drop-down menus and text boxes are replaced with differently shaped/styled ones that look outdated.

### **Screenshots**

Screenshots are in the first section.

### **System Information:**
 - OS: Arch Linux with KDE Plasma 5.19.3
 - Browser: Firefox Nightly 80.0a1 (2020-07-25) (though I can confirm the bug exists in Firefox Stable, too.)
 - Dark Reader version: 4.9.15

**Comment by Gusted** [comment]
This is a OS thingy. As the drop down menu's etc are being fetched for each OS different. But we don't touch it just the colors and thst shouldn't affect if it's rounded. Could you make a screenshot of the styles that has been applied to the element trough devtools.

**Comment by romhacks** [comment]
You mean to screenshot DevTools when I have selected the text box in it? (sorry my english is not perfect)

**Comment by Gusted** [comment]
The element itself so the `rounded element`

**Comment by romhacks** [comment]
Apologies if this is not what you are looking for.
DevTools of the text box:
![Screenshot_20200726_111652](https://user-images.githubusercontent.com/42524580/88482830-c85b5f80-cf31-11ea-8968-d36bbed678fa.png)
DevTools of the drop-down menu:
![Screenshot_20200726_111748](https://user-images.githubusercontent.com/42524580/88482839-d4dfb800-cf31-11ea-9ae9-9d6655003c64.png)

**Comment by Gusted** [comment]
Hmm interesting, if you maximize the window you should see css on the right side could you screenshot that too than I can get a good picture of what happend.

**Comment by romhacks** [comment]
This is as large as i could make it on my rather small laptop screen.
Text box:
![Screenshot_20200726_113143](https://user-images.githubusercontent.com/42524580/88483113-bf6b8d80-cf33-11ea-90c2-c33fd457131f.png)

Drop-down menu:
![Screenshot_20200726_113043](https://user-images.githubusercontent.com/42524580/88483119-cc887c80-cf33-11ea-8031-1fde997e3254.png)

**Comment by Gusted** [comment]
Could you disable the border-color Like this
![](https://i.imgur.com/YMmdKYu.png)
And see if it changes anything.

**Comment by romhacks** [comment]
Border color ON (default):
![Screenshot_20200726_122340](https://user-images.githubusercontent.com/42524580/88484219-08731000-cf3b-11ea-86f0-471c8ccddafb.png)

Border color OFF:
![Screenshot_20200726_122404](https://user-images.githubusercontent.com/42524580/88484233-145ed200-cf3b-11ea-9785-900d30e714d7.png)

The square shape is still there, but the outline goes from a tan color to a white color.

**Comment by Gusted** [comment]
Try to disable other values from `inline:` and see when the square shape is gone.

**Comment by romhacks** [comment]
I am not very familiar with DevTools and CSS, so I may have missed something, but I was unable to find a value that would affect the border shape.

**Comment by Gusted** [comment]
That's the problem, I can't find suchs CSS either.
