### ISSUE TITLE
[Feature Request] Active different global themes based on time (automation)

### ISSUE THREAD

**Issue by OliEfr** [darkreader/darkreader#3243]
Allow the user to specify different dark themes, which can be automatically activated based on current time.

**Comment by Gusted** [comment]
You mean something like [this](https://darkreader.org/blog/automation)?

**Comment by OliEfr** [comment]
This feature is good - but it only allows for general activation or deactivation of dark-mode, as far as i understand.

It would be great to be able to activate a "light-dark" mode for daytime, and a "darker-dark" mode for night time.
So the user can specify different themes and activate them at a given time automcatically.

I could also imagine, that the darkness can be set dynamically. This is darkness = function (time).

**Comment by Gusted** [comment]
Ah, #2860 I already made a PR for it 👍🏽

**Comment by Gusted** [comment]
It should switch between Dark Scheme and Light Scheme, but it's not that prioritized at the moment so expect it to be open for a while.

**Comment by OliEfr** [comment]
Awesome, thanks! I'll have a look at it soon.
