### ISSUE TITLE
[Broken Website] HTTPS Everywhere Atlas

### ISSUE THREAD

**Issue by Zayne64** [darkreader/darkreader#3247]
**Website**
[https://atlas.eff.org/](https://atlas.eff.org/)

**How to Reproduce**
> 1. Go to website
> 2. Turn on darkreader

**Expected behavior**
Have background appear at the bottom

**Actual behavior**
Background cuts off to a grey colour

**Screenshots**
![Without Dark Reader](https://user-images.githubusercontent.com/11258171/88532599-cc07e880-cffc-11ea-904d-e9dedfc7c093.png)
![With Dark Reader](https://user-images.githubusercontent.com/11258171/88532633-d88c4100-cffc-11ea-9995-07fe1f3b961d.png)

**System info:**
 - OS: Arch Linux
 - Browser: Firefox 78.0
 - Darkreader Version: 4.9.15

**Comment by LoganDark** [comment]
The background thing happens on every website, for example https://colean.cc.

![image](https://user-images.githubusercontent.com/4723091/88532834-22076c80-cfba-11ea-8e02-58f3e7d815fb.png)

**Comment by Gusted** [comment]
Or https://www.example.com

Its just a thingy with body/html I will have a look if we can make it more the same.

**Comment by Gusted** [comment]
```typescript
lines.push(`    background-color: ${modifyBackgroundColor({r: 255, g: 255, b: 255}, filter)} !important;`);
```
It's some static code trying to prevent white-flashes...
