### ISSUE TITLE
[BUG] All Google.com sites are being turned dark

### ISSUE THREAD

**Issue by Berkyjay** [darkreader/darkreader#3254]
### **Describe the bug**

When I tag one Google.com site to be darkened it turns all of the sites dark.  For example, if I want only want google.com/search darkened but not google.com/maps I can't do that currently.

### **Steps to reproduce**

Go to any Google.com site and darken it

Then go to another site and notice that it is now also dark.

### **Expected behavior**

Only sites I want darkened become dark

### **Actual behavior**

All Google.com sites are being darkened.

### **System Information:**
 - OS: Windows 10
 - Browser:  Chrome 84
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
Hi @Berkyjay,

You can do this manually to add those sites to the site list.

Regards,
Gusted

**Comment by Viscira-Animation** [comment]
@Gusted Thank you!  I missed the location to edit the site list as it was in the 'settings'.

**Comment by Berkyjay** [comment]
@Gusted Thank you! I missed the location to edit the site list as it was in the 'settings'.

**Comment by CyanoFresh** [comment]
How I can enable for google search and disable for google maps? Maps has static location

**Comment by Gusted** [comment]
Hi @CyanoFresh 

In your sitelist you need to add `google.com/maps`

**Comment by CyanoFresh** [comment]
@Gusted Hi. Thanks for the reply. 
Should I use another beta version? Because now I cannot toggle dark mode for maps. 
I added google.com.ua/maps (and aliases) but when I click on site's name in extension menu - nothing happens.
Recording: https://drive.google.com/file/d/1F9nPqe6PY5Npxszwn8XE7vIUEvDsn7RC/view

**Comment by Gusted** [comment]
Just try `www.google.com.au/maps`

**Comment by CyanoFresh** [comment]
yep, tried this, cannot toggle at all

**Comment by Gusted** [comment]
Do you have google.com.au or something in your sitelist or anything else related to it?

**Comment by CyanoFresh** [comment]
nope, that's my list:
```www.fastify.io
...other unrelated sites...
translate.google.com
www.google.com.ua/maps
```

**Comment by Gusted** [comment]
Backup your list and try it with a clean list.
