### ISSUE TITLE
[Broken Website] https://docs.python.org/3/library/hashlib.html

### ISSUE THREAD

**Issue by yanzhen0610** [darkreader/darkreader#3262]
**Website**
The link of the broken website

[https://docs.python.org/3/library/hashlib.html](https://docs.python.org/3/library/hashlib.html)

**How to Reproduce**
An example of this is
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors

Added `docs.python.org` to the list, then enter the website.

**Expected behavior**

All in dark.

**Actual behavior**
A clear and concise description of what happened.

Parts of the website are light, but re-added the site to the list temporarily fixes it.

**Screenshots**

![image](https://user-images.githubusercontent.com/24453597/88635742-a1945900-d0ea-11ea-91ad-6a8e19b7171d.png)

**System info:**
 - OS: Linux (Ubuntu 20.04) [e.g. Windows, MacOS, Linux]
 - Browser: Chrome [e.g. chrome, safari]
 - Darkreader Version: 84.0.4147.89 (Official Build) (64-bit) [e.g. 4.9.9]
 
**Additional context**

**Comment by Gusted** [comment]
#835 dup
