### ISSUE TITLE
[Broken Website] Quip

### ISSUE THREAD

**Issue by lnunno** [darkreader/darkreader#3267]
**Website**
https://www.quip.com

**How to Reproduce**

1. Go to the site and open / add a doc with any default text
2. Text is purple instead of white

Text is inverted as purple instead of white (old behavior). This seems to have just started very recently for me (within the last day).

**Expected behavior**
Text is white

**Actual behavior**
Text is purple

**Screenshots**
![image](https://user-images.githubusercontent.com/5023012/88701338-bd820580-d0be-11ea-83eb-bcea4a7932b2.png)

![image](https://user-images.githubusercontent.com/5023012/88700852-13a27900-d0be-11ea-8de6-db09e6d2548e.png)

**System info:**
 - MacOS
 - Chrome
 - Darkreader Version: 4.9.16
 
**Additional context**

**Comment by Gusted** [comment]
Smh, enterprised product.

Hmm, Is still purple with dark reader turned off?
4.9.16 was just released but didn't touched any color things.
You could change the color manual trough
```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.

Custom background, text and selection colors (under Theme click See all options, Colors).
```

**Comment by gibfahn** [comment]
Seeing the same issue.

> 4.9.16 was just released but didn't touched any color things.

I can confirm that:
1. I am on 4.9.16
2. I wasn't seeing this yesterday 

>Hmm, Is still purple with dark reader turned off?

No, it's black text on a white background.

Also this only occurs in Dynamic mode, Filter+, Filter, Static all work fine (though obviously they don't look as nice).

> You could change the color manual trough

Text colour seems to think it should be white already:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/15943089/88712546-cb14ab00-d111-11ea-8463-43283b3f5620.png">

**Comment by Gusted** [comment]
Try modifying the text value maybe it will be affected. Else hmm their could be another problem.

**Comment by gibfahn** [comment]
>Try modifying the text value maybe it will be affected. Else hmm their could be another problem.

That changes the text around the main page (in the sidebars etc), but not the main page.

**Comment by Gusted** [comment]
That's intresting.
Are you familiar with the devtools?

**Comment by gibfahn** [comment]
Chrome Devtools yes (reasonably familiar).

**Comment by Gusted** [comment]
Okay, nice.

Can you get ahold of the exact `color:` that's being used in the main page? And see what it's originial color was(Darkreader Disabled). Maybe it detected it was a certain color.

**Comment by gibfahn** [comment]
Dark Reader enabled: #9347f5

Dark Reader disabled: #333333

**Comment by Gusted** [comment]
Hmm with normal settings `#333` should transform to `#c8c3bc`. Can you make a screenshot of the CSS that is being applied to it when Dark Reader is on?

**Comment by gibfahn** [comment]
Yeah, I see that the comment bar text etc is `#c8c3bc`, it's just the main page text that is purple.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/15943089/88725731-70d11580-d124-11ea-96a7-8911bfdf1dc6.png">

Clicking on this takes me to:

```
<style class="darkreader darkreader--sync" media="screen"></style>
```

The element itself looks like:

```
<div class="content" data-id="KSU..." data-contextmenu="section-context-menu">Test</div>
```

**Comment by Gusted** [comment]
If you disable dark reader is that selector(that caused purple) still active for that element? It might we picked up CSS that shouldn't be sussposed to be used.

**Comment by gibfahn** [comment]
With Dark Reader:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/15943089/88726460-ac201400-d125-11ea-90e1-18eca4bd807b.png">

Without Dark Reader:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/15943089/88726499-bb9f5d00-d125-11ea-8364-65cbe207d8df.png">

Source of that:

```css
.document-content .section.use-less[data-section-type="0"]>.content {
    color: var(--editor-document-text-color);
    caret-color: var(--editor-document-caret-color)
}
```

(not sure if this answers your question, the first box is missing in the devtools)

**Comment by gibfahn** [comment]
Interestingly the

**Comment by Gusted** [comment]
Could be related to #3241(This is a complicated issue about our codebase)

**Comment by gibfahn** [comment]
I tried cloning this repo, going back to an old tag (tried v4.9.15 and even v4.9.10), running `npm install && node tasks/build.js --release` and got the same behaviour (purple text).

This suggests that maybe something changed in Quip to cause this.

**Comment by Gusted** [comment]
Could be.

**Comment by hicder** [comment]
FYI, if I change the Mode from Dynamic to Filter, Quip works fine (text becomes white on black background as expected)

**Comment by gsisson** [comment]
FYI: I just noticed that in the last couple of days when viewing Quip documents that I have started seeing purple on white with DR enabled, whereas it used to be purple on black. Purple was certainly annoying, but now the background is white regardless of DR enabled/disabled so DR isn't providing any sort of "dark mode". (also, thank you all very much for this great extension - I wish I knew front-end css and could help-out on the project)

**Comment by Gusted** [comment]
Hmm, got finally around and created a quip account that somehow was `verified`. And noticed this same behaviour and had a lot of similarity's with a bug I found #3241 which been on the backlog and verifying the variables can have a lot of performance impact.

AFAIK and seems Firefox-only some bug with white background mentioned in the comment above me ^.

**Comment by gibfahn** [comment]
As a workaround you can turn on Filter Mode vs dynamic mode for the Quip website itself. The colour scheme is less nice than the Dynamic one, but it does give you black text on white.

Dark Reader -> Settings -> Theme -> click the website -> Filter Mode

**Comment by gsisson** [comment]
Thank you gibfahn.  It was a bit tricky to enable that setting correctly, but I think I finally did it with these steps:

Dark Reader -> "More" Tab -> toggle "Only for quip-amazon.com" on -> toggle "Filter" on

That third step isn't obvious, and if not done you get "filter" mode for all websites (though you might not immediately notice it if other sites aren't open in other visible pages)

Thanks again gibfahn

**Comment by gibfahn** [comment]
Ahh yeah, looks like it's different for different browsers, I posted the Safari instructions, I think Chrome and Firefox work the way you noted.

**Comment by gibfahn** [comment]
FWIW Quip just added a built-in dark mode, so this is probably not a big deal going forward.

https://quip.com/release-notes/2020-01-26
