### ISSUE TITLE
[Feature Request] The automation settings are lost if I toggle on/off manually. Can they be saved?

### ISSUE THREAD

**Issue by saravanabalagi** [darkreader/darkreader#3268]
**Is your feature request related to a problem? Yes**

The automation settings are lost if I toggle on/off manually.

I have set Dark Reader to turn on automatically based on sunset at a specified location and it works fine. But when I manually turn it on during daytime briefly and switch it off, the location based on/off stops working. 

**Describe the solution you'd like**
Turning off reverts to auto on/off mode based on settings saved.

**Additional context**

![20200728_170137_1](https://user-images.githubusercontent.com/8567893/88701593-1921b280-d102-11ea-9c49-73c60933e55a.gif)

**Comment by Gusted** [comment]
To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Have a look how it behave with the new UI. It should preserve the Settings. 
The automation settings are under Settings -> Automation

**Comment by saravanabalagi** [comment]
The new one doesn't work 👎 

![20200806_154439](https://user-images.githubusercontent.com/8567893/89547928-47884780-d7fe-11ea-8179-8eaafe3316e9.gif)

**Comment by Gusted** [comment]
Hmm, seems like it we have 1 variable that also controls the on/off status alongside the current option :/

**Comment by saravanabalagi** [comment]
I have the auto mode on based on location. There are times when I needed to switch dark mode off at night, but when I turn it back on it's stuck to constant on. Isn't there an easy fix for that?

**Comment by Gusted** [comment]
> . Isn't there an easy fix for that like adding it as a global setting variable?

It is already, but
We have it as a variable, but it was programmed in such way that we have 4 options [as seen here](https://github.com/darkreader/darkreader/blob/master/src/definitions.d.ts#L85)
So when it's '' it mean it's off and on/off is selected and poof settings are gone.

**Comment by saravanabalagi** [comment]
Okay, now I get why it's happening. 

When we turn off, it should stay what it is, instead of becoming `''`. So the dark mode should turn on both `enabled` and `automation` variables. Can you point out in code where this happens? I may be able to do a pull request

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/blob/master/src/ui/popup/main-page/app-switch.tsx#L26 This is the function that makes automation becomes `''`.
Here is the automation page itself
https://github.com/darkreader/darkreader/blob/master/src/ui/popup/automation-page/index.tsx

Automation logic to see if it has to be enabled/disabled is right here
https://github.com/darkreader/darkreader/blob/master/src/background/extension.ts#L51

**Comment by saravanabalagi** [comment]
Thanks @Gusted I'll try this weekend or the next when I'm free. Cheers.

**Comment by Gusted** [comment]
> 
> 
> Thanks @Gusted I'll try this weekend or the next when I'm free. Cheers.

Good luck 😬 Make sure that the current settings are compatible with new logic so it won't break anyone current's settings

**Comment by SimonSteinberger** [comment]
I'm facing this exact same issue still today. It's 4+ years since the "fix". Not sure if it truly was ever fixed. Does anybody have some context on it?
