### ISSUE TITLE
[BUG] Broken colors on certain websites using the dynamic filter

### ISSUE THREAD

**Issue by Ghosty141** [darkreader/darkreader#3281]
### **Describe the bug**

Since yesterday the dynamic filter just does not work correctly anymore, Sites like google, github or soundcloud have completely messed up colors:

### **Steps to reproduce**

Not sure how to reproduce this. This only happens on firefox, trying dark reader on chrome works fine.

### **Screenshots**

![firefox_2020-07-29_18-42-22](https://user-images.githubusercontent.com/17564201/88828468-92d1a300-d1cb-11ea-863d-f0cdf6d07ec7.png)
![firefox_2020-07-29_18-45-18](https://user-images.githubusercontent.com/17564201/88828533-a846cd00-d1cb-11ea-987e-43f8ad5a944b.png)

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox 79.0 (64-Bit)
 - Dark Reader version: Version 5 Preview (4.9.16)

**Comment by Gusted** [comment]
1. Reinstall dark reader
2. Try on a new fresh profile

I got this before but only when I was testing new features, did you install from offical sources?

**Comment by Myshor** [comment]
One suggestion to try ('cause I had similar strange colors issue at work today).
Try to restart firefox. It seems that new feature for background color and new CSS variables can mess a little bit when upgrade od extension happens during browser usage. Everything started to work fine in my 79.0b9 (64 bit) Firefox Browser Developer after restart of it.

**Comment by Ghosty141** [comment]
Thanks for the quick responses. Sadly reinstalling doesn't do it. Switching to a new profile might work but you can probably understand why this isn't a practical solution for me. I also restarted firefox but it didn't help.

**Comment by Gusted** [comment]
It's rather to check if it works on a new profile so I can try to understand what's the underlying problem.

**Comment by Ghosty141** [comment]
So I created a new profile, installed darkreader and it worked just fine. So it must be related to the profile. I could share my profile if you want. (I'd delete the history passwords etc. of course).

**Comment by Gusted** [comment]
No let's go trough some basic settings that could cause this.
Do you have any custom settings at about:preferences#privacy

**Comment by Ghosty141** [comment]
Yes I ticked the following ones (my settings are german so I hope you can figure it out)
Cookies -> in the dropdown I selected the one with social media in the name
The one saying crypto-miner
Identifiert (Fingerprinter)

**Comment by Gusted** [comment]
Hmm, we had some issues before with the custom settings(Firefox is strict). You could try setting certain things back(So far for every user it was other things that resolved to set back).

**Comment by Ghosty141** [comment]
I set the settings to 'Standard' and restarte firefox sadly it did not resolve it.

**Comment by Gusted** [comment]
Could you try uninstall dark reader than restart and install dark reader afterwards.

**Comment by ArttuLai** [comment]
Yeah I've noticed similar regression recently when using Dark Reader on Chromium Edge (stable/beta/dev). It started happening recently on Google sites etc. My Google search page looks identical to yours, while a week ago it looked just fine.

**Comment by Gusted** [comment]
Hmm are their any errors in console?

**Comment by ArttuLai** [comment]
When I switched sites back to the default theme, they look normal again. It might've been that those sites had a custom theme, "custom for google.com" etc. I also reset the theme settings back to defaults first.

**Comment by Gusted** [comment]
We have added support for presets recently... But it shouldn't be interfering with custom sites. [more info on presets](https://darkreader.org/blog/v4-9-16/), but I couldn't get a reproduceable case with custom settings enabled. So once again



> Hmm are their any errors in console?

As this could lead to a conclusion why.

**Comment by ArttuLai** [comment]
Sorry @Gusted can't reproduce the bug after resetting theme & settings & custom themes for sites and starting over. Everything seems to be in order, maybe it was just that something got wonky after the pretty recent update. 

(console doesn't show anything abnormal anymore).

**Comment by Gusted** [comment]
Hmm weird could be once again related to #2969 But that was another cause anyway, it's confirmed that you can reset it. Also you can backup the settings before up and than reconfigure if you want as it's rather hard to make this automated.

**Comment by Ghosty141** [comment]
> 
> 
> Could you try uninstall dark reader than restart and install dark reader afterwards.

I did this, it did not help. I don't have a custom theme nor preset enabled. So this happens is using stock darkreader.

I reverted all settings. this "fixed" it, the problem did not reappear after reimporting my previous settings.
