### ISSUE TITLE
🐞: Download, Share, Print icons get oblivated on https://drive.google.com/file/ previews

### ISSUE THREAD

**Issue by joe733** [darkreader/darkreader#3291]
### **Describe the bug**

The file option seen on the top right corner (near profile picture) disappears when the dark-reader is enabled.

### **Steps to reproduce**

- Go to your GDrive open a `.docx` (this behaviour is not seen with `.pdf`) in *View Only Mode*.
- Enable and disable dark reader to see the anomaly

### **Expected behavior**

Those icons remain intact even though they are while originally because the background is already black.

### **Actual behavior**

The icons disappears in the dark background.

### **Screenshots**

Dark Reader switched off:
![Screenshot from 2020-07-29 23-48-07](https://user-images.githubusercontent.com/38415384/88994188-68840080-d305-11ea-80f0-b8c9d8a96be6.png)

Dark Reader switched on:
![Screenshot from 2020-07-29 23-48-21](https://user-images.githubusercontent.com/38415384/88994190-6a4dc400-d305-11ea-94f8-763a8fa2f81c.png)

### **System Information:**
 - OS: elementary OS 5.1.6 Hera (base 18.04 Bionic Beaver)
 - Browser: Firefox 79
 - Dark Reader version: 4.9.16

### **Additional context**

Error seen in `.docx` preview, did not test `.xlsx` or `.pptx` previews from the google drive.

**Comment by sprinkledcheese** [comment]
Example link?

**Comment by Gusted** [comment]
Disable dark reader and see that when you scroll it's fade away or over time. This is normal behaviour.

**Comment by joe733** [comment]
> Example link?

https://drive.google.com/file/d/1D-6vqegTlHvHiH02gu5e7VsX52moWawT/view?ths=true

> Disable dark reader and see that when you scroll it's fade away or over time. This is normal behaviour.

I'm afraid no.

**Comment by Gusted** [comment]
Hmm seems to only happend on first page load
