### ISSUE TITLE
[Feature Request] Sync whitelists 

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#3292]
Can you please have whitelisted sites sync with Firefox Sync?

**Comment by Gusted** [comment]
Every setting is being synced. Make sure you have Firefox Sync on tho.

**Comment by leodoi3** [comment]
It is on and the sites did not sync.

**Comment by Gusted** [comment]
Tell me your situation that you know it's not being synced.
also are other settings synced?

**Comment by leodoi3** [comment]
I'm not sure about settings since I always leave them at default , but it did not sync any of my whitelisted sites.

**Comment by Gusted** [comment]
Try to add some custom setting.they should be synced as well it's just 1 object with all information that get synced.

**Comment by leodoi3** [comment]
I've tried setting brightness to max and changing theme generation to static and neither of them synced.

**Comment by Gusted** [comment]
Welp that means it isn't getting synced.
do you have the default UI enabled if dark reader?

**Comment by leodoi3** [comment]
I think so 
![image](https://user-images.githubusercontent.com/46114199/89720911-4127d600-d98c-11ea-83f2-98632bc3ae33.png)

**Comment by Gusted** [comment]
To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.


After this:
    Click Dark Reader icon.
    Click Settings.
    Click Manage settings.
    Check if the option Settings synchronization is enabled.

**Comment by leodoi3** [comment]
> To activate the new user interface do the following:
> 
>     Click Dark Reader icon.
>     Click Dev tools (in the bottom-right corner).
>     Click Preview new design.
> 
> 
> After this:
>     Click Dark Reader icon.
>     Click Settings.
>     Click Manage settings.
>     Check if the option Settings synchronization is enabled. 

I did this on both devices unfortunately it didn't work.

**Comment by Gusted** [comment]
Okay, could you download this addon https://addons.mozilla.org/en-US/firefox/addon/about-sync/?src=search
and than go to `about:sync` and make a screenshot of the left side of the page. Their might be something off with Firefox Sync

**Comment by leodoi3** [comment]
![image](https://user-images.githubusercontent.com/46114199/90070216-5bbdc000-dca8-11ea-869f-151fa9f783d5.png)
![image](https://user-images.githubusercontent.com/46114199/90070244-65472800-dca8-11ea-9edc-f281e00bd451.png)

**Comment by Gusted** [comment]
Could you export to file and see if you see any of your custom settings are there.
It's probably 1 big mess in the file so I see `anonymize data` option If you don't get it you could mail the file to `williamzijl7@hotmail.com`. Also I recommend turning off the first option.

**Comment by Gusted** [comment]
As a matter of fact,

![](https://i.imgur.com/AGJvyfL.png) Just your bookmarks are being synced

Could you have a look at

    Open the Options panel.
    In the Sync My section, check the box next to add-ons on each of your computers. 

And than make a change and wait 20+ minutes at minimal just to make sure. And close browser/computer and check it on browser/computer if it had been synced.

**Comment by Gusted** [comment]
As a matter of fact, Just your bookmarks are being synced. Only found trace to bookmarks in the sync json.

Could you have a look at

    Open the Options panel.
    In the Sync My section, check the box next to add-ons on each of your computers. 

And than make a change and wait 20+ minutes at minimal just to make sure. And close browser/computer and check it on browser/computer if it had been synced.

**Comment by leodoi3** [comment]
I do already have addons checked. Firefox already syncs my addons just fine.

**Comment by Gusted** [comment]
Could you name a addon that sync normally?

**Comment by leodoi3** [comment]
Actually i couldn't find any addon that was syncing.

**Comment by Gusted** [comment]
> Actually i couldn't find any addon that was syncing.

Than I suggest troubleshooting Firefox Sync as that is the problem at the moment. So far I could tell only your Bookmarks are being synced, You also could open up a ticket over [here](https://support.mozilla.org/en-US/kb/how-do-i-submit-bug-firefox-sync). As it's seeming this isn't dark reader's bug I will close this issue

Regards,
Gusted

**Comment by leodoi3** [comment]
Opened up issue on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1659314) was able to get sync working on other addons except Darkreader

**Comment by Gusted** [comment]
> Opened up issue on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1659314) was able to get sync working on other addons except Darkreader

Did you had a look on the [new desing](https://darkreader.org/blog/v4-9/) and made sure it's states it's being synced?
