### ISSUE TITLE
[BUG] Youtube.com: Dark Mode re-enables after switching tabs

### ISSUE THREAD

**Issue by MMK21Hub** [darkreader/darkreader#3293]
### **Describe the bug**

When on [Youtube](https://www.youtube.com/), with Youtube Blacklisted, the dark theme enables once you have switched to another tab.

### **Steps to reproduce**

- Go to Youtube
- Turn on *Youtube's* Dark Theme
- Blacklist Youtube form DarkReader
- Switch to another tab
- Switchback again

### **Expected behavior**

YouTube's Dark Theme would persist

### **Actual behavior**

DarkReader's Dark Theme is used

### **System Information:**
 - OS: Microsoft Windows [Version 10.0.19041.388]
 - Browser: 84.0.4147.105 (Official Build) (64-bit)
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
Hi!

Some more info about htis.
Did you switched the tab after darkreader was unloaded.
Could you have a try with the same steps but changing Contrast and Brightness to the highest setting(Youtube dark theme and normal darkreader looks a lot of the same).
It wasn't reproduceable for me..

Regards,
Gusted

**Comment by MMK21Hub** [comment]
It doesn't seem to be a problem anymore... weird...

**Comment by Gusted** [comment]
Maybe darkreader had a bad hour, can happen 🤷🏽‍♀️
