### ISSUE TITLE
[BUG] Exported CSS for google calendar doesn't darken the header

### ISSUE THREAD

**Issue by Geobert** [darkreader/darkreader#3296]
### **Describe the bug**

I've exported the generated CSS and it doesn't darken the header

[DarkReader-calendar-google-com.css.txt](https://github.com/darkreader/darkreader/files/5006000/DarkReader-calendar-google-com.css.txt)

### **Steps to reproduce**

- Export the dark CSS from google calendar
- Copy paste the content of the CSS in a new Stylus theme

### **Expected behavior**

the header should be dark as well (it's working with dynamic theming)

### **Actual behavior**

the header of google calendar is white

### **Screenshots**

![image](https://user-images.githubusercontent.com/72570/89017648-8c9a0e80-d312-11ea-8ec2-f46c8cb57665.png)

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox Nightly
 - Dark Reader version:  4.9.16

**Comment by Gusted** [comment]
Ah.
It's a Inline style
![](https://i.imgur.com/u9KxJsd.png)
#3212 

you can simple add
```css
header {
    background-color: var(--darkreader-neutral-background) !important;
}
```
That should do it.

**Comment by Geobert** [comment]
Thank you for the tip!

So when the inline support is merged, it will work as expected without manually adding style?

My point was that the theme exported was not giving the same result than with dynamic theming :)

I also noticed the full day event colors are brighter with the exported theme than with dynamic theme.

But this might be another inline style :)

**Comment by Gusted** [comment]
Yep.
But we don't export everything yet.
Just like IFrames.

**Comment by Gusted** [comment]
thats another inline btw

**Comment by Geobert** [comment]
Thanks for the feedback :) is there an issue to track what's missing in the export atm?

**Comment by Gusted** [comment]
Not really. We need to think about how it should behave still and what we want to implement.
