### ISSUE TITLE
Dark reader in Firefox 79.0 with profile in ram disk keep loading.

### ISSUE THREAD

**Issue by agwEgamE** [darkreader/darkreader#3297]
### **Describe the bug**

Dark reader in Firefox 79.0 with profile in ram disk keep loading.

### **Steps to reproduce**

1. Update Firefox to 79.0
2. Win + R type:  `firefox -p` or any method to open profile manager 
3. Create new profile and set to ram disk.
4. Open with new profile and install dark reader.

### **Expected behavior**

Dark reader start-up success without loading forever.
### **Actual behavior**

"Loading, please wait" forever.

### **Screenshots**

![78 02](https://user-images.githubusercontent.com/68129013/89080218-dc341500-d3ba-11ea-8c04-3b56a50f0429.jpg)
![79 0](https://user-images.githubusercontent.com/68129013/89080223-ddfdd880-d3ba-11ea-8887-98c09ad2f62e.jpg)
![debug](https://user-images.githubusercontent.com/68129013/89080224-de966f00-d3ba-11ea-92db-0f1737ea15a6.jpg)

### **System Information:**
- OS: Window 10 2004
- Browser: Firefox 79.0
- Dark Reader version: 4.9.16

### **Additional context**

Dark reader in Firefox 79.0 with A new profile in default path (c:\user\...) works and no any loading.

**Comment by Gusted** [comment]
> 3\. Create new profile and set to ram disk.

I only can set a name...

Also this seems something with Firefox Sync. Do you have any special network settings or releated?

**Comment by agwEgamE** [comment]
![0](https://user-images.githubusercontent.com/68129013/89115877-f1df3280-d4bf-11ea-97d5-309f256cae38.jpg)
![1](https://user-images.githubusercontent.com/68129013/89115879-f4418c80-d4bf-11ea-9da5-9b6690873547.jpg)
![2](https://user-images.githubusercontent.com/68129013/89115880-f4da2300-d4bf-11ea-875d-f79f6354df2c.jpg)

Firefox is not signed in so this may not related to Firefox Sync.
Since this caused after Firefox update and nothing changed to Firefox included network setting, the only casue should be Firefox version.
Therefore, I rolled back Firefox version and Dark reader work fine.

**Comment by Gusted** [comment]
Seems like firefox issue, so reporting a bug won't help as it will get on the backlog somewhere who nobody will ever look.
So could you have a look with this [debug-firefox.zip](https://github.com/darkreader/darkreader/files/5012230/debug-firefox.zip)
build and see if the problem is solved. I just added a extra check if sync is acutally their.

**Comment by agwEgamE** [comment]
Yes this solved the problem.
# With debug-firefox version
![04](https://user-images.githubusercontent.com/68129013/89132012-a53d3b00-d543-11ea-9dc3-0934cdb01ef8.jpg)
# With Firefox addons version
![05](https://user-images.githubusercontent.com/68129013/89132013-a5d5d180-d543-11ea-92a1-6bb225062e4d.jpg)

**Comment by Gusted** [comment]
Will open up a PR to fix this for the next version 👍🏽
