### ISSUE TITLE
[BUG] Doesn't work on firefox home page

### ISSUE THREAD

**Issue by anmol257** [darkreader/darkreader#3299]
### **Describe the bug**
Whenever the home button is clicked suddenly white light glares on the eyes which is harmful to eyes in firefox laptop. Even in fenix the extension faces the isue whenever any website is visited.
### **Steps to reproduce**

- Go to '...'
- Click on '...'
- Scroll down to '...'

### **Actual behavior**

A clear and concise description of what actually happened.

### **System Information:**
 - OS: [e.g. iOS 11]
 - Browser: [e.g. Chrome 73, Safari 13]
 - Dark Reader version: [e.g. 4.9.9]

**Comment by Gusted** [comment]
Fill out the Issue template. Your talking about home and than back to Fenix.
