### ISSUE TITLE
Storing Site specific custom settings

### ISSUE THREAD

**Issue by dfpoon** [darkreader/darkreader#33]
This feature request may be a bit demanding. But could you store those site specific customization in the extension locally, so that we don't need to change it every time?

e.g. Even for the dark theme, I may prefer a contrast with -30% for one particular site, while other sites remain at -10%.

uBlock Origin has this kind of site specific customerization. You may take a look at its source code:
https://github.com/uBlockOrigin/uAssets

**Comment by txomon** [comment]
In my case, I see this as a killing feature, not because of contrasts (which would also be welcome) but because there are a lot of places in the "Not inverted list" that should be using the Light mode rather than not being inverted.

**Comment by Baccanno** [comment]
+1

**Comment by aidalgol** [comment]
I also want to use different theme engines on different sites.

**Comment by yubo56** [comment]
Would having the "cycle engines" hotkey be able to go through a subset of engines, or being able to set hotkeys for "use XXX engine" solve your use case? I have the same problem and think my solution would be much faster to implement and still be fine for my use case

**Comment by Baccanno** [comment]
It won't solve the use case. Every site might have its own particular setting

**Comment by yubo56** [comment]
Oh, sorry, I didn't see you need contrast adjustment, yeah that won't work for you then
