### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3300]
**Website**
https://music.163.com/ 

**How to Reproduce**
> 1. Go to https://music.163.com/ site

**Expected behavior**
Background of some content should be dark.

**Actual behavior**
Background of some content are in white, including the player at the bottom, the scroll up botton, and two other elements.

**System info:**
 - OS: Windows
 - Browser: Google Chrome
 - Darkreader Version: 4.9.16

**Comment by sprinkledcheese** [comment]
Can you give specific page or some screenshot?

**Comment by Gusted** [comment]
#3304 should fix for most part the damage.
