### ISSUE TITLE
[Broken Website]  white flash on git.sr.ht

### ISSUE THREAD

**Issue by B0pol** [darkreader/darkreader#3307]
**Website**
https://git.sr.ht and all hosted projects on it, e.g. https://git.sr.ht/~cadence/bibliogram
**How to Reproduce**
An example of this is
1. Go to the bibliogram project (2nd link) or any other project you know on git.sr.ht
2. Browse the website by clicking on links

**Expected behavior**
The page is dark instantly

**Actual behavior**
The page is dark after about one second

**System info:**
 - OS: Android
 - Browser: Firefox nightly
 - Darkreader Version: 4.9.16
 
**Additional context**
This is not related to mozilla-mobile/fenix#6313 which only happens when you load a website in a new tab. Except this first white flash which is due to a browser bug, there are no other white flashes on any website when you browse it **in the same tab** (not using a new tab). But on git.sr.ht it happens, therefore I think it's a darkreader bug.

**Comment by Gusted** [comment]
This is normal behaviour due we need to analyze style sheets darken them insert them watch them etc etc etc. A lot of microtask that slows down. This most like due that first paint is being rendered without we already have inserted stylesheets(or it's already inserted but not rendered than we got a Fenix bug right here). And after the First Paint it's being rendered with html { background-color: *something blackish* } and cause to cancel the white flash.

So solution, IDK. Mobile is hard to debug and find if this is a bug or just rather our messy slow code.

**Comment by Gusted** [comment]
Hi!

Dark reader v4.9.17 has been released that has the fix that fixes this issue 🎉.
To make sure you are on the latest version to make sure this is the case.
First, we should make sure your on the new user interface of Dark reader, by doing:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

This should have activated the new user interface and should look like this: ![](https://i.imgur.com/cJJwSrY.png). Make sure to pay attention to the bottom text that says the current version. If it states an older version e.g. 4.9.16 I suggest to remove the extension and re-install it trough https://darkreader.org/ so it will be forced to download the latest version.
If this fix still indicates this issue let me know and hopefully improvements can be made!

Regards,
Gusted

**Comment by Gusted** [comment]
> This is not related to [mozilla-mobile/fenix#6313](https://github.com/mozilla-mobile/fenix/issues/6313) which only happens when you load a website in a new tab. Except this first white flash which is due to a browser bug, there are no other white flashes on any website when you browse it **in the same tab** (not using a new tab). But on git.sr.ht it happens, therefore I think it's a darkreader bug.

Oh it's still being related, from what I can read of the comments the initial color seems to sometimes have also a effect between the same-origin switches

**Comment by apiraino** [comment]
thanks @Gusted the latest  4.9.17 version greatly improves the user experience of Dark Reader (also on FF desktop)! :+1:

**Comment by B0pol** [comment]
@Gusted I even forgot about old design because the new one is the default on my phone and desktop, I don't know why, I didn't change anything.

When will it roll out?

**Comment by Gusted** [comment]
> @Gusted I even forgot about old design because the new one is the default on my phone and desktop, I don't know why, I didn't change anything.

Uhm it should say the current version in the UI. If that is 4.9.16 you can remove the add-on and than re-install it so it will get forced to use the latest version.
