### ISSUE TITLE
[BUG] The Site List in my Dark Reader extension for Firefox keeps resetting/getting deleted since v4.9.16 update

### ISSUE THREAD

**Issue by Mistrelvous** [darkreader/darkreader#3317]
### **Describe the bug**

The Site List in my Dark Reader extension for Firefox keeps resetting/getting deleted.
Dark v4.9.16

### **Steps to reproduce**

-Launch Firefox browser [79.0 (64-bit)] in private window 
-Click on Dark Reader extension (at this point the new version **pop up v4.9.16** keeps popping up, telling me Dark Reader has been updated. I know that I have the latest version, so stop popping up telling me that I do. As soon as I see this pop-up, I just know that my site list is gonna be empty.)
-Click on site list
-All previous saved sites are missing or gone

### **Expected behavior**

I expected my site list from previous days to still be there and not force me to keep adding sites back to the list every day.

### **Actual behavior**

This keeps happening to me once a day now. The extension will pop-up letting me know that I have the newest v4.9.16 and my site list in Dark Reader for Firefox is constantly empty.
Sometimes I will run CCleaner before I shut down the PC for the night.
Is CCleaner somehow able to wipe my site list for the Dark Reader extension?
Or is it because I use firefox in private window mode only?
This never used to happen, and has only started happening in the past few days. 

### **System Information:**
 - OS: Windows 10 Pro version 1909, OS build 18363.959
 - Browser: Firefox 79.0
 - Dark Reader version: 4.9.16

### **Additional context**

I browse Firefox exclusively in Private mode, but closing does not seem to reset extension. (I will check this again to see if it does but I am writing this up in firefox private browser right now.)
Possibly me running CCleaner (v5.69.7865) is doing this but it never used to do so in the past, only recently in the past 3 days did this happen (the latest dark reader update was Jul 31st, three days ago)
The latest version of CCleaner was updated 10 days before Dark reader's latest update, Jul 21st.

**Comment by Gusted** [comment]
> -Launch Firefox browser [79.0 (64-bit)] in private window

Why in private window?

> pop up v4.9.16 keeps popping up,

Seems rather their is a problem with syncing.

> Sometimes I will run CCleaner before I shut down the PC for the night.

What if you restart firefox without running CCleaner. I'm not sure, but CCleaner is rather for weekly usage.

> Or is it because I use firefox in private window mode only? 

What does it say when your not in private window mode?

I will have a look what possible could cause this.

**Comment by Mistrelvous** [comment]
I'm sorry i bothered you with my write-up. I think I have figured out the problem.  Firefox extension settings are apparently now being saved in cookie format (firefox.settings.services.mozilla.com) so every time I used ccleaner to get rid of firefox cookies, it was resetting my Dark Reader extension settings by deleting that cookie.

**Comment by Gusted** [comment]
> I'm sorry i bothered you with my write-up.

Don't worry ^-^ You were detailed I like that :)
