### ISSUE TITLE
[BUG Continuation of ad window pop-ups

### ISSUE THREAD

**Issue by AKasera** [darkreader/darkreader#3321]
Whenever I toggled between dark mode and light mode, I would often get a new tab or window opened up with some type of ad. The ads were most always for express-vpn but also had other ads. I know that what I installed is from official channels because I have used the link posted by you guys in this GitHub and have even verified the ID of the extension. I am using the normal Opera Browser (not GX) if that helps at all. This isn't the first time I've had this issue but there are a few sites these days that I need to toggle between so its kind of annoying. 

You guys closed the issue but it's come back and now there is a screen recording

https://drive.google.com/file/d/1iluzhGmwcnJLpG6SVNSsQdxccHz-GSE2/view?usp=sharing
Sorry, you guys closed this but you did ask for a screenshot/vid thing and this is one when it started acting up again. Also I took this on my phone because I didn't have any screen recording software at the time and didn't want to risk the issue just magically disappearing like it occasionally does

**Comment by Gusted** [comment]
Okay, so.

on 00:15 you Toggle the mode off.
on 00:16 It seems like the site refresh? I'm not sure if this normal behaviour as this shouldn't. Could be opera thingy.

Also when you toggle the mode on the malware site, it seems to happend to open another tab?

After a quick search this seems just some unwanted domain for adware and PUP. I higly recommend to run some software like malwarebytes(free version just for a quick scan). Also it seems like to target content changes on the site.

**Comment by Gusted** [comment]
moonshot
