### ISSUE TITLE
[BUG] Style takes a while to apply when browsing some sites like github and causes a white flash

### ISSUE THREAD

**Issue by wapenshaw** [darkreader/darkreader#3322]
### **Describe the bug**

Whenever I am browsing, sometimes the dark style takes a while to apply to a website causing a white flash. 

Example 

![cKa1W3AfOr](https://user-images.githubusercontent.com/739546/89146620-d1f15280-d543-11ea-8868-a206f5ac5325.gif)

### **Expected behavior**

Once I visit the website I expected  the extenstion to cache the style but maybe its not. 

### System Details 

Firefox 79.0 64bit
Dark Reader: 3.5.4

**Comment by gabriele2000** [comment]
It's still present on Firefox 81.0a1.
It's firefox's fault I guess, still, it doesn't have a dark mode yet so that could be the cause.
Another guess is: dark reader activates only when the site is fully loaded or, at least, the CSS part

**Comment by Gusted** [comment]
#1219 dup

**Comment by tmpm697** [comment]
this is known issue but overloaded with ff 79, ff 78 works smoother.

**Comment by wapenshaw** [comment]
> 
> 
> this is known issue but overloaded with ff 79, ff 78 works smoother.

Thanks, I already had shadowfox custom css setup when I posted this, this only seems to happen on some sites where there is some async sort of loading etc. It lines up with what @gabriele2000 said about not being fully loaded.

**Comment by Gusted** [comment]
Yep so far this issue only has been found on github.com 
Their CSS is a bit weird with loading I already could tell, as they also like to have all their CSS in 1 big CSS file(so also for other unrelated sites).
It mostly also obsevered when you see a big X button in your screen and than the CSS is loading slowly.
