### ISSUE TITLE
Google Chrome german google maps and timeline satellite images inverted

### ISSUE THREAD

**Issue by ndarr** [darkreader/darkreader#3323]
**Website**
maps.google.de
maps.google.com/maps/timeline

**How to Reproduce**
An example of this is
> 1. Go to german Google Maps site (or open timeline in com-version)
> 2. Change to satellite mode 
> 3. Satellite images are inverted

**Expected behavior**
Satellite images shouldn't be inverted as it is on maps.google.com

**Actual behavior**
Satellite images are inverted

**Screenshots**
![image](https://user-images.githubusercontent.com/14993570/89171576-af7e2a00-d581-11ea-8f33-38ba7d322921.png)

**System info:**
 - OS:  Linux
 - Browser: chrome
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
![](https://i.imgur.com/Qf6g1il.jpg)

Hmm this is a weird situation. I don't have it.
Are you familiar with the dev tools? It might be some A/B testing from Google and their changing selectors 🤷🏽‍♀️

**Comment by ndarr** [comment]
Hi, double checked it. Looks like it works for me aswell on the normal google maps page. But the timeline page is broken. The affected element is #activity-map-wrapper. Adding this selector to the theme editor under google.*/maps google.*.*/maps
 fixed it for me

**Comment by Gusted** [comment]
Could you show how it looks like?

**Comment by ndarr** [comment]
See my initial post, every other element got inverted correctly. It is just the satellite image which shouldn't be inverted

**Comment by Gusted** [comment]
> See my initial post, every other element got inverted correctly. It is just the satellite image which shouldn't be inverted

Yes, but I had a look even with git diff. But when changing the modes I saw 0 changes in the html to detect if it's using satelitte or Map. That's why I ask how it looks like in your dev tools.

**Comment by Myshor** [comment]
I found old code and include some fix in a while. ;)

**Comment by Myshor** [comment]
Can you @ndarr try my fix without you changes including #activity-map-wrapper?
To be sure it will work independent the language of maps 😉

**Comment by Gusted** [comment]
Can confirm ![](https://i.imgur.com/SA9oz9d.jpeg)
