### ISSUE TITLE
[BUG] Toggle current site not always working

### ISSUE THREAD

**Issue by MPeti1** [darkreader/darkreader#3329]
### **Describe the bug**

The "Toggle current site" button does not work every time.
When it does not work, the hover and click animations of the button are still working.
Currently I only experience the bug on https://discourse.pi-hole.net/ , but earlier I experienced it on other sites too.

### **Steps to reproduce**

- Go to https://discourse.pi-hole.net/
- Click on "Toggle current site" on the dark reader popup

### **Expected behavior**

The colors get themed or the theme gets turned off, and the icon on the button switches between the "x" and the tick

### **Actual behavior**

Nothing changes

### **System Information:**
 - OS: Windows 10 1903
 - Browser: Firefox 79.0
 - Dark Reader version: 4.9.16

### **Additional context**

Page reload, tab close and page reopen on new tab does not help

**Comment by Gusted** [comment]
Any changes you have pi-hole.net in the sitelist already?

**Comment by MPeti1** [comment]
Yes, the toggle for pi-hole.net is on, otherwise it uses the global configuration (it does not have "only for pi-hole.net" enabled)

**Comment by Gusted** [comment]
Ah yep :( If you have the main domain in the list you can't toggle any sub-domains(bug).
It's planned on this get it fixed before V5 release. I'd like to recommend, to subscribe #373

**Comment by MPeti1** [comment]
no problem. should I close this problem now, or when 373 will be closed?

**Comment by Gusted** [comment]
When #373 is closed this issue will be fixed. So now as it's better to manage 😅
