### ISSUE TITLE
[BUG] Switching to/from custom browser theme breaks user-defined styling

### ISSUE THREAD

**Issue by erkinalp** [darkreader/darkreader#3337]
### **Steps and symptoms**

On Firefox (57+):
Click the blue monster icon of dark reader
More->toggle Browser theme
Browser ignores userContent.css and userChrome.css files until the end of that browsing session

### **Expected behavior**

userContent.css and userChrome.css to take precedence over Dark Reader styling

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 79 beta
 - Locale: Turkish (UTF-8)
 - CPU: x86-64
 - Dark Reader version: 4.9.16

### **Additional context**

Closing and restarting the session, even abnormally by killing the main browser process, reverts to the correct styling behaviour.

**Comment by Gusted** [comment]
Welp, this is a *old* Firefox button that can be watched here.
https://bugzilla.mozilla.org/show_bug.cgi?id=1415267
some bugs that have been merged in the bug above me 
https://bugzilla.mozilla.org/show_bug.cgi?id=1585290
https://bugzilla.mozilla.org/show_bug.cgi?id=1592831

We actually have in our code this comment above the code that causes this
`BUG: resets browser theme to entire`

**Comment by NSExceptional** [comment]
I'm not sure if this is related, but in Chrome, DarkReader seems to ignore CSS variable overrides set with Stylus. My overrides work when DarkReader is off, but not when it is on.

Should I open another issue for this?

**Comment by Gusted** [comment]
> Should I open another issue for this?

Yes


Also the Orginial issue can't be fixed by Dark reader, closing.
