### ISSUE TITLE
[BUG] The text selection color is not set to inverse

### ISSUE THREAD

**Issue by jascodes** [darkreader/darkreader#3339]
When I copy anything from darked url, the textselection color is still the same and most times darks. So give consideration to this missing part.

**Comment by Gusted** [comment]
You should paste the text with ctrl + Shift + v. Than it should be in pasted without any information and just the text and colors should be normal. This is a feature from the browser.

**Comment by jascodes** [comment]
You got it all wrong, I am not talking about pasting. I am saying I can't see text selection because text selection color is also dark.

**Comment by Gusted** [comment]
Than you change the text selection color in the UI

**Comment by jascodes** [comment]
Okey actually this was particular site 'https://audible.in' is using `!important` in ::selection, maybe that is causing the issue. Anyhow not that important since happening in single case. Feel free to keep it shut. I have suggestion though lemme post it on another thread.
