### ISSUE TITLE
[BUG] Can't export settings

### ISSUE THREAD

**Issue by B0pol** [darkreader/darkreader#3346]
### **Describe the bug**
When I open settings -> manage settings -> export settings (json) or dynamic theme (css), I get a white page
### **Steps to reproduce**

- Install Dark Reader on Firefox for Android (79+, then if 79 hasn't rolled out in your country (https://arewefenixyet.com) install Firefox beta or nightly.
- Export settings via settings -> manage settings -> export settings (json) or dynamic theme (css)

### **Expected behavior**
I choose what folder to save my settings in

### **Actual behavior**
I get a white page

### **Screenshots**

<img src="https://user-images.githubusercontent.com/58657617/89382517-49b5ad80-d6fb-11ea-895c-0b2f948eeefa.png" width="300">

### System Information
 - OS: Android 9
 - Browser: Firefox nightly (for android)
 - Dark Reader version: 4.9.16

### **Additional context**
It's probably a browser bug since it works on Firefox desktop

**Comment by Gusted** [comment]
Dup of https://github.com/darkreader/darkreader/issues/3273

I've already found the error code, but was a bit short on time to investigate for a workaround Il hope that I can get a PR for this in a few days.
