### ISSUE TITLE
[Feature Request] Custom selection colours

### ISSUE THREAD

**Issue by erkinalp** [darkreader/darkreader#3347]
**Is your feature request related to a problem? Please describe.**
There is no ability to customise the selection colours. Even the browser itself allows such customisation.

**Describe the solution you'd like**
Primary colour preference for selections.

**Comment by Gusted** [comment]
Hi @erkinalp! 

Please read the blog carefully https://darkreader.org/blog/v4-9/ it should give you all information need to change the selection color. Comment if you have any further question!

Regards
Gusted

**Comment by erkinalp** [comment]
I am in FF79. The extension says 4.9.16 but I see the older UI (no auto toggle, no selection colour choice).

**Comment by Gusted** [comment]
To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

**Comment by erkinalp** [comment]
OK. I though `Preview new design` meant **temporarily apply** CSS changes.
