### ISSUE TITLE
[Feature Request] Do not allow lowering the contrast

### ISSUE THREAD

**Issue by erkinalp** [darkreader/darkreader#3348]
**Is your feature request related to a problem? Please describe.**
The contrast slider currently allows lowering contrast to less than 100%. There are absolutely no use cases that you want to have lower contrast than original website.

**Describe the solution you'd like**
This should be prevented.

**Comment by Gusted** [comment]
Hi @erkinalp!

People are weird and have specific requests, I rather just leave it how it is now and let people self choose if they think lower contrast is better I don't stop them to have it like that.

Regards,
Gusted
