### ISSUE TITLE
[Feature Request] V5: Mouse wheel slider control

### ISSUE THREAD

**Issue by cbf305** [darkreader/darkreader#3351]
I am testing out V5 and it is working very well and has lots of control :-), however, the clickable arrows on either sides of the sliders in V4 are gone, so sometimes it can be difficult to dial in the settings that I want for certain sites.  Could we have support for using the mouse wheel for those fine grain movements.  I think the fine grain controls with the wheel should either be the -/+ 5 like in V4 or -/+ 1.

Thanks for all your hard work on this extension!  (My eyes thank you as well :-)

**Comment by Gusted** [comment]
Hi @cbf305!

This is a good feature to implement, I think it's just a matter of thinking what's the best -/+

Regards,
Gusted
