### ISSUE TITLE
[Feature Request] Darkreader will reveal spoilers behind the common black highlight on black text method.

### ISSUE THREAD

**Issue by Ranzear** [darkreader/darkreader#3352]
**Is your feature request related to a problem? Please describe.**
It's common for forums and other sites to use black highlight on black text to hide spoilers, usually revealing (removing the highlight or changing the text color) on a mouseover or manually selecting the text.

Darkreader is changing the text color to white or equivalent but not changing the highlight, leaving it revealed as white text on black.

**Describe the solution you'd like**
Detect when text highlight color matches text color and don't alter text color, or alter both equally.

**Comment by Gusted** [comment]
Hi @Ranzear!

Unfortunate for this kind of cases we can't do much as this is hard to detect.
We have [dynamic-theme-fixes.config](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config) You can give it self a try or open up a issue for a broken website(just 1 If multiple sites with same issue).

Regards,
Gusted
