### ISSUE TITLE
[BUG] Dynamic theme is completely broken

### ISSUE THREAD

**Issue by liltrigger** [darkreader/darkreader#3353]
### **Describe the bug.**

Dynamic theme seems to not be working on any website, although it works fine on sites that I have added to the list in the past, but it will break if I turn off and on. 

### **Steps to reproduce**

- Go to 'firefox'
- Click on 'dark reader'
- Click on 'mode'
- Select 'dynamic'

### **Expected behavior**

Dynamic theme will act dynamic.

### **Actual behavior**

Dynamic theme is completely broken and does not look right.

### **Screenshots**

![image](https://user-images.githubusercontent.com/58832936/89475850-f87add80-d73d-11ea-84fe-848c0ea74b54.png)

### **System Information:**
 - OS: [Windows version 10.0.19041.388]
 - Browser: [Firefox 79.0]
 - Dark Reader version: [Version 5 preview 4.9.16]

### **Additional context**

This only happens in firefox.

**Comment by Gusted** [comment]
Hi @liltrigger!

Do you have by any chance custom settings for github and the other sites? 
Could you give a try to uninstall Dark reader ->
- Uninstall of dark reader 
- Close Firefox 
- Reboot
- Re-install dark reader on the official way.

Regards,
Gusted
Regards,
Gusted

**Comment by DuccinatorAlpha** [comment]
I can confirm that Dynamic mode is broken across most websites, even the larger ones including reddit, discord, youtube, wikipedia etc. This is happening on edge and I am on the new design. It also sometimes breaks videos, they will simply not render.
![image](https://user-images.githubusercontent.com/59556103/89591162-20199500-d867-11ea-907d-4971404f0425.png)
![image](https://user-images.githubusercontent.com/59556103/89591178-29a2fd00-d867-11ea-8447-b983f126c47e.png)
As you can see on reddit, a bunch of text is missing and the video isn't rendered
![image](https://user-images.githubusercontent.com/59556103/89591346-8ef6ee00-d867-11ea-904b-98799b181da1.png)
![image](https://user-images.githubusercontent.com/59556103/89591333-87cfe000-d867-11ea-9c1f-cd57e5dd8ecf.png)
On github itself
![image](https://user-images.githubusercontent.com/59556103/89591419-c2d21380-d867-11ea-8c2a-c2327af26391.png)

**Comment by Gusted** [comment]
Reset settings in settings menu it has to due with custom settings not sure how even.

**Comment by DuccinatorAlpha** [comment]
Kay I did that, even reinstalled the extension. Still broken

**Comment by Gusted** [comment]
Any error codes in console(asking like 5th to someone with this issue but no responds)?

I really need to change behavior not closing issues.

**Comment by DuccinatorAlpha** [comment]
![image](https://user-images.githubusercontent.com/59556103/89592570-8a800480-d86a-11ea-9ace-2ec5b1f7a558.png)
![image](https://user-images.githubusercontent.com/59556103/89592589-953a9980-d86a-11ea-9671-550851f487c4.png)
![image](https://user-images.githubusercontent.com/59556103/89592600-9bc91100-d86a-11ea-9804-144fc5c96e3a.png)
![image](https://user-images.githubusercontent.com/59556103/89592607-a1265b80-d86a-11ea-813b-2bea0869c33e.png)
most of these are server errors, or content blocked by ublock origin

**Comment by Gusted** [comment]
hmm... What about fresh *temporarily* profile?

**Comment by DuccinatorAlpha** [comment]
idk what you mean by a temporary profile, but I just played around and set brightness to 101% (after restoring defaults) and it fixed a lot of stuff(almost all of it)

Note that only dynamic is broken and the other filters work fine

**Comment by Gusted** [comment]
Hmm yeah I'm sure somethings is going wrong with settings. But I still can't lay my finger on it, as we did almost nothing to the settings and affects small userbase.....

**Comment by DuccinatorAlpha** [comment]
that's sad, I guess I will roll with my current settings for now

**Comment by DuccinatorAlpha** [comment]
![image](https://user-images.githubusercontent.com/59556103/89593143-09c20800-d86c-11ea-9951-413a9b97eced.png)
github at 101% brightness ¯\_(ツ)_/¯

**Comment by Gusted** [comment]
And back to 100% brightness it's still works?

**Comment by Gusted** [comment]
> that's sad, I guess I will roll with my current settings for now

Welp I wished I had the solutions but I can't lay my finger on it as mostly a error should kick in for this kind of things.
