### ISSUE TITLE
[Broken Website] cn.nytimes.com

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3354]
**Website**
https://cn.nytimes.com/

**How to Reproduce**

> 1. Go to the website

**Expected behavior**
"The New York Times" can be clearly seen in the masthead.

**Actual behavior**
"The New York Times" can hardly be seen in the masthead.

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
#3343 Dup.
