### ISSUE TITLE
[BUG] Browser Hangs -Gmail Website - Firefox browser

### ISSUE THREAD

**Issue by anmol257** [darkreader/darkreader#3361]
### **Describe the bug**
Whenever darkreader is used on Gmail on firefox browser it hangs up & slows down the system.

### **Steps to reproduce**

Heading is sufficient.

### **Expected behavior**

It should be a smooth operation.

### **Actual behavior**

Hangs

### **System Information:**
 - OS: [e.g. iOS 11]
 - Browser: [e.g. Chrome 73, Safari 13]
 - Dark Reader version: [e.g. 4.9.9]

**Comment by Gusted** [comment]
Hi @anmol257!

Gmail is a heavy un-optimized website,
With a `Intel pentium N4200 1.1Ghz` it took a good couple minutes to load everything, even with dark reader. 
I recommend to [check this blog](https://darkreader.org/blog/v4-9-16/) and see how you can extract the generated dynamic theme and re-use it in the mode `Static` so it will not re-generate everything.

Regards,
Gusted
