### ISSUE TITLE
Dark Reader breaks dodrio-based sites

### ISSUE THREAD

**Issue by luxxxxy** [darkreader/darkreader#3362]
**Website**: Example website using dodrio - https://iced.rs  
Dodrio github: https://github.com/fitzgen/dodrio

**How to Reproduce**
1. Go to [iced.rs](https://iced.rs)
2. Click "Next"
3. See error!

**Expected behavior**
The website to work.

**Actual behavior**
Nothing happens, and this error is reported:
```
Uncaught TypeError: top(...) is null
    pushFirstChild dodrio/change-list.js:90
    applyChangeRange dodrio/change-list.js:231
    applyChanges dodrio/change-list.js:220
    __wbg_applyChanges_80aff4692bcb5634 https://iced.rs/tour/tour.js:281
    __wbg_elem_binding2 https://iced.rs/tour/tour.js:27
    real https://iced.rs/tour/tour.js:444
    __widl_f_request_animation_frame_Window https://iced.rs/tour/tour.js:285
    __wbg_elem_binding4 https://iced.rs/tour/tour.js:33
    cb0 https://iced.rs/tour/tour.js:228
    __wbg_new_9951dc76868e804f https://iced.rs/tour/tour.js:234
    __wbg_elem_binding4 https://iced.rs/tour/tour.js:33
    cb0 https://iced.rs/tour/tour.js:228
    __wbg_new_9951dc76868e804f https://iced.rs/tour/tour.js:234
    __wbg_elem_binding3 https://iced.rs/tour/tour.js:30
    real https://iced.rs/tour/tour.js:406
    eventHandler dodrio/change-list.js:262
    newEventListener dodrio/change-list.js:138
    applyChangeRange dodrio/change-list.js:231
    applyChanges dodrio/change-list.js:220
    __wbg_applyChanges_80aff4692bcb5634 https://iced.rs/tour/tour.js:281
    init https://iced.rs/tour/tour.js:510
    promise callback*init https://iced.rs/tour/tour.js:507
    <anonymous> https://iced.rs/:12
tour.js line 259 > eval:90:27
```

**Screenshots**
![Bf7dR1aoTu](https://user-images.githubusercontent.com/65794972/89686297-1bd39300-d8cc-11ea-8935-c5e0d3297197.gif)

**System info:**
 - OS: Windows 10 (version 2004, build 19041.388)
 - Browser: Tested in both Firefox 79.0 and Ungoogled Chromium 84.0.4147.89
 - Darkreader Version: 4.9.16

[Also confirmed broken on Chrome and Vivaldi on MacOS.](https://github.com/fitzgen/dodrio/issues/133)
 
**Additional context**
Dodrio/Iced are WebAssembly-based.

**Comment by Gusted** [comment]
Hi @luxxxxy1

We are just adding style elements, but they are detecting it as their own. 
A simple check should be made at their side, in order to fix this. As We can't do much to this other than not styling the page. I will close this issue issue.

Regards,
Gusted

**Comment by luxxxxy** [comment]
Could you point me on how to fix this, I'd be willing to PR it.

**Comment by Gusted** [comment]
Ask it on their issue I'm not familiar with their code base
We neither support custom website support other than config files what won't help

**Comment by luxxxxy** [comment]
Alright.

**Comment by luxxxxy** [comment]
I tried using the JS DarkReader api (`DarkReader.disable()`) as a band-aid fix, to no avail.
