### ISSUE TITLE
[Broken Website] nicovideo.jp

### ISSUE THREAD

**Issue by niconicocolonel** [darkreader/darkreader#3365]
**Website**
https://www.nicovideo.jp

**How to Reproduce**

> 1. Install Tampermonkey, [ZenzaWatch DEV版](https://greasyfork.org/ja/scripts/367968-zenzawatch-dev%E7%89%88)
> 2. Open the video on the site and view the player.
> 3. Check that the volume bar at the bottom of the player does not appear.

**Expected behavior**
Volume bar display. Dealing with the developer tools.

**Actual behavior**
First, the developer tools.
I tried INVERT, CSS and IGNORE INLINE STYLE for the problem selector. It did not respond.

Next, triy userstylesheet. 
In Scr, seek bar is also darkened, which is not the way it should be displayed. This could be addressed with a user stylesheet. 
Only the volume bar did not respond, as did the CSS in the developer tools.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/13079577/89716666-ef159d80-d9e9-11ea-9194-3d7aa7a7dbc8.PNG)

**System info:**
 - OS: Windows
 - Browser: Chrome, Firefox (Scr is Chrome. Also check by Firefox.)
 - Darkreader Version: 4.9.16
 
**Additional context**
In static, the volume bar is still displayed. However, there are many other reversals that need to be corrected, which are not realistic.

Concerns are conflicts with external extensions, the use of variables for selector properties. So, I personally prefer to address the problem areas rather than fix the extension.

**Comment by Gusted** [comment]
Hi @niconicocolonel!

Most if not all of this sites content require a account or is not available for this country.
Do you know for sure the meter element is the problem? For example if you delete it, is it still their or not?

Regards,
Gusted

**Comment by niconicocolonel** [comment]
I was able to respond by rewriting the script. Thank you for nothing.
