### ISSUE TITLE
How to tell dark theme supported page to Dark Reader?

### ISSUE THREAD

**Issue by nwtgck** [darkreader/darkreader#3367]
Hi, thank you so much for wonderful extension!

I use Dark Reader every day, and I develop some web sites, which support dark mode by default.  But, Dark Reader makes my web sites dark again. Could you have any way to tell dark-theme-supported page to Dark Reader?

**Comment by Gusted** [comment]
Hi @nwtgck!

You could add those sites to [this list](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config).
Or if you don't want to rely on the list you can add a `<meta>` tag into the `head` element. The meta element should look like
`<meta name="darkreader" content="112c16363257854828c5af5afc663d50">`

Regards,
Gusted

**Comment by nwtgck** [comment]
@Gusted Thank you very much for your reply!

I'd like to use the way of `<meta name="darkreader" ...`. Could you tell me how it works? 
I tried to find the implementation a little and found the following code. Is this the implementation?
https://github.com/darkreader/darkreader/blob/74195d25af39fb7678e193a5d9f45514005aae16/src/inject/dynamic-theme/index.ts#L378-L380

If so, can I use `<meta name="darkreader" content="this_site_supports_dark_mode">`  instead of "112c16363257854828c5af5afc663d50"?  I'm not sure what "112c16363257854828c5af5afc663d50" is in the "content" attribute.

**Comment by Gusted** [comment]
Oh it's a custom UID implementation. It can be whatever you like to have in it.

**Comment by nwtgck** [comment]
@Gusted Thanks.

Is there any standard way to tell dark-mode-supported site to Web browser? It will help Dark Reader and also help other eye-friendly software.

**Comment by Gusted** [comment]
> Is there any standard way to tell dark-mode-supported site to Web browser?

There isn't one. Maybe in the future.

**Comment by nwtgck** [comment]
Thanks!
