### ISSUE TITLE
[Feature Request] Adjust text color in Dynamic mode?

### ISSUE THREAD

**Issue by NSExceptional** [darkreader/darkreader#3391]
I noticed that in Filter/Filter+ modes, the text color is white. But in Dynamic mode, the text color is an off-white, sepia-looking color. Is there a way to adjust this? I prefer the plain white text that is used in Filter mode. Screenshots below, with the dynamic mode first

<img width="70%" height="50%" alt="dynamic" src="https://user-images.githubusercontent.com/8371943/89952219-759ccb80-dbf2-11ea-990a-517457691fc9.png">
<img width="70%" height="50%" alt="filter" src="https://user-images.githubusercontent.com/8371943/89952225-77ff2580-dbf2-11ea-824b-8fc376c42fae.png">

**Comment by Gusted** [comment]
Hi @NSExceptional 

To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Custom background, text and selection colors (under Theme click See all options, Colors).

For more info: https://darkreader.org/blog/v4-9/

Regards,
Gusted
