### ISSUE TITLE
Icon does not appear on Toolbar

### ISSUE THREAD

**Issue by mannycastaneda** [darkreader/darkreader#3402]
Chrome 84.0.4147.125, Win10

Icon is nowhere to be found in the toolbar- cannot toggle nor change settings. Tried modifying to allow in incognito with no other extensions, but still no icon.

**Comment by Gusted** [comment]
Hi @mannycastaneda!

Could you grab a picture of your toolbar? Is their for example 2x a `>` that you could click on?

Regards,
Gusted

**Comment by mannycastaneda** [comment]
Here's a screenshot of the regular toolbar
![image](https://user-images.githubusercontent.com/3136330/90244826-879f8980-ddff-11ea-9435-e92530a4e16b.png)

Here is the toolbar in incognito mode - the extension is set to display in incognito:
![image](https://user-images.githubusercontent.com/3136330/90244984-ccc3bb80-ddff-11ea-90bd-4882eb98b7d2.png)

**Comment by Gusted** [comment]
Could you click on the 🧩 icon the most right one. It's a new feature of chrome.

**Comment by mannycastaneda** [comment]
Well,  now I feel stupid.... Problem solved - it looks like it was user error id10T
