### ISSUE TITLE
[Feature Request] How to prevent darker reader from reversing the style of other Google extensions

### ISSUE THREAD

**Issue by CraKeyBoy** [darkreader/darkreader#3403]
**Is your feature request related to a problem? Please describe.**
I installed the [Saladict Google extension](https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg/reviews?hl=en), and this extension provides dark mode, and when I set the dark mode of the extension, darkreader reverses the color of the extension, as shown below.
![image](https://user-images.githubusercontent.com/1518543/90213153-9e59d680-de27-11ea-95d4-de734facf5dd.png)

**Describe the solution you'd like**
I have no idea.

**Additional context**

**Comment by Gusted** [comment]
Do you have invert mode enabled in dark reader?

**Comment by CraKeyBoy** [comment]
@Gusted I have enabled invert mode.
![image](https://user-images.githubusercontent.com/1518543/90240613-278b0080-de5c-11ea-91cd-689829847304.png)

This pic is disabled invert mode.
![image](https://user-images.githubusercontent.com/1518543/90240821-89e40100-de5c-11ea-8e42-daac04f013f6.png)

**Comment by Gusted** [comment]
Unfortunate due to a bug #2541 I can't make a good fix for this. As the whole panel is being moved under the page and is not use able. I recommend for now to not enable dark mode for this.
