### ISSUE TITLE
can't change hot-keys on Firefox 

### ISSUE THREAD

**Issue by paperclone22** [darkreader/darkreader#342]
I'm currently changing from chrome which has the option to rebind the shortcut keys for "toggle current site" and "toggle extension". I'd like to be able to change these hot-keys to what I had them in chrome. Also I have another extension that uses the same key binding as the "toggle extension" shortcut, so if there's no way to do this, I'll have to delete one of these extentions

**Comment by txomon** [comment]
Happens the same to me.

I would propose Changing the title to "Can't change hot-keys on Firefox", so that it states clearly the browser

**Comment by alexanderby** [comment]
Firefox 60 should have some API for changing hotkeys.

**Comment by AndydeCleyre** [comment]
I finally figured out how to do it! Thanks @alexanderby !

For anyone finding this who couldn't immediately figure it out, click the "Toggle current site" text and then hit your desired shortcut. 

I'm not sure if this looks different (more obvious) for others, but while it's waiting for my input, it's:

![image](https://user-images.githubusercontent.com/1787385/88208066-ac4c7b00-cc1e-11ea-9233-7cf833a63b40.png)

**Comment by paperclone22** [comment]
> 
> 
> I finally figured out how to do it! Thanks @alexanderby !
> 
> For anyone finding this who couldn't immediately figure it out, click the "Toggle current site" text and then hit your desired shortcut.
> 
> I'm not sure if this looks different (more obvious) for others, but while it's waiting for my input, it's:
> 
> ![image](https://user-images.githubusercontent.com/1787385/88208066-ac4c7b00-cc1e-11ea-9233-7cf833a63b40.png)

Hey thanks a lot! I've been messing with Firefox css for a while now to darkmode my most visited sites. this will save me some time
