### ISSUE TITLE
[BUG] Extension is stuck on "Loading Please Wait" and the dark mode is not working.

### ISSUE THREAD

**Issue by JSJosh** [darkreader/darkreader#3424]
### **Describe the bug**

The extension does not seem to work anymore, after it working all of yesterday. Now, whenever I go to a site it wont load the dark mode, and in the extension itself it continuously says "Loading, please wait", it has been doing this for too long now for me to believe it will stop loading, since it usually loads so fast. This happens despite of restarting the browser and reinstalling Dark Reader.

### **Steps to reproduce**

Open the browser
Try to go to a site, dark mode will never load
Click on extension icon, and it is forever loading

### **Expected behavior**

Any given site to go into dark mode and for the extension to show the various options in its extension menu.

### **Actual behavior**

What happened above, dark mode is no longer working and the extension menu says its always loading.

### **Screenshots**

![image](https://user-images.githubusercontent.com/34352316/90313377-7b402d00-dee2-11ea-9d75-4ea895523cb8.png)

![image](https://user-images.githubusercontent.com/34352316/90313384-8a26df80-dee2-11ea-855a-f1492cbc37dc.png)

### **System Information:**
 - OS: Windows 8.1
 - Browser: Chrome 84.0.4147.125
 - Dark Reader version: 4.9.16

**Comment by erkinalp** [comment]
Reinstall the addon and come back again.

**Comment by JSJosh** [comment]
As said in the issue - I already tried that.

**Comment by Gusted** [comment]
Hi @JSJosh!

This is a specific user bug as I see, so let's see what the cause of this problem is.
Could you go to chrome://extensions/ and click on the blue word like this ![](https://i.imgur.com/gXtYPXE.png).
Also could you enable Dark Reader in Private window and check if that works?

Regards,
Gusted

**Comment by JSJosh** [comment]
This is what I get with background/index.html, I clicked on the error icon in the top right as well.
![image](https://user-images.githubusercontent.com/34352316/90317536-b05b7800-df00-11ea-8253-11b715cb2a3f.png)

As for private window, which I assume is incognito, I have turned on the extension for incognito, and its the same issue, infinite loading.

**Comment by erkinalp** [comment]
Do you have any other conflicting extensions?

**Comment by JSJosh** [comment]
Not that I know of. I havent added any new ones, and this extension was working yesterday.

**Comment by Gusted** [comment]
By any chance you enabled synchronization on/off in dark reader or in chrome?

**Comment by JSJosh** [comment]
To be honest, I dont even know what that is or where to find it.

**Comment by Gusted** [comment]
Did you changed any settings in chrome or dark reader?

**Comment by JSJosh** [comment]
No, I have not.

**Comment by emerson67** [comment]
I´ve got the same issue just after update the extension. Uninstall and reinstall does not fix it. Firefox 79.0 x64.

**Comment by Gusted** [comment]
Hi!

I've made a PR(#3425) for a possible solutions to this problem. 
I would like if you could test this version trough
- Go to chrome://extensions/
- Enable developer mode.
- Click on Load unpacked.
- Load [this file](https://github.com/darkreader/darkreader/files/5079520/build.zip).

Make sure to remove the original one so you won't see a double extension in pop-up. 
Let me know if there are problems with this build!

Regards,
Gusted

**Comment by JSJosh** [comment]
I mean, other than the fact that I (obviously) don't have my whitelist anymore - this works perfectly fine! Thank you :D

**Comment by Gusted** [comment]
> I mean, other than the fact that I (obviously) don't have my whitelist anymore.

I will request a hotfix so hopefully that you can use the original alongside your whitelist.

**Comment by JSJosh** [comment]
That would be quite nice - regardless thank you very much for your help! :grin:

**Comment by fungilife** [comment]
How can this same bug materialize elsewhere a month later, same browser (Mozilla fork) since July, and happen mid-session, without other addon changes or settings?
Pages were already darkened  and suddenly this new tab doesn't reverse.  You click on the addon icon same exact screen with OP. like trying to reach a site and doesn't load up.

System arch linux current.  Add on worked till yesterday.

**Comment by Gusted** [comment]
@fungilife Dark reader has updated and you most likely got auto-updated to v4.9.35 which has several regressions. You can see the recent closed issues about this behavior.

**Comment by fungilife** [comment]
I downloaded the update from here and installed it manually, problem solved.

**Comment by Doxophobia** [comment]
> Hi!
> 
> I've made a PR(#3425) for a possible solutions to this problem. I would like if you could test this version trough
> 
> * Go to chrome://extensions/
> * Enable developer mode.
> * Click on Load unpacked.
> * Load [this file](https://github.com/darkreader/darkreader/files/5079520/build.zip).
> 
> Make sure to remove the original one so you won't see a double extension in pop-up. Let me know if there are problems with this build!
> 
> Regards, Gusted

I'm getting the same problem as OP now, but I'm using it on Opera and I can't do that whole developer mode thing. 

OS: Windows 10
Browser: Opera 81.0.4196.54
Dark Reader version: 4.9.42

**Comment by Gusted** [comment]
If someone has this problem - open up a new issue about it. Locking.
