### ISSUE TITLE
[Broken Website] bromite.org

### ISSUE THREAD

**Issue by B0pol** [darkreader/darkreader#3429]
**Website**
https://www.bromite.org
**How to Reproduce**

1. Go to bromite.org

**Expected behavior**
The website is dark

**Actual behavior**
The website is gray

**System info:**
 - OS: Android
 - Browser: firefox nightly
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
Hi @B0pol! 

What a coincidence a PR(#3428) has been merged to fix this. In order to get this fix you can go to dark reader addon settings. Click on manage settings and enable "Synchronize sites fixes"

Regards.
Gusted
