### ISSUE TITLE
[Broken Website] Upwork.com

### ISSUE THREAD

**Issue by ZeroTex** [darkreader/darkreader#3437]
upwork.com

**How to Reproduce**

Visit the website with the extension on. 

**Expected behavior**
For buttons and dropdowns to not constantly blink from white to black. This is on the Dynamic Theme.

**Screenshots**

https://i.imgur.com/yFhNRaF.png also the buttons on the side to save jobs also blink a lot

**System info:**
 - OS: Windows & Linux
 - Browser: Chrome 84.0.4147.105
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
Ah another blinking hmm.

Does the blinking seem to be the same as https://www.x-kom.pl/g-4/c/1590-smartfony-i-telefony.html ?

**Comment by ZeroTex** [comment]
I can't seem to reproduce any kind of blinking on that website.

**Comment by Gusted** [comment]
Hmm that's weird.

**Comment by Gusted** [comment]
Does enabling/disabling dark reader resolve the blinking?

**Comment by ZeroTex** [comment]
Okay so I did some messing around with it.

Turning dark reader off and on does fix it, but the blinking returns whenever reloading the page. Switching between tabs has no effect.

**Comment by ZeroTex** [comment]
I've been looking at it with the dev tools and it looks like the extension is changing the styling of the classes:

.btn-default.sc-up-c-dropdown

But it should be this:

.btn-circle.sc-up-c-dropdown

**Comment by Gusted** [comment]
> Turning dark reader off and on does fix it, but the blinking returns whenever reloading the page. Switching between tabs has no effect on the issue.

Yep that is the #3138 #3004 Bug. 


Also have a look at this https://github.com/darkreader/darkreader/issues/3411#issuecomment-674205766

> I've been looking at it with the dev tools and it looks like the extension is changing the styling of the classes:
> 
> .btn-default.sc-up-c-dropdown
> 
> But it should be this:
> 
> .btn-circle.sc-up-c-dropdown

Huh? Explain

**Comment by ZeroTex** [comment]
The .btn-default is the class that gets modified on the Upwork page, but Upwork keeps trying to force styles on .btn-default.

Is it possible to specify styles for specific sites?

.btn-circle {
    color: rgb(148, 255, 92) !important;
    background-color: rgb(24, 26, 27) !important;
    border-top-color: transparent !important;
    border-right-color: transparent !important;
    border-bottom-color: transparent !important;
    border-left-color: transparent !important;
}

Doing this in the dev tools fixes it.

**Comment by Gusted** [comment]
Hmm, this basically overrides everything, but permanent as dark reader is doing this, but in `flashes`. Not sure if a temporary solutions should do it as it would be included in the next update that hopefully contains a fix for this flash behavior.

**Comment by ZeroTex** [comment]
As a workaround until the fix is implemented, one can download this Chrome extension [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) and add the aforementioned CSS and it fixes it.

**Comment by Gusted** [comment]
Going to merge it as well into #3411
