### ISSUE TITLE
[Broken Website] - Bing.com/images

### ISSUE THREAD

**Issue by lufadriad** [darkreader/darkreader#3448]
Bing.com/images

How to Reproduce

Visit the website with the extension on. 
select the images tab
Search something.

Expected behavior
Using the Dynamic Theme, the background turns dark as expected but seconds later it turns white again.

Screenshots

https://imgur.com/O71hIGo

System info:

OS: Windows 10
Browser: MS Edge Beta Version 85.0.564.30
Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
Additional info: Restoring the node isn't restoring correctly.
