### ISSUE TITLE
[BUG] [ESPN & such] White backgrounds in certain areas/banners 

### ISSUE THREAD

**Issue by NRN1337** [darkreader/darkreader#3456]
### **Describe the bug**

Some sites like ESPN (ESPN as best example,there's dozen more) have some weird "glitches" when using dark theme. 
At first (not always) it works fine but when you close the tab and re-open it again or have 3-4 more tabs to follow/compare games,it doesn't apply the whole dark theme. Even if you use it on the same tab and you go BACK and re-enter the box score tab,it still stays broken. 

It's mixed with coloring on the team names and you can't even see player's numbers/names either. 
I'll post pictures below from both scenarios. It happens on some websites but most common one I use and notice it consistantly is ESPN. 

### **Steps to reproduce**

- Go to: ESPN.com
- Click on: Any game score box and try going back and re-opening it or have it in mutliple tabs

### **Expected behavior**

To have the originally applied theme when whitelisting and removing it from whitelist which looks like [pic2] and be consistantly just like that

### **Actual behavior**

Bugs out after re-opening the tab/opening mutliple

### **Screenshots**

[pic1] ![image](https://user-images.githubusercontent.com/16810196/90453387-c62f8f80-e0f0-11ea-8595-e2554b00d963.png)

[pic2] ![image (1)](https://user-images.githubusercontent.com/16810196/90453393-ca5bad00-e0f0-11ea-9eb5-792bab3e5736.png)

### **System Information:**
 - OS: Windows 10 Pro x64 1909 Build
 - Browser: Brave 1.11.101 * Chrome 84.0.4147.125 * Edge 84.0.552.61 (Happens on all browsers pretty consistantly)
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
Hi @NRN1337!

I see the listed browsers all have a chromium back-end. Could you try with Firefox as well.
From what you are saying, you are re-opening in a rapid(0-20s delay) between the tabs? It could be that the browser don't give all good information trough because of that or Dark reader is losing sense of elements because of the re-opening etc.

Regards,
Gusted

**Comment by NRN1337** [comment]
It's the same on firefox,I'll upload a screenshot. 
![image](https://user-images.githubusercontent.com/16810196/90839765-91be0c80-e358-11ea-8337-080cc3f80fe7.png)

I'm not even re-opening anything,I just go to espn,click on NBA (https://www.espn.com/nba/) and choose a match I'm interested to check Box Score and this happens. And now its literally so consistant it happens 90% of time I visit and if I want to "fix" it,I have to remove the theme and put it on again which beats the purpose ofc.

**Comment by NRN1337** [comment]
> > Hopefully it's easy to resolve
> 
> Unfortunate not, a lot of time debugging this issue will resolve it 🤷🏽‍♀️

Alright,keep me posted if possible. My apologies for the trouble but it can be super annoying when it's 50/50 and I doubt there's any good alternatives anyway.

**Comment by Gusted** [comment]
Hi @NRN1337!

It could be the same underlaying bug as #3411. So I suggest to subscribe to that issue as well.

**Comment by NRN1337** [comment]
> Hi @NRN1337!
> 
> It could be the same underlaying bug as #3411. So I suggest to subscribe to that issue as well.

Could be. I'll sub.

**Comment by Gusted** [comment]
Merged the fix(#3692) next release will contains those fixes.
