### ISSUE TITLE
This page is protected by browser bypass[Feature Request]

### ISSUE THREAD

**Issue by RashiqAzhan** [darkreader/darkreader#3462]
Browser pages are protected by the browser. Is there anyway to remove this protection feature?

Would like for it work normally on the extension store of various browsers.

**Comment by ktpx** [comment]
Came here to look for exactly this.  I'm having a terrible time installing any browser extensions, as its bright as daylight.   Hopefull this can be implemented.  :+1:

**Comment by Gusted** [comment]
As a extension we can't make a bypass however, in about:config you can disable this protected page somewhere. And for Chrome their is a flag to let run extension on chrome://. And than disable the check in settings(#3426) and than it should work. But it's not a out of the box feature.

**Comment by Gusted** [comment]
#3426 has been merged

**Comment by fred-sheehan** [comment]
about:config

look for this;
extensions.webextensions.restrictedDomains

delete all the sites listed there, save and restart firefox.

**Comment by AntonSamokat** [comment]
@fred-sheehan Thanks for the solution. Dark mode on https://support.mozilla.org pages appeared only after disabling and enabling `darkreader` add-on manually with hotkey `Shift + Alt + A` (Toggle current site). Pressed it several times. 
Linux Firefox version: 125.0.2

Here is recommended something not useful:  [How to disable protection, or enable dark mode, for Firefox pages](https://support.mozilla.org/en-US/questions/1436420)
