### ISSUE TITLE
[BUG] Applying the default style does not work, but works after page unload / load.

### ISSUE THREAD

**Issue by wvxwxvw** [darkreader/darkreader#3482]
### **Describe the bug**

Applying the default style does not work, but works after page unload / load.

### **Steps to reproduce**

- Go to 'for example, https://github.com/darkreader/darkreader/blob/master/package-lock.json '
- Click on 'button "RAW"'

### **Expected behavior**

Dark background, light text.

### **Actual behavior**

Light background, dark text.

### **Screenshots**

![2020 08 20_190728](https://user-images.githubusercontent.com/13194155/90799032-5e10c180-e31b-11ea-8de3-7fa249e06901.png)       

### **System Information:**
 - OS: Windows 7
 - Browser: Firefox 78 ESR
 - Dark Reader version: 4.9.16

### **Additional context**

Unload the tab (for example, using https://github.com/NiklasGollenstede/unload-tabs ), refresh the tab and get the initially expected result - dark background, light text.

![2020 08 20_190814](https://user-images.githubusercontent.com/13194155/90799065-67019300-e31b-11ea-9fea-f5c05d1a4a14.png)

**Comment by Gusted** [comment]
Hi @wvxwxvw!

Oh, that's a security bug right their. As #1446 
I'm pretty sure this is not allowed for a Add-on I will investigate further this week.
But it's normal behavior it's not being darken, A [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1654588) already has been opened by @ShalokShalom

Regards,
Gusted.

**Comment by wvxwxvw** [comment]
The bug is gone. Terms and conditions are the same, current Firefox ESR. The code is now consistently always "white on black". With unloading, reloading and just like that. I don't know what happened, and I somehow missed the exact moment ...))
