### ISSUE TITLE
[BUG] Tiny scrollbars when enabled

### ISSUE THREAD

**Issue by spinedoc777** [darkreader/darkreader#3490]
### **Describe the bug**

When Dark reader is enabled on any website the scrollbars become very thin/small
### **Steps to reproduce**
Go to any website, enable Dark reader

### **Expected behavior**

Scroll bars should stay the same size as when Dark reader is not enabled
### **Actual behavior**

When Dark reader is enabled scroll bars become very small/thin
### **Screenshots**

With Dark reader OFF
![DRoff](https://user-images.githubusercontent.com/36245422/90888413-3275f180-e384-11ea-80f3-cdeffa5f7cfc.JPG)
With Dark reader ON
![DRon](https://user-images.githubusercontent.com/36245422/90888426-39046900-e384-11ea-8d8b-6da4cd4cc146.JPG)

### **System Information:**

Windows 10 Pro Version: 1909 Build: 18363.1016
Browser: Microsoft Edge Version: 84.0.522.61 (Official build) (64-bit)
Dark reader version: 4.9.16

**Comment by Yash-Singh1** [comment]
Don't have this problem on Chrome. This could be fixed possibly by using the `scrollbar-width` property:
https://css-tricks.com/almanac/properties/s/scrollbar-width/

**Comment by Gusted** [comment]
> 
> 
> Don't have this problem on Chrome. This could be fixed possibly by using the `scrollbar-width` property:
> https://css-tricks.com/almanac/properties/s/scrollbar-width/

Unfortunately, this is only for Firefox. Chromium-based browsers has the [::scrollbar pseudo](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar). So it seems Chromium edge is giving some thin scrollbar?

**Comment by kevgilmore** [comment]
Is there a way to invert the dark reader scroll bar? As the default makes it difficult to find because it's the opposite of what you expect from normal UIs.

**Comment by Gusted** [comment]
> Is there a way to invert the dark reader scroll bar? As the default makes it difficult to find because it's the opposite of what you expect from normal UIs.


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Check `(under Theme click See all options, Colors).` the scrollbar option you can customize it to get the best result out of it.
