### ISSUE TITLE
[Feature Request] Change going to website for embedded page after installing

### ISSUE THREAD

**Issue by TotalCaesar659** [darkreader/darkreader#3493]
**Is your feature request related to a problem? Please describe.**
After installing Dark Reader for a first time, it goes to its website.

**Describe the solution you'd like**
I propose to change it to embedded page like Privacy Badger. It would be open off-line and should be great for privacy.

**Additional context**
![1](https://user-images.githubusercontent.com/14265316/90916224-5fa8bb00-e3e9-11ea-891d-e6e0e1ef0102.png)
![2](https://user-images.githubusercontent.com/14265316/90916241-63d4d880-e3e9-11ea-99e3-fe3b18847afd.png)

**Comment by Gusted** [comment]
Not possible. Help pages are customized and on a different repo.
