### ISSUE TITLE
[Broken Website] GitLab

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#3507]
**Website**
https://gitlab.com/explore

**How to Reproduce**
An example of this is
> 1. Go to https://gitlab.com/explore
> 2. It's not dark
> 3. Reload the site or toggle dark reader
> 4. It's dark now

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
Hi @linsui!

It seems like they switched the way of CSS files. I'm not sure why Dark reader is not throwing any errors or why it's not showing anything abnormal. I will have a look tomorrow.

Regards,
Gusted

**Comment by Gusted** [comment]
Hi @linsui!

I think I've identified the issue(Not sure as it's been working for me probably due caching I can't disable from the browser itself).
But I'd like to if you give 
[this](https://github.com/darkreader/darkreader/files/5117707/build-firefox.zip) build a try to adds [support for some experimental DOM](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/as). That Gitlab is using. However I can't test it as all platforms it's now consistent dark on stock dark Reader(4.9.16).

Instructions to side-load:
- Press ctrl + shift + a
- Click on the settings icon ![](https://i.imgur.com/rhlKN16.png) 
- Click on `Debug Add-ons` *Warnings this is white site so be aware for your eyes*
- Click on `Load Temporary Add-on....` 
- Select the file inside the zip(If you haven't unzipped the zip already).
- Go to `gitlab.com/explore` and test if this works and if Stock Dark Reader is still giving a white site.

Side-note for myself as I don't have a branch for this code [the .patch file with the code in the build-firefox.zip](https://github.com/darkreader/darkreader/files/5117742/aslink.zip) to apply it on a later moment when it's confirmed to work

Regards,
Gusted

**Comment by linsui** [comment]
Thanks! But I can't reproduce this issue any more.

**Comment by Gusted** [comment]
Well than I close this issue as nobody else seems to have this issue it was probably a temporary problem on their side 🤷🏽‍♀️

**Comment by linsui** [comment]
I sufferred this problem again and the test build above doesn't fix it.

**Comment by Gusted** [comment]
Hi @linsui!

Could have a try with the latest version of darkreader 4.9.20 It has been pushed some hours ago after your comment.

Regards,
Gusted

**Comment by linsui** [comment]
I'll test it as soon as it is available on AMO.

**Comment by Gusted** [comment]
> I'll test it as soon as it is available on AMO. I tested it on Edge, the new version works well! Thanks!

No problems it probably had to due with #3665

**Comment by linsui** [comment]
The new version works well on Firefox, thanks!
