### ISSUE TITLE
[Broken Website] Misc issues with Kotaku, AV Club

### ISSUE THREAD

**Issue by pranavmarla** [darkreader/darkreader#3512]
**Website**
https://kotaku.com/
https://www.avclub.com/

**How to Reproduce**
Difficult to reliably reproduce: There are a few different issues I've seen -- usually, 1 of them occurs when I visit the site. In other words, not all the issues happen at the same time, every time, but there is USUALLY at least 1 issue present.

**Expected behavior**
Entire page should be dark instead of white, no flashing/fluctuating between black and white, text should be readable.

**Actual behavior**
Both Kotaku and AV Club seem to display a different one of these issues most of the times I visit them:
1. Certain frames of the page (eg. the top frame of the page, where the Kotaku/AV Club logo is displayed), keep fluctuating/flashing between black and white.
2. The bottom frame of the page, containing the comments section, is still white.
3. The text is almost the same colour as the background, making it almost unreadable.

Since these 2 sites are part of the same 'network' of sites, I assume there is a common issue -- perhaps other sites in this same network occasionally experience one or more of these issues as well.

**Screenshots**
3. Unreadable text, taken from https://kotaku.com/
![unreadable-text](https://user-images.githubusercontent.com/6486632/90986410-aa911280-e550-11ea-8e21-3b2d6cccda21.PNG)

**System info:**
 - OS: Windows 10
 - Browser: Chrome 84.0.4147.125
 - Darkreader Version: 4.9.16

**Comment by Gusted** [comment]
Ugh uhm going to merge this issue into #3411 as it's the same underlying issue
