### ISSUE TITLE
[BUG] Darkmode doesn't automatically toggle on with system settings

### ISSUE THREAD

**Issue by Leakbang** [darkreader/darkreader#3513]
### **Describe the bug**

In the settings, the "Use system color skin" option is now broken and is not toggled automatically when the dark mode is toggled on windows.

### **Steps to reproduce**

- Go to settings and enable Use System Color Skin
- Switch to dark mode in windows 10

### **Expected behavior**

The add-on activates and darkens the webpages.

### **Actual behavior**

The add-on doesn't activate and it doesn't darken the webpages.

### **System Information:**
 - OS: [Windows 10]
 - Browser: [Firefox 79.0]
 - Dark Reader version: [4.9.16]

Could anyone else test this feature and verify the issue is not on my end? Thanks :)

**Comment by Gusted** [comment]
Hi @Leakbang!

By any change you have the option `privacy.resistFingerprinting` enabled?
This causes to forces to let websites/add-ons know it's a Light System.

Regards,
Gusted

**Comment by Leakbang** [comment]
Thank you @Gusted 
After disabling `privacy.resistFingerprinting` the addon works just fine.
