### ISSUE TITLE
[BUG] Github user repository contribution color squares

### ISSUE THREAD

**Issue by clarkshaeffer** [darkreader/darkreader#3515]
### **Bug Description**

The new browser version of Github features users' repository contributions' squares in a new style of green, more and more saturated with more contributions per day. The light version of Github looks great in this way:
![Screen Shot 2020-08-23 at 4 46 27 PM](https://user-images.githubusercontent.com/58539767/90991845-f946a880-e560-11ea-91c2-78b8a43ca30b.png)
But the darkreader version does not invert the color scheme, making it look a bit off.
![Screen Shot 2020-08-23 at 4 46 15 PM](https://user-images.githubusercontent.com/58539767/90991872-22673900-e561-11ea-9310-5723cd35a242.png)

I'm not sure whether to put this as a bug or a feature request, and am unsure if this has already been recognized, but I might as well mention it.

### **Steps to reproduce**

- Go to any Github user's profile
- Scroll down to their repository contributions section

### **Expected behavior**

The green colors should show a black-to-green color scheme to show daily intensity of contributions.

### **Actual behavior**

The green color scheme goes white-to-green, same as the light version.

### **System Information:**
 - OS: macOS 10.15.3
 - Browser: Chrome 84.0.4147.135
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
Hi @clarkshaeffer!

Well when github released this new colors for the daily contributions it was already changed to give the correct `darken` color at #3162 and my thought was too to have it a white-to-green scheme however after [testing that myself](https://github.com/darkreader/darkreader/pull/3162#issuecomment-660975432) I prefer the black-to-green scheme. It has too much white in my eyes and noticeable to give it a [backlight dim](https://en.wikipedia.org/wiki/Backlight) to the pixels around on a normal LCD monitor.

Regards,
Gusted

**Comment by clarkshaeffer** [comment]
Ok, good to know it has already been addressed.
Thanks!

**Comment by Gusted** [comment]
> Thanks!

No problems!
