### ISSUE TITLE
[Feature Request] independent activation between tabs

### ISSUE THREAD

**Issue by gilleschapron** [darkreader/darkreader#3521]
First, thanks you very munch for your great work on this extension that save my eyes every days.

I wonder if it is possible to add the ability to activate dark mode independently between tabs, for example:
- I have activated dark mode on a first tab
- I switch to another tab, and I need to deactivate dark mode, so I use alt-shift-D
- When I switch back to the first tab, dark mode would be still activated.

Thanks

**Comment by Gusted** [comment]
Hi @gilleschapron!

Could you try the shortcut `Alt+Shift+A` This should toggle the current site/tab.

Regards,
Gusted

**Comment by gilleschapron** [comment]
Yes it does the job! 
I forgot this because I have switched to the new preview design and there is no reminder of how to configure this shortcuts so this one was disable by Chrome and I was using global activation / deactivation instead.
Thanks.
