### ISSUE TITLE
[BUG] Lightmode for a split second while loading a page

### ISSUE THREAD

**Issue by thany** [darkreader/darkreader#3523]
### **Describe the bug**

While loading a new page, even on the same webite that has dark mode set, the page may go white mode for a split second, resulting in a very clear flash of glaring white.

### **Steps to reproduce**

- Browse around on, for example, Github.

### **Expected behavior**

Always stay darkmode if darkmode is enabled.

### **Actual behavior**

A flash of white, sometimes, when loading a page.

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox 79
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
#1219

**Comment by thany** [comment]
Not the same issue.

That ssue describes the white flash when loading a new tab. I'm describing the white flash when loading a new page on the *same* tab. Even by doing something mundane like using the back/forward buttons, *even* when they don't cause a roundtrip to the server.

**Comment by Gusted** [comment]
Can I ask for your system specifications. As for my old laptop a (Intel Pentium N4200 1.1ghz) I also experiencedtthis issue on every site how small it was from a small test case site to a big site.it's just due it's not fast enough to run first all Firefox code and than Dark readers code to add the fallback(to make it appear like dark)

**Comment by thany** [comment]
It's a laptop with Core i9-8950HK (6 cores, 12 threads), 32GB memory, 1TB NVMe storage, GPU is both Intel Graphics 630 and a GTX 1050Ti Max-Q (not sure which is used for rendering in Firefox, I'm guessing the Intel one).

I really don't think that's slow enough to be having this problem, if it depends on performance 😀

**Comment by Gusted** [comment]
Hi!

Dark reader v4.9.17 has been released that has the fix that fixes this issue 🎉.
To make sure you are on the latest version to make sure this is the case.
First, we should make sure your on the new user interface of Dark reader, by doing:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

This should have activated the new user interface and should look like this: ![](https://i.imgur.com/cJJwSrY.png). Make sure to pay attention to the bottom text that says the current version. If it states an older version e.g. 4.9.16 I suggest to remove the extension and re-install it trough https://darkreader.org/ so it will be forced to download the latest version.
If this fix still indicates this issue let me know and hopefully improvements can be made!

Regards,
Gusted

**Comment by thany** [comment]
I did a cursory test, and I think it might indeed be fixed! 😎

Although I have to say I'm not all over the new design, to be honest.

**Comment by Gusted** [comment]
> I did a cursory test, and I think it might indeed be fixed! 😎

Glad it does 🎉 their might be still some cases probably that causes light mode.

> Although I have to say I'm not all over the new design, to be honest.

That's personal opinion and everyone have their own kind of style 🤷🏽‍♀️. If you think their are ways to improve it make sure to open up a new issue about it.
