### ISSUE TITLE
[Broken Website] Quora's logo is invisible in dynamic dark theme

### ISSUE THREAD

**Issue by felixonmars** [darkreader/darkreader#3526]
**Website**
https://www.quora.com/ (Login needed, perhaps)

![2020-08-26-051941-c824bc](https://user-images.githubusercontent.com/1006477/91229056-d9c79f80-e75b-11ea-9382-bc6204241e22.png)
![2020-08-26-051954-c861ff](https://user-images.githubusercontent.com/1006477/91229061-db916300-e75b-11ea-8078-e18fdf125116.png)

I tried to figure it out myself but failed :(

**Comment by Gusted** [comment]
Somehow dark reader sets it's `fill` value to `none` 
So a little
```CSS
.logo_fill {
    fill: rgb(219, 87, 83) !important;
}
```

Should do it's job

**Comment by Gusted** [comment]
Also how in earth you get so many commits on a day? Are you living on github?

**Comment by felixonmars** [comment]
Thanks!

> Also how in earth you get so many commits on a day? Are you living on github?

I do packaging for Arch so that makes up most of my commits...

**Comment by Gusted** [comment]
Wait, they aren't automated. Well well respect.
