### ISSUE TITLE
[BUG] Leetcode problems don't appear in dark mode

### ISSUE THREAD

**Issue by andre-fu** [darkreader/darkreader#3535]
### **Describe the bug**

Leetcode.com works fine, but going to the problem itself doesn't most of the time, showing a dark screen instead of the darkmode text. 

### **Steps to reproduce**

- Go to Leetcode.com
- Click on a problem

### **Expected behavior**
- expect theme to be dynamically changed to a dark mode

### **Actual behavior**

- theme only occasionally changes to dark mode, no idea why 

### **Screenshots**

https://drive.google.com/file/d/1mHBifLyJRPVQPInGeBk74FvYMOvEnW9U/view?usp=sharing

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome
 - Dark Reader version: 4.9.16

### **Additional context**

It happens randomly, don't know why. Will occasionally work, but most times just shows a black screen. 

PS: Love this extension!!! Fantastic work, thank you so much for building it

**Comment by andre-fu** [comment]
@Gusted @mxiao6  thank you !

Is it possible for you to help me build this from source please? I ran the `npm install && npm run release` but that only builds the 4.9.16 not the source - how do i build it so that I get this bug fix?

**Comment by Gusted** [comment]
Hi @andre-fu!

I think it's rather efficient to use the `Synchronize sites fixes` option. First

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Than

    ⚙Settings -> Manage settings -> Enable Synchronize sites fixes.

Now,
Either re-install the extension or restart the browser in order to get latest fixes.

**Comment by andre-fu** [comment]
@Gusted thank you!

![image](https://user-images.githubusercontent.com/39042250/91750693-81483600-eb91-11ea-98b8-94c5b1d76e3f.png)


While the page is now darkened something else is wrong... I'm exploring it but any advice please?

**Comment by Gusted** [comment]
Hi @andre-fu!

Does it work after disable -> enable the site?

**Comment by andre-fu** [comment]
@Gusted  :( No it doesn't shows the same wonky dark version

**Comment by Gusted** [comment]
@andre-fu is it possible you have any errors in the site itself?
Also maybe a Fresh install of the extension helps?

**Comment by andre-fu** [comment]
@Gusted I've fresh installed the extension & it still persists - The Filter Theme works well, seems to be an issue with Dynamic only? 

What do you mean errors on the site itself? It worked previously (on occasion - see google drive video in issue)

**Comment by Gusted** [comment]
@andre-fu The fix is only for dynamic theme. If you like  to use filter mode you can use that, but it can give bad results on some sites.

If you open the dev tools(ctrl + shift + i), you can go to the console tab and see potential errors.
