### ISSUE TITLE
White flash on rendering on Filter theme

### ISSUE THREAD

**Issue by rishabhdeepsingh** [darkreader/darkreader#3538]
### **Describe the bug**

Whenever I scroll down or up the new content that renders shows a white screen first and then rendered the page.

### **Steps to reproduce**

- Go to [darkreader](https://github.com/darkreader/darkreader)
- Scroll down

### **Expected behavior**

There should be no white flash.

### **Actual behavior**

A white flash displays on the new content.

### **Screenshots**

![darkreader](https://user-images.githubusercontent.com/28526643/91538477-84df8100-e935-11ea-8390-9061e40167c1.gif)

### **System Information:**
 - OS: MacOs Catalina 10.15.6
 - Browser: Chrome 84.0.4147.135 (Official Build) (64-bit)
 - Dark Reader version: 4.9.16

### **Additional context**

The white flash doesn't display on Static or Dynamic theme.

**Comment by Gusted** [comment]
Hi @rishabhdeepsingh!

This is a rendering issue by the browser itself, so I will to get a test-case and let you run it and get some other information as well to open up a chromium bug report.

Regards,
Gusted

**Comment by Gusted** [comment]
[help.zip](https://github.com/darkreader/darkreader/files/5142849/help.zip)
Could you try to unzip this file and disable dark reader and scroll trough the .html inside the unzipped folder, and check if you see this white flash rendering as well?
@rishabhdeepsingh

**Comment by rishabhdeepsingh** [comment]
@Gusted I opened the `.html` file on the same browser and I am seeing a white flash on scrolling. 
So this means that the problem is on my side?

**Comment by Gusted** [comment]
No, this means it's a reproduce able case. Did you had dark reader disabled while scrolling the html?

**Comment by rishabhdeepsingh** [comment]
Yes, I did. I have set darkreader to `InvertListOnly` and also white testing, I turned it off.

**Comment by Gusted** [comment]
Okay, that means it's good. 
So do you have any GPU/Hardware acceleration Enabled or Disabled(Also try to toggle this and try it again could be a certain bug). 
`chrome://settings/?search=Hardware`
![](https://i.imgur.com/8sPgLoH.png) That setting.

**Comment by rishabhdeepsingh** [comment]
@Gusted It is enabled, disabling it creates even bigger white flashes.

**Comment by Gusted** [comment]
Okay got ya.
As this is a rendering bug and now reproduced.
I suggest opening a bug report at [chromium itself](https://bugs.chromium.org/p/chromium/issues/).
So the first step should be filled out normally.
Second step should look like this ![](https://i.imgur.com/4MSgfFX.png)
Third step, bear with me.
It should look like this ![](https://i.imgur.com/BvQYqec.png).
You can copy paste the text and make sure that it's correct for **you**.
`Filter CSS gives white flashes while scrolling`
`Test Case`
```
1. Go to a site
2. Have for example `filter: invert(100%) hue-rotate(180deg)` in HTML element
3. Scroll and see that that non-pre-rendered areas are white.
```
```
1. Go to a site
2. Have for example `filter: invert(100%) hue-rotate(180deg)` in HTML element
3. Scroll and see that the content is there or a dark-ish color to let the content be loaded.
````
```
The non-pre-rendered areas are white and causing a flash in my eyes.
```
```
Hardware acceleration is enabled, disabling this is creating bigger flashes.
This issue was original observed trough dark reader(https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) 's filter mode.
It actually turned out to be reproduced without this extension by a simply Filter CSS.
```
Make sure to attach the [html file](https://github.com/darkreader/darkreader/files/5142849/help.zip). Also attaching a GIF should give the chromium developers a better understanding what's happening. Also check if this happens on Firefox(This is a question in step 3).
If there is anything I can help with, I hear it!
Also it would be nice if you could post the chromium bug report when filled out here so I can watch it too.

Regards,
Gusted

**Comment by rishabhdeepsingh** [comment]
Opened [Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1123316)
on firefox it is showing white color background, not dark.

**Comment by Gusted** [comment]
> on firefox it is showing white color background, not dark.

Oh weird.

> Opened [Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1123316)

I will subscribe to the issue and help out when needed as sometimes they can be *bossy* sometimes from experience.

**Comment by erkinalp** [comment]
> `filter: invert(100%) hue-rotate(180deg)`

The correct value is `filter: hue-rotate(90deg) invert(1) hue-rotate(90deg)`

**Comment by Gusted** [comment]
It's the same underlying bug, it realy doesn't matter a lot

**Comment by Gusted** [comment]
Issue is being continued on another issue tracker. ^
