### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by RocksteadyTC** [darkreader/darkreader#3539]
**Website**
https://github.com

**Expected behavior**
needs to be dark
**Actual behavior**
not dark

**Screenshots**
![image](https://user-images.githubusercontent.com/34389545/91588696-34105e00-e91e-11ea-96ca-9d125a2e2125.png)

**System info:**
 - OS:Linux]
 - Browser: 79.0 (64-bit)
 - Darkreader Version: current version

**Comment by RocksteadyTC** [comment]
firefox

**Comment by Gusted** [comment]
Hi @RocksteadyTC! 

Does it show its activated in the Pop-up?

Regards,
Gusted

**Comment by Fuseteam** [comment]
works fine here, are you sure it is activated @RocksteadyTC

**Comment by Gusted** [comment]
No response.
