### ISSUE TITLE
[BUG] Unit test broken on latest version (v4.9.16)

### ISSUE THREAD

**Issue by jdgarvey** [darkreader/darkreader#3542]
### **Describe the bug**

When trying to run `npm run release` on a fresh install (on the master branch), I am getting a unit test failure.
I also tried from the latest tag (v4.9.16) and got the same result.

### **Steps to reproduce**

Followed the directions to install from a file (https://github.com/darkreader/darkreader#building-for-use).

- `git clone git@github.com:darkreader/darkreader.git`
- `npm i`
- `npm run release`

### **Expected behavior**

All unit tests should pass.

### **Actual behavior**

A unit test in `tests/config/config.tests.ts` failed.

### **Screenshots**

![image](https://user-images.githubusercontent.com/1544557/91623998-ce8a9480-e952-11ea-8743-096ea6213ae8.png)

### **System Information:**
 - OS: MacOS Catalina (10.15.5)
 - Browser: N/A
 - Dark Reader version: 4.9.16

**Comment by Gusted** [comment]
Hi @jdgarvey!

Could you run the `git fetch` and `git pull` command.
And try again if the unit test is still broken?

Regards,
Gusted

**Comment by jdgarvey** [comment]
It works! Thanks :)
