### ISSUE TITLE
[BUG] protected pages cannot be disabled when granted permission

### ISSUE THREAD

**Issue by erkinalp** [darkreader/darkreader#3548]
### **Describe the bug**

 If a protected page is allowed to be modified by darkreader, that page cannot be toggled

### **Expected behavior**

If you grant permission for darkreader to work on protected pages, the dark mode should be able to be toggled just like another website.

### **Screenshots**

Dark mode cannot be disabled on addons.mozilla.org (recommendation of Dark Reader is by pure chance):
![image](https://user-images.githubusercontent.com/5833034/91642584-344f4d00-ea35-11ea-871a-5e65b55e03ff.png)
I tried screenshotting the settings window but it disappears when I capture the picture.

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 81 beta
 - Dark Reader version: GitHub development snapshot mentioned on #3533

**Comment by Gusted** [comment]
Hi @erkinalp!

By any chance you had a look over at #3426
Also, it should just toggle(after you refresh the UI it's a current bug that it will render the old view)

Regards,
Gusted

**Comment by erkinalp** [comment]
I did. Even closing&reopening the tab did not change the result, though.

**Comment by Gusted** [comment]
@erkinalp 
As it seems you have know how to install snapshots. I don't need some fancy instructions
[support.zip](https://github.com/darkreader/darkreader/files/5145824/support.zip)
Go to the master branch, fetch and pull the latest source code. And unzip support.zip
`git apply support.patch`
and than you can build dark reader and it should be fixed.

**Comment by erkinalp** [comment]
Thanks. Fixed.

**Comment by erkinalp** [comment]
this patch broke everything except protected pages

**Comment by Gusted** [comment]
> I still have this issue: I cleared extensions.webextensions.restrictedDomains, but Dark Reader still won't work on the page. I'm on 4.9.51.

Did you enable the corresponding setting in Dark Reader? By-Default dark reader won't try to modify protected site(to avoid errors )

**Comment by DUOLabs333** [comment]
What setting?

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Settings -> Site list -> Enable on restricted pages.

**Comment by DUOLabs333** [comment]
Oh, it's on the new design. Thanks.

**Comment by miltuss** [comment]
I managed to resolve the issue by enabling the option below

<img width="483" height="469" alt="Image" src="https://github.com/user-attachments/assets/89e9c266-4f29-417b-8e51-3b1db6f9ede6" />

Thank you very much for your help
