### ISSUE TITLE
[Feature Request] Edge Chromium support for hotkey settings

### ISSUE THREAD

**Issue by webmaster-cob** [darkreader/darkreader#3559]
DarkReader seems to be working as expected when installed in Microsoft Edge (Chromium version). However, when selecting the "Setup current site toggle hotkey" link, it takes you to the general extensions page in Edge ( edge://extensions/ ). Figured out you can manually type in "edge://extensions/shortcuts", but it'd be great if it could redirect to this location automatically. Curious if there's a plan to have a "native" Edge extension for DarkReader planned.

Thanks!

**Comment by Gusted** [comment]
> Curious if there's a plan to have a "native" Edge extension for DarkReader planned.

https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc

**Comment by webmaster-cob** [comment]
Thanks for the lightening-fast response!

**Comment by Gusted** [comment]
> Thanks for the lightening-fast response!

11 minutes? I made faster answers.
