### ISSUE TITLE
Black text on transparent images is invisible

### ISSUE THREAD

**Issue by quilicicf** [darkreader/darkreader#356]
Hi, 

First of all, thanks for Dark Reader. I've tried lots of solutions to rest my eyes (Stylish and co) but never found one that matches it.

I'd like to report a small inconvenience though. When browsing a page that shows a transparent image with black text, the black text is not visible ([example](https://github.com/ohmtech/flip-public/blob/master/documentation/markdown/overview/model.md)).

![selection_003](https://user-images.githubusercontent.com/5594303/38373456-9cbc02b8-38f1-11e8-94dc-6c856c8b0b5d.png)
![selection_004](https://user-images.githubusercontent.com/5594303/38373463-a01f1a9e-38f1-11e8-9e7d-f7d986f117a5.png)

I've tried to fiddle a bit with the CSS to understand what happens and found a big ol' `background-color: transparent !important` applied from a style tag `<style id="dark-reader-style">`.

This means that lots of diagrams on the net show partially with dark reader installed and the `!important` makes it unfixable (trying to 'win' against that rule with a stylish rule bears no fruits).

I don't know the history behind the CSS rule so I'm not comfortable creating a PR. Can you think of any elegant solution to fix that ?

**Comment by quilicicf** [comment]
@alexanderby 

Yeah, I've discovered the contribution mechanism in the meantime. 
My only issue here is that the behavior explained above is specifically added in a GitHub rule:

```
github.com

INVERT
.jumbotron-codelines
.bg-gray-dark
.bg-gray-dark .form-group
.header-logo-invertocat
.notification-indicator
.label
.label-color
.tooltipped:not(.notification-indicator)::before
.tooltipped:not(.notification-indicator)::after
.HeaderNavlink [data-ga-click*="(Logged out)"]

CSS
header {
    background-color: #dae1e7 !important;
}
.markdown-body img {
    background-color: transparent !important; <==== HERE!
}
```

Without knowing the reason for this rule, I can't revert it or I'd risk breaking something else :( 
Git blame shows you are the last one who edited this line, any idea?

**Comment by goretkin** [comment]
I was having trouble using dark reader on a publisher's website. A search query brings me to this thread.
If someone else doesn't have a ton of time and wants a quick fix for this issue, open the [dark reader dev tools](https://github.com/darkreader/darkreader#use-dev-tools), and place one of the following two solutions in the "Dynamic Theme Editor".

Solution: Invert image all gifs:
```
================================

learning.oreilly.com

INVERT
img[src$=".gif"]
```

Alternative Solution: Put white background behind all gifs:
```
================================

learning.oreilly.com

CSS
img[src$=".gif"] {
    background-color: var(--darkreader-neutral-text) !important;
}
```

I don't know that this solution works on all pages on the publisher, but it made the textbook I was reading readable. More than anything, someone else might come across this and I hope this self-contained example helps.

**Comment by alexanderby** [comment]
Unfortunately in case of mixed light/dark graphics you will have to add a manual fix into `dynamic-theme-fixes.config`.
