### ISSUE TITLE
How do I use it on my website?

### ISSUE THREAD

**Issue by kapooramit** [darkreader/darkreader#3569]
Hi,

I included darkreader.js and toggled the theme. It came on but styles are messed. What am I doing wrong? Do I need to include anything else in my website and also, how do I customize  the styles?

-Amit

**Comment by Gusted** [comment]
Hi @kapooramit!

You say the styles are messed. Do you mean the page doesn't look good? If this is the case does the site looks good with the dark reader extension?

> how do I customize the styles?

You mean modifying the background/foreground color?

Regards,
Gusted

**Comment by kapooramit** [comment]
Hi @Gusted ,

The body text looks dark and nothing readable. However, with the extension, it looks fine - whitish. For sure I am missing something but don't know what. 

I mean customizing the styles in general because this is an official product documentation website and I would need to add some branding styles here.

**Comment by Gusted** [comment]
> The body text looks dark and nothing readable. However, with the extension, it looks fine - whitish. For sure I am missing something but don't know what.

Hmm, does it show any errors in the dev tools console?
Also, does the text looks like ![](https://i.imgur.com/XLI6ubh.png) this when you use the API?

> I mean customizing the styles in general because this is an official product documentation website and I would need to add some branding styles here.

I still don't get what you trying to say.

**Comment by kapooramit** [comment]
Yeah. There is error - I didn't expect but it is there. 

````
Error: Embedded Dark Reader cannot access a cross-origin resource https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.
````

**Comment by Gusted** [comment]
Now you do the exact thing it says.

Before the line that is enabling dark reader e.g. `DarkReader.enable()` You place this line `DarkReader.setFetchMethod(window.fetch)`

**Comment by kapooramit** [comment]
I did that but nothing. I am now getting CORS error:

_Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.cdn.mycompanyname.com/main/assets/css/headerfooter.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://www.mycompanyname.com’)._

Also, it seems that inline styles are being overridden by a stylesheet I link to:

![image](https://user-images.githubusercontent.com/4463752/91884586-ee4bf080-eca3-11ea-8ec1-5452f5cc679d.png)

**Comment by Gusted** [comment]
What if you try 
`DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))` instead of `DarkReader.setFetchMethod(window.fetch)`

**Comment by kapooramit** [comment]
No go. I tried without ";" at the end too :-) . Because of the error below, the dialog that contains this theme toggle code is not showing up now. 

![image](https://user-images.githubusercontent.com/4463752/91886978-c068ab00-eca7-11ea-814c-8b6418a11825.png)

**Comment by Gusted** [comment]
What if you try using this script
```
 0.43 KB

const proxyFetch = (url) => {
    return fetch('https://cors-anywhere.herokuapp.com/' + url);
}
const newScript = document.createElement('script');
newScript.src = "https://unpkg.com/darkreader@latest/darkreader.js";
document.body.appendChild(newScript);
newScript.onload = () => {
    DarkReader.setFetchMethod(proxyFetch);
    DarkReader.enable({
        brightness: 100,
        contrast: 90,
        sepia: 10
    });
}
```

**Comment by kapooramit** [comment]
Same errors as before:

![image](https://user-images.githubusercontent.com/4463752/91889866-2eaf6c80-ecac-11ea-9f8f-3191730943bb.png)

**Comment by Gusted** [comment]
Than I really suggest to take a look at the current CORS policies and get them tweaked to get Dark Reader working.

**Comment by kapooramit** [comment]
Cool! Thanks. I am also considering using the Export Theme feature of the extension. That would be equally good I suppose? Except that it need to be updated with updates that come in the extension?

**Comment by Gusted** [comment]
> That would be equally good I suppose? Except that it need to be updated with updates that come in the extension?

It's equally good(So long you don't have any Iframes in your site or any weird adoptedStyleSheets), but for every CSS(colors etc) changes it requires to be updated. As the `.css` is static and won't be dynamically updated.

**Comment by kapooramit** [comment]
I will have to live with that for now until we get the CORS tweaked.

**Comment by kapooramit** [comment]
Thanks for the prompt support!!! :-)

**Comment by Gusted** [comment]
> I will have to live with that for now until we get the CORS tweaked.

Make sure to not to forgot updating it when your adjusting your styles :)

> Thanks for the prompt support!!! :-)

No problems! Have a great day 🥂 

Regards,
Gusted
