### ISSUE TITLE
[BUG] Dark Reader Inverting Vivaldi Web Panels

### ISSUE THREAD

**Issue by NorianNyx** [darkreader/darkreader#3575]
### **Describe the bug**

As of the most recent update, it appears that Dark Reader is inverting sites loaded via Vivaldi's web panels, even if they are not on the inversion list.

### **Steps to reproduce**

Open Vivaldi and add a web panel for Reddit, set Dark Reader to "Invert only listed" in the Site List. Open Reddit via the web panel.

### **Expected behavior**

Prior to the most recent update, Dark Reader had no affect on web panels at all.

### **Actual behavior**

Dark Reader appears to always invert; have tested on Reddit, Spotify, and Gmail.

### **Screenshots**

![Annotation 2020-09-02 164938](https://user-images.githubusercontent.com/7103726/92048333-4e8e7100-ed3c-11ea-94f2-3558983a86fd.png)

### **System Information:**
 - OS: Windows 10
 - Browser: Vivaldi v3.2.1967.47
 - Dark Reader version: 4.9.17

**Comment by sanon** [comment]
Yep. I suffer from this issue too. Hope it can be fixed.

**Comment by Gusted** [comment]
I really don't have a clue what we changed in order to do this as this wasn't on purpose. Any idea this also could be happening because of a new Vivaldi update?

**Comment by tomasdeml** [comment]
For me there was no update. I just restarted Vivaldi...

**Comment by sanon** [comment]
> I really don't have a clue what we changed in order to do this as this wasn't on purpose. Any idea this also could be happening because of a new Vivaldi update?

I don't think so. This happened all of a sudden. The next day after this happened I received a Vivaldi update.

**Comment by Gusted** [comment]
Somehow the fallback is not getting removed in the web panels what actually should it's hard to debug in a web panel so I hope I can find the the faulty code.

**Comment by penguinairlines** [comment]
Same issue, quite strange. I thought it wasn't Dark Reader since even if I turn it off or exclude the URL, the panel stays dark. However, disabling Dark Reader allows me to see the web panel normally. This is true of both Mobile Version and Desktop Version of the panel. Also, I notice that the way it makes the Web Panel dark is different than the full web page.

Hope this information helps. With some luck, maybe we'll get proper dark web panels! 💯

**Comment by sunarowicz** [comment]
Definitely an extension problem. Just installed the previous version 4.9.16 and the web panel pages are not inverted again as earlier.

**Comment by penguinairlines** [comment]
Great work guys! It appears to be working for me.

**Comment by sanon** [comment]
Works for me too. Thanks for the super quick fix.

**Comment by sunarowicz** [comment]
Works for me too. Thx for the quick fix!
