### ISSUE TITLE
[Broken Website] personal.vanguard.com

### ISSUE THREAD

**Issue by JJCUBER** [darkreader/darkreader#3576]
**Website**
personal.vanguard.com

**How to Reproduce**
[This happens even with blacklisting the site or turning dark reader off from the GUI]
> 1. Go to the site personal.vanguard.com and log in
> 2. Go to any page that has information related to your balance
>     - https://personal.vanguard.com/us/MyHome
>     - https://personal.vanguard.com/us/secfunds/stocks
> 3. Now you have a blank screen that looks like this:
![image](https://user-images.githubusercontent.com/34446698/92059808-30d30300-ed60-11ea-9161-9ff264326991.png)
or
![image](https://user-images.githubusercontent.com/34446698/92059832-42b4a600-ed60-11ea-88b0-ee5632005b66.png)
The only way to view the content is to disable dark reader entirely from chrome settings (clearing cookies does nothing).

**Expected behavior**
The site should look like this (had to disable dark reader in chrome settings to get this to work):
![image](https://user-images.githubusercontent.com/34446698/92060027-be165780-ed60-11ea-8027-cffcf57472d8.png)
Please not that there is more to the page, but had to leave it out due to it all being personal information.

**Actual behavior**
Even with disabling dark reader from within dark reader or blacklisting the site, the site is blank.  The only way to fix it is by completely disabling dark reader in chrome settings or uninstalling the extension, then the site works normally.

**System info:**
 - OS: Windows 10
 - Browser: Chrome 85.0.4183.83 (Official Build) (64-bit)
 - Darkreader Version: 4.9.17

**Comment by Gusted** [comment]
Hi @JJCUBER!

It could be possible that the bank site is blocking weird behaviour(due to our dynamic mode), you could try to use Filter(+)/Static.
Also you say blacklisting say's it stay the same. Are you sure? As blacklisting a site should have 0 code injected or executed into the page from dark reader.

Regards,
Gusted

**Comment by fbearoff** [comment]
Same issue as @JJCUBER, only way to get the website to load properly is to completely disable the extension.

System info:

    OS: Windows 10
    Browser:  Firefox 80.0.1 (64-bit)
    Darkreader Version: 4.9.17

**Comment by nickwerline** [comment]
Dynamic, Filter, Filter+, and static all give the same results. Not even turning the extension off works. Only disabling it through Chrome extension settings fixes the page on a reload.

**Comment by JJCUBER** [comment]
@Gusted As others are reiterating, nothing works except completely disabling the chrome extension from chrome settings.  I would have thought that it wouldn't inject code while blacklisting a site / disabling dark reader from its own gui, but it seems that this is not the case.  It's entirely possible that it temporarily injects code into the site then removes it?  I wouldn't know, but this is an issue that seems to be occurring for others as well.

**Comment by gopipal** [comment]
I agree with @JJCUBER . Same issue for me. I had to turn off the extension completely.

**Comment by Gusted** [comment]
Oh lmao. This is quite funny.

Somehow we are triggering that it seems like javascript is disabled(what we can't even touch or do at all), but I will open up a simple CSS fix to override this ridiculous behavior.

Regards,
Gusted

**Comment by Gusted** [comment]
So now #3602(the fix) is been merged you all want to use this fix of course in order to browse it normally with dark reader.

Do the following

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And than

     Click Dark Reader icon.
    ⚙Settings -> Manage settings -> Synchronize sites fixes.

Have a nice day!

Regards,
Gusted

**Comment by irvinm** [comment]
Thanks for the update @Gusted.  Just an FYI that the fix works well when Dark Reader is enabled and the Vanguard site is enabled.  However, if Dark Reader is enabled but the Vanguard site is disabled, the problem still persists.  Obviously this is much less of a issue than the original problem.

**Comment by gopipal** [comment]
I am running 4.9.19 and have the same issue as @irvinm . I normally turn off darkreader for vanguard.com.

**Comment by Gusted** [comment]
> if Dark Reader is enabled but the Vanguard site is disabled, the problem still persists.

That's weird as that means vanguard somehow detects something what isn't sussposed to be detected. Their is nothing much we can do to prevent this other than not disable vanguard?

**Comment by nickwerline** [comment]
On Chrome, nothing changed for me after synchronizing sites fixes. The fix you made wasn't in my Dev Tools, but I added it manually and it works when vanguard is not disabled.

**Comment by Gusted** [comment]
Oh yeah, it's a bit weird how the syncronize fixes working it doesn't Immediately syncronize it, but mostly after a restart of the browser.
