### ISSUE TITLE
[BUG] Can't toggle dark reader on sub domain when domain is disabled

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#3579]
### **Describe the bug**

When I disable dark reader on a domain, I can't enabled it on sub domain using the toggle current website button.

### **Steps to reproduce**

- Go to github.com
- Disable dark reader on github.com
- Go to docs.github.com
- Dark reader can't be enabled

### **Expected behavior**

Before I can disable dark reader on a domain and enable it on a sub domain, I should be able to enable the domain on sub domain page.

### **Actual behavior**

I had to go to github.com to enable dark reader. The toggle button on docs.github.com doesn't work.

### **System Information:**
 - OS: Win10
 - Browser: Firefox 80
 - Dark Reader version: 4.9.17

**Comment by cyqsimon** [comment]
Same. Many sites these days have a main landing page and a forum under the same domain, and often times the forum is running an old UI that does not offer dark theme.

Take `https://worldoftanks.com/` for example. While this page is nicely dark-themed, `https://forum.worldoftanks.com/` is not.

**Comment by Gusted** [comment]
Duplicate #3359
