### ISSUE TITLE
[Broken Website] PDFs converted to PDFium, used within Chromium based browsers, tested on Brave

### ISSUE THREAD

**Issue by coughingmouse** [darkreader/darkreader#3585]
**Website**
Example pdf link: [Emma by Jane Austen](https://www.gutenberg.org/files/158/158-pdf.pdf)

**How to Reproduce**
> 1. Go to some pdf file online or open a local pdf file with Brave browser
> 2. Hover into the top section or the bottom-right corner of the page if you can't see any UI besides the background.

**Expected behavior**
> The contents in PDF should be inverted, but the UI and background, which by default is dark-themed, should not have been

**Actual behavior**
> Everything within the page is affected by Dark Reader. 
> The brightness of UI and background shines through your dark room onto your fragile retina.

**Screenshots**
![Screen Shot of something already described above](https://user-images.githubusercontent.com/15174845/92127277-1c643880-ee3c-11ea-9e85-8a23e54b7a06.png)

**System info:**
 - OS: macOS Catalina 10.15.6, Debian 10
 - Browser: Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
 - Darkreader Version: 4.9.17

**Additional context**
This could be really useful if fixed.

**Comment by Gusted** [comment]
Hi @coughingmouse!

Unfortunate PDF's in chromium are exposed as 1 big element [as seen here](https://i.imgur.com/s7O0Aon.png) so we can only invert it so the effect will get the PDF inverted and giving the effect of a darkend PDF however the background-color get unfortunate a gray-ish color. At this moment we can't do anything.

Regards,
Gusted

**Comment by coughingmouse** [comment]
@Gusted Thanks for pointing out very kindly that I didn't even try to press F12.
