### ISSUE TITLE
Suppress github.dev by default

### ISSUE THREAD

**Issue by felipecrs** [darkreader/darkreader#3588]
The `*.github.dev` is the default domain for GitHub Codespaces (Visual Studio Code Online). Since it's VSCode, you have the dark theme builtin.

**Comment by Gusted** [comment]
Hi @felipecrs!

Yes, it has a dark theme builtin. But unfortunate it seems like by default it's a white theme(for users that doesn't have a dark mode system enabled) and if that's the case we can't add it into the dark-sites.config

Regards,
Gusted

**Comment by felipecrs** [comment]
But did you see that the effect that Dark Reader causes in VsCode is super awkward?

**Comment by Gusted** [comment]
> But did you see that the effect that Dark Reader causes in VsCode is super awkward?

I really don't know from what I can see it's early access. So let me guess some white flashing?

**Comment by felipecrs** [comment]
By the way, it follows the user choice through VSCode Settings Sync, so in my case, for example, the "default" theme was my preferred one (Dracula - not white).

> So let me guess some white flashing?

No white flashing, but for example, the main window where the code is open becomes dark yellow, pretty weird. The preview-and-scroll bar stays white, I believe if we keep looking we can find more glitches (which is 100% normal for a so complex web page).
