### ISSUE TITLE
[Broken Website] vbulletin

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3589]
**Website**
https://www.vbulletin.com/
and 
http://www.huayuqiao.org/

**How to Reproduce**
> 1. Go to the two websites

**Expected behavior**
Dark background

**Actual behavior**
Light background

**Screenshots**

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.17

**Comment by garamlee500** [comment]
Here's a screenshot of https://vbulletin.com

![image](https://user-images.githubusercontent.com/64779344/92221942-2581f380-ee96-11ea-87a7-46dce84ccff0.png)
