### ISSUE TITLE
[BUG] DarkReader keeps being forced on Gmail (and other sites) every time I open Chrome

### ISSUE THREAD

**Issue by SixelAlexiS90** [darkreader/darkreader#3595]
### **Describe the bug**

DarkReader keeps being forced on Gmail site every time I open Chrome

### **Steps to reproduce**

- Open Chrome
- Go on https://mail.google.com/mail
- Now DarkReader is forced and I have to click on the top left button of DarkReader extension to disable it
- The setting is saved until I close the current instance of Chrome and I open another one, at that point DarkReader is forced again on Gmail

### **Expected behavior**

DarkReader should always remember my preferences

### **Actual behavior**

DarkReader forces his theme even if I don't want to

### **System Information:**
 - OS: Windows 10 Pro 1909 - Build 18363.1049
 - Browser:  Chrome 85.0.4183.83
 - Dark Reader version:  4.9.18

### **Additional context**

This bug started a few days ago, never had a similar problem before.

**Comment by ghjb004** [comment]
It's not just Gmail. I'm seeing this across several sites. Since a few days ago it activated on sites where it had been disabled.

**Comment by SixelAlexiS90** [comment]
> It's not just Gmail. I'm seeing this across several sites. Since a few days ago it activated on sites where it had been disabled.

Yeah, I suspected that but I didn't find another site that shows the same behavior yet, so I didn't want to makes assumptions. 
I hope they will fix it ^^

**Comment by freMea** [comment]
> It's not just Gmail. I'm seeing this across several sites. Since a few days ago it activated on sites where it had been disabled.
Yes. Same issue the current 4.9.18 since a few days. As if it fails to save what need to be excluded or not. My browser is Vivaldi 3.2.1967.47 based on Chromium 84.0.4147.135. It has been working perfectly for years with vivaldi until now. I suspect the bug was introduced in 4.9.17.

**Comment by vaindil** [comment]
The site list is broken as of the most recent version, apparently, because adding/removing sites does nothing at all. Close/reopen the browser and the site list is the same as it was before you made any changes during your last session.

**Comment by vaindil** [comment]
This is also a problem in Firefox, site list changes aren't being saved across browser restarts.

**Comment by erkinalp** [comment]
@Gusted Maybe related to #3549 fix?

**Comment by ghjb004** [comment]
Don't know how long it has been an issue on Firefox but Chrome updated a few days ago.
Co-incidence? I think maybe not...

**Comment by Gusted** [comment]
Hi everyone!

This seems our side.
So or I don't understand this bug our I can't reproduce it, if someone can make a GIF with maybe also the devtools open and than a look at the console tab(first the inspector) would make me understand this bug a lot more. As I think the bug is probably that ![](https://i.imgur.com/DfwhwbY.png) That `--fallback` element isn't being removed.

@erkinalp I actually suspect #3533 or #3586

Regards,
Gusted

**Comment by Gusted** [comment]
> This is also a problem in Firefox, site list changes aren't being saved across browser restarts.

That's another issue. You should open up another issue for that so every issue will only prioritize 1 issue at the time and also is better to find.

**Comment by vaindil** [comment]
> > This is also a problem in Firefox, site list changes aren't being saved across browser restarts.
> 
> That's another issue. You should open up another issue for that so every issue will only prioritize 1 issue at the time and also is better to find.

No, I believe this is the same issue, as stated in the OP. They're toggling Gmail and it isn't saved after the browser restarts.

**Comment by Gusted** [comment]
> I can also manually delete an entry from the site list and it will come right back after restarting the browser.

Okay basic information.
Browser?
Latest dark reader version?
Any custom settings?
Did anything weird to Sync settings -> Please disable the synchronize settings functions so it will only be stored local

**Comment by vaindil** [comment]
I'm using Firefox 81, Dark Reader 4.9.18. It's happening on two different machines, one of which has sync enabled and one which doesn't and never has. I tried disabling add-on sync in the browser that does have it enabled, and that didn't fix the problem.

I opened Firefox's debugger for the extension and tried changing the site list, and I'm seeing this warning:

> Settings synchronization was disabled due to error: Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.

That only appears one time though, and I have add-on sync disabled. I do see a `console.log()` with the saved settings, and it does change as I remove items from the list, but they revert back after restarting the browser.

My guess is that something changed involving the settings sync code, and the quota being exceeded means it's now not saving at all even though the `console.log()` statement says it's being saved.

**Comment by freMea** [comment]
I tried to disable sync features in Vivaldi 3.2.1967.47 (based on Chromium 84.0.4147.135) to no avail. For instance, I disabled DR for Facebook but after restarting browser with sync off, DR is enabled again on FB.

I really think this bug has occurred since 4.9.17.

**Comment by ghjb004** [comment]
Google Chrome
Version 85.0.4183.83 (Official Build) (64-bit)

I don't know about synch because my Dark Reader options are not available, the options menu item is greyed out and unavailable in the drop down menu. The extension options item is missing from the "manage extension" page.

<img width="1177" alt="Screen Shot 2020-09-07 at 08 50 00" src="https://user-images.githubusercontent.com/66056391/92337969-0084bf00-f0e8-11ea-8d49-c489d6189306.png">

<img width="1372" alt="Screen Shot 2020-09-07 at 08 52 00" src="https://user-images.githubusercontent.com/66056391/92337974-0b3f5400-f0e8-11ea-8241-c2a37c563c26.png">

**Comment by Gusted** [comment]
> I don't know about synch because my Dark Reader options are not available, the options menu item is greyed out and unavailable in the drop down menu. The extension options item is missing from the "manage extension" page.

Uhm you should left click on the dark reader icon instead of right click.

**Comment by ghjb004** [comment]
I know about that menu, but I thought there might be more. I see no synch option in the left click menu.

**Comment by Gusted** [comment]
Do the following

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And than

     Click Dark Reader icon.
    ⚙Settings -> Manage settings -> Enable setting sync


.

**Comment by ghjb004** [comment]
I would have never looked for a setting under there 👍 

Anyway seems you have just pushed an update and now my dev tools has no "preview new design."

Only "switch to old design". 

But no worries I will wait until this update gets up and running.

**Comment by freMea** [comment]
> Do the following
> 
> ```
> Click Dark Reader icon.
> Click Dev tools (in the bottom-right corner).
> Click Preview new design.
> ```
> 
> And than
> 
> ```
>  Click Dark Reader icon.
> ⚙Settings -> Manage settings -> Enable setting sync
> ```
> 
> .

I did this and enabled sync feature of DR. Then I restarted my browser. Facebook keep being reset as darken. DR 4.9.19 old UI has been reset. Its sync feature has been disabled by itself. I tried several times.

Does it mean DR fail to save its settings between session ? I don’t see such issue with other extensions I have.

**Comment by vaindil** [comment]
Can confirm the same thing, enabling or disabling the settings sync option has no effect on this bug.

**Comment by Gusted** [comment]
Weel it seems like 4.9.19 should fix it as @alexanderby made a nice  PR #3605

**Comment by freMea** [comment]
> Well it seems like 4.9.19 should fix it as @alexanderby made a nice PR #3605
> 
> EDIT: wrong button didn't mean to close it.

As I said 2 posts above yours, the bug was still there in 4.9.19 when I ran my test (or maybe I forgot to run them). But today, I didn’t change anything and when I opened my browser, the rule I set for Facebook was respected and after further tests, DR seems to save site rules changes now.

**Comment by Gusted** [comment]
> As I said 2 posts above yours, the bug was still there in 4.9.19 when I ran my test (or maybe I forgot to run them). But today, I didn’t change anything and when I opened my browser, the rule I set for Facebook was respected and after further tests, DR seems to save site rules changes now.

That means the fix kicked in, it's a bit weird how the current storage is handled. Their is no define method to force it as even a browser close/open won't always force it.

**Comment by vaindil** [comment]
I can confirm that 4.9.19 seems to have resolved the issue. Thanks!

**Comment by Gusted** [comment]
That are 2 individual persons seems good to me.
