### ISSUE TITLE
[BUG] JSON Beautifier & Editor

### ISSUE THREAD

**Issue by Zailer43** [darkreader/darkreader#3599]
### **Describe the bug**

This bug is that when you see a JSON with [JSON Beautifier & Editor](https://microsoftedge.microsoft.com/addons/detail/json-beautifier-editor/kpfjmbnldfjpgbglcdcmlkekajbcjlem) extension in "tree" mode (the one that comes by default) you don't see the variable name unless you hover over it

### **Steps to reproduce**

- Install the extension in the browser (in this case Microsoft Edge Chromium)
- Go to an API where you're sent JSON (for [example](https://api.mojang.com/users/profiles/minecraft/Zailer43))

### **Expected behavior**

See the name of the variable

### **Actual behavior**

Variable of the same color as the background, totally invisible unless you hover over it

### **Screenshots**

![image](https://user-images.githubusercontent.com/63565983/92317590-00e26480-efd9-11ea-934d-56654878af75.png)
![image](https://user-images.githubusercontent.com/63565983/92317598-19527f00-efd9-11ea-9fb8-639a9910ff00.png)
![image](https://user-images.githubusercontent.com/63565983/92317607-4a32b400-efd9-11ea-9d08-64e87ec7c97f.png)

### **System Information:**
 - OS: Windows 10 2004
 - Browser: Microsoft Edge Chromium 85.0.564.44
 - Dark Reader version: 4.9.18
-  JSON Beautifier & Editor version: 0.1.9

**Comment by Gusted** [comment]
Hi @Zailer43!

Unfortunate the extension is using the injectCSS option as extension which means we have 0 control to modify that color and make it actually visible. Other than disabling dark reader on those sites their isn't much we can do from our side.

Regards,
Gusted
