### ISSUE TITLE
Any ways to turn off some features to make it faster? 

### ISSUE THREAD

**Issue by resting** [darkreader/darkreader#3607]
It looks nice, but it's extremely slow, and in some cases it flips between light/dark mode for a while and stays in light mode.

Had to disable it unfortunately. Are there any features that can be turned off so it could be smoother?

**Comment by Gusted** [comment]
Hi @resting!

Well I don't know what your doing computer is doing, but the first code being executed since the latest version is to make it dark mode(fallback style). If you think it's extremely slow I suggest to have a look at Filter(+) and Static mode.

Regards,
Gusted
