### ISSUE TITLE
Is there a way to make Dark Reader work on OneTab?

### ISSUE THREAD

**Issue by 537** [darkreader/darkreader#3611]
It says that the page is protected by my browser so I can't enable anything and adding _chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/onetab.html_ to the inverted list doesn't do the job.

**Comment by Gusted** [comment]
Hi @537!

Well first I suggest to enable the `chrome://flags/#extensions-on-chrome-urls` flag.
Than we you can bypass this protected check for Dark Reader by


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And than


    Click Dark Reader icon.
    Click Settings.
    Click Site List
    Click Enable on restricted pages

Regards,
Gusted

**Comment by 537** [comment]
I can't find the very last setting (restricted pages) you mentioned.

**Comment by Gusted** [comment]
> I can't find the very last setting (restricted pages) you mentioned.

Do you have the latest version 4.9.19? And the new design?

**Comment by 537** [comment]
I just updated as I have to do it manually since I'm running Chromium, I did everything you said and I can now enable/disable Dark Reader on OneTab but still, nothing changes.

**Comment by ltnn** [comment]
A workaround is to create another profile (user), and install dark reader on the new profile and open it in a new window.

**Comment by Gusted** [comment]
> I just updated as I have to do it manually since I'm running Chromium, I did everything you said and I can now enable/disable Dark Reader on OneTab but still, nothing changes.

Did you enabled chrome://flags/#extensions-on-chrome-urls ?

**Comment by 537** [comment]
Yes...

**Comment by Gusted** [comment]
Doesn't work for me either and It seems Google is just restricting Dark Reader. 🤷🏽‍♀️

**Comment by ars4l4n** [comment]
> Doesn't work for me either and It seems Google is just restricting Dark Reader. 🤷🏽‍♀️

Has it worked at any point for you?
I've unsuccessfully tried it so far with the latest Chrome Build (90.0.4430.93) (Official Build) (64-Bit) and the latest Vivaldi Browser Build (3.8.2259.37) (Stable channel) (64-Bit)

**Comment by Gusted** [comment]
> Has it worked at any point for you on any browser?

Nope and it never will due to security.

**Comment by m4heshd** [comment]
It sucks. Webstore is freaking blinding. Since Chrome's own web contents dark mode works on it, I wish it was possible to enable that only for the Webstore.

**Comment by MulverineX** [comment]
"""security"""

**Comment by yurenchen000** [comment]
I wish chrome://flags/#enable-force-dark could apply for only restricted pages.
To supplement the lack of dark-mode on restricted pages,
but it over fire and mess up other webpages

**Comment by yurenchen000** [comment]
> Hi @537!
> 
> Well first I suggest to enable the `chrome://flags/#extensions-on-chrome-urls` flag. Than we you can bypass this protected check for Dark Reader by
> 
> ```
> Click Dark Reader icon.
> Click Dev tools (in the bottom-right corner).
> Click Preview new design.
> ```
> 
> And than
> 
> ```
> Click Dark Reader icon.
> Click Settings.
> Click Site List
> Click Enable on restricted pages
> ```
> 
> Regards, Gusted

2023, chrome 110.0, ubuntu 22.04, x11
seems not work

**Comment by yurenchen000** [comment]
> I wish `chrome://flags/#enable-force-dark` could apply for only restricted pages. To supplement the lack of dark-mode on restricted pages, but it over fire and mess up other webpages

my final workaround:
- enable-force-dark (for all pages) // it's weird on some page
- dark-reader dev tools manually add custom css // to fix broken page
