### ISSUE TITLE
[BUG] Tables in Notion

### ISSUE THREAD

**Issue by stankovictab** [darkreader/darkreader#3615]
### **Describe the bug**

Table borders in Notion aren't clearly visible with dark mode, regardless of whether the site's dark mode is on or off.

### **Steps to reproduce**

- Go to 'www.notion.so/'
- Switch to Notion's dark mode from the settings (or don't)
- Create a page
- Create a table
- Turn on Dark Reader

### **Expected behavior**

Borders should be visible.

### **Actual behavior**

Borders are so dark you can't see them.

### **Screenshots**

The standard dark mode
![Annotation 2020-09-09 020052](https://user-images.githubusercontent.com/62820268/92539015-8fa4ea80-f240-11ea-9ddc-0406135a17c9.jpg)

Dark Reader
![Annotation 2020-09-09 020131](https://user-images.githubusercontent.com/62820268/92539043-9e8b9d00-f240-11ea-9bdb-2e40b5c0a4be.jpg)

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome
 - Dark Reader version: 4.9.19

**Comment by Gusted** [comment]
Hi @stankovictab!

Unfortunate this product seems to be enterprise.
Are you familiar with the dev tools?

Regards,
Gusted

**Comment by stankovictab** [comment]
I'll see if I can muster somrthing up in the dev tools, but the last time I tried it I got lost in all the css, it seemed quite complicated. I'll update this thread if I come up with something.

**Comment by Gusted** [comment]
> 
> 
> I'll see if I can muster something up in the dev tools, but the last time I tried it I got lost in all the css, it seemed quite complicated. I'll update this thread if I come up with something.

Well I assume it's probably a border-color CSS e.g. in this example
![](https://i.imgur.com/goimUNH.png)
Or it's a custom element and in that case you can use the ![](https://i.imgur.com/rhIEg9m.png) inspect button to get the element.

**Comment by yarub123** [comment]
@stankovictab It's been 3 years did you muster up anything yet?

**Comment by stankovictab** [comment]
@yarub123 Hi there, well, I gave up on using Dark Reader for Notion, and switched to Notion Enhancer. 
It's a browser extension that gives you the ability to apply Themes to Notion, and even your own CSS changes. 
Apart from that you can use it to do a whole lot of other fixes and optimisations to Notion, I really recommend it. 
I'm using a theme I made for Notion, but I'm sure you'll find some good ones in the included list. 
[Here's](https://github.com/stankovictab/.dotfiles/blob/main/notion-mgz.css) the link if you want to try it out, however it's a work in progress. 

This is how that same table looks like now. 

![image](https://user-images.githubusercontent.com/62820268/234876291-6d8966e8-5faa-4565-a9c3-bfff4de75c2f.png)

**Comment by yarub123** [comment]
@stankovictab Dude you're fucking LIT. This is super awesome. Love you man. Bless you ♥️

Also I had originally replied so I can let you relive some nostalgia of a post you made 3 yrs ago that you probably forgot about.

**Comment by stankovictab** [comment]
@yarub123 😂 It really is a blast from the past. Glad I could help man, thank you!

**Comment by sunnysamantara** [comment]
Is this issue fixed I'm still facing this issue at the latest build 2.2.1
