### ISSUE TITLE
Every time I change the viewing settings, an ad page pops up

### ISSUE THREAD

**Issue by anoldmaninthesea** [darkreader/darkreader#3622]
Whenever I change the light, contratst, etc viewing settings, a tab automatically pops up. 
Fortunately I have an adblocker. The adblocker has been able to blocked most of the popups, but not all. They usually redirect me to a gamming site.
Honestly, now I'm wondering if there are substitutes to this chrome app. 
Lately it has had several bugs, some more annoying than others.

The last page the Dark Reader tried to open was: 
https://asuydisi.com/NdS.php?a=6804985&i=2114641459&f=1599743148&y=1500740558&o=429&x=%21NGBAJK%2BHQ3KNQlxc2xhdvGIZc1PHicmrQXsv9OwkpcZfhprIeyLWMaetLS0l5vYu9yJ%2B5WibIx9bwYHhaOYX6k6kfXuijtyXjq5UXMvkRRsyuFoasyd%2FkotBIw5kOaMVoMn5pnQm4AuqsvGmvCglBEjOHFKHzpNARdnaOUeN3max%2BlvmwLvkh0nDyZAlq4BI9dPXiaN6gQfVXWr7LBZLa7FmJvBsSZqGrDaGjgnHv5PrJec2sksJK3zWicCuXLqRccBQlo5DfbID2628Vdt6fYrpgDOHY6sUW4%2BzMRkDG6%2BK0%2FNP%2Fb8FPm6ni6VUCWq2tDKbqKJNeG49O7C7D4bXT4tYKfBPtwdWNkOc1GNr9aKjtEcyF30RG4vw2TubmZ66onuvvg536xbnLhICMl042SYTWFWfslKsHQ6mjM53jPQ%3D&r=&p=&g=

**Comment by Gusted** [comment]
Hi @anoldmaninthesea!

Did you maked sure you have the correct extension?
You can try to uninstall it and than re-install it trough https://darkreader.org/

Regards,
Gusted
