### ISSUE TITLE
[Broken Website] Unreadable text on a number of sites

### ISSUE THREAD

**Issue by athlonusm** [darkreader/darkreader#3625]
Dark Reader makes the text on the sites below difficult to read. I am using the dynamic mode.

https://www.imperial-library.info/
http://www.biology.arizona.edu/
https://calleteach.wordpress.com/
https://calibre-ebook.com/ (move your mouse over the links in the upper panel)
(in Russian) http://tes.ag.ru/
(in Russian) http://www.norma-tm.ru/
(in Russian) https://ilibrary.ru/
(in Russian) http://rusgram.narod.ru/ (e.g., http://rusgram.narod.ru/vved1t.html)

**System Information**
OS: Windows 10
Browser: Brave
Dark Reader version: 4.9.19

**Comment by Gusted** [comment]
Hi @athlonusm!

The sites you have listed are old sites and some even use .gif files as background-images ![](https://i.imgur.com/n4ZFktj.png)
Those sites are known to not work well along side dynamic mode. I suggest to use for this kind of sites Filter(+) or Static theme.

Regards,
Gusted

**Comment by Yash-Singh1** [comment]
@athlonusm
Just a quick FYI, #3726, will probably fix the problem for calibre-ebook.com.
