### ISSUE TITLE
Why is there no NO INVERT rule for dynamic-theme-fixes?

### ISSUE THREAD

**Issue by AlexByte** [darkreader/darkreader#3627]
The sites have areas that are already dark, and the extension can spoil the style on them.

**Comment by Gusted** [comment]
Hi @AlexByte!

Because, it will not make parts white if it's already dark so it's not needed as it won't be inverted but rather made darker.
Also for things that actually get inverted e.g. images we have a `NO IMAGE ANALYSIS` rule.

Regards,
Gusted

**Comment by AlexByte** [comment]
What if I don't want to make them darker?

**Comment by Gusted** [comment]
Than you or disable dark reader or you use CSS to manually reset it's originial value.

**Comment by AlexByte** [comment]
using css to reset all styles is too hard.

**Comment by AlexByte** [comment]
There is NO INVERT rule in inversion-fixes.config. Can this functionality be copied to Dynamic Theme mode?

**Comment by Gusted** [comment]
> using css to reset all styles is too hard.

All styles? Is the site already dark than?



>  Can this functionality be copied to Dynamic Theme mode?

Like I said, not really because we darken background-color and lighten text colors. And we don't invert them.

**Comment by AlexByte** [comment]
Not all site, but big block.
