### ISSUE TITLE
Does not work for local HTML files [Feature Request]

### ISSUE THREAD

**Issue by ljynfo** [darkreader/darkreader#3629]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Gusted** [comment]
Marking as invalid as this should be a Bug report. Also

`Open chrome://extensions page, find Dark Reader, click Allow access to file URLs.`

**Comment by ljynfo** [comment]
Thanks，it's OK after do your suggest. Thank you very mutch.
