### ISSUE TITLE
[Feature Request] Use dark background before page loads (Firefox for Android)

### ISSUE THREAD

**Issue by theRealPadster** [darkreader/darkreader#3632]
**Is your feature request related to a problem? Please describe.**
When I'm using dark mode on my phone (Firefox browser UI, my phone's system UI, and the dark reader addon), and I load a page, it flashes white for a brief second before loading the page. It's pretty disruptive if you're browsing in a dark environment, like before bed. 

**Describe the solution you'd like**
Change the default page background colour to black if the user is has dark mode enabled for the currently-loading site. 

**Additional context**
I'm using the Dark Reader addon for Firefox Nightly for Android. I'm not sure if this issue is something that would be fixable by the Dark Reader addon, or if it's something that would need to be done on the browser level, so I have submitted a bug report there as well.

**Comment by Gusted** [comment]
https://github.com/mozilla-mobile/fenix/issues/6313
