### ISSUE TITLE
[Broken Website] https://asahichinese-j.com/

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#3633]
**Website**
https://asahichinese-j.com/

**How to Reproduce**
An example of this is
> 1. Go to https://asahichinese-j.com/

**Screenshots**

![sshot-012](https://user-images.githubusercontent.com/36977733/93013395-a7a9a080-f597-11ea-8ab7-253ff3c30a99.png)

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.17

**Comment by Gusted** [comment]
Hi @linsui!

It seems that the site is blocking our request to read the CSS rules.
So unfortunate you should use Static/Filter(+) mode on this site.

Regards,
Gusted

**Comment by linsui** [comment]
Thanks!
