### ISSUE TITLE
[Feature Request]能不能根据时间自动开启或关闭插件

### ISSUE THREAD

**Issue by DazzlingGalaxy** [darkreader/darkreader#3637]
1.用户手动设置开启和关闭的时间，24小时制，比如19:00-1:00自动开启，其他时间自动关闭。就像安卓手机的夜间模式(例如MIUI12，在设置-显示-深色模式-定时开启)
2.根据用户当地的日出日落时间自动确定开启和关闭的时间，至于用户当地的日出日落时间如何获得，①根据用户IP判断地理位置②用户手动输入地理位置，以地区或地理坐标的形式。我用过2个支持这一项功能的软件，Iris(https://iristech.co/，作者也有github，后来不怎么在上面更版本了)和WinDynamicDesktop(https://github.com/t1m0thyj/WinDynamicDesktop)，第一个是过滤蓝光的护眼软件，能根据用户当地的日出日落时间全天自动调节屏幕色彩，第二个是桌面壁纸软件，能根据用户当地的日出日落时间全天自动切换壁纸，壁纸颜色的深浅不同，缓解眼疲劳。
以上就是我这个想法的来源，以及我知道的实现方式，不知道插件能不能实现。

**Comment by Gusted** [comment]
你好 @DazzlingGalaxy!

此功能已经实现，请阅读更多关于此的内容[这里](https://darkreader.org/blog/automation/)

祝贺。
Gusted

**Comment by DazzlingGalaxy** [comment]
> 你好 @DazzlingGalaxy!
> 
> 此功能已经实现，请阅读更多关于此的内容[这里](https://darkreader.org/blog/automation/)
> 
> 祝贺。
> Gusted

谢谢，看到了，不过那3个小点太隐蔽了，我一开始都没看到，能不能调得醒目一些？
而且帮助页也没有介绍(https://darkreader.org/help/zh-CN/)，希望添加介绍。
另外，请问坐标是哪个标准的？好像Google地图和国内地图的标准不太一样，按Google地图得填？

**Comment by Gusted** [comment]
> 谢谢，看到了，不过那3个小点太隐蔽了，我一开始都没看到，能不能调得醒目一些？
> 而且帮助页也没有介绍([https://darkreader.org/help/zh-CN/)，希望添加介绍。](https://darkreader.org/help/zh-CN/)%EF%BC%8C%E5%B8%8C%E6%9C%9B%E6%B7%BB%E5%8A%A0%E4%BB%8B%E7%BB%8D%E3%80%82)

嗨！

在新的UI设计中，它们变得更加明显。

你可以通过打开弹出式窗口，然后点击 "开发工具"，再点击 "预览新设计 "来实现。
它可以在设置->自动化中使用。

祝贺。
Gusted

**Comment by DazzlingGalaxy** [comment]
> > 谢谢，看到了，不过那3个小点太隐蔽了，我一开始都没看到，能不能调得醒目一些？
> > 而且帮助页也没有介绍([https://darkreader.org/help/zh-CN/)，希望添加介绍。](https://darkreader.org/help/zh-CN/)%EF%BC%8C%E5%B8%8C%E6%9C%9B%E6%B7%BB%E5%8A%A0%E4%BB%8B%E7%BB%8D%E3%80%82)
> 
> 嗨！
> 
> 在新的UI设计中，它们变得更加明显。
> 
> 你可以通过打开弹出式窗口，然后点击 "开发工具"，再点击 "预览新设计 "来实现。
> 它可以在设置->自动化中使用。
> 
> 祝贺。
> Gusted

好的，再反馈个小问题，吾爱破解的搜索框适配得不太好，不过不影响使用，我使用的其他Discuz!论坛没这个问题。
