### ISSUE TITLE
[Broken Website] www.g2a.com

### ISSUE THREAD

**Issue by dav9597** [darkreader/darkreader#3640]
**Website**
www.g2a.com

**How to Reproduce**
> 1. Go to www.g2a.com
> 2. Click on a random game
> 3. Click all offers

**Expected behavior**
With the site in dark mode, you should see normally all the offers of the various stores

**Actual behavior**
In the dark mode, the offers don't appear, and you see only the top one

**System info:**
 - OS: Windows
 - Browser: Firefox 80.0.1
 - Darkreader Version: 4.9.19

Additional comments

I confirmed this extension is the problem, because switching off both and respectively uBlock Origin and built-in ad-blocking protection from Firefox didn't solve the issue

**Comment by Gusted** [comment]
Hi @dav9597!

It seems like we are triggering something that is causing this behaviour, but that the site is not adding the offers is on their side and should also be fixed on their side. As it's some obfuscated code I don't know how we are trggering. The best way is to have a chat with with G2A only it seems they don't have any public e-mail address and only some form for bussiness or a media inquiry.

Regards,
Gusted

**Comment by dav9597** [comment]
I will leave a message on their page, with the feedback option.
