### ISSUE TITLE
[Feature Request] Use specific strategy for certain elements

### ISSUE THREAD

**Issue by Gravifer** [darkreader/darkreader#3641]
**Problem**
Currently, a user like I either use one of the four pre-defined strategies, or will have to manually modify the style sheet. However sometimes the overall treats just a few elements on a page wrongfully, however the visual integrity is compromised. If **elements can be specified by there HTML tag or attribute**, and accordingly have a strategy different from the overall one applied, this problem can be much mitigated. 

**Desired interface**
The celebrated [AdBlock](https://adblockplus.org/) provides a neat interface: for each visible element it provides a menu item "Block element", and allows the user to block itself, or some higher in the hierarchy including it.

**Comment by Gusted** [comment]
Hi @Gravifer!

The modes are called specific as modes as they have 0 similarity between them and therefor it would be weird to have specific elements treated differently.


>  this problem can be much mitigated.

Well, not really as I can tell already the colors from all 4 modes a whole different color scheme. Where by Filter is using the invert and thereby a 'weird color scheme' and dynamic that colors all colors trough a color and thereby get a correct color scheme to fit every element and Static that is just a pre-defined Stylesheet and color-scheme.

Regards,
Gusted

**Comment by Gravifer** [comment]
Sorry, I have just found I raised this thread! I understand this now, and will close this issue.
