### ISSUE TITLE
[Broken Website] Techspot comments on Fenix Nightly going white

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#3649]
**Website**
https://www.techspot.com/news/86788-mozilla-needs-help-figure-out-youtube-recommendation-algorithms.html

**How to Reproduce**
1. Go to any article on Techspot 
2. Scroll down, and press on open comments
3. All the comments are white until you open dark reader settings to disable and renable it for techspot.com

**Expected behavior**
Dark background with white text

**Actual behavior**
White background with white text

**Screenshots**
![Screenshot_2020-09-16-01-47-40-60](https://user-images.githubusercontent.com/60446763/93260313-d6ee2680-f7be-11ea-8913-62997995ea49.jpg)

**System info:**
 - OS: Android
 - Browser: Firefox Nightly 200914 06:05
 - Darkreader Version: 4.9.19
 
**Additional context**

**Comment by jenabaivab** [comment]
Any fixes possible?

**Comment by Gusted** [comment]
> 
> 
> Any fixes possible?

#3665 :)

**Comment by jenabaivab** [comment]
@Gusted you're the best!
