### ISSUE TITLE
[BUG] Dark reader and pinterest Save buttons cannot used together. Will make web page CPU 99%. Fake Dead!

### ISSUE THREAD

**Issue by smart-z** [darkreader/darkreader#3651]
- OS: MacOS 11.0
 - Browser: microsoft edge 85.0.564.51
 - Dark Reader version: 4.9.19

**Comment by Gusted** [comment]
Duplicate #1222

**Comment by smart-z** [comment]
> Duplicate #1222

Sorry for the repeated question. I can't find a solution, I'm just a computer noob. sorry again.
