### ISSUE TITLE
[BUG] Roundcube Mail is broken if Dark Reader 4.9.17 or later is loaded (even if inactive)

### ISSUE THREAD

**Issue by MartyMacGyver** [darkreader/darkreader#3653]
### **Describe the bug**

Roundcube Mail web client cannot save or send email when Dark Reader 4.9.17 is loaded (even if inactive). First noticed with 4.9.19 as the updates from 4.9.17 onward happened while I wasn't using this system

### **Steps to reproduce**

This is tricky - you need an instance of Roundcube Mail to try this with, and it's not something you'd normally have public access to

### **Expected behavior**

Roundcube Mail should work normally

### **Actual behavior**

When sending an email or saving a draft, Roundcube just hangs until it finally times out.

### **System Information:**

Affects Roundcube 1.41 and 1.48 (I upgraded in the midst of debugging this) via Windows 10 Chrome 85.0.4183.83 (Official Build) (64-bit). Also fails via current 85.0.4183.102 (Official Build) (64-bit). This appears to have broken recently - within the last 10 days or less.

### **Additional context**

I've been using Dark Reader for years, and have never seen this happen. I first thought it was RC not working right with newer Chrome, but I narrowed it down to Dark Reader - even if I disable every other extension this one alone will break RC Mail in a way it didn't do 10 days or so ago when I last used it on this machine.

**I was able to find the original CRX fles for Dark Reader 4.9.16 through 4.9.19. After carefully editing the manifest to prevent upgrade, I was able to load each in turn unpacked, and confirm that 4.9.16 was the last version that worked properly in this regard.**

**Comment by MartyMacGyver** [comment]
This is correlated to the bug I originally opened here, thinking it was Roundcube and Chrome not getting along:
https://github.com/roundcube/roundcubemail/issues/7607

**Comment by Gusted** [comment]
Hi @MartyMacGyver!

Before I get this mail setup. Are their any errors that show up in console?

Regards,
Gusted

**Comment by MartyMacGyver** [comment]
The one error you will always see on RC is for skin.min.css.map being missing. That's normal and unrelated.

Otherwise there is nothing to indicate the issue. Nothing special happens when you save a draft or try to send it... It just spins.

Note I've only confirmed this in Chrome. I will see if I can replicate this in Firefox.

**Comment by Gusted** [comment]
Hi @MartyMacGyver!

After some failed attempts of setting roundcube up. Is their any demo page where you can reproduce this bug?

Regards,
Gusted

**Comment by MartyMacGyver** [comment]
Unfortunately not... you need to be in RCmail to create a draft to see the effect. I just tried with the default CPanel version and unfortunately it seems to be too old (1.3.14) to have the effect. My Softaculous-installed RCmail does though.

I'm not sure how else to debug this. It's definitely a break as of 4.9.17, but I am not sure how to track down the exact issue. If you have some debugging tips I might be able to narrow it down though.

**Comment by randomuser4444** [comment]
Hello @MartyMacGyver, I can confirm this is a problem with me also. 

The fact that disabling Darkreader doesn't fully disable is more of a concern! (so you need to remove the extension fully) 

Also it seems to only break if you have Dark Theme in windows also.

Darkreader + Dark Windows Theme + Chromium (Chrome or Edge).

**Comment by godrider** [comment]
Got the same problem. Can't send any mail when Dark Viewer is enabled in Chrome.
I made a quick video showing the issue, with 3 test scenarios: https://www.youtube.com/watch?v=6epMHy_o7xg

**Comment by Gusted** [comment]
> To make Roundcube send mail again, you have to manually disable Dark Reader in chrome://extensions - the built in toggle extension button doesn't fix it.



> The fact that disabling Darkreader doesn't fully disable is more of a concern! (so you need to remove the extension fully)

Seeing from this 2 sentences, I'm thinking dark reader is triggering something inside Roundcube that's causing this. To confirm my theory it's the best to switch to `Filter` mode and check if this bug persists.

**Comment by MartyMacGyver** [comment]
> Seeing from this 2 sentences, I'm thinking dark reader is triggering something inside Roundcube that's causing this. To confirm my theory it's the best to switch to `Filter` mode and check if this bug persists.

As noted, even with the current Dark Reader toggled off, the problem occurs.

I also switched it on and toggled the various modes (Filter, Filter+, etc) and still, same problem. The only time it doesn't act up is if I disable the current version of the extension. Then things are fine whether the older version is enabled and whether it's active or not in any filter mode.

(Note, I am only ever enabling one version of the extension at a time, and I've already done many tests with only one version installed too. _**If a version of this extension 4.9.17 or later is present AND enabled (whether or not it's toggled ON and regardless of filtering mode) it will exhibit this problem.**_)

**Comment by Gusted** [comment]
> (Note, I am only ever enabling one version of the extension at a time, and I've already done many tests with only one version installed too. _**If a version of this extension 4.9.17 or later is present AND enabled (whether or not it's toggled ON and regardless of filtering mode) it will exhibit this problem.**_)

I think it's a good practice to use [git bissect](https://git-scm.com/docs/git-bisect) to identify the commit causing this as I can't get a reproduce-able setup to do this.

As you mention 4.9.17 is a good commit
```
git bisect start
git bisect bad
git bisect good v4.9.17
```
In the order I've stated. 
To compile the source code by `npm run debug`.
And after side-loading/refreshing(Don't forget this step ahem) the extension in your browser.
And than state if the current commmit is good/bad by the following command.
![](https://i.imgur.com/HNAHPnY.png)
After identified which commit caused this I can understand this issue a lot better.

Regards,
Gusted

**Comment by MartyMacGyver** [comment]
This adds a lot of variables - am I using the same version of Node you did when you produced 4.9.17? The same package versions? I guess we'll find out.

I'll do it as time permits, but as I mentioned the last good commit is 4.9.16, NOT 4.9.17. A lot changed in 4.9.17 so it'll be interesting to see just how much work is involved in recompiling and retesting each bisection.

Did you ever get Roundcube set up? It should be as simple as using Softaculous to install it (using whatever shared web hosting you might happen to have).

**Comment by Gusted** [comment]
> This adds a lot of variables - am I using the same version of Node you did when you produced 4.9.17? The same package versions? I guess we'll find out.

The [dev packages](https://github.com/darkreader/darkreader/blob/master/package.json#L36) are Exact versions. So it's known which version has been used. As for the NPM, NPM LTS and higher should do it and doesn't make a difference from what I can tell.



> I'll do it as time permits, but as I mentioned the last good commit is 4.9.16, NOT 4.9.17. A lot changed in 4.9.17 so it'll be interesting to see just how much work is involved in recompiling and retesting each bisection.

Woops than it's
```
git bisect start
git bisect bad v4.9.17
git bisect good v4.9.16
```
Also, so far I know git bisects has a algorithm to narrow down the exact commit within some steps, and I suggested to use `npm run debug` that has a cache in the back-end so it won't recompile sections that hasn't changed(Doesn't effect the output).


> Did you ever get Roundcube set up? It should be as simple as using Softaculous to install it (using whatever shared web hosting you might happen to have).

That's the problem you need a web hosting, what I unfortunately don't have.

**Comment by MartyMacGyver** [comment]
Just to be sure, once I've cloned this repo and started bisecting, what node commands do I need to run to generate everything necessary to load the plugin?

**Comment by Gusted** [comment]
> Just to be sure, once I've cloned this repo and started bisecting, what node commands do I need to run to generate everything necessary to load the plugin?

`npm install` so the devDepency are the same as the public release.
`npm run debug` this generate a `debug` and `debug-firefox` folder.
Assuming you will use chromium as platform to load the extension, go to `chrome://extensions/` and have Developer mode enabled(top right). This will show a `load unpacked` button, use this to load the `debug` folder.
Now it's side-loaded into the browser after confirming the commit is good or bad, you can re-do the steps on the next commit that is being chosen by git's bissect.

> `npm install` so the devDepency are the same as the public release.
`npm run debug` this generate a `debug` and `debug-firefox` folder.

Now you should use the refresh button on the extension to re-load the whole extension onto the new source code.
![](https://i.imgur.com/kRqRiTr.png)

**Comment by MartyMacGyver** [comment]
Thank you kindly for the thorough explanation! I have never had a reason to use `git bisect` before today... but it's definitely useful knowledge to have.

Here's the result:

```
8d4ee65ef3a0878309d8d7de5f5b20f169f6f5bf is the first bad commit
commit 8d4ee65ef3a0878309d8d7de5f5b20f169f6f5bf
Author: Gusted <williamzijl7@hotmail.com>
Date:   Tue Sep 1 16:35:19 2020 +0200

    Prevent a white flash when the document starts loading (#3533)

    - Prevent a white flash when the document starts loading, but the message haven't been received from the background page yet.
    - Fixed #3523
    - Fixed #1219
    - Fixed #3307
    - Fixed #1965
    - Fixed #695

    Co-authored-by: Alexander Shutau <shutovby@gmail.com>

 src/background/extension.ts                |  8 ++++----
 src/inject/dynamic-theme/css-collection.ts |  2 +-
 src/inject/dynamic-theme/index.ts          |  4 ++--
 src/inject/fallback.ts                     | 11 +++++++++++
 src/manifest.json                          |  1 +
 tasks/bundle-js.js                         |  9 +++++++++
 6 files changed, 28 insertions(+), 7 deletions(-)
 create mode 100644 src/inject/fallback.ts
```

`fallback.js` had caught my eye as a notable change in 4.9.17 so I decided to poke at it first via `src\inject\fallback.ts`. If I comment out `document.documentElement.appendChild(fallbackStyle);` at this point, things work fine.

Then I reset things, ended the bisection, switched to master, and commented out the same one line. Reinstalled, rebuilt, refreshed... and it works fine.

For whatever reason RoundCube really doesn't like that `fallbackStyle` being added.

**Comment by alexanderby** [comment]
Hi @MartyMacGyver, we were not able to install this server. Could you please open Console and see if there's a JavaScript error?

**Comment by MartyMacGyver** [comment]
> Hi @MartyMacGyver, we were not able to install this server. Could you please open Console and see if there's a JavaScript error?

I already explained there was no error associated with this bug, otherwise it might be easier. But I did bisect down to the change that led to this issue (above) so hopefully it will help lead to a solution.

**Comment by Gusted** [comment]
Hi @MartyMacGyver!

I think I've come up(after a good suggestion from @alexanderby) with a new approch to inject the style.
[debug.zip](https://github.com/darkreader/darkreader/files/5266263/debug.zip)
If you could try this copy on Roundcube and the drafting works again, I can confirm this is a good fix.

Regards,
Gusted

**Comment by MartyMacGyver** [comment]
Looks like you made a lot of changes to the fallback mechanism. I've loaded and unloaded this a couple of times (and also unloaded the one I built) - so far things are working fine with your `debug.zip`!

**Comment by Gusted** [comment]
> Looks like you made a lot of changes to the fallback mechanism. I've loaded and unloaded this a couple of times (and also unloaded the one I built) - so far things are working fine with your `debug.zip`!

Great :) I've opened up a PR(#3691) with the fixes.

**Comment by alexanderby** [comment]
Hi @MartyMacGyver, sorry for interrupting you. Could you please check if this build works?
[darkreader-fallback-fix.zip](https://github.com/darkreader/darkreader/files/5276786/darkreader-fallback-fix.zip)

**Comment by MartyMacGyver** [comment]
@alexanderby Seems to work fine, fixing the problem like what @Gusted posted previously.
