### ISSUE TITLE
[question]access to theme or style sheet

### ISSUE THREAD

**Issue by Fuseteam** [darkreader/darkreader#3658]
i really like the dark theme darkreader gives to whatsapp web for example, is there a way for me get the stylesheet of what is applied somehow? i would like to use it in my personal whatsapp web webapp

**Comment by Gusted** [comment]
Hi @Fuseteam!

As of a simple copy paste from the [blog](https://darkreader.org/blog/v4-9-16/)

Users, who activated Dark Reader v5 Preview, can try some new features. It's easy to activate if you haven't already:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.


# Export generated CSS

One of the popular requests was adding the ability to export CSS. Go to ⚙Settings -> Manage settings -> Export dynamic theme. You can now use the generated CSS for your website or for other purposes.

Let me know if you can't follow the steps.

Regards,
Gusted

**Comment by Fuseteam** [comment]
thanks for the swift answer i am unable to find the "settings" you refer to, where should i look?

**Comment by Gusted** [comment]
> 
> 
> thanks for the swift answer i am unable to find the "settings" you refer to, where should i look?

In the Pop-up.
![image](https://user-images.githubusercontent.com/25481501/93529880-f6ab5900-f93c-11ea-8cb1-a860ee31ecb2.png)

**Comment by Fuseteam** [comment]
i don't see that in the popup
actually the pop up looks different for me
i'm using the extension for firefox fwiw

**Comment by Gusted** [comment]
> i don't see that in the popup
> actually the pop up looks different for me
> i'm using the extension for firefox fwiw

Did you try:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.

**Comment by Fuseteam** [comment]
ohw "new design" refers to the pop up o.O i did not understand that my bad
