### ISSUE TITLE
[BUG] Not working when Firefox Redeader View is enabled

### ISSUE THREAD

**Issue by gkorland** [darkreader/darkreader#3659]
### **Describe the bug**

When clicking on `Toggle Reader View (Ctrl+Alt+R)` the Dark Reader has no impact

### **Steps to reproduce**
- Click on `Toggle Reader View (Ctrl+Alt+R)` 
- Click on `Dark Reader`
- Nothing happens

And vice versa 

- Click on `Dark Reader`
- Click on `Toggle Reader View (Ctrl+Alt+R)` 
--> the dark mode is disabled

### **Expected behavior**

Dark mode + Reader view should work together 

### **Actual behavior**

Reader view is working without Dark view

### **Screenshots**

![image](https://user-images.githubusercontent.com/753206/93439658-7f8fa980-f8d7-11ea-9b97-8e44e410149f.png)

### **System Information:**
 - OS: Ubuntu 20.0.4.1
 - Browser: Firefox 80.0.1 (64-bit)
 - Dark Reader version:     4.9.19

**Comment by Gusted** [comment]
Hi @gkorland!

This isn't actually a bug, but rather intended usage.
As the reader mode is actually on a `about:` page and for Firefox add-ons are by disallowed to modify it.
Also as it's a browser generated site their isn't any workaround for this behavior.
![](https://i.imgur.com/718AV6V.png)
![](https://i.imgur.com/HsGZ49O.png)

Regards,
Gusted
