### ISSUE TITLE
[Feature Request] Don't invert the color pallet selector

### ISSUE THREAD

**Issue by gitSaptarshi** [darkreader/darkreader#3660]
# Color pallet selector must not be inverted.

I use figma.com a lot in chrome. And every time I enable dark reader the color pallet selector live also gets inverted. I know that it is the job of this extension. **But it also invert all the colors, like white becomes black and same with the rest of the colors.** And it is very annoying for those who works with colors, it makes them feel annoying. To see the correct color we selected we need to toggle the extension off, which we don't want to. I mean who wants to go back to the light version when have a better dark mode. But there is no other way for us.

A screenshot is given below. **The color E5E5E5 is a very light-grey, but in the feed it is showing as a dark grey.**

### Screenshot
![color pallete selector](https://user-images.githubusercontent.com/37685073/93484504-9b1ea280-f91f-11ea-9ef5-9e226e9779d1.png)

**Comment by Gusted** [comment]
Hi @gitSaptarshi!

For this kind of edge-cases whereby the colors are used for color pickers. We have implemented a `IGNORE INLINE STYLE` option in the fix config to ignore styling it and display the original color, I will make a fix for this site to have this problem resolved.

Regards,
Gusted

**Comment by fakhamatia** [comment]
How about for Amazon and other shopping sites?

![Screenshot_20240312_135837-1](https://github.com/darkreader/darkreader/assets/20030910/ed1cb052-f7a5-4235-a72e-632d975d147c)
![Screenshot_20240312_135918-1](https://github.com/darkreader/darkreader/assets/20030910/7f61ea54-fcaa-4973-b4b2-ef7c8f43f210)


@Gusted

**Comment by alexanderby** [comment]
@fakhamatia Thanks for noticing, the fix will be published soon.

**Comment by fakhamatia** [comment]
> @fakhamatia Thanks for noticing, the fix will be published soon.

Only for Amazon or all shop sites?
We have [Digikala ](https://www.digikala.com/product/dkp-4011476/%D9%85%D8%AD%D8%A7%D9%81%D8%B8-%DA%A9%D8%A7%D8%A8%D9%84-%D9%88-%D9%87%D9%86%D8%AF%D8%B2%D9%81%D8%B1%DB%8C-%D9%85%D8%AF%D9%84-shine/) and this color chooser problem.

![image](https://github.com/darkreader/darkreader/assets/20030910/621f5846-0b5f-4b33-983d-7e7061e23cb2)
