### ISSUE TITLE
[Broken Website] GitHub network insights graph hover avatar inverted

### ISSUE THREAD

**Issue by TheChilliPL** [darkreader/darkreader#3670]
**Website**
https://github.com/darkreader/darkreader/network

**How to Reproduce**
1. Go to any repository's network insights graph (the link above) and hover over any of the commits there

**Expected behavior**
The avatar should be displayed normally.

**Actual behavior**
The avatar's brightness is inverted.

**Screenshots**
![image](https://user-images.githubusercontent.com/18823939/93670077-b660ed80-fa98-11ea-975c-203370967782.png)

**System info:**
 - OS: Windows 10 Version 2004 Build 19041.508
 - Browser: Chrome 85.0.4183.102 x64
 - Darkreader Version: 4.9.19
 
**Additional context**
Theme generation mode: Dynamic

**Comment by Gusted** [comment]
Hi @TheChilliPL!

Unfortunately, their is no good fix for this behavior. Other than disabling dark reader or switching to another mode.
As the element in this case the network graph is 1 element that contains all information.

The element is a `canvas` that is meant to being drawn on by javascript and doesn't require complicated logic elements to reproduce this behavior. So we are simply inverting it so it looks good and match the color scheme of dark reader.

Regards,
Gusted

![](https://i.imgur.com/F5NoMgp.png)
