### ISSUE TITLE
[BUG] 0% sepia still adds yellow tint

### ISSUE THREAD

**Issue by chinwobble** [darkreader/darkreader#3672]
### **Describe the bug**

When the Sepia theme value is set to 0%, DarkReader will still skew the colours to yellow.

### **Steps to reproduce**

Create a simple html document
```html
<head>
    <style>
    * {
        color: rgb(50, 50, 50);
    }
    </style>
</head>
<body>
  <h1>list sample</h1>
  <h2>Latest articles</h2>
  <ul class="latest-articles-list" aria-label="latest articles">
    <li>
      <a href="/http-guide-part-1">A guide to http part 2</a>
      <span>Published on December 19, 2020</span>
    </li>
    <li>
      <a href="/http-guide-part-1">A guide to http part 1</a>
      <span>Published on December 18, 2020</span>
    </li>
  </ul>
</body>
```

2. Enable dark reader with the following theme configuration.
![image](https://user-images.githubusercontent.com/18226001/93706533-91d54600-fb6a-11ea-990e-166b552b538a.png)

0% sepia and increase the contrast.

The computed colour for the text is 
```
rgb(207, 203, 195)
```

This skews it to yellowish rather than light grey as expected.

### **Expected behavior**

With dark reader enabled, it shouldn't skew the colours to yellowish if sepia is set to 0%.

### **Actual behavior**

The colour is skewed to yellowish. This should only happen if sepia is enabled.

### **System Information:**
 - OS: Windows 10
 - Browser: Firefox 80.0.1
 - Dark Reader version: 4.9.19

**Comment by Gusted** [comment]
Hi @chinwobble!

This weird...
I've tried to reproduce this with the settings you gave and my computed color came to another color `rgb(207, 203, 195)`, which isn't yellow-ish.
Do you have by any chance another setting modified?

Regards,
Gusted

![](https://i.imgur.com/9HNfDJS.png)

**Comment by sujay1844** [comment]
Even I have a similar issue

**Comment by Gusted** [comment]
> Even I have a similar issue

This adds 0 information for me to understand this issue as explained in the post above you ^.

**Comment by chinwobble** [comment]
For me the issue was because the default text colour had changed from yellow to white. I fixed the issue by changing back to white.

![image](https://user-images.githubusercontent.com/18226001/93948517-07672f00-fd82-11ea-99f9-6609ed37362b.png)

**Comment by Gusted** [comment]
Oh yeah, we have dynamic coloring that should fix the issue by changing it around a bit to hae it match `your perfect white-ish text color`.

> Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.

And than to modify the dynamic coloring.
> Custom background, text and selection colors (under Theme click See all options, Colors).

Regards,
Guste
