### ISSUE TITLE
[BUG] Using Filter+, text inside highlighted GitHub text boxes with a scrollbar, is rendered wrong

### ISSUE THREAD

**Issue by Ririshi** [darkreader/darkreader#3682]
### **Describe the bug**

When using filter+, the text inside GitHub text boxes with a scrollbar, is rendered with wrong colours, but only when the text box is selected / highlighted.

### **Steps to reproduce**

1. Open any GitHub page where you can get a text box with a scrollbar

2. Type some text inside the text box

3. Set your DR to Filter+ mode

4. Click inside and outside the text box to select and deselect it

5. Closely watch the text in the box as its colour and rendering changes slightly

### **Expected behaviour**

Text in the text box to be rendered normally.

### **Actual behaviour**

Text in the text box is rendered with weird colour / rendering artefacts.

### **Screenshots**

This first screenshot shows the wrongly rendered text, which occurs when a GitHub text box is selected while having a scrollbar.
![image](https://user-images.githubusercontent.com/8461226/93828167-10b1a800-fc6b-11ea-8c37-93d7dddea8e4.png)

This second screenshot shows the the normal text, which is visible when the text box has no scrollbar OR when it does but is not selected.
![image](https://user-images.githubusercontent.com/8461226/93828187-1909e300-fc6b-11ea-85ff-e4d935d3e86a.png)

Please look at the screenshots with DR turned off (or at least not with filter+ on) to clearly see the difference. Opening them in a separate tab and zooming in also makes the difference much more noticeable.

### **System Information:**
 - OS: Windows 10
 - Browser: Google Chrome Version 85.0.4183.102 (Official build) (64-bits)
 - Dark Reader version: 4.9.19

### **Additional context**

I am not sure if this only happens in GitHub, or whether other text box with a scroll bar and a select / highlight modifier have this issue as well. Would be nice to see if others can replicate this on other websites with similar scrollable text boxes.

**Comment by Gusted** [comment]
Hi @Ririshi!

Unfortunately this behaviour is caused by sub-pixel rendering. You could try to have a look at `Filter` mode or disabling Sub-pixel rendering somewhere in the windows settings(I thought In the control panel -> Fonts the best chance).

Regards,
Gusted

**Comment by Ririshi** [comment]
This subpixel rendering only happens when the text box is selected though? Isn't there a chance that something in this extension is causing the way the text is rendered to be changed when a scrollbar is visible inside a selected text box?

I understand that you'd like to close issues as soon as you know you cannot / won't fix them, but I think this issue deserves a little bit of extra love before closing it 😇

**Comment by Gusted** [comment]
> This subpixel rendering only happens when the text box is selected though? Isn't there a chance that something in this extension is causing the way the text is rendered to be changed when a scrollbar is visible inside a selected text box?

Nope, we are just giving some parameters to the browser to get it inverted and all the rendering is on their side.
The sub-pixel rendering is probably even caused by Window's font.




> I understand that you'd like to close issues as soon as you know you cannot / won't fix them, but I think this issue deserves a little bit of extra love before closing it 😇

I'm here to support dark reader and not external things that we don't have control over.
Also, I'm only closing issues when either I've posted a solution(whereby I know it should resolve the issue if the reporter can follow the steps) or either a explanation about the bug and can't/isn't our problem. In this case isn't our problem and I tried to give you a direction into the Windows settings so you still have a lead what to do with this.

Regards,
Gusted

**Comment by Ririshi** [comment]
You didn't mention in your first comment that you were already certain that this issue is caused by the way Windows renders the font, rather than how the extension tells the browser / Windows to render it. That said, I didn't mean to bash you for not doing your job right or anything like that. Appreciate all the hard work keeping DR up to date and bug-free, and thanks for the extra explanation!
