### ISSUE TITLE
Firefox theme gets changed[BUG]

### ISSUE THREAD

**Issue by sujay1844** [darkreader/darkreader#3683]
### **Description**

 I don't like how the extension changes the theme of the browser. Is there any way to just change the webpage colors without affecting the theme?? I was confused to classify this issue as 'bug' or 'feature request'.

### **Screenshots**

![2020-09-22 (1)](https://user-images.githubusercontent.com/68642484/93885927-70a75d80-fd02-11ea-8537-2e940a2456a9.png)
Or instead you could just make the dark theme in the extension more darker. (as dark as the webpage or even darker)

### **System Information:**
 - OS: Windows_NT 10.0 19041 and Arch Linux
 - Browser: Firefox 80.0.1
 - Dark Reader version:
  4.9.19

**Comment by sujay1844** [comment]
I could change the theme everytime I switch on dark mode but that's not suitable for me.

**Comment by Gusted** [comment]
Hi @sujay1844!

Follow the following steps.
1. Open the UI/Pop-up
2. Go to the `More` tab.
3. Switch to `Default` option ![](https://i.imgur.com/wHuGstz.png)
4. Re-Enable your own theme.

Regards,
Gusted

**Comment by sujay1844** [comment]
Thank you
