### ISSUE TITLE
MS Edge version

### ISSUE THREAD

**Issue by alexanderby** [darkreader/darkreader#37]

**Comment by boarder2** [comment]
I had better than expected results using https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/porting-chrome-extensions/ and side loading.

Lots of things are broken, like the popup menu and some sites like GitHub don't work.

I might be willing to put some effort forth in making this happen but my extension development experience is limited.  Any thoughts on where to start looking first?  

Having this extension in Edge would be a life saver.

**Comment by alexanderby** [comment]
@boarder2 Thanks for direct links. I will have a look.

**Comment by alexanderby** [comment]
I tried to port it, seems like font API and command API don't work, though some bridge is documented. Still in common the extension works, so I will publish it soon.

**Comment by boarder2** [comment]
Yeah, even with limited functionality I've been using it for the last week and it's been very helpful. I'll keep an eye out for commits on this issue! Thanks for checking it out!

**Comment by alexanderby** [comment]
The extension was adopted for MS Edge (though build process is made by some external program). Unfortunately somebody has taken a Dark Reader name, so I cannot publish it to store.

**Comment by alexanderby** [comment]
I've requested an extension name back, but the process of publishing is too much cumbersome. Until it is improved try to download and install the extension manually http://darkreader.org/downloads/darkreader-3.5.3-edge.zip

**Comment by boarder2** [comment]
At first glance this seems pretty solid! I hope the publishing process gets easier. Would love to see this available without side loading.

**Comment by sakeofepte** [comment]
Great fan of the Extension, not so much of Google Chrome.
I found that the name "darkreader" is not yet in use. Can you maybe publish under that name?
I snagged it up so no-one can use it atm, let me know if you want to publish and I will delete it from my list so you can use it.

**Comment by SciFreakholic** [comment]
Hi, @alexanderby. Is it possible to fully refactor to use Edge callbacks instead porting the extension with the Microsoft tool? BTW, is still in active development?

Regards.

**Comment by SciFreakholic** [comment]
> I've requested an extension name back, but the process of publishing is too much cumbersome. Until it is improved try to download and install the extension manually http://darkreader.org/downloads/darkreader-3.5.3-edge.zip

Not sure if the required APIs are fully supported in recent versions of Microsoft Edge, and I also cannot found any app nor extension in [Microsoft Store](https://www.microsoft.com/es-mx/search/result.aspx?q=dark+reader) that uses "Dark Reader" name. Night Eye has launched a version for Edge and I think the first one would have been Dark Reader. :(

I hope you are able to publish the extension soon. Good luck!

**Comment by khuongduybui** [comment]
Where can we download the latest version for edge in the meantime? The link above 404'd.

**Comment by alexanderby** [comment]
I asked to free up the "Dark Reader" name some time ago, so it now belongs to me. I will publish start working on Edge version as soon as Safari version will be released.

[Here](https://github.com/darkreader/darkreader/releases) are download links for old Dark Reader versions.

**Comment by khuongduybui** [comment]
Now that the Safari version is out, can we get an ECD for Edge version?
If I can be of help in anyway please do say.

**Comment by SciFreakholic** [comment]
>           Now that the Safari version is out, can we get an ECD for Edge version?
> If I can be of help in anyway please do say.

Me too.

**Comment by khuongduybui** [comment]
Thanks for being realistic with your roadmap. I will stop waiting.

**Comment by alexanderby** [comment]
> If you wait by the river long enough, the bodies of your enemies will float by.
― Sun Tzu

You can now use **Dark Reader** for Edge.
- [Download](https://www.microsoftedgeinsider.com/en-us/download/) some official Edge Chromium-based build.
- Open `edge://extensions` page.
- Click **Allow extensions from other stores**.
- Install [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) extension from the **Chrome Web Store**.

To make Edge browser frame dark:
- Open `edge://flags` page.
- Search for `edge-follow-os-theme` and **Enable** it.

**Comment by spinedoc777** [comment]
> > If you wait by the river long enough, the bodies of your enemies will float by.
> > ― Sun Tzu
> 
> You can now use **Dark Reader** for Edge.
> 
> * [Download](https://www.microsoftedgeinsider.com/en-us/download/) some official Edge Chromium-based build.
> * Open `edge://extensions` page.
> * Click **Allow extensions from other stores**.
> * Install [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) extension from the **Chrome Web Store**.
> 
> To make Edge browser frame dark:
> 
> * Open `edge://flags` page.
> * Search for `edge-follow-os-theme` and **Enable** it.

Been waiting for this forever!  Dark Reader works great on chromium Edge, been using it for a few weeks now.  Only issue is that Dark Reader makes Edge's scroll bar really narrow and dark, almost invisible and very difficult to use.  Hope that gets fixed soon.

**Comment by alexanderby** [comment]
Finally Dark Reader has been released for Edge (Chromium) https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc

Please, if you already have Dark Reader installed from Chrome Web Store, disable it before installing from Microsoft Store.
