### ISSUE TITLE
Not working in background tabs

### ISSUE THREAD

**Issue by Symbai** [darkreader/darkreader#370]
I've noticed the addon does not work when opening tabs in backgrounds. I have to reload the tab while its active to get the dark mode applied.

Dark Reader: 4.2.1
FF 59.0.2

**Comment by alexanderby** [comment]
Previously a new script was generated and injected for each page opening or setting change. Now there is a static script which communicates with the extension via messaging API. Seems it's buggy in Firefox, I will think about how to patch it.

**Comment by alexanderby** [comment]
I've just checked, it works well in Firefox 59 and 60. Maybe there is a problem on specific URL.

**Comment by joshsleeper** [comment]
@alexanderby Gimme a sec, I'll give you a list of sites I _tend_ to see it happen on...

**Comment by alexanderby** [comment]
Are you using "Filter" mode?

**Comment by joshsleeper** [comment]
I am indeed using `Filter` mode.

![image](https://user-images.githubusercontent.com/849941/38999047-c6a2280a-43a5-11e8-8da6-929fe69c8765.png)

**Comment by alexanderby** [comment]
Should be fixed

**Comment by joshsleeper** [comment]
I ran a few tests and it seems to be completely resolved for me after that change.
Thanks so much @alexanderby!

**Comment by alexanderby** [comment]
@Cochonours Please open new issue and steps to reproduce.
