### ISSUE TITLE
Text overlap [BUG]

### ISSUE THREAD

**Issue by JoykishanSharma** [darkreader/darkreader#3705]
### **Describe the bug**

Hi :wave:, I got this bug at [Online Dart Editor website](https://dartpad.dartlang.org/) which overlaps text on top of each other (when font styles are enabled), It's kinda confusing :confused:, but if you follow these steps you will understand what i'm talking about :smile: . 

### **Steps to reproduce**

- Go to 'https://dartpad.dartlang.org/'
- Enable "Dark Reader" (also check if default font style is enabled or not in the "Dark Reader")
- The "Navigation bar" texts and button text, gets an overlapping text on top of them. 

### **Expected behavior**

Although the website already has it's dark mode, but if I visit it with "Dark Reader" enabled, this bug occurs. I temporarily fixed this issue by disabling font style from "Dark Reader" UI.

### **Actual behavior**

Text overlap with other text in Navigation bar and button text.

### **Screenshots**

![Bug](https://user-images.githubusercontent.com/47889468/94228652-0f0e0b80-ff1b-11ea-8b7c-c4509076c05d.png)

### **System Information:**
 - OS: Windows 10 Pro
 - Browser:  Google Chrome 85
 - Dark Reader version: 4.9.19

**Comment by Gusted** [comment]
Hi @JoykishanSharma!

As you state your using Segou UI Font, which is completely being handled by Chromium and we have 0 control over. It seems like Dartpad has a fixed font-size. I think It's the best to disable this font on this website as it doesn't work.

Regards,
Gusted

**Comment by JoykishanSharma** [comment]
Thanks for replying :smile: I'll disable the font style on this website for now. :+1:
