### ISSUE TITLE
[BUG] Darkreader is applying dark mode on all websites even when disabled ones on firefox

### ISSUE THREAD

**Issue by masterx1** [darkreader/darkreader#3709]
After my firefox updated to 81.0, darkreader is applying dark mode on every website which looks weird and clunky, even those that I have the extension disabled on 
![image](https://user-images.githubusercontent.com/5236358/94274095-2b22a480-ff3d-11ea-9950-d5952d85bdae.png)

### **Steps to reproduce**

- Update firefox to 81.0
- Open Website that have darkreader disabled on
- Get website with dark mode on for no reason 

### **System Information:**
 - OS: Windows 10 
 - Browser: Firefox 81.0
 - Dark Reader version: 4.9.20

**Comment by Gusted** [comment]
Hi @masterx1!

If you open the console(ctrl + shift + i > Console tab) does it show any errors? Also do you know if you have any custom settings despite the default ones?

Regards,
Gusted

**Comment by masterx1** [comment]
![image](https://user-images.githubusercontent.com/5236358/94275391-cff1b180-ff3e-11ea-8225-8b6afdd12b08.png)

these are the errors I see in console, from what i can see, nothing related the darkreader, maybe
And no, i don't have any custom settings, besides the filtering

**Comment by Gusted** [comment]
Hmm, could you try to close the browser and restart it. Also re-installing dark reader could help

**Comment by RootOperator** [comment]
![image](https://user-images.githubusercontent.com/20143055/94279724-cec78100-ff4c-11ea-90ec-3f6cec1b433a.png)

I'm having the same issue. 
I'm also on firefox version 81.0

the right console is the Dark reader console
dark reader is turned off in the screenshot

restarting and reinstalling did not help for me

**Comment by Gusted** [comment]
Aha, I see. The fallback-style is not being removed

**Comment by masterx1** [comment]
Update: Nothing worked as suggested but I think u figured out the bug. But now, I'm facing another bug (or is it the same ?). Even when the extension is disabled, it's still puts every site on dark mode 
![image](https://user-images.githubusercontent.com/5236358/94312783-7789d680-ff75-11ea-9f8b-a16403d9b4e7.png)

**Comment by masterx1** [comment]
![image](https://user-images.githubusercontent.com/5236358/94312835-8f615a80-ff75-11ea-85b5-3028c6852438.png)

**Comment by Gusted** [comment]
Hi @masterx1!

Could you try side-loading

[build-firefox.zip](https://github.com/darkreader/darkreader/files/5285309/build-firefox.zip)

It should contain a possible fix for this bug 😬 

Firefox
- Open the hamburger menu in the right upper corner. ![](https://i.imgur.com/ALb9GMU.png)
- Click on Addons. ![](https://i.imgur.com/565La4k.png)
- Click on the setting icon. ![](https://i.imgur.com/dA0XZ3G.png)
- Click on `Debug Add-ons`. ![](https://i.imgur.com/6AmFnyY.png) **WARNING SOMEHOW THIS IS A WHITE-ISH SITE**
- Click on `Load Temporary Add-On`. ![](https://i.imgur.com/J7PCwsw.png)
- Now go to the unpacked folder and select `manifest.json`. ![](https://i.imgur.com/WrloLPR.png)
- Click on `Open`.
- Poof and side-loaded the extension congratulations.

Regards,
Gusted

**Comment by masterx1** [comment]
Just did, but this fix is just temporary. I have to side-load each time i restart firefox. 

I'm just happy that I no longer have youtube with double dark mode, or weird unusable github. I'm just gonna wait for a fix for the first bug, and might use my glasses all the time because having each website on light mode makes me cry.

**Comment by Gusted** [comment]
Hi!

I've opened up a PR(#3715) which might fix this.
If someone could be so nice and try to side-load the fix by:

[build-firefox.zip](https://github.com/darkreader/darkreader/files/5286111/build-firefox.zip)

- Unpack build-firefox.zip into a folder and remember where this folder is located.

- Open the hamburger menu in the right upper corner. ![](https://i.imgur.com/ALb9GMU.png)
- Click on Addons. ![](https://i.imgur.com/565La4k.png)
- Click on the setting icon. ![](https://i.imgur.com/dA0XZ3G.png)
- Click on `Debug Add-ons`. ![](https://i.imgur.com/6AmFnyY.png) **WARNING SOMEHOW THIS IS A WHITE-ISH SITE**
- Click on `Load Temporary Add-On`. ![](https://i.imgur.com/J7PCwsw.png)
- Now go to the unpacked folder and select `manifest.json`. ![](https://i.imgur.com/WrloLPR.png)
- Click on `Open`.
- Poof and side-loaded the extension congratulations.

Regards,
Gusted

**Comment by random-scrub** [comment]
Just side-loaded, seems to fix the issue from the few websites I tried it with.

**Comment by alexanderby** [comment]
So, the fix was pushed in version 4.9.21. Not sure if it will be reviewed on weekends.

As a workaround try disabling system dark mode.

**Comment by alexanderby** [comment]
Update: the fix is in the store!

**Comment by thegamerx1** [comment]
still happening for me in firefox

**Comment by masterx1** [comment]
@thegamerx1 did u force update from Addons tab settings ? Because I just updated 3 hours ago to 4.9.21 and didn't encounter the bug since then

**Comment by thegamerx1** [comment]
weird i didnt see any update button but after removing and reinstalling it works

**Comment by thompol** [comment]
Had the same problem. You can update manually by going to about:addons, click the gear icon, and then "Check for updates". Seems to be fixed in 4.9.21.

Thanks!

**Comment by MattSuda** [comment]
I am having a similar issue using version 4.9.21 in Google Chrome on Mac. For the past week every site that Dark Reader is DISABLED for, on page load the background will be black before the content loads. On every page load, it flashes a black background before loading the site content that shows as normal. Very annoying when browsing and I can't determine what the problem is other than there might have been a change causing this. Checked all my settings and they are correct.

**Comment by Gusted** [comment]
> I am having a similar issue using version 4.9.21 in Google Chrome on Mac. For the past week every site that Dark Reader is DISABLED for, on page load the background will be black before the content loads. 

Uhm yes, that's preventing a white flash. Or am I misunderstanding you?

> Very annoying when browsing because it messes up the way things look on a website while it's loading and I can't determine what the problem is other than there might have been a change causing this. Checked all my settings and they are correct.

Define `messing` and `things`. This is a vague description for me.

**Comment by chalda** [comment]
this is happening again
