### ISSUE TITLE
Change [X]/[V] font button to [ ]/[V]

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#371]
I think it should be like [OFF] and [ON] instead of [X] and [V], because user can perceive [X] as "Reset" selected font.

Also you can change desc below to "Select a custom font" to make it more clear for user.

**Comment by alexanderby** [comment]
As my colleague said: Programming is like a poem: if you move a word it loses sense. In this case design is like a poem :) Maybe removing X and leaving empty square should be enough. I liked that animation but cross is really confusing.

**Comment by risualiser** [comment]
Seriously, I didn't understand, why custom font doesn't work until I try to press the button.
Maybe, you add feature, that when user select some font, it automatically turns on?

**Comment by 4goodapp** [comment]
I Agree with this, and the [V] is very similar to the select arrow:

![image](https://user-images.githubusercontent.com/6249230/45758620-8a929f00-bc15-11e8-91ae-11caffcb2e1c.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/oAwTFjp.png) New UI
1. Enabled
2. Disabled
