### ISSUE TITLE
[BUG] Occasionally getting stuck at fallback style

### ISSUE THREAD

**Issue by erkinalp** [darkreader/darkreader#3716]
### **Describe the bug**

Dark Reader sometimes fails to apply the theme after the fallback style.

### **Expected behavior**

Fallback style only appearing briefly, then would transition into actual page style

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 81 beta
 - Dark Reader version: 4.9.20

**Comment by Gusted** [comment]
Install 4.9.21. It has been fixed by #3715
