### ISSUE TITLE
[BUG] When I open twitter.com in a new tab, the page is broken.

### ISSUE THREAD

**Issue by cyatarow** [darkreader/darkreader#3719]
### **Steps to reproduce**
(I am a Japanese user.)
1. Go to [twitter.com](twitter.com)
2. Right-click on any username link
![20200926a](https://user-images.githubusercontent.com/26016252/94338995-a6fe1900-0031-11eb-841d-5aaa89a2000f.png)
3. Click on [Open in a New Tab]
4. The page in the new tab is broken even if twitter.com is blacklisted.
![20200926b](https://user-images.githubusercontent.com/26016252/94339130-871b2500-0032-11eb-8f85-6963c650e189.png)

### **System Information:**
 - OS: Windows 10 2004 Pro
 - Browser: Firefox 81.0
 - Dark Reader version: 4.9.20

**Comment by Gusted** [comment]
Hi @cyatarow!

Please download the newest version of darkreader thst fixed this bug 4.9.21

Regards,
Gusted
