### ISSUE TITLE
Compatibility with Chrome below 60

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#372]
My chrome has version **57**, and it doesn't support all es6 features like spread operator, so chrome extention doesn't work, it's just stacking in "loading" state all time. 

I went to background page, and found the following error:
![2018-04-17 02-52-17](https://user-images.githubusercontent.com/11363215/38841028-fed2395c-41ea-11e8-84f3-904ba95e4c13.png)
![2018-04-17 02-57-16](https://user-images.githubusercontent.com/11363215/38841035-0dfb61ec-41eb-11e8-80c3-c18cb4be3736.png)

**Comment by BANOnotIT** [comment]
Upgrading worked for me, thanks. But it might be difficult to another person...

**Comment by BANOnotIT** [comment]
> Can you suggest how to safely install older Chrome version?
I thought docker can be used, but I've found no official images of chrome, and all other versions are ~50.

**Comment by alexanderby** [comment]
That's one of the reasons, I don't want to download it from untrusted sources. I think I should display some warning prompting to update Chrome.

**Comment by Gusted** [comment]
Hey their!

I just looked again with Chromium v59 and Their are no/little problems with it as it just now does it jobs and the error you reported is gone.

as For


> That's one of the reasons, I don't want to download it from untrusted sources. I think I should display some warning prompting to update Chrome.
@alexanderby 
https://www.chromium.org/getting-involved/download-chromium
