### ISSUE TITLE
[BUG] All webs changed

### ISSUE THREAD

**Issue by LordSprit** [darkreader/darkreader#3720]
Hi

After the last update, I have an issue that changes all webs to dark mode but I have activated "invert listed only". I don't know what is the problem but I have configured the dark reader more grayish and this global changes puts all web in a blackish mode  more darker than my config. If I swap the inverted listed only to the other option it seems like is corrected but in a couple seconds if I open new tab with a new or opened web it changes back to black.

**Screenshots**

![Portapapeles01](https://user-images.githubusercontent.com/8897404/94343323-9771d680-0017-11eb-86aa-e5a8c411b8ed.png)
default changes to all webs
![Portapapeles02](https://user-images.githubusercontent.com/8897404/94343325-9a6cc700-0017-11eb-95c7-b4cbefea2eb3.png)
my configured changes

**System Information:**
 - OS: Win 10 64bit
 - Browser: Firefox 81.0
 - Dark Reader version: 4.9.20

**Comment by gabefoster** [comment]
I am also having this issue, same configuration as LordSprit. Toggling a website on and off seems to correct the issue, so I suspect this may have to do with how DarkReader recognizes whether it is enabled for a website.

**Comment by clasick** [comment]
@LordSprit toggling it fixes until the website is visited again, at which point the bug reoccurs.

**Comment by mwessman** [comment]
Yup. Same thing here. Really annoying since it breaks a few streaming sites like Twitch and Netflix.

**Comment by Gusted** [comment]
#3709
