### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mystiquewolf** [darkreader/darkreader#3721]
### **Describe the bug**
Since about 25 September some websites like Google, Github and Quora apply dark mode, even when dark mode is disabled globally in the extension, extension itself is enabled and system dark mode is also enabled. I believe it may have something to do with 4.9.21.

### **Steps to reproduce**
Browse to Google/Github/Quora

### **Expected behavior**

Websites are in light mode

### **Actual behavior**

Websites are in dark mode

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox Nightly 83.0a1 build 20200926092504
 - Dark Reader version: 4.9.21

### **Additional context**
Nope

**Comment by Gusted** [comment]
Hi @mystiquewolf!

Could you try to re-install the addon and than restart Firefox to make sure it's getting forced 4.9.21

Regards,
Gusted

**Comment by jstaro** [comment]
Same thing started happening to me today on Firefox 81, most notably Youtube.

**Comment by Gusted** [comment]
> Same thing started happening to me today on Firefox 81, most notably Youtube.

Hi @jstaro!

Did you make sure your on 4.9.21?

**Comment by jstaro** [comment]
Oh right, I wasn't on the latest version.
Had to manually trigger an update.
4.9.21 solves the problem for me!
