### ISSUE TITLE
[Broken Website] calibre-ebook.com

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3723]
**Website**
https://calibre-ebook.com/

**How to Reproduce**

> 1. Go to the  site
> 2. Hover mouse over top menu

**Expected behavior**
Dark background

**Actual behavior**
Light background

**System info:**
 - OS: Windows,
 - Browser: Chrome
 - Darkreader Version: 4.9.21

**Comment by Yash-Singh1** [comment]
Looks like the behaviour could be fixed with some configuration:
![Screenshot from 2020-09-26 12-16-21](https://user-images.githubusercontent.com/53054099/94348576-426f9980-fff2-11ea-9726-159ada7a2363.png)

**Comment by Yash-Singh1** [comment]
#3726
