### ISSUE TITLE
[Broken Website] residentevil.net

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3724]
**Website**
https://www.residentevil.net/en/

**How to Reproduce**

> 1. Go to the site
> 2. Open the age drop-down menu

**Expected behavior**
Dark background

**Actual behavior**
Light background

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.21

**Comment by Yash-Singh1** [comment]
Also, some of the flags are reversing:
![Screenshot from 2020-09-26 13-11-41](https://user-images.githubusercontent.com/53054099/94349519-dbee7980-fff9-11ea-8e26-8d63ee096037.png)
This includes mainly the Japanese Flag. This could be fixed with some configuration.

**Comment by Yash-Singh1** [comment]
#3727
