### ISSUE TITLE
[Broken Website] amazon.cn

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3725]
**Website**
https://www.amazon.cn/

**How to Reproduce**

> 1. Go to the site

**Expected behavior**
Top menu background dark

**Actual behavior**
Top menu background light

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.21

**Comment by Yash-Singh1** [comment]
Looks like this is the issue, right?:
![Screenshot from 2020-09-26 13-08-59](https://user-images.githubusercontent.com/53054099/94349468-7d290000-fff9-11ea-878d-6452ea7987ff.png)
