### ISSUE TITLE
URL match patterns

### ISSUE THREAD

**Issue by alexanderby** [darkreader/darkreader#373]
Implement user-friendly URL glob patterns with negation ability and some special behavior. Similar to [globby](https://www.npmjs.com/package/globby), [extension match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns) etc.

### How it should work:
- `*` matches everything
- `*/*.pdf` matches PDF file extension
- `google.com` matches www.google.com, mail.google.com, google.com/search etc.
- `google.*` matches google.com, google.by etc.
- `*.google.com` matches mail.google.com, inbox.google.com etc.
- `google.com/mail/*` matches google.com/mail/inbox etc.
- `google.com/*.pdf` matches google.com PDF files.
- `localhost:*`should match localhost and any port
- `ftp://*` should match FTP protocol only
- `/^.google\.com\/mail/` should behave as a regular expression` *(but should not be implemented yet, maybe there is no need for it)*.

`*` can only be surrounded by dots and first `/` in host part and by last `/` and file extension dot at path part. `*` corresponds to one host or one path part or to many parts if placed at start or end. Queries should not be allowed.
- `*.google.com` OK
- `goo*.com` error
- `google.com/blog/*` OK
- `google.com/blog*` error
- `google.com/*/blog` OK 
- `google.com/*.pdf` OK
- `google.com/2018-07-*.jpg` error
- `google.com/search?q=cat&p=dog` error, we won't investigate if it should match search?p=dog&p=cat, use regular expressions for that

### URL lists
URL lists are used in user's Site List config and fixes configurations (each record can have multiple URLs). `!` should reverse pattern result.
- `google.com, !*.google.com` should match google.com except it's subdomains.
- `google.com, !mail.google.com` should match everything that matches `google.com` except everything that matches `mail.google.com`
- `google.com, !mail.google.com, mail.google.com/compose` should not match everything that matches `mail.google.com` except everything that matches `mail.google.com/compose`

### Pattern specificity
Pattern specificity is used to determine which exact match from config file to use. It should behave similar to CSS specificity.
- `*` 0.1.0.0
- `google.*` 1.1.0.0
- `google.com` 2.0.0.0
- `*.google.com` 2.1.0.0
- `mail.google.com` 3.0.0.0
- `mail.google.com/*` 3.0.0.1
- `mail.google.com/mail` 3.0.1.0
- `mail.google.com/mail/*` 3.0.1.1
- `mail.google.com/mail/compose` 3.0.2.0

Result is an array of
1. Host parts exact matches (plus protocol and port).
2. Host `*` matches (plus `*` protocol and port matches).
3. Path parts exact matches (plus file extension).
4. Path `*` matches (plus `*` file extension).

### URL list sorting
It is needed to validate alphabetical order in configuration files so that they stay maintainable. Configuration records are compared by first URL. Prefix '*.' should be skipped, resulting repeated records should be sorted by specificity. Regular expressions should not be used in comparison.
```
bing.com
google.*
google.com
*.google.com
google.com/*
google.com/mail
google.com/search
wikipedia.org
```

### UI behavior
- Clicking "Toggle" button should add negation pattern if URL matches some other pattern in list.
- There should be ability for user to pick multiple possible patterns for toggle, e.g. `google.com`, `google.com/maps`.

**Comment by Aqa-Ib** [comment]
With this implementation I think that Dark Reader could inherit the capabilities of programs such as Stylus, in the way that it could inject user own CSS code through "dev tools" for every site (*), adding exceptions, etc.

**Comment by freMea** [comment]
Eager to be able to exclude sub-domains 👍

**Comment by Samillion** [comment]
Awesome! Definitely can't wait for this to be implemented, it will make the great experience even greater.

Not sure if this is different, wanted to point out just in case, this also applies to IP URLs.

For example if you invert `https://192.168.1.1` it will affect `192.168.1.12`, `192.168.111` and so on. So it's not an exact match, a wild card one.

**Comment by Gusted** [comment]
Negative Patterns #2327

**Comment by vaindil** [comment]
I was pointed here from #3359. This looks mostly great, but I do see one issue.

> ### How it should work
> 
> * `google.com` matches www.google.com, mail.google.com, google.com/search etc.

I believe that this is fundamentally incorrect with how the internet works. No other part of the internet's infrastructure that I'm aware of treats `something.google.com` the same as `google.com`. If my site list has an exception for `google.com`, then _only_ `google.com` should be considered as part of the list. Including all subdomains is incorrect behavior, if I want them included then I would use `*.google.com` to match both `google.com` and all of its subdomains (which is the behavior specified on the [extension match patterns page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) linked in the issue).

At the very least, regardless of what syntax is chosen, the default behavior of toggling the current site should toggle _only the current site_. If I'm at `stackoverflow.com` and toggle the current site, either by keyboard shortcut or by clicking that button in the popup, I don't want all subdomains to be included in that--I want `stackoverflow.com` and nothing else to be toggled.

**Comment by Gusted** [comment]
> I believe that this is fundamentally incorrect with how the internet works. No other part of the Internet's infrastructure that I'm aware of treats `something.google.com` the same as `google.com`.

That's correct, no disagreement on that part, but unfortunate there are exemptions with site that likes to just have a bunch of subdomains while the theme/color scheme is being the same.

>  If my site list has an exception for `google.com`, then _only_ `google.com` should be considered as part of the list.

Now we are coming onto opinions, as some people(including myself) if I specify to disable on google.com I also want on `mail.google.com` and `google.com/search`. We could consider a option but I'm unsure how This is going to be calculated in code if a string hasn't any subdomains. As checking the amount of dots could possible come into `.co.uk` or `.co.uk.edu` etc. Even thinking about it, adding `^google.com` should only target sites that starts with the main domain `google.com` so `mail.google.com` shouldn't be targeted. However I now remember I didn't added any logic for `^` and `$` But this can be bypassed to use regex that should be supported trough #2517 .

**Comment by vaindil** [comment]
> Now we are coming onto opinions, as some people(including myself) if I specify to disable on google.com I also want on `mail.google.com` and `google.com/search`.

Then the correct way to do this would be adding a site to your list in the format of `*.google.com`, which would match both `google.com` and all of its subdomains, rather than forcing a strange quirk into the system to save having to type `*.`.

If an option is desired, it should affect adding new entries to the list. The site list should always act the same, so an entry of `google.com` doesn't match any subdomains, but you could have an option to make the "toggle current site" action either add `google.com` or `*.google.com` to the list.

**Comment by Gusted** [comment]
> Then the correct way to do this would be adding a site to your list in the format of `*.google.com`, which would match both `google.com` and all of its subdomains, rather than forcing a strange quirk into the system to save having to type `*.`.

Uhm, no this wouldn't be expected behavior as the user sees just the site and don't expect to have `*.` added in the site list without asking.



> If an option is desired, it should affect adding new entries to the list. The site list should always act the same, so an entry of `google.com` doesn't match any subdomains, but you could have an option to make the "toggle current site" action either add `google.com` or `*.google.com` to the list.

What about a little circle like this
![](https://i.imgur.com/Oljwzif.png)
That as on `google.com` a `^google.com` to the site list.
And on `mail.google.com` a `^mail.google.com` to the sitelist so it ensures to just have the current site
I think that would be a good idea without messing the whole logic of Match patterns and existing Site list. And as for sakes to detect whatever it's a subdomain or not as some sites passes `www.` that isn't a subdomain caused by weird CName records probably.

**Comment by Atralb** [comment]
Hi, I see a lot of people looking forward to this feature, but it's been two and a half years and it is still open without apparent work in progress.

I certainly feel it is very much needed for the extension.

Is the team actually working on this or does it consider this as a secondary problem and will simply accept pull requests for that ?

PS: I hope my message willl not be taken the wrong way, I'm in no way complaining. Just genuinely would like to have information on the progress of this feature since the whole thread has just been design discussion for now.

**Comment by Gusted** [comment]
> Hi, I see a lot of people looking forward to this feature, but it's been two and a half years and it is still open without apparent work in progress.

Their is, #2517 

> Is the team actually working on this or does it consider this as a secondary problem and will simply accept pull requests for that ? Paging @alexanderby .

```
Gusted 24/09/2020
I don't have really something else to do
Other than waiting for issues or for requesting changes
Maybe it's time to get a old branch and work on (looking to you URL-patch) *That's #2517*
Not sure what your ideas are on it

Alexander 24/09/2020
Let me think
```

**Comment by Gusted** [comment]
> I believe that this is fundamentally incorrect with how the internet works. No other part of the internet's infrastructure that I'm aware of treats `something.google.com` the same as `google.com`. If my site list has an exception for `google.com`, then _only_ `google.com` should be considered as part of the list. Including all subdomains is incorrect behavior, if I want them included then I would use `*.google.com` to match both `google.com` and all of its subdomains (which is the behavior specified on the [extension match patterns page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) linked in the issue).

As this opinion is shared with a lot of other user(which is now including me) I've implemented this behavior in the PR https://github.com/darkreader/darkreader/pull/2517#issuecomment-720103367

**Comment by PwrSrg** [comment]
**This is _EXACTLY_ what I need.**

My local torrent server requires that I pass my creds in the URL, and Dark Reader **_refuses_** to recognize the domain.  😤

Example: http://username:password@torrentserver:56988/gui/

**Comment by Fred-Vatin** [comment]
Anyone know if it is currently possible to disable dark reader on `github.com/*` except on `github.com/marketplace/*`.

It would be a great feature to force some pages to dark mode on part of site that already have dark mode except on some parts.

**Comment by joshsleeper** [comment]
@Fred-Vatin I get that today by using "Invert listed only" and adding something like `github.com/marketplace/` to the list.

if you use the "Not invert listed" mode though (AKA opt-out vs opt-in to DR theming pages) I don't think there's currently a reasonable way to only enable it on a subset of a site's pages

**Comment by BearBearCodes** [comment]
> Anyone know if it is currently possible to disable dark reader on `github.com/*` except on `github.com/marketplace/*`.
> 
> It would be a great feature to force some pages to dark mode on part of sites that already have dark mode except on some parts.

@Fred-Vatin You should be able to do this by setting Dark Reader into the "Invert listed only" option and then adding this line into the list:
```text
^github.com/marketplace
```
you may also have to add:
```text
^www.github.com/marketplace
```

This should turn only turn on Dark Reader on `github.com/marketplace*` URLs.

**Comment by mattphi** [comment]
> Anyone know if it is currently possible to disable dark reader on github.com/* except on github.com/marketplace/*.

> @Fred-Vatin You should be able to do this by setting Dark Reader into the "Invert listed only" option and then adding this line into the list:

@Fred-Vatin - Personally, I don't like "Inverted list" because I want the default behaviour for new websites to be dark mode, so my workaround is to add these to the normal (non-inverted) list -

```
github.com/a
...
github.com/l
github.com/n
...
github.com/z
```

It's ugly, but the only way to achieve it until the feature requested in this thread is implented.

**Comment by Fred-Vatin** [comment]
> @Fred-Vatin - Personally, I don't like "Inverted list" because I want the default behaviour for new websites to be dark mode, so my workaround is to add these to the normal (non-inverted) list -

Same. For me it’s not an option.

**Comment by Fiveby21** [comment]
Can we please get an option to use regex strings... parituclarly with negative lookaheads. It would be so much more flexible.

**Comment by maximillianus** [comment]
I just discovered Dark Reader and I love its Dark theme. Very convenient for reading.

This feature will be great to implement as I need to allow only certain section in a website to be darkened. 

This pattern: `https://mainsite/*/subsection1`  does not work on me.

**Comment by chrisjacobs91** [comment]
Likewise, this would be very helpful to apply to google docs, but not google slides

**Comment by ziroau** [comment]
how has this not been implemented yet? Theres quite a few duplicate issues for this

**Comment by martin-braun** [comment]
@ziroau The problem is the [PR](https://github.com/darkreader/darkreader/pull/2517) by @Gusted has been Dusted. Rhyme intended.

Pick it up, and bring it to latest, so that it can be merged without any conflicts. I think there are also challenges about not breaking current rules. 

Everybody wants it to land, but nobody wants to get their hands dirty, a typical GitHub issue in the landscape, it had its opportunity, but you are free to change that.

**Comment by alexanderby** [comment]
Hello! You can now try using Regular Expressions in the Site List. Just start and end the pattern with `/` slash, for example:
```
/^www\.google\..*?\/maps/
```

Please let me know if there are any issues.

**Comment by yurenchen000** [comment]
Seems the URL Pattern Syntax in Site-list is changed recently.
<br>

I used to use `^demo.hedgedoc.org/[^/]+$` for
- Disable pages like https://demo.hedgedoc.org/features  And
- Enable pages like https://demo.hedgedoc.org/s/features  

now it Not working anymore.

<br>

and I have to change it to `^demo.hedgedoc.org/*$`
then it works again.

// but it not normal regex syntax anymore

**Comment by alexanderby** [comment]
Hi @yurenchen000! We were not supporting the RegExps before, they were partially working, because the implementation was based on RegExps. Now you can use simple patterns like in your example (`^demo.hedgedoc.org/*$`) or use RegExps inside of slashes (`/^demo.hedgedoc.org/[^/]+$/`).

**Comment by sharpjs** [comment]
FWIW, in Firefox 120.0.1, the pattern seems to match against the entire URL.  For example:

```
/^https?:\/\/(?:www\.)?phoronix\.com(?!\/forums)/
```

works, but

```
/^(?:www\.)?phoronix\.com(?!\/forums)/
```

does not.

Also, it would be good to mention just for completeness the specific flavour of regular expression supported.  I guessed it was JavaScript since this is a browser extension.

**Comment by alexanderby** [comment]
The URL matching has been simplified since version 4.9.69. There are now 2 ways to match a website:

### Simple patterns
- `example.com` will match `example.com` and `www.example.com`, but not `subdomain.example.com`.
- You can specify a wildcard like `*.example.com` to match all subdomains.
- `example.*` will match `example.com` and `example.*.*` will match `example.co.uk`.
- Use `^example.com` if you don't want to match `www.example.com`.
- `example.com/path$` will match `example.com/path` but not `example.com/path/long`.
- You can use protocols like `http://*` or `file:///*`.

### Regular expressions
- A regular expression should start and end with `/` like `/www\.google\.com\/maps/`.
- They are tested against the whole URL, so be careful to match the protocol too, like `/^https?:\/\/.*`.
- Only patterns supported by [JavaScript regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) can be used.

**Comment by JuttuJ** [comment]
Not working for patterns like `*.pdf`.
Does this belong here or should I create a new issue?
