### ISSUE TITLE
New rounded UI not available

### ISSUE THREAD

**Issue by ddnexus** [darkreader/darkreader#3733]
I just added the extension to a new laptop running the same version of Ubuntu, same browser (Vivaldi latest) same version of Dark Reader (latest) of another laptop. In the new laptop it shows the old squared UI while in the old laptop it shows the new rounded one. 
What happens?

**Comment by Gusted** [comment]
```
Users, who activated Dark Reader v5 Preview, can try some new features. It's easy to activate if you haven't already:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

```

**Comment by ddnexus** [comment]
D'oh. I couldn't find it even if I explored that very page :).
Thank you for the super fast answer, and the super useful extension!!!
