### ISSUE TITLE
[Broken Website] Dr Rath Shop white bar

### ISSUE THREAD

**Issue by xerus2000** [darkreader/darkreader#3735]
**Website**
https://shop.dr-rath.com/de-de/alle-produkte/

**How to Reproduce**
Use Dynamic Dark Mode

**Expected behavior**
Page is dark

**Actual behavior**
Area behind the text is white

**Screenshots**
![image](https://user-images.githubusercontent.com/13354331/94447942-ac32a380-01aa-11eb-9412-06509b1ca383.png)

**Comment by Gusted** [comment]
Will have a look later, but this seems to be a code bug with Dark reader... An interesting one actual.
