### ISSUE TITLE
[Broken Website] ecs.toranoana.jp "Illegal page transition was detected"

### ISSUE THREAD

**Issue by DeathByNukes** [darkreader/darkreader#3736]
**Website**
https://ecs.toranoana.jp/ec/app/common/login/
_The website is in Japanese, which makes it difficult to create an account. I am only bothering to report this because it is such a strange issue. If you are actually interested, I can make an account for you to use._

**How to Reproduce**
> 1. Visit https://ecs.toranoana.jp/ec/app/common/login/
> 2. Set the Dark Reader mode to "Dynamic" if it wasn't already.
> 3. Enter valid login credentials and submit the form.

**Expected behavior**
Logged in and redirected to main page.

**Actual behavior**
Not logged in and redirected to https://ecs.toranoana.jp/ec/app/error/invalid_access/

**Error Message**
Machine translation of the error message:
>Page transition error
>Illegal page transition was detected due to session expiration or operation in tab browser.

**System info:**
 - OS: Windows 10 LTSB (Windows Server 2016)
 - Browser: Firefox 81.0 (64-bit)
 - Darkreader Version: 4.9.21
 
**Additional context**
Seems to be Firefox-specific; there was no problem in Vivaldi (Chromium). Switching to any Dark Reader mode other than Dynamic and refreshing eliminates the problem. Disabling ad/tracking blockers does not help.

**Comment by unbeatable-101** [comment]
![image](https://user-images.githubusercontent.com/58151048/95275421-6e6ef400-0816-11eb-964d-da80bb316e58.png)
Can reproduce. It happens when trying to register.

**Comment by Gusted** [comment]
The page has some weird detection algorithm as `security`, What's dark reader is triggering. I suggest as a work around to use Filter(+) for this specific site.
