### ISSUE TITLE
Not working in PDF viewing

### ISSUE THREAD

**Issue by rolagg** [darkreader/darkreader#374]
According to some review and my experience on Chrome.

**Comment by yubo56** [comment]
This is currently working for me again, mark as resolved?

**Comment by risualiser** [comment]
This is working for me only in Filter/Filter+ in Chrome and Vivaldi.
What about Firefox releases - I don't know, but I checked Dev Edition (60.0beta) and there is a completely different PDF viewer, where Dark Reader doesn't work in all modes.

**Comment by alexanderby** [comment]
Firefox viewer seems to be invertable. Chrome one is all in one component, it will be tricky to invert page only and it would be impossible to not invert images.

**Comment by shaybenmoshe** [comment]
It didn't work for me either a few days ago, but then a couple of days later it started working again (maybe the upgrade to Chrome 66 fixed that somehow).

Anyhow, now I saw the new Dynamic mode, and pdfs aren't inverted by it, nor by static (but they do by both Filter and Filter+).

Thanks for everything!

**Comment by yubo56** [comment]
^ - yup same experience here

**Comment by nimafazeli** [comment]
It does not work on firefox. I am using the last version of ff.
It is odd though because I remember it used to work in the past.

**Comment by Raijin56** [comment]
The darkification of PDF files works when using Filter+ (not with Dynamic). My usual solution is saving the config with Filter+ only for the current webpage, but it's annoying doing that with every site that have a PDF.

I suggest to apply Filter+ (if it isn't the default engine) to all PDFs.

**Comment by eromoe** [comment]
What si `Filter+` ???

**Comment by sbelharbi** [comment]
@eromoe they are talking about this
![Screenshot from 2019-04-06 23-41-54](https://user-images.githubusercontent.com/23446793/55678354-0b6d6b80-58c6-11e9-8ca5-eb603cafbf3a.png)

It seems to work on Chromium, Google Chrome but not on Firefox, nor Waterfox.

**Comment by timeakesmarky** [comment]
@rolagg Not possible to make local PDFs dark? My eye strains reading books on computer.

**Comment by sbelharbi** [comment]
if by `local` you mean desktop PDF reader, you can try Evince reader with the option `Inverted Colors` on. It gives the following results:
![dark1](https://user-images.githubusercontent.com/23446793/62837065-e3599480-bc38-11e9-9a7c-31aaf1e64a5b.png)

![dark2](https://user-images.githubusercontent.com/23446793/62837066-e6ed1b80-bc38-11e9-8db0-7004cfe5324c.png)

**Comment by timeakesmarky** [comment]
@sbelharbi Hey, thanks for the reply. I mean chrome's built-in PDF reader. I don't have any apps installed. I just drag a PDF to chrome. I wish the extension could make it dark too.

For now, the workaround is to upload the PDF to google drive and read it from there with dark reader extension.

**Comment by sbelharbi** [comment]
I see.
* I just tried reading a local PDF using Google Chromium, and the dark them does not work.
* Why not use desktop apps to read PDF files? it's more straightforward than using a navigator and go through Google drive. You can write notes/highlight text and so on on desktop apps (Okular for instance which has as well inverted colors, see below). It is tedious to go through a navigator especially if you want to keep track of your readings.
* FYI, If you are using it only to read `books`, you can use [calibre](https://calibre-ebook.com/) to organise your library locally. It opens the default reader in the system, though.

![dark3](https://user-images.githubusercontent.com/23446793/62837886-d0e45880-bc42-11e9-8a43-e4d25f4e1830.png)

**Comment by timeakesmarky** [comment]
I want to have as few apps as possible. Also an old system.

**Comment by sbelharbi** [comment]
going through Google drive is a solution, than.
hopefully, the team will add this option to be able to use the them for local files. cc @alexanderby

**Comment by tylerliu1998** [comment]
Agreed with Raijin56. I suggest automatically applying Filter+ to all PDFs. Also, it seems that DarkReader can only accept the site-wise configuration. It would be much more helpful if we could use more customed pattern matching and I don't think there would be any difficulty to implement this feature.

**Comment by timeakesmarky** [comment]
> For now, the workaround is to upload the PDF to google drive and read it from there with dark reader extension.

This is not working anymore. Pity. :(

**Comment by luo-chuan** [comment]
For the same online pdf page in Chrome, the plugin "Midnight Lizard" can invert the page's color, but "Dark Reader" can't.  
![midnightlizard](https://user-images.githubusercontent.com/33930736/68875175-56454080-073d-11ea-8795-0f727ff67502.jpg)  
![darkreaderdynamic](https://user-images.githubusercontent.com/33930736/68875202-60673f00-073d-11ea-91e2-19f1df000420.jpg)

**Comment by sbelharbi** [comment]
you may need to change your settings.
![Screenshot from 2019-11-14 12-10-31](https://user-images.githubusercontent.com/23446793/68879755-efda0700-06d7-11ea-82af-88e9073e6582.png)

**Comment by eromoe** [comment]
@luo-chuan  you need use Filter+  (过滤+)

**Comment by haobangpig** [comment]
I used the Filter+ mode, it works on the online pdf file, but not at the local pdf file.

**Comment by zbot473** [comment]
Filter+ Causes the Sidebar to become white.

**Comment by ele3131** [comment]
Black Sidebars would be GREAT! Maybe this turns out to become a 'PDF Mode'

Filter+ isn't perfect for the job yet. (Better than nothing though)

**Comment by Franck-Dernoncourt** [comment]
How can I configure the Dark Reader Google Chrome extension so that the Filter+ mode is only activated for PDFs? For the other webpages I want to keep the dynamic mode.

**Comment by cool-RR** [comment]
Hey, I've had this problem of local PDFs not becoming dark. I switched to Filter+, and it worked on my desktop, but not on my laptop. I ensured they're both the same version (4.9.5). Any idea why it wouldn't work on my laptop? Maybe your new change would fix it? Has it made it to a release yet?

**Comment by cool-RR** [comment]
@Gusted @alexanderby Got time to answer my questions above?

**Comment by Gusted** [comment]
We didn't touched PDF make sure you have permission for file:// enabled

**Comment by cool-RR** [comment]
Correct, that was the issue. Thank you!

**Comment by zbot473** [comment]
Where is the option?
I can't find it on the chrome web store version.

**Comment by Gusted** [comment]
https://darkreader.org/help/en/#faq -> 
```
The extension doesn't work for local files
Open chrome://extensions page, find Dark Reader, click Allow access to file URLs.
```


@zbot473

**Comment by zbot473** [comment]
I can't find the enablePDF option for any pdf files.

**Comment by Gusted** [comment]
> I can't find the enablePDF option for any pdf files.
> Is it part of Filter+ now?

It isn't an option yet, it will be an option with darkreader V5

**Comment by zbot473** [comment]
Can I just clone the repo and build v5 for myself?

**Comment by Gusted** [comment]
> Can I just clone the repo and build v5 for myself?

Buggy and not fast ATM

**Comment by zbot473** [comment]
Ok, I'll wait then. Thanks!

**Comment by y0rune** [comment]
Now it is working in Chrome Browser, but I can not turn it off :(

**Comment by Gusted** [comment]
> Open a seperate issue for your question
@y0rune

**Comment by ak0005** [comment]
in firefox -> f12>console> viewer.style = 'filter: grayscale(100%) invert(64%) contrast(228%) brightness(80%)'

adjust the numbers according to your preference.

**Comment by dn7** [comment]
> 
> 
> for local pdf in firefox
> -> f12>console> viewer.style = 'filter: grayscale(100%) invert(64%) contrast(228%) brightness(80%)'
> 
> adjust the numbers according to your preference.

You can even run this with one click by creating a new bookmarklet (bookmark) with the following Location (target):
`javascript:void(viewer.style = 'filter: grayscale(0%) invert(100%) contrast(100%) brightness(100%)')`

Instructions: create a bookmark in Firefox by pressing CTRL+B > right-click the target folder, e.g. "Bookmarks Menu" > "New Bookmark ...".
Note that colors are also inverted, so blue becomes yellow etc. You can make everything grayscale by setting grayscale to 100%. To undo the darkening simply refresh the page (CTRL+R)

**Comment by jirikrepl** [comment]
it seems to be working fine on file PDF https://github.com/darkreader/darkreader/issues/374#issuecomment-623557873

but how to set dark reader to not invert toolbar and sides?
Those 3 rectangles are already dark and should not be inverted.

<img width="1281" alt="Screen Shot 2021-05-26 at 20 19 13" src="https://user-images.githubusercontent.com/2588479/119711583-fcf4bc00-be5f-11eb-8bfa-69db8bfb21b8.png">

**Comment by Gravifer** [comment]
I find from a reddit thread that you could input
```
document.querySelector('embed').style.filter = 'invert()'
```
in the browser console to invert the page without affecting the toolbar and the background.
Does this help to find a solution to @jirikrepl's problem?

**Comment by jirikrepl** [comment]
@Gravifer I disabled dark mode, opened the console, and pasted your code to it.
It inverts the colors, but it will invert all - pdf background and top toolbar

**Comment by Gravifer** [comment]
@jirikrepl sorry I didn't clarify the context; I am using Microsoft Edge, and the team modified the viewer plugin. The command actually only inverts the content when the controls are in night mode. Maybe we should hack the plugin already... This is silly.

**Comment by TejasO2** [comment]
> https://darkreader.org/help/en/#faq ->
> 
> ```
> The extension doesn't work for local files
> Open chrome://extensions page, find Dark Reader, click Allow access to file URLs.
> ```
> 
> @zbot473

Thanks! This worked smoothly!!

**Comment by virenchocha** [comment]
As per users, PDF are opening in darkmode if accessed on webpage residing on webserver. Why we can't have a local webserver running and read file from it. I've done exactly that and it works. No extra addins. A few mins of work and you have it.

- Have darkreader enabled on Chrome
- Install XAMPP (This will install php, mysql, apache etc.) and it will be rewarding in long run.
- Open XAMPP and start Apache webserver (in case of error of port change port to 8080 in config file of apche)
- Make a folder in already existing 'htdocs' subfolder of XAMPP folder and dump .pdf file you want to read there
- create an index.php file in htdocs and paste following php code.
- In the below code replace filename with file you want to read.
- Remeber index.php and .pdf file you want to read must be in same subfolder of 'htdocs' folder of XAMPP

<?php
// Store the file name into variable.
$file = './filename.pdf';
$filename = './filename.pdf';
  
// Header content type
header('Content-type: application/pdf');
 header('Content-Disposition: inline; filename="' . $filename . '"');
 header('Content-Transfer-Encoding: binary');
 header('Accept-Ranges: bytes');
  
// Read the file
@readfile($file);
?>
- Save the file
- type http://localserver:8080.
- Voila ! Your PDF file in dark mode will open
- Feel free to contact or comment.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
