### ISSUE TITLE
[Feature Request] Round scroll bar for all sites

### ISSUE THREAD

**Issue by Roshan4tech** [darkreader/darkreader#3741]
::-webkit-scrollbar {
    width: 16px !important;
    height: 16px !important;
}

::-webkit-scrollbar-thumb {
    background: #5f6368 !important;
    background-clip: padding-box !important;
    border: 4px solid transparent !important;
    -webkit-border-radius: 8px !important;
    border-radius: 8px !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    min-height: 50px !important;
    min-width: 50px !important;
}

```
::-webkit-scrollbar-track {
    background: none !important;
    border: none !important;
}

::-webkit-scrollbar-track:vertical:hover {
    border-left: 1px solid rgba(0,0,0,.1) !important;
    background: rgba(0,0,0,.05) !important;
}

::-webkit-scrollbar-track:horizontal:hover {
    border-top: 1px solid rgba(0,0,0,.1) !important;
    background: rgba(0,0,0,.05) !important;

```

If any user add this code initially in the code of dark reader dev tools, then each and every scroll bar in the chrome becomes round which looks pretty much cool. My feature request is that, Add this code by-default in dev tools so that everyone gets the round scrollbar.

![chrome_3dHrvNmBpg](https://user-images.githubusercontent.com/62097808/94514964-23664700-0240-11eb-83a0-15ef839ace0f.png)

**Comment by Gusted** [comment]
Hi @Roshan4tech!

That seems more like a enchantment to make the style like roundish?
I'm not sure if everyone likes that as we have specific chosen to not touch the scrollbar other than the colors so every browser can decide for itself what's the best scrollbar style.

Regards,
Gusted

**Comment by Roshan4tech** [comment]
Okay. Thanks for the response.

**Comment by krystian3w** [comment]
@Gusted - Firefox 63 - 71 no match color based on background of page, Firefox 72 added these for:

 https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color

**https://www.ghacks.net/2019/11/11/firefox-72-dynamic-scrollbars-based-on-page-color/**

I have no idea how to detect that someone is still using Firefox 71 or older to release 64. Maybe needed based on this section https://developer.mozilla.org/pl/docs/Mozilla/Firefox/Releases/72#CSS with "`@supports`".

**Comment by Gusted** [comment]
I'm not sure, but what has `scrollbar-color` to do with this?

**Comment by krystian3w** [comment]
> I'm not sure if everyone likes that as we have specific chosen to not touch the scrollbar other than the colors so every browser can decide for itself what's the best scrollbar style.

So for Firefox 63 - 71 you can safe override, because Mozilla no based on system/page background.

**Comment by Gusted** [comment]
> So for Firefox 63 - 71 you can safe override, because Mozilla no based on system/page background.

I mentioned it's a browser chose to choose the styling of the scrollbar, but you're mentioning the color of it which we are already dynamic styling. Anyway I'm saying no to this feature request.
