### ISSUE TITLE
[BUG] Darkreader package on Angular 9 app

### ISSUE THREAD

**Issue by mBakir2** [darkreader/darkreader#3748]
### **Describe the bug**
The app become slower and I get this issues in the console:
 Embedded Dark Reader cannot access a cross-origin resource https://fonts.googleapis.com/css?family=Montserrat&display=swap Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.

darkreader.js:278 Error: Embedded Dark Reader cannot access a cross-origin resource https://fonts.googleapis.com/icon?family=Material+Icons Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.

darkreader.js:278 Error: Embedded Dark Reader cannot access a cross-origin resource https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.

darkreader.js:278 Error: Embedded Dark Reader cannot access a cross-origin resource https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.

### **Steps to reproduce**

After activating the dark reader in the angular 9 app using the following methods
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        enableDarkMode({
          brightness: 100,
          contrast: 90,
          sepia: 10,
        });
        followSystemColorScheme(result);
      } else {
        disableDarkMode();
      }
    });

### **Expected behavior**
The app should be smooth, not slow

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome Version 85.0.4183.121
 - Dark Reader version: darkreader@4.9.21
 - Angular 9

**Comment by Gusted** [comment]
Hi @mBakir2!

Can you try to add
```javascript
DarkReader.setFetchMethod(window.fetch)
``` 
before the line
```javascript
if (result) {
``` 
Is this seems to be a common CORS issue whereby no fetch method has been set.

Regards,
Gusted

**Comment by mBakir2** [comment]
> Hi @mBakir2!
> 
> Can you try to add
> 
> ```js
> DarkReader.setFetchMethod(window.fetch)
> ```
> 
> before the line
> 
> ```js
> if (result) {
> ```
> 
> Is this seems to be a common CORS issue whereby no fetch method has been set.
> 
> Regards,
> Gusted

I have already figured it out using  `setFetchMethod(window.fetch);` But thank!
I thought the app is slow because of these issues, but after fixing it using the method above, it still very slow.

I noticed that when I'm enabling the darkreader using the enable method, it won't apply the dark theme to all the pages, but the app is fast as usual. Using the ```
followSystemColorScheme({
brightness: 100,
contrast: 90,
sepia: 10,
});
```
which applies the dark theme every wherein the web app, make it slower, But using the extension won't make it slower the same way as `followSystemColorScheme` method.. So any idea about this issue?

**Comment by Gusted** [comment]
> I thought the app is slow because of these issues, but after fixing it using the method above, it still very slow.

Well your using the dynamic theme, so it will first analyze all Styles and modify them on-the-fly.

> But using the extension won't make it slower the same way as followSystemColorScheme method.. So any idea about this issue?

In which order is API being loaded? It's the best to have it loaded as last possible code.

**Comment by mBakir2** [comment]
> > I thought the app is slow because of these issues, but after fixing it using the method above, it still very slow.
> 
> Well your using the dynamic theme, so it will first analyze all Styles and modify them on-the-fly.
> 
> > But using the extension won't make it slower the same way as followSystemColorScheme method.. So any idea about this issue?
> 
> In which order is API being loaded? It's the best to have it loaded as last possible code.

If I did understand you correctly - After the app being loaded, If the user wants to switch to the dark mode he selects the theme that he wants. Based on the result which is a boolean result, I'm calling the API after closing the dialog
```
dialogRef.afterClosed().subscribe(result => {
      setFetchMethod(window.fetch);
      if (result) {
        // enableDarkMode({
        //   brightness: 100,
        //   contrast: 90,
        //   sepia: 10,
        // });

        followSystemColorScheme({
          brightness: 100,
          contrast: 90,
          sepia: 10,
        });
      } else {
        disableDarkMode();
      }
    });
```

**Comment by Gusted** [comment]
Hmm,
Can you define `slow` in this case for the Angular 9 app.

**Comment by mBakir2** [comment]
> Hmm,
> Can you define `slow` in this case for the Angular 9 app.

Sure, basically when I try to open dialogs or select an option from lists or searching using tables. It's slow in every way you can imagine while using the app. (There's a delay of a second or two while hovering over different options)

**Comment by mBakir2** [comment]
But the weird thing is that, it works perfectly using the darkreader chrome extetion

**Comment by Gusted** [comment]
> Sure, basically when I try to open dialogs or select an option from lists or searching using tables. It's slow in every way you can imagine while using the app. (There's a delay of a second or two while hovering over different options)

Wait, but that shouldn't be happening AT ALL. The only slow-down something can be experienced is when style sheets are being updated, are they? e.g. `<style>` elements. Like constant? Or any other CSS that's constant being modified.

**Comment by Gusted** [comment]
> 
> 
> But the weird thing is that it works perfectly using the darkreader chrome extension

Can you have a extra check if your using the [latest](https://unpkg.com/darkreader@latest/darkreader.js) version of the API

**Comment by mBakir2** [comment]
> > But the weird thing is that it works perfectly using the darkreader chrome extension
> 
> Can you have a extra check if your using the [latest](https://unpkg.com/darkreader@latest/darkreader.js) version of the API

![image](https://user-images.githubusercontent.com/44927719/94618138-a7d4bc00-0278-11eb-8328-82897c011b8a.png)

**Comment by mBakir2** [comment]
The arrow shows the point of disabling darkreader
![image](https://user-images.githubusercontent.com/44927719/94618384-0f8b0700-0279-11eb-9516-e07e0c8ca7b3.png)

**Comment by Gusted** [comment]
Could you try the performance tab and profile when it's `slow` and check which functions are repeatably being executed.

**Comment by mBakir2** [comment]
> Could you try the performance tab and profile when it's `slow` and check which functions are repeatably being executed.

![image](https://user-images.githubusercontent.com/44927719/94619392-d358a600-027a-11eb-9cb7-00b63e175a7e.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/6TyOht7.png)
Could you pinpoint on one of those blocks and check the details of that block and see what function is being executed.

**Comment by mBakir2** [comment]
> ![](https://camo.githubusercontent.com/c842929a9dbb903f74dbdb521c68f4a09a602a9b/68747470733a2f2f692e696d6775722e636f6d2f3654794f6874372e706e67)
> Could you pinpoint on one of those blocks and check the details of that block and see what function is being executed.

![image](https://user-images.githubusercontent.com/44927719/94619866-9f31b500-027b-11eb-89b3-5d06452786e4.png)

**Comment by Gusted** [comment]
Yea, those all seems seems to be Angular code, as  you can recognize Dark Reader code if it comes out the file `index.js`.
However Angular seems to have problems with dark reader 🤷🏽. Why? IDK.

Guess opening a issue over at Angular could lead to more answers.

**Comment by mBakir2** [comment]
> Yea, those all seems seems to be Angular code, as you can recognize Dark Reader code if it comes out the file `index.js`.
> However Angular seems to have problems with dark reader 🤷🏽. Why? IDK.
> 
> Guess opening a issue over at Angular could lead to more answers.

Alright sounds good, thanks for your efforts.
