### ISSUE TITLE
[Broken Website] https://gatling.io

### ISSUE THREAD

**Issue by senpl** [darkreader/darkreader#3757]
**Website**
https://gatling.io

**How to Reproduce**
An example of this is
> 1. Go to https://gatling.io
> 2. try different avaliable filters

**Expected behavior**
Color inverted in one filter

**Actual behavior**
not inverted

**System info:**
 - OS: Windows 7
 - Browser: Vivaldi
 - Darkreader Version: 4.9.21

**Comment by Gusted** [comment]
> try different avaliable filters

Uhm what?

**Comment by unbeatable-101** [comment]
![image](https://user-images.githubusercontent.com/58151048/95275184-d3761a00-0815-11eb-9d63-aa8d1de5bbc9.png)

This is the static filter

**Comment by Gusted** [comment]
Their is no support for static filters.
