### ISSUE TITLE
Switching mode affects FF menu theme

### ISSUE THREAD

**Issue by Symbai** [darkreader/darkreader#376]
I have FF 59.0.2 the official dark theme activated. Since a few days if I turn off the dark mode by Dark Reader it also changes the menu background at the top to white. I have to switch to white FF theme and back to dark to restore the color.

I believe it has something to do with FF dev team making the menu background stylable. Anyway it would be nice if the dark mode only affects the website as it previously did.

**Comment by alexanderby** [comment]
I think this is a browser bug or inconsistent API. I've used Dynamic Theme API to take part in Mozilla contest. Dark Reader applies filter settings to tabs colors (works in Firefox 60). When you click Disable it resets the theme. I will remove that reset then.
