### ISSUE TITLE
[Broken Website] Missing example output on developer.mozilla.org

### ISSUE THREAD

**Issue by fvbommel** [darkreader/darkreader#3761]
**Website**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**How to Reproduce**
1. Open the link in Firefox with dark mode enabled (dynamic theme generation mode)
2. Look at the output of "HTML Demo: \<details\>" near the top.

**Expected behavior**
The output of the example should be visible.

**Actual behavior**
The output of the example is missing.

**Screenshots**

Light mode: ![image](https://user-images.githubusercontent.com/4797722/94828582-e6e64700-0409-11eb-821c-9cd075d29fc6.png)

Dark mode: ![image](https://user-images.githubusercontent.com/4797722/94828483-cfa75980-0409-11eb-9767-bda2549188cd.png)

**System info:**
 - OS: Linux Mint 18.3 Sylvia
 - Browser: Firefox 81 (`mozilla/5.0 (x11; ubuntu; linux x86_64; rv:81.0) gecko/20100101 firefox/81.0`)
 - Darkreader Version: 4.9.21

**Additional context**
It works in Chromium (`Version 85.0.4183.121 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)`) which also has Darkreader version 4.9.21.

**Comment by Gusted** [comment]
Hi @fvbommel!

It seems to be a internal error of MDN itself which we are triggering but can't fix.
Best way, to get this fixed is to forward this issue to Mozilla.
![](https://i.imgur.com/amqQSDF.png)

Regards,
Gusted
