### ISSUE TITLE
[BUG] Random crash while browsing, stuck on light mode until you restart

### ISSUE THREAD

**Issue by PtrckDns** [darkreader/darkreader#3768]
### **Describe the bug**

It will freeze suddenly and needs to be relaunch

### **Steps to reproduce**

Go to youtube or reddit and it will usually occur within a few seconds

### **Expected behavior**

The dark mode will disappear forcing you on light mode until you end process and relaunch the extension

### **System Information:**
 - OS: Linux Mint 20
 - Browser: Chrome 85.0.4183.121 (Official Build) (64-bit)
 - Dark Reader version: 4.9.21

**Comment by Gusted** [comment]
Hi @PtrckDns!

Does Chrome show any notification of crashing?
As you seems to get it easily reproduced, could you try to launch Chrome with logging enabled to see if their is any specific cause for this. [Support page from Google](https://support.google.com/chrome/a/answer/6271282?hl=en)

Regards,
Gusted
