### ISSUE TITLE
[BUG] Stuck On Loading, Have to Restart Dark Reader

### ISSUE THREAD

**Issue by Phoenix465** [darkreader/darkreader#3772]
Occasionally, I notice that it makes all sites automatically black, even whitelisted one, so when I click the extension it is stuck on the loading screen with the text on the top right just saying loading. To resolve this I had to restart Dark Reader by turning it off and on again.

### **Steps to reproduce**
I have to way of reproducing it as it just happens randomly.

### **Expected behavior**

Whitelisted sites stay normal and others get darkened.

### **Actual behavior**

I notice that it makes all sites automatically black, even whitelisted one, so when I click the extension it is stuck on the loading screen with the text on the top right just saying loading

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome 85.0.4183.121
 - Dark Reader version: 4.9.21

**Comment by Gusted** [comment]
Hi @Phoenix465!

Have you tried to re-install dark reader?
Also, does it show any errors in console?

Regards,
Gusted

**Comment by Phoenix465** [comment]
Hello, 
I have re-installed dark reader and it still occurs.
I haven't got any errors yet but I'll post if I see it, however since late yesterday I haven't got it crashing yet.

**Comment by Gusted** [comment]
Hi @Phoenix465!

Does this issue still persist?

Regards,
Gusted

**Comment by Phoenix465** [comment]
Hello again, 

The issue seems to somehow have resolved itself, I haven't had any problems for the past days. Should I close this issue?

Thanks,

**Comment by Gusted** [comment]
> The issue seems to somehow have resolved itself,

Glad it did :D
