### ISSUE TITLE
[Feature Request] Please consider adding the "Hacktoberfest" topic to this project.

### ISSUE THREAD

**Issue by ceiphr** [darkreader/darkreader#3774]
**Is your feature request related to a problem? Please describe.**
Recently, DigitalOcean announced Hacktoberfest to be opt-in only:
https://twitter.com/hacktoberfest/status/1312221208667185153

This is to help mitigate spam for large projects such as this one.

**Describe the solution you'd like**
If the maintainers of this project are open to the idea, would they be willing to add the "Hacktoberfest" topic to this project?

**Additional context**
https://hacktoberfest.digitalocean.com/

**Comment by Gusted** [comment]
@alexanderby You have the power to edit topics.

Even though my personal opinion on the Hacktoberfest isn't a postive one, but that shouldn't ruin the fun for others.

**Comment by Gusted** [comment]
Seems no interest into doing this.
