### ISSUE TITLE
[Broken Website] microsoftstore.com.cn

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3779]
**Website**
https://www.microsoftstore.com.cn/

**How to Reproduce**

> 1. Go to the site

**Expected behavior**
Dark background
**Actual behavior**
Not dark background

**System info:**
 - OS: Windows
 - Browser: Edge
 - Darkreader Version: 4.9.20

**Comment by unbeatable-101** [comment]
![image](https://user-images.githubusercontent.com/58151048/95275063-8134f900-0815-11eb-99f6-47ede9ed874f.png)
