### ISSUE TITLE
Darkreader crashes my firefox theme (persona)

### ISSUE THREAD

**Issue by Enchufadoo** [darkreader/darkreader#379]
Using FF 59.02 64 bit on Windows 7/10 darkreader crashes the persona theme on loading firefox, when I open a new window the persona reappears I think.

I record it here (didn't know where else to upload the video 🤦‍♂️ 

https://www.reddit.com/user/enchufadoo/comments/8da4yb/dark_reader_error/

**Comment by alexanderby** [comment]
Thank you for the video. I've published a fix, that will not reset a theme when Dark Reader is switched Off (via settings popup).

Dark Reader creates it's own theme with applied filter settings in Firefox 60 (Firefox 59 has the same API, but has no effect). When you click Off Dark Reader disables it's theme. But Firefox has a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1415267

I will make a button to make this feature optional.

**Comment by alexanderby** [comment]
The button for disabling this feature was added. Still the Firefox will reset the browser theme when you enable and then disable the feature. Re-enable preferred theme plugin in such case.
