### ISSUE TITLE
[BUG] Some elements cannot be rendered

### ISSUE THREAD

**Issue by hxse** [darkreader/darkreader#3792]
### **Describe the bug**

Some elements cannot be rendered.
![image](https://user-images.githubusercontent.com/22582226/95197866-d7516e80-080c-11eb-952b-0496ef0e6dfc.png)

Need to re-render manually to be useful
![image](https://user-images.githubusercontent.com/22582226/95197909-e506f400-080c-11eb-871a-aee3ba246800.png)

### **Steps to reproduce**

- Go to https://docs.python.org/3/whatsnew/3.9.html
- Click on '...'
- Scroll down to '...'

### **System Information:**
 - OS: windows 10
 - Browser: 85.0.4183.121
 - Dark Reader version: 4.9.21

**Comment by Gusted** [comment]
#835
