### ISSUE TITLE
Dark reader randomly loads pages in light mode in Firefox

### ISSUE THREAD

**Issue by robsmith11** [darkreader/darkreader#380]
Dark Reader has been working great in Firefox (60b13), but at some point over the past 1-2 weeks an issue has started where sometimes a page will load as if the Dark Reader was turned off (even though the icon still indicates it is in dark mode).

Usually a refresh will fix it.  It seems more likely to happen on some pages than others.  It's much more likely to happen when I open a tab in the background and then switch to it.  I'd say it happens on 10% of the time when refreshing an open tab and 50% of the time when loading a new tab in the background.

I'm guessing it's some kind of timing issue where something will randomly get loaded too soon/late.  I've disabled all other extensions and the problem persists.

**Comment by alexanderby** [comment]
Are you using "Filter" mode?

**Comment by alexanderby** [comment]
I've published a fix in version 4.2.5
