### ISSUE TITLE
Gmail hangouts color is not inverted

### ISSUE THREAD

**Issue by yubo56** [darkreader/darkreader#381]
<img width="1440" alt="screen shot 2018-04-19 at 13 30 52" src="https://user-images.githubusercontent.com/5651687/39008202-016a4686-43d6-11e8-961a-8aa136b9f337.png">

Think the gmail sidebar used to be inverted? On Dark reader Dark it gets inverted correctly. Thought it would be fixed with pdfs being fixed but looks like not

**Comment by alexanderby** [comment]
It's because we do not invert iframes content yet. The fix should be rather simple.

**Comment by yubo56** [comment]
I seem to recall this worked correctly at one point though? Maybe my memory is fuzzy.

Glad it's on your radar though, no rush! Love the extension so much, it works great
