### ISSUE TITLE
[Broken Website] worldofwarcraft.com

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#3810]
**Website**
https://www.wowchina.com
https://worldofwarcraft.com

**How to Reproduce**

> 1. Go to the sites
> 2. Hover over "新闻" button in wowchina.com
> 3. Hover over "NEWS" button in worldofwarcraft.com

**Expected behavior**
Text visible.

**Actual behavior**
Text hardly visible.

**System info:**
 - OS: Windows,
 - Browser: Edge
 - Darkreader Version: 4.9.20

**Comment by Gusted** [comment]
Hi @hgajshb!

Do you still experience this issue, I can't reproduce this.
![](https://i.imgur.com/j0joBA4.png)

Regards,
Gusted
