### ISSUE TITLE
Dark Reader scrollbar option

### ISSUE THREAD

**Issue by barnoii** [darkreader/darkreader#3812]
So I recently re-installed Dark Reader and I love the new UI. One thing that did bother me was the scrollbar. Last versions you were able to disable Dark Reader's scrollbar, but I couldn't find it in this version. I'm not sure if I missed it or it's hidden somewhere, I just couldn't find it.

**Comment by Gusted** [comment]
Hi @barnoii!

If you change the option to `Default` ![](https://i.imgur.com/kbXQcZ6.png)
It will not modifying scrollbar.

Regards,
Gusted

**Comment by barnoii** [comment]
Sorry, but that's the problem. Mine doesn't appear to have that feature anywhere.
![image](https://user-images.githubusercontent.com/65990582/95511045-e9561d00-0984-11eb-8fd7-df8c154d16cc.png)
![image](https://user-images.githubusercontent.com/65990582/95511084-f6730c00-0984-11eb-9cd0-3f2be3ee47d6.png)
I downloaded this version from the chrome web store.

**Comment by Gusted** [comment]
>  and I love the new UI.

You stated you already had the new UI.

Anyway, Dev Tools -> Preview new design.

**Comment by barnoii** [comment]
Oh I'm really sorry. Last time I downloaded it was set to that by default. I thought it was a new design. Sorry for the inconvience!

**Comment by Gusted** [comment]
No problems.

**Comment by Arbiterz** [comment]
Changing my scrollbar to default did not change a thing.

**Comment by Gusted** [comment]
What's your expected output? Please just open a new issue instead of posting a *non-actionable* comment on a old issue.
