### ISSUE TITLE
[Feature Request] Change shade based on time

### ISSUE THREAD

**Issue by JeffryMAC** [darkreader/darkreader#3825]
**Describe the solution you'd like**
It would be great if the "level" of dark can be configurable based on time (automatically)
It doesn't always have to be so dark or be handled manually.
![Weekdone-Dark-Mode-setttings-700x363](https://user-images.githubusercontent.com/63792998/95677809-bef89f80-0bd0-11eb-836b-b2e5c729622e.png)

taken from [this](https://blog.weekdone.com/why-you-should-switch-on-dark-mode/) blog post.

**Comment by Gusted** [comment]
Hi @JeffryMAC!

Could you active the new design by the following steps

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

When you have the new design enabled, please check the new dynamic color picker *(under Theme click See all options, Colors).*
You can adjust the colors to your needs and even make the background `#000000` Which give it a black shade.

A part of your request seems to be automation for the kind of color? I personally don't think this is a good feature as I don't really see the benefit or the use-case for this feature.

Regards,
Gusted

**Comment by JeffryMAC** [comment]
not automation of color as itself.
I'm saying that when it's middle of the night a more light black is OK
when it's mid day dark black is better.
I'm looking for TIME based automation.

**Comment by kylrth** [comment]
I agree. This is a common setting on many phones. On my Android, most of my apps (including Firefox) use a light mode during the day and a dark mode at night. This is what I want to happen in my desktop browser too.

**Comment by kylrth** [comment]
@Gusted can we reopen this?

**Comment by Gusted** [comment]
> 
> 
> @Gusted can we reopen this?

I'm not sure why, as the main idea of automation for `SHADES of color` isn't going into Darkreader. However you suggested the [already integrated automation](https://darkreader.org/blog/automation/)

**Comment by kylrth** [comment]
Ah I see! I couldn't find that setting. Thanks.
