### ISSUE TITLE
[Feature Request] Download and upload Site List to a file?

### ISSUE THREAD

**Issue by thouu** [darkreader/darkreader#3829]
I have Dark Reader on both my desktop computer and my laptop. I want to move my Site List from my desktop to my laptop, but I'm unable to.

Maybe you could download the Site List to a file, so then you can load it into Dark Reader on other computers.

**Comment by Gusted** [comment]
Hi @thouu!

Please follow the following steps.

Activate the new user interface:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

`Ability to import and export settings (click Settings, Manage settings).`

Regards,
Gusted
