### ISSUE TITLE
[Broken Website] Amazon Progress Tracker

### ISSUE THREAD

**Issue by jrd** [darkreader/darkreader#3831]
**Amazon**
Experienced on https://www.amazon.fr

**How to Reproduce**
> 1. Have an Amazon command
> 2. Go to the progress tracker for that command

**Expected behavior**
Amazon animation is smooth and lines/dashes drawn between steps

**Actual behavior**
Flickering shown and no “lines” drawn between steps.

**Screenshots**
With darkreader:
![image](https://user-images.githubusercontent.com/497895/95746870-cc2c9180-0c97-11eb-8292-377d1ac679eb.png)

Without darkreader:
![image](https://user-images.githubusercontent.com/497895/95746954-e5354280-0c97-11eb-9fc9-69a3675e18d1.png)

**System info:**
 - OS: Linux / Manjaro
 - Browser: Firefox 81.0
 - Darkreader Version: 4.9.21

I didn’t find how to force the lines/dashes to display using the css debug tools.

**Comment by jrd** [comment]
Here is a sample for that page, for testing.
[amazon-progress-tracker-for-darkreader.zip](https://github.com/darkreader/darkreader/files/5365374/amazon-progress-tracker-for-darkreader.zip)

One can test it by creating a simple website to bypass the `file://` protocol (where darkreader won’t apply).
For instance using `python -m http.server` and opening `http://127.0.0.1:8000/amazon-progress-tracker-for-darkreader.html`

**Comment by Gusted** [comment]
#3718 This should fix it.

**Comment by jrd** [comment]
Oh thanks, didn’t find this.
