### ISSUE TITLE
[BUG] Brave browser: Dynamic Theme Generation Mode goes to bottom of new tab link opened

### ISSUE THREAD

**Issue by Danie10** [darkreader/darkreader#3833]
### **Describe the bug**

This is not occurring with Chromium so only with Brave browser. Also it does not show up if you right-click and open a link from drop-down menu. It occurs when left-clicking on a  link to open the link in a new tab. If any other Theme Generation Mode is chosen it opens tab at top of the page. It is certainly something isolated to the Brave browser and the Dynamic Theme Generation mode.

### **Steps to reproduce**

- Left-click with mouse on any URL link in text paragraph.
- New tab opens and renders the page fine in dark mode.
- But reading position is right at the bottom of the page and you have to scroll up to top every time.

### **Expected behavior**

Left-click ona  link, new tab opens, reading position at top of that page. Does work correctly on Chromium.

### **Actual behavior**

New tab open but positioned at bottom of the page. Rendering of colour is all correct.

### **Screenshots**

N/A

### **System Information:**
 - OS: Manjaro Linux KDE 64-bit
 - Browser: Brave Version 1.13.54 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)
 - Dark Reader version: 4.9.21

### **Additional context**

Is working 100% on Chromium. Also works fine on other Theme Generation Modes, but they do not render as well as Dynamic does. Colour rendering sis till fine on Dynamic Mode, it is purely that it goes to the bottom of every new page opened when left-clicking on links.

**Comment by Gusted** [comment]
Hi @Danie10!

Could you try Brave Nightly and could you make some screenshot of this behavior as I can't fully understand this issue.

Regards,
Gusted

**Comment by Danie10** [comment]
@Gusted OK did so, and pretty weird. Narrowed it down further and realise why it only is happening with Brave browser by me. I'm using vTabs extension on Brave. So it worked fine at first on Brave Nightly but then I noticed it was breaking again. It only misbehaves if I have both Dark Reader and vTabs extensiions running. vTabs on it's own without Dark Reader enabled is working fine. Likewise if I have just Dark Reader enabled but vTabs is disabled it works fine.

Suspect I'll have to close this, as vTabs is currently not supported and was withdrawn from the store a few months back. vTabs is set to shrink the page to show the tabs on the side and I suspect that is what is actually breaking things here, not Dark Reader. Both extensions mess with the page draw and I think they clash together.

Thanks for responding so quickly though as it did help me narrow it down to where I think the problem is.
