### ISSUE TITLE
[Feature Request] Cloud sync of settings

### ISSUE THREAD

**Issue by Firehawke** [darkreader/darkreader#3835]
This extension is incredibly useful in its current state, but there's one missing feature that I think would bring it to perfection in my eyes. Please consider adding cloud sync of settings to the extension.

I'd like all settings for the extension to be synced to the cloud similarly to how you can use Tampermonkey/Stylish/etc to sync to Google Drive, Dropbox, and so forth. Many users, like myself, have more than one machine they work from-- a desktop and a laptop, or a phone (assuming this works on phone; I haven't yet looked into that). Additionally, sometimes your OS breaks and you need to do a reinstall. Being able to recover your settings as well as keep multiple machines synced with the same profiles would make this extension even better.

That said, while an issue is not the best place to be complimenting your extension, I do have to say that I've had this installed for less than an hour and I'm already quite certain it's staying on every machine I work from. I have extreme light sensitivity and suffer from migraines, so pages with bright white backgrounds are not only difficult to read but somewhat painful. This extension has already saved me significant amounts of pain today alone-- so please accept my sincere thanks for this project.

**Comment by Gusted** [comment]
Hi @Firehawke!

Dark reader is by native already synchronizing to the browser's cloud storage, but you state
`Google Drive, Dropbox, and so forth.` Is their any benefit over the native storage of the browser?

Regards,
Gusted

**Comment by Firehawke** [comment]
Okay, so let me ask this clearly: It currently saves to Firefox Sync? If so, that's sufficient, but it doesn't look like the actual plugin settings are shared across my two computers on the Firefox Sync account.

**Comment by Gusted** [comment]
> Okay, so let me ask this clearly: It currently saves to Firefox Sync?

Well to make it sure.


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Settings -> Manage Settings -> Sync Settings. Make sure it's enabled like ![](https://i.imgur.com/zC28ytM.png)

**Comment by Firehawke** [comment]
I see the option and I have it turned on, but it definitely isn't syncing between the two machines here.
I turned on dark mode for code.visualstudio.com, went to this machine (it was off), powered it up and it's not showing the setting as synced despite both machines having the same overall settings (and Firefox sync turned on).

**Comment by Firehawke** [comment]
It finally did go through.

It seems to be really slow to sync. It did come up, but only after I ran the browser, exited, waited awhile, and reopened it.

Guess I can close this now.

**Comment by Firehawke** [comment]
Actually, I'm going to aside on ONE last thing on this. I noticed that this supports Chrome as well as Firefox. Having a non-browser-backed sync option would be good for those who work in multiple browsers.

**Comment by slrgt** [comment]
I use the Preview of the new design (4 years and still in preview?) but it still does not sync
