### ISSUE TITLE
[Broken Website]  https://www.investing.com Firefox only

### ISSUE THREAD

**Issue by asdaskns** [darkreader/darkreader#3837]
**Website**
The link of the broken website https://www.investing.com

The site will not change to dark, and it will use a lot of CPU every time I open it without even making it dark.

An this happens on all the subpages on the website

Apparently this is in Firefox only

**Comment by vasseray** [comment]
I can confirm this bug exists.

In my case, It only happens when you first open the website or doing ctrl+shift+R.
If you refresh the page or click a link to different sub-pages, it will work properly.

Windows 10/Firefox 83.0b5
