### ISSUE TITLE
[Broken Website] infinitysearch.co

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#3841]
**Website**
infinitysearch.co

**How to Reproduce**
An example of this is
> 1. Go to infinitysearch.co

**Expected behavior**
![sshot-005](https://user-images.githubusercontent.com/36977733/95878733-116ac500-0d65-11eb-8268-632cfc0ba280.png)

**Actual behavior**
![sshot-004](https://user-images.githubusercontent.com/36977733/95878764-1891d300-0d65-11eb-917b-1d3575653bd9.png)

After reenable dark reader it will look like the above one.

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.17

**Comment by Gusted** [comment]
Need a look later this week or even next week as it seems the `disabled` attribute isn't being respected.

**Comment by Gusted** [comment]
Update to 4.9.23 it has been fixed.

**Comment by linsui** [comment]
Hi, I can still reproduce the same behavior here.

**Comment by Gusted** [comment]
Hi @linsui!

Got the behaviour again and made opened up a PR(#4138) to handle this correctly.

Regards,
Gusted
