### ISSUE TITLE
[Broken Website] accounts.google.com flags.png

### ISSUE THREAD

**Issue by lazycrazy07c2** [darkreader/darkreader#3858]
**Website**
[accounts.google.com](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2F&hl=en&dsh=S218527022%3A1602709022920286&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp)

**How to Reproduce**
> 1. Go to accounts.google.com site
> 2. Create account
> 3. Fill needed fields and click on the Next button
> 4. Next page will ask for to verify a phone number and the country chooser (flag box) is broken

**Expected behavior**
expected to see the selected country
![has to be](https://user-images.githubusercontent.com/72767361/96047146-f25b5880-0e74-11eb-8f49-14777591f39a.png)

**Actual behavior**
the Inspector shows that there is a background-image with a strange url that makes it broken: 
https://ssl.gstatic.com/accounts/static/_/ss/k=gaia.gaiafe_glif.wJTyC_VA1vg.L.W.O/am=78UHDPxBHWDABQAB5gAAAAAAAAAABpAHLMtD1WuF7x8G/d=0/ct=zgms/'//ssl.gstatic.com/i18n/flags/48x32/nobevel/66bdb7a1bbbdbf86a67de382fac49ecc/flags.png'
![now](https://user-images.githubusercontent.com/72767361/96046521-e9b65280-0e73-11eb-81c1-811bd6b517a6.png)
without darkreader
![without](https://user-images.githubusercontent.com/72767361/96047114-e5d70000-0e74-11eb-9490-0751b9331236.png)

**System info:**
 - OS: Linux
 - Browser: firefox 81, chromium 85
 - Darkreader Version: 4.9.21
 
**Additional context**
i see by other *.google.com parts that it can be done with follow part, but this url seems like generated. ¿what do you thing about it?
```
CSS
.Fy0Xbe {
    background-image: url('//ssl.gstatic.com/i18n/flags/48x32/nobevel/66bdb7a1bbbdbf86a67de382fac49ecc/flags.png') !important;
}
```

**Comment by Gusted** [comment]
Hi @lazycrazy07c2!

I think 
```CSS
#countryList div[role="option"][data-value] div[style] {
    background-image: url( '//ssl.gstatic.com/i18n/flags/48x32/nobevel/66bdb7a1bbbdbf86a67de382fac49ecc/flags.png') !important;
}
```
Should do it, however I'm worried about the maybe generated path of the background-image.

Regards,
Gusted

**Comment by lazycrazy07c2** [comment]
thanks for response. i did a look, it's a bit colorful on click/select, but
` #countryList div[role="option"][data-value] > div > div > div[style] `
can be used to prevent the magic on click.
maybe it is possible to prevent this behavior with the broken url (see _Actual behavior_) instead of fix each time the dynamic-theme-fixes.config.
regards
