### ISSUE TITLE
[Filter+] trakt.tv: colors are inverted only when the first page is loaded for the first time

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#386]
When you load <https://trakt.tv> for the first time, it loads the _Dashboard_ <https://trakt.tv/dashboard>, and the colors are correctly inverted:
![image](https://user-images.githubusercontent.com/10074769/39117573-a78d3264-46bd-11e8-9d9e-5eca5c05b51c.png)
If you navigate to any other page, for instance, the _History_ or _Collection_:
![image](https://user-images.githubusercontent.com/10074769/39117620-c8b42bdc-46bd-11e8-971a-40a851324ef7.png)
the colors are not inverted:
![image](https://user-images.githubusercontent.com/10074769/39117647-d58eee14-46bd-11e8-8cfc-8c5ecd827d6d.png)
Thereafter, no matter what page you load, even the _Dashboard_, the colors are not inverted anymore:
![image](https://user-images.githubusercontent.com/10074769/39117666-e43c4eac-46bd-11e8-8e36-48d65c9a78bd.png)

**Comment by logical-and** [comment]
Same for me. But it happens randomly, so I'm forced to click apply dev tools N times per day. Please please fix it. This is the only thing why I didn't donate yet :)

**Comment by Aqa-Ib** [comment]
@logical-and if you donate alexanderby can spend more time fixing the program ;)

**Comment by alexanderby** [comment]
I'm already doing it full-time :) Some sites are hard to fix in Filter mode, that's one of the reasons for implementing Dynamic mode. What I've noticed on this website is a light background image with dark TV. I'm working on some improvements of background image modification, we will see if it helps here. But for Filter mode the only solution is to write selectors in config.

**Comment by logical-and** [comment]
I've noticed custom rules works fine now - no need to apply once more and once more and repeat that forever. Thank you - I definitely should donate you for you hard work and one of that recent great updates :)
Btw, a suggestion - could you guys integrate the plugin in Slack - by hardcode or something. It's chrome based app

**Comment by marcelpaulo** [comment]
This is working flawlessly with the Dynamic engine.
