### ISSUE TITLE
[BUG] no icon in Chrome 86

### ISSUE THREAD

**Issue by mariusa** [darkreader/darkreader#3863]
### **Describe the bug**

Using  Chrome 86, first time I installed this extension. There's no extension icon in the upper-right toolbar. Most other extensions have an icon there. 
I've also restarted the browser.

### **Steps to reproduce**

- Install extension in Chrome 86
- Navigate to sites, background is dark
- There's no extension icon

### **Expected behavior**

Have an extension icon

### **Screenshots**

![Screenshot from 2020-10-15 22-22-59](https://user-images.githubusercontent.com/1283842/96176413-023a7180-0f35-11eb-85ac-c8f25b9ba4c5.png)

### **System Information:**
 - OS: Fedora
 - Browser: Chrome 86
 - Since yesterday (don't know how to see it)

**Comment by Gusted** [comment]
Hi @mariusa!

Could you press on the first icon left of your profile picture? It's a new feature of Google Chrome. 

Regards,
Gusted

**Comment by mariusa** [comment]
Thanks for the quick reply! I don't see it there either :(

![Screenshot from 2020-10-15 22-29-27](https://user-images.githubusercontent.com/1283842/96177054-f1d6c680-0f35-11eb-9381-91cab020c318.png)

**Comment by Gusted** [comment]
Could you try reinstall it? This is totally the browser handling the icon to be in the toolbox. So I'm not sure what caused this as hiding a icon isn't possible due to security reasons.

**Comment by mariusa** [comment]
Argh, I disabled it after seeing no way to turn it off on some sites. It does show there now! Thank you so much for your kind help :)
