### ISSUE TITLE
Firefox 81.0.2 Says that Dark Reader is slowing the browser down

### ISSUE THREAD

**Issue by Quizicalgin** [darkreader/darkreader#3870]
As the title says, firefox shows the little yellow drop down with the message that Dark reader is causing the browser to slow down with the webpage being very slow to load for a moment before popping in.  The message is only there for a moment so if it has some other means of telling me what is wrong from the dialogue box I wouldn't know. It comes up the most on youtube and gmail, but the pop up alert has shown up on other sites as well, just not as consistently.

**Comment by Gusted** [comment]
Hi @Quizicalgin!

Could you capture a profile trough the [Built-in profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Reporting_a_Performance_Problem) and share the link?

Regards,
Gusted

**Comment by Quizicalgin** [comment]
https://share.firefox.dev/2T5ctUY

Here ya go, recorded it refreshing the youtube page.

**Comment by Gusted** [comment]
Hi @Quizicalgin!

Thank you for sharing the profiler link, because of that I could opened up 2 PR's(#3873 #3874) that should optimize 2 logic used in Dark Reader that probably(high chance) caused this slow down and showed the Dark Reader was slow message.
Thank you once again for opening this bug report!

Regards,
Gusted

**Comment by Quizicalgin** [comment]
Woot woot!

**Comment by Gusted** [comment]
Hi @Quizicalgin!

And so 5 days later #3873 and #3874 was merged. Those optimizations are included in the next release(no ETA), thanks once again for opening this issue!

Regards,
Gusted

**Comment by Quizicalgin** [comment]
Sure thing! I'm glad it was something that was fixable! Hopefully firefoxe's next update doesnt break something else. . w. ;

**Comment by Gusted** [comment]
> Hopefully firefoxe's next update doesnt break something else. . w. ;

Small chance, however mostly it's fixable within 24 hours when reported.
