### ISSUE TITLE
[Feature Request] Custom theme for Light and Dark modes

### ISSUE THREAD

**Issue by lxgreen** [darkreader/darkreader#3882]
**Is your feature request related to a problem? Please describe.**
I'd like to use Solarized Dark and Solarized Light Firefox themes in Dark and Light modes, respectively. Currently, the Dark Reader allows to apply custom browser theme accordingly to the mode, but these themes are not customizable. 

**Describe the solution you'd like**
It would be nice if we had 2 more settings:
Light Mode Theme: _____ 
Dark Mode Theme:  _____

**Comment by Gusted** [comment]
Hi @lxgreen!

Please check the new design.
Open the popup. 
Click on devtools.
Click on Preview new Design

See that under `See all Options` > `Colors` you can modify the colors. As for the buttons you suggested #2876 

Regards,
Gusted

**Comment by lxgreen** [comment]
I actually mean the browser theme rather color customization -- the appearance of tabs, toolbars, etc. I'm using [two](https://addons.mozilla.org/en-US/firefox/addon/solarized-dark-afraidofmusic/) [themes](https://addons.mozilla.org/en-US/firefox/addon/winetys-solarized-light/) for Firefox with [this](https://addons.mozilla.org/en-US/firefox/addon/automatic-dark/) addon which switches them automatically. I think the Dark Reader could handle this, as it exactly fits its purpose.

**Comment by Gusted** [comment]
Under settings of the new Design
![](https://i.imgur.com/udbRljs.png)
