### ISSUE TITLE
[Broken Website] Math on wikipedia (Firefox only)

### ISSUE THREAD

**Issue by wyphan** [darkreader/darkreader#3885]
**Website**
Any page with both svg diagrams and math, for example [this one](https://en.wikipedia.org/wiki/Mandelstam_variables)

**How to Reproduce**
> 1. Go to Wikipedia
> 2. Find a technical article in mathematics or physics
> 3. Change modes as needed

**Expected behavior**
Both math and diagrams are rendered and/or inverted properly in Dark mode.

**Actual behavior**
Depending on mode, either the math equations or the svg diagrams (but not both at the same time) are unreadable.

**Screenshots**

Side-by-side comparison of Firefox and Chromium, both in Filter+ mode
![Screenshot from 2020-10-20 13-47-37](https://user-images.githubusercontent.com/50928756/96624930-7715fe80-12db-11eb-888f-251ebc85f91d.png)

Firefox in Static mode
![Screenshot from 2020-10-20 13-48-05](https://user-images.githubusercontent.com/50928756/96625038-a0cf2580-12db-11eb-97a0-8e9438172f0c.png)

**System info:**
 - OS: Ubuntu Linux 20.04.1 LTS x86_64
 - Browser: Firefox 81.0.2+build1-0ubuntu0.18.04.1
 - Darkreader Version: 4.9.21

**Comment by Gusted** [comment]
Hi @wyphan!

I couldn't reproduce the issue in Firefox for Filter(+) mode, do you have by any chances modified the dev tools?
Also for Static isn't any support as it's supposed for the user itself tinker CSS together.

Regards,
Gusted

**Comment by wyphan** [comment]
I think I did, when I was trying to tinker with #2485 . How do I reset my settings?

**Comment by Gusted** [comment]
![](https://i.imgur.com/I1G34Yd.png) use the Reset button inside the Dev Tools.

**Comment by wyphan** [comment]
Hmm, I clicked on "Reset" but it doesn't do anything for me. Let me test with a virtual machine using a live Ubuntu session.

**Comment by Gusted** [comment]
To reset the full settings, maybe it will help on your current installation.
Enable new design under Dev tools.
Go to Settings -> Manage Settings -> Reset Settings.

**Comment by wyphan** [comment]
@Gusted Weird, it still doesn't work for me, even after clicking "Reset Settings". Maybe I need to manually update `inversion-fixes` file to newest version from GitHub?

Just now I also tested with a fresh new Firefox profile using `firefox -P` from the terminal, where the page is displayed normally, like in the virtual machine.

**Comment by Gusted** [comment]
>  Maybe I need to manually update inversion-fixes file to newest version from GitHub?

Settings -> Manage Settings -> Syncronize Site fixes.
Force quit(So the extension gets for sure a fresh copy of the site fixes) Firefox and re-open it.
