### ISSUE TITLE
[BUG]: Firefox new tab/Pocket stories page no longer dark

### ISSUE THREAD

**Issue by tustinn** [darkreader/darkreader#3888]
### **Describe the bug**

Firefox new tab/Pocket stories page no longer dark

### **Steps to reproduce**

-click new tab function on Firefox browser
-displays "pocket" stories tiles

### **Expected behavior**

-display with dark reader settings

### **Actual behavior**

-displays in default background (not dark)

### **Screenshots**
![image](https://user-images.githubusercontent.com/23008966/96667564-27045f80-130e-11eb-91e1-d1daa2791b38.png)

### **System Information:**

 - Browser: [Firefox 82.0 (64-bit)]
 - Dark Reader version: [4.9.21]

### **Additional context**

-used to work with previous version of Firefox before it was updated

thank you!

**Comment by Gusted** [comment]
Hi @tustinn!

Do you have the site disabled or any other custom settings for this? As a fresh setup of getpocket seems to work for me ![](https://i.imgur.com/4rtGMVk.png)

Regards,
Gusted

**Comment by tustinn** [comment]
Hello, Gusted!  Thanks for responding.  Sorry for the confusion.  It works if I'm logged into the GetPocket site, but not if I am not.  To clarify, the Firefox Homepage and new windows or (New tabs) if set to blank or set to Firefix Home (Default) no longer show dark.  Does the Firefox home page (if set to Firefox default) show dark for you?  Thank you!

**Comment by Gusted** [comment]
> Does the Firefox home page (if set to Firefox default) show dark for you? Thank you!

I have some custom CSS so yes... But Dark Reader has native browser theme. Do you have under the tab `more` ![](https://i.imgur.com/gq8rtZ5.png) Custom Browser Theme enabled?
