### ISSUE TITLE
[BUG] settings import doesn't work

### ISSUE THREAD

**Issue by DAmNRelentless** [darkreader/darkreader#3899]
### **Describe the bug**
I recently switched from Brave to Opera GX and installed Dark Reader.
Because I had a lot of sites excluded from the Dark Reader, I wanted to import my settings. So I enabled the preview for the new design and exported my settings.
When I try to import these settings in my Opera GX Dark Reader, it simply does nothing. No settings are applied, no sites are imported. Just nothing, not even a message.

I tested the file on a website to make sure it's valid JSON and it is. All the information in the JSON file are correct and even the sites are listed, the import just doesn't work.

### **Steps to reproduce**
- open another browser and exclude some sites from the dark reader
- export the settings as JSON
- go to your current browser and try importing the settings

### **Expected behavior**
I'd say it should import the settings and add the sites from my old configuration.

### **Actual behavior**
It does nothing at all.

### **System Information:**
 - OS: Windows 10 64bit 2004
 - Browser: Opera GX LVL2 (core: 71.0.3770.287)
 - Dark Reader version: 4.9.21

**Comment by Gusted** [comment]
Hi @DAmNRelentless!

It seems like another issue that when the File Dialog has opened that the extension gets closed by Opera. Whereby when you open the settings-file. The code that is supposed to run isn't getting executed, I will look for a work-around.

Regards,
Gusted

**Comment by Gusted** [comment]
Closing in favor of #3927 (more activity + discussion)
