### ISSUE TITLE
[Broken Website] Google Sheets in Firefox

### ISSUE THREAD

**Issue by Vicharian** [darkreader/darkreader#3900]
**Website**
Google sheets - https://docs.google.com/spreadsheets

**How to Reproduce**
1. type a formula in a cell
2. Look at the formula bar

**Expected behavior**
Text should be contrasted with the dark background

**Actual behavior**
Text color is black

**Screenshots**
This is how is shows in Opera/Chrome
![image](https://user-images.githubusercontent.com/7212636/96754990-f3195080-1386-11eb-9b6d-8e589a9339a0.png)

And this is how it is in Firefox
![image](https://user-images.githubusercontent.com/7212636/96755095-19d78700-1387-11eb-8f8f-f8b94b16752c.png)

**System info:**
 - OS: windows
 - Browser: firefox

**Comment by Gusted** [comment]
Hi @Vicharian!

Are you using Filter(+)? Or Dynamic?

Regards,
Gusted

**Comment by Vicharian** [comment]
Gusted, Thanks for your comment. Please tell me how I can find that out?

**Comment by Vicharian** [comment]
I just realized that those are Dark Reader settings not browser settings.

I am using Dynamic. Filter+ fixed the Google sheet. However, Github went dark so have changed the setting to be Filter+ just for Google.
