### ISSUE TITLE
adaptive to day and night time [Feature Request]

### ISSUE THREAD

**Issue by wojosc** [darkreader/darkreader#3901]
Wouldn't it be cool if we where able to set a day and night time in the add-on to auto-switch?

**Comment by Gusted** [comment]
Hi @wojosc!

Please follow the following steps

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And then

    Click Dark Reader icon.
    Click Settings.
    Click Automation.

You can use your latitude/latitude to dynamically get the day/night time or the active hours.

Regards,
Gusted

**Comment by wojosc** [comment]
Thanks @Gusted 

Here some pictures for future queries on the matter :)
![image](https://user-images.githubusercontent.com/22279621/97045359-ea3aa180-1575-11eb-96c8-df8057b6f91b.png)

Choose according to requirement:
![image](https://user-images.githubusercontent.com/22279621/97045447-0b02f700-1576-11eb-8a71-d9fc4c086996.png)
