### ISSUE TITLE
[Feature Request] Apply different filter settings for domain and subdomain

### ISSUE THREAD

**Issue by SJNBham** [darkreader/darkreader#3912]
It would be great to have the option of treating subdomains differently than their parent domains when using the "Only for _subdomain_" option. Not just for dark/light mode, but for the type of filtering. We have some websites where the top-level domain needs to be dynamic and a subdomain needs to be static. 

Also, is there a way to achieve this using configuration files - even if it's not possible through the GUI yet?

Thanks for considering this enhancement!

**Comment by Gusted** [comment]
Dup #3359

**Comment by SJNBham** [comment]
Hi @Gusted,

I read through ticket #3359 before submitting this one, but I couldn't readily discern if it included allowing the application of different filtering settings for subdomains vs. top-level domains. So being able to accomplish the following using the GUI (or configuration files):

domain.com (Static filter)
subdomain.domain.com (Dynamic filter)
subdomain2.domain.com (no filtering - not inverted)

**Comment by Gusted** [comment]
Hi @SJNBham!

The issue I chose for duplicate might not seems like the same, but the underlying issue that dark reader can't tell the difference between a normal domain and a sub domain of it. This will be fixed by #2517. that use the function used by the "Only for".  Also I just tested it, but it seems to work for me. It might be that I use the new design 

To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.


Regards,
Gusted

**Comment by SJNBham** [comment]
I tried toggling over to the new user interface but see the same behavior. The domains I'm using are:

domain.org (set to Static)
subdomain.domain.org (set to dynamic)
subdomain2.domain.org (set to dynamic)

Whatever domain.org is set to, the subdomains inherit.

Hopefully, #3359 will resolve it.

Thanks for the explanation.

**Comment by Gusted** [comment]
Hi!

Woops, seems like I didn't properly tested my theory.  So...
Export the settings `Settings -> Manage Settings -> Export Settings`.
Open the file and locate the customTheme. And than the url that defines the main domain.
Change that url e.g. `domain.org` -> `^domain.org`  this will Tell dark reader to match this url that STARTS with domain.org and will left out the subdomains. **SAVE THE FILE**
`Settings -> Manage Settings -> Import Settings`. Poof it should hopefully work.

**Comment by SJNBham** [comment]
@Gusted - brilliant! That did the trick. Thank you ;)
