### ISSUE TITLE
[BUG] Github.com | comment box

### ISSUE THREAD

**Issue by Gusted** [darkreader/darkreader#3914]
### **Describe the bug**

The comment box's background-color is currently controlled trough a inline variable as shown in the screenshot.
Currently Dark Reader isn't styling this.

### **Steps to reproduce**

- Just scroll down in this issue and check the comment box. Might be some A/B testing as I noticed this bug this morning already on my mobile(Firefox Beta |  DR 4.9.21) and no one reported it yet.

### **Expected behavior**

Dark Reader should style it. e.g. adding support for inline variables? #3100

### **Actual behavior**

A clear and concise description of what actually happened.

### **Screenshots**

![](https://i.imgur.com/90vlc5e.png)

### **System Information:**
 - OS: Windows 10
 - Browser:  Brave | 1.16.62 Chromium: 86.0.4240.80
- Dark Reader version: 4.9.21

### **Additional context**

~I think my PR #3100 was to fix this issue with some other site. Not sure will update this when know for sure.~
That was definetly another issie, so #3915

**Comment by Gusted** [comment]
Nope it wasn't #3100 who fixed this, that's another issue for another day.

I've made up a PR(#3915) to fix this problem.
![](https://i.imgur.com/Sj331ES.png)

Regards,
Gusted

**Comment by zemse** [comment]
I'm facing this too on Safari, maybe some recent changes made by GitHub. I hope if an update gets pushed to Safari soon. Because staying with a look like this for long is horrible. Please @Gusted can you try getting the update on Safari store? 🙏

![Screenshot 2020-10-24 at 6 51 42 AM](https://user-images.githubusercontent.com/22412996/97064694-79bb7100-15c5-11eb-9666-1c215bf85278.png)

**Comment by Gusted** [comment]
> maybe some recent changes made by GitHub.

It is.

> Please @Gusted can you try getting the update on Safari store? 🙏

I don't do the pushing of extension to the extension stores and Safari has another codebase and not this one.

Regards,
Gusted

**Comment by saschanaz** [comment]
Note that this also affects previews:

![image](https://user-images.githubusercontent.com/3396686/97087243-eddb3080-1628-11eb-88c7-edaf60d79f5a.png)

![image](https://user-images.githubusercontent.com/3396686/97087246-f469a800-1628-11eb-9329-2b6d2d467728.png)

**Comment by Gusted** [comment]
It seems that this will be fixed Next week as it require code review for #3915. And as well a new Update pushed to the extension stores. So... Here is a simple work around, take your favourite CSS Editor e.g. stylus or Dark Reader Dev Tools. And insert this beauty.
```CSS
:root {
    --color-previewable-comment-form-bg: #181a1b !important;
}
```

Regards,
Gusted

**Comment by zemse** [comment]
Thanks so much @Gusted for the work around. In case of Safari, I had to buy another [extension](https://apps.apple.com/us/app/cascadea/id1432182561?ls=1&mt=12) to add the above code that fixed this for me and it looks good now.

**Comment by Gusted** [comment]
Update extension to 4.9.22

**Comment by Andre601** [comment]
Something I want to point out is the fact, that even with #3915 not merged (yet) is this issue gone for me, while the other issue of random light-grey text areas/fields appeared (As I'm writing this does this issue not show any of those boxes which is quite surprising and weird)

I doubt this may also fix this current issue? If not, is there a fix planned for this, as it looks and feels very odd.
I talk about #4182 to be precise...

**Comment by Gusted** [comment]
> Something I want to point out is the fact, that even with #3915 not merged (yet) is this issue gone for me, while the other issue of random light-grey text areas/fields appeared (As I'm writing this does this issue not show any of those boxes which is quite surprising and weird)

#3931 did the trick for now.

>  doubt this may also fix this current issue? If not, is there a fix planned for this, as it looks and feels very odd.
I talk about #4182 to be precise...

Nope, that's unfortunate another issue whereby no known good fix for inside the Dark Reader code is known.
