### ISSUE TITLE
[Broken Website] MDN example output is killed

### ISSUE THREAD

**Issue by saschanaz** [darkreader/darkreader#3918]
**Website**
The link of the broken website https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color

**How to Reproduce**
1. Open the above link
2. See whether the output box exists inside HTML Demo box.

**Expected behavior**
The box should exist

**Actual behavior**
It does not

**Screenshots**

![image](https://user-images.githubusercontent.com/3396686/97087212-a785d180-1628-11eb-8ae9-3a626f5e8419.png)

**System info:**
 - OS: Windows
 - Browser: Firefox 82/84
 - Darkreader Version: 4.9.21
 
**Additional context**

**Comment by Gusted** [comment]
Hi @saschanaz!

This seems to be caused by a internal Error of MDN itself. Only they can resolve this issue.
![](https://i.imgur.com/X3HPUjs.png)

Regards,
Gusted
