### ISSUE TITLE
[Feature Request] Click Darkreader icon to toggle dark mode.

### ISSUE THREAD

**Issue by drmirk** [darkreader/darkreader#3920]
Right now when we press Darkreader icon, it shows a menu. From there we can choose to on/off dark mode. This menu also shows other options like, brightness-contrast etc.

What I am proposing is:
- Pressing icon would toggle dark mode. 
- Right clicking would give us the settings/customization menu. (uBlock Origin or DownThemAll implemented this type of behavior)

**Comment by Gusted** [comment]
Hi @drmirk!

> Right clicking would give us the settings/customization menu. (uBlock Origin or DownThemAll implemented this type of behavior)

So far I can see and know this isn't even possible override the right click behavior. 

Regards,
Gusted

**Comment by drmirk** [comment]
Hello @Gusted , Right clicking gives me this. If you are sure not possible, then please close this issue.

![dark](https://user-images.githubusercontent.com/18001314/97092706-edae5580-1667-11eb-9be0-c1cf6b4fe8b9.png)

**Comment by Gusted** [comment]
Both extension has as left click the function to open the Pop Up and as Right click to open some context menu. Many people expect this. And as the right click is a context menu and can't be overridden to be some action this is unfortunately not possible.
