### ISSUE TITLE
[Broken Website] https://youtube-dl.org

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#3923]
**Website**
https://youtube-dl.org/

**How to Reproduce**
An example of this is
> 1. Go to x site
> 2. Observe that text is unreadable.

**Expected behavior**
Text is readable with darkreader on.
Body is inverted in colour

**Actual behavior**
Text changes to white and becomes unreadable with darkreader on.
Body colour not changed

**Screenshots**
Off:
![image](https://user-images.githubusercontent.com/22572406/97097401-e0ff2100-16aa-11eb-9e30-912c20f1ad7d.png)
On:
![image](https://user-images.githubusercontent.com/22572406/97097403-e78d9880-16aa-11eb-973a-d4599516a969.png)

**System info:**
 - OS: Windows
 - Browser: Firefox 82.0
 - Darkreader Version: 4.9.21

**Comment by jaydensar** [comment]
Looks just fine for me, Firefox 83.0b3, Dark Reader 4.9.21
![](https://i.jaydensar.net/frE3g9HBzf.png)

**Comment by nathanielcwm** [comment]
I believe I tested on Firefox 82 not 100% tho.

**Comment by nathanielcwm** [comment]
Firefox 82 on Linux:
![image](https://user-images.githubusercontent.com/22572406/97097946-325ede80-16b2-11eb-9991-1388e9eaecb5.png)

**Comment by Gusted** [comment]
Hi @nathanielcwm!

Looking at your screenshot it seems that the background-image wasn't inverted, this could be a temporarily thing. As in your next screenshot(comment above me), it seems to work again. Does this issue still persist?

Regards,
Gusted

**Comment by nathanielcwm** [comment]
Just checked and it still persists on Windows.

**Comment by Gusted** [comment]
Any errors in console?

**Comment by Gusted** [comment]
Update to 4.9.23
