### ISSUE TITLE
consider more of the URI path in whitelist 

### ISSUE THREAD

**Issue by joe1970** [darkreader/darkreader#3930]
I try to get google search darkened, but leave google maps out. I use the whitelist for darkening. If I add google.com to the whitelist it darkens a google search well, but also goggle maps, which has the URI "www.google.com/maps"

It seems that I can only set black and whitelists per site. It would be great if I could specify further parts of the URI path that should be considered. 

I also noticed that I can either use a whitelist or a  blacklist. If would be great if I can use both in parallel. for example put google.com on the whitelist and then google.com/maps on the blacklist. This means I want google.com darkened with the exception of google.com/maps

**Comment by Gusted** [comment]
Dup #373
