### ISSUE TITLE
[Feature Request] Allow for disabling the extension on a single site basis.

### ISSUE THREAD

**Issue by busti** [darkreader/darkreader#3932]
Currently it is only possible to set the extension to dark or light mode on a single site basis, or to disable it globally.  
This request is for a feature where it would be possible to disable the extension for a single site.

**Is your feature request related to a problem? Please describe.**
Some University internal websites do not work well with dark mode and setting them to light mode still retains some annoying artifacts which are not present in the default style.

**Describe the solution you'd like**
Introduce a third state additional to the "dark" and "light" states called "default". This state can be applied to a single site by activating the "only for example.com" toggle first.

**Comment by Gusted** [comment]
Hi @busti!

What's wrong with toggle of the site?
![](https://i.imgur.com/HOu6lJE.png)

**Comment by busti** [comment]
Ah, how could I overlook that, in hindsight it's really obvious... Thanks :)
