### ISSUE TITLE
[BUG] Certain icons/images stopped showing in Dynamic mode

### ISSUE THREAD

**Issue by albicant** [darkreader/darkreader#3935]
On multiple computers using Firefox, in Dynamic mode icons/certain images are no longer visible - they appear black on black, such as the menu bar in Gmail, the menu bar on Bitbucket, etc. Previously, these used to show white on black, thus they were visible - now they're just black on black, and are not visible at all.

Please fix this issue as it makes using Dynamic mode impossible now because I can't see what I'm clicking on. It worked perfectly before and suddenly stopped working today.

**Comment by Gusted** [comment]
Use the template for bug reports. Invalid
