### ISSUE TITLE
[BUG] Icons/images invidible in Dynamic mode (black on black)

### ISSUE THREAD

**Issue by albicant** [darkreader/darkreader#3936]
### **Describe the bug**

On multiple computers using Firefox, in Dynamic mode icons/certain images are no longer visible - they appear black on black, such as the menu bar in Gmail, the menu bar on Bitbucket, etc. Previously, these used to show white on black, thus they were visible - now they're just black on black, and are not visible at all.

Please fix this issue as it makes using Dynamic mode impossible now because I can't see what I'm clicking on. It worked perfectly before and suddenly stopped working today.

### **Steps to reproduce**

- Open Gmail using Dynamic mode Dark Reader
- Click to open to compose new email
- See the menu bar in the Draft and see that it shows as black on black and is not visible

- Go to '...'
- Click on '...'
- Scroll down to '...'

### **Expected behavior**

Menu bar and icons should be white on black

### **Actual behavior**

A clear and concise description of what actually happened.

Menu bar and icons are black on black and thus not visible

### **Screenshots**
<img width="602" alt="Screen Shot 2020-10-26 at 12 55 03 PM" src="https://user-images.githubusercontent.com/28948063/97209629-93f27c00-178a-11eb-8d56-b0c5e09e5e27.png">
<img width="270" alt="Screen Shot 2020-10-26 at 12 55 31 PM" src="https://user-images.githubusercontent.com/28948063/97209665-9e147a80-178a-11eb-8d37-94efeb2ea87e.png">
<img width="82" alt="Screen Shot 2020-10-26 at 12 55 35 PM" src="https://user-images.githubusercontent.com/28948063/97210116-21ce6700-178b-11eb-81b0-00bff325e04b.png">
<img width="79" alt="Screen Shot 2020-10-26 at 12 55 45 PM" src="https://user-images.githubusercontent.com/28948063/97210130-24c95780-178b-11eb-95ae-7cb42e321a54.png">

 

### **System Information:**
 - OS: macOS 10.14.6
 - Browser: Firefox 81.0.2 (64-bit)
 - Dark Reader version: 4.9.22

**Comment by alexanderby** [comment]
An update v4.9.23 is now available, check it out.
