### ISSUE TITLE
[BUG] Security Error: Content at moz-extension.. may not load data from blob..

### ISSUE THREAD

**Issue by S-ed** [darkreader/darkreader#3939]
### **Describe the bug**

XSS security issue (or some newly imposed security rules)

### **Steps to reproduce**

- Go to Soundcloud
- Enable dark theme
- Look in console

### **Expected behavior**

No errors, all elements loaded

### **Actual behavior**

Some elments are not loaded.

> Security Error: Content at moz-extension://8c54e3fe-58da-4a4e-bac2-9056538884ca/ may not load data from blob:https://soundcloud.com/f149d59f-c4dc-4af1-bfa1-8a36b01a5ac0.

That blob is PNG for Control buttons.

### **Screenshots**
![screenshot 1603755370](https://user-images.githubusercontent.com/3008353/97239955-f20c7700-17fd-11eb-8abd-647c3d51fad5.png)
![screenshot 1603755359](https://user-images.githubusercontent.com/3008353/97239953-f173e080-17fd-11eb-8bc3-5b61fa5582cb.png)

![screenshot 1603756228](https://user-images.githubusercontent.com/3008353/97240422-4c5a0780-17ff-11eb-9f63-cf0a14f31f06.png)

### **System Information:**
 - OS: Windows 10 2004
 - Browser: Firefox 82
 - Dark Reader version: 4.9.22

### **Additional context**

Not sure if the settings for XSS are changed in my profile. But I've also tested on my Firefox Dev that has version 75 and no customized profile. So I assume it's the DarkReader that's the same on both.

**Comment by unbeatable-101** [comment]
#3936

**Comment by alexanderby** [comment]
Duplicate of #3936, seems like Firefox bug. We've submitted an update, it is under review.

**Comment by alexanderby** [comment]
An update v4.9.23 is now available, check it out.
