### ISSUE TITLE
Dynamic Theme mode bug on https://www.opennet.ru

### ISSUE THREAD

**Issue by Kerrung** [darkreader/darkreader#394]
For example:
https://www.opennet.ru/opennews/art.shtml?num=48487

White unreadable text on the white background.

![screenshot from 2018-04-24 22-33-44](https://user-images.githubusercontent.com/36989404/39203900-9792711e-480f-11e8-8170-c5be4e824742.png)

**Comment by risualiser** [comment]
Also, there is the same bug with black text on black bg on some pages, which appear both in Static and Dynamic modes.
Example: http://ipiranlogos.com/systems/hunt_1.htm

**Comment by Kerrung** [comment]
Thank you! Fixed for me!

**Comment by risualiser** [comment]
New update is great!
![](https://i.imgur.com/drc3hN9.png)
