### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by Shaurya-Kalia** [darkreader/darkreader#3942]
**Website**
gmail.com

**How to Reproduce**
> 1. Go to gmail.com and log in
> 2. Click on compose button. A window to compose a message appears
> 3. Check the buttons in bottom of compose window

**Expected behavior**
Buttons are white against dark background

**Actual behavior**
Buttons are dark or not visible at all

**Screenshots**
![Screenshot_20201027_132124](https://user-images.githubusercontent.com/6441797/97272293-b0a8b580-1857-11eb-9aff-48123dfa67c6.png)

**System info:**
 - OS: [Linux]
 - Browser: [Firefox 84]
 - Darkreader Version: [4.9.22]
 
**Additional context**

**Comment by Gusted** [comment]
Dup #3939
