### ISSUE TITLE
[Broken Website] GitHub Text boxes are broken

### ISSUE THREAD

**Issue by Andre601** [darkreader/darkreader#3948]
**Website**
https://github.com (Mainly any comment boxes)

**How to Reproduce**

1. Go to any repository or place, where you can use the text box with markdown (And preview tab)
2. You'll notice a white border around the "Write" tab and complete white on the "Preview" tab.

**Expected behavior**
The box should render dark

**Actual behavior**
"Write" tab has a white border and "Preview" is completely white.

**Screenshots**
Write active
![image](https://user-images.githubusercontent.com/11576465/97369272-e88e1800-18ac-11eb-8d21-2155227b5518.png)

Preview Active
![image](https://user-images.githubusercontent.com/11576465/97369313-fe034200-18ac-11eb-827d-04aa8c1c2bed.png)

**System info:**
 - OS: Windows 10
 - Browser: Microsoft Edge 86.0.662.56
 - Darkreader Version: Version 5 Preview (4.9.20. Please Note that this also happens with the old/current design)
 
**Additional context**
No changes where made towards the used CSS and functions of Dark Reader. The site just suddenly changed like that with no real reason why.

**Comment by Gusted** [comment]
Update to 4.9.23 #3914

**Comment by caneleex** [comment]
@Gusted i'm having the same issue even though i'm running version 4.9.23.

**Comment by Gusted** [comment]
> i'm running version 4.9.23.

Your on microsoft edge? That's still on 4.9.20.

**Comment by caneleex** [comment]
no, i'm running firefox. that's why i said i'm running 4.9.23

**Comment by Gusted** [comment]
You sure it's 4.9.23, Try re-installing and restarting the browser.

**Comment by caneleex** [comment]
![img](https://i.imgur.com/0XqGKbb.png)

yeah i'm sure and i don't feel like reinstalling firefox now, is there anything else i can do to help except reinstalling my browser?

**Comment by Gusted** [comment]
> restarting the browser.

I never mentioned re-installing.

**Comment by caneleex** [comment]
ah sorry, i misread that as trying to reinstall the browser too. is there an option where i can export my settings for pages so i don't lose them when reinstalling?

**Comment by Gusted** [comment]
> ah sorry, i misread that as trying to reinstall the browser too. is there an option where i can export my settings for pages so i don't lose them when reinstalling?

I think it's better to reset Dark Reader's settings in order to get the fix for Github.com 


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.


Ability to import and export settings (click Settings, Manage settings).

**Comment by caneleex** [comment]
reinstalling dark reader has fixed the problem, thanks.

**Comment by Andre601** [comment]
4.9.22 seems to also already having the fix.
The issue was also, that even a re-install of the extension didn't fix it at first (Probs because Edge wasn't having the latest version)
