### ISSUE TITLE
[Dynamic] not working on engadget.com

### ISSUE THREAD

**Issue by joshsleeper** [darkreader/darkreader#395]
Dark Reader `4.2.8`
Firefox `59.0.2`
https://www.engadget.com/

![image](https://user-images.githubusercontent.com/849941/39204747-80519186-47ad-11e8-93b2-15d9c85ea337.png)

**Comment by joshsleeper** [comment]
Oh hey, it's fixed in the latest version!

Nice, thanks so much @alexanderby!!

**Comment by joshsleeper** [comment]
@alexanderby 
aaaaaand it's broken as quick as it was fixed.
it seemed to work properly on `4.3.0` but `4.3.1` is no longer working again.

**Comment by alexanderby** [comment]
Currently it doesn't work because the extension doesn't handle `@import` declarations. Maybe their styles are served from different CDNs and it worked for some time.
