### ISSUE TITLE
Wikipedia issue

### ISSUE THREAD

**Issue by BlackTooths** [darkreader/darkreader#396]
there's a reaaaly big problem with wikipedia
(regular filter mode is working great, its about the dynamic mode as you can see)
check it out:
![1](https://user-images.githubusercontent.com/38706513/39217241-c42a1548-4827-11e8-8775-a2eae42bbf0c.png)

**Comment by alexanderby** [comment]
The reason is inline style, current decision was to use `INLINE` config rule, because analyzing all the elements can impact the performance, but it wasn't well tested well yet, just an assumption.
