### ISSUE TITLE
Is it possible to not invert Firefox Control-F search highlighting in dark mode?

### ISSUE THREAD

**Issue by kstauffer** [darkreader/darkreader#3964]
First, a thousand thanks for making this extension. It makes the web easier on my tired eyes.

To my request: an option to disable Dark Reader's inverting of colors highlighted by Firefox's control-f find.

I set three Firefox about:config entries:
* `ui.textHighlightBackground = #d33682` (Solarized magenta)
* `ui.textHighlightForeground = #fdf6e3` (Solarized base3)
* `ui.textSelectBackgroundAttention = #b58900` (Solarized blue)

That highlights searched-for text as off-white on a magenta background. Incremental searches (search-as-you-type) are highlighted as off-white on blue background. These color combinations are very visible (to my eye) in Dark Reader's light mode. I expect they would be visible in dark mode, too, except that Dark Reader apparently inverts the colors of highlighted search text in dark mode. In dark mode what I get is garish pink-on-white, or blue-on-white for incremental search. Is there a way to globally stop Dark Reader from inverting search highlighting? I poked around the "Dev tools" of Dynamic theme generation, but I didn't see anything that would cause this. (Also didn't see any related issues [even closed ones].)

**Comment by Gusted** [comment]
Hi @kstauffer!

Enable the new design.

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then *(under Theme click See all options, Colors).* set Selection to Default ![](https://i.imgur.com/O73PYae.png)

Regards,
Gusted

**Comment by kstauffer** [comment]
Hm, thanks for the response, but that option controls something else. That changes the color of selected text (click-and-drag with mouse). I'm talking about the color of highlighted text when one searches with control-F.

I'll try to whip up a screenshot.

**Comment by Gusted** [comment]
Oh, their isn't really a option to disable or change that. That's pure Firefox internal code.

**Comment by kstauffer** [comment]
Interesting. What is Dark Reader doing that causes Firefox to think inversion is necessary?

**Comment by Gusted** [comment]
> Interesting. What is Dark Reader doing that causes Firefox to think inversion is necessary?

Changing the color. AFAIK Firefox creates the `highlight` color on what the current color is.
