### ISSUE TITLE
[BUG] Github.com | contribution calendar

### ISSUE THREAD

**Issue by plainheart** [darkreader/darkreader#3967]
**Website**
https://github.com

**How to Reproduce**
> 1. Go to a personal page on GitHub, for example, https://github.com/Gusted
> 2. Look at the contribution calendar panel
> 3. The background of each small box is so bright. It was dark before.

**Expected behavior**
The color won't be so bright and keep dark as it was as before.

**Actual behavior**
The color looks a bit bright.

**Screenshots**
![image](https://user-images.githubusercontent.com/26999792/97514463-ba522a80-19c9-11eb-864e-acfe1c7f4af8.png)

**System info:**
 - OS: Windows 10
 - Browser: Chrome 86.0.4240.111 (x64)
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
Hi @plainheart!

They seems to be switched to variables which wasn't being modified I made a PR(#3977) to fix this.
Thanks for reporting!

Regards,
Gusted

**Comment by plainheart** [comment]
Nice! Thank you for the quick fix. I do appreciate this extension.

**Comment by latipun7** [comment]
Hi @Gusted , I still have this issue (2020/12/1). It's worked few days ago.

![screenshot](https://i.imgur.com/QKjcyjn.png)

**System info:**
- OS: Windows 10
- Browser: Microsoft Edge 87.0.664.52 (Official build) (64-bit)
- Darkreader Version: 4.9.25

**Comment by Gusted** [comment]
Hi @plainheart!

Thanks for the heads-up! I've fixed this with #4340

Regards,
Gusted

**Comment by plainheart** [comment]
@Gusted @latipun7 Thanks a lot!
