### ISSUE TITLE
[Broken Website] www.quora.com

### ISSUE THREAD

**Issue by vasseray** [darkreader/darkreader#3969]
**Website**
https://www.quora.com/

**How to Reproduce**
1. Go to https://www.quora.com/
2. Login to your account
3. Open the home page

**Expected behavior**
The background of the page should be dark all through the length of infinite scroll page.

**Actual behavior**
While background only at the top part of the infinite scroll page. However if you scroll down, the lower part background is dark. 

**Screenshots**
![quora1_LI](https://user-images.githubusercontent.com/73635810/97543814-1473df80-1a0c-11eb-81d0-d9237a1a523c.jpg)
![quora2](https://user-images.githubusercontent.com/73635810/97542433-1046c280-1a0a-11eb-9f02-a848de5b1d2c.JPG)
![quora3](https://user-images.githubusercontent.com/73635810/97542446-1472e000-1a0a-11eb-92b2-dbefb25091b5.JPG)

**System info:**
 - Windows 10 Education 2004 Build 19041.572
 - Browser: Microsoft Edge 86.0.622.51 & Firefox 83.0b5
 - Darkreader Version: 4.9.22 (Edge) & 4.9.23 (Firefox)
 
**Additional context**
1. This error only happens when using "Dynamic" mode in Darkreader. Other modes (Filter, Filter+, etc) run just fine.
2. If you switch to other mode and return back to dynamic mode, the white background will get darkened, but with slightly different color from the rest of the page.
![quora4](https://user-images.githubusercontent.com/73635810/97543386-826bd700-1a0b-11eb-9cb7-ab40b3d77344.JPG)

**Comment by Sevenoni** [comment]
on the side `color: rgb(206, 202, 196);` is being implemented and i think - I'm not sure - it needs to be changed to `rgb(24, 26, 27)` or `--darkreader-neutral-background: #181a1b;` hope this helps .

**Comment by vasseray** [comment]
Thank you, Sevenoni.
I add those lines of code under quora.com entry in the DevsTools and it works now.

`body {
    background-color: var(--darkreader-neutral-background) !important;
}`

I don't know if this is best implementation, though.

![devtools](https://user-images.githubusercontent.com/73635810/97577838-49dff380-1a33-11eb-9128-a07d8b38998b.JPG)

![quorafixed](https://user-images.githubusercontent.com/73635810/97577856-4f3d3e00-1a33-11eb-8012-9b68d9d05195.JPG)
