### ISSUE TITLE
Dynamic theme coloring different first load and reenabling

### ISSUE THREAD

**Issue by txomon** [darkreader/darkreader#397]
I have been using dynamic theme to test it out, and it has weird behaviours in many pages. One of the last one I have caught, is this one:

Go in with dynamic theme activated to https://www.timeshighereducation.com/features/ten-steps-to-phd-failure#survey-answer

Toggle dark mode off

Toggle dark mode on

You will see that the first time looks one way and the next one different.

First time:
![image](https://user-images.githubusercontent.com/228250/39218830-84ad29fe-481e-11e8-8927-0f5c0ad47017.png)

Second and following time:
![image](https://user-images.githubusercontent.com/228250/39218846-97b78c88-481e-11e8-987f-6a11a6b132c4.png)

**Comment by txomon** [comment]
If my opinion counts, I wouldn't recommend switching to dynamic theme as default, but actually encouraging your user base to try out and report on the dynamic theme.

Cheers!

**Comment by alexanderby** [comment]
Dynamic Theme is used for Firefox an Mobile by default because CSS filters often fail to render anything and make phones hot.
