### ISSUE TITLE
[BUG] stuck on loading screen

### ISSUE THREAD

**Issue by baris-inandi** [darkreader/darkreader#3975]
I installed the latest version of Dark reader on Firefox 82.0.2 (Windows 10 Pro 64-bit). When I open the popup, it is stuck on the loading screen. 

The extenstion still works but in an awkward way. Most elements in websites are not visible and in some places the text color is the same with the background, also some containers have light backgrounds on dark text with a weird gold-gray theme. 

I tried removing and reinstalling the extention. I disabled all other extentions and any custom stylesheets just in case they were causing this issue but the it still seems to continue.

**Comment by Gusted** [comment]
Invalid, use the correct Bug Format. Side-note doesn't seem to be anything weird in the specs maybe it could be something in `about:config`
