### ISSUE TITLE
[Broken Website] GitHub contribution graph is now bright

### ISSUE THREAD

**Issue by saschanaz** [darkreader/darkreader#3985]
**Website**
https://github.com/autokagami/

**How to Reproduce**
1. See the contribution graph

**Expected behavior**
White cells should become dark

**Actual behavior**
White cells are still white

**Screenshots**
![image](https://user-images.githubusercontent.com/3396686/97746589-e0bbb700-1aea-11eb-8323-3c19df708b85.png)

**System info:**
 - OS: Windows
 - Browser: Firefox
 - Darkreader Version: 4.9.23
 
**Additional context**
I think this is a regression.

**Comment by Gusted** [comment]
#3967 Dup
