### ISSUE TITLE
Dynamic theme issue with arstechnica.com

### ISSUE THREAD

**Issue by lukechadwick** [darkreader/darkreader#399]
![image](https://user-images.githubusercontent.com/6725655/39220288-0c648ba2-4884-11e8-96cb-253e9dd87874.png)

Images are darkened and those white boxes are supposed to be comment bubbles.

![image](https://user-images.githubusercontent.com/6725655/39220306-322b9ace-4884-11e8-95c7-e06d9d61592b.png)

**Comment by alexanderby** [comment]
The reason is `background-blend-mode: multiply`, so it multiplies dark background color with images colors. I didn't want to add `CSS` rule into Dynamic fixes, but it seems like the only solution.
