### ISSUE TITLE
Support for all websites

### ISSUE THREAD

**Issue by ShinySir** [darkreader/darkreader#400]
some website just destroyed it so needs support

**Comment by Saucistophe** [comment]
@ShinySir, you need to describe symptoms, your configuration (Static? Dynamic?) and the websites where this happens. Also have a look at the project's readme for clues as of what to report and how to fix some trivial problems.

**Comment by alexanderby** [comment]
@ShinySir There is endless count of ways to style web pages. The more fixes we provide for some sites, the more chance is the same fixes will work for other sites.

**Comment by lacostenycoder** [comment]
Here's example of site that's not working and lately i'm finding more and more.  I will post here as I find them.

https://www.digitaltrends.com/computing/how-to-disable-cortana/

Is there a reason we cant use a basic javascript invert as a fallback?

I have a bookmarklet on my chrome that I have not used in a long time but have been using more and more lately because the chrome extension has been not working:

```javascript

javascript: (function() {
	var css = 'html {-webkit-filter: invert(100%);' + '-moz-filter: invert(100%);' + '-o-filter: invert(100%);' + '-ms-filter: invert(100%); }';
	var head = document.getElementsByTagName('head')[0];
	var style = document.createElement('style');
	if (!window.counter) {
		window.counter = 1;
	} else {
		window.counter++;
		if (window.counter % 2 == 0) {
			var css = 'html {-webkit-filter: invert(0%); -moz-filter: invert(0%); -o-filter: invert(0%); -ms-filter: invert(0%); }'
		}
	}
	style.type = 'text/css';
	if (style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		style.appendChild(document.createTextNode(css));
	}
	head.appendChild(style);
}());
```

**Comment by lacostenycoder** [comment]
Update, I just tried using static and dynamic filter settings and it seems to work now at least for the link I posted in previous comment

**Comment by alexanderby** [comment]
I know what's the reason. Versions below 4.3.3 require that there is some `REMOVE BG` or `CSS` in `*` inversion fixes config section. The fix should be applied within 15 minutes.
