### ISSUE TITLE
[Dynamic] Google Sheets

### ISSUE THREAD

**Issue by qubitz** [darkreader/darkreader#402]
![darkreader](https://user-images.githubusercontent.com/15070724/39231203-2873a3fc-481e-11e8-89aa-cc57411fa4c9.PNG)

Is it intentional to leave the cells white? Filter or Filter+ works great with Sheets, but it would be nice not to have to switch from Dynamic to Filter+ and back again. Also the some of the toolbar icons are also not toggled.

P.S. Just switched to Dynamic today and let me say WOW! It's freaking amazing.
Double P.S. I accidentally hit enter while typing the title of this issue *facepalm*

**Comment by krupenja** [comment]
No longer reproducible with Dynamic theme.

**Comment by alexanderby** [comment]
It introduced another problem with saving cells colors, but the initial issue described here was fixed.
