### ISSUE TITLE
[Feature Request] Please provide an option to NOT darken sites by default

### ISSUE THREAD

**Issue by ameaninglessname** [darkreader/darkreader#4021]
I wanna turn on this extension but don't want it darken every site I opened right now.
(Extension is turned on, but it's functionality has not started yet.)

I just wanna darken several specific sites. (I wanna toggle them choose manually)
Because darken tens of sites would make the whole performance impacted.

**Comment by Gusted** [comment]
Hi @ameaninglessname!

Enable Invert listed only under Sitelist ![](https://i.imgur.com/wQqP8HU.png)

Regards,
Gusted
