### ISSUE TITLE
[Feature Request] Default setting to have disabled on site

### ISSUE THREAD

**Issue by binaryPUNCH** [darkreader/darkreader#4039]
I'm really surprised this doesn't seem to be possible in DarkReader today... You can't tell DarkReader to be disabled by default for all sites, except for the ones you whitelist.

I only want to use Darkreader on a handful of sites, but as it is now, I have to constantly enable/disable DarkReader as a whole, which is super annoying. 

When I browse the web and visit sites I've never been to before, I don't want DarkReader to do anything... But then I need to turn off DarkReader entirely. And remember to turn it back on when I'm e.g. on YouTube or Google.

Could there please be a default behavior setting?

**Comment by Gusted** [comment]
Dup #4021

**Comment by binaryPUNCH** [comment]
Thanks. I was about to close this myself after noticing that feature.
