### ISSUE TITLE
Dynamic Mode - Blender wiki not Inverted

### ISSUE THREAD

**Issue by sonicdee** [darkreader/darkreader#404]
Blender Wiki is not converted at all with dynamic mode

see:
https://wiki.blender.org/index.php
or deeplink:
https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Nodes/Nodes_Efficiency_Tools

**Comment by alexanderby** [comment]
Looks fine now (v4.5.6). Soon it will be possible to remove strange backgrounds using Dev Tools.
