### ISSUE TITLE
[Broken Website] microsoftedge.microsoft.com

### ISSUE THREAD

**Issue by kizule** [darkreader/darkreader#4043]
**Website:**
https://microsoftedge.microsoft.com/

**How to Reproduce:**
Go to the website.

**Expected behavior:**
Site should be "dark".

**Actual behavior:**
Site isn't dark.

**Screenshots:**
![image](https://user-images.githubusercontent.com/28963303/98197691-92157f00-1f27-11eb-85f1-16e3e9f75074.png)

**System info:**
 - OS: Windows 10 (20H2 19042.610)
 - Browser: Microsoft Edge 86.0.622.63
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
It's a protected page and therefor can't be styled.
