### ISSUE TITLE
[Broken Website] Quip

### ISSUE THREAD

**Issue by allysunh** [darkreader/darkreader#4045]
**Website**
https://quip-amazon.com/browse

**How to Reproduce**
An example of this is
> 1. Go to Quip
> 2. Create a new document
> 3. Document is white with purple lettering.

**Expected behavior**
Document should be black with white lettering. (was purple but someone opened a ticket for that and I care a lot less about that then it being white)

**Actual behavior**
Document is white with light purple lettering. Side bar is still black like it should be...

**Screenshots**
![image](https://user-images.githubusercontent.com/68342538/98273660-bab16f00-1f4f-11eb-8f37-950faad63d1a.png)

**System info:**
 - OS: Linux (Ubuntu)
 - Browser: Firefox, Chrome
 - Darkreader Version: 4.9.16
 
**Additional context**
I'm in dynamic filtering which was working fine last week. If i swap to filter or filter+ on firefox it makes the screen go black but it works correctly on chrome (black with white lettering).

**Comment by Gusted** [comment]
#3267 Dup
