### ISSUE TITLE
[Broken Website] https://personal.vanguard.com/

### ISSUE THREAD

**Issue by kdchabuk** [darkreader/darkreader#4046]
**Website**
https://personal.vanguard.com/us/funds/snapshot?TTVETF=VETFCNTRL&FundId=0308&FundIntExt=INT

**How to Reproduce**
1. Go to https://personal.vanguard.com/us/funds/snapshot?TTVETF=VETFCNTRL&FundId=0308&FundIntExt=INT
2. See that page is blank.

**Expected behavior**
Page is displayed with dark mode.

**Actual behavior**
Page is blank.

**Screenshots**
![vanguard-dark](https://user-images.githubusercontent.com/11097068/98284148-8e98ec80-1f55-11eb-96c8-630aceae283f.PNG)

**System info:**
 - OS: Windows 10, Ubuntu 18.04
 - Browser: Edge 86.0.622.63, Firefox 82.0.2
 - Darkreader Version: 4.9.22, 4.9.23
 
**Additional context**
This issue occurs even if Dark Reader is switched to "off". The extension must be disabled or removed in the browser in order to view the page.

**Comment by Gusted** [comment]
> I saw a similar issue for https://retirementplans.vanguard.com/VGApp/pe/ContribAlloc.jsf page; this time it only occurs with Dark Reader being “off” at this domain (or the root domain). In addition it seems to be related to `hidePageIfJSdisabled` as well. Shall I file a new issue?
> 
> Note that the link might requires logging in. I can help debugging.

Is it a persistent issue? We most likely want a new issues opened about this.
