### ISSUE TITLE
[Broken Website] Expo Developer Tools QR Code

### ISSUE THREAD

**Issue by educbraga** [darkreader/darkreader#4047]
**Website**

localhost:19002

**How to Reproduce**
An example of this is
> 1. Start expo web from terminal
> 2. Open the given link on the browser
> 3. See that the QR Code has a dark background. This way isn't possible to make a camera recognize it. 

**Expected behavior**
A QR Code with a white background.

**Actual behavior**
A QR Code with a dark background.

**Screenshots**
![Captura de Tela 2020-11-05 às 16 03 59](https://user-images.githubusercontent.com/21699905/98285404-42fc3800-1f81-11eb-961e-be9859b7e2fe.png)

**System info:**
 - OS: MacOS 10.15.7
 - Browser: Chrome 86.0.4240.183
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
Hi @educbraga!

Unfortunately it's a local site and theirfor no fix can be provided/made.

Regards,
Gusted
