### ISSUE TITLE
[Broken Website] Transmission remote Web UI

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#4048]
**Website**

http://localhost:8080/

**How to Reproduce**
An example of this is

1. Launch Transmission remote Web UI.
2. Download a BitTorrent / magnet URI submission to completion, then pause.
3. Pause another BitTorrent / magnet URI submission at 0% complete.
3. Select dark mode (any of the four theme engines).

**Expected behavior**

The progress bars should be distinct between 0% downloaded vs. 100% downloaded.

**Actual behavior**

The contrast is very poor between the two progress bar states.

This happens with all four of the standard theme engines.

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
Hi @mcandre!

Unfortunately it's a local site and theirfor no fix can be provided/made.

Regards,
Gusted
