### ISSUE TITLE
Artifacts in Jira on Dynamic mode

### ISSUE THREAD

**Issue by dliuzzi** [darkreader/darkreader#405]
There seems to be some issue on the new Dynamic mode that causes artifacts on Jira:

|Filter mode|Dynamic mode|
|-----------|------------|
|![Filter](https://user-images.githubusercontent.com/143884/39234090-95193798-4872-11e8-9984-ad5a5043772d.png)|![Dynamic](https://user-images.githubusercontent.com/143884/39234092-98f4044c-4872-11e8-89a5-ef182c440c39.png)|

This does not happen when using the default "Filter" mode.

**Comment by alexanderby** [comment]
This could be a possible fix https://github.com/darkreader/darkreader/commit/12d8253ce8350639298a68a9d28af08521f689cd
Need to check after release

**Comment by dliuzzi** [comment]
I just checked and it still happens, unfortunately. I'm on v4.3.0 if it matters.

**Comment by dflock** [comment]
This is still happening to me using v4.5.3.

**Comment by alexanderby** [comment]
Could you please have a look how it works with version 4.5.6? My free account has expired.

**Comment by dflock** [comment]
Fixed with 4.5.6 :tada:
