### ISSUE TITLE
[Broken Website] New LinkedIn UI has broken contrasts

### ISSUE THREAD

**Issue by kartikcho** [darkreader/darkreader#4053]
**Website**
The link of the broken website: https://www.linkedin.com/feed/

**How to Reproduce**
> 1. Go to LinkedIn feed or any other page on the site.
> 2. Observe.

**Expected behavior**
LinkedIn grooving in dark mode. 🦜 

**Actual behavior**
As evident in the screenshot, much of the navigational text is unreadable along with some icons, etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/48270786/98358270-7061e800-204c-11eb-9d58-a5f32888fb16.png)

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.19

**Comment by Myshor** [comment]
I made 3 fixes for linkedin - all related to dark text and dark icons for dynamic filtering.
