### ISSUE TITLE
[Firefox] about:newtab

### ISSUE THREAD

**Issue by killoid** [darkreader/darkreader#406]
i am using the default built in dark theme in firefox nightly. when using dark reader on firefox nightly, it turns my about:newtab background always white. i have to reapply my dark theme to turn it back.

**Comment by alexanderby** [comment]
I think this is a Firefox bug. There are lots of theme bugs in Firefox, what I can do is to make an option to not override browser theme.

**Comment by killoid** [comment]
bug is solved with the new update of v4.4.0.

**Comment by alexanderby** [comment]
I've placed an option into More tab to enable it, though there is a new bug: the theme doesn't change when you change filter settings.

**Comment by killoid** [comment]
yes can confirm it.

**Comment by alexanderby** [comment]
Fixed in 4.4.1
