### ISSUE TITLE
[Feature Request] Toggle dark mode on only for selected tab.

### ISSUE THREAD

**Issue by szyszak** [darkreader/darkreader#4060]
**Is your feature request related to a problem? Please describe.**
From what I understand there is no way to toggle the dark mode on only for certain open tabs. Clicking the extension icon and toggling on/off works globally and adding a new URL to the site list every time is not an optimal solution. 

**Describe the solution you'd like**
I'd like to be able to toggle the dark mode on only for certain open tabs, with the global default setting being off.

**Comment by Gusted** [comment]
Hi @szyszak!

> and adding a new URL to the site list every time is not an optimal solution.

Could you explain a bit more about this?

**Comment by szyszak** [comment]
Every weekend I open multiple web dev related articles and blog posts from newsletters I subscribe to. They are often hosted on different domains. Adding a new domain every time would be very cumbersome. 
I don't need Dark Reader activated across all the tabs and the theme generating engine slows down by browser.
A perfect solution for me would be to use the ALT+SHIFT+A keyboard shortcut to toggle the Dark Reader ON for current website, while it remains OFF everywhere else. Right now it's the other way around, when you turn on the extension all websites use dark mode and you can toggle it OFF for active tab using mentioned keyboard shortcut.

**Comment by Gusted** [comment]
> A perfect solution for me would be to use the ALT+SHIFT+A keyboard shortcut to toggle the Dark Reader ON for current website, while it remains OFF everywhere else.

That's the exact purpose of the shortcut.

> Right now it's the other way around, when you turn on the extension all websites use dark mode and you can toggle it OFF for active tab using mentioned keyboard shortcut.

Did you try the `Invert listed only` option under the SiteList whereby only sites in the sitelist will be darken.

Regards,
Gusted

**Comment by szyszak** [comment]
> Did you try the `Invert listed only` option under the SiteList whereby only sites in the sitelist will be darken.

That's exactly what I was looking for, thank you very much.
