### ISSUE TITLE
[Broken Website] https://cn.bing.com/

### ISSUE THREAD

**Issue by hgajshb** [darkreader/darkreader#4067]
**Website**
https://cn.bing.com/search?q=donald%20trump&qs=n&form=QBRE&sp=-1&ghc=1&pq=donald%20trump&sc=9-12&sk=&cvid=995CC68332E548738AACC2FF8F523389

**How to Reproduce**
> 1. Go to the site
> 2. move mouse into searchbar dropdown menu
> 3. See that images displayed at top right

**Expected behavior**
No images displayed at top right

**Actual behavior**
Images displayed at top right

**Screenshots**
![image](https://user-images.githubusercontent.com/306685/98501492-57467a80-228a-11eb-9922-6543a68c41ee.png)

**System info:**
 - OS: Windows
 - Browser: chrome
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
Not reproduce-able do you have any other possible extensions?

**Comment by hgajshb** [comment]
> Not reproduce-able do you have any other possible extensions?

Dark reader is the only extension installed. And if I disable it the issue is gone. But you don't get redirected to www.bing.com?

**Comment by Gusted** [comment]
> But you don't get redirected to www.bing.com?

Oh woops I actually do...

**Comment by hgajshb** [comment]
> > But you don't get redirected to [www.bing.com](http://www.bing.com)?
> 
> Oh woops I actually do...

If that's the case will uploading the page source help debugging?

**Comment by Gusted** [comment]
> It could be those rules specified in dynamics theme editor, if I delete those rules about bing.com the isuue is gone.

Any specific rule?
