### ISSUE TITLE
[Broken Website] Not effective on https://saladict.crimx.com/

### ISSUE THREAD

**Issue by liuhao326** [darkreader/darkreader#4070]
**Website**
<https://saladict.crimx.com/> and URL under this website, for example, <https://saladict.crimx.com/manual.html>.

**How to Reproduce**
An example of this is
> 1. Go to <https://saladict.crimx.com/>
> 2. And will find Darkreader will not turn this website to the black theme(or the lighter one).

**Expected behavior**
It should change the background-color of this website(but it can't).

**Actual behavior**
Darkreader can't turn this website to the black theme(or the lighter one). Actually, Darkreader changed the appearance at the moment open the site, but it can't persist.

**Screenshots**

![GIF 2020-11-9 19-31-08](https://user-images.githubusercontent.com/51501079/98536194-52052200-22c2-11eb-836a-0f6987d7569e.gif)

**System info:**
 - OS: [Windows10 x64]
 - Browser: [chrome86.0.4240.183]
 - Darkreader Version: [4.9.22]
 
**Additional context**
Actually, it works well sometimes, but not effective most of the time.

This is a great extension. Thanks a lot!⭐️

**Comment by Gusted** [comment]
Hi @liuhao326!

This issue doesn't seems to happen for me, could you try tuning some settings when your on the site.
What if you enable/disable the site?

Regards,
Gusted

**Comment by liuhao326** [comment]
Hi!👋 @Gusted 

It seems that there is really something wrong with my setting because Darkreaderworks well after I reinstall it. 

But there is another possible issue:

**Website**
<https://saladict.crimx.com/>

**How to Reproduce**
Steps to reproduce the behavior:
An example of this is
> 1. Open a new tab of Chrome
> 2. Input <https://saladict.crimx.com/> into the URL bar and Enter.
> 3. Click the Home button.
       If can't get this issue at the end, try to change the speed of clicking the Home button.
> 4. Click the Back button(will return to <https://saladict.crimx.com/>). Darkreader seems can't recover it to the black theme.


<details>
			<summary><strong>Screenshots</strong></summary>
In order to show what's the mean of "If can't get this issue at the end, try to change the speed of clicking the Home button." I test this two times in this Gif.

As we can see, I test it slowly at the beginning, and I didn't get the issue, but it happened in the second test(faster one).

![back problem4](https://user-images.githubusercontent.com/51501079/98625243-32b1d780-234a-11eb-8bc8-fcf85ce6252a.gif)

</details>

<details>
			<summary><strong>Additional information</strong></summary>


After reproducing this issue, seems that will be more likely to encounter other errors on this website. For example, after I test for several times:

![back problem6](https://user-images.githubusercontent.com/51501079/98627513-64796d00-234f-11eb-85f8-75062aace2e1.gif)

</details>

**Comment by Gusted** [comment]
Can't reproduce also this can happen when the browser is getting a full load e.g. going back and forth between website.

**Comment by liuhao326** [comment]
I don’t think this really matters either. Thanks!
