### ISSUE TITLE
[BUG] Inconsistent settings sync in Vivaldi

### ISSUE THREAD

**Issue by leaumar** [darkreader/darkreader#4073]
### **Describe the bug**

The site list (and possibly other settings, but I don't use them) syncs inconsistently across my multiple Vivaldi installations on different windows machines. Sometimes my changes propagate, sometimes my whitelists just keep diverging over time (measured over minutes, hours, and weeks). Sync otherwise works fine for everything else in my browser, even disabling/enabling dark reader as an addon, sometimes instantaneously.

Manually running syncs after whitelist changes shows changes being detected and shared by the browser but not picked up/applied by the addon on the receiving end. Sometimes restarting both vivaldis at the same time gets the whitelists straightened out, though which version of the list wins is uncertain.

Sorry this isn't a very precise description but it's pretty random/unpredictable to me. Since vivaldi is a chrome clone, I wouldn't expect the issue to be their sync implementation.

### **Steps to reproduce**

- add/remove sites to/from the whitelist on separate instances of vivaldi in sequence/parallel and with browser restarts here and there (sync manually to save your time), i.e. just fast-forward emulate normal multi-device browsing behavior, you'll see the lists diverge after a while

### **Expected behavior**

The whitelist converges to the same list across multiple devices over time, especially when syncs occur

### **Actual behavior**

Lists diverge and stay diverged.

### **System Information:**
 - OS: windows 10
 - vivaldi 3.4.2066.94 (Stable channel) (64-bit)
 - Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
Hi @leaumar!

The current logic of sync is basic.
You change a setting -> Gets saved to sync and locally nothing more.
I suspect that because we don't get fresh data it doesn't show up for the other instances, but after a restart it does(as then it will pull the fresh data to the local extension. However we save every setting and will override the previous one.
It wasn't meant for simultaneous instance running and being used and changing settings and adding a check to prevent this will be more resource expensive for the server and a higher chance of getting a rate limited error. 

Regards,
Gusted

**Comment by leaumar** [comment]
Strange though. If the storage handling is basic, the addons should eventually (after a period without changes and some syncs/restarts) have the same data in storage. I saw today that one of my instances was divergent, but it's been three weeks since my last config change and I've restarted all my vivaldis dozens of times in the meantime, half the time with only 1 pc active at a time and the other half both active at the same time. There's really no reason for them to be divergent if there's no local caching layer over the sync storage or anything.

Just to clarify, I don't mean settings should sync up with concurrent modifications the way two git branches would converge. It makes sense with concurrent changes that one change would overwrite the other.

**Comment by Gusted** [comment]
> Strange though. If the storage handling is basic, the addons should eventually (after a period without changes and some syncs/restarts) have the same data in storage. I saw today that one of my instances was divergent, but it's been three weeks since my last config change and I've restarted all my vivaldis dozens of times in the meantime, half the time with only 1 pc active at a time and the other half both active at the same time. There's really no reason for them to be divergent if there's no local caching layer over the sync storage or anything.

It could be due to some errors it's not being synced. To make sure:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then check under Settings -> Manage Settings -> Sync settings.

**Comment by leaumar** [comment]
Thanks for getting around to that! I downloaded the source but then got so busy I forgot to get back to this.
