### ISSUE TITLE
[Broken Website] pixiv.net

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#4079]
**Website**
https://www.pixiv.net/en/artworks/85527915

**How to Reproduce**
An example of this is
> 1. Go to https://www.pixiv.net/en/artworks/85527915
> 2. Click on the button on the top right corner
> 3. The pop-up menu is not dark

**Expected behavior**
![sshot-020](https://user-images.githubusercontent.com/36977733/98661961-0cd30580-233f-11eb-9610-e0c73e6528a1.png)

**Actual behavior**
![sshot-019](https://user-images.githubusercontent.com/36977733/98661972-10668c80-233f-11eb-9138-9ced12e727dc.png)

**Screenshots**

**System info:**
 - OS: Windows
 - Browser: Firefox
 - Darkreader Version: 4.9.23
 
**Additional context**

**Comment by Gusted** [comment]
Hi @linsui!

What's your Firefox version? It seems to work for me.

Regards,
Gusted

**Comment by linsui** [comment]
Thanks! It works for me now. Looks like it's an  accidental issue.
