### ISSUE TITLE
[Broken Website] groovefunnels.com Preview & Publishing is broken if DarkReader is Enabled

### ISSUE THREAD

**Issue by ViperMaul** [darkreader/darkreader#4095]
**Website**
groovefunnels.com

**How to Reproduce**
> 1. Get a free account here https://groovepages.groovesell.com/a/5QQaDGdYjwPw 
> 2. Go to GroovePages or if no pages Click the NEW SITE button and create a page that includes photos in the background.
> 3. Click Preview, you will notice the photos do not display and the colors are all dark. 
> 4. Now turn off the DarkReader plugin. Same issue

**Expected behavior**
When the site is excluded or when the extension is turned off (enabled but turned off), the site should function as desired. It should preview the page properly. Is should publish the page properly. 

**Actual behavior**
Preview and Publishing on this site is broken.
The only work around is to either disable DarkReader as turning it off won't work. 
Or making sure DarkReader does not have access to private or incognito pages and use groovefunnels.com in private browsers. 

**Screenshots**
The picture on the left is what it should look like. The picture on the right is what clicking the Preview button results look like.
https://i.imgur.com/dbcaH3P.png
https://i.imgur.com/ZGBCUOf.jpg

**System info:**
 - OS: Windows 10
 - Browser: Brave, Chrome, Edge (all latest versions)
 - Darkreader Version: 4.9.16
 
**Additional context**
When you click the preview button, the actual page that results is the following. 
https://v1.gdapis.com/api/groovepages/pages/preview
So technically the problem could be with this page
When you click the Publish button, the page that results looks like the broken preview seen. 
Again when I disabled the extension both preview and publish features works on their site.

**Comment by Gusted** [comment]
Hi @ViperMaul!

Please first update to the latest Dark Reader version 4.9.22

Regards,
Gusted

**Comment by ViperMaul** [comment]
Hmm... Surprised it didn't auto update. 
Ok updated to version 4.9.22 
Same issue. Only disabling resolves the issue.

**Comment by Gusted** [comment]
Hmm, as I won't get around to get a account setup legally.
Could you on the `preview site` do the following.

To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Go to ⚙Settings -> Manage settings -> Export dynamic theme. 

And upload the result of the saved CSS File?

Regards,
Gusted

**Comment by ViperMaul** [comment]
Here you go...

[DarkReader-v1-gdapis-com.zip](https://github.com/darkreader/darkreader/files/5539483/DarkReader-v1-gdapis-com.zip)

**Comment by Gusted** [comment]
> DarkReader-v1-gdapis-com.zip

0 Rules are injected from Dark Reader. Means the site itself is doing this.

**Comment by ViperMaul** [comment]
> > DarkReader-v1-gdapis-com.zip
> 
> 0 Rules are injected from Dark Reader. Means the site itself is doing this.

I don't doubt what you are saying. 
However how do you explain the following?
If you toggle off DR v4.9.22 the Preview Button still generates the impaired page. 
If you disable the DR extension the Preview Button generates the expected working page.

**Comment by Gusted** [comment]
> If you toggle off DR v4.9.22 designed to not affect any pages, the Preview Button still generates the impaired page.
If you disable the DR extension the Preview Button generates the expected working page.

Toggle off as meaning toggling the site in the UI?
Disabling as in the Extension is Off.

**Comment by Gusted** [comment]
Both have the same affect on the page ^ It sends an `clean-up` command to the site and removes any Dark Reader Trace(even if their isn't one) and that's it for a disabled page.

**Comment by ViperMaul** [comment]
Apparently not in this case as shown here. 
Toggled Off
https://i.imgur.com/5coLPik.png

Disabled
https://gyazo.com/7206090f71b58214266efe6f5b818d2e
https://i.imgur.com/nZDeUwB.png

**Comment by ViperMaul** [comment]
I have completed Step 1 in the steps to reproduce for you. 
Here is your temporary login

**Site**:  https://groovefunnels.com or https://app.groovefunnels.com/#/login 
**UserName**: fepayib241@pidouno.com
**Password**:  Gusted&ViperMaul4President:)

1. Go to GroovePages, I have created a quick sample page there. 
2. Hover over the DarkReader Test and Click "Open Editor" 
    https://i.imgur.com/fbmLHVe.png
3. Click the preview button
    https://i.imgur.com/CE24cEQ.png

My results are as follows:
https://i.imgur.com/YVq8V6O.png

But it should look like this (I had to go to extensions and disable it from there):
https://i.imgur.com/YVq8V6O.png

See if you can reproduce the problem like I can.

**Comment by Gusted** [comment]
Open up a ticket at the groovefunnels. They are the one causing this. AFAIK even an request to the site already contains the style that cause this bug ![](https://i.imgur.com/eupei06.png) It seems like they process Dark Reader style as their own in the website builder and just process it to the `preview API` and Display it.

Regards,
Gusted
