### ISSUE TITLE
[Broken Website] www.infoq.cn

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#4099]
**Website**
https://www.infoq.cn/article/57asBCrBGEB1ebhfgcdb
**How to Reproduce**
An example of this is
> 1. Go to https://www.infoq.cn/article/57asBCrBGEB1ebhfgcdb

**Expected behavior**
It's dark.

**Actual behavior**
It's not dark.

**Screenshots**

![sshot-014](https://user-images.githubusercontent.com/36977733/98888195-6ba79480-248f-11eb-80c2-b1c7bdccac64.png)

**System info:**
 - OS: Windows

 - Browser: Firefox
 - Darkreader Version: 4.9.23

**Comment by Gusted** [comment]
Same underlying bug as #835 
It can't read the CSSRules of an Import Rule.
