### ISSUE TITLE
Sometimes DarkReader fails to inject its <style>

### ISSUE THREAD

**Issue by ershov** [darkreader/darkreader#41]
I noticed that occasionally some sited stay not inverted.
Examined the DOM I found out that DarkReader's `<style id="dark-reader-style" ...` is not there.
Adding-removing the site from the exclusion list doesn't help.
Sometimes the page gets inverted when reloaded.

One site the most often suffer from this is docs.google.com.

**Comment by puranjayjain** [comment]
that might be due to the fact that some websites use the shadow dom or shady dom which cannot be styled from the outside.

see these https://www.polymer-project.org/1.0/blog/shadydom

**Comment by ershov** [comment]
Not really.
It's the same website behaving differently.

**Comment by puranjayjain** [comment]
Oh thats an issue.

**Comment by alexanderby** [comment]
Would be great if anyone will post a link to a buggy website. Another reason for this can be if style is removed by script (eg. virtual DOM).

**Comment by ershov** [comment]
As I said, it's docs.google.com, a quite famous one :)
I can't share the docs themselves, sorry. But it seems not to be related to the doc itself.

Interesting fact is that once DarkReader fails to load on a particular page, it will not recover on that page until the browser is restarted.
After restart it will fork just fine though (but may get stuck at another page).

I'd think this may be a Chrome's issue rather than DarkReader's one.

Also, I'm trying to figure out the conditions for this to happen and think of any possible work-arounds.
Just because the bright screen is annoying.

By the way, it's Linux.

**Comment by telemea** [comment]
http://popurls.com/ keeps its white background no matter what...

**Comment by alexanderby** [comment]
The problem should be fixed. If you see some website remains unchanged, and you are sure it is not ignored by Site List, please file a new issue.
