### ISSUE TITLE
[Feature Request] Don't invert a region of website, such as the design area of Google Draw

### ISSUE THREAD

**Issue by bendavis78** [darkreader/darkreader#4100]
When using apps such as Google Draw, the design area is inverted, which is not desirable.

A rule such as IGNORE could be added that would allow you to ignore just one region of a page.

**Comment by Gusted** [comment]
Hi @bendavis78!

> When using apps such as Google Draw, the design area is inverted, which is not desirable.

People will agree or disagree with this statement, as e.g. some people still like to have it in a dark envirement whereby people also just wants to have it's original colors.

> A rule such as IGNORE could be added that would allow you to ignore just one region of a page.

This won't be possible due to performance reason and because it's technically not possible.

If people wants to have their design area not darken, they should just stick to the light theme or disabling Dark Reader for that site as ignoring a portion of a site will mess up the color scheme and Dark Reader won't have much effect.

Regards,
Gusted

**Comment by B3nji957** [comment]
@Gusted will it be possible to add a feature to select elements of a webpage that we'd like to be inverted if we have the website in "Not invert listed"?

**Comment by Gusted** [comment]
>  will it be possible to add a feature to select elements of a webpage that we'd like to be inverted if we have the website in "Not invert listed"?

This means that Dark Reader is disabled for that site, we won't do anything to the webpage. If you like to invert something you can use custom CSS alongside Stylus in order to do this.

Regards,
Gusted

**Comment by bendavis78** [comment]
> People will agree or disagree with this statement, as e.g. some people still like to have it in a dark envirement whereby people also just wants to have it's original colors.

I don't think it's as subjective as you say. When working in an app designing something for **publication**, you would want to see it as the general public would see it. This could apply to many different web-based design tools.

> If people wants to have their design area not darken, they should just stick to the light theme or disabling Dark Reader for that site as ignoring a portion of a site will mess up the color scheme and Dark Reader won't have much effect.

This is not possible for Google Drawings, because the domain is `docs.google.com`. I still want the dark theme for spreadsheets.

**Comment by Gusted** [comment]
> When working in an app designing something for **publication**, you would want to see it as the general public would see it. This could apply to many different web-based design tools.

I agree with this, however just *disabling* the design your working and the other tools not disabling seems weird in my eyes.




> This is not possible for Google Drawings, because the domain is `docs.google.com`. I still want the dark theme for spreadsheets.

`docs.google.com/drawings` add that into your sitelist and it should disable only for drawings.
