### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by heinebold** [darkreader/darkreader#4101]
**Is your feature request related to a problem? Please describe.**
I am using dark themes in my OS, which contain dark buttons and inputs. Dark Reader's styling is not necessary for them and makes them look uglier.

**Describe the solution you'd like**
I would like an option to tell Dark Reader to use the system's control elements (i.e. not style them)
- never
- always
- when system theme is dark
- when system theme is not dark

maybe configurable separately for Dark Reader's dark and light mode

**Comment by Gusted** [comment]
Hi @heinebold!

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Under See all options click on Fonts & more and disable `Style system controls`.

Regards,
Gusted
