### ISSUE TITLE
[Broken Website] https://discord.com/ and https://support.discord.com/

### ISSUE THREAD

**Issue by Brian-Graham** [darkreader/darkreader#4110]
**Website**
https://discord.com/ & https://support.discord.com/

**How to Reproduce**
An example of this is
1. Go to either site
2. No dark mode what so ever

**Expected behavior**
Dark mode

**Actual behavior**
Light mode

**System info:**
 - OS: MacOS
 - Browser: Safari
 - Darkreader Version: 1.3.3

**Comment by NorthIsUp** [comment]
this seems to work fine for safari 14.0
