### ISSUE TITLE
Mirror for dynamic-theme-fixes.config and inversion-fixes.config

### ISSUE THREAD

**Issue by kizule** [darkreader/darkreader#4116]
Hello,
I'm using this extension which is the best. 😄 

I would like to make a mirror (for free) for dynamic-theme-fixes.config and inversion-fixes.config files.

**Comment by Gusted** [comment]
Hi @kizule!

Mirror? What do you try to achieve?

Regards, 
Gusted

**Comment by kizule** [comment]
@Gusted I would like to help you with providing of mirror, so these files can be synced automatically, without waiting for a new release of this extension.

I believe it would mean something to everyone. Personally, I probably wouldn't benefit from this, but it doesn't matter. I just want to help, nothing else.

**Comment by Gusted** [comment]
@kizule Aha I see.

We currently provide an option to sync the config files with Github one.
![](https://i.imgur.com/fA96ZL0.png)
The README.md currently state it doesn't but should be fixed with the new README.md layout #3917

Regards,
Gusted

**Comment by kizule** [comment]
Oh, great. 😃

**Comment by kizule** [comment]
But.. I don't see it in 4.9.22.

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Under Settings -> Manage Settings -> Synchronize Settings.

**Comment by kizule** [comment]
Okay, this works. Thank you @Gusted. I'm closing this issue now.
