### ISSUE TITLE
[Dynamic] odd coloring/styling on Firefox release notes version header

### ISSUE THREAD

**Issue by joshsleeper** [darkreader/darkreader#412]
# info
* firefox `59.0.3`
* dark reader `4.4.1`
* dynamic theme
* site: https://www.mozilla.org/en-US/firefox/59.0.2/releasenotes/

# problem(s)
odd header color/style change when using the dark reader dynamic theme.
visible by the short height grey bar just above the version number (`59.0.2`), which should extend decently below the date of the release.

# without theme
![image](https://user-images.githubusercontent.com/849941/39266169-11f5abce-487e-11e8-89b8-6ca19a93693a.png)

# with theme
![image](https://user-images.githubusercontent.com/849941/39266180-1a844cc8-487e-11e8-8a00-a8bc5b7ceab8.png)

**Comment by Gusted** [comment]
Resolved.
