### ISSUE TITLE
[Broken Website]  - https://telekomhilft.telekom.de/ partially broken

### ISSUE THREAD

**Issue by Felixkruemel** [darkreader/darkreader#4123]
**Website**
https://telekomhilft.telekom.de/

**How to Reproduce**
1. Visit the site 
2. Click on some sub menus or open some threads
3. Sometimes it will show everything correctly, other times some elements are white
**Expected behavior**
It will darken every element every time like on the first visit.

**Actual behavior**
Sometimes some elements stay white

**Screenshots**

If it doesn't work as it should:
![image](https://user-images.githubusercontent.com/12109804/99154968-2dd78580-26b4-11eb-9f2d-5942b82e2cfe.png)

If it works as it should:
![image](https://user-images.githubusercontent.com/12109804/99154980-434caf80-26b4-11eb-97c2-02521f69ac0b.png)

**System info:**
 - OS: Windows 10 2004
 - Browser: Chrome 86.0
 - Darkreader Version: 4.9.22

**Comment by Gusted** [comment]
Hi @Felixkruemel!

I tried to reproduce this however I couldn't get the behaviour.
Is this an consistent problem?

Regards,
Gusted

**Comment by Felixkruemel** [comment]
@Gusted 
It happens like 10% of the time if I load some random thread / page on the forum. So yeah it's pretty much consistent.

Actually, if I have got the developer console open it hapens nearly 100% of the time, pretty much always. Maybe it's due to the mobile(ish) site view then. So please try that, maybe it gives the error for you then too.

But I don't see anything related to that in the browser console too, mhmm

**Comment by Gusted** [comment]
Hmm when I used the stock dark reader from the extension store I got it immediately. I suspect #4005 has this issue covered.
Could you sideload this extension and temporarily uninstall the stock one?
`go to chrome://extensions/`
`Enable developer mode`
`click on the unzipped folder of build.zip`
[build.zip](https://github.com/darkreader/darkreader/files/5541358/build.zip)

Regards,
Gusted

**Comment by Felixkruemel** [comment]
@Gusted That actually works fine. Didn't get it a single time until now. Also the Tab switching error is gone!
So I guess 4.9.23 fixes all that.

When will you push that release to the official Chrome Extension Store? Would make updating in the future easier.

**Comment by Gusted** [comment]
> When will you push that release to the official Chrome Extension Store? Would make updating in the future easier.

The version with this fix will be 4.9.24 and their is no official release calendar however the last few updates has been around the end of the month.

**Comment by Felixkruemel** [comment]
@Gusted 
Okay nice, thanks for the help!

Great to have such good devs doing that in their free time 👍 
If you want you can close this issue then or let it open till the new release for others to check

**Comment by Gusted** [comment]
Issue is technically already fixed in the current codebase but not release yet 🤷🏽

**Comment by Gusted** [comment]
> Okay nice, thanks for the help!

No problems!



> Great to have such good devs doing that in their free time +1

Thank you!
