### ISSUE TITLE
[BUG] White Flash before Darkened DarkReader API

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4126]
### **Describe the bug**

I created a simple site that uses the DarkReader API. After reloading, a white flash appears before entering dark mode.

### **Steps to reproduce**

View the GIF

### **Actual behavior**

A clear and concise description of what actually happened.

### **Screenshots**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53054099/99159874-b72b8f80-2695-11eb-84fd-a92973c3a567.gif)

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Chrome 87
 - Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
Browser bug. Not fixable by the API.
