### ISSUE TITLE
[Broken Website] Lloyds Bank logs the user out when Dark Reader is applied

### ISSUE THREAD

**Issue by AntonioRedondo** [darkreader/darkreader#4130]
British bank Lloyds will log out as soon as you log in and the extension is enabled. This seems like the site detects some styling change and will log out and ban the user's IP address as a security measure.

There is nothing wrong with the appearance of the dark theme applied. It's just the fact the extension will trigger the page to log the user out. The extension can be enabled, just not applied to Lloyds Bank, in order for this site to work.

This bug is related to [this other one happening for Vanguard.com](https://github.com/darkreader/darkreader/issues/3576).

**Website**
https://online.lloydsbank.co.uk/personal

**How to Reproduce**
1. Go to https://online.lloydsbank.co.uk/personal
2. Log in with your personal bank account credentials.
3. Click _View statement_ (you may already be logged out at this point).

**Expected behavior**
You should be able to log in correctly and navigate through your personal account site without being logged out unless you click the _Log out_ button.

**Actual behavior**
You'll be logged out and be shown the below error page as soon as you log in or you click some link once you're logged in. Then, at that point your IP address will be flagged from Lloyds servers and if you try to log in again, even with Dark Reader not applied to this site, you will be shown the error page again. You'll have to restart your router or use your phone connection to log in again from a different IP address. At that point the IP ban will be removed and you'll be able to connect from the same IP in case the router wasn't reset.

> Sorry, we've had to log you off [Error: 1007 ID: 18.6fb77568.1605407747.138d12ac]

**Screenshots**
![image](https://user-images.githubusercontent.com/5444421/99161545-562ea680-26eb-11eb-933c-1047a391988b.png)

**System info:**
 - OS: Windows 10 1903
 - Browser: Firefox 81.0
 - Darkreader Version: 4.9.23

**Comment by Gusted** [comment]
Hi @AntonioRedondo!

This is an unfortunate bug... Whereby we are limited in what we can do.
I think it's the best to now add the `online.lloydsbank.co.uk` to the dark-sites.config so it won't be styled from default.

Regards,
Gusted
