### ISSUE TITLE
On google slides it changes the slide colour

### ISSUE THREAD

**Issue by Busaruba2011** [darkreader/darkreader#4137]
I was doing something in Google Slides, and for some reason, Dark Reader changed the slide colour. I turned it off, and it stopped.

**Comment by Gusted** [comment]
Use issue format.

**Comment by Busaruba2011** [comment]
How do I do that?

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D

**Comment by Busaruba2011** [comment]
Ok
