### ISSUE TITLE
[BUG] Dark Reader alters with Google Slides slide colour and text colour

### ISSUE THREAD

**Issue by Busaruba2011** [darkreader/darkreader#4139]
### **Describe the bug**

I was doing something in Google Slides, and for some reason, Dark Reader changed the colour in the slide. I turned Dark Reader off, and it stopped.

### **Steps to reproduce**

- Go to 'docs.google.com/presentation'
- Click on 'Blank'
- Add text
-Turn on Dark Reader

### **Expected behavior**

Changes slide and text colour to b and w.

### **Actual behavior**

Changed slide colour

### **Screenshots**

![Screenshot (72)](https://user-images.githubusercontent.com/65495333/99188475-1cde5100-2754-11eb-88ed-287e4265709b.png)

### **System Information:**

- OS: Windows 10 Home
- Browser: Chrome 86.0.4240.198 
- Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
Hi @Busaruba2011!

Seeing a gradient background color it might indicate your using a theme, do you know if your using a theme?

Regards,
Gusted

**Comment by Busaruba2011** [comment]
> Hi @Busaruba2011!
> 
> Seeing a gradient background color it might indicate your using a theme, do you know if your using a theme?
> 
> Regards,
> Gusted

I was using 'Simple White', and added a gradient because I was making a theme. Previously, it was just white, and Dark Reader changed it black. The gradient was added to the master slide.

**Comment by Gusted** [comment]
Hi @Busaruba2011!

It seems like Google Slides uses the [stop](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop) element to creates gradients, however the stop element uses [stop-color](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color) as attribute to indicate the color. Which Dark Reader isn't currently modifying, I've made opened up a PR(#4140) to fix this.

Regards,
Gusted

**Comment by Busaruba2011** [comment]
> Hi @Busaruba2011!
> 
> It seems like Google Slides uses the [stop](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop) element to creates gradients, however the stop element uses [stop-color](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color) as attribute to indicate the color. Which Dark Reader isn't currently modifying, I've made opened up a PR(#4140) to fix this.
> 
> Regards,
> Gusted

Thanks!

**Comment by Ishaanrathod09** [comment]
Still the bug exists
