### ISSUE TITLE
[Dynamic] web.whatsapp.com: tip of dialog boxes and check marks don't look right

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#414]
I'm running darkreader b117f94491401335b0164b434af3708691965d27 on Google Chrome 66.0.3359.117, on Xubuntu 17.10.

Using theme engine `Dynamic`, the tip of the dialog boxes and the check marks on https://web.whatsapp.com/ don't look quite right:
![image](https://user-images.githubusercontent.com/10074769/39268597-ab28d3e8-48a6-11e8-92fb-2c40cf405da1.png)

They look OK using theme engine `Filter+`:
![image](https://user-images.githubusercontent.com/10074769/39268647-d0937b6a-48a6-11e8-9809-2a32af972595.png)

**Comment by Gusted** [comment]
Hey their!

I've made a fix for this in #2328

**Comment by Gusted** [comment]
Fixed.
