### ISSUE TITLE
Disable or IGNORE only single div/element

### ISSUE THREAD

**Issue by josdyr** [darkreader/darkreader#4144]
I'd like to be able to disable dark reader on a certain div. I use the monaco-editor which is embedded in an iframe on my site. I'd like to continue using dark mode on my site, but only to disable it within the iframe monaco-editor window where my code is (as the monaco-editor itself happen to have a dark theme option already).

Right now it works very well, but the only problem I have is that the highlighted text (if I double click a variable to see where the other similar variables are referenced, the referenced variables/words don't get highlighted.). I am expecting all variables/words to light up/be highlighted/multiselected if I highlight one word.

I can just barely see it, but it is not good enough (see image)...

Maybe the best solution is to ignore/disable dark reader only for my iframe element? I have tried to INVERT it, which works fine, but the IGNORE INLINE STYLE don't seem to do anything (assuming the style is not written inline):

================================

example.com

INVERT
iframe

Also, the blinking cursor blends in quite a bit too, so I guess that again - the best solution is to disable dark reader on this element.

Why is there not a single 'IGNORE' function?

![multiselect_not_working_well_enough](https://user-images.githubusercontent.com/16963358/99274513-b8da8c00-282a-11eb-9b65-ebf0492be4be.png)

**Comment by Gusted** [comment]
Hi @josdyr!

Their is no `IGNORE` as that gives a quite a big performance impact and as well it can inherit styles from parents elements and therefore it still can be styled. A good universal solution to adding `IGNORE` isn't practical.

So as this individual case
> Maybe the best solution is to ignore/disable dark reader only for my iframe element?

Hmm that is a option that could be added to Dark Reader, however no big use case for this.

As it's mentions in your site, I assume you can edit the styles and a simple `darkreader` into the class of the styles should disable it from styling them.

Regards,
Gusted

**Comment by josdyr** [comment]
Hi Gusted, thanks for your response!

I'm afraid I'm not entirely sure what you meant by:

> As it's mentions in your site, I assume you can edit the styles and a simple darkreader into the class of the styles should disable it from styling them.

Are you saying I should edit my website's css to include a darkreader property somehow? Or are you referring to the Darkreader's "Dev tools" window?

Thanks for giving me some more insight into this issue.

**Comment by Gusted** [comment]
> Are you saying I should edit my website's css to include a darkreader property somehow?

Yes, adding the attribute `class="darkreader"` into the style element should ignore it completely from getting styled.

Regards,
Gusted

**Comment by josdyr** [comment]
I still can't get it to work. Let me know if you have any luck on this website: https://microsoft.github.io/monaco-editor/

On this site, there is a nested demo-window (editor-frame) of the monaco editor, exactly as on my own site.

How - on this site - can I get the demo window to get excluded/ignored? (make sure you select under 'Theme:' "Visual Studio Dark")

I tried to add the `darkreader` class you mentioned in the chrome devtools, but to no luck...

Best,
Jos

**Comment by Gusted** [comment]
Hi @josdyr!

Like I mentioned before it only works on sites that uses the API alongside adding into the styles `class="darkreader"` which provide the style to the editor.

Regards,
Gusted

**Comment by BrianLeishman** [comment]
@Gusted What API are you referring to?

I'm right there with OP in trying to find a way to ignore monaco editor because it breaks the cursor, and the editor itself already has a dark mode, but the site it's being used on does not, so it would be nice to enable dark mode, but skip just the editor

**Comment by Gusted** [comment]
> @Gusted What API are you referring to?

https://github.com/darkreader/darkreader#using-for-a-website

> I'm right there with OP in trying to find a way to ignore monaco editor because it breaks the cursor, and the editor itself already has a dark mode, but the site it's being used on does not, so it would be nice to enable dark mode, but skip just the editor

Becuase, it's not in an isolated iFrame it isn't possible and as matching elements etc. the editor + all it's children elements would be expensive for the Browser it won't be implemented in Dark Reader.
As for the cursor a simple CSS Fix should do it:
```CSS
.monaco-editor .cursors-layer .cursor {
    background-color: #000 !important;
    border-color: #000 !important;
    color: #fff !important;
}
```

Regards,
Gusted

**Comment by BrianLeishman** [comment]
The background of the cursor being black was actually the problem here, makes it invisible on a dark editor background, but setting it back to the vscode/monaco default cursor color for their dark theme fixed it for me

```css
.monaco-editor .cursors-layer .cursor {
    background-color: #aaa !important;
}
```

**Comment by hewenguang** [comment]
My extension uses shadowdom to isolate the style of the original web page, and at the same time provides a dark mode by itself. The plugin completely disrupts my product UI. Is there any way to disable shadowdom without affecting it?

**Comment by Nekzuris** [comment]
If you want to ignore the color conversion on many elements with different color values or just avoid hardcoding the color, try the css `revert-layer`
```css
.day-cell {
    fill: revert-layer !important;
}
```
