### ISSUE TITLE
view-source has white background

### ISSUE THREAD

**Issue by sthiele** [darkreader/darkreader#4149]
### **Describe the bug**

On Firefox, if I right click on a website and choose "View Page Source" from the context menu I get a page with white background.

view-source:https://darkreader.org/

### **Steps to reproduce**

- Go to 'https://darkreader.org/'
- Right click on website
- Select 'View Page Source'

### **Expected behavior**

A dark source view.

### **Actual behavior**

A bright source view.

### **System Information:**

- OS: Linux
- Browser: Firefox 82.0.3
- Dark Reader version: 4.9.23

**Comment by Yash-Singh1** [comment]
@sthiele 
I think that the `view-source` protocol is protected from extensions in `firefox`. This can be enabled with the following on `google-chrome`:
- In the new UI, go to Settings > Site List and enable on restricted pages
- Enable the `chrome://flags/#extensions-on-chrome-urls` flag

`firefox` has prevented access to the protocol for security purposes.

**Comment by sthiele** [comment]
Is this the same why the raw content is black on white with firefox?
https://raw.githubusercontent.com/darkreader/darkreader/master/README.md

**Comment by Yash-Singh1** [comment]
No, that isn't supposed to be happening:
![Screenshot from 2020-11-16 21-07-49](https://user-images.githubusercontent.com/53054099/99349022-ceae7800-284f-11eb-935b-ea470e4734da.png)

**Comment by sthiele** [comment]
> Is darkreader enabled and raw.githubusercontent.com given access?
Yes. I don't have this issue on chrome.

**Comment by Yash-Singh1** [comment]
@sthiele 
Hmm...

You are not alone. I am experiencing this problem also:
![Screenshot from 2020-11-17 08-18-19](https://user-images.githubusercontent.com/53054099/99416209-760dc800-28ad-11eb-9c55-5bb82b59bbe0.png)

**Comment by Gusted** [comment]
Hi @sthiele and @Yash-Singh1!

> `firefox` has prevented access to the protocol for security purposes.

That's correct and for an add-on it's not possible to bypass or do anything related to make it still work.




> Is this the same why the raw content is black on white with firefox?
> https://raw.githubusercontent.com/darkreader/darkreader/master/README.md

That's another issue #1446 and already a bug has been filled for this at [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1654588) however it wasn't updated the last 4 months so I will have a comment on this, if their was any progression or any reason to have this behaviour as for ^ `view-source` it's for security reasons, but I don't quite understand for normal text pages.

Regards,
Gusted
