### ISSUE TITLE
[Dynamic] various styling issues with Google Calendar

### ISSUE THREAD

**Issue by joshsleeper** [darkreader/darkreader#415]
# info
* firefox `59.0.2`
* dark reader `4.2.8`
* dynamic theme
* site: https://calendar.google.com/calendar/r/week

# problem(s)
* header is still white, but text is changed to make it dark-background friendly, making it unreadable
* colored event blocks are unchanged, but dark text on light event blocks (past events) is changed to white, making it unreadable
* masking to make arrow shape on events that run beyond the shown time frame (visible in the upper right, on the "Visiting Mom" event) is left white, which looks odd on the black background

# without theme
![image](https://user-images.githubusercontent.com/849941/39270634-844d66be-488b-11e8-9cc4-c389b20fe93f.png)

# with theme
![image](https://user-images.githubusercontent.com/849941/39270641-8afffe86-488b-11e8-8437-338ab32f6fa1.png)

**Comment by joshsleeper** [comment]
Same comment I left here: https://github.com/darkreader/darkreader/issues/413#issuecomment-386692740

> @alexanderby has this been fixed?
>
> As of the Dark Reader 4.3.0 release for Firefox I'm seeing the exact same issue still.

**Comment by alexanderby** [comment]
I will publish changes soon, many issues had the same fix.

**Comment by joshsleeper** [comment]
Calendar looks much better than before, thanks!!

![image](https://user-images.githubusercontent.com/849941/39654679-b971dfac-4faa-11e8-87e0-de98b611bf94.png)

_That said_, there's still one issue I mentioned above that remains:
> * masking to make arrow shape on events that run beyond the shown time frame (visible in the upper right, on the "Visiting Mom" event) is left white, which looks odd on the black background

In this case, I've moved to the next week, so it's actually visible in the very top left, just under the big "Sun 29" label. Here's a more focused image:

![image](https://user-images.githubusercontent.com/849941/39654864-b13d22fa-4fab-11e8-85b5-a2542afaea7a.png)

Comparing it to an example without Dark Reader applied, you can see the difference:

![image](https://user-images.githubusercontent.com/849941/39654847-9c33c990-4fab-11e8-8d95-57cdac37b654.png)
