### ISSUE TITLE
[Broken Website] youtube.com

### ISSUE THREAD

**Issue by Rakleed** [darkreader/darkreader#4150]
**Website**
https://www.youtube.com/

**How to Reproduce**
1. Go to https://www.youtube.com/ site
2. Also go to https://www.youtube.com/watch?v=OPf0YbXqDm0 site

**Expected behavior**
The block separators (borders) are clearly visible.

**Actual behavior**
The block separators (borders) are almost invisible.

**Screenshots**

<details>
<summary>Main page</summary>
DarkReader enabled:

![2020-11-17 01-51-33 YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321456-e5b88e80-287e-11eb-930c-544c6abdc81c.png)

Default YouTube dark theme:
![2020-11-17 01-48-58 YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321459-e7825200-287e-11eb-94e8-5a23185f87a4.png)

</details>

<details>
<summary>Video player page №1</summary>
DarkReader enabled:

![2020-11-17 01-59-42 Mark Ronson - Uptown Funk (Official Video) ft  Bruno Mars - YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321615-4ba51600-287f-11eb-8f7d-68c3fe482439.png)

Default YouTube dark theme:
![2020-11-17 01-58-01 Mark Ronson - Uptown Funk (Official Video) ft  Bruno Mars - YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321621-4d6ed980-287f-11eb-8740-959b51d0d92f.png)

</details>

<details>
<summary>Video player page №2</summary>
DarkReader enabled:

![2020-11-17 02-04-31 Mark Ronson - Uptown Funk (Official Video) ft  Bruno Mars - YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321654-5f507c80-287f-11eb-85bf-1f7bf6b3bc5a.png)

Default YouTube dark theme:
![2020-11-17 02-02-52 Mark Ronson - Uptown Funk (Official Video) ft  Bruno Mars - YouTube - Google Chrome](https://user-images.githubusercontent.com/19418601/99321661-64adc700-287f-11eb-9e4f-aff7395591db.png)

</details>

**System info:**
- OS: Windows 10 v. 20H2
- Browser: Chrome 86.0.4240.198 
- Darkreader Version: 4.9.22

**Additional context**
I tried to fix this myself, but I got long selector names, for some selectors the rule simply did not work, and I also don’t know which color would look better.

I also found this problem on some other sites - #2261, #2770. Perhaps this is some kind of bug in Dark Reader?

**Comment by Gusted** [comment]
Hi @Rakleed!

> I also found this problem on some other sites - #2261, #2770. Perhaps this is some kind of bug in Dark Reader?

Dark Reader just sees the border-color and assumes it should be darken however in this case the contrast messes up :shrug: and that's something very hard to fix within the code-base itself so I will prepare a simple CSS fix for this.

Regards,
Gusted
