### ISSUE TITLE
[BUG] Unchecked runtime.lastError

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4151]
### **Steps to reproduce**

- Go to `chrome://extensions`
- Make sure developer mode is enabled
- Make sure collect errors is enabled for `darkreader`
- Go to `gmail.com`
- Quickly close the tab before `darkreader` loads
- See the error inside `chrome://extensions`

Note: This error works for all sites, I chose `gmail.com` because it takes time to load
Also, it is very hard to replicate

### **Expected behavior**

The error not to appear

### **Actual behavior**

The error appeared

### **Screenshots**

![Screenshot from 2020-11-16 16-35-29](https://user-images.githubusercontent.com/53054099/99331862-e62c3780-2834-11eb-8d4c-0d3ab8457d04.png)

### **System Information:**

- OS: Ubuntu 20.04
- Browser: Chrome 78
- Dark Reader version: 4.9.23

### **Additional context**

This bug is happening because the tab closes before the `tabs.executeScript` runs.
Maybe checking it with: ` _=> { let e = chrome.runtime.lastError }` in https://github.com/darkreader/darkreader/blob/master/src/background/tab-manager.ts#L124 works

**Comment by Gusted** [comment]
Hi @Yash-Singh1!

We are already checking this with `!tab.discard` https://github.com/darkreader/darkreader/blob/master/src/background/tab-manager.ts#L119 that should prevent this, however the time between actually injecting and executing this command is slow and therefore the tab can already be closes and causes this error. It's not a big problem 🤷🏽 and only logged for debug-builds and explicitly enabling Error logging.

Regards,
Gusted
