### ISSUE TITLE
[Bug] Images in cells in Google Sheets Inverted

### ISSUE THREAD

**Issue by eberkain** [darkreader/darkreader#4152]
When using the command =image() to insert an image into a google sheet the image appears with colors inverted. 

Dynamic mode seems to strive for unaltered images in most situations, so this should probably be corrected. 

https://i.imgur.com/pqDbWtR.png

I am using...
Windows 10.0.18363
Dark Reader 4.9.22
Chrome 86.0.4240.198

**Comment by Gusted** [comment]
#1934
