### ISSUE TITLE
[Dynamic] Terminal theme in ddg gets brighter

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#416]
https://duckduckgo.com/?kae=t

**Comment by alexanderby** [comment]
It can become brighter due to your "brightness" and "contrast" settings.

**Comment by ShalokShalom** [comment]
It is the default setting?

**Comment by alexanderby** [comment]
Default contrast is -10%, so it makes already dark backgrounds brighter. I will try to not apply these settings to already dark backgrounds.
