### ISSUE TITLE
[BUG] On allegro.pl darkreader prevent to properly load page.

### ISSUE THREAD

**Issue by maver1ck** [darkreader/darkreader#4162]
### **Describe the bug**

On allegro.pl darkreader prevent to properly load page.

### **Steps to reproduce**

- Go to 'https://allegro.pl/oferta/ikea-skrall-wieszak-hak-na-rower-uchwyt-na-krzesla-9756400379'

### **Expected behavior**

Whole page is loading.

### **Actual behavior**

Parts of the page are missing.

### **Screenshots**

Dark reader OFF:
![image](https://user-images.githubusercontent.com/4006010/99430155-3f659b00-2909-11eb-98c0-b0b1fcdeec05.png)

Dark reader DYNAMIC:
![image](https://user-images.githubusercontent.com/4006010/99430202-54dac500-2909-11eb-8e47-570fe91035cb.png)

### **System Information:**

- OS: Windows 10
- Browser: Edge 86.0.622.69
- Dark Reader version: 4.9.22

**Comment by Gusted** [comment]
After closer inspection the site is not getting the correct CSSRules, which we can't fix nor is our scope to do so.

**Comment by maver1ck** [comment]
@Gusted 
Could you please explain a little more ?

**Comment by Gusted** [comment]
As you can see in the screenshot
![image](https://user-images.githubusercontent.com/25481501/104356487-4fb28480-550c-11eb-9d72-1c3c7fcd58cf.png)
This error is causing to not load the site properly. It saying it's accessing a cross-origin style. Which is most likely a style element from Dark Reader. The site is incorrectly getting their target and is instead targetting Dark Reader. We cannot fix this nor is our scope to do so.
