### ISSUE TITLE
[Broken Website] Google Docs, weird effect on document title

### ISSUE THREAD

**Issue by KibSquib48** [darkreader/darkreader#4163]
**Website**
docs.google.com

**How to Reproduce**
Open a document with a relatively long name
There is now a weird effect on the title making some of the text unreadable

**Expected behavior**
The title looks normal, no weird double effect, just text being displayed with no issue

**Actual behavior**
There's a weird effect and it makes the title look weird, I'm not sure how to really describe it so I attached a screenshot of it

**Screenshots**
![image](https://user-images.githubusercontent.com/33189136/99431430-c1899b80-28d8-11eb-8e67-8da8e086c528.png)

**System info:**

- OS: Windows and Chrome OS
- Browser: Microsoft Edge and Google Chrome
- Darkreader Version: 4.9.22

**Comment by Yash-Singh1** [comment]
This is present when editing the document only, maybe there are two elements showing the same thing with an offset.

**Comment by Gusted** [comment]
> This is present when editing the document only, maybe there are two elements showing the same thing with an offset.

Correcto what I remembered an input element and an `p` or `span` element. However I didn't find an offset.

**Comment by Yash-Singh1** [comment]
Maybe we can disable viewing for the `span`.

**Comment by Gusted** [comment]
> Maybe we can disable viewing for the `span`.

It might be the same span that's used in `view` mode. Not sure as this info what I remembered was from some couple months ago when I got this same behaviour and wasn't bothered fixed until someone came with an issue about it.

Also to reproduce it -> Just get a long string in the title.

**Comment by Yash-Singh1** [comment]
I added in the following:
```css
#docs-title-input-label-inner {
    visibility: hidden !important;
}
```
It worked fine. I can't reproduce the behavior so can you test it?

**Comment by Gusted** [comment]
What about

```CSS
.docs-title-input-label:not([style*="pointer-events: auto"]) > #docs-title-input-label-inner {
    visibility: hidden !important;
}
```

As the only change detectable is `pointer-events: auto` in view mode and so preserve the title. It LGTM to hide the `span` as it's anyway not being used in `edit/react` mode if it's being `pointer-events: none` 🤷🏽

**Comment by Yash-Singh1** [comment]
@Gusted Sure, we can do that. Added in ffe7c25.
