### ISSUE TITLE
[Feature Request] Allow URL patterns for root path only

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4178]
**Is your feature request related to a problem? Please describe.**

Currently the homepage: https://repl.it/ is dark. There is no way though to only specify the root path `/` of `repl.it`.

**Describe the solution you'd like**

The pattern to have something like:
- `example.com/` selects the root path of `example.com` only
- `example.com` selects the whole domain of `example.com`

**Additional context**

I am happy to create a PR if wanted

**Comment by Gusted** [comment]
Hi @Yash-Singh1!

Please comment this out on #373 as it's best to have this issue as an `mega thread` of the ongoing URL match patterns. 
As for the PR #2517 is currently an candidate as fix.

Regards,
Gusted
