### ISSUE TITLE
Dynamic has issues with asynchronous content.

### ISSUE THREAD

**Issue by leetNightshade** [darkreader/darkreader#418]
Dynamic has issues with asynchronous content in Firefox, like on the new Beta Reddit newly opened posts like the Sidebar can have text show up black on black. 

Toggling the extension Off then On, works.

**Comment by jackblackmore** [comment]
I've found this as well, https://www.eventhubs.com/ is a good example where it looks like a few elements are caught by the Dynamic filter but anything that's loaded after isn't handled. 

As @leetNightshade mentions, toggling the extension correctly applies the filter

**Comment by alexanderby** [comment]
Looks like eventhubs uses some strange non-blocking technique for loading CSS `<link onload="this.rel='stylesheet'">`
