### ISSUE TITLE
[Feature Request] Unintentional(?) grey boxes for GitHub website

### ISSUE THREAD

**Issue by Andre601** [darkreader/darkreader#4181]
**Website**
https://github.com

**How to Reproduce**
The issue should be visible straight away without doing anything of importance.

**Expected behavior**
The GitHub page should look as usual (Same dark grey colors used throughout the site)

**Actual behavior**
The GitHub site is displayed with light-grey boxes/fields/areas.
While this doesn't look horrible in itself does it feel unintentional.

So far I've seen those grey boxes on the Frontpage (For open issues and PRs, the repository and group list on the left and recent commits/actions by follows), a repository's file/folder list and README file, it's issue/PR page and the issue/PR itself.

This seems to also happen randomly as I sometimes don't get it and after a page refresh does it appear again.

**Screenshots**
Frontpage:
![image](https://user-images.githubusercontent.com/11576465/99522009-6a95cc00-2995-11eb-8929-c3ab21756f9e.png)

Repository:
![image](https://user-images.githubusercontent.com/11576465/99521523-cdd32e80-2994-11eb-839b-b08e0adee246.png)

Issues/PRs:
![image](https://user-images.githubusercontent.com/11576465/99522135-91540280-2995-11eb-8460-f797b7e8c054.png)

**System info:**

- OS: Windows 10
- Browser: Microsoft Edge 86.0.622.69
- Darkreader Version: 4.9.22 (With v5 preview enabled)

**Additional context**

**Comment by Gusted** [comment]
#4182 check that issue.

**Comment by Andre601** [comment]
And you choose the issue created after this one because....?

**Comment by Gusted** [comment]
I got 2 emails and checked the first one thst stated this issue and simply commented on it and pinned it after thst I checked the second one which was this. If I saw this issue at first this was the pinned one

**Comment by alfoltran** [comment]
Same here.

    OS: Microsoft Windows 10 Pro (10.0.19042 Build 19042)
    Browser: Firefox 83.0 (64-bit)
    Darkreader Version: 4.9.23
