### ISSUE TITLE
[Performance] Vinted.nl (possibly vinted.com as well)

### ISSUE THREAD

**Issue by natbrood** [darkreader/darkreader#4186]
**Website**
https://www.vinted.nl/
https://www.vinted.com/

**How to Reproduce**

> 1. Go to Vinted.nl
> 2. Go create a search query, like, clothes: pants | brand: Levi's or something
> 3. Keep scrolling and notice CPU spiking more and more
> It seems worse when you use Filter and Filter+

**Performance Profiler**
I could probably supply it if I knew what it was 

**System info:**

- OS: Win10 - Version 2004
- Browser: Brave (Chromium based)
- Dark Reader Version: 4.9.22

**Comment by Gusted** [comment]
Hi @natbrood!

Does this CPU spikes happens with any other browser?
Does this CPU spike any remotely happen without Dark Reader on?
Do you have hardware acceleration enabled?

I wasn't able to reproduce this cpu spike only understandable CPU Usage around 5%.

Regards,
Gusted
