### ISSUE TITLE
[Broken Website] Differencebetween.net

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#4188]
**Website**
http://www.differencebetween.net/technology/software-technology/difference-between-gplv2-and-gplv3/

**Screenshots**

![Screenshot_2020-11-18-21-46-48-63_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/99586155-9c378300-29e7-11eb-9179-6dba1f537d49.jpg)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] Android
- Browser: [e.g. chrome, safari] Firefox
- Darkreader Version: [e.g. 4.9.9] current

**Additional context**

**Comment by Yash-Singh1** [comment]
@ShalokShalom Do you have `DarkReader` enabled and `differencebetween.net` removed from the site list?

**Comment by ShalokShalom** [comment]
I have no sitelist and yes, it is enabled. Do you have different results?

**Comment by Yash-Singh1** [comment]
I did have different results on desktop:
![Screenshot from 2020-11-19 09-08-21](https://user-images.githubusercontent.com/53054099/99699609-fddb0a00-2a46-11eb-8ce5-556640b60622.png)
Does this bug happen specifically on this site or also on others?

**Comment by ShalokShalom** [comment]
Just on this site. Maybe a bug in the Firefox plugin? 
It just changed its entire rendering engine. Could that be?

**Comment by Gusted** [comment]
Hey @ShalokShalom!

Which Firefox release branch do you exactly use e.g. Nightly or Beta.

Regards,
Gusted

**Comment by ShalokShalom** [comment]
The default, stable one.

**Comment by Gusted** [comment]
Reproduce-able on Stable/Beta/Nightly. Doesn't seems to be an regression. As this requires some mobile debugging I will take a look later.

Regards,
Gusted

**Comment by Gusted** [comment]
Couldn't debug properly also Firefox didn't seems to show where the CSS that's causing it was coming, neither did dark reader really... I only know it works after an On/Off, so just replicating the behaviour should fix it.

Regards,
Gusted
