### ISSUE TITLE
[BUG] WSL local URI's ignored

### ISSUE THREAD

**Issue by mcandre** [darkreader/darkreader#4191]
### **Describe the bug**

URIs for Windows Subsystem for Linux (`wsl$/<distribution>`..., URI-encoded as `wsl%24/<distribution>/`...) appear to be ignored by Dark Reader. No amount of toggling gets local Doxygen HTML files to properly darken.

### **Steps to reproduce**

- Launch WSL.
- Produce documentation with `doxygen`.
- Launch file://wsl%24/Ubuntu/home/andrew/go/src/github.com/mcandre/toys/c/args/doc/html/index.html or similar doxygen report.

### **Expected behavior**

The documentation appears in dark mode.

### **Actual behavior**

The documentation is light mode.

### **System Information:**

- OS: Windows 10
- Browser: Chrome 86
- Dark Reader version: 4.9.22

**Comment by Yash-Singh1** [comment]
Try the following:
```
Go to chrome://extensions
Press Details underneath DarkReader
Enable access of file://* urls
```
This will allow DarkReader to darken `file://*`

**Comment by Gusted** [comment]
Enable local files as instructed in the previous comment.
