### ISSUE TITLE
[Broken Website] Google drive pdf viewer

### ISSUE THREAD

**Issue by unbeatable-101** [darkreader/darkreader#4209]
**Website**
https://drive.google.com/file/d/1M6V3HAKnl7wPAn7s57b93x_hKRC8daFz/view

**How to Reproduce**
Steps to reproduce the behaviour:
An example of this is
>
> 1. Go to x site
> 2. Look at the icons
> 3. See that that they are all weird

**Expected behaviour**
The icons look the same as when Darkreader is disabled

**Actual behaviour**
They don't appear properly

**Screenshots**
Enabled
![image](https://user-images.githubusercontent.com/58151048/99838968-f8112180-2b37-11eb-831e-7ff050cddd25.png)
Disabled
![image](https://user-images.githubusercontent.com/58151048/99839119-34dd1880-2b38-11eb-9a2a-10c604b22f3c.png)

**System info:**

- OS: Windows 20H2
- Browser: Firefox 84b3
- Darkreader Version: 4.9.24

**Comment by Gusted** [comment]
Hi @unbeatable-101 !

Do you have anything changed to the screen settings e.g. zoom or scaling?

Regards,
Gusted

**Comment by unbeatable-101** [comment]
> 
> 
> Hi @unbeatable-101 !
> 
> Do you have anything changed to the screen settings e.g. zoom or scaling?
> 
> Regards,
> Gusted

No, but I am in a window, not full-screen.

**Comment by Gusted** [comment]
Hmm, weird.

I made a fix for the icons as they wouldn't display at first actually, does this problem occur when you enable Dark Reader for private window and go to it? Also do you have any `about:config` changes for Firefox?

Regards,
Gusted

**Comment by unbeatable-101** [comment]
![image](https://user-images.githubusercontent.com/58151048/99843811-209d1980-2b40-11eb-8096-70d251711c2d.png)
I tried a fresh profile and the icons at the bottom don't show at all, but the top ones are fine. I do have `about:config` tweaks and am currently looking through to see which ones I have, I'll test some and see what happens.

**Comment by Gusted** [comment]
Woops, thanks for noticing.
Probably forgot there were bottom icons when I made the fix for the toolbar only.
#4210

**Comment by Rakleed** [comment]
Also, when clicking on the three dots in the upper right corner, the same problem is present.

**Comment by Gusted** [comment]
#4219

**Comment by Rakleed** [comment]
@Gusted
```
CSS

div[role="menu"] > div[role="menuitem"] > div > div {
    background-image: url('//ssl.gstatic.com/docs/common/viewer/v3/v-sprite33.svg') !important;
}
```
rule breaks the icons at the top in the middle when you click on the arrow next to "Open with."

Also, when you click on the "Add a shortcut to Google Drive" icon in the upper right corner, some icons are incorrectly inverted.

**Comment by Gusted** [comment]
#4231

**Comment by Rakleed** [comment]
I reset all the rules in Dev Tools, copied the rules for drive.google.com, drive.google.com/file and drive.google.com/picker from the last commit https://github.com/darkreader/darkreader/commit/de2c121c9c7c805c121caa24356e20548fe65d36, but in the upper right corner, when I clicked on three dots, the icon is still dark.

<details>
<summary>Rules</summary>

drive.google.com

INVERT
img[src$="google_gsuite"]
div[role="menuitem"] svg

IGNORE INLINE STYLE
div[role="presentation"] svg

================================

drive.google.com/file

INVERT
div[role="menu"] > div[role="menuitem"] > div > div > div

CSS
div[role="toolbar"] div[role="button"] > div[class*='-']:not([onclick]):not(:link):not(:visited):not([style*="background-image"]):first-child,
div[role="toolbar"] div[role="button"] > div[class*='-']:not([onclick]):not(:link):not(:visited) > :nth-child(2) > div,
div[style="bottom: 0px;"] > div[style^="opacity:"] div[role="button"] > div:not([onclick]):not(:link):not(:visited),
div[role="menu"] > div[role="menuitem"] > div > div:not([style*="background-image"]) {
    background-image: url('//ssl.gstatic.com/docs/common/viewer/v3/v-sprite33.svg') !important;
}

================================

drive.google.com/picker

INVERT
div[role="menu"] div[role="menuitem"]:not([class*=" "]) > div > div > div
div[role="button"][tabindex="0"]

CSS
div[role="menu"] div[role="menuitem"][class*=" "] > div > div > div,
div[role="button"][aria-disabled="true"] > div {
    filter: invert(50%) !important;
}

IGNORE INLINE STYLE
svg[class=""]
svg[class=""] *

================================

</details>

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/99911312-86d29980-2d04-11eb-8115-2bd09e42675c.png)

</details>

**Comment by Gusted** [comment]
#4239
