### ISSUE TITLE
[BUG] Google Search 'blurbs' are not affected by extension

### ISSUE THREAD

**Issue by CurtisTD** [darkreader/darkreader#4218]
### **Describe the bug**

On occasion, when using Google search, the 'blurbs' appear white and are unreadable.

### **Steps to reproduce**

Doesn't always happen, but when searching anything on Google that results in one of these 'blurbs'.

### **Expected behavior**

These 'blurbs' to match the surrounding color scheme/dark theme.

### **Actual behavior**

These blurbs appear white and are unreadable.

### **Screenshots**

![image](https://user-images.githubusercontent.com/20627159/99867451-91b3ef80-2b87-11eb-8fc2-590572459e10.png)

### **System Information:**

- OS:Windows 10
- Browser: Firefox 82.0.3
- Dark Reader version: 4.9.24

### **Additional context**

Again, this only happens on occasion. Doesn't seem to be always reproducible. Not sure of the underlying cause.

**Comment by Gusted** [comment]
Hi @CurtisTD!

Do you have any custom settings?

Regards,
Guste

**Comment by CurtisTD** [comment]
@Gusted 

Hey there, the only thing I remember changing was the color that it changes too. Maybe also the sliders in the drop-down. Are there any specific settings you mean?

**Comment by nathanielcwm** [comment]
I'm experiencing the same issue with no settings changes.

**Comment by nathanielcwm** [comment]
Weird now it appears to be fine.

**Comment by nathanielcwm** [comment]
Wait nvm featured snippets are still borked.

**Comment by Gusted** [comment]
I need a exact link for this as it's working for me fine.

**Comment by CurtisTD** [comment]
Like I said, it doesn't always happen. Refreshing seems to fix it. Can't seem to find a pattern for it.

**Comment by a-hwang** [comment]
Also experiencing this issue occasionally. Refreshing seems to solve

**Comment by Gusted** [comment]
Unfortunately I don't use google as daily driver. Can anyone provide an URL where I can *possible* reproduce this error?

**Comment by turkeydonkey** [comment]
@Gusted https://www.google.com/search?client=firefox-b-1-d&q=dark+reader (see the "People also ask" section)

It appears to happen consistently unless I bypass the browser cache with shift reload, at which point I get the expected behavior. Also touching most any of the dark reader controls updates the element colors to match the rest of the page.

![image](https://user-images.githubusercontent.com/245169/100029801-e4b7bd80-2da6-11eb-8e22-a29b23c7a7b0.png)

**Comment by Gusted** [comment]
Hmm, I made around 100 refresh with different scenario's
- Disabling caching.
- Throttling network activity.
- Changing rendering.

It gave me this white `blurbs` ~5 however for a split second and then it got darkend like intended.
It might be due some CORS issue, a new release is planned SOON and has an workaround for this kind of issue.
Hopefully it will fix this one as well.

Regards,
Gusted

**Comment by Gusted** [comment]
Hey!

Out of nowhere I actually got this bug on another machine and it confirmed one of my thoughts, that it was causing an CORS error
![image](https://user-images.githubusercontent.com/25481501/100215748-50b23700-2f09-11eb-851c-10a48d310c41.png)
#4270 resolves this issue and an new update v4.9.25 has been made and is currently under review by the web stores and should be available shortly, in fact I just checked and chrome has the newest version available. 

Regards,
Gusted
