### ISSUE TITLE
[Broken Website] miro.com boards

### ISSUE THREAD

**Issue by sxiii** [darkreader/darkreader#4226]
**Website**
https://miro.com

**How to Reproduce**
>
> 1. Create brainwriting board
> 2. It will be whole white

**Expected behavior**
It should be black or dark with dark mode.

**Actual behavior**
The color does not change to black.

**Screenshots**
https://imgur.com/a/WS1yQ9r

**System info:**

- OS: Manjaro Linux 20.2 - Nibia
- Browser: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Darkreader Version: 4.9.24

**Comment by MartinRistov** [comment]
Issue still persist even on latest version installed on Jan 10 2023, the PR referenced earlier did not fix the issue.
