### ISSUE TITLE
[Broken Website] Google Drive Icons issue

### ISSUE THREAD

**Issue by sarveshraj** [darkreader/darkreader#4227]
**Website**
https://drive.google.com/

**How to Reproduce**
An example of this is
>
> 1. Go to Google Drive
> 2. Log in and go to any folder
> 3. Notice the `List view` and `View details` buttons on the top right
> 4. They both have an overlay of a link icon

**Expected behavior**
Original icons should be visible

**Actual behavior**
Both icons have an overlay of a different icon

**Screenshots**
<img width="1792" alt="Screenshot 2020-11-22 at 11 37 15 AM" src="https://user-images.githubusercontent.com/35839390/99896634-57963b00-2cb8-11eb-9f8b-373c0463258a.png">

**System info:**

- OS: MacOS Catalina 10.15.7
- Browser: Firefox 81.0.1
- Darkreader Version: 4.9.24

**Additional context**
A quick inspection using dev tools showed me the CSS which was responsible for this overlapping icon. I have highlighted the same in the screenshot. Toggling the `background-image` property removes the overlapping icon.

**Comment by Gusted** [comment]
Fixed by #4219
