### ISSUE TITLE
[Broken Website] matomo.org

### ISSUE THREAD

**Issue by WeGiao** [darkreader/darkreader#4229]
**Website**
https://matomo.org/
https://matomo.org/100-data-ownership/
https://matomo.org/privacy/

**There are many similar pages ...**

**Screenshots**
### page: `https://matomo.org/`
![](https://cdn.jsdelivr.net/gh/WeGiao/ImageHost/PicGo/img/20201122190106.png)
![](https://cdn.jsdelivr.net/gh/WeGiao/ImageHost/PicGo/img/20201122190301.png)
![](https://cdn.jsdelivr.net/gh/WeGiao/ImageHost/PicGo/img/20201122190422.png)

### page: `https://matomo.org/100-data-ownership/`
![](https://cdn.jsdelivr.net/gh/WeGiao/ImageHost/PicGo/img/20201122190543.png)

### page: `https://matomo.org/privacy/`
![](https://cdn.jsdelivr.net/gh/WeGiao/ImageHost/PicGo/img/20201122190637.png)

**System info:**

- OS: Windows
- Browser: chrome
- Darkreader Version: 4.9.24

**Additional context**

**for which I wrote a repair code:** 
```
================================

matomo.org

INVERT
img[alt*="WordPress"]
img[src*="Mailfence"]
img[src*="sampling"]
img[src*="logo"]
img.mega-menu-logo

CSS
select, .elementor-text-editor, .elementor-text-editor *,
.elementor-blockquote *, .elementor-testimonial *,
.elementor-price-table * {
    color: #b3aca2 !important;
}

.elementor-card-shadow-yes .elementor-post__card:hover {
    box-shadow: rgb(76 75 75 / 42%) 0px 0px 30px 0px;
}
.elementor-card-shadow-yes .elementor-post__card {
    box-shadow: rgb(0 0 0 / 23%) 0px 0px 10px 0px;
}

```

**Comment by Gusted** [comment]
Hi @WeGiao!

It seems like you quite figured out an CSS fix for this, you can open up an PR to edit https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config and add this fix.

Regards,
Gusted

**Comment by Gusted** [comment]
#4235
