### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by deepesh-meena** [darkreader/darkreader#4230]
**Website**
https://www.quora.com/What-is-github-com

**How to Reproduce**
An example of this is
>
> 1. Go to any asked quora question through google or any other search engine
> 2. The first answer is white upto some point and then the rest of website has dark theme applied
**Expected behavior**
A Uniform dark mode that normally is applied on answers below the question.

**Actual behavior**
First answer/ answer on top most is white with faded black font upto to some length and then rest of the answer and the following answers are dark as expected.

**System info:**

- OS:  Windows10 20H2
- Browser: Microsoft Edge
- Darkreader Version: 4.9.22

**Additional context**

**Comment by Gusted** [comment]
Hi @deepesh-meena!

It seems like Dark Reader for Edge is still on 4.9.22 whereby the new version 4.9.24 is still under review. I wasn't able to reproduce this on Chromium/Firefox and seems most likely fixed in the newest version. Could you check for this as well?

Regards,
Gusted

**Comment by deepesh-meena** [comment]
Ok, as Edge allows to install extension from chrome store as well, so I tried installing from it and it worked perfectly well maybe its just because the version is old on microsoft store. Could you update it for ms store and does chrome store version is generally released first as compared to others??

**Comment by Gusted** [comment]
>  Could you update it for ms store 

> whereby the new version 4.9.24 is still under review. 

> does chrome store version is generally released first as compared to others??

Actually Firefox is, but generally every store is updated within a matter of days.
