### ISSUE TITLE
[Performance] 

### ISSUE THREAD

**Issue by nulh** [darkreader/darkreader#4241]
**Website**
If applicable, the link of the website where the performance issue is noticed.

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Go to x feature
> 3. Notice spikes in CPU Usage

**Performance Profiler**
A link to either profile.zip *Chromium only* or a firefox profiler *Firefox only*.

**System info:**

- OS: [e.g. Windows, MacOS, Linux]
- Browser: [e.g. chrome, safari]
- Dark Reader Version: [e.g. 4.9.9]

**Comment by Gusted** [comment]
Don't create unnecessary issues
