### ISSUE TITLE
[BUG] Other sites break when new sites are added to the disabled sites list

### ISSUE THREAD

**Issue by a-hwang** [darkreader/darkreader#4245]
### **Describe the bug**

Tabs previously darkened break when a site is added to the disabled sites list. The issue seems to occur when many extensions are added. The only workarounds are to reload the broken page or disable and renable the entire extension.

### **Steps to reproduce**

- Install many addons (10-20+)
- Open two different sites
- Disable Dark Reader for one specific site (add to disabled sites list)

### **Expected behavior**

Non-disabled site should either automatically readjust itself or remain unchanged. This behavior occurs regularly when few addons are installed. After testing, no specific addon seemed to conflict with Dark Reader.

### **Actual behavior**

Non-disabled site breaks, and Dark Reader fails to "refresh" the style automatically.

### **Screenshots**

[Site 1 (Pre-disabling)](https://i.imgur.com/LWu85iX.png)
[Site 2 (Pre-disabling)](https://i.imgur.com/InDMZ7Y.png)

I then add Google to the disabled sites list.

[Site 1 (Post-disabling)](https://i.imgur.com/TtoG5Cd.png)
[Site 2 (Post-disabling)](https://i.imgur.com/sDml6aL.png)

### **System Information:**

- OS: Windows 10 Pro 20H2
- Browser: Firefox 83.0
- Dark Reader version: 4.9.24

### **Additional context**

List of addons currently in use:
- Bitwarden
- Buster: Captcha Solver for Humans
- Bypass Paywalls
- Dark Reader
- Disable Page Visibility API
- Firefox Multi-Account Containers
- Hide Private Mode
- Honey
- inlineDisposition Reloaded
- Nano Defender for Firefox
- Nuke Anything
- Old Reddit Redirect
- Quora Login Bypass
- Reddit Comment Collapser
- Reddit Enhancement Suite
- Reddit Scammer Labeler
- SoundFixer
- SponserBlock for YouTube
- Tap to Tab
- Translate Web Pages
- uBlock Origin
- Universal Bypass
- Violentmonkey

**Comment by Gusted** [comment]
Hi @a-hwang!

Just to make sure if the add-ons are really the issue, could you allow Dark Reader for private windows and check if reproduce this behaviour in an private window.

Regards,
Gusted

**Comment by a-hwang** [comment]
> 
> 
> Hi @a-hwang!
> 
> Just to make sure if the add-ons are really the issue, could you allow Dark Reader for private windows and check if reproduce this behaviour in an private window.
> 
> Regards,
> Gusted

I opened a brand new Firefox profile and installed only Dark Reader. I didn't receive any errors, and when I added a site to the disabled sites list, other pages (such as Site 2 in my initial post) appeared broken as shown in the example but recycled themselves after a split second. As I added more addons, I noticed that it took gradually longer for the sites to "refresh", until I eventually reached a point where they stopped refreshing entirely. I enabled and disabled a wide variety of addons to make sure it wasn't conflicting with a specific addon, and I found that this wasn't the case.

**Comment by Gusted** [comment]
Hmm, that's weird and seems to be some sort of performance issue within Firefox as we have currently no known conflicts with other add-ons and should work nice along side. Just out of curiosity, does this happen on v82? I've noticed v83 had some changes in the webExtension behaviour.

**Comment by a-hwang** [comment]
> 
> 
> Hmm, that's weird and seems to be some sort of performance issue within Firefox as we have currently no known conflicts with other add-ons and should work nice along side. Just out of curiosity, does this happen on v82? I've noticed v83 had some changes in the webExtension behaviour.

This issue has persisted for a few months, and I only recently updated to 83.0 a few days ago. I'm experiencing similar issues on my laptop as well. I have not tested whether this issue exists in Chrome, but it honestly isn't something I'd be willing to migrate to Chrome over.

**Comment by Gusted** [comment]
> I have not tested whether this issue exists in Chrome, but it honestly isn't something I'd be willing to migrate to Chrome over.

If chrome doesn't have this issue, something inside Firefox is causing this and an Mozilla developer should take a look at it.

**Comment by a-hwang** [comment]
> 
> 
> > I have not tested whether this issue exists in Chrome, but it honestly isn't something I'd be willing to migrate to Chrome over.
> 
> If chrome doesn't have this issue, something inside Firefox is causing this and an Mozilla developer should take a look at it.

Interestingly, after I upgraded my PC to the 5900X from a 2600, the issue no longer seems to exist. I wouldn't quite call the 2600 an incapable chip, but perhaps it was my system lagging behind after all.

**Comment by Gusted** [comment]
> Interestingly, after I upgraded my PC to the 5900X from a 2600, the issue no longer seems to exist. I wouldn't quite call the 2600 an incapable chip, but perhaps it was my system lagging behind after all.

Well second generation didn't seem a success in my eyes, mostly because of some performance issues, however congrats on 5900x take good care of it :D
