### ISSUE TITLE
[BUG] Regression: Cannot load `darkreader` with Webpack

### ISSUE THREAD

**Issue by meeq** [darkreader/darkreader#4252]
### **Describe the bug**

As of https://github.com/darkreader/darkreader/pull/4107 I get the following error in my Webpack build:
```
Module not found: Error: Can't resolve 'darkreader' in 'lib/dark-mode.js'
```

### **Steps to reproduce**

- In a Webpack project...
- Integrate `darkreader` as described in [README: Using for a website](https://github.com/darkreader/darkreader#using-for-a-website) using ES Modules
- Run Webpack to create bundled JS containing `darkreader`

### **Expected behavior**

Webpack can find and bundle the `darkreader` module

### **Actual behavior**

Webpack cannot find the `darkreader` module

**Comment by meeq** [comment]
Suggested fix: Revert https://github.com/darkreader/darkreader/pull/4107

**Comment by Gusted** [comment]
Hi @meeq!

I've reverted the commit, please use an local build for now(documented how to in the readme.me) until the next release.

Regards,
Gusted
