### ISSUE TITLE
Hi @mikerouxfr!

### ISSUE THREAD

**Issue by nulh** [darkreader/darkreader#4269]
Hi @mikerouxfr!

The fix should be made to https://github.com/darkreader/darkreader/blob/master/src/config/inversion-fixes.config

Regards,
Gusted

_Originally posted by @Gusted in https://github.com/darkreader/darkreader/pull/4262#issuecomment-733067197_

**Comment by alexanderby** [comment]
You are banned now.

**Comment by mikerouxfr** [comment]
> You are banned now.

Me?

**Comment by alexanderby** [comment]
@mikerouxfr No, that strange spam bot, that opens issues an copies text from somewhere.

**Comment by mikerouxfr** [comment]
Okay thanks. Had a doubt 😅
