### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JadenJSJ** [darkreader/darkreader#4275]
### **Describe the bug**
The bug is that Google looks like this
![image](https://user-images.githubusercontent.com/44781632/100178340-4478aa80-2f06-11eb-894b-3ddde9fddac6.png)
![image](https://user-images.githubusercontent.com/44781632/100178774-35dec300-2f07-11eb-9e8e-b81f4ec938b4.png)
![image](https://user-images.githubusercontent.com/44781632/100178938-8d7d2e80-2f07-11eb-9078-83cd51cb039d.png)

And some other sites break and don't even use darkmode and the text becomes invisible

### **Steps to reproduce**
Use chrome canary with no flags and and it will still happen on icognito (With the extentioned allowed there)

Google Chrome 89.0.4335.0 (Official Build) canary (64-bit) (cohort: Clang-64)
Revision 4fffcbfd3db5e925d543f8ee49774c91d82c477f-refs/branch-heads/4335@{#1}
OS Windows 10 OS Version 2009 (Build 19042.630)

### **Expected behavior**
The expected result is
![image](https://user-images.githubusercontent.com/44781632/100178570-b4873080-2f06-11eb-9f18-8dcb3edbeecf.png)
^ Using Chrome Stable

It was working fine until tile last canary update

**Comment by JadenJSJ** [comment]
I also have a request but ill just put it here.
Maybe a style to disable darkreader?
So if the website/server has
darkreader { enabled: false}
dark reader wont make the site dark mode because my site has darkmode built in and with dark reader ill kinda loom gray

**Comment by Gusted** [comment]
dup #4246
