### ISSUE TITLE
[Dynamic] engadget.com

### ISSUE THREAD

**Issue by vaindil** [darkreader/darkreader#428]
A white background is set by `.th-base` on engadget.com ([here's an example post](https://www.engadget.com/2018/04/27/windows-10-s-next-major-update-arrives-on-april-30th/)). I know that's the selector that causes the background but I couldn't get any rules to work to fix the problem. This is with the dynamic filter.

**Comment by joshsleeper** [comment]
Beat you to the report in #395! ;)
I'd suggest closing this as a dupe and just add your comment to that.
