### ISSUE TITLE
[Feature Request] Add a list of websites which follows device theme

### ISSUE THREAD

**Issue by kidonng** [darkreader/darkreader#4297]
**Is your feature request related to a problem? Please describe.**
More and more websites are using the `prefers-color-scheme` query to allow following device's color theme. The most prominent one I can think of is YouTube (and now GitHub!). Most of the time these websites don't need Dark Reader and we need to turn it off every time we encounter a new one.

**Describe the solution you'd like**
We now have a list of dark websites that are excluded by default, could **we also have a similar list of websites that follows the device color scheme by default?** These websites should (in my opinion) be disabled by default as well.

**Additional context**
There are many websites that provide light and dark themes but don't follow the device theme automatically ~~(such as Notion)~~, I'd also like to have a list of these kinds of websites since I tend to use their own dark theme.
**What if we can have something like "presets"? (like uBlock)** Users can choose to disable Dark Reader on different presets of websites, so the built-in list becomes "Websites that are already dark", and the requested list becomes "Websites that follow device theme" and "Websites that provide dark theme".

**Comment by kidonng** [comment]
@Gusted Kinly bumps :)

**Comment by Gusted** [comment]
Hmm, more lists? No
Less performance due to more list checking? Please no.
Better solution? See, #5719 It will mitigate all this list away.

**Comment by kidonng** [comment]
> Hmm, more lists? No
> Less performance due to more list checking? Please no.

Fair point. I can see this is also added maintenance burden...

> Better solution? See, #5719 It will mitigate all this list away.

Awesome! Then I'll close this issue if it spots the darkness well 👀

**Comment by Gusted** [comment]
> Awesome! Then we can close this issue if it spots the darkness well eyes

Yep! I'm working on making it work with the current dark list and later on detect if the pages changes from color and act onto it.
