### ISSUE TITLE
[Broken Website] Scribd.com/document

### ISSUE THREAD

**Issue by dexeonify** [darkreader/darkreader#4303]
**Website**
Any Scribd Document will work, like:
https://www.scribd.com/document/43513379/Video-Streaming

**How to Reproduce**
> 1. Go to `https://www.scribd.com/document/*`
> 2. Issue occurs.

**Expected behavior**
Text should be white in colour or opposite to the dark background.

**Actual behavior**
The background of the document turns dark correctly, but the texts also stay dark, so it's unreadable.

**Screenshots**
![image](https://user-images.githubusercontent.com/72267349/100493629-d33e2f00-3173-11eb-92eb-714347186d4a.png)

**System info:**

- OS: Windows 10
- Browser: Firefox 83.0 (64-bit)
- Darkreader Version: Version 4.9.25

**Additional context**
This is with Dynamic theme btw.

![image](https://user-images.githubusercontent.com/72267349/100493682-4e074a00-3174-11eb-95c2-4d733c50844f.png)
For some reasons, dark reader worked as expected in the blurred part of the document. But that's not very helpful is it ;)

**Comment by Gusted** [comment]
Hi @dexeonify!

It seems like #1003 was on purpose inverting the text, however I don't see a useful use case for this so.
So I'm removing it and should be a good to go then.

Regards.
Gusted

**Comment by symphonymarie** [comment]
It looks like this issue has returned.

<img width="601" height="596" alt="Image" src="https://github.com/user-attachments/assets/6109b0b0-d3b1-42a8-97cf-f66a83c4b74f" />
