### ISSUE TITLE
[Broken Website] docs.microsoft.com

### ISSUE THREAD

**Issue by Demonese** [darkreader/darkreader#4307]
**Website**
docs.microsoft.com

**How to Reproduce**

> 1. visit any "docs.microsoft.com" website, set style to "Dark"
> 2. download DarkReader, and switch to OFF or add docs.microsoft.com to block list (because it has built-in dark mode)
> 3. F5 refresh website

**Expected behavior**
Dark theme
![image](https://user-images.githubusercontent.com/57629614/100521359-2b118000-31de-11eb-8d3f-f87c4e2dca5f.png)

**Actual behavior**
High Contrast theme (why?)
![image](https://user-images.githubusercontent.com/57629614/100521458-a70bc800-31de-11eb-8c81-b28710ba6f62.png)

**Screenshots**
see above

**System info:**

- OS: Windows 20H2 19042.630
- Browser: Microsoft Edge 87.0.664.47
- Darkreader Version: 4.9.25

**Additional context**
Turn OFF DarkReader or add docs.microsoft.com to block list didn't takes effect. I have to disable or remove DarkReader.
![image](https://user-images.githubusercontent.com/57629614/100521499-079b0500-31df-11eb-9187-0d0751730f15.png)
![image](https://user-images.githubusercontent.com/57629614/100521764-9b210580-31e0-11eb-8f8d-21834fa39560.png)

**Comment by Gusted** [comment]
#3618 dup
