### ISSUE TITLE
[Feature Request] Provide opt-in HTML mechanism to indicate that my website is already dark

### ISSUE THREAD

**Issue by phoenixeliot** [darkreader/darkreader#4325]
**Is your feature request related to a problem? Please describe.**
Normally the 'disable for site' functionality solves this problem, but I'm using the [Majestic](https://github.com/Raathigesh/majestic) local Jest GUI, and it opens on a random port every launch. So while Majestic is dark mode by default, this extension inverts it and causes it to become light mode very time I launch Majestic.

And I know I can do the workaround of forcing the port to a certain value with the Majestic CLI, but I think this problem has broader applicability. It would be nice for general website developers to be able to indicate to this extension that the site is already dark, so users don't have to fiddle this extension on/off quite so often while browsing the web.

**Describe the solution you'd like**
I would love to have some kind of HTML attribute I can put on the root, or meta tag I can add to the head, or something, that I can add to a page to tell this extension that the page is _already_ in dark mode, so the extension can automatically know not to run.

(Then, once that exists, I can submit a PR to Majestic to add that flag.)

**Additional context**

What Majestic normally looks like:
<img width="298" alt="Screen Shot 2020-11-29 at 8 14 00 PM" src="https://user-images.githubusercontent.com/491376/100564922-8b0c3300-327f-11eb-89f7-4f5fa047685c.png">

What Majestic looks like while this extension is enabled:
<img width="298" alt="Screen Shot 2020-11-29 at 8 14 14 PM" src="https://user-images.githubusercontent.com/491376/100564927-8e072380-327f-11eb-8b05-bb5e1576fa62.png">

**Comment by atwright147** [comment]
It could (if it doesn't already?) sniff for the `@media(prefers-color-scheme: dark)` CSS rule via `window.matchMedia('prefers-color-scheme: dark').matches`, more info: https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/#check-the-preferred-theme-using-javascript-

That would offer a more universal solution. Does Majestic use this CSS rule?

**Comment by Gusted** [comment]
> It could (if it doesn't already?) sniff for the `@media(prefers-color-scheme: dark)` CSS rule via `window.matchMedia('prefers-color-scheme: dark').matches`, more info: https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/#check-the-preferred-theme-using-javascript-

It's very unreliable because big sites tends to use it, but have it also not in use, you won't know if that CSSrules when activated for `prefers-color-scheme: dark` what content will be dark.

Currently having `<meta name="darkreader" content="SOME UID">` inside the head element however this is unreliable, as dark reader often begins before the head element is even loaded... However some ideas has been posted https://github.com/darkreader/darkreader/pull/2855#issuecomment-713040345 and the general Issue about this #1285 as this requests for an opt-in HTML mechanism it doesn't seems to be a duplicate and left it open.

**Comment by atwright147** [comment]
That sucks :(

I have added more suggestions here: https://github.com/darkreader/darkreader/pull/2855#issuecomment-741118499
