### ISSUE TITLE
[Broken Website] alexn.org

### ISSUE THREAD

**Issue by alexandru** [darkreader/darkreader#4330]
I updated my website [alexn.org](https://alexn.org) to support a dark theme via a `@media (prefers-color-scheme: dark)` query.

Unfortunately Dark Reader messes with my design. And I tried adding these tags in `<head>`, for turning Dark Reader off, but it doesn't work (after reading #1114):

```html
<meta name="darkreader" content="41637b04c7ddb955e533a5c76d68a2c8">
<meta name="color-scheme" content="light dark">
```

Looking at this repository, I see there's a [dark-sites.config](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config) file, but it doesn't apply, since these websites seem to have a dark theme by default.

So how can I prevent Dark Reader from messing with my own dark theme?

PS: [twitter.com](https://twitter.com/) is another example with a theme that's changed by Dark Reader, even if they support a proper dark theme, and on Android the menu icons are gone.

PPS: thank you for all your hard work ❤️

---

**UPDATE** 

Tested with:

- Firefox 83.0 + 84.0b6 (Developer Edition)
- Chrome 87.0.4280.67

Screenshot of what I'm seeing in Firefox, on the desktop:

<https://user-images.githubusercontent.com/11753/100605126-21883500-3310-11eb-93f2-1f680ddd1aa6.png>

Screenshot of Firefox for Android:

<https://user-images.githubusercontent.com/11753/100605448-9c515000-3310-11eb-8deb-21ae9722b8af.jpg>

Here's the current design with Dark Reader off, which is what I expect to see, notice the colors:

<https://user-images.githubusercontent.com/11753/100605561-c571e080-3310-11eb-8c7d-3a24aa0c8f01.png>

**Comment by Gusted** [comment]
Hi @alexandru!

In the most scenario's currently with modern browsers, extension starts before any element has been loaded(excluding html element) and therefore doesn't detect the meta ^, however it could be improved if the first element in the head is actually the `meta` one. In the current scenario their isn't really a way to do this, however I think we can improve on our side as well to detect if the `meta` is loaded later and than still disable it.

**Comment by alexandru** [comment]
Thanks for the reply,

This issue is complicated because my website now has a theme that switches based on the system's settings. But those settings might be different than Dark Reader's on/off.

1. in case the system settings is set to Dark Mode, would be good to tell Dark Reader "_trust me, I have a usable dark theme, don't do anything_"
2. in case the system settings is set to Light Mode, but Dark Reader is active, then Dark Reader could see that the website has a dark theme and enable it (via `prefers-color-scheme: dark` if possible)

I just fixed my website to be Dark Reader friendly (previously I had a background image that looked horrible when inverted). Now the scenario that I want to avoid most is for Dark Reader to darken my already dark theme.

I'm mentioning this because I'm not sure if I'd like for Dark Mode to be disabled completely for my website. An less likely, but possible scenario is for the system settings to be in Light Mode, with the user still activating Dark Reader. Maybe because the system does not have a dark mode that can be activated (this is a feature on more modern devices/platforms/versions).

So what could be done about (1) keeping Dark Reader active, while (2) avoiding double-darkening, with a preference for the website's own dark theme?

**Comment by Gusted** [comment]
> * in case the system settings is set to Dark Mode, would be good to tell Dark Reader "_trust me, I have a usable dark theme, don't do anything_"
> 
> *

I've opened up a PR(#4334) to implement a behaviour to disable Dark Reader from a website perspective by looking for `<meta name="darkreader-lock">` and if detected completely disable Dark Reader.

> So what could be done about (1) keeping Dark Reader active, while (2) avoiding double-darkening, with a preference for the website's own dark theme?

When the site's dark theme is enabled, just add that ^ meta into the DOM and when the site is showing a light theme don't have that meta in the DOM that way dark reader will still style the site when it's in a light-theme.

Regards,
Gusted
