### ISSUE TITLE
[BUG] The extension is stuck on disabled on local files if a 'C:' (or other drive) entry is present on the site list

### ISSUE THREAD

**Issue by TrianguloY** [darkreader/darkreader#4345]
### **Describe the bug**

When the site list (entries where the extension will be disabled, from settings->site list) contains the entry "C:" (or 'D:' or other drive), then on files loaded from the corresponding drive (url "file:///C:/user/something") the extension is permanently disabled and can't be toggled from the main popup toggle (the 'file:' button). More precisely, the toggle works, which removes/adds the 'file:' entry in the list, but the 'C:' entry is not removed.

### **Steps to reproduce**

- Open a local file so the url displayed is "file:///D:/user/something" (the steps assume the drive is D, but also works with other drives). The extension is enabled and turns the page dark.
- Open the Dark reader popup, press 'Settings' then 'Site list'
- Add 'D:' as a new entry, the extension will be disabled in the current file.
- Go back to the main menu (or close/reopen).
- Click the 'x file:' button (the toggle on/off) to enable the extension.

### **Expected behavior**

The extension is enabled on the current page

### **Actual behavior**

The extension is kept disabled, the button does nothing

### **Screenshots**

![imagen](https://user-images.githubusercontent.com/10616202/100789200-6bf3d980-3416-11eb-9cbc-4e6ac02b1cb4.png)

![imagen](https://user-images.githubusercontent.com/10616202/100788194-094e0e00-3415-11eb-9ec3-6648be45bc01.png)

### **System Information:**

- OS: Windows 10 (V 1909)
- Browser: Firefox 83.0 (64-bit)
- Dark Reader version: 4.9.26

### **Additional context**

The bug can be fixed simply by removing manually the 'D:' entry in the list.

I don't know how I managed to get the D: entry on the extension, I don't remember adding it myself. It should probably have been added in a previous dark reader version (I usually work with local files and have to toggle the extension there) but can't confirm.

Also I couldn't find any troubleshoot guide where this was explained, all I could find for 'the extension doesn't work on local files' is the chrome flag, so I also hope that if someone in the future has this same problem this could be of help.

**Comment by Gusted** [comment]
Hi @TrianguloY!

#4346 Fixes this by using the full pathname of the file instead of just `file:`.

Regards,
Gusted

**Comment by skfjirim** [comment]
Is still possible dark reader work for local files?
For me it does not work for any local html/mhtml. It hurts! :(
These workaround didn't help. I didnt have files in the list, and when I added full path of file wanted dark, nothing changed.

**Comment by Gusted** [comment]
That's another issue. Not related to this, you have to give dark reader permission for local files on chrome browsers.

Open chrome://extensions page, find Dark Reader, click Allow access to file URLs.
