### ISSUE TITLE
[Dynamic] Google Analytics' sub pages

### ISSUE THREAD

**Issue by yamlCase** [darkreader/darkreader#436]
Dark reader seems to work well on the Google Analytics home page, but click on Audience > Overview, or Real-Time > Overview and the meat is still white.

https://analytics.google.com/analytics/web

**Comment by alexanderby** [comment]
I think it was mostly fixed a week ago. I've also fixed black text color inside iFrames, it will be released soon.

Not sure, if performance became worse.
