### ISSUE TITLE
[Broken Website] github.com

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4363]
**Website**
The link to the broken website
https://github.com

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors

1. Go  to issue with thumbs up
2. Put the thumb up

**Expected behavior**
Background should differ significantly, to show that you have reacted.

**Actual behavior**
A clear and concise description of what happened.
Background differs so slightly, so it's impossible to say if you have reacted.

**Screenshots**
![image](https://user-images.githubusercontent.com/14617699/100031252-32174780-2e06-11eb-84a9-85f96bb9fe22.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

**Comment by Gusted** [comment]
Hi @532910!

Currently Dark Reader on Github is a bit broken, could you try to side-load https://github.com/darkreader/darkreader/pull/4291#issuecomment-736846310 and confirm it fixes this issue?

Regards,
Gusted

**Comment by 532910** [comment]
`build-firefox.xpi` from [Binaries.zip](https://github.com/darkreader/darkreader/files/5625688/Binaries.zip) doesn't solve this issue

**Comment by Gusted** [comment]
Hmm, weird it just tried it myself and the background changes for me. You might have still the old fix in devtools that overrides it's behaviour.

**Comment by 532910** [comment]
> background changes for me

It's different even in the screenshot above, but it differ so slightly that I can't distinguish with eyes. With color picker only. Could you say exact hex values?

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/101420804-df9c5780-38ea-11eb-8083-ce1fb031bec6.png)
Pressed also `#1c1e1f`
![image](https://user-images.githubusercontent.com/25481501/101420947-2b4f0100-38eb-11eb-84c1-ca5fd28c46f9.png)
Not pressed also `#181a1b`

It's a little and subtitle change bit weird the contrast seems to be not correct with the light mode variant.

**Comment by 532910** [comment]
> `#1c1e1f`  `#181a1b`

my screenshot has exactly the same values.

**Comment by 532910** [comment]
github now supports dark theme: https://github.com/settings/appearance
