### ISSUE TITLE
[BUG] sites that respects prefers-color-scheme should be considered dark

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4366]
### **Describe the bug**

Sites that respects prefers-color-scheme should be considered darks.

### **Steps to reproduce**

- Go to '...'
- Click on '...'
- Scroll down to '...'

Open https://duckduckgo.com/

### **Expected behavior**

Darkreader should not be used on sites that respects prefers-color-scheme

### **Actual behavior**

A clear and concise description of what actually happened.

Darkreader is used on sites that respects prefers-color-scheme

### **System Information:**

- OS: [e.g. iOS 11] doesn't related
- Browser: [e.g. Chrome 73, Safari 13] doesn't related
- Dark Reader version: [e.g. 4.9.9] 4.9.26

### **Additional context**

Example sites that respects prefers-color-scheme
https://forum.f-droid.org/
https://duckduckgo.com/
https://docs.microsoft.com/

**Comment by Gusted** [comment]
#1285
