### ISSUE TITLE
[BUG] sites that can be dark should be considered dark

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4367]
### **Describe the bug**

Sites that can be dark should be considered dark.

### **Steps to reproduce**

- Go to '...'
- Click on '...'
- Scroll down to '...'

1. Open https://www.youtube.com/
2. Set appearance dark in the settings

### **Expected behavior**

Darkreader should not be used on sites that can be dark

### **Actual behavior**

A clear and concise description of what actually happened.
Darkreader is used on sites that can be dark

### **System Information:**

- OS: [e.g. iOS 11] doesn't related
- Browser: [e.g. Chrome 73, Safari 13] doesn't related
- Dark Reader version: [e.g. 4.9.9] 4.9.26

### **Additional context**

Example sites that can be dark:
https://forum.openwrt.org/
https://www.youtube.com/
https://app.element.io/
https://stackoverflow.com/

**Comment by Gusted** [comment]
#1285
