### ISSUE TITLE
[Dynamic] Protonmail

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#437]
![screenshot_20180430_214216](https://user-images.githubusercontent.com/6344099/39447546-67f245b2-4cc2-11e8-92ce-c82848b582ee.png)

In edit mode ^

**Comment by alexanderby** [comment]
I'm not using Protonmail, but so many fixes were made. Could you please check if still happens?

**Comment by ShalokShalom** [comment]
Same story, thanks for trying

**Comment by alexanderby** [comment]
Well, then I will have to register.

**Comment by ShalokShalom** [comment]
Thanks a lot.

**Comment by alexanderby** [comment]
Looks OK.

**Comment by ShalokShalom** [comment]
Still unreadable: 
![screenshot_20181103_025533](https://user-images.githubusercontent.com/6344099/47946965-f7d36880-df13-11e8-96f9-d40bb9f66edc.png)

Can you see "DarkReader" in this case? Sure an improvement, while still uncomfortable to me. 

Thy

**Comment by tostercx** [comment]
+1, I seem to only have this problem while composing mail.

A temporary workaround is setting the background to something lighter under protonmail's settings > appearance > custom theme:

    .squire-container {
        background-color: #AAA;
    }

<img src="https://user-images.githubusercontent.com/4965387/49536598-9a925480-f8cf-11e8-9db2-823e658ff19d.png" width="320px">

**Comment by RoxKilly** [comment]
Came here to report this problem as well. Only happens when composing a new mail.

**Comment by Gusted** [comment]
![](https://i.imgur.com/hR1U6l2.png) Seems good to me
