### ISSUE TITLE
[BUG] Browser stays darkened after deletion

### ISSUE THREAD

**Issue by Hiro016D** [darkreader/darkreader#4376]
### **Describe the bug**

After deleting the extension from my chrome browser and restarting. all websites still remain darkned

### **Steps to reproduce**

- Go to Chrome Store
- Install Dark Reader
- Click on 'Dark '
- Delete Dark Reader

### **Expected behavior**

I expected the browser to revert back to its original state instead of remaining darkened

### **Actual behavior**

Browser remained darkened instead of reverting back

### **Screenshots**

![image](https://user-images.githubusercontent.com/59138407/100987564-1d565480-3568-11eb-85b5-0ec9580972ef.png)
![image](https://user-images.githubusercontent.com/59138407/100987615-2e06ca80-3568-11eb-9664-5247433cc9b9.png)

![image](https://user-images.githubusercontent.com/59138407/100987757-5bec0f00-3568-11eb-94ce-41be839f48d8.png)

### **System Information:**

- OS: Windows 10 Home
- Browser: Brave

**Comment by Gusted** [comment]
Open a issue over at brave, we can't control this neither bypass this. Totally browser bug
