### ISSUE TITLE
[Feature Request] No Flash mode

### ISSUE THREAD

**Issue by Tomatoide** [darkreader/darkreader#4385]
**Is your feature request related to a problem? Please describe.**

Some websites have built in dark modes, but when you disable dark reader on these websites, you lose the no flash functionality of dark reader.

**Describe the solution you'd like**

Add a No Flash mode to custom theme rendering modes (dynamic, static...) so when you choose it for a website the extension works on initial site load then stops as the site with its own dark mode is ready.

**Comment by Gusted** [comment]
Hi @Tomatoide!

The `No flash` CSS is always inserted into the page even disabled ones, but removed on a later stage. It might be possible that when removing this CSS the dark mode or the CSS hasn't been applied yet, It's currently not possible to watch when this changes neither to detect dark mode pages. 

Having to wait until some other CSS takes is currently technically impossible.

Regards,
Gusted
