### ISSUE TITLE
[Broken Website]  google images

### ISSUE THREAD

**Issue by revotsna1** [darkreader/darkreader#4386]
Dark Reader hides the images on google images. Oddly toggling dark mode by bernard on then off again will restore images. Issue began occurring within the last two weeks.

**Screenshots**
![goog](https://user-images.githubusercontent.com/45445445/101227200-f6df0900-368e-11eb-8665-d5910b6e2539.png)

**Additional context**
Disabling plugins that can block scripts (privacy badger) has no effect.

**Comment by Yash-Singh1** [comment]
@revotsna1:
```
Click on the dark reader icon
Click on dev tools
Click on preview new design
Click on the dark reader icon again (show the popup again)
Make sure your mode is not static (make it dynamic)
```

This issue is known for the static mode in #2941

**Comment by Gusted** [comment]
#2941 Dup
