### ISSUE TITLE
Jupyter Notebook Text Greyscale

### ISSUE THREAD

**Issue by daniel-farrell1526** [darkreader/darkreader#4388]
The text turns to greyscale in Jupyter notebook cells which hides code coloring useful for learning. Examples below:
Off
![image](https://user-images.githubusercontent.com/73511234/101234931-cea4d980-3691-11eb-82b5-890eef2acd42.png)
Darkmode
![image](https://user-images.githubusercontent.com/73511234/101234938-e11f1300-3691-11eb-9258-627e37825507.png)
Lightmode
![image](https://user-images.githubusercontent.com/73511234/101234963-19265600-3692-11eb-90b7-63517656ae71.png)

**Comment by Gusted** [comment]
Use Issue template.
