### ISSUE TITLE
[Bug, both FF&GC] Can't get "UPD" to disappear from DarkReader icon

### ISSUE THREAD

**Issue by o-l-a-v** [darkreader/darkreader#439]
I really like the new update, but theres a small issue/ bug:
If you are using same account on Chrome or Firefox across several machines, you'll only see the DarkReader update anouncement on one of those. Which leaves the other installation with a green "UPD" banner, which, with my current knowledge at least, can't be removed.

![image](https://user-images.githubusercontent.com/6450056/39476104-1bf4481a-4d5b-11e8-8abe-e6527b432b15.png)

This happened with me on both Google Chrome (v66.x) and FireFox (v59.x).

I've gone through all DarkReader menus for a way of removing it. I've also tried do disable and re-enable DarkReader, which did not help.

**Comment by alexanderby** [comment]
There will be no more pop-ups, the news section will be placed at the bottom with the highlights of important release notes or events. It will be finished in a day or two.

**Comment by alexanderby** [comment]
News section was added, if you open a link or close this section, you will not see badge with the count of unread messages on all devices with the same account.
