### ISSUE TITLE
[Broken Website] Microsoft Docs

### ISSUE THREAD

**Issue by jeremyVignelles** [darkreader/darkreader#4394]
**Website**
https://docs.microsoft.com/en-us/

Example :
https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2019

**How to Reproduce**
1. Go to the site
2. Scroll to the bottom of the site and enable the dark theme
3. See that links are in an agressive yellow shade

**Expected behavior**
This website has a feature to turn it dark. There is no need to tweak it.

**Actual behavior**
The links and buttons are all yellow.

**Screenshots**
![image](https://user-images.githubusercontent.com/3399355/101246846-08b7bf00-3716-11eb-9815-40930317ba26.png)

**System info:**

- OS: Windows 10
- Browser: firefox 84.0b8 (developer edition)
- Darkreader Version: 4.9.26

**Additional context**
Seems to occur on every page of the domain, but didn't check every doc.

**Comment by Gusted** [comment]
#3618 dup
