### ISSUE TITLE
[Broken Website] lichess.org

### ISSUE THREAD

**Issue by jeremyVignelles** [darkreader/darkreader#4395]
**Website**
https://lichess.org/tv

**How to Reproduce**
Go to the given page or any other game in play.
use right-click/shift+right click/ctrl+right click to draw arrows

**Expected behavior**
Two timer show up,
arrows shouldn't change colors (higher contrast the default way)

**Actual behavior**
with dark reader enabled, upper timer disappears and arrows are harder to read

**Screenshots**
lichess dark mode theme
![image](https://user-images.githubusercontent.com/3399355/101260140-fcd7f700-372d-11eb-883d-40713a01bda0.png)
![image](https://user-images.githubusercontent.com/3399355/101260204-77087b80-372e-11eb-8ce3-119ffebcd23d.png)

Dark reader enabled
![image](https://user-images.githubusercontent.com/3399355/101260135-f21d6200-372d-11eb-85ed-e44cf0594300.png)
![image](https://user-images.githubusercontent.com/3399355/101260210-825ba700-372e-11eb-8a15-08f5b5dd556a.png)

**System info:**

- OS: Windows
- Browser: Firefox 68 developer edition
- Darkreader Version: 4.9.13

**Additional context**
Dark/light lichess theme both behave the same. Disabled dark reader on this website.

**Comment by jeremyVignelles** [comment]
What a reactive repo, congrats and thanks for your work!

**Comment by Gusted** [comment]
No problems!
