### ISSUE TITLE
[Broken Website] instagram, github & citilink.ru in Light mode

### ISSUE THREAD

**Issue by DragonSerW** [darkreader/darkreader#4399]
macOS 10.15.7, current DR in Firefox ESR.
Citilink: https://i.ibb.co/ZSxDqMH/Screenshot-2020-12-06-at-09-38-04.png wrong colour in round buttons after 'В корзину' button.
IG: https://i.ibb.co/vV1qDrZ/Screenshot-2020-12-06-at-09-37-20.png -- all buttons are wery dark, in Mobile mode there are hard2view '+' buttons and others!
github: dark text on dark fill.

Please reply in Russian ))

**Comment by Gusted** [comment]
Use the template.
