### ISSUE TITLE
[Feature Request] Stop Dark Reader inverting pictures

### ISSUE THREAD

**Issue by Busaruba2011** [darkreader/darkreader#4402]
It annoys me all the time when Dark Reader inverts images colours. It happened to my school logo on Drive.

**Describe the solution you'd like**
Stop Dark Reader inverting images.

**Additional context**
![Screenshot (73)](https://user-images.githubusercontent.com/65495333/101278195-c8a61a00-37b1-11eb-9457-edee5c6bd080.png)
apple.com/macos/big-sur

**Comment by Gusted** [comment]
Report those sites. Completely disabling inverting images/icons will make major sites not even use-able.
