### ISSUE TITLE
[Feature Request] Filter light or dark mode based on content type

### ISSUE THREAD

**Issue by jjanedoh** [darkreader/darkreader#4405]
[Feature Request] Filter light or dark mode based on content type

I want to be able to have light mode when reading PDF document files and so forth but dark mode on other content (along with site exclusions)

Currently with dark mode enabled the PDF document looks like reading a negative image, undesirable

I want to be able to set an exclusion rule on content type (PDF in this case but not limited to just PDF)

**Comment by Gusted** [comment]
Use template.

**Comment by mariusa** [comment]
> Use template.

What do you mean? What is the solution to disable on PDF?

**Comment by mariusa** [comment]
Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.
Then

Click on Settings
Click on Site List
Disable PDF

**Comment by jjanedoh** [comment]
No such option found on it

**Comment by Gusted** [comment]
I saw in my e-mail that someone commented *deleted by now* which template I meant. I meant the template you're forced to use if you want to open up an issue, so all information can be seen in once other than having to ask certain pieces of the issue and wait for the author to respond. However I don't see any of the template back into the issue and closed it thereby as we don't handle issue who ignored the template.

**Comment by jjanedoh** [comment]
> I saw in my e-mail that someone commented _deleted by now_ which template I meant. I meant the template you're forced to use if you want to open up an issue, so all information can be seen in once other than having to ask certain pieces of the issue and wait for the author to respond. However I don't see any of the template back into the issue and closed it thereby as we don't handle issue who ignored the template.

I think it is pretty obvious what the feature request is for

**Comment by jjanedoh** [comment]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

PDF documents come out as negative images

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

Filter PDF content (or other content) from inverting by a filter like sites

**Additional context**
Add any other context or screenshots about the feature request here.

No screenshots
