### ISSUE TITLE
[Safari] ISSUE#855 NO Resolved [Mermaid Diagrams's font is too dark,but in chrome it is good] 

### ISSUE THREAD

**Issue by Leowang628** [darkreader/darkreader#4410]
https://github.com/darkreader/darkreader/issues/855
> Resolved

No Resolved, The version is APPSTORE-1.4.2，please go to this website to check：https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgQWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgQWxpY2UtPj4rSm9objogSm9obiwgY2FuIHlvdSBoZWFyIG1lP1xuICAgIEpvaG4tLT4-LUFsaWNlOiBIaSBBbGljZSwgSSBjYW4gaGVhciB5b3UhXG4gICAgSm9obi0tPj4tQWxpY2U6IEkgZmVlbCBncmVhdCFcbiAgICAgICAgICAgICIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ

**Comment by Gusted** [comment]
Use template. Also didn't notice it was safari.
