### ISSUE TITLE
[Broken Website] inspireminds.in

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4412]
**Website**
The link to the broken website

https://inspireminds.in/englishblog/1021/inspiring-story-of-jan-koum-a-college-drop-out-who-started-whatsapp.html

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Turn on dark mode
> 3. Colors and everything messes up

**Expected behavior**

Colors and everything not to mess up

The header for example is to light

**Actual behavior**
A clear and concise description of what happened.

Colors and everything messes up

**Screenshots**

![Screenshot from 2020-12-06 19-50-59](https://user-images.githubusercontent.com/53054099/101307470-6292b480-37fc-11eb-9a43-d04ac2782d60.png)

**Comment by Gusted** [comment]
Hi @Yash-Singh1!

This site is using images on almost every element. I'm not even bothering with this one to get fixed. It's recommend to use Filter(+) on this kind of sites. Dynamic is targeted for modern sites.

Regards,
Gusted
