### ISSUE TITLE
[Feature Request]Publish and subscribe blacklist/whitelist on the web

### ISSUE THREAD

**Issue by munierujp** [darkreader/darkreader#4415]
**Is your feature request related to a problem? Please describe.**

I am using Dark Reader on multiple accounts.
I'd like to synchronize blacklist/whitelist between different accounts.

**Describe the solution you'd like**
I want the feature which can publish blacklist/whitelist and subscribe to them on the web, like [uBlacklist](https://github.com/iorate/uBlacklist).

**Comment by Gusted** [comment]
Hi @munierujp!

What is the user-case for having different accounts but still syncing settings?

Regards,
Gusted
