### ISSUE TITLE
[Broken Website] sortablejs.github.io

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4427]
**Website**
The link to the broken website

https://sortablejs.github.io/sortablejs/

**How to Reproduce**
An example of this is
>
> 1. Go to the link given above
> 2. Turn on dark mode
> 3. Colors went everything breaks

**Expected behavior**

Colors there nothing breaks

**Actual behavior**
A clear and concise description of what happened.

Colors went everything breaks

**Screenshots**

![Screenshot from 2020-12-07 18-56-28](https://user-images.githubusercontent.com/53054099/101432560-eeb8e080-38bd-11eb-84bb-fd2452b694df.png)

However, filter mode makes it better but slower

**Comment by Gusted** [comment]
Hi @Yash-Singh1!

Can you see if the `.darkreader--fallback` style has textContent?

Regards,
Gusted

**Comment by Yash-Singh1** [comment]
@Gusted The problem seems to be resolved now. I am closing for now. I will check for `.darkreader--fallback` the next time the problem comes up.
