### ISSUE TITLE
[Feature Request] System to dump Darkreader generated CSS.

### ISSUE THREAD

**Issue by fuwn** [darkreader/darkreader#4428]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a bug of any sort, more of something that would be a cool tool.

**Describe the solution you'd like**
Requesting the ability to dump the generated dark CSS that Darkreader creates.

**Additional context**
This would be great to convert pre-existing light CSS stylesheets to dark.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/604#issuecomment-661107893
