### ISSUE TITLE
Dark reader flagged as PUA:Win32/CoinMiner 

### ISSUE THREAD

**Issue by ekrof** [darkreader/darkreader#4430]
Windows defender flagged the chrome extension as malware `PUA:Win32/CoinMiner` when downloading from [chrome store
](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)

![image](https://user-images.githubusercontent.com/14015087/101467468-a263b400-3942-11eb-9e7f-bad6f8e5365d.png)

Just wanted you to be aware of this

**Comment by StefanSimion** [comment]
Same issue here on Windows 10 Pro machine. This time with Firefox and Tor. Both of them have Dark Reader installed from [Firefox store](https://addons.mozilla.org/en-US/firefox/)

![DarkReader](https://user-images.githubusercontent.com/26160087/101486076-05117b80-3954-11eb-897c-056c3d8cdb5e.PNG)

**Comment by alexanderby** [comment]
Did it start happening today?

**Comment by Gusted** [comment]
Hi @ekrof & @StefanSimion!

Thanks for letting us know, I first want to point out that that the detected file seems to be `dark-sites.config` which is a list of known dark-by-default sites and let dark reader know to not style it by default. However I don't use Windows anymore and can't go into a analysis which `site` is being listed as coinminer so we can remove it from the list. I runned [virustotal](https://www.virustotal.com/gui/file/cc079b869b4f352cc61ad5ceab3b5fe8d9b115698b97dc55a87c4a56a6b381e0/detection) on the current file, but seems to be undetected. So unfortunately it seems only windows defender detect it at this time. It seems like the only way to detect which site it is to use a tool like [DefenderCheck](https://github.com/matterpreter/DefenderCheck) and see which bytes the windows defender is tricking. @alexanderby Could you have look with this tool?

Regards,
Gusted

**Comment by alexanderby** [comment]
How did you know it is dark-sites.config?

**Comment by Gusted** [comment]
> How did you know it is dark-sites.config?

![image](https://user-images.githubusercontent.com/25481501/101488403-7999e980-3957-11eb-853f-56c28c547c05.png)
![image](https://user-images.githubusercontent.com/25481501/101488425-81f22480-3957-11eb-89bd-bd172d6b4994.png)
Both screenshots is being traced down to either the cached version or the source file of config/dark-sites.config

**Comment by StefanSimion** [comment]
> 
> 
> Did it start happening today?

Hi @alexanderby
Yes, it start happening today. 
I usually do a full scan using Windows Defender on a weekly basis and I don't recall seeing this error before.

**Comment by alexanderby** [comment]
I've reported the problem to Microsoft, they have a special form for it. My Windows Defender is silent even though is up to date. I will try to dig into it.

**Comment by alexanderby** [comment]
A message from MS:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by Gusted** [comment]
Seems like it's solved should have this as a pinned issue for a while?

**Comment by alexanderby** [comment]
Can somebody run the check again?

**Comment by nikolabebic95** [comment]
> A message from MS:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

I've done these steps and am still getting the same issue:
![image](https://user-images.githubusercontent.com/12418927/101546662-6b74b900-39a9-11eb-9ad8-a8b9461298a7.png)

Is there something I missed?

**Comment by StefanSimion** [comment]
@alexanderby I tried the solution from Microsoft, but the issue remains

![DefenderUpdate](https://user-images.githubusercontent.com/26160087/101617678-d4d7e480-3a08-11eb-8900-f6961476425f.PNG)
![DefenderScan](https://user-images.githubusercontent.com/26160087/101617683-d6091180-3a08-11eb-8fc7-5a0417aa28ae.PNG)

**Comment by ekrof** [comment]
Followed the same Microsoft guide, plugin still blocked for the same reason. My machine is running Windows 10 Pro 20H2  on an office E3 license with MDM for the company I work for which have some policies in place.

**Comment by Gusted** [comment]
@alexanderby By any chance you reported the direct file link? It could be that e.g. firefox or vivaldi or other that has another file path is still being affected. I'm not sure how their `exclusion` list works.

**Comment by alexanderby** [comment]
I've uploaded dark-sites.config. It's very strange, because no threat is shown in my Windows Defender.

**Comment by alexanderby** [comment]
Guys, could you please share your Windows Defender versions? Antimalware Client, Engine, Antivirus, Antispyware.

**Comment by alexanderby** [comment]
It is reported that 1.329.104.0 doesn't show the alarm, but 1.327.2245.0 does.

**Comment by StefanSimion** [comment]
> 
> 
> A message from MS:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
>     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 
>     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 
>     3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

I updated Windows Defender again today

![OldVersion](https://user-images.githubusercontent.com/26160087/101751813-a28dbc00-3ac8-11eb-81ae-0b04543d2c30.PNG)

Now Windows Defender version is 

![NewVersion](https://user-images.githubusercontent.com/26160087/101751856-b5a08c00-3ac8-11eb-97c7-28133549c5b0.PNG)

Then I did a full scan on the computer and I got this

![Scan](https://user-images.githubusercontent.com/26160087/101757656-52662800-3acf-11eb-8654-535580bd3575.PNG)

**Comment by ekrof** [comment]
Chrome plugin download works fine today. Just tested. Defender version: `4.18.2011.6 `

**Comment by stefan-simion** [comment]
It looking fine for me now.

Windows Defender version is
![Version](https://user-images.githubusercontent.com/66673772/102067416-f6631280-3df2-11eb-8464-c09d7268eaef.PNG)

**Comment by Gusted** [comment]
Seems like the new version is rolling out and most people have received or is receiving it. Closing and will be pinned for the next few days.
