### ISSUE TITLE
[Feature Request] Option to not invert documents content

### ISSUE THREAD

**Issue by jjanedoh** [darkreader/darkreader#4432]
**Is your feature request related to a problem? Please describe.**

PDF documents come out as negative images

**Describe the solution you'd like**

Filter PDF content (or other content) from inverting by a filter like sites, ability to specify content type, document types for example to not invert, even a checkbox would do

**Additional context**

**Comment by Yash-Singh1** [comment]
```
Click on the DR icon
Click on DevTools
Click on preview new design
Press the DR icon again
Click on settings
Click on site list
The option is there
```

**Comment by jjanedoh** [comment]
> ```
> Click on the DR icon
> Click on DevTools
> Click on preview new design
> Press the DR icon again
> Click on settings
> Click on site list
> The option is there
> ```

Where is the checkbox for "don't invert for documents" ? I cannot find it

I see a bunch of code, I don't want to edit code

**Comment by Yash-Singh1** [comment]
There is a checkbox underneath the site list in the settings.

**Comment by jjanedoh** [comment]
> There is a checkbox underneath the site list in the settings.

Ahh I see it now, it's for specific sites or global?

I don't see this on Firefox but I do see it on Brave extension

There seems to be a difference between Firefox and Brave DarkReader

**Comment by Yash-Singh1** [comment]
In a firefox extension, at the bottom of the popup there will be an option saying devtools. This will open a new window. Click preview new design in that.

**Comment by jjanedoh** [comment]
> In a firefox extension, at the bottom of the popup there will be an option saying devtools. This will open a new window. Click preview new design in that.

Why should I click DEV tools? I am a user, users don't code ok

**Comment by Yash-Singh1** [comment]
The DevTools doesn’t contain code only. It has a button for users to use the new UI inside DarkReader. You are using the old UI by default.

**Comment by jjanedoh** [comment]
> The DevTools doesn’t contain code only. It has a button for users to use the new UI inside DarkReader. You are using the old UI by default.

And you expect users to go through these hoops? Come on

**Comment by Yash-Singh1** [comment]
@jjanedoh When v5 releases, the new design will be used as default. Currently the new UI is not complete.
