### ISSUE TITLE
[Feature Request] Global blacklist

### ISSUE THREAD

**Issue by Revadike** [darkreader/darkreader#4435]
**Is your feature request related to a problem? Please describe.**
By default, dark reader affects every site.

**Describe the solution you'd like**
I'd like to see an option for dark reader to be turned off for popular websites that already have native dark mode. Perhaps like a toggle. This site list will be curated for everyone using dark reader, as opposed to self-curated manually. 

**Additional context**
An alternative solution would be to dynamically detect existing dark modes on websites and decide to apply dark reader or not based on that. Of couse, this feature should be optional for users that would like every site to use dark reader, regardless of the site's native theme.

**Comment by Yash-Singh1** [comment]
@Revadike The `dark-sites.config` contains a list of all of the globally dark sites

**Comment by Revadike** [comment]
Seems that list don't include sites with optional dark mode? This is what this issue includes.

**Comment by Yash-Singh1** [comment]
Does #2774 help?

**Comment by Revadike** [comment]
> Does #2774 help?

yeah, that's what my 2nd solution was getting at.

**Comment by Gusted** [comment]
> Seems that list don't include sites with optional dark mode?

Right and won't be supported.
