### ISSUE TITLE
Option for NOT syncing settings

### ISSUE THREAD

**Issue by swors** [darkreader/darkreader#444]
I want to turn on the darkreader on my desktop computer, but turn off it on my laptop computer.
For more.
Further,  can we add some profiles and switch between the profiles in the different instances of chrome?

**Comment by rugk** [comment]
I do have the same problem: I want it to be enabled one one device and disabled on another one…

It would be enough to just not sync the "enabled" setting, at least optionally…
Everything else can be synced…

**Comment by Gusted** [comment]
It's weird that nobody implemented that simple button to enable/disable syncing.
