### ISSUE TITLE
Yandex browser: dark reader doesn't invertge page

### ISSUE THREAD

**Issue by pdimri** [darkreader/darkreader#445]
Dark reader doesn't invert the page when used with yandex browser whenever the web page is loaded first time. If I refersh the page or load any other webpage page,it gets inverted. This issue is consistent when ever browser is opened first time.

**Comment by alexanderby** [comment]
Should be fixed in version 4.3.2 (I haven't checked it for Yandex browser but for Chrome).

**Comment by Stargateur** [comment]
I have a lot of site where the plugin don't work anymore.
