### ISSUE TITLE
[Feature Request] Option to exclude images from inverting colors

### ISSUE THREAD

**Issue by MaciejGorczyca** [darkreader/darkreader#4455]
**Is your feature request related to a problem? Please describe.**

In some cases it's better when you can keep dark mode on but you need original image colors instead of inverted colors.

**Describe the solution you'd like**

Simply adding "Exclude images" in options could fix this and make usage of Dark Reader 1000x better.

**Additional context**
Putting additional option on the "More" page seems the best - you can make it global so it always excludes images from inverting colors or you can make it only for current website.

![66emvPdjNi](https://user-images.githubusercontent.com/26925976/101619016-fd64dc00-3a12-11eb-9257-c8a3c6166873.png)

This is the menu I'm talking about.

PS. I searched with google and github for image-related issues and couldn't find anything similar to the request.

**Comment by Gusted** [comment]
Hi @MaciejGorczyca!

I can see why people would need this, however I'm interested in your use-case as it you mention github/google is their some kind of problem going on?

Regards,
Gusted

**Comment by MaciejGorczyca** [comment]
I actually opened Google spreadsheets/docs and want to keep it dark but the images have negated colors and it kinda ruins them. I have to either get my eyes assblasted by deadly light rays or have weird looking pics.

**Comment by Gusted** [comment]
For google spreadsheets #1934 is their an open issue, however no known fix, because all the content is 1 element so if you do something to it it will also cause to do it to all the other elements of it.

**Comment by steph643** [comment]
Why has this issue been closed? Excluding images really sounds like a must-have. I need to disable Dark Reader on all web stores because product images are not true. I mean, go to Amazon and try to purchase some paint with Dark Reader on! :-) Or am I missing something?

**Comment by Gusted** [comment]
This issue was closed as it was rather a more specific request for google spreadsheets.

**Comment by steph643** [comment]
Ok, thanks. So I created this one: https://github.com/darkreader/darkreader/issues/6894

**Comment by yolpsoftware** [comment]
Need this too.

**Comment by Cannedfood** [comment]
@m0dbot For thomann.de specifically I submitted a PR: #9170

**Comment by psbell-meta** [comment]
This should be reopened as a feature rather than fixing specific websites

**Comment by Gusted** [comment]
Unless there's a good use-case, that doesn't involve fixing a website I prefer to keep this closed.

**Comment by pragma-** [comment]
This is about your extension, but ok. I was going to open an similar issue, but I thought I'd search through existing issues first. Glad I did so I don't waste my time with this any longer.

**Comment by MaciejGorczyca** [comment]
Hey @pragma- this is such a great idea. I never realized I could do that and it's good to know there are no conflicts. Still, it kinda sucks we have no "don't touch images" feature in DarkReader. :(

**Comment by useronegit** [comment]
I would also find cool if that would be integrated

**Comment by xyzDist** [comment]
this still happening in google doc, any update? I hope this got a option to exclude the images,

**Comment by DougS2K** [comment]
Add me to the list of people that want this feature. Still having this issue in google spreadsheets and can't find any way around it. Anyone have any suggestions?

**Comment by ItzTyrone** [comment]
Any updates to this feature? I've been hoping it would get added for years.

**Comment by MS89x** [comment]
I think this feature would be great. Would make navigating ecommerce sites more viable.

**Comment by MS89x** [comment]
This would be a good feature. To workaround for _some_ sites, open up the DevTools (in both the browser and Dark Reader), locate the offending image(s) class, and add _(for example, on Amazon)_:

```
.a-image-container {
background-color: white;
}
```

**Comment by TheDeviantCrafter** [comment]
This is an issue I've noticed on about half of all websites I've attempted to use Dark Reader with. Many of them are tiny sites that I would never expect the devs to add a site-specific exception for. An ignore images toggle would save a lot of headaches.

**Comment by cstmth** [comment]
I cannot see how this feature is not considered essential. This is _the_ sole reason why I keep jumping off Dark Reader time and time again.

**Comment by gitterspec** [comment]
Completely agree. Makes graphs unreadable on many many websites. Hard to read news articles in general. In the meantime, if anyone has a temporary alternative, please let us know.

**Comment by pragma-** [comment]
As I mentioned in an earlier comment last year, the https://addons.mozilla.org/en-US/firefox/addon/invert-image/ Firefox extension works well to invert images to make them readable. But I have to manually right-click each image to select "Invert image". This is a major annoyance.

It would be absolutely ideal if Dark Reader would have an "Invert images" option in its settings for those who would prefer to have their images inverted. It can even be disabled by default, though I suspect most users would enable it.

@Gusted Please consider the above.

**Comment by pragma-** [comment]
@gitterspec As I mentioned in an earlier comment last year, the https://addons.mozilla.org/en-US/firefox/addon/invert-image/ Firefox extension works well to invert images to make them readable. But I have to manually right-click each image to select "Invert image". This is a major annoyance.

@Gusted It would be absolutely ideal if Dark Reader would have an "Invert images" option in its settings for those who would prefer to have their images inverted. It can even be disabled by default, though I suspect most users would enable it. Ideally this option would be toggleable per-site as well.

**Comment by fmaribo** [comment]
so there's a chrome extension called "Google Docs Dark Mode" with about 600'000 users that has dark mode without inverting images or emojis, maybe it could be worth reverse engineering that? 
link to example:
https://chromewebstore.google.com/detail/google-docs-dark-mode/lgjhepbpjcmfmjlpkkdjlbgomamkgonb

**Comment by nikitosych** [comment]
Why is this issue closed? That's not an intended behaviour, kinda dissapointing that devs cannot solve it and just give it up 👎

**Comment by Leonixar** [comment]
They celebrate 10 years tomorrow, but to perfect their work as much as possible doesn't matter to them anymore. Videos and images are the second essential content of the internet after text. 20 years ago, this addition would have been a big boom because the internet was mostly about text. But today? Dark Reader isn't keeping up with the time, and it's going to need a replacement. In 80% of sites, I have to turn it off for that page just because in addition to text and background, it also edits images and videos... useless... ._.

**Comment by atamasco** [comment]
2025 and websites using PNGs with black text on transparent background still seem broken when using DarkReader. :/

Example (top left image): https://carloarg02.medium.com/how-amazon-and-google-view-ci-cd-in-an-entirely-different-way-824b9c36777e

**Comment by atamasco** [comment]
2024 and websites using PNGs with black text on transparent background still seem broken when using DarkReader. :/

[Example (top left image)](https://carloarg02.medium.com/how-amazon-and-google-view-ci-cd-in-an-entirely-different-way-824b9c36777e)

**Comment by neilfranci** [comment]
@Leonixar If you found any replacement or fix pls share. 'Cause this literally hurt my eye on almost any website with images.

**Comment by Leonixar** [comment]
> @Leonixar If you found any replacement or fix pls share. 'Cause this literally hurt my eye on almost any website with images.

sadly no... :c not yet... :(

**Comment by Predulus** [comment]
Please provide an option to disable image inversion.  Should be an incredibly easy thing to do.

**Comment by neilfranci** [comment]
> Please provide an option to disable image inversion. Should be an incredibly easy thing to do.

Have you tried to remove img tag under the INVERT in the developer tools?

**Comment by Predulus** [comment]
> Have you tried to remove img tag under the INVERT in the developer tools?
Not quite sure how.  I'm not much of a web-dev guy.

**Comment by Predulus** [comment]
> > Have you tried to remove img tag under the INVERT in the developer tools?
> > Not quite sure how.  I'm not much of a web-dev guy.
Oh I think I've figured it out ... it's listed per-site .. gonna give it a go

**Comment by atamasco** [comment]
> > Please provide an option to disable image inversion. Should be an incredibly easy thing to do.
> 
> Have you tried to remove img tag under the INVERT in the developer tools?

It would be very helpful if you could share how to find this option in the DarReader or browser options.

**Comment by neilfranci** [comment]
@atamasco 
Here, just follow the gif. This is what I did (the img tag was there before but I removed it) under the INVERT section.
Not sure why they moved the dev tools from the popup to the setting in the new version but it's inconvenient.

![msedge_j1iEolRPTd](https://github.com/user-attachments/assets/dc935f05-51a9-43a8-8a96-c66d1a01052b)

**Comment by atamasco** [comment]
> @atamasco Here, just follow the gif. This is what I did (the img tag was there before but I removed it) under the INVERT section. Not sure why they moved the dev tools from the popup to the setting in the new version but it's inconvenient.
> 
Thank you very much, @Predulus ! That was really helpful. Putting any class/id there that should be inverted works like a charm.

**Comment by Leonixar** [comment]
> @atamasco Here, just follow the gif. This is what I did (the img tag was there before but I removed it) under the INVERT section. Not sure why they moved the dev tools from the popup to the setting in the new version but it's inconvenient.

Could you provide some other source of the animation (video), where you show us, how to add fill formats to the code? Seeing it in chat, it's kinda small and blurry, I can't read what you are writing there, only that it is something short... maybe .gif or *.gif? And when I try to open it in other tab, then my browser tell me this:

No website could be found at https://private-user-images.githubusercontent.com/66520542/374821326-dc935f05-51a9-43a8-8a96-c66d1a01052b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTc1MDUsIm5iZiI6MTcyODQ5NzIwNSwicGF0aCI6Ii82NjUyMDU0Mi8zNzQ4MjEzMjYtZGM5MzVmMDUtNTFhOS00M2E4LThhOTYtYzY2ZDFhMDEwNTJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE4MDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNmIyN2ZlN2EzOWFkMmQ0YzA3ZjdkZjllYzc2OTY2ODJhMDA3ODMyMzNhYTZjMjJmMjZmZDI5NDM2NjY1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qot4kGaIsFdrq5NqlLvWz6ZdDqBaEhnZZve2qLF06mM

**Comment by neilfranci** [comment]
@Leonixar That's weird, what browser you using? Cause I still can open it it another tab.

**Comment by Leonixar** [comment]
> @Leonixar That's weird, what browser you using? Cause I still can open it it another tab.

Opera GX O.o

**Comment by neilfranci** [comment]
> > @Leonixar That's weird, what browser you using? Cause I still can open it it another tab.
> 
> Opera GX O.o

Are you still have this happens when open other image, video in github from other people? (Not just my) If still I will try to make a video or host it in other platforms.

**Comment by ensbana** [comment]
> [@atamasco](https://github.com/atamasco) Here, just follow the gif. This is what I did (the img tag was there before but I removed it) under the INVERT section. Not sure why they moved the dev tools from the popup to the setting in the new version but it's inconvenient.
> 
> ![msedge_j1iEolRPTd](https://github.com/user-attachments/assets/dc935f05-51a9-43a8-8a96-c66d1a01052b) [ ![msedge_j1iEolRPTd](https://github.com/user-attachments/assets/dc935f05-51a9-43a8-8a96-c66d1a01052b) ](https://private-user-images.githubusercontent.com/66520542/374821326-dc935f05-51a9-43a8-8a96-c66d1a01052b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5Njc2NTMsIm5iZiI6MTc0MDk2NzM1MywicGF0aCI6Ii82NjUyMDU0Mi8zNzQ4MjEzMjYtZGM5MzVmMDUtNTFhOS00M2E4LThhOTYtYzY2ZDFhMDEwNTJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDAyMDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTU2ZDMwNGEyOTA4ZTUwNDVlZWM0ZjM4NTAzNzZhNGRkM2FlYTYzZDgyMDcxYmMwNGVkOGU2NGE4ZjFiMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BCrvSnbHJ0GTmssQTH74kR2R8obEgu5VCh7xwab-hs4) [ ](https://private-user-images.githubusercontent.com/66520542/374821326-dc935f05-51a9-43a8-8a96-c66d1a01052b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5Njc2NTMsIm5iZiI6MTc0MDk2NzM1MywicGF0aCI6Ii82NjUyMDU0Mi8zNzQ4MjEzMjYtZGM5MzVmMDUtNTFhOS00M2E4LThhOTYtYzY2ZDFhMDEwNTJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDAyMDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTU2ZDMwNGEyOTA4ZTUwNDVlZWM0ZjM4NTAzNzZhNGRkM2FlYTYzZDgyMDcxYmMwNGVkOGU2NGE4ZjFiMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BCrvSnbHJ0GTmssQTH74kR2R8obEgu5VCh7xwab-hs4)

I tried your fix but the "img" tag was not there by default. I also tried to put it there, and it worked! 

But now all websites have their images color-inverted. Is there a way to apply this fix specifically just for one website? I've tried the "Per Site Editor" option (by adding the intended website's URL, copying the whole code from the "Full Editor" panel, and adding the "img" tag), but the fix still applies to all websites.

![Image](https://github.com/user-attachments/assets/e3383835-e571-4083-9649-ad01322b31ba)

**Comment by nielpattin** [comment]
@ensbana Very sorry, I miss this nofi.

You can just add
```
INVERT
img
```
below the url, like here what I did. No need to copy the whole thing.
I tested it and the website in the img got image inverted.

![Image](https://github.com/user-attachments/assets/dcf51844-5f4d-438c-b045-6eff91b943c0)
And other sites like Amazon, for example, images will not be inverted.
![Image](https://github.com/user-attachments/assets/b814d8df-e430-4405-be57-26c93d10df51)

**Comment by johngibbs** [comment]
> @pragma- This is about your extension, but ok. I was going to open an similar issue, but I thought I'd search through existing issues first. Glad I did so I don't waste my time with this any longer.
> 
> edit: Instead, I went ahead and searched for an extension specifically for inverting images to use along with DarkReader. I have found that https://addons.mozilla.org/en-US/firefox/addon/invert-image/ works very well and solves my issues with images with dark lines/text and a transparent background being impossible to see while DarkReader is enabled.

FYI, I made an extension for Microsoft Edge called [Media Inverter](https://microsoftedge.microsoft.com/addons/detail/media-inverter/lpbgicnjpblgalhechobpnjladlgcdig) inspired by the Invert Image extension for Firefox that you mentioned.

**Comment by MagicPlants** [comment]
How the hell is this not a feature stock in 2025?!?

**Comment by shinobi-zue** [comment]
> > [@atamasco](https://github.com/atamasco) Here, just follow the gif. This is what I did (the img tag was there before but I removed it) under the INVERT section. Not sure why they moved the dev tools from the popup to the setting in the new version but it's inconvenient.
> 
> I tried your fix but the "img" tag was not there by default. I tried to put it there instead, and it worked!
> 
> But now all websites have their images color-inverted. Is there a way to apply this fix specifically just for one website? I've tried the "Per Site Editor" option (by adding the intended website's URL, copying the whole code from the "Full Editor" panel, and adding the "img" tag), but the fix still applies to all websites.
> 
> ![Image](https://github.com/user-attachments/assets/e3383835-e571-4083-9649-ad01322b31ba)

This screenshot is exactly how my use case looks but just adding "img" as demonstrated does absolutely nothing for me whatsoever, much less work toward resolving the image inversion issue. I don't understand why there's no built-in feature for this; needing to view true-to-life deliverables seems like a no-brainer to me, especially on one of the most widely-used software suites on the market.

I am using Opera GX and all the google pages suddenly became blinding white - the invert media plugin doesn't exist for me :(

**Comment by Metazolid** [comment]
Just adding my two cents for some activity here. While I think it's reasonable it shouldn't be expected to fix inverted images on a per-website basis, Google Sheets and Docs are so fundamental and widely used that a fix for those would affect probably the largest group of users who have an ongoing issue with inverted images.
