### ISSUE TITLE
[Broken Website] JIRA crashes when I open any ticket and click on the Description section

### ISSUE THREAD

**Issue by cecobask** [darkreader/darkreader#4473]
**Website**
https://{{company}}.atlassian.net/browse/{{issueID}}

**How to Reproduce**
> 1. Open any JIRA ticket with dark mode on using Google Chrome.
> 2. Everything works fine until you click on Description section.
> 3. After that the whole webpage freezes and the tab crashes after a few seconds.

**Expected behavior**
I expected to be able to operate JIRA in dark mode and use all functionality of the website.

**Actual behavior**
The Google Chrome tab crashed.

**Screenshots**
Not applicable

**System info:**

- OS: MacOS Catalina 10.15.7
- Browser: Google Version Chrome 87.0.4280.88 (Official Build) (x86_64)
- Darkreader Version: 4.9.26

**Comment by sebekz** [comment]
RCA in https://github.com/darkreader/darkreader/issues/1595

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/1595#issuecomment-853777753
