### ISSUE TITLE
[BUG] Site recognition needs tweaking. 

### ISSUE THREAD

**Issue by jeremiah-rs** [darkreader/darkreader#4489]
### **Describe the bug**

Darkreader does not differentiate between different network addresses such as 192.168.1.1 and 192.168.1.100. Those two IP addresses can correspond to two different devices/sites on someones network but Darkreader will not recognize them as such. 

If I disable it on the lower address, it will follow that behavior on the higher address. 

### **Steps to reproduce**

- Add devices 192.168.1.1 and 192.168.1.100 to network, or something similar like 192.168.1.2 and 192.168.1.200
- Disable dark reader on the lower address.
- Dark reader will follow that setting on the higher address, even if you try to enable it. 

### **Expected behavior**

Dark reader should treat both addresses as two distinct addresses, and allow configuration on each separately.

### **Actual behavior**

Dark reader will treat both addresses as the same. 

### **System Information:**

- OS: MacOS Catalina, Windows 10
- Browser: Firefox
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
#4375
