### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by avi12** [darkreader/darkreader#4490]
**Is your feature request related to a problem? Please describe.**
It's annoying that I need to manually toggle dark mode every day
There's a partial solution that allows setting automatic dark mode (OS-based), but it only works for individual sites

**Describe the solution you'd like**
Allow toggling the dark mode across all sites based on the OS's state
Also, it'd be nice if I could opt-out a site from having dark mode enabled/disabled temporarily, and then when I toggle it back, it follows the OS's dark mode

There are 2 reasons for opting-out a site from automatic dark mode:
1. The site implements its own automatic dark mode (e.g. GitHub)
1. The extension's dark mode breaks the site so it's harder to use, if possible

**Comment by Gusted** [comment]
https://darkreader.org/blog/automation/#activate-when-system-dark-mode-is-on enable OS-Preference and just disable sites like usual to exclude them from the automation.

**Comment by avi12** [comment]
Right, but last time I tried, it only persisted to the specific website
I rather wish to toggle the setting once for all sites

**Comment by WhyNotHugo** [comment]
@Gusted Can you point me to the PR where this is implemented? I'd like to have a go at implementing this for Linux as well.

**Comment by Gusted** [comment]
I assume you mean the code implemented to detect this #1522 #1513 #878 the 3 options time/location/OS-detection.
