### ISSUE TITLE
[Feature Request] Add Safari support via extension convertion

### ISSUE THREAD

**Issue by arshiyasolei** [darkreader/darkreader#4493]
Recently with the release of Big Sur, lots of chrome extensions can be fully converted and be used in Safari. I converted this extension by just running one command line and generated an Xcode Extension! 

https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by alexanderby** [comment]
Great! But we have many users on High Sierra, who cannot use the latest Safari, and many users of Safari App Extensions platform. So the transition process is more complex, then just converting the extension in command line.

**Comment by lesterlo** [comment]
Any good news about the conversion?

**Comment by alexanderby** [comment]
Let's wait for developer tools for this. It seems that mobile extensions have a bit different API, but of course I will do my best to provide a mobile version before the new iOS release.

**Comment by thisbansal** [comment]
I've tried converting it using `safari-web-extension-converter` but the UI elements doesn't get render at all. All I get is a $BODY text instead of UI elements of Dark reader under safari. Could anyone point me in right direction what I'm doing wrong? It install and runs just fine on iOS 15 safari but I'm not able to get the UI working.

**Comment by arche-dev** [comment]
> Let's wait for developer tools for this. It seems that mobile extensions have a bit different API, but of course I will do my best to provide a mobile version before the new iOS release.

@thisbansal Maybe because of this?

**Comment by Gusted** [comment]
I'm not sure how safari-web-extension-converter work, nor do I own any apple products to test this on. But if you're seeing $BODY... that does mean you've didn't even build dark reader from the source, as those strings only exist in the source code and is replaced when building dark reader.

**Comment by TheNoim** [comment]
The basic extension is working on iOS just fine. The ui sometimes glitches around and the auto switch for dark/light mode isn't working. But overall, it works. 

![image](https://user-images.githubusercontent.com/5133056/129041690-87c404df-b919-45a3-aa2d-0f1b83db0a44.png)

**Comment by rakleed** [comment]
@TheNoim Can you write instructions on how to install an extension on iOS if I have a desktop with macOS?

**Comment by TheNoim** [comment]
I think, you need a paid developer account. However, I am not sure. The setup itself isn't that hard.

**Comment by bershanskiy** [comment]
> The basic extension is working on iOS just fine. The ui sometimes glitches around

Well, "glitches around" is not really "fine". :)

> the auto switch for dark/light mode isn't working.

That should be fixed in the next release or if you build from source. Details are here: #6347

> I think, you need a paid developer account. However, I am not sure. The setup itself isn't that hard.

You can build from source and install extensions on your own device for free. But if you want to publish on App Store you do need to pay $100/year for "Apple Developer Program" subscription.

**Comment by TheNoim** [comment]
> You can build from source and install extensions on your own device for free. But if you want to publish on App Store you do need to pay $100/year for "Apple Developer Program" subscription.

But only for 7 days.

**Comment by TheNoim** [comment]
> @TheNoim Can you write instructions on how to install an extension on iOS if I have a desktop with macOS?

Prerequisites:

1. NodeJS
2. XCode **Beta** (Run it the first time and install components)

Guide:

1. Clone the repo
2. `cd` into repo
3. Run `npm install`
4. Run `npm run build`
5. Select Xcode Beta `sudo xcode-select -s /Applications/Xcode-beta.app`
6. Run `xcrun safari-web-extension-converter --project-location . --app-name darkreader --swift --ios-only --bundle-identifier BUNDLE_IDENT ./build` (Replace BUNDLE_IDENT with a proper bundle identifier)
7. Now open the xcode project (I think, after running xcrun it should open by itself)
8. 
![Screenshot 2021-08-11 at 16 34 00](https://user-images.githubusercontent.com/5133056/129049100-7c217473-fe36-4b1b-8025-9204176bb68d.png)
9. 
![Screenshot 2021-08-11 at 16 37 23](https://user-images.githubusercontent.com/5133056/129049395-2a3426d2-e9e2-4c6c-8a51-3db771aab62e.png)
10. Now you should be able to run the extension on the device via xcode. 

I hope I didn't forgot any step @rakleed

**Comment by gem2578** [comment]
I see the comment has `--ios-only`, are you also like and replacing the existing Mac version with this converter?

**Comment by alexanderby** [comment]
Some news regarding the Dark Reader for iOS release. The extension should be available in the store as soon as iOS 15 will go public.

**Comment by lesterlo** [comment]
Hello @alexanderby ,

Will the dark reader for mac safari be upgraded at the same time? 

Are the current release (1.4.3) of the dark reader for mac built with safari extension conversion?

**Comment by Ichicoro** [comment]
> Some news regarding the Dark Reader for iOS release. The extension should be available in the store as soon as iOS 15 will go public.

Amazing! Is a TestFlight beta coming in the meantime?

**Comment by sith-on-mars** [comment]
> Some news regarding the Dark Reader for iOS release. The extension should be available in the store as soon as iOS 15 will go public.

Just updated to iOS 15 and Dark Reader is still not in the store yet...

**Comment by jpike88** [comment]
@alexanderby im checking the App Store every day :(

**Comment by alexanderby** [comment]
Please wait while it will be reviewed.

**Comment by clnhs** [comment]
> Please wait while it will be reviewed.

It’s out on the Canadian store! So glad I can finally have Dark Reader on my iPhone! 

Is there an ETA on automatic theme switching? I only have on and off right now. Or did I miss something about it being only available if I build from source per earlier instructions?

Also, thank you so much for the free upgrade! I’d totally forgotten I had purchased it for Safari on MacOS since I barely use the browser anymore.

**Comment by lesterlo** [comment]
I found the Dark reader app on App store.

Do we need to purchase it again even I have purchased the Mac dark reader?

**Comment by alexanderby** [comment]
Hi there. The app is now available for iPhones and iPads https://apps.apple.com/us/app/dark-reader-for-safari/id1438243180#?platform=iphone

Automation based on system dark mode will be added in the next release. Let me know what other features do you need.

The macOS app will be updated soon. The support for macOS High Sierra will be dropped. Also, most likely, the settings will not be transferred from the obsolete extension to the new one.

**Comment by iovis** [comment]
Installed it last night and works great!

> Let me know what other features do you need

I use the keyboard shortcut for toggling on/off per website a lot, I saw 1Password had a keyboard shortcut for their Safari Extension in iOS so I'm assuming (hoping) it should be possible

**Comment by alexanderby** [comment]
> I use the keyboard shortcut for toggling on/off per website a lot, I saw 1Password had a keyboard shortcut for their Safari Extension in iOS so I'm assuming (hoping) it should be possible

A keyboard shortcut on iPhone? Or when a keyboard is connected to iPad?

**Comment by iovis** [comment]
Sorry, I should've clarified! I meant for iPad users that use a keyboard

**Comment by clnhs** [comment]
> Automation based on system dark mode will be added in the next release.

Just got the update! Again, thank you for your work, @alexanderby !

**Comment by planet0** [comment]
Awesome! Just received the macOS update now.

**Comment by bershanskiy** [comment]
Since Safari and iOS versions of Dark Reader are available, I'm closing this now. If you experience any issues, please open a dedicated issue.

**Comment by AJAYK-01** [comment]
> > @TheNoim Can you write instructions on how to install an extension on iOS if I have a desktop with macOS?
> 
> Prerequisites:
> 
> 1. NodeJS
> 2. XCode **Beta** (Run it the first time and install components)
> 
> Guide:
> 
> 1. Clone the repo
> 2. `cd` into repo
> 3. Run `npm install`
> 4. Run `npm run build`
> 5. Select Xcode Beta `sudo xcode-select -s /Applications/Xcode-beta.app`
> 6. Run `xcrun safari-web-extension-converter --project-location . --app-name darkreader --swift --ios-only --bundle-identifier BUNDLE_IDENT ./build` (Replace BUNDLE_IDENT with a proper bundle identifier)
> 7. Now open the xcode project (I think, after running xcrun it should open by itself)
> 
> ![Screenshot 2021-08-11 at 16 34 00](https://user-images.githubusercontent.com/5133056/129049100-7c217473-fe36-4b1b-8025-9204176bb68d.png) 9. ![Screenshot 2021-08-11 at 16 37 23](https://user-images.githubusercontent.com/5133056/129049395-2a3426d2-e9e2-4c6c-8a51-3db771aab62e.png) 10. Now you should be able to run the extension on the device via xcode.
> 
> I hope I didn't forgot any step @rakleed

Hey I tried converting to Safari extension using a similar command but for MacOs, the built app converts websites to dark mode, but neither the shortcuts nor the extension ui works.
Basically I'm stuck in Always On Dark Mode as long as the extension is enabled.
<img width="311" alt="Screenshot 2021-10-04 at 8 21 50 PM" src="https://user-images.githubusercontent.com/55079486/135873603-108fd493-d8e4-46be-9236-58a3ae4e9bb7.png">
