### ISSUE TITLE
[Feature Request] Add a class to a top level HTML element to identify Dark Reader style applied

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#4494]
I was thinking more about our discussion on allowing the user to edit the dynamic or other themes for user-specified sites.

I think it's a very worthwhile long-term goal.  In the short-term, I have a proposal that is easy to implement while simultaneously providing maximum flexibility: *Add a class to a top level HTML element (such as `body`) that identifies the Dark Reader style being applied (dynamic, filter, filter+, custom01, custom02, etc.).*

This simple improvement allows the user to apply any additional styles (or other functionality, such as scripts) they want, dependent on the Dark Reader theme being applied.  People can apply those styles using `userContent.css`, Stylish, or whatever they prefer.

This other project already performs this class-adding behavior, and as you can see, the implementation is rather simple: https://github.com/codebicycle/videospeed

The only hiccup I can think of right now is ensuring that the user-override styles are able to override any Dark Reader CSS that uses `!important`.

**Comment by Gusted** [comment]
Hi @Gitoffthelawn!

Seems like a good idea in my eyes.
It's rather `what` to use as identify e.g. a new attribute to HTML `darkreader-mode="dynamic"` seems good. and can then be used as
```CSS
[darkreader-mode="dynamic"] h1 {
    color: red !important;
```



> The only hiccup I can think of right now is ensuring that the user-override styles are able to override any Dark Reader CSS that uses `!important`.

Stylus & `userContent.css` will override Dark reader if `!important` is applied. We can't detect `userContent.css` and have an special exclusion for `Stylus`.

**Comment by Gitoffthelawn** [comment]
Hello @Gusted!

Yes, what you wrote is exactly what I was thinking. :)

We can use whatever we want, but when I don't want to take any chance of interfering with a site's code, I usually add something that is a touch unusual that most other programmers would not choose to do on their own.  For example, `darkreader_` or `_darkreader_`.

For the values, I'm thinking, `dynamic`, `filter`, `filter+` (would have to ensure the plus sign is always valid), and `custom_xyz` where `xyz` is the name the user assigned to their custom theme, with any non-alpha-numeric characters converted to dashes.

Whatcha think?

**Comment by KaKi87** [comment]
Please make it `data-darkreader-mode` so it's W3C compliant. Thanks !

**Comment by Gusted** [comment]
#4860 Not sure how I've missed these 2 notifications.

**Comment by Gitoffthelawn** [comment]
@KaKi87 Thanks for your suggestion.  Just so I can learn, why does your recommendation make it W3C-compliant?

@Gusted Thank you!  Has #4860 been pushed to release yet?

**Comment by KaKi87** [comment]
Although HTML parsers will not throw errors when an element attribute does not exist, the W3C HTML standard recommends using the `data-` prefix for custom element attributes.

[Source](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)

When using the W3C HTML validator, or an IDE that validates HTML following the W2C HTML standard, like the JetBrains suite, a warning will be thrown.

**Comment by Gusted** [comment]
> @Gusted Thank you! Has #4860 been pushed to release yet?

*Checks status of #4860* >>  Open

**Comment by Gusted** [comment]
#4860 merged and in latest release.
