### ISSUE TITLE
[Feature Request] Element picker

### ISSUE THREAD

**Issue by Mar-vo** [darkreader/darkreader#4495]
Is your feature request related to a problem? Please describe.
It is quite hard to add a single element from a web page to the list of elements to be ignored from inversion.

Describe the solution you'd like
I would like an element picker, like the one included in ublock origin and other ad-blockers. This lets you click an element after freezing the page. Then there is a rules editor that let's you pick a css selector of the appropriate scope. After confirming this selector, a rule would automatically be added to the blacklist.
Optionally, a toggle for "global" to allow for easy creation of global rules would be helpful for things dark reader consistently inverts by mistake (like video players) and allow for less tweaking in the long run.

Describe alternatives you've considered
A simpler alternative could be a "ignore element" mode where a user simply selects a single element to be ignored from inversion to allow temporary/specific readability. This simply omits the "rules editor" stage and would be much less powerful/useful as a result.

Additional context
Example image of the ublock element picker (in dutch) - in order to get a feel for what i'm suggesting, it could be useful to try this feature from ublock origin.
![](https://user-images.githubusercontent.com/46787993/102003884-9e9dac00-3d0b-11eb-830a-80bd7499a8f1.png)

**Comment by Gusted** [comment]
#48
