### ISSUE TITLE
[BUG] Bandcamp Logo

### ISSUE THREAD

**Issue by Nowena** [darkreader/darkreader#4500]
### **Bandcamp logo**

The bandcamp logo at the top-left of the site isn't visible in any band page

### **Steps to reproduce**

- Go to any band page on bandcamp
- look at the top-left corner
- You notice logo is not visible

### **Expected behavior**

You should be able to see the logo.

### **Actual behavior**

The logo is not visible.

### **Screenshots**

https://imgur.com/of2NzSM

### **System Information:**

- OS: Windows 10
- Browser: Opera browser 73.0.3856.257
- Dark Reader version: 4.9.26. and using Dynamic option for Theme generation mode

**Comment by Gusted** [comment]
Hi @Nowena!

Do you have a link where you see this happening?

Regards,
Gusted

**Comment by Nowena** [comment]
Hello,

Yes, here:
https://mhonos.bandcamp.com

and here:
https://mhonos.bandcamp.com

or any other band page
