### ISSUE TITLE
[BUG] When youtube goes full screen, then black rectangles appear from top and bottom. (Issue seems specific to mozilla and appears when we try to open the youtube in full screen mode(by pressing F)).

### ISSUE THREAD

**Issue by vaibhavcs99** [darkreader/darkreader#4503]
### **Steps to reproduce**

- Go to '...'
- Click on '...'
- Scroll down to '...'

### **Actual behavior**

A clear and concise description of what actually happened.

### **System Information:**

- OS: [e.g. iOS 11]
- Browser: [e.g. Chrome 73, Safari 13]
- Dark Reader version: [e.g. 4.9.9]

**Comment by Gusted** [comment]
The title isn't the issue template, fill out all information and use a short title to describe the issue.
