### ISSUE TITLE
[Feature Request] Respect `ui.SystemUsesDarkTheme`

### ISSUE THREAD

**Issue by WhyNotHugo** [darkreader/darkreader#4505]
**Is your feature request related to a problem? Please describe.**

I'm working on automatically changing `ui.SystemUsesDarkTheme` on a schedule every day. I'd like for `darkreader` to pick this up.

**Describe the solution you'd like**

Change `darkreader` to use the value of `ui.SystemUsesDarkTheme` to toggle its state between on/off.

**Additional context**

Currently, on/off must be changed manually.

**Comment by Gusted** [comment]
Hey @WhyNotHugo!

Could you try the following things:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And then `Go to ⚙Settings -> Automation.`
If you enable in this menu `Use system color scheme` it should work(their might be a slight delay on Firefox for dark reader to pick this up).

Regards,
Gusted

**Comment by WhyNotHugo** [comment]
There's no `dev tools` icon:

![image](https://user-images.githubusercontent.com/730811/102217266-3bab4100-3ed4-11eb-9afe-195cff1741d4.png)

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/102217465-83ca6380-3ed4-11eb-92ed-2db3ee00c7e2.png)
Uhm... Do you have special settings? As it seems like the popup is now cropped.

Alternatively you can do it the hacky way, by right clicking the popup and press on `view page source` and in the new tab, remove in the URL `view-source:` and poof you got the popup in a tab.

**Comment by WhyNotHugo** [comment]
> As it seems like the popup is now cropped.

It's a reported yet unfixed issue for Firefox on Linux. Something about handling screen sizes and scaling wrong.

Thanks for the neat hack, didn't know of it. `Auto` doesn't work though. With `ui.systemUsesDarkTheme` set to `1`:

![image](https://user-images.githubusercontent.com/730811/102218046-55995380-3ed5-11eb-99ec-b41dd2cad07c.png)

![image](https://user-images.githubusercontent.com/730811/102218054-57631700-3ed5-11eb-8712-09e2d6bf7ecc.png)

**Comment by Gusted** [comment]
by any chance `privacy.resistFingerprinting` enabled? This causes to force sites/extension know it uses a light theme, regardless of the `ui.systemUsesDarkTheme`.

**Comment by WhyNotHugo** [comment]
I _am_ using `privacy.resistFingerprinting`.

Changing `ui.systemUsesDarkTheme` does not affect websites, but does apply to Firefox itself.

Are you referring to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1535189)? It seems to indicate `privacy.resistFingerprinting` affects how websites see the `prefers-color-scheme` property, but there's no mentions of extensions being unable to read the `ui.systemUsesDarkTheme` setting.

Is `ui.systemUsesDarkTheme` unreadable with `privacy.resistFingerprinting` too?

**Comment by Gusted** [comment]
> Changing `ui.systemUsesDarkTheme` does not affect websites, but does apply to Firefox itself.

Correct, Firefox can still use this value.



> Are you referring to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1535189)? It seems to indicate `privacy.resistFingerprinting` affects how websites see the `prefers-color-scheme` property, but there's no mentions of extensions being unable to read the `ui.systemUsesDarkTheme` setting.

That's the problem, we can only detect the system's color scheme trough the `prefers-color-scheme` property as we can't read any settings in `about:settings` and therefore Dark Reader thinks the system is light. No workaround neither a bypass for this.

**Comment by WhyNotHugo** [comment]
Hmmm... so extensions cannot read the value of `ui.systemUsesDarkTheme`?

Darn. It seems that then this feature **cannot** be implemented due to browser limitations. I wanted to somehow programatically set `ui.systemUsesDarkTheme`, and eventually have `Dark Reader` inherit that setting.

I guess I'll have to rely on #2870: once it's resolved I can have my `darkman` communicate with `Dark Reader` directly.

Thanks for the informative replies!

**Comment by Gusted** [comment]
> I guess I'll have to rely on #2870: once it's resolved I can have my `darkman` communicate with `Dark Reader` directly.

I will squeeze some improvements into the PR in the following days make sure to subscribe to the PR. It's been on the backlog for far too long.
