### ISSUE TITLE
[Feature Request] Ability to invert subdomain but not root domain

### ISSUE THREAD

**Issue by NSExceptional** [darkreader/darkreader#4508]
For example, `github.com` recently got dark mode, but `gist.github.com` did not.

I use the "invert not listed" mode because DarkReader looks great on most websites by default. However this means I cannot block github.com while allowing gist.github.com to be inverted.

I trued changing the entry for GitHub to `https://github.com` but this still matches `gist.github.com` for some reason.

**Comment by Gusted** [comment]
#147 and alternatively use `^github.com` in the sitelist to bypass this behaviour.

**Comment by NSExceptional** [comment]
Omg I was going to suggest this, I didn't think that would work out of the box haha. You're a genius, thank you!

**Comment by Gusted** [comment]
> Omg I was going to suggest this, I didn't think that would work out of the box haha. You're a genius, thank you!

No problems!
