### ISSUE TITLE
[BUG] Can't enable the addon on certain websites.

### ISSUE THREAD

**Issue by KamilBaczkowski** [darkreader/darkreader#4520]
### **Describe the bug**
I can't enable the extension on certain websites. Once in a while I stumble upon some website, that just doesn't work. https://www.homesbyagee.com/ is an example.

### **Steps to reproduce**

- Go to https://www.homesbyagee.com/
- The extension doesn't work. All I can see is the _Disabled for current website_ text, and I can't enable it back, using UI or the hotkey.

### **Expected behavior**

The website should be handled properly, it should be darkened

### **Actual behavior**

I can't enable the extension on the website.

### **System Information:**

- OS: Manjaro
- Browser: Firefox 83
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Hi @KamilBaczkowski!

How does your current sitelist looks like?

Regards,
Gusted

**Comment by epakai** [comment]
I hit this on a homeip.net site. Turns out I had disabled dark mode while browsing something in my /home directory. The "home" got stored in the sitelist and overrode any toggling of the homeip.net site.

**Comment by KamilBaczkowski** [comment]
@Gusted I'm completely sorry, I totally forgot about the email. I think the bug is that if you disable dark reader for a website on a domain, and then visit a website in a subdomain, the subdomain can't be enabled.
You can try it out with my website: I have [a blog](https://kavela.ch) and [a git web ui](https://git.kavela.ch). If you disable the add-on on my blog, you can't enable it on the git UI.

**Comment by Gusted** [comment]
Yup, #3359

**Comment by Francewhoa** [comment]
If https://www.homesbyagee.com is a subdomain of https://homesbyagee.com then this is likely a bug

I can confirm this bug with Dark Reader V4.9.62. Using [Firefox](http://mozilla.org/firefox) V102.7 or [Ungoogle Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) V109.0. Chromium is the same engine as Chrome. But Chromium as much stronger privacy and stronger security. Dark Reader works with both.

For users facing this challenge, I published [this easy, quick, and temporary workaround](https://github.com/darkreader/darkreader/issues/1896#workaround).

For developers interested to contribute to resolving this bug, you might be interested in this:
* [Steps to reproduce](https://github.com/darkreader/darkreader/issues/1896#steps)
* Pull request at https://github.com/darkreader/darkreader/pull/2517
