### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by morihofi** [darkreader/darkreader#4521]
**Website**
https://www.linuxmint.com/start/ulyana/

**How to Reproduce**
An example of this is
>
> 1. Go to https://www.linuxmint.com/start/ulyana/ site
> 2. You'll see it... terrible

**Expected behavior**
A normal dark design

**Actual behavior**
It looks terrible

**Screenshots**
A Screenshot is available under https://cloud.morihofi.de/nextcloud/index.php/s/x7FzjH36yLmZAoJ

**System info:**

- OS: Linux Mint 20 Cinnamon 64bit
- Browser: Mozilla Firefox
- Darkreader Version: 4.9.26

**Additional context**

**Comment by Gusted** [comment]
Hi @morihofi!

These kind of sites also `intranet` sites uses images to style elements and are problematic to solve within Dark Reader and with custom CSS fixes. It's considered to use `Filter` mode for this kind of sites.

Regards,
Gusted
