### ISSUE TITLE
[Broken Website] Wikipedia reference highlight

### ISSUE THREAD

**Issue by irvnriir** [darkreader/darkreader#4522]
with dynamic mode, after clicking a link to reference, on a page, the target reference highlight are barely distinguishable .

**Comment by Gusted** [comment]
Use the template.

**Comment by irvnriir** [comment]
You don't know what WP Reference is ?

**Fixed:**
wikipedia.org
```
ol.references li:target, sup.reference:target {
    background-color: rgb(45, 43, 46);
}
```

Is that enough info for you ?

**Comment by Gusted** [comment]
Use the [issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website.md&title=%5BBroken+Website%5D+)

**Comment by irvnriir** [comment]
Ignore if you wish to, i have more important stuff to do than filling forms for clearly no sense .

**Comment by Gusted** [comment]
> Ignore if you wish to, i have more important stuff to do than filling forms for case when it clearly makes no sense .

Wikipedia has a variety of articles so it could be any of the URL's to see to see this things as `link reference`, also I don't have a clue what this is and thereby don't know how to reproduce neither to get this `target reference`. We made issue templates for a reason to get the basic information that anyone who is willing to fix this bug, know what the bug exactly is and know how to reproduce it.
