### ISSUE TITLE
[Broken Website] surveymonkey.com - odd behavior hiding text

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#4525]
**Website**
https://www.surveymonkey.com/

**How to Reproduce**
> 1. Enable Dark Reader`filter` mode
> 2. Go to https://www.surveymonkey.com/r/22XZM8K
> 3. Complete the survey
> 4. See that the "thank you" for completing the survey is hidden

**Expected behavior**
Show the "thank you" text when survey is completed

**Actual behavior**
"Thank you" text hidden

**System info:**

- OS: Windows
- Browser: FF 84.0
- Darkreader Version:  4.9.26

**Additional context**

Overall, surveymonkey.com does not work well with Dark Reader's `dynamic` mode.  Thus, using the `filter` mode instead.

This issue is really odd.  The text described above will disappear when any CSS `filter` is applied to this page.

The text is contained within `.bd .headline`.  For that element, simply changing the CSS from `bottom: 0` to `bottom: initial` (or doing something like changing margins from `margins: auto` to `margins: 0`) will fix the issue.

I haven't yet been able to determine if this is a browser bug, or something else.  I'm quite interested in hearing people's ideas of what is going on.

**Comment by Gusted** [comment]
Hi @Gitoffthelawn!

I tried the survey with and without Dark reader's filter mode, but nothing stood out to me that was different and the header with `thank you` appeared as well.

Regards,
Gusted

**Comment by Mar-vo** [comment]
I tried to recreate your issue but wasn't able to. Page 7 is empty - maybe you're seeing that page by accident? The thank you message is on page 8

**Comment by Gusted** [comment]
Page 7 is indeed blank even without dark reader and page 8 is indeed the thank you that is clearly visible for me with dark reader.
