### ISSUE TITLE
[Dynamic] Disqus

### ISSUE THREAD

**Issue by wooles** [darkreader/darkreader#453]
Disqus comments mix with the background.

![ufgv7gt](https://user-images.githubusercontent.com/9068595/39654724-5a67237c-4ff6-11e8-8039-64699580802b.png)

**Comment by alexanderby** [comment]
Could you please give some links where it happens. Disqus dynamically analyzes page content and chooses light or dark theme.

**Comment by wooles** [comment]
Sure, 
http://horriblesubs.info/
http://antyweb.pl/bmw-m5-competition-pierwsze-plotki/

**Comment by EdHartHub** [comment]
Has this issue been solved yet?

One thing I noticed, when I refresh (F5), comments in Disqus become readable! I'm using Firefox if that makes a difference, Please check:

https://www.revzilla.com/common-tread/first-look-2020-triumph-rocket-3-tfc
https://sempreinter.com/2019/05/03/report-suggests-inter-ceo-marotta-hasnt-given-up-on-juventus-paulo-dybala/

These pages are just examples, check any pages with Disqus within these domains. Generally speaking, majority of the websites that I've encountered with Disqus have the same issue. 

Great add0n regardless, thanks for your handwork!
