### ISSUE TITLE
[Feature Request] Removing all items from "site list" at once

### ISSUE THREAD

**Issue by telmotrooper** [darkreader/darkreader#4531]
Is there any way to remove all sites from "Site list"? I decided I want pages to default to their original color scheme, so I switched to "invert listed only",  but I have way too many sites saved on "Site list". Now I'm stuck removing them one by one because all pages I previously selected to not invert are inverting...

I'd be nice if the extension had a button to remove all items or if the lists were split, but as of now, is there any file I can delete to wipe all entries at once? Thank you.

**Comment by Gusted** [comment]
Hi @telmotrooper!

Could you try

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

And then in the new UI go to Settings -> Sitelist and see that you can quick remove a site. As removing all sites is a rare situation a quick convention for this will highly not be implemented.

Regards,
Gusted

**Comment by telmotrooper** [comment]
This is indeed easier than removing from the default site list, I had no idea there even was an option to access a new interface. Thank you.
