### ISSUE TITLE
github and stackoverflow light mode problem

### ISSUE THREAD

**Issue by vagra** [darkreader/darkreader#4534]
**Website**
https://github.com
https://stackoverflow.com

**How to Reproduce**
1. Go to site
2. Set Light mode
3. the site background color is black, not light color.

![图片](https://user-images.githubusercontent.com/1576687/102621328-5acafc80-417a-11eb-9006-96bf3d2dcfcc.png)

**Expected behavior**
I want using light color for the site background, like this:
![图片](https://user-images.githubusercontent.com/1576687/102621133-1f303280-417a-11eb-8cea-8eb4a05f7ab9.png)

**Actual behavior**
the site background color is black in light mode:
![图片](https://user-images.githubusercontent.com/1576687/102621204-34a55c80-417a-11eb-969a-a28ac00918a3.png)
![图片](https://user-images.githubusercontent.com/1576687/102621283-4edf3a80-417a-11eb-8df7-9ba0e022cb79.png)

**Screenshots**

- OS: Windows 10
- Browser: Firefox 84
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
#4291 Resolves this issue

**Comment by vagra** [comment]
I updated darkreader to 4.9.27, but this problem is not resolved.

**Comment by Gusted** [comment]
> I updated darkreader to 4.9.27, but this problem is not resolved.

It's still open, so don't expect to get it fixed. It relies on #4291.
