### ISSUE TITLE
[BUG] DarkMode config UI has really bad performance with lots of tabs

### ISSUE THREAD

**Issue by jrmuizel** [darkreader/darkreader#4539]
### **Steps to reproduce**

- I have 469 open tabs
- Opening the configuration window gives profiles like: https://share.firefox.dev/34tpfmp which has janks of around 2 seconds

**Comment by chmichael** [comment]
Hello, 
  I have the same problem! With firefox 84 is even worse.

**Comment by Gusted** [comment]
Hi @jrmuizel!

Weowie 469 is quite huge, however the profiler only recorded the background script which is in another process than the sites itself and shouldn't interfere with the sites performance with every 2 seconds jank. So it happens on opening the configuration window? and not on the site itself? Some more explanation needs to come around here.

@chmichael mentioned that on Firefox 84 it became worse, you think v84 might have a role in this as than Mozilla should get aware of it.

Regards,
Gusted

**Comment by jrmuizel** [comment]
Yeah, the darkmode config ui is basically unusable because there's a 2 second delay after ever interaction. I rephrased the issue title to make it more clear.

**Comment by Gusted** [comment]
Hi @jrmuizel!

So the 2 second delay happens when? After changing a setting and the site displays the change after 2 seconds or if you navigate trough the UI their is a 2 second delay before it let you see where you navigated to.

**Comment by jrmuizel** [comment]
The delay happens after changing a setting. e.g. clicking left arrow on the brightness control.

**Comment by Gusted** [comment]
> The delay happens after changing a setting. e.g. clicking left arrow on the brightness control.

Somehow this doesn't indicate for me if you meant the UI is laggy or the site your on is laggy.

**Comment by chmichael** [comment]
Now i saw it. I was talking about the perfomance of firefox with DarkMode reader and a lot of tabs not only the UI of Darkmode reader. With firefox 84 some tabs are tottaly are unresponsive! Should i make a new tiket ?

**Comment by Gusted** [comment]
> Now i saw it. I was talking about the perfomance of firefox with DarkMode reader and a lot of tabs not only the UI of Darkmode reader. With firefox 84 some tabs are tottaly are unresponsive! Should i make a new tiket ?

Not really, just explain what's exactly happening. The OP had 469 tabs which is considerable huge and should expect slowdown. Even a good PC should stress with that huge amount of tabs.

**Comment by chmichael** [comment]
Hello,
  Firefox 84.0.1 fixed my issues so it wasn't Dark Reader's fault!

Thank you

**Comment by Gusted** [comment]
I saw @jrmuizel opened up a bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1683116

**Comment by jrmuizel** [comment]
@Gusted what does that bug have to do with this issue?

**Comment by Gusted** [comment]
v84 introduced a lot more of performance regression my guess is that, that bug let them know that. Even though it was specific to canvas.

**Comment by jrmuizel** [comment]
The canvas performance regression was because of remote canvas and specific to Windows. The issue that I'm seeing is in darkreader js code and I'm running it on macOS.

**Comment by Gusted** [comment]
> The issue that I'm seeing is in darkreader js code

If you know how to run a profiler, I will appreciate that. I'm still on v84 and tried to reproduce it for a while, but didn't saw anything abnormaly from v83.
