### ISSUE TITLE
help.netflix.com is not changed at all

### ISSUE THREAD

**Issue by hotaru2k3** [darkreader/darkreader#454]
help.netflix.com keeps its blinding white background no matter what I do with this extension.

**Comment by alexanderby** [comment]
It's because Netflix is in [Dark List](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config).

**Comment by alexanderby** [comment]
I've replaced `netflix.com` with `www.netflix.com` so it should work now (at least within 15 minutes).

**Comment by hotaru2k3** [comment]
thanks, it works now!
