### ISSUE TITLE
Cant filter websits correctly with similar endings like .co and .com [BUG]

### ISSUE THREAD

**Issue by whary318** [darkreader/darkreader#4544]
### **Describe the bug**

When i want the add-on to only work on a website such as "aaa.co" but i visit a website with the link "aaa.com", the ".com" website would still be considered under the filter and the colors would be inverted.

### **Steps to reproduce**

- Go to a website. Example: "aaa.co".
- Click on the website name on the add-on window to add the website to the filter list.
- Go to "Site list" on the add-on window.
- Click "Invert listed only"
- Visit another website with the same name. Example: "aaa.com".

### **Expected behavior**

The first website have its colors inverted.
The second website have its colors as it originally was.

### **Actual behavior**

The first website have its colors inverted.
The second website have its colors also inverted.

### **Screenshots**

![Screenshot (79)_LI_Moment_Moment](https://user-images.githubusercontent.com/32772890/102688049-1bc09980-41c2-11eb-9e91-5f10044c051b.jpg)

### **System Information:**

- OS: Windows 10 Version 10.0.18363 Build 18363
- Browser: Firefox 84.0 (64-bit)
- Dark Reader version: 4.9.26

**Comment by OmarNamis** [comment]
Remove the slash at the end.
"wuxiaworld.co" works for both '.co' and '.com'

**Comment by whary318** [comment]
Oh sorry i forgot to remove it. I was testing if it was going to make any difference but it didn't. I added that slash. The problem is present even without it.


> "wuxiaworld.co" works for both '.co' and '.com' 

And that is the issue. It works for both when it shouldn't. 
The "wuxiaworld.co" and "wuxiaworld.com" websites are different.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/2517#issuecomment-742345717 This behaviour was pointed out to me to net yet fixed and has been fixed in the PR that resolves a lot of URL matching problems.
