### ISSUE TITLE
[Broken Website] 

### ISSUE THREAD

**Issue by loldoll** [darkreader/darkreader#4545]
**Website**
Several websites including duckduckgo and dark reader's own help page does not change to custom defined background color on Dark reader for Firefox Android.

**How to Reproduce**
Set a custom background color in the dark reader extension (In "theme for all websites" box press "See all options" and then "Colors" then set the backgound color to black (#000000) instead of the default way too bright washed out grey.

Try to e.g. do a search on duckduckgo, notice how the background is not black but washed out grey.
Notice how this will happen on some other webpages as well, like dark readers own help page.

**Expected behavior**
I expected the background to be black, not grey.

**Actual behavior**
*Removed by Gusted*

Firefox Android 84.1.1
Android 10
Dark reader 4.9.26

**Comment by OmarNamis** [comment]
If you want a perfect black background, I suggest increasing the contrast instead of changing the colors.

**Comment by Gusted** [comment]
Hi @loldoll, 

Inside the settings of duckduckgo's search engine(main page or an a search result) Under appearance select the left theme and see that it's get applied the perfect dark. Dark Reader's help page is by default not getting styled.

Regards,
Gusted
