### ISSUE TITLE
[Broken Website] filfre.net/

### ISSUE THREAD

**Issue by tobz1000** [darkreader/darkreader#4551]
**Website**
https://www.filfre.net/

**How to Reproduce**
Visit the home page or any article

**Expected behavior**
The main background is dark.

**Actual behavior**
The main background is dark momentarily, then changes to white. This may be related to a script on the site.

**Screenshots**
![Screenshot_20201220-195452](https://user-images.githubusercontent.com/1471978/102723105-c4274880-42fd-11eb-9521-6c3f609ed9e9.png)

**System info:**

- OS: Android 11
- Browser: Firefox 83
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
Hi @tobz1000!

For this site you can enable `static` or `filter` theme inside Dark Reader's setting. It uses images as background images which are problematic to correctly get styled.

Regards,
Gusted
