### ISSUE TITLE
[Feature Request] Changing those 4 colors in a config file (for pywal)

### ISSUE THREAD

**Issue by Bugswriter** [darkreader/darkreader#4552]
I want to use dark reader with pywal and I can simply do this if darkreader have some kind of config file.
I don't know if there is any existing config file.
I will just make a shell script and create new config file with my pywal generated background, text, scrollbar, selection color. 
It will be more great if darkreader have some kind of pywal feature!

**Comment by Gusted** [comment]
#2168
