### ISSUE TITLE
[Broken Website] wikipedia references

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4553]
**Website**
The link to the broken website
https://en.wikipedia.org/wiki/ExFAT#cite_note-56

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors
1. Go to wikipedia site
2. Click some reference

**Expected behavior**
Highlighted background must be invisible

**Actual behavior**
A clear and concise description of what happened.
Highlighted background is invisible

**Screenshots**

![image](https://user-images.githubusercontent.com/14617699/102745281-ab09b080-436c-11eb-9a49-094a395ddfe1.png)
![image](https://user-images.githubusercontent.com/14617699/102745287-ae04a100-436c-11eb-967a-0c7143ae969f.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

**Comment by Gusted** [comment]
#4439

**Comment by 532910** [comment]
ack, thank you!
