### ISSUE TITLE
[Feature Request] Ignoring video embeds

### ISSUE THREAD

**Issue by Mar-vo** [darkreader/darkreader#4558]
**Is your feature request related to a problem? Please describe.**
Embedded videos with inverted colors tend to be a very bright and attention-grabbing. The inverted colors also make the video unwatchable. Embedded videos turn into bright unintelligible blocks of muddled colours.

**Describe the solution you'd like**
An option to turn off the inversion for embedded video players.

**Comment by Gusted** [comment]
Hi @Mar-vo!

Could you describe an scenario where the video embedded is being inverted?

Regards,
Gusted

**Comment by Mar-vo** [comment]
Any embedded youtube video will do the trick. I assume embedding a youtube video here would render similiar results.

Here is an example page. Warning - contains nightmarish inverted video :) In this first case Dark Reader didn't invert the thumbnail for some reason - but then it did invert the video:

https://www.kvraudio.com/video/synthwave-10624

Here is another example page, where the thumbnail sadly does get inverted as well as the video:

https://www.gearslutz.com/board/mastering-forum/1252522-targeting-mastering-loudness-streaming-lufs-spotify-youtube-why-not-do.html

I hope the provided examples are enough to work with - if needed i can find some more.

It seems there also often is a dark overlay over youtube video embeds, which then turns into a brightening overlay. This also goes for other video players. So in my opinion, it would be very good if dark reader excluded video embeds by default. Video controls are generally dark, meaning inverting their colors leads to brightness. Not to mention that inverted videos are essentially unwatchable, or at least very jarring in 90% of cases.

![image](https://user-images.githubusercontent.com/46787993/102944165-452b3f00-44ba-11eb-9eb8-0c0cc1c0e20e.png)

![image](https://user-images.githubusercontent.com/46787993/102944518-4ad55480-44bb-11eb-862b-491424fe7eff.png)

**Comment by Mar-vo** [comment]
By the way, here is an example of a page with an overlay on embeds - to give an example of the brightening that occurs because of this:

https://bitwig.community/preset-Rhythmique
