### ISSUE TITLE
Makes permanent changes to Google Sheets cell colors

### ISSUE THREAD

**Issue by thhowl** [darkreader/darkreader#456]
Developer here, so I know the difference between darkreader changing a color at render time, and the color of text in a G-sheets cells being set to a different color by the user. (E.g. darkready aside, user sets the color of his text in a G-Sheet).  

The issue I'm reporting is that darkready changes the text color of a cell permanently (saved with the file) as if user had made the change using G-Sheet controls.  

To reproduce:    I edited my G_Sheet  while darkreader on.  Anytime I went to edit a cell with Red text, it changed the text to an off orange - that's fine, that's darkready doing best it can.   Edit it again, and now the murky orange is changed to a murky yellow.  Again, fine, not the issue.     The Issue:    I turned darkready off.  I reloaded my G-Sheet.  Cell colors were shown as murky yellow.

There must be something in how G-SHeets uses the current HTML to save the cell color.

**Comment by alexanderby** [comment]
OK, closing this as a duplicate. So much time has passed, I will look into it soon.
