### ISSUE TITLE
[Broken Website] samcodes.co.uk

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4561]
**Website**
The link to the broken website
https://samcodes.co.uk/

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors
1. Go to site

**Expected behavior**
Must be readable

**Actual behavior**
A clear and concise description of what happened.
unreadable

**Screenshots**
![image](https://user-images.githubusercontent.com/14617699/102947806-3a31d800-44d5-11eb-89c7-b7e4de66e06f.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux]
- Browser: [e.g. chrome, safari]
- Darkreader Version: [e.g. 4.9.9]

**Additional context**

**Comment by OmarNamis** [comment]
Adding this to the dev tool should fix the issue:

```css
================================

samcodes.co.uk

INVERT
.logo
```

![image](https://user-images.githubusercontent.com/14346945/102973991-6c0f6280-4506-11eb-837b-532dee2d8771.png)


It's not a popular website, so I'm not sure whether it should be included by default.

**Comment by 532910** [comment]
ack, thank you!
