### ISSUE TITLE
[Broken Website] RouterOS WebFig

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4573]
**Website**
The link to the broken website
RouterOS WebFig
Demo: http://demo.mt.lv/webfig/#Quick_Set

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors
Go to RouterOS WebFig Quick_Set

**Expected behavior**
Must be visible

**Actual behavior**
A clear and concise description of what happened.
Invisible

**Screenshots**
![image](https://user-images.githubusercontent.com/14617699/103069437-7007b700-45d0-11eb-9ab9-f61486f9fcee.png)
![image](https://user-images.githubusercontent.com/14617699/103069440-726a1100-45d0-11eb-86a6-ec259fc01bdc.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

**Comment by Gusted** [comment]
#4579

**Comment by 532910** [comment]
http://demo.mt.lv/webfig/#Quick_Set is just a demo.
real addresses are like http://IP/ or http://router.local/ or something else.

**Comment by Gusted** [comment]
Dark reader doesn't style local sites due to low accuracy to get the correct "site"

**Comment by 532910** [comment]
In fact it does:
![image](https://user-images.githubusercontent.com/14617699/103095593-3192ec00-4612-11eb-85d9-d4d20757f948.png)

**Comment by Gusted** [comment]
> Dark reader doesn't ~style~ local sites due to low accuracy to get the correct "site"

Fix* as having such selectors it can break any other local site and darkreader doesn't know if it's the correct local site. However you can just use the fix in stylus or dark reader's dev tools to have it applied.
