### ISSUE TITLE
[Broken Website] Significant impact on avito.ru speed

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4576]
**Website**
The link to the broken website
https://www.avito.ru/rossiya?q=github

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors
1. Go to website

**Expected behavior**
Should not affect load speed.

**Actual behavior**
A clear and concise description of what happened.
Page is loading too long and with glitches.

**Screenshots**
![Peek 2020-12-24 11-13](https://user-images.githubusercontent.com/14617699/103073723-296a8a80-45d9-11eb-930b-c574fb58e04f.gif)
![Peek 2020-12-24 11-12](https://user-images.githubusercontent.com/14617699/103073729-2bcce480-45d9-11eb-8c2f-6075bf9c603a.gif)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

The most notable annoyance is image load: the right side of the image is displayed first, and the left side is displayed with a delay.

**Comment by Gusted** [comment]
Use the [performance template](https://github.com/darkreader/darkreader/issues/new?assignees=&template=performance_issue.md&title=%5BPerformance%5D+) for anything performance related.
