### ISSUE TITLE
Should sites that automatically adapt to system appearance be added to the dark list?

### ISSUE THREAD

**Issue by nyuszika7h** [darkreader/darkreader#4578]
> If a website is already dark (has all pages dark by default), you can add it to the dark-sites.config file (please, preserve alphabetical order).

The README is not entirely clear, does this also apply to sites that use `prefers-color-scheme` to automatically respect system appearance, or only sites that are always dark by default regardless?

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/3917/commits/97b5476967601035a7062cc69fed6dff9e195835

**Comment by nyuszika7h** [comment]
Thanks for the clarification. (Might want to fix the typo: preffered -> preferred 😉 )

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/3917/commits/bb43545422849f2cb11106644c96cd3d7b35c7b3
