### ISSUE TITLE
Gmail settings not inverted for dynamic theme engine

### ISSUE THREAD

**Issue by prstorero** [darkreader/darkreader#458]
![image](https://user-images.githubusercontent.com/7811371/39665752-5dc38ef8-505e-11e8-9aa8-5b2c9f3bc7c6.png)

![image](https://user-images.githubusercontent.com/7811371/39665768-964b7646-505e-11e8-8dd4-200f2867584e.png)

**Comment by risualiser** [comment]
I don't have any of these issues. Try to update extension.

**Comment by prstorero** [comment]
I checked for updates and don't have any available. I'm on FireFox, perhaps the Chrome version is updated further ahead?

**Comment by risualiser** [comment]
No, there is a same version for both, I mean 4.3.2.

**Comment by risualiser** [comment]
No, sorry for bothering. It seems better to wait for the dev.

**Comment by prstorero** [comment]
No problem at all. I appreciate the effort.

**Comment by alexanderby** [comment]
@prstorero It looks like you are using built-in GMail dark theme and have `mail.google.com` listed in your exceptions list. Try to click "Toggle" button or open "Site List" tab and remove `mail.google.com` or similar record.

**Comment by prstorero** [comment]
@alexanderby You were correct, I forgot I had used the dark theme after switching to FireFox before I found the extension for this browser as well. Issue resolved.
