### ISSUE TITLE
[Broken Website] http://wlodb.com/

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#4583]
**Website**
http://wlodb.com/

**How to Reproduce**
An example of this is
>
> 1. Go to http://wlodb.com/

**Expected behavior**
The page is dark.

**Actual behavior**
It's not dark.

**System info:**

- OS: Windows
- Browser: Firefox
- Darkreader Version: 4.9.26

**Additional context**

**Comment by Gusted** [comment]
Hey @linsui

Could you point where the site is not dark?
![image](https://user-images.githubusercontent.com/25481501/103137092-d9192880-46bd-11eb-82d6-51a2feef8764.png)

Regards,
Gusted

**Comment by linsui** [comment]
Well, in my browser it is

![sshot-032](https://user-images.githubusercontent.com/36977733/103137270-58f3c280-46bf-11eb-8f37-09746bc44c35.png)

and no css rule is shown in the developer tool

![sshot-033](https://user-images.githubusercontent.com/36977733/103137355-331aed80-46c0-11eb-999e-eeb92f30b5b5.png)

**Comment by Gusted** [comment]
Their should be CSSRules from the site itself *application.css* 
![image](https://user-images.githubusercontent.com/25481501/103137393-812ff100-46c0-11eb-9d27-28b363dc87d8.png)
Ignore the `user-agent` styles.

**Comment by linsui** [comment]
If I remove `<style>@import "/stylesheets/application.css";</style>` the style will be broken so the css has effect but for some reasons not visible to developer tool and dark reader. Looks like this is a firefox issue...
Thanks, I'll close this issue as it's not related to dark reader.

**Comment by linsui** [comment]
Well, it's somehow related to dark reader. If I disable dark reader, wait until the website is loaded completely and enable dark reader, the website will be dark and the developer tool work well. Dark reader somehow breaks the website.

**Comment by linsui** [comment]
It can't be reproduced all the times. Looks like it's still a Firefox issue.
