### ISSUE TITLE
[Feature Request] Exclude subdomain or page

### ISSUE THREAD

**Issue by webmastak** [darkreader/darkreader#4594]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

Add a list to exclude - subdomain or page. Example: https://yandex.ru/maps/
Since not all subdomains or pages work correctly with dark rendering.

**Comment by Gusted** [comment]
`Please make sure there is no existing issue about this kind of feature.`

https://github.com/darkreader/darkreader/issues?q=is%3Aissue+subdomain+is%3Aopen
