### ISSUE TITLE
[Broken Website] about:blank

### ISSUE THREAD

**Issue by coolandsmartrr** [darkreader/darkreader#4606]
**Website**
[about:blank](about:blank)

**How to Reproduce**
An example of this is
>
> 1. Go to about:blank

**Expected behavior**
Darkness.

**Actual behavior**
All I see is the Light.

**Screenshots**
<img width="1437" alt="Screen Shot 2020-12-28 at 10 55 39" src="https://user-images.githubusercontent.com/905436/103184385-4960bd80-48fb-11eb-9320-a4f1f3c27dce.png">

**System info:**

- OS: macOS
- Browser: Chrome
- Darkreader Version: 4.9.26
https://whatismybrowser.com/w/DYW3N5D

**Additional context**
This issue is antithetical to the logo of this app.

**Comment by Gusted** [comment]
Hi @coolandsmartrr!

Currently the abour:blank cannot be styled in chrome, you should install an third party theme from the chrome webstore to make it dark. 

Regards, 
Gusted
