### ISSUE TITLE
Shows top-bar in wrong color

### ISSUE THREAD

**Issue by anandado** [darkreader/darkreader#4608]
In Chrome Os, when viewing a website as a separate window, many sites are displayed with a white top-bar despite having dark mode on. Eg. when viewing Facebook or messenger. It happens using any of the filter modes.
<a href="https://ibb.co/gSxJ9yk"><img src="https://i.ibb.co/9b7WgnQ/Screenshot-2020-12-27-at-19-38-56-1.png" alt="Screenshot-2020-12-27-at-19-38-56-1" border="0"></a>

**Comment by Gusted** [comment]
Hi @anandado!

We as an extension can't style this, to make this dark you can install an third party dark theme from the chrome web store. 

Regards, 
Gusted
