### ISSUE TITLE
Filter mode regression on https://cgit.freedesktop.org/mesa/mesa/log/

### ISSUE THREAD

**Issue by Kerrung** [darkreader/darkreader#461]
https://cgit.freedesktop.org/mesa/mesa/log/
Filter and Filter+ modes don't work at this website anymore, beginning today.

![screenshot from 2018-05-06 14-24-23](https://user-images.githubusercontent.com/36989404/39671858-8d62ff0a-5139-11e8-930b-2c79f6d317f8.png)
![screenshot from 2018-05-06 14-24-16](https://user-images.githubusercontent.com/36989404/39671859-8d837b86-5139-11e8-98b9-162a65c077ef.png)

**Comment by alexanderby** [comment]
Versions below 4.3.3 require that there is some `REMOVE BG` or `CSS` in `*` inversion fixes config section.  But today IFrames were removed from there and they became empty breaking older Dark Reader versions. The fix should be applied within 15 minutes.

**Comment by Kerrung** [comment]
@alexanderby 
>Versions below 4.3.3 require that there is some REMOVE BG or CSS in * inversion fixes config section. >But today IFrames were removed from there and they became empty breaking older Dark Reader >versions. The fix should be applied within 15 minutes.

fixed for me. Thank you!
