### ISSUE TITLE
Navigating to the next page on 'docs.python.org' breaks dark mode parsing

### ISSUE THREAD

**Issue by WoodpeckerBaby** [darkreader/darkreader#4614]
### **Describe the bug**

Navigating to the next page on 'docs.python.org' breaks dark mode parsing on the next page and every page that follows.

- Refreshing does not help.
- Open the link in a new tab does not cause the issue. 
- The first webpage of this site you opened parses fine. 
- Toggling Dark Reader solves the issue for that instance, but the issue reoccurs when navigating to the next page.

### **Steps to reproduce**

- While the dark mode is on and your global setting is in Dynamic
- Go to 'https://docs.python.org/3/'
- Click on 'Tutorial' or anything in the main navigation section
- notice the issues

### **Expected behavior**

Clicking on the links within 'docs.python.org' while opening in the same tab does not break dark mode dynamic parsing.

The following is expected:

<img width="1669" alt="Screen Shot 2020-12-29 at 6 44 58 PM" src="https://user-images.githubusercontent.com/14303318/103278448-78b02100-4a06-11eb-9987-a3838747e11f.png">
<img width="1680" alt="Screen Shot 2020-12-29 at 6 44 45 PM" src="https://user-images.githubusercontent.com/14303318/103278458-7cdc3e80-4a06-11eb-9311-2399ae9d93ef.png">

### **Actual behavior**

All subsequent websites opened within 'docs.python.org' in the same tab breaks dark mode parsing.

The following is what actually happens.

<img width="1669" alt="Screen Shot 2020-12-29 at 6 44 58 PM" src="https://user-images.githubusercontent.com/14303318/103278482-8a91c400-4a06-11eb-938f-b43e9a4b09d0.png">
<img width="1661" alt="Screen Shot 2020-12-29 at 6 45 09 PM" src="https://user-images.githubusercontent.com/14303318/103278487-8cf41e00-4a06-11eb-9bb7-c35d504ec513.png">

### **System Information:**

- OS: macOS Big Sur 11.1
- Browser: Safari 14.0.2
- Dark Reader version: 1.4.2 (15)

### **Additional context**

- This appears to be an isolated case and does not happen on any other websites that I have visited.

**Comment by WoodpeckerBaby** [comment]
Also tested in the latest release version of Chrome, and it also has this issue. Strangely when you refresh the page, it arbitrarily toggles between the correct and incorrect dark mode parsing.

**Comment by Gusted** [comment]
#835
