### ISSUE TITLE
[BUG] NVIDIA Driver Downloads Page

### ISSUE THREAD

**Issue by cyatarow** [darkreader/darkreader#4628]
### **Steps to reproduce**
1. Go to https://www.nvidia.co.jp/Download/index.aspx
2. Click on any drop-down list
3. Select any value from the list

### **Expected behavior**
The selected value does not change automatically.

### **Actual behavior**
The selected value reverts to the default value automatically.

### **Screenshots**
![20201230a](https://user-images.githubusercontent.com/26016252/103352805-98207a00-4aea-11eb-8dca-5e9b20928b2d.png)

### **System Information:**

- OS: Windows 10 Pro 20H2
- Browser: Firefox x64 84.0.1
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Not Dark Reader's fault. This is an fault with Firefox & Nvidia. You can confirm this by removing the Dark Reader extension and see that the same behaviour happens.
