### ISSUE TITLE
[BUG] Text selection color too dark with dynamic theme generation

### ISSUE THREAD

**Issue by Cyberbeni** [darkreader/darkreader#4629]
### **Describe the bug**

Text selection color doesn't have sufficient contrast with both background and text color.

### **Steps to reproduce**

- Default settings with "invert listed only" and google.com included
- Go to google.com
- Type text into search bar and then select it

### **Expected behavior**

Text selection color should have sufficient contrast with both background and text color.

### **Actual behavior**

Text selection color is too similar to background color.

### **Screenshots**

google.com with Dark Reader:
![2020-12-30](https://user-images.githubusercontent.com/8356175/103354762-b6678500-4aac-11eb-863e-bfe96057bcf4.png)

github.com with it's default dark theme:
![2020-12-30 (1)](https://user-images.githubusercontent.com/8356175/103354778-c1bab080-4aac-11eb-9a4f-f401cb900531.png)

### **System Information:**

- OS: Windows 10.0.19042 Build 19042
- Browser: Edge 87.0.664.66 (Official build) (64-bit)
- Dark Reader version: 4.9.26 (from chrome store)

**Comment by Gusted** [comment]
Hi @Cyberbeni!

You can change the color of the Text Selection.

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

    Custom background, text and selection colors (under Theme click See all options, Colors).
    
Regards,
Gusted

**Comment by Cyberbeni** [comment]
Thanks. The actual highlight will be slightly different color than the one set here, so copy pasting the color code wasn't enough I got to #009bea with some trial and error and it's close enough. (At least on google.com)
