### ISSUE TITLE
NO INVERT doesn't seem to work in dev tools for Dynamic Theme

### ISSUE THREAD

**Issue by lingylol** [darkreader/darkreader#463]
I tried using NOINVERT, as well as pretty much every variant of it but I can't seem to get it to work. The Dev tools either split it to leave just INVERT or delete it altogether. Perhaps it was renamed or something?

**Comment by lingylol** [comment]
[](url)

**Comment by alexanderby** [comment]
Dynamic Theme config has `INVERT` only, I'm also thinking of adding `REMOVE BG`. Inversion Fixes has `INVERT`, `NO INVERT`, `REMOVE BG` and `CSS` https://github.com/darkreader/darkreader#using-dev-tools

**Comment by freMea** [comment]
So how can we easily test `NO INVERT`, `REMOVE BG` and `CSS` if the dev tools can't handle them ? We would need dev tools to handle those options or let the user select a FILTER THEME EDITOR that could apply them.

And what about STATIC themes ? We need to fix it for some sites for those it's the best theme like [here](https://fr.audiofanzine.com/sequenceur-generaliste/presonus/studio-one-4-professional/forums/t.666051,commentaires-sur-le-test-studio-one-prend-la-chord,post.9637153.html).

**Comment by alexanderby** [comment]
I will add them soon (not sure about `NO INVERT` for dynamic mode yet). Unfortunately I was not farsighted to the necessity of these options. Versions before 4.5.5 (published 3 weeks ago) will work incorrectly after adding new options into config, that they don't know. Chrome Web Store stats shows that at least 5% of all users have old versions installed. I don't know what's the reason for not updating, but there is a chance these users will be not satisfied with the changes. So I will try to finish it by the end of week.

**Comment by NSExceptional** [comment]
Why was this issue closed? Can you reopen it, @alexanderby? We still need `NO INVERT` for the Filter/+ modes at least.
