### ISSUE TITLE
[BUG] Dark Reader inverts PDF link/site not listed in "Invert Listed Only"

### ISSUE THREAD

**Issue by LittleBenjiBoy** [darkreader/darkreader#4635]
### **Describe the bug**
Dark Reader inverts any PDF link/site not listed in "Invert Listed Only". 

### **Steps to reproduce**
- Activate Dark Reader extension by clicking on it.
- Click on 'Site List'
- Click on 'Invert Listed Only'
- Open any link containing a PDF, for example: https://www.thinkfun.com/wp-content/uploads/2015/09/RushH2-5010-IN.pdf
- 'Invert Listed Only' does not have 'thinkfun.com'. 

### **Expected behavior**
I expect Dark Reader to not invert this PDF link/site. When I turn off Dark Reader, the PDF page is no longer inverted.

### **Actual behavior**
Dark Reader inverted the PDF page/link.

### **System Information:**
- OS: Windows 10
- Browser: Tested on Microsoft Edge Chromium 89 (Dev Channel) and Google Chrome 87.
- Dark Reader version: 4.9.25 on Microsoft Edge and 4.9.26 on Google Chrome

### **Additional context**
This happens with every other PDF site/link I encounter.

**Comment by Gusted** [comment]
Hi @B3nji957!

This is intended behaviour, the PDF is completely separate from the normal URL matching.

Regards,
Gusted

**Comment by LittleBenjiBoy** [comment]
Hi Gusted!

@Gusted thank you for your reply! But can this be a feature request to have an option to enable to stop PDF links from being inverted? It would be convenient to not have to disable Dark Reader each time.

Note that Dark Reader does not invert PDFs that I open with my browser.

Many thanks!
Ben

**Comment by LittleBenjiBoy** [comment]
Hi @Gusted!

Thank you for your reply! I've found my solution! By activating Dark Reader and opening "Dev Tools", clicking on "Preview new design", then going to "Settings", "Site List" and clicking on "Enable for PDF files", which was previously enabled.

Thank you,
Ben
