### ISSUE TITLE
dynamic theme - artefacts when using atlassian stash

### ISSUE THREAD

**Issue by sloik** [darkreader/darkreader#464]
When using dynamic theme:
![screen shot 2018-05-07 at 10 50 27](https://user-images.githubusercontent.com/1531955/39693536-a2e07dde-51e4-11e8-9c13-ae3a10f2bab9.png)
![screen shot 2018-05-07 at 10 50 32](https://user-images.githubusercontent.com/1531955/39693537-a300f8ca-51e4-11e8-8066-e7cf2cdc7ff5.png)

**Comment by alexanderby** [comment]
My free Atlassian account expired recently. A more reliable fix for problems like this was made in version 4.5.6, could you please have a look?

**Comment by sloik** [comment]
I will be back on monday and I will check it out :) Cheers :D

**Comment by alexanderby** [comment]
There was another open Jira issue, and reporter said it is fixed now https://github.com/darkreader/darkreader/issues/405

**Comment by sloik** [comment]
It works :) Thx :)
