### ISSUE TITLE
Google Sheets white boxes with Force Dark Mode flag

### ISSUE THREAD

**Issue by StructByLightning** [darkreader/darkreader#4653]
## Reproduction
1. Enable the Force Dark Mode flag at chrome://flags/#extensions-on-chrome-urls.
2.Turn on Dark Reader's dynamic theming 
3. Go to sheets.google.com
4. Sign in and create a new spreadsheet
5. Click in one of the cells

## Expected result
The formula bar and input cells should be darkened like the rest of the page.

## Actual result
The formula bar and input cells are a bright white and their contents are illegible.
![image](https://user-images.githubusercontent.com/32056364/103471232-9517ca80-4d32-11eb-8eff-c6c4aebffeee.png)

## Misc
It works fine without the Force Dark Mode flag, but then every site has a white flash and Chrome's internal pages are all brilliant white since Dark Reader can't theme them. Filter/filter+ left the inactive cells white and static turned everything a murky blue (including the text inside the cells).

**Comment by Gusted** [comment]
Hi @StructByLightning!

Any configuration with other dark modes enable isn't supported by Dark Reader due to bugs/inconsistency in situations like this.

Regards,
Gusted
