### ISSUE TITLE
[BUG] Wordpress video not loading

### ISSUE THREAD

**Issue by LuiggiPiumbu** [darkreader/darkreader#4657]
WordPress hosted (Videopress) videos are not loading when DarkReader is enabled.  Will work when disabled.

Steps to reproduce

- Enable Dark Reader
- Go to any Wordpress website using  Videopress (for example https://videopress.com/)
- Click on The video
- It Will display "Loading..." forever

(If you disable the extension and reload, the video will normally play.)

Tested with Firefox, on Windows 10 and Linux (Manjaro)

**Comment by Gusted** [comment]
Please open up a ticker over at videopress for this, we can't fix this issue from Dark Reader's side.
