### ISSUE TITLE
Noto Emoji fonts are inverted

### ISSUE THREAD

**Issue by travankor** [darkreader/darkreader#466]
Tested on linux, emojis rendered by the Noto Emoji font are inverted. 

[Example 1](https://s14.postimg.cc/squivx4jl/emoji.png)

[Example 2](https://s14.postimg.cc/jj2af9029/skintoneemoji.png)

**Comment by alexanderby** [comment]
I've added a fix for website you mentioned. If you mean that it doesn't work on all websites, than I think there is no solution with CSS filters if emoji is placed somewhere in text, use Dynamic mode instead.
