### ISSUE TITLE
[Broken Website] rpcs3 compatibility page

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#4660]
**Website**
https://rpcs3.net/compatibility

**Expected behavior**
Text is inverted and is readable

**Actual behavior**
Text at the top is not inverted and thus becomes unreadable.

**Screenshots**
![image](https://user-images.githubusercontent.com/22572406/103506130-ed67dd00-4e96-11eb-8544-4d8846635d24.png)

**System info:**

- OS: Windows
- Browser: Firefox 84.0.1
- Darkreader Version: 4.9.26

**Comment by AndrewDaGuy** [comment]
[done](https://github.com/darkreader/darkreader/pull/4664)
