### ISSUE TITLE
Where are the user preferences writen?

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#467]
Hello! I am trying to know where does Dark Reader write the user preferences, for example the mode, the brightness level, the sepia level, etc. I want to know it to write a script in my computer to swap from my dark settings to my light settings easily.

Thank you very much for this program, it is an amazing piece of software.

**Comment by alexanderby** [comment]
The extension uses Chrome Storage Sync API, to get your settings you can right-click Dark Reader icon and click **Inspect popup**. Then open **Console** tab and execute
```javascript
chrome.storage.sync.get(['config'], (config) => console.log(JSON.stringify(config, null, ' ')));
```

**Comment by Aqa-Ib** [comment]
Nice! Thank you very much sir, now I see it clear.
In the future it would be an awesome feature if Dark Reader could remember the user settings of brightness, contrast, grayscale and sepia for both, the dark and the light mode.

Keep up the good work, Dark Reader has revolutioned the way we surf the web!
Best regards.

**Comment by alexanderby** [comment]
Dark Reader 4.4 allows you to store site-specific settings http://darkreader.org/blog/custom-site-settings/
