### ISSUE TITLE
Maybe a better editer for website list is good idea

### ISSUE THREAD

**Issue by FantaZZ** [darkreader/darkreader#4672]
**Is your feature request related to a problem? Please describe.**
No problem, just a suggest.

**Describe the solution you'd like**
Maybe a better editer for website list is good idea

**Additional context**
I use dark reader long time, so I have a long website list in there.
When I want to edit this list, it is difficulty.

**Comment by Gusted** [comment]
Hi @FantaZZ!

We are currently working on a new UI for v5, which you can currently preview by following the next steps:
    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    
And please look under Settings -> Site List to see the new sitelist.

Regards,
Gusted

**Comment by FantaZZ** [comment]
Good job
