### ISSUE TITLE
[BUG] Buying an album pop up on bandcamp

### ISSUE THREAD

**Issue by Nowena** [darkreader/darkreader#4673]
### **Describe the bug**

The pop up window that appears when you try to buy an album looks weird

### **Steps to reproduce**

- Go to 'bandcamp'
- As an example, look for a band callled Allochiria
- Try to download one of their albums, then you see the pop up

### **Expected behavior**

The pop up should look smooth

### **Actual behavior**

The pop is one part black and the other is grey instead of being a single colour

### **Screenshots**

https://i.imgur.com/oyASTNM.png

### **System Information:**

- OS: Windows 10
- Browser: Opera 73.0.3856.329
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Same popup issue with #4478 which has been in #4480, but not in 4.9.26 applied, it should be by the next release.

**Comment by Nowena** [comment]
When the price is in dollars and doesn't need to be converted, the popup looks fine. That Allochiria page has the price in euros so that's why it looks like that. Any other currency that you want to convert to dollars (or anything else) looks like the Allochiria page.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/103814055-fa342e80-5058-11eb-8478-5148e4677c4e.png)
The converted price popup also looks good with the fix.

**Comment by Nowena** [comment]
Why does it look different (like the screenshot I gave) on Allochiria's page? I tried other pages too and it looks fine like you just showed. Is this like the bandcamp logo that for some reason looks different depending on the band page? 

And I added the fix that resolves #4478 and #4480 when you first posted it a while ago using the dev tools but it still looks that way on Allochiria's page.

**Comment by Gusted** [comment]
The site isn't bandcamp but an custom site 
![image](https://user-images.githubusercontent.com/25481501/103820419-3faa2900-5064-11eb-833b-ad301da41fae.png)

**Comment by Nowena** [comment]
Oh yea, I tried another custom site (the page for Autarch) and it looks just like the Allochiria page. 

So is there a global fix for all this bandcamp-based custom sites or you'd have to add extra code for every single one of them in order to fix this?

If there's no global fix then I guess it's staying that way.

**Comment by Gusted** [comment]
> So is there a global fix for all this bandcamp-based custom sites or you'd have to add extra code for every single one of them in order to fix this?

Depends if they don't share a common part in their URL then we've to add every single URL that has this issue.
