### ISSUE TITLE
[Broken Website]  brave.com

### ISSUE THREAD

**Issue by AndrewDaGuy** [darkreader/darkreader#4681]
**Website**
https://brave.com/

**Expected behavior**
The "wave" gradient is blackish/inverted

**Actual behavior**
The "wave" gradient is retina-burning white

**Screenshots**

**System info:**

- OS: `macOS 10.14.6`
- Browser: `Brave 1.18.77`
- Darkreader Version: `4.9.26`

**Additional context**

The element thats not inverted (i think) 
```html
<img style="width: 100%; height: auto;" src="/static-assets/images/blurplebg_light.svg" alt="">
<img style="width: 100%; height: auto;" src="/static-assets/images/blurplebg.svg">
```

**Comment by AndrewDaGuy** [comment]
forgot screenshots:

Dark mode:

![image](https://user-images.githubusercontent.com/66189242/103733019-98fb5500-4f9d-11eb-992e-870f70ebb350.png)
![image](https://user-images.githubusercontent.com/66189242/103732992-85e88500-4f9d-11eb-8ba4-c5a7cccc96a5.png)

Light:
![image](https://user-images.githubusercontent.com/66189242/103733043-aca6bb80-4f9d-11eb-86f9-351fe6e066ae.png)
![image](https://user-images.githubusercontent.com/66189242/103733111-d1029800-4f9d-11eb-8931-0d3613e18e56.png)

**Comment by Gusted** [comment]
Hi @AndrewDaGuy 

It isn't technically possible to get the effect back if it's an image. SVG would been a different story. Unless someone is willing to put time to get an hand fully crafted `invert` CSS it won't be possible to get this waviness back. As this would be quite annoying for an dark reader to see this I will remove this image.

Regards,
Gusted
