### ISSUE TITLE
[Broken Website] www.virustotal.com

### ISSUE THREAD

**Issue by JadenJSJ** [darkreader/darkreader#4682]
**Website**
www.virustotal.com

**How to Reproduce**
An example of this is
> Visit the site
> The site dosen't fully turn dark
> The logo just dissapears

**Expected behavior**
Expected behaviour is the logo existing, and the upload box dark

**Actual behavior**
Logo not there and the upload box being light themed

**Screenshots**
![image](https://user-images.githubusercontent.com/44781632/103733376-34330f80-501c-11eb-85ad-65f49ebf8f2c.png)

**Browser Info**

Google Chrome | 89.0.4379.0 (Official Build) canary (64-bit) (cohort: Clang-64)
Revision | de20bcd3d57dae2e47f65e5323e617273233af40-refs/branch-heads/4379@{#1}
OS | Windows 10 OS Version 2009 (Build 19042.685)
JavaScript | V8 8.9.204

**System info:**

Device name	JadenJSJ-Laptop
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
Installed RAM	8.00 GB (7.85 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎10/‎28/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional context**
But the weird thing is that the dark theme works time to time then randomly stops working.
![image](https://user-images.githubusercontent.com/44781632/103733652-d0f5ad00-501c-11eb-9c96-2a6101434ad4.png)

**Comment by AndrewDaGuy** [comment]
thats a lot of info you got there 0_o

**Comment by Gusted** [comment]
Note to myself: It might be a browser specific issues, Firefox didn't show any reproduce at all with `layout.css.constructable-stylesheets.enabled` enabled which should give the same web envirement as chrome for the API's virustotal CSS uses.

**Comment by AndrewDaGuy** [comment]
the logo seems to  disappear when the upload part loads

**Comment by AndrewDaGuy** [comment]
More info: it seems to always break when you do a hard reset, going to check on other broswers

**Comment by rakleed** [comment]
@Gusted in versions 4.9.30 and 4.9.31, even after turning off and turning on DarkReader, on [the main page](https://www.virustotal.com/gui/home/upload) the footer does not become dark, and on [the page with the results](https://www.virustotal.com/gui/file/cd7df18a2bf36c24f6053030134971a28c6d22b4ed6df1ee5b4caa02d2ac51f6/detection) the header and information about the file also do not turn dark.

**Comment by fredddd1** [comment]
Can confirm the issue, has been present for a long while now, pretty frustrating.

OS: Windows 64-bit Version 20H2 (OS Build 19042.928)
Browser: Google Chrome Version 89.0.4389.128 (Official Build) (64-bit)
Dark Reader Version: 4.9.32

![dark-reader-virustotal](https://user-images.githubusercontent.com/80743272/115954309-824b2080-a4f0-11eb-870b-60015a091d1a.png)

**Comment by shenzhiming88** [comment]
@Gusted Hello! This looks like it's not working at all
https://www.virustotal.com/gui/file/5d95b04f1931e30470f6f02d5eb089570a5df24aaea3e9fb5e22574693bf5eec/detection
![image](https://user-images.githubusercontent.com/66902050/127665731-27e1d58c-4771-4d03-a05a-41922100f09b.png)

**Comment by rakleed** [comment]
@Gusted still during scanning, the animation of the wheel in the upper left corner breaks.

<details><summary>Screenshots</summary>

![screenshot-www-virustotal-com-gui-file-analysis-YWUxMTA2NDE3YTFjY2U5OGE2N2E-1628074123753](https://user-images.githubusercontent.com/19418601/128168826-35a98c94-aa50-4100-90dc-c204d3ead38a.png)

![screenshot-www-virustotal-com-gui-file-analysis-YWUxMTA2NDE3YTFjY2U5OGE2N2E-1628074117876](https://user-images.githubusercontent.com/19418601/128168821-156caa5a-fdd0-48a0-ad42-17df77492162.png)

</details>

And also the wheel is not displayed in the results.

<details><summary>Screenshots</summary>

![screenshot-www-virustotal-com-gui-file-3782c9f96d9bdf19928bd41fc78573bc6782-1628074257225](https://user-images.githubusercontent.com/19418601/128168973-71983582-2395-401b-9a76-fccc9ac76792.png)

![screenshot-www-virustotal-com-gui-file-3782c9f96d9bdf19928bd41fc78573bc6782-1628074300494](https://user-images.githubusercontent.com/19418601/128168999-bedc3454-6ba3-47a8-84de-44503398bdc6.png)

</details>

**Comment by rakleed** [comment]
@Gusted if you reload the page several times, sometimes it will still load with non-inverted styles for some elements. Can this be fixed?

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/128708740-08f2b068-1bbd-40e2-ac84-7e568018b250.png)

![image](https://user-images.githubusercontent.com/19418601/128708769-e64bf7b6-9ba1-4f6d-8671-875ba259d6eb.png)

</details>

**Comment by Gusted** [comment]
Yep I'm aware of that issues, and a very hard issue to reproduce/add tests for. As this is something with the current implementation of "searching" [shadow roots](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot). Which isn't really performant not reliable and causes this kind of issues. Currently I cannot think of a better way nor I can't find any way to improve this behavior and is unfortunaly something to live with for now. Little improvements can be made trough slowing down this code so it has more success of finding _all_ shadow roots, but still not a guarantee.

**Comment by rakleed** [comment]
@Gusted there are more non-inverted elements at https://www.virustotal.com/gui/file/a8a7b9bcaf86f22587fe70a1069a06ded71244ebe1ce0640be8b07037f149b7f/relations and https://www.virustotal.com/gui/file/a8a7b9bcaf86f22587fe70a1069a06ded71244ebe1ce0640be8b07037f149b7f/community.

**Comment by rakleed** [comment]
@Gusted ping

**Comment by Gusted** [comment]
I do not mind fixing it, but the fundamental issues are just that shadow-roots are currently a issue in dark reader and cannot be very easily fixed as they all posses their own DOM, and browsers currently don't seem to like them either - I have a stash somewhere that has on paper more reliably and is using proxies, but yet, it doesn't work and just sucks as well as the current implementation.

**Comment by Gusted** [comment]
Main issue to track shadow-root problems.

**Comment by qarmin** [comment]
Still broken
![Screenshot from 2022-08-30 20-19-29](https://user-images.githubusercontent.com/41945903/187513462-c604b79b-bfd9-4842-99c5-4cdd3433e6d5.png)

**Comment by dexeonify** [comment]
Works in Chromium browsers, but not Firefox. Thankfully, filter mode works very well for this website. You can learn how to set it here: https://darkreader.org/blog/filter-mode/

**Comment by Pdzoc** [comment]
I've found another problem on virusTotal:

![virusTotalIssue](https://user-images.githubusercontent.com/71113600/192129107-44dea5fc-bfe1-4313-9a43-9d7328b15dbc.jpg)

Windows, DR 4.9.57, Chrome 105

**Comment by aydynx** [comment]
not inverting at all, on windows using firefox
![image](https://user-images.githubusercontent.com/75395457/197645946-27fb5d9b-444f-40fa-91c3-0ac386283860.png)

**Comment by Dragodraki** [comment]
www.virustotal.com still shows white background though Dark Reader is active.
Maybe you can fix it with the next update since the problem still exists and www.virustotal.com ist one of the major webportals around the internet as for security. Of course, I can activate the websites own dark theme but thats not the same and won't withstanding when I delete my cookies.

**Comment by Tintedfireglass** [comment]
It partly works on chrome but non-functioning on firefox

**Comment by JadenJSJ** [comment]
VirusTotal now has a built in dark mode, maybe we can just add the site to a global blacklist?
note: virustotal has light default theme
![2023-09-07_11-21](https://github.com/darkreader/darkreader/assets/44781632/758baa3c-d1cc-4aca-8585-cae12803e25a)
![2023-09-07_11-22](https://github.com/darkreader/darkreader/assets/44781632/0426dfa6-1aca-4564-bc10-f206382684e6)

**Comment by alexanderby** [comment]
Looks like it's working fine now.

**Comment by Dragodraki** [comment]
Yeah, it works now.
