### ISSUE TITLE
[Broken Website] getmimo.com

### ISSUE THREAD

**Issue by stef-devs** [darkreader/darkreader#4698]
**Website**
The link to the broken website
[Mimo](https://getmimo.com/)
**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors

**Expected behavior**

**Actual behavior**
A clear and concise description of what happened.

**Screenshots**

**System info:**

- OS: [e.g. Windows, MacOS, Linux]
- Browser: [e.g. chrome, safari]
- Darkreader Version: [e.g. 4.9.9]

**Additional context**

**Comment by AndrewDaGuy** [comment]
:/ whats the problem

**Comment by AndrewDaGuy** [comment]
nvm

**Comment by stef-devs** [comment]
Oops I was wrong to write issues, in practice the Mimo site when I log in does not load the rest of the page, and I only see the login page and it does not make me go forward. I removed the plugin for the site and everything worked fine.

**Comment by Gusted** [comment]
Hi @stef-devs!

Does it show any errors in the console when mimo won't load with Dark Reader enabled?

Regards,
Gusted

**Comment by stef-devs** [comment]
Hi, sorry for the delay in replying, I am attaching the console logs.
These mistakes are repeated hundreds of times.
![console](https://user-images.githubusercontent.com/68437687/104086311-100f4280-5257-11eb-8380-7792cef95425.PNG)

**Comment by Gusted** [comment]
Those are errors from getmimo, which is only fixable by mimo itself. We unfortunately can't do anything about this issue.
