### ISSUE TITLE
[Broken Website] binance.com -  checkboxes show being ticked when they aren’t

### ISSUE THREAD

**Issue by vKnmnn** [darkreader/darkreader#4702]
**Website**
[https://www.binance.com/de/my/settings/api-management](https://www.binance.com/de/my/settings/api-management)

**How to Reproduce**
> create an api key

**Expected behavior**
correct checkboxes

**Actual behavior**
greyed-out checkboxes seem to be ticked

**Screenshots**
![image](https://user-images.githubusercontent.com/16045883/103903359-1a68f980-50fc-11eb-913f-0e45fdae1af5.png)
![image](https://user-images.githubusercontent.com/16045883/103903406-22c13480-50fc-11eb-8920-40d8d7b57690.png)

**System info:**

- OS: Linux
- Browser: Firefox 83 from fedora
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
Ah... Crypto sites of the many sites I can't legally enter nor register.
Someone who has a binance account can come up with a CSS Fix it shouldn't be hard to make an checkbox which isn't checked to an default color(probably `var(--darkreader-neutral-background)`). The real question is to have a CSS Selector for this.

Regards,
Gusted
