### ISSUE TITLE
[BUG] arguments in dynamic-theme passed to overrideInlineStyle  are in the wrong order.

### ISSUE THREAD

**Issue by softgripper** [darkreader/darkreader#4705]
### **Describe the bug**
In src/inject/dynamic-theme/index.ts

ignoreInlineSelectors and ignoreImageSelectors are in the wrong order when passed to overrideInlineStyle method on lines
209 and 384

This causes strange behavior when trying to use ignore functionality.

**Comment by Gusted** [comment]
Thanks! Not sure how that slipped trough code review.

**Comment by softgripper** [comment]
> Thanks! Not sure how that slipped trough code review.

It happens.

Maybe need them as types or something to prevent it.  Passing around 2 string arrays is risky business 👍

**Comment by Gusted** [comment]
> Maybe need them as types or something to prevent it. Passing around 2 string arrays is risky business +1

I would look into that, so it won't happen in the future.
