### ISSUE TITLE
[Dynamic] Embedded tweet background color is white

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#471]
Steps:
1. Open a page with embedded tweets.

Result:
Tweet background color is white.

Some examples:
https://meduza.io/slides/vsya-amerika-obsuzhdaet-novyy-klip-chayldisha-gambino-pochemu
![image](https://user-images.githubusercontent.com/26354715/39784354-c30555d4-5320-11e8-8e3d-5ab31fa1fefe.png)
https://dev.twitter.com/web/embedded-tweets
![image](https://user-images.githubusercontent.com/26354715/39784385-de3054da-5320-11e8-9c08-721b88938748.png)

**Comment by alexanderby** [comment]
Should be fixed in v4.5.8

**Comment by rolagg** [comment]
Not fixed yet: #813
