### ISSUE TITLE
[BUG] Dark Reader won't work for sub-domains, exclusively.

### ISSUE THREAD

**Issue by martin-braun** [darkreader/darkreader#4713]
### **Describe the bug**

Trying to enable dark reader only for a subdomain, while keeping the main domain untouched is impossible. The subdomain will not turn into dark mode.

### **Steps to reproduce**

- Go to github.com and disable darkreader (because GitHub offers an own darkmode)
- Now go to gist.github.com that does not support dark mode yet and try to enable the plugin only for the subdomain
- Dark mode will only work when whole GitHub is on dark mode.

### **Expected behavior**

gist.github.com should get dark while github.com will not be affected by darkreader

### **Actual behavior**

gist.github.com won't turn dark when enabling darkreader when darkreader is of for main domain github.com

### **Screenshots**

![2021-01-09 03 12 04](https://user-images.githubusercontent.com/24259245/104080489-8ba5cb00-5228-11eb-87e6-5563eccb114a.gif)

### **System Information:**

- OS: macOS 11.1 (20C69)
- Browser: Brave Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)
- Dark Reader version: 4.9.26

### **Additional Context:**

Clicking the "Only for gist.github.com" button had no effect, either.

**Comment by Gusted** [comment]
#4508
