### ISSUE TITLE
[BUG] ^github.com disables Dark Reader on github.community

### ISSUE THREAD

**Issue by nyuszika7h** [darkreader/darkreader#4717]
### **Describe the bug**

Since GitHub has native dark mode but it does not extend to subdomains like gist.github.com yet, I added `^github.com` to the "not invert" list. However, this also excludes github.community from the inversion, and I haven't found a way to fix this.

I've also tried the following:
* `^github.com/`: makes no difference
* `^github.com$`: doesn't invert the front page of github.com, but any pages under it are inverte
* `^github.com` and `!github.community`: makes no difference

### **Steps to reproduce**

- Turn on "Enable by default"
- Add `^github.com` to the site list
- Visit github.community

### **Expected behavior**

github.community should be inverted.

### **Actual behavior**

The site is not inverted.

### **System Information:**

- OS: Windows 10 20H2
- Browser: Edge 87.0.664.66
- Dark Reader version: Version 5 Preview (4.9.26)

**Comment by Gusted** [comment]
Hi @nyuszika7h!

This issue has been addressed in a PR https://github.com/darkreader/darkreader/pull/2517#issuecomment-742345717 and is fixed https://github.com/darkreader/darkreader/commit/bdf0850629a7b203c7d19f5e201a742938dfed1e

Regards,
Gusted
