### ISSUE TITLE
[Dynamic] Google docs very slow

### ISSUE THREAD

**Issue by v4lley** [darkreader/darkreader#472]
I was editing a document in google docs when i noticed that when writing and deleting characters they had a delay and appeared very slowly on the screen. I then discovered that it was because of the dynamic engine, when using the old engine everything was very smooth.

**Comment by alexanderby** [comment]
Please, check if it is still slow in version 4.5.2

**Comment by v4lley** [comment]
It's fixed, it works now!

**Comment by Sneffel** [comment]
Still very slow
