### ISSUE TITLE
[Feature Request] That you can set that the boxes of the website keep the same look as the original site,but in dark.

### ISSUE THREAD

**Issue by Toadfield** [darkreader/darkreader#4726]
**Is your feature request related to a problem? Please describe.**
So for example,normally on the site it looks [like this](https://i.imgur.com/YXrSxsh.png),but with Darkreader it looks [like this](https://i.imgur.com/epO7CKD.png).
My problem is that the boxes don't keep their shape.

**Describe the solution you'd like**
That the boxes look like the same,but dark.

**Comment by Gusted** [comment]
Dup #734 #3239
