### ISSUE TITLE
[BUG]Sometimes if I switch between multiple tabs the dark mode is buggy and I have to disable and then enable the dark mode gain so it looks normal

### ISSUE THREAD

**Issue by Toadfield** [darkreader/darkreader#4728]
### **Describe the bug**

If I have many tabs open and Darkreader enabled on all of them and if I switch between them then sometimes if I go back to a tab it looks buggy.

### **Steps to reproduce**

-Open many tabs with dark reader
- Switch between them

### **Expected behavior**

That it doesn't look buggy.

### **Actual behavior**
That it looks like [this](https://i.imgur.com/cJUIoa1.png) instead of [this](https://i.imgur.com/piCqvoG.png).

### **System Information:**

- OS: Manjaro Kde with Kernel 5.10
- Browser: Firefox 84.0.1-0.1
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Firefox will discard the tab if system is low on memory, and the fallback is applied give it some time to remove itself.

**Comment by Toadfield** [comment]
Can I disable that in Firefox somehow?

**Comment by Gusted** [comment]
> Can I disable that in Firefox somehow?

Might be hidden somewhere in `about:config`, but I don't know 1..2..3.. which one.

Regards,
Gusted
