### ISSUE TITLE
[Feature Request] Modify URLs and Anchors

### ISSUE THREAD

**Issue by studiofruits** [darkreader/darkreader#4732]
Hi there, I have downloaded the dark reader code from github. I want to add a prefix before every single URL entered in Chrome address bar. For example:

If I type example.com in the Chrome address bar, the page loaded will be myserver.com/stat.html?example.html 

Also do you know how I would do this anchors in a webpage, for example:

<a href="https://www.example.com">example.com</a>  is converted to <a href="https://myserver.com/stat.html?https://www.example.com">example.com</a>

Is there an easy way to do this? Like modifying url.host to: ""https://myserver.com/stat.html?"+ url.host    ??

Any help is greatly appreciated

**Comment by Gusted** [comment]
Not in our scope to do this.
