### ISSUE TITLE
[Broken Website] Twitter.com

### ISSUE THREAD

**Issue by privacyguy123** [darkreader/darkreader#4739]
**Website**
https://www.twitter.com

**How to Reproduce**

>
> 1. Go to site
> 2. See that both side panels of Twitter are unaffected by Dark Reader now - this is a new bug.

**Expected behavior**
Expecting the same dark colour across the whole page.

**Actual behavior**
See above.

**Screenshots**
![image](https://user-images.githubusercontent.com/50337995/104177530-d417e100-5400-11eb-81be-148ed5885dc1.png)

**System info:**

- OS: Windows 10 Pro
- Browser: FireFox 84.02
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
Noticed this too yesterday and made a fix #4735

**Comment by privacyguy123** [comment]
You mentioned a fix for this but Twitter still looks like this for me?

**Comment by Gusted** [comment]
Thanks for letting me know, seems like they've changed their CSS again. I will make another fix.

**Comment by Gusted** [comment]
#4916
