### ISSUE TITLE
[Feature Request] See all changes made by DarkReader and edit them

### ISSUE THREAD

**Issue by jupiter104** [darkreader/darkreader#4745]
Let's say I applied DarkReader on a site and there are some changes done by DarkReader that I don't like. For example, it made a specific font too dark or put a weird border around something. So, I want the feature to be able to see all the changes (CSS) made by DarkReader to that site so I can edit out certain changes and make it perfect for me. Sorry, if this is already possible in DarkReader but I couldn't find any such options.

**Comment by Gusted** [comment]
Use an external tool like Stylus to edit CSS or the Dev Tools itself.

**Comment by jupiter104** [comment]
> Use an external tool like Stylus to edit CSS or the Dev Tools itself.
Dev tools doesn't list all the changes it makes to a site, only a few. I know about Stylus but if you don't know exactly what Dark Reader is changing, it's pointless.

**Comment by Gusted** [comment]
> I know about Stylus but if you don't know exactly what Dark Reader is changing, it's pointless.

How could Dark Reader elaborate what's changing? We don't have an element picker nor probably have one in the future.
If you want the pure chances that Dark Reader make, please read about [Export Generated CSS](https://darkreader.org/blog/v4-9-16/)

**Comment by jupiter104** [comment]
> How could Dark Reader elaborate what's changing? We don't have an element picker nor probably have one in the future.
> If you want the pure chances that Dark Reader make, please read about [Export Generated CSS](https://darkreader.org/blog/v4-9-16/)

Where is this setting to export generated css? When I click the three dots, it shows automation options only.

**Comment by Gusted** [comment]
```


Users, who activated Dark Reader v5 Preview, can try some new features. It's easy to activate if you haven't already:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

```

**Comment by jupiter104** [comment]
That makes life a lot easier. The new design is pretty cool.
