### ISSUE TITLE
Gmail loads very slow [BUG]

### ISSUE THREAD

**Issue by mrlinuxfish** [darkreader/darkreader#4746]
### **Describe the bug**

Gmail is very slow to load with darkreader enabled. Sometimes it will take up to a minute to load to the point any of the site elements are able to be interacted with. Disabling darkreader allows the site to load within about a second.

### **System Information:**

- OS: Arch Linux
- Browser: Firefox 84.0.2
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Open an [performance issue](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=&template=performance_issue.md&title=%5BPerformance%5D+)
