### ISSUE TITLE
[Broken Website] - script.google.com

### ISSUE THREAD

**Issue by swvajanyatek** [darkreader/darkreader#4751]
**Website**
script.google.com

**How to Reproduce**
open any google app script project file

**Expected behavior**
Caret should be visible

**Actual behavior**
The caret in the editor not visible when using Dark Reader

**System info:**
- OS: Windows
- Browser: Version 87.0.4280.141 (Official Build) (64-bit)
- Darkreader Version: v4.9.16

**Comment by Gusted** [comment]
Hi @swvajanyatek!

Could you elaborate what you mean by `caret`?

Regards,
Gusted

**Comment by swvajanyatek** [comment]
The "pipe" or "bar" that indicates where the cursor is.  I took a swing at using the Developers Tool and my google-fu suggested that what I think of as the "cursor" is actually called a "caret" in CSS.  But please know - i have no CSS skills.

**Comment by Gusted** [comment]
Duplicate https://github.com/darkreader/darkreader/issues?q=is%3Aissue+script.google.com+is%3Aclosed

**Comment by swvajanyatek** [comment]
forgive me for being dense, but does this mean that the issue is fixed but not yet released?  If so, is there an anticipated release date?  tia

**Comment by Gusted** [comment]
Not yet released. Release Dates are not knon.

**Comment by swvajanyatek** [comment]
got it. i was able to build and install from source.  works great again, thank you so much!
