### ISSUE TITLE
Dynamic Theme on several YouTube elements

### ISSUE THREAD

**Issue by KeldorKatarn** [darkreader/darkreader#477]
The dynamic theme is getting better but it still has several issues on youtube. 
In the creator studio the buttons at the top next to the user menu (bell icon for new messages and upload arrow icon) are black on dark grey. depending on the settings. One get fix that by changing the contrast slightly but that makes other things worse. Those should really be turned white.

Same when trying to respond to a comment. While already existing comments are fine, light text on dark background, the textbox where you enter NEW comments is black text.

**Comment by Gusted** [comment]
Should be fixed.
