### ISSUE TITLE
Options applicable separately for each container

### ISSUE THREAD

**Issue by opqriu** [darkreader/darkreader#4777]
I would like to have a feature that applies Firefox Multi Account Containers separately.  [Options applicable separately for each container] [LINK](https://addons.mozilla.org/ko/firefox/addon/multi-account-containers/)
But even without this feature, Darkreader is just too good.
Thank you.

**Comment by Gusted** [comment]
Stick to the [format](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=[Feature+Request]%20).
