### ISSUE TITLE
Dynamic Theme makes some icons on forums invisible

### ISSUE THREAD

**Issue by KeldorKatarn** [darkreader/darkreader#478]
See title. A good example is this forum:

https://www.tt-forums.net/

the icons to the left of the subforums, which show whether the forums contain new posts, are invisible with the dynamic theme.

**Comment by alexanderby** [comment]
I'm not sure, but maybe it is fixed already?

**Comment by toolatetotheparty** [comment]
forum.ixbt.com icon corruption https://i.imgur.com/MukoK4J.png
