### ISSUE TITLE
[BUG] iOS 12.4.8 TypeError: darkScheme.addEventListener is not a function

### ISSUE THREAD

**Issue by guyskk** [darkreader/darkreader#4788]
### **Describe the bug**

DarkReader.auto in iOS 12.4.8 will cause error, tested in both safari and chrome.

### **Steps to reproduce**

Execute below code in iOS Safari or iOS Chrome:

```javascript
import * as DarkReader from 'darkreader'
DarkReader.auto({
    brightness: 95,
    contrast: 95,
})
```

Error shows in console:

```javascript
TypeError: darkScheme.addEventListener is not a function. (In 'darkScheme.addEventListener('change', handleColorScheme)', 'darkScheme.addEventListener' is undefined)
```

### **Expected behavior**

Expect not throw error, skip dark mode, and maybe log a warning message to console.

### **Actual behavior**

Throws an error and my code after DarkReader.auto() will not execute.

### **Screenshots**

NA

### **System Information:**

- OS: iOS 12.4.8
- Browser: Chrome 87.0, Safari.
- Dark Reader version: 4.9.26

### **Additional context**

My workaround:

```javascript
import * as DarkReader from 'darkreader'
import _ from 'lodash'

function autoDarkMode() {
  // see also: https://web.dev/prefers-color-scheme/
  let match = window.matchMedia('(prefers-color-scheme)')
  if (match.media === 'not all' || _.isNil(match.addEventListener)) {
    console.log('Dark mode not supported!')
    return
  }
  DarkReader.auto({
      brightness: 95,
      contrast: 95,
  })
}
```

**Comment by Gusted** [comment]
#4501 https://github.com/darkreader/darkreader/pull/4501/commits/c4f02092c3bf66c7765eb71b91d097a10cf26dac

**Comment by alexanderby** [comment]
@guyskk Hi, please try version 4.9.27.

**Comment by Gusted** [comment]
#4839
