### ISSUE TITLE
Personalize the color of the fonts with dynamic mode

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#479]
With the new dynamic mode, I am using a global CSS style on top of it to personalize the color of the fonts and the result is awesome. 
It would be very nice if Dark Reader itself could have an option to select personalized colors for the fonts (normal fonts, links, and headers fonts colors basically).

P.S.: Actually you can try this by installing some extension like Stylus and pasting on it a CSS code like this one that I have made: https://pastebin.mozilla.org/9084996
Use it along Dark Reader !

**Comment by Gusted** [comment]
Hey @Aqa-Ib 

We recently added this feature to change the color of text.
Instructions how so: https://darkreader.org/blog/v4-9/

Regards,
Gusted
