### ISSUE TITLE
[Broken Website] chromestatus.com

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#4798]
**Website**
https://www.chromestatus.com/features/5678152091172864

**Expected behavior**
Text inverted to be readable

**Actual behavior**
Text not inverted

**Screenshots**
![image](https://user-images.githubusercontent.com/22572406/104846524-f08eae80-5915-11eb-8dbf-ff8d00a7b974.png)

**System info:**

- OS: Windows
- Browser: Firefox 84.0.2
- Darkreader Version: 4.9.26

**Comment by Gusted** [comment]
#4291 will fix this issue

**Comment by Araxeus** [comment]
@Gusted
Hey I don't want to open a new issue for this, but it seems that https://chromestatus.com/  is broken once again

**Comment by StevenSchifter** [comment]
There are forced white backgrounds on https://chromestatus.com/feature/5579556305502208 .

![Image](https://github.com/user-attachments/assets/5f756afe-e4f8-41b6-a599-3169e909e47f)
