### ISSUE TITLE
[Broken Website] redbubble.com

### ISSUE THREAD

**Issue by mattwelke** [darkreader/darkreader#4801]
**Website**
https://www.redbubble.com

**How to Reproduce**

1. Go to site
2. Search for anything
3. See that the link bar at the very top and the one below the search box still have a light background

**Expected behavior**
All parts of the page have a dark background

**Actual behavior**
The link bar at the very top and the one below the search box still have a light background

**Screenshots**
![image](https://user-images.githubusercontent.com/7719209/104972694-7c5d1500-59c0-11eb-95d0-d781b2b45d08.png)

**System info:**

- OS: Windows 10 Pro
- Browser: Firefox version 84.0.2 (64-bit)
- Darkreader Version: 4.9.26

**Comment by timothymhuang** [comment]
And when you don't search for anything it's even worse.
![chrome (398)](https://user-images.githubusercontent.com/59073651/105110074-aa029680-5a72-11eb-843d-fd67804325cb.png)
