### ISSUE TITLE
[Broken Website] Gmail Loading Icon

### ISSUE THREAD

**Issue by dragonBall561** [darkreader/darkreader#4812]
The Gmail loading icon is less dark at the top of the icon. Here is a screenshot
![bug](https://user-images.githubusercontent.com/61358474/105077284-4d937d00-5a5a-11eb-81f9-ed94e9ca9940.png)

I am using the Dynamic theme

**Comment by Gusted** [comment]
Stick to the [issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website.md&title=%5BBroken+Website%5D+).
