### ISSUE TITLE
[BUG] Doesn't work with local PDF file

### ISSUE THREAD

**Issue by karan221** [darkreader/darkreader#4814]
### **Doesn't work with local pdf files **

With microsoft edge, when pdf is open from the web it has dark mode but when you open a local pdf file with edge it doesn't have dark mode.

### **Steps to reproduce**

- Open any pdf file from web, e.g: https://cses.fi/book/book.pdf
- Save the file
- Open the saved file with edge

### **Expected behavior**

Dark mode with local pdf files.

### **Actual behavior**

No dark mode with local pdf files.

### **Screenshots**

![image](https://user-images.githubusercontent.com/41018276/105094141-d72e6380-5ac9-11eb-96ed-8fe0be094660.png)

### **System Information:**

- OS: [Windows 10 1909]
- Browser: [Microsoft Edge 87.0.664.66 ]
- Dark Reader version: [e.g. 4.9.25]

**Comment by Gusted** [comment]
dup #4497
