### ISSUE TITLE
Can not disable darkreader, neither using switch nor by uninstalling!

### ISSUE THREAD

**Issue by Hubert21** [darkreader/darkreader#4829]
Hello,
I can not disable darkreader, neither using the switch nor by uninstalling it!
Hence it's darken on Every website!
I am using a portable version of firefox 84.0.2 (using the portableapps.com plateform).
Uninstalling darkreader doesn't solve anything, even after restarting firefox.
Thanks in advance for your help.

**Comment by Gusted** [comment]
Stick to the [bug template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D).
Make sure you remove the addon trough "ctrl + shift + a" menu.
