### ISSUE TITLE
[BUG]Can not disable darkreader, neither using switch nor by uninstalling!

### ISSUE THREAD

**Issue by Hubert21** [darkreader/darkreader#4831]
### **Describe the bug**

Hello,
I can not disable darkreader, neither by using the switch nor by uninstalling it!
Hence it's darken on Every website!
I am using a portable version of firefox 84.0.2 (using the portableapps.com plateform).
Uninstalling darkreader doesn't solve anything, even after restarting firefox. (I removed the addon trough "ctrl + shift + a" menu)
Thanks in advance for your help.

### **Steps to reproduce**

- Install a portable version of firefox (e.g. using the portableapps.com plateform)
- Install darkreader (https://addons.mozilla.org/en-US/firefox/addon/darkreader/)
- at some point the off switch do not switch off anymore
- uninstall dark reader, the darkening of all the websites is still there, even if you restart firefox

### **Expected behavior**

I would expect to get all the websites back to normal when uninstalling or switching off darkreader

### **Actual behavior**

The websites are still dark, even when uninstalling dark reader and restarting firefox

### **System Information:**

- OS: Windows 10
- Browser: firefox 84.0.2, portable version
- Dark Reader version: 4.9.26

**Comment by Gusted** [comment]
Hi @Hubert21!

It seems like you've removed the addon from Firefox. Using the Addon menu. It seems like Firefox is not processing this and still holding Dark Reader in memory. I suggest to create an new profile and see if this problem is reproduce-able.

Regards,
Gusted

**Comment by Gusted** [comment]
No response.

**Comment by Hubert21** [comment]
Hi @Gusted !

Thanks for your feedback and your advises, and sorry for not replying before.
I actually got the problem solved in a weird way: by restarting the whole computer after reinstalling DarkReader, not just restarting firefox.
Best regards
