### ISSUE TITLE
[Broken Website] gitlab.com

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#4838]
# Broken Website

## Website
gitlab.com

## Expected behavior
The action buttons are visible.

## Actual behavior
The action buttons are not visible.

## Screenshots
![sshot-002](https://user-images.githubusercontent.com/36977733/105355598-47340b00-5bea-11eb-89c8-0d62b85d06f0.png)
![sshot-003](https://user-images.githubusercontent.com/36977733/105355605-49966500-5bea-11eb-97b4-c3065111d7df.png)

## System Information

- OS: Windows 10
- Browser: Firefox
- Dark Reader Version: 4.9.26

**Comment by Gusted** [comment]
Hey @linsui!

Do you have an example link?

Regards,
Gusted

**Comment by linsui** [comment]
For example, https://gitlab.com/fdroid/fdroidclient/-/issues/1568 .

**Comment by linsui** [comment]
Thanks!
