### ISSUE TITLE
[Feature Request] Sync DarkReader mode with device theme

### ISSUE THREAD

**Issue by dineshdevkota001** [darkreader/darkreader#4841]
# Feature Request

## Describe the solution you'd like

Sync the Dark Reader setting dark mode sequence to device theme. i.e. enable dark mode only if the device theme is dark theme. This works on site like youtube in dynamic theme.

**Comment by Gusted** [comment]
Dup #745

https://github.com/darkreader/darkreader/issues/745#issuecomment-564056626
https://github.com/darkreader/darkreader/issues/745#issuecomment-664382611
