### ISSUE TITLE
[Broken Website] docs.python.org

### ISSUE THREAD

**Issue by HexCodeFFF** [darkreader/darkreader#4847]
# Broken Website

## Website
https://docs.python.org/

## How to Reproduce
visit any documentation in docs.python.org, it's most consistently reproduced by clicking a google result. e.g. google "python multiprocessing" and click the link on google.

## Expected behavior
![image](https://user-images.githubusercontent.com/35177464/105515510-62f6ea00-5c9a-11eb-8266-4b15a17117d6.png)
I was able to get this screenshot by toggling the extension off and on which fixes the problem until i reopen the website

## Actual behavior
![image](https://user-images.githubusercontent.com/35177464/105515625-86ba3000-5c9a-11eb-86fa-240fc675aeec.png)

## Screenshots
see above

## System Information

- OS: Windows 10
- Browser: Chrome Version 87.0.4280.14
- Dark Reader Version: 4.9.26

## Additional context
h

**Comment by Gusted** [comment]
dup #835
