### ISSUE TITLE
Inverts duckduck go logo on firefox

### ISSUE THREAD

**Issue by Fycbicbeth** [darkreader/darkreader#485]
When visiting duckduck go the logo on the page has its colours inverted. Does not happen on chrome.

**Comment by alexanderby** [comment]
Currently I see it is not inverted, maybe it was fixed by tuning the image analysis thresholds.
<img width="897" alt="screen shot 2018-05-30 at 15 40 51" src="https://user-images.githubusercontent.com/9638588/40720591-f500b3de-641f-11e8-9db1-8c765874467a.png">
