### ISSUE TITLE
[BUG] It is not possible to change the "toggle current website" hotkey

### ISSUE THREAD

**Issue by realnc** [darkreader/darkreader#4858]
# Bug Report

## Describe the bug

I recently had to re-install my OS (Gentoo Linux). After I installed Firefox (84.0.2), it automatically re-installed all my extensions. However, unlike in my previous installation, Dark Reader does not allow me to set a hotkey to toggle the current site on and off.

The help site (https://darkreader.org/help/en/) is of no help, since the screenshot shown there does not actually match what I'm seeing here. There is no "Toggle current site Alt+Shift+A" text that I can click on to set my own hotkey. There is nothing in the Dark Reader settings either.

## Steps to reproduce

In Firefox, click the dark reader icon and try to change the toggle current site hotkey. There is no way to do that.

## Expected behavior
I should be able to change the hotkey.

## Actual behavior
There is no way to change the hotkey.

## Screenshots
![image](https://user-images.githubusercontent.com/1665903/105611860-9b90e380-5dc0-11eb-9ff8-2b91f192d430.png)

## System Information

- OS:  Gentoo Linux AMD64
- Browser:  Firefox 84.0.2 (64-bit)
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Hi @realnc!

You are in the newer UI of Dark Reader, which hasn't yet been updated to get hotkey support as it's still in preview/beta. You can switch back temporarily to the old UI.

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview old design.
    
Once hotkey set you can repeat the steps to go back.
 
Regards,
Gusted

**Comment by realnc** [comment]
Ah, thanks! Got it working now.
