### ISSUE TITLE
[BUG] Dark Mode only works as it should if I enable,disable and then enable it again on some websites

### ISSUE THREAD

**Issue by Toadfield** [darkreader/darkreader#4859]
# Bug Report

## Describe the bug
If I just go to a site and have the dark mode enabled,it doesn't look right sometimes,but it looks right after disabling and enabling it again.

## Steps to reproduce

  An example of this is:
  1.Go on a site
  2.Look if the site looks wrong
  3.disable darkreader
  4.Enable it again

## Expected behavior
That it looks right by default without the need to disable and enable it again.

## Actual behavior
That I have to disable and enable darkreader.

## Screenshots
How it looks by default:
![image](https://user-images.githubusercontent.com/68649672/105614213-4bb61a80-5dc8-11eb-9c5a-2af929474ff4.png)
How it looks if I disable and enable dark reader:
![image](https://user-images.githubusercontent.com/68649672/105614240-7ef8a980-5dc8-11eb-9519-0b700d40c8f7.png)

## System Information

- OS:Manjaro Kde
- Browser:Firefox 84
- Dark Reader Version:4.9.27

**Comment by Gusted** [comment]
> 1.Go on a site
> 2.Look if the site looks wrong

This is vague. It seems you are on youtube? with some extension adding something?

**Comment by Toadfield** [comment]
@Gusted 

> It seems you are on youtube? with some extension adding something?

Yes,exactly

**Comment by Gusted** [comment]
Hi @Toadfield!

Could you please specific which extension?

Regards,
Gusted

**Comment by Toadfield** [comment]
[VidIQ](https://addons.mozilla.org/en-US/firefox/addon/vidiq-vision-youtube/) is the extension I'm using.

**Comment by Gusted** [comment]
Hi!

When I wanted to install it I saw in the pop-up it also wanted access to the clipboard, which has concerned me a bit and looking at their Privacy Policy it basic says "We request everything we want and we use it for [Insert standard sales talk] and we may disclose it with Google, Facebook Advertising, Twitter and Intercom." Which are red alarm for me and + it has "provided data by you" section which seems to correspond with the info you must login with, which *knowing this kind of extension* is a must to even use this extension.

Due to this alarming reasons I cannot install this add-on and see why it's broken. I will leave the issue open for anyone to investigate and provide with an fix.

Regards,
Gusted

**Comment by Toadfield** [comment]
When I installed it,I didn't got that popup.
For the login,you don't have to login with your youtube account or something,but you have to make a account for that extension.
But I didn't road the privacy policy and cause of that what you said,I will uninstall it and look for a better statistic shower that doesn't spy,and I also will look into privacy policy next time.

**Comment by zedrood** [comment]
I use two addons together, vidiq is great addons for helping for upload videos in youtube , it's make hard without this addons.
any help for solve this problems ??  @Gusted 
![image](https://user-images.githubusercontent.com/58371257/120075978-c5348100-c0b8-11eb-90ee-d7a2dcdd0c56.png)
![image](https://user-images.githubusercontent.com/58371257/120075991-d087ac80-c0b8-11eb-8234-dbbf1eecfc4c.png)
![image](https://user-images.githubusercontent.com/58371257/120076006-e4331300-c0b8-11eb-829c-633f8039918b.png)
![image](https://user-images.githubusercontent.com/58371257/120076026-f1500200-c0b8-11eb-8674-e91fc7cc3dcc.png)
![image](https://user-images.githubusercontent.com/58371257/120076032-fc0a9700-c0b8-11eb-877b-30c4c4062e2b.png)

**Comment by Gusted** [comment]
> any help for solve this problems ??

Not from me. Styling other extensions is near impossible. As this seems to be content generated from Vidiq itself.

**Comment by zedrood** [comment]
thanks for answering ❤️
