### ISSUE TITLE
汽车之家的视频全黑看不到！The video of autohome is black...

### ISSUE THREAD

**Issue by fsfyx** [darkreader/darkreader#4879]
譬如以下网址的视频：
https://chejiahao.autohome.com.cn/info/7843264#pvareaid=3311331#position=62
全黑看不到。

For example，the URL as blow：
https://chejiahao.autohome.com.cn/info/7843264#pvareaid=3311331#position=62
can't see the video

**Comment by jack9603301** [comment]
Please don't use Chinese

**Comment by jack9603301** [comment]
International community please use English

**Comment by fsfyx** [comment]
Both have Chinese and English👌

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Gusted** [comment]
> Please don't use Chinese

Have a check with our [Code of Conduct](https://github.com/darkreader/darkreader/blob/master/CODE_OF_CONDUCT.md), it's totally allowed.

Thereby
```
<!-- 
  ⚠⚠ Do not delete this issue template! ⚠⚠ 
  Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
-->
```

**Comment by jack9603301** [comment]
@Gusted From the perspective of international norms, it is a good habit to use English in the international community (not all readers can read Chinese, I have formed the habit of using English in the community, even if I need to translate). It's Chinese, so as a friendly, let me remind you.. On this issue, if there is such a problem, you may have to consider how to fix it

**Comment by jack9603301** [comment]
It seems that this problem does exist. The video has been expanded and disappeared

**Comment by jack9603301** [comment]
Repeated references: https://github.com/darkreader/darkreader/issues/4880
