### ISSUE TITLE
[Dynamic] Tetris Wiki overrides settings

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#488]
Each new page on this Tetris wiki overrides the setting.
Once I set/toggle it for the specific page explicitly, does it stay saved.

https://tetris.wiki/

**Comment by alexanderby** [comment]
Are you trying to use "Only for" button for applying the settings for a specific page? Currently it works only for entire domain.

**Comment by ShalokShalom** [comment]
Idk, it works now at all. How to check if thats just if I pressed the toogle before?
I am curious if it works now for all people.

**Comment by LaikaFusion** [comment]
Just checked this. I'm not really finding any unusual behavior here. 

If I change from Dynamic to anything else it changes on every page and doesn't change back. Either with `Only for tetris.wiki` on or off. 

Probably safe to close.

**Comment by Gusted** [comment]
Fixed.
