### ISSUE TITLE
[Feature Request] Too Easy to Reset the Dynamic Theme Editor

### ISSUE THREAD

**Issue by bondsbw** [darkreader/darkreader#4885]
# Feature Request

## Is your feature request related to a problem? Please describe
The `Reset` button in the Dynamic Theme Editor is too easy to click accidentally due to its placement next to `Apply`.  Doing so resets all changes ever made, and there appears to be no way to revert.

## Describe the solution you'd like
Some ideas:

- Make the Reset button harder to access (perhaps inside a menu)
- Add an "Are you sure?" dialog when resetting
- Add a way to view and revert to previous versions

**Comment by Gusted** [comment]
Hi @bondsbw!

I couldn't agree more that's too easy to reset it #4887

Regards,
Gusted
