### ISSUE TITLE
Light mode + Dynamic theme does not work on Youtube

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#489]
With the new 4.4.5 version, the light mode + the dynamic theme on youtube no longer works as expected. It shows a dark background instead of the expected light background.

Much love.

**Comment by alexanderby** [comment]
It didn't work in v4.4.4, did it work before?

**Comment by Aqa-Ib** [comment]
It did.

**Comment by Aqa-Ib** [comment]
I am pretty sure that it worked in 4.4.4 by the way, not 100% but pretty sure. Although, I am 100% sure that it has worked well in this actual week.

**Comment by Aqa-Ib** [comment]
OK, I have learnt how to install past builds of Dark Reader. I am trying every past build possible and it does not work. I don't know man, maybe I have dreamed about it working. I am sorry for the inconvenience. If I make it work I will let you know.

Peace, thank you very much for your work brother.

**Comment by Aqa-Ib** [comment]
OK man, I am not crazy. 
Look at this capture of Youtube that was taken on May 8: https://web.archive.org/web/20180508000015/https://youtube.com/

The problem was caused by some changes made on youtube itself on May 9.

**Comment by Gusted** [comment]
Hi @Aqa-Ib!

Over the past 2 years darkreader has improved a lot and for youtube also Could you take another look at youtube.com and see if this issue still persist?

**Comment by Aqa-Ib** [comment]
Hello Gusted! Sorry for the delay, I could not access my Github account until today.
Dark Reader on its light mode does not work properly on youtube yet. It happens on latest Firefox and Chrome. It behaves the same as if it was on the dark mode, but with some bugs included. For example:

![Screenshot_20201202_191548](https://user-images.githubusercontent.com/16420574/100914373-42e54e80-34d3-11eb-8ce1-7f8b98647495.png)

Look at those unreadable dark fonts. This text bug only happens on Firefox though.
Thank for your attention, Sir.

**Comment by alexanderby** [comment]
Should work now.
