### ISSUE TITLE
[Broken Website] Insert title here apkmirror

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4893]
# Broken Website

## Website

https://www.apkmirror.com/

## How to Reproduce

goto https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/tik-tok-18-4-7-release/

## Expected behavior

text must be visible

## Actual behavior

text is invisible

## Screenshots

![image](https://user-images.githubusercontent.com/14617699/105986036-65e44700-60ad-11eb-9b8e-5dd8c510bf41.png)

## System Information

- OS:  linux
- Browser:  firefox
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Not fix-able site is overriding with inline styles which isn't overrideable. 
![image](https://user-images.githubusercontent.com/25481501/106176149-dadb7d80-618e-11eb-8d2f-d2a1e4337ec8.png)
