### ISSUE TITLE
[Broken Website] Insert title here ixbt

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4896]
# Broken Website
https://www.ixbt.com

## How to Reproduce

goto https://www.ixbt.com/live/flashlight/acebeam-h30---samyy-yarkiy-nalobnyy-fonarik.html

## Expected behavior

text must be visible

## Actual behavior

text is invisible

## Screenshots

![image](https://user-images.githubusercontent.com/14617699/105987357-3cc4b600-60af-11eb-8808-bf292108e5ea.png)

## System Information

- OS:  android
- Browser:  firefxo
- Dark Reader Version:   4.9.27

## Additional context

It works fine on desktop, but not on mobile.

**Comment by Gusted** [comment]
Not reproduce-able. Firefox Nightly.

**Comment by 532910** [comment]
The latest nightly (210130):
![image](https://user-images.githubusercontent.com/14617699/106383601-08673780-63d8-11eb-87aa-c6691416e97d.png)
![image](https://user-images.githubusercontent.com/14617699/106383686-6136d000-63d8-11eb-840b-ed13a9cc42f1.png)

**Comment by Gusted** [comment]
HI @532910!

I'm still unsure how this is being caused, so I'm taking a logical guess that the `body` CSS is not being modified and #4929 should solve that.

Regards,
Gusted
