### ISSUE TITLE
[Broken Website] Insert title here муринские-бани.рф

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4897]
# Broken Website

## Website

муринские-бани.рф

## How to Reproduce

goto https://муринские-бани.рф/

## Expected behavior

menu must be visible

## Actual behavior

menu is invisible

## Screenshots

![image](https://user-images.githubusercontent.com/14617699/105987702-b361b380-60af-11eb-9d2d-d9cc57c03587.png)
![image](https://user-images.githubusercontent.com/14617699/105987757-c7a5b080-60af-11eb-918e-78a478afca68.png)

## System Information

- OS:  linux / android
- Browser:  firefox
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Everything if not all is wrapped into weird imagery. Filter(+) is advised.
