### ISSUE TITLE
[youtube.com] text in the search box is invisible with static engine

### ISSUE THREAD

**Issue by MR-Diamond** [darkreader/darkreader#4898]
# Broken Website

## Website
youtube.com

## How to Reproduce
  - Go to youtube.com
  - Open DarkReader settings and set the engine as Static instead of Dynamic
  - Type inside the youtube's search box: the typed text is invisible.

## Expected behavior
Since all other text is visible, also the typed text inside the search box should be visible

## Actual behavior
the typed text inside the search box is invisible when using Static engine instead of Dynamic

## Screenshots
![Peek 2021-01-27 13-26](https://user-images.githubusercontent.com/32249442/105991581-43016500-60a4-11eb-910d-8c474aa70a3b.gif)

## System Information

- OS: Manjaro Linux 64 bit
- Browser: Chromium 87.0.4280.14
- Dark Reader Version: 4.9.26

**Comment by Gusted** [comment]
Hi @MR-Diamond!

The static mode is an template and is consider "bring your own CSS to the party" and considered to have certain elements like this broken which should be fixed by the user.

Regards,
Gusted
