### ISSUE TITLE
[Broken Website] docs.python.org

### ISSUE THREAD

**Issue by AnthonyWritesBadCode** [darkreader/darkreader#4915]
# Broken Website

## Website

https://docs.python.org

## How to Reproduce

- Load a new window
- Go to docs.python.org
- Most of the page does not work
- Ctrl+R does not fix this, but Ctrl+Shift+R does

## Expected behavior

The page should immediately work in dark mode, without having to be reloaded

## Actual behavior

Most of the page does not immediately work in dark mode

## Screenshots

Upon loading the page:
![image](https://user-images.githubusercontent.com/9437154/106248941-fdfb4100-6211-11eb-8e97-aee6db78bd87.png)
After Ctrl+Shift+R:
![image](https://user-images.githubusercontent.com/9437154/106248979-09e70300-6212-11eb-8ca1-3f29f5979171.png)

## System Information

- OS: Windows 10 Home
- Browser: Chrome 87.0.4280.141
- Dark Reader Version: 4.9.26

## Additional context

NA

**Comment by Gusted** [comment]
#835
