### ISSUE TITLE
[Feature Request] Support Firefox's "Reader View" mode (F9)

### ISSUE THREAD

**Issue by MV10** [darkreader/darkreader#4919]
# Feature Request

## Is your feature request related to a problem? Please describe
Firefox has a "Reader View" mode which attempts to extract the body text from articles to remove distracting videos, advertisements etc. Normally this is displayed in a relatively dark style, but when darkreader is running, it inverts to black text on a white background. Reader View is normally toggled with the F9 key or a button in the address bar.

## Describe the solution you'd like
Assuming darkreader can detect the switch to Reader View, either allow us to disable darkreader in this mode, or correct the style settings which applies to this mode.

## Additional context
n/a

**Comment by Gusted** [comment]
Hi @MV10!

Unfortunately is the Reader view mechanism under an `about:` URL which are protected by Firefox and disallows us to modify it.
![image](https://user-images.githubusercontent.com/25481501/106280504-4e889380-623e-11eb-931b-909b27d2ff32.png)

However, Reader View has an native option(Under type controls) to enable an dark mode as seen in the screenshot.
![image](https://user-images.githubusercontent.com/25481501/106280410-2862f380-623e-11eb-8381-5d844a8c1f07.png)

Regards,
Gusted

**Comment by MV10** [comment]
Nice, totally missed that setting, thank you!
