### ISSUE TITLE
[Broken Website] Insert title here OSM iD

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4927]
# Broken Website

## Website

https://osm.org
https://github.com/openstreetmap/iD

## How to Reproduce

1. Sign in OSM
2. Start editing in iD

## Expected behavior

icons must be visible

## Actual behavior

icons are inisible

## Screenshots

![image](https://user-images.githubusercontent.com/14617699/101289722-4ea47e00-380f-11eb-8c20-bbfc2c7a118e.png)

## System Information

- OS:  linux
- Browser:  firefox
- Dark Reader Version:  4.9.27

## Additional context

a dup of #4406 as it's still not fixed, not reopened and ignored

**Comment by Gusted** [comment]
Hi @532910!

I will have right now a look what went wrong with the fix.

> not reopened and ignored

Recently my spam filter was aggressive and purged ~10 mails of notifications I was able to 'restore' 8 of them but unfortunately missed 2 whereby 1 of them was that message. My apologies for that.

Regards,
Gusted

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/106383975-828bc200-63c0-11eb-87ea-cd8243fe7bb1.png)
LGTM now
