### ISSUE TITLE
update issues templates

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4936]
Please, update issue templates.

Yes, I noticed that templates have been updated recently. But I have some more suggestions:

1. `Insert title here` -> `Replace with title`

2. `[Broken Website]`, `[BUG]`, `[Feature Request]` and `[Performance]` are superfluous, labels are enough.

3. Title could be completely removed, github will prevent issues without title.

4. Comments are clearer with `[//]: #`, and saves two lines in contrast with `<!-- -->`. (https://armdong.github.io/markdown-101/) Compare:
```
<!-- 
  ⚠⚠ Do not delete this issue template! ⚠⚠ 
  Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
-->
```
```
[//]: #   ⚠⚠ Do not delete this issue template! ⚠⚠ 
[//]: #   Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
```

5. `Steps to reproduce the behavior:` is superfluous in the _Steps to reproduce_, and they are an ordered list:
```
## Steps to reproduce
<!-- We need to know how you encountered the bug to properly troubleshoot the issue. -->
<!--
  Steps to reproduce the behavior:
  An example of this is:
  - Go to x site
  - Hover over x button
  - See that when hovering it isn't changing colors
-->
```
`->`
```
## Steps to reproduce
[//]: #   We need to know how you encountered the bug to properly troubleshoot the issue. For example:
[//]: #
[//]: #   1. Go to x site
[//]: #   2. Hover over x button
[//]: #   3. See that when hovering it isn't changing colors
```

6. `Please add a version of the browser you are using.` must be under `## System Information` (and superfluous in my opinion)

**Comment by Gusted** [comment]
>     1. `Insert title here` -> `Replace with title`

Fair point, will change that.



>     2\. `[Broken Website]`, `[BUG]`, `[Feature Request]` and `[Performance]` are superfluous, labels are enough.



>     2\. `[Broken Website]`, `[BUG]`, `[Feature Request]` and `[Performance]` are superfluous, labels are enough.

https://github.com/darkreader/darkreader/pull/4700#issuecomment-761692070

>     3\. Title could be completely removed, github will prevent issues without title.

Rule 0. Never trust users.
Rule 1. Never trust users even if said otherwise.

The little indication of that the issue is about + some (un)meaningful title is better than some (un)meaningful title.



>     3\. 
> 
>     4\. Comments are clearer with `[//]: #`, and saves two lines in contrast with `<!-- -->`. (https://armdong.github.io/markdown-101/) Compare:
> 
> 
> ```
> 
> ```

Good point.

>     1. `Steps to reproduce the behavior:` is superfluous in the _Steps to reproduce_, and they are an ordered list:
> 
> 
> ```
> ## Steps to reproduce
> 
> 
> ```
> 
> `->`

Good point.


I will open up a PR for it.

Regards,
Gusted
