### ISSUE TITLE
[Broken Website] helix.ru

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4943]
# Broken Website

## Website

https://helix.ru/

## How to Reproduce

goto https://helix.ru/

## Expected behavior

logo must be visible
## Actual behavior

logo is invisible
## Screenshots

![image](https://user-images.githubusercontent.com/14617699/106442271-1d9d9e00-648c-11eb-9096-1b9d446c3c96.png)

## System Information

- OS: linux
- Browser: firefox
- Dark Reader Version: 4.9.27

**Comment by AndrewDaGuy** [comment]
Since this breaks in static mode and from what @Gusted said,
> Static has the concept of "Bring your own CSS". It's an template to build your own CSS on it.
> And therefore most likely to break things like these and can be fixed by the user.
> [Comment Link](https://github.com/darkreader/darkreader/issues/4952#issuecomment-772411831)

> If your CSS knowledge isn't that good and a site breaks, it's recommended to switch for that page to Filter(+) or Dynamic.
> [Comment Link](https://github.com/darkreader/darkreader/issues/4952#issuecomment-772426192)

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/commit/25c61f8db5c60c42ebe47762374eb3221d252c15
