### ISSUE TITLE
[Broken Website] FF Crash on https://www.dell.com/de-de/shop/

### ISSUE THREAD

**Issue by 5georgeK** [darkreader/darkreader#4949]
# Broken Website

## Website

https://www.dell.com/de-de/shop/alienware-25-gaming-monitor-aw2521hfl/apd/210-awgv/monitore-und-monitorzubeh%C3%B6r

## How to Reproduce

just open the website and scroll down, FireFox will crash.
No problems with Dark Reader and Chrome.

## Expected behavior

No crash

## Actual behavior

Firefox crashes

## System Information

- OS:  Windows 10 Pro 64bit
- Browser:  FireFox 85.0 64bit
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Hi @5georgeK!

Could you elaborate on the meaning of "crashes", I wasn't able to reproduce and looking at the profiler their is some huge pain for the graphics non-related to dark reader.

![image](https://user-images.githubusercontent.com/25481501/106617401-822d2b80-6566-11eb-9257-343dd6b2e345.png)

Regards,
Gusted

**Comment by Gusted** [comment]
No response 🤷🏽‍♀️
