### ISSUE TITLE
[Dynamic] opensubtitles.org search box disappears with Dynamic theme engine

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#495]
The search box in <https://www.opensubtitles.org> disappears when using the Dynamic theme engine:
![image](https://user-images.githubusercontent.com/10074769/39960882-39acce64-5601-11e8-88e4-ac9bb9399d8b.png)

It shows using the Filter+ theme engine:
![image](https://user-images.githubusercontent.com/10074769/39960888-48eb11a6-5601-11e8-8ba1-77cd2791be70.png)

or with darkreader switched off:
![image](https://user-images.githubusercontent.com/10074769/39960889-518f119a-5601-11e8-9d38-e5954fe07f5a.png)

**Comment by Aqa-Ib** [comment]
This does not happen to me. What version of Dark Reader are you using?

**Comment by marcelpaulo** [comment]
My sincerest apologies, what a poor issue I opened, without necessary information !

I installed DarkReader from the git repo (9f474e8), on **Xubuntu 18.04**. I've just confirmed that 9f474e8  is the latest commit. My Google Chrome version is **66.0.3359.170**.

**Comment by Aqa-Ib** [comment]
It is strange man. Can you try with a clean Chrome profile?

**Comment by marcelpaulo** [comment]
Good idea, @Aqa-Ib, I should have thought of it before ! Well ... Created a clean Chrome profile, didn't even login, no extensions loaded but darkreader:
![image](https://user-images.githubusercontent.com/10074769/40027875-6e97e6ba-57b2-11e8-8022-f88a5332282b.png)

and the search box on www.opensubtitles.org now shows up:
![image](https://user-images.githubusercontent.com/10074769/40027982-e22b1106-57b2-11e8-99e1-4a314cbc8557.png)

So... I'll try adding the extensions one by one to the clean profile and see which one is interfering with darkreader. On my current profile, I disabled some likely candidates, Vimium and Tampermonkey, but it had no effect, the search box was still missing. I hope to have better results with the clean profile.

**Comment by marcelpaulo** [comment]
A reasonable workaround was to keep AdBlock enabled, but disable it on www.opensubtitles.org, which actually I should have done already since that's how the site survives.

**Comment by Aqa-Ib** [comment]
I am happy that you managed to fix it. As a replacement for AdBlock, I recommend you uBlock Origin. That is the one that I use and the one recommended by https://prism-break.org

Regards.

**Comment by marcelpaulo** [comment]
I followed your recommendation: replaced AdBlock with uBlock Origin. Thanks for that ! Another immediate benefit: it doesn't interfere with darkreader on www.opensubtitles.org.
