### ISSUE TITLE
[BUG] table rows with inline background style are ignored.

### ISSUE THREAD

**Issue by Superard** [darkreader/darkreader#4950]
# Bug Report

## Describe the bug

Table rows with background css inline on "tr" elements are ignored.

## Steps to reproduce

Create an html table with "table", "tr" and "td" elements.
Apply background to "tr" element with something like style="background: #ACD".
Then use DarkReader.enable();
It will ignore this color applied in the row, and use the color on the cell, but the cell does not have any defined color.
If the style is applied to the individual cell ("td" element), it works fine.

## Expected behavior

It should work with styles on the rows "tr" as well as it does with cells "td".

## Actual behavior

It does not apply the correct color on table rows when the background style is defined on row "tr" instead of cells "td".

## Screenshots

Not enabled (the result is the same with background on "tr" or " td"):
![image](https://user-images.githubusercontent.com/1715112/106614546-3ff5f100-654a-11eb-8c74-ef3e813d05a1.png)

Enabled (with background style applied on "tr" element:
![image](https://user-images.githubusercontent.com/1715112/106614593-4be1b300-654a-11eb-8c68-a11dac7beeea.png)

Enabled (with background style applied on each "td" element of a "tr":
![image](https://user-images.githubusercontent.com/1715112/106614697-6582fa80-654a-11eb-8b6b-cf10879ac760.png)

## System Information

- OS: Windows 10 20H2 
- Browser: Microsoft Edge (chromium) 88.0.705.56
- Dark Reader Version: 4.9.27 

## Additional context

I've applied it on an internal website, to create dark/light theme.
I've tested it on different pages, with different colors and layouts, the result is always the same.
I've not tested "th" element, but based on my results, i believe the problem is there too.

**Comment by Gusted** [comment]
Hi @Superard!

I've made a simple example case, however using the steps you've provided gave me not the results you're getting. It's modifying fine and doesn't error anything.
[repo.zip](https://github.com/darkreader/darkreader/files/5912099/repo.zip)

Regards,
Gusted

**Comment by Superard** [comment]
Hi, i've found that the problem occours only when using it together with Bootstrap version 5, so it's not a bug, just an incompatibilty with something inside Bootstrap.
Because Bootstrap is still in "alpha", it is not even something that we need to care about in this moment.
Thank you, and sorry for this inconvenience.
