### ISSUE TITLE
[Broken Website] medium.com covers some page space with a sidebar

### ISSUE THREAD

**Issue by MoskovchenkoD** [darkreader/darkreader#4952]
# Broken Website

## Website
https://medium.com/

## How to Reproduce
- Enter any article. For example, [this one](https://medium.com/@tigranbs/why-developers-prefer-dark-coding-themes-a00cbf9d8900).
- Scroll the page down until you see a sidebar that shows the author, number of claps and comments.

![sidebar01](https://user-images.githubusercontent.com/12684111/106667750-ff31c280-65b1-11eb-994b-eed0f92d24a3.png)
- Turn on Dark Reader and see that a some text is covered by an invisible object.

Works for both dark and light themes.

## Expected behavior
Nothing would cover the content within this rectangle (or anywhere else on the page).

![expected](https://user-images.githubusercontent.com/12684111/106667515-b11cbf00-65b1-11eb-9979-30fc60d5f47a.png)

## Actual behavior
Some content is covered and it lasts until I scroll up to the headline or reach the end of the article. If I scroll down to further articles, this rectangle disappears and the content shows like normal.

![actual](https://user-images.githubusercontent.com/12684111/106668173-a31b6e00-65b2-11eb-92fa-44fb1a182a5d.png)

## Screenshots
I think something is wrong with that element. I'm not good at front-end stuff =(

![sidebar](https://user-images.githubusercontent.com/12684111/106668008-63548680-65b2-11eb-922e-eb8674b6dbef.png)

## System Information
- OS: Windows 7 x64 SP1
- Browser: Chrome 88.0.4324.146 (Official Build) (64-bit)
- Dark Reader Version: 4.9.26

## Additional context
Adblock doesn't influence the behavior. This rectangle remains even with Adblock turned off.

**Comment by AndrewDaGuy** [comment]
On `LibreWolf 85.0 (64-bit)` it seems to work correctly *LibreWolf is a fork of Firefox
![Screenshot 2021-02-03 at 1 43 06 AM](https://user-images.githubusercontent.com/66189242/106728421-552f5600-6604-11eb-8685-ff7bda76d2e6.png)

**Comment by Gusted** [comment]
Hi @MoskovchenkoD!

Static has the concept of "Bring your own CSS". It's an template to build your own CSS on it.
And therefore most likely to break things like these and can be fixed by the user.

Regards,
Gusted

**Comment by MoskovchenkoD** [comment]
May I ask for some extended explanation? What is "static" in this context? I don't bring anything to the page and my CSS knowledge is at Elementary level.

**Comment by Gusted** [comment]
Dark reader has 4 modes.
"Dynamic", "Filter", "Filter+", "Static".
Dynamic: Ready-to-go solution, it analyzes the pages and modifies it accordingly.
Filter(+): Simple solution which invert white parts of the page but can be heavy on GPU.
Static: A template to create CSS for pages, it doesn't do anything other than injecting a standard template and user's CSS which he/she/they provided. Static in this context meant, no mater what it will use _this_ CSS. 

If your CSS knowledge isn't that good and a site breaks, it's recommended to switch for that page to Filter(+) or Dynamic.

Regards,
Gusted
