### ISSUE TITLE
[Broken Website] Quora 

### ISSUE THREAD

**Issue by brazenvoid** [darkreader/darkreader#4971]
# Quora breaks differently in different areas and works in others (account required)

## Website
https://www.quora.com/
https://www.quora.com/notifications
https://www.quora.com/Have-you-ever-thought-your-child-was-faking-being-sick-but-later-discovered-it-was-something-serious

## How to Reproduce
Just go to the home, notifications or any question page. Most of the times, colors will not be applied correctly, sometimes it does work. 

## Expected behavior
Colors are applied correctly.

## Actual behavior
Parts of the pages has white background.

## Screenshots

![Screenshot_2021-02-04 Quora](https://user-images.githubusercontent.com/8722533/106927034-8d818200-6733-11eb-9630-f72410006317.png)

![Screenshot_2021-02-04 Have you ever thought your child was faking being sick, but later discovered it was something serious](https://user-images.githubusercontent.com/8722533/106927039-8fe3dc00-6733-11eb-8f9d-8e5f66c9a33f.png)

![Screenshot_2021-02-04 Notifications - Quora](https://user-images.githubusercontent.com/8722533/106927041-907c7280-6733-11eb-9cbe-510fa9222c54.png)

## System Information
- OS: Windows 10 20H2
- Browser: Firefox v85.0
- Dark Reader Version: v4.9.27

**Comment by Gusted** [comment]
Hi @brazenvoid!

Do you have any special settings? the 4.9.27 should have a fallback fix for Quora to encounter this.

Regards,
Gusted

**Comment by brazenvoid** [comment]
Here are my settings, don't know what you refer as special settings:
[Dark-Reader-Settings.zip](https://github.com/darkreader/darkreader/files/5927468/Dark-Reader-Settings.zip)

**Comment by Gusted** [comment]
Okay, it might help to go to Settings -> Devtools -> Reset. It should fetch the latest fix(confirm this by searching `quora.com` and see this.
![image](https://user-images.githubusercontent.com/25481501/106932733-fd7e1100-670f-11eb-879b-f37d196cb561.png)

**Comment by brazenvoid** [comment]
Thanks! It is slower than before but it works. 

Any news on v5 release?

**Comment by Gusted** [comment]
> Any news on v5 release?

Unfortunately not, due to conditions(Intentional vague).

> Thanks! It is slower than before but it works.

Will look into it!
