### ISSUE TITLE
[Dynamic] forum.kde.org white background

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#498]
Hello! The following web site has a white background with the dynamic mode:
https://forum.kde.org

I wish to learn how to fix this type of issues to help you man.
Thank you very much, Dark Reader is the greatest!

**Comment by alexanderby** [comment]
Currently it shows me a gray background pattern. The solution will be to allow using image URLs under `INVERT` in the Dev Tools config. I can also improve the image analysis, but it can become less performant.

**Comment by Aqa-Ib** [comment]
Actually you can only see it kind of white using the light mode with the following settings: brightness -20, contrast -50, sepia +100, greyscale +100.

In dark mode, depending on your filter configuration you can either be able to read the fonts or not.

Thank you man.

**Comment by Gusted** [comment]
Hi their!

#2554 Will be included in the next release! Thank you for reporting this issue

Regards,
Gusted
