### ISSUE TITLE
[Broken Website] Google Drive PDFs and Videos have weird icons

### ISSUE THREAD

**Issue by Elaborendum** [darkreader/darkreader#4980]
# Broken Website

## Website
https://drive.google.com

## How to Reproduce
  - Go to Google Drive
  - Open a PDF or a Video in a separate tab
  - See weird icons

## Expected behavior
Icons appear normally, likely in a light color.

## Actual behavior
Icons don't appear correctly, some are even invisible.

## Screenshots

![image](https://user-images.githubusercontent.com/71190696/107079695-35dc2880-67be-11eb-96ab-75d35816ba11.png)
![image](https://user-images.githubusercontent.com/71190696/107079718-3ffe2700-67be-11eb-8496-fdf919a52841.png)

## System Information

- OS: Windows 10
- Browser: Firefox 85
- Dark Reader Version: 4.9.27

## Additional context
I have enabled 'Synchronize Sites fixes', but still no result. I've disabled all about:config tweaks I could remember to have modified.

**Comment by Gusted** [comment]
> I have enabled 'Synchronize Sites fixes', but still no result.

Please go to the devtools and click on Reset.

**Comment by Elaborendum** [comment]
Makes sense, thank you.
