### ISSUE TITLE
[Broken addon] Doesn't work with Thunderbird Conversations' message pane

### ISSUE THREAD

**Issue by ildar** [darkreader/darkreader#4983]
# Broken addon

## Addon
https://addons.thunderbird.net/ru/thunderbird/addon/gmail-conversation-view/

## How to Reproduce
Install the addon and open a message

## Expected behavior
should be dark

## Actual behavior
it's white

## System Information

- OS: Linux
- TB: 78
- Dark Reader Version: latest

**Comment by Gusted** [comment]
Hi @ildar!

The extension "hijacks" the conversation panel to another source which is internally protected by Thunderbird and thus won't allow any modifications by add-ons.

Regards,
Gusted

**Comment by ildar** [comment]
it's a pity.
thanks
