### ISSUE TITLE
[Broken Website] Google Trends

### ISSUE THREAD

**Issue by ajs256** [darkreader/darkreader#4984]
# Broken Website

## Website
https://trends.google.com/trends/?geo=US

## Expected behavior
I expected the colors of the maps to match the labels.
## Actual behavior
The maps are black and white.

## Screenshots

![image](https://user-images.githubusercontent.com/67526318/107136435-f265e500-68b7-11eb-8197-55ac332462c0.png)

## System Information

- OS: macOS 11.1
- Browser: Chrome `88.0.4324.150 (Official Build) (x86_64)`
- Dark Reader Version: 4.9.27

## Additional context
N/A

**Comment by Gusted** [comment]
Hi @ajs256!

Does this behavior stay the same after refresh?
This behavior didn't occur to me:
![image](https://user-images.githubusercontent.com/25481501/107153727-ec7b0d00-6966-11eb-8d3d-b9f71979878a.png)

Regards,
Gusted

**Comment by ajs256** [comment]
Oh, the refresh fixed it! Thanks @Gusted
