### ISSUE TITLE
Excel Office 365

### ISSUE THREAD

**Issue by MrObvious** [darkreader/darkreader#4993]
# Broken Website

## Website
Do not have direct URL as it uses company URL. Do not wish to dox myself. But just standard Office 365 Excel.

## Expected behavior

Dark background with light text.

## Actual behavior

Cells are white background. This also seems to affect Powerpoint.

## Screenshots

![image](https://user-images.githubusercontent.com/5652131/107391534-6540ad00-6abe-11eb-8439-a7ac849d3ea5.png)

## System Information

- OS: Win 10 20H2
- Browser: FF 85.0.1
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Hi @MrObvious!

Could you share an URL with any PII/company name replace with an 'description' of it. So I can make sure the URL would be correct.

Regards,
Gusted

**Comment by MrObvious** [comment]
https://(company)-my.sharepoint.com/:x:/r/personal/username_company_com/_layouts/15/Doc.aspx?sourcedoc=%7B5ef40333-2d5f-4a40-9bfd-043d79eb15ed%7D&action=editnew&wdPreviousSession=70d47831-fc1e-40c0-bff4-cbf0fe77c05b&wdNewAndOpenCt=1612974092010&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=c05d2ce2-0322-4525-bccd-2facf864a039

This is my corporate O365 account.

**Comment by Fanatiikon** [comment]
Issue is occuring again af of patch 4.9.77. Exactly the same, company sharepoint excel cells are white again.
