### ISSUE TITLE
[Broken Website] pushbullet.com

### ISSUE THREAD

**Issue by amine250** [darkreader/darkreader#5009]
# Broken Website

## Website
https://www.pushbullet.com/

## How to Reproduce

Have darkreader enabled for all websites.
Go to https://www.pushbullet.com/

## Expected behavior

Website should load normally.

## Actual behavior

Page stays blank.

## System Information

- OS: MacOS
- Browser: Firefox 85.0.1
- Dark Reader Version: 4.9.27

## Additional context

Reactivating DarkReader after the website has loaded works fine.
JS Console logs the message:
```
error message:CSSStyleSheet.insertRule: Not allowed to access cross-origin stylesheet stack:proxyInsertRule@https://www.pushbullet.com/:31:60
onecup.css@https://www.pushbullet.com/js/pushbullet.js:7989:33
@https://www.pushbullet.com/js/pushbullet.js:11890:8
onecup.css@https://www.pushbullet.com/js/pushbullet.js:7982:5
@https://www.pushbullet.com/js/pushbullet.js:11889:6
@https://www.pushbullet.com/js/pushbullet.js:12385:4
 type:unhandled
```

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/1170#issuecomment-735622342 some explanation why. Will put up an PR to fix this.

**Comment by Gusted** [comment]
#5011 Easy Fix luckily :P
