### ISSUE TITLE
[Broken Website] Bing.com

### ISSUE THREAD

**Issue by KibSquib48** [darkreader/darkreader#5013]
# Broken Website

## Website
bing.com

## How to Reproduce
- go to bing.com
- search

## Expected behavior
The website will stay dark

## Actual behavior
After a few seconds, some elements go white again.

## Screenshots
![image](https://user-images.githubusercontent.com/33189136/107584976-5eec2700-6bcb-11eb-95a7-5778b8b66630.png)

## System Information
- OS: Windows 10
- Browser: Microsoft Edge Dev 90.0.789.1
- Dark Reader Version: 4.9.27

**Comment by joshhuggins** [comment]
Yeah, this has been like this for months or longer unfortunately. It used to work great with Bing.

**Comment by Gusted** [comment]
> Yeah, this has been like this for months or longer unfortunately. It used to work great with Bing.

This add little to none contribution nor any information about this issue. + that you mentioned you had this for months and didn't consider opening a issue is little bit frustrating me

Hi @KibSquib48!

Is it 100% of the time reproduce able?
This behavior doesn't occur to me.

Regards,
Gusted

**Comment by KibSquib48** [comment]
> Is it 100% of the time reproduce able?

happens every single time

**Comment by Gusted** [comment]
> > Is it 100% of the time reproduce able?
> 
> happens every single time

Hmm, could you check if it happens with another Chromium browser? It could be a Edge specific problem.

**Comment by KibSquib48** [comment]
> > > Is it 100% of the time reproduce able?
> > 
> > 
> > happens every single time
> 
> Hmm, could you check if it happens with another Chromium browser? It could be a Edge specific problem.

Same thing happens in ungoogled-chromium, so I think it's an issue with chromium itself. I'll try and see if it's the same with Firefox, too

**Comment by KibSquib48** [comment]
> I'll try and see if it's the same with Firefox, too

yeah same thing with firefox, seems like a problem with the website or the extension itself

**Comment by Gusted** [comment]
> yeah same thing with firefox, seems like a problem with the website or the extension itself

I'm not quite sure how it's being caused, I've searched around for around 10 minutes on Firefox/Chromium, however it didn't seem to occur me once. Do you have any other extension installed?

**Comment by KibSquib48** [comment]
I have stylus, that's the only other one that changes css but when I tried it with ungoogled-chromium it was the only extension installed and activated. if it has anything to do with my hardware, my browser is using Intel UHD Graphics and I have the new design enabled with some custom settings. Changing it back to default settings doesn't fix it though so I don't think that's the problem.

**Comment by Gusted** [comment]
Hmm, Does it show any error in Console(Ctrl + shift + i -> Console tab) when it occur?

**Comment by KibSquib48** [comment]
![image](https://user-images.githubusercontent.com/33189136/107991749-41410800-6fa5-11eb-9cdd-7d43784125ba.png)
yeah

**Comment by Gusted** [comment]
> ![image](https://user-images.githubusercontent.com/33189136/107991749-41410800-6fa5-11eb-9cdd-7d43784125ba.png)
> yeah

Hmm, that Error is being occured in Microsoft's script. Are their any other errors?

**Comment by KibSquib48** [comment]
No other errors, just that one. It did stop showing up for me though so it probably wasn't at all related to dark reader.

**Comment by Doug-Murphy** [comment]
I have the same issue on Edge when using Bing. After a search is finished, it shows as expected. But a few seconds letter, some of the text reverts back to black.

Below screenshot is showing the issue:
![image](https://user-images.githubusercontent.com/1383347/111331044-e7386e80-8646-11eb-8c31-47be78f7787c.png)

If I toggle Dark Reader off and then back on, it fixes it and remains fixed. It does not revert back to black text after a few seconds.
![image](https://user-images.githubusercontent.com/1383347/111331079-f0c1d680-8646-11eb-907d-4a1be31f7309.png)

**Comment by StormyIceLeopard** [comment]
> I have the same issue on Edge when using Bing. After a search is finished, it shows as expected. But a few seconds, some of the text reverts back to black.
> 
> Below screenshot is showing the issue:
> ![image](https://user-images.githubusercontent.com/1383347/111331044-e7386e80-8646-11eb-8c31-47be78f7787c.png)
> 
> If I toggle Dark Reader off and then back on, it fixes it and remains fixed until doing another search.
> ![image](https://user-images.githubusercontent.com/1383347/111331079-f0c1d680-8646-11eb-907d-4a1be31f7309.png)

I experience this on Google Chrome.

**Comment by KibSquib48** [comment]
![image](https://user-images.githubusercontent.com/33189136/113514106-c3c45d80-953a-11eb-81a4-1a84e37edb8c.png)
seems like there's a new issue with Bing, the search bar text is black on black, aka barely readable
