### ISSUE TITLE
[Broken Website] relay.firefox.com

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#5019]
# Broken Website
Firefox Relay

## Website

relay.firefox.com

## How to Reproduce

1. Go to relay.firefox.com and login to your firefox account.

## Expected behavior

The website background should be dark
## Actual behavior

It's still white, and on changing it manually via extension, it breaks the website design, and sometimes goes back to white on a refresh anyway.
## System Information
Windows
- Browser:  Firefox Beta 86.0b8
- Dark Reader Version:  4.9.27

## Additional context

This used to work before, something changed either with the extension or the website stylesheets.

**Comment by Gusted** [comment]
Hi @jenabaivab!

It looks for me like 
![image](https://user-images.githubusercontent.com/25481501/107610030-86c5a400-6c38-11eb-9ceb-7b3056b0a38b.png)

Do I need to be on a specific site?

Regards,
Gusted

**Comment by jenabaivab** [comment]
**Using on edge -**

![image](https://user-images.githubusercontent.com/60446763/107610762-601f6180-6c68-11eb-995f-cc99b2695ddd.png)


**Using on firefox beta -**

![image](https://user-images.githubusercontent.com/60446763/107610797-7cbb9980-6c68-11eb-953d-ecc137ed4939.png)


You can see the difference in the top bar color, and the 'forwarding' toggle beside each alias.
Apart from that, the copy symbol beside each alias is also being hidden, irrespective of browser (not the important part here though).

**Comment by Gusted** [comment]
> You can see the difference in the top bar color, and the 'forwarding' toggle beside each alias.
Apart from that, the copy symbol beside each alias is also being hidden, irrespective of browser (not the important part here though).

Yep that's definitely not right. Does it show any errors in console? (ctrl + shift + i) -> Console tab.

**Comment by jenabaivab** [comment]
Now it's a 50-50, even with extension being enabled.

![image](https://user-images.githubusercontent.com/60446763/107745635-9e855100-6d3a-11eb-8b33-bae61faf4163.png)


Regarding the error, here it is, 
![image](https://user-images.githubusercontent.com/60446763/107745714-b65cd500-6d3a-11eb-9fb8-4e332f124149.png)

**Comment by Gusted** [comment]
> Regarding the error, here it is,

Aha. Could you post the full `index.js:` with the line so I know where the error relies.

**Comment by jenabaivab** [comment]
@Gusted Where to find it? This is all I see

![image](https://user-images.githubusercontent.com/60446763/107746246-7f3af380-6d3b-11eb-9a21-4bc2c0d16ada.png)

**Comment by Gusted** [comment]
> @Gusted Where to find it? This is all I see

Oh I meant inside the console. You posted the screenshot on the left side 
![image](https://user-images.githubusercontent.com/25481501/107746352-995ddd00-6d0d-11eb-91ab-5e489f31ed94.png) you can see `index.js:[...]` I'd like to know what those numbers are.

**Comment by jenabaivab** [comment]
@Gusted 
http://notepad.pw/index123
You can find the index.js file here.

Also, saw 2 extra errors this time.

![image](https://user-images.githubusercontent.com/60446763/107746897-9a5a3300-6d3c-11eb-9c69-94fa979ddc49.png)

**Comment by Gusted** [comment]
So just leaving this comment later for me.
First error occured
https://github.com/darkreader/darkreader/blob/master/src/inject/utils/dom.ts#L348-L350

And the second one is surprisingly
https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/style-manager.ts#L127-L129

**Comment by Gusted** [comment]
Hi @jenabaivab!

I've opened an PR(#5037) to resolve this issue alongside an file to potentially test this PR out. https://github.com/darkreader/darkreader/pull/5037#issuecomment-778628207

Regards,
Gusted

**Comment by jenabaivab** [comment]
@Gusted Thank you!
Will inform when I see it's fixed.
