### ISSUE TITLE
[Request]automatic Dark Reader/ adjustable time period

### ISSUE THREAD

**Issue by zartakuz** [darkreader/darkreader#502]
Hello, is it possible to add an Automatic Dark Reader according to the users local time or an even better option is to add a start and end time period adjusted by the user.

**Comment by Aqa-Ib** [comment]
This one is duplicate of #10.

**Comment by zartakuz** [comment]
sorry, didn't saw it, gonna delete it

**Comment by Aqa-Ib** [comment]
Thank you though.
