### ISSUE TITLE
[Broken Website] mail.qq.com

### ISSUE THREAD

**Issue by shenzhiming88** [darkreader/darkreader#5026]
# Broken Website

## Website

mail.qq.com
## How to Reproduce

- Open this site
- Login your account
## Expected behavior

The left and bottom should be black.
## Actual behavior

They're not black.
## Screenshots

![image](https://user-images.githubusercontent.com/66902050/107775106-d7451a80-6d7a-11eb-80fb-d75e413ec930.png)

## System Information

- OS: Windows
- Browser: Microsoft Edge 88.0.705.63
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Hi @shenzhiming88!

Due to the process of signing up and certain PII I need to give I can't signup for this service and checkout what's the problem. I will leave this issue open for anyone to take a look at it.

Regards,

Gusted

**Comment by shenzhiming88** [comment]
@Gusted 
Please forgive me, I don't know much about this, so could you please help me?
![image](https://user-images.githubusercontent.com/66902050/127000558-95185e78-fe0f-47e7-a9f0-37ae3ed8575f.png)

**Comment by Gusted** [comment]
No worries, but it seems it might be able to fixed with a fix like:
```
mail.qq.com

CSS
body {
    background-color: var(--darkreader-neutral-background) !important;
}

================================
```

**Comment by shenzhiming88** [comment]
> No worries, but it seems it might be able to fixed with a fix like:
> 
> ```
> mail.qq.com
> 
> CSS
> body {
>     background-color: var(--darkreader-neutral-background) !important;
> }
> 
> ================================
> ```

Hello!
This does not look fixed and breaks the page
![image](https://user-images.githubusercontent.com/66902050/127001539-52a9c307-56bf-4758-a27d-5f1cae99f2b2.png)

**Comment by Gusted** [comment]
That's weird, could you scroll up a bit in the "dev tools" list.  In particular until you find an `<iframe` element.

**Comment by arche-dev** [comment]
What if we change `#leftPanel`?

**Comment by arche-dev** [comment]
> That's weird, could you scroll up a bit in the "dev tools" list. In particular until you find an `<iframe` element.

There's an `iframe` on the bottom
![image](https://user-images.githubusercontent.com/66189242/127001958-2f5aa5fb-ddd7-4f8d-8b4f-c4b5518cfb23.png)

**Comment by Gusted** [comment]
Hmm, that seems like I was looking for @arche-dev - thanks. 

So that means whatever it is all these elements have their own "frames" but for some weird reason they aren't getting modified by dark reader.

**Comment by arche-dev** [comment]
> Hmm, that seems like I was looking for @arche-dev - thanks.

haha zoom into picture go brrrrrr

**Comment by shenzhiming88** [comment]
Hello!
Is this okay?
![Uploading image.png…]()

**Comment by Gusted** [comment]
> What if we change `#leftPanel`?

Let's try this approach,

```
qq.com

CSS
#leftPanel {
    background-color: var(--darkreader-neutral-background) !important;
}

================================
```

**Comment by shenzhiming88** [comment]
Hello!
This looks strange ...... and I just found out that there are some other places where there are some problems. Thank you for your efforts!
![image](https://user-images.githubusercontent.com/66902050/127003262-86ec43e0-d7e2-4941-8edd-091f2cd92487.png)

**Comment by shenzhiming88** [comment]
@Gusted Hello!
Can I contact you by email? So that I can send you the account number and password.

**Comment by shenzhiming88** [comment]
@Gusted I think it would be better to delete these codes
```
.settingSub a {
    color: ${#4d5d2c} !important;
}
```
![image](https://user-images.githubusercontent.com/66902050/127151571-526d260d-310c-4594-9b57-54b95be4ef7a.png)
Thank you

**Comment by shenzhiming88** [comment]
@Gusted Hello!
Here is another small question
![image](https://user-images.githubusercontent.com/66902050/127157504-5bc010e2-5d78-48cb-8fd8-9d453fc68611.png)

![image](https://user-images.githubusercontent.com/66902050/127157613-5b499f5f-f0a0-432a-997a-c34950dca763.png)

And I submitted a Pull Request for another issue https://github.com/darkreader/darkreader/pull/6363
