### ISSUE TITLE
[Broken Website] centercode.com

### ISSUE THREAD

**Issue by MaleNurse** [darkreader/darkreader#5027]
# Broken Website

## Website

*.centercode.com

## How to Reproduce

In a discussion or issue report, start a new reply.

## Expected behavior

Text editor color is white/distinct from dynamically changed background

## Actual behavior

Text color remains black

## Screenshots

https://user-images.githubusercontent.com/12175293/107791661-1044a700-6d09-11eb-85b7-ccd476456e5a.mp4

## System Information

- OS: `Windows 10 Pro                2004                       10.0.21301.1000`

- Browser: `Chrome 88.0.4324.150 (Official Build) (64-bit)`
- Dark Reader Version: 4.9.28 (Commit 96fbb1c77cd779a993d34e080a0c5c43628bb023)

## Additional context

Disabling and reenabling darkreader corrects the issue. Relevant CSS:

```
.cc-editor-cont {
    font-size: 15px;
    font-family: Lato, 'Helvetica Neue', Sans-Serif;
    line-height: 1.6;
}
```

**Comment by Gusted** [comment]
Hi @MaleNurse!

Hmm, that relevant CSS shouldn't interfere with it. Because it's behind several walls of logins and applications I cannot make a fix for this. However could you possibly get an CSS Selector that match with the text? 

Regards,
Gusted

**Comment by MaleNurse** [comment]
Hey @Gusted 
Yeah, figured this would be a toughy, was hoping you might be involved in a project that utilized that platform but it was a longshot, so I wouldn't be offended at all if this were closed w/o resolution. 

Anyway first off, sorry I didn't include this in the original post (let's blame it on homework burnout). To clarify a little bit of context, if I add `color: ${black} !important;` to the dev tools, it changes the font color for that session, but as soon as I reload or go to another issue: poof it's back to black.  I've searched though the inspector for all of the tags shown in the image below, added them to dev tools, but still no dice. It's like the CKEditor plugin styles aren't loaded until after clicking "Reply" or clicking in the entry box, which I'm guessing darkreader doesn't try to change since the page itself is already loaded. Also included below is the developer console after selecting the element. 

Thanks for taking a look, and for all your work on this project.

![Screenshot (2)](https://user-images.githubusercontent.com/12175293/107856432-f8d6ee00-6ddc-11eb-91a4-8de5cac37726.png)
![Screenshot 2021-02-13 092329](https://user-images.githubusercontent.com/12175293/107856551-b7930e00-6ddd-11eb-83a2-23a40db7a13f.png)

**Comment by Gusted** [comment]
> Anyway first off, sorry I didn't include this in the original post (let's blame it on homework burnout).

Don't worry.


Seeing from the pretty useful, the IFrame seems to be loaded from an `unkown` which I assume is an `Blob:` due to https://bugs.chromium.org/p/chromium/issues/detail?id=55084#c47 and https://bugzilla.mozilla.org/show_bug.cgi?id=1475831#c16 and thus cannot be styled unfortunately. 

Regards,
Gusted

**Comment by MaleNurse** [comment]
Hey @Gusted 
You are correct, "$preferred_formal_pronoun!" Watching the sources in the inspector as I click into that field, surely enough a blob appears. Stupid blobs. 

Thanks for looking into this, I'll go ahead a close it since it turns out to not be darkreader's fault.
