### ISSUE TITLE
[Broken Website] When using Zenhub/Github, styles don't change 

### ISSUE THREAD

**Issue by StephenBitmovin** [darkreader/darkreader#5028]
# Broken Website

## Website
Zenhub extension on Github

## How to Reproduce
Download Zenhub and use on Github

## Expected behavior
Dark mode should appear

## Actual behavior
Mishmash of darkmode and not

## Screenshots
<img width="1787" alt="Screen Shot 2021-02-12 at 1 05 11 PM" src="https://user-images.githubusercontent.com/63260675/107817146-f91aaf00-6d32-11eb-97de-8dca98d3ad0b.png">

## System Information
Chrome latest

- OS:  Mac
- Browser: Chrome
- Dark Reader Version: Latest

## Additional context
N/a

**Comment by Gusted** [comment]
Hi @StephenBitmovin!

This is expected behavior. Zenhub's extension loads their CSS/Styles trough an native way, which unfortunately cannot be detected programmatically nor be overwritten. 

Regards,
Gusted
