### ISSUE TITLE
[Broken Website] https://docs.python.org/

### ISSUE THREAD

**Issue by emerconghaile** [darkreader/darkreader#5031]
# Broken Website

## Website
https://docs.python.org/

## How to Reproduce
 - The site loads broken for me (\<div class="body" role="main"\>)
 - Turn off, the back on, Dark Reader (this fixes the issue)

## Expected behavior
Expected entire site to be dark mode

## Actual behavior
\<div class="body" role="main"\> does not load in dark mode

## Screenshots
https://imgur.com/AwClKyP.png

## System Information

- OS: Manjaro Linux
- Browser: Brave Version 1.19.92 Chromium: 88.0.4324.152 (Official Build)
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
#835
