### ISSUE TITLE
[BUG] The Change Fonts function will broke some icons/logos

### ISSUE THREAD

**Issue by KimiNoNaWaGithub** [darkreader/darkreader#5034]
# Bug Report

## Describe the bug

Like the title, some icons/logos will be changed to text format when enable Change Fonts

## Steps to reproduce

  - Go to a Google Meet online meeting (not only GG Meet, some other pages has this issue)
  - Enable Dark Reder and turn on Change Fonts function
  - Some icons (not all) was broken
  - Turn off Change Fonts and icons/logos are  #back

## Expected behavior

The page will be darkened, so it will suit my eyes.

## Actual behavior

It works, but not the icons: the arow up button now became keyboard_arrow_up, the add button beacme person_add, etc.. 

## Screenshots

![image](https://user-images.githubusercontent.com/62417238/107843176-727dd480-6dfb-11eb-8062-45d7404fbf84.png)
![image](https://user-images.githubusercontent.com/62417238/107843211-c1c40500-6dfb-11eb-84a6-3203b8440db6.png)
The difference between turn on and off Change Fonts function

## System Information

- OS: Windows 10 Pro, 20H2, stable channel
- Browser: 88.0.4324.150 (64 bit)
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/736#issuecomment-434982206
