### ISSUE TITLE
[Broken Website] https://vercel.com/new

### ISSUE THREAD

**Issue by ZeroTex** [darkreader/darkreader#5039]
# Broken Website

## Website
https://vercel.com/new (Specifically the /new slug

## How to Reproduce

Go to this link while logged in and you will see a large white background.

## Expected behavior

A more optimized experience with the colors, maybe not such a dark shade of black on the elements in the center, nav and footer.

## Actual behavior

Large white background, difficult to look at elements.

## Screenshots

https://imgur.com/a/qOHf6c5

## System Information

- OS: Linux
- Browser: Chrome: Version 88.0.4324.150 (Official Build) (64-bit)
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Most improvements will be made out of #4291, but now #5040 should be good.
