### ISSUE TITLE
[Feature Request] Enable use of fonts from host operating system

### ISSUE THREAD

**Issue by mikeloeven** [darkreader/darkreader#5047]
# Feature Request

## Is your feature request related to a problem? Please describe
I noticed there is a menu that allows you to specify a replacement font for page text however there is a very limited set of font options.

## Describe the solution you'd like
I would like to see the plugin populate the full list of fonts installed in the operating system

**Comment by Gusted** [comment]
Hi @mikeloeven!

This isn't possible due to some technical logistic, which mostly occur due to Firefox and Edge not exposing all listed fonts.
https://github.com/darkreader/darkreader/blob/70a9e5d0f242f3b13388f7cf601a774551d12a37/src/background/utils/extension-api.ts#L101-L113

Regards,
Gusted
