### ISSUE TITLE
Improve legibility for some color patterns

### ISSUE THREAD

**Issue by Saucistophe** [darkreader/darkreader#505]
I was reading a Crucible (Atlassian's solution for code monitoring) code review, and while the Dynamic filter work flawlessly, giving some vivid color and no performance impact, some lines were hard to read.

On the following image (raw then inverted) notice how the 
![image](https://user-images.githubusercontent.com/7082839/40044555-f6f6f40e-5827-11e8-9d29-9a21ae7a9998.png)
![image](https://user-images.githubusercontent.com/7082839/40044557-f8a3b706-5827-11e8-904a-57cb6c0fecf3.png)

The dev tools tells me that the color switched from #0000FF to #3333FF.
![image](https://user-images.githubusercontent.com/7082839/40044699-7a6c744e-5828-11e8-8504-2fab2959d0e0.png)

So the value stays at 100%, the hue stays the same, but the saturation drops from 100 to 80. So, all in all, in this particular case the color stays as bright but is less vivid, so it is less legible in this case.

Maybe there is a color space or transformation that would improve the results?

I can provide an HTML test page if needed.

**Comment by alexanderby** [comment]
Blue color was improved recently.
