### ISSUE TITLE
[BUG] Does not work wıth thunderbird

### ISSUE THREAD

**Issue by avatar-lavventura** [darkreader/darkreader#5052]
I have installed the plugin into thunderbird but it does not make any affect. What should I do it make it work on thunderbird?

<img width="278" alt="image" src="https://user-images.githubusercontent.com/18537398/107952815-4e60f580-6fab-11eb-8713-7ee656b78a90.png">

**Comment by Gusted** [comment]
Follow the template.

**Comment by avatar-lavventura** [comment]
Where can I find the template? Also it does not change the background of the mails from white to black like it does on `docs.google.com`

**Comment by Gusted** [comment]
Unless their is an bug in Github.com issue system, the template was already provided to you when you clicked on bug report https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Replace+with+title
![image](https://user-images.githubusercontent.com/25481501/107954080-4e0d2e00-6f9c-11eb-962f-803263b9fd63.png)
