### ISSUE TITLE
[thunderbird]  Is it possible to change the background color of the mail from white to black?

### ISSUE THREAD

**Issue by avatar-lavventura** [darkreader/darkreader#5053]
This is related to https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1550:

---------

> Example view:
> 
> <img width="590" alt="image" src="https://user-images.githubusercontent.com/18537398/98450676-9c19c680-214f-11eb-879b-54dc9ce841b3.png">
> 
> If possible I want to change the background colour from white to darker one like dark blue. If yes, I would like to change also the font color into white. 
> 
> => How could I achieve this?

The response I get was: 

> There's no work around at the moment, but I would accept patches.

**[Q]** Can `darkreader` overcame this problem with a proper configuration?

**Comment by Gusted** [comment]
Use the proper template.
