### ISSUE TITLE
[BUG] THUNDERBIRD mailing background does not change from white to black

### ISSUE THREAD

**Issue by avatar-lavventura** [darkreader/darkreader#5054]
There is not proper [documentation](https://addons.thunderbird.net/en-US/thunderbird/addon/darkreader/) on the thunderbird side and developers keep closing the issues to ignore to proper solution, I believe they didn't make implementation to solve it.

`darkreader` does not change background of mails from white to black, please see the related issue I experienced https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1550#issue-738311491. So there is no meaning to use darkreader on the thunderbird, which only work as a theme. So it should be called as `darkreader` theme. 

Note: [dracula-theme ](https://addons.thunderbird.net/en-US/thunderbird/addon/dracula-theme-for-thunderbird/?src=cb-dl-recentlyadded ) does much better job than `darkreader` to organize colors.

**Comment by Gusted** [comment]
>  and developers keep closing the issues to ignore to proper solution

And you are ignoring to follow the proper bug template, which after 3 issues is getting me really annoyed. Which I prefer don't be at the beginning of the week. 



>  I believe they didn't make implementation to solve it.

That _can_ be the case. However I won't not look into the issue as long no proper issue has been filled which information that follows the template.





> `darkreader` does not change background of mails from white to black, please see the related issue I experienced [thunderbird-conversations/thunderbird-conversations#1550 (comment)](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1550#issue-738311491).

It does, thereby the the creator of thunderbird-conversations itself seems to say their is no workaround for that specific problem https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1550#issuecomment-723667570 and is being tracked at https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1510




> So there is no meaning to use darkreader on the thunderbird, which only work as a theme. So it should be called as `darkreader` theme.

Their is, however as  I see it their is an problem with this add-on on the styling which they acknowledge and are tracking the issue.


>  So there is no meaning to use darkreader on the thunderbird, which only work as a theme. So it should be called as `darkreader` theme.
> 
> Note: [dracula-theme ](https://addons.thunderbird.net/en-US/thunderbird/addon/dracula-theme-for-thunderbird/?src=cb-dl-recentlyadded) does much better job than `darkreader` to organize colors.

Thank you for the information on this bug report, it helped a lot to understand this bug.

Hereby I warn you for 3x not using the proper template, please consult [CODE OF CONDUCT](https://github.com/darkreader/darkreader/blob/master/CODE_OF_CONDUCT.md) for possible consequences if you continue doing so.
