### ISSUE TITLE
[Broken Website] bestreviewguide completely white

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#5058]
# Broken Website

## Website
https://www.bestreviewguide.com/en/reviews/electronics/best-headphones/audio-technica-ath-sr5bt-review/

## How to Reproduce
Just visit the homepage

## Expected behavior
Dark

## Actual behavior
Bright

## Screenshots
![Screenshot_20210215_164257-1](https://user-images.githubusercontent.com/6344099/107967016-e4e1e680-6fac-11eb-9be0-04202c4b8211.png)

## System Information

- OS: Linux
- Browser: Firefox 85
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Quite challenging one, why this was blank. But managed to got an PR out of it #5059

**Comment by ShalokShalom** [comment]
So does this work now?

**Comment by Gusted** [comment]
After #5059 is merged, it should works.
