### ISSUE TITLE
[Broken Website] reverso.net login form not working

### ISSUE THREAD

**Issue by antenore** [darkreader/darkreader#5060]
# Broken Website

## Website

https://context.reverso.net/translation/

- Go to the linked website
- Click on the 'Log in' link on the right of the header

## Expected behavior

The website should show up a login form, but that doesn't happen

## Actual behavior

The page is refreshed, the login is not possible.

## System Information

- OS: Linux (fedora 33 and Arch Linux)
- Browser: Firefox 85.0.2 (64-bit)
- Dark Reader Version: 4.9.27

## Additional context

Thanks a lot for this amazing add-on!!!
I feel your pain in checking everything single report you receive, I'll help somehow, sorry if I cannot help with code and better debugging now :-\

**Comment by Gusted** [comment]
Does it happens when you disable Dark reader?
https://user-images.githubusercontent.com/25481501/108089876-f7722380-7071-11eb-845d-45df4b256cd7.mp4

**Comment by antenore** [comment]
@Gusted disabling Dark reader it works, the login form appear and I can log-in 

This you can test also yourself if you like.

**Comment by Gusted** [comment]
> @Gusted disabling Dark reader it works, the login form appear and I can log-in
> 
> This you can test also yourself if you like.


> https://user-images.githubusercontent.com/25481501/108089876-f7722380-7071-11eb-845d-45df4b256cd7.mp4

**Comment by antenore** [comment]
Now it works! Sorry for this, I've tried multiple times, and it didn't work.

Closing.
