### ISSUE TITLE
[Feature Request] An option to use the qt theme

### ISSUE THREAD

**Issue by Toadfield** [darkreader/darkreader#5064]
# Feature Request

## Is your feature request related to a problem? Please describe
Not really a problem,but I change my qt theme many times and I am not good at finding the same color for dark reader.

## Describe the solution you'd like
That there is a option to enable that your current qt theme gets used for dark reader and that if you change it that it automatically gets changed for dark reader.

**Comment by Gusted** [comment]
Hi @Toadfield!

Could you elaborate on what you mean with `QT theme`

Regards,
Gusted

**Comment by AndrewDaGuy** [comment]
> Could you elaborate on what you mean with `QT theme`

From what I found on *the internet*, it seems `QT theme` means gnome theme, which probably dark reader can't get :/

**Comment by Toadfield** [comment]
I mean the kde theme for qt programs.

**Comment by Gusted** [comment]
Hi @Toadfield!

@AndrewDaGuy is right, as an extension we cannot fetch this theme nor detect it.

Regards,
Gusted
