### ISSUE TITLE
Problem with navbar on www.w3c.org [Dynamic]

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#508]
I went on [this page](https://www.w3.org/TR/clipboard-apis/#async-clipboard-api)
![image](https://user-images.githubusercontent.com/11363215/40083910-362a0bcc-589e-11e8-88b4-c6ab0d9afee1.png)

And problem is with id `#toc`, 'case [here is another page with the same problem](https://www.w3.org/TR/2018/WD-payment-method-basic-card-20180510/)

**Comment by sicu** [comment]
================================

w3.org

INVERT
#toc
.toc

================================
