### ISSUE TITLE
[BUG] Dark Reader not enabled in Vivaldi Web Panels

### ISSUE THREAD

**Issue by RadBrad87** [darkreader/darkreader#5080]
# Bug Report

## Describe the bug
Add a Web Panel in Vivaldi for a site that has Dark Reader enabled, Dark Reader is not enabled in the panel as expected

## Steps to reproduce

-Add a Web Panel in Vivaldi for a site that has Dark Reader enabled by clicking the "+" on the left bar
-Dark Reader is not enabled in the panel as expected

## Expected behavior

Dark reader should be enabled in the web panel

## Actual behavior

Dark Reader not enabled in the panel.

## System Information

- OS: MacOS
- Browser: Vivaldi
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Hi @RadBrad87!

Due to how the web panels logic are composed with the data that we are given, we've disabled support for web panels. As we don't know any relevant info other than the site's URL and due to this cannot use it to it's full capability. 

Regards,
Gusted

**Comment by RadBrad87** [comment]
Hi @Gusted,

What other information is needed? Perhaps the Vivaldi team could make it available if requested.

Cheers,
Brad

**Comment by Gusted** [comment]
> What other information is needed?

See comment: https://github.com/darkreader/darkreader/blob/v4.9.31/src/background/tab-manager.ts#L46
It doesn't have the basic information like any other tab has. Making it impossible to target the web panel.
