### ISSUE TITLE
[BUG] - On change tab

### ISSUE THREAD

**Issue by julien-boucly-needone** [darkreader/darkreader#5081]
# Bug Report

## Describe the bug

On change tab, DarkReader apply dark mode on page desactivated

## Steps to reproduce

- Go to https://google.com
- Open new tab with another website, exemple : https://github.com/ <= On this website DarkReader is desactivated in config
- Switch tab 

## Expected behavior

On the website Github DarkReader is descativated.

## Actual behavior

DarkReader is activated...

## Screenshots

![Enregistrement de l’écran 2021-02-18 à 10 03 39](https://user-images.githubusercontent.com/65957492/108333184-facff100-71d0-11eb-971d-a7d3e66ad344.gif)

## System Information

- OS: MacOS
- Browser: Chrome Version 88.0.4324.150  (x86_64)
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Hi @julien-boucly-needone!

Your video starts on google.com already an not on github.com so the situation is a little unclear. So github.com is deactivated and when you open github normally it isn't getting darkened, but when you than switch tabs to e.g. google and then back it is activated?

Regards,
Gusted

**Comment by julien-boucly-needone** [comment]
> Salut @ julien-boucly-needone !
> 
> Votre vidéo démarre déjà sur google.com et non sur github.com, donc la situation n'est pas claire. Donc, github.com est désactivé et lorsque vous ouvrez github normalement, il ne s'assombrit pas, mais lorsque vous passez d'un onglet à Google par exemple, puis à nouveau, il est activé?
> 
> Cordialement,
> Gusted

Hi @Gusted 

excuse me for my unclear explanation. 

Basically I'm on whatever tab where DarkReader is or isn't enabled, and I'm switching tabs on a site like Github that's in the list of websites that shouldn't be taken into account. account by DarkReader but it is still taken into account.

**Comment by julien-boucly-needone** [comment]
I solved the problem by clicking twice on this button => 
![Capture_d_écran_19_02_2021_10_42](https://user-images.githubusercontent.com/65957492/108487121-2f11e300-729f-11eb-8261-a9884092bcaa.png)
