### ISSUE TITLE
[Feature Request] Replace with title

### ISSUE THREAD

**Issue by getFaster** [darkreader/darkreader#5084]
# Feature Request

## Is your feature request related to a problem? Please describe
Pure black theme is better than bright color, but I still get eyesore sometimes. I wish Dark Reader can have a dark green color like Monokai.

## Describe the solution you'd like
Maybe Dark Reader can let its user to choose the color he/she wishes to use. Or a simple small feature that provide another dark color other than pure black will be very helpful.

## Additional context
I imagine this feature will not be too difficult. If someone can kindly point out places in source code to look in, maybe I will be able to make a pull request some time.

**Comment by Gusted** [comment]
Hi @getFaster!


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Custom background, text and selection colors (under Theme click See all options, Colors).

Regards,
Gusted
