### ISSUE TITLE
[Broken Website] Jellyfin Metadata Issue

### ISSUE THREAD

**Issue by Nan123721** [darkreader/darkreader#5102]
# Broken Website
Jellyfin Media Server
## Website

http://localhost:8096 (By Default) MUST BE RAN LOCALLY
## How to Reproduce

After navigating pages going back using your browsers built in back arrow and not the UI elements.
## Expected behavior

Show saved metadata images in the correct format.
## Actual behavior

Shows white image in place of where metadata should be.
## Screenshots

![Screenshot_20210220_145421](https://user-images.githubusercontent.com/49777069/108610630-0a476980-738c-11eb-82f9-35e8bc7dc89a.png)

## OS Info
- OS: Arch Linux
- Browser: Firefox 85.0.2
- Dark Reader Version: 4.9.27

**Comment by Gusted** [comment]
Hi @Nan123721!

This seems to be more likely an issue with Jellyfin rather than Dark Reader as anything related should still display something. This could be an floof and network issue. When you open the Dev Tools(ctrl + shift + i) Then navigate to the console tab does it show any error or warning?

Regards,
Gusted

**Comment by Nan123721** [comment]
Nope, No issues. Disabling Darkreader on the site fixes the issue. It could very well be an issue with Jellyfin. Either way turning the extension off fixed it so I figured I would report it anyway. I can close the issue If you would like.

**Comment by Gusted** [comment]
> Nope, No issues. Disabling Darkreader on the site fixes the issue. It could very well be an issue with Jellyfin. Either way turning the extension off fixed it so I figured I would report it anyway. I can close the issue If you would like.

I will have a look tomorrow with Jellyfin and see if their is anything not behaving.

**Comment by Revadike** [comment]
Hey @Nan123721, I suggest changing the issue title for better searchability for others that may be searching for this issue. You're currently using the default title of the issue template.

**Comment by Nan123721** [comment]
hahaha i feel dumb. Will do

**Comment by Gusted** [comment]
Hmm, Seems like an flook that could happen once in the while. Not really anything to safeguard against it.

Regards,
Gusted
