### ISSUE TITLE
[Broken Website] NPM Runkit

### ISSUE THREAD

**Issue by Revadike** [darkreader/darkreader#5103]
# NPM Runkit

## Website
https://npm.runkit.com/

## How to Reproduce
  - Go to the site
  - See that the sandbox environment isn't loading

## Expected behavior
The sandbox environment (where you put in your node.js code) should be loading

## Actual behavior
It is not loading

## Screenshots
![image](https://user-images.githubusercontent.com/4411977/108612680-3514da80-73eb-11eb-88a0-a089b839e0b7.png)
![image](https://user-images.githubusercontent.com/4411977/108612693-4b229b00-73eb-11eb-8eaa-fbfd9e053455.png)

## System Information

- OS: Windows
- Browser: Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
- Dark Reader Version: 4.9.27

## Additional context
N/A

**Comment by Trunks8257** [comment]
same on firefox

**Comment by simon-pct** [comment]
duplicate of #2420

**Comment by Revadike** [comment]
Not sure why it needs closing when the issue is unresolved.

**Comment by Gusted** [comment]
This is a duplicate issue.
