### ISSUE TITLE
[BUG] Hotkeys swallowing inputs

### ISSUE THREAD

**Issue by cathrinevaage** [darkreader/darkreader#5106]
# Bug Report

## Describe the bug
Hotkeys captures and swallows inputs.
The hotkeys `⌥⇧A` and `⌥⇧D` both have corresponding symbols, symbols that can't be typed with the keyboard alone, as the extension captures these combinations.
As a Norwegian user with an English keyboard layout, the way for me to reach the 3 extra letters of the alphabet, æøå, is done with `⌥` and a letter. If I want the letter to be in uppercase I'm gonna have a hard time typing Å with this extension active.

## Steps to reproduce
Press `⌥⇧A`.

## Expected behavior
The keyboard input should be swallowed.

## Actual behavior
The keyboard input is swallowed.

## System Information

- OS: MacOS
- Browser: Chrome
- Dark Reader Version: 4.9.27

## Proposed solution
Make the hotkeys adjustable, so that they can be moved to less obstructive combinations.
Allow the hotkeys to be disabled all together.

**Comment by Gusted** [comment]
Hi @cathrinevaage!

Please visit `chrome://extensions/shortcuts` to change the shortcuts.

Regards,
Gusted

**Comment by cathrinevaage** [comment]
Oh, I had no idea that was a thing. Thank you!
