### ISSUE TITLE
[Broken Website] https://architects.ffm.to/fttwte

### ISSUE THREAD

**Issue by caneleex** [darkreader/darkreader#5110]
# Broken Website

## Website

https://architects.ffm.to/fttwte

## How to Reproduce

- Go to the site
- Have dark reader enabled for the page (if dark reader is not enabled for the site, enable it and refresh the page)

## Expected behavior

The content of the page should be visible

## Actual behavior

The whole page is dark and blank

## Screenshots

How it looks without dark reader being enabled:
![](https://i.imgur.com/diKA32L.png)
How it looks after enabling dark reader for the page:
![](https://i.imgur.com/9XmVrw8.png)
How it looks after enabling dark reader and refreshing the page:
![](https://i.imgur.com/cRJud3b.png)

## System Information

- OS:  Windows
- Browser:  Firefox 85.0.2
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Nothing to do the sites expects element x but gets element y which is an Dark Reader style. And because it's uses generic functions on the element it's out of the question to spoof it to get them to `element x` and which they expect.
