### ISSUE TITLE
[Broken Website] whatbox.ca

### ISSUE THREAD

**Issue by Amandaville** [darkreader/darkreader#5111]
# Broken Website
whatbox.ca

## How to Reproduce

You added whatbox.ca to the dark-sites.config a few weeks ago and I have been having problems ever since.  Everything was fine prior to the site being added to the global dark list.

The problem is not with the public facing sales pages.  They will look fine if you browse the site.  

The addition to the global dark list broke the VPS servers on that domain.  ex: myserver.whatbox.ca.  There are a variety of applications running on these servers and dark mode is now broken.  Most notably ruTorrent.  Parts of the page are dark, while others are bright and text is unreadable.  I tried different modes, dynamic, filter, filter+ and static but they are all problematic.  So I tried editing the Dev Tools options and after several hours of frustration, all I could do is reverse the light and dark areas but not make the entire page dark.  

The next thing I tried was to remove whatbox.ca from the dark-sites.config file.  Well that broke the entire extension!  I tried to reverse the changes but the extension was permanently damaged apparently.  I clicked the repair extension button and that wiped out all of the custom adjustments I had made to many sites over the course of several months and reset everything to defaults.

I now have nearly 4 hours in to this and I'm no closer to fixing it and have lost several months worth of custom edits.  Since the problems didn't seem to start until the root domain was added to the global dark list, I have to believe that's where the problem lies.

## Screenshots

![Screenshot 2021-02-23 36](https://user-images.githubusercontent.com/37563017/108779259-2ec46100-7599-11eb-8897-07b80b681690.png)

![Screenshot_2021-02-23_05-04-18](https://user-images.githubusercontent.com/37563017/108779292-384dc900-7599-11eb-85a2-47e3e5efa353.png)

## System Information

- OS:  Linux
- Browser:  Brave
- Dark Reader Version:  4.9.29

**Comment by Gusted** [comment]
> There are a variety of applications running on these servers and dark mode is now broken. Most notably ruTorrent. Parts of the page are dark, while others are bright and text is unreadable. I tried different modes, dynamic, filter, filter+ and static but they are all problematic. So I tried editing the Dev Tools options and after several hours of frustration, all I could do is reverse the light and dark areas but not make the entire page dark.

This could happen when they are being loaded into an IFrame which aren't probably excluded and served on another domain. I'm not sure but it's the best guess for this behavior.

> The next thing I tried was to remove whatbox.ca from the dark-sites.config file. Well that broke the entire extension!

Well, I should assume you did go to the brave's userdata folder and in the folder where dark reader is saved you've modified the dark-sites.config. This shouldn't be the way to modify an extension nor it's config files, due to signing of the extension it will fail to verify the integrity/sign process of the add-on and will show as corrupt.

>  I clicked the repair extension button and that wiped out all of the custom adjustments I had made to many sites over the course of several months and reset everything to defaults.

I suspect chrome's repair button simply re-installs the extension and remove any setting related to it to produce an 'clean build' of it and don't make it corrupt anymore.

> I now have nearly 4 hours in to this and I'm no closer to fixing it and have lost several months worth of custom edits. Since the problems didn't seem to start until the root domain was added to the global dark list, I have to believe that's where the problem lies.

I will remove the site from the config for now.

Regards,
Gusted
