### ISSUE TITLE
[Broken Website] Cannot toggle mode on https://firebase.flutter.dev/

### ISSUE THREAD

**Issue by brizaldi** [darkreader/darkreader#5123]
# Broken Website

## Website
https://firebase.flutter.dev/

## How to Reproduce
  - Go to https://firebase.flutter.dev/
  - Toggle dark reader mode on
  - Now we cannot disable/toggle it off

## Expected behavior
User can toggle on/off dark reader mode

## Actual behavior
After enable dark reader mode on, we cannot disable it

## Screenshots
![Screenshot of the problem](https://user-images.githubusercontent.com/41714881/108930081-d2843e80-7677-11eb-9c25-948914c2bdfc.png)

## System Information
- OS: Windows 10 20H2 Build 19042.804
- Browser: Firefox 86.0
- Dark Reader Version: 4.9.29

**Comment by AndrewDaGuy** [comment]
I don't understand how you can't disable it? I cannot reproduce this issue.

**Comment by brizaldi** [comment]
@AndrewDaGuy

https://user-images.githubusercontent.com/41714881/110456638-62a49800-80fc-11eb-8ffd-6d5f9da5a7d4.mp4

**Comment by AndrewDaGuy** [comment]
> @AndrewDaGuy
> 2021-03-09.17-22-09.mp4

o.o I will try to reproduce this

**Comment by Gusted** [comment]
Hi @brizaldi!

Make sure the domain `flutter.dev` isn't in the site list. Due to #147 this isn't possible.

Regards,
Gusted

**Comment by brizaldi** [comment]
@Gusted okay, it's working after i removed flutter.dev from site list, but is there a way to include flutter.dev while excluding it's subdomain?

**Comment by Gusted** [comment]
> @Gusted okay, it's working after i removed flutter.dev from site list, but is there a way to include flutter.dev while excluding it's subdomain?

Luckily their is! Add `^flutter.dev` into the sitelist.

**Comment by brizaldi** [comment]
@Gusted Wow, thank you 👍, it's working perfectly now.

Closing this thread.
