### ISSUE TITLE
Please don't change scrollbox color

### ISSUE THREAD

**Issue by Kratorator** [darkreader/darkreader#5141]
Everybody knows Windows 10 was a big step back in terms of UI user-friendliness. Now that things are slightly improved, please do not modify the scrollbox color (Firefox latest version, monitor brightness 100%).

**In DR dark mode**, even after thousands of uses, it still is impossible to remember where the scrollbox is when you're at the top or bottom of the webpage. Is it the grey part of the scrollbar, or the black one? We get it wrong about 50% of the time.
Same **in DR light mode**: when hovering over the scrollbar, the scrollbox becomes a shade so close to the scrollbar background that if you look away at the page content and return to the scrollbar, you think the scrollbox has disappeared. Good UI design provides instant feedback on the situation. Now that Firefox has fixed its own problem in this regard, please simply keep the default scrollbox color and behavior in both DR modes.

**Comment by Gusted** [comment]
Not following the [issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFeature+Request%5D+Replace+with+title)
