### ISSUE TITLE
[BUG] Error: Embedded Dark Reader cannot access a cross-origin resource

### ISSUE THREAD

**Issue by ibrahemesam** [darkreader/darkreader#5147]
Error: Embedded Dark Reader cannot access a cross-origin resource file:///mnt/sda6/Desktop/Code/Projects/Chaty/redist/main.css Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.
- - - - - -
I tried:
`<script src="darkreader.js"></script>`
then :
```
DarkReader.setFetchMethod(window.fetch);
DarkReader.enable();
```
, but the error remains
![Screenshot from 2021-02-26 06-51-27](https://user-images.githubusercontent.com/43931249/109258545-27a08b80-7803-11eb-9fb3-fbdd75f44567.png)

**Comment by Gusted** [comment]
Hi @ibrahemesam!

Please host your local website on an local webserver trough something like python
```
python3 -m http.server 8080
```
It isn't possible for dark reader to fetch local resources that are on the user's computer. That would break `security 101` principles.

Regards,
Gusted

**Comment by caihai123** [comment]
有没有某种方式可以忽略掉类似的文件呢，我的iconfont.css使用的外部的资源，我想直接忽略它
