### ISSUE TITLE
Thunderbird Dark Reader does not make e-mail messages dark

### ISSUE THREAD

**Issue by fredddii** [darkreader/darkreader#5148]
# Bug Report

## Describe the bug

Dark mode is not functioning in e-mail messages.

## Steps to reproduce

1. Install Dark Reader in the latest Mozilla Thunderbird 64-bit for Windows.
2. Open any e-mail either HTML or text.

## Expected behavior

For e-mail messages to be converted to dark mode like websites are converted to dark mode in browsers.

## Actual behavior

E-mail messages are not converted to dark mode after adding the add-on.

## Screenshots

![dark-reader-thunderbird-dark-email-issue](https://user-images.githubusercontent.com/15217150/109385095-a5db5b80-78f1-11eb-892d-75b671bc547a.png)

## System Information

- OS: Windows 10 Pro Version 20H2 (OS Build 19042.844)
- Browser: Mozilla Thunderbird 78.8.0 (64-bit)
- Dark Reader Version: Dark Reader 4.9.28

**Comment by Gusted** [comment]
Hi @fredddii!

Do you have any other add-ons?

Regards,
Gusted

**Comment by fredddii** [comment]
No, these are the only ones. This is both happening on my desktop and laptop.

Before I used to manually adjust colours under Options -> General -> Language & Appearance -> Colours.

I would set the text to white, and background to a bit above the black colour. Now I installed Dark Reader and reverted the colours to default, but Dark Reader seems to do nothing at all.

**Comment by Gusted** [comment]
Hmm, no suchs known problems has been noted before. What if you do a simple restart of thunderbird?

**Comment by fredddii** [comment]
Nothing. I have tried toggling a lot of options on and off but nothing helps. It dose not work for me.

Are there logs available somewhere that I can check out for errors?

**Comment by Gusted** [comment]
> Are there logs available somewhere that I can check out for errors?

Unfortunately, when Dark Reader isn't doing something at all. No logs will help. You could however try to re-install it.

**Comment by Theblockbuster1** [comment]
This also happened to me, but closing and opening Thunderbird mostly solved this issue. However, it kept not working for one email account using the [Owl add-on](https://addons.thunderbird.net/en-GB/thunderbird/addon/owl-for-exchange/).

**Comment by Gusted** [comment]
> I think if you manually mess around with the colours, Dark Reader will not override them, until Mozilla Thunderbird will update to a next version.

Seems like a bug on its own? It should consist between browsers.
> Can you change the text colour and background colour in Options -> General -> Language & Appearance -> Colours... and tell me if Dark Reader still works for you?

DR disabled:
![image](https://user-images.githubusercontent.com/25481501/110497020-5e757c00-80f6-11eb-9731-bd53f9c717c5.png)

DR enabled:
![image](https://user-images.githubusercontent.com/25481501/110497073-6af9d480-80f6-11eb-843b-b4b334368b1f.png)

**Comment by fredddii** [comment]
For me the bug is fixed now. Thanks for the replies.
