### ISSUE TITLE
[BUG] very minor bug when navigating google sports live results

### ISSUE THREAD

**Issue by akaitori221** [darkreader/darkreader#5149]
# Bug Report

## Describe the bug
I often use google to track live football matches, and the app's dynamic mode is FANTASTIC i have to say, and it works on regular google searches great, but with the live sports window that google shows, in the beginning the theme displays the text color correctly (which is white foreground over dark background). However, if I expand the window showing the results then go back to the main page, the text color changes to grey.

## Steps to reproduce
1. Google search "la liga" for example, you will see a window just below the search bar that is displaying the current matches going on.
2. Click the "See More" button that has a downward arrow on it, this will expand the view to see more matches.
3. now either click the back button from the browser, or the back button on the google window it self.
4. now that you are back on the original search window, the text turns grey instead of white.

## Expected behavior
Text should be staying white on the window before and after expanding the window

## Actual behavior
Text turns to grey if you expand the window and then go back.

## Screenshots
before any navigation:
![Before_Expanding window](https://user-images.githubusercontent.com/66203372/109388856-aa931600-78d7-11eb-8570-31f37ed86122.PNG)

After navigating into the window and going back
![After_Expanding window and clicking back](https://user-images.githubusercontent.com/66203372/109388861-ae269d00-78d7-11eb-8c6d-e403f041dd88.PNG)

## System Information
OS: Windows 10 Pro x64 Insider Preview Dev build 21322.1000
Browser: Firefox/86.0
Dark Reader Version: v5 preview (4.9.29)

**Comment by Gusted** [comment]
#4977

**Comment by akaitori221** [comment]
Hey please forgive my ignorance. I attempted this fix and it still does not work, but I wanna make sure I didn't mess up the fix. All I did was extract the .xpi extension file, changed the inject/index.js file with the changes you referred to, re-compressed the files back to .zip and changed it to .xpi, and added the extension to firefox manually. It is still doing the same behavior, is this not how I am supposed to do it? let me know, appreciate it!

**Comment by AndrewDaGuy** [comment]
> Hey please forgive my ignorance. I attempted this fix and it still does not work, but I wanna make sure I didn't mess up the fix. All I did was extract the .xpi extension file, changed the inject/index.js file with the changes you referred to, re-compressed the files back to .zip and changed it to .xpi, and added the extension to firefox manually. It is still doing the same behavior, is this not how I am supposed to do it? let me know, appreciate it!

@akaitori221 I'm pretty sure thats not how you build it, you can find build instructions [here](https://github.com/darkreader/darkreader#building-for-use).

But in the nutshell you (Copied from build instructions):
1. Download the source code from https://github.com/darkreader/darkreader/tree/CORS-Patch or check out from git.
2. Install [Node.js LTS](https://nodejs.org/en/)
3. Open terminal in root folder and run:
	- `npm install` 
	- `npm run build`
4. You should have `build-firefox.xpi` (Firefox) and a `build.zip` that you don't need (unless using chromium)
5. Add the extension to your browser.

Hope this helps! :]

**Comment by akaitori221** [comment]
Hey Andrew,

Really appreciate your reply! Unfortunately tho, I did exactly the steps you mentioned, and at first firefox didn't want to add the extension as it was not "verified". But I then loaded the extension temporarily on firefox "Debug Add-on" option, and the issue is still persisting with it.

Any ideas what the issue might be here? maybe I should clear the cache? appreciate your help

**Comment by AndrewDaGuy** [comment]
> Hey Andrew,
> 
> Really appreciate your reply! Unfortunately tho, I did exactly the steps you mentioned, and at first firefox didn't want to add the extension as it was not "verified". But I then loaded the extension temporarily on firefox "Debug Add-on" option, and the issue is still persisting with it.
> 
> Any ideas what the issue might be here? maybe I should clear the cache? appreciate your help

@akaitori221 At this point I have no idea as im too lazy to build it for myself and test it out :[ , maybe @Gusted can help?

**Comment by Gusted** [comment]
> @akaitori221 At this point I have no idea as im too lazy to build it for myself and test it out :[ , maybe @Gusted can help?

I've tested it myself, the #4977 seems to improve this behavior but not 100% remove it.

**Comment by akaitori221** [comment]
> 
> 
> > @akaitori221 At this point I have no idea as im too lazy to build it for myself and test it out :[ , maybe @Gusted can help?
> 
> I've tested it myself, the #4977 seems to improve this behavior but not 100% remove it.

Thanks for the confirmation Gusted, nice heart tattoo
