### ISSUE TITLE
Style browser extensions

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#515]
It would be nice if Dark Reader could style browser extensions, to get rid of white backgrounds from extensions too.

As a reference, a code to affect all chrome and firefox extensions:
`@-moz-document regexp("chrome-extension://.*"), regexp("moz-extension://.*")`

Thanks for your attention,
Regards.

**Comment by lucasfariaslf** [comment]
@Aqa-Ib does this snippet you posted make dark reader affect extension pages also?

**Comment by Aqa-Ib** [comment]
Some of them ye, other not. For example, the extension page of Stylus is affected, but not that of Bookmark Sidebar.

**Comment by Aqa-Ib** [comment]
Although, probably Stylus is the exception because I am trying the global dark style into Stylus itself. 

So now that i think it, probably the answer to your question is not. At least for Chrome.
Yet, in firefox you can style extension pages adding CSS rules to userContent.css.

**Comment by Aqa-Ib** [comment]
Yes. Go to your user's firefox settings folder. In linux it's ~/.mozilla. In windows I guess that it is here: C:\Users<username>\AppData\Roaming\Mozilla\
There it must be a folder called something similar to this: ns67dll2.default
In that folder go to a folder called chrome. If it doesn't exist, create it. There create a file called userContent.css and insert a code like this: https://pastebin.mozilla.org/9085977

**Comment by alexanderby** [comment]
I remember Chrome disallows injecting scripts to extensions pages, Firefox allows to do this for own pages, not sure about external extension pages.

**Comment by Aqa-Ib** [comment]
Actually, now that I look at it, Dark Reader could only style the extension's in-page pop-ups, and extensions that have a in-page widget. Examples of extensions that could be affected:

![screenshot_20180530_154630](https://user-images.githubusercontent.com/16420574/40724142-a3d464fa-6420-11e8-8bf3-47e6d305310a.png)

![screenshot_20180530_154705](https://user-images.githubusercontent.com/16420574/40724209-ca868dd0-6420-11e8-8f9d-b2bbad9d88be.png)

**Comment by Gusted** [comment]
Chromium disallow to change anything to chrome:// urls so also external extension.

**Comment by Gusted** [comment]
Just discovered if you use experimental API's with chrome://flags to enable that extension can do stuff to chrome:// related links google chrome would reject this extension into the store.

**Comment by Yash-Singh1** [comment]
The extension could use the darkreader API. Also, this could possibly be done by enabling darkreader on restricted pages.

**Comment by Gusted** [comment]
> Also, this could possibly be done by enabling darkreader on restricted pages.

This. Also make sure your enabled to allow this in your browser.
