### ISSUE TITLE
When dark mode is on, can't see the video of autohome.com.cn

### ISSUE THREAD

**Issue by fsfyx** [darkreader/darkreader#5170]
For example:
https://chejiahao.autohome.com.cn/info/8063928#pvareaid=2808345
The video is black

**Comment by Gusted** [comment]
Does not follow the [issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website.md&title=%5BBroken+Website%5D+Replace+with+title).
