### ISSUE TITLE
[BUG] Mixed HTTP/HTTPS content errors in Chrome

### ISSUE THREAD

**Issue by MaleNurse** [darkreader/darkreader#5172]
# Bug Report

## Describe the bug

Mixed content errors (HTTP and HTTPS) in Chrome

## Steps to reproduce

Go to https://www.mayoclinic.org/diseases-conditions/diabetic-nephropathy/symptoms-causes/syc-20354556
Check "Manage Extensions"

## Screenshots

![Screenshot 2021-03-03 073818](https://user-images.githubusercontent.com/12175293/109830750-a3c81400-7bf3-11eb-8b71-19ac2217d66b.png)
Full output of stack trace seen above: [Stack Trace.txt](https://github.com/darkreader/darkreader/files/6077112/Stack.Trace.txt)

## System Information

- OS: Windows 10 Pro (Insider Build) 21322.rs_prerelease.210220-1651
- Browser: Version 88.0.4324.190 (Official Build) (64-bit)
- Dark Reader Version: 4.9.29 commit 9b2d516

**Comment by Gusted** [comment]
Hi @MaleNurse!

Seems like error that should be fixed by an extra check.
Not sure how this the first time reported, as websites including `http://` content on a `https://` (accidentally or not) server seems to be not that uncommon.

Regards,
Gusted
