### ISSUE TITLE
[Broken Website] Khronos OpenGL Ref Pages

### ISSUE THREAD

**Issue by jas35484** [darkreader/darkreader#5176]
# Broken Website

## Website
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glAccum.xml

## How to Reproduce

1. go to: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/
2. go to any of the links on the left hand side (for example "glAccum")
3. see that the page doesn't change colors

or 

1. go to: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glAccum.xml
2. see that the page doesn't change colors

## Expected behavior
The selected theme mode is applied to the page.

## Actual behavior
The webpage is unchanged.

## Screenshots
The main page:
![top page](https://user-images.githubusercontent.com/60618606/110010301-c20d3d00-7ce3-11eb-8f20-05739591cce6.png)

An example of a broken page:
![glAccum](https://user-images.githubusercontent.com/60618606/110010309-c46f9700-7ce3-11eb-9cb0-15a5a17a927c.png)

## System Information

- OS: Windows 10
- Browser: Firefox 86.0 (64-bit)
- Dark Reader Version: 4.9.29

also tested on:

- OS: Windows 10
- Browser: Chrome 89.0.4389.72 (Official Build) (64 bit)
- Dark Reader Version: 4.9.29

## Additional context
The different theme modes work correctly on the main page but none of them are applied to any of the .xml pages.

**Comment by Gusted** [comment]
Hi @jas35484!

XML's are not supported, due to rather weird way of styling elements.

Regards,
Gusted

**Comment by jas35484** [comment]
That's too bad, thanks anyway.
