### ISSUE TITLE
probable memory leak

### ISSUE THREAD

**Issue by kikobb** [darkreader/darkreader#5180]
Love the project but unfortunately I have encounter probable memory leak. Firstly I noticed it when Firefox have eaten up my whole memory (16GB) after using same tabs for 2 days (not opening new ones just using already loaded ones). Granted it was a lot of tabs 80+ in 5 windows but in Firefox safe mode ram usage was stable. Secondly flipping on/off button steadily increases ram usage (roughly 100MB every 4 - 5 toggles) afterwards the memory is not freed to previous level (approximately little more than half of used ram by dark-reader is freed)

OS: Ubuntu 20.04.2, kernel: Linux 5.8.0-44-generic, Browser: Firefox Version 86.0 
To reproduce: toggle on/off button and observe memory usage or use heavily Firefox with this extension for a while

**Comment by Gusted** [comment]
Hi @kikobb!

I wasn't able to reproduce this, nor know where to look. As past few weeks, I already spend good amount of time on `about: memory` to check other related memory. And can say that Dark Reader don't waste any memory and is pretty _low_ on memory consumption. Could you please when you encounter this go to `about:memory` then use the Measure and Save button and send an compressed version of it, might indicate where the problem relies.

Regards,
Gusted
