### ISSUE TITLE
[BUG] Darkreader Stopped Working on Linkedln  

### ISSUE THREAD

**Issue by andreprawira** [darkreader/darkreader#5196]
# Bug Report

## Describe the bug
 I use Linkedln everyday and I notice 2 days ago Darkreader on Linkedln stopped working

## Steps to reproduce
Attached videos are showing whats on my screen

https://user-images.githubusercontent.com/42351199/110270764-2e11ce80-7f8c-11eb-8b7f-d46881c9e12d.mp4

https://user-images.githubusercontent.com/42351199/110270800-4681e900-7f8c-11eb-8d7d-9d8cd6cf9696.mp4

## Expected behavior
Should show Linkedln with dark theme, I would attach a screenshot if I had it but I dont

## Actual behavior
 As you can see in the videos, when the website loads, it shows a darkscreen when Linkedln was "loading" then soon as it enters the actual page, the page is broken, its not dark, and there are missing things (check video number 2).

## Screenshots
Please view the videos

## System Information

- OS:  Windows 
- Browser:  Brave browser V1.21.74
- Dark Reader Version:  4.9.29

**Comment by AndrewDaGuy** [comment]
I guess this is more of a "Broken Website" than a bug, I will test this once I finish my homework :]

**Comment by andreprawira** [comment]
Bug is fixed, all good now. Thanks!
