### ISSUE TITLE
heads-up: Dark Reader is failing a lot on Firefox Nightly 88.0a1

### ISSUE THREAD

**Issue by fluffynuts** [darkreader/darkreader#5197]
# Bug Report
A lot of sites are not working as expected with Dark Reader under Firefox Nightly 88.0a1. I know this won't be of highest priority, but it may be an indicator of things to come. 

Simpler sites that have always worked like mybroadband (https://mybroadband.co.za/news/fibre/388580-vumatels-high-fibre-prices-under-fire.html) as well as sites like 15five.com are rendering partially, or not at all darkly.

## Steps to reproduce
- install Dark Reader into the current Firefox Nightly (88.0a1)
- browse to https://mybroadband.co.za/news/fibre/388580-vumatels-high-fibre-prices-under-fire.html

## Expected behavior
Expected the dark site I usually see

## Actual behavior
Site appears mostly dark-on-light, but some text has been made light. What's odd is that if I load a bunch of tabs and go to one later, the page starts out dark but quickly transitions to light, as if Dark Reader _was_ applied, and then "overridden".

## Screenshots
![image](https://user-images.githubusercontent.com/4669340/110288239-60551780-7ff0-11eb-9987-0dfb7f774280.png)
screenshot shows that most of the page is dark-on-light, with an orange arrow at an example where the Dark Reader light text has been applied, but the background has remained light.

## System Information
- OS: Windows 10
- Browser: Firefox Nightly 88.0a1
- Dark Reader Version: latest as at time of writing (4.9.29)

**Comment by Gusted** [comment]
Hi @fluffynuts!

Thank you, we are aware. https://github.com/darkreader/darkreader/issues/5182#issuecomment-792557779.

Regards,
Gusted
