### ISSUE TITLE
Dark Reader gets stuck downloading

### ISSUE THREAD

**Issue by HayStax** [darkreader/darkreader#520]
Sometimes I'll load up a site (https://login.teamviewer.com is one that it has happened with recently) and Dark Reader will get stuck downloading traffic, using about 100KB/s traffic until I disable it and re enable it.

Is this normal and am I just being impatient with it? I don't have  a fast connection so this slows everything down quite a bit.

Using Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by alexanderby** [comment]
Currently Dark Reader has to load stylesheets, images, background images due to security restrictions. If it slows the traffic too much, try using Filter or Static mode.
