### ISSUE TITLE
[Feature Request] Be able to CLEAR the site lists

### ISSUE THREAD

**Issue by heyvoon** [darkreader/darkreader#5203]
# Feature Request

## Describe the solution you'd like
Be able to CLEAR the site lists

**Comment by Gusted** [comment]
```
<!-- 
  ⚠⚠ Do not delete this issue template! ⚠⚠ 
  Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
-->
```
Please follow [the template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFeature+Request%5D+Replace+with+title) and fill out the information accordingly.
