### ISSUE TITLE
[Feature Request] An option to have sites off by default

### ISSUE THREAD

**Issue by Beatso** [darkreader/darkreader#5209]
# Feature Request

## Is your feature request related to a problem? Please describe
I only want the extension for a few websites; and do not want it on for most sites I visit; either because I am okay with the light mode, or it somewhat breaks the site.

## Describe the solution you'd like
A setting to make sites unchanged by default. The per site setting can still be changed to make it light or dark though.

**Comment by AndrewDaGuy** [comment]
Hi @Beatso, This feature is in dark reader already.

1. Open the dark reader panel
2. Click `Dev Tools`
3. Go to the `Dark Reader developer tools` window
4. You should see a button named `Preview new design` on the right of the `Apply` button
5. Click it and it should change to `Switch to old design` (You can close the Dev tool window now)
6. Now navigate to `Settings` in the dark reader panel
7. On the top you should see a toggle called `Enable by default` (Image included below)
![ScreenShot](https://user-images.githubusercontent.com/66189242/110420176-b4183d00-8092-11eb-84cf-dfd5e8952c67.png)
8. Click on the toggle to switch it off

**Comment by Beatso** [comment]
Thanks, these instructions work!
