### ISSUE TITLE
[BUG] Filter+ not applying to whole page.

### ISSUE THREAD

**Issue by JonathanILevi** [darkreader/darkreader#5217]
I have a webpage which has only absolutely positioned elements.  For whatever reason, with Filter+, it is not inverting content which is above or to the left of the most top-left element.

I found this is easily fixed by not just adding a background, but also a border, to the html element.

```
html {
    border: solid 1px rgb(255,255,255) !important;
    background: rgb(255,255,255) !important;
}
```

**Comment by Gusted** [comment]
Hi!

Please follow [the template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Replace+with+title) and fill out the necessary information.

Regards,
Gusted
