### ISSUE TITLE
[Feature Request] Add settings synchronization 

### ISSUE THREAD

**Issue by Croydon** [darkreader/darkreader#5219]
# Feature Request

## Is your feature request related to a problem? Please describe

I'm having several Firefox installations in which I'm using Dark Reader. For many websites, I'm disabling Dark Reader due to breakages or native available dark modes provided by the website.

What is annoying about this, is that I have to maintain this list of websites on each device separately.

## Describe the solution you'd like

Integrate into `storage.sync` to make use of the browser's synchronization abilities.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by AndrewDaGuy** [comment]
Hello @Croydon!

I'm *pretty sure* is a feature in dark reader already!

### Epic Instructions

1. Open the dark reader panel
2. Click `Dev Tools`
3. Go to the `Dark Reader developer tools` window
4. You should see a button named `Preview new design` on the right of the `Apply` button
5. Click it and it should change to `Switch to old design` (You can close the Dev tool window now)
6. Now navigate to `Settings` in the dark reader panel
7. Click `Manage settings`
8. Toggle `Enable settings sync`

Hope this helps :]

**Comment by Croydon** [comment]
Thank you @AndrewDaGuy

Indeed there seems to be such a feature already. Now the question is why I couldn't notice this empirical. Is the sync only available in this preview or is it always enabled?

I will retest this later today or tomorrow.

**Comment by AndrewDaGuy** [comment]
> Thank you @AndrewDaGuy
> 
> Indeed there seems to be such a feature already. Now the question is why I couldn't notice this empirical. Is the sync only available in this preview or is it always enabled?
> 
> I will retest this later today or tomorrow.

@Croydon The preview seems like just an UI change (According to Guested), so it should be still synced when in the old design.

**Comment by Gusted** [comment]
> @Croydon The preview seems like just an UI change (According to Guested),

Correcto.

**Comment by AndrewDaGuy** [comment]
> > @Croydon The preview seems like just an UI change (According to Guested),
> 
> Correcto.

🤔 where do you guys even store the settings in the old design anyways

**Comment by Gusted** [comment]
> thinking where do you guys even store the settings in the old design anyways

The same place where we store the new design :). It's pure and pure the UI that changes. Nothing else.
