### ISSUE TITLE
Add your builds in the release tab

### ISSUE THREAD

**Issue by walrus543** [darkreader/darkreader#522]
Hi,
I can only use your WebExtension by downloading the zip file for Firefox.
Please add your recent builds [there](https://github.com/darkreader/darkreader/releases).

Thank you.

**Comment by Yash-Singh1** [comment]
I think this is supported:
![Screenshot from 2020-11-13 10-52-56](https://user-images.githubusercontent.com/53054099/99109915-69802b80-259e-11eb-9dda-770a86fc1612.png)

**Comment by Primokorn** [comment]
@Yash-Singh1 that's only the source code.

**Comment by alexanderby** [comment]
Done https://github.com/darkreader/darkreader/releases
