### ISSUE TITLE
[Broken Website] bpmn.io

### ISSUE THREAD

**Issue by lvmm** [darkreader/darkreader#5222]
# Broken Website

## Website

demo.bpmn.io/s/start

## How to Reproduce

just open

## Expected behavior

diagram elements should have contracting text and background

## Actual behavior

With dynamic theme engine diagram elements have very similar text and background colours, text is unreadable. With static theme engine lines are black and are invisible on dark background. Only filter engine renders readable image. Multiple confluence charts have similar problems but they are not on publicly accessible pages, so bpmn.io it is.

## Screenshots

dynamic
![dynamic_bpmn_io](https://user-images.githubusercontent.com/11752339/110590494-e7d58e80-8188-11eb-97e8-91b163c480cc.png)
static
![static_bpmn_io](https://user-images.githubusercontent.com/11752339/110590498-e906bb80-8188-11eb-82fb-b07acdc577d0.png)
filter
![filter_bpmn_io](https://user-images.githubusercontent.com/11752339/110590496-e86e2500-8188-11eb-8b0e-e51e321d0d5e.png)

## System Information

- OS: windows 10, linux
- Browser: chrome 87, firefox 86
- Dark Reader Version: 4.9.29

**Comment by AndrewDaGuy** [comment]
Hi, @lvmm!
I will try to push out a fix for this, hopefully :]
