### ISSUE TITLE
[Broken Website] kinopoisk.ru

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#5230]
# Broken Website
## Website
https://www.kinopoisk.ru/

## How to Reproduce
1. Go to https://www.kinopoisk.ru/ site

## Expected behavior
The search field and placeholder in it are visible against the background of the header.

## Actual behavior
The search field and placeholder in it are not visible against the background of the header.

## Screenshots
<details>
<summary>DarkReader on</summary>

![image](https://user-images.githubusercontent.com/19418601/110674249-c43f3200-81e2-11eb-9648-b92d1d899383.png)

</details>
<details>
<summary>DarkReader off</summary>

![image](https://user-images.githubusercontent.com/19418601/110674277-ca351300-81e2-11eb-86c9-c4c6641570c1.png)

</details>

## System Information
- OS: Windows 10
- Browser: Chrome 89
- Dark Reader Version: 4.9.29

## Additional context
If you click on the search field, it will at least become visible, but the placeholder will still not be visible.

**Comment by rakleed** [comment]
@Gusted Can you make the background of the search field itself more contrasting against the background of the header? Since now, they are barely distinguishable.

**Comment by Gusted** [comment]
#5236
