### ISSUE TITLE
[Broken Website] dev.to

### ISSUE THREAD

**Issue by Dinoosawruss** [darkreader/darkreader#5241]
# Broken Website

## Website

https://dev.to/

## How to Reproduce

- Go to dev.to
- See all text is the wrong colour and background isn't changed

## Expected behavior

Expected background and other text items to change to darkmode

## Actual behavior

Everything changes to white/light grey and text is unreadable

## Screenshots

With Dark Reader:
![image](https://user-images.githubusercontent.com/22278485/110827340-de821a00-828d-11eb-9b32-c73772c69ac5.png)
Without:
![image](https://user-images.githubusercontent.com/22278485/110827346-e17d0a80-828d-11eb-8bbf-d6908dc4e1d1.png)

## System Information

- OS: Windows 10
- Browser: Chrome 86
- Dark Reader Version: 4.9.29

## Additional context

N/A

**Comment by AndrewDaGuy** [comment]
Hi, @Dinoosawruss !

It seems I cannot reproduce this?
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/66189242/110831784-7f72d400-8292-11eb-91d7-1e03685612a1.png">

**Comment by Dinoosawruss** [comment]
Oh thats really strange I just went back there and it's fixed 

Not sure what happened lol
