### ISSUE TITLE
[Broken Website] colab.research.google.com

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#5244]
# Broken Website
## Website
https://colab.research.google.com

## How to Reproduce
1. Go to https://colab.research.google.com/notebooks/intro.ipynb site

## Expected behavior
The background of the site is dark gray.

## Actual behavior
The background of the site is purple.

## Screenshots
![image](https://user-images.githubusercontent.com/19418601/110847286-cb873e00-82bd-11eb-8655-c5af9126bbcf.png)

## System Information
- OS: Windows 10
- Browser: Chrome 89, Safari 13
- Dark Reader Version: 4.9.29

**Comment by Gusted** [comment]
This issue is fixed with #4291 and is merged and is in the next release.
![image](https://user-images.githubusercontent.com/25481501/110858754-bf4db180-82ba-11eb-9862-f184540153ee.png)
