### ISSUE TITLE
[Broken Website] wikipedia.org

### ISSUE THREAD

**Issue by lvmm** [darkreader/darkreader#5250]
# Broken Website

## Website
https://en.wikipedia.org/wiki/Unified_Modeling_Language#Diagrams

## How to Reproduce
just go there

## Expected behavior
The first diagram (Hierarchy of UML 2.2 Diagrams, shown as a class diagram) should be readable

## Actual behavior
In Dynamic and Static themes black lines on dark background are unreadable, only Filter themes work. In addition, when mouse pointer hovers above the diagram, Dynamic theme changes diagram background colour which probably is wrong too because it doesn't change when Dark Reader is off.

## System Information

- OS: windows 10, linux
- Browser: chrome 87, firefox 86
- Dark Reader Version: 4.9.29

## Additional context
Some of the diagrams below are similarly affected, also here https://en.wikipedia.org/wiki/IDEF1X#IDEF1X_building_blocks Could be related to #5222 - looks similar.

**Comment by AndrewDaGuy** [comment]
Hi @lvmm !
I will release a patch for this soon :]

**Comment by AndrewDaGuy** [comment]
I can't seem to fix the others, so maybe someone can fix the others :[

**Comment by Gusted** [comment]
> . In addition, when mouse pointer hovers above the diagram, Dynamic theme changes diagram background color which probably is wrong too because it doesn't change when Dark Reader is off.

https://github.com/darkreader/darkreader/pull/2321#issuecomment-615878325 It's the _best_ behavior that can happen with sites like Wikipedia where you can't really distinguish certain things without messing up other things.
