### ISSUE TITLE
[BUG] No settings accessible in Firefox for Android

### ISSUE THREAD

**Issue by t-o-o-m** [darkreader/darkreader#5260]
# Bug Report

## Describe the bug

Using Firefox for Android (nightly, Build #2015797899 and daylight Build #2015785883) there is no possibility to access Dark Reader's settings. The menu item normally listed in Firefox's add-on settings is missing.

## Steps to reproduce

In Firefox for Android:
 - Go to settings > add-ons
 - Click on Dark Reader
 - Notice that there is no 'settings' item which would normally give you access to Dark Reader's settings

## Expected behavior

Have access to Dark Reader's settings via Firefox's add-on menu

## Actual behavior

No access to Dark Reader's settings via Firefox's add-on menu

## System Information

- OS: Android 10
- Browser: Firefox for Android (nightly, Build #2015797899 and daylight Build #2015785883)
- Dark Reader Version: 4.9.29

**Comment by Gusted** [comment]
Hi @t-o-o-m!

Their could be certain things causing this.
1. Your on an new tab, please make sure on a tab with a website.
2. Give it some time to load. Somehow in the first few seconds it wouldn't show in certain scenario's.
3. With "settings" you mean the 3 dots in the top/bottom? If not, then I suggest using the 3 dots and than navigate to the add-on item.

Regards,
Gusted

**Comment by t-o-o-m** [comment]
Thanks, this was an user error. 

The settings are not accessible via 3dot > settings > add-ons > Dark Reader > settings (as is the case for e.g. Ublock) but rather via 3dot > add-ons > Dark Reader.
