### ISSUE TITLE
[BUG] Does not work properly with local files

### ISSUE THREAD

**Issue by x4e** [darkreader/darkreader#5275]
# Bug Report

## Describe the bug

DarkReader will always be enabled for local files (i.e. `file://` protocol) on firefox.
It is not possible to disable darkreader.

## Steps to reproduce
Open a local file in firefox with darkreader installed.

## Expected behavior
Should be possible to disable darkreader. 
The normal functionality is to disable it for the entire site, I with files it should disable itself for all files.

## Actual behavior
Darkreader cannot be disabled, either for the page or for the "site".

## System Information

- OS: `Linux 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux`
- Browser: Firefox 86.0
- Dark Reader Version: 4.9.29

**Comment by Gusted** [comment]
Hi @x4e!

Is their any other entry within your site list that could be conflicting with the `file://` protocol?

Regards,
Gusted

**Comment by x4e** [comment]
Hi.
No there is not. An entry does get added to the site list with the content `file:` if I try to "Toggle current site" however it does not have an effect.

**Comment by Gusted** [comment]
Hmm, could you clear your list? Their might be some faulty entry.

**Comment by x4e** [comment]
Apologies, reinstalling dark reader seemed to fix the problem. Not sure why this was happening. Thanks for the help!
