### ISSUE TITLE
[BUG] Firefox 88.0a1 (2021-03-16) + Sync Settings completely destroys Dark Reader menu and logic

### ISSUE THREAD

**Issue by Marocco2** [darkreader/darkreader#5277]
# Bug Report
New Firefox Nightly desktop 88.0a1 (2021-03-16) build breaks Dark Reader in multiple ways
## Describe the bug

- Wipes out local settings (list of sites non-inverted, saturation-contrast, etc.)
- Resets app every time menu is hidden
- Makes switching to new 5.0 menu impossible

## Steps to reproduce

Install Firefox Nightly desktop 88.0a1 (2021-03-16) and enable Sync Settings in v5 settings. It should revert to old menu and wipes every setting you've made.
## Expected behavior

It should save settings and keep changes
## Actual behavior

See description
## Screenshots

![recording(1)](https://user-images.githubusercontent.com/3944248/111343558-d3f3c600-867b-11eb-86f7-748092b036db.gif)
(sorry for bad quality gif)
## System Information

- OS:  Windows 10 build 20279 64bit
- Browser: Firefox Nightly desktop 88.0a1 (2021-03-16)
- Dark Reader Version:  4.9.29 and latest compiled from master

**Comment by AndrewDaGuy** [comment]
I guess this is kind of related to #5182?

**Comment by Gusted** [comment]
> I guess this is kind of related to #5182, but with more things broken?

Not sure, this just looks like a simple storage error which is resolved by restarting firefox.

**Comment by Marocco2** [comment]
> 
> 
> I guess this is kind of related to #5182, but with more things broken?

It's totally unrelated to that thread

**Comment by Marocco2** [comment]
> 
> 
> > I guess this is kind of related to #5182, but with more things broken?
> 
> Not sure, this just looks like a simple storage error which is resolved by restarting firefox.

Restarted multiple times Firefox. Same behavior. Maybe I should file an issue in Bugzilla

**Comment by Gusted** [comment]
> Restarted multiple times Firefox. Same behavior. Maybe I should file an issue in Bugzilla

Make sure that other extension have the same behavior.

**Comment by Marocco2** [comment]
> 
> 
> > Restarted multiple times Firefox. Same behavior. Maybe I should file an issue in Bugzilla
> 
> Make sure that other extension have the same behavior.

I tried stylus and it doesn't behave like Dark Reader. I'll try more extensions now

**Comment by AndrewDaGuy** [comment]
Can't seem to reproduce this on a fresh installation of Firefox nightly 88.0a1 (2021-03-16)

**Comment by Marocco2** [comment]
![immagine](https://user-images.githubusercontent.com/3944248/111353837-f7bc0980-8685-11eb-9213-b95da839ab49.png)
I search if it's related to an already existing issue. I'll change OP accordingly

**Comment by Gusted** [comment]
> ![immagine](https://user-images.githubusercontent.com/3944248/111353837-f7bc0980-8685-11eb-9213-b95da839ab49.png)
> I'll search if it's related to an already existing issue and change OP accordingly

Hmm, that means indeed the storage isn't working. But should default to local storage.

**Comment by Marocco2** [comment]
![immagine](https://user-images.githubusercontent.com/3944248/111355068-4ae28c00-8687-11eb-830b-d0a37f1ec9a7.png)
Sync Setting did break Dark Reader. I've changed the value to false and now it's working as expected.

**Comment by Gusted** [comment]
[build-firefox.zip](https://github.com/darkreader/darkreader/files/6151202/build-firefox.zip)
This should check the properties first of browser.storage, could you please check if this works?

**Comment by Marocco2** [comment]
> 
> 
> [build-firefox.zip](https://github.com/darkreader/darkreader/files/6151202/build-firefox.zip)
> This should check the properties first of browser.storage, could you please check if this works?

![immagine](https://user-images.githubusercontent.com/3944248/111370659-cc8ee580-8698-11eb-9a00-c9d6f66680f4.png)
doesn't work

**Comment by Gusted** [comment]
> > [build-firefox.zip](https://github.com/darkreader/darkreader/files/6151202/build-firefox.zip)
> > This should check the properties first of browser.storage, could you please check if this works?
> 
> ![immagine](https://user-images.githubusercontent.com/3944248/111370659-cc8ee580-8698-11eb-9a00-c9d6f66680f4.png)
> doesn't work

That's an error from Firefox. and the settings sync was disabled which means the check works and should fall back to local.

**Comment by Marocco2** [comment]
> 
> 
> > > [build-firefox.zip](https://github.com/darkreader/darkreader/files/6151202/build-firefox.zip)
> > > This should check the properties first of browser.storage, could you please check if this works?
> > 
> > 
> > ![immagine](https://user-images.githubusercontent.com/3944248/111370659-cc8ee580-8698-11eb-9a00-c9d6f66680f4.png)
> > doesn't work
> 
> That's an error from Firefox. and the settings sync was disabled which means the check works and should fall back to local.

![immagine](https://user-images.githubusercontent.com/3944248/111371539-da913600-8699-11eb-8065-17fdd71dc014.png)
This is what I get

**Comment by Gusted** [comment]
What if you try on a new Profile?

**Comment by Marocco2** [comment]
> 
> 
> What if you try on a new Profile?

It's.. working. It switches from old to new menu and revert some local settings to "synced" ones if I change some parameters. It properly saves and reload settings if I relaunch the new profile

**Comment by Gusted** [comment]
Best way I can think it's broken, is due to some about:config setting.

**Comment by Marocco2** [comment]
> 
> 
> Best way I can think it's broken, is due to some about:config setting.

That affects storage? I don't have any idea

**Comment by Gusted** [comment]
> That affects storage? I don't have any idea

`about:config` can configure a lot of things. I'm pretty sure.

**Comment by Marocco2** [comment]
> 
> 
> > That affects storage? I don't have any idea
> 
> `about:config` can configure a lot of things. I'm pretty sure.

I mean, I don't have any idea if there is some param that I accidentally modified to make DR broken 😅

**Comment by Gusted** [comment]
> I mean, I don't have any idea if there is some param that I accidentally modified to make DR broken sweat_smile

The indication that it worked on a new profile, gives away that's most likely an param that's faulty.

**Comment by Marocco2** [comment]
I'm gonna close this. Seems like storage was corrupted in some way. Dunno what's caused by. New firefox profile resolved the issue
