### ISSUE TITLE
Make fonts more readable

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#528]
I think that the fonts of dark reader could be much more readable. 
Maybe adding an option to add contrast to fonts color would help.

Before:
![screenshot_20180524_003034](https://user-images.githubusercontent.com/16420574/40454610-bb6b2450-5ee9-11e8-92e0-c43b10b20d85.png)

After;
![screenshot_20180524_003133](https://user-images.githubusercontent.com/16420574/40454637-d5ca9286-5ee9-11e8-9a0a-db991e70ff12.png)

"Before" represents default Dark Reader fonts, using dynamic mode and filters.
"After" represents a CSS font style added on top of Dark Reader.

**Comment by alexanderby** [comment]
The problem is that text style doesn't know what background color is under the element which uses it. I can only adjust the maximal background lightness and minimal text lightness. And also add ability to modify CSS for specific cases.

**Comment by Aqa-Ib** [comment]
And adding a new filter to add contrast to text could be viable?
The problem is that when you reduce the values of brightness and contrast filters, the fonts become difficult to read.

**Comment by Gusted** [comment]
Check the text-stroke option and with contrast isn't optimal. We can't just deselect text from the contrast filter.
