### ISSUE TITLE
Automatic Switching to Dark Mode in Specified Time Period

### ISSUE THREAD

**Issue by Orionsg** [darkreader/darkreader#529]
I find that I mostly like to use the Dark Mode at night when there is no daylight in the office.
It would be great if Dark Reader could automatically switch to dark mode within a specified time period with the possibility for manual override.

**Comment by Aqa-Ib** [comment]
This is a duplicate of #10.

Regards.

**Comment by Orionsg** [comment]
Right, didn't see it.
