### ISSUE TITLE
[BUG] Mozilla Thunderbird plugin not working

### ISSUE THREAD

**Issue by fredddd1** [darkreader/darkreader#5292]
Is it possible to diagnose the issue in logs somewhere?

**Comment by fredddd1** [comment]
@Gusted 

I have observed the following behaviour:
- I open Mozilla Thunderbird. Dark Reader does not work.
- I open an e-mail in a new tab.
- I drag the tab out of the current window.
- The tab now gets created in a new Mozilla Thunderbird window.
- Dark Reader works in the new Mozilla Thunderbird window.

![mozilla-thunderbird-dark-reader-not-working-issue](https://user-images.githubusercontent.com/80743272/112189859-baff8d80-8c04-11eb-94f1-de4215251819.png)

**Comment by Hou-Rui** [comment]
I have experienced the same problem. It seems to happen only in a very recent version of Thunderbird. The versions I tried are Thunderbird 78.7.1 (64-bit), Dark Reader 4.9.28 and Ubuntu 20.04. I also tried building from latest master, but the problem persisted. Hope this can be fixed soon.

**Comment by fredddd1** [comment]
At the moment with the latest Mozilla Thunderbird it seems to always work.

Closing the issue for the time being.
