### ISSUE TITLE
[BUG] wrong build instructions

### ISSUE THREAD

**Issue by yardenac** [darkreader/darkreader#5293]
Your master-branch README.md says to build with `npm run build`, but there's no such script. It seems from a cursory look that your developers are using the `CleanUp-Patch` branch - is that the recommended branch to build from right now?

**Comment by alexanderby** [comment]
Hi, there is such script https://github.com/darkreader/darkreader/blob/master/package.json#L8

Maybe you are doing it from a wrong folder.

**Comment by Gusted** [comment]
> It seems from a cursory look that your developers are using the `CleanUp-Patch` branch - is that the recommended branch to build from right now?

You probably mean me 😄, I'm working on trying to remove Rollup as it's slow with our bundling as well with the current typescript compiler functions and replace it with ESBuild & `tsc` for type checking to improve speed and hopefully more optimizations that can be enabled in the further. However the main branch should be build-able.

**Comment by Gusted** [comment]
Closing - `npm run build` is just a package.json defined script. Any errors shouldn't be specific to dark reader.
