### ISSUE TITLE
[BUG] Site toggle keyboard shortcut does not activate in PDF tabs

### ISSUE THREAD

**Issue by munael** [darkreader/darkreader#5296]
# Bug Report

## Describe the bug

Keyboard shortcuts to toggle dark mode for PDF files doesn't work.

## Steps to reproduce

1. Open a PDF file.
2. Try enabling/disabling Dark Reader for PDF for the corresponding site using the keyboard shortcut.
3. It doesn't work.

## Expected behavior

Works same as in "normal" websites.

## Actual behavior

Nothing triggers. You have to use the icon by mouse.

## System Information

- OS: Windows 10 
- Browser: Chrome 89 
- Dark Reader Version: 4.9.29

**Comment by AndrewDaGuy** [comment]
Are you 99% sure that you did the shortcut correctly?

**Comment by Gusted** [comment]
> Are you 99% sure that you did the shortcut correctly?

Yes I did, and Indeed the shortcut wasn't working on PDF's. So did you use the shortcut correctly and actually got an PDF toggled?
