### ISSUE TITLE
Problem with the colors in EasyEDA.com

### ISSUE THREAD

**Issue by boromyr** [darkreader/darkreader#5313]
Hi, I wanted to report a problem with the EasyEDA.com web editor. The problem is visible in the picture, the background colour does not change correctly. After one or two restarts of the application the problem is resolved.
Browser: Edge 91
OS: Windows 10 
![easyeda](https://user-images.githubusercontent.com/52782032/111924931-0ef46000-8aa7-11eb-979d-92183e75619a.png)

**Comment by Gusted** [comment]
Stick to the [template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website.md&title=%5BBroken+Website%5D+Replace+with+title) and fill out the necessary information.
