### ISSUE TITLE
[BUG] Rule "github.com" matches "github.community"

### ISSUE THREAD

**Issue by liurui39660** [darkreader/darkreader#5317]
# Bug Report

## Describe the bug

I have `github.com` in the exclusion list, but when I open https://github.community/, it is also excluded and I can't turn on the dark mode for it.

## Steps to reproduce

1. Open Dark Reader extension menu
2. Switch to "Site list" and select "Not invert listed"
3. Add an entry `github.com`
4. Open a new tab and go to https://github.community/
5. Remove the entry `github.com`
6. Try to turn on dark mode for https://github.community/

## Expected behavior

The page is in dark mode or I can turn on dark mode for it, no matter whether `github.com` is in the exclusion list or not.

## Actual behavior

With that entry in the exclusion list, https://github.community/ is in light mode and I can't turn on dark mode for it. After removing that entry, I can turn on dark mode as normal.

## Screenshots

![image](https://user-images.githubusercontent.com/20491264/112138557-9c04f980-8c0c-11eb-9bd4-4d9f065c63f1.png)

## System Information

- OS: Windows 10
- Browser: Chrome Version 89.0.4389.90 (Official Build) (64-bit)
- Dark Reader Version: 4.9.29

## Additional context

None.

**Comment by Gusted** [comment]
#4717
