### ISSUE TITLE
 [Feature Request] the extension need a "normally off" button 

### ISSUE THREAD

**Issue by leao-nardo** [darkreader/darkreader#5320]
# Feature Request

## Is your feature request related to a problem? Please describe
the extension when ON only work as a "normally on" switch, that is, it applies to ALL sites unless its marked as off for the site.

## Describe the solution you'd like
its good to have a a "normally off" switch, that is, in this state  it applies ONLY  to sites markeds as ON , and dont change all other sites.

## Additional context
Why i ask that ? because on chrome and edge, the browser is already making the pages dark , so darkreader in making unnecessary duplicate work, so as the normally OFF , it will be on but only for the sites that we chose(sites not being darked by browser itself )

**Comment by AndrewDaGuy** [comment]
Related to #5209:

Hi @leao-nardo, This feature is in dark reader already.

1. Open the dark reader panel
2. Click 
3. Go to the  window
4. You should see a button named  on the right of the  button
5. Click it and it should change to  (You can close the Dev tool window now)
6. Now navigate to  in the dark reader panel
7. On the top you should see a toggle called  (Image included below)
![ScreenShot](https://user-images.githubusercontent.com/66189242/110420176-b4183d00-8092-11eb-84cf-dfd5e8952c67.png)
8. Click on the toggle to switch it off

I'm still pretty sure you can do the same thing in the old design but I have no idea how to do that :/

_Copied and pasted from https://github.com/darkreader/darkreader/issues/5209#issuecomment-793388883 :]_
