### ISSUE TITLE
[Feature Request] Replace with title

### ISSUE THREAD

**Issue by KibSquib48** [darkreader/darkreader#5323]
# Feature Request

## Is your feature request related to a problem? Please describe
I'm using linux and dark reader helps make the web feel more in line with all my other apps by giving it a dark mode with all the same colors my GTK theme has. But the custom HTML form controls are very out of place. I have a setting enabled in Firefox that changes the HTML form controls to match my GTK theme, but with Dark Reader enabled, it uses its own controls instead.

## Describe the solution you'd like
I want an option to remove the custom Dark Reader form controls in favor of my custom GTK ones.

## Additional context
Example of Dark Reader controls:
![Screenshot_20210323_211917](https://user-images.githubusercontent.com/33189136/112239789-8815c380-8c1d-11eb-93ae-400a033b33fc.png)
GTK controls: 
![Screenshot_20210323_212042](https://user-images.githubusercontent.com/33189136/112239862-a7145580-8c1d-11eb-8680-48a43ae2fd1f.png)
GTK looks much nicer, doesn't it?

**Comment by Gusted** [comment]
Hi @KibSquib48!

> GTK looks much nicer, doesn't it?

It indeed does, luckily we have due to that as somehow overriding normal styles messes up other properties e.g. borders. an option to disable this.
Please follow the next steps:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Click on See all Options within the pop-up.
    Click on Fonts & More.
    Disable Style System Controls.

Regards,
Gusted

**Comment by KibSquib48** [comment]
Oh, whoops, I completely missed that option! Thanks for pointing it out, have a good day!

**Comment by KibSquib48** [comment]
apparently I can't close issues from the github mobile app, weird
