### ISSUE TITLE
[Broken Website] Firestore in GCP

### ISSUE THREAD

**Issue by millerg6711** [darkreader/darkreader#5325]
# Broken Website

## Website
https://console.cloud.google.com/firestore

## How to Reproduce
  - Go to GCP
  - Go to Firestore in Navigation Menu
  - Setup Firestore
  - Create Collection
  - Add data to collection
  - See text is dark

## Expected behavior
Text needs to be light color

## Actual behavior
Text is dark color

## Screenshots
![image](https://user-images.githubusercontent.com/34997916/112245916-daf07a80-8c1f-11eb-8e14-688dfb6b868e.png)

## System Information
OS: macOS
Browser: Chrome 89.0.4389.90 (Official Build) (x86_64)
Dark Reader Version: 4.9.29

## Additional context
  - Requires GCP Account
  - Requires GCP Project

**Comment by millerg6711** [comment]
Looks like this is still happening with the data itself.

![image](https://user-images.githubusercontent.com/34997916/112390330-1ba1cf80-8cc4-11eb-8692-084ea428b169.png)

**Comment by Gusted** [comment]
#5329
