### ISSUE TITLE
Some random images at google search appears with inverted colors!

### ISSUE THREAD

**Issue by Alex-Mirov** [darkreader/darkreader#5336]
Hello

This bug appears from version 4.9.27 and up when using dynamic theme
it happens both on windows 10 computer and android device.

I've experienced this bug on different windows computers and android devices.

Thanks

![2](https://user-images.githubusercontent.com/71181695/112686449-02954c00-8e87-11eb-93e5-5022ae6b9a42.jpg)
![1](https://user-images.githubusercontent.com/71181695/112686472-0aed8700-8e87-11eb-99fc-f797f72e9a33.jpg)

**Comment by Gusted** [comment]
```
<!-- 
  ⚠⚠ Do not delete this issue template! ⚠⚠ 
  Issues that do not use the issue template/don't fill out the essential information are likely to be ignored and closed. 
-->
```

**Comment by Alex-Mirov** [comment]
Hello

The comment is unclear, can you tell what does it mean?

Thanks

**Comment by AndrewDaGuy** [comment]
> Hello
> 
> The comment is unclear, can you tell what does it mean?
> 
> Thanks

@Alex-Mirov You should be using the premade template provided ;]
