### ISSUE TITLE
[Feature Request] Preserve already dark sections of content. Example - Google Sheets

### ISSUE THREAD

**Issue by arfyness** [darkreader/darkreader#5338]
# Feature Request

## Is your feature request related to a problem? Please describe

Annoyingly, on a few pages I've come across (for example Google Sheets) a content area with already dark background and light text is inverted back to light mode.  With Dark Reader disabled, the surrounding content is in a light theme, and the dark content remains as dark theme.  When Dark Reader is enabled, the whole UI is dark theme, and the already dark content becomes light theme. Unfortunately I can't remember the other places I've seen this in passing, or I'd include them here. If memory serves, they were all whole areas of content, whether DIV, TABLE, IFRAME or otherwise, I really have no idea.

## Describe the solution you'd like

It would be great if Dark Reader could detect whole areas of content that already have overwhelmingly a dark background and light text.  Then, when that's the case, leave that section alone.

## Additional context

In this example from Google Sheets, the entire sheet is already configured with dark background and light text. Shown below is a progression: disabled, enabled and loading, enabled and loaded, then the ideal: keep the original content colors of the sheet since they're dark already.

 1. Dark Reader Disabled...
![image](https://user-images.githubusercontent.com/5240512/112711518-60359280-8e9f-11eb-9e7c-04a267b4d42f.png)

 2. Dark Reader enabled, page loading, not yet functional...
![image](https://user-images.githubusercontent.com/5240512/112712155-fb306b80-8ea3-11eb-9dcd-36b7601b04a1.png)

 3. Dark Reader enabled, page fully loaded...
![image](https://user-images.githubusercontent.com/5240512/112711536-8ce9aa00-8e9f-11eb-864e-528aded0c183.png)

 4. Ideal View ( # 1 content area overlaid on # 3 UI)
![image](https://user-images.githubusercontent.com/5240512/112711561-af7bc300-8e9f-11eb-88df-89e8561a3b62.png)

I recognize it's a bit of an edge case. But if there is any way to incorporate an option to do some advanced filtering for this type of case, I would absolutely love it.

**Comment by Gusted** [comment]
Hi @arfyness!

This is indeed an type of an edge-case. However due to how google sheets is made up. We apply an general filter over the canvas, which we can't take into factor if it's already dark or not.

Regards,
Gusted
