### ISSUE TITLE
[BUG] Infinite CSS requests from Nest.com

### ISSUE THREAD

**Issue by dltacube** [darkreader/darkreader#5339]
# Bug Report

## Describe the bug
Under certain conditions, websites like nest.com will download png images for infinity.

## Steps to reproduce
Using chrome browser:
  - Install uBlock origin
  - Install Dark Reader
  - Open dev tools inspector, go to the network tab
  - Disable caching
  - Enable Preserve log
  - Go to nest.com
  - Turn on dark mode
  - Make sure viewport is at least 768px wide

## Expected behavior
For assets to be downloaded only once.

## Actual behavior
Assets are downloaded forever, had it go on for about 10gb.

## Screenshots
![image](https://user-images.githubusercontent.com/1683055/112734175-81879480-8f1a-11eb-8eab-c6e354ad1aec.png)

## System Information
- OS: macOS Big Sur 11.2.3
- Browser: Chrome 89 and 91 (canary)
- Dark Reader Version: 4.9.29
- uBlock Origin: 1.34.0

## Additional context
I know that disable caching causes it to re-download the images, but I wonder if the images get re-read and reloaded from cache when it is enabled. Not sure how I would go and check that.

**Comment by Gusted** [comment]
Ublock origin issues. Reproduce-able without Dark Reader.
I suggest to post this issue over at https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by dltacube** [comment]
Strange, I don't see it without dark reader.

Any advice for reproducing it?

**Comment by Gusted** [comment]
Well, I opened my Ungoogled Chromium installation. Side-loaded Ublock Origin(default settings) 1.34.0, traveled to nest.com opened Network tab in dev tools. Did a few refresh and than observed my data being slurped.

**Comment by dltacube** [comment]
Yep, you're absolutely right.

Was able to reproduce it w/ ungoogled chromium but regular chrome/canary required dark reader for some reason.

I'll see if I can sort that out.
