### ISSUE TITLE
Dev tool theme only uses global theme generation mode

### ISSUE THREAD

**Issue by fishstik** [darkreader/darkreader#534]
When using the Dev tools, if the current site has custom settings (using the "Only for \<site\>" feature), the dev tools should be in the custom setting's mode. Currently if the specific site is set to e.g. Filter+ but the global config is set to e.g. Dynamic, and you want to use dev tools for the specific site in Filter+ mode, you must deactivate "Only for <site>" and set the global mode to Filter+.

**Comment by Gusted** [comment]
#2728 Woops missed this issue out.
