### ISSUE TITLE
[BUG] Unable to activate on blog.discord.com

### ISSUE THREAD

**Issue by Kirbyrocket** [darkreader/darkreader#5341]
# Bug Report

## Describe the bug
Dark Reader is unable to activate on blog.discord.com

## Steps to reproduce
  - Go to anywhere on [blog.discord.com](https://blog.discord.com/lets-hear-it-for-the-mods-3aaa2426254b)
  - Activate the extension as if it wasn't inverted
  - See that the colors do not invert

## Expected behavior
The colors should invert once the extension is activated

## Actual behavior
The colors don't invert.

## Screenshots
I'll do you better with [a video](https://streamable.com/idmd6i) instead

## System Information

- OS: Windows 10 Home
- Browser: Microsoft Edge Version 89.0.774.63 (Official build) (64-bit)
- Dark Reader Version: 4.9.29

## Additional context
I haven't tested any other sections of the blog page.

**Comment by AndrewDaGuy** [comment]
Looks like a URL matching issue, and #4291 *should* fix this issue.
