### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#5342]
# Broken Website

## Website
https://linux-hardware.org/?view=computers

## Screenshots
![Screenshot_20210328_002832](https://user-images.githubusercontent.com/6344099/112737724-d8ae5900-8f5c-11eb-8101-b4bef61b9f07.png)

## System Information

- OS:  Linux
- Browser:  Firefox 87
- Dark Reader Version:  4.9.29

## Additional context
Thanks a lot

**Comment by AndrewDaGuy** [comment]
Hi, @ShalokShalom!
I'm going to make a patch for this soon! :]
