### ISSUE TITLE
[Broken Website] All Shopify Stores 

### ISSUE THREAD

**Issue by The-Black-Fox** [darkreader/darkreader#5351]
# Broken Website

## Website

Shopify.com Stores. 
* If needed I can give access to a test store 

## How to Reproduce

  An example of this is:
  - Shopify.com 
  - Sign in 
  - Login to a Shopify Store 
  - *.myshopify.com/admin/
  - None of the pages work with the Dynamic setting. 

## Expected behavior

* When using Dynamic on any website to properly convert to a darkened state 

## Actual behavior

* Dark Reader does not change the sites colors

## Screenshots

<img width="1368" alt="29-21-t75do-u5u7k" src="https://user-images.githubusercontent.com/36429498/112835916-e997c100-9067-11eb-8e23-4182e418cd7f.png">

## System Information

- OS: Mac Windows 
- Browser: Chrome, Safari, Firefox 
- Dark Reader Version:

**Comment by Gusted** [comment]
Hi @The-Black-Fox!

This is most likely due to using extensive variables. Which will be fixed within the next release.
Could you side-load
[build.zip](https://github.com/darkreader/darkreader/files/6221693/build.zip)?
and see if it works then.

Regards,
Gusted

**Comment by The-Black-Fox** [comment]
You are a saintm it works!  😭  
Thank you so much!!! <3 

<img width="1402" alt="29-56-twvfk-j57tp" src="https://user-images.githubusercontent.com/36429498/112839916-b99eec80-906c-11eb-8459-63c5c353ae94.png">

**Comment by Gusted** [comment]
Wait for the next release :)
