### ISSUE TITLE
[Dynamic] Google Drive settings show tick marks where there aren't

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#536]
Using the Dynamic theme engine, Google Drive settings are showing tick marks where there are none. Here's the page with Dynamic:
![image](https://user-images.githubusercontent.com/10074769/40584226-bc9af670-6173-11e8-8ee1-d20eafc0306f.png)

and here's the page without darkreader:
![image](https://user-images.githubusercontent.com/10074769/40584232-c8203834-6173-11e8-8ab5-86084a74347b.png)

Filter+ renders it correctly:
![image](https://user-images.githubusercontent.com/10074769/40584262-4323a3ae-6174-11e8-903d-7b7182467851.png)

I thought Google Drive wasn't allowing me to change the settings since the tick marks didn't change, but it was just the Dynamic theme which always rendered them even though there were none.

I'm running darkreader 601369708c11194706497a1ee82365ff486ef1b7 with nodejs 10.2.1 on Xubuntu 18.04.

**Comment by cyatarow** [comment]
I have the same issue.
