### ISSUE TITLE
[Broken Website] payu.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5378]
# Broken Website

## Website
payu.com

secure.payu.com

## How to Reproduce
Go to
https://secure.payu.com/
https://poland.payu.com/

## Expected behavior
Proper looking.

## Actual behavior

Countries names on map are black.
Payments options in secure.payu.com are white. IMHO can be `REVERT`.

## Screenshots

![20210330-1617101867-001](https://user-images.githubusercontent.com/9846948/112978875-217e3180-9158-11eb-9e8f-fa7bf3af7f3d.png)

![20210330-1617102146-001](https://user-images.githubusercontent.com/9846948/112978915-30fd7a80-9158-11eb-8e79-0288ffb0eaed.png)

## System Information

- OS: Windows 10 X64
- Browser: Chrome Stable X64
- Dark Reader Version: 4.9.29 (from Chrome Store)

## Additional context
See https://poland.payu.com/wp-content/uploads/sites/14/2021/03/PayU-Map_Homepage_World.svg

**Comment by FadeMind** [comment]
@Gusted 

Fixes for map should be available for all subdomains `payu.com`
They are like Paypal - but have subdomains prefixes. 
See
![20210330-1617118075-001](https://user-images.githubusercontent.com/9846948/113014889-4b961a80-917d-11eb-80c9-7985186c4b62.png)

Regards

**Comment by Gusted** [comment]
#5395
