### ISSUE TITLE
Is it possible to add a "Invert everything" option to the addon?

### ISSUE THREAD

**Issue by a2clef** [darkreader/darkreader#538]
I use systemwide color inversion when working(idk if anyone is also doing this). But when browsing certain sites I don't want the color to be inverted, so I think I should find a color inversion addon to re-inverse these site, and I found this great addon. But darkreader will not invert pictures in the page.

**Comment by alexanderby** [comment]
If you want to prevent Dark Reader from working on some websites, click "Toggle" button or add website address into "Site list".

If you want already dark page to become white, this extension is not suitable for that, you can only try to use "Light" mode in "Filter" settings and "Static" mode in "More" settings tab, press "Only for" button to apply this settings to current website only.

**Comment by Fabian42** [comment]
A simple inversion could be a good mode to choose for websites where none of the four current modes (dynamic, filter+, filter, static) work properly. This can already be done for the entire window or screen on most systems, but that has to be done manually and no matter how fast you are, there will always be a short flash of white.
