### ISSUE TITLE
[Broken Website] mojosoft.com.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5381]
# Broken Website

## Website
https://www.mojosoft.com.pl/

## How to Reproduce
Go to https://www.mojosoft.com.pl/

## Expected behavior
Proper dark mode.

## Actual behavior

Mess.

## Screenshots

![20210330-1617104128-001](https://user-images.githubusercontent.com/9846948/112982674-0661f080-915d-11eb-98bd-71aebc68a7bb.png)
![20210330-1617104109-001](https://user-images.githubusercontent.com/9846948/112982676-06fa8700-915d-11eb-93da-201cc9ee1ae2.png)
![20210330-1617104086-001](https://user-images.githubusercontent.com/9846948/112982677-06fa8700-915d-11eb-9fd3-fdb45f9e46df.png)

## System Information

- OS: Windows 10 X64
- Browser: Chrome Stable X64
- Dark Reader Version: 4.9.29 (from Chrome Store)

**Comment by FadeMind** [comment]
@Gusted 

You made typo in domain.
Regards 
line 6380 (or near)

INVALID `mojosoft.com`
CORRECT `mojosoft.com.pl`

Even after fix typo after scroll page is bad:
![20210330-1617119645-001](https://user-images.githubusercontent.com/9846948/113018575-fa882580-9180-11eb-9f31-62179dd85457.png)

Better in Filter+ but cannot handle header at all.

![20210330-1617119784-001](https://user-images.githubusercontent.com/9846948/113018864-433fde80-9181-11eb-8938-59079e38372d.png)
![20210330-1617119759-001](https://user-images.githubusercontent.com/9846948/113018866-43d87500-9181-11eb-8962-50d19ea73ae4.png)
![20210330-1617119750-001](https://user-images.githubusercontent.com/9846948/113018867-44710b80-9181-11eb-9674-1cb9b445724d.png)
![20210330-1617119645-001](https://user-images.githubusercontent.com/9846948/113018869-44710b80-9181-11eb-9443-e4b130381685.png)

**Comment by Gusted** [comment]
#5397
