### ISSUE TITLE
[Broken Website] sergeistrelec.ru

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5386]
# Broken Website

## Website
https://sergeistrelec.ru

## How to Reproduce
Go to https://sergeistrelec.ru

## Expected behavior
Proper look.

## Actual behavior
Mess

## Screenshots

![20210330-1617114883-001](https://user-images.githubusercontent.com/9846948/113006724-e68af680-9175-11eb-8d90-0371e64d6206.png)
![20210330-1617114871-001](https://user-images.githubusercontent.com/9846948/113006728-e7bc2380-9175-11eb-87bc-dfc04737a823.png)

## System Information

- OS: Windows 10 X64
- Browser: Chrome Stable X64
- Dark Reader Version: 4.9.29 (from Chrome Store)

## `Filter+` looking fine except revert some images too. 
![20210330-1617115026-001](https://user-images.githubusercontent.com/9846948/113007083-31a50980-9176-11eb-8bdc-0ed72d2c90a8.png)
![20210330-1617115013-001](https://user-images.githubusercontent.com/9846948/113007087-323da000-9176-11eb-866b-b3f9a68b0549.png)

**Comment by Gusted** [comment]
Too much images to even begin an fix for this site.
Filter+ recommended.
