### ISSUE TITLE
I have an request. I also hope to support Mozilla Thunderbird, SeaMonkey.

### ISSUE THREAD

**Issue by Shitennouji** [darkreader/darkreader#539]
I have an request.
I also hope to support Mozilla Thunderbird, SeaMonkey (v2.49. *).

**Comment by risualiser** [comment]
In Thunderbird you can use [TT DeepDark](https://addons.mozilla.org/en-us/thunderbird/addon/tt-deepdark/).

**Comment by Shitennouji** [comment]
I already implemented "TT DeepDark" about Thunderbird. However, it will soon become a WebExtension specification, it is the fate that makes "TT DeepDark" unusable. It was a request for that.
However, due to the For dark interface (not page style), it is impossible. OK.
On the other hand, is SeaMonkey (v2.49. *) Possible?
Best regard,

**Comment by Shitennouji** [comment]
Dear @risualiser,

I’m sorry to trouble you.
Certainly, TT DeepDark seems to be able to continue using it in the future.
I seem to have misunderstood.

The contribution of GitHub
<https://github.com/darkreader/darkreader/issues/539#issuecomment-392746898>,
was corrected.

Best regard,
四天王寺 Shitennouji

**Comment by Shitennouji** [comment]
I appreciate your polite reply.
Thanks to you, I understood the circumstances.
Thank you very much.

**Comment by olee** [comment]
Hey, could this issue maybe be reopened for Thunderbird support?
Right now I'm using Dark Reader for Chrome and would like to use it in Thunderbird as well.
I think it should not be too difficult as Mozilla updated Thunderbird 60+ especially for that.
Right now not having a good dark-reader-like addon for Thunderbird 60+ makes me continue using the older versions around 52

**Comment by ByJumperX4** [comment]
I would be happy to see dark reader on seamonkey as it is my main browser.
I'm currently trying to find an old release of dark reader that works on seamonkey
You could do like how uBlock Origin does : they do a firefox-legacy branch for browsers based on old firefox (Basilisk, IceWeasel-UXP, Waterfox, SeaMonkey, ...)

**Comment by Gusted** [comment]
> I would be happy to see dark reader on seamonkey as it is my main browser.
> I'm currently trying to find an old release of dark reader that works on seamonkey
> You could do like how uBlock Origin does : they do a firefox-legacy branch for browsers based on old firefox (Basilisk, IceWeasel-UXP, Waterfox, SeaMonkey, ...)

Please open up a new issue for this so it can be tracked and discussed.
