### ISSUE TITLE
[Dynamic] Scrollbars in gmail are virtually invisible

### ISSUE THREAD

**Issue by Elliott-M** [darkreader/darkreader#541]
![image](https://user-images.githubusercontent.com/1437327/40682993-d31ed1ce-6352-11e8-8600-ce1835fd2393.png)

**Comment by darkfeline** [comment]
I find that this is true on almost all pages.  Maxing the brightness slider makes the scrollbar more visible (but the page text too bright).  Maybe the base scrollbar brightness needs to be higher?

**Comment by Fabian42** [comment]
The same definitely also happens with the regular scroll bar of Chrome and the scrollbar in long Google Keep notes (even though it looks different without Dark Reader).

**Comment by Gusted** [comment]
Made a fix for this issue #2269

**Comment by PradeepSinghMakwana** [comment]
We just want to identify where the scrollbar is....A white border surrounding scrollbar is enough, no need to mess around with background, brightness or other things. Making the scrollbar filled with some color is not going to be way around. Please.
