### ISSUE TITLE
[Performance] Slow rendering times (confirmed on firefox)

### ISSUE THREAD

**Issue by haug1** [darkreader/darkreader#5410]
# Performance Issue

## Website

Domain:
https://www.flashscore.com/
Sample:
https://www.flashscore.com/match/WhMfKG50/#match-summary

## How to Reproduce

Method 1 (most significant):
- Go to Domain 
- Click any match 
- A new 'reduced' window with the match information should pop up

Method 2 (less significant):
- Go to Sample URL

The spinner animation will have significant longer render time with Dark Reader enabled as compared to Dark Reader disabled.

## Performance Profiler

If you can't reproduce I can try to get some profiling data, but it should be very noticeable and reproducible for you so cba..

## Tested on

- OS: Windows/Linux
- Browser: Firefox 87 and probably prior
- Dark Reader Version: 4.9.29 and probably prior

I have tested with other extensions disabled and on multiple Linux/Windows systems, but other browsers are untested by me.

## Extra

I experience that the performance issue is much worse when you click the match from the main page rather than going directly to the Sample URL, though it is noticeable either way. Their seems to be some especially heavy work going on when it opens in a new 'reduced' firefox window.

**Comment by haug1** [comment]
I briefly tried to do some debugging, but I quickly notice that I will not continue beyond this. Seems like the website is loading a lot of unnecessary images and DarkReader probably processing all of them in addition to whatever else it does. 

Seems like this application is doing a lot of work beyond my wishes of usually getting a dark ish web site at zero cost. It pretty much always works though, kudos to the devs for that, but yeah after a closer look it's a little too much for me personally. I need something that consistently and instantly works or does not work and works independantly of the web site's returned size, content or runtime behavior. In summary I'd rather have an instant white page than a 2-seconds-to-load dark page.

Why isn't black the default everywhere, curse you inventor of the web!

**Comment by Gusted** [comment]
Hi @haug1!

I've tried to reproduce it and I only find a small overhead from Dark reader in contrast to whats flash score is loading and doing some insane GPU-Intensive tasks.

If you find it the overhead too much I'd recommend using Filter for this site to remove the overhead of Dark Reader.

> I need something that consistently and instantly works or does not work and works independantly of the web site's returned size

The web site's size doesn't mater within Dark Reader.

> In summary I'd rather have an instant white page than a 2-seconds-to-load dark page.

It's the site's decision to have such spinner and having an loading mechanism(to reduce load).

> curse you inventor of the web!

This sentence isn't in line with our [code of conduct](https://github.com/darkreader/darkreader/blob/master/CODE_OF_CONDUCT.md#our-standards). Please refrain from saying such things.

Regards,
Gusted

**Comment by dx-pbuckley** [comment]
There's definitely something different in firefox on osx (big sur) that has gotten way, way slower with dark reader within the past couple weeks. Webpages that used to be fine (github.com, okta.com) now take at least a minute to load (more like 2-3 min for okta, a visible few seconds per image tile), and ffox frequently complains that dark reader is the extension taking a long time to run. Any recommendations for how to troubleshoot or isolate this, or to make dark reader work better with whatever has changed out from under it?

**Comment by haug1** [comment]
> It's the site's decision to have such spinner and having an loading mechanism(to reduce load).

I don't understand this response. If you consider it a problem with the web site and not Dark Reader, that is sad to hear. It means that you think web sites should optimize for compatibility with Dark Reader and not the other way around. That sounds very unrealistic. 

The issue remains on my end: consistently <.5 secs load time without Dark Reader, ~2 secs load time with Dark Reader.
Thanks for your suggestion to add a blacklist rule for this specific page, but the issue for me is that it could still happen on any other web site with similar implementation and for me that is feasible. I have enough extensions to manage already and so I would rather remove Dark Reader.

Because you seem offended, let me clarify that I'm not trying to belittle your work or demand a fix if you think there is no need for one, I'm simply being straight-forward about this issue and how it impacts me. 

Let me know if you are looking to fix and you think I can provide more information.

**Comment by haug1** [comment]
Also, please, I understand that the web site is doing sub-optimal things, but that is to be expected from random web sites. I expect my extensions to not slow down my system because of a badly implemented web site.

**Comment by Gusted** [comment]
> It means that you think web sites should optimize for compatibility with Dark Reader and not the other way around. That sounds very unrealistic.

I never meant that nor think that way. It's just such loading mechanism aren't reliable. Dark Reader due to java script nature is one-threaded. Meaning while dark reader does something the site cannot do anything and thus e.g. removing such spinner. Thereby the amount of overhead in scripts comparison to Dark Reader on this site is just not it.
