### ISSUE TITLE
[Feature Request] Extension icon dark/light when dark mode for current page on/off

### ISSUE THREAD

**Issue by vikrend** [darkreader/darkreader#5419]
# Feature Request
Current behavior is when the extension is ON, the extension icon is dark. It would be better if it was dark when dark mode for current page is ON.

## Describe the solution you'd like

Change behavior from "extension on/off -> extension icon dark/light" to "dark mode for page on/off -> icon dark/light"

**Comment by Gusted** [comment]
dup #1671
