### ISSUE TITLE
[Broken Website] Tutanota 2FA QR Code doesn't appear properly

### ISSUE THREAD

**Issue by gdnzz** [darkreader/darkreader#5420]
## Website
mail.tutanota.com

## How to Reproduce
Go to settings in the Tutanota account and try to add 2FA.

## Expected behavior
A proper QR code supposed to show up.

## Actual behavior
It shows a white square without any black lines when dark reader extension is enabled.

## System Information
Firefox 87 
Windows 10 64 bit
Dark reader version 4.9.29

**Comment by Gusted** [comment]
For legal reason I cannot make such account and don't have the appropriate information to create an fix.
