### ISSUE TITLE
[BUG] "Use system color scheme" works on Firefox Linux, but not on Chrome Linux

### ISSUE THREAD

**Issue by OmeCor** [darkreader/darkreader#5430]
# Bug Report

## Describe the bug
When using the setting "Use system color scheme" in Google Chrome, dark mode is not enabled in Chrome when a dark color scheme is enabled on the system. In Firefox dark mode IS enabled.

## Steps to reproduce
- Enable the setting "Use system color scheme" in Dark Reader Google Chrome
- Enable the setting "Use system color scheme" in Dark Reader Firefox
- Enable theme Adapta-Cyan-Nokto (a dark color scheme) in Linux
- In Firefox dark mode is enabled
- In Google Chrome dark mode is NOT enabled, i.e. Dark Reader in Google Chrome does not change 
- Enable theme Adapta (a light color scheme) in Linux
- In Firefox dark mode is disabled
- In Google Chrome no change

## Expected behavior
With the setting "Use system color scheme", Dark Reader in Google Chrome should change the light filter to dark if the system color scheme is changed to dark

## Actual behavior
Notwithstanding the setting "Use system color scheme", Dark Reader in Google Chrome does NOT change the light filter to dark if the system color scheme is changed to dark

## System Information
- OS: Linux Mint 19.3 Cinnamon. All updates installed.
- Kernel: 5.4.0-70-generic
- Dark Reader version 4.9.16 in Google Chrome Version 89.0.4389.90 (Official Build) (64-bit).
- Dark Reader version 4.9.16 in Firefox 87.0 (64-bit)

**Comment by Gusted** [comment]
Dup #2722
