### ISSUE TITLE
Nextcloud Tasks broken

### ISSUE THREAD

**Issue by fredddd1** [darkreader/darkreader#5436]
# Broken Website

## Website
Any Nextcloud Tasks provider. An example would be woelkli.com.

## How to Reproduce

- Load the Tasks page
 
## Expected behavior
For all tasks to load and to remain connected to the server.

## Actual behavior
Things load only half way and then a "Connection to server lost" message appears and the browser console is filled with errors that otherwise would not be there.

## Screenshots (gif does not loop, refresh to restart)
![nextcloud-tasks-dark-reader-connection-to-server-lost-issue](https://user-images.githubusercontent.com/80743272/113425206-c0fa2900-93d1-11eb-9873-e1778f954d7c.gif)

## System Information

- OS: Windows 64-bit Version 20H2 (OS Build 19042.906)
- Browser: Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.30

**Comment by fredddd1** [comment]
@Gusted I have e-mailed you Nextcloud credentials for you to test this behaviour.

**Comment by Gusted** [comment]
I got it once reproduced but after that it seems to be working fine and go a bunch of error messages in my face with it.

**Comment by fredddd1** [comment]
> I got it once reproduced but after that it seems to be working fine and go a bunch of error messages in my face with it.

I added some more tasks, usually it does this with a lot of tasks.

**Comment by Gusted** [comment]
> I added some more tasks, usually it does this with a lot of tasks.

Ah yes that did it! I got the source of problem of the thousand of errors that we were generating and properly give the server a little bit of a hard time(notice the amount of HTTP2 protocol errors). And with that the problem seems to be solved.
