### ISSUE TITLE
Email Contact field on hootsuite

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#544]
It may be required to click on next, if the chat window appears on the bottom left:
![screenshot_20180603_121142](https://user-images.githubusercontent.com/6344099/40885843-751bdc40-672e-11e8-89b7-dc2d4961ddb6.png)

Idk when it triggers which kind of input field, it seems random. 
Click on `Get Support Now'
https://hootsuite.com/de/about/contact-us#

**Comment by Gusted** [comment]
Fix has been make #2329
