### ISSUE TITLE
Got Dark Mode for mongodb compass with darkreader

### ISSUE THREAD

**Issue by Chidhambararajan** [darkreader/darkreader#5442]
MongoDB compass didn't officially have a darkmode, so I unpacked the app.asar of the electron app ,
added darkreader.js to it , viola got the darkmode

Darkmode for any electron app is just a few clicks away , thanks for the amazing app

![image](https://user-images.githubusercontent.com/26043350/113470059-46341b00-9470-11eb-8ddd-60c095b88ff1.png)

Just wanted to say thanks for making the awesome project and opensourcing it!!

**Comment by majkeldream** [comment]
Boisz się ?😂😉
