### ISSUE TITLE
QR Code on WhatsApp

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#545]
Currently, the QR Reader here is unavailable with DarkReader: 
https://web.whatsapp.com/

**Comment by ShalokShalom** [comment]
The theme itself seems also improvable: 

![screenshot_20180603_143711](https://user-images.githubusercontent.com/6344099/40886621-cefa1300-673b-11e8-8b7e-5420f76bbedf.png)

**Comment by baitarakhov** [comment]
same problem

**Comment by BlackDex** [comment]
It seems WhatsApp have made some changes since this is broken again.

**Comment by xmha97** [comment]
same problem

**Comment by Gusted** [comment]
#2748 @xmha97 You don't need to go to multiple issues to reply `same problem`

**Comment by Gusted** [comment]
Next release it will be fix for good and not rely on classes.

**Comment by xmha97** [comment]
> 
> 
> Next release it will be fix for good and not rely on classes.

Thanks and sorry for that.
