### ISSUE TITLE
[Broken Website] github labels

### ISSUE THREAD

**Issue by AndrewDaGuy** [darkreader/darkreader#5450]
# Broken Website

## Website

https://github.com/

## How to Reproduce

- Go to any repository 
- Go to issues
- When DR is on, the colours disappear 

## Expected behaviour

Label colours should not be affected

## Actual behaviour

Colours are affected

## Screenshots

DR enabled:
![image](https://user-images.githubusercontent.com/66189242/113496519-01e56100-94ea-11eb-821c-a0ae2cc975db.png)

DR disabled: 
![image](https://user-images.githubusercontent.com/66189242/113496536-26d9d400-94ea-11eb-9865-d99764774acf.png)

## System Information

- OS: macOS Catalina `10.15.7` (`19H2`) 
- Browser: Firefox `87.0` 
- Dark Reader Version: `4.9.30`

**Comment by Gusted** [comment]
https://github.com/settings/appearance -> Set it to permanent light. Dark Reader(Like me) doesn't likes github's colors.
