### ISSUE TITLE
[Feature Request] Replace with title

### ISSUE THREAD

**Issue by endorphin-pk** [darkreader/darkreader#5464]
# Feature Request

## Is your feature request related to a problem? Please describe

I tried to move this extension's dark mode exception setting to another browser, but it failed because there was no export function and there were too many to do it manually.

## Describe the solution you'd like
I hope I can export and recall the excluded sites list.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/615#issuecomment-730496304
