### ISSUE TITLE
Default toggle shortcut unusable on Firefox 60

### ISSUE THREAD

**Issue by Lesik** [darkreader/darkreader#548]
The default toggle shortcut of Dark Reader, `Alt + Shift + D`, doesn't seem to work for me in Firefox 60. Instead of being passed to the extension, it opens the application menu:

![](https://user-images.githubusercontent.com/2021487/41106278-04945714-6a70-11e8-91aa-e63c782e29dd.png)
![](https://user-images.githubusercontent.com/2021487/41106394-3fd5aefe-6a70-11e8-9405-d024c1fa5ae0.png)

**Comment by shanecp** [comment]
Had the same issue on a Mac. Solution was to go to `about:addons` and update the extension shortcut manually. 
Windows and Mac keys seems to be recognized separately.

**Comment by Lesik** [comment]
I am now on `68.9.0esr` and it is working as expected. Can somebody else test their version?

**Comment by Gusted** [comment]
You can change the shortcut if you want to.

**Comment by Lesik** [comment]
@Gusted: This issue isn't about wanting to change the shortcut, it's about broken defaults. Please reopen.

**Comment by Gusted** [comment]
You that's why I say you just can change it to something else. Now changing default will make people confused and asking why it's not more working.

**Comment by Lesik** [comment]
I'm not suggesting changing the default. I'm wondering why the default seems to be broken for some users but not others.

**Comment by Lesik** [comment]
I am now on `68.9.0esr` and it is working, though I have the suspicion this might be unrelated to the Firefox version but rather to the locale. Since the "File" menu is called "**D**atei" in German, `Alt+D` opens that menu. @shanecp could you confirm that your system language is German or another language where the translation of the word "File" starts with a "D"?

**Comment by Gusted** [comment]
Thst could explain why some users have or have not the problem because of their language.

**Comment by shanecp** [comment]
I'm on Firefox 78.0.2, Mac Catalina

The language is Australian English, locale Australia.

Seems the original issue was a conflict with Amethyst on Mac (https://github.com/ianyh/Amethyst)

However Ctrl+Shift+D is not recognised correctly on Macs. (See screenshot)

If I press Ctrl+Shift+D when setting shortcut, it accepts it, but the shortcut doesn't work.
If I go to Firefox settings, I can see it's set to Cmd+Shift+D

If I set Ctrl+Shift+D from Firefox settings, the new setting is shown on extension as MacCtrl+Shift+D. And it works.
![46](https://user-images.githubusercontent.com/1654017/87869979-6bb6ec80-c9e7-11ea-8450-29a05fc92b80.png)

Looks like there's an issue with recognising Ctrl/Command keys correctly.

**Comment by sahmadraza** [comment]
I am having the same problem on Ubuntu 20.04 with Firefox 78.0.2. My default language is en-us.

**Comment by Gusted** [comment]
@samtimalsina does it something instead?

**Comment by sahmadraza** [comment]
For me, it does not do anything.

**Comment by Gusted** [comment]
Could you try changing it to another shortcut without ctrl + Shift might something to due wiwjt your keyboard and Linux drivers.

**Comment by sahmadraza** [comment]
I am using a standard Qwerty keyboard and do not have any proprietary drivers in Linux. Of course I can change the shortcut to something else. But the default settings of the extension do not work.

**Comment by Gusted** [comment]
Changing defaults to another one should be a challenge to get enough main users have it working of course, like this issue their will be situation where it will be broken and for that you can change it to another shortcut.

**Comment by lowzyyy** [comment]
Shortcuts just stopped working and it were working couple of days ago ff 106

**Comment by bershanskiy** [comment]
To @lowzyyy who wrote:
> Shortcuts just stopped working and it were working couple of days ago on ff 106

This is a separate issue which should be fixed in recently released Dark Reader 4.9.60. That shortcut issue is tracked as #10176 and was fixed by #10186.

**Comment by lowzyyy** [comment]
> To @lowzyyy who wrote:
> 
> > Shortcuts just stopped working and it were working couple of days ago on ff 106
> 
> This is a separate issue which should be fixed in recently released [Dark Reader 4.9.60](https://github.com/darkreader/darkreader/releases/tag/v4.9.60). That shortcut issue is tracked as #10176 and was fixed by #10186.

Thank you for fast response !!!

**Comment by bershanskiy** [comment]
> > To @lowzyyy who wrote:
> > > Shortcuts just stopped working and it were working couple of days ago on ff 106
> > 
> > 
> > This is a separate issue which should be fixed in recently released [Dark Reader 4.9.60](https://github.com/darkreader/darkreader/releases/tag/v4.9.60). That shortcut issue is tracked as #10176 and was fixed by #10186.
> 
> Thank you for fast response !!! Do you know when will be pushed to firefox addon "store" ?

As of writing, I see Dark Reader 4.9.60 already online on the Firefox Addons. If you have 4.9.59 installed on your Firefox profile, you might want to manually trigger update: go to `about:addons`, open "Extensions" section, click on "Cog" icon and then "Check for Updates". I hope this helps!

**Comment by lowzyyy** [comment]
Great, working as expected! 👍😎
