### ISSUE TITLE
[Broken Website] tokfm.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5483]
# Broken Website

## Website
https://www.tokfm.pl/Tokfm/0,0.html

## How to Reproduce
Open https://www.tokfm.pl/Tokfm/0,0.html and scroll all page to see.

## Expected behavior
Proper looking in dark. 

## Actual behavior
Mess

## Screenshots
![20210406-1617689950-001](https://user-images.githubusercontent.com/9846948/113667402-0e67e600-96b1-11eb-9153-dc23d0afd353.png)
![20210406-1617689966-001](https://user-images.githubusercontent.com/9846948/113667398-0dcf4f80-96b1-11eb-989a-407b5935caad.png)
![20210406-1617689984-001](https://user-images.githubusercontent.com/9846948/113667396-0dcf4f80-96b1-11eb-8aef-317b49f18e7a.png)
![20210406-1617689997-001](https://user-images.githubusercontent.com/9846948/113667395-0c9e2280-96b1-11eb-9094-a1c40a8a6d73.png)

**Comment by FadeMind** [comment]
@Gusted 
Small fix for tokfm.pl 
```
INVERT
span[class="play"]
```
AFTER FIX

![20210406-1617735959-001](https://user-images.githubusercontent.com/9846948/113765050-114bf080-971c-11eb-946f-1ae0be3cad83.png)

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/commit/b86cdea179bf856bb9df87722e4d4b20f66353ea
