### ISSUE TITLE
[Broken Website] instagram.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5488]
https://www.instagram.com/p/CNUjNVJslFT/

![20210406-1617707895-001](https://user-images.githubusercontent.com/9846948/113703081-a29a7300-96da-11eb-901a-052d4ca4cd54.png)

Why profile names links have BORDER?

**Comment by Gusted** [comment]
> Why profile names links have BORDER?

Because it's broken. 🤷🏽. Bugs happen.

**Comment by FadeMind** [comment]
@Gusted In front page still exists. Random name.
https://www.instagram.com/
![20210406-1617709178-001](https://user-images.githubusercontent.com/9846948/113705385-a7145b00-96dd-11eb-9cd1-b003545f11dd.png)

**Comment by Gusted** [comment]
> @Gusted after applying fixes from lastest config still exists. Random name.
> https://www.instagram.com/
> ![20210406-1617709178-001](https://user-images.githubusercontent.com/9846948/113705385-a7145b00-96dd-11eb-9cd1-b003545f11dd.png)

Don't have an account so I cannot fix this one.

**Comment by FadeMind** [comment]
What do you need for investigate?

**Comment by Gusted** [comment]
> What do you need for investigate?

Within the dev tools(ctrl + shift + i), select the name and something like this:
![image](https://user-images.githubusercontent.com/25481501/113706070-8ac4ee00-96de-11eb-95be-907c0fea0ddc.png)

Should be used. I need a brief screenshot of the elements

**Comment by FadeMind** [comment]
![20210406-1617711420-001](https://user-images.githubusercontent.com/9846948/113709494-d6799680-96e2-11eb-93c2-9fcd144d7a69.png)
![20210406-1617711403-001](https://user-images.githubusercontent.com/9846948/113709498-d7aac380-96e2-11eb-9a06-fc8fb22231b1.png)
![20210406-1617711387-001](https://user-images.githubusercontent.com/9846948/113709499-d7aac380-96e2-11eb-9b12-651435707ab9.png)
![20210406-1617711374-001](https://user-images.githubusercontent.com/9846948/113709500-d8435a00-96e2-11eb-931b-a40395b98633.png)
![20210406-1617711224-001](https://user-images.githubusercontent.com/9846948/113709501-d8435a00-96e2-11eb-938a-0aaf98f7f5a8.png)
![20210406-1617711211-001](https://user-images.githubusercontent.com/9846948/113709504-d8dbf080-96e2-11eb-85dd-232b12b6209a.png)

**Comment by Gusted** [comment]
#5492 5492
