### ISSUE TITLE
Reset to default missing (Chrome)?

### ISSUE THREAD

**Issue by nopynoop** [darkreader/darkreader#550]
I was playing with some parameters then I wanted to reset back to the default and I couldn't find it. 

I ended up removing and adding back the addon.

I am sorry if I missed it.

**Comment by Noexpert** [comment]
Same issue for Firefox.

**Comment by orschiro** [comment]
I believe this can be closed in favour of https://github.com/darkreader/darkreader/issues/550.

**Comment by alexanderby** [comment]
@orschiro I think you added a link to the same issue.

This is planned to add, but this script should also work:
```javascript
chrome.storage.sync.clear(() => chrome.runtime.reload());
```

**Comment by orschiro** [comment]
@alexanderby thanks, already fixed! :-)

> This is planned to add, but this script should also work:

Wow, that's great, much appreciated!

Would removing and reinstalling the extension also reset it?

**Comment by alexanderby** [comment]
@orschiro Reinstallation resets settings only for Chrome.
