### ISSUE TITLE
[Performance] Memory leak

### ISSUE THREAD

**Issue by leonard-vlaicu** [darkreader/darkreader#5502]
# Performance Issue

## Website
https://azure.microsoft.com/en-us/services/

## How to Reproduce
  I have 8GB of RAM. When I tested this, only 50% was in use.
  Dark Reader is ON.
  After entering the site, the RAM is continously getting eaten until to 98-99% in use.
  
## System Information
- OS: Windows
- Browser: Firefox 87
- Dark Reader Version: 4.9.31

- Do you have this performance issue with Dark Reader disabled? No
- Does it happen in other browsers? Haven't tested
- Do you have hardware acceleration enabled? Yes

![Screenshot (2)](https://user-images.githubusercontent.com/56519529/113855896-3c305600-97a9-11eb-929c-b96b7c85d52a.png)
![Screenshot (4)](https://user-images.githubusercontent.com/56519529/113855888-3aff2900-97a9-11eb-9578-848beefcd43c.png)

**Comment by ikenna8317** [comment]
Same with me. No matter the browser Dark reader consumes too much system resources. I had to uninstall the extension.

**Comment by Zerossoul** [comment]
I am noticing this on Safari as well. It's sad because I love how fast Safari is in big sur over Chrome, but there are no other dark mode extensions that work well in Safari. Props to Dark Reader for atleast having it.

**Comment by jersten** [comment]
I'm also having this issue. I'm using LibreWolf, a modified version of firefox aimed at being much more secure. This extension causes my computer to freeze up for about 7 minutes at a time, and I have 16Gb of RAM which should be more than enough. I'd say this needs to be fixed asap. I had to uninstall Darkreader.

**Comment by Gusted** [comment]
@alexanderby Do we by any chance store images within the content script? I know the background-script has a cache for fetched elements. But the numbers shows that we are somehow holding onto big images that seems to be coming from the urlToImage function and GC ain't cleaning it up.

**Comment by alexanderby** [comment]
There's `URL.createObjectURL`. For inverting the images they are put into SVG with a filter. I think data URLs are used because image URLs don't work in Blob URLs as far as I remember.

**Comment by Gusted** [comment]
Hmm, yeah. Pretty weird, might get a minimal case and send it as a bug report if it's confirmed that the GC isn't cleaning up as their was around 2gb of data: url's within the memory and the analyzeImage function was being pretty heavy.

**Comment by alexanderby** [comment]
It's not a bug, these images are cleared with URL.revokeObjectURL but there's no way to detect if it's needed. So, if placing usual URLs instead of Data URLs is not possible (to reduce string size), we could add some counter to stop collecting these object URLs when some threshold is reached. Basic latin string size in bytes is usually equal to string length.

**Comment by Gusted** [comment]
Aha I see. You seems to be more knowledge-able about this part 😄
