### ISSUE TITLE
[Broken Website] FIX forum.eset.com AND forums.laptopvideo2go.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5503]
@Gusted 
I don't know how DarkReader handle order different names domains for SAME RULES. 
FORUM CSS FIXED.  They using SAME CSS/CMS

DOMAINS
```
forum.eset.com
forums.laptopvideo2go.com
```
FIX CODE
```
INVERT
.ipsReact_button

CSS
.ipsBadge {
    --darkreader-bg--badge--background: var(--darkreader-neutral-background) !important;
}
.ipsReact_reactCount > a, 
.ipsReact_reactCount > span {
    background-color: var(--darkreader-neutral-background) !important;
}
.elFullInbox_menu, .ipsMenu_auto, .ipsPadding, .ipsList_reset, .ipsMenu_headerBar, .ipsMenu_innerContent, .ipsMenu_footerBar, .ipsMenu_title, .ipsMenu_item, .ipsMenu_sep {
background-color: var(--darkreader-neutral-background) !important;
}
```

RESULTS
![20210407-1617795358-001](https://user-images.githubusercontent.com/9846948/113860365-3be28b80-97a6-11eb-9834-71c70f58e7b2.png)
![20210407-1617795342-001](https://user-images.githubusercontent.com/9846948/113860368-3d13b880-97a6-11eb-9759-789ce4c5527a.png)
![20210407-1617795265-001](https://user-images.githubusercontent.com/9846948/113860369-3d13b880-97a6-11eb-8809-485c19f9b7c2.png)

**Comment by Gusted** [comment]
Please refrain from using capslocks and if you have a fix you can create a PR yourself at [the file](https://github.com/darkreader/darkreader/edit/master/src/config/dynamic-theme-fixes.config). It's getting time consuming.
