### ISSUE TITLE
[Feature Request] Allow custom css to exclude icons font css classes if font is changed (or other workaround)

### ISSUE THREAD

**Issue by giddev** [darkreader/darkreader#5505]
# Feature Request

## Is your feature request related to a problem? Please describe
If the font is changed in darkreader then on some sites font icons like font awesome and glyphicons display as squares since they are overwritten by the changed font

## Describe the solution you'd like
I would like to customize the font override by adding additional css class exclusions

Currently when changing the darkreader font e.g. to Montserrat , darkreader inserts the following css into all sites in the html header

````
<style class="darkreader darkreader--text" media="screen">*:not(pre) {
  font-family: Montserrat !important
 }</style>
````
I would like to add my own css classes to exclude so it looks like 

````
<style class="darkreader darkreader--text" media="screen">*:not(pre,.far,.fa, .glyphicon) {
  font-family: Montserrat !important
 }</style>
````
e.g.`.fa,.far` css classes belongs to font awesome font and `.glyphicon` css class belong to glypicon font

## Additional context
This is just two font icons on sites I found. There might be others in the future, hence the reason I think custom css is probably the easiest solution rather than hardcoding it in.

**Comment by Gusted** [comment]
> This is just two font icons on sites I found. 

For now they can be hard coded.

> There might be others in the future, hence the reason I think custom css is probably the easiest solution rather than hardcoding it in.

I'm not sure, as this kind of things I prefer calling "Advanced settings", as it requires some knowledge about CSS which probably a lot of Users don't know and having such option could be _confusing_ why it's there and how you use it and which use case it for.

Regards,
Gusted

**Comment by giddev** [comment]
You could put it in Dev Tools as there is already a DYNAMIC THEME EDITOR there where you allow users to edit.


Another one:

https://docs.microsoft.com/
https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli

Icon class is `docon` which is what microsoft docs uses
