### ISSUE TITLE
[Broken Website] developer.android.com

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#5507]
# Broken Website

## Website
https://developer.android.com/ndk/guides/cpp-support

## How to Reproduce

Go to https://developer.android.com/ndk/guides/cpp-support

## Screenshots

![sshot-008](https://user-images.githubusercontent.com/36977733/113980318-d938d080-9835-11eb-9acc-4b4f6ed8e128.png)

## System Information

- OS: Win10
- Browser: Firefox 87
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/commit/55d3a13cb6fb0785e6e3e7f4e199045c79bd8d95

**Comment by linsui** [comment]
Thanks!
