### ISSUE TITLE
Is it possible to set different generation theme modes for different sites?

### ISSUE THREAD

**Issue by Alkasul** [darkreader/darkreader#551]
Just like how you can set custom filters for different sites, I'd like an option for generation theme modes since I use some sites which looks better with filter/filter +.

**Comment by alexanderby** [comment]
Sure, if you are using Chrome, you will see "Only for" button under "More" tab. If you are using Firefox, click "Only for" button at "Filter" tab. There was not enough space for this button in Firefox, as far as there is already a browser theme toggle button.
![image](https://user-images.githubusercontent.com/9638588/41308643-341ce406-6e85-11e8-868f-b33b6764f0ab.png)
