### ISSUE TITLE
[Broken Website] HackerNews code blocks are unreadable (white text on white background)

### ISSUE THREAD

**Issue by glenneroo** [darkreader/darkreader#5512]
# Broken Website

## Website
https://news.ycombinator.com

## How to Reproduce
Open comments section which contains code blocks e.g. this article:
https://news.ycombinator.com/item?id=26731305

Here is a link to one comment with a code block:
https://news.ycombinator.com/item?id=26744531

Notice how the text in the code block is unreadable - white text on white background.

## Expected behavior
Text should be inverse color of code block. Code blocks are white, therefore text should probably be dark.

## Actual behavior
Text is white on white background.

## Screenshots
[Example comment with a code block](https://i.imgur.com/rXrQ4B8.png)

## System Information
- OS: Windows 10 Pro build 19042.867
- Browser: Firefox 87.0
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
Hi @glenneroo!

I don't see this issue nor really think of a way how so. 
As the code block doesn't get anything special other than the font.
Could you please share a screenshot of the devtools(ctrl + shift + i) with the the code block selected, as seen in this screenshot:
![image](https://user-images.githubusercontent.com/25481501/114147518-10cc7900-9919-11eb-829a-0b0ad1a6227c.png)

Regards,
Gusted

**Comment by glenneroo** [comment]
![2021-04-09 16_39_27-Settings](https://user-images.githubusercontent.com/1424173/114197079-4a6da600-9952-11eb-97e1-53ff52af9d8a.png)

**Comment by AndrewDaGuy** [comment]
> Hi @Gusted !
> Thanks for writing back so quickly. Here is a screenshot:

 Hmmm, it seems the `.c00` selector is at fault here

**Comment by glenneroo** [comment]
Therefore it must some other plugin I have installed?

**Comment by Gusted** [comment]
> Therefore it must some other plugin I have installed?

Yeah, could you list them? Maybe I see something interesting.

**Comment by glenneroo** [comment]
Now I feel bad, this issue is due to another plugin specifically for Hacker News, which has a very similar bug which I reported last year:
https://github.com/plibither8/refined-hacker-news/issues/71

After disabling that add-on, code blocks are readable.

I completely forgot I still had it installed, as the white-on-white for Refined-Hacker-News add-on is only visible when opening the configuration dialog.

This report can be closed.

**Comment by goswami-rahul** [comment]
I had the same issue with these two plugins. fwiw, I added a fix on darkreader dev tools locally by adding
```
CSS
// for code blocks
pre {
    background-color: var(--darkreader-neutral-background) !important;
}
// for inline code
code {
    background-color: var(--darkreader-neutral-background) !important;
}
```
to the `news.ycombinator.com` section.

**Comment by glenneroo** [comment]
@goswami-rahul  Thanks for the code. Added that block, hit apply, refreshed the page and still white on white :( Did you also make any tweaks to the Refined-Hacker-News plugin?

The plot thickens...

**Comment by goswami-rahul** [comment]
I didn't change anything from the refined-hacker-news plugin. Here's how my complete block looks like, if it helps
```
================================

news.ycombinator.com

INVERT
.votearrow

CSS
[data-darkreader-inline-bgcolor] {
    background-color: var(--darkreader-neutral-background) !important;
}
pre {
    background-color: var(--darkreader-neutral-background) !important;
}
code {
    background-color: var(--darkreader-neutral-background) !important;
}

================================
```
The `[data-darkreader-inline-bgcolor]` part is to change background of whole page to black (from the greenish sepia), though this works for me without that part too. The page looks like this.

![image](https://user-images.githubusercontent.com/30523092/114304736-68720c80-9af2-11eb-9f95-abf1ae36ce85.png)
