### ISSUE TITLE
[BUG] A few websites cannot be switched to dark theme.

### ISSUE THREAD

**Issue by BlueStaggo** [darkreader/darkreader#5518]
# Bug Report

## Describe the bug
A few websites are permanently on light theme and cannot be switched to a dark theme.

## Steps to reproduce
1. Go to any of the websites I have linked
2. Enter the Dark Reader menu
3. Try to click on the website URL to make it dark, but clicking it does nothing

## Expected behavior
All of the websites linked below have a dark theme.

## Actual behavior
All of the websites linked below are permanently stuck with a dark theme.

## Screenshots
![image](https://user-images.githubusercontent.com/71090710/114163807-838e2200-9922-11eb-9991-bf29b40c1cee.png)

## System Information

- OS: Windows 10
- Browser: Google Chrome 89
- Dark Reader Version: 4.9.31

## Additional context
* Changing the Dark Reader mode from Auto to On does not fix the problem
* Here are some websites with this issue:
    * https://pages.github.com/
    * https://yzhong-cs.medium.com/how-to-setup-opengl-on-mingw-w64-in-windows-10-64-bits-b77f350cea7e is the original URL, but it redirects you to medium.com. Before this website was merged to medium.com, I couldn't apply a dark theme to it.
* These websites do not appear on the site list

**Comment by AndrewDaGuy** [comment]
> These websites do not appear on the site list

Maybe one of those URL matching problems I guess (#2517)

**Comment by Gusted** [comment]
> > These websites do not appear on the site list
> 
> Maybe one of those URL matching problems I guess (#2517) or it has to do something with the new DR update

Ding ding 🔔 you can continue for the 1 million question.

It's URL matching he probably has github.com disabled and other "main" domains.

**Comment by gurkantuna** [comment]
> > > These websites do not appear on the site list
> > 
> > 
> > Maybe one of those URL matching problems I guess (#2517) or it has to do something with the new DR update
> 
> Ding ding 🔔 you can continue for the 1 million question.
> 
> It's URL matching he probably has github.com disabled and other "main" domains.

You are right :+1:, let's move on to the other nine hundred ninety-nine... questions 😂

![GithubPages](https://user-images.githubusercontent.com/55924924/114301346-0521b380-9acd-11eb-85de-c2c088bf3d80.PNG)

**Comment by gurkantuna** [comment]
> > > These websites do not appear on the site list
> > 
> > 
> > Maybe one of those URL matching problems I guess (#2517) or it has to do something with the new DR update
> 
> Ding ding 🔔 you can continue for the 1 million question.
> 
> It's URL matching he probably has github.com disabled and other "main" domains.

You are right 👍, let's move on to the other nine hundred ninety-nine... questions 😂

![114301346-0521b380-9acd-11eb-85de-c2c088bf3d80](https://user-images.githubusercontent.com/55924924/114301567-0c958c80-9ace-11eb-9b80-aaca7e6b2f23.png)

**Comment by BlueStaggo** [comment]
> > > These websites do not appear on the site list
> > 
> > 
> > Maybe one of those URL matching problems I guess (#2517) or it has to do something with the new DR update
> 
> Ding ding 🔔 you can continue for the 1 million question.
> 
> It's URL matching he probably has github.com disabled and other "main" domains.

You are right. When I switched on Dark Reader on Github, I could make pages.github.com into a dark theme. When I turned it off, pages.github.com stayed light.

**Comment by BlueStaggo** [comment]
One month later, this issue is still here.

**Comment by BlueStaggo** [comment]
Accidental close

**Comment by Gusted** [comment]
Same issue as #147 and see #2517 their are a lot of people waiting for the PR to be merged. But quite frankly It's a breaking change and planned for V5 and still needs some peer review with some feedback about the code.
