### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by Phaeton20** [darkreader/darkreader#5520]
# Broken Website

## Website

dominos.de The Tracker for Orders

## How to Reproduce

- Go to dominos.de Website
- Order something
- After Order the Livetracker slider is broken

## Expected behavior

Getting a readable Slider

## Actual behavior

White Text on white backgroung

## Screenshots

Issue:
![DarkReader1](https://user-images.githubusercontent.com/69821706/114187150-f8278780-9947-11eb-8bb4-dcb437256cfb.PNG)
Original:
![DarkReader2](https://user-images.githubusercontent.com/69821706/114187156-f8c01e00-9947-11eb-8f52-2ad8840c8959.PNG)

## System Information

- OS:  Windows 10
- Browser:  Firefox 81
- Dark Reader Version:   4.9.16

**Comment by arche-dev** [comment]
I think this was fixed in #5671 🤔 Can you try to update DR and see if the problem occurs again?

**Comment by Gusted** [comment]
I've fixed the issue myself while it was ordering something and this was the exact same thing - closed.
