### ISSUE TITLE
[Dynamic] Vedomosti.ru background too bright

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#554]
Vedomosti.ru background is too bright with Dynamic theme, could be darker. Background looks OK with Static theme.

![image](https://user-images.githubusercontent.com/26354715/41206154-5e452c1c-6d08-11e8-9439-6d86a9d2cd44.png)

**Comment by Gusted** [comment]
![](https://i.imgur.com/gmYbU2m.png) Site Layout is changed.
