### ISSUE TITLE
dark reader is hogging the Bandwidth 

### ISSUE THREAD

**Issue by ZulluBalti** [darkreader/darkreader#5543]
I'm using brave browser and I've notice couple of time that my internet is slowing down quite a bit. On inspection I found that the extension dark reader is using all the bandwidth. What is it using for? and why is it happening so often?

**Comment by Gusted** [comment]
Stick to [the format](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Replace+with+title)
