### ISSUE TITLE
Change only fonts not theme

### ISSUE THREAD

**Issue by rulet** [darkreader/darkreader#5545]
# Feature Request

## Is your feature request related to a problem? Please describe

Don't need to use dark or light theme on some sites

## Describe the solution you'd like

Change font on any site without changing theme

**Comment by Gusted** [comment]
Not within our scope to have such feature.

**Comment by rulet** [comment]
Ok, is it possible to change config file to make this function?

**Comment by Gusted** [comment]
Use stylus if you want such features. Dark reader will be unreliable for this.
