### ISSUE TITLE
Imposible to have webpage seen as without plugin

### ISSUE THREAD

**Issue by txomon** [darkreader/darkreader#555]
I have noticed that regardless on the status, even when it appears that the plugin is completely disabled, there are some texts that are unreadable, or even still reversed.

This for example is how the a google docs file's title looks when the extension is disabled.

![image](https://user-images.githubusercontent.com/228250/41220326-f04bc634-6d58-11e8-8724-e2af3d1b0e85.png)

The most common problem is that text in form fields gets a white color with the white background that it came with by default, making it impossible to edit or see.

I usually need to disable the plugin because load times are extremely big (around 5 secs).

For all this I am using dynamic theme.

**Comment by alexanderby** [comment]
I hope this exact problem was fixed. If you see a similar issue somewhere, please file a bug with a link.

**Comment by txomon** [comment]
I can confirm that this was not an issue with DarkReader, but rather with Firefox, in Gnome shell, with the dark desktop theme. It seems like a bug firefox, because how stuff inside the browser is rendered depends on the theme outside.

It was fixed in my case by launching firefox with `GTK_THEME=Adwaita:light`
