### ISSUE TITLE
dark reader is hogging the Bandwidth 

### ISSUE THREAD

**Issue by ZulluBalti** [darkreader/darkreader#5557]
# Bug Report

## Describe the bug

I'm using brave browser and I've notice couple of time that my internet is slowing down quite a bit. On inspection I found that the extension dark reader is using all the bandwidth. What is it using for? and why is it happening so often?

## System Information

- OS:  Linux (arch)
- Browser: brave - Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
Hi @ZulluBalti!

Dark reader shouldn't be hogging your bandwidth. In certain cases it will request external CSS/Images when a site loads but other than that it doesn't do anything with resources.

Is it reproduce-able on certain sites?

Regards,
Gusted
