### ISSUE TITLE
[Broken Website] WashingtonPost.com

### ISSUE THREAD

**Issue by archaik** [darkreader/darkreader#5559]
# Broken Website

## Website

https://www.washingtonpost.com

https://www.washingtonpost.com/nation/2021/04/14/derek-chauvin-trial/?itid=hp-top-table-main

## How to Reproduce

Go to https://www.washingtonpost.com
Click on any article
Article page shows white boxes around each div section
Site logo at the top of the page does not show up against dark background (is not inverted).

## Expected behavior

Expect white borders to be absent or to be more muted against the black background.
Expect the site logo at the top of the page to show up against dark background.

## Actual behavior

White borders are around each section, when they didn't used to be there.
Site logo is too dark against the dark background.

**changing from Dynamic to Filter, Filter+, or Static all have their own separate issues. None of these settings are ideal.

## Screenshots

![Screen Shot 2021-04-14 at 4 40 04 PM](https://user-images.githubusercontent.com/6326106/114794309-0d822480-9d41-11eb-815e-80d1279c8290.jpg)

![Screen Shot 2021-04-14 at 4 40 12 PM](https://user-images.githubusercontent.com/6326106/114794327-1672f600-9d41-11eb-8952-13d007ffce00.jpg)

## System Information

- OS:  macOS 10.15.7
- Browser:  Firefox 87.0
- Dark Reader Version:  4.9.31

## Additional context

Thank you!

**Comment by nathanielcwm** [comment]
The boxes are back.
