### ISSUE TITLE
[Feature Request] Regex support for sites black/ white list

### ISSUE THREAD

**Issue by twio142** [darkreader/darkreader#5569]
# Feature Request

## Is your feature request related to a problem? Please describe
github.com loads significantly slowly when dark reader is enabled. I'd like to have github.com excluded for dark reader since the website already has a native dark theme; but then some other github pages without native dark theme (e.g. lab.github.com, docs.github.com, etc.) must be excluded as well.

## Describe the solution you'd like
- More advanced regex support for black and white list, or
- Tell specific urls to do completely nothing in Dev Tools

## Additional context
(macOS, Chrome 90, Dark Reader 4.9.31)

**Comment by twio142** [comment]
Update: I set static mode for just github.com and it seems to solve my problem so far.

But it'd still be nice to be able to maintain a more precise black/ white list.

**Comment by Gusted** [comment]
#2517 and for now use `github.com$` in the site list to just target github.com
