### ISSUE TITLE
[Dynamic] Github contribution graph not very readable

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#558]
See screenshot, Dynamic theme. Also note that the colors in the legend below the graph do not correspond to the colors on the graph. Looks better with Static, Filter and Filter+.

![image](https://user-images.githubusercontent.com/26354715/41255373-fccc0efc-6dce-11e8-9f98-0fd421453cd2.png)

**Comment by gilbertohasnofb** [comment]
> Looks better with Static, Filter and Filter+.

It does look better, but still with a lot of problems: 

* Static mode does a bit better with the grid, but makes the rest of the page looking buggy:

![image](https://user-images.githubusercontent.com/5700795/49329683-84f0f800-f57a-11e8-9498-f58aab99ff10.png)

![image](https://user-images.githubusercontent.com/5700795/49329686-9508d780-f57a-11e8-9f27-2180e9a78bfd.png)

* Filter mode makes the grid look quite better, except that the scale becomes inverted, the lighter the green the more contributions an user made in a day:

![image](https://user-images.githubusercontent.com/5700795/49329696-c2ee1c00-f57a-11e8-86a0-108f4b6ef96d.png)

* Filter+ makes the page become fully black with no text nor images for me.

**Comment by krupenja** [comment]
@gilbertohasnofb As a temporary workaround, you can use https://github.com/StylishThemes/GitHub-Dark to generate a custom dark theme. then, in Dark Reader, you can enable Static theme, open Dark Reader CSS Editor and paste your generated theme there. This will get you a decent-looking contribution graph:

![image](https://user-images.githubusercontent.com/26354715/49534249-bc88d880-f8c9-11e8-9652-9203479a5262.png)

**Comment by gilbertohasnofb** [comment]
@krupenja Thanks for the tip, I will check that out!

**Comment by Mrgove10** [comment]
Any news on when this will be fully implemented in darkreader ?
