### ISSUE TITLE
[Feature Request] Make the "View Page Source" Dark

### ISSUE THREAD

**Issue by iamvinny** [darkreader/darkreader#5582]
# Feature Request
It would be interesting if you could make the _"View Page Source"_ dark, as of now, when you right-click on any page and then click on _"View Page Source"_, the HTML code has a white background and black text, that would be nice if it were inverted.

## Describe the solution you'd like
Make the _"View Page Source"_ page dark.

**Comment by Gusted** [comment]
dup #4149
