### ISSUE TITLE
[Broken Website] On instagram.com, account names have a box around them.

### ISSUE THREAD

**Issue by sharadmathur1** [darkreader/darkreader#5585]
# Broken Website

## Website
https://www.instagram.com/p/CN0ILoCDSKe/

## How to Reproduce

  An example of this is:
Go to any post on instagram.com.

## Expected behavior
The account names should not have boxes around them. The names are pretty clear already

## Actual behavior
The account names have boxes around them.

## Screenshots
![image](https://user-images.githubusercontent.com/17840830/115157522-7225e200-a0a7-11eb-8456-1b92fc632684.png)

## System Information

- OS: Windows 10
- Browser: Chrome 89.0.4389.128
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
#5488

**Comment by sharadmathur1** [comment]
But how do i solve this problem?

**Comment by Gusted** [comment]
You either wait for the next release or enable the "sync sites fixes" feature.
