### ISSUE TITLE
[Feature Request] Add PrivacyTools.io to global Dark List

### ISSUE THREAD

**Issue by PrSunflower** [darkreader/darkreader#5586]
# Feature Request

Please add https://privacytools.io/ to the Global Dark List. It has a nice ☀ **_Theme_** button at the top!

### I 🖤 you!

What a wonderful extension with magnificent design! A big **THANK YOU** to all developers and collaborators!

**Comment by Gusted** [comment]
`

If a website is already dark (has all pages dark by default)
`

**Comment by PrSunflower** [comment]
@Gusted sorry I didn't understand your message?

If you're saying that for you the website is bright by default, on my computer with Dark Reader **disabled** and **cookies cleaned** the website is dark by default:

![image](https://user-images.githubusercontent.com/59576952/115446561-72012000-a228-11eb-8f7e-d0ad72f9e62a.png)



### System specs

- Windows 10 version 20H2 with **_"Choose your colour"_** set as **"Dark"**
- Mozilla Firefox 87.0 (64-bit)

**Comment by PrSunflower** [comment]
Same on Microsoft Edge. [PrivacyTools.io](https://privacytools.io/) is already dark.

I guess it respects Windows's dark mode preference.

**Comment by Gusted** [comment]
> I guess it respects Windows's dark mode preference.

Yeah and such preference should be under "light mode" still show dark.

**Comment by PrSunflower** [comment]
Oh 😮  That's the requirement for Global Dark? That's high expectations 😆

Alright then thanks.
