### ISSUE TITLE
[Broken Website] Cloudflare Worker script editor is not resized correctly

### ISSUE THREAD

**Issue by SamSirry** [darkreader/darkreader#5588]
# Broken Website

https://dash.cloudflare.com/

## How to Reproduce

* Go to https://dash.cloudflare.com/
* Log in.
* From the Menu at the top of the page, select Workers.
* Click "Create a Worker"

## Expected behavior

The Workers editor opens with all panes extended to fill the height of the page.

## Actual behavior

The Workers editor opens with all panes constrained to the upper part of the page.

## Screenshots

https://i.imgur.com/5A8t9Ye.png

## System Information

- OS: Windows
- Browser: Firefox 87 (Latest)
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
Seems to me it's just working fine
![image](https://user-images.githubusercontent.com/25481501/115195510-23039f80-a0ef-11eb-89e3-efc10e1c5a7c.png)
As well on Firefox 87

**Comment by SamSirry** [comment]
Yes, in deed. I've tested on another device and it's working fine.
On the device with issues, I've tried disabling almost all extensions, changing Enhanced Tracking Protection settings, and studied the console messages for any clues, but nothing helped.

Any idea how I can debug this? or is this not the right place to ask for help?

**Comment by Gusted** [comment]
Immediately? That means we are touching some of the properties that shouldn't be touched. When you enable the Filter mode, does this still occur?

**Comment by SamSirry** [comment]
Right. Filter and Filter+ are causing the issue. I must have changed this setting long ago and forgot about it.

Thank you for your follow-up. I will change the filter to Dynamic for the time being, and mark this bug as closed.

Your help is much appreciated :)
