### ISSUE TITLE
Enable Dark Reader on New Tab pages

### ISSUE THREAD

**Issue by 99-lives** [darkreader/darkreader#56]
A possible new feature for Dark Reader would be to function on New Tab pages, using whatever algorithm it normally uses to darken pages on the New Tab page. I'm not sure how possible this is, and it may conflict with themes that the user has installed, but if it can be done it would really improve the experience of using the extension.

**Comment by DanRathbun** [comment]
Add to this list the "Apps" page.

**Comment by MareinK** [comment]
Seems like this has been implemented? At least for me the new tab page is dark, although there is a white flash when I open one.

**Comment by Matmo10** [comment]
Since people see the new tab page more than any other page probably, I'd say this is a pretty important one. Is this possible, @alexanderby ?

**Comment by alexanderby** [comment]
You can install a dark theme from Chrome Web Store and it will work for the whole browser (except chrome:// pages).

**Comment by DanRathbun** [comment]
We tried CWS dark themes. They were inferior. **This is why we use Dark Reader !**

I repeat the question... is it possible for Dark Reader to theme the Apps and New Tab pages, please?

**Comment by alexanderby** [comment]
Chrome disallows injecting scripts into new tab page, chrome settings pages and Chrome Web Store page. Content Scripts used to work, but they seem to be disallowed for new tabs since Chrome 61 https://developer.chrome.com/extensions/content_scripts

Personally I use Morpheon Dark theme https://chrome.google.com/webstore/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad

**Comment by DanRathbun** [comment]
Loaded this theme to try it. It is **not** working for me. New Tab pages remain as default bright white background.

**Comment by alexanderby** [comment]
I would also suggest [Material Simple Dark Grey](https://chrome.google.com/webstore/detail/material-simple-dark-grey/ookepigabmicjpgfnmncjiplegcacdbm). I can also try to publish a separate theme created on my own. Dark Reader now generates tabs theme for Firefox 60. Both browsers seem to have no API for modifying new tabs on the fly.

**Comment by m2c2lure67** [comment]
Just Use: https://chrome.google.com/webstore/detail/humble-new-tab-page/mfgdmpfihlmdekaclngibpjhdebndhdj
It's awesome!...
![image](https://user-images.githubusercontent.com/21203218/39781355-f4506a64-52dc-11e8-8687-ddd9e5f96e10.png)

**Comment by alexanderby** [comment]
Extensions cannot inject scripts into New Tab page. I've found the way to inject the script and reported it to Chrome team, the issue was fixed https://bugs.chromium.org/p/chromium/issues/detail?id=844428

**Comment by zbot473** [comment]
Can't you add a custom new page with dark theme?

**Comment by talesa** [comment]
The best solution is per @m2c2lure67: use https://chrome.google.com/webstore/detail/humble-new-tab-page/mfgdmpfihlmdekaclngibpjhdebndhdj and set the background colour to e.g. #242525 which corresponds to Dark Reader's default. You can tweak your new tab however you like which was important for me since I like mine completely empty.

**Comment by DanRathbun** [comment]
You do **not** need an extension to have the New Tab, Settings or Extensions pages in dark mode.

Instead install a dark **theme** for Chrome. I use ...
https://chrome.google.com/webstore/detail/dark-theme-for-google-chr/annfbnbieaamhaimclajlajpijgkdblo

It works very well with the Dark Reader extension.

----

There are also other themes. (Search the Chrome Store.)

**Comment by m2c2lure67** [comment]
I tried your suggested theme, and my LastPass vault was still whiter than
virgin snow...

*------------------------------*


*Thank You, Mitchell McClure*
*E-Mail: mailto:Mitchell.G.McClure@GMail.COM <Mitchell.G.McClure@GMail.COM>*
*T-Mail: mailto:4239462551@vText.com <4239462551@vText.com>*
*Snail-Mail: 134 Wilbur Dam Road, Elizabethton, Tennessee 37643*
*Work: (423)431-0528, Mobile: (423)946-2551**Home Page.:
**http://m2c2.ihostfull.com/mmcc/internetstatus.htm
<http://m2c2.ihostfull.com/mmcc/internetstatus.htm>*

On Tue, Apr 7, 2020 at 6:13 PM DanRathbun <notifications@github.com> wrote:

You do *not* need an extension to have the New Tab, Settings or Extensions

**Comment by DanRathbun** [comment]
>I tried your suggested theme, and my LastPass vault was still whiter than
virgin snow...

Don't know what "LastPass vault" is, but this theme works (for New Tab page ONLY) on my Chrome under Win10, regardless of whether Dark Reader is on or off, and when Win 10 Dark mode is off (ie, set to Light mode.)

The Settings page, and the chrome://flags page are only dark if the system Win 10 Dark mode is enabled. This mode also cause the New Tab page to be dark if the dark theme is removed (reset to default Chrome theme.)

So for Win 10 users there are two ways to have the New Tab page dark without a Chrome extension.

----

If you are not running Win 10, then there are some experimental **built-in settings** you can try:
[chrome://flags/#enable-force-dark](chrome://flags/#enable-force-dark)

However, this experimental forced dark mode will be at odds with the Dark Reader extension.

----

(P.S. - Please don't quote everything, nor post all that signature "noise" to GitHub comments.)

**Comment by m2c2lure67** [comment]
Mr.Rathbun,   Sorry about the auto-sig in my previous message!  To further
clarify; what I'm trying to ask is, IF it's at all possible for your "Dark
Reader" extension to affect "other" extension pages / urls;...
...for example: *chrome-extension://???xxx*

On Wed, Apr 8, 2020 at 1:20 AM DanRathbun <notifications@github.com> wrote:

I tried your suggested theme, and my LastPass vault was still whiter than

**Comment by DanRathbun** [comment]
> To further
clarify; what I'm trying to ask is, IF it's at all possible for your "Dark Reader" extension to affect "other" extension pages / urls;... ...for example: *chrome-extension://???xxx*

This isn't my project, I'm a consumer like you. This (feature request) issue and discussion is specifically about the **New Tab** pages, and has been **closed** by the project owner (as the answer was **no** extensions cannot change this page. I speculate that the answer likely extends to other "system" pages as well.)

Your request seems different so it may be best to open a new request issue. (Ie, we are having this discussion in the collection of closed issues which some people don't see or ignore.)

**Comment by nh2** [comment]
I'm a bit confused by the help text on https://darkreader.org/help/en/:

> The extension cannot change the appearence of a new tab or browser (it can since Firefox 60). Install some dark theme or new tab extension from extensions store.

So what exactly is now possible since Firefox 60? The sentence suggests that it can now change everyhing, but on my Firefox > 60, the new-tab page is still white.

Does the help need to be clarified?

**Comment by Gusted** [comment]
It only can on Firefox & v60 and higher.

**Comment by nh2** [comment]
> It only can on Firefox & v60 and higher.

It can _what exactly_ since v60? I am on Firefox 77, and my `about:blank` new-tab page is white:

![Screenshot from 2020-06-12 22-44-45](https://user-images.githubusercontent.com/399535/84544862-743c4900-acfe-11ea-860c-04a201f755e6.png)

It also says specifically `This page is protected by your browser`. Am I missing something?

**Comment by Gusted** [comment]
Ugh It's a bug with Firefox and it's hard to explain why this happend only I know 50% why this is happening.

**Comment by Juju-cloud** [comment]
Hey everyone,
I just fixed the issue after encountering it on my side as well!
here's a step by step easy fix:
First, I'd like to assume you're using firefox if you ran into this problem, now let's get into it. 

1. Open a new tab and open: about:addons (just copy-paste it)

2. You should find your firefox themes there. Disable any that are enabled. then open a new tab, you may now notice that the tab is dark again ... bare with me. 

3. Now open DarkReader: 
   - Turn it off
   - Turn it on again
   - Back to about:addons, re-enable your firefox DarkTheme. 

Now that should be it!
Hope this will helps

**Comment by Gusted** [comment]
Oh wait #3634 should resolve this issue.

**Comment by ptrkstr** [comment]
about:blank was white for me on firefox and what I ended up needing to do was this step:
https://superuser.com/a/1142572/959934

`browser.display.background_color.dark` didn't seem to be read so I changed `browser.display.background_color` and that worked.
