### ISSUE TITLE
Unity Answers has a messed up logo

### ISSUE THREAD

**Issue by ylluminarious** [darkreader/darkreader#560]
Hi,

I started using your extension recently; I'm very pleased by it! The ability to darken on a per-site basis is *very* useful and is sadly something that is not done by most extensions. I've noticed one issue, though:

On [answers.unity.com,](https://answers.unity.com) the logo looks completely white. Here's a screenshot:

![unity_answers](https://user-images.githubusercontent.com/4912973/41327593-14f72aac-6e92-11e8-9129-05103e65f05e.png)

I'm using default settings, except for the sites I've added to my site list. Is there some way for me to work around this via Dark Reader's settings?

EDIT:

It seems that this is specifically affecting an element of the class `.shard`.

**Comment by alexanderby** [comment]
It was auto-detected as a transparent icon. I will add some more config options to fix it manually.

**Comment by ylluminarious** [comment]
@alexanderby Thank you!

**Comment by ylluminarious** [comment]
FYI, here's a workaround for anyone else facing this issue.

Place the following filter in your adblocker of choice:

```
answers.unity.com##.shard
```

It will prevent this element from appearing.
