### ISSUE TITLE
Safari or Tampermonkey versions?

### ISSUE THREAD

**Issue by NorthIsUp** [darkreader/darkreader#562]
With 10.14 having a dark mode it would be really cool to have darkreader for safari. Any chance of that happening?

**Comment by alexanderby** [comment]
I was thinking about it recently, at least adding some simplified version. Unfortunately creating a Safari extension means that the half of the extension should be rewritten in Swift. I will do some more research.

**Comment by NorthIsUp** [comment]
Someone made a worse version and is charging $1.99 for it

https://itunes.apple.com/us/app/dark-mode-for-safari/id1397180934?mt=12&ref=producthunt

**Comment by alexanderby** [comment]
It's better, then nothing.

**Comment by pshirshov** [comment]
> It's better, then nothing. And as far as I know App Store charges $99 from developer every year.
Not so big deal. You may ask someone to publish or to give you some money in case it's a blocker.

**Comment by brunolemos** [comment]
Safari extension development docs: https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension

**Comment by L3rchal** [comment]
This somehow works (now it's broken) but I dont see any swift code in it...
https://github.com/350d/stylish

**Comment by alexanderby** [comment]
@L3rchal This is an old extensions format, it will be deprecated in Safari 12.

[Here](https://medium.com/@honestbleeps/what-apple-gives-you-for-100-as-a-safari-extension-developer-and-why-reddit-enhancement-suite-6e2d829c2e52) is a great article about developer's pain when creating a Safari extension. Some quick highlights:
- $100 fee every year.
- Requires making a Swift app in XCode. Only code executed in web-page can be written in JavaScript. Workflow is absolutely different.
- Poor documentation and few tutorials at the moment.
- App review process takes up to 2 weeks. Tech support can ignore your problems.
- Extension installation process is strange.

I've tried it recently so here are my thoughts:
- It will be possible to create a simple extension, without any configuration (like it was in Dark Reader 1) by the end of August.
- The app will be paid, $0.50/month.
- If our crowdfunding campaign will be successful and we will extend our team, then we will reconsider this plan.

**Comment by L3rchal** [comment]
@alexanderby thanks for the info! 
I know that I would be pain to add support for safari. 

Anyway if you go for this plan I do recommend posting this idea on r/apple so people would know about this awesome app. Plus with the coming dark mode on macOS this will be really needed and I am sure there'll be huge demand from people using macOS (even if paid (thought 0.5$ per month sound pretty ok)). 

I really want this for safari :)

**Comment by pshirshov** [comment]
Personally I would prefer the extension to be more expensive (okay, $20) but free of any subscriptions. It's always a pain to keep all that subscription stuff in mind so I'm always avoiding them. Though my opinion may be irrelevant...

**Comment by ylluminate** [comment]
I'm wagering that most people would be willing to pay $5-10 for a Dark Reader for Safari. This is sorely missed and I'm LOVING Safari again with Mojave.

**Comment by alexanderby** [comment]
It's about to be released, here is how the initial version will look like.
<img width="1042" alt="screen shot 2018-10-05 at 11 12 11" src="https://user-images.githubusercontent.com/9638588/46524079-5e6f5300-c890-11e8-9930-6bc0b50b4065.png">

**Comment by wzxu** [comment]
Awesome work! Oh man can't wait to return to Safari. 

Ever since I found Dark Reader I'd been forced to use Chrome because the dark mode was just too good. Now I can finally enjoy the fluidity of Safari *and* not burn my eyes.

Seriously this is gonna be the first browser extension I pay for. Hopefully it'll gain feature parity soon.

**Comment by ylluminarious** [comment]
@alexanderby Will there be an `Invert listed only` or `Not invert listed` option? I rely heavily on the `Invert listed only` option; with it, I can cover sites for which there are no Userstyles.

**Comment by alexanderby** [comment]
@ylluminarious The features will be ported one by one. The initial release is as simple as possible.

**Comment by alexanderby** [comment]
Finally it's in the App Store, more info here https://darkreader.org/safari/

Please, let me know if you see any issues.

**Comment by ylluminarious** [comment]
@alexanderby Thanks for the info! Exciting stuff!

**Comment by NorthIsUp** [comment]
Downloaded it last night as soon as I got the email. I opened the issue and I hope I was the first download from the store.

Thanks for making it happen!
