### ISSUE TITLE
[Feature Request] support for general Webkit browser with WebExtension

### ISSUE THREAD

**Issue by Tuxino88** [darkreader/darkreader#5627]
Is it possible to support browsers that use webkit such as Gnome-Web? (Webkit2Gtk4).

**Comment by Gusted** [comment]
[Stick](https://www.youtube.com/watch?v=RLINayEfvNo). [to](https://www.youtube.com/watch?v=RLINayEfvNo). [The](https://www.youtube.com/watch?v=RLINayEfvNo) [format](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFeature+Request%5D+Replace+with+title).
