### ISSUE TITLE
[Feature Request] License for exported theme

### ISSUE THREAD

**Issue by rpadovani** [darkreader/darkreader#5628]
# Feature Request

## Is your feature request related to a problem? Please describe

I'd like to add a dark theme to my personal website, and the CSS generated from Dark Reader (amazing extension BTW!) is a very good starting point (95% already there, I'd say). Unfortunately, there is no license attached when you export the theme, so I cannot in good faith include it in my website. 

## Describe the solution you'd like

Can we add a notice at the top of the file, with the license? I'd love it to be MIT, so I can integrate as long as I keep the notice, but any other free license should be good

**Comment by Gusted** [comment]
Hi @rpadovani!

Never really thought about that as the code is generated from a MIT-Licensed extension and then spit out to the user without any-kind of License.

@alexanderby What you think about:

I think to just add the "This code is MIT-license" or any other valid license notice. MIT-License in general should be good to go as it's allowed(unlike GPL variants) to make any variants open-source/available so anyone have the free will to modify it however they like to. 
The only condition of MIT is to have the license/copyright notice must be included when you use the 'licensed' CSS. However I don't we are going to pursue anyone who either left it out or some minifier removed it.

Regards,
Gusted

**Comment by Gusted** [comment]
#5697
