### ISSUE TITLE
[Feature Request] Add explanation as to why DR can't be applied to a site

### ISSUE THREAD

**Issue by Andre601** [darkreader/darkreader#5631]
# Feature Request

## Is your feature request related to a problem? Please describe

There exists this issue where DR only shows "Disabled for this website" and clicking the domain doesn't make it apply to the site in question.
The is no extra info or reason provided as to why this happens.

## Describe the solution you'd like

DR should have a more explaining text telling you if it can't be applied to a page and also give a proper reason for it, be it an incompatible page type or perhaps an override from the settings or site itself.
Just displaying "Disabled for this website" gives the impression that you can use DR on the site and clicking it without any result can lead to the belief, that DR is completely broken.

## Additional context

There have been a few pages for me, where DR didn't work, but I'm not experienced enough to debug those situations to find a common cause for this problem.

**Comment by Gusted** [comment]
Hi @Andre601!

Sounds look a good idea for me, as yeah as you describe it's pretty weird we will block you from enabling such site. Just for sakes, your still able to click the "domain" button? Or is it completely disabled. As if your still able to click it that means their is a bug going on(#3359).

Regardless of that,
@alexanderby :

I think we could implement an "hover" or even a dedicated button that will redirect to our wiki explaining why. Your thoughts?

Regards,
Gusted

**Comment by Andre601** [comment]
> Just for sakes, your still able to click the "domain" button? Or is it completely disabled.

What does count as "disabled" here?
Like the button is clickable (Highlights when clicked on) but does nothing in that regards.

**Comment by Gusted** [comment]
> What does count as "disabled" here?
> Like the button is clickable (Highlights when clicked on) but does nothing in that regards.

Disabled means the button isn't clickable.

**Comment by Gusted** [comment]
^ And as it's clickable it most likely the bug from #3359

**Comment by Andre601** [comment]
> ^ And as it's clickable it most likely the bug from #3359

Yeah. But again: What counts as "clickable"? Like since this isn't like a GH button where it's greyed out (And since I never saw that before in DR so I can't tell if it has this) so I can't tell if the button is "clickable" or not...

**Comment by Gusted** [comment]
You stated when it is highlighted when you clicked on it. That means you can click it and make it's clickable. When it's disabled/not clickable it is just greyed out and you can't do anything about e.g. (https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh or https://addons.mozilla.org/en-US/firefox/addon/darkreader/) such sites are protected and greyed out.
