### ISSUE TITLE
[Feature Request] Enable/Disable changing theme

### ISSUE THREAD

**Issue by nchristopher** [darkreader/darkreader#5634]
# Feature Request

## Is your feature request related to a problem? Please describe
I have Dark Reader disabled on some websites that already have a dark mode (such as GitHub). However, I'd still like to change the fonts to a custom one. Currently, Dark Reader will always either create a dark/light version of a website. Disabling Dark Reader for a website also disables other features, such as fonts.

## Describe the solution you'd like
A checkbox next to the Dark/Light toggle. When disabled, Dark Reader _wouldn't_ change the theme, but _would_ change other things, such as fonts & contrast.

**Comment by Gusted** [comment]
So disabling Dark Reader's main functionality but still preserving functionality that depend on it? Not going to work, out-of-our-scope.

**Comment by nchristopher** [comment]
Completely understandable, thanks anyway!
