### ISSUE TITLE
[Broken Website] gog.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5635]
https://gog.com

Hover mouse on any title box. Details will be not readable.
![20210425-1619334080-001](https://user-images.githubusercontent.com/9846948/115984021-242c4500-a5a5-11eb-98b7-8baa2727447c.png)
![20210425-1619334074-001](https://user-images.githubusercontent.com/9846948/115984022-255d7200-a5a5-11eb-8bc9-5577520cbbd9.png)
![20210425-1619333997-001](https://user-images.githubusercontent.com/9846948/115984023-25f60880-a5a5-11eb-97db-4edee3fb669f.png)

See selector
```
product-tile product-tile--expand-left has-discount product-tile--active
```

**Comment by racofer** [comment]
Something changed on the GOG site again. The product tile is white with light text, barely readable.
![](https://i.imgur.com/ttH2eru.png "")

I have found the following selectors to work properly:
`
.product-tile__info,
.product-tile__content {
    background-color: var(--darkreader-neutral-background) !important;
}`

The `product-tile__content` selector is necessary to properly display in list view on the site.

![](https://i.imgur.com/3yimF1G.png "")

**Comment by Gusted** [comment]
I cannot reproduce such behavior.
