### ISSUE TITLE
Zero contrast bugs

### ISSUE THREAD

**Issue by MrX-at-GitHub** [darkreader/darkreader#564]
I got a couple of bugs re zero contrast issues.

First one happens on Youtube when clicking the comment box to start writing it. Letters are written with zero contrast so they're not visible at all:

http://imgbox.com/9YGZ5B8j

Second one is about Google's homepage. Search box is not visible (no contrast) if it wasn't for the blinking cursor:

http://imgbox.com/pbzRFVKT

Btw, great nice project of yours... Thank you.

**Comment by alexanderby** [comment]
These modern CSS variables are such a pain.

**Comment by MrX-at-GitHub** [comment]
So I should understand you are not fixing them soon, or never ever at all?

**Comment by MrX-at-GitHub** [comment]
I appreciate your hard work a lot. Thank you for making this useful extension.
