### ISSUE TITLE
[Broken Website] https://wpshout.com/how-to-create-wordpress-theme-from-scratch/

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#5641]
# Broken Website

## Website

https://wpshout.com/how-to-create-wordpress-theme-from-scratch/

## How to Reproduce

Visit the web site with **DR with its Light Theme.**
I expect the background of the web site to be of a light warm color.

## Actual behavior

The background is actually of light green color.

## Screenshots

![Screenshot_20210425_152359](https://user-images.githubusercontent.com/16420574/115995156-5f953680-a5da-11eb-8c04-bc66eeef8faf.png)

## System Information

The lastest XHR branch and also the release branch.

- OS: 
- Browser:  Chromium and Firefox
- Dark Reader Version:   4.9.29 (XHR) , 4.9.32 (Release)

## Additional context

There is no problem with Dark Reader with its dark mode enabled.

Regards, thanks for the attention.

**OFFTOPIC:** also, there is a bug with your github create a bug template, that at the end, when you post it, the actual post doesn't show "How to reproduce" and it is only showing the "Actual behavior instead".

**Comment by Aqa-Ib** [comment]
Thank you @Gusted nice work :)
Have you read this?

> OFFTOPIC: also, there is a bug with your github create a bug template, that at the end, when you post it, the actual post doesn't show "How to reproduce" and it is only showing the "Actual behavior instead".

**Comment by Gusted** [comment]
> Have you read this?


I did but wasn't able to reproduce

**Comment by Aqa-Ib** [comment]
> > Have you read this?
> 
> I did but wasn't able to reproduce

OK nevermind, that was only on my part because I fucked up the template and I left a loose "<!--"
