### ISSUE TITLE
Chromium Embedded Framework possibilities?

### ISSUE THREAD

**Issue by yamlCase** [darkreader/darkreader#565]
I'm working on an app that will be using CEF (https://bitbucket.org/chromiumembedded/cef) as an embedded web browser.  Normally I don't want to include any extensions, but Dark Reader is just so freaking good at making websites readable I'd rather use it than try to poorly reinvent the wheel.

Who has experience with Chromium Embedded Framework and Dark Reader integration and can give us an idea on the level of difficulty for this?  Thanks.

**Comment by alexanderby** [comment]
Maybe you should have a look at AdBlock browser or some similar apps.
