### ISSUE TITLE
Feedly.com slideBumpers not showing in Dynamic mode

### ISSUE THREAD

**Issue by zedug** [darkreader/darkreader#566]
Found this weird bug, whereas when activating dynamic mode in feedly the slidebumpers (left and right arrows on screen to move from article to article similar to j/k keystrokes) disappear.

I'm no CSS expert but when disabling darkreader the arrows are fetched at 

https://s5.feedly.com/images/slider-previous.png
https://s5.feedly.com/images/slider-next.png

and it behaves as advertised.

However switching darkreader on in dynamic mode causes the browser to fetch the png's at 

https://feedly.com/images/slider-previous.png
https://feedly.com/images/slider-next.png

Note how the s5. has disappeared from the domain, resulting in a 404 and no arrows.

Again I'm not an expert so it may linked to another issue but this is what I found.

Oh, I'm using Opera 53.0 FYI.

Thanks for this super useful extension.

**Comment by sbarrier** [comment]
All the images loaded from the CSS are fetched on the wrong URL, this is generating hundred of 404 requests and triggering errors rate limit on server side for the users.

here's an example of the call url("//s5.feedly.com/images/library-sharing-dark@2x.png")

It happen on Chrome 67.0.3396.99

**Comment by alexanderby** [comment]
Should be fixed by https://github.com/darkreader/darkreader/commit/3892ac617793aa0e5cac7f5072cc877b391ecc0c

The fix will be published soon.
