### ISSUE TITLE
[Feature Request] Not really a feature request, more of an idea, 'brightreader'

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#5660]
# Feature Request

Just a thought that occurred to me... but shouldn't we maybe get a 'brightreader' (lightreader is taken on GitHub) for automatically light theming to only dark websites? (lol, I understand if this gets instantly shutdown).

**Comment by Gusted** [comment]
Brightreader? We currently have a "light" theme option that will be changed to "dimmed" version later on. It's possible to change to Scheme to "light"
