### ISSUE TITLE
[Broken Website] Domino's order tracking becomes invisible

### ISSUE THREAD

**Issue by fredddd1** [darkreader/darkreader#5671]
# Broken Website

## Website

Please delete this link after the issue has been resolved:
_Removed by Gusted_

## Screenshots

![dominos-tracker-dark-reader-issue](https://user-images.githubusercontent.com/80743272/116390292-2d741680-a81e-11eb-98e2-8e2752b4e328.png)

## System Information

- OS:  Windows 20H2 64-bit
- Browser:  Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
- Dark Reader Version:  4.9.32

**Comment by Gusted** [comment]
Have a good meal mate!

**Comment by fredddd1** [comment]
@Gusted Is there anything special I need to do to obtain this fix? I am now on 4.9.33 but the issue still persists.

**Comment by AndrewDaGuy** [comment]
> @Gusted Is there anything special I need to do to obtain this fix? I am now on 4.9.33 but the issue still persists.

Either:

1. You haven't got the fix / patch yet
Fix:

<details>
<summary>"Classic" DR UI</summary>

afaik, there's no "sync site fixes" button in the "classic" UI

So I guess you have to use the new v5 preview UI

1. Click dev tools
2. On the 3 buttons click `Preview new design`
3. Goto Settings > Manage Settings > Enable Sync Site fixes

![image](https://user-images.githubusercontent.com/66189242/120480820-fb1a8380-c39e-11eb-9be3-f3a2335b9607.png)


</details>

<details>
<summary>v5 Preview UI</summary>

Settings > Manage Settings > Enable Sync Site fixes

![image](https://user-images.githubusercontent.com/66189242/120480820-fb1a8380-c39e-11eb-9be3-f3a2335b9607.png)


</details>

2. It hasn't been fixed (and _maybe_ your getting another pizza)

Fix: ~~Get Gusted to buy another pizza for you~~


## Some weird things happening 

When I switched back to classic, I realized there was a _secret_ 3 dot menu and clicked on it and now there's weird white things on the extension (It seems to like go poof when I hover over them)

![image](https://user-images.githubusercontent.com/66189242/120481242-71b78100-c39f-11eb-975e-2ff51fae883e.png)

![image](https://user-images.githubusercontent.com/66189242/120481398-99a6e480-c39f-11eb-81d2-d981de3c5d33.png)

![image](https://user-images.githubusercontent.com/66189242/120481470-a9262d80-c39f-11eb-9139-8950e76ea934.png)

![image](https://user-images.githubusercontent.com/66189242/120482124-5600aa80-c3a0-11eb-828d-c64e0a3c5d60.png)
