### ISSUE TITLE
Popups Irregular

### ISSUE THREAD

**Issue by rgletter** [darkreader/darkreader#568]
FIREFOX

On some websites, popup behavior is altered compared to having the utility OFF. On one site the screen nearly turned all white, making the site useless.

On eBay, as a seller, clicking "tracking" for an item moves the popup below the visible screen. It scrolls the screen down 50% of the way down.

**Comment by alexanderby** [comment]
If you are using a Filter mode, this is most likely a browser bug. Try using the Dynamic mode. I don't remember if I reported the problem to developers, most likely not yet.

**Comment by K4YT3X** [comment]
@alexanderby the thing is, I personally find filter mode looking really nice, so I'm using only filter mode. Dynamic and Static modes don't filter images, thus making them looking really sharp.

**Comment by Gusted** [comment]
Should be fixed.
