### ISSUE TITLE
[BUG] DarkReader not work on Chrome

### ISSUE THREAD

**Issue by jeremyjone** [darkreader/darkreader#5684]
I 'm using DarkReader to overwrite the style of my website:

```js
DarkReader.setFetchMethod(window.fetch);
DarkReader.enable({
	brightness: 100,
	contrast: 90,
	sepia: 10
});
```

Then, it work on FireFox, but not work on Chrome and new Edge.

`DarkReader.isEnabled()` is `true`.

Did I do something wrong?

**Comment by Gusted** [comment]
Hi @jeremyjone!

Could you give some more information about the "it isn't working"?

**Comment by jeremyjone** [comment]
Hi @Gusted

You can visit my website https://www.jeremyjone.com , I used the code in my website.

I referenced `<script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.32/darkreader.min.js"></script>` in the header

And then, I wrote the code in my `costum.js` and ref it.

FireFox run OK, but Chrome not work.

It might conflict with what, but it's weird. I am puzzled.

**Comment by jeremyjone** [comment]
Hi @Gusted

You can visit my website https://www.jeremyjone.com , I used the code in my website.

I referenced `<script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.32/darkreader.min.js"></script>` in the header

And then, I wrote the code in my `costum.js` and ref it.

FireFox run OK, Chrome mobile on my phone is OK, too. But Chrome desktop not work.

It might conflict with what, but it's weird. I am puzzled.

**Comment by Gusted** [comment]
Ah this is the weird chrome behavior, which isn't documented. 
You might want to add the `crossorigin` attribute to the styles.
```html
<link rel="stylesheet" id="kicon-css" href="https://cdn.jsdelivr.net/gh/vtrois/kratos@3.2.9/assets/css/iconfont.min.css?ver=3.2.9" type="text/css" media="all" crossorigin>
```

**Comment by jeremyjone** [comment]
@Gusted

 I've tried it. It doesn't seem to work.

**Comment by Gusted** [comment]
Hmm, after further debugging it seems like it is getting fetched correctly, however it won't be send to the right function which might indicate that the bundler is having something faulty. So if you load this version of darkreader.js instead of the CDN one. 
[darkreader.zip](https://github.com/darkreader/darkreader/files/6409755/darkreader.zip)

**Comment by jeremyjone** [comment]
Alas~ It still doesn't work.I tried a different theme and everything worked out fine.But I still like the current theme.It seems to have something to do with the theme of Kratos.But I don't understand why using extensions is fine, but using code is not. Does it make a difference? Anyway, thank you very much.

**Comment by jeremyjone** [comment]
Alas~ It still doesn't work.I tried a different theme and everything worked out fine.But I still like the current theme.It seems to have something to do with the theme of Kratos.But I don't understand why using extensions is fine, but using code is not. Does it make a difference? This problem is not a 比problem for me, but curious about its cause, I will go to look at the theme code. Anyway, thank you very much.
