### ISSUE TITLE
Baidu.com bug

### ISSUE THREAD

**Issue by mlch911** [darkreader/darkreader#569]
When I click next-page, the whole page turn white in baidu.com whatever I search for.
When I use Dynamic theme, it would't turn to white. But the content text of every search result turn to dark...

**Comment by mlch911** [comment]
This is the first page.
![image](https://user-images.githubusercontent.com/26565394/41496595-d47781ac-7175-11e8-8d1e-2b563be9247c.png)

when I turn to next page, it look like this.
![image](https://user-images.githubusercontent.com/26565394/41496592-cbc9cea2-7175-11e8-99d7-310cace1bf26.png)

**Comment by alexanderby** [comment]
The problem with baidu.com was fixed recently.
