### ISSUE TITLE
[BUG] The keyword 'slider-vertical' specified to an 'appearance' property is not standardized

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5690]
Latest dev build npm. Chrome latest stable. @Gusted 😱 😜 
Error:
```
The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
```

![20210430-1619804737-001](https://user-images.githubusercontent.com/9846948/116733699-b3de5300-a9ec-11eb-96ee-9e60c7e4d494.png)

**Comment by Gusted** [comment]
Yeah not fix, it's from the cors logic, meaning it's fetched from an external site and which include such keyword👻
