### ISSUE TITLE
[BUG] Changing settings for specific file URIs is not possible

### ISSUE THREAD

**Issue by samuelgrf** [darkreader/darkreader#5699]
# Bug Report

## Describe the bug
Changing settings for a specific file URI is not possible. Settings apply to all local files even after pressing the `Only for file:` button.

## Steps to reproduce

  - Enable `Allow access to file URLs` in Chrome's extension settings.
  - Open a local HTML file.
  - Open the Dark Reader options window.
  - Press the `Only for file:` button and change a setting.
  - Open another local file.
  - Observe the settings also being applied to that page.

## Expected behavior
Detect the file and change the settings accordingly.

We might want to change the button text to `Only for <filename>` instead of `Only for file:///path/to/file.html`, as file paths are usually much longer than domains. 
This can lead to a bad looking layout, potentially cutting off text (see mockup in screenshot 2 vs 3).

## Actual behavior
See `Describe the Bug`

## Screenshots
![Screenshot_20210501_182456](https://user-images.githubusercontent.com/67663538/116788558-98398200-aaaa-11eb-91d6-d9318720db2b.png)
#### Mockups:
![Screenshot_20210501_183640](https://user-images.githubusercontent.com/67663538/116788900-7640ff00-aaac-11eb-913b-766288a4a0c8.png)
![Screenshot_20210501_183747](https://user-images.githubusercontent.com/67663538/116788907-7b9e4980-aaac-11eb-91d3-b1299b0baef6.png)

## System Information

- OS: Linux (NixOS)
- Browser: Chromium 90.0.4430.85
- Dark Reader Version: 4.9.32

**Comment by Gusted** [comment]
Dup #4345
