### ISSUE TITLE
[Broken Website] hanime

### ISSUE THREAD

**Issue by Alistair1231** [darkreader/darkreader#5703]
# Broken Website

## Website

https://hanime.tv/

## How to Reproduce

- Go to website
- use search or open menu
- see that it doesn't work

## Expected behavior

- menu should open
- search should search
- 
## Actual behavior

- nothing happens

## System Information

- OS:  windows 10.0.19043 Build 19043
- Browser:  Firefox 88.0
- Dark Reader Version:  4.9.32

**Comment by Gusted** [comment]
NSFW site.
