### ISSUE TITLE
[Broken Website] Filter/Filter+ inverts notifications' images on vk.com

### ISSUE THREAD

**Issue by adem4ik** [darkreader/darkreader#5704]
# Broken Website

## Website
https://vk.com/feed

## How to Reproduce
- Enable Filter or Filter+ theme in DarkReader
- Login to vk.com
- Open Feed vk.com/feed
- Press Notifications button at the top menu (with the bell icon)

## Expected behavior
Correct images such as user pictures or photos

## Actual behavior
Inverted images such as user pictures or photos

## Screenshots
![2021-05-02_16-07](https://user-images.githubusercontent.com/4707112/116812681-13f60600-ab61-11eb-849c-a07536bb8e11.png)
![tDt1VTI](https://user-images.githubusercontent.com/4707112/116812685-16586000-ab61-11eb-9686-d0fee13f08eb.png)

## System Information

- OS: Windows 10 Pro x64
- Browser: Vivaldi | 3.8.2259.37 (Stable channel) (64-bit)
- Dark Reader Version: 4.9.32

## Additional context
It doesn't happen with Static or Dynamic theme enabled

**Comment by AndrewDaGuy** [comment]
Apparently VK requires a phone number for account validation (when signing up) so I can't fix this D:
