### ISSUE TITLE
[Broken Website] Quora -- A part of the background is white.

### ISSUE THREAD

**Issue by BlueStaggo** [darkreader/darkreader#5707]
# Broken Website

## Website
Any [Quora](https://quora.com) question.

## How to Reproduce
1. Go to any Quora question.
2. The background is white and so is the text.
3. Scroll down and the background turns into black.

## Expected behavior
The whole background is dark.

## Actual behavior
Part of the background is white.

## Screenshots
![image](https://user-images.githubusercontent.com/71090710/116819662-e319cf00-ab68-11eb-885e-6eb2ae5d66d8.png)

## System Information

- OS: Windows 10 x64 1909
- Browser: Chrome 90
- Dark Reader Version: 4.9.32

**Comment by Gusted** [comment]
Hi @BlueStaggo!

Do you have any special settings? As this issue was quite a while fixed.

Regards,
Gusted

**Comment by BlueStaggo** [comment]
Here are some of my settings:
![image](https://user-images.githubusercontent.com/71090710/118003063-2120ab00-b340-11eb-9ae7-3ecdaed08233.png)
![image](https://user-images.githubusercontent.com/71090710/118003099-28e04f80-b340-11eb-97de-73a6bef0d016.png)
![image](https://user-images.githubusercontent.com/71090710/118003129-31d12100-b340-11eb-8e2d-53abd58982d5.png)

**Comment by Gusted** [comment]
Please go to Settings -> manage settings -> Enable Synchronize site fixes.
Then go back and go to Settings -> Dev tools -> Reset.
Check again.

**Comment by BlueStaggo** [comment]
That white background has now become a darker shade of grey. Still not fixed but it's bearable!
![image](https://user-images.githubusercontent.com/71090710/118149418-71b00b00-b409-11eb-912e-4bbbc4d69029.png)
