### ISSUE TITLE
[Feature Request] Applying css styles in light mode

### ISSUE THREAD

**Issue by Sithell** [darkreader/darkreader#5708]
# Feature Request

## Is your feature request related to a problem? Please describe
I know this is not exactly how this extension is intended to use, but I find it very convenient to change the looks of the sites I frequently use via css styles in "make a fix for a website" menu even if these changes are not related to dark mode (e.g. change size of an element, use different colors, etc.).
I do this using CSS keyword in config file. The problem is that these styles are applied only when dark mode is turned on.

## Describe the solution you'd like
I would like to have an option for custom css rules to be applied both in light and dark mode. This would allow to customize not only dark theme, but also the "default" look. 
Perhaps there could be a new keyword "LIGHT_CSS" in the config, or something along these lines.
Or maybe there could be two sections in the fix file: "LIGHT" and "DARK", or 2 different config files. I'm not sure which option is best.

I could probably make a pull request and try to fix it myself, but I'm not sure if I can make it work and also want to know if it is something possible/worth doing.

**Comment by Gusted** [comment]
Hi @Sithell!

So there 2 things here.

1. Correct, this isn't the way as intended and Il highly recommended [Stylus](https://github.com/openstyles/stylus/) to fulfill this purpose.
2. The proposed solution won't be taken in account unless their is a real usage for this whereby the light mode need fixes for a specific site.

Regards,
Gusted

**Comment by Sithell** [comment]
Ok, thank you for the reply :)
