### ISSUE TITLE
[Dynamic] Google News icons breaking and showing alt text

### ISSUE THREAD

**Issue by JasonKaz** [darkreader/darkreader#573]
Seems like the dynamic theme can't handle the icons, which are a font, and only shows the alt text instead.

![image](https://user-images.githubusercontent.com/959848/41560604-8c564146-7315-11e8-8872-876272f7b7a1.png)

Normally:
![image](https://user-images.githubusercontent.com/959848/41560682-e4212170-7315-11e8-86d2-0d307f2bf5ad.png)

**Comment by alexanderby** [comment]
Do you have some custom font enabled?

**Comment by JasonKaz** [comment]
I do not.

**Comment by alexanderby** [comment]
Looks OK now.
![image](https://user-images.githubusercontent.com/9638588/47910478-0da94500-dea4-11e8-8022-d70faead27fb.png)
