### ISSUE TITLE
[Broken Website] Python documentation webpages are somewhat broken.

### ISSUE THREAD

**Issue by Barafu** [darkreader/darkreader#5738]
# Broken Website

## Website

https://docs.python.org/3.9/library/index.html

## How to Reproduce

Open the page, start randomly prosing the linked pages. 

## Actual behavior

In Dynamic mode, sometimes it works, sometimes the page stays dark for a second, and then the main text area becomes bright again. In Filter+ mode it works all the time. 

## System Information

- OS:  Manjaro Linux
- Browser:  Brave Version 1.23.71 Chromium: 90.0.4430.72 
- Dark Reader Version:  4.9.23

**Comment by Gusted** [comment]
#835
