### ISSUE TITLE
macOS: bright scrollbars when scroll bars are shown automatically based on mouse or trackpad

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#574]
Steps:
1. On a Mac, go to System Preferences -> General.
2. Make sure that "Show scroll bars" is set to "Automatically based on mouse or trackpad".
3. Open Chrome and enable Dark Reader.

Result:
Scrollbars are bright. Happens for Dynamic/Static/Filter.
![image](https://user-images.githubusercontent.com/26354715/41626344-a00d97ba-7424-11e8-8189-cdd882b4937e.png)

Does not happen if "Show scroll bars" is set to "When scrolling". Also not reproducible on Windows.

**Comment by krupenja** [comment]
Just a note: not reproducible on Vivaldi 1.15.1147.47.

**Comment by Gusted** [comment]
Chromes override this fully. Nothing we can do about
