### ISSUE TITLE
[Question] What setting is responsible for "Follow System Color Scheme"

### ISSUE THREAD

**Issue by Jegahan** [darkreader/darkreader#5748]
Hi!

I'm using Firefox on Fedora 34. 

The automation setting "Follow System Color Scheme" used to work, until I installed a custom Firefox CSS Theme from Github. The new theme does follow the System, and I can find in the CSS files of my Firefox Profile this setting for the dark.css (prefers-color-scheme: dark).

So my Question is this: where does Dark Reader looks for "prefers-color-scheme: dark" and how can I add back this automation.

Thanks for your Time

**Comment by Gusted** [comment]
> The automation setting "Follow System Color Scheme" used to work, until I installed a custom Firefox CSS Theme from Github. The new theme does follow the System, and I can find in the CSS files of my Firefox Profile this setting for the dark.css (prefers-color-scheme: dark).

That's weird, custom Firefox CSS shouldn't mess with that setting.



> So my Question is this: where does Dark Reader looks for "prefers-color-scheme: dark"

Well, we ask it in every 'tab' that you'd have open and watch for it to be changing.



>  how can I add back this automation.

I ain't sure as I don't know what causes this.

**Comment by Jegahan** [comment]
So I've been testing around, deleting completly firefox and any related files. On a clean install the "follow system color scheme works". The CSS does indeed not break this feature. Instead login into my firefox account does. Login back out doesn't fix the issue. I have no idea what weird setting my firefox account changes. Any idea what could cause this?

**Comment by Jegahan** [comment]
In case it helps, I just noticed that on a clean install, the popup stays interactable, even if the "follow system color scheme" is active. 
However, if I sign in my firefox account the popup is only interactable if "follow system color scheme" is off. With "follow system color scheme" on, all the option under Filter, Site list and More are greyed out and cannot be clicked.

**Comment by Gusted** [comment]
> Any idea what could cause this?

🤷🏽 maybe `privacy.resistFingerprinting` I'm not an expert in this configuration of firefox other than it's a big pile.



> However, if I sign in my firefox account the popup is only interactable if "follow system color scheme" is off. With "follow system color scheme" on, all the option under Filter, Site list and More are greyed out and cannot be clicked.

The fuck, then there is something that's on your account, probably some kind of setting causing this weird shit.

**Comment by AndrewDaGuy** [comment]
> 🤷🏽 maybe `privacy.resistFingerprinting` I'm not an expert in this configuration of firefox other than it's a big pile.

Yea, that config seems to mess with the system colour scheme (Maybe because light/dark mode can also be tracked?)

**Comment by Jegahan** [comment]
Thanks! Setting privacy.resistFingerprinting set to False in about:config solves the problem. 
I thought I was getting crazy
