### ISSUE TITLE
Swapped to brave, darkreader seems to be missing the "auto" option which is present in chrome/chromium

### ISSUE THREAD

**Issue by klepp0906** [darkreader/darkreader#5749]
This is likely not an "issue" and more of a support thing as both extensions show as being 4.9.32 but here is what it looks like in chrome or chromium

![image](https://user-images.githubusercontent.com/10392920/117291682-4d6a9200-ae3d-11eb-8c2c-42216f705948.png)

Here is what it looks like in Brave installed from the same link

![image](https://user-images.githubusercontent.com/10392920/117291725-5bb8ae00-ae3d-11eb-997c-76f47c04d895.png)

What happened to my auto option?  Can someone enlighten me?  Does it just function differently in brave?

**Comment by Gusted** [comment]
Dev tools -> Preview New Design. Poof you got it back.
