### ISSUE TITLE
DEVtools either broken or needs better documentation

### ISSUE THREAD

**Issue by CollinChaffin** [darkreader/darkreader#575]
https://techcrunch.com/

Not sure I follow your "double and triple inversion" explanation but I've been a DEV myself for 30yrs and for the life of me can't simply open this site, click filter+, and add the one element for "video" which, when added to techcrunch.com mysteriously instantly disappears upon clicking "apply", but then appears (along with other mystery changes) above it to the youtube section.  So, I figure okay perhaps it's an embedded video - doesn't matter it won't simply stop the inversion in filter+ mode.  Dynamic mode ironically does not incorrectly invert this element, but frankly dynamic mode simply is just not very usable yet and turns all links invisible and kills most colors so is only used for me as an absolute last resort so I really would like to know how to properly (and easily) get the element fixes working for day to day use.

**Comment by alexanderby** [comment]
I will write a more detailed doc soon.

**Comment by Gusted** [comment]
README has been updated a long time ago with more info about and it shouldn't be any problem anymore on the sites with current mode with wrongly inverting(not sure)
