### ISSUE TITLE
Doesn't affect text color in text input fields for some websites

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [darkreader/darkreader#576]
On some websites, when using the extension in dark mode, and writing in a text field, the text color doesn't change.

An example of these websites is YouTube. Open any video, try writing a comment, and the result is:

![screenshot_700](https://user-images.githubusercontent.com/19984935/41655638-bdce7828-748d-11e8-8809-7124da2d4d5f.jpg)

The expected result is for the text to be light instead of black.

Same goes for Google Sheets:

![screenshot_701](https://user-images.githubusercontent.com/19984935/41655672-e97ca012-748d-11e8-9b14-c262f952dcc0.jpg)

**Comment by alexanderby** [comment]
The YouTube problem was fixed, unfortunately Google Sheets was not yet, use Filter mode for it.

**Comment by gibfahn** [comment]
Dup of https://github.com/darkreader/darkreader/issues/490

**Comment by AbdelrahmanHafez** [comment]
Great, let's follow up at #490 then.
