### ISSUE TITLE
Difficulty configuring "Invert listed only" mode for sites in the global dark list

### ISSUE THREAD

**Issue by heliosyne** [darkreader/darkreader#5763]
# Bug Report

## Describe the bug

A site being in the global dark list (GDL) disables the normal controls, making Dark Reader difficult to use when set to "Inverted listed only".

## Steps to reproduce

These steps use Netflix as the specific example because its in the global dark list but has an account section that is black-on-white, making the inverted/uninverted state easy to see. I noticed this one in particular because the player and DVD queue parts of Netflix are dark mode natively, so I leave Dark Reader disabled for it to improve load times and avoid the issues that appear when Dark Reader is enabled on a site that is already dark.

1. Set Dark Reader to "Inverted listed only" in the Site list tab;
2. Make sure netflix.com is not listed in the site list for that mode;
3. Go to a bright part of Netflix, such as https://www.netflix.com/YourAccount;
4. Observe the site not being inverted and the panel showing "× netflix.com" on the toggle button;
5. Try to enable dark mode for the site by clicking the toggle button or pressing Alt-Shift-A and see no change;
6. Manually add "netflix.com" to the "Invert listed only" site list and see the site invert.

## Expected behavior

Step 5 should have inverted the site.
Step 6 should not be necessary.

Toggling the enable/disable button and keyboard shortcut should work whether or not a site is in the GDL.

## Actual behavior

A site being in the GDL when the extension is set to "Invert listed only" prevents the toggle button and keyboard shortcut from working as expected, forcing a workaround of manual list entry.

## System Information

- OS: Windows 10 Pro 20H2
- Browser: Firefox 88.0 64-bit
- Dark Reader Version: 4.9.32

**Comment by heliosyne** [comment]
Can someone explain what that patch does? From my read of it, it's going to force dark mode for sites in the GDL even when Dark Reader is set to "invert listed only".

The fix is to not disable the toggle button or Ctrl-Shift-A. DR otherwise worked correctly when set to invert listed only. The bug is literally with that change in the UI, not in how the GDL is being applied.

**Comment by Gusted** [comment]
> The fix is to never disable the toggle button or Ctrl-Shift-A. DR otherwise worked correctly when set to invert listed only. The bug is literally with that change in the UI, not in how the GDL is being applied.

The bug is a larger one, the button doesn't change as the returned value said that it wasn't in the list and thus applied it into the list. 

However upon detecting if the page should be darkend it said: "Nope it shouldn't be darkened" thus making the button look like the page isn't being darkened.

**Comment by Gusted** [comment]
As for what the patch does ^ 

It will now regardless of invert listed only or don't invert listed mode check if the dark site is within the special list for dark sites which should be enabled.

**Comment by heliosyne** [comment]
> It will now regardless of invert listed only or don't invert listed mode check if the dark site is within the special list for dark sites which should be enabled.

That's what I was afraid of. That would be a regression. Dark Reader is useful to me specifically because I set it not invert a site unless I explicitly tell it to. I have it configured that way because there are sites in the global dark list that I need not inverted.

If you want to add a opt-out for the global dark list, that would be fine, but please do not break "invert listed only" by forcing the GDL against it.
