### ISSUE TITLE
[Broken Website] github.community

### ISSUE THREAD

**Issue by Zerotask** [darkreader/darkreader#5768]
# Broken Website

## Website

https://github.community/

## How to Reproduce

Open Edge and the website, and activating darkmode.
I clicked multiple times on the activate button, I also tried the preview.
The page still looks bright and white as usual.

## Expected behavior

See a darkmode website

## Actual behavior

nothing happens (no error messages)

## System Information

- OS:  Windows 10
- Browser:  Edge 90.0.818.56
- Dark Reader Version:   4.9.32

**Comment by Gusted** [comment]
See issue https://github.com/darkreader/darkreader/issues/4717
