### ISSUE TITLE
Dark Reader does not need to be disabled on addons.mozilla.org

### ISSUE THREAD

**Issue by ylluminarious** [darkreader/darkreader#577]
It seems that Dark Reader decidedly does not work on [addons.mozilla.org](http://addons.mozilla.org/) no matter what. [This line in `extension-api.ts`](https://github.com/darkreader/darkreader/blob/1ad3a6da442c5d7dbc04b1fb5067b3716574efdf/src/background/utils/extension-api.ts#L15) explicitly prevents Dark Reader from running on this domain:

            && url.indexOf('https://addons.mozilla.org') !== 0

This is problematic since [Web Extensions can be enabled on Mozilla websites.](https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/) Could we add some extra conditional to see whether Web Extensions are disabled on Mozilla websites *and then* decide whether Dark Reader should be disallowed from injecting based on whether that is the case?

I would really like to enable Dark Reader on this domain to prevent my eyes from burning out... ;)

**Comment by alexanderby** [comment]
Previously Firefox Add-ons moderator didn't let to publish the extension, because it threw an error in console when trying to inject script into some Mozilla pages.

**Comment by ylluminarious** [comment]
@alexanderby Hmm, I see. Is there some way we could prevent that error?

**Comment by ylluminarious** [comment]
@alexanderby This issue can be solved by using [ShadowFox.](https://github.com/overdodactyl/ShadowFox) I think this is a satisfactory solution, so I'll go ahead and close this.

**Comment by Geobert** [comment]
I disagree, I don't want to use ShadowFox but still want to enable Dark reader on addons.mozilla.org.

Can you check the presence/value of `privacy.resistFingerprinting.block_mozAddonManager`? And/or avoid injecting in domains present in `extensions.webextensions.restrictedDomains`?
