### ISSUE TITLE
[Feature Request] Detect if website is already dark before darken it

### ISSUE THREAD

**Issue by Enzodtz** [darkreader/darkreader#5780]
# Feature Request

## Is your feature request related to a problem? Please describe

I'm pretty satisfied by the extension, however it would be really nice to detect if a website is already dark before actually darken it.

## Describe the solution you'd like

Maybe a third state? (Dark, Light, Detect).

## Additional context

Inspired mostly by github that has its own beautiful dark theme, but I think it would be useful in other websites too.

Thanks

**Comment by AndrewDaGuy** [comment]
Do you mean #5719?

**Comment by Enzodtz** [comment]
Thank you! Actually I just searched in the issues.

**Comment by AndrewDaGuy** [comment]
> Thank you! Actually I just searched in the issues.

@Enzodtz You're welcome :D

**Comment by Mahdi-Noor-Hasan** [comment]
I want this feature.
