### ISSUE TITLE
[Performance] Is there an issue with firefox 88?

### ISSUE THREAD

**Issue by peey** [darkreader/darkreader#5787]
# Performance Issue

## How to Reproduce

Can't narrow it down to a single website since I have lots of them open.

## System Information

- OS: Ubuntu 20.04
- Browser: Firefox 88
- Dark Reader Version: 4.9.32 

Do you have this performance issue with Dark Reader disabled? No
Does it happen in other browsers? Didn't check
Do you have hardware acceleration enabled? Yes

## Additional context

Xorg server starts running at 100% CPU usage and stays that way, slowing down the system.

Firefox 88 seems to have many problems with extensions, generally speaking. I wanted to know if there is a known issue regarding performance of dark reader in ff 88.

Everything would work great with the same set of tabs / websites prior to ff 88.

**Comment by peey** [comment]
If there are no known issues, please close this issue and I'll go through each of my tabs to see where the perf issue is coming from and I'll attach a profiler log and then reopen it.

**Comment by peey** [comment]
I have some more observations

1. This does not seem to happen if the extension is disabled, and I enable it while the browser is running. It only happens if I open the browser is started with the extension enabled.
2. It's not an infinite loop. The CPU usage of `xorg` server spikes to 100% and stays there for 3 minutes, and then it begins to normalize.

Additionally. I have a very very large number of tabs and windows open which are all restored when the browser starts up. This is made more manageable by the [auto tab discard](https://github.com/rNeomy/auto-tab-discard/) extension (chrome has similar ones). 

I believe the issue is happening in observation 1 because all pages are restored first and then darkreader spends time darkening them all up, before any tabs are discarded. It doesn't happen in observation 2 because non-discarded tabs are few to begin with. 

I'm gonna see how I can remedy this. @Gusted do you think this reasoning might be correct, and do you think there's anything here which falls in darkreader's domain (e.g. making things easier on startup in general if users have too many tabs being restored, irrespective of what other extensions they might be using)?

**Comment by Gusted** [comment]
> then darkreader spends time darkening them all up, before any tabs are discarded

If tabs are being restored, so does the state of dark reader in certain cases. So either it's already darkened and dark reader is just sitting there idle. Or dark reader is seeing a new site and waiting for it to become visible for the user, before doing any darkening. So either way Dark Reader shouldn't do any heavy things, unless Firefox is having a bug whereby it injects Dark Reader on some state whereby Dark Reader thought it was already darkened and then do some heavy works.

But any of this still shouldn't explain why it's the `xorg` sever that's being pressured on CPU Usage.
