### ISSUE TITLE
[Broken Website] Catch Connect remains white

### ISSUE THREAD

**Issue by nobelharvards** [darkreader/darkreader#5788]
# Broken Website

## Website
https://catchconnect.com.au

## How to Reproduce
Go to website.

## Expected behavior
Toggle Dark Reader off and on after the page has finished loading. Something that looks similar to that. Light text on a dark background.

## Actual behavior
The initial pulsating loading circle is dark, but the content generated afterwards is dark text on a light background. There is also some dark on dark at the very bottom.

## Screenshots
<details>
<summary>Top of page with Dark Reader on</summary>

![image](https://user-images.githubusercontent.com/9457934/117824032-7366bb00-b2b1-11eb-80e5-ef2fc722bdc9.png)
</details>
<details>
<summary>Bottom of page with Dark Reader on</summary>

![image](https://user-images.githubusercontent.com/9457934/117825204-77dfa380-b2b2-11eb-8c65-53436d4554c3.png)
</details>
<details>
<summary>Top of page after toggling Dark Reader off and on after the page has loaded</summary>

![image](https://user-images.githubusercontent.com/9457934/117825273-8a59dd00-b2b2-11eb-8fc8-890b03ee8e9e.png)

</details>
<details>
<summary>Bottom of page after toggling Dark Reader off and on after the page has loaded</summary>

![image](https://user-images.githubusercontent.com/9457934/117825322-95ad0880-b2b2-11eb-8a37-b96ffb807e5d.png)
</details>

## System Information
- OS: Windows 10 20H2 19042.928
- Browser: Firefox 88
- Dark Reader Version: 4.9.32

## Additional context
The website seems to dynamically load its content. The dark theme is applied to the initial pulsating loading circle, but not to the content generated afterwards.

**Comment by Gusted** [comment]
Use filter(+) this site is doing a lot besides normal working. Cannot even see what the current active styles are on this website.
