### ISSUE TITLE
[Broken Website] tokfm.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5791]
https://www.tokfm.pl/Tokfm/7,103085,27070882,koniec-ochotniczej-strazy-pozarnej-mswia-chce-zabrac-im-nazwe.html#s=BoxOpImg6

Scroll page to see it. 

![20210511-1620758818-001](https://user-images.githubusercontent.com/9846948/117868636-20353e00-b29a-11eb-922a-7e6a49763115.png)
![20210511-1620758803-001](https://user-images.githubusercontent.com/9846948/117868643-20cdd480-b29a-11eb-874c-64422d3ff59e.png)

**Comment by Gusted** [comment]
Weird chromium
