### ISSUE TITLE
[Feature Request] LaTeX rendering on certain websites is atrocious

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#5797]
# Feature Request

## Is your feature request related to a problem? Please describe

On certain websites, the LaTeX rendering is not legible at all in dark mode. For example, in the screenshot provided, the inline math is fine but the display math mode is not legible at all.

## Describe the solution you'd like

Not sure if this is a dark reader issue per se or the upstream website but a crystal clear rendering (just like in light mode) could be achieved in dark mode. Note that this is an issue on certain websites only and not all. LaTeX rendering on some "modern" websites works flawlessly. 

## Additional context

This is a screenshot from [nature.com](https://www.nature.com/)

*Dark mode*:
![pic-selected-210512-1810-57](https://user-images.githubusercontent.com/59497618/117977231-3b618580-b34e-11eb-8cbe-3bdc6dad7426.png)

*Light mode*:
![pic-selected-210512-1815-21](https://user-images.githubusercontent.com/59497618/117977362-5b914480-b34e-11eb-84e2-43326f2dfacc.png)

**Comment by Gusted** [comment]
Please share the exact nature.com article

**Comment by paniash** [comment]
> Please share the exact nature.com article

https://www.nature.com/articles/ncomms4768

**Comment by paniash** [comment]
@Gusted Hi! I just noticed that you've merged a fix for the issue. Does updating dark reader now solve it?

**Comment by Gusted** [comment]
> @Gusted Hi! I just noticed that you've merged a fix for the issue. Does updating dark reader now solve it?

Either wait for next release or settle down and read the README.md for how to get the latest fixes https://github.com/darkreader/darkreader#site-fixes

**Comment by paniash** [comment]
Hi. Another broken site: https://iopscience.iop.org/article/10.1088/1361-648X/aa8315

![pic-selected-210513-2144-02](https://user-images.githubusercontent.com/59497618/118154268-763de900-b434-11eb-9efc-d52ce8349f4a.png)

**Comment by Gusted** [comment]
Voila, thanks for reporting #5811

**Comment by paniash** [comment]
Hello again lol, another broken site: http://hyperphysics.phy-astr.gsu.edu/hbase/qunoh.html#c2

**Comment by Gusted** [comment]
Strawberry is tasteful, #5812
