### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by Aviortheking** [darkreader/darkreader#5798]
# Broken Website

## Website

https://www.cssportal.com/css-3d-transform-generator/

## Expected behavior

Dark Reader should not turn off/on

## Actual behavior

Dark Reader should not turn off/on

## System Information

- OS: Windows 10 
- Browser: Brave 1.24.82 based on Chromium 90.0.4430.93 
- Dark Reader Version: Version 5 preview 4.9.32

**Comment by Gusted** [comment]
"Dark Reader should not turn off/on"? The what? Please don't be such vague issue.

**Comment by Aviortheking** [comment]
Dark Reader is trying to update the whole thing so for a moment I have the normal theme back and the dark theme come back after

**Comment by Gusted** [comment]
Normal behavior, especially on larger styles/lower specs machines.
