### ISSUE TITLE
[Feature Request] Filter/Filter+ are not affected by color settings

### ISSUE THREAD

**Issue by remi-dupre** [darkreader/darkreader#5806]
# Feature Request

## Is your feature request related to a problem? Please describe
(Tested on Firefox Android)
When using Filter/Filter+ modes, the background and font are pure black and white for any color setting.

## Describe the solution you'd like

It would be great to be able to customize the background and text color, like in dynamic mode.

**Comment by Gusted** [comment]
Filter(+)/Static mode won't be able to have this as quite frankly dynamically setting the color is just for the dynamic theme and due to how Filter(+) works it isn't possible at all.
