### ISSUE TITLE
[Dynamic] No text in Google News

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#581]
Go to [Google News](news.google.com). The text under Headlines and Fact Check is not visible.

![image](https://user-images.githubusercontent.com/26354715/41808681-e2a246bc-76e9-11e8-96af-4398902cdad5.png)

**Comment by alexanderby** [comment]
Seems like it was fixed in version v4.5.8, web components support was improved.
![image](https://user-images.githubusercontent.com/9638588/41812941-fa428976-7734-11e8-9cb8-1fcc3ea8de44.png)
