### ISSUE TITLE
[Dynamic] Store pages on ebay have white background

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#582]
Open a store page on ebay, e.g. [this](https://www.ebay.co.uk/sch/notebookbitz/m.html?Category=31569&sellerName=notebookbitz&_sacat=31569&_trkparms=pageci%3A2b2cf122-76d4-11e8-a3d6-74dbd1801140%7Cparentrq%3A2c4a55511640a9cb70287c98fffc6a48%7Ciid%3A2). 

![image](https://user-images.githubusercontent.com/26354715/41808901-98184840-76ed-11e8-819e-974dc025cfa9.png)

**Comment by alexanderby** [comment]
Currently we don't process background images defined in elements styles, as far as it can significantly downgrade the performance. The solution would be to remove background using custom config. In a few days I will add more options into config, so it will become possible.

**Comment by kaovilai** [comment]
This background
ir.ebaystatic.com/pictures/aw/pics/cmp/ds3/imgbg.jpg

is also used on ebay.com/itm and ruins the look of inverted site.

**Comment by alexanderby** [comment]
Ebay.com was fixed, unfortunately other country domains are not.
