### ISSUE TITLE
[Broken Website] bulldogjob.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5820]
https://bulldogjob.pl/for-employers/job-offers

![20210514-1621003067-001](https://user-images.githubusercontent.com/9846948/118286586-e4d18400-b4d2-11eb-8f0a-e910c72ec701.png)
![20210514-1621003083-001](https://user-images.githubusercontent.com/9846948/118286582-e3a05700-b4d2-11eb-8641-efdbcadf36c2.png)
![20210514-1621003043-001](https://user-images.githubusercontent.com/9846948/118286591-e4d18400-b4d2-11eb-95e5-b0e2deb45984.png)
![20210514-1621002880-001](https://user-images.githubusercontent.com/9846948/118286593-e56a1a80-b4d2-11eb-8d95-ff374c2d5c6f.png)
![20210514-1621003282-001](https://user-images.githubusercontent.com/9846948/118286899-3b3ec280-b4d3-11eb-9ea2-489755937d8f.png)
![20210514-1621003264-001](https://user-images.githubusercontent.com/9846948/118286903-3c6fef80-b4d3-11eb-8a9e-48f1e90f87b0.png)

**Comment by Gusted** [comment]
Ah #4886 will resolve the other issues.
