### ISSUE TITLE
[Broken Website] techcrunch.com

### ISSUE THREAD

**Issue by Elaborendum** [darkreader/darkreader#5829]
# Broken Website

## Website

https://techcrunch.com
## How to Reproduce

  - Open any article
  - Scroll down until you find an article recomendation
  - See the white block 

## Expected behavior

Block's color is dark like the background.

## Actual behavior

Article preview block is white.

## Screenshots

![image](https://user-images.githubusercontent.com/71190696/118381108-14ed5580-b5ad-11eb-90cc-d156e3056288.png)

## System Information

- OS: Windows 10
- Browser: Firefox 88.0.1
- Dark Reader Version: 4.9.32

**Comment by Gusted** [comment]
Not reproduce-able, I don't even see the recommendation at all.

**Comment by Elaborendum** [comment]
Maybe it depends on the article? Heres one techcrunch.com/2021/05/15/rocket-labs-20th-electron-launch-ends-in-failure-with-the-loss-of-its-payload/ that has two of those blocks. I reset the settings to so everything is the defaults.

**Comment by Gusted** [comment]
Ah, I now see it. However upon looking it seems like the content is in a iframe with has some sandboxing going on. So it's out of our reach to get darkreader injected into this iframe 
![image](https://user-images.githubusercontent.com/25481501/118521279-6707b580-b72a-11eb-81d5-21d7aa6aad5d.png)
