### ISSUE TITLE
[Feature Request] Select to not edit pdfs

### ISSUE THREAD

**Issue by LaserRob** [darkreader/darkreader#5838]
# Feature Request

## Is your feature request related to a problem? Please describe
PDF's are darkened which is sometimes ok but more often than not ends in me disabling for a short time to read then enabling once back to the site. 

## Describe the solution you'd like
Add a toggle switch for "Apply to PDF's"

## Additional context
QR codes on some pdfs become un-scannable due to dark mode.

**Comment by Gusted** [comment]
Dup, see https://github.com/darkreader/darkreader/issues/2450#issuecomment-624629425
