### ISSUE TITLE
Documentation and Guacamole Bug

### ISSUE THREAD

**Issue by cypexxlucas** [darkreader/darkreader#5841]
# Feature Request

First of all, I would like to ask whether there are more options/settings when initializing the darkmode with DarkReader.enable() in the JS lib. If so, a documentation about the options would be nice, because I was not able to find one.

I do also have a problem with the API...
Maybe you have already heard of Guacamole....However, it is a WEB RDP/SSH/VNC Client which also provides a JavaScript lib. This lib generates different elements when I connect to a server, but darkreader causes that the screen/shell is not shown to me. 

![image](https://user-images.githubusercontent.com/59261322/118538867-0343b380-b74f-11eb-9074-f356fd8184a3.png)

**Comment by Gusted** [comment]
> because I was not able to find one.

Give or take it about 5 scrolls in the readme.md https://github.com/darkreader/darkreader#using-dark-reader-for-a-website
A more exhaustive list, see https://github.com/darkreader/darkreader/blob/master/index.d.ts#L41

**Comment by cypexxlucas** [comment]
> > because I was not able to find one.
> 
> Give or take it about 5 scrolls in the readme.md https://github.com/darkreader/darkreader#using-dark-reader-for-a-website

I already read that, but I know, there are more options in the chrome/firefox extension such as "Filter" and I wonder, whether this can also be customized in the JS lib.

But thanks for the second link!

**Comment by Gusted** [comment]
> whether this can also be customized in the JS lib.

Nope, we only support "dynamic" mode. And any other settings in the extension can only be done trough browser API's or are irrelevant for the Dark reader lib.

**Comment by cypexxlucas** [comment]
Because of my problem with the guacamole display I tried to disable DarkReader for the div in which the element with the display is, but either it does not work or I implemented it wrongly...
The display is inside a div with the id remote-connection-display and that's the code I use to start DarkReader

`    DarkReader.enable({
    brightness: 100,
    contrast: 90,
}, {
    ignoreInlineStyle : "#remote-connection-display"
});`

**Comment by Gusted** [comment]
> Because of my problem with the guacamole display I tried to disable DarkReader for the div in which the element with the display is, but either it does not work or I implemented it wrongly...

You cannot disable dark reader for a specific element due to technical reasons.
Dark reader shouldn't conflict with some div. If you know what's causing in you can write a simple `style` element with the `darkreader` class so we ignore that style and include within that style the correct/fix CSS.

**Comment by cypexxlucas** [comment]
Thank you for your help, I resolved my problem!
