### ISSUE TITLE
[Dynamic] Twitter is white

### ISSUE THREAD

**Issue by risualiser** [darkreader/darkreader#585]

**Comment by alexanderby** [comment]
Maybe it's disabled by your settings?
![image](https://user-images.githubusercontent.com/9638588/41812383-839a2298-772a-11e8-9e32-2b91219e137f.png)

**Comment by risualiser** [comment]
It's okay in Chrome, but not in Firefox 62.

**Comment by alexanderby** [comment]
Works OK in latest Nightly. Do you have some error in console? Maybe you have web components flag enabled, it will be shipped in Firefox 63 by default.
![image](https://user-images.githubusercontent.com/9638588/41813025-297f4f84-7736-11e8-8f71-41a414ffeba5.png)

**Comment by risualiser** [comment]
Ok, I found the cause of issue. A few days I set "Always" for browser security instead of "Only in private mode". Extension works again with the default setting. I think now you can close this issue.

[](https://i.imgur.com/GWCxwsl.png)
[](https://i.imgur.com/3FKEAdY.png)
