### ISSUE TITLE
[Feature Request] Use CSS property `color-scheme: dark;` to change scrollbar in Chromium-based browsers

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#5850]
# Feature Request
## Is your feature request related to a problem? Please describe
It would be great if you used the default system scrollbar in Chromium-based browsers instead of setting your own. Since in this case, in Chromium-based browsers on macOS, the scroll would correspond to the system one.

## Describe the solution you'd like
When enabling DarkReader in Chromium-based browsers, instead of creating your own scroll bar, use the property `color-scheme: dark;`.

## Additional context
Useful link: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

**Comment by Gusted** [comment]
Hi @rakleed!

Unfortunately until v90 of chromium scrollbar wasn't styled by the color-scheme. 
Thereby either I'm not sure if you can just target this to chromium as otherwise we will have separate patches for Chromium-based ones to use `color-scheme: dark` and Firefox that have custom CSS colors which probably will bring problems I prefer not to face. But I give it a try to see if worth it. 

Regards,
Gusted

**Comment by Gusted** [comment]
> But I give it a try to see if worth it.

Forgot to post the results I found. 
Seems nice to have, but it will bring out the inconsistency with Firefox. However we can provide a option to enable this. HOWEVER `colors-scheme: dark` isn't limited to scrollbars but also style `<select>`,`<input` etc etc which in dark reader are 2 separate options which means we should add a third option which unexpectedly override the 2 other options that are meant for this. 

Regards,
Gusted

**Comment by xasx** [comment]
This would also bring arrows on the scroll bars, wouldn't it?

If so, I'd highly appreciate this being implemented because due to disability, I can hardly use the mouse scroll wheel and especially for long websites need to scroll using the scroll bar's arrows .

Thanks for consideration 👍

**Comment by oktayacikalin** [comment]
Yes, please don't create a custom one when using dynamic mode.

On bigger pages scrolling can get **really laggy** and since I'm on **elementary OS** I much prefer the small overlay scrollbars in **Chrome**.

Thanks!

**Comment by Gusted** [comment]
> Yes, please don't create a custom one when using dynamic mode.

There's a option to disable it.



> On bigger pages scrolling can get **really laggy** (e.g. amazon product page) and since I'm on **elementary OS** I much prefer the small **overlay scrollbars** in **Chrome**.

The custom scrollbar cannot cause such issues, it's most likely another issue, the scrollbar is pure styling.

**Comment by oktayacikalin** [comment]
> > Yes, please don't create a custom one when using dynamic mode.
> 
> There's a option to disable it.

You mean https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151 ? Nice!
But can this be more prominent and not hidden so deep that "nobody" can find it? :-/

> > On bigger pages scrolling can get **really laggy** (e.g. amazon product page) and since I'm on **elementary OS** I much prefer the small **overlay scrollbars** in **Chrome**.

> The custom scrollbar cannot cause such issues, it's most likely another issue, the scrollbar is pure styling.

Normally I would completely agree with you. This time I don't know what causes this, but disabling the custom scrollbar and just use the native ones (even the normal one), is such a huge difference. See for yourself:

https://user-images.githubusercontent.com/687189/150204380-3d1d6b1c-fe2e-4dff-8fec-190796a7f1f3.mp4

**Comment by rakleed** [comment]
@alexanderby @Gusted and why if the value "Auto" is selected, then a custom scroll is displayed instead of the default one?

**Comment by Gusted** [comment]
> and why if the value "Auto" is selected, then a custom scroll is displayed instead of the default one?

Auto is the "custom" scrollbar with the default settings for the colors. Only "Default" will not style the scrollbar option.

**Comment by rakleed** [comment]
And why do you choose "Custom" scrollbar for "Auto" with default settings for the colors, and not "Default"? I just expected that by default you will use the system implementation of the scroll bar.

**Comment by Gusted** [comment]
> And why do you choose "Custom" scrollbar for "Auto" with default settings for the colors, and not "Default"? I just expected that by default you will use the system implementation of the scroll bar.

By default on a lot of systems(only recent excluding edge) will have a white scrollbar, and that doesn't match the dark mode.

**Comment by rakleed** [comment]
I chose the "Default" color of the scrollbar, and on macOS and on Windows in Chrome, Firefox and Edge, I always had a dark color system scrollbar (even if I turned on the light theme in the system/browser settings). Or are you talking about something else?

**Comment by Gusted** [comment]
> I chose the "Default" color of the scrollbar, and on macOS and on Windows in Chrome, Firefox and Edge, I always had a dark color system scrollbar (even if I turned on the light theme in the system/browser settings). Or are you talking about something else?

That's pretty weird, my experiences have never been like that. Maybe time to revisit all OS's and see if we can by default use the OS's scrollbar.
