### ISSUE TITLE
[Broken Website] timetravel.mementoweb.org

### ISSUE THREAD

**Issue by Rummskartoffel** [darkreader/darkreader#5852]
# Broken Website

## Website

http://timetravel.mementoweb.org/reconstruct/http://www.unece.org/trans/conventn/signalse.pdf

## How to Reproduce

Navigate to the URL I provided.

## Expected behavior

Dark Reader changes the page's styling.

## Actual behavior

Dark Reader does not change the page's styling because it think it's a PDF (it isn't), saying "This page is protected by browser" in its pop-up.

## Screenshots

N/A

## System Information

- OS:  Windows 10
- Browser:  Firefox 88.0.1 x64
- Dark Reader Version:  4.9.32

## Additional context

It's me again :)! I observed and reported pretty much the same issue on Wikipedia about a year ago in #2856.

**Comment by Gusted** [comment]
Ah, Once again false-positive.
