### ISSUE TITLE
How can I change the style on the same domain but on different tabs?

### ISSUE THREAD

**Issue by brendan8c** [darkreader/darkreader#5858]
I want google.com to be dark.
But I also want google.com/maps to be light (standard without styling).
I also want translate.google.com to be light (standard without styling).
How to do it? The domain is the same..

**Comment by AndrewDaGuy** [comment]
This should be possible with some site list magic :o

1. Open the DR popup/config thing
2. Change to the site list tab
	2a. If your on the "Old design" click the site list tab and you can ignore step `2b`
	![image](https://user-images.githubusercontent.com/66189242/118974568-825d0580-b962-11eb-879d-5a350ec63778.png)

	2b. If your on the "New design" click settings
	![image](https://user-images.githubusercontent.com/66189242/118974720-ad475980-b962-11eb-99ae-47b39673ed25.png)

	then click on site list 
	![image](https://user-images.githubusercontent.com/66189242/118974837-cea84580-b962-11eb-8a8d-86248d9b376f.png)

3. You should see a site list config, something like this:
![image](https://user-images.githubusercontent.com/66189242/118975033-0ca56980-b963-11eb-871a-57306701142a.png)
![image](https://user-images.githubusercontent.com/66189242/118975086-2181fd00-b963-11eb-965c-5e242e9e3630.png)

4. Add the URLS you don't want to be dark: (make sure its on "Not invert listed")

<table>
<tr>
	<td> <code>google.com/maps</code>
<tr>
	<td> <code>translate.google.com</code>
</table>

5. It should now be not inverted on the sites you list and rest of the pages will be dark

**Comment by brendan8c** [comment]
Yes it worked!
But it looks confusing.
It would be more convenient for users to make 2 separate lists. I got confused with these switches (one list for all switches).
