### ISSUE TITLE
[BUG] The site-toggle button randomly stops working on certain sites.

### ISSUE THREAD

**Issue by georgebushfourtwenty** [darkreader/darkreader#5859]
# Bug Report

## Describe the bug

Darkreader sometimes automatically disables itself for certain sites which were working previously. It reads "Disabled for current website". Pressing the site-toggle button does nothing. I'm not sure if it's just me.

Basically, `$('.site-toggle').click()` does nothing.

Right now, I'm seeing this behavior https://codeforces.com in the brave browser.

## Steps to reproduce

- Start brave browser
- Go to codeforces.com
- Try enabling darkreader using the site-specific (not global) button

-- or --
```
chrome.runtime.connect({name: 'ui'}).postMessage({type: "toggle-url", data: "https://codeforces.com"})
``` 
Run this on darkreader's console.
## Expected behavior

Dark mode

## Actual behavior

Dark mode disabled, cannot enable. Pressing the site-toggle button doesn't toggle it.

## System Information

- OS: linux 
- Browser: brave 
- Dark Reader Version: 4.9.32

**Comment by georgebushfourtwenty** [comment]
`chrome.runtime.connect({name: 'ui'}).postMessage({type: "toggle-url", data: "https://codeforces.com"})` does nothing.

**Comment by AndrewDaGuy** [comment]
Not reproducible on firefox, can't bother to download brave because chromium browsers tend to crash 99.999% of the time 😔

**Comment by georgebushfourtwenty** [comment]
Another website - `codedrills.io`

**Comment by Gusted** [comment]
I don't really see anything why this shouldn't other then that you already have a entry in your sitelist that is conflicting with this site.

**Comment by georgebushfourtwenty** [comment]
Even if the entry was present, wouldn't it be removed when the button is toggled?
In my case, the button doesn't change state at all.

One more thing. If `enabled by default`(in the settings menu) is disabled, the site starts to obey darkreader. This time the `site-toggle` button stays enabled instead of disabled. And like before, pressing the `site-toggle` neither changes the state of the button, nor the site.

**Comment by Gusted** [comment]
> Even if the entry was present, wouldn't it be removed when the button is toggled?

Not really, it might be conflicting but it won't be removed when the button it's toggled.

Could you send over the sites you have in your list? Or see if you think anyone of them is causing this problem as it could be matching the same domain.

**Comment by georgebushfourtwenty** [comment]
How? Is there a file?

Also, if the sitelist has an entry `<name>` in it, what should happen to `<name><suffix>.com`?

**Comment by jackreeds** [comment]
Apparently putting `<prefix>` in the list causes this to happen to `<prefix>*`. I think this should be a bug, but I'm not sure if the maintainers would agree.

**Comment by georgebushfourtwenty** [comment]
Apparently putting `<prefix>` in the sitelist causes this behavior for `<prefix>*`. I think this should be a bug, but I'm not sure if the maintainers would agree. Anyways, problem seems to be solved.

**Comment by Gusted** [comment]
#147

**Comment by Francewhoa** [comment]
If you're facing this challenge on a subdomain, it is likely a bug

This is to confirm this bug on subdomaines with Dark Reader V4.9.62. Using [Firefox](http://mozilla.org/firefox) V102.7 or [Ungoogle Chromium](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) V109.0.

For users facing this challenge on subdomains, I published [this easy, quick, and temporary workaround](https://github.com/darkreader/darkreader/issues/1896#workaround).

For developers interested to contribute to resolving this bug, you might be interested in this:
* [Steps to reproduce](https://github.com/darkreader/darkreader/issues/1896#steps)
* Pull request at https://github.com/darkreader/darkreader/pull/2517
