### ISSUE TITLE
[Question]  How to install an old version?

### ISSUE THREAD

**Issue by Pecco01** [darkreader/darkreader#5861]
Hi I have a compatibility problem of recent versions of Dark Reader with Kiwi browser (chrome based) on android.
Basically it doesn't keep the theme dark constantly, but when you go into a site it initially shows the white background on each site for a few seconds (es. the white of google pages). While with the old versions of Dark Reader everything was ok.
All of this happened after a fresh installation of Kiwi and Dark Reader. 
Trying an old version of Kiwi the problem is always there.

Can you tell me how to install an old version of Dark Reader on Kiwi browser?
(Or a way to solve this problem).

**Comment by AndrewDaGuy** [comment]
> Hi I have a compatibility problem of recent versions of Dark Reader with Kiwi browser (chrome based) on android.
Basically it doesn't keep the theme dark constantly, but when you go into a site it initially shows the white background on each site for a few seconds (es. the white of google pages).

Sounds like a bug :o

> (Or a way to solve this problem).

You can report it as a bug so we can fix it and/or follow the instructions below)

> Can you tell me how to install an old version of Dark Reader on Kiwi browser?

I don't think you can install an older version from the official chrome web store, though you can maybe travel back in time to a version that was not broken (https://github.com/darkreader/darkreader/tags). Then you can follow the building instructions from here (https://github.com/darkreader/darkreader#building-for-use) :D (also maybe disabled auto extension update)

**Comment by Pecco01** [comment]
I will try to report as a bug. I had already tried to install an old older version manually on Kiwi but it gives me an error (file manifest not found or something like that), I can't install it.

**Comment by Gusted** [comment]
Hi @Pecco01!

That's pretty remarkable as the last few version I've been working on getting rid of the white flashes and no such scenario has yet came up yet of actually having it again after never having it. However it could be that kiwi got onto a chromium version that made it harder to remove the white flashes and thereby are now actually showing these ugly white flashes. 

As nothing has been done to initial white flashes logic or injection method, it makes me more to believe that kiwi got onto this chromium version, As any "old version" that might work is older than 4.9.17(which introduces this system) which is now 6-7 months ago.

As for a solution, I'm working on #3921 
Regards,
Gusted

**Comment by Pecco01** [comment]
Thanks for your reply. Actually the Kiwi version I had before formatting was the latest, but I don't know if the extension was updated, I think not. I could also try to install an old extension on an old version of Kiwi. The problem is that as a novice I am not able to manually install an old extension on Kiwi, starting from the downloadable .zip file. Are there instructions for beginners?

**Comment by Pecco01** [comment]
I installed an old version via .crx file and it finally installed.
Unfortunately the problem still exists, although it does it less than before.
It is difficult to understand why this could depend, even before I had the latest version of Kiwi and it didn't have this problem. Maybe it's fresh from installation, is that the problem?

**Comment by Gusted** [comment]
More likely it's due toe version of kiwi your using.

**Comment by Pecco01** [comment]
I installed the version of Kiwi I had initially, over a year ago (Quadea), with the old version of the plugin from then, and the situation does not change.

**Comment by Pecco01** [comment]
Now after other tests with the old version of Kiwi and the old plugin it seems ok. Thank you.

**Comment by Pecco01** [comment]
But after a day Kiwi auto updates the plug-ins.
Does anyone know if it is possible to block this update on Kiwi?

**Comment by AndrewDaGuy** [comment]
> But after a day Kiwi auto updates the plugins. :-(
> Does anyone know if it is possible to block this update on Kiwi?

Maybe in the settings?

**Comment by Pecco01** [comment]
> > But after a day Kiwi auto updates the plugins. :-(
> > Does anyone know if it is possible to block this update on Kiwi?
> 
> Maybe in the settings?

No it's not in the settings, but I did the manual installation, maybe this way it won't do the auto update, but I'm not sure.
