### ISSUE TITLE
[Broken Website] Jupyter notebooks

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#5864]
# Broken Website
Dark reader with jupyter notebook doesn't give correct syntax highlighting and in general doesn't look as good as one expects.

## Screenshots

![pic-full-210521-1134-11](https://user-images.githubusercontent.com/59497618/119089918-8a7f7880-ba28-11eb-9ccd-a4262e3f46b3.png)

## System Information

- OS:  Linux
- Browser:  Firefox 88
- Dark Reader Version:  Latest stable release

**Comment by Gusted** [comment]
#1106
