### ISSUE TITLE
[Broken Website] meta.stackexchange.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5865]
https://meta.stackexchange.com/questions/31228/comments-should-support-the-strike-element

![20210521-1621584989-001](https://user-images.githubusercontent.com/9846948/119105543-b6e1c780-ba1d-11eb-990f-5ca14c18c573.png)

![20210521-1621584998-001](https://user-images.githubusercontent.com/9846948/119105539-b6493100-ba1d-11eb-8a21-12b32bccf5bd.png)

**Comment by Gusted** [comment]
Not sure what happened to the fix, but it didn't had the right background-color that was intended.
