### ISSUE TITLE
visualstudio.com : Copied text is saved as black-on-black

### ISSUE THREAD

**Issue by Loda103** [darkreader/darkreader#5867]
# Broken Website

## Website

visualstudio.com

## How to Reproduce

Input text box save the COPIEd text as black-on-black.

- active the darkreader
- Comment on a ticket
- write something
- copy a part of the text
- past it
- save the comment
- disable the dark reader

## Expected behavior

The copied-pasted text has the same style as the rest of the text

## Actual behavior

the copied text is black on black and cannot be read

(it can be read if you use dark reader.)

## Screenshots

![Screen Shot 2021-05-21 at 14 00 05](https://user-images.githubusercontent.com/84574048/119134050-f4098200-ba3c-11eb-99f0-cfb9d53b85d5.png)
![Screen Shot 2021-05-21 at 14 00 13](https://user-images.githubusercontent.com/84574048/119134055-f4a21880-ba3c-11eb-9ca2-edbef189f0a4.png)

## System Information

- OS:  MacOS
- Browser:  Chrome  88.0.4324.192 (Official Build) (x86_64)
- Dark Reader Version:  4.9.32

## Additional context

The issue is not visible if you are a using dark reader ON.

**Comment by Gusted** [comment]
This is normal behavior as the copy/paste system also have the ability to remember which color/font/background-color etc the copied text was, so any page with this color-scheme will have the same issue, you can remove this "remembered propertied" by pasting it with "ctrl + shift + v".

Regards,
Gusted

**Comment by Loda103** [comment]
"ctrl + shift + v" does the trick. thanks.

Anyhow, I believe something could be done to improve this behavior or warn the user, as this is not obvious and came to me a surprise when I saw my comments on someone else computer...

**Comment by Gusted** [comment]
> Anyhow, I believe something could be done to improve this behavior

Not really, it's not accessible from us to access the raw clipboard, and if it is it will require a new permission which in a lot of cases the browser doesn't like when that happen.

Regards,
Gusted
