### ISSUE TITLE
[Dynamic] Yandex hint card turns white

### ISSUE THREAD

**Issue by risualiser** [darkreader/darkreader#587]
Happens only one (first) time per session.

![](https://i.imgur.com/h3P7pTC.png)

**Comment by alexanderby** [comment]
I've published version 4.5.9 today with a possible fix, does it still happen with the latest version?

**Comment by risualiser** [comment]
Nope, I have updated if few hours ago. This bug was in couple of previous versions too.

**Comment by risualiser** [comment]
Seems fixed now.
