### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by KonstantMan** [darkreader/darkreader#5870]
**Question**
Hey i really like using your extension with Firefox PWA on my phone but some sites like Instagram for example have this weird white line on the top 

Do you know a way i can remove it? 
![Screenshot_2021-05-21-19-35-26.png](https://user-images.githubusercontent.com/56481040/119170309-9a13b700-ba52-11eb-9696-3ea4dd62457e.png)

**Comment by Gusted** [comment]
As for now, not. As this bar is being styled by [theme-color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) However Firefox Mobile doesn't currently support this.

You can follow the issue over at mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1706179
