### ISSUE TITLE
[Broken Website] Wikipedia "chemical" pages

### ISSUE THREAD

**Issue by AndrewDaGuy** [darkreader/darkreader#5884]
# Broken Website

## Website

- https://en.wikipedia.org/wiki/Ethanol
- https://en.wikipedia.org/wiki/Acetone
- https://en.wikipedia.org/wiki/Potassium_chloride
- https://en.wikipedia.org/wiki/NFPA_704

## Expected behavior

The "fire diamond" divisions should be readable and the "info headers".

## Actual behavior

The white and yellow division is unreadable and the "info headers" are completely unreadable

## Screenshots

![image](https://user-images.githubusercontent.com/66189242/119596317-7512a180-bdce-11eb-88bb-9919b4863e02.png)

![image](https://user-images.githubusercontent.com/66189242/119596449-b1de9880-bdce-11eb-9c14-9c0947472ca1.png)

![image](https://user-images.githubusercontent.com/66189242/119596515-daff2900-bdce-11eb-8963-aeafba5dc08f.png)

![image](https://user-images.githubusercontent.com/66189242/119596503-d470b180-bdce-11eb-82f4-278f5cdde7d5.png)

## System Information

- OS: macOS 10 
- Browser: Firefox 88 
- Dark Reader Version: 4.9.32

**Comment by DableUTeeF** [comment]
Is this suppose to be fixed? Since I'm still having the issue.
