### ISSUE TITLE
[Broken Website] restoreprivacy.com

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#5887]
# Broken Website

## Website

restoreprivacy.com/vpn-review-websites-owned-by-vpns/

## How to Reproduce

Just visit the link mentioned above and you can see the white background with white text.

## Expected behavior

Black background
## Actual behavior

White background
## Screenshots

![image](https://user-images.githubusercontent.com/60446763/119613809-28a18300-be1b-11eb-9536-a6fafd1f98b3.png)

## System Information

- OS:  Windows 10
- Browser:  Edge Stable (v92)
- Dark Reader Version:  4.9.32

## Additional context

Shoutout to @Gusted for always responding to issues very quickly. Can't thank you enough.

**Comment by Gusted** [comment]
> Shoutout to @Gusted for always responding to issues very quickly. Can't thank you enough.

🔔 And fixed once again.

**Comment by jenabaivab** [comment]
> > Shoutout to @Gusted for always responding to issues very quickly. Can't thank you enough.
> 
> 🔔 And fixed once again.

Thank you so much!

**Comment by jenabaivab** [comment]
@Gusted , still not seeing the fix. Using MS Edge. Do I have to wait for extension update? I have installed it from chrome web store and 'Synchronize site fixes from remote server' is enabled

**Comment by AndrewDaGuy** [comment]
> @Gusted , still not seeing the fix. Using MS Edge. Do I have to wait for extension update? I have installed it from chrome web store and 'Synchronize site fixes from remote server' is enabled

It should update, maybe install the edge extension instead of the chrome web store one? https://microsoftedge.microsoft.com/addons/detail/dark-reader/ifoakfbpdcdoeenechcleahebpibofpc/

**Comment by jenabaivab** [comment]
@Gusted the website is still not fixed. Tried both the edge and chrome extension.

**Comment by Gusted** [comment]
@jenabaivab please check: https://github.com/darkreader/darkreader#site-fixes

**Comment by jenabaivab** [comment]
@Gusted I have synchronize site fixes enabled since day 1 actually. No Help there either :/

**Comment by Gusted** [comment]
Force a reset -> 

Open the popup
Click on the settings button.
Click on "Dev tools"
Click on "Reset"
Click on "Apply"
Refresh the site.

**Comment by jenabaivab** [comment]
@Gusted nope, still the same.

**Comment by Gusted** [comment]
If you search up "restoreprivacy.com" within the "dev tools" page does it show anything?

**Comment by jenabaivab** [comment]
@Gusted No, there are no results for the word restore.

**Comment by Gusted** [comment]
You could restart the browser, it's most likely that either the browser is giving you a old cached version of the https://raw.githubusercontent.com/darkreader/darkreader/master/src/config/dynamic-theme-fixes.config(which you btw could copy paste into the dev tools and click on "Apply") or that Dark reader is somehow sticking to an older version.

**Comment by jenabaivab** [comment]
Pasting the contents fixed the file. But how do I fix this sync problem? Now that I think about it, there is something wrong with the fetch, since this is already 5 days old, and browser has been restarted 100 times since then. 

![image](https://user-images.githubusercontent.com/60446763/120550300-4f128000-c412-11eb-9fd6-e4e0c6c7604a.png)

This exclamation mark has been here since 2 months or so, probably why its not syncing. Any fixes?

**Comment by Gusted** [comment]
> This exclamation mark has been here since 2 months or so, probably why its not syncing. Any fixes?

Since 2 months? Please Please click on "Reset" button within the Dev tools. It means the contents of the devtools had been altered with and at the moment overriden content is preffered over remote content.

**Comment by jenabaivab** [comment]
Thank you, its fixed now. A click on the reset button and a browser restart is all it took to update the site fixes on its own.



> Force a reset of the settings ->
> 
> Open the popup
> Click on the settings button.
> Click on "Dev tools"
> Click on "Reset"
> Click on "Apply"
> Refresh the site.

Here, the moment i press apply, it reverts back to the overwritten content I think, because the exclamation mark appears once apply is clicked after pressing reset. This time I pressed reset, closed the windows and restarted the browser. No exclamation this time. Website change is updated on its own.

**Comment by Gusted** [comment]
Hmm maybe time to add a lot of troubleshooting steps to the syncing sites section. @AndrewDaGuy You like tinkering with markdown :) as we got literally one a few minutes back #5943

**Comment by AndrewDaGuy** [comment]
> Hmm maybe time to add a lot of troubleshooting steps to the syncing sites section. @AndrewDaGuy You like tinkering with markdown :) as we got literally one a few minutes back #5943

wat
