### ISSUE TITLE
[Question] Dark Reader import clarification

### ISSUE THREAD

**Issue by IslandRhythms** [darkreader/darkreader#5896]
So I'm attempting to use DarkReader in my vue project however, I can't seem to get it to work.
I do

`import DarkReader from 'darkreader'`

and then do

`DarkReader.enable()`

only for it to throw an error. Do I have to do
```
import {
    enable as enableDarkMode,
    disable as disableDarkMode,
    auto as followSystemColorScheme,
    exportGeneratedCSS as collectCSS,
    isEnabled as isDarkReaderEnabled
} from 'darkreader';
```
to get it to work?

The error is `Cannot read property 'enable' of undefined`

**Comment by Gusted** [comment]
It really depends on your workflow/setup within vue. As 

```javascript


import {
    enable as enableDarkMode,
    disable as disableDarkMode,
    auto as followSystemColorScheme,
    exportGeneratedCSS as collectCSS,
    isEnabled as isDarkReaderEnabled
} from 'darkreader';
```
is a ESM standard to import from other packages. Knowing a bit how vue works your most likely doing this import from a .vue file and then you should do something like

```vue
<script>
import {
    enable as enableDarkMode,
} from 'darkreader';

enableDarkMode({
    brightness: 100,
    contrast: 90,
    sepia: 10,
});
</script>
```

Regards,
Gusted

**Comment by IslandRhythms** [comment]
@Gusted Ok so its not possible to just do `import DarkReader from 'darkreader' => `DarkReader.enable({})`

**Comment by Gusted** [comment]
>  Ok so its not possible to just do `import DarkReader from 'darkreader'` to then do `DarkReader.enable({})` for example?

I mean, I think so? I don't have a vue setup at the moment to test it out. I will say just try it out.

**Comment by IslandRhythms** [comment]
That's the thing, I've tried doing that and am getting that error.

**Comment by Gusted** [comment]
I don't have another clue. This is really a vue-problem and having external packages.

**Comment by IslandRhythms** [comment]
If you're saying this is possible then this may be a bug with DarkReader. I can do this kind of stuff with other packages, its only DarkReader thats giving me a hard time.

**Comment by Gusted** [comment]
> If you're saying this is possible then this may be a bug with DarkReader.

Actually intended behavior if I'm seeing this correctly. 

We declare the named functions to ESM, but not a global name like:
```javascript
export default DarkReader;
```
whereby DarkReader is a object with the functions. Probably the other scripts do this.

However we export named functions, whereby you only can use the import {functions here} from 'darkreader';

I thought a simple switch would fix this but see: https://github.com/rollup/rollup/issues/3413#issuecomment-592918666
So it will be more complicated as is to have non-breaking compatibility to fix this.

**Comment by IslandRhythms** [comment]
ok thanks
