### ISSUE TITLE
[Broken Website] citilink.ru/profile/

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#5897]
# Broken Website
## Website
https://www.citilink.ru/profile/

## How to Reproduce
- Log in to your account on https://www.citilink.ru/login/?_from=/profile/ site
- Go to https://www.citilink.ru/profile/ site

## Expected behavior
All text is correctly inverted and readable.

## Actual behavior
Some text is incorrectly inverted and unreadable.

## Screenshots
![image](https://user-images.githubusercontent.com/19418601/119871062-c041c700-bf2a-11eb-8912-48c8ea8a2799.png)

## System Information
- OS: Windows 10 v. 21H1
- Browser: Chrome 91
- Dark Reader Version: 4.9.32

## Additional context
The same problem on other pages in the personal account: https://www.citilink.ru/profile/orders/, https://www.citilink.ru/profile/club/, https://www.citilink.ru/expert/, https://www.citilink.ru/profile/delivery/, etc.

**Comment by Gusted** [comment]
Hmm, let me have a little guess, all the black-ish colors are being styled by either `initial` or `inherit`?

**Comment by rakleed** [comment]
As far as I know, the color of the text is set via the CSS property `color`, but for incorrectly inverted elements I could not find the property `color` with the values `initial` or `inherit`.

**Comment by Gusted** [comment]
Hmm, that's weird. So either they aren't being styled or we are the one to blame. But either way I cannot really check as this site is within Russian and last time I couldn't even speak with my big friend Putin in Russian so I'm pretty sure I cannot understand what the register(if it even is the register page) page says

**Comment by rakleed** [comment]
It looks like https://www.citilink.ru/about/privacy-policy/ page has the same problem. And registration is not required here.

**Comment by Gusted** [comment]
Could you try the fix:

```CSS
.OldPageLayout {
    color: var(--darkreader-neutral-text) !important;
}
```
on the registered ones?

**Comment by rakleed** [comment]
It works. Is this a problem because of `.OldPageLayout { all: initial; }`?

**Comment by Gusted** [comment]
> It works. Is this a problem because of `.OldPageLayout { all: initial; }`?

It seems to be.
It's causing the colors to be reset to the browser's default.
