### ISSUE TITLE
svg images on wikipedia

### ISSUE THREAD

**Issue by deathtrip** [darkreader/darkreader#59]
When viewing wikipedia articles svg images in them are unreadable, as the background is inverted but the rest of the image is not. Not sure if it applies to other sites too.

**Comment by alexanderby** [comment]
Could you please check if there is an issue with Dynamic Theme mode and give a link?

**Comment by krupenja** [comment]
Yes, this is still an issue with Dynamic mode as well. Sample link, check first four graphs under "Differentiation": https://en.wikipedia.org/wiki/Derivative

**Comment by deathtrip** [comment]
Yeah, same for me, still an issue using Dynamic Theme. Happens on all pages with svg images, as far as i can tell.

**Comment by azag0** [comment]
Not sure if it is the same issue, but Dark Reader creates interesting effects on the SVG picture on my homepage: https://janhermann.cz I guess this asks a more general question whether SVG figures should be inverted or not.

**Comment by alexanderby** [comment]
@azag0 Currently inline SVGs are analyzed by every element (path, rect etc). Maybe they should be analyzed as a whole image and simple inverted by CSS filter.

**Comment by blakejwc** [comment]
```
a.image img

CSS
a.image img {
    background-color: white !important;
}
```

Works on https://en.wikipedia.org/wiki/Pigpen_cipher

**Comment by iamdrrot** [comment]
The SVGs on Wikipedia have the class "mwe-math-fallback-image-inline" and the parent Span has the class "mwe-math-element". As they are both listed under INVERT in Dynamic Theme Editor, the inverts cancel each other out.
Just remove the fallback one.

**Comment by t-ye** [comment]
@iamdrrot Thanks. Unfortunately, as I think you imply, this works for rendered LaTeX but not for actual svg images.

**Comment by iamdrrot** [comment]
@t-ye Yes, the problem is that there are no special classes for svg images (except math). Inverting all would lead to ugly Photos etc.
However, I scrolled through the CSS Reference and found attribute Selectors that let you choose based on the end of an attribute. They are probably slow or heavy, but it works.
This is my complete Wikipedia section:
```
INVERT
a[href$=".svg"]
.mw-wiki-logo
.central-textlogo__image
.svg-Wikimedia-logo_black
.mwe-math-element

CSS
a.image img.thumbimage {
    background-color: transparent !important;
}
```

**Comment by anohren** [comment]
Would be nice if bullets in bullet lists were inverted: https://en.wikipedia.org/w/skins/Vector/images/bullet-icon.svg?872f1

**Comment by scaomath** [comment]
Similar things can be replicated in github using codecogs LaTeX svg renderer, for example: https://github.com/lyc102/ifem/wiki/Testing-ground:-finite-element-related-LaTeX
which looks like 
![](https://i.imgur.com/9t4XMHN.png)

In an old Chrome extension: https://github.com/bgromov/wiki-mathjax, svg can be properly rendered (if you set a custom CSS in wikipedia)
![](https://i.imgur.com/WTYMwsx.png)

**Comment by Gusted** [comment]
Closed per #1404 & #2321

**Comment by Gusted** [comment]
> Similar things can be replicated on github using codecogs LaTeX svg renderer, for example: https://github.com/lyc102/ifem/wiki/Testing-ground:-finite-element-related-LaTeX
> which looks like
> ![](https://camo.githubusercontent.com/3a80872efcfb73308df048ce7126a62b23ff644b/68747470733a2f2f692e696d6775722e636f6d2f397434584d484e2e706e67)

That isn't wikipedia related, we're researching for a global solution.

**Comment by Inspirateur** [comment]
I'm having the same problem with version 4.9.9 on Firefox, Ubuntu 18.04
```
================================

wikipedia.org

INVERT
.mwe-math-element
.mw-ext-score
.mw-wiki-logo
.central-textlogo__image
.svg-Wikimedia-logo_black
.header .branding-box > a > span > img
.main-footer-menuToggle

CSS
div .thumbimage[src$=".png"],
div .thumbimage img[src$=".png"] {
    background-color: white;
}
.mw-mmv-image .svg,
.fullImageLink [src*=".svg"],
a[href$=".svg"]:hover > img {
    background-color: rgba(255, 255, 255, 0.75) !important;
    background-blend-mode: color;
}
.diff-addedline .diffchange {
    background-color: ${lightblue} !important;
}
.diff-deletedline .diffchange {
    background-color: ${#feeec8} !important;
}
@keyframes unseen-fadeout-to-unread {
    from {
        background-color: ${#dce8ff} !important;
    }
    to {
        background-color: ${#ffffff} !important;
    }
}
@keyframes unseen-fadeout-to-read {
    from {
        background-color: ${#dce8ff} !important;
    }
    to {
        background-color: ${#eaecf0} !important;
    }
}

IGNORE INLINE STYLE
.legend-color

================================```

**Comment by Gusted** [comment]
Open a seperate issue. This isn't related like you said

**Comment by insipidlight** [comment]
4.9.19 Firefox 81.0b9 – This is still a problem, but I don't think it's necessary to open a new issue. It makes chemistry articles completely unusable.

 I'm using the fix above in https://github.com/darkreader/darkreader/issues/59#issuecomment-456448425, here's before and after. Note the Wikipedia logo at top left is unaffected.

https://en.wikipedia.org/wiki/Cholesterol

# Before (default)
![DarkReader 20200913 Cholesterol - Wikipedia 1](https://user-images.githubusercontent.com/34975382/93027996-d139ea80-f5de-11ea-83b9-7e78694124f4.png)
![DarkReader 20200913 Cholesterol - Wikipedia 2](https://user-images.githubusercontent.com/34975382/93027998-d1d28100-f5de-11ea-8e87-d5d2aa2ab1ab.png)

 # After
![DarkReader 20200913 Cholesterol - Wikipedia 1 after](https://user-images.githubusercontent.com/34975382/93027995-d139ea80-f5de-11ea-9a27-9d40f7e8f819.png)
![DarkReader 20200913 Cholesterol - Wikipedia 2 after](https://user-images.githubusercontent.com/34975382/93027997-d1d28100-f5de-11ea-9dbf-e6317e1947be.png)

**Comment by Gusted** [comment]
> It makes chemistry articles completely unusable.

And for this cases their was made a `hover` fix that made the background-color white-ish when you hover over it so it will be read-able as we can't invert the image to make it look good on a black-ish background.

**Comment by insipidlight** [comment]
Ah that makes sense. However I just realized those diagrams in the biosynthesis are actually in GIF format, and the hover over does not work on them. I'll keep using the fix–maybe there could be a built-in toggle to ignore all images?

**Comment by Gusted** [comment]
> 
> 
> Ah that makes sense. However I just realized those diagrams in the biosynthesis are actually in GIF format, and the hover over does not work on them. I'll keep using the fix–maybe there could be a built-in toggle to ignore all images?

Well I only know they used in the early days the .gif format to save images and seems this specific page hadn't a update to a .png *yet* So I expose the fix to the gif format as well with #3638

**Comment by insipidlight** [comment]
I've also added an INVERT rule for mouseover pop-ups, using selector `.mwe-popups-is-not-tall`. This does make the entire pop-up white, but it makes SVG header image previews readable.

**Comment by ayaanmaan** [comment]
How do I actually implement these fixes?
