### ISSUE TITLE
[Filter+] (and Filter) page part is missing on: http://www.tristanharris.com/2016/05/how-technology-hijacks-peoples-minds%e2%80%8a-%e2%80%8afrom-a-magician-and-googles-design-ethicist/ 

### ISSUE THREAD

**Issue by fad1** [darkreader/darkreader#590]
The page is completely black after the paragraph : "Imagine millions of people getting interrupted like this throughout their day, running around like chickens with their heads cut off, reciprocating each other — all designed by companies who profit from it."

http://www.tristanharris.com/2016/05/how-technology-hijacks-peoples-minds%e2%80%8a-%e2%80%8afrom-a-magician-and-googles-design-ethicist/

It's OK in Dynamic mode, but cut off with Filter and Filter+.

**Comment by Gusted** [comment]
Removed all blog posts...
