### ISSUE TITLE
[Broken Website] Samsung Community

### ISSUE THREAD

**Issue by RozvM** [darkreader/darkreader#5908]
# Broken Website
## Website
https://eu.community.samsung.com

## How to Reproduce
1. Go to one of the Samsung Community websites in the EU region. (https://eu.community.samsung.com/t5/magyar/ct-p/hu or https://eu.community.samsung.com/t5/english/ct-p/uk for example)
2. Login
3. Open a post. (https://eu.community.samsung.com/t5/viselhet%C5%91-eszk%C3%B6z%C3%B6k/smartthings/td-p/3493029 or https://eu.community.samsung.com/t5/samsung-lounge/samsung-pay-watch-plug-in-is-unavailable-in-belarus/td-p/3493956 for example)

## Expected behavior
It should load a full whiteish backgrounded website like this:
![kép](https://user-images.githubusercontent.com/74600479/120074685-47fc1280-c09e-11eb-9c09-9fe2f5274389.png)

## Actual behavior
The background is normal until in the first half or until you don't have to scroll. Immediately after scrolling, you get the black colors.

![kép](https://user-images.githubusercontent.com/74600479/120074554-ae346580-c09d-11eb-9d1e-ffbf5b074fdd.png)

## System Information
OS: Windows 10 Pro N 19042.985 x64
Browsers: Mozilla Firefox 88.0.1 x64 & Google Chrome 91.0.4472.77 x64
Dark Reader: 4.9.33

**Comment by Gusted** [comment]
Hi @RozvM!

Is this issue persistent? I don't seem to be able of reproducing this problem.

Regards,
Gusted

**Comment by RozvM** [comment]
Yes, it still exists. Are you logged in and tried the examples that I wrote in the issue?

The only way to clear this issue (for me) is to reinstall the mentioned browsersa and use them without Dark Reader. The removal of the extension or just deleting the browser's AppData contents (most of the time) is not enough.

I didn't had this issue for the past ~2 years/since I use Samsung Community and the addon.

**Comment by Gusted** [comment]
> Yes, it still exists. Are you logged in and tried the examples that I wrote in the issue?

I did. I tried multiple times but didn't see anything near it. Do you maybe encounter a error within the console(ctrl + shift + i -> Console tab)?

> The removal of the extension or just deleting the browser's AppData contents (most of the time) is not enough.

Could you explain?

**Comment by RozvM** [comment]
> Do you maybe encounter a error within the console?

https://user-images.githubusercontent.com/74600479/120077262-d629c600-c0a9-11eb-9344-ed6fb2ed44a1.mp4


Ok, I think it is not related with Dark Reader. I reinstalled Chrome once again (with the AppData deletion) and the black areas reappeared without the add-on after login.

**Comment by Gusted** [comment]
That's pretty weird behavior.

**Comment by RozvM** [comment]
The mentioned phenomenon was solved recently.
