### ISSUE TITLE
[ Dynamic ] Blackberry Blog

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#591]
http://blogs.blackberry.com

**Comment by risualiser** [comment]
Most of this site doesn't look wrong inverted for me. But if you mean logo, can you suggest a fix like this:
```
blogs.blackberry.com

INVERT
#brand
.bb-branding
```

**Comment by alexanderby** [comment]
Repeated background images usually look too bright, image processing should be improved.

**Comment by Gusted** [comment]
LGTM
