### ISSUE TITLE
[Broken Website] Strange colour filter on some images on Wikipedia

### ISSUE THREAD

**Issue by Rummskartoffel** [darkreader/darkreader#5914]
# Broken Website
## Website
https://de.wikipedia.org/wiki/File:Brazil_vs_Germany,_in_Belo_Horizonte_04.jpg ([what it's supposed to look like](https://commons.wikimedia.org/wiki/File:Brazil_vs_Germany,_in_Belo_Horizonte_04.jpg))
https://ar.wikipedia.org/wiki/File:Acute_angle_closure_glaucoma.JPG
https://en.wikipedia.org/wiki/Away_colours#FIFA_World_Cup
https://en.wikipedia.org/wiki/Brazil_v_Germany_(2014_FIFA_World_Cup)

There are probably more, but these should be enough to demonstrate the general principle.

## How to Reproduce
Navigate to the URLs provided.

## Expected behavior
The images on the page are displayed correctly.

## Actual behavior
Some or all of the images on the page have a colour filter applied to them, becoming strangely discoloured.

## Screenshots
![image](https://user-images.githubusercontent.com/20257197/120105818-dcc44600-c15a-11eb-9ebc-f49c826be2f3.png)

## System Information

- OS: Windows 10 
- Browser: Firefox 88.0.1 x64
- Dark Reader Version: 4.9.33

## Additional context
I have been able to reproduce this issue on all Wikipedias I've tried (test, test2, simple, en, ru, ar, de, als, pt), so it probably affects all subdomains of wikipedia.org, but I have not been able to reproduce it on other Wikimedia Projects such as Wikiquote, Wikisource, Wiktionary, or the Wikimedia Commons.
I don't recall ever having noticed this issue before today; it may be caused by a recent update.

**Comment by Gusted** [comment]
> it may be caused by a recent update.

🔔 Correct.

**Comment by Gusted** [comment]
Please check https://github.com/darkreader/darkreader#site-fixes how to enable "early" site fixes so you don't have to wait for the next update to get this fixed.

**Comment by Rummskartoffel** [comment]
Wow, that was quick! Thanks a lot. I think the second URL I posted will still be affected, though, because it'll match this: https://github.com/darkreader/darkreader/blob/5128c1d91bece13e894e5a53ad4e64dee4889ea5/src/config/dynamic-theme-fixes.config#L12549

**Comment by Gusted** [comment]
#5918
