### ISSUE TITLE
[Broken Website] Binance Notifications page

### ISSUE THREAD

**Issue by fredddd1** [darkreader/darkreader#5916]
# Broken Website
## Website

https://www.binance.com/en/inmail

## Screenshots

![image](https://user-images.githubusercontent.com/80743272/120106321-dd5ddc00-c15c-11eb-9393-d1c14ef54529.png)

## System Information

- OS:  Windows 21H1 64-bit
- Browser:  Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- Dark Reader Version:  4.9.33

## Additional context

@Gusted I have sent you login credentials.

**Comment by Gusted** [comment]
Hmm, another weird behavior #5925 should do the job to satisfy binance(cloudflare).

**Comment by fredddd1** [comment]
@Gusted Thank you very much!
