### ISSUE TITLE
[BUG] Extension Reloading the site

### ISSUE THREAD

**Issue by Win-tharsh** [darkreader/darkreader#5917]
Website name - Leetcode 

The page is dark and thats fine. But whenever i click on any button (mainly two buttons) on the web url, it reloads the page. If I just disable the extension, then the web works fine.

Please look into this issue.

BTW, A great project!

**Comment by Gusted** [comment]
Whatever it should reload the page or not is up to the browser - extension doesn't really have any say into this.

**Comment by Win-tharsh** [comment]
Maybe this could be the reason
