### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by Bhooty** [darkreader/darkreader#5919]
# Broken Website
## Website  
www.1mlsbd.com

## Expected behavior
 the  horizontal carousel to appear

## Actual behavior
 The  Carousel disapears

## Screenshots

![Screenshot_20210531-022541_Firefox](https://user-images.githubusercontent.com/46019727/120119135-d3b59200-c1b7-11eb-949c-706f9211085e.jpg)

## System Information

- OS: 
- Browser: Firefox mobile stable 88.1.4
- Dark Reader Version: 4.9.33

**Comment by Bhooty** [comment]
Why closed?

**Comment by Gusted** [comment]
No information was given.

**Comment by Bhooty** [comment]
I forgot to remove the comment sign xD 
My bad 
Should i make another?

**Comment by Gusted** [comment]
> I forgot to remove the comment sign xD
> My bad
> Should i make another?

Don't worry. Within the edit button I could see the website -> https://1mlsbd.com/

**Comment by Bhooty** [comment]
> > I forgot to remove the comment sign xD
> > My bad
> > Should i make another?
> 
> Don't worry. Within the edit button I could see the website -> https://1mlsbd.com/

I edited the post now :)

**Comment by Gusted** [comment]
Please check https://github.com/darkreader/darkreader#using-dark-reader-for-a-website how to get the fix before the next update.

**Comment by Gusted** [comment]
Bump, check new link ^

**Comment by Bhooty** [comment]
> Bump, check new link ^

I activated it in firefox but new update isn't getting pushed for some reason 
Its still same

**Comment by Gusted** [comment]
Restart Firefox or otherwise press on the reset button under `Settings -> Dev tools`
