### ISSUE TITLE
[BUG] Replace with title

### ISSUE THREAD

**Issue by JumperLuko** [darkreader/darkreader#5921]
# Bug Report

## Describe the bug
sub domains of sites interfere with the site list and cause a problem in the "togle current site"

## Steps to reproduce
- enter [Twitter.com](https://twitter.com/)
- click to place the site on the list of exceptions (success yey)
- go to the [help.twitter.com](https://help.twitter.com/) page
- click to remove the page from the list of exceptions (nothing happens)

## Expected behavior
I hope the button works
I would be very happy if I could make a custom list for sub domains

## Actual behavior
I can't deal with the exception of subdomains whose domains are already in the exception

## Screenshots
![image](https://user-images.githubusercontent.com/22037309/120120703-6aad2a80-c175-11eb-8880-2cd7a33c5579.png)

## System Information

- OS: Linux Mint 20.1 (Gnome 3.36.3)
- Browser: Version 89.0.4389.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.33

## Additional context
The conflict of domains and subdomains is bad and is if it is resolved, but it would be interesting that subdomains could have different configurations, as in the case of twitter where the homepage already has dark mode and the help page does not.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues?q=is%3Aissue+sub+domain #147

**Comment by JumperLuko** [comment]
Thanks i found in https://github.com/darkreader/darkreader/issues/19#issuecomment-219210664
