### ISSUE TITLE
[Broken Website] Binance Pool

### ISSUE THREAD

**Issue by nan4k7** [darkreader/darkreader#5922]
# Broken Website
## Website
https://pool.binance.com/en/statistics

## How to Reproduce
Log to pool

## Expected behavior
Should be black

## Actual behavior
Nothing changes, only font color

## Screenshots
![image](https://user-images.githubusercontent.com/8295972/120135456-aad8d100-c1a6-11eb-8e0c-294795694ea6.png)

## System Information
- OS: Windows
- Browser: Firefox 88.0.1 & Chrome 90.0.4430.212
- Dark Reader Version: 4.9.33 & 8.540

**Comment by Gusted** [comment]
Similar situation with #5916 and should be fixed with #5925
