### ISSUE TITLE
[Broken Website] Google Drive File Preview Icons

### ISSUE THREAD

**Issue by RuthlessRuler** [darkreader/darkreader#5924]
# Broken Website
## Website
drive.google.com

## How to Reproduce

  - Go to google drive site
  - Open PDF/MP3/Video/etc
  - icons to download/print/3 dots & etc are all black thus submerged with background and not visible.
  -  Weird Font Rendering in Open with google

## Expected behaviour
The icons should be in white colour to be visible to the users.

## Actual behaviour
The Icons are too getting inverted to black colour thus not visible

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/20885012/120157654-e01a0900-c210-11eb-8160-b89b5c450ace.png)
After:
![image](https://user-images.githubusercontent.com/20885012/120157484-b4971e80-c210-11eb-9dd3-14487473afd9.png)

## System Information

- OS: Windows & Linux
- Browser: Firefox 88
- Dark Reader Version:  4.9.33

**Comment by Gusted** [comment]
@rakleed it seems like the fix for drive.google.com is causing this #5835. 
Specific 
```CSS
div[role="dialog"] div[role="button"][tabindex="0"]
```

**Comment by RuthlessRuler** [comment]
Okay.
I would also like to add that i was doing some additional testing, so if Open A file from Google Drive, then click on 3 dots and click open in new Tab, the icons are actually visible there properly. (i.e the Link is drive.google.com/file/***)

Google Drive Preview: 3 Dot menu Preview Pane:
![image](https://user-images.githubusercontent.com/20885012/120192488-d99f8780-c238-11eb-9691-385ec6b92c42.png)

Google Drive File Link: 3 dot menu
![image](https://user-images.githubusercontent.com/20885012/120192922-69ddcc80-c239-11eb-9f84-8ef0ef141b27.png)
Dark Reader Off:
![image](https://user-images.githubusercontent.com/20885012/120192083-5f6f0300-c238-11eb-98bf-22295b6f1766.png)
Dark Reader On:
![image](https://user-images.githubusercontent.com/20885012/120192184-7e6d9500-c238-11eb-9d39-bf162a2bc2e6.png)

**Comment by rakleed** [comment]
I fixed the main problem https://github.com/darkreader/darkreader/issues/5924#issue-907185448, but I don't know how to fix this problem https://github.com/darkreader/darkreader/issues/5924#issuecomment-851457080. I tried rules that I did not add from `drive.google.com/picker` (https://github.com/darkreader/darkreader/pull/5208#issuecomment-841845115), but it didn’t work. @Gusted please take a look.
