### ISSUE TITLE
Issue rendering Fomantic-UI base webpage with Dynamic Mode.

### ISSUE THREAD

**Issue by SimonVallieresPMG** [darkreader/darkreader#5942]
Hello,

I would like to report an issue while generating the dark theme of any site using the [Fomantic-UI] framework (https://github.com/fomantic/Fomantic-UI). For example: https://fomantic-ui.com/introduction/build-tools.html.

It seems that this problem only occurs when DarkReader mode is set to Dynamic
![image](https://user-images.githubusercontent.com/85201078/120516266-27cd9b80-c39d-11eb-94ff-7c1f6faaa057.png)

Here is what happens when you open any page of a site using this framework:

![fomantic-ui-Network-tab](https://user-images.githubusercontent.com/85201078/120514780-a75a6b00-c39b-11eb-9231-65ee7b358c77.gif)

Actually what I'm guessing is darkreader is trying to convert all svg emoji from Fomantic-UI to "dark mode". Which consequently loads them all despite the fact that they are not used on the web page.

I just exported the CSS file DarkReader generated, and it confirmed what I thought. We can see in the file 3057 lines of this kind:

```
em[data-emoji=":interrobang:"]::before, em[data-emoji="interrobang"]::before {
    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMTUwIiBoZWlnaHQ9IjE1MCI+PGRlZnM+PGZpbHRlciBpZD0iZGFya3JlYWRlci1pbWFnZS1maWx0ZXIiPjxmZUNvbG9yTWF0cml4IHR5cGU9Im1hdHJpeCIgdmFsdWVzPSIwLjI0OSAtMC42MTQgLTAuNjcyIDAuMDAwIDEuMDM1IC0wLjY0NiAwLjI4OCAtMC42NjQgMC4wMDAgMS4wMjAgLTAuNjM2IC0wLjYwOSAwLjI1MCAwLjAwMCAwLjk5NCAwLjAwMCAwLjAwMCAwLjAwMCAxLjAwMCAwLjAwMCIgLz48L2ZpbHRlcj48L2RlZnM+PGltYWdlIHdpZHRoPSIxNTAiIGhlaWdodD0iMTUwIiBmaWx0ZXI9InVybCgjZGFya3JlYWRlci1pbWFnZS1maWx0ZXIpIiB4bGluazpocmVmPSJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSFpwWlhkQ2IzZzlJakFnTUNBek5pQXpOaUkrUEhCaGRHZ2dabWxzYkQwaUkwSkZNVGt6TVNJZ1pEMGlUVEl4SURJM1l5MHhMalkxTnlBd0xUTXRNUzR6TkRNdE15MHpkaTAwWXpBdE1TNDJOVGNnTVM0ek5ETXRNeUF6TFRNZ0xqWXdNeTB1TURBMklEWXRNU0EyTFRVZ01DMHlMVEl0TkMwMUxUUXRNaTQwTkRFZ01DMDBJREl0TkNBeklEQWdNUzQyTlRjdE1TNHpORE1nTXkweklETnpMVE10TVM0ek5ETXRNeTB6WXpBdE5DNDROemdnTkM0MU9DMDVJREV3TFRrZ09DQXdJREV4SURVdU9UZ3lJREV4SURFeElEQWdOQzR4TkRVdE1pNHlOemNnTnk0ek1UTXROaTQwTVRNZ09DNDVNaTB1T1M0ek5URXRNUzQzT1M0MU9EY3RNaTQxT0RjdU56UTNWakkwWXpBZ01TNDJOVGN0TVM0ek5ETWdNeTB6SURONklpOCtQR05wY21Oc1pTQm1hV3hzUFNJalFrVXhPVE14SWlCamVEMGlNakVpSUdONVBTSXpNaUlnY2owaU15SXZQanhqYVhKamJHVWdabWxzYkQwaUkwSkZNVGt6TVNJZ1kzZzlJallpSUdONVBTSXpNaUlnY2owaU15SXZQanh3WVhSb0lHWnBiR3c5SWlOQ1JURTVNekVpSUdROUlrMDVJREkwWXpBZ01TNDJOVGN0TVM0ek5ETWdNeTB6SUROekxUTXRNUzR6TkRNdE15MHpWalZqTUMweExqWTFOeUF4TGpNME15MHpJRE10TTNNeklERXVNelF6SURNZ00zWXhPWG9pTHo0OEwzTjJaejQ9IiAvPjwvc3ZnPg=="); 
}
```

[DarkReader.css.txt](https://github.com/darkreader/darkreader/files/6586270/DarkReader.css.txt)

So, would there be a way to block this behavior ?

**Comment by Gusted** [comment]
Hi @SimonVallieresPMG!

This is kinda intended behavior. And it's even a bit unavoidable, as it's very hard with the current web API's to detect if a certain ruleset is being used or not, as a proposed idea to avoid this is to listen when the emoji's are actually used but is not possible at this moment. However it's a good idea to disable image analysis all together, (IgnoreImageAnalysis option)

 I'm not sure how you are using, as a extension or as the API?

**Comment by SimonVallieresPMG** [comment]
Hi,

I'm using it as a extension. Could you show me where could i find the IgnoreImageAnalysis option.

Thanks.

**Comment by Gusted** [comment]
> I'm using it as a extension. Could you show me where could i find the IgnoreImageAnalysis option.

in that case it's going to be a little bit more difficult. I saw from the screenshot that you where using the 127.0.0.1:8080 domain. In that case you should open the devtools:

- Open up dark reader
- Click on devtools.

You will see this: 
![image](https://user-images.githubusercontent.com/25481501/120537429-d3dea900-c3d4-11eb-8757-cb8eb22f14b6.png)

now copy paste this part:

```CSS

127.0.0.1:8080

IGNORE IMAGE ANALYSIS
*

================================
```

And please copy paste it like this:
![image](https://user-images.githubusercontent.com/25481501/120537629-07b9ce80-c3d5-11eb-9fd0-9c91dc63dae9.png)


Click on Apply, refresh the page and you're ready to go!

**Comment by SimonVallieresPMG** [comment]
That it!

You got it!

Thanks a lot for your help it was very appreciated.
