### ISSUE TITLE
Can't find the Settings button/link

### ISSUE THREAD

**Issue by mdcclxv** [darkreader/darkreader#5943]
In the MD file there is this:
**Enable the Synchronize site fixes setting, under Settings -> Manage Settings.**

Where exactly is that? There is no Settings button/link anywhere.

**Comment by Gusted** [comment]
Please follow all steps:
```
Click on the Dark Reader icon.
Click on the Dev tools button (in the bottom-right corner).
Click on the Preview new design button.
```
Which where listed.

**Comment by mdcclxv** [comment]
Did that, nothing happens, except that the caption of the button is changing to "Switch to old design". See the attached screenshot.
![image](https://user-images.githubusercontent.com/33668915/120546667-d3580980-c3f8-11eb-9c94-3c6c060b2fac.png)

**Comment by Gusted** [comment]
You have to reopen the popup now.

**Comment by mdcclxv** [comment]
Wow, now that's a genuine Easter egg. Thanks :)

**Comment by mdcclxv** [comment]
I guess I hit another Easter egg: how do I undo the Preview. There is no more **Dev tools** button in the popup.

**Comment by mdcclxv** [comment]
Oh man, ok, I must be blind, I've been in that section several times. Thanks.
