### ISSUE TITLE
[BUG] Jira cloud hangs when typing /panel

### ISSUE THREAD

**Issue by samuelgfeller** [darkreader/darkreader#5947]
# Bug Report

## Describe the bug

The new Jira cloud issue view has a functionality where it creates a rectangular box highlighted with a background color and a logo on the left side. It generates when typing `/panel` in the issue description.   
After clicking on a panel suggestion (warning, info, error etc.) the tab freezes until the browser alerts that the page didn't respond.   

## Steps to reproduce

* Go to a Jira issue with the new view (@Gusted please [contact me](mailto:contact@samuel-gfeller.ch), so I can give you the credentials to connect you to my jira workspace and let me know here when you wrote the email)
* Enable the dark reader extension
* Start to type `/panel` in the description view [like shown in this video](https://live.staticflickr.com/video/51222069128/fa1ac95d15/1080p.mp4?s=eyJpIjo1MTIyMjA2OTEyOCwiZSI6MTYyMjcwNjY5NSwicyI6ImY4N2VkODk0ZWRhZWMzMzBiOTIyMmNiY2MwMGY0Yjk4OGI4MjMwYTkiLCJ2IjoxfQ)
* Select a panel from the dropdown 

## Expected behavior

Panel creates and tab not freezing

## Actual behavior

Tab stops responding and after some time the browser alerts that the tab didn't respond.

## Screenshots

[This video](https://live.staticflickr.com/video/51222069128/fa1ac95d15/1080p.mp4?s=eyJpIjo1MTIyMjA2OTEyOCwiZSI6MTYyMjcwNjY5NSwicyI6ImY4N2VkODk0ZWRhZWMzMzBiOTIyMmNiY2MwMGY0Yjk4OGI4MjMwYTkiLCJ2IjoxfQ)

## System Information

- OS:  Windows 10
- Browser:  Chrome  91.0.4472.77 / Microsoft Edge 91.0.864.37
- Dark Reader Version:  4.9.33

## Additional context

Note: Bug only appears in edit mode. If panel was created without dark reader on and description is saved and only then dark reader is enabled, it can display the panels.

**Comment by Gusted** [comment]
>     * Go to a Jira issue with the new view (@Gusted please [contact me](mailto:contact@samuel-gfeller.ch), so I can give you the credentials to connect you to my jira workspace and let me know here when you wrote the email)

:) Done

**Comment by samuelgfeller** [comment]
Probably linked with #1595

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/1595#issuecomment-853777753

**Comment by samuelgfeller** [comment]
I noticed page freezes at other places than panels in the ticket description editor (when changing the colour of the text).
How does  `IGNORE INLINE STYLE` affect the things? Does anything speak against doing the following:
```
IGNORE INLINE STYLE
.ak-editor-content-area *
```
Which would also include panels and everything else inside the editor area (which applies to ticket description and comments). Can I make a pull request with those changes or you can do it yourself if its actually a good thing.

**Comment by Gusted** [comment]
> How does `IGNORE INLINE STYLE` affect the things?

So, my dog said that Dark Reader was trying to override the inline style(`<div style="this is inline style">`) over and over again and that Jira was basically overriding it as well causing it to be a loophole and crashing the tab.



> Which would also include panels and everything else inside the editor area (which applies to ticket description and comments).

Yeah sure, you will need to find a good CSS selector to do this that is a parent div of all these things, or multiple separate ones. Whatever is the best way

> Can I make a pull request with those changes or you can do it yourself if its actually a good thing.

I trust you with it 😄.
