### ISSUE TITLE
[BUG] New FireFox build tab-bar override

### ISSUE THREAD

**Issue by HHallavy** [darkreader/darkreader#5954]
# Bug Report

## Describe the bug

The Tabbar of the new Firefox (Ver 89.0) is not working as intended. Dark reader is disabling both the original dark tab bar and theme tab bar.
## Expected behavior

I would expect the app to display the default theme tab bar
## Screenshots

![image](https://user-images.githubusercontent.com/74372072/120670912-2045e980-c4a6-11eb-9d85-68fde9ec2029.png)
↑ Is the wrong display
![image](https://user-images.githubusercontent.com/74372072/120671048-3f447b80-c4a6-11eb-8511-7656ebe2f299.png)
↑ Is the right display of the tab bar
## System Information

- OS: Windows 10
- Browser: FireFox 89.0
- Dark Reader Version: 4.9.33

**Comment by Gusted** [comment]
Hi! Do you have the change browser theme setting enabled?
![image](https://user-images.githubusercontent.com/25481501/120671572-0c3bc100-c481-11eb-9e96-15775ae2225b.png)
![image](https://user-images.githubusercontent.com/25481501/120671755-37beab80-c481-11eb-9243-3ef7f864e9b7.png)

**Comment by HHallavy** [comment]
Hi! Thanks, it works now. But the original DarkReader behavior was a little bit different. Disabling theme changing will give up **Brightness**,**Contrast**, and other settings for the tab-bar.
It would be better for devs to fix it and make it more stylish for the _modern_ Firefox!

**Comment by Gusted** [comment]
> But the original DarkReader behavior was a little bit different.

We didn't change anything regarding this theme nor the functions behind it. It's most likely due to the new proton theme/UI that Firefox has been enabling to users in Firefox 89

> It would be better for devs to fix it and make it more stylish for the _modern_ Firefox!

I'm not sure what to fix here. It's just dark reader applying the theme over's the Firefox's default theme.

**Comment by HHallavy** [comment]
I think the proper display of the tab-bar with DarkReader on (without "Change the browser theme" set to Default) would be the same color display but with a drop shadow behind the active tab (currently it's only displaying a blue outline).

Thank you for replying.

**Comment by Gusted** [comment]
> would be the same color display but with a lighter color for the active tab without an outline

I'm not sure which could be thingy but probs `tab_line` https://github.com/darkreader/darkreader/blob/master/src/background/window-theme.ts#L49-L70 and for the rest we are passing these arguments to make sure every element of the UI is getting colored to match the dark reader's settings.

**Comment by HHallavy** [comment]
The color (#0073ad Cerulean) is outlining tabs and there's a (#a0a0a0 Nobel) solid line just above the address bar. Remove this and all will be good... I guess.
Here's what I mean:
![image](https://user-images.githubusercontent.com/74372072/121188805-b69b5600-c87e-11eb-8a8f-881f32c8e8a6.png)
![image](https://user-images.githubusercontent.com/74372072/121190052-eac34680-c87f-11eb-8599-f5700e193c64.png)

**Comment by HHallavy** [comment]
Thanks for addressing the issue. I'm closing it now.

**Comment by heinebold** [comment]
Shouldn't this have only been closed _after_ the PR is merged?

**Comment by Gusted** [comment]
But it's merged 😈

**Comment by heinebold** [comment]
ARGH sorry, this is what's called a rece condition
