### ISSUE TITLE
[Broken Website] Mozilla.org and Disroot upload

### ISSUE THREAD

**Issue by gdnzz** [darkreader/darkreader#5957]
# Broken Website
https://www.mozilla.org/en-US/firefox/new/
https://disroot.org/en/services/upload

## How to Reproduce
Just go to these sites. Firefox one misses some elements, and disroot one misses huge photo at the top.

## Screenshots
![firefox](https://user-images.githubusercontent.com/76991571/120805557-7615a280-c535-11eb-82f5-6d923bd8da53.jpg)
![disroot](https://user-images.githubusercontent.com/76991571/120805601-80d03780-c535-11eb-9377-7a9d9921a66b.jpg)

## System Information
Windows 10/64bit
Firefox 89.0
Darkreader 4.9.33

## Additional context
I didn't want to open 2 issues thinking it may bother you, sorry for that if it is a problem.

**Comment by Elaborendum** [comment]
I also want to add that it happens on all of the services pages in disroot. 

Latching on to this report, maybe relevant or not, but this is also similar to what happens in https://www.wickeditor.com, in which the background image on top completely dissappears.

**Comment by gdnzz** [comment]
Yeah, I also checked it out. It emerges on many services. @Gusted

**Comment by Gusted** [comment]
#5963 resolves all those problems.
