### ISSUE TITLE
firefox shortcuts

### ISSUE THREAD

**Issue by Azox-sudo** [darkreader/darkreader#5959]
im using firefox version : 88.0.1 (64-bit)
and i sit the shortcut of the ext (on/off) doesn't really work
if there's data i can provide tell me please

**Comment by Gusted** [comment]
> im using firefox version : 88.0.1 (64-bit)
> and i sit the shortcut of the ext (on/off) doesn't really work
> if there's data i can provide tell me please

This is bare minimum information... And doesn't explain what "doesn't really work" Use template: https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Replace+with+title
