### ISSUE TITLE
Adding custom css rules when darkreader is enable.

### ISSUE THREAD

**Issue by SimonVallieresPMG** [darkreader/darkreader#5960]
Hello,

I am trying to implement the darkreader library to my site.

Everything works fine, but I would like to add css when darkreader is active. Unfortunately I can not find any documentation as to the possible options to give to the enable method.

Right now, here's what I have as code.
```
<script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.32/darkreader.min.js"></script>
<script>
  if (Cookies.get("dark-mode") == "true") {
    DarkReader.enable({
      brightness: 100,
      contrast: 100
    });
  }
</script>
```
I would like to be able to add CSS rules as we can do in the extension.

1 - How to add css rules when the enable function is called ?
2 - Where can I find the documentation for darkreader's methods ?

Thank you!

**Comment by Gusted** [comment]
> Unfortunately I can not find any documentation as to the possible options to give to the enable method.

You can follow the index.d.ts file for the possible options, they are essentially for typescript but it also explains which options are available. https://github.com/darkreader/darkreader/blob/master/index.d.ts#L7



> I would like to be able to add CSS rules as we can do in the extension.

What the extension does is essentially not adding regular CSS from the extension's dev tools, but adding fixes made in CSS. 

> 1 - How to add css rules when the enable function is called ?

This a general question and out of our scope, but something alike:
```javascript
function addCSSToPage(cssCode) {
  const styleElement = document.createElement("style");
  styleElement.textContent = cssCode
  styleElement.classList.add('darkreader');
  styleElement.media = 'screen';
  document.head.appendChild(styleElement);
}
```
should do the job.

> 2 - Where can I find the documentation for darkreader's methods ?
See -> https://github.com/darkreader/darkreader/blob/master/index.d.ts
