### ISSUE TITLE
[Broken Website] IMDb search results

### ISSUE THREAD

**Issue by simenopsahl** [darkreader/darkreader#5961]
# Broken Website
IMDb
## Website
https://www.imdb.com/

## How to Reproduce

Enter a term in the search field in the top bar. This bug occurs on the homepage and elsewhere.

## Expected behavior
The search result dropdown covers the page content.

## Actual behavior
The background of the search results are transparent (with a darken hover highlight), making text hard to read.

## Screenshots

![chrome 21 06 04-22 38 27hCb7XN1f](https://user-images.githubusercontent.com/2676016/120860906-b6514100-c586-11eb-89e3-dc337ece1dc4.png)

## System Information

- OS: Windows 10 21H1
- Browser: Chrome 92.0.4515.40
- Dark Reader Version: 4.9.33

## Additional context
This issue has been present since IMDb launched the redesign. It works as expected on Firefox.

**Comment by simenopsahl** [comment]
After some tinkering in the console I found out that 
`--darkreader-bg--ipt-baseAlt-shade1-bg`
is undefined.
Setting it to anything changes the background.

I set it to the same as
`--darkreader-bg--ipt-base-shade1-color: #1a1d1e;`
but seeing as it's named baseAlt it may be supposed to be some other color.

**Comment by rakleed** [comment]
@Gusted I still have no background (transparent) in Chrome when I open any drop-down menu and search, even with your fix.

**Comment by simenopsahl** [comment]
> @Gusted I still have no background (transparent) in Chrome when I open any drop-down menu and search, even with your fix.

Yep, still having the same issue.🤔

**Comment by rakleed** [comment]
@simenopsahl Gusted and I fixed it. You can copy [the updated rules](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config#L6021-L6091) to yourself before an extension update is released.
