### ISSUE TITLE
For White List  of Specific Site

### ISSUE THREAD

**Issue by loveminimal** [darkreader/darkreader#597]
Firstly, thank you for your chrome-plugin. 

I am a front-end web developer, and sometimes I have to debug some web pages. At this time, I must quit dark reader, and it is so depressed. 

So, add a functionality of withe list is perfect.

**Comment by risualiser** [comment]
The extension already provides site list: http://darkreader.org/help/en/#site-list
You can click on "Toggle..." button on the top to turn it off on specific sites.
