### ISSUE TITLE
Edges of voting arrows on Hacker News are ugly

### ISSUE THREAD

**Issue by NginUS** [darkreader/darkreader#598]
Viewing news.ycombinator.com/news in Chrome (google-chrome-stable) on Linux Mint (18) KDE, the edges of the arrows used to upvote/downvote articles/comments are pixelated unless the darkening is disabled for that site.

Screenshot:
![untitled](https://user-images.githubusercontent.com/8769067/42077350-9f9a6988-7b46-11e8-91ef-54bec8730562.png)

**Comment by alexanderby** [comment]
The reason is they use GIF instead of PNG, so only 1 transparency level is supported. I've inverted the icons, so it should look better now.
