### ISSUE TITLE
[BUG] Replace with title

### ISSUE THREAD

**Issue by homezonebenny** [darkreader/darkreader#5983]
**It seems that it's not working with:**
Thunderbird 78.11.0 (64-Bit)

I guess there was an automatic Update for Thunderbird but I'm not fully sure.
A week ago it was working and now it's not working anymore for E-Mail content.
I can redesign the Thunderbird-UI but not the E-Mail content.

I can provide any info you need, just tell me. :-)

**Comment by Gusted** [comment]
See https://github.com/darkreader/darkreader/issues/5541#issuecomment-836956935
