### ISSUE TITLE
[Broken Website] stackoverflow.com

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#5993]
# Broken Website
## Website
https://stackoverflow.com/questions/10969953/how-to-output-a-multiline-string-in-bash

## How to Reproduce

- Go to https://stackoverflow.com/questions/10969953/how-to-output-a-multiline-string-in-bash

## Expected behavior

The text should be white.

## Actual behavior

The text is black.

## Screenshots

![sshot-001](https://user-images.githubusercontent.com/36977733/121356075-0ed66480-c920-11eb-99ad-1b25507a4f25.png)

## System Information

- OS:  Win10
- Browser: Firefox 89
- Dark Reader Version: 4.9.33

**Comment by Gusted** [comment]
Hi @linsui!

Do you have any other settings enabled other than your javascript disabled? As the styles should just load fine and darkreader will be able to modify them.

Regards,
Gusted

**Comment by linsui** [comment]
It works on another profile so I guess there are some settings break it. The `var(--darkreader-text--black-700)` is unspecified so that the text is black. Do you know why? Thanks!

**Comment by Gusted** [comment]
> The `var(--darkreader-text--black-700)` is unspecified so that the text is black. Do you know why?

I don't know 🤷🏽‍♀️ Can be for various reasons. But most likely that dark reader cannot get ahold of the styles that are being loaded and thus the default + overrides styles are being loaded.

**Comment by JosefLitos** [comment]
You could find quite a bunch of sites that don't invert the text color in firefox (in brave everything works). Some sites I found the same issue in:
https://fel.cvut.cz/cz/prestudent/studium-bakalarske.html
https://lbry.com/

**Comment by linsui** [comment]
I close this because I don't have the profile any more so that I can't reproduce it.

**Comment by JosefLitos** [comment]
What does it mean? What sort of profile do you need to reproduce this?
It is as simple as opening buggy page (lbry.com for instance) with dark reader enabled on firefox.

**Comment by linsui** [comment]
I don't know. I can only see this bug on one of my Firefox profiles and I don't have it anymore. I didn't find the setting causing this.

**Comment by JosefLitos** [comment]
I just tried it on mobile version of firefox and actually, it isn't there either. Do you use localcdn on firefox? As that is the only other addon I have on pc but not on my phone.

**Comment by linsui** [comment]
I use that. But there is no problem on my other profiles. By the way, it works for me on lbry.com. Maybe you can create another profile and see if problems go.

**Comment by PlusoneWang** [comment]
I fix this issue by clear all the browser memory cache of stackoverflow.
