### ISSUE TITLE
Vivaldi  hotkey issue

### ISSUE THREAD

**Issue by Donkeyfish87** [darkreader/darkreader#60]
Works great when I use this extension in the Vivaldi browser, but the hotkeys doesn't work.

I've tried to set the same hotkeys in Chrome and then they work just fine.

Probably not a very high priority to fix, rare browser and its not really broken, but might be good to know.

**Comment by RalphLesch** [comment]
This is a Vivaldi Issue, the hotkeys for extensions do not work in general, see [Vivaldi forum: Extension keyboard shortcuts not working](https://forum.vivaldi.net/topic/12606/extension-keyboard-shortcuts-not-working).

**Comment by krupenja** [comment]
Workaround, would be to set the hotkey in Vivaldi to global. Then it works.

**Comment by Gusted** [comment]
> Workaround would be to set the hotkey in Vivaldi to global. Then it works.

This ^ We can't fix it on our end. It's browser bug that still presents 3 years later :/
