### ISSUE TITLE
Visibility issues on Webpage & Browser drop-down menus

### ISSUE THREAD

**Issue by NginUS** [darkreader/darkreader#600]
Would like to see a way to apply coloring to these menus. At least in this case one of them could end up easier to read.

Chrome menu:
![chromemenu](https://user-images.githubusercontent.com/8769067/42128609-6d4da408-7c7d-11e8-9bd9-cf423f7da28c.png)

Webpage menu:
![pagemenu](https://user-images.githubusercontent.com/8769067/42128610-6d60ab0c-7c7d-11e8-8da1-48075092d5f6.png)

**Comment by alexanderby** [comment]
Unfortunately a browser extension cannot do this.

**Comment by alexanderby** [comment]
...But the background of select control can be improved.

**Comment by Gusted** [comment]
![](https://i.imgur.com/1su184e.png)
