### ISSUE TITLE
[Feature Request] List sites in dark sites list in which Dark Reader is active

### ISSUE THREAD

**Issue by Elaborendum** [darkreader/darkreader#6002]
# Feature Request

## Is your feature request related to a problem? Please describe

I would like to keep track of the sites in the dark list in which I have activated DR to better manage them. I could maybe turn Dark Reader on in one of those sites for a short moment and forget about it later on, having no way to check if I have it active on that site, other than revisiting the site some time later.

## Describe the solution you'd like

There should be a list like the "(don't) invert these sites" list.

## Additional context

Maybe this already exists and I just missed it. I don't frequently use the new interface.

**Comment by Nicholaiii** [comment]
> 
> # Feature Request
> ## Is your feature request related to a problem? Please describe
> 
> I would like to keep track of the sites in the dark list in which I have activated DR to better manage them. I could maybe turn Dark Reader on in one of those sites for a short moment and forget about it later on, having no way to check if I have it active on that site, other than revisiting the site some time later.
> ## Describe the solution you'd like
> 
> There should be a list like the "(don't) invert these sites" list.
> ## Additional context
> 
> Maybe this already exists and I just missed it. I don't frequently use the new interface.
It exists
![image](https://user-images.githubusercontent.com/7280931/127971412-e98423c8-cfa0-4789-b18a-a1cbc3b4ea0a.png)

**Comment by Gusted** [comment]
That's the old UI, otherwise go to Settings -> Sitelist on the new UI.
