### ISSUE TITLE
www.wired.com does not work 

### ISSUE THREAD

**Issue by Joshuad2uiuc** [darkreader/darkreader#601]
<img width="1679" alt="screen shot 2018-07-01 at 9 45 40 pm" src="https://user-images.githubusercontent.com/21283480/42141624-3bb8a450-7d78-11e8-846a-2e6b8dc3b4ad.png">

**Comment by alexanderby** [comment]
It should work now. Unfortunately it flashes white sometimes, maybe some Wired code removes some Dark Reader style element, and a recent fix returns this style back.

**Comment by Gusted** [comment]
Why are some issues already solved a long time ago, but still open ¯\_(ツ)_/¯
