### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6024]
# Feature Request
Add ability to use website's own Dark mode if one is supported. If you are interested in this feature and would review a PR but don't want to spend your own time on it implement, I would gladly make an appropriate PR.

## Is your feature request related to a problem? Please describe

Some popular websites (GitHub, Reddit) provide native support for dark mode, but this dark mode can interact poorly with Dark Reader. I propose to add a setting for Dark Reader so that if website has native dark mode, then Dark Reader just activates this native dark mode.

It is already possible to acheive a similar eddect by disabling Dark Reader on such sites and using site settings and/or using external content scripts, but this feels clunky and inconvenient.

## Describe the solution you'd like

Dark reader alredy has a way to store custom CSS for each website, I propose adding a way to add custom JS for making sure user Dark Reader state and website preferences state match. Specifically, Dark Reader will need a way to specify scriplets for the following scenarios:
 1. Save a setting to site-specific place when user interacts with Dark Reader UI
 2. Read a setting from a site-specific place (e.g., when Dark Reader is installed for the first time)
 3. Detect when a site writes a new setting value to its site-specific place (e.g., when user disables dark reader via site's own settings, Dark Reader should not present confusing info)

## Additional context

Some websites store dark mode prefs in cookies, some in local storage. Dark reader can easily access them 

Reddit dark mode pref is stored in cookie named "USER" and can be easily be retreived like so:
```
JSON.parse(atob(document.cookie.match(/USER=[a-z0-9]+/i)[0].substring("USER=".length))).prefs.nightmode
```
This is basically what "scriplet" for Reddit for scenario 2 would look like. Alternatively, the same thing with `browser.cookies` API would look a lot cleaner, if you decide to use it.

**Comment by Gusted** [comment]
dup #1285
