### ISSUE TITLE
Export a CSS file with the current settings

### ISSUE THREAD

**Issue by riverocdavidb** [darkreader/darkreader#604]
I'm working in my personal website and could be very useful that the extension let you download all generated CSS in a single file with the current settings,  (eg: _style-dark-reader.css_) or a .zip file with all  the CSS associated. eg: 

**anydomain.any-styles**
    _mainstyles-dark-reader.css_
    _layout-dark-reader.css_
    _design-dark-reader.css_
    _maindark-reader.css_
    _navdark-reader.css.css_
    _subpage-dark-reader.css_

I love the chrome extension, nice work guys! 

@alexanderby  I saw your  #602  commit and It looks great but what do you think about this feature request?

**Comment by alexanderby** [comment]
I had similar thoughts for caching the results and speeding up future loads. Unfortunately many websites work in different ways: have many inline styles, styles hidden in Web Components, changing styles dynamically.

If you want to make multiple themes for your website, have a look at CSS variables or SCSS and LESS preprocessors.

This script will give you all the current Dark Reader styles (except those in web components)
```javascript
Array.from(document.querySelectorAll('.darkreader')).map((n) => n.textContent).join('\n');
```

**Comment by riverocdavidb** [comment]
Oh man, thanks for your suggestion, I really apréciate it!

**Comment by XanderLuciano** [comment]
Well that doesn't work for every mode, but this sure was a quick way to generate 60-80% of a basic dark theme for my site! Thanks x2

**Comment by Marr11317** [comment]
Sorry for that, but how (or where) do you run that script?

**Comment by XanderLuciano** [comment]
Hit F12, paste in the console tab.

**Comment by HackedBeat** [comment]
Recently, I needed to retrieve the styles generated by DarkReader. Unfortunately, the @alexanderby 's [script](https://github.com/darkreader/darkreader/issues/604#issuecomment-406237559) did not work for me.

So, I wrote my own script to fix it. I'll just leave it here:

```js
[...document.querySelectorAll(".darkreader")]
  .flatMap(stylesheet => [...stylesheet.sheet.cssRules])
  .map(rule => rule.cssText)
  .filter(Boolean)
  .join("\n")
```

**Comment by azharuniverse** [comment]
@HackedBeat solution is the only solution that worked for me. for some reason 

doing darkreader.enable() works fine on my local system but doesn't work on production

**Comment by alexwh** [comment]
The above script didn't work in Firefox for me, citing a `SecurityError: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet` error (even after disabling `security.fileuri.strict_origin_policy`). Running the script in Chrome and copying the static rules back into Firefox worked fine, though.

**Comment by saschanaz** [comment]
>The above script didn't work in Firefox for me

I can confirm the issue and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1631047

**Comment by Gusted** [comment]
#3120 Will add official support for this.

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted

**Comment by phseiff** [comment]
@Gusted Is there a corresponding function for that in the js module as well? I'm asking because if there was, I would run it in a headless browser in my website builder to automatically keep the css up-to-date with my website (it's a static site).

**Comment by Gusted** [comment]
Hi @phseiff!

Thanks for the suggest, I've made up a PR(#3872) for this to be exposed to the API.

Regards,
Gusted

**Comment by phseiff** [comment]
Thanks for the PR!
I'm using DarkReader with the PR you suggested since yesterday, and it works wonders. Allowed me to reduce my websites loading time by around 2 seconds by emulating DarkReader with selenium and extracting the CSS.

**Comment by Gusted** [comment]
Hi @phseiff!

That's great to hear!

Regards,
Gusted

**Comment by aranapatona** [comment]
> Recently, I needed to retrieve the styles generated by DarkReader. Unfortunately, the @alexanderby 's [script](https://github.com/darkreader/darkreader/issues/604#issuecomment-406237559) did not work for me.
> 
> So, I wrote my own script to fix it. I'll just leave it here:
> 
> ```js
> [...document.querySelectorAll(".darkreader")]
>   .flatMap(stylesheet => [...stylesheet.sheet.cssRules])
>   .map(rule => rule.cssText)
>   .filter(Boolean)
>   .join("\n")
> ```

Uncaught DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
    <anonymous> debugger eval code:2
    <anonymous> debugger eval code:2
[debugger eval code:2:27](chrome://devtools/content/webconsole/debugger%20eval%20code)

**Comment by e-t-l** [comment]
> Hello!
> 
> In the next update of Dark Reader 4.9.16 you can export it to CSS File 🎉 This can trough the following steps:
> 
>     * Click Dark Reader icon.
> 
>     * Click Dev tools (in the bottom-right corner).
> 
>     * Click Preview new design.
> 
>     * Click on settings in the popup
> 
>     * Click on Manage Settings
> 
>     * Click on Export Dynamic Theme
> 
> 
> Regards, Gusted

Does this still work / are these instructions still correct? I'm using the DR in the new design layout, and after clicking Settings I do not see anything like "Export Dynamic theme" anywhere.....

**Comment by Artemako** [comment]
> If anyone else comes here with the same question, as of v4.9.99 the instructions are:
> 
>     1. Open the DR popup
> 
>     2. Click on "See all options"
> 
>     3. Click on "Fonts and more"
> 
>     4. Click on "Export Dynamic theme"

@e-t-l, I'm sorry, but if it's not too much trouble, can you take skin shots of the stages?
I don't see the "See all options", I see "All settings" instead, and there's no "Fonts and more" anywhere in it.

**Comment by e-t-l** [comment]
> I'm sorry, but if it's not too much trouble, can you take skin shots of the stages?
> I don't see the "See all options", I see "All settings" instead, and there's no "Fonts and more" anywhere in it.

Is this what your DarkReader popup looks like? If not, you might still be using the old layout, which you can change under advanced settings (where exactly is described elsewhere in this repo). The "See all options" button is the one underneath Theme and Mode in the screenshot.

![Image](https://github.com/user-attachments/assets/d1742697-3951-4871-a3b9-590a3327b5e7)

**Comment by Artemako** [comment]
> Is this what your DarkReader popup looks like?

No, my DarkReader (Version 4.9.99) looks different in both Firefox and Chrome. I'll try to find out how to change the layout. 
Could this be due to the fact that I didn't donate to the project?

![Image](https://github.com/user-attachments/assets/29174c28-7195-42ee-81d9-43e17293751c)![Image](https://github.com/user-attachments/assets/68b0e05f-cb75-48d7-847d-b4c284f4955c)![Image](https://github.com/user-attachments/assets/7670dd48-2760-4066-8279-1fa302c0019b)

**Comment by hilbix** [comment]
"Export Dynamic Theme" apparently was removed quite a time ago (as I found out the hard way):

- https://github.com/darkreader/darkreader/discussions/12741#discussioncomment-11652519
- https://github.com/darkreader/darkreader/issues/13#issuecomment-2126082174

It now looks like this:

<img width="427" height="787" alt="Image" src="https://github.com/user-attachments/assets/1855c189-f2c0-4739-ac9b-1acb11ce2bd6" />
