### ISSUE TITLE
Why is the Safari extension so far behind the Chrome one, and why isn't it open source?

### ISSUE THREAD

**Issue by jpike88** [darkreader/darkreader#6042]
Question above.

Loving the plugin otherwise, my eyes thank you!

**Comment by Gusted** [comment]
I cannot really comment on this one as Safari isn't under my maintenance, but it's a separate code base due to how safari _was_ programmed, but nowadays supports webextension which this open-source one is based on and is tracked at #4493

**Comment by jpike88** [comment]
Maybe that extension can be part of this repo's deployment/release artifacts? I can build it ok but for noobs it might be a lot to take in.
