### ISSUE TITLE
marketplace.visualstudio.com incorrect text color

### ISSUE THREAD

**Issue by Sregey** [darkreader/darkreader#605]
[link to bad page](https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio#overview)

![image](https://user-images.githubusercontent.com/15161054/42380823-d9fd42fc-8137-11e8-9005-90c5c3b53e90.png)

**Comment by Sregey** [comment]
If i turn off and turn on Dark Reader, text color will be correct

**Comment by krupenja** [comment]
I think this depends on Chromium version. I get this problem with Chrome Stable 67 but not with Chrome Canary 69.

**Comment by alexanderby** [comment]
Works OK now.

**Comment by spikespaz** [comment]
This issue should be reopened, this problem persists. What is previously in the developer tools CSS thingy is incorrect. What it should be is this:

```css
marketplace.visualstudio.com

CSS
.details-tab {
  color: ${rgba(51, 51, 51, 0.9)} !important;
}
```

Here is what it looks like after the change:

![image](https://user-images.githubusercontent.com/12502988/60940467-709f7700-a290-11e9-8fe3-144e8dcbddf8.png)
