### ISSUE TITLE
[Broken Website] linuxmint.com

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#6057]
# Broken Website
## Website
https://www.linuxmint.com/

## Expected behavior
Background changed to darker colour

## Actual behavior
Background is an unbearably bright shade of green.

## Screenshots
![image](https://user-images.githubusercontent.com/22572406/122588269-76fc1780-d091-11eb-8ddf-50c8c70d9565.png)

## System Information
- OS: Windows
- Browser: Firefox 89.0.1
- Dark Reader Version: 4.9.33

**Comment by Gusted** [comment]
Yeez, what a old structure site for such a popular distro among beginners. If they see this - Hire me to fix this site, I might even do it for free - I can't stand this to my eyes.
