### ISSUE TITLE
[Feature Request] Cool / Warm Color Tone Slider

### ISSUE THREAD

**Issue by Enteleform** [darkreader/darkreader#606]
Currently, some of the color schemes that Dark Reader creates end up clashing in terms of coolness/warmth.

```
Left:   some neutral-grey Stylish theme

Right:  Dark Reader
  Brightness:  off
  Contrast:    -30
  Sepia:       off
  Grayscale:   off
```
![2018-07-02_05-05-10](https://user-images.githubusercontent.com/10906415/42386412-6cb0ac04-810d-11e8-94f1-e6ac42531acc.png)

In the example above; the page background has a cool slate-grey color set, but the text is on the warmer side & seems out of place.

My proposal is to implement a slider where leftmost is cool, center is neutral, and rightmost is warm. This could potentially replace the `Sepia` & `Grayscale` settings as well.

These would be the results of adjusting said slider (*with varying amounts of tone applied throughout the range of the slider*):

![darkreader](https://user-images.githubusercontent.com/10906415/42387831-a01d4922-8111-11e8-836c-5d7318a29845.png)

**Comment by Gusted** [comment]
Hey!

Will dynamic color pickers [First picture](https://darkreader.org/blog/v4-9/) Solve this issue? As their isn't a good efficient implementation in my eyes.

Regards,
Gusted
