### ISSUE TITLE
[Notice] Chrome now supports native dark scrollbars

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#6060]
See https://mspoweruser.com/google-chrome-scrollbars-get-dark-mode/#:~:text=In%20a%20bid%20to%20make,implementation%20of%20the%20Dark%20Mode.

I just noticed this today, and thought it was dark reader until doing research, since I know there is quirks with trying to make an actual dark scrollbar with CSS (mainly button disables not theming correctly), but I guess that's nothing to worry about now.

**Comment by Gusted** [comment]
Mainly a dup of https://github.com/darkreader/darkreader/issues/5850 ?

**Comment by TheAlienDrew** [comment]
> Mainly a dup of #5850 ?

Only sorta, because I'm pretty sure these dark scrollbar's only take affect when dark mode is turned on for the system, but I could be wrong.

**Comment by Gusted** [comment]
> because I'm pretty sure these dark scrollbar's only take affect when dark mode is turned on for the system, but I could be wrong.

Yeah, but we still override them and can force them with `color-scheme: dark` which is a discussion within #5850.

**Comment by TheAlienDrew** [comment]
Ah gotcha, nice.

**Comment by Gusted** [comment]
Anyway, thanks for the notice.
