### ISSUE TITLE
ALL sites OFF by default

### ISSUE THREAD

**Issue by PwrSrg** [darkreader/darkreader#6061]
Hello,

I **LOVE** the extension!  It is by far the **BEST** and **SMARTEST** Dark Mode extension ever created.

**BUT...**

Is there **_ANY WAY_** to have dark mode **OFF** for "ALL sites" **_by default_**, instead of **ON** for ALL sites _by default_??Because I mostly want to use this on the 20 or 30 sites that I visit every week, **_NOT_** every single site on the web!

Right now, **_EVERY_** site I visit, I have to "Toggle current site" FIRST to see if the site is already "dark".  _THEN_ if itisn't, I toggle it _BACK_ to dark mode.  But if it IS already pretty dark, OR the site just didn't look right in dark mode, then I leave it OFF.  But right now, it's behavior is the **_opposite_** of what I would like.

I hope you understand what I mean, but I would be very surprised if you have not received this exact request before.  I tried to find a similar question, but couldn't find one.  If this is _NOT_ currently possible, then I will change this to a **Feature Request**.

Thanks!

**Comment by Gusted** [comment]
Yeezus - so many caps and bold. 

Also it's just an option in the UI. Either settings -> Enable by default
![image](https://user-images.githubusercontent.com/25481501/122616999-fd592f00-d07a-11eb-86e6-f64a61ee49b8.png)

Or Site list -> Invert listed only
![image](https://user-images.githubusercontent.com/25481501/122617043-0e09a500-d07b-11eb-8a60-a0f2e14c49c8.png)

**Comment by PwrSrg** [comment]
Yeezus, I always use them for **_EMPHASIS_**, exactly how they were _designed_ to be used.  😄

Anyways, that looks _exactly_ like what I am looking for, but I don't see "settings" _anywhere_.  (better??)

![image](https://user-images.githubusercontent.com/711603/122617273-907d6f00-d051-11eb-8a19-daaf040179cb.png)

**Comment by Gusted** [comment]
> Anyways, that looks _exactly_ like what I am looking for, but I don't see "settings" _anywhere_. (better??)

See latter:
![image](https://user-images.githubusercontent.com/25481501/122617509-eebf4780-d07b-11eb-8bc6-b50603e784a4.png)

**Comment by PwrSrg** [comment]
Wow, and you _immediately_ **closed** this without a _real answer_??  🤔

OK, I will try that _workaround_ instead.  😕

Thanks.  Kinda.

**Comment by Gusted** [comment]
> Wow, and you _immediately_ **closed** this without a _real answer_??

Uhm, I gave you the answer. However we currently have 2 UI's which I never know of any user which they have. So I commented both instructions to either be the first one or the other one for both UI's.

> OK, I will try that workaround instead.

In the back-end it will toggle the same option. It's just different naming between the UI's.

> Thanks. Kinda.

Happy to help?
