### ISSUE TITLE
[Broken Website] ProtonMail

### ISSUE THREAD

**Issue by saegl5** [darkreader/darkreader#6065]
# Broken Website
## Website
https://mail.protonmail.com/u/0/inbox

## How to Reproduce
Click on "New message"

## Expected behavior
I would expect the From box to be dark

## Actual behavior
The From box is light

## Screenshots
![image](https://user-images.githubusercontent.com/63764270/122628637-30082500-d085-11eb-98a6-9c7d5a8408a8.png)

## System Information
- OS: macOS
- Browser: Brave 1.25.73
- Dark Reader Version: 4.9.33

## Additional context
n/a

**Comment by arche-dev** [comment]
Can I know what theme your using?

**Comment by saegl5** [comment]
hi @arche-dev
Snow

**Comment by arche-dev** [comment]
Done :D #6066
