### ISSUE TITLE
Dark reader causing flashing on local development website even when toggled off?

### ISSUE THREAD

**Issue by WilsonCWong** [darkreader/darkreader#6067]
**Question**
So, this is a bit strange. I'm currently developing a website with Next.js and Chakra UI. When I create a deployment build and serve it, the site has flashing elements whenever I refresh.

![GjgsSIZUqM](https://user-images.githubusercontent.com/7454084/122629649-7c4a6980-d073-11eb-94f2-e6ceb01b6410.gif)

The strange part is that when I turn off the Dark Reader extension (by turn off, I mean disable it in the browser), this behavior stops. It still happens even when the extension is disabled for the site or when the extension is toggled off in the settings. I have to disable the extension or uninstall altogether to get this to stop happening. Does anyone have any clue what's going on here?

**Comment by arche-dev** [comment]
What happens when you turn it off on the extension?
![image](https://user-images.githubusercontent.com/66189242/122629780-02d06c80-d0af-11eb-8ce4-01d0ac6ca427.png)

**Comment by WilsonCWong** [comment]
@arche-dev It still happens weirdly enough.
![SrxHlBKjHl](https://user-images.githubusercontent.com/7454084/122629821-a9e3e280-d074-11eb-8608-d716f4ff6680.gif)

**Comment by arche-dev** [comment]
> @arche-dev It still happens weirdly enough.
> ![SrxHlBKjHl](https://user-images.githubusercontent.com/7454084/122629821-a9e3e280-d074-11eb-8608-d716f4ff6680.gif)

Maybe create a fresh firefox profile with DR and see if it happens?

**Comment by WilsonCWong** [comment]
> Maybe create a fresh firefox profile with DR and see if it happens?

Yup, still happening even with a fresh Firefox profile. Also happening on Chrome and Edge as well, though it doesn't flash nearly as bad.

**Comment by arche-dev** [comment]
Huh that's weird DR shouldn't be doing anything if its off, gonna have to summon @Gusted for this one

**Comment by Gusted** [comment]
> Huh that's weird DR shouldn't be doing anything if its off, gonna have to summon @Gusted for this one

![Have I been summoned!](https://media1.tenor.com/images/7e220874eb29a1b9bfcd50f6136cc068/tenor.gif?itemid=19735106)


@WilsonCWong Could you give me a example code? So that I can investigate it locally?

**Comment by WilsonCWong** [comment]
@Gusted 
Sure! Here is an example project I plucked from the `chakra-ui` repo: [next-js.zip](https://github.com/darkreader/darkreader/files/6680486/next-js.zip)

Reproduction steps:
1. Unzip project
2. Run `cd next-js`
3. Run `yarn` or `npm install` to install dependencies
4. Run `yarn build` or `npm run build` to create a build
5. Run `yarn start` or `npm run start` to serve the build
6. Go to `localhost:3000`, toggle off Dark Reader, and start refreshing. You'll notice it flashing.

**Comment by Gusted** [comment]
I cannot get the issue reproduced. Does the issue by any chance reproduce when dark reader is uninstalled?

**Comment by WilsonCWong** [comment]
> I cannot get the issue reproduced. Does the issue by any chance reproduce when dark reader is uninstalled?

It works fine when Dark Reader is uninstalled. Even with my excessive F5ing, there is no flashing. However, the moment I reinstall Dark Reader, the flashes start occurring immediately.

**Comment by Gusted** [comment]
> > 
> 
> It works fine when Dark Reader is uninstalled. Even with my excessive F5ing, there is no flashing. However, the moment I reinstall Dark Reader, the flashes start occurring immediately.

Hmm, we only had issues with flashing on older version of dark reader, are you on 4.9.33?

Also how does the devtools look like when it's flashing? Which elements are exactly being changed.

**Comment by WilsonCWong** [comment]
> Hmm, we only had issues with flashing on older version of dark reader, are you on 4.9.33?
> 
> Also how does the devtools look like when it's flashing? Which elements are exactly being changed.
Yeah, I'm 4.9.33. The devtools is actually blank when the flashing occurs, which means the flashing occurs before the browser dev tools can even read the HTML. From what I've seen, it's mostly anything wrapped with an `a` tag or `input` elements like `textarea`. I've attached a .gif below showing the process and how it disappears after Dark Reader is removed.

![xZM4jSvIK5](https://user-images.githubusercontent.com/7454084/122639978-c5b9a980-d0b1-11eb-9c2f-565c9366c278.gif)

**Comment by Gusted** [comment]
My best guess is that the fallback style is creating a little overhead which is to prevent white-flashes. Nothing really to be done here. As I've noted when I made that patch that I rather have a better chance of preventing the white-flash than making sure that non-darkened site aren't getting it. Also it's in my eyes not that big of a deal - as it's not a permanent change.

**Comment by WilsonCWong** [comment]
That's fair, though I find it rather odd that DR is applying styles when the extension is toggled off. Not a huge issue for me though now that I know what's happening. It may affect some developers though, since I thought this was a bug with the server-side rendering on my site. I spent a bit of time trying to fix it, and I almost ruled DR out as the problem when it still happened after toggling it off. Luckily, I decided to wipe my browser and try again, which is how I finally found out. 

I think if it's possible for the fallback styles to be disabled when the extension is toggled off, that'd be a good compromise.

**Comment by Gusted** [comment]
> That's fair, though I find it rather odd that DR is applying styles when the extension is toggled off.

> I think if it's possible for the fallback styles to be disabled when the extension is toggled off, that'd be a good compromise.

This is a limitation which I somehow try to fix. We at this moment cannot dynamically enable/disable scripts to be injected. That's something for #3921 which allows us to dynamically register content scripts and also unregistered them - But with the upcoming manifest v3 it's going to be a hard take to reliably control it. - thereby you also have sites that are being disabled that are dark, but are still slow to apply a dark theme whereby a extension has a little priority and can fix this.

**Comment by WilsonCWong** [comment]
Sounds good, I hope it works out. I'll close the issue since there's not much that can be done at this moment. It thankfully doesn't happen during development so it doesn't really affect me now that I know about it. Thanks for the help!
