### ISSUE TITLE
[Broken Website] NBA.com stream seek bar is invisible

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#6083]
# Broken Website
## Website

https://www.nba.com/game/mil-vs-bkn-0042000217?watch

## How to Reproduce

Once you go to the link, press on watch, and select TNT on the list of providers. 

## Expected behavior

The seek bar should be visible below the video.

## Actual behavior

The seek bar goes completely invisible, and its impossible to understand the progress of the stream.

## Screenshots

Dark reader ON:

![image](https://user-images.githubusercontent.com/60446763/122687612-04c43800-d235-11eb-8214-147a29e55cea.png)

Dark reader OFF:
![image](https://user-images.githubusercontent.com/60446763/122687616-0db50980-d235-11eb-9580-c5db8ede1050.png)

## System Information

- OS:  Windows 10
- Browser:  Edge Stable
- Dark Reader Version:  4.9.33

**Comment by jenabaivab** [comment]
@Gusted is this not applicable? 
I can close this issue if you want

**Comment by Gusted** [comment]
Paid service, so I cannot access it. In such caes Il leave it open for anyone to have a look at it and tackle the issue themself.

**Comment by jenabaivab** [comment]
@Gusted Is it okay if I share the credentials to you via email? Temporary password till its fixed

**Comment by Gusted** [comment]
> @Gusted Is it okay if I share the credentials to you via email? Temporary password till its fixed

That's possible. Please make sure you send it to right email `williamzijl7@hotmail.com` it's the same one as linked on [my profile](https://github.com/Gusted)

**Comment by jenabaivab** [comment]
@Gusted ah nevermind. It seems you need an Indian VPN to access it anway. NBA doesn't allow league pass bought in one country to be used in another. :(

**Comment by arche-dev** [comment]
> @Gusted ah nevermind. It seems you need an Indian VPN to access it anway. NBA doesn't allow league pass bought in one country to be used in another. :(

indian VPN? why though 🤔

**Comment by jenabaivab** [comment]
> > @Gusted ah nevermind. It seems you need an Indian VPN to access it anway. NBA doesn't allow league pass bought in one country to be used in another. :(
> 
> I guess it's for preventing account sharing stuff

Actually its because of licensing. The NBA league pass in India is ridiculously cheap, so people tend to use VPNs and buy it from India, and watch it from USA. To prevent this, NBA just went ahead and region locked game pass.
