### ISSUE TITLE
[Feature Request] Clear Indication of Current Site Toggle

### ISSUE THREAD

**Issue by doubledgedboard** [darkreader/darkreader#609]
Unless I'm missing something, toggling dark reader on or off per site only changes the setting, it does not have any corresponding visual indicator showing whether or not it's enabled.

For certain sites it can be extremely difficult to tell if it's on or off just by the colors of the site changing.

This is a request to add something to make it plainly obvious whether or not it's toggled on for the current site. Using the same ON/OFF style toggle used for the global setting would even be fine.

**Comment by JasonBoy** [comment]
like the dark mode on youtube, it's really hard to tell if the extension's dark mode is toggle on or not

**Comment by doubledgedboard** [comment]
As a follow-up to this, some sites experience extreme performance penalties with this enabled, and it's still very hard to tell whether or not it's enabled for the site.

I was having serious problems with page performance on twitch.tv combined with chat and extensions like ffz and bttv, and eventually discovered somehow my per-site settings had reset and the extension was re-enabled.

**Comment by alexanderby** [comment]
It is going to look like for Safari version
<img width="646" alt="darkreader-safari-preview" src="https://user-images.githubusercontent.com/9638588/47909583-69260380-dea1-11e8-91b4-acdd900aa4d2.png">

**Comment by doubledgedboard** [comment]
I'm using Chrome, will I see a similar change?
