### ISSUE TITLE
[Broken Website] Sentry Documentation

### ISSUE THREAD

**Issue by BANOnotIT** [darkreader/darkreader#6091]
# Broken Website
## Website
https://docs.sentry.io/product/cli/installation/

## Expected behavior
Have white text on dark backround

## Actual behavior
Some light blocks and paragraphs backgrounds. Code block heads are light.

## Screenshots
![изображение](https://user-images.githubusercontent.com/11363215/122816995-1282c780-d2e0-11eb-80d0-c61ce9a05086.png)
Here's first light block header is light and others are as expected.

![изображение](https://user-images.githubusercontent.com/11363215/122817099-31815980-d2e0-11eb-9baa-cd2a4d21ba4d.png)
Here's quote block which is all light while in original it has dark left border and slightly colorful background

![изображение](https://user-images.githubusercontent.com/11363215/122817233-5675cc80-d2e0-11eb-8075-f079c3ecebda.png)
Here's start of the article. Search box has light block above it but on original page there's no blocks. First two paragraphs have background while there's none in original version.

## System Information

- OS: Linux
- Browser: FF 89
- Dark Reader Version: 4.9.33

## Additional context
Dynamic theme is used

**Comment by arche-dev** [comment]
#6097 👍
