### ISSUE TITLE
[Broken Website] AhaDNS website text is unreadable

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#6094]
# Broken Website
## Website

https://ahadns.com/dns-stamps/

## How to Reproduce

Pretty straightforward website

## Expected behavior

Text should be visible

## Actual behavior

Text is submerged in the black background

## Screenshots

![image](https://user-images.githubusercontent.com/60446763/122831282-47eedb80-d307-11eb-9a24-79723d3ce620.png)

## System Information

- OS:  Windows 10
- Browser:  Edge stable
- Dark Reader Version:  4.9.33

**Comment by arche-dev** [comment]
Fixed in #6095 :+1:
