### ISSUE TITLE
[Broken Website] There is likely invalid in https://docs.python.org/3/

### ISSUE THREAD

**Issue by Python-37** [darkreader/darkreader#6118]
# Broken Website
## Website

https://docs.python.org/3/ and some other language pages (like https://docs.python.org/zh-tw/3/) are same.

## How to Reproduce

Just go to https://docs.python.org/3/ , and the page may behave like this , if not, refresh for several times.

## Actual behavior

Navigation and main zone in the page may not in dark background.

## Screenshots

![網頁擷取](https://user-images.githubusercontent.com/19404655/123197486-23009100-d4de-11eb-8e54-a4a282814222.jpeg)

## System Information

- OS:  Windows 10
- Browser:  Microsoft Edge based on  Chromium 91
- Dark Reader Version:  4.9.33

**Comment by Gusted** [comment]
Go search other issues, #835
