### ISSUE TITLE
[Broken Website] windy.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#6131]
https://www.windy.com/51.713/17.314?49.767,17.150,7

Meteogram is not readable when darkreader is ON. 

![20210624-1624559741](https://user-images.githubusercontent.com/9846948/123315297-db085b00-d52b-11eb-9581-b19d8eb64d21.png)

![20210624-1624559755](https://user-images.githubusercontent.com/9846948/123315300-dc398800-d52b-11eb-815c-49cfcf180c5c.png)

**Comment by Morgan1er** [comment]
Hi,

I know it is marked as fixed and closed but I still get a problem with the "temperature" line inside the graph, I can't see the numbers. 

I run Dark Reader 2.0.3 with Safari 17.2.1 on macOS Sonomo 14.2.1

Here are 2 screenshots:
<img width="1210" alt="Capture d’écran 2024-01-21 à 23 26 26" src="https://github.com/darkreader/darkreader/assets/92629032/98a64f74-1402-4aa3-9dae-731d1761aec0">
<img width="1206" alt="Capture d’écran 2024-01-21 à 23 26 05" src="https://github.com/darkreader/darkreader/assets/92629032/8f86c9ec-ea10-4be7-a7c8-2956db04704a">
