### ISSUE TITLE
[Broken Website] Quillbot lot of buttons and text missing

### ISSUE THREAD

**Issue by jenabaivab** [darkreader/darkreader#6135]
# Broken Website
## Website

https://quillbot.com/premium

## Expected behavior

Buttons and text to be visible

## Actual behavior

Not visible buttons

## Screenshots

![image](https://user-images.githubusercontent.com/60446763/123417321-422e1a00-d5d5-11eb-8141-ad09d0fdc31d.png)

![image](https://user-images.githubusercontent.com/60446763/123417343-49552800-d5d5-11eb-9ce2-75d4f6df0830.png)

## System Information

- OS:  Windows 10
- Browser:  Edge stable
- Dark Reader Version:  4.9.33

**Comment by Gusted** [comment]
Fixed by #6078
