### ISSUE TITLE
[Broken Website] Discord login QR code broken

### ISSUE THREAD

**Issue by KaBankz** [darkreader/darkreader#6137]
# Broken Website
## Website
[https://discord.com/login](https://discord.com/login)

## How to Reproduce

  - Go to [https://discord.com/login](https://discord.com/login)
  - Try to scan the QR code using the discord app
  - QR code fails to scan because the border was turned black

## Expected behavior

QR code successfully scans

## Actual behavior

QR code fails to scan

## Screenshots

Dark reader disabled QR code theme (works)
![default](https://user-images.githubusercontent.com/20971850/123474978-c4fca800-d5c8-11eb-84cb-146cef9d971f.png)
Dark reader enabled QR code theme (broken)
![darkreader](https://user-images.githubusercontent.com/20971850/123475074-e52c6700-d5c8-11eb-849a-0e45ee77cdcf.png)

## System Information

- OS:  Windows 10
- Browser:  Firefox Dev 90.0b12
- Dark Reader Version:  4.9.33

**Comment by arche-dev** [comment]
Dark reader should be disabled on that site according to [`dark-sites.config`](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config) file:

```
discord.com/app
discord.com/channels
discord.com/developers
discord.com/invite
discord.com/login    <- this one here
discord.com/register
```

**Comment by KaBankz** [comment]
That's strange, I didn't manually enable it for discord, and in the extension pop-up, it didn't say it was on the global dark list.

I just uninstalled and reinstalled dark reader and now it does say discord is on the global dark list. I guess my extension wasn't in sync with the global dark list.

Before
![Screenshot 2021-06-26 003503](https://user-images.githubusercontent.com/20971850/123502144-e3d65b00-d617-11eb-9afe-5ee224929f57.png)

After reinstalling
![Screenshot 2021-06-26 004457](https://user-images.githubusercontent.com/20971850/123502150-f05ab380-d617-11eb-88cf-fa7bebafa443.png)
