### ISSUE TITLE
[Broken Website] surveymonkey.com

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#6146]
# Broken Website
## Website
https://www.surveymonkey.com/r/22XZM8K
https://www.surveymonkey.com/r/JTFGWWD

*(Note: I have nothing to do with either of these surveys.)*

## How to Reproduce
When I have an issue with a site being compatible with Dark Reader, I usually just fix it myself.  But for this site, I'm getting odd behaviour, so I'm writing an issue report.

Let's start with: https://www.surveymonkey.com/r/22XZM8K

With DR's Dynamic Dark mode, in Firefox with a dark theme, and the OS with a dark theme, this is how it looks for me:

![upload - screenshot - www surveymonkey com](https://user-images.githubusercontent.com/7672848/123574221-4e0c0e80-d784-11eb-97bb-a9581bdb5563.png)

As you can see (or, in this case, *can't see*), the radio button for each option is missing.

Here is another screenshot, this time with the second option selected:

![upload - screenshot - www surveymonkey com](https://user-images.githubusercontent.com/7672848/123574221-4e0c0e80-d784-11eb-97bb-a9581bdb5563.png)

You probably noticed that there is no difference.  Exactly.

When you get to page 6 in the survey, "Future Directions", it gets very confusing because all of the radio buttons are missing, and that's key for the UI:

![u2-screenshot - www surveymonkey com](https://user-images.githubusercontent.com/7672848/123574518-d8547280-d784-11eb-9478-2d37f063d6fc.png)

Let's try a different survey on their site that uses a different template:  https://www.surveymonkey.com/r/JTFGWWD

Again, the radio buttons are missing:

![u3 - screenshot - www surveymonkey com](https://user-images.githubusercontent.com/7672848/123574861-79432d80-d785-11eb-94be-fd725d759753.png)

But now things are going to get real weird.  Follow these steps:
1. Set DR to use the default Dynamic Mode for all sites.
1. Open a new tab with https://www.surveymonkey.com/r/JTFGWWD
1. Notice the radio buttons are all missing.
1. Disable DR using the DR toolbar button dropdown pane.
1. Refresh the page with https://www.surveymonkey.com/r/JTFGWWD
1. Notice that the radio buttons appear.
1. Enable DR using the DR toolbar button dropdown pane.
1. Notice that the radio buttons are still present even with DR on even though they were missing in step 3 above!  Everything should be the same, but the behaviour is inconsistent.

## Expected behavior
Consistent behaviour with all elements, including radio buttons, visible.  The selected answer should always be indicated visually.

## Actual behavior
Inconsistent behaviour with radio buttons often missing.

## Screenshots
See above.

## System Information

- OS: Win7 with a dark theme
- Browser: Firefox 89.0.2
- Dark Reader Version: 4.9.33 w/v5 beta UI enabled

**Comment by Gusted** [comment]
Someone needs to get a talk about how to not detect high-contrast:

![image](https://user-images.githubusercontent.com/25481501/123680711-51b59900-d849-11eb-9d17-897b47aeaf27.png)

So it's detect a different background-color and just slam that `is-high-contrast` attribute, which for no reason will dissapear the radio buttons. 
![image](https://user-images.githubusercontent.com/25481501/123681003-8f1a2680-d849-11eb-8c80-6bf682cf06f0.png)

I will be sending a email to surveymonkey.com as even with a somehow valid use-case the radio buttons will just be gone for you, very funny. And for now create a CSS Fix for this stupid behavior. 

Regards,
Gusted

**Comment by Gitoffthelawn** [comment]
@Gusted Thanks for the help on this one.  They certainly don't make programmers like they used to. :)

That's some ugly, ugly code they have there.

What's the story with the rendered output being different as you go through the "8 steps" section I provided?

**Comment by Gusted** [comment]
> What's the story with the rendered output being different as you go through the "8 steps" section I provided?

Probably, once again the buttons are being hidden by them. Or some other mechanism related.

**Comment by Gitoffthelawn** [comment]
Thanks.  Just curious... is there an ETA for the next AMO release?  If so, I might put together another pull request with fixes for a popular site.

**Comment by Gusted** [comment]
Not really any ETA, it would be released when we feel enough sufficient changes had been done
