### ISSUE TITLE
[Broken Website] virustotal.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#6150]
https://www.virustotal.com/gui/file/84b818bf3c06297fb59306bfde8a7afa2d3564483bac7b85ae8f0a4212bc7367/detection

https://www.virustotal.com

![20210628-1624898216](https://user-images.githubusercontent.com/9846948/123672879-21b5c800-d840-11eb-9cbd-e118582af765.png)
![20210628-1624898232](https://user-images.githubusercontent.com/9846948/123672883-224e5e80-d840-11eb-8ed1-499adfda6ebd.png)
![20210628-1624898243](https://user-images.githubusercontent.com/9846948/123672884-224e5e80-d840-11eb-9ec7-2b718dc6a363.png)
![20210628-1624898286](https://user-images.githubusercontent.com/9846948/123672886-22e6f500-d840-11eb-827a-3e01202a9acd.png)
![20210628-1624898301](https://user-images.githubusercontent.com/9846948/123672888-22e6f500-d840-11eb-9c64-f3f535faa9e7.png)
![20210628-1624898319](https://user-images.githubusercontent.com/9846948/123672889-237f8b80-d840-11eb-89d2-6bb3b121ea4e.png)

**Comment by Gusted** [comment]
#4682 Reported already, but because I wanted to leave that issue open after some PR would be merged(to ensure to have a good indication what's going on). But it seems like we are missing some implementation... thanks for the reminder, Il be looking in to it and close this as a dup of #4682
