### ISSUE TITLE
[Broken Website] Broken on python docs website

### ISSUE THREAD

**Issue by Avnsx** [darkreader/darkreader#6164]
# Broken Website
## Website

https://docs.python.org/

## How to Reproduce

Just go on the website. The white background stays white. If it doesn't just refresh the site / browse through it and load it up a couple times, it will eventually get stuck having a complete white background.

## Expected behavior

Turning the plain white background to a darker color.

## Actual behavior

It just keeps staying plain white, while the left navigation sidebar only turns dark.

## Screenshots

![screenshot](https://i.imgur.com/C16Kg4t.png)

## System Information

Windows 10, latest chrome version & dark reader version.

**Comment by Gusted** [comment]
Just search the issue tracker for the site - I've marked this issue as duplicated too many times by now.

**Comment by arche-dev** [comment]
> Just search the issue tracker for the site - I've marked this issue as duplicated too many times by now.

That's a lot of dupe issues o_O anyways, I think the issue you're looking for is #835 @Avnsx

**Comment by Avnsx** [comment]
> Just search the issue tracker for the site - I've marked this issue as duplicated too many times by now.

It's amazing how you've not fixed the site since https://github.com/darkreader/darkreader/issues/835 literally 3 years passed already

**Comment by Gusted** [comment]
It's amazing how people complain, this wasn't a first priority issue over a lot issues. And I only just recently found the root cause on accident. Which was a very clever problem and current a PR is open to fix the issue.
