### ISSUE TITLE
How can I use Darkreader's beta or dev release?

### ISSUE THREAD

**Issue by max-programming** [darkreader/darkreader#6172]
**How can I use Darkreader's beta or dev release?**
I have seen screenshots of darkreader's future version on [its blog post](https://darkreader.org/blog/v4-9-16/) which looks and feels quite nice and I really want to use it. Like this

![image](https://user-images.githubusercontent.com/51731966/124303919-a2e2c700-db80-11eb-9516-2c402fc81567.png)

**Comment by Gusted** [comment]
Read the blog post... Give some attention to the very first ~4 sentences.

**Comment by max-programming** [comment]
> Read the blog post... Give some attention to the very first ~4 sentences.

Thanks for answering!
