### ISSUE TITLE
[Feature Request] Automatic activation via sunrise and sunset

### ISSUE THREAD

**Issue by Gian-Marco-Del-Freo** [darkreader/darkreader#6181]
# Feature Request

## Is your feature request related to a problem? Please describe
It is tiring to continuously activate and deactivate the extension in order not to tire the eyes

## Describe the solution you'd like
It would be wonderful if like Apple the extension found and turned off based on sunrise and sunset. This is a system that has been in use for a long time and the implementation would be great!

**Comment by Gusted** [comment]
Hi @Gian-Marco-Del-Freo!

Are you using a non-safari browser? Only the safari extension cannot do this.

Regards,
Gusted

**Comment by Gian-Marco-Del-Freo** [comment]
> Hi @Gian-Marco-Del-Freo!
> 
> Are you using a non-safari browser? Only the safari extension cannot do this.
> 
> Regards,
> Gusted

I'm actually using Chrome on windows 10

**Comment by Gusted** [comment]
Ah because you were referencing Apple I got a bit confused.

But, good news this is already possible.


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Now you can find the sunrise/sunset settings under -> Settings -> Automation.

Regards,
Gusted

**Comment by TheRakeshPurohit** [comment]
make the new design as default

**Comment by Gusted** [comment]
It's still a preview, and the new design is probably going to change quite a bit. It's  not definite design, thus still behind a toggle.

**Comment by lorenzofanchi-enpicom** [comment]
Will the Safari extension get this ability at some point?
