### ISSUE TITLE
[Feature Request] support ! mark in site list 

### ISSUE THREAD

**Issue by jerryc05** [darkreader/darkreader#6185]
# Feature Request

## Is your feature request related to a problem? Please describe
I want to invert some pages (but not all) under (e.g.) `xxx.com`, be it `xxx.com/whitepages/......`. 

Note that I use "not invert listed" and I don't want to switch to "invert listed only" because I have other pages that I don't wish to invert.

## Describe the solution you'd like
Support a syntax like `!xxx.com/whitepages` in the "not invert listed" list, meaning that I want to invert pages under xxx.com/whitepageswhile keeping other pages under xxx.com intact.

Here is what I expect the `not invert listed` to look like:
```
xxx.com
!xxx.com/whitepages
```

## Additional context
This might have been addressed somewhere but I cannot find any documentation.

**Comment by Gusted** [comment]
#373 is the tracking issue, and the current PR #2517 has support built-in for this syntax.
