### ISSUE TITLE
[Dynamic] Text is blue on Wikipedia with Timeless theme

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#619]
OK, this one needs a few steps to repro:

1. Create an account on Wikipedia.
2. Log into Wikipedia and go to Preferences -> Appearance.
3. Change theme to Timeless.
4. Open any page.

Text is in blue color. Looks OK with Filter and Filter+. Workaround for Dynamic theme: set Sepia to +50.
![image](https://user-images.githubusercontent.com/26354715/42728123-dc3bdd28-87bb-11e8-80a8-2c5d6af5f6aa.png)

**Comment by alexanderby** [comment]
It's because this theme uses dark blue color, which is transformed into light blue by Dark Reader.

Go to preferences, click **Custom CSS** and add
```css
p {
    color: black;
}
```

This will override text color making it black, then Dark Reader will transform it into white (light brown).
