### ISSUE TITLE
[Feature Request] Render local vector graphics dark

### ISSUE THREAD

**Issue by legendofa** [darkreader/darkreader#6193]
# Feature Request

## Is your feature request related to a problem? Please describe

Every time i open a vector image with firefox for example `.svg`, it is displayed as is, even with Darkreader toggled on.

## Describe the solution you'd like

Website-like behaviour of Darkreader when directly opening a vector image.

## Additional context

This is for example useful for reviewing generated diagrams late at night.

**Comment by Gusted** [comment]
Just wrap the svg around `<html> <svg>...</svg> </html>` I already end up with more than 50 checks to just make some functionality use-able. Too much of a hassle to get it working and making it maintainable is a nightmare.
