### ISSUE TITLE
[BUG] Replace with title

### ISSUE THREAD

**Issue by gregsdennis** [darkreader/darkreader#6211]
# Bug Report

## Describe the bug

The sites `github.com` and `github.community` are linked.  I have dark mode enabled through `github.com` so DarkReader is off, but this also turns off `github.community`, which is blinding.

## Steps to reproduce

- Go to github.com (congrats, you're probably there if you're reading this)
- Disable DarkReader for this site (blinding)
- Enable dark mode in your Github settings (that's better)
- Go to (e.g.) https://github.community/t/run-job-only-if-folder-changed/118292 (blinding)
- Feel the burn.

## Expected behavior

I would expect these sites to be controlled separately since they're on different domains.

## Actual behavior

They're configured together as if they were one site.

## System Information

Chrome - Version 91.0.4472.124 (Official Build) (64-bit)
Windows 10

- OS: 
- Browser: 
- Dark Reader Version: 

## Additional context

I've found performance issues while having DarkReader on with github, but that's a separate issue.  I prefer github's native dark mode anyway.

I understand that they should skin the `github.community` site to match user preferences, and I'll be raising that with them separately.

**Comment by gregsdennis** [comment]
I found where I can enable dark mode on the community site, but it still seems like they should be controlled separately, so this bug is still pertinent.

**Comment by Gusted** [comment]
Change the entry in your sitelist from `github.com` to `github.com$` It's fixed with #2517

**Comment by gregsdennis** [comment]
Thanks. Didn't realize those were RegEx.
