### ISSUE TITLE
[Broken Website] https://outlook.live.com/owa/

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6215]
# Broken Website
## Website
https://outlook.live.com/owa/ (This URL is the homepage for the site.)
https://outlook.live.com/mail/0/inbox (This URL is the one displayed once signed in to the site.)

## How to Reproduce
1. Visit the site. (See screenshots for the original and the Dark Reader versions of the site.)
2. Create account / Use existing account.
3. Sign in.

## Expected behavior
The site displays correctly when using Dark Reader.

## Actual behavior
The site displays black text on a dark background when using Dark Reader.

## Screenshots
Original:

![outlook com-DR-disabled](https://user-images.githubusercontent.com/87130982/124942970-b56e5d80-dfd1-11eb-8b57-2f24eab8cafb.png)

Dark Reader:

![outlook com-DR-enabled](https://user-images.githubusercontent.com/87130982/124942941-aedfe600-dfd1-11eb-94d4-70a0fc734d26.png)

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210708091856)
- Dark Reader Version: 4.9.34

## Additional context
N/A

**Comment by Gusted** [comment]
Ah thanks for noticing,

It seems like we aren't correctly watching for "root" variables in the `<html>` element.

**Comment by DJ-Katalina** [comment]
Hey @Gusted, no problem! 😃

Thank you for being so prompt to answer comments and fix issues. I appreciate your helpfulness and easy going / easy to work with mindset.

I have been wanting to report a few issues with various sites and finally created an account on GH to do so.

I am looking forward to working with you in the future with any other issues I may find!

**Comment by Gusted** [comment]
#6217 should fully fix this issue.
 
 

> I have been wanting to report a few issues with various sites and finally created an account on GH to do so.
> 
> I am looking forward to working with you in the future with any other issues I may find!

Please don't hesitate to open up bug reports! I really love finding certain bugs and discover them.
