### ISSUE TITLE
[Broken Website] wiki.manjaro.org

### ISSUE THREAD

**Issue by piousdeer** [darkreader/darkreader#6216]
# Broken Website
## Website
https://wiki.manjaro.org/index.php/Main_Page
https://wiki.manjaro.org/index.php/Plymouth

## How to Reproduce

Visit any Manjaro Wiki page

## Expected behavior

Colors are inverted properly

## Actual behavior

Titles are black on black; cards, inline code and code blocks are not inverted

## Screenshots

![image](https://user-images.githubusercontent.com/31318219/124956453-36fdd400-e042-11eb-8ddd-280632358215.png)
![image](https://user-images.githubusercontent.com/31318219/124956481-3cf3b500-e042-11eb-9850-0471340e909c.png)

## System Information

- OS: Manjaro Linux
- Browser: Firefox 90
- Dark Reader Version: 4.9.34

## Additional context

uikit.min.css provides these colors which Dark Reader doesn't override for some reason.

**Comment by Gusted** [comment]
> uikit.min.css provides these colors which Dark Reader doesn't override for some reason.

They are being loaded cross-origin wrapped in a `@import url('[...]uikit.min.css')` and thus result in a error when trying to get the CSS of this. We currently do have any mechanism to handle that is kinda harder then it looks. Il give it a spin to see if I can trigger the right mechanism that should handle this.

**Comment by Gusted** [comment]
Thanks for reporting, #6218 should fix this issue.
