### ISSUE TITLE
[Broken Website] https://southpark.cc.com/

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6223]
# Broken Website
## Website
https://southpark.cc.com/

## How to Reproduce
Visit the site. (See screenshots for the original and the Dark Reader versions of the site.)

## Expected behavior
The site needs to be optimized for Dark Reader.

## Actual behavior
The site isn't optimized for Dark Reader.

## Screenshots
*** (I used Imgur for these screenshots due to the length and overall size of the files.) ***

Original:

https://imgur.com/qVrKbCt

Dark Reader: (I have selected a few examples where Dark Reader is incorrectly trying to apply fixes and other areas where Dark Reader is correctly applying fixes. Selected examples are highlighted in red.)

https://imgur.com/qnIoLQ8

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210708091856)
- Dark Reader Version: 4.9.34

## Additional context
N/A

**Comment by Gusted** [comment]
This requires some more investigation so I'll be looking into this one later this day/week.

**Comment by Gusted** [comment]
Seems to be my analysis is _correct_, and stumbled onto a possible browser bug which both happens in Chromium and Firefox.

Il be fixing it for now with CSS, and might end up later filling browser bug.

**Comment by DJ-Katalina** [comment]
The site now looks amazing! Great job! Thank you very much! 👍
