### ISSUE TITLE
Crashes some webpage scripts

### ISSUE THREAD

**Issue by jmbromley** [darkreader/darkreader#623]
Darkreader does not appear to be sufficiently isolated.  In particular it can cause webpage scripts to crash with the error `Uncaught TypeError: Cannot read property 'childNodes' of undefined`.

Two examples are:

* The javascript real-time debugger used by elm-reactor (part of the developer tools from http://elm-lang.org.

* The app hosted at https://ellie-app.com/

To reproduce the problem.

1. Activate Dark Reader

2. Visit https://ellie-app.com/

3. Open the browser's javascript console.

4. Accept the terms and conditions to launch the app.

The result is that the app crashes while loading as can be seen from the javascript console.

Without Dark Reader the app runs without problem, and this is not the only app to have this problem, so it is definitely something Dark Reader is doing.

**Comment by alexanderby** [comment]
Unfortunately this is how Dynamic mode works. When it meets a `<style>` element somewhere in the DOM tree, it adds it's own style element with changed colors right after the source. So Ellie App gets a wrong DOM element by index and crashes.

I don't see the way to fix it, it is important to preserve style sheets order and leave the sources untouched.

Currently try using static mode for this page.

**Comment by Gusted** [comment]
Don't see the errors anymore :shrug:
