### ISSUE TITLE
Ignore a div from being styled using api mode (i embedded darkreader.js on my website)

### ISSUE THREAD

**Issue by azeemh** [darkreader/darkreader#6230]
I am using darkreader on my website.

I load `<script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.26/darkreader.min.js"></script>` and i successfully use it with 
```
<script>
        DarkReader.setFetchMethod(window.fetch)
        DarkReader.enable({
                brightness: 95,
                contrast: 111,
                sepia: 0
            });
</script>
```
            
There's an element in my source that I want to exclude or ignore from darkreader style overrides. however trying the recommended solution has not worked for me on my local machine. 

> Yes, adding the attribute `class="darkreader"` into the style element should ignore it completely from getting styled.
> 
> Regards,
> Gusted

_Originally posted by @Gusted in https://github.com/darkreader/darkreader/issues/4144#issuecomment-729896113_

I have an element that that can be any user chosen color background. my app outputs the brighter colors with a black text foreground. yet if the user chooses a brighter yellow colored background it keeps re-coloring the div and making the text white, even though my app already color matched this particular div. How can i use darkreader but skip only these divs? I want to just add a class that ignores it from getting styled. I will be adding this into the source code of my website, not from browser tools/extension.

Please let me know if the modifier or class name has been updated or otherwise how I should proceed. Thank you!

**Comment by Gusted** [comment]
HI @azeemh!

Such thing to just skip a few elements aren't possible, the attribute is specifically for `<style>` and `<link rel="stylesheet">`, so if it's possible you can add a new `<style class="darkreader user-generated">` element with the user-generated content within that style and dark reader won't touch it from darkening them. 



> `<script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.26/darkreader.min.js"></script>`

You can better use 
```diff
- <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.26/darkreader.min.js"></script>
+ <script src="https://cdn.jsdelivr.net/npm/darkreader@latest/darkreader.min.js"></script>
```

**Comment by azeemh** [comment]
i ended up writing my own dark mode for my website. thanks for the plugin help however the overrides simply don't work.
