### ISSUE TITLE
[Broken Website] https://us.creative.com/ & https://support.creative.com/

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6233]
# Broken Website
## Website
https://us.creative.com/
https://support.creative.com/

## How to Reproduce
https://us.creative.com/

Visit the site. (See screenshots for the original and the Dark Reader versions of the sites.)

https://support.creative.com/ - (You can choose any product on this webpage and it will exhibit this issue. I have included an example of how to navigate the page to display this issue.)

Part 1:

1. Visit the site. (See screenshots for the original and the Dark Reader versions of the sites.)
2. Click on the SOUND BLASTER Tile / Button under the Search by Product Category header. (Webpage will refresh and open additional options below.)
3. Click on the G-Series link in the first column under SOUND BLASTER.
4. Click on the Sound BlasterX G5 link in the second column under PLEASE SELECT YOUR PRODUCT.
5. The product image will appear on the right side on the second column. (Here you will see the white background on the product image.)

Part 2:

6. Click on the product image. (This will take you to the product support page.) (Here you will see the white background on the product image as well.)

## Expected behavior
https://us.creative.com/
1. The product category images to the right of the SELECT YOUR CATEGORY section should be optimized for Dark Reader. (Just below the main rotating product image near the top of webpage.) (See Shot 2.)
2. The product images near the bottom of the page should be optimized for Dark Reader. (See Shot 2.)
3. The logo image in the top left corner, after you scroll down the page a bit, should be optimized for Dark Reader. (See Shot 4.)

https://support.creative.com/
1. The logo image in the top left corner should be optimized for Dark Reader. (See Shot 6.)
2. The product image should have a dark background on both the main support page as well as the product support page. (See Shots 6 & 8.)

## Actual behavior
https://us.creative.com/
1. The product category images to the right of the SELECT YOUR CATEGORY section aren't optimized for Dark Reader. (Just below the main rotating product image near the top of webpage.) (See Shot 2.)
2. The product images near the bottom of the page aren't optimized for Dark Reader. (See Shot 2.)
3. The logo image in the top left corner, after you scroll down the page a bit, isn't optimized for Dark Reader. (See Shot 4.)

https://support.creative.com/
1. The logo image in the top left corner isn't optimized for Dark Reader. (See Shot 6.)
2. The product image doesn't have a dark background on both the main support page as well as the product support page. (See Shots 6 & 8.)

## Screenshots

*** (I used Imgur for these screenshots due to the length and overall size of the files.) ***

Shot 1: Original

https://imgur.com/VtOTgL7

Shot 2: Dark Reader (Issues with the site are highlighted in red.)

https://imgur.com/aTZkfuM

Shot 3: Original

https://imgur.com/1HHKh1F

Shot 4: Dark Reader (Issues with the site are highlighted in red.)

https://imgur.com/flOCtBM

Shot 5: Original

https://imgur.com/8vIHacm

Shot 6: Dark Reader (Issues with the site are highlighted in red.)

https://imgur.com/R7g3fEe

Shot 7: Original

https://imgur.com/kLr7ihj

Shot 8: Dark Reader (Issues with the site are highlighted in red.)

https://imgur.com/N9i9dTR

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210709094609)
- Dark Reader Version: 4.9.34

## Additional context
N/A

**Comment by DJ-Katalina** [comment]
@Gusted

Can you provide any insight or input on the following questions?

(I am genuinely just asking questions, because I am trying to learn and understand what can and cannot be done through site fixes in Dark Reader. This is still all very new to me. I mean no disrespect or ungratefulness towards anyone. I appreciate any and all who contribute to help fix site issues that are reported.)

https://us.creative.com/
Issues 1 & 2: I read arche-dev's comments on these issues. Is there a solution that allows the images to display correctly without any inversion?

Issue 3: The fix implemented by arche-dev has indeed fixed the original issue reported with the logo image in the top left corner, after you scroll down the page a bit. However, the fix actually broke the logo image when you are at the top of the page without having scrolled yet. The fix for the logo image kind of reversed the original issue. Is there a solution that will make both versions of the logo display correctly?

https://support.creative.com/
Issue 1: The logo image in the top left corner is working as expected. *Solved*
Issue 2: The product images now have a dark background on both the main support page and the product support page. However, all the images are inverted. Is there a solution that allows the images to have a dark background and display correctly without any inversion?

Thank you for your help!

**Comment by Gusted** [comment]
> Issues 1 & 2: I read arche-dev's comments on these issues. Is there a solution that allows the images to display correctly without any inversion?

Depends, which images. Certain images are only fix-able by inversion but others should be leave as-is.

@arche-dev I've only checked certain pages, did I merge a PR that's inverting legitimate images?







> ). The fix for the logo image kind of reversed the original issue. Is there a solution that will make both versions of the logo display correctly?

will be fixed.

> Issue 2: The product images now have a dark background on both the main support page and the product support page. However, all the images are inverted. Is there a solution that allows the images to have a dark background and display correctly without any inversion?

I don't see any inverted images... Give a moment to check it out.

**Comment by arche-dev** [comment]
>  I've only checked certain pages, did I merge a PR that's inverting legitimate images?

I don't think so 🤷‍♂️

**Comment by DJ-Katalina** [comment]
@Gusted,

To address your question to arche-dev, I did ask to have certain product images and product category images fixed that either cannot be fixed or should have been left alone to begin with. Can either of you @arche-dev or @Gusted please revert the requested fixes to these product images and product category images that were made by me in error. (The original requested fixes for the images were completely my fault and my mistake. After Gusted explained what can and cannot be done with images in another issue, I now understand the limitations. I apologize for any and all extra work and wasted time that my lack of knowledge has caused in regards to this requested fix and corresponding revert.)

To address your fix for the logo image on the main site here: https://us.creative.com/, the fix is working as intended. Please don't change a thing. 🤣

To address the logo image on the support site here: https://support.creative.com/, the logo image is still exhibiting the original issue (See here: https://imgur.com/MEn9Axz). I believe that a separate fix for this site alone needs to be done to correct just this issue. Thoughts?

Thanks again to you both and for your understanding.

**Comment by arche-dev** [comment]
> To address your question to @arche-dev, I did ask to have certain product images and product category images fixed that either cannot be fixed or should have been left alone to begin with. 

I think they meant they meant this:

![image](https://user-images.githubusercontent.com/66189242/125181025-605c6280-e1f0-11eb-89ad-3e48b80bc4fc.png)

**Comment by DJ-Katalina** [comment]
@arche-dev,

That image is one of the examples that I do mean to have the fix reverted. I don't think the image needs to be ineverted at all. It just needs to have the text corrected if possible.

**Comment by DJ-Katalina** [comment]
@arche-dev,

Please also revert this entire fix on https://support.creative.com/ that caused the images to be inverted:

![lffgdjkgldkj](https://user-images.githubusercontent.com/87130982/125181352-891d3180-e1c9-11eb-9ea9-c4d025e2c453.png)

I believe that the original state these images were in prior to me requesting the change is best.

**Comment by arche-dev** [comment]
> @arche-dev,
> 
> Please also revert this entire fix on https://support.creative.com/ that caused the images to be inverted:
> 
> ![lffgdjkgldkj](https://user-images.githubusercontent.com/87130982/125181352-891d3180-e1c9-11eb-9ea9-c4d025e2c453.png)
> 
> I believe that the original state these images were in prior to me requesting the change is best.

Do you also want to revert the fix on the product page?

**Comment by DJ-Katalina** [comment]
> Do you also want to revert the fix on the product page?

If you mean the same product images as shown above that are on each product support page. then yes. Please?

Thank you again.

**Comment by arche-dev** [comment]
> > Do you also want to revert the fix on the product page?
> 
> If you mean the same product images as shown above that are on each product support page. then yes. Please?
> 
> Thank you again.

this one?
[image](https://user-images.githubusercontent.com/66189242/125153525-dfe02800-e143-11eb-9129-cacd5b540d04.png)

**Comment by DJ-Katalina** [comment]
> 
> 
> > > Do you also want to revert the fix on the product page?
> > 
> > 
> > If you mean the same product images as shown above that are on each product support page. then yes. Please?
> > Thank you again.
> 
> this one?
> ![image](https://user-images.githubusercontent.com/66189242/125181539-4e30f300-e1f5-11eb-9360-bbbbcead942f.png)

Exactly!

**Comment by arche-dev** [comment]
> > > > Do you also want to revert the fix on the product page?
> > > 
> > > 
> > > If you mean the same product images as shown above that are on each product support page. then yes. Please?
> > > Thank you again.
> > 
> > 
> > this one?
> > ![image](https://user-images.githubusercontent.com/66189242/125181539-4e30f300-e1f5-11eb-9360-bbbbcead942f.png)
> 
> Exactly!

Done :D

**Comment by arche-dev** [comment]
> @arche-dev,
> 
> That image is one of the examples that I do mean to have the fix reverted. I don't think this specific image needs to be inverted at all. It just needs to have the text corrected if possible, exactly how you fixed this image here:
> 
> Before:
> 
> ![fsggfd](https://user-images.githubusercontent.com/87130982/125181198-24ada280-e1c8-11eb-8897-2a9c925f10f9.png)
> 
> Aftter:
> 
> ![fgfdklj](https://user-images.githubusercontent.com/87130982/125181251-abfb1600-e1c8-11eb-88bd-9784ea907d34.png)

Alds done #6250 c:

**Comment by DJ-Katalina** [comment]
@arche-dev,

I owe you a BIG thank you for your patience and kindness for putting up with me and my mistakes!

THANK YOU! 😃

**Comment by DJ-Katalina** [comment]
@Gusted,

To address your fix for the logo image on the main site here: https://us.creative.com/, the fix is working as intended. Please don't change a thing. 🤣

To address the logo image on the support site here: https://support.creative.com/, the logo image is still exhibiting the original issue (See here: https://imgur.com/MEn9Axz). I believe that a separate fix for this site alone needs to be done to correct just this issue. Thoughts?

**Comment by DJ-Katalina** [comment]
@Gusted

https://support.creative.com/ - Everything is working fine on this site now.

https://us.creative.com/ - The top left logo image, while you are still at the beginning of the page before scrolling down, is now messed up again. --- (At this point, we have tried to apply multiple fixes to these top left logo images on both reported sites. However, every time we apply one fix, it somehow interferes with the other fixes and the end result is that something else is wrong. Is it even possible to fix all of the logo images at once to have them all display correctly? If not, then let us just put this matter to rest. I do not want to keep burdening you and others with this dilemma.)

![lkfjdlkfdjgfdklj](https://user-images.githubusercontent.com/87130982/125195233-6d8e4700-e21a-11eb-9b77-edc9fe9cd523.png)
