### ISSUE TITLE
[Broken Website] https://www.phonescoop.com/

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6234]
# Broken Website
## Website
https://www.phonescoop.com/

## How to Reproduce
Visit the site. (See screenshots for the original and the Dark Reader versions of the site.)

## Expected behavior
The site needs to be optimized for Dark Reader.

## Actual behavior
The site isn't optimized for Dark Reader.

## Screenshots
*** (I used Imgur for these screenshots due to the length and overall size of the files.) ***

Original:

https://imgur.com/1FhqIUs

Dark Reader: (Several examples of issues with the site are highlighted in red.)

https://imgur.com/wjFkDQ0

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210709214006)
- Dark Reader Version: 4.9.34

## Additional context
The site has a very unorthodox layout to it. (Possibly the worst and most crappiest layout I have ever seen.) The panels at the top and on the sides are hard to explain and understand why they even exist or if they serve a purpose. The main issue with the site is that it is a gigantic mess with Dark Reader. The entire site needs a Dark Reader optimization overhaul. I have highlighted several examples of issues on the site in the second screenshot. You also need to go through each of the links: Phones, News, Carriers, Android and iOS on the navigation panel on the top left to fully comprehend how atrocious each section is and the entire site overall.

**Comment by arche-dev** [comment]
I don't see anything wrong with it?

**Comment by DJ-Katalina** [comment]
Hi @Gusted.

Thanks for the fixes on the site. It looks a lot better with the top and side panels not visible anymore.

I wanted to ask you if it is possible to implement something like a top-level fix that would correct the two main issues that still effect all sub-pages and images on the site. (Not sure if a top-level fix is something that exists or even can be used vs. manually having to implement a fix for every individual thing.)

1. The top and side panel fix you implemented only affects the main page. All sub-pages still exhibit the initial issue. (The site most likely has tens of thousands of individual sub-pages that include news stories, cell phone reviews, product specification pages, etc...)

2. Thousands of images that need to be fixed so that they have a dark background. (This includes images of cell phones, manufacturer and carrier logos, Android OS and iOS logos, images used in each news story, and any other random images that the site may use.)

**Comment by Gusted** [comment]
1 will be fixed in a minute
2 Isn't possible, this is way how images work and are being displayed via the web.

**Comment by DJ-Katalina** [comment]
Thanks again Gusted!

I appreciate the explanation on the images request. Very good to know!

**Comment by DJ-Katalina** [comment]
Hey @Gusted.

All of the side panels on the main page look great now.

However, all sub-pages are still exhibiting the same original behavior with the side panels not being fixed. I saw where you mentioned that you did a global fix, but it didn't work. Unless my understanding is flawed?

You can literally go to the main page on the site here: https://www.phonescoop.com/ and click on any link to a news article, new phone, or any link in the main navigation panel on the left side of the site to see that the issue is still happening.

Here are a few examples of various pages on the site that show the issue is still happening:

https://www.phonescoop.com/site/tou.php
https://www.phonescoop.com/carriers/carrier.php?c=2
https://www.phonescoop.com/phones/phone.php?p=6420
https://www.phonescoop.com/articles/article.php?a=22552

**Comment by DJ-Katalina** [comment]
🙌 Praise be to the great @Gusted! 🙌

The site looks fantastic now.

🖐️ But Wait! There's More! 🖐️

The global site fix is working finally! 😄

In all seriousness though, thank you so much for fixing this site!
