### ISSUE TITLE
[Performance] nzherald.co.nz very slow with darkreader enabled

### ISSUE THREAD

**Issue by drbluetongue** [darkreader/darkreader#6237]
# Performance Issue
Slow page performance on nzherald.co.nz with darkreader enabled
## Website
https://www.nzherald.co.nz/

## How to Reproduce

Go to the homepage or any subpage, it's very slow.
Turn off darkreader for this website, performance is as expected
## Performance Profiler

[Here's both enabled and disabled profiles on a fresh FF 89 profile](https://github.com/darkreader/darkreader/files/6794842/profiles.zip)

## System Information

Firefox Nightly and Stable 89
- OS: 
- Browser: 
- Dark Reader Version: 
Windows 10, Android. DR 4.9.34

Works fine with dark reader disabled. Webrender enabled.

**Comment by Gusted** [comment]
Hi!

You have to use profiler.firefox.com to profile any site, the older ones via the devtools are worthless for extensions as they give little-no information about specific details and events.

Regards,
Gusted

**Comment by drbluetongue** [comment]
Here's the profiler link for Darkreader enabled!

https://profiler.firefox.com/public/w9gkmk2x8myhjrns0hrh2eb35phjzxc9zjt75er/calltree/?thread=10%2C28&transforms=%3B&v=5&view=active-tab

**Comment by Gusted** [comment]
Ah great, you've stumbled on the same performance problem. It should be partially solved with #6241 Il be trying to get a "manager" in place that delay the analyzing of images, so it won't impact the loading time of the page as this images are not that critical anyway.

**Comment by drbluetongue** [comment]
Thank you!
