### ISSUE TITLE
Google Translate extension tooltip white

### ISSUE THREAD

**Issue by Reliquat** [darkreader/darkreader#625]
Google traduction extension's popup which is displayed on text highlight is not well displayed by darkreader.
I tried to disable darkreader for the popup's class but I didn't find a way to apply it on all domains?

**Comment by alexanderby** [comment]
Seems like this extension injects it's stylesheet in a special way, and the Dark Reader doesn't see it.

I will add a support for a custom CSS in Dev Tools for Dynamic mode.
