### ISSUE TITLE
imdb.com - Body/#wrapper background is white

### ISSUE THREAD

**Issue by RavenDT** [darkreader/darkreader#626]
New to Dark Reader.  I opened up imdb.com and saw that the background was still a very bright white.  I tried to add custom code in the dynamic theme editor, but every time I try to use CSS or NO FILTER, it disappears when I hit apply.  Anyway, here's a screenshot of how imdb.com looks with a fresh install of Dark Reader:

![image](https://user-images.githubusercontent.com/5491569/42919591-ae58491e-8ae0-11e8-9280-168f392806cf.png)

I think the fix would involve altering either the body tag or the \#wrapper div or a combination of the two.  The rest of the content looks great, though.

**Comment by alexanderby** [comment]
Are you using some other extensions? For me the reason for this seems to be uBlock Origin, it injects it's style sheet making the background white. Strange.

**Comment by RavenDT** [comment]
Aye.  That would be the reason why.  I turned off uBlock Origin for IMDB and now it displays properly.

![image](https://user-images.githubusercontent.com/5491569/42956025-d81b23f4-8b4c-11e8-9b0f-4c48e311722d.png)

**Comment by alexanderby** [comment]
Well, I think it will be fixed by adding custom CSS support for Dynamic Fixes config.

**Comment by krystian3w** [comment]
`imdb.com#@#body#styleguide-v2:style(background-color: #e3e2dd !important; background-image: none !important;)` and you can turn on uBlock Origin.

uBlock Origin in this method remove background advertisement.

**Comment by Gusted** [comment]
Closing as ![](https://i.imgur.com/zYkYlJb.png) it already had been fixed in the latest version.
