### ISSUE TITLE
[BUG] huawei logging user out 

### ISSUE THREAD

**Issue by devrob20** [darkreader/darkreader#6275]
i cannot use darkreader on my Gateway HG659, it logs me out again.  the dark theme works, but my router doesnt like the code injections. for now i use darkmode flag in chrome, but it would be nice to have DR working in de future. 

i noticed that the password save option is also not working when i have DR on for my  routers 192. IP

# Bug Report

## System Information

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
Seems pretty much unrelated and if the router doesn't like any type of code injections or changes, we cannot do much about it. We cannot make dark reader silent to the webpage itself.

**Comment by devrob20** [comment]
well ok, but what would make it log out (and in chrome i noticed it also wont let me autofill the user/pass, even tough its in my setting/passwords) and on new incognito it wont let me save the router passw.  it logs in for 3 sec and then reloads the loginpage, as if DR was blocking some script. 

i cant debug it, its reloads in 3 sec so no time to capture or look with F12 tools.

**Comment by Gusted** [comment]
I don't have a clue, I don't have a huawei router. Nor have ever seen such condition. Especially the "doesn't save password" part is confusing as we cannot interfere with such browser implementations or other password managers. It's more likely some other issue.
