### ISSUE TITLE
[Feature request] Add support for OpenStreetMap

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#628]
Would be great to have support for https://www.openstreetmap.org similar to Google Maps.

**Comment by inthreedee** [comment]
I was able to get the map inverted by adding the following to Dev tools:

```
================================

openstreetmap.org

INVERT
#map

CSS
#map {
    background-color: ${#1b1b1b} !important;
}

================================
```

It's not a complete solution, as the login page still has bright background elements and I'm not sure how it looks if you sign in with an account.  But for casual use without an account, this seems to do the trick.

**Comment by Gusted** [comment]
Hey their!

#2292 Has been merged and will be available in the next update of Darkreader. 
Thanks for making a suggestion! If their are any issues or more Features to add. Feel free open a new issue.
