### ISSUE TITLE
[Broken Website] Chrome Web Store

### ISSUE THREAD

**Issue by MegN09** [darkreader/darkreader#6283]
<p>Dark Reader does not work on Chrome Web Store. The <a href="https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related">site</a> says that the browser (Google Chrome) has protected this site from the extension.</p>

<ul>
<li>OS: Windows 10</li>
<li>Browser: Chrome</li>
<li>Dark Reader Version: 4.9.34</li>
</ul>
<img src="![notcompatible](https://user-images.githubusercontent.com/87452907/126015439-5640085c-403b-4ad7-8873-bf0a6c615f2a.JPG)">

**Comment by Gusted** [comment]
> The site says that the browser (Google Chrome) has protected this site from the extension.

Pretty self-explained... the browser doesn't allow extension on those kind of sites to be modifying. And are so called "protected"
