### ISSUE TITLE
[BUG] Automation autochanges to system dark mode

### ISSUE THREAD

**Issue by k2helix** [darkreader/darkreader#6293]
# Bug Report

## Describe the bug
Hello, I'm trying to set the automation settings according to the time, and it works fine if I don't change the mode from Auto. However, if I manually set dark reader to On and then change it another time to Auto, it switches according to system dark mode

## Steps to reproduce
  - Switch to the new design
  - Select the automation according to time and select Auto.
  - Manually set dark reader to On
  - Switch to Auto again

## Expected behavior
The automation mode should switch according to time.

## Actual behavior
The automation mode sets to "according to system dark mode"

## System Information
- OS: Windows 10
- Browser: Firefox 90.0
- Dark Reader Version: 4.9.34 (Version 5 preview)

## Additional context
I don't know if this is really a bug or if it is expected to behave like this. If this is the case, then this would be more a kind of request for any option to change it.

**Comment by Gusted** [comment]
Dup of #3268
