### ISSUE TITLE
Vim-Vixen no invert on hit boxes

### ISSUE THREAD

**Issue by wviana** [darkreader/darkreader#630]
Hello, I'm a darkreader user and also a [vim-vixen](https://github.com/ueokande/vim-vixen/)

When I press `f` on Vixen I get a some hits boxes.

So I got the Vixen Source code and found this class `.vimvixen-hint`. I tried to place a `NO INVERT` in the *dev tools* with an `*` , but I think there is no way to apply a `NO INVERT` to all sites. Is there a URL for extensions ?

Could you help me to place this rule?

**Comment by robsmith11** [comment]
I am also looking for a solution to this.

On a related note, have you gotten "static" mode to work with Vim Vixen?  For me it just blacks out the entire screen.

**Comment by wviana** [comment]
Does someone could give us some tip of where does the config file is interpreted. Looked around but couldn't figure out.

**Comment by nonetrix** [comment]
I am still having this issue
