### ISSUE TITLE
[Feature Request] Option to disable enable-force-dark darkmode on sites that aren't blocked away from extensions

### ISSUE THREAD

**Issue by schockocraft** [darkreader/darkreader#6321]
# Feature Request

## Is this feature request related to a problem?

DarkReader is way more configurable and usable then Chromes internal Dark mode, but Dark reader doesn't work on all sites, for example The chrome web store. So i have to activate the internal dark mode to be able to use these without eye strain and the following headache. But as the enable-force-dark feature doesn't allow any further configuration (apart from the filter to use) it now interferes with all other pages for which i want to use DarkReader. 

Right now the way i use these extension-blocked pages is that i first go into chrome://flags/ then switch internal dark mode on, then restart the browser, then go to whatever site, then go back to switch off internal darkmode, then restart the browser again, and then finally continue with what i was doing before. It would be a very great feature if Dark reader could have a config toggled on to undo the internal dark mode changes before then applying it's own ones, that way the internal dark mode would work for the special sites, and don't interfere with normal sites.

**Comment by Gusted** [comment]
Not possible. Extensions don't have any control over the flags.
