### ISSUE TITLE
[Bug] Exclude SVG image from being turned into dark mode

### ISSUE THREAD

**Issue by NAPTheDev** [darkreader/darkreader#6325]
# Bug Report

## Bug Description
SVG in websites are images so please exclude them from being turned into dark mode, the inverted images look weird.

## Screenshot
![image](https://user-images.githubusercontent.com/74483690/126577335-0f343cf8-0c7d-412c-8b08-d2e7d6e88044.png)

## System Information
- OS: Windows
- Browser:  Chrome 91
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Intended behavior - report such bugs as broken websites if you think they are wrong in a particular case.
