### ISSUE TITLE
[Bug] Dark Reader breaks GottY and still affects the pages even toggle is off

### ISSUE THREAD

**Issue by TheCGDF** [darkreader/darkreader#6326]
# Bug Report

## Bug Description
Dark Reader breaks  GottY and still affects the pages even toggle is off.

## Steps To Reproduce
Open GoTTY page of VPS.

## Expected Behavior
![vivaldi_T12geNF5KA](https://user-images.githubusercontent.com/17256673/126613858-46b38798-e99b-43ab-af5e-6593da7c165e.jpg)

## Actual Behavior
![vivaldi_kjKyLqWUeb](https://user-images.githubusercontent.com/17256673/126613959-2fa1d590-098f-49a3-a278-2798632a0157.jpg)

The words will be shown in one line.

And even if I toggled off Dark Reader, this BUG still exists.
Only if I disabled Dark Reader, GottY will be shown correctly.

## System Information

- OS: Windows 10.0.17763.1039
- Browser: Vivaldi | 4.0.2312.33 (Chrome/91.0.4472.114)
- Dark Reader Version: 4.9.34

## Additional Context
https://github.com/darkreader/darkreader/issues/5932

**Comment by Gusted** [comment]
Dup of the mentioned issue #5932

**Comment by TheCGDF** [comment]
> Dup of the mentioned issue #5932

It's not totally duplicate because this issue refers to two BUG.

The another one is: Dark Reader still affects the pages even toggle if off.

**Comment by Gusted** [comment]
> The another one is: Dark Reader still affects the pages even toggle if off.

Intended behavior - and in this case it's the same underlying issue as #5932
