### ISSUE TITLE
[ruwix.com] needs a fix for Dynamic theme

### ISSUE THREAD

**Issue by freMea** [darkreader/darkreader#634]
App version | Browser
------------------ | ---- 
 4.6.0 | Chrome 65.0.3325.183

## Steps to reproduce

1. go to [https://ruwix.com/puzzle-scramble-generator/?type=rubiks-cube](https://ruwix.com/puzzle-scramble-generator/?type=rubiks-cube)
2. use Dynamic theme

## Results

Cube colors doesn't match the site with DR disabled. Add

```
ruwix.com

INVERT
.haromszorharmas
```
to dev tools really doesn't help. It darkens the original colors.

The only fix is open the Chrome dev tools select  `.fld1` and disable the css rule added by DR: `    background-image: url(blob:https://ruwix.com/eec6a51d-4192-4655-9d1d-8051c19304ae);`

**Comment by Gusted** [comment]
Thresholds where changed long time ago I don't see them inverted anymore.
