### ISSUE TITLE
[Broken Website] Bing.com tabs disappear

### ISSUE THREAD

**Issue by KibSquib48** [darkreader/darkreader#6341]
# Broken Website Report

## Website Address
Bing.com

## Steps To Reproduce
- Go to Bing.com
- Make sure one of the themes are enabled, or hover over the hamburger menu icon on the right

## Expected Behavior
Nothing special happens, the tab labels stay there.

## Actual Behavior
The tab labels disappear, but can still be clicked.

## Screenshots
dark reader on
![image](https://user-images.githubusercontent.com/33189136/126849659-aaa6d6bf-b430-4052-8166-6721dd275c81.png)
dark reader off
![image](https://user-images.githubusercontent.com/33189136/126849673-2ef985d1-10b2-4539-b260-e200ee7de2d7.png)

## System Information
- OS: Windows 11 22000.100
- Browser: Microsoft Edge Dev 93.0.957.0
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Hi @KibSquib48!

Do you have any special settings related to bing.com?

They are looking fine for me -
![image](https://user-images.githubusercontent.com/25481501/126870543-be32208e-e990-4412-a254-150e69149a95.png)

Regards,
Gusted

**Comment by KibSquib48** [comment]
Yes, but it does the same when I reset all of my custom settings
![image](https://user-images.githubusercontent.com/33189136/126873254-88951a81-5d14-4ef9-982a-8f1fe6d186c3.png)

**Comment by Gusted** [comment]
Do you by any chance use a custom theme of bing?

**Comment by KibSquib48** [comment]
> Do you by any chance use a custom theme of bing?

No

**Comment by Gusted** [comment]
It's really weird as the tabs don't have any particular things that other selectors don't have.

Is it the same situation if you create temporarily a new profile(`about:profiles`) and install dark reader on it?

**Comment by KibSquib48** [comment]
The same thing happens on a fresh Edge profile, and I can't test on my Firefox install since it doesn't have themes

**Comment by Gusted** [comment]
Hmm, edge. Last time I tried that out it crashed. Could you try something like Google Chrome or Chromium? Also why can't you test on Firefox due to bing theme? Are you using one then?

**Comment by KibSquib48** [comment]
> Also why can't you test on Firefox due to bing theme? Are you using one then?

no i mean bing has a built in themes feature but for some reason it's not available on firefox
![image](https://user-images.githubusercontent.com/33189136/126908910-16f6e437-257c-4bcd-98b8-a652641ab698.png)
I'm talking about these

also I did try in ungoogled chromium and the same thing happened
