### ISSUE TITLE
[Broken Website] Talkchess.com logging out after a few clicks

### ISSUE THREAD

**Issue by mvanthoor** [darkreader/darkreader#6349]
# Broken Website Report

## Website Address

talkchess.com

## Steps To Reproduce

- Log into the website with darkreader enabled. (Account needed; I'm willing to test.)
- Click around on the site.
- Within a few clicks, you're logged out.

## Expected Behavior

Obviously, the expectation is to stay logged in. I've been using Darkreader for a long time, and this broke very recently. No problem seen on other sites, as of yet.

## Actual Behavior

After logging in on talkchess.com, the site logs out after you start clicking around on the forums. After disabling darkreader, logging back in, and then browsing the site, it stays logged in.

## Screenshots

Screenshot not applicable.

## System Information

- OS: Windows 10, 21H1 
- Browser: Firefox 90.0.2
- Dark Reader Version: 4.9.34

- OS: Debian Linux 11, Bullseye 
- Browser: Firefox 78.12esr
- Dark Reader Version: 4.9.34

## Additional Context

This broke quite recently; within the last few days before 25-august-2021

**Comment by Gusted** [comment]
Hmm that's very weird behavior and I don't see why talkchess would log out as it seems to be cookie-based. It's more likely talkchess's developers can shed some more information on this behavior as I don't know how their code works and what could trigger this.

**Comment by mvanthoor** [comment]
I've been looking for a solution to this problem today, and stumbled on this issue:

https://github.com/darkreader/darkreader/issues/1173

I've switched the rendering mode from Dynamic to Filter+ (even though the DarkReader help says that it works poorly on Firefox...), and the logout-problem on Talkchess seems to be gone. I need to browse the site more (also using Firefox / DarkReader on Windows) to be definitive, but it seems the Dynamic mode does something which breaks cookie-based logins.

**Comment by mvanthoor** [comment]
PS: Filter+ breaks GitHub, at least in Firefox. (GitHub is set to light mode.) When switching between Filter, Filter+, Static and Dynamic, the GitHub page is completely black when Filter+ is set.
