### ISSUE TITLE
DarkReader injects style code when I edit website HTML

### ISSUE THREAD

**Issue by jeffstaple** [darkreader/darkreader#635]
Background: I edit a government website for my work. We use Microsoft SharePoint as the CMS . I do not have access to edit the website CSS directly, so occasionally I have to add <style> tags or style attributes in-line.

Issue: Whenever I edit a web page that has <style> tags or style attributes in the HTML body code, DarkReader injects new style code directly into my website code. I don't know what (if any) impact this could have on my website users, but I don't think your Chrome extension should behave this way regardless. At the very least, give me an option to turn this off. It's annoying to constantly need to delete this code.

The injected code looks like this:

<style class="darkreader darkreader--sync" media="screen" type="text/css">
/* DarkReader Styles I didn't ask for */
</style>

**Comment by alexanderby** [comment]
Dynamic mode observes web pages and when a new Link or Style element appears, it analyzes it and creates a copy with changed colors. It is the only way Dynamic mode can work properly. I didn't understand how your HTML editor works, if the code is separated from preview, you should not worry, but if Dark Reader modifies your code some way, please, disable the extension.
