### ISSUE TITLE
[Performance Issue] Firefox hangs when I hover or click on the toolbar icon

### ISSUE THREAD

**Issue by mt-empty** [darkreader/darkreader#6351]
# Performance Issue Report

## Website Address

It seems that the more heavy(more content on website) the more it hangs, such as this one https://www.youtube.com

## Steps To Reproduce

- Play a video on https://www.youtube.com such as https://www.youtube.com/watch?v=5qap5aO4i9A
- Click or Hover over the DarkReader icon.
- Notice Firefox hangs(freezes) for a few seconds

## Performance Profile

[profile](https://share.firefox.dev/3eRBMFh)

## System Information

- OS:  Ubuntu 20.04
- Browser:  Firefox
- Dark Reader Version:  4.9.34

## Additional Context
- Does this happen when Dark Reader is disabled? Nope
- Does this happen in other browsers? I only use it on Firefox
- Do you have hardware acceleration enabled? Yes, I turned it off `Firefox setting -> Performance`, same issue.

**Comment by Gusted** [comment]
Please fill out the form. The tittle and some vague additional context isn't working.

**Comment by mt-empty** [comment]
@Gusted Could you check now?

**Comment by Gusted** [comment]
Hmm the profile should be coming from https://profiler.firefox.com as the built-in one is not more worth than garbage IMO. 

But for me it seems like to not have any CPU spikes after the initial load which at most gives 2,5-5% extra CPU usage which is IMO acceptable. My own profile seems to not show any spikes or slowdowns other than some well-known slowdowns my images, which is solved by #6259 in the next release.

**Comment by mt-empty** [comment]
I uploaded my profile and updated my issue

**Comment by Gusted** [comment]
Thank you for using the profiler.firefox.com 

However in this profile, I don't see much code being run other than the site itself and some internal Firefox code that could explain the CPU spike, especially if Dark Reader is causing it. However I did find the graphics is being heavy which is most likely the video, you could try enabling some `about:config` options like `gfx.webrender.all` and `gfx.webrender.compositor`. 

When you have this CPU Spikes does any entry within `about:performance` stands out, when it happens?

**Comment by mt-empty** [comment]
Thanks for following up.

I enabled both `gfx.webrender.all` and `gfx.webrender.compositor`, no improvement.

When this issue occurs, Firefox hangs, including `about:performance`, its really hard to figure out which process stands out. 
 
In the following profile I had both `gfx.webrender.all` and `gfx.webrender.compositor` enabled, I had the performance open in a separate window and I also included the images https://share.firefox.dev/3BOqL1m

**Comment by Gusted** [comment]
It's really weird as still the only "big" chunk is video rendering which dark reader cannot effect, as you can see:
![image](https://user-images.githubusercontent.com/25481501/127147109-2c1de7c8-7008-4a84-a17c-8b3c4a1977c9.png)
It stands out in the graph, whereby, the graph for all javascript code including dark reader, is quiet and not something you expect for a CPU spike.
![image](https://user-images.githubusercontent.com/25481501/127147159-a599fbe3-46a4-44af-8cca-dfe8fb05de45.png)

> its really hard to figure out which process stands out.

It should show under "battery impact" a high value when the hangs happens or actually before the hang as 99/100 time the culprit can already be seen before firefox goes into a hang/deadlock.

Regards,
Gusted

**Comment by mt-empty** [comment]
I checked again, nothing goes to 99/100.
Not hovering:
![image](https://user-images.githubusercontent.com/59728838/127148676-993acd84-678a-4bcb-8526-a51cd6fc1304.png)
Hovering over it, image taken when Firefox hanged:
![image](https://user-images.githubusercontent.com/59728838/127148767-ac98ce25-d31f-4f5c-ac91-a8fb1cb8a29c.png)

**Comment by mt-empty** [comment]
Its worth noting that this occurs even when I have a single page open and this page is blacklisted.

**Comment by Gusted** [comment]
That still doesn't correlate with an firefox hang for me. It's almost their is some other factor doing this.

> Its worth noting that this occurs even when I have a single page open and this page is blacklisted.

That's even weirder because other than some start-up code of dark reader we don't do anything after that. Nothing can even trigger that we do something. Sorry, but I have no clue whatsoever how dark reader could do this, when in my eyes the numbers don't add up or show anything that could cause a hang, especially if dark reader is doing it. 

The best thing you can do is have a mozillian have a look at this hanging problem and shed some more information. You can do so by the following steps: https://firefox-source-docs.mozilla.org/performance/reporting_a_performance_problem.html

**Comment by mt-empty** [comment]
I switch to Wayland instead of X server, I'm no longer getting this issue.

**Comment by mt-empty** [comment]
Upon further investigation on X server, even after disabling Dark reader the issue still persist(hovering over other icons such as ublock).
