### ISSUE TITLE
[Broken Website] www.msn.cn

### ISSUE THREAD

**Issue by shenzhiming88** [darkreader/darkreader#6356]
# Broken Website Report

## Website Address

https://www.msn.cn/zh-cn/money/news/%E5%8F%B0%E9%A3%8E-%E7%83%9F%E8%8A%B1-%E7%99%BB%E9%99%86%E5%8D%8A%E5%B0%8F%E6%97%B6%E5%89%8D-%E4%B8%8A%E6%B5%B7%E5%B7%B2%E5%AE%89%E5%85%A8%E8%BD%AC%E7%A7%BB36%E4%B8%87%E4%BA%BA-%E6%97%A0%E4%BA%BA%E5%91%98%E4%BC%A4%E4%BA%A1/ar-AAMwKy8?ocid=winp1taskbar
## Steps To Reproduce

Scroll down the page until "More content selected for you"(`为你精选更多内容`)
## Expected Behavior

Text color matching according to background
## Actual Behavior

The text is not color-matched to the background
## Screenshots

![image](https://user-images.githubusercontent.com/66902050/126980402-3d8258be-980c-4228-8e9b-e13bcd9ce5f4.png)

## System Information

- OS: Windows
- Browser: Microsoft Edge 92.0.902.55
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
HI @shenzhiming88!

Did you copy-pasted the correct link? I can see "relevant stories" but I don't see any of those stories have background-images like on your screenshot.

Regards,
Gusted

**Comment by shenzhiming88** [comment]
> HI @shenzhiming88!
> 
> Did you copy-pasted the correct link? I can see "relevant stories" but I don't see any of those stories have background-images like on your screenshot.
> 
> Regards,
> Gusted

Hello @Gusted !
I'm sure the link I copied is correct.
I think this may have been a random push, I was still able to find similar content when I just opened that link.
![image](https://user-images.githubusercontent.com/66902050/126988490-22c8c401-68e7-4d09-ba59-03a301224d10.png)

**Comment by Gusted** [comment]
I gave it a few refresh and other browsers BUt I'm not able to find any of those images/content.

**Comment by shenzhiming88** [comment]
Hello @Gusted !
You don't need the exact image, only the color of these fonts will do.

**Comment by Gusted** [comment]
Thats still a problem because I don't get  any similair content like you. Because I cant go invert the text that ID inside images. Because that will break the other portion of the images.

**Comment by arche-dev** [comment]
> Hello @Gusted !
> You don't need the exact image, only the color of these fonts will do.

I think that'll just break other images too and make this text black
![image](https://user-images.githubusercontent.com/66189242/126993162-285f902a-32a6-42bb-8ab8-1034943d415b.png)

**Comment by shenzhiming88** [comment]
Yes, it is indeed not easy to deal with ......
However, when I close Dark Reader, I get the following image
So I guess there is some way to disable the text color change in this section
![image](https://user-images.githubusercontent.com/66902050/126993515-40cd88d7-f63e-43a9-bf86-c9f460949ac0.png)

**Comment by Gusted** [comment]
Correct, that's why I was looking to get the same content so I can correctly select those text.

**Comment by arche-dev** [comment]
I also wasn't able to get the content with those fancy blur things

**Comment by shenzhiming88** [comment]
@Gusted @arche-dev Hello!
Will this work for you?
![image](https://user-images.githubusercontent.com/66902050/126994387-252d3ed4-d8c7-4446-8c0f-ae20ede77078.png)
![image](https://user-images.githubusercontent.com/66902050/126994393-5423428d-bff1-4ea7-945d-b1655cdd20ac.png)

**Comment by Gusted** [comment]
Perfection, I can make a fix out of this.

If you feel comfortable, could you open the "dev tools" button(right-bottom) and paste
```
msn.cn

IGNORE INLINE STYLE
div[part="article"]

================================
```
Into the text form, but make sure it's in the correct "format" like:
![image](https://user-images.githubusercontent.com/25481501/126994971-d70ca83c-597e-4271-9e8e-d64e98a636cf.png)
After that please click `Apply`, then make sure you can find the fix(ctrl + f "msn.cn") and give the page a refresh.

**Comment by arche-dev** [comment]
Going a bit off topic here but when is that reset button going to have a confirmation?

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/4887 If you can test-out the PR and look for any possible bugs and don't find any, I'm happy to merge it myself.

**Comment by shenzhiming88** [comment]
@Gusted 
Is this the case?
But it still doesn't seem to work after my hard refresh
![image](https://user-images.githubusercontent.com/66902050/126996129-2adc35df-d5e9-48df-9dd4-7c0d385be6f1.png)

**Comment by arche-dev** [comment]
Did you click `Apply`?

**Comment by shenzhiming88** [comment]
> Did you click `Apply`?

Yes

**Comment by Gusted** [comment]
Hmm...
What about
`div[part="article"]` => `.article`

**Comment by shenzhiming88** [comment]
> Hmm...
> What about
> `div[part="article"]` => `.article`

It looks perfect! Thanks!
![image](https://user-images.githubusercontent.com/66902050/126999432-e38416c0-a6b5-4c57-a402-7ac554e69fc6.png)
So can https://github.com/darkreader/darkreader/issues/5026 be solved in the same way?

**Comment by arche-dev** [comment]
> It looks perfect! Thanks!
> ![image](https://user-images.githubusercontent.com/66902050/126999432-e38416c0-a6b5-4c57-a402-7ac554e69fc6.png)

Horray! :D

**Comment by shenzhiming88** [comment]
@arche-dev Also thank you!

**Comment by Gusted** [comment]
Well if you can provide the same screenshots as before with, I'd give it a shot #5026

**Comment by shenzhiming88** [comment]
@Gusted Hello!
The one you provided me with seems to be different from the one you submitted in the Pull Request(https://github.com/darkreader/darkreader/pull/6357), I followed the changes you submitted and it still seems to be invalid, I don't know what the reason is 😂

**Comment by Gusted** [comment]
Hmm, Ah I see, you copy pasted my whole message while I meant you could replace `div[part="article"]` with `.article`. In which I thought was correct after you confirmed it worked.

**Comment by shenzhiming88** [comment]
@Gusted Hello!
I found that I copied the `div[part="article"] => .article` together above

**Comment by Gusted** [comment]
Hmm, you could try to have 

```
msn.cn

IGNORE INLINE STYLE
div
```

**Comment by shenzhiming88** [comment]
> Hmm, you could try to have
> 
> ```
> msn.cn
> 
> IGNORE INLINE STYLE
> div
> ```

Hello!
Sorry, it is not working
It is possible that I accidentally closed Dark Reader earlier
![image](https://user-images.githubusercontent.com/66902050/127011588-f9d67b1f-10e5-4803-a5bc-f4b763882e54.png)

**Comment by Gusted** [comment]
Could you replace `div` with `*`, click Apply and then give the site a refresh?

**Comment by shenzhiming88** [comment]
@Gusted 

![image](https://user-images.githubusercontent.com/66902050/127012214-9386c947-f0f6-46b7-b7ac-962f087097af.png)

**Comment by Gusted** [comment]
Hmm that's really weird, could you post an screenshot of the devtools which the text being selected?

**Comment by Gusted** [comment]
Sure thing.

**Comment by Gusted** [comment]
Ill be using the selector that seamlessly somehow worked for now.

**Comment by shenzhiming88** [comment]
@Gusted 
![image](https://user-images.githubusercontent.com/66902050/127104191-4abeac2e-469f-4fb5-a7d0-48bf7d2b4511.png)

**Comment by shenzhiming88** [comment]
@Gusted I find that if you use the `Microsoft Edge` browser, you can get a similar effect to mine, none of the other browsers seem to have this effect (maybe you can change the browser UA?)

**Comment by shenzhiming88** [comment]
@Gusted I think it's the browser, Microsoft Edge seems to have this part "locked down" and `uBlock Origin` doesn't seem to work here either

**Comment by Gusted** [comment]
#6361 should do the trick if the part isn't locked down. Otherwise we can't do much.

**Comment by shenzhiming88** [comment]
@Gusted I think this fix is also problematic
![image](https://user-images.githubusercontent.com/66902050/127152647-d41ea515-b6cb-4472-ac48-6b53f974301b.png)

**Comment by Gusted** [comment]
I'm not sure what you looking at, but the gradient's background should be white(give it a refresh).

**Comment by shenzhiming88** [comment]
Hmm...
I have gave it a hard refresh
![image](https://user-images.githubusercontent.com/66902050/127154867-f607ca67-ba78-4c2b-8864-ac608213b059.png)

**Comment by Gusted** [comment]
It shouldn't be showing any dark background color as thats being disabled via the fix.

**Comment by shenzhiming88** [comment]
I don't think I have a problem here
![image](https://user-images.githubusercontent.com/66902050/127155239-1614384a-fcd1-429d-873f-9c5bccee16be.png)

**Comment by Gusted** [comment]
Im not sure how they are modifying the custom color. But its a trade off im willing to make in order to fix all the other cards.
