### ISSUE TITLE
Inverted colors video on DuckDuckGo search page

### ISSUE THREAD

**Issue by clstaudt** [darkreader/darkreader#636]
Using the DuckDuckGo search page and playing videos from the video tab, the video appears in inverted colors:

https://duckduckgo.com/?q=darth+vader&atb=v97-4_g&iar=videos&iax=videos&ia=videos

**Comment by alexanderby** [comment]
I see this problem in Filter mode.It can be fixed by Dev Tools, but the fix can be tricky since IFrame wrapper has background image and should be reverted, but IFrame itself contains video that shouldn't.
