### ISSUE TITLE
[Feature Request] add method to remove keyboard shortcut

### ISSUE THREAD

**Issue by draeath** [darkreader/darkreader#6360]
# Feature Request

## Is this feature request related to a problem?

Feature request

## Screenshots

N/A

## Additional Context

If one accidentally assigns a shortcut to, say "Add site to list" there seems to be no way to remove this mapping. Please consider adding a means to do so.

**Comment by Gusted** [comment]
If one does so accidentally, you can go the extension's page of the browser and remove it. We don't have any ability to remove such shortcut on our own without binding it to another key.
