### ISSUE TITLE
[Feature Request] A list of sites using Light Mode (see description for use case)

### ISSUE THREAD

**Issue by AnishDe12020** [darkreader/darkreader#6365]
# Feature Request

A list of sites specifically using **lightmode** so that they are always converted to dark unless disabled by the user. This would make sense for sites like `github.com` which has dark mode all over the site except some pages like `github.com/marketplace` This way `github.com` can be added to the list of dark mode supported sites and `github.com/marketplace` can be added to the list of sites using light mode (at least until GitHub updates GitHub Marketplace to use a dark UI :smile:) so that Dark Reader applied the required styles only on that specific page.

## Is this feature request related to a problem?

In [`CONTRIBUTING.md`](https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md) there is a line:
> All pages are dark by default regardless of the system's preferred color-scheme

If this feature is implemented, say a site has 100 pages and 98 of those use dark mode but 2 use light mode, that site can be added to the list of sites supporting dark mode and the 2 pages can be added to the list of sites using light mode.

## Screenshots

None

## Additional Context

None, already explained in the Feature Request section

**Comment by Gusted** [comment]
> If this feature is implemented, say a site has 100 pages and 98 of those use dark mode but 2 use light mode, that site can be added to the list of sites supporting dark mode and the 2 pages can be added to the list of sites using light mode.

I don't see any real-life example other than github.com being mentioned. And github.com doesn't even qualify for this as they have by default a dark-theme. 



> This would make sense for sites like `github.com` which has dark mode all over the site except some pages like `github.com/marketplace` This way `github.com` can be added to the list of dark mode supported sites and `github.com/marketplace` can be added to the list of sites using light mode (at least until GitHub updates GitHub Marketplace to use a dark UI smile) so that Dark Reader applied the required styles only on that specific page.

See #2517 which would allow to disable specific pages. With `github.com/marketplace$`, other than that it will solve a problem that doesn't exist in my eyes.
