### ISSUE TITLE
[Broken Website] en.wikipedia.org

### ISSUE THREAD

**Issue by unbeatable-101** [darkreader/darkreader#6374]
# Broken Website Report

## Website Address

https://en.wikipedia.org/wiki/Main_Page
## Steps To Reproduce

Go to https://en.wikipedia.org/wiki/Main_Page

Look at the sidebar on the left
## Expected Behaviour

The sidebar is darkened (It actually does get darkened for a split second before turning white).
## Actual Behaviour

The sidebar is white
## Screenshots

<img width="1069" alt="Picture of white wikipedia sidebar" src="https://user-images.githubusercontent.com/58151048/127424505-6f1f4c27-ded6-4ab5-9a66-e5002d1e4cfb.png">

## System Information

- OS: macOS 12.0 Beta (21A5284e)
- Browser: Firefox 92.0a1 (2021-07-28) (64-bit)
- Dark Reader Version: 4.9.34

## Additional Context
Wikipedia's own WIP darkmode has the same issue.

**Comment by Gusted** [comment]
Hi @unbeatable-101!

Is this a persistent issue?
Also, does this happen with any other content on wikipedia?

**Comment by unbeatable-101** [comment]
It is persistent, and I haven't noticed it anywhere else.

Interestingly, scrolling down does this
<img width="1081" alt="Screen Shot 2021-07-29 at 14 52 28" src="https://user-images.githubusercontent.com/58151048/127549625-a6ea0909-9302-485c-a5d1-e5df3389bebd.png">

**Comment by Gusted** [comment]
Hmm, this problem has came forward a few times with mediawiki's engine. So it will be an easy fix even though it shouldn't happen at all
