### ISSUE TITLE
[Broken Website] Rust's suggestion website is broken.

### ISSUE THREAD

**Issue by thaurane** [darkreader/darkreader#6375]
# Broken Website Report

## Website Address
https://rust.nolt.io/

## Steps To Reproduce
Go to https://rust.nolt.io/, turn on dark reader if it is not on, switch to dark mode, switching to light mode makes the issue even worse.

## Expected Behavior
The middle column should be an off brown/green. As well as the upvote/downvote buttons.

## Actual Behavior
The middle column's background is disabled and matches the background of the rest of the page. As well as the upvote/downvote buttons.

## Screenshots
How it should look: https://i.imgur.com/oTcN56o.png

How it looks with dark mode: https://i.imgur.com/B81FfhJ.png

How it looks with light mode: https://i.imgur.com/cYrWTx7.png

## System Information
Windows 10
Firefox 90
Dark reader 4.9.34

**Comment by Gusted** [comment]
One simple fix is to just slap it into the dark-sites.config so dark reader would be disabled by default as this in fact is a dark mode by default site.

**Comment by thaurane** [comment]
Yup that worked. Thanks!
