### ISSUE TITLE
Excluding emoji images from inversion like with images

### ISSUE THREAD

**Issue by ruskiar** [darkreader/darkreader#638]
If it's feasable, it would be great to exclude the range of unicode characters that function as emoji from inversion. There are certain sites where they are excluded correctly e.g. slack for whatever reason, but other sites e.g. hangouts, gmail where they are inverted. 

Not sure how realistic it is to implement this feature but it would be a great addition.

**Comment by alexanderby** [comment]
Did you use Filter mode? I don't think it is possible.

**Comment by ruskiar** [comment]
I did use the different modes for inversion in case one of them worked but none did. I do have an answer as to why some sites show the emoji correctly and some incorrectly though. Slack uses images instead of the actual unicode characters to represent emojis and therefore they are not inverted. The sites where it does not work use the actual unicode characters and the browser displays them as images.

**Comment by alexanderby** [comment]
Filter mode inverts the whole screen pixel-by-pixel, no matter if there is a text or image, then more filters are applied to HTML elements specified in config (`<img>`, `<video>` and other elements) to invert them again. There is no static way to crop emoji from text and apply filter to it.

Dynamic mode changes color declaration, so if it sets white color to text, the text will be colored white, but emoji will stay the same.

**Comment by ruskiar** [comment]
So that actually worked, I did dynamic mode, text is still readable yet the emoji unicode characters are still colored correctly, thank you.
