### ISSUE TITLE
Links/Underlines not visible

### ISSUE THREAD

**Issue by mxchange** [darkreader/darkreader#639]
Example: https://m.signalvnoise.com/library-rules-how-to-make-an-open-office-plan-work-f9f6d69a2d4c

On dark mode the underlined links are not visible, they should be the same color as text.

I see that `text-decoration` is set to `none`, and I'm not sure what `withMagicUnderlines` is supposed to do ;p

**Comment by alexanderby** [comment]
I was reviewing the issue and didn't find anything wrong. Maybe they used bottom border instead of text decoration.
