### ISSUE TITLE
[Bug] Does not work on kinopoisk.ru/top/navigator/

### ISSUE THREAD

**Issue by azat11** [darkreader/darkreader#6395]
# Bug Report

## Bug Description

When turning on on https://www.kinopoisk.ru/top/navigator/ the DarkReader does not work. The issue occurs only after selection of multiple options and going throug pages of results, when the link in the address bar gets long.

## Steps To Reproduce

- Go to https://www.kinopoisk.ru/top/navigator/.
- Choose multiple options.
- Search and go to another page of results, so that link gets long.

## Expected Behavior

Page stays dark.

## Actual Behavior

Page returns to default color.

## System Information

- OS: Windows 7
- Browser: Waterfox G3.2.4.1 (64-bit)
- Dark Reader Version: 4.9.34

## Additional Context

As stated above, the cause seems to be connected to the length of the page link.

**Comment by Gusted** [comment]
Hi @azat11!

Is this a persistent bug?
I don't seem to be able to reproduce any problems despite the length of the page link.

Regards,
Gusted

**Comment by azat11** [comment]
> 
> 
> Hi @azat11!
> 
> Is this a persistent bug?
> I don't seem to be able to reproduce any problems despite the length of the page link.
> 
> Regards,
> Gusted

I encountered it only on that site. Don't know why it happens, but it is still pretty much there. It is easily reproducible on that site. Here's an example of the link when DR stops working, despite being turned on: https://www.kinopoisk.ru/top/navigator/m_act[egenre]/12%2C1747%2C15%2C9%2C25%2C999%2C26%2C1751/m_act[country]/1%2C1/m_act[years]/1990%3A2005/m_act[rating]/1%3A/m_act[ex_rating]/7%3A/m_act[is_film]/on/order/ex_rating/page/2/#results

**Comment by Gusted** [comment]
Other than some minor issues, all looking good to me.
![image](https://user-images.githubusercontent.com/25481501/128602480-e9ee232b-04e5-466a-86f0-71ad0caeab2b.png)

**Comment by azat11** [comment]
> 
> 
> Other than some minor issues, all looking good to me.

Well I guess then it's a browser bug. Okay then.
