### ISSUE TITLE
[Broken Website] buttons on brilliant.org stop working

### ISSUE THREAD

**Issue by vwkd** [darkreader/darkreader#6396]
Clicking on buttons in an SVG doesn't work and breaks any normal buttons from working as well.

https://user-images.githubusercontent.com/33468089/127709861-5859ef5c-fce8-422c-a17e-0795949b1f95.mov

Sometimes I can fix it temporarily by turning Dark Reader off and on again and/or reloading the page.

**Comment by Gusted** [comment]
Hi @vwkd!

Please use [the provided template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website.md&title=%5BBroken+Website%5D+Replace+with+title) so we have the basic information to be able to debug the bug.

Regards,
Gusted
