### ISSUE TITLE
[Question] Export CSS file option disappeared?

### ISSUE THREAD

**Issue by shelmz** [darkreader/darkreader#6411]
since one of the last updates I can't find the function to export a static CSS file from the style generated by Dark Reader anymore. Does the possibility still exist in any kind of way?

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

 Go to ⚙Settings -> Manage settings -> Export dynamic theme.

**Comment by shelmz** [comment]
On Linux I still find it there, but at the Windows version **there are no "Settings" anymore**. The menu got simplified.
