### ISSUE TITLE
[Broken Website] VirusTotal

### ISSUE THREAD

**Issue by RagglenLove** [darkreader/darkreader#6414]
# Broken Website Report

## Website Address
https://www.virustotal.com

## Steps To Reproduce

- Go to https://www.virustotal.com.
- Click on "Choose file" and select a file for scanning.
- Let it upload your file and wait for the results.

## Actual Behavior

Please refer to the screenshot.

## Screenshots
![Screenshot_2021-08-03_18-57-47](https://user-images.githubusercontent.com/45503845/128007058-38092543-160b-4efe-b0f9-894ef43a4b25.png)

## System Information

- OS: Xubuntu 20.04 LTS
- Browser: Firefox 90.0.2 (64-bit)
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
#4682
