### ISSUE TITLE
[Feature Request] Auto backup of theme editor CSS

### ISSUE THREAD

**Issue by arelkin** [darkreader/darkreader#6424]
Previously, I have accidentally nuked all my customizations, and had to start again. 

Is there any way to have a feature that  automatically backs up CSS? Possible options:
1. Back up every: hour/day/week/month
2. keep last X backup copies 
3. (if necessary: backup name format; timestamp, etc...)

**Comment by Gusted** [comment]
Hi @arelkin!

Do you mean a backup of the Dev tools' content?

Regards,
Gusted

**Comment by arelkin** [comment]
Thanks for the quick response.

I meant all the custom CSS that is customizable on the DEVTOOLS tab.

**Comment by Gusted** [comment]
Hmm, Devtools was designed to test out fixes for site and check if they would work. They were never meant to be used to apply Custom CSS over a longer period of time. For such tasks I recommend [stylus](https://github.com/openstyles/stylus/).

**Comment by arelkin** [comment]
There are some styles that I apply only when DarkReader is active.

If DevTools was only meant to be a test and you are suggesting Stylus, then maybe an alternate feature request might be to include an ID on the HTML or BODY tag, something like darkReaderActive or darkReaderCustom.

**Comment by Gusted** [comment]
> If DevTools was only meant to be a test and you are suggesting Stylus, then maybe an alternate feature request might be to include an ID on the HTML or BODY tag, something like darkReaderActive or darkReaderCustom.

```css
[data-darkreader-scheme="dark"] { .... }
```

Such attributes are added to the HTML element.

**Comment by arelkin** [comment]
OK, thanks.
