### ISSUE TITLE
[Broken Website] Bing.com Info Card Titles Missing

### ISSUE THREAD

**Issue by KibSquib48** [darkreader/darkreader#6430]
# Broken Website Report

## Website Address
bing.com

## Steps To Reproduce
- Search Bing for something that has an info card, like the example in the screenshot

## Expected Behavior
The title on the top of the card should show up.

## Actual Behavior
The title is missing.

## Screenshots
dr off:
![image](https://user-images.githubusercontent.com/33189136/128431964-d5ade765-a44f-4908-a2b1-4f6d282506f2.png)
dr on:
![image](https://user-images.githubusercontent.com/33189136/128431950-58e8cfda-3249-47b7-93ce-806f9b37e2d1.png)

## System Information
- OS: Windows 11 22000.120
- Browser: Edge Dev 94.0.972.0
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Hi @KibSquib48!

I don't seems to be able to reproduce this problem, does this only reproduce on edge by any chance?
![image](https://user-images.githubusercontent.com/25481501/128547132-78d6e421-0d0e-444d-b3b1-69d16b154fbc.png)

Regards,
Gusted

**Comment by KibSquib48** [comment]
Weird, just checked again and it's all good now so I guess there's no more issue
