### ISSUE TITLE
[Broken Website] Amazon.in breaks when opened in a new tab

### ISSUE THREAD

**Issue by monish-1234** [darkreader/darkreader#6437]
# Broken Website Report

## Website Address
www.amazon.in

## Steps To Reproduce

- Go to amazon.in
- Choose a product, rightclick -> open in a new tab
- going to the tab after the page loads, breaks it. (check screenshots)
- loading it in the same page or reloading the broken page works perfectly. 

## Expected Behavior
Proper dark mode even when opened in a new tab

## Actual Behavior
Breaks the page when opened in a new tab

## Screenshots

When opened in a new tab
![image](https://user-images.githubusercontent.com/26372820/128592385-251fc037-b8aa-49a7-948c-6f5de84280b8.png)

After Reloading
![image](https://user-images.githubusercontent.com/26372820/128592396-0a260755-e90a-46d4-952c-28f65ce04c83.png)

## System Information

- OS: Windows 10 20H2
- Browser: Chrome Version 92.0.4515.131 (Official Build) (64-bit)
- Dark Reader Version: 4.9.34

**Comment by monish-1234** [comment]
Video example (Google Drive)
https://drive.google.com/file/d/1Uso048jUn83i-V5K1XxXu6WvWBKdImbX/view?usp=sharing

**Comment by Gusted** [comment]
Hi @monish-1234!

I don't seem to be able to reproduce this issue, I've tried it under a lot of condition and at a point had a bunch of different product pages over but the issue didn't occur to me.

Do you have any other extensions enabled?

Regards,
Gusted

**Comment by monish-1234** [comment]
Hey ! I found the issue ! . It is with the Keepa (Amazon Price Tracker Extension).
Disabling it solved the issue ! 
Closing it now,

Thanks,
Monish
