### ISSUE TITLE
Gmail: unread emails not sufficiently highlighted 

### ISSUE THREAD

**Issue by Noexpert** [darkreader/darkreader#644]
This is for the Firefox version,
Ordinarily, unread emails in Gmail are highlighted in gray and the font is bold.

With the add-on activated however, there is not sufficient highlighting or change in the font, and therefore it is difficult to distinguish between read and unread emails,

Thanks

**Comment by Gusted** [comment]
Unread email have by default a darker background-color what is noticable by default theme and a background-image as theme.
