### ISSUE TITLE
[Performance] Kickstarter Project Pages Use Too Much Memory

### ISSUE THREAD

**Issue by dastrdly6585** [darkreader/darkreader#6442]
# Performance Issue Report
When visiting kickstarter.com pages (in particular, project pages), Firefox memory use increases by several GB and does not decrease substantially as long as kickstarter.com is still actively in a tab.  In several instances, memory use increased to 10+ GB and locked up Firefox entirely, requiring me to end the process externally.

## Website Address

[https://www.kickstarter.com/](https://www.kickstarter.com/)

## Steps To Reproduce

- Go to kickstarter.com.
- Visit any category page (e.g. [https://www.kickstarter.com/discover/categories/games](https://www.kickstarter.com/discover/categories/games))
- Click on any project page
- Hit back to return to the category page and click on any other project page.
- Repeat previous step several times.
- Memory usage rises by several GB with each page project visited and even after waiting some time for automatic garbage collection only a fraction of the increased memory is released.  In some extremely bad circumstances, memory use exceeds 10 GB and locks up computer.

Alternate method of reproduction:
- Go to kickstarter.com with Dark Reader disabled.
- Visit any project page.
- Enable Dark Reader.
- Memory usage rises immediately by at least several GB.  In some extremely bad circumstances, memory use exceeds 10 GB and locks up computer.

## Performance Profile

[https://share.firefox.dev/3Cs21fS](https://share.firefox.dev/3Cs21fS)

## Screenshots

Firefox memory usage with Dark Reader enabled on Kickstarter project page:
_(Note: not same session as performance profile linked above)_
![KS_DarkReader](https://user-images.githubusercontent.com/13990010/128617986-1d1a6f9d-27b7-4234-a5bd-747728cc972e.jpg)

Firefox memory usage with Dark Reader disabled on Kickstarter project page:
![KS_NoDarkReader](https://user-images.githubusercontent.com/13990010/128617973-473c3ef0-54ed-45b0-90f4-e90e924b1c68.jpg)

## System Information

- OS: Windows 10
- Browser: Firefox 90.0.2
- Dark Reader Version: 4.9.34

## Additional Context
- Does this happen when Dark Reader is disabled?  
_No, memory usage issue only occurs with Dark Reader enabled on kickstarter.com_
- Does this happen in other browsers? 
_No, tested Google Chrome._
- Do you have hardware acceleration enabled?  
_Yes_

**Comment by Gusted** [comment]
Hmm well I don't see a direct link with memory. I will hold off on this issue until the next release of dark reader as I do see an indirect link with image's memory which is _hopefully_ resolved in the next release and currently would be hard to work on while having that bugging in the memory analysis.

**Comment by MobiuSRIT** [comment]
I wanted to add that I have a similar issue using Brave browser.  Kickstarter pages start using all available RAM on the device and I typically need to crash the browser out to recover.

**Comment by dastrdly6585** [comment]
I am no longer seeing the issue in Dark Reader v4.9.50 and Firefox v100.0 so I am closing the issue, but the issue may still persist in the Brave browser as @MobiuSRIT stated above.
