### ISSUE TITLE
[Broken Website] bugs.chromium.org (again)

### ISSUE THREAD

**Issue by HexCodeFFF** [darkreader/darkreader#6449]
# Broken Website Report

## Website Address
https://bugs.chromium.org/

## Steps To Reproduce
view any page or bug on the website, most are broken. i viewed https://bugs.chromium.org/p/chromium/issues/detail?id=700838

## Expected Behavior
all elements of the site are correctly darkened

## Actual Behavior
bug comments and the search bar are left bright and comment text is unreadable

## Screenshots
![image](https://user-images.githubusercontent.com/35177464/128667183-90573aab-38a7-4039-91df-e6e4a59a7c56.png)
![image](https://user-images.githubusercontent.com/35177464/128667209-fd1ccf8a-7e85-491c-bbe1-b5928b19363f.png)

## System Information

- OS: Edition	Windows 11 Home Version 21H2 OS build 22000.120
- Browser: Chrome Version 92.0.4515.131 (Official Build)
- Dark Reader Version: 4.9.34

## Additional Context
I'm aware of #3966 but it seems to be a different issue

**Comment by rakleed** [comment]
@Gusted it looks like the `INVERT
i.material-icons` rule doesn't work.

**Comment by rakleed** [comment]
@Gusted and the `mr-header` element has a transparent background when Dark Reader is enabled, although it should have a white/black background.
