### ISSUE TITLE
[Feature Request] Hope to enable and disable the Dark Reader automaticly at a certern time

### ISSUE THREAD

**Issue by Hodpel** [darkreader/darkreader#6453]
# Feature Request
In the daytime I would like to disable the Dark Reader and at night (maybe 7 o'clock) I would like to enable it. However ,it is too flashing when I have to enable it at night (cause I use  task scheduler to set my computer to or out of dark mode automaticly).It will be nice if I can set a time when the dark mode is on or not.

**Comment by Gusted** [comment]
Search for other issues, #72
