### ISSUE TITLE
Dark Reader can purge dark background with default value

### ISSUE THREAD

**Issue by delvh** [darkreader/darkreader#6454]
# Bug Report

## Bug Description
It seems that dark reader purges the background CSS of a page below what is visible in the original screen display.
While this could also be website specific, I suppose it isn't as different background behaviors could be observed when dark reader is enabled vs. when it is disabled for the same, unreloaded tab (see screenshots below).

## Steps To Reproduce
Most likely: Have a website that already declares a dark background, and that is longer than the screen, and then scroll down.

## Expected Behavior
The background CSS of the website should not be ignored below the visible screen.

## Actual Behavior
The background CSS of the website is ignored below the visible screen (see screenshots below).

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/128708482-f1831b75-65fa-406f-8d89-8e3d94d91b46.png)
Website behavior, when dark reader is enabled

![image](https://user-images.githubusercontent.com/51889757/128710506-8b3ea9fa-e4c3-4575-b903-578d1c4381cd.png)
Website behavior, when dark reader is disabled

![image](https://user-images.githubusercontent.com/51889757/128712119-2819fc69-b195-477f-b5ab-27e204afe4c7.png)
Website behavior, when dark reader is enabled and the browser console is opened

## System Information
- OS: Kubuntu 20.04
- Browser: Firefox 90.0.2
- Dark Reader Version: 4.9.34
- Screen size: 4K monitor

**Comment by Gusted** [comment]
Hi @delvh!

This is the correct behavior for dark reader, the `html` uses a different background-color than `body` most of the time, because `html`'s background-color is used for the first content paint and avoids white flashes. 

I'm not sure at which page of gitea you are, so I can't say for sure that is this exact behavior. However it's possible that there are background-color mis-match between some elements.

Regards,
Gusted

**Comment by delvh** [comment]
Thanks Gusted,
I confirmed it, the difference between `body` and `html` indeed seems to be the reason for this weird behavior.
What I don't understand is that everything is located inside the `body` of the file, and hence there should be no separation when displaying `html` and `body`.
I do see that this issue does not seem to be the fault of dark reader.
But is it the fault of firefox, or is it simply engraved in the web standards, that the `body` only covers the first visible screen?
