### ISSUE TITLE
[Feature Request] Detect websites' native dark theme

### ISSUE THREAD

**Issue by MiguelGuthridge** [darkreader/darkreader#6458]
# Feature Request

## Is this feature request related to a problem?

The extension will override the themes for websites that are already dark, which may lower the quality of the experience.

## The suggestion
Have the extension check the unmodified background colour and colour of text on web-pages. That way, it can only force a dark theme only if a dark theme isn't already used by the website, which would lead to a better overall browsing experience.

## Screenshots

![image](https://user-images.githubusercontent.com/31365175/128809457-1430800a-d89a-4e68-a151-bf81cd5ce28d.png)
GitHub in dark mode will still be modified by the extension, causing the page to look far less polished.

**Comment by bershanskiy** [comment]
I agree that this would be very useful.

@MiguelGuthridge As a temporary workaround, you can disable Dark Reader on GitHub: click on DarkReader icon to open popup UI, then on "github.com" at the left top corner.

**Comment by MiguelGuthridge** [comment]
> As a temporary workaround, you can disable Dark Reader 

Already doing this, but thanks for letting me know :)

**Comment by Gusted** [comment]
#1285
