### ISSUE TITLE
[Bug] Pages Flash White When Scrolling in Filter & Filter+ modes 

### ISSUE THREAD

**Issue by wander3** [darkreader/darkreader#6463]
## Bug Description
Sections of pages flash white before displaying while scrolling in Filter & Filter+ modes.

## Steps To Reproduce
* Enable Dark mode, Filter or Filter+
* Enter a search query on Google.com
* Scroll down

## Expected Behavior
No white flashing
 
## Actual Behavior
Sections scrolled down to flash white
 
## System Information
* OS: Windows 11 Dev Channel
* Browser: Microsoft Edge Beta
* Dark Reader Version: 4.9.34

## Additional Context
Dynamic mode resolves the issue

**Comment by Gusted** [comment]
Not too much we can do, chromium officially closed the [issue report](https://bugs.chromium.org/p/chromium/issues/detail?id=1123316) as "wontfix", you can try to comment on them or create a new issue. But this is out of our hands to fix.
