### ISSUE TITLE
[Broken Website]  Broken "Zoom Out", "Reset Zoom", "Zoom In" Icons in a file preview

### ISSUE THREAD

**Issue by yugaan24x7** [darkreader/darkreader#6468]
# Broken Website Report

## Website Address
https://classroom.google.com/

## Steps To Reproduce
- Go to (https://classroom.google.com/)
- Click 'Go to Classroom'
- Sign in
- Open any Classroom that is present for you (If there is no classrooms for you then create one by 
   clicking on the + in top right corner of your screen. Then open that class room. Announce something 
   to the class and upload pdf or image or doc in that announcement.)
- Open an image or a pdf file or doc in the classroom and preview it
- Look at bottom of the screen

## Expected Behavior
There should be **Zoom Out**, **Reset Zoom**, **Zoom In** with proper icons like this
![image](https://user-images.githubusercontent.com/77913635/128984409-b25a56ef-a86a-4692-ad09-e4718c842f0f.png)
 
## Actual Behavior
But the icons of the **Zoom Out**, **Reset Zoom**, **Zoom In** are messed up and the look like this 
![image](https://user-images.githubusercontent.com/77913635/128984288-b536902e-f740-4715-ab19-e74abfaac69d.png)

## Screenshots
How they look when Dark Reader is **disabled**
![image](https://user-images.githubusercontent.com/77913635/128985269-aa0c67c3-f02a-411d-86f6-ed5f09d83a50.png)

How they look when Dark Reader is **enabled**
![image](https://user-images.githubusercontent.com/77913635/128986205-73172f48-ef2a-4516-bad6-c4985c418f36.png)

## System Information
- OS: Windows
- Browser: Chromium(92.0) Based Browsers [Edge, Brave]
- Dark Reader Version:  4.9.34

## Additional Context
    -

**Comment by Gusted** [comment]
Already fixed, see https://github.com/darkreader/darkreader#site-fixes to enable the fixes already.
