### ISSUE TITLE
[Broken Website] Unreadable white text on pink background on meta.wikimedia.org

### ISSUE THREAD

**Issue by Rummskartoffel** [darkreader/darkreader#6469]
# Broken Website Report

## Website Address
https://meta.wikimedia.org/wiki/Special:Contributions/198.73.209.0/24

## Steps To Reproduce

- Go to the URL provided.
- Look at the light pink message box near the top of the page.

## Expected Behavior
The text in the message box should strongly contrast with the background colour of the box.

## Actual Behavior
Most of the text (excepting links) in the message box is almost completely white, making it impossible to read over the light pink background.

## Screenshots
![image](https://user-images.githubusercontent.com/20257197/129025402-e05ac900-877b-4cfd-90dc-0e7b9469b3a3.png)

## System Information

- OS: Windows 10 x64
- Browser: Firefox 90.0.2
- Dark Reader Version: 4.9.34

## Additional Context
Other Wikimedia sites appear unaffected.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/129039491-67d5ca7c-624b-4ffa-87be-4a5836363f6f.png)

The site appears fine to me, could you try to enable https://github.com/darkreader/darkreader#site-fixes?

**Comment by Rummskartoffel** [comment]
Doesn't seem to work. I've actually had it turned on for a while now, but the fixes don't seem to load.

**Comment by Gusted** [comment]
Could you try:
- Pop-up of dark reader
- Devtools
- Reset button.

It will force the newest fixes.

**Comment by Rummskartoffel** [comment]
Hmm, okay, that's definitely making it load. The box is still pink, though.

**Comment by Gusted** [comment]
> Could you try:
> 
>     * Pop-up of dark reader
> 
>     * Devtools
> 
>     * Reset button.
> 
> 
> It will force the newest fixes.

Please try this again it should work this time.

**Comment by Rummskartoffel** [comment]
It took a browser restart on top of pressing the reset button, but that did it. Thank you very much for your help and for making this awesome extension 👍
