### ISSUE TITLE
[Bug] Cannot import settings.

### ISSUE THREAD

**Issue by liltrigger** [darkreader/darkreader#6474]
# Bug Report

## Bug Description
When trying to import Dark Reader settings, the add-on popup disappears before I am able to select the backup file.

## Steps To Reproduce
Open Dark Reader > Settings > Manage Settings > Import settings  

Here is an example:
- Go to example.com.
- Hover over the example button.
- Notice that when hovering over the example button, it does not change color.
-->

## Expected Behavior
I expected that the add-on popup would stay open and I would be able to select the backup file to backup my settings.

## Actual Behavior
When I clicked "Import Settings", the popup for the add-on disappeared and I was not able to backup my settings. I tried clicking on the backup file but nothing happened.

## System Information

- OS: <! --Windows 
- Browser: Firefox, Firefox 90.0.2 
- Dark Reader Version: 4.9.34

-->

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
#3927
