### ISSUE TITLE
[Broken Website] nature.com

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6477]
# Broken Website Report

## Website Address

https://www.nature.com/articles/s41586-019-1083-9

## Expected Behavior

All text is legible in dark mode.

## Actual Behavior

Display math equations are very faint compared to the rest of the text.

## Screenshots

![pic-window-210812-1019-10](https://user-images.githubusercontent.com/59497618/129139770-d5c31a95-2353-443c-a58a-d5dde97660b1.png)

## System Information

- OS:  Linux
- Browser:  Firefox 90
- Dark Reader Version:  4.9.34

**Comment by Gusted** [comment]
Hi @paniash!

I need to a non-paid article to check it out myself, or you have to be comfortable around firefox's devtools and get a screenshot of the `math` element so I can see which class is used.

Regards,
Gusted

**Comment by paniash** [comment]
Hi @Gusted!

Could you try this link?: https://www.nature.com/articles/s41586-021-03702-0
