### ISSUE TITLE
Request: darken browser chrome

### ISSUE THREAD

**Issue by lonix1** [darkreader/darkreader#648]
Midnight Lizard has a cool option where it also darkens the browser's chrome - the button bar, title bar, tabs, and so on. Also the new tab page.

This prevents the situation that the web page is dark, but the chrome is bright. When this feature is active, everything is dark, and looks good.

**Comment by lonix1** [comment]
@paulodiovani Then it could be an option for those of us who want it, assuming the developers like the idea.
What theme do you use?

**Comment by alexanderby** [comment]
If you are talking about Firefox, Dark Reader can change the browser colors. Open **More** tab and click **Custom**. The only problem is text selection color, it cannot be changed yet. Also when you disable the feature, Firefox resets the colors to default, you will have to re-enable the theme you want to use. As for me the built-in dark theme in FF 60 already looks well. For Chrome you can install some dark theme.

**Comment by lonix1** [comment]
@alexanderby That is good enough, thanks.

**Comment by paulodiovani** [comment]
> What theme do you use?

@lonix1 
Actually, I'm not using a custom theme for a while, just GTK+ with Gnome Adwaita Dark variant.
I can't remember the theme I used before, sorry.
