### ISSUE TITLE
Habrahabr: math formulas are not readable

### ISSUE THREAD

**Issue by unstope** [darkreader/darkreader#649]
For example, this article: https://habr.com/post/317798/

![image](https://user-images.githubusercontent.com/5121368/43401560-27f5e222-9419-11e8-8ad9-766677b808b3.png)
![image](https://user-images.githubusercontent.com/5121368/43401577-3314a602-9419-11e8-89d6-ad0a1200179f.png)

**Comment by unstope** [comment]
Seems to work now.
![image](https://user-images.githubusercontent.com/5121368/44515434-3acebf80-a6cb-11e8-947f-e45165988350.png)

**Comment by unstope** [comment]
I tried risualiser's fix and it does not work for me.
But if I put the same rule into NO INVERT section it works.

**Comment by risualiser** [comment]
Could you please show examples of articles?

**Comment by risualiser** [comment]
Added config for Filter mode.
