### ISSUE TITLE
[Bug] Devtools don't work in the latest commit

### ISSUE THREAD

**Issue by Gusted** [darkreader/darkreader#6494]
# Bug Report

## Bug Description

Load the latest commit into firefox,
Open darkreader's dev tools.
Add a simple but obvious fix like add `*` into the `INVERT` section of `*`:

```CSS
*

INVERT
.jfk-bubble.gtx-bubble
.captcheck_answer_label > input + img
span#closed_text > img[src^="https://www.gstatic.com/images/branding/googlelogo"]
span[data-href^="https://www.hcaptcha.com/"] > #icon
#bit-notification-bar-iframe
::-webkit-calendar-picker-indicator
*
```

See that it's not saved, the background page is erroring about a message: (destructured parameter) is undefined
![image](https://user-images.githubusercontent.com/25481501/129244147-ddb8f0db-9779-49c8-b838-9e3e8abdf902.png)

## Expected Behavior
See desc.

## Actual Behavior
See desc.

## Screenshots
See desc.

## System Information

- OS: Linux(Arch Linux)
- Browser: Firefox nightlies 92.0a1 (2021-08-09)
- Dark Reader Version: https://github.com/darkreader/darkreader/commit/e06b96dd8b930980423e0636f55cbbafc11a5954

## Additional Context
I will run a bisect onto this and see which commit is the faulty.

@bershanskiy You've done a lot of refactoring with messaging between UI and background and content script so just pinging you in case.

**Comment by alexanderby** [comment]
Maybe it's related, but the latest master breaks on YouTube (not seen for v4.9.34).

There is a bug in v4.9.34 too, but the app keeps working. For some reason some HTMLStyleElement and Templates match `:not(:defined)` selector, that only Custom Elements (those with `-` in their name), that were not yet defined, should match. The quick fix would be to check for `-` in the tag name.

But for some reason the fallback style for YouTube doesn't disappear in the latest master. But disappears in v4.9.34 despite the error.

**Comment by alexanderby** [comment]
Just in case how to compare all changes https://github.com/darkreader/darkreader/compare/v4.9.34..master

**Comment by felixonmars** [comment]
Just did a quick bisect:

05cea434836e7c46bdb01464a93f2391feabf23c is the first bad commit

**Comment by Gusted** [comment]
> Just did a quick bisect:
> 
> [05cea43](https://github.com/darkreader/darkreader/commit/05cea434836e7c46bdb01464a93f2391feabf23c) is the first bad commit

Thank you, that commit seems to make sense.

**Comment by Gusted** [comment]
Ah we are running into the old compatbility bug again.

`chrome.runtime.sendMessage` in Firefox doesn't support a `responseCallback` argument. Where in Chromium does.

**Comment by alexanderby** [comment]
There's a problem with Dev Tools in Chrome too.

**Comment by Gusted** [comment]
#6495 solves to at least apply correct CSS. Reset button seems broken and @alexanderby mentions chromium is broken so Ill have a check to that as well.

**Comment by bershanskiy** [comment]
Ah, I broke it with https://github.com/darkreader/darkreader/commit/05cea434836e7c46bdb01464a93f2391feabf23c The bug is in checking `sender.url`. Instead of this
```
if (sender.url === chrome.runtime.getURL('/ui/popup/index.html'))
```
it should be
```
if (sender.url.startsWith(chrome.runtime.getURL('/ui/')
```
