### ISSUE TITLE
[Bug] pypi's styles are missing with darkreader master

### ISSUE THREAD

**Issue by felixonmars** [darkreader/darkreader#6499]
# Bug Report

## Bug Description
pypi's styles are missing when using darkreader master. After a lot of reloads it could be correct for one time or two. With darkreader 4.9.34 this is not reproducible.

## Steps To Reproduce

- Go to https://pypi.org/project/oci/

## Expected Behavior
Styles are retained while backgrounds are darken, like usual.

## Actual Behavior
All backgrounds are black and styles are gone.

## Screenshots
With 4.9.34:
![image](https://user-images.githubusercontent.com/1006477/129262604-9ccb3a30-7530-4abf-9c7c-ae3a5b10421b.png)

With master:
![image](https://user-images.githubusercontent.com/1006477/129262644-532613fe-7d23-4573-a821-1e00750f04b3.png)

## System Information

- OS: Arch Linux
- Browser: Firefox 92.0b2
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Phew, so many regressions for 1 day. I will have a look as this seems as well reproduce-able.
