### ISSUE TITLE
Dark Reader doesn't invert PDF colors

### ISSUE THREAD

**Issue by SarveshMD** [darkreader/darkreader#6502]
# Question

I don't know if Dark Reader invert PDF files. I want to invert PDFs too. If this feature is available, how can I use that ?
If this feature isn't available, this might be a feature request or please suggest an extension which does that. I found some extensions which invert PDF colors for PDFs from the web, but they don't do it on Local Files. I want it to invert colors on Local PDF Files too.

**Comment by bershanskiy** [comment]
Dark Reader supports this, just do this:
 - Open any PDF file
 - Click on Dark Reader icon
 - A popup will apear, click on "PDF" in the top left corner

**Comment by SarveshMD** [comment]
I tried this, but it didn't work.

**Comment by bershanskiy** [comment]
Which browser are you using? Are you using Chrome Could you make sure  This option is here:
 - If Chrome, please you go to `chrome://extensions/?id=eimadpbcbfnmbkopoojfekhnkhdbieeh` and make sure Dark Reader is allowed to open local URLs
 - If Firefox, do you see "This page is protected by browser"?

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/45960703/129312011-76673dac-e74e-4556-967a-f506160467e6.png)
</details>

**Comment by SarveshMD** [comment]
Switching on "Allow access to file URLs" option worked, thanks a ton @bershanskiy.

**Comment by KarelPeeters** [comment]
@bershanskiy What if I do see "This page is protected by browser"? Is there a way to allow the add-on to access local files?
