### ISSUE TITLE
Large Static Style is not being saved

### ISSUE THREAD

**Issue by ddaza** [darkreader/darkreader#651]
I moved my static styles to darkreader and it works great until I close my browser and  then the stylings go away/get deleted and nothing is applied.

I use [GithubDark](https://github.com/StylishThemes/Github-Dark) and the styling generated can be up to a 4000 line file.  ie. this [file](https://gist.github.com/ddaza/1b6c97c9f181be0b2e802283c75abe630)
Please help, am I doing something wrong? 

![screen](https://user-images.githubusercontent.com/290254/43538179-e87adc3c-9586-11e8-9fc7-054bd12e45ff.png)

Additionally, it would be great to add a way to specify the same static styles to multiple domains. ie. github and github enterprise (different domain, same page structure).

thanks!

**Comment by krupenja** [comment]
This is a duplicate of #612.

**Comment by ddaza** [comment]
I see the

**Comment by ddaza** [comment]
dupe

**Comment by alexanderby** [comment]
I've improved the settings structure and will test it for a while. Your second request is possible to do, but there is no UI for it yet. I'm thinking to create an editor of settings JSON file.

**Comment by alexanderby** [comment]
I've published version 4.6.3. When there will be not enough space, you will be switched from sync storage to local (so your settings will not be synchronized across devices). There is a 5MB limit for local storage, if it will be exceeded, the extension can ask for unlimited storage permission (not implemented yet).
