### ISSUE TITLE
[Broken Website] Gmail labels colors are only partially handled

### ISSUE THREAD

**Issue by fmigneault** [darkreader/darkreader#6510]
# Broken Website Report

## Website Address
https://mail.google.com

## Steps To Reproduce
- open gmail with an account that has nested lablels
- notice that displayed 1st level labels are darkened, but not 2nd level ones

## Expected Behavior

Because lower level labels (2nd and below) in the hierarchy and all displayed levels applied onto emails in mail-view list remain with the original color, 1st level label colors should also keep the original color. 
I think that although DarkReader usually darkens colors overall, it being unable to match label-menu colors with actual label colors on email just makes it more confusing to associate them, so it should refrain from changing them at all.

## Actual Behavior
First level items are darkened, while every other label related colors are not. 

## Screenshots

Below is a snippet of my mail's label section. 
As presented, all first level colors are modified by DarkReader (labels: `[TODO]`, `[URGENT]`, `Administration`, `ÉTS`, `Personal`, `Programs` and `Work`), while other ones under them have original colors. 
<details>
  <summary>Expand for image </summary>
 <img src="https://user-images.githubusercontent.com/19194484/129427010-f64bc374-01a3-454f-9847-e169a7b0ddef.png">
</details>

## System Information

- OS: Windows
- Browser: Firefox 90.0.2 (64-bit)
- Dark Reader Version: 4.9.34

**Comment by fmigneault** [comment]
@Gusted 
Even with version 4.9.43, I am still seeing this issue.

**Comment by Gusted** [comment]
I'm not able to reproduce it anymore, please ensure you have the latest fixes within dark reader(dev tools -> Reset button).
