### ISSUE TITLE
Dark Reader & Firefox ≥ 91   (Bug #6465 Redux)

### ISSUE THREAD

**Issue by RAMilewski** [darkreader/darkreader#6516]
"Dear me! I am not certain quite,
That even now I've got it right."

-- **Eletelephony** _by Laura Richards_

https://allpoetry.com/Eletelephony

 I suspect there is another new pref in Firefox that is interfering with Dark Reader.

Any Suggestions?

Screen shots from Firefox 92.0b3 and Chrome 92.0 attached to illustrate: 

![Screen Shot 2021-08-14 at 1 26 51 PM](https://user-images.githubusercontent.com/702294/129459767-a4bee903-0906-42e3-bf2b-84bdf12886d0.png)
![Screen Shot 2021-08-14 at 1 39 05 PM](https://user-images.githubusercontent.com/702294/129459771-c5562bf9-1c40-40d3-a576-bf87e1c45b8b.png)
![Screen Shot 2021-08-14 at 1 29 36 PM](https://user-images.githubusercontent.com/702294/129459775-2a86ac9a-56f8-48b1-b66e-8dc7a054285e.png)

**Comment by Gusted** [comment]
I am... not so sure what to look for? I get the same result on my machine which seems to be the expected result?

**Comment by RAMilewski** [comment]
Shouldn't the Dark mode on Chrome and Firefox look at least similar?

**Comment by felixonmars** [comment]
Your Firefox screenshot has dark reader turned off for the website. Perhaps try again with it enabled?

**Comment by RAMilewski** [comment]
OK!  My error!!   I was looking at the Global ON/OFF buttons, not the Alt-Shift-A toggle.   Perhaps a bit more emphasis in the docs would be in order.  That's a pretty subtle difference in the display especially when trying to debug unexpected display behavior.   

Please don't interpret any of this as a complaint.   Dark Reader is my all time favorite Firefox Add-On.
