### ISSUE TITLE
[Broken Website] wikipedia

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6518]
# Broken Website Report

## Website Address

https://en.wikipedia.org/wiki/Ultraviolet_catastrophe

## Expected Behavior

All math equations be clearly legible in dark mode.

## Actual Behavior

Math equations are nearly invisible in dark mode.

## Screenshots

![pic-window-210815-1101-16](https://user-images.githubusercontent.com/59497618/129468219-a6d7beed-a225-4dba-9dbe-ecf380cd90a2.png)

## System Information

- OS:  Linux
- Browser:  Firefox 78.12.0esr
- Dark Reader Version:  4.9.34

**Comment by felixonmars** [comment]
I can reproduce with Firefox 78.12.0esr, but not with latest Firefox 91.0, 92.0b3, or Chromium 92.0.4515.131.

**Comment by dw61** [comment]
I don't think this is fixed; I'm still experiencing this issue

<img width="1137" alt="Screen Shot 2021-12-06 at 01 22 07" src="https://user-images.githubusercontent.com/27620726/144797434-62b0388a-3c9e-48d7-94a4-1de3639d39ba.png">
