### ISSUE TITLE
When visiting milligram, enabling Dark Reader shows thousands of lines of code that shouldn't appear

### ISSUE THREAD

**Issue by popey456963** [darkreader/darkreader#652]
https://milligram.io/#forms

It seems to actually target the:

    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">

And insert it into the document as a whole system.

**Comment by alexanderby** [comment]
Just checked now and haven't seen anything suspicious. Please reopen the issue if problem still happens and give some more details.

**Comment by popey456963** [comment]
True, issue appears to have been fixed, :+1:

**Comment by c24w** [comment]
I think this has reappeared.  If you look [here](https://milligram.io/#getting-started), the example should appear like this:

```html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

<link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">

<link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
```

but is polluted with all sorts:

```html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">


<link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css"><style class="darkreader darkreader--cors" media="screen">html {
  line-height: 1.15; 
  -webkit-text-size-adjust: 100%; 
}

...

```

**Comment by popey456963** [comment]
Aha, so it isn't an issue in Firefox, but is in Chrome.

I had switched from Chrome to Firefox, hence why the issue appeared fixed for me.
