### ISSUE TITLE
[Bug] No longer working with Thunderbird 91

### ISSUE THREAD

**Issue by racofer** [darkreader/darkreader#6521]
# Bug Report

## Bug Description
With the release of Thunderbird 91, Dark Reader is no longer working, despite the add-on being marked as installed.

## Steps To Reproduce

- Install Thunderbird 91
- Setup an account
- Install Dark Reader from the Thunderbird add-ons page

## Expected Behavior

- Dark Reader should load properly as in Thunderbird 78
- ![](https://i.imgur.com/0XjZoOw.png)

## Actual Behavior

- Dark Reader shows as installed, but it's stuck in "loading"
- ![](https://i.imgur.com/DrSjP1d.png)
- No e-mails are shown in dark mode

## System Information

- Thunderbird version 91
- Dark Reader version 4.9.32
- Windows 10 x64 / Ubuntu 20.04 LTS

**Comment by Gusted** [comment]
Wow, v91 seems to contain some bugs that is borking dark reader. I have a look.

**Comment by Gusted** [comment]
Filled a bug report[1], because the amount of things happening in thunderbird does overwhelm me to properly understand why all these errors within thunderbird are happening and why dark reader currently doesn't work.

1. https://bugzilla.mozilla.org/show_bug.cgi?id=1725864

**Comment by alexanderby** [comment]
Please check if version 4.9.34.1 fixes the issue.

**Comment by racofer** [comment]
> 
> 
> Please check if version 4.9.34.1 fixes the issue.

Everything appears to be working just fine now with the new version in TB91.

**Comment by glima** [comment]
Still not working here :(

**Comment by Gusted** [comment]
Did you install v4.9.34.1? If not, please install, otherwise please open up a new issue.

**Comment by glima** [comment]
I did. Not sure what to point out on a new issue, though. Will do it soon. Thanks for answering :)
