### ISSUE TITLE
Cannot be used in FeishuDocs. uture Request] Replace with title

### ISSUE THREAD

**Issue by suiyun08** [darkreader/darkreader#6530]
# Feature Request

## Is this feature request related to a problem?

Hope to support the use in “feishu.cn/docs/”.
## Screenshots

![image](https://user-images.githubusercontent.com/29906815/129701864-e8d73e0d-3971-4ccf-a4fd-901582cf0fdd.png)

**Comment by Gusted** [comment]
I think you meant to use the bug report template? I'm not sure what you're trying to achieve.
