### ISSUE TITLE
[Broken Website] chitanka.info is brown/yellow

### ISSUE THREAD

**Issue by Gitleptune** [darkreader/darkreader#6532]
# Broken Website Report

## Website Address

https://chitanka.info/

## Steps To Reproduce

1. Go to https://chitanka.info/.
2. Page is wrong colour.

## Expected Behaviour

1. Go to https://chitanka.info/.
2. Website is black/dark theme.

## Actual Behaviour

1. Go to https://chitanka.info/.
2. Website is ugly brown/yellow.

## Screenshots

![image](https://user-images.githubusercontent.com/76597257/129787247-ef0ce92e-d6a3-4897-a8db-ac0bb1921004.png)

## System Information

- OS: Windows.
- Browser: [Vivaldi](https://vivaldi.com) 4.1.2369.15 (Stable channel) (64-bit)
- Dark Reader Version: Version 5 Preview (4.9.34)

## Additional Context

Problem is probably caused by yellowish gradient over everything.

Since the page is in Bulgarian (some of the classes are in Bulgarian as well), I can help if you need translating.

**Comment by Gusted** [comment]
Hmm, the original page is in the yellow colorspace according to HS{L,B}. So DR simply modify it to a darker yellow color. I don't think DR is doing anything wrong here.

**Comment by Gitleptune** [comment]
Alright, closing if there aren't going to be any changes here.
