### ISSUE TITLE
[Feature Request] Have Dark Reader enabled for certain websites and disabled for every other website by default

### ISSUE THREAD

**Issue by fourteen-1** [darkreader/darkreader#6537]
# Feature Request

## Is this feature request related to a problem?
Most used websites already have a native dark mode and darkreader is only useful for the handful of websites that dont. Having to manually disable dark-reader for every website that has a built-in dark mode is tedious and inefficient.

It would be a lot better if this process was in reverse. Have an option to have dark reader off by default, and toggle it on for specific websites. 

## Screenshots
n/a

## Additional Context
n/a

**Comment by ajdajd** [comment]
I think we have the same use case. Try this:

- Toggle extension: ON
- Under site list, select `Inverted listed only`
- Then for each (new) site you want to have Dark Reader activated on dark mode, click the site toggle (to the left of the Toggle extension)

**Comment by Gusted** [comment]
I normally reply something along the lines of what @ajdajd said. Which is the correct answer, closing.
