### ISSUE TITLE
[Feature Request] Indication when extension does not have permission to access local URLs

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6538]
# Feature Request
UI should indicate when extension does not have "local URLs" permission.

## Is this feature request related to a problem?
People get confused when they open local PDF files and Dark Reader does not work on them despite being enabled. This usually happens because extension does not have proper permission to "open local URLs" (not granted by default).

## Screenshots

![image](https://user-images.githubusercontent.com/45960703/129863890-beda429e-ff34-4b51-92f2-bce076acaac2.png)

## Additional Context

To test this:
 - Open Chrome and install extension from store
 - Open extension details at `chrome://extensions/?id=eimadpbcbfnmbkopoojfekhnkhdbieeh` and make sure "local URLs" toggle is off (default)
 - Open a local PDF
 - Notice that Dark Reader disaplays "PDF" with a checkmark, but page is not inverted

**Comment by Gusted** [comment]
Yup, if this could be a UI indicator that would be great. I actually have looked at it a few times. But this main problem is to detect if you access to such pages(which is pretty obscure). I don't know of any web extensions API that cover this, so you would have to do some trial-and-error code to check if you can inject code into such pages.
