### ISSUE TITLE
[Broken Website] bromite.org

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6556]
# Broken Website Report

## Website Address

https://www.bromite.org/

## Expected Behavior

Complies with dark mode.

## Actual Behavior

Dark mode is almost the same as light mode.

## System Information

- OS:  Linux
- Browser:  Firefox 91
- Dark Reader Version:  4.9.34

**Comment by Gusted** [comment]
Hi @paniash!

Do you have any setting enabled(about:config)? Does it happen on a fresh new profile(about:profiles)? 

I wasn't able to reproduce the bug.

Regards,
Gusted

**Comment by paniash** [comment]
@Gusted Hi! I did try it with a fresh profile, and still end up with the same issue.

![pic-window-210821-1426-15](https://user-images.githubusercontent.com/59497618/130316611-c3fffc97-6435-47d7-b0bf-54964faffb8a.png)

**Comment by Gusted** [comment]
Hmm, could you try: https://github.com/darkreader/darkreader#site-fixes it seems like a CSS Fix was made some time ago for this.

**Comment by paniash** [comment]
@Gusted I don't notice the changes unfortunately. On a related note, I have the "sync" features enabled always but notice site fix changes after a really long time (around a month or so).

**Comment by Gusted** [comment]
> On a related note, I have the "sync" features enabled always but notice site fix changes after a really long time (around a month or so).

That can be the case, the current sync behavior is behaving like it should but if someone has custom fixes, it simply won't work. You can force a reset by using the "Reset" button on the dev tools.

**Comment by paniash** [comment]
> That can be the case, the current sync behavior is behaving like it should but if someone has custom fixes, it simply won't work. You can force a reset by using the "Reset" button on the dev tools.

Thanks you very much! Now I can see the website in the gorgeousness of darkness!
