### ISSUE TITLE
[Broken Website] Watchasian.in

### ISSUE THREAD

**Issue by SaruDesu** [darkreader/darkreader#6565]
# Broken Website Report

## Website Address

watchasian.in

## Steps To Reproduce

Go to watchasian.in open any drama or episode.

## Expected Behavior

Text color is dynamic, changing with the use of the extension interface.

## Actual Behavior

Most text color is black, as well as player elements.

## Screenshots

![image](https://user-images.githubusercontent.com/51081028/130321955-971b4fd5-14c4-44c1-994c-f4057d11aeeb.png)
![image](https://user-images.githubusercontent.com/51081028/130321957-252d0458-034b-4f99-a81b-88b938f4a943.png)
![image](https://user-images.githubusercontent.com/51081028/130321959-f654f6df-661a-48de-8b56-ecf032e4a4c2.png)

## System Information

- OS:  Windows 10
- Browser:  Chrome 92
- Dark Reader Version:  4.9.34

## Additional Context
Requested pull #6551 as fix but rejected as I lazily used * selector as fix. It works in my browser (It is stable) so I didn't bother to find the specific selectors and also I forgot that * selector is unacceptable. Here are the proofs that using fix in pull #6551:

Without fix:
![image](https://user-images.githubusercontent.com/51081028/130322136-ff2a0a12-7f7e-499d-a39a-0c80cda75e2a.png)

With fix (Dynamic with 25% Sepia):
![image](https://user-images.githubusercontent.com/51081028/130322141-7023d36c-e3ff-458e-a5be-3e3e255e5dc9.png)

With fix (Dynamic with 25% Sepia, Without adblock):
![image](https://user-images.githubusercontent.com/51081028/130322155-07437faa-e4c9-4113-9516-e1f085d72b7d.png)

**Comment by Gusted** [comment]
Hi @SaruDesu!

Could you try this in a new chrome profile? This issue doesn't appear to be happening for me.

Regards,
Gusted

**Comment by SaruDesu** [comment]
I tried in a new chrome profile and it seems that this issue only appears on my browser. I tried to disable all modifications I did in my chrome profile including custom skins and extensions but to no luck finding the source of the issue. Thus, this issue will be closed.
