### ISSUE TITLE
[Broken Website] https://www.twitch.tv/

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6579]
# Broken Website Report

## Website Address
https://www.twitch.tv/

## Steps To Reproduce
Watch any Recent Broadcast on any streamer's channel. (Example: https://www.twitch.tv/videos/1125185338) (See screenshot.)

## Expected Behavior
The video scrubbing slider would be light. This would allow it to match the rest of the UI elements for the video controls. (Recently, #6570 was implemented to fix the volume slider, which was a great fix. I have been meaning to report that one also, but @c-nagy's fix reminded me to report this one as well.)

## Actual Behavior
The video scrubbing slider is dark.

## Screenshots
(Issue with the site is highlighted in red.)

![Untitled](https://user-images.githubusercontent.com/89356985/130368204-df9ae6d6-ae4c-418b-af5a-53bda7a156c1.png)

## System Information

- OS: Windows 10 21H1 (19043.1165)
- Browser: Firefox Nightly 93.0a1 (20210821212131)
- Dark Reader Version: 4.9.34

**Comment by c-nagy** [comment]
Hey, I see what you mean. Does this fix the issue on your end?: https://github.com/darkreader/darkreader/pull/6580/files

**Comment by DJ-Katalina** [comment]
Hi @c-nagy,

Yes, this does fix the issue reported. But I noticed one more thing with the fix implemented.

Is it possible to retain the Twitch purple color on the seeker bar itself? With your fix, the Twitch purple color on the seeker bar is also white-washed out. (See screenshots below).

Shot 1: (Twitch with Dark Reader and your fix implemented on a fresh Firefox Nightly Profile.)

![5Untitled](https://user-images.githubusercontent.com/89356985/130369382-fec7a3fd-a2e6-446b-86db-60498df892de.png)

Shot 2: (Twitch with no Dark Reader on a fresh Firefox Nightly Profile.)

![9](https://user-images.githubusercontent.com/89356985/130369611-4621eebc-8dd7-453d-9b71-439417994290.png)

**Comment by c-nagy** [comment]
Good catch, I updated the same pull request above to force the original color using CSS. How's that look?
