### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by spazstatic** [darkreader/darkreader#6581]
# Broken Website Report

## Website Address
https://fio.fnar.net/priceindices

## Steps To Reproduce

Graph colors do not update (specifically black) and leaves invisible graph lines

## Expected Behavior

Expected black graph line to be inverted or otherwise altered to be visible on dark background

## Actual Behavior

Black graph line is black and background is also black, rendering a portion of the graph invisible.

## Screenshots

![Screenshot from 2021-08-22 16-57-11](https://user-images.githubusercontent.com/30455085/130371306-88a738e1-9c42-4900-bab3-335343a75402.png)
![Screenshot from 2021-08-22 16-59-18](https://user-images.githubusercontent.com/30455085/130371319-3c5369e0-16b3-415c-b417-a4869e4ad855.png)

## System Information

- OS: Ubuntu 20.04.1 Kernel 5.11.0-27-generic
- Browser: Firefox 91.0.1 (64-bit)
- Dark Reader Version: 4.9.34

**Comment by c-nagy** [comment]
Hi, does this fix work on your end too? https://github.com/darkreader/darkreader/pull/6583/files

**Comment by Gusted** [comment]
#6583 is merged
