### ISSUE TITLE
Option to custom scrollbar or change the default scrollbar

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#6589]
# Feature Request
The default scrollbar looks too big and sharp, it's quite not nice so I think we need to add an option to change it. If it is too complicated or cumbersome, you can simply change the default scrollbar.

## Screenshots
Suggestions:
You can change from this:
![Screenshot 2021-08-23 172709](https://user-images.githubusercontent.com/87893636/130435224-5ecad7f8-0285-4ef7-9ca5-560bb80edb89.png)
To this:
![Screenshot 2021-08-23 172919](https://user-images.githubusercontent.com/87893636/130435373-09a54f8c-caef-47ac-b201-4e579c1d0a2f.png)

**Comment by Gusted** [comment]
#3812

**Comment by NguyenASang** [comment]
> #3812
I doesn't same my question
I mean change the scroll bar not only change the color of it. 
Why don't we change the scroll bar look more nice.

**Comment by bershanskiy** [comment]
@NguyenASang I'm not sure what you are requesting. Could you specify exactly what you want it to look like?

**Comment by NguyenASang** [comment]
> @NguyenASang I'm not sure what you are requesting. Could you specify exactly what you want it to look like?

I want it smaller and more round like this:
![130435373-09a54f8c-caef-47ac-b201-4e579c1d0a2f](https://user-images.githubusercontent.com/87893636/131506322-0feb3a57-d698-460a-aaa0-469ca438e3ec.png)

**Comment by Gusted** [comment]
> Why don't we change the scroll bar look more nice.
> Reopen it pls

"Nice" is a objective thing. I personally do like it more the current way which in my opinion is already pretty small.
If we will change default things each release I can guarantee you that other people will complain because something has just changed which they were used to. I can re-open it but unless their is a very high demand I don't see the reason why we would change the default.

**Comment by NguyenASang** [comment]
Okay if many people have very high demand, pls reopen it :((

**Comment by Gusted** [comment]
I will let it open for a while then.

**Comment by Uranite** [comment]
it would be good to have it as an option in the scrollbar settings, chrome canary and edge canary already has a flags to enable overlay scrollbar but firefox doesnt have one so its nice to have an overlay scrollbar in firefox, also i just couldnt get https://github.com/spencerwooo/firefox-overlay-scrollbar to work and it seems like it has issue with youtube fullscreen
![image](https://user-images.githubusercontent.com/62639703/132189300-3fd23b6c-c2d4-4f15-8771-169720821060.png)

**Comment by NguyenASang** [comment]
This is a long time no one commented or reviewed. So I decided to take my time to do it. 
Would you agree and allow me to do this @Gusted @alexanderby ? 
Honestly, I'm a newbie in programming, but I'll do my best 😁

**Comment by Gusted** [comment]
> This is a long time no one commented or reviewed. So I decided to take my time to do it.
Would you agree and allow me to do this
Honestly, I'm a newbie in programming, but I'll do my best grin

I'm not so sure what to add as we already have the option to ignore styling the scrollbar:
![image](https://user-images.githubusercontent.com/25481501/142828526-5f47b0e5-e271-4cbc-9df7-fb015103f40d.png)

**Comment by NguyenASang** [comment]
@Gusted Resize ? change curvature ? Only that. That's enough for me.

**Comment by Gusted** [comment]
> @Gusted Resize ? change curvature ? Only that. That's enough for me.

That isn't within the scope of Dark Reader, we just simply let you change the color of things, we shouldn't allow for cosmetic changes like that, it will just add more burden and complexity for something that you don't expect in dark reader.

**Comment by NguyenASang** [comment]
@Gusted Okay, now you can close this issue ;)) Thanks for answer and explain for me. I really want to donate for your wonderful support but I don't have Paypal :((

**Comment by Gusted** [comment]
> I really want to donate for your wonderful support but I don't have Paypal :((

It's not necessary to donate ;)

**Comment by NguyenASang** [comment]
@Gusted No, you deserve it.
