### ISSUE TITLE
[Broken Website] wikipedia.org

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6593]
# Broken Website Report

## Website Address

https://en.wikipedia.org/wiki/Poisson_distribution

## Expected Behavior

Labels in graph figures be compliant with dark mode.

## Actual Behavior

The x axis and y axis labels of graphs (LaTeX) become invisible in dark mode.

## Screenshots

![pic-selected-210823-2308-21](https://user-images.githubusercontent.com/59497618/130492402-43d57a6c-81ee-492e-8e32-4c1daada6c40.png)

![pic-selected-210823-2308-31](https://user-images.githubusercontent.com/59497618/130492417-1a409395-70ed-4a9d-bc13-2df6ffb0bbf0.png)

## System Information

- OS:  Linux
- Browser:  Firefox 91
- Dark Reader Version:  4.9.34

**Comment by Gusted** [comment]
Hi!

This is expected behavior, due to the way that wikipedia store images like these. We cannot invert such images as they would target other images which doesn't need to be inverted. Our proposed solution was to lighten the image when you hover over them.

Regards,
Gusted
