### ISSUE TITLE
Subdomain of sites in global dark list may not be dark

### ISSUE THREAD

**Issue by yodahuang** [darkreader/darkreader#660]
We need a more powerful syntax to specify what sites are truly "dark", just a domain names isn't enough.

An example would be [ffmpeg.org](https://ffmpeg.org). Its main site is dark, but [its Wiki (trac.ffmpeg.org/wiki)](https://trac.ffmpeg.org/wiki) is bright.

To make things worse, this setting can not be toggled by user since it's hard-coded in the global dark list. Hope there's an elegant solution for these situation.

**Comment by afarah1** [comment]
I'm having the same issue with trac.ffmpeg.org. I came here looking for a way to remove a website from this "global dark list" or at least understand what this is but found no documentation, just this issue.

**Comment by Oussebon** [comment]
The Humble store and Fanatical are both on the global dark list for me - despite the Humble store always having a bright background, and Fanatical's blog having a white background (unlike the main store page which is naturally dark grey) https://www.fanatical.com/en/blog

**Comment by Hubro** [comment]
I just Googled a question on https://faq.i3wm.org and the website is *insanely* bright, but it's in the dark list so I can't enable dark mode. This should be overridable by the user.

**Comment by val-litvak** [comment]
I am having the same issue with pro.coinbase.com and docs.pro.coinbase.com 

pro.coinbase.com is dark normally, so I added it to the dark list, but I wanted to make docs.pro.coinbase.com dark(it is white and there is no way to change the theme) but it seems like it is not possible with the current implementation.

**Comment by val-litvak** [comment]
Thanks @alexanderby ! Your solution would normally work, but because `pro.coinbase.com` is in global dark list, it did not work for me, please see my PR which fixes the problem(tested locally): https://github.com/darkreader/darkreader/pull/830

**Comment by metalim** [comment]
Huge Ping on this one!
It's awful to see Dark Reader being disabled on many subdomains, because you "tried hard" to make it work on main domains of those sites. https://support.discordapp.com/ burns my eyes.

**Comment by camdenorrb** [comment]
I'm also experiencing this with https://trac.ffmpeg.org/wiki

**Comment by Feez** [comment]
https://www.epicgames.com/fortnite/en-US/patch-notes/v8-10
dark btw

**Comment by Programatic** [comment]
I mean, its not terrible difficult to remove a site from the dark list. The extension is stored on your computer, so all you have to do is go to where it is installed, (for me I use Brave) https://stackoverflow.com/questions/21475866/where-are-installed-google-chrome-extensions-stored-locally  but this generally shows where it is and you can find it for each browser. This one goes for all chromium based ones. Then, you just go into the extension id (which you can find by enabling developer mode in chrome://extensions and looking at the id) and then just editing dark-sites.config in configs folder and remove the site. Then, just restart the extension by turning it off and on again and then it is removed.

**Comment by AlexByte** [comment]
@Programatic it will recover when the extension is updated.

**Comment by aaronth07** [comment]
The issue still exists, it would be amazing to be able to add individual subdomains to the inverted/non inverted list.

**Comment by camdenorrb** [comment]
Or maybe, like an option to bypass the global dark list?

**Comment by PicchiarelloMatto** [comment]
> I mean, its not terrible difficult to remove a site from the dark list. The extension is stored on your computer, so all you have to do is go to where it is installed, (for me I use Brave) https://stackoverflow.com/questions/21475866/where-are-installed-google-chrome-extensions-stored-locally but this generally shows where it is and you can find it for each browser. This one goes for all chromium based ones. Then, you just go into the extension id (which you can find by enabling developer mode in chrome://extensions and looking at the id) and then just editing dark-sites.config in configs folder and remove the site. Then, just restart the extension by turning it off and on again and then it is removed.


This method worked until before the update to Chrome 76, now if I modify the dark-sites.config file, after restarting the browser the extension does not start, and a message like "This extension may have been damaged" is reported (I translated it from my language).

**Comment by JacquesLeRoux** [comment]
+1, I'd really like to have this too!

**Comment by niczoom** [comment]
> What I'd like is related. I'd like to have google.com/maps in light mode but all google.com and all other subdomains in dark

Exactly what Im looking to do. I cant see an update which would enable this?

**Comment by niczoom** [comment]
Just had another look at it. I manually added 'google.com.au/maps' to 'Site list : Not invert listed' which now forces that address to be not inverted all the time.

Would be a much better option to have more granular control for sites like this. At the moment because google maps (/maps) isnt differentiated from google.com.au it cant be treated individually. Unlike myaccount.google.com which is a separate domain and dark mode can be toggled on/off.

**Comment by Gusted** [comment]
#2327 With this patch it's possible to add ! before a subdomain to exclude

**Comment by superarts** [comment]
@Gusted could you explain how it works please? I tried `/.+(google\.com\/maps).+/, !google.com/maps, /!google.com/maps/` and neither of them works for `https://www.google.com/maps/blah`

**Comment by Gusted** [comment]
Hi @superarts!

What are you trying to achieve?

It seems like you have google disabled but want google maps enabled?
I've just checked and then `!google.com/maps` should work. Do you have #2517's binary side-loaded?

**Comment by superarts** [comment]
Thanks @Gusted ! I want to enable Dark Mode for google, but not Google Maps, and I was modifying the last "exclude from dark mode" section.

![image](https://user-images.githubusercontent.com/491257/105200813-38782600-5b0e-11eb-8cec-505891abb7f1.png)

But about #2517, it was merged 10 days ago, and [in chrome store](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj?hl=en) it still shows 0.3.9 12/8/2020 build. How do I get the latest version please?

**Comment by Gusted** [comment]
> I want to enable Dark Mode for google, but not Google Maps,

Simply add `google.com/maps`.



> ![image](https://user-images.githubusercontent.com/491257/105200813-38782600-5b0e-11eb-8cec-505891abb7f1.png)

I've never seen this UI before.



> But about #2517, it was merged 10 days ago,

No? It's still pending and probably won't be merged for the next few months.



> How do I get the latest version please?

https://github.com/darkreader/darkreader/pull/2517#issuecomment-763747768
Latest commit of the master branch + the URL-Patch PR.

**Comment by pl0xy** [comment]
> > I want to enable Dark Mode for google, but not Google Maps,
> 
> Simply add `google.com/maps`.
> 
> > ![image](https://user-images.githubusercontent.com/491257/105200813-38782600-5b0e-11eb-8cec-505891abb7f1.png)
> 
> I've never seen this UI before.
> 
> > But about #2517, it was merged 10 days ago,
> 
> No? It's still pending and probably won't be merged for the next few months.
> 
> > How do I get the latest version please?
> 
> [#2517 (comment)](https://github.com/darkreader/darkreader/pull/2517#issuecomment-763747768)
> Latest commit of the master branch + the URL-Patch PR.

I've been using this for google maps for a while but google isn't on the global dark list./ now that i am using GitHub dark theme pages likes 1docs.github.com` are white and i can't figure out how to unexcluded them if you get my meaning?

**Comment by superarts** [comment]
I'm awfully sorry that  I am actually  looking at another product. My bad sir! 🙇

**Comment by Gusted** [comment]
> I've been using this for google maps for a while but google isn't on the global dark list./ now that i am using GitHub dark theme pages likes `docs.github.com` are white and i can't figure out how to unexcluded them if you get my meaning?

`github.com$` should do the job for now and later for #2517 just `github.com`

**Comment by mattwelke** [comment]
Ran into this today with `docs.github.com`. The page itself is kind of grey, so I think it's using my github.com theme choice (which is cool) but for a docs site, I would prefer something with more contrast. So I tried to turn on Dark Reader for just that subdomain, and noticed that it wouldn't enable it.

**Comment by alexanderby** [comment]
Fixed by https://github.com/darkreader/darkreader/commit/5546bd52e82f00dd1c436867f340170faaea868f
