### ISSUE TITLE
[Broken Website] quantrimang.com

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#6609]
## Website Address

https://quantrimang.com/internet-va-world-wide-web-co-giong-nhau-127310
( A Vietnamese website )

## Steps To Reproduce

Normally when I hover the cursor there, it turns orange like this:

![Screenshot (170)_LI](https://user-images.githubusercontent.com/87893636/130920787-713404a9-4321-466d-a707-31e5bf906c09.jpg)

But when I hover over the link that was fixed yesterday (the links in the circle I drew), it doesn't turn orange. (Actually in this picture, I hovered my cursor to the link but when I take a screenshot, the cursor doesn't appear)

![image](https://user-images.githubusercontent.com/87893636/130920122-1c804b7e-6055-4d53-9813-16af88f3793b.png)

When I enable the "Darkreader" extension, the website's icon is partially hidden

![image](https://user-images.githubusercontent.com/87893636/130919597-cb9c5ecf-608a-4030-88c3-8f7b812a9045.png)

When I turn off it

![image](https://user-images.githubusercontent.com/87893636/130919759-5f651980-fabc-4abc-a377-a4ce31693aff.png)

## System Information

OS: Windows 11 build 22000.160 64bit
Browser: Edge 92.0.902.78
Dark Reader Version: 4.9.34

**Comment by NguyenASang** [comment]
Can you fix it ? If you can pls read my report and fix the site 😕

**Comment by Gusted** [comment]
#6605

**Comment by NguyenASang** [comment]
These are new problems. You fixed the old bug and now I found another problem. Pls reopen or fix it

**Comment by NguyenASang** [comment]
You forgot to fix the logo bro -.-

**Comment by Gusted** [comment]
> When I enable the "Darkreader" extension, the website's icon is partially hidden

I'm not sure if I'm getting old or blind or having both, but I'm not seeing this "partially hidden" thing you're mentioning.

**Comment by NguyenASang** [comment]
You can see in this video :D 

https://user-images.githubusercontent.com/87893636/132798139-7409417b-5e64-4974-aec9-baf90729444c.mp4

You don't getting old or blind, you just don't notice it !

**Comment by Gusted** [comment]
That bug should be fixed with the latest master. Might be time to put up a issue and check for any issues before we release a new update.
