### ISSUE TITLE
Just an image is moved up partially outside the window

### ISSUE THREAD

**Issue by gaydenko** [darkreader/darkreader#661]
Image URL: http://gaydenko.com/audio/se/pcb/schematics20.png
Browser: Firefox 61.0.1 (64-bit)
OS: Manjaro Linux
Result: http://gaydenko.com/tmp/DarkReaderFirefoxError.png

**Comment by gaydenko** [comment]
Unfortunately, I prefer Filter mode. Can you, please, point me to that Firefox bug? Probably some workaround does exist...

And I can not understand the Firefox bug takes place here: with Dark Reader turned off image rendering doesn't expose any problems. So I would treat the issue as Dark Reader's one.

**Comment by risualiser** [comment]
You can just copy-paste the lines below to "Not invert listed".

> You can just add a general site exclude rule:
* `*/.*\.(jpg|jpeg|png|bmp|gif|svg|ico)$` for images
* `*/.*\.(mp3|wave|flac|ogg|webm|mp4)$` for audio and video
> - RalphLesch

**Comment by gaydenko** [comment]
Thanks for the workaround!
I still guess some predefined config can be equipped with distribution to avoid the issue.

**Comment by risualiser** [comment]
>some predefined config can be equipped with distribution

@alexanderby, what do you think about it?
