### ISSUE TITLE
Font size issue on spamcop.net

### ISSUE THREAD

**Issue by aimi617** [darkreader/darkreader#6624]
# Bug Report

## Bug Description
Dark Reader reduces a font size on spamcop.net site making it very small and hard readable.

## Steps To Reproduce
Go to [https://www.spamcop.net](https://www.spamcop.net) and switch to dark theme applying Alt+Shift+A or adding www.spamcop.net domain to Site list.

## Expected Behavior
All spamcop.net pages should switch to dark theme.

## Actual Behavior
The dark theme is applied but all fonts are reduced to a very small size around 6px-8px, after browser zooming up to 150% the redirection to another page triggers an opposite effect - very large font. Switching back to a normal white theme and reloading the font issue disappears.

## Screenshots
Without Dark Reader
![image](https://user-images.githubusercontent.com/33189191/131170624-3947a99d-86cf-47ae-b843-20061df79a39.png)

With Dark Reader
![image](https://user-images.githubusercontent.com/33189191/131170693-13c27bd7-fc99-40ef-8785-aba712273f03.png)

## System Information

- OS: Windows 7 SP1 64-bit
- Browser: Firefox Developer Edition v.92.
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
This is most likely a bug with firefox, we can do little to do this. Nor can I find any explaination of why it's doing this. But this seems to be also the behavior without dark reader.
