### ISSUE TITLE
'npm run release' fails: Cannot find module 'rollup-plugin-typescript2'

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#663]
I've just pulled 84335e1, and `npm run release` fails:

```
Error: Cannot find module 'rollup-plugin-typescript2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/paulo/src/darkreader/tasks/bundle-js.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/paulo/src/darkreader/node_modules/ts-node/src/index.ts:396:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/paulo/src/darkreader/node_modules/ts-node/src/index.ts:399:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! darkreader@4.6.2 release: `npm test && gulp release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the darkreader@4.6.2 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2018-08-08T20_38_54_901Z-debug.log
```

Here's the [debug log](http://paste.openstack.org/show/727673)

I'm running darkreader 84335e1 with nodejs 10.8.0-1nodesource1 on Xubuntu 18.04.1.

**Comment by alexanderby** [comment]
Try running `npm install`, some new dev dependency was added.

**Comment by marcelpaulo** [comment]
Hey, thanks for the info ! I installed nodejs just for darkreader, so you can guess how little I know about npm :-(

After running `npm install`, I got this:

```
found 227 vulnerabilities (134 low, 82 moderate, 11 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

so I went ahead and ran `npm audit fix` as suggested:

```
paulo:~/src/darkreader (master)$ npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2 packages from 2 contributors, removed 14 packages and updated 11 packages in 8.273s
fixed 201 of 227 vulnerabilities in 25210 scanned packages
  5 vulnerabilities required manual review and could not be updated
  2 package updates for 21 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)
```

Here I wasn't sure whether I should go on and run `npm audit fix --force`, so I tried `npm run release` again, and got these errors:

```
gulp[10472]: ../src/node_contextify.cc:637:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8b8210 node::Abort() [gulp]
 2: 0x8b82e5  [gulp]
 3: 0x8eb237 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb4daa8  [gulp]
 5: 0xb4fa12 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x3a263d1841bd
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! darkreader@4.6.2 release: `npm test && gulp release`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the darkreader@4.6.2 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2018-08-09T06_34_06_122Z-debug.log
```

I didn't know how to get out of this jam, so I wiped the repo, cloned it back, and repeated everything I'd done before:

```
npm install
npm audit fix --force
npm run release
```

Got the same error messages along the way, but this time `rpm run release` completed OK, even though gulp ate all my CPU away and took a long time to complete, longer that it used to before.

I really can't get my way around the nodejs ecosystem ! I follow the recipes to the letter, and get lost when things break. Anyway, darkreader updated. I left everything documented, just in case another lost soul like myself gets in the same jam and doesn't know how to get out of it.

**Comment by marcelpaulo** [comment]
I wasn't convinced whether it was really necessary to run `npm audit fix`, so I wiped the repo again, and repeated the steps, but not running `npm audit fix`, and `npm run release` built darkreader OK.

Not sure if this is off-topic, if you prefer I can open another issue to track it: do you know of a way to script the chrome extension refresh ? I use [myrepos](http://myrepos.branchable.com/) to handle updates to the repos I've cloned, and I haven't discovered a CLI command to refresh the chrome extension after running `rpm run release`: I open chrome, load `chrome://extensions` and manually refresh it. Right now I update darkreader using:

```
if gitup; then
    git pull -p
    npm run release
fi
```

(`gitup` is a simple bash script that checks whether there are new commits to pull)

I'd like to insert a command after `npm run release` to refresh the extension on chrome.

**Comment by alexanderby** [comment]
Most likely you have installed the latest Node.js with the latest NPM 6 and now you see the vulnerabilities report. Dark Reader itself doesn't have any dependencies (except one of my own packages). But it uses many packages for building the source files. As far as I know these vulnerabilities will not harm your computer, but if you build a website using these dependencies it can become vulnerable. Some of the dependencies (like `gulp-connect`) have outdated vulnerable dependencies and haven't published the update yet.

**Comment by marcelpaulo** [comment]
Thanks for the explanations, @alexanderby ! Indeed I have installed nodejs 10.8.0-1nodesource1 with npm 6.2.0.
