### ISSUE TITLE
[Broken Website] google.com/maps

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#6631]
## Website Address

https://www.google.com/maps/@75.5039189,-26.2466773,3z
## Screenshots

![image](https://user-images.githubusercontent.com/87893636/131205607-31a9dcaf-7a98-46cb-903a-fc4eba5884f6.png)

Error with color of the map.
## System Information

OS: Windows 11 build 22000.168 64bit
Browser: Edge 92.0.902.84
Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
This is correct behavior, it's simply inverting the color. It's the best we can do to make google maps dark.

**Comment by NguyenASang** [comment]
Can you make it like that. It's really beautiful :D
https://developers.google.com/maps/documentation/javascript/examples/style-array
If yes, reopen it.
