### ISSUE TITLE
[Feature Request] Add option to toggle off news fetching

### ISSUE THREAD

**Issue by codeswhite** [darkreader/darkreader#6637]
# Feature Request

## Is this feature request related to a problem?
DarkReader silently sends a POST request to `darkreader.github.io` which is **redirected** to `darkreader.org` a proprietry website as far as I know.

This poses a privacy issue, For the sake of the argument lets suppose that the owner of `darkreader.org` decides to take nefarious actions and track users without consent,
In that case, I could not know about that unless im told to.

So as far as things currently are, DarkReader could be classified as a spyware, unfortunately.
It collects user's data (including IP which is not anonymous).

## Screenshots
Location in code: `./src/background/newsmaker.ts:56`
`https://github.com/darkreader/darkreader/blob/0097a6d4c32fae10f13bbe8236d89e53a25191a8/src/background/newsmaker.ts#L56`

## Additional Context
I could suggest few options:
* Transparency over `darkreader.org` backend
* Toggle switch option for connecting to `darkreader.org`
+ Bonus: disable news fetching by default and issue a request only upon clicking "Get news!" or "What's new?"

A similar discussion took place on Etcher's github page:
https://github.com/balena-io/etcher/issues/2977

Please enlighten me if there was any mistake in my statements.
I'd like to amphasize that im a big fan of the work done on this project, it is really outstanding and i wish for it to become much more popular, please give users the privacy that they deserve.
 
EDIT: Typo and link to Etcher issue

**Comment by Gusted** [comment]
Hi @codeswhite!

> DarkReader silently sends a POST request to `darkreader.github.io` which is **redirected** to `darkreader.org` a proprietry website as far as I know.

You can find the source code on our organization profile[1][2]

Also the server is actually hosted by github.com, darkreader.org is only registered as domain but(assumption as I don't have any control over that repo) enabled as custom domain for github pages[3][4]

> This poses a privacy issue 

I agree! I've already opened up a PR to disable this news feature #4472 I just still need someone to code-review it and test it out before I can merge it with a guarantee that it works.

> For the sake of the argument lets suppose that the owner of `darkreader.org` decides to take nefarious actions and track users without consent,

Well the site is static-content, without any back-end to control(other then github that serve these files)[5] so any request that isn't going to evaluate JS(like fetch calls) is in theory not track-able for us, as our only way would be to do it via JS, which to clarify that we don't do this, we do not track users in any way possible.


> In that case, I as a user could not get to know about that.

Anything that involves the back-end can have this argument. As you can't verify what code is running on a server/machine[6]

>     * Transparency over `darkreader.org` backend

See my other comments. That should explain the 80%, but don't hesitate to ask questions.

>     * Toggle switch option for connecting to `darkreader.org`

Also see my other comment.

>     * Bonus: disable news fetching by default and issue a request only upon clicking "Get news!" or "What's new?"

That's a bit hard. As we do have a system in place for "important" messages, which we already have used. Such important messages will be displayed over the UI when fetched. These are important posts like about malware in the wild which installed by a quite few users[7]

1. https://github.com/darkreader/darkreader.github.io (Production-ready files)
2. https://github.com/darkreader/darkreader.org (development files)
3. https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
4. https://github.com/darkreader/darkreader.github.io/blob/master/CNAME
5. https://guides.github.com/features/pages/
6. https://www.youtube.com/watch?v=LkH2r-sNjQs (Pay attention to "Trust")
7. https://darkreader.org/blog/attention/

Regards,
Gusted

**Comment by codeswhite** [comment]
I see, should've done more research :)
Thanks for understanding!

**Comment by bershanskiy** [comment]
@codeswhite wrote:
>For the sake of the argument lets suppose that the owner of darkreader.org decides to take nefarious actions and track users without consent,

Browser extensions are in a sense the worst XSS threat that that web has ever faced. If you installed an extenison with `<all_urls>` and `tabs` permissions, than you have a much bigger problem on your hands than a benign server ping for recent blog post titles.

> I agree! I've already opened up a PR to disable this news feature #4472 I just still need someone to code-review it and test it out before I can merge it with a guarantee that it works.

I glanced over that PR and it looks reasonable. It just needs to be updated to use `chrome.alarms` instead of `clearInterval` and `clearInterval`. If you have time to resolve merge conflicts and migrate to `chrome.alarms`, I can do a proper review, test this manually and add unit tests.

Also, we should make sure Dark Reader does not store extra uniquely identifiers like user id/session cookies, uniquie HTTP ETags, etc. The fetched URL contains `(new Date()).toISOString()`:
https://github.com/darkreader/darkreader/blob/0097a6d4c32fae10f13bbe8236d89e53a25191a8/src/background/newsmaker.ts#L56
Is this really necessary? Off the top of my head, I do not see any legitimate reason for it. If user's and server's time is accurate, this value should match. If user's time is not accurate, it might be somewhat uniquelly identifying. If this is used to force cache off, it is probably redundant.

**Comment by Gusted** [comment]
> Is this really necessary? Off the top of my head, I do not see any legitimate reason for it. If user's and server's time is accurate, this value should match. If user's time is not accurate, it might be somewhat uniquelly identifying. If this is used to force cache off, it is probably redundant.

Actually, not that I know.

> If this is used to force cache off, it is probably redundant.

More likely this, it can be removed within the PR.

**Comment by Gusted** [comment]
> More likely this, it can be removed within the PR.

I've now removed that feature in the PR https://github.com/darkreader/darkreader/pull/4472/commits/7a01777446865eac6b50978eda4c9140b3f41561 as like you mentioned it was used to force a new cache. But given that their haven't been any blog posts over a year and a a a a lot of times are between them(while I do like and already mentioned some time to write some engineering blogs about problems we'd faced and how we solved them) it's really unnecessary to have it.|

And the conflicts are resolved now :) Goodluck reviewing!

**Comment by bershanskiy** [comment]
@codeswhite I'm pretty confident that commit which makes news fetching optional (#4472) will be included in the upcoming Dark Reader release.

**Comment by bershanskiy** [comment]
@codeswhite The relevant PR was merged, so in the next release you will be able to turn off news fetching. Also, you can do that even now if you build from current `master`. To do use this option:
 - click on extension icon to open popup
 - click on developer tools button to open Dark Reader's deeloper tools
 - in the window which will appear click on "Preview new design" to enable the new design (and then close this window)
 - open the popup again and click "Settings" > "Manage settings" > "Notify of news" to disable it
