### ISSUE TITLE
working inccorectly while using auto fill  in inputs

### ISSUE THREAD

**Issue by Akhil132-dev** [darkreader/darkreader#6649]
# Bug Report
dark reader  Working incorrect in login form 
## Bug Description
dark reader  Working incorrect while using auto fill in input 
## Steps To Reproduce
turn on dark reader 
go to any site login page 
use to auto fill to fill user info
## Expected Behavior
input background should be black and input text should to be white 

## Actual Behavior
input background is black on some site and text is also black and input background is white on some site and text color is black 

## Screenshots
![Screenshot from 2021-08-31 11-09-22](https://user-images.githubusercontent.com/71202802/131448859-0b4ca7f5-45cd-43a9-a7c0-318742f7c359.png)
![Screenshot from 2021-08-31 11-08-02](https://user-images.githubusercontent.com/71202802/131448885-97da3aef-ece9-4064-adb8-1545092f7963.png)

- OS: Linux 
- Browser:  Chrome 91
- Dark Reader Version: e.g. 4.9.34

**Comment by Gusted** [comment]
Hi @Akhil132-dev!

Do you use the native password manager of chromium?
As I'm not sure if we can do much due to that autofill is a protected feature and sites cannot style the autofill behavior:
https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill

Regards,
Gusted
