### ISSUE TITLE
darkreader settings are stored in which file ?

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#666]
As I kept using darkreader, I've added some sites to the `Not invert listed` list, and changed the theme engine for a lot of other sites. In which file these customizations are written ? I'd like to start including this file in my daily backup, in case I need to reinstall darkreader on Chrome, or install it on another browser and take with me all my customizations. Once I started using darkreader, I can't live without it ! So I'd like to keep safe all my customizations.

I've seen that #615 and #467 touch the same subject, but I wondered whether something had changed since those issues were opened. If your instructions in those issues is the way to get a backup of the settings, please forgive me for opening yet another issue.

I'm using darkreader installed from git master (6d468a4) with Google Chrome 68.0.3440.106 on Xubuntu 18.04.1

**Comment by alexanderby** [comment]
Just pushed an update 4.6.3.

Now to get all the settings use
```javascript
chrome.storage.sync.get(null, (settings) => console.log(JSON.stringify(settings, null, 4)));
```
To get site list only use
```javascript
chrome.storage.sync.get('siteList', (settings) => console.log(JSON.stringify(settings, null, 4)));
```

There is no UI for editing all the settings yet. I'm going to add at least a JSON editor. Currently you can edit settings using the console:
```javascript
chrome.storage.sync.set(JSON.parse('json text here'), () => console.log(chrome.runtime.lastError || 'OK'));
```
and then restart
```javascript
chrome.runtime.reload();
```

**Comment by marcelpaulo** [comment]
I've just upgraded to latest master and backed up my config following your instructions. Thanks a lot for the detailed answer, this is good reference material !

**Comment by CollinChaffin** [comment]
@alexanderby when the quota is exceeded and switched to local storage it appears I then get an outdated list from sync (from when it switched).  What DB is the local storage using if I need to back it up after the switch?  TIA!

**Comment by fermmm** [comment]
**Updated answer:**
Now settings export / import is supported in the UI
Go to: `More tab > All settings button > Advanced > There you can find the Import / Export buttons`
