### ISSUE TITLE
[Broken Website] tinder.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#6677]
# Broken Website Report

## Website Address
https://tinder.com/app/recs

## Expected Behavior
Buttons have icons.

## Actual Behavior
Icons does not have icons. 

## Screenshots
![20210903-1630689679](https://user-images.githubusercontent.com/9846948/132044262-236fcf36-c4f0-4368-a4cc-515c15361d50.png)
![20210903-1630689665](https://user-images.githubusercontent.com/9846948/132044265-09e4f7e3-7698-464d-a13f-fae48128d2ab.png)

## System Information

- OS: Windows
- Browser: Latest Chrome Stable
- Dark Reader Version: latest dev

**Comment by c-nagy** [comment]
Does that fix your issue ^ or is there anything else that needs tweaking?

**Comment by WaseemRakab** [comment]
also this site https://evewho.com/

**Comment by FadeMind** [comment]
@c-nagy thank you. Fix works perfectly. Regards

**Comment by c-nagy** [comment]
Good to hear! Hope you get some good matches on there.
