### ISSUE TITLE
[Broken Website] horstmann.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#6692]
# Broken Website Report

## Website Address
http://www.horstmann.pl/_pl/index.shtml

## Steps To Reproduce
- go to http://www.horstmann.pl/_pl/index.shtml

## Expected Behavior
Good looking site in dark.
## Actual Behavior
Mess. 

## Screenshots

![20210904-1630765853](https://user-images.githubusercontent.com/9846948/132098013-86a816ac-624c-4645-8994-9677246a8854.png)
![20210904-1630765840](https://user-images.githubusercontent.com/9846948/132098015-e25c24b4-d70e-4519-ab78-7d84e38a6895.png)

## System Information

- OS: Windows
- Browser: Chrome latest stable
- Dark Reader Version: latest dev

**Comment by Gusted** [comment]
It's indeed a mess, and uses a lot of images as styling with a combination of background-color attributes. Is such sites actually uses nowadays? As I otherwise don't see the necessary for a fix.

**Comment by FadeMind** [comment]
Fine.
