### ISSUE TITLE
[Broken Website] amazon.de

### ISSUE THREAD

**Issue by nyllewin** [darkreader/darkreader#6699]
# Broken Website Report

## Website Address
https://amazon.de

## Steps To Reproduce
open amazon.de with extension enabled either logged in or out, search for products

## Expected Behavior
should be dark

## Actual Behavior
listings and product detail page is not affected

## Screenshots
https://imgur.com/a/AsV1jz4

## System Information
 OS: w10 x64
- Browser: chrome latest
- Dark Reader Version: latest from chrome webstore

## Additional Context
in incognito i only allowed the dark reader extension

**Comment by Gusted** [comment]
Hi @nyllewin!

Do you have any other extensions enabled? I don't seem to be able to reproduce this bug.

Regards,
Gusted

**Comment by nyllewin** [comment]
Hi, yes but i added screenshots from incognito mode where only dark reader was allowed to function so that makes it a no.

**Comment by nyllewin** [comment]
fixed it by toggling dynamic mode to something else and back a few times. weird.
