### ISSUE TITLE
Unable to view cursor within CodeBlocks addon in Google Doc.

### ISSUE THREAD

**Issue by tarrenj** [darkreader/darkreader#671]
Not sure if this is within the scope of darkreader to fix or not. Please close this issue with `WontFix` if not.

https://chrome.google.com/webstore/detail/code-blocks/ebieibfdjgmmimpldgengceekpfefmfd?hl=en-US

Inside of a Code Blocks block with the zenburn theme, the cursor is not visible. This only happens when using Dark mode, and works as expected when using the Light mode.

**Comment by ShangxuanWu** [comment]
Did you find any solution to this? Thanks!

**Comment by tarrenj** [comment]
No I didn't.  Good luck!

**Comment by Gusted** [comment]
can't reproduce should be fixed.
