### ISSUE TITLE
Make automation independent of global on/off state of the extension

### ISSUE THREAD

**Issue by djasa** [darkreader/darkreader#6710]
# Bug Report

## Bug Description

Automation settings should be kept regardless of whether extension is on or off similarly as per-site settings are

## Website Address
 N/A

### Scenario one
1. install and enable DR
2. set up automation (e.g. Use system color scheme)
3. disable DR as whole
4. reenable DR

### Scenario two
1. install DR
2. set up automation
3. enable DR

### Scenario one
Settings are as in step 2: extension is enabled and follows system color scheme

### Scenario two
No automation is active, user setting was discarded

### Scenario one
DR is enabled with no automation, all sites are black even with light system scheme

### Scenario two
Automation is active

## System Information

- OS: Linux
- Browser: Firefox 91
- Dark Reader Version: 4.9.34

## Additional Context
N/A

**Comment by Gusted** [comment]
Seems like a good overlap with #3268
