### ISSUE TITLE
[Feature Request] Toggle inversion of specific image on the site

### ISSUE THREAD

**Issue by meandmymind** [darkreader/darkreader#6711]
# Feature Request

## Is this feature request related to a problem?
Generally I want to invert images on websites because they're too bright for dark mode. However, right now process of inverting images is complicated:
1. You have to invert image on the site by inserting special rule in Dev tools.
2. All images on the site are inverted and there's no easy way to un-invert one specific image if it's inversion looks bad. 

I would like to have an easy way to reinvert one particular image. For example, to right click on image and have line in context menu "Dark Reader > Invert Image" or "Dark Reader > Revert Image"

## Screenshots
For example:
This matrix image looks great inverted ![image](https://user-images.githubusercontent.com/24773652/132492989-751e754b-64dc-4ef2-a741-d29d8adb045b.png)

 But this Harold image looks bad inverted 
![image](https://user-images.githubusercontent.com/24773652/132493063-cd942f59-c3cc-4429-8a76-c64d41ffee17.png)

## Additional Context
DarkReader 4.9.34, Google Chrome 93.0.4577.63.

**Comment by Gusted** [comment]
A good overlap with issue #48 whereby such solution will cover this scenario.

**Comment by meandmymind** [comment]
@Gusted while this feature isn't implemented, can I use chrome dev tools picker and set some style class to element or smth to get it automatically inverted? or this won't work?

**Comment by Gusted** [comment]
> can I use chrome dev tools picker and set some style class to element or smth to get it automatically inverted? or this won't work?

Well the best thing you will get is to use the Chrome dev tools + DR dev tools. You can read more about the DR devtools usages in https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md
