### ISSUE TITLE
[Feature Request] Add context menus?

### ISSUE THREAD

**Issue by Enzodtz** [darkreader/darkreader#6717]
# Feature Request
Hey, I would like to suggest that in the feature that already exists of enabling or disabling the extension you could not disable the whole extension, but set default mode for ON/OFF. So, I could set it to be ON/OFF by default, and change its behavior if needed for the active tab. **Right now, you can't set it OFF by default and enable it only for the active tab, if its off, the tab option is off too.**

Also, it might be interesting to add this option of turning on/off when you right click in the page, like other extensions do. 

Thanks a lot!

## Is this feature request related to a problem?
No. 

## Additional Context
--

**Comment by bershanskiy** [comment]
This option is available under list of inverted pages.

**Comment by Enzodtz** [comment]
Oh, really cool, thanks a lot! It would be nice if the `alt+shift+a` function could be achieved via the right click too!

**Comment by bershanskiy** [comment]
> It would be nice if the `alt+shift+a` function could be achieved via the right click too!

Are you talking about [context menu](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items)? I can add that as an option, not sure if it will be enabled or disabled by default.

**Comment by Gusted** [comment]
What would be the added value into adding it into the context menu? I've been very reluctant to adding things to the context menu as people expect some kind of magic to be happening for those things. As we do have a limited space as extension and things like element pickers are still an open issue/feature request.

**Comment by bershanskiy** [comment]
> What would be the added value into adding it into the context menu?

It's just another alternative to shortcuts and regular buttons. I personally can remember (or find) context menu entries much easier than I can remember shortcuts.

> I've been very reluctant to adding things to the context menu as people expect some kind of magic to be happening for those things.

I agree that context menus should be very much opt-in, like shortcuts. Basically, context menu feature would be disabled by default with checkbox option on settings page.

I drafted a patch to add context menus and here is the new UI: 
![image](https://user-images.githubusercontent.com/45960703/132959971-bd539758-7848-473c-a12f-74f46e194b7c.png)

> As we do have a limited space as extension and things like element pickers are still an open issue/feature request.

What limited space are you talking about?

On a side note, I'll definitely make `contextMenus` permission optional. I don't like when apps/extensions require permissions to send notifications, add useless context menus, and do other annoying stuff.

**Comment by Enzodtz** [comment]
> As we do have a limited space as extension and things like element pickers are still an open issue/feature request.

I think that you are able to create side dropdowns, so this could maybe make the space a bit bigger.

But this is just a suggestion, please don't take it as an obligation, your work is already incredible, thanks!

**Comment by Gusted** [comment]
> What limited space are you talking about?

https://developer.chrome.com/docs/extensions/reference/contextMenus/#property-ACTION_MENU_TOP_LEVEL_LIMIT

Last time I checked it was something like 2 and some other limitation if other extensions added a context menu, but 6 seems sensible to work with.

**Comment by bershanskiy** [comment]
> > What limited space are you talking about?
> 
> https://developer.chrome.com/docs/extensions/reference/contextMenus/#property-ACTION_MENU_TOP_LEVEL_LIMIT
> 
> Last time I checked it was something like 2 and some other limitation if other extensions added a context menu, but 6 seems sensible to work with.

I think we should use nested dropdown, so we use only one top-level entry and then three entries within it.

As I mentioned, context menus would be entirely optional.

**Comment by bershanskiy** [comment]
@Enzodtz I drafted a PR for context menus, if you have any input, plase share. Does this properly address your needs?
