### ISSUE TITLE
[Feature Request] Export whitelist to JSON

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#6725]
Could you please add a feature to export all our whitelisted sites and settings to JSON? So in case we switch to another browser we could import it from that.

**Comment by bershanskiy** [comment]
Closing this for now, since this feature is already supported (please see above). If you have any other questions or this does not work for you, comment and I'll reopen this.

**Comment by haolly** [comment]
> Have you tried "Export Settings" option in the new UI?
> 
> To use it:
> 
> 1. Enable the new UI: press on Dark Rreader icon -> in the UI popup click on the bottom right button -> on the popup which opens press "Preview new design"
> 2. Export settings: press on Dark Reader icon -> in the UI popup click on "Settings" -> click on "Manage settings" -> click on "Export settings" -> a file will be saved
Step one is vague, I find it in the "Dev tools" button

**Comment by mmahmoudian** [comment]
[The instruction](https://github.com/darkreader/darkreader/issues/6725#issuecomment-916340005) was very confusing but I finally made it. I hope these would help the next person:

![image](https://user-images.githubusercontent.com/390889/144245559-3b1040f3-2a04-4959-80bf-cc278d2e3055.png)

![image](https://user-images.githubusercontent.com/390889/144245661-53e47ca7-7d59-42aa-bc97-a6ab10d2efb6.png)

![image](https://user-images.githubusercontent.com/390889/144245758-d73fe2e5-7a05-4bf7-a3d8-d37ba66b55cd.png)

![image](https://user-images.githubusercontent.com/390889/144245898-6a9124a9-1150-47ca-b283-57e2116bd867.png)

![image](https://user-images.githubusercontent.com/390889/144245943-591b8427-7333-4489-ae2c-349d1428f140.png)
