### ISSUE TITLE
[Broken Website] Comment icon on arstechnica.com

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6732]
# Broken Website Report

## Website Address
https://arstechnica.com/gadgets/2021/09/injunction-apple-must-open-up-app-store-payments-in-90-days/

## Steps To Reproduce
- Enable Dark Reader
- Go to https://arstechnica.com/gadgets/2021/09/injunction-apple-must-open-up-app-store-payments-in-90-days/
- Notice that the comment icon on the left of the article is broken.

## Expected Behavior

Comment icon works right.

## Actual Behavior

Comment icon is replaced with a broken inline icon.

### Dark Reader OFF
![image](https://user-images.githubusercontent.com/45960703/132912138-93af5476-eba6-4be1-be53-9aef1281a083.png)

### Dark Reader ON (broken)
![image](https://user-images.githubusercontent.com/45960703/132912223-7c80d3aa-78cf-4f48-8c49-d84a05e424f4.png)

### Dark Reader ON and inline style on `.comment-count` is removed (fine)
![image](https://user-images.githubusercontent.com/45960703/132912318-e03f7816-f7d3-4636-b2f1-cd5e81a41475.png)

## System Information

- OS: Windows
- Browser: Chrome 93
- Dark Reader Version:  4.9.34

**Comment by Gusted** [comment]
So this is good to note that this only seems to be happening on Chrome:
As on firefox, it will by default already correctly show it.
![image](https://user-images.githubusercontent.com/25481501/132956352-846d4721-2d35-4e5a-aeee-4de7631cf6f7.png)

**Comment by do-wie-ching** [comment]
It still happens on Chrome 94.0.4606.

**Comment by bershanskiy** [comment]
This was fixed in release 4.9.58 recently published to all stores (Chrome Web Store, Mozilla Addons, Edge Store). Please re-open if needed.
