### ISSUE TITLE
V4.9.35 Release

### ISSUE THREAD

**Issue by Gusted** [darkreader/darkreader#6737]
*Gusted gives Gusted a bypass to not follow the issue template*

So, hi @alexanderby and @bershanskiy and everyone interested into the dark reader development.

I'm trying to make this issue as for the first time in 1.5years we've not followed our unwritten rule about release schedules which was always every ~1 month. Our last release was 2 months ago on 7 July, which is quite a while back. 

I'm hoping with this issue to gather the release blockers before we can release(something that we might continue in the future).
I know that @bershanskiy has made some drastic changes, which luckily seems to not have broken anything in the master branch, but if you do have anything to be addressed before the next release please say it :).

I personally don't like having a long time between releases as certain changes like code changes, especially those who fixes bugs are only affected when a new release is distributed. 

So I do propose to have next week(on a Saturday) a new release if no release blockers come up and fixed by then.

Regards,
Gusted

**Comment by alexanderby** [comment]
How quickly the time passes.

Let's take a look if anything is broken in both Chrome and Firefox. I mean, any rare possible configuration, like automation by time or location, enabling for specific websites, anything else.

**Comment by alexanderby** [comment]
We should have done it by Puppeteer tests, but they are broken for Firefox, maybe some API have changed, maybe anything else.

**Comment by Gusted** [comment]
> We should have done it by Puppeteer tests, but they are broken for Firefox, maybe some API have changed, maybe anything else.

Hmm, I've seen that. Most likely it's some weird issue again with Puppeteer. As firefox seems to be hitting to a error(shown sometimes otherwise just some generic error with a weird stacktrace) `[firefox-profile] cannot delete profileDir on exit /tmp/firefox-profilenycVVr/ Error: ENOTEMPTY: directory not empty, rmdir '/tmp/firefox-profilenycVVr/'` You could check if your `tmp` folder is also having a non-empty firefox-profile as otherwise I will send a patch to https://github.com/saadtazi/firefox-profile-js

**Comment by Gusted** [comment]
This is getting kinda offtopic, but #6740 should be good to at least run the tests. I will check if can get a patch working for the firefox-profile-js.

**Comment by Gusted** [comment]
*Even more off-topic*, https://github.com/saadtazi/firefox-profile-js/pull/126

**Comment by alexanderby** [comment]
Hope it cannot remove everything, e.g. if profile directory is an empty string :)

**Comment by Gusted** [comment]
The application should run without elevated permissions...

**Comment by bershanskiy** [comment]
I'll look into the parser magic tomorrow with a fresh set of eyes. :)
From the top of my head, I do not think there are any other release blockers. I'll continue testing, though.

**Comment by bershanskiy** [comment]
If you have time, please review #6769 which has a simple fix for an annoying bug.

**Comment by Gusted** [comment]
Release-blocker: #6789

This messages will be edited to strike trough'ed text once resolved.

**Comment by Gusted** [comment]
@alexanderby Could you once you have time release the new update? The release-blocker has been resolved and fixed in the master branch.

**Comment by alexanderby** [comment]
Wow, well done! In the morning guys. We have never released on Saturday night yet 😁

**Comment by Gusted** [comment]
New version is up, can take a while to get published to the extension store due to new permission usages in `manifest.json`. Closing.
