### ISSUE TITLE
[Bug] Domains Index aren't URL Matched

### ISSUE THREAD

**Issue by Gusted** [darkreader/darkreader#6738]
# Bug Report

## Bug Description
The index.domains are currently being checked by 1-on-1 equal check:
https://github.com/darkreader/darkreader/blob/d69522753bff6abea855bcbc7661642ffc950db4/src/generators/utils/parse.ts#L172-L174

While they currently should be parsed by our inefficient and weird isURLMatch implemenation as it will allow `unix.stackexchange.com` to match `stackexchange.com`(Please note that the current config has *.stackexchange.com, but I'm planning on removing all `*.` references for now until the #2517 is merged)

## Website Address
https://unix.stackexchange.com/questions/797/how-can-i-find-the-implementations-of-linux-kernel-system-calls

## Steps To Reproduce
- Go to the site.
- See that the fixes aren't applied.

## Expected Behavior
Have the fixes applied

## Actual Behavior
Fixes aren't found.

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 93.0a1 (2021-09-04) 
- Dark Reader Version: https://github.com/darkreader/darkreader/commit/d69522753bff6abea855bcbc7661642ffc950db4

## Additional Context
CC @bershanskiy 
Blocker for #6737

**Comment by bershanskiy** [comment]
Just to make sure I understand this correctly, does pattern `example.com` match all subdomains? For example, `isURLMatched('https://www.sub.example.com', 'example.com')` returns `true`. Is this intentional?

When I was writing the new parser, I assumed that subdomains must be matched only against explicit wildcards. That is, pattern `example.com` does not imply any wildcards.

**Comment by Gusted** [comment]
> Just to make sure I understand this correctly, does pattern `example.com` match all subdomains?

Currently, yes. 

> For example, `isURLMatched('https://www.sub.example.com', 'example.com')` returns `true`

Yup, wel... not sure because of the added `www.` but in theory it should according to the current rules.

> Is this intentional?

Unfortunately, yes. That behavior is already removed in #2517 as it doesn't make sense to me as well.

> When I was writing the new parser, I assumed that subdomains must be matched only against explicit wildcards. That is, pattern `example.com` does not imply any wildcards.

Yup! In the same boat.

**Comment by bershanskiy** [comment]
I created PR #6749 which restores the old bahavior and adds unit tests for this behavior.
