### ISSUE TITLE
[Bug] bad uri parsing

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#6748]
# Bug Report

## Bug Description

Address parsing is wrong.

## Website Address

https://jigsaw.w3.org/css-validator/validator?uri=https://test.tld

## Steps To Reproduce

1. add test.tld to the local list
2. open https://jigsaw.w3.org/css-validator/validator?uri=https://test.tld

## Expected Behavior

jigsaw.w3.org should look dark

## Actual Behavior

jigsaw.w3.org should looks white

## System Information

- OS: 
- Browser: Firefox 92
- Dark Reader Version: 4.9.34

**Comment by bershanskiy** [comment]
Which "local list" are you talking about? The "invert only these" or "do not invert" list?

**Comment by 532910** [comment]
I see the only one list. It should be "do not invert", I suppose.

**Comment by Gusted** [comment]
Pretty sure this is a duplicate of #6417

**Comment by bershanskiy** [comment]
Since reporter reacted with "thumbs up", I'm closing this as duplicate.

**Comment by 532910** [comment]
it looks so
