### ISSUE TITLE
[Bug] PDFs with not clear text

### ISSUE THREAD

**Issue by demolitioner** [darkreader/darkreader#6755]
# Bug Report

## Bug Description
Not clear display of text in PDF files.

## Website Address
Address with PDF file:
https://www.researchgate.net/profile/Vigouroux-Regis-2/publication/277430396_The_role_of_ecological_strategies_in_the_colonization_success_of_pelagic_fish_in_a_large_tropical_reservoir_Petit-Saut_Reservoir_French_Guiana/links/55b74a9708ae092e96570dc7/The-role-of-ecological-strategies-in-the-colonization-success-of-pelagic-fish-in-a-large-tropical-reservoir-Petit-Saut-Reservoir-French-Guiana.pdf

Address from where this PDF file (also note, this page also bugging):
https://www.researchgate.net/publication/277430396_The_role_of_ecological_strategies_in_the_colonization_success_of_pelagic_fish_in_a_large_tropical_reservoir_Petit-Saut_Reservoir_French_Guiana

## Steps To Reproduce
Go to address with PDF file, which is noted in "Website Address" section.

## Expected Behavior
Good clear text (how "Night Eye" addon shows PDF text):
![2021-09-14 005855](https://user-images.githubusercontent.com/68711737/133162073-8fe82268-797b-4d3c-8a8b-86db6766b4ae.png)

## Actual Behavior
Not so clear text with violet antialiasing. Not convenient to read, you have to disable addon or scale.
![2021-09-14 005813](https://user-images.githubusercontent.com/68711737/133162061-9e4bcd2e-22bf-4f51-9a59-bd3139affb51.png)

## Screenshots
I don't know if it's appropriate to list additional bug from site https://www.researchgate.net/
That same PDF file, but in "site mode":
https://www.researchgate.net/publication/277430396_The_role_of_ecological_strategies_in_the_colonization_success_of_pelagic_fish_in_a_large_tropical_reservoir_Petit-Saut_Reservoir_French_Guiana

![2021-09-14 010456](https://user-images.githubusercontent.com/68711737/133162622-882d7a54-e701-4293-85ca-f750a872a99f.png)

white unneeded background, unintelligible faint text.
Bottom part showing pretty good.

## System Information
- OS: windows 10 x64 with latest patches.
- Browser: Any chromium based (chrome, edge, vivaldi etc)
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
The unclear text is coming from a side-effect to make images look more manage-able, I'm not sure what night-eye is doing. But I could give the current filter a try.
