### ISSUE TITLE
[Feature Request] Enable dark reader on selected websites only.

### ISSUE THREAD

**Issue by diivi** [darkreader/darkreader#6762]
# Feature Request

## Is this feature request related to a problem?
Currently, I have to enable dark reader on all websites, even if I want to use it only for one website, for eg. instagram, and then disable it on the ones that I don't want to use it for (many). I was thinking if a feature to enable darkmode only on specific sites could be added.

**Comment by bershanskiy** [comment]
This is already possible. Just do this: click on Dark Reader icon to open the popup UI -> click on "Lists" to open list tab -> click on "Invert only selected" -> add sites you want to be inverted.

I'm closing this issue since it is not actionable.
