### ISSUE TITLE
[Broken Website] Youtube (playlists)

### ISSUE THREAD

**Issue by javi2man** [darkreader/darkreader#6784]
![Screenshot_2021-09-17-00-09-14](https://user-images.githubusercontent.com/36956081/133718444-a1b8a89d-cd95-49f0-942e-f5f6f8b28daf.png)

Actual behaviour: On Firefox for Android, settings: from default ones, only changed Background color to #9FAC8A & Font color: to #000000 (Pure black). When opening a playlist on Youtube, the name of the videos are unviewave cause of the dark background (screenshot capure), 
Expected behaviour: More suitable background colour, visible videos's titles

**Comment by Gusted** [comment]
Please follow the issue template. I cannot understand what this issue is other then that it has some problem on youtube and playlist.
