### ISSUE TITLE
[Broken Website] Bytescout

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#6794]
# Broken Website Report

## Website Address
https://bytescout.com/products/developer/documentparsersdk/index.html

## Steps To Reproduce
- Open Firefox
- Set Dark Reader to use Dynamic Dark Mode
- Go to https://bytescout.com/products/developer/documentparsersdk/index.html
- Notice long delay until page fully loads all its resources
- Disable Dark Reader
- Clear all caches
- Go to the same URL 
- Notice that the site finishes loading all resources 5-6 times faster than with Dark Reader

## Expected Behavior
Page load its resources at about the same speed whether or not Dark Reader is enabled.

## Actual Behavior
With Dark Reader Dynamic Dark Mode enabled, page takes 5-7 times longer to finish loading than without Dark Reader.  If you load a bunch of pages from that site in background tabs, things get *even slower*.

## System Information

- OS: Windows
- Browser: Firefox 92
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
This is a performance issue, please use [the performance template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Performance+Issue&template=performance_issue.md&title=%5BPerformance+Issue%5D+Replace+with+title)

**Comment by Gitoffthelawn** [comment]
> This is a performance issue, please use [the performance template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Performance+Issue&template=performance_issue.md&title=%5BPerformance+Issue%5D+Replace+with+title)

Okay... I was following the example set by https://github.com/darkreader/darkreader/issues/6744

**Comment by Gusted** [comment]
Kinda my fault. But while doing initial profiling of that site it was clear to me that it was a old performance bug that was already fixed. This site is hitting another performance blocker which isn't fixed within the master branch.

**Comment by Gitoffthelawn** [comment]
> Kinda my fault. But while doing initial profiling of that site it was clear to me that it was a old performance bug that was already fixed. This site is hitting another performance blocker which isn't fixed within the master branch.

No problem... I won't have a machine on which I can perform a profile for at least a couple weeks (likely longer).  Would you still like me to file the issue report?  Whatever you prefer is good.
