### ISSUE TITLE
[Performance Issue]  Stripe.com Dashboard 30+ sec load time

### ISSUE THREAD

**Issue by Riversedgedesigns** [darkreader/darkreader#6799]
# Performance Issue Report

## Website Address
https://dashboard.stripe.com/

## Steps To Reproduce
Go To Stripe Dashboard. 
Any page on the subdomain of dashboard.stripe.com. 
Page takes 30+ seconds to load. High Ram 5+GB and high CPU ~16%.

## Performance Profile
https://share.firefox.dev/3nKwyAv

- OS: Windows 10
- Browser: Firefox 92 and Chrome 93
- Dark Reader Version: 4.9.34

## Additional Context
- Does this happen when Dark Reader is disabled? 
**No. Loads normally when dark reader is off.**
- Does this happen in other browsers? 
**So far tested in Firefox and Chrome**
- Do you have hardware acceleration enabled? 
**Probably?**

**Comment by Riversedgedesigns** [comment]
I should add: This is new. I'm fairly certain I was using Dark Reader on stripe before with no issues. No clue if its a Dark Reader or Stripe issue. 
If I had free time, I would look more into it. For now I will have to turn it off on the dashboard.  **[Insert meme of wearing sun glasses and still going blind]**

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/134228029-1b52e878-b3b3-425e-9095-cabd4275b389.png)
Not sure what Firefox is doing, but a lot of time is spent on native java script functionality which we cannot magically fix or reduce.
`insertRule` Already takes 4s 
`join` already takes 3s
`getImageData` already takes 2.5s 

It's all functions that generally take way way way less time to execute. So I'm really unsure why this is happening at all. As I'm only partially reproducing the problem but my profiler is more complaining about other hot functions and not generally these functions that you're having problems with.

**Comment by c-nagy** [comment]
Even with javascript fully disabled in `about:config` > `javascript:enabled` > `false` the page is still extremely sluggish. Looking at the style editor, there are tens of thousands of inline style sheet rules. Could this be related?
![rules](https://user-images.githubusercontent.com/3061769/134752604-98b83fa6-0bb3-4400-a95f-73db3d09bf6e.png)

**Comment by Gusted** [comment]
Could be related and as of why the insertRules are at such a high CPU time, as I do remember Firefox is now adding all reflows and recalculating of the styles into the CSSOM entries. And given that I do see in the profiler 
![image](https://user-images.githubusercontent.com/25481501/134761458-39833568-07b8-4c41-8d0a-aa5683fd38d1.png)
A high amount of reflushs, the high amount could be related.

**Comment by dm17** [comment]
For me stripe.com (docs) and dashboard.stripe.com cause tabs to crash consistently if dark reader is enabled. Happens in chromium & vivaldi.

**Comment by ricardo-rp** [comment]
I am having the same issue. Stripe will just straight-up refuse to load sometimes if the extension is enabled.

**Comment by lcdennison** [comment]
Same here. I have to disable/turn off DarkReader to use Stripe. I'm using Chrome here.

**Comment by Gusted** [comment]
I've had another fresh look at why this is being such slow, I'm still not able to find the root cause(Where it happens is clear, but the why and how to fix it is still unknown to me). I did however saw a optimize opportunity that should make loading the dashboard by 25%(average) faster. #7405 It's still not optimal and not the performance anyone wants.

@alexanderby Could you have a glance over at the `setRule` function and maybe identify why it's such slow in this case. I'd might be a specific combination of CSSText whereby Firefox is spending a lot of time parsing it? I'm not really able to figure it out.

Regards,
Gusted

**Comment by dm17** [comment]
Maybe if we all push on Stripe, they'll implement a dark theme toggle?

**Comment by Mitch-PragmaFlow** [comment]
Same issue here fwiw

**Comment by mohamedGamalAbuGalala** [comment]
same here using chrome (Version 108.0.5359.124 (Official Build) (64-bit)) on Ubuntu (22.04.1 LTS)

**Comment by matthewlloyd** [comment]
A simple workaround is to disable Dark Reader for `dashboard.stripe.com`, install the [TamperMonkey](https://tampermonkey.net/) extension, and add this user script which simply inverts the entire dashboard. Note you need to remove Stripe from TamperMonkey's security blacklist ("Blacklisted Pages") to get this to work:

```
// ==UserScript==
// @name         Stripe Dashboard Invert Colors
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Invert colors on the Stripe Dashboard
// @author       Matthew Lloyd (github@matthewlloyd.net)
// @match        https://dashboard.stripe.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=stripe.com
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';
    GM_addStyle('html {-webkit-filter: invert(100%); -moz-filter: invert(100%); -o-filter: invert(100%); -ms-filter: invert(100%); }');
})();
```

**Comment by aacitelli** [comment]
I am also experiencing this issue on Chrome 109.0.5414.120 64-Bit, Dark Reader 4.9.62, Windows 10. Stripe takes forever to load with the extension enabled.

**Comment by dm17** [comment]
Maybe it would be faster if we all pestered Stripe to have a dark mode feature? That seems like something that shouldn't be hard for them, especially considering their funding and supposed forward-thinking.

**Comment by nwparker** [comment]
> Maybe it would be faster if we all pestered Stripe to have a dark mode feature? That seems like something that shouldn't be hard for them, especially considering their funding and supposed forward-thinking.

Unfortunately, I doubt people are choosing their payment processor based on their presence of a dark mode. So there's likely near zero incentive for this to be added.

**Comment by dm17** [comment]
> > > Maybe it would be faster if we all pestered Stripe to have a dark mode feature? That seems like something that shouldn't be hard for them, especially considering their funding and supposed forward-thinking.
> > 
> > 
> > Unfortunately, I doubt people are choosing their payment processor based on their presence of a dark mode. So there's likely near zero incentive for this to be added.
> 
> It is actually something that I am weighing in my decision of which payment processor I integrate into my web application.
> 
> If a user has Dark Reader activated then there is a high likelihood that the user gives up on paying for the product.
> 
> Dark Reader is a popular extension and when it is activated Stripe frequently struggles to load.

Right, especially when it works on basically every website they'll just assume Stripe is broken in some other way and not have the time or skill to debug. That's reasonable imo - more to your point.

**Comment by alexanderby** [comment]
Could you please guys provide some relevant steps to reproduce, so that I can quickly look into it and possibly release a patch?

**Comment by dm17** [comment]
> Could you please guys provide some relevant steps to reproduce, so that I can quickly look into it and possibly release a patch?

Do you have access to an account that has dashboard.stripe.com? It should be as simple as having Dark Reader enabled and being on the page.

**Comment by alexanderby** [comment]
I will try registering. Could you please tell if there are any issues with the checkout itself?

**Comment by dm17** [comment]
> I will try registering. Could you please tell if there are any issues with the checkout itself?

I haven't seen any, no. And there is no checkout within dashboard.stripe.com.

**Comment by alexanderby** [comment]
Thank you for the update. I identified the cause: they are embedding lots of images into their [stylesheets](https://b.stripecdn.com/manage-statics-srv/assets/login.0af6239450bb0a72776c.css) for some reason, which is absolutely not optimal, and that causes slowdowns during CSS manipulations. I added some optimisations and will think of adding some more.

**Comment by alexanderby** [comment]
A lot of optimisations have been made. Now the loading time with Dark Reader is not noticeably different. It should benefit many other websites too. Unfortunately I'm afraid to release an update, because the review times are going to be unpredictable during the holidays, and I may not be able to push a hot fix for some potential critical bug. So it will be released around January 3. In the meantime please try using the Filter mode for that particular website.

**Comment by DouglasMoody** [comment]
This is still a major issue, so much so googled Stripe performing horribly to find this page.   Disabled Dark Reader on the page and first time Stripe ran perfect.

**Comment by beedell-roke** [comment]
@DouglasMoody, I am able to affirm this: [^1]

[^1]: [`reddit.com/r/stripe/comments/1ktdk3x/comment/nmire78`](https://www.reddit.com/r/stripe/comments/1ktdk3x/comment/nmire78/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

1. #### With DR Disabled

   I captured [`share.firefox.dev/492TWkF`](https://share.firefox.dev/492TWkF). However, if it's not as expected, that might be due to [`bugzilla.redhat.com/show_bug.cgi?id=2411722#c13`](https://bugzilla.redhat.com/show_bug.cgi?id=2411722#c13). I'll capture a replacement if so.

1. #### With DR Enabled

   [`share.firefox.dev/437mNR1`](https://share.firefox.dev/437mNR1) renders higher peaks.

I don't know whether a separate report is best. Especially, because frequent lag spikes remain regardless. ~~Perhaps, this would be, instead, best reported to [`webcompat/web-bugs/issues/new`](https://github.com/webcompat/web-bugs/issues/new?template=webcompat-bug-report.md).~~

#### My Environment

<blockquote>

~~~YAML
Version      : 143.0.4
Release      : 1.fc43
Architecture : x86_64
Install Date : Thu 30 Oct 2025 20:52:49 GMT
Size         : 262059513
Signature    : RSA/SHA256, Wed 08 Oct 2025 08:27:03 BST, Key ID 829b606631645531
Source RPM   : firefox-143.0.4-1.fc43.src.rpm
Build Date   : Mon 06 Oct 2025 08:16:57 BST
Build Host   : buildhw-x86-04.rdu3.fedoraproject.org
Packager     : Fedora Project
Vendor       : Fedora Project
Bug URL      : https://bugz.fedoraproject.org/firefox

~~~

</blockquote>

**Comment by nok91** [comment]
I’m experiencing significant performance issues when using Stripe dashboard and Stripe checkout page on the Zen Browser (Firefox fork). The dashboard becomes extremely laggy and nearly unusable. Scrolling, clicking, and loading different sections all feel delayed.

Other websites and web apps load normally in Zen, so this appears to be specific to GitHub’s UI or scripts.

Environment:
	•	Browser: Zen Browser 1.17.8b (Firefox 145.0.1)
	•	OS: Windows 11
	•	Stripe UI: dashboard, checkout page

Issue Details:
	•	Dashboard/checkout responds slowly to interactions
	•	Visual lag when scrolling
	•	Sometimes elements freeze before updating

**Comment by beedell-roke** [comment]
@nok91, I got as close to filing a ticket at [`webcompat/web-bugs/issues/new?template=webcompat-bug-report.md`](https://github.com/webcompat/web-bugs/issues/new?template=webcompat-bug-report.md) [^WebCompatPR] as:

[^WebCompatPR]: [`webcompat/web-bugs/pull/190965`](https://github.com/webcompat/web-bugs/pull/190965#issue-3656503955)

```Markdown
#### Browser/Version

`rpm -qi $(rpm -qf $(command -v firefox))` returns:

<blockquote>

~~~YAML
Version      : 143.0.4
Release      : 1.fc43
Architecture : x86_64
Install Date : Thu 30 Oct 2025 20:52:49 GMT
Size         : 262059513
Signature    : RSA/SHA256, Wed 08 Oct 2025 08:27:03 BST, Key ID 829b606631645531
Source RPM   : firefox-143.0.4-1.fc43.src.rpm
Build Date   : Mon 06 Oct 2025 08:16:57 BST
Build Host   : buildhw-x86-04.rdu3.fedoraproject.org
Packager     : Fedora Project
Vendor       : Fedora Project
Bug URL      : https://bugz.fedoraproject.org/firefox

~~~

</blockquote>

#### Operating System

`rpm -qa | grep fedora-release` returns:

<blockquote>

~~~ASM
fedora-release-identity-kde-desktop-43-25.noarch
fedora-release-common-43-25.noarch
fedora-release-kde-desktop-43-25.noarch
~~~

</blockquote>

#### What The Problem Is <!-- (Required) -->

- [ ] Desktop site, instead of mobile site
- [ ] Mobile site is not usable
- [ ] Video doesn't play
- [ ] Layout is messed up
- [ ] Text is not visible
- [x] Something else <!-- (Add details below) -->

#### Steps To Reproduce



#### Expected Behavior



#### Actual Behavior

As [`darkreader/darkreader/issues/6799#issuecomment-3476329563`](https://github.com/darkreader/darkreader/issues/6799#issuecomment-3476329563) explains:

<blockquote>

@DouglasMoody, I am able to affirm this: [^1]

[^1]: [`reddit.com/r/stripe/comments/1ktdk3x/comment/nmire78`](https://www.reddit.com/r/stripe/comments/1ktdk3x/comment/nmire78/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

1. #### With DR Disabled

   I captured [`share.firefox.dev/492TWkF`](https://share.firefox.dev/492TWkF). However, if it's not as expected, that might be due to [`bugzilla.redhat.com/show_bug.cgi?id=2411722#c13`](https://bugzilla.redhat.com/show_bug.cgi?id=2411722#c13). I'll capture a replacement if so.

1. #### With DR Enabled

   [`share.firefox.dev/437mNR1`](https://share.firefox.dev/437mNR1) renders higher peaks.

I don't know whether a separate report is best. Especially, because frequent lag spikes remain regardless. Perhaps, this would be, instead, best reported to [`webcompat/web-bugs/issues/new`](https://github.com/webcompat/web-bugs/issues/new?template=webcompat-bug-report.md).

</blockquote>
```

However, I re-evaluated with a new `about:profiles` in `firefox-145.0.1-1.fc43.x86_64` with `4.9.115.xpi`, for good measure, and, lo and behond, it was remediated. [^FFNew] Re-enabling DR on my original profile initially didn't appear to reduce the speed significantly. However, it appeared to become worse as I left it enabled, even without the tab open. It solely appears to affect significant UI actions, though.

[^FFNew]: [`share.firefox.dev/4ps9X8A`](https://share.firefox.dev/4ps9X8A)

**Comment by alexanderby** [comment]
I discovered that getBoundingClientRect() for SVG elements seem to work slower than in Chrome. There are quite many inline SVG icons. It seems to work fine after an optimization. Please share some examples of the Stripe payment pages with no registration requirement (I have access to the dashboard itself).

In the meantime please use Filter mode for Stripe.
