### ISSUE TITLE
[Bug] Darkreader breaks RunKit

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#6809]
# Bug Report

## Bug Description

Darkreader breaks RunKit

## Website Address

https://npm.runkit.com/regexpp

## Steps To Reproduce

- Go to above site
- Turn on darkreader
- Reload
- Editor isn't there
- Turn off darkreader
- Reload
- Editor is there

## Expected Behavior

Editor is there

## Actual Behavior

Editor isn't
## Screenshots

![Screenshot from 2021-09-19 16-50-51](https://user-images.githubusercontent.com/53054099/133946946-beff4206-b03e-4303-b0e1-df428f4bbb7f.png)

## System Information

- OS: Ubuntu
- Browser: Chrome 92.0.4515.159
- Dark Reader Version: 4.9.34

## Additional Context

Noticed a few 404s, maybe DarkReader does something to `fetch`?
![Screenshot from 2021-09-19 16-51-58](https://user-images.githubusercontent.com/53054099/133946986-819d6c12-1894-409c-9bfd-8582452f7582.png)

**Comment by Gusted** [comment]
#2420
