### ISSUE TITLE
[Broken Website] lg.com

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#6810]
# Broken Website Report

## Website Address
https://www.lg.com/us/burners-drives/lg-GH24NSC0-internal-dvd-drive

## Expected Behavior
Page inverted

## Actual Behavior
Page not inverted and is thus blinding.

## System Information

- OS: Windows
- Browser: FF
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Hi @nathanielcwm!

The page is just working as fine and is getting modified. Are you using dynamic theme?

Regards,
Gusted

**Comment by nathanielcwm** [comment]
Yep

**Comment by Gusted** [comment]
Seems like it just affected me, not sure what happened to me 2 days ago 🤷🏽
