### ISSUE TITLE
[Bug] Suddenly doesn't work anymore in Waterfox 2021.08.1

### ISSUE THREAD

**Issue by mkruselj** [darkreader/darkreader#6815]
# Bug Report

## Bug Description
So I was just browsing the Web as per usual, Dark Reader helping me with overly bright sites as per usual. Out of a sudden, it just stopped working globally, on any sites I tried. I also tried completely removing and reinstalling the add-on, same thing happens.

## Website Address
Any website

## Steps To Reproduce
No real reproduction steps, it just stopped working suddenly!

## Expected Behavior
Obviously, I'd like it to work normally :)

## Screenshots
When I click on Dark Reader icon, I see this:

![image](https://user-images.githubusercontent.com/2393720/134067821-5e114cae-4d30-4fde-9128-08870b2c3d65.png)

In about:debugging I see this:

![image](https://user-images.githubusercontent.com/2393720/134067854-c61468c3-62d9-4376-b1a4-0fa7f96014df.png)

Then if I click on Debug I see this:

![image](https://user-images.githubusercontent.com/2393720/134068030-ef7fd261-52e9-40f0-90ac-9ca6c7d41db7.png)

![image](https://user-images.githubusercontent.com/2393720/134068039-e6cd835d-f2fe-4e84-a82c-e950f35860b9.png)

## System Information
- OS:  Windows 10 Pro 2004
- Browser: Waterfox 2021.08.1
- Dark Reader Version: 4.9.35

**Comment by Gusted** [comment]
Well we don't treat waterfox as a first class browser, it was a pretty dead simple fix this time around.
CC @alexanderby Another reason to get a hotfix for this issue + Dev tools.

**Comment by mkruselj** [comment]
@Gusted Thanks for extremely quick turnaround!

I still really depend on some XUL add-ons, which is why I still use Waterfox... But yeah, it's getting more and more difficult to retain the freedom in how I want my browser to work and what I want it to do. 🙁

**Comment by Gusted** [comment]
> I assume then the very next version of Dark Reader will have this fix in. Are there any nightly builds available, perhaps?

Yup, and nope no nightly versions. But a hotfix will hopefully be released.
