### ISSUE TITLE
Getting endless "Loading, please wait". (EDIT: caused by going from version 4.9.34 to 4.9.35 on older firefox versions like 75?) Tried reinstalling. Tried deleting obvious cache files from firefox profile. Any *non* obvious cached data I should try clearing out?

### ISSUE THREAD

**Issue by OwenAR** [darkreader/darkreader#6819]
(
EDIT:
So given a couple other people quickly jumped in here reporting the same problem on older firefox versions (and forks equivalent to older firefox versions)
it sounds like maybe this was actually caused by a recent update to darkreader itself,
and it was just a coincidence that it happened to me right after I restored my system with the newer firefox and synced from it.
(And therefore clearing out cached stuff from my firefox profile wouldn't solve the problem.)

---
EDIT:
Just installed previous version 4.9.34 (from https://addons.mozilla.org/firefox/downloads/file/3806938/dark_reader-4.9.34-an+fx.xpi ) (reverting from 4.9.35)
(and turned off "Allow automatic updates")
and yup, it works again!

I assume I should leave this open as a bug though, right? Since presumably the newer version of the addon can and should be fixed to still work with older versions of firefox?
)

---
---
I just started getting this endless "Loading, please wait" on one of my computers
(and darkmode isn't working on any pages).

(
The firefox it's broken on is an old v 75.0 (which I need to still run on that computer for reasons)
(the firefox on the other computer is v 92.0 on ubuntu, where darkreader is working fine).

I'm *suspecting* the issue was caused by some weird syncing edgecase thing,
because I just restored the computer running 92.0 from a backup...
)

Anyway, I tried uninstalling and reinstalling,
but that didn't work.

Then I tried uninstalling, deleting the obvious cache files from my firefox profile, and *then* reinstalling.
(
"Obvious" meaning the matches in my firefox profile dir for
`find -iname '*dark*reader*'`
which were just
`./browser-extension-data/addon@darkreader.org`
`./extensions/staged/addon@darkreader.org`
)
But that didn't work either.

---
So are there any *non*-obvious cached data I should try clearing out?
How should I do so?

Because when I grep in my profile dir for `'dark.*reader'`, I get a bunch of matches:
```
	addons.json
	browser-extension-data/bookmarksearchplus2@aafn.org/storage.js.migrated
	prefs.js
	saved-telemetry-pings/0dadd29c-ae49-4f1d-a50f-ef38994df75a
	saved-telemetry-pings/125493a8-0db0-4f02-9601-f117b6ee0505
	saved-telemetry-pings/1b85f300-15a1-43e1-9856-f869e2484ebe
	saved-telemetry-pings/2702a488-f512-4218-8512-22817b78333d
	saved-telemetry-pings/2c485e8d-a41d-4ab7-8698-0a0373b1ae49
	saved-telemetry-pings/2d5fa56c-918e-4ce4-9504-2c08bb862fda
	saved-telemetry-pings/2e96af11-e19e-47e5-b16f-9f1716d396a2
	saved-telemetry-pings/3a19f531-129e-4fb9-bc8b-fefbba519805
	saved-telemetry-pings/3e6c72eb-4980-4f23-8b21-d468f8a8740b
	saved-telemetry-pings/4ddf57ac-8a99-4c76-b6de-e1520f157dd4
	saved-telemetry-pings/631cb3ea-0de5-402a-85ee-3e3eee67e924
	saved-telemetry-pings/64caa585-b3b1-43e5-9dfd-7abb8fb80c3b
	saved-telemetry-pings/6835ac4e-14b7-4944-8afc-079fbbe82cb2
	saved-telemetry-pings/6cb1b8af-60f9-46d6-a2f0-e1f6909aa5b4
	saved-telemetry-pings/7198c9e6-4722-4b48-9025-a02caf00d5dd
	saved-telemetry-pings/71b94b01-799d-484e-980e-111b07cdd246
	saved-telemetry-pings/7921ad8f-9f37-4087-ab12-526588d411a8
	saved-telemetry-pings/7ac2d535-9b85-4318-9ed6-7fdf75081c3a
	saved-telemetry-pings/809bd238-177b-4d0f-9807-c515239a8ed7
	saved-telemetry-pings/8137e1dc-b97e-454d-a207-4c4e87b1cbae
	saved-telemetry-pings/815046e7-cd2d-46a0-980e-6ec0c4cee429
	saved-telemetry-pings/8dce370e-7d46-4f41-967c-5a8ace39e28f
	saved-telemetry-pings/8f70539a-6ca4-4efc-a0b5-163dc1620a3a
	saved-telemetry-pings/90ee3c47-77db-49f0-81ef-e91f37fca12e
	saved-telemetry-pings/9476f9e7-7001-413f-bd78-aa809a643d7c
	saved-telemetry-pings/98d7bd9f-938e-4765-adca-bf013370a958
	saved-telemetry-pings/9981d2da-94c0-4786-b417-4a5ca37bcf14
	saved-telemetry-pings/a2594f5c-0521-4e58-86e7-adb9f300bc3e
	saved-telemetry-pings/a44192cf-716a-438a-b3cc-33308e1496f3
	saved-telemetry-pings/a547fd39-eff1-4847-8216-22adb8cbcb4d
	saved-telemetry-pings/a8fe944c-7807-4ac8-8b8d-28db2f37b52f
	saved-telemetry-pings/b2fa110b-c320-4e99-814c-249fc1582aff
	saved-telemetry-pings/b54c58ff-ec38-4275-b3cc-47844e4810c5
	saved-telemetry-pings/bbc4447f-e8e1-47af-a904-079af9ace439
	saved-telemetry-pings/beccfddd-2c8b-4c0c-84e3-d20403fc6a8e
	saved-telemetry-pings/bf8aff95-93f6-4fb0-85da-49c56eaf3a11
	saved-telemetry-pings/cdbea5e0-de89-4b9f-94cd-e618f5fd0ba9
	saved-telemetry-pings/d169ee9c-6283-47d0-a5d6-78c8ee6f3a70
	saved-telemetry-pings/d5259932-7827-409b-8425-a104691970c1
	saved-telemetry-pings/dc37c0d0-605b-4bac-870c-36aa6820b0b3
	saved-telemetry-pings/e27a9bb6-95b8-4a24-a30f-41e984d55156
	saved-telemetry-pings/f122e0c4-b776-4f63-bb47-8801ec620d69
	weave/addonsreconciler.json
	weave/logs/error-sync-1631807388254.txt
	weave/logs/error-sync-1631873585264.txt
	weave/logs/error-sync-1631874256024.txt
	weave/logs/error-sync-1631874349482.txt
	weave/logs/error-sync-1631874537960.txt
	weave/logs/error-sync-1631876778614.txt
	weave/logs/error-sync-1631878138253.txt
	weave/logs/error-sync-1631878835688.txt
	weave/logs/error-sync-1631879122786.txt
	weave/logs/error-sync-1631879792773.txt
	weave/logs/error-sync-1631880999768.txt
	weave/logs/error-sync-1631881723648.txt
	weave/logs/error-sync-1631882384787.txt
```
and obviously I'm neither gonna delete a bunch of files that I don't understand what they do,
nor go through and blindly try to manually remove references to darkreader...

(To be clear, all of this messing with reinstalling and cache deleting stuff was on the computer with 75.0 ; I haven't messed with in on the 92.0 comp at all.)

**Comment by CuriousApe2020** [comment]
Same issue with LibreWolf.

**Comment by Gusted** [comment]
Seems to resemble #6815. If someone could build from the master branch and check if the issue is fixed with libreWolf + older Firefox version would be nice as Im not able to do that.

**Comment by slumbergod** [comment]
Broken for me too.
Waterfox Classic 2021.9 (64 bit) on Manjaro

**Comment by OwenAR** [comment]
So given a couple other people quickly jumped in here reporting the same problem on older firefox versions (and forks equivalent to older firefox versions)
it sounds like maybe this was actually caused by a recent update to darkreader itself,
and it was just a coincidence that it happened to me right after I restored my system with the newer firefox and synced from it...?

I guess I should edit-to-add a note bout that to my opening post.

**Comment by slumbergod** [comment]
Rolled back to previous version: Dark Reader Version 4.9.34
Problem gone.

**Comment by OwenAR** [comment]
Just installed it (from https://addons.mozilla.org/firefox/downloads/file/3806938/dark_reader-4.9.34-an+fx.xpi )
(and turned off "Allow automatic updates")
and yup, it works again!

Thank you so much! I've been slogging through fractal computer problems for days,
so it's encouraging to for once be able to reach out for help and have a bug disappear pretty much immediately. ^^

**Comment by OwenAR** [comment]
Whoops, guess I shouldn't've *closed* the bug, since presumably the newer version of the addon can and should be fixed to still work with older versions of firefox, right?

**Comment by Gusted** [comment]
Pretty sure v4.9.35 is causing this.

**Comment by ahembree** [comment]
Can confirm that the new Dark Reader 4.9.35 is causing login page issues. Disabling extension allows the login pages to work. I submitted another bug report that mentions a CSRF error I get from the webserver logs. https://github.com/darkreader/darkreader/issues/6839

**Comment by dezraj** [comment]
I'm experiencing this very same issue in Firefox for Android version 68.6.0 in an old Asus tablet with Android 4.4.2. After the update the extension stopped working. Is a fix for this being worked on or should I uninstall the new version and reinstall the previous one?

**Comment by Gusted** [comment]
V4.9.36 is already created and IIRC being published to the extensions stores: https://github.com/darkreader/darkreader/releases/tag/v4.9.36

Which will fix this issue.

**Comment by CuriousApe2020** [comment]
I still have the same Issue!

**Comment by OwenAR** [comment]
@CuriousApe2020 You should probably say what version of what browser you're on, and what version of darkreader you're running?

**Comment by Gusted** [comment]
Locking this issue as any further issue after v4.9.36 is a new and other exciting issue.
