### ISSUE TITLE
[docs.google.com] Cursor black on dark background

### ISSUE THREAD

**Issue by zeroepoch** [darkreader/darkreader#6821]
# Broken Website Report

## Website Address
docs.google.com

## Steps To Reproduce
1. Enable dark mode on Chrome using chrome://flags
2. Enable dark reader and visit a Google document
3. Looks better generally except the cursor is black, which is very hard to read on a near black background

## Expected Behavior
The cursor color should match the text color, which is normally white when in dark mode.

## Actual Behavior
The cursor color is always black and very hard to read.

## Screenshots
![image](https://user-images.githubusercontent.com/1310250/134088305-e3b1e7b9-3b34-49c0-83bc-8773b2c1aa61.png)
The cursor above is between "E" and "r", which is hard to tell.

## System Information
- OS: Linux (Fedora 34)
- Browser: Chrome 93.0.4577.82
- Dark Reader Version: 4.9.34

## Additional Context
It doesn't happen on Firefox and correctly shows a white cursor color. It's specific to Google Chrome's dark mode when enabled by chrome://flags. Removing the `.kix-cursor-caret` block added by #2135 fixes the issue. This might be a problem with the Google docs dark theme on Chrome, but Dark Reader is generally able to enhance the theme and correct this issue with the change mentioned earlier.

**Comment by Gusted** [comment]
We do not support the usage of multiple dark modes.

**Comment by zeroepoch** [comment]
@Gusted what do you mean by multiple dark modes? Is Dark Reader not supported when the browser is forced to dark mode. Google docs chooses to show a dark theme by default (can't see a way to change it actually) when the browser is in dark mode. Maybe that is what you are referring to? Not supporting that would be strange since dark mode in the browser makes blank pages black and changes some of the settings pages that compliment Dark Reader.

**Comment by bershanskiy** [comment]
Browser flags are experimental and subject to change without any prior announcement. Dark Reader does not support them.

> Enable dark mode on Chrome using chrome://flags
Just to make sure are you talking about Chrome's flag "Force Dark Mode for Web Contents" at chrome://flags/#enable-force-dark ? There are 8 "enable" options, are you using the simplest one?

**Comment by zeroepoch** [comment]
That's correct I'm just using the plain Enabled option.
![image](https://user-images.githubusercontent.com/1310250/134136562-0c059bf3-6215-4a1f-ab71-069cd8c21bfa.png)

**Comment by zeroepoch** [comment]
I think I understand now why Dark Reader and Chrome's dark mode option are not guaranteed to work together. As you explained Chrome could make changes that are inconsistent even on the same version between platforms. We can keep this closed. I have a local workaround for now anyways.

**Comment by Korb** [comment]
I'm using Dark Reader 4.9.110 (July 18, 2025) with Mozilla Firefox 144.0b2, and after enabling dark theme for `docs.google.com`, the cursor turns black _(i.e., invisible in most cases)_ when copying formatting.

Can this be fixed?
