### ISSUE TITLE
[Bug] Location base automation does not work anymore since update

### ISSUE THREAD

**Issue by freebrowser1** [darkreader/darkreader#6827]
# Bug Report

## Bug Description
After the update of 20 Sept to 4.9.35 the automatic darkening based on location did not work anymore, It happens on any website.

## Website Address
Any

## Steps To Reproduce
Fill in a location (in my example 44 N and 6 E) and when getting dark, the dar reader does not enable automatically anymore. Same applies to sunrise.

## Expected Behavior
It should work as previously, i.e. automatically darken at sunset at the provided location.

## Actual Behavior
Automation does not work.

## System Information

- OS: macOS
- Browser: Firefox 92
- Dark Reader Version: 4.9.35

## Additional Context
As long as this does not work, where can I obtain the 4.9.34 ?

![Screenshot 2021-09-21 at 07 46 00](https://user-images.githubusercontent.com/26625141/134118646-c51fd0f4-5993-463d-8acf-4379ed68264d.png)
>

**Comment by Gusted** [comment]
@bershanskiy Could you have a look for this one?

**Comment by bershanskiy** [comment]
Can reproduce locally. Will prepare a patch.
