### ISSUE TITLE
[Bug] Keyboard shortcuts no longer working on Firefox

### ISSUE THREAD

**Issue by X-m7** [darkreader/darkreader#6832]
# Bug Report

## Bug Description

Dark Reader's keyboard shortcuts no longer work on Firefox (as in the toggle extension, toggle current site and theme generation mode shortcuts do nothing when pressed).

## Steps To Reproduce

- Open any page that isn't protected by the browser (like this issue report page).
- Press Alt+Shift+A (or any of the other keyboard shortcuts).

## Expected Behavior

The shortcut should take effect (so if it's Alt+Shift+A the look of the site should change to match the setting).

## Actual Behavior

Nothing happens.

## System Information

- OS: Arch Linux
- Browser: Firefox 92.0
- Dark Reader Version: 4.9.35

## Additional Context

The browser does catch the shortcuts, they work if I assign the same key combinations (say Alt+Shift+A) to another extension (like the built in Firefox screenshot one, I also tested [this](https://addons.mozilla.org/en-US/firefox/addon/duplicate-tab-shortcut/) extension and it worked too). I also tried changing the shortcut combination to several other ones, and they still don't work. I also tried creating a new profile to start fresh and only install this extension, and it doesn't work there either.

Also, I don't use the shortcuts all that often anymore since I've already blacklisted most of the sites that either already have a dark mode or just don't work well for whatever reason, so I can't pinpoint when exactly it started breaking and what changes in the system could have caused it.

**Comment by Gusted** [comment]
Hotfix will be released later this week after we've fixed all regressions.
