### ISSUE TITLE
Stopped working on fennec fdroid 68.12esr

### ISSUE THREAD

**Issue by metbic** [darkreader/darkreader#6837]
Yesterday evening dark reader stopped working. Used to work very well. Going to the three dot menu and tapping on dark reader does not open the normal black bg settings window. Instead a broken loading bar goes endlessly.

**Comment by metbic** [comment]
Deinstalled, re-installed, no effects.

**Comment by metbic** [comment]
Downgrading to 4.9.34 fixes it.

**Comment by Gusted** [comment]
Not actionable. Please follow the bug report next time, but a hotfix which fixes this issue will be send out this week.
