### ISSUE TITLE
[Broken Website] https://vivaldi.com/ is broken

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6845]
# Broken Website Report

## Website Address

https://vivaldi.com/

## Steps To Reproduce

- Go to https://vivaldi.com/
- Press "Download Vivaldi" to be taken to greeting page
- Observe that the greeting has a light image background

## Screenshots

![image](https://user-images.githubusercontent.com/45960703/134243792-d8a84247-54c5-49af-9c56-404ba82ca999.png)

## System Information

- OS: Windows 10
- Browser: Chrome 93
- Dark Reader Version: 4.9.36

## Additional Context

The background uses [this image](https://vivaldi.com/wp-content/themes/vivaldicom-theme/img/bg_soft_lights.webp). Perhaps, we could simply replace it with Dark Reader's neutral background color.

**Comment by demolitioner** [comment]
Another bug in https://vivaldi.com/features/

![1](https://user-images.githubusercontent.com/68711737/134329083-46c896ba-f02e-4f28-9146-a853e0929508.png)
![2](https://user-images.githubusercontent.com/68711737/134329085-245f4c1b-39b9-4552-a1e8-f151338cb67a.png)

Image flow not showing at right of "Everything's an option" in dark mode.
Images becomes dark-invisible, yet they are not background images.

win10, chromium-based, DR 4.9.36.
