### ISSUE TITLE
[Bug] [NOT A DUPLICATE OF #3585] New Chrome PDF viewer UI can be modified

### ISSUE THREAD

**Issue by Raymo111** [darkreader/darkreader#6850]
## THIS IS NOT A DUPLICATE OF #3585

# Bug Report

## Bug Description
The new Chrome PDF viewer can be modified by right click > inspect element (Ctrl+shift+I does NOT work). As a result we can apply CSS to things like the toolbar to make it dark.

## Website Address

Any PDF

## Steps To Reproduce

1. Open any PDF
2. Right click > Inspect element (Ctrl+shift+I does NOT work)

## Expected Behavior

UI elements are also dark along with the PDF

## Actual Behavior

Only the PDF is dark

## Screenshots

![Screenshot_20210921_235829](https://user-images.githubusercontent.com/34818275/134281334-d0ee86f6-70d0-4ea9-ae3e-9cb013a47595.png)

## System Information

- OS:  Arch Linux
- Browser:  Version 93.0.4577.82 (Official Build) (64-bit)
- Dark Reader Version: 4.9.35 

## Additional Context

See https://github.com/darkreader/darkreader/issues/3585 for history.

**Comment by Gusted** [comment]
That's pretty weird, I'm on 94.0.4606.54 (Official Build) (64-bit) + Arch Linux
But: http://www.africau.edu/images/default/sample.pdf
Is still showing me: 
![image](https://user-images.githubusercontent.com/25481501/134300185-bbdfda43-4f78-4127-8f52-68c56c9309af.png)

**Comment by Raymo111** [comment]
> That's pretty weird, I'm on 94.0.4606.54 (Official Build) (64-bit) + Arch Linux
> But: http://www.africau.edu/images/default/sample.pdf
> Is still showing me:
> ![image](https://user-images.githubusercontent.com/25481501/134300185-bbdfda43-4f78-4127-8f52-68c56c9309af.png)

Did you right click > inspect element? The title of the window should then go from the URL to the Chrome PDF Viewer extension (that's how Chrome does the new PDF viewer), and all the extra elements should appear.

**Comment by Raymo111** [comment]
![Screenshot_20210922_111955](https://user-images.githubusercontent.com/34818275/134372428-1b7c80dd-0817-4ef1-92ed-5aa4e469c278.png)

**Comment by Gusted** [comment]
> Did you right click > inspect element? The title of the window should then go from the URL to the Chrome PDF Viewer extension (that's how Chrome does the new PDF viewer), and all the extra elements should appear.

I always uses ctrl + shift + i because the inspect element is really really tricky as it can open the devtools in a sub-frame like these. And because this is a extension:
![image](https://user-images.githubusercontent.com/25481501/134373154-a97e9f10-cd0a-4fd8-a592-fda07b502f65.png)

It will not be supported as we cannot do anything to other extensions not even with weird injections or shenigans or anything, simply not possible. Issue is closed.
