### ISSUE TITLE
[Broken Website] The advertisement on YouTube is cut when the dark reader turns on.

### ISSUE THREAD

**Issue by do-wie-ching** [darkreader/darkreader#6851]
# Broken Website Report

## Website Address
https://www.youtube.com/

## Steps To Reproduce
- Go to https://www.youtube.com/
- See the Advertisement on the front page.
- Turn on/off dark reader.

## Expected Behavior
Show the whole advertisement.

## Actual Behavior
Advertisement's left and right sides usually are cut.

## Screenshots
![](https://github.com/do-wie-ching/screenshots/blob/main/Trun_off.png?raw=true)
![](https://github.com/do-wie-ching/screenshots/blob/main/Trun_on.png?raw=true)

## System Information

- OS: Windows 11 Pro 22458
- Browser: Chrome 93
- Dark Reader Version: 4.9.36

**Comment by Gusted** [comment]
Hmm not sure how this can happen as we do not touch `img`. Ill leave this open for now as I don't see any indication for the reasoning.

**Comment by do-wie-ching** [comment]
# Hi Gusted,
# Thank you for replying
