### ISSUE TITLE
"null" message when loading menu

### ISSUE THREAD

**Issue by risualiser** [darkreader/darkreader#686]
Noticed on 4.6.3 on mobile Firefox.
The extension itself still works.

**Comment by alexanderby** [comment]
Could you please give more details?

**Comment by risualiser** [comment]
Ok, it may be not actual now, but this happens for 0.5-2 seconds only on current version.

![](https://i.imgur.com/dyAhb53.png)

Also, logo can be not loaded immediately (for 0.5 seconds too).

![](https://i.imgur.com/OXY1WSk.png)

**Comment by risualiser** [comment]
"null" message disappeared in 4.6.5, great!

**Comment by alexanderby** [comment]
I've just pushed the update 4.6.5. The page was showing "null" instead of "Loading, please wait". Strange, that it doesn't happen to me, but the stats shows that 5,000 users silently removed the app the same day the 4.6.3 was published.
