### ISSUE TITLE
[Broken Website] Unable to trigger PayPal account MFA challenge on Firefox 

### ISSUE THREAD

**Issue by DamienCarpy** [darkreader/darkreader#6860]
# Broken Website Report

## Website Address
paypal.com

## Expected Behavior
when connecting to one's account for the first time, an MFA challenge is proposed (either SMS or phone call).

## Actual Behavior
Having automatic dynamic Dark Reader enabled on FF 92.0 gives an error from PayPal. Authentication process is stopped. Disabling Dark Reader for paypal.com enables proceeding to MFA challenge page (in my case receiving an SMS). Works perfectly on Chrome 94 with or without Dark Reader enabled.

## Screenshots

Broken step with Dark Reader enabled
![image](https://user-images.githubusercontent.com/47356096/134322655-c0a93111-cd57-4900-bcd3-8d72b251e187.png)
Working step with Dark Reader disabled (either globally or just for PayPal)
![image](https://user-images.githubusercontent.com/47356096/134323047-32933267-9d8f-48f1-bd2d-c50521cc6a4f.png)

## System Information

- OS:  Windows 10 21H1
- Browser:  Firefox 92.0
- Dark Reader Version:  4.9.35

**Comment by bershanskiy** [comment]
Hello, do you get anything in the consoles (page's own console, Dark Reader console)?

**Comment by DamienCarpy** [comment]
Sorry, I don't know how to do that

**Comment by jones23** [comment]
I have encountered the same problem. both with Firefox 92 and the latest version of Brave browser. But this error does not occur on every installation. i have multiple VMs with multiple browsers on each. and only in two cases this error occurs. in other instances both firefox and brave work just fine with dark reader and paypal.

but i have a reproducible situation with a Firefox installation.  i can provide more information if you tell me how to open the dark reader console. 
![Capture2](https://user-images.githubusercontent.com/20248863/134789535-181bc293-7441-4a1f-9c29-d85b68e98ead.PNG)

this little bug cost me a RX6800 btw :(

**Comment by larry77** [comment]
Hello,
Any news on this? It is actually a major issue for a wonderful tool like dark reader.

**Comment by Gusted** [comment]
> Hello,
> Any news on this? It is actually a major issue for a wonderful tool like dark reader.

Not much, I'm not able to reproduce any of this. The next release might solve it. But other than that it's just open for anyone to have a look at it. I cannot force myself into a reproduction and then fix it.

**Comment by larry77** [comment]
I see. Then I cross my fingers for the next release of Firefox and /or dark reader.

**Comment by cipitaua** [comment]
confirmed on both firefox and chromium

**Comment by larry77** [comment]
In my case, with the new Firefox release the issue appears to have gone away.

**Comment by xandro0777** [comment]
This plagued me for some time and problem magically disappeared now :) Since I am on an older LTS version of Firefox I don't think that it was a browser update in my case but could be wrong.

**Comment by javierorozco** [comment]
it's resolved for me in all browsers and OS after new version updates

**Comment by Gusted** [comment]
OP, @DamienCarpy, is the issue resolved for you?

**Comment by DamienCarpy** [comment]
Yes it's working again with Dark Reader active. Besides browser update, Paypal also changed the way they're interacting with european customers, it may have also changed things here. Closing issue now, thank you for your patience, feedback & keep up the good work :-)

**Comment by flleeppyy** [comment]
It's happening again :(

with DR
<img width="426" height="278" alt="Image" src="https://github.com/user-attachments/assets/db3619b3-3d12-44b4-aae2-c1992f1d9c70" />

without DR

<img width="401" height="360" alt="Image" src="https://github.com/user-attachments/assets/52f540d6-a6b4-4903-973b-e742d850f91c" />
