### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by sanon** [darkreader/darkreader#6870]
# Bug Report

## Bug Description

In Vivaldi, Dark Reader affects web panels. This was a resolved issue actually but it's started happening again.

## Website Address

Any site.

## Steps To Reproduce

- Add any site as web panel in Vivaldi. 
- Open its panel.
- (Please see the attached capture. Even if Wikipedia is not in my "invert listed only" list, it is darkened on the panel. On the tab it looks ok.) 

## Expected Behavior

Web panels should not be affected by Dark Reader.

## Actual Behavior

All web panels are affected by Dark Reader.

## Screenshots

![2021-09-22 20 38 46 en m wikipedia org 3e85774ac40f](https://user-images.githubusercontent.com/6686059/134395980-a264608f-8eca-4577-b0ff-88e7f731d744.jpg)

## System Information

- OS:  Edition	Windows 10 Home 64bit 20H2; OS build: 19042.1165
- Browser:  Vivaldi 4.2.2406.48 (Stable channel) (64-bit)
- Dark Reader Version:  4.9.35

## Additional Context

İf this has nothing to do with Dark Reader now I am sorry to waste your time but the closed issue which was about the same problem basically was resolved by the Dark Reader team if my memory doesn't fail me. Thanks in advance...

**Comment by Gusted** [comment]
#6842

**Comment by bershanskiy** [comment]
@sanon You write that you used Dark Reader 4.9.35. The fix was applied after 4.9.35 was released, so you might not have the fix.

**Comment by sanon** [comment]
Hi @bershanskiy , 
4.9.35 is the latest version on Chrome's web store. Should I download a newer version from Github?

**Comment by bershanskiy** [comment]
At this time I'm not sure when the fix will land in CWS and what will be the version number (4.9.37, may be).

If this bug really bothers you, then you are welcome to build from source on CI and install the output. Of course, you will be able to go back to CWS version once fix propagates to it. Note: remember to export your Dark Reader settings, if you need them _before_ deleting CWS version.

To do this:
 1. Fork this repo
 2. Go to GitHub Actions "Create binary for release" action under the new fork https://github.com/sanon/darkreader/actions/workflows/tagged-release.yml
 3. Dispatch workflow by clicking "Run workflow" and selecting `master` branch and duration of 1 (day) or more.
 4. Wait for completion
 5. Download produced `artifact.zip` and extract `darkreader-chrome.zip`, then extract that and install it.

Hopefully, instructions are sufficiently detailed and clear. If not, ask.

**Comment by sanon** [comment]
@bershanskiy 
Seems to be working now. Thanks for the detailed instructions.
