### ISSUE TITLE
[Broken Website] linuxcollections.com

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#6875]
# Broken Website Report

## Website Address
https://linuxcollections.com/products/debian/debian.htm

## Expected Behavior
Background inverted

## Actual Behavior
Background is kept a blinding white.

## Screenshots
![image](https://user-images.githubusercontent.com/22572406/134460922-869688f6-1397-43b1-b570-2166a3763fac.png)

## System Information

- OS: Windows
- Browser: FF 92
- Dark Reader Version: 4.9.36

**Comment by Gusted** [comment]
Phew, this is too many images to invert and it wouldn't look as good as it someone might expect. Wontfix.
