### ISSUE TITLE
[Broken Website] Wikipedia charts are broken

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#6876]
# Broken Website Report

## Website Address
https://en.wikipedia.org/w/index.php?title=Main_Page&action=info

## Steps To Reproduce

 - Go to https://en.wikipedia.org/w/index.php?title=Main_Page&action=info
 - Click on the cell right of "Page views in the past 30 days"
 - Observe that axis labels are invisible
## Expected Behavior

Chart is visible.

## Actual Behavior

Axis labels are invisible (black on almost-black).

## Screenshots

Dark Reader OFF:
![image](https://user-images.githubusercontent.com/45960703/134461444-3b6f2035-61a5-46c2-85d1-503449f686e2.png)

Dark Reader ON:
![image](https://user-images.githubusercontent.com/45960703/134461479-2e8e483a-4759-4d1c-a519-90d82395c542.png)

## System Information

- OS: Any
- Browser: Any
- Dark Reader Version: 4.9.36

## Additional Context

Same fix should probably be applied to all Wikipedia locales `*.wikipedia.org`.

**Comment by Gusted** [comment]
Did you share the correct link? I cannot find any link to such charts on the provided webpage.

**Comment by bershanskiy** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/45960703/134522835-51bae61d-ac2e-4234-a6a0-babcf6bb51dd.png)

**Comment by Gusted** [comment]
Ah seems like you can only see those when you're logged in.
