### ISSUE TITLE
Opera side bar

### ISSUE THREAD

**Issue by noxan-dev** [darkreader/darkreader#6882]
# Bug Report

## Bug Description

While the extension is active the opera sidebar addons; Instagram, WhatsApp, Twitter, and the rest have Dark Reader enabled even though I have "invert listed only". This is a recent issue and after I updated Opera, not sure who the issue belongs to. The individual websites for the sidebars don't apply a dark theme, just the sidebar.

## Steps To Reproduce

Install extension using the Chrome addon
Turn it on using invert list
Look at the sidebar extensions and they should be in the dark theme when not added to the list

## Expected Behavior

I expect the side extensions to not be in a dark theme

## Actual Behavior

Set to a dark theme

## Screenshots

![image](https://user-images.githubusercontent.com/59417659/134542279-006efe0a-0d09-4ea9-a114-230711dbc80e.png)
![image](https://user-images.githubusercontent.com/59417659/134542344-e2d176d2-f95c-4869-87be-28e290e39a33.png)

## System Information

- OS:  Windows 10
- Browser:  Opera 79.0.4143.50
- Dark Reader Version:  4.9.36

## Additional Context

Things like WhatsApp and the player aren't even showing pictures or chats.

**Comment by bershanskiy** [comment]
I can not reproduce this locally.

This is oddly similar to a Vivaldi bug we fixed recently, #6870. Would you be interested in installing a pre-release build to see if it fixes this issue?

**Comment by noxan-dev** [comment]
> I can not reproduce this locally.
> 
> This is oddly similar to a Vivaldi bug we fixed recently, #6870. Would you be interested in installing a pre-release build to see if it fixes this issue?

Sure. Let me know what you would like me to do.

**Comment by bershanskiy** [comment]
If you could follow test plan from #6858 that would be great.

**Comment by noxan-dev** [comment]
should I be installing the mv3 or the plain one?

**Comment by noxan-dev** [comment]
I tried both and they don't seem to work

> If you could follow test plan from #6858 that would be great.

**Comment by noxan-dev** [comment]
is there anything else I can try

**Comment by Gusted** [comment]
Not really anything to do as far as I know, if it is a regression a possible git-bisect could help. But as from I understand it could be either opera bug or something on our end.

**Comment by noxan-dev** [comment]
ok. It may be Opera because this only happened after I had performed an update.

**Comment by Donkeykong307** [comment]
I have the same issue in #6925. Only discord in my sidebar comes up blank, the rest are ok. I downloaded and built the source for v4.9.34 and discord doesn't have the issue with that version, for me at least.

**Comment by noxan-dev** [comment]
> I have the same issue in #6925. Only discord in my sidebar comes up blank, the rest are ok. I downloaded and built the source for v4.9.34 and discord doesn't have the issue with that version, for me at least.

any way you can run me through how to do this myself? I want to give it a shot.

**Comment by cremasterjedi** [comment]
this is still happening w/me in Opera, both with discord and websites that are added as custom panels (via a flag you can turn on).  seems very similar to the issue with the vivaldi panels.

**Comment by Demo95** [comment]
Tried this today and installed Dark Reader in Opera. (4.9.42)
Enabled the manual bookmark addition and noticed that regardless of the settings in Dark Reader, every added sidebar panel was in 'static' dark mode, even if I disable the extension in it's settings (switch to off).
I then built 4.9.34 manually and the sidebar panels are now in 'dynamic' dark mode and seem to listen to the setting I make in Dark Reader. Perhaps it's noteworthy that changed settings aren't applied immediately, but only after I restart the browser.

**Comment by RomX2** [comment]
Im still having this issue on Instagram, Twitter, Discord and Spotify. Opera GX LVL3 (core: 82.0.4227.50) and Dark Reader 4.9.43

**Comment by Intenzi** [comment]
> Im still having this issue on Instagram, Twitter, Discord and Spotify. Opera GX LVL3 (core: 82.0.4227.50) and Dark Reader 4.9.43

I am having the same issue on this dark reader version of 4.9.43 for opera gx on all sites on my sidepanel including Spotify.

**Comment by Intenzi** [comment]
The only thing that I have noticed that could be of any assistance is :- 
Manually turning off the extension completely and then refreshing Spotify side panel player fixes it.
![image](https://user-images.githubusercontent.com/62426443/148165749-22e89820-31e3-49cb-809c-0b949754bb11.png)


Turning the extension off from alt+shift+d and then refreshing the Spotify side panel player **does not fix it.**
![image](https://user-images.githubusercontent.com/62426443/148165856-3cc60cb1-4fb3-432f-ac05-3d6faf1ae150.png)

**Comment by noxan-dev** [comment]
> 

This does work but when you refresh the tab it resets. Just tried update 4.9.43 and it's still the same.
