### ISSUE TITLE
Static generator mode does not allow changes

### ISSUE THREAD

**Issue by marshallbrain** [darkreader/darkreader#6887]
# Bug Report

## Bug Description
Editing the static theme generator mode does not remember changes made within the css editor.

## Website Address
Any Website

## Steps To Reproduce
- Select the static generator mode under the more tab
- Click on the red circle with the slash in it in the upper right corner of the static button
- Make changes within the text box of the window that opened
- Click apply
- Website does not change to reflect the changes
- Close and reopen the window
- Changes no longer there

## Expected Behavior
Website should change to reflect the changes made to the static css editor and should remember changes when reopened.

## Actual Behavior
Website does not change and the css editor does not remember changes when reopened.

## System Information

- OS: Windows 10
- Browser: Chrome 94
- Dark Reader Version: 4.9.37.1

## Additional Context
The bug seems to be caused by this line : 
https://github.com/darkreader/darkreader/blob/e10df7b5c4d4546e8bcac0f9014510be59d546fa/src/ui/connect/connector.ts#L14
The line errors with this message :

> Error handling response: TypeError: Cannot destructure property 'data' of 'undefined' as it is undefined.

This causes the stylesheet-editor to only display the default interface.

**Comment by Gusted** [comment]
That's pretty weird, I don't get such error. And looking at the code such thing cannot happen theoretical as we don't rely on some obscure code.

**Comment by marshallbrain** [comment]
I looked into it some more and found that this line: 
https://github.com/darkreader/darkreader/blob/90bb1f0c4ae7e915e547bf2bdc603e725326c1b0/src/background/messenger.ts#L30

If I add `, chrome.runtime.getURL("/ui/stylesheet-editor/index.html")` to the end of the list then it at least partially fixes it for me.

**Comment by Gusted** [comment]
Aha, we still uses the old stylesheet-editor for the non-V5 UI.
