### ISSUE TITLE
Controlling grayscale/contrast/sepia in images

### ISSUE THREAD

**Issue by ddnexus** [darkreader/darkreader#689]
The fact that images are not inverted looks good, but what about controlling their other properties in order to blend them with the overall look?

If you use a quite low contrast and desaturated setup for html items, the icons and images are painfully popping out from the rest, and I would like to lower contrast and saturation accordingly.

**Comment by ddnexus** [comment]
I found out that the `filter` and `filter+` already apply the grayscale/contrast/... to images, while `static` and `dynamic` don't. 

An enhancement to explicitly include/exclude images from the filter might be welcome for the overall flexibility of the extension, but I am happy even without, since I am using the plain `filter` that already looks pretty good with my settings.

**Comment by ddnexus** [comment]
Maybe the final goal of this ticket coshoulduld be modified to "Adding an explicit `images` check-box option, in order to include/exclude images from the filtering".

**Comment by alexanderby** [comment]
These modes work on different principles: Filter mode inverts the whole page pixel by pixel and adds some filter areas over images, videos, etc. to invert them back. Dynamic and Static modes change the colors declared for elements, filters are also used when the image is detected (or declared) as an icon that needs to be inverted. It should be possible to add filter for other images, but I'm afraid it can slow down the app, some research is needed.

**Comment by ddnexus** [comment]
Thanks for the explanation. As I said, I am fine with `filter`  and `filter+` which look great with my settings. Personally, I don't find the need to use `static` or `dynamic` at all, so it's up to you at this point :). Thanks for the single most useful extension in the world! :1st_place_medal:

**Comment by Gusted** [comment]
#6044
