### ISSUE TITLE
[Bug] Chrome Extension: Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by nCubed** [darkreader/darkreader#6892]
# Bug Report

## Bug Description
Viewing any website/page causes an error in the console: 
```
Unchecked runtime.lastError: The message port closed before a response was received.
```

## Website Address
Any website.

## Steps To Reproduce
- open any website
- open the dev tools > console
- an error is written to the console  (see above)
- refresh the page; error is repeated

## Expected Behavior
No errors are thrown or written to the console.

## Actual Behavior
Error is written out to the console.

## Screenshots
n/a

## System Information
- OS: Windows 10 x64 
- Windows Version: 20H2
- Windows Build: 19042.1237
- Windows Feature Experience Pack 120.2212.3530.0
- Browser: Chrome Version 94.0.4606.54 (Official Build) (64-bit)
- Dark Reader Version: 4.9.37

## Additional Context
Toggled all my extensions off until I found the extension throwing the above error. Disabling Dark Reader and the error is no longer thrown. Enabling Dark Reader and the error is shown again.

## Possible Resolution?
- Stackoverflow: https://stackoverflow.com/a/56483156/9664
- Be sure to read the comments of the linked answer as well; accepted answer is crap.

**Comment by Gusted** [comment]
Hi @nCubed!

This error is not really helpful by chromium as it happens on some port at some code. However I've stated quite before on other related issues. As long this error is not causing any misbehaving, I don't see the time fit to add a bunch of guards and checks into preventing this.

CC @bershanskiy Not really sure which code it could be but most likely some code on `src/inject/index.ts` but kinda weird nothing is misbehaving. Not sure if you want to see this fixed, otherwise Il just leave it for a backlog or something.

Regards,
Gusted

**Comment by nCubed** [comment]
@Gusted I just added a link to the bug report to a possible resolution. This is a new error I started to see today; was not present yesterday or this week. Maybe a new version of Chrome was released? Or Dark Reader was updated?

**Comment by Gusted** [comment]
Yeah dark reader was updated a week ago. With a ton of new features are refactors. But like I said if the error had any real good message it might be worth fixing, but the code is not misbehaving and everything just works 🤷🏽

**Comment by Joshua-Hager** [comment]
Currently also having this issue. From a web developer point of view, I thought something was wrong with my code when I opened the DevTools and spent time figuring out it was just the Dark Reader; I would appreciate having this bug fixed so I don't see an error when I am working in the DevTools Console.

I rely on Dark Reader rather heavily, so I am willing to make time this weekend to start looking into this for a possible patch, but only if someone is able to point me in the correct direction so I'm not chasing my own tail.

**Comment by Gusted** [comment]
> I rely on Dark Reader rather heavily, so I am willing to make time this weekend to start looking into this for a possible patch, but only if someone is able to point me in the correct direction so I'm not chasing my own tail.

Yeah that's kind of the problem the error doesn't really indicate where, so it could be any of the ports we're using. You can try using the stackoverflow that @nCubed has linked. But we're in a middle of refactor of messaging and migrating to Manifest V3 for extensions. So it will most likely still be caught the issue.


@nCubed While you don't have to agree with me, I hope it's understandable I'm personally not interested into fixing this problem if it's not causing any weird issue. As this kinds of things are really time consuming to analyze and find the correct piece, thereby the solution could be either easy or hard. I'm still a student with too much homework so my time is limited to these kinds of things.

**Comment by tydira** [comment]
> Currently also having this issue. From a web developer point of view, I thought something was wrong with my code when I opened the DevTools and spent time figuring out it was just the Dark Reader; I would appreciate having this bug fixed so I don't see an error when I am working in the DevTools Console.
> 
> I rely on Dark Reader rather heavily, so I am willing to make time this weekend to start looking into this for a possible patch, but only if someone is able to point me in the correct direction so I'm not chasing my own tail.

I'm also in this boat. You're going to have many more of us showing up here, @Gusted. This isn't a problem on our end, this is something that began happening today because of a plugin that I don't even have enabled for my local app development. This is going to cause a lot of people serious headaches.

**Comment by nCubed** [comment]
@Gusted I hear ya. Time commitment can be difficult. What I disagree with is the blasé attitude that this is a non issue, re: a lot of us have the console open during dev. Seeing an error in our dev environment leads us to believe there is an issue going on with our code. It wasn't until I dug deeper and realized it was an extension, and then toggling them all until I found the actual culprit.

So, while from your perspective there is nothing misbehaving, our perspective is a bit different.

All the same, I appreciate the extension and hope someone can find some time to dig into this issue and resolve any/all errors being thrown into the console.

**Comment by tydira** [comment]
Definitely related https://github.com/gatsbyjs/gatsby/issues/9899#issuecomment-466862123

**Comment by tydira** [comment]
It's a good opportunity for me to say thank you to @Gusted, @alexanderby, and the rest of the contributors, for the hard work you put into making Dark Reader the best night reading extension I've come across. It's well designed, and practically indispensable with so few websites supporting dark mode (as you're well aware).

**Comment by bershanskiy** [comment]
I bisected and fount the faulty commit: #6858.

**Comment by Gusted** [comment]
Well well, looks like I will have to refit some homework for tomorrow, #6897

**Comment by Joshua-Hager** [comment]
Awesome, thank you so much!

**Comment by Gusted** [comment]
FYI: A new chrome release will be made for this. Might take a while due to weekends and someone had uploaded the wrong binary as the new "Version" so the next release might not be the one with the fix.
