### ISSUE TITLE
[Feature Request] Global font setting, not tied to theme-enabled status of a specific wesite

### ISSUE THREAD

**Issue by mattalexx** [darkreader/darkreader#6896]
# Feature Request

## Is this feature request related to a problem?
I want to see the same font at all times. Something akin to unchecking Firefox's "allow pages to use their own fonts" setting, except hopefully [without](https://bugzilla.mozilla.org/show_bug.cgi?id=1363454) [the](https://bugzilla.mozilla.org/show_bug.cgi?id=1638585) [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=789788), which affect Material Fonts, and are not being fixed because of a technicality (Unlike Font Awesome, Google uses standard characters for their symbol fonts, which means that they usually have no replacements in standard font-families. Or something like that. It's a bug that they could fix if their philosophy was a bit less dogmatic.

Anyway, Dark Reader already deals with this the correct way, so I'd like to use it, but I white list several sites if they already provide a nice dark theme. Currently I can't use Dark Reader to change the fonts on those sites, and I don't believe that's a restriction that needs to exist. You may disagree.

## Screenshots

I don't think that a screenshot would explain things any clearer, but I would be happy to show anyone on request.

## Additional Context

Nope that pretty much covers it.

**Comment by Gusted** [comment]
Hi @mattalexx!

Thank you for your feature request, this mostly looks like #5545 which was closed as a wontfix given that our scope is modifying the webpage's CSS and the font was addition to this. Whereby a workaround is to use [stylus](https://github.com/openstyles/stylus/) whereby you can copy the extensive CSS selector https://github.com/darkreader/darkreader/blob/master/src/generators/text-style.ts#L7 and use it that way. But the current font-family will just stay with this behavior. Closing.

Regards,
Gusted
