### ISSUE TITLE
[feature requests] would darkreader for Safari schedule in the future

### ISSUE THREAD

**Issue by dwaynewei** [darkreader/darkreader#690]
hi, I'm a macOS user and I use safari more than Chrome.   with macOS more more popular, would it be possible that there would be a safari version of our extention?

**Comment by risualiser** [comment]
Even if developer make it for macOS, [it will be paid](https://github.com/darkreader/darkreader/issues/562#issuecomment-407017922), so I recommend you to use Chrome or Firefox.

**Comment by ylluminate** [comment]
Please see #562. I think there are a lot of us who'd like this and I'm even pushing Apple via [Bug Report](https://bugreport.apple.com/) to give some love and attention to devs like this.  Extensions like Dark Reader are critical to getting Safari moving in the right direction after they've nerfed us again.

**Comment by alexanderby** [comment]
https://darkreader.org/safari/
