### ISSUE TITLE
[Bug] Automation settings page is blank on Firefox Android 92

### ISSUE THREAD

**Issue by helloworld1** [darkreader/darkreader#6912]
# Bug Report

## Bug Description
The automation page is blank and cannot change automation settings. 

## Steps To Reproduce

Go to darkreader settings and the settings and automation

## Expected Behavior

Display time schedule etc

## Actual Behavior

Blank page
![Screenshot_20210925-125022_Fennec](https://user-images.githubusercontent.com/247316/134784429-034efb9a-0b4d-4afb-b744-1113a1b89ac1.jpg)

## System Information

- OS: Android 11
- Browser: Firefox Android 92.1.1
- Dark Reader Version: 4.9.37.1

**Comment by bershanskiy** [comment]
I was able to reproduce and found the root cause of the bug. Will prepare a fix.
