### ISSUE TITLE
[Bug] Kiwi Browser (94.0.460656) Dark Reader unresponsive after selecting any toggle

### ISSUE THREAD

**Issue by maxelo** [darkreader/darkreader#6913]
# Dark Reader unresponsive after selecting a single toggle

## Using Dark Reader (94.0.460656) today on Kiwi Browser only lets you push one toggle before the extension gets stuck (like all or nothing gets darked).
I would love to know if there any suport planning for kiwi browser? Maybe a way to just import a .json configuration

## Android 11
Kiwi Browser (94.0.460656)
One UI 3.1
 

- OS: Android 11
- Browser: Kiwi Browser (94.0.460656) 
- Dark Reader Version: 4.9.38

**Comment by Gusted** [comment]
Someone was just a little quicker, duplicate #6912
