### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by larry77** [darkreader/darkreader#6914]
# Broken Website Report

## Website Address
www.paypal.com

## Steps To Reproduce
go to paypal.com
Insert yousername and password
Click next when prompted for a text to your mobile phone to verify your identity

finally you get an error message that something went wring

## Expected Behavior

I expected to simply be able to request a text to my mobile phone to access paypal.
## Actual Behavior

finally you get an error message that something went wring
## System Information

- OS:  Debian 11
- Browser: Firefox 92
- Dark Reader Version: 4.9.37.1

**Comment by Gusted** [comment]
Duplicate of #6860
