### ISSUE TITLE
Dark Reader causing "Error: 429 / Too Many Requests (HAP429)" on feedly.com

### ISSUE THREAD

**Issue by wzxu** [darkreader/darkreader#692]
Every now and then feedly will refuse to connect or display this message in the middle of loading new posts: "Error: 429 / Too Many Requests (HAP429)". A quick Google directed me to [this post](https://plus.google.com/+KeithRiggle/posts/KEqBXMUy4q6) where feedly identified Dark Reader as the cause of this issue. I have run into this issue on Opera, Chrome, and Firefox with Dark Reader installed. Any idea?

P.S. Sometimes Dark Reader fails to apply the correct color on feedly until I toggle it off and then on. Perhaps I should file another issue for it later.

**Comment by alexanderby** [comment]
Thank you, the fix will be published soon. That's a shame that I've found an e-mail from Feedly representative describing the issue a month ago.
