### ISSUE TITLE
[Broken Website] tjournal.ru

### ISSUE THREAD

**Issue by jtraub** [darkreader/darkreader#6928]
# Broken Website Report

## Website Address
tjournal.ru (however the same issue can be seen on other sites of cmtt.ru network (dtf.ru and vc.ru) since they use the same engine)

## Steps To Reproduce
Open any tjournal article with at least dozen of comments and navigate to the comment section

Last comment in each thread will have a distinct white bar on the left side

## Expected Behavior
No white blocks next to comments

## Actual Behavior

For example it can be observed here
https://tjournal.ru/internet/445539-aviasales-zapustil-koroche-karty-s-obzorami-gorodov-i-kontaktami-mestnyh-gidov-i-fotografov

![image](https://user-images.githubusercontent.com/153191/134894513-f8ec795b-c2aa-4982-86c0-708fcc2cfcc8.png)

What is going on there:

Site developers always draw a vertical line on the left side of each comment
![image](https://user-images.githubusercontent.com/153191/134894746-382614fc-e765-4a14-81f2-ecb97faf7130.png)

but for the last comment in a thread they hide it with box-shadow

```
.comment__children > .comment:not(.comment--level-last):last-child {
  box-shadow: calc(var(--offset-branch)*-1 - 1px) 0 0 0 #fff;
}
```

For some reason DarkReader doesn't change the color - hence we see the white box.

If I try to add following fix in the dynamic theme editor for tjournal.ru

```
.comment__children > .comment:not(.comment--level-last):last-child {
  box-shadow: calc(var(--offset-branch)*-1 - 1px) 0 0 0 ${#fff} !important;
}

```

I end up with black boxes

![image](https://user-images.githubusercontent.com/153191/134895224-be0d1b14-fd65-440a-8fa1-1b9471684744.png)

For some reason DarkReader converts `background-color: #fff;`  to `background-color: #222322;` on `div.l-island-bg` but `#fff` on `box-shadow` for `.comment` in the snippet above gets converted to `#000`

At the moment I mitigated the issue on my local machine with forcing `#222322` on box-shadow but obviously this is not a solution to the problem.

## System Information
- OS: Linux
- Browser: Chromium 94
- Dark Reader Version: 4.9.38

**Comment by Gusted** [comment]
Hi @jtraub!

Thanks for the issue, seems like it was a little misunderstanding within the DR code.

Regards,
Gusted

**Comment by jtraub** [comment]
@Gusted thanks a lot for prompt response and fix.

I hope it will be released soon
