### ISSUE TITLE
[Broken Website] archive.org

### ISSUE THREAD

**Issue by RagglenLove** [darkreader/darkreader#6929]
# Broken Website Report

## Website Address
https://archive.org/

## Steps To Reproduce
- Go to archive.org.
- Try typing or copying and pasting text on the Wayback Machine searchbox, nothing appears.
- Try typing or copying and pasting text on the archive.org’s searchbox, the text is so faint, making it hard to read.

## Expected Behavior
- Typing or copying and pasting text on archive.org’s searchboxes should produce readable text.

## Actual Behavior
- The text on both searchboxes are not readable.

## Screenshots
![Screenshot_2021-09-27_19-34-19](https://user-images.githubusercontent.com/45503845/134908132-acae9f0f-4195-4e4f-bb32-6beefd9b2d25.jpg)

## System Information
- OS: Xubuntu 20.04.
- Browser: Firefox 92.0 (64-bit)
- Dark Reader Version: 4.9.37.1

## Additional Context

**Comment by LargePrime** [comment]
is this not still broken?
