### ISSUE TITLE
strange behavior in plesk admin panel

### ISSUE THREAD

**Issue by mpgr04** [darkreader/darkreader#6933]
Hi!

I've been using Dark Reader in Microsoft Edge browser ( 94.0.992.31) for quite some time now.

However, what I noticed is that with the extension turned on, I get the following error messages in the Plesk Admin Panel when navigating around (See attachment). As soon as I deactivate Dark Reader on this page, these error messages disappear, the behavior is also reproducible, so I strongly suspect that this has something to do with the extension itself.
![Screenshot_3](https://user-images.githubusercontent.com/34566496/134942401-92fece25-bd67-44da-a7fd-d995a6fb4da7.png)
![Screenshot_4](https://user-images.githubusercontent.com/34566496/134942404-22d856b0-26ea-4f29-ae8a-f97ef0d4d13a.png)

**Comment by Gusted** [comment]
Hi @mpgr04!

Please follow the issue template.

Regards,
Gusted
