### ISSUE TITLE
Please make it easier to fix/exclude elements and re-write instructions

### ISSUE THREAD

**Issue by CollinChaffin** [darkreader/darkreader#694]
This phrase is literally unreadable and makes absolutely no sense as it is so full of double-negatives itself which is also sounds like is how this extension has to handle reversing itself:

````
IMPORTANT: When Dark mode is on, the whole page (root <html> element) is inverted by filter. To revert the images, videos etc. INVERT selectors are used, so the inversion will be applied to these elements twice. If inverted elements contain other elements that match the INVERT selectors, then these elements will be inverted 3 or more times. To prevent it NO INVERT selectors are used.
````
I assume by the way the instructions are written that they perhaps were translated to English?  Either way, is it possible to provide actual step-by-step instructions on ANY test site etc. with a single element both a "standard" invert exclusion/reversal using a selected DOM element, and also I guess an example of what sounds like a "double reversal so really INVERT rather than NO INVERT it" example?

I have a very simple `div#fanart` table that frankly no matter what I do, like just about every other site attempt am totally unable to simply prevent darkreader from removing the table background, prevent any inversion via NO INVERT, etc.  Also, what it sounds like is needed most is a "NO REMOVE BG" to negate element background removal on any element, rather than having to do anything else with reversing color inversion as is often the case I find where inversion of dark is great, but this automatic killing of almost all background images kills critical parts of the page.

TIA!

**Comment by CJShearer** [comment]
I need this for learnopengl.com. There are functions listed (such as glCreateShader [here](https://learnopengl.com/Getting-started/Hello-Triangle)) which display a #hover element that becomes unreadable with the dynamic engine. 

A NO INVERT tag for the dynamic engine would be a convenient solution for this.

**Comment by alexanderby** [comment]
@CJShearer I would suggest you to open Chrome Dev Tools and Dark Reader Dev Tools. Inspect the background element, what selector adds the wrong background, then add `.selector { background-image: none !important; }`.

**Comment by CJShearer** [comment]
@alexanderby I didn't realize I could add CSS to the dev-tools sheet. The following seemed to do the trick: 
```
learnopengl.com

CSS
#hover {
    background-image: none;
}

================================
```
Thanks for the advice : )
