### ISSUE TITLE
[Bug] Auto switch theme based on system theme is broken

### ISSUE THREAD

**Issue by KyroOW** [darkreader/darkreader#6948]
# Bug Report

## Bug Description

I'm using a program that automatically switches my Windows theme to dark in the evening, Dark Reader is set to switch between dark mode and light mode depending on the system theme. The next day when turning on my computer, the system theme is light again but sometimes Dark Reader stays on the dark theme for some reason, this has never ever happened before, it only began to happen since a few days.

## Expected Behavior

Be on light mode as my Windows theme is in light mode.

## Actual Behavior

It stays on dark mode even though my Windows theme is set to light mode.

## Screenshots

https://i.imgur.com/aTUR2og.png

## System Information

- OS: Windows 10 x64 21H1 build 19043.1237
- Browser: Microsoft Edge 94.0.992.31
- Dark Reader Version: 4.9.38

**Comment by Gusted** [comment]
Hi @KyroOW!

That's pretty weird as we should just be getting notified that the system got dark/light. Did the theme switches while Edge was open? Or did you open it afterwards?

Regards,
Gusted

**Comment by KyroOW** [comment]
I don't really know, i believe everything happens before i'm even logged into Windows, but i think Edge is opened anyways as when i log in, Edge is already there, i guess that's because of the setting i enabled in Windows 10 which automatically restarts programs after signing in, i don't have the exact translation for this setting though.

**Comment by Gusted** [comment]
Hmm, it is possible that edge is still loaded, but all javascript and extensions and sites are put to "idle", and resumed when the computer starts, in such scenario I don't think that we will ever receive a message that the system's theme has changed.

**Comment by KyroOW** [comment]
Perhaps that's a recent change within Chromium ? It has always been working perfectly fine before.

**Comment by Gusted** [comment]
That would be weird, as such changes should be noted into the release notes and I haven't see any of them recently.

**Comment by bershanskiy** [comment]
@KyroOW If you could say which application you use, I would be able to install it and test on my computer and develop a fix.

**Comment by KyroOW** [comment]
@bershanskiy I'm using this one https://github.com/AutoDarkMode/Windows-Auto-Night-Mode

**Comment by Gusted** [comment]
> I have a feeling that the issue reported by OP is more broad than just related to system theme. But if you feel this is a separate issue, let me know and I can open a new issue.

Feels more like a Firefox issue honestly. I have my fair bit of linux experience with a lot of different DE, so it's always a kinda catchy to have working theme switching with the browsers. Chromium is really worse in that opinion, Firefox has more support on that integration. So given that it only works when the browser is re-opened is a possible sign that Firefox is not able to detect the changes in themes etc, so please open up a new issue for that.

**Comment by janxkoci** [comment]
@Gusted Sorry, but I don't change system themes. I have set a timer in DR settings to change website theme based on the time of the day. OS theme has nothing to do with it.

**Comment by janxkoci** [comment]
I just got past the trigger time in my timezone and DR simply didn't notice. It shows the timer is set to 19:00, it's 19:15 here, but the toggle is still on the off position. I can click it to toggle it on (which disables the timer) and the website changes the theme.

So maybe my issue can be rather related to one of those issues with settings not working properly (e.g. #6926 and such).

**Comment by wistlo** [comment]
This is happening on latest Firefox beta:  auto ignores system theme set to dark. I use f.lux to automatically switch system themes.  This probably is a Firefox issue, but I'll take my chances there might be a workaround DR could push.   

Firefox Version : 95.0b2 (64-bit)

Chrome Version 96.0.4664.35 (Official Build) beta (64-bit) still tracks Windows Theme.  

Windows Version:
PS C:\temp> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0

**Comment by moltar** [comment]
Same here. I don't know if it ever worked, as I am a new user. But the ext does not switch back and forth if I switch the system setting (built-in macOS, no third-party apps). For example, GitHub reacts fine, automatically (without the ext).

- macOS Big Sur 11.6.1
- Firefox: 94.0.1 (64-bit)

**Comment by tech189** [comment]
I have the same issue, it worked before but I can't remember when exactly.

I'm using Dark Reader in Firefox on Windows 11 with https://github.com/AutoDarkMode/Windows-Auto-Night-Mode but also in Firefox on Android where the system has a built-in setting to switch to dark mode at night.

Usually I can get the extension to respond again by toggling the extension's On/Off toggle but it doesn't always work. If that doesn't work the only way to fix it is to restart the browser!

**Comment by bandgeekdante** [comment]
I'm getting the same issue on Windows 10 using Dark Reader 4.9.42 and Chrome 95.0.4638.69

**Comment by KyroOW** [comment]
I recently had a few instances of Dark Reader not switching modes when the OS switched color schemes normally, without even going to sleep or anything.

It's getting worse.

**Comment by chrisdothtml** [comment]
This feature has never worked for me (I assumed it just wasn't supported)

```
macOS Monterey Version 12.0.1 (21A559)
Google Chrome Version 96.0.4664.55
```

**Comment by MillikCN** [comment]
Same case like author, I have to click that "follow system theme" button every time and then it would start to change (from light theme to dark theme and vice versa)

**Comment by RyanLeigh39** [comment]
same here on windows 11 22000.348 and edge 96.0.1054.53

**Comment by thenickname** [comment]
if that helps: same bug on macOs Monterey + Firefox 95.0.1. Once dark reader is in dark mode, it stays in dark mode forever (unless I manually change it manually or disable and re-enable "use system colors")

**Comment by AlbertoFabbri93** [comment]
On my pc Dark Reader on Edge (windows 11) does not switch back to light mode when I toggle the system theme manually with Auto Dark Mode (the program linked by the original author of the issue).

**Comment by twio142** [comment]
On my Bis Sur mac the auto-switch fails occasionally. After reading this thread I realise that it might be due to the `App Tamer` I'm using which is set to slow down Chrome when it's not in front. Will suspend App Tamer for a while and see if the auto-switch works properly.

**Comment by MintMain21** [comment]
I've had this same issue with Firefox Android, where Dark Mode won't turn off in the morning to respect my system theme change.

**Comment by bowencool** [comment]
I've this same issue with `Chrome 99 / Mac OS 12.3`

**Comment by momt99** [comment]
Same issue here. Usually, when Edge is open and the windows theme changes, the edge theme changes correctly but DarkReader doesn't get notified/change. I have to go to its settings and turn off and on "Use system color scheme".

Windows: 10 21H2
Edge: Version 100.0.1185.12 (Official build) beta (64-bit)

**Comment by samcarter** [comment]
I still experience this problem on 

- macOS Big Sur 11.6.1
- Firefox: 98.0.1 

For the time being, I switched to Midnight Lizard. The colour choices aren't as good there as in Darkreader, but it detects the system mode changes while the computer is asleep.

**Comment by vobrechkov** [comment]
Same issue with Edge on Windows 11 - Dark Reader does not detect system theme change until manually unselecting and re-selecting the setting to follow system theme.

**Comment by Gusted** [comment]
Going to comment here once, the OP issue is from chromium-based browsers. Firefox-based browsers aren't the same issue as this as Firefox is since a few releases being _stupid_ with how their _awesome_ new themes work and didn't properly pass on the system's theme and instead reported the theme's theme(which would be incorrect anyway) that issue should be fixed with Firefox 100(or 101).

As for chromium 🤷🏽‍♂️, it's still looking all good on my side someone will need to have some brilliant insight for that one in order to understand what's going wrong.

**Comment by tech189** [comment]
@Gusted could you please link to the bugzilla page for that Firefox bug you mentioned? I can't find it myself

**Comment by Gusted** [comment]
@tech189 For more context see: https://www.reddit.com/r/firefox/comments/thcj9g/theming_changes_on_nightly_for_firefox_100/ Which should give a better explanation of the situation.

**Comment by Gusted** [comment]
> it is not working with Firefox Nightly 100.0a1 either :(

Check the reddit post, you might need to tweak one of your settings. With they focus on **"Colorways and most AMO themes (unless they explicitly specify their color-scheme as per above)"**. At this point, it's more of the Firefox fault(due to their reasoning to not return the OS's color scheme anymore without any notice) Dark Reader is simply using the information that's given.

**Comment by samcarter** [comment]
I followed all the suggestions from the reddit post. Also for sites with a native dark mode and other addons, detecting the system theme works fine again ever since updating to FF98.

**Comment by SpineEyE** [comment]
If someone still has this bug (on Firefox Nightly): I had to go to `about:config` and reset the `layout.css.prefers-color-scheme.content-override` value.

Changing the setting in `about:preferences` somehow didn't work, the browser didn't actually catch the system theme. Now everything works as it should.

**Comment by djmango** [comment]
FF99 did not detect the system theme correctly with one of the new Firefox custom themes - Vegging Out. Changing my install to Firefox Beta to get on [100.0beta](https://www.mozilla.org/en-US/firefox/100.0beta/releasenotes/) fixed it for me. I didn't find any of the aforementioned variables in about:config to be off default, but your mileage may vary.

**Comment by Abderrian** [comment]
I am using macos 12.3.1 and chrome 101.0.4951.54. If there is a window of chrome opening, the auto switch based on system theme works fine. 
However if there is no window of chrome opening and chrome is still running in background, the system theme changes. When you open a new window of chrome, dark reader won't change its theme based on system theme. It will stay on its original theme when the window of chrome close.
If chrome is completely closed, not running in background, dark reader will change its theme based on system theme when you open a new window of chrome.

**Comment by bershanskiy** [comment]
This bug and #7041 might have the same underlying cause.

**Comment by Stooovie** [comment]
It's not working in Sept 2023 either. Not by following System theme nor Location.

**Comment by alexanderby** [comment]
Should be fixed already by https://github.com/darkreader/darkreader/commit/94760a5cfd9a1af71494ef888833941aa780c10a
