### ISSUE TITLE
[Bug] Vivaldi v4.2+ only: the "Translate Selection" popup looks totally wrong and unusable when DR is active

### ISSUE THREAD

**Issue by Agych** [darkreader/darkreader#6949]
# Bug Report

## Bug Description
[VIVALDI only]
In the last versions of Vivaldi, where the "translate selected" was introduced,
when using this feature and Dark Reader is active on the site, the translation pop-up looks just totally wrong and barely visible.

## Steps To Reproduce

- Go to any website.
- Ensure that Dark Reader is active on it.
- Select some text and use the "Translate Selection" feature of Vivaldi.
- See the results.
- To see how it normally looks, deactivate Dark Reader and use the translate feature again.

## Expected Behavior

Normal look of the translation popup.

## Actual Behavior

Looks horribly wrong and barely usable.

## System Information

- OS: Windows 7
- Browser: Vivaldi v4.2
- Dark Reader Version: v4.9.38

**Comment by AdriGeeK03** [comment]
Sorry I don't know what you are talking about. My browser just display the popup fine for me, even if I'm using darkreader 
With dr extension : https://prnt.sc/1u3vlar
W/out it : https://prnt.sc/1u3voos

**Comment by Agych** [comment]
Here is how it looks:
[1](https://upload.disroot.org/r/_R6JACmy#t+Y6HRM8f3m/BWiEK/N7ehU/GFrYzKB8U4g+Is29MxY=)
[2](https://upload.disroot.org/r/04Mzp6Lp#p7Rvq7/JP3k+kWA/yairG1SMU6VIA/MeBpKwDBtJu84=)

And it's like that on every site where DR is in use.

All looks fine when DR is not in use.

**Comment by Gusted** [comment]
> Here is how it looks: [1](https://upload.disroot.org/r/_R6JACmy#t+Y6HRM8f3m/BWiEK/N7ehU/GFrYzKB8U4g+Is29MxY=) [2](https://upload.disroot.org/r/04Mzp6Lp#p7Rvq7/JP3k+kWA/yairG1SMU6VIA/MeBpKwDBtJu84=)
> 
> And it's like that on every site where DR is in use.
> 
> All looks fine when DR is not in use.

Do you have any other extensions on by any chance?

**Comment by AdriGeeK03** [comment]
> Here is how it looks: [1](https://upload.disroot.org/r/_R6JACmy#t+Y6HRM8f3m/BWiEK/N7ehU/GFrYzKB8U4g+Is29MxY=) [2](https://upload.disroot.org/r/04Mzp6Lp#p7Rvq7/JP3k+kWA/yairG1SMU6VIA/MeBpKwDBtJu84=)
> 
> And it's like that on every site where DR is in use.
> 
> All looks fine when DR is not in use.

Oh yeah it looks like shit, just try to disable all of ur extensions without dr and if it works properly again, try turn on all of the extensions one by one and test it to see which one is doing this.

**Comment by Agych** [comment]
> Do you have any other extensions on by any chance?
ofc I do xD 
Internet is unusable and unsurfable without extensions

> just try to disable all of ur extensions without dr and if it works properly again
created a clean test profile with DR only - the result is the same. :-/

**Comment by demolitioner** [comment]
Have no problems with vivaldi 4.2, win10. Popups looks the same as intended.

**Comment by Agych** [comment]
DR v4.9.39 and Vivaldi v4.3, looks like all is good now! :-)
