### ISSUE TITLE
White background flashing when opening a web page

### ISSUE THREAD

**Issue by LArctic** [darkreader/darkreader#695]
White background flashing when opening a web page
Although very short, it is too bright. Can it be turned into night mode?

**Comment by risualiser** [comment]
What's browser, what's extension mode (Filter(+)/Static/Dynamic)?

**Comment by LArctic** [comment]
Quantum Firefox 62.0 beta19

**Comment by risualiser** [comment]
Try these steps:
1) Open extension menu -> "More" -> "Default" (browser theme)
2) Right-click on extensions panel (or open browser menu) -> "Customize" -> "Themes" -> "Dark"

**Comment by risualiser** [comment]
I use Firefox too (62.0b20), but I also use [this script](https://github.com/overdodactyl/ShadowFox) for keeping all the browser dark, not only web pages.
I turned it off and got the same issue, but only on opening new tabs. Other flashes happened because of "slow" extension work in Dynamic theme (which didn't happened in Static, for example).
For new tabs - you can try the script I mentioned, but for regular pages, it's better to use Static (if white flashes aren't just blank pages).

**Comment by LArctic** [comment]
The new page is dazzling white, is there any way to modify it?

**Comment by risualiser** [comment]
Sorry, I have no idea, better wait for the developer.

**Comment by wzxu** [comment]
Add the following to your userChrome.css (customize the color to fit your darkness level):

```
#main-window,
#content,
browser[type="content-primary"],
browser[type="content"],
browser[type="content"] > html {
  background: #16171d !important;
}
```

For more information regarding userChrome.css see [this link](http://kb.mozillazine.org/index.php?title=UserChrome.css).

**Comment by laurentS** [comment]
I suspect this white flash problem is related to the background color in firefox. You can go to "about:config" and modify the `browser.display.background_color` key from the default `#FFFFFF` (white) to something else, and see if it helps. I think the solution by @wzxu above does more or less the same thing. I think it'd be cool for darkreader to adjust this value when toggled on/off.

**Comment by alexanderby** [comment]
@laurentS Modifying this flag didn't work for me.

**Comment by Gusted** [comment]
Hi!

Dark reader v4.9.17 has been released that has the fix that fixes this issue 🎉.
To make sure you are on the latest version to make sure this is the case.
First, we should make sure your on the new user interface of Dark reader, by doing:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

This should have activated the new user interface and should look like this: ![](https://i.imgur.com/cJJwSrY.png). Make sure to pay attention to the bottom text that says the current version. If it states an older version e.g. 4.9.16 I suggest to remove the extension and re-install it trough https://darkreader.org/ so it will be forced to download the latest version.
If this fix still indicates this issue let me know and hopefully improvements can be made!

Regards,
Gusted
