### ISSUE TITLE
[Bug] Getting endless "Loading, please wait" in LibreWolf

### ISSUE THREAD

**Issue by CuriousApe2020** [darkreader/darkreader#6955]
I run "LibreWolf Version 92.0.1 (64-bit)" and "Dark Reader Version 4.9.37.1"
And I still only see "Loading please wait" when clicking the Extension icon similar to: issue: https://github.com/darkreader/darkreader/issues/6819
Version 4.9.34 Works fine all newer are broken.

**Comment by bershanskiy** [comment]
That bug was fixed by #6927. I don't remember exactly which commit went into 4.9.37.1, but I think you are running a known-faulty version. Could you please update to current `master`? I can give you detailed instructions how to do that and build it for you.

**Comment by CuriousApe2020** [comment]
You are right, I reinstalled LibreWolf and everything works now sorry for the "false" report.

**Comment by NyaomiDEV** [comment]
I am getting the same error with Librewolf 94.0.2 and Dark Reader 4.9.43.

**Comment by Gusted** [comment]
> I am getting the same error with Librewolf 94.0.2 and Dark Reader 4.9.43.

Yeah, that's to be expected... Librewolf has decided to change their user-agent to a unique one. I haven't come around to add the new user-agent yet as it's really weird to see that it has their own user-agent.

**Comment by Gusted** [comment]
#7632
