### ISSUE TITLE
Google Chart indicators Gets a weird text style with the dark reader applied;

### ISSUE THREAD

**Issue by Tainan404** [darkreader/darkreader#696]
Dark reader on:
![with-dark-reader](https://user-images.githubusercontent.com/15806883/44605558-3c2de400-a7c0-11e8-8910-2fe5afcb4aa9.png)

Dark reader off:
![without-drak-reader](https://user-images.githubusercontent.com/15806883/44605578-55369500-a7c0-11e8-8cb3-998df6a2772d.png)

**Comment by krupenja** [comment]
This is a duplicate of #552
