### ISSUE TITLE
[Feature Request] Support setting export/import

### ISSUE THREAD

**Issue by haolly** [darkreader/darkreader#6961]
# Feature Request
Export/Import setting
## Additional Context

I use two different browser, and need to sync the setting; It's very convenient if I can export from one and import to another

**Comment by bershanskiy** [comment]
Dark Reader already supports settings export and import. Please see this comment for details: https://github.com/darkreader/darkreader/issues/6725#issuecomment-916340005

Closing this now, but will reopen if that does not work for you.

**Comment by haolly** [comment]
@bershanskiy  There was no such a setting as described in  #6725 
Seem my image below 
![image](https://user-images.githubusercontent.com/2383231/135485675-ca17d9be-25a9-4291-95b5-5516333c9b2a.png)

**Comment by haolly** [comment]
Find the new UI in the dev tools button
