### ISSUE TITLE
[Bug] unable to edit site list on Firefox android

### ISSUE THREAD

**Issue by mobileNetscapeUser** [darkreader/darkreader#6963]
# Bug Report

## Bug Description

Hi. Thank you for your great work. I use dark reader on Firefox for Android.

To only have it used on a few specific sites, I have the extension enabled but disabled for all sites unless in the site list. My site list is small <10.

I wanted to add another site. when I click to edit the site list, only a back arrow at the top and the dark reader heading is displayed. The page is blank--I do not see any sites.

I have tried enabling/disabling the add on. I have uninstalled/reinstalled dark reader with no change in behavior.

It does seem to be working on sites that I had previously added. But I can not modify the site list.

## Steps To Reproduce

- press menu
- press add-ons arrow
- select dark reader
- select settings
- select site list
- a blank screen is displayed

## Expected Behavior

The site list page should be displayed to add and remove sites.

## Actual Behavior

The site list page is blank--I do not see any sites listed or a way to modify the site list.

## System Information

- OS: android 11
- Browser: Firefox 92.1.1
- Dark Reader Version: 4.9.37.1

**Comment by helloworld1** [comment]
I have the same issue reported in https://github.com/darkreader/darkreader/issues/6912
It was supposed to be fixed now. I don't see a new release to test

**Comment by mobileNetscapeUser** [comment]
I have a new version and the issue appears to be fixed in 4.9.39. Thank you.
