### ISSUE TITLE
[Broken Website] avito.ru/profile

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#6968]
# Broken Website Report

## Website Address
https://www.avito.ru/profile

## Steps To Reproduce
- Log in https://www.avito.ru
- Go to https://www.avito.ru/profile

## Expected Behavior
The image in front of the ad title is displayed.

## Actual Behavior
The image in front of the ad title is not displayed.

## Screenshots
<details>
<summary>Screenshots</summary>

![Личный кабинет - Мои объявления - Авито - Google Chrome - Dark](https://user-images.githubusercontent.com/19418601/135607741-a8f2cc48-bc04-4060-81ce-dff75eec5ff0.png)

![Личный кабинет - Мои объявления - Авито - Google Chrome - Light](https://user-images.githubusercontent.com/19418601/135607754-15177827-e637-489f-aafd-88acd31de325.png)

</details>

## System Information
- OS: Windows 10
- Browser: Chrome 94
- Dark Reader Version: 4.9.38

## Additional Context
The image is added through a `div` that has a `background-image` property set. I tried rule `IGNORE IMAGE ANALYSIS div[class^="item-preview-image"]` and `IGNORE IMAGE ANALYSIS div[class^="item-preview"]` but they didn't help.

**Comment by Gusted** [comment]
Hi @rakleed!

This seems to be a `z-index` problem, due to our static styles. All negative z-index's aren't shown, if you can open up a PR with something like:
```CSS
CSS

div[class^="item-preview"] {
    z-index: 0 !important;
}
```
Whereby the selector is more correct(?), would be appreciated.

Regards,
Gusted
