### ISSUE TITLE
Dynamic is too blue (or font is too yellow)

### ISSUE THREAD

**Issue by gaydenko** [darkreader/darkreader#697]
Hi!

On dynamic mode (Firefox, Linux) (regardless a site) a background is tending to be shifted to blue (say, rgb 21, 22, 30 just now on github). Is it possible to change this base background to be gray?

**Comment by risualiser** [comment]
What about "Sepia"?
![default](https://user-images.githubusercontent.com/35914376/44665805-7f39c280-aa1f-11e8-937a-0c124f265474.png)
![default](https://user-images.githubusercontent.com/35914376/44665839-924c9280-aa1f-11e8-9e47-145890c954f3.png)

**Comment by gaydenko** [comment]
So is there a way to keep bg dark grey and set fg to be color-less (that is light grey)?

**Comment by risualiser** [comment]
What's the fg?

![default](https://user-images.githubusercontent.com/35914376/45266412-88854f00-b463-11e8-8bc5-823acbb694d4.png)

**Comment by gaydenko** [comment]
This way you just kill all fonts colouring at all! 
I don't understand underlying logic :) 
To my taste this is the logic for default conversion:
- white bg must be converted to  dark grey
- (almost) black font must be converted to (almost) white
- red font must be converted to light red
- green font must be converted to light green
- and so on...

**Comment by gaydenko** [comment]
So, what do you think about presented above approach? In fact it is just consistency between foreground and background which is not respected now.

**Comment by alexanderby** [comment]
Seems like the effect varies on different screens. I'll try to adjust it a little bit. There is an idea of making some color themes.

**Comment by gaydenko** [comment]
> Seems like the effect varies on different screens

Not sure I understand. Not-zero saturation can be detected/verified by colour picker regardless screen adjustment.

**Comment by alexanderby** [comment]
I mean that pure gray looks worse. If you pick a color from well designed dark mode (e.g. Mojave) it will be e.g. 21,21,23, a little bit blue, which makes it more comfortable. So I will tune down the saturation a little bit and also will make sepia and grayscale to have less effect on colored elements.

**Comment by gaydenko** [comment]
I see your point. And I can easy accept my taste is shifted and it is the reason to prefer real grey.
OTOH I still guess it would be more obvious and handy 
- to use Sepia ranging from, say, -50% to +50% with real not-saturated zero,
- and - at any case! - to keep correlation between bg and fg,  that is dark grey (or black) bg must correspond to light grey (or white) fg.

**Comment by SilverWolf32** [comment]
Just for information, the macOS Mojave dark color scheme actually does seem to use pure gray. (Not that a bit of blue isn't bad, just that gray isn't bad either.)

**Comment by alexanderby** [comment]
I've published some improvements recently. Also it is planned to add separate color pickers for background and text, so you will not have to play with Brightness, Contrast and other Filter mode inheritance.

**Comment by gaydenko** [comment]
Sorry, I don't understand why the issue is closed. The thing is, even with 4.6.11 (Firefox) we have blue-shifted bg with not-colored fg, or, on sepia adjusting, yellow-shifted fg with grey bg. Nothing changed.

**Comment by alexanderby** [comment]
I've made colors less saturate to conform with popular dark themed apps, so it suits for most of the users. I understand that it can still look too saturate on your screen. For that purpose I'm going to add color pickers instead of brightness and contrast trackbars.

**Comment by gaydenko** [comment]
It's very unusual (and looks like a not-funny joke) to close the issue before merging a fix to master :(
Ok, let's be on waiting for the pickers.
