### ISSUE TITLE
[Broken Website] science.org

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6971]
# Broken Website Report

Titles of webpages become dark in dark mode.

## Website Address

https://www.science.org/content/article/after-years-failed-experiments-i-made-mid-ph-d-pivot-here-s-what-i-learned

## Expected Behavior

White title on a dark background.

## Actual Behavior

Title is colored black along with a dark background, making it difficult to read.

## Screenshots

![pic-selected-211001-2040-10](https://user-images.githubusercontent.com/59497618/135644266-fa765b00-0c2d-46e1-8e7e-de5555ba10a5.png)

- OS:  Linux 
- Browser:  Firefox 92
- Dark Reader Version:  4.9.37

**Comment by OmarNamis** [comment]
Can't reproduce, the title is white for me.

**Comment by Gusted** [comment]
Hi @paniash!

This issue is already fixed, please see [the Readme](https://github.com/darkreader/darkreader#site-fixes).

Regards,
Gusted

**Comment by paniash** [comment]
@Gusted Thank you!
