### ISSUE TITLE
[Bug] Problem with toolbar icons in Google Drive PDFs on Microsoft Edge

### ISSUE THREAD

**Issue by vinayakv22** [darkreader/darkreader#6976]
# Bug Report

## Steps To Reproduce

-Opening any Google drive PDF link.

## Expected Behavior

The Icons are supposed to be the same as experienced when Dark Reader is Turned Off. Basically the icons are not the colour inverted versions of normal icons that usually happens when Dark Reader is Turned On. 

## Actual Behavior

Some random icons appear and that too cropped.

## Screenshots

![image](https://user-images.githubusercontent.com/75321135/135680888-a80b19c7-bede-4477-b533-0ca25f031010.png)
Icons when Dark Reader is Turned off(above)
![image](https://user-images.githubusercontent.com/75321135/135680855-819c4fc8-9e96-4c05-9a8c-bebe62fc71f5.png)
Icons when Dark Reader is Turned on(above)

## System Information

- OS: Windows 11
- Browser: Edge 94
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Hi @vinayakv22!

This issue is fixed within the next release.

Regards,
Gusted
