### ISSUE TITLE
[Broken Website] palshovon.wixsite.com

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#6987]
# Broken Website Report

## Website Address

https://palshovon.wixsite.com/uthd

## Expected Behavior

Dark background, with light colored text, nicely adhering to a dark website.

## Actual Behavior

Light background, with text inverted to a light color, making it difficult to read.

## Screenshots

![pic-window-211002-2233-01](https://user-images.githubusercontent.com/59497618/135725881-f124b81f-d4bf-47cb-bfee-a022b47a7b80.png)

## System Information

- OS:  Linux
- Browser:  Firefox 92
- Dark Reader Version:  4.9.37.1

**Comment by paniash** [comment]
@Gusted Thank you! Is it possible to make the footer of the webpage dark as well? (As seen in the screenshot below)

![pic-selected-211002-2249-57](https://user-images.githubusercontent.com/59497618/135726358-9cb5597c-d3df-47c4-a3e8-4b3f392bedb7.png)

**Comment by Gusted** [comment]
#6998

**Comment by paniash** [comment]
Thank you very much!

**Comment by paniash** [comment]
@Gusted Sorry for the trouble once again but the "Team" section of the website appears to be light themed. (See below screenshot). Link: https://palshovon.wixsite.com/uthd/the-team

![pic-selected-211003-1942-59](https://user-images.githubusercontent.com/59497618/135757627-be3dcb80-3a0e-4b25-a799-4681d6c4c05b.png)

Also, certain links (research highlights) appear dark when in dark mode, rendering them difficult to read. (See below screenshot)

![Imagepipe_1](https://user-images.githubusercontent.com/59497618/135758041-f5c3d716-cc5e-43cd-b5e2-70d3ea09fce5.jpg)
