### ISSUE TITLE
[Feature Request] Automatic Dark Mode Based on Time

### ISSUE THREAD

**Issue by jxnding** [darkreader/darkreader#6991]
# Feature Request
Allow us to automatically turn on Dark Reader based on time. Ex: dark mode is off (no CSS changes) 7am to 7pm, dark mode is on 7pm to 7am.

## Is this feature request related to a problem?
No

**Comment by OmarNamis** [comment]
Already exists.

Open Dev tools, then click on "Preview new design".

Then you will find an option called "Automation" inside the settings.

**Comment by melvio** [comment]
I've made an extensive write-up with screenshots of how to do this over here: https://stackoverflow.com/questions/68806383/how-to-automatically-toggle-the-dark-reader-chrome-plugin/69513557#69513557
