### ISSUE TITLE
[Feature Request] New UI

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#6993]
# Feature Request

Remove the white border in the extension interface

## Screenshots

![image](https://user-images.githubusercontent.com/87893636/135720885-b96c9ea3-610d-45ff-8350-2583dcd30c63.png)

How about changing the color to this ?

![135720885-b96c9ea3-610d-45ff-8350-2583dcd30c63](https://user-images.githubusercontent.com/87893636/135735491-660ddf36-7958-456d-aac2-42721495edf8.png)

## Additional Context
I really like the new user interface, it's clean, modern and very convenient. My sincere thanks to everyone who helped make this extension more and more better 😁

**Comment by alexanderby** [comment]
Oh, yes, it's too bright.

**Comment by NguyenASang** [comment]
#6999 I changed in this pull request

**Comment by quick007** [comment]
Ngl I would love to have those fancy rounded borders back as well

**Comment by NguyenASang** [comment]
@alexanderby #7002 I changed on this request

**Comment by NguyenASang** [comment]
Closed because my idea was rejected :(
