### ISSUE TITLE
[Feature Request] skip websites that already use dark themes

### ISSUE THREAD

**Issue by rahul-ve** [darkreader/darkreader#6994]
# Feature Request

Skip webpages that already use dark themes, as more and more sites are designed with dark/eye-safe themes, it will be unnecessary to apply any further transformations. 

The below webpage has a very  nice dark theme and darkreader applies further modifications which are unnecessary and in some places even makes it hard to read due to incompatible background and foreground color choices.

e.g. https://docs.microsoft.com/en-us/documentation/

This might even improve performance.

**Comment by NguyenASang** [comment]
You can add the website already has dark theme like this pull request:
https://github.com/darkreader/darkreader/pull/6992

If you add it, next time you visit the page, the extension won't enable anymore.

**Comment by rahul-ve** [comment]
I was thinking of a scalable approach to this issue, we can add the specific website to the exception list but it is not a scalable approach as more and more websites move to dark themes, e.g., Linkedin, Google are slowly rolling out dark themes. 

I haven't looked at the code but it might be possible to have some analytical approach to this problem, one way to handle this might be like first time a webpage/site loads we follow existing setup but if we have a way to analyze their theming, we can decide to modify or not for subsequent loads. I am just thinking aloud.

**Comment by NguyenASang** [comment]
Do you mean the extension will check if web page has a dark theme? if: 

- Yes, turn on that website's dark mode automatically
- No, let's make a dark theme for that website

It would be nice to be able to detect that, we don't need to add it manually!!!

**Comment by Gusted** [comment]
> I haven't looked at the code but it might be possible to have some analytical approach to this problem, one way to handle this might be like first time a webpage/site loads we follow existing setup but if we have a way to analyze their theming, we can decide to modify or not for subsequent loads. I am just thinking aloud.

#5719 Is a little prototype I made, the main logic is just sitting there to detect 90-95% of all dark pages in the current config. Yet it has many problems like performance and integrating existing logic(as we should be able to dynamically disable DR for a site in the middle of doing a lot of shit). Every time I had revisit that PR another not so very fun problem has come up, and with the existing PR's and problems DR has I don't have a lot of time nor can justify a lot of time for that PR and spend some weekends  on that.

**Comment by rahul-ve** [comment]
@NguyenASang yep exactly

@Gusted 
No rush,  I completely understand the time pressures. 
I would love to collaborate but I will not have time right away,  if #5719 is still open towards the end of the year, I will get some time to work on it.

**Comment by NguyenASang** [comment]
But I have a question, if the website has a dark theme but the default theme of that website is a light theme. Is it possible to automatically find and enable it?

**Comment by Gusted** [comment]
> Is it possible to automatically find and enable it?

No, mainly for 2 reasons:
1) Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
2) This is only able to implement on a site-basis.

**Comment by NguyenASang** [comment]
Ye, I think the same as you, who wants the normal to replace the custom one ;))

**Comment by Gusted** [comment]
> One of the heuristics I'd recommend checking for (if possible),

It's something we could indeed check for.

> is if any of the site's CSS uses the [`prefers-color-scheme: dark`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature;

That's certainly a good heuristic, yet for some reason I do have seen it being abused by some (major) websites which do have such media query but just not use it or behind some kind of toggle and all other weird shenanigans. It's not really a strong heuristic to check against, maybe in a list of heuristic it could be but not as a stand-alone one.

> You could also try to figure out if the site has a predominantly dark background colour overall, but I don't know enough about what add-ons have access to to say if that would be possible.

That's currently a experiment by #5719

**Comment by Ambient-Impact** [comment]
> That's certainly a good heuristic, yet for some reason I do have seen it being abused by some (major) websites which do have such media query but just not use it or behind some kind of toggle and all other weird shenanigans. It's not really a strong heuristic to check against, maybe in a list of heuristic it could be but not as a stand-alone one.

Agreed, you'd want other checks as well. I think it also depends on the site - my own stuff uses it extensively, so maybe also take into account how many times it appears in the CSS and weigh that heuristic more heavily if it's used a lot? Maybe that's getting too complex.

**Comment by artisticfox8** [comment]
> 
> 
> Do you mean the extension will check if web page has a dark theme? if:
> 
>     * Yes, turn on that website's dark mode automatically
> 
>     * No, let's make a dark theme for that website
> 
> 
> It would be nice to be able to detect that, we don't need to add it manually!!!

The ex

> 
> 
> You can add the website already has dark theme like this pull request: #6992
> 
> If you add it, next time you visit the page, the extension won't enable anymore. But make sure almost page in that website has dark theme.

Reddit and Google search have a dark theme. Dark Reader could flip the toggles for these sites, so their dark mode is used when Dark Reader is active

**Comment by NguyenASang** [comment]
Like @Gusted said:
> No, mainly for 2 reasons:

> 1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> 2. This is only able to implement on a site-basis.

Moreover, turning on their dark mode is difficult. Because in each website, their way of enabling dark mode is different.

**Comment by artisticfox8** [comment]
> 
> 
> Like @Gusted said:
> 
> > No, mainly for 2 reasons:
> 
> > 1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> > 2. This is only able to implement on a site-basis.
> 
> Moreover, turning on their dark mode is difficult. Because in each website, their way of enabling dark mode is different.

It should be done for performance reasons on already big slow sites like reddit for instance
Doing this for top 10 biggest internet sites is feasible, I could assist with that (I know enough JS to figure THAT out)

**Comment by artisticfox8** [comment]
> 
> 
> Like @Gusted said:
> 
> > No, mainly for 2 reasons:
> 
> > 1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> > 2. This is only able to implement on a site-basis.
> 
> Moreover, turning on their dark mode is difficult. Because in each website, their way of enabling dark mode is different.

Plus I'd say the native darkmodes are less buggy than Dark Reader (which has bugs because it can't possibly figure out everything - perfect algorithms don't exist

**Comment by artisticfox8** [comment]
> 
> 
> > Is it possible to automatically find and enable it?
> 
> No, mainly for 2 reasons:
> 
>     1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> 
>     2. This is only able to implement on a site-basis.

The websites native one is usually faster (as is the case with gmail for example). 
2. It is well worth it for the top 10 websites of internet (google, reddit,  etc.)

**Comment by Gusted** [comment]
> (which has bugs because it can't possibly figure out everything - perfect algorithms don't exist

Correct, which is why I do like when such bugs are reported such that it can be fixed instead of trying to work around it by creating new features as that simply avoids the bug.



> > > Is it possible to automatically find and enable it?
> > 
> > 
> > No, mainly for 2 reasons:
> > ```
> > 1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> > 
> > 2. This is only able to implement on a site-basis.
> > ```
> 
> The websites native one is usually faster (as is the case with gmail for example). 2. It is well worth it for the top 10 websites of internet (google, reddit, etc.) (Sorry I don't know how to reply to two users at once)

The whole point of having a extension is by having a consistent color-scheme over all sites, if we now simply give up and just turn on the site's dark mode that whole point is just gone. Users should uninstall dark reader and go search for the dark mode of their favorite websites.

**Comment by artisticfox8** [comment]
> 
> 
> > (which has bugs because it can't possibly figure out everything - perfect algorithms don't exist
> 
> Correct, which is why I do like when such bugs are reported such that it can be fixed instead of trying to work around it by creating new features as that simply avoids the bug.
> 
> > > > Is it possible to automatically find and enable it?
> > > 
> > > 
> > > No, mainly for 2 reasons:
> > > ```
> > > 1. Why? We our self have a great dark mode, with customization etc ;) would be weird to just enable the native's one.
> > > 
> > > 2. This is only able to implement on a site-basis.
> > > ```
> > 
> > 
> > The websites native one is usually faster (as is the case with gmail for example). 2. It is well worth it for the top 10 websites of internet (google, reddit, etc.) (Sorry I don't know how to reply to two users at once)
> 
> The whole point of having a extension is by having a consistent color-scheme over all sites, if we now simply give up and just turn on the site's dark mode that whole point is just gone. Users should uninstall dark reader and go search for the dark mode of their favorite websites.

The point here is different - to make Dark Reader the Dark mode toggle for web, as a polyfill of sorts (not the best word) for Dark mode, until all websites have their own

**Comment by artisticfox8** [comment]
The goal is that all websites have a standard color-scheme dark CSS, until then Dark Reader is needed

**Comment by Gusted** [comment]
> The point here is different - to make Dark Reader the Dark mode toggle for web, as a polyfill of sorts (not the best word) for Dark mode, until all websites have their own

I don't think we share the same vision of dark reader - while it's of course nice that each website would have a dark mode on it's own(which will never happen). Dark Reader shouldn't be a toggle to toggle the site's dark mode. That would include site-specific(which I highly regard as it's done in Javascript)

**Comment by Gusted** [comment]
> I think i speak for many that the preferred option for this extension is to _provide_ a dark mode where missing, not to _force_ a specific dark theme - in the end it is all about not being blinded at night, right? (additionally, trying to force a specific standard dark mode would never work anyways due to different modes being a thing and websites overriding things anyways)

I've never been a fan of making dark reader a toggle of dark mode, it's just to add a dark mode already where needed(and sometimes over an already existing dark mode). Yet here's being talked about that we _detect_ sites that have their own dark sites.

**Comment by ClassicDarkChocolate** [comment]
Maybe just follow spec. Detect if the site supports sec-ch-prefers-color-scheme.

Chrome has already implemented it. And sites might finally support it someday.

**Comment by thebigsmileXD** [comment]
> add a dark mode already where needed
> _detect_ sites that have their own dark sites.

Essentially is the same thing

**Comment by kusalux** [comment]
> Maybe just follow spec. Detect if the site supports sec-ch-prefers-color-scheme.
The problem with that might be that it's hardly used by now. Also - idk - are forced colors taken care of? [Infos](https://github.com/WICG/user-preference-media-features-headers)
For completion some ideas i've listed [here](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/320). Also check against [that guide](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) if it's really complete?

**Comment by Gamrix** [comment]
FYI, there is a new (as of 10/2022) beta feature for detecting websites
https://github.com/darkreader/darkreader/discussions/9016
