### ISSUE TITLE
[Broken Website] phpBB 3.2.11 login/logout

### ISSUE THREAD

**Issue by mkem114** [darkreader/darkreader#7038]
# Broken Website Report

## Website Address
[mr2.org.nz/phpbb3](https://mr2.org.nz/phpbb3/ucp.php?mode=login)

## Steps To Reproduce
Go to a phpBB forum and try to login or logout. The form submit will fail due to mismatching session IDs (I believe) and the user will be presented this error when logging out or "form was invalid" when logging in

## Expected Behavior
The same session ID is retained.

## Actual Behavior
Dark reader is making requests in the background and that is creating new session IDs (again I'm guessing) so the server sees an old ID when the user tries to login/logout and doesn't recognise it.

## Screenshots
![logging-in](https://user-images.githubusercontent.com/20897849/136463615-3f783788-850d-463a-a333-be821a2687fb.png)
![logging-out](https://user-images.githubusercontent.com/20897849/136463595-76971edd-ecb3-4101-93d6-4d30428bbc98.png)

## System Information
- OS: Windows 10 20H2
- Browser: Chrome 94.0.4606.61 Stable
- Dark Reader Version: 4.9.39

**Comment by Gusted** [comment]
Merging into #7015
