### ISSUE TITLE
Dynamic filtering: pixel "lightness" measurement is wrong

### ISSUE THREAD

**Issue by Indigo744** [darkreader/darkreader#704]
Hello,

The way you [measure the pixel "lightness"](https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/image.ts#L108) is wrong: you are taking only the two max components of RGB to compute a "lightness" value, entirely leaving out another component which may make the image brighter.

The proper way is to compute the pixel luminance, taking into accounts the human eyes color perception:
`L = (0.299*R + 0.587*G + 0.114*B)` (fast)
`L = sqrt( 0.299*R^2 + 0.587*G^2 + 0.114*B^2 )` (slower)
See this helpful StackOverflow thread: https://stackoverflow.com/a/596243/8861729

Formula is for RGB values in range [0-1]. You have to divide by 255 before applying the formula.

**Comment by alexanderby** [comment]
Thank you, I missed it. Similar formula is used for converting colors into grayscale.
