### ISSUE TITLE
[Broken Website] Doesn't apply to chrome or Edge web stores

### ISSUE THREAD

**Issue by josh-65** [darkreader/darkreader#7043]
# Broken Website Report

## Website Address

https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home
https://chrome.google.com/webstore/category/extensions

## Expected Behavior
Dark mode should be applied

## Actual Behavior
They stay white

## Screenshots

![image](https://user-images.githubusercontent.com/26977075/136602920-0605c100-8148-4ec1-a7cb-752451bc1b56.png)

## System Information

- OS: Windows 10 19043.1237
- Browser: Edge v94.0.992.38 
- Dark Reader Version: 4.9.39

**Comment by quick007** [comment]
Chrome disables addons on certain websites so addons can't make it so users can't uninstall them (by blocking access to certain pages)

**Comment by Gusted** [comment]
> Is the no way of getting it to work then?

Nope.
