### ISSUE TITLE
[Bug] IP addresses blacklist matching too ambitious

### ISSUE THREAD

**Issue by JJGadgets** [darkreader/darkreader#7044]
# Bug Report

## Bug Description
My router is 10.0.0.1, while another service is 10.0.0.11
I can change the theme of my router UI, so I disabled Dark Reader on 10.0.0.1, while it is default enabled for anything not blacklisted.
However, 10.0.0.11 also gets blacklisted, while the site list only shows 10.0.0.1 on the blacklist, and if I remove 10.0.0.1 from the blacklist while 10.0.0.11, I can see that 10.0.0.11 now gets themed by Dark Reader, but so does 10.0.0.1 which I don't want themed.

## Website Address
10.0.0.1
10.0.0.11

## Steps To Reproduce
Have a website on xx.xx.xx.1 and xx.xx.xx.11, xx.xx.xx being the same IP range, and blacklist the .1, and the .11 will also get blacklisted.

## Expected Behavior
10.0.0.1 gets blacklisted, but 10.0.0.11 doesn't.

## Actual Behavior
Blacklisting 10.0.0.1 from being themed by Dark Reader also disables Dark Reader theming.

### Without Blacklist:
![image](https://user-images.githubusercontent.com/5709019/136634068-508e7731-4dec-4c6b-9db8-544a4aa52c69.png)
### With 10.0.0.1 Blacklist:
![image](https://user-images.githubusercontent.com/5709019/136634045-b4a002fe-e332-44d4-a742-ca4929ae7cfc.png)

## System Information
- OS: Windows & Linux
- Browser: Microsoft Edge 94.0.992.38
- Dark Reader Version: 4.9.34

## Additional Context
None

**Comment by Gusted** [comment]
#373
