### ISSUE TITLE
[Broken Website] zeit.de

### ISSUE THREAD

**Issue by uhkeller** [darkreader/darkreader#7096]
# Broken Website Report

## Website Address
https://www.zeit.de/

## Steps To Reproduce

Load any article on zeit.de with darkreader set to dynamic theme generation, e.g. [this one](https://www.zeit.de/politik/deutschland/2021-09/koalitionsbildung-news-ampel-jamaika-spd-gruene-fdp-union-sondierungen).

## Expected Behavior

Text should be readable :)

## Actual Behavior

Text is not readable. Almost everything except hyperlinks appears as very dark grey on black.

## Screenshots

![zeit_darkreader](https://user-images.githubusercontent.com/2323704/137458053-e3494cf8-67c1-4efe-b723-54e3cd786146.png)

## System Information

- OS: macOS 11.6
- Browser: Firefox 93.0
- Dark Reader Version: 4.9.39

(same issue with Firefox on Android)

## Additional Context
<!-- Provide any additional information about this website issue. --
>

**Comment by Gusted** [comment]
#7026 fixed this.
