### ISSUE TITLE
Firefox 61: port.sender.tab is undefined

### ISSUE THREAD

**Issue by reaysawa** [darkreader/darkreader#710]
### System information

Ubuntu 18.04
Firefox 61.0.1 x64

### How to reproduce
1. Hover the extension's icon

The following error is shown in the Browser Console:

![image](https://user-images.githubusercontent.com/17429390/44952192-a1807580-ae4f-11e8-9d95-475cb4d1fd1c.png)

**Comment by alexanderby** [comment]
Currently I'm using Firefox 62 and cannot reproduce it. Maybe there should be some more steps to reproduce.

**Comment by jpsouzasilva** [comment]
It doesn't have any special conditions or steps for triggering it as far as I know. I've tried starting the browser both with the extension enabled or disabled and, regardless, the error still shows up in the console upon hovering the icon in the address bar. Maybe it's a Linux-only bug.

Offending piece of code seems to be this:

```
class TabManager {
        constructor({ getConnectionMessage }) {
            this.ports = new Map();
            chrome.runtime.onConnect.addListener((port) => {
                if (port.name === 'tab') {
                    const tabId = port.sender.tab.id; <------------------------- port.sender.tab is undefined
```

I should also say that it doesn't obstruct functionality in any way as far as my usage is concerned.
