### ISSUE TITLE
[Feature Request] Choose set of icons.

### ISSUE THREAD

**Issue by boromyr** [darkreader/darkreader#7106]
# Feature Request
Hi, I wanted to propose to add to DarkReader the possibility to change the icon set in the extension bar, either with new built-in sets or by uploading your own custom icons.
It could be integrated into "Settings" -> "Change icons"(new voice) -> *choice list* or "Load new Icons"(a day icon, a night icon).
## Is this feature request related to a problem?

No, it's a cosmetic enhancement.
## Screenshots

Examples:
Day
![image](https://user-images.githubusercontent.com/52782032/137585482-cfd5c4dc-399c-42e4-8467-cd3d693af75c.png)
Night
![image](https://user-images.githubusercontent.com/52782032/137585516-65e7aeab-eec5-4bfc-b227-3e821cba83a3.png)

## Additional Context
This functionality can be used by all users.
I currently use this set of icons, as shown by the screenshots above. I am attaching them solely as an example.
[icons.zip](https://github.com/darkreader/darkreader/files/7357462/icons.zip)

**Comment by bershanskiy** [comment]
@boromyr I'm not aware of any other extension which would allow user to change extension icons like that. Also, your proposal would require Dark Reader to store icons to extension storage and then set extension icons to an arbitrary image from storage. The latter part might be considered dangerous and flagged by reviewing scripts.

If you need help, I can help you set up a personal fork of Dark Reader with CI which regularly (e.g., on every release) pulls all the changes  form upstream and applies your icons to it. However, I don't think we will be able to upstream this specific feature.

**Comment by Gusted** [comment]
I do think just the fact that this has never been done by any extension and I also personally don't see the personal benefit of having this should be a reason to not upstream this feature as well as the technical problems that @bershanskiy mentions.

**Comment by boromyr** [comment]
I didn't know it could be difficult to implement. However, there are extensions that allow you to change the badge icon and colors, like Stylus:  
![image](https://user-images.githubusercontent.com/52782032/137623557-f88d2bda-004b-4901-9e26-a18b4f988b5a.png)

> If you need help, I can help you set up a personal fork of Dark Reader with CI which regularly (e.g., on every release) pulls all the changes form upstream and applies your icons to it. However, I don't think we will be able to upstream this specific feature.

Interesting, I think that might be the solution for me. So I should fork DR and load the custom icon set, nothing complicated so far, then how should I proceed? @bershanskiy 
Thanks in advance!!!

**Comment by mattalexx** [comment]
> If you need help, I can help you set up a personal fork of Dark Reader with CI which regularly (e.g., on every release) pulls all the changes form upstream and applies your icons to it. 

Nice of you. 👍

**Comment by bershanskiy** [comment]
I do not think that we will ever implement this change upstream, but I would be glad to help anyone set up custom forks. It's pretty simple, since you can just literally change two .png files directly and omit the settings UI component entirely.

Closing this as non-actionable.
