### ISSUE TITLE
Default set of static webpages

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#714]
A couple of pages are themed more fast and accurate by a userscript. 
I suggest to ship this add-on by default with a few of them, like Github, Facebook and Youtube. 

This means higher speed on often used webpages and less work to adjustments due to changes there for the darkreader team. 

Is there any downside?

P.S: While greatly working, is the static implementation hard to reach and the blog post about it even missed the whole point, that the user has to be on the particular page, while following the steps. 

The button which opens the window to input your own CSS is too tiny and the whole thing is hidden and slightly confusing. By implementing a sane set of userscripts, can we avoid fixing that :package: 

For now, of course. :wink:

**Comment by Gusted** [comment]
If people want specific userscript they can copy paste it no need to have us having a default.

**Comment by ShalokShalom** [comment]
seems redundant now, since the speed of dynamic is much faster
