### ISSUE TITLE
[Bug] Firefox may report inaccurate time zone breaking Automation

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#7143]
# Bug Report

## Bug Description

Automation does not work.

## Steps To Reproduce

- Install Dark Reader from CWS or from current `master`
- Open popup, try to enable Automation (e.g., set start time ten minutes earlier) and notice that nothing happens.

## Expected Behavior

Automation works.

## Actual Behavior

Nothing happens.

## Screenshots

![image](https://user-images.githubusercontent.com/45960703/138163360-c7092f6b-5ea5-4a39-8b67-f5697f42f848.png)

## System Information

- OS: Windows 10 
- Browser: Firefox 93.0 
- Dark Reader Version: 4.9.39

**Comment by Gusted** [comment]
Automation is broken as whole or just a specific mode of automation?

**Comment by Gusted** [comment]
> On Firefox (and not Chrome)

That's weird. Any chance you have `privacy.resistFingerprinting` enabled?
