### ISSUE TITLE
[Feature Request] Add conditional compilation variable __TEST__

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#7156]
# Feature Request

## Is this feature request related to a problem?

If you open `build/release/firefox/ui/popup/index.js`, you will find `createConnectorMock()` in it. Clearly, this function is not needed in release builds.

## Additional Context

Perhaps, we could hide it behind build-time constants like `__DEBUG__`. We could call this variable `__TEST__`, for example.

**Comment by Gusted** [comment]
Does this issue still need to be open?

**Comment by bershanskiy** [comment]
> Does this issue still need to be open?

No, I just forgot about it. 😄
