### ISSUE TITLE
Bugzilla 'Possible Duplicates' buttons (Add me to CC list)

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#716]
Dynamic: 
![screenshot_20180906_112821](https://user-images.githubusercontent.com/6344099/45148729-3aa0ea80-b1c8-11e8-9bcb-2eceaaea2fb4.png)

Static does it fine: 
![screenshot_20180906_112909](https://user-images.githubusercontent.com/6344099/45148735-3ffe3500-b1c8-11e8-995c-e32f28ed9604.png)

The buttons to "Add me to the CC list" are unreadable in dynamic mode

**Comment by alexanderby** [comment]
Oh, this requires registration.

**Comment by ShalokShalom** [comment]
Is there anything I can do for you? 
You can use a 10 minute mail: https://10minutemail.net/

**Comment by Gusted** [comment]
Button has been removed.
