### ISSUE TITLE
Outlook Web App, OWA: message creating is broken

### ISSUE THREAD

**Issue by gaydenko** [darkreader/darkreader#721]
Hi! On attempt to create new message I get a window with just background regardless filter type in use.
Sorry, I have not publicly available href for you.

Well, the issue takes place with Firefox extension. All is OK with (Chrome based) Vivaldi.

**Comment by gaydenko** [comment]
> I have not publicly available href for your

That is OWA is using for internal corporate purposes.

**Comment by alexanderby** [comment]
Maybe using Filter mode specially for Outlook could help you.

**Comment by gaydenko** [comment]
Have tried them all.

**Comment by gaydenko** [comment]
I still can not use darkreader (currently 4.9.26) with OWA site under Firefox. Was there some fix I have missed?

**Comment by Gusted** [comment]
I actually forgot the comment

"report it to outlook self it's most likely to have a problem internally thst causes this thst isn't fixable by Dark reader"
