### ISSUE TITLE
[Broken Website] Google Maps dark theme not working on Opera

### ISSUE THREAD

**Issue by sonicruiser** [darkreader/darkreader#7213]
# Broken Website Report

## Website Address

maps.google.com

## Steps To Reproduce

Navigate to  maps.google.com on Opera using Chrome extension
Google Maps Dark Theme does not work

## Expected Behavior

Google Maps dark theme works normally in Chrome, it should look the same in Opera

## Actual Behavior

Dark theme does not work on Google Maps and nothing happens

## Screenshots

![image](https://user-images.githubusercontent.com/93456886/139563038-c4148a3e-78a2-4d48-997c-34f3c3c07518.png)

![image](https://user-images.githubusercontent.com/93456886/139563045-be22f052-2b5c-4563-aefc-83cdc0fb4b21.png)

## System Information

- OS: macOS Monterey version 12.01 (Google Maps dark theme on Opera did not work with macOS Big Sur either) 
- Browser: Opera 80.0.4170.72 (x86_64)
- Dark Reader Version: Chrome extension 4.9.39

**Comment by bershanskiy** [comment]
Can confirm the bug occurs on Opera and Opera GX with Dark Reader 4.9.39.

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/139575100-152258ed-ea3e-4f96-9a37-75c968acca39.png)
`Allow access to search page results` has to be enabled.

**Comment by sonicruiser** [comment]
You're right, that fixed it, thanks!
