### ISSUE TITLE
[Feature Request] website whitelist export to file

### ISSUE THREAD

**Issue by zhenjie1999** [darkreader/darkreader#7216]
# website whitelist export to file

## Is this feature request related to a problem?
no need to add website to whitelist one by one next time reinstall extension or new pc

**Comment by bershanskiy** [comment]
Dark Reader already supports settings export:
- enable new UI: open popup and click on "Dev tools", on popup which will appear click "Preview new design"
- export settings: open popup again and click "Settings" > "Manage settings" > "Export settings"

You can import settings as well (via "Settings" > "Manage settings" > "Import settings").

Closing this now, but feel free to comment if you still need help.
