### ISSUE TITLE
[Feature Request] Add `minimum_chrome_version` to Chrome manifest

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#7217]
# Feature Request

## Is this feature request related to a problem?

We should add `minimum_chrome_version` to Chrome manifest to explicitly specify the smallest supported version.

## Screenshots

N/A

## Additional Context

Firefox manifest already specifies the equivalent `strict_min_version`:
https://github.com/darkreader/darkreader/blob/a4c6111898b0dbe5ed2f508c400a165cebd37a8a/src/manifest-firefox.json#L5

**Comment by Gusted** [comment]
Our `minium_chrome_version` should be pretty low, pretty sure it's able to support a chromium version from some years ago. So in that sense I'm not sure what the benefit is from adding it, while on the other hand I'm not against it.

We do have a script somewhere in the dark reader codebase `compatibility.js` which already checks for the chromium version.

**Comment by bershanskiy** [comment]
On a second thought, I agree that there is no benefit to using `minimum_chrome_version`. In particular:
 - changing manifest in MV2 builds submitted to CWS might delay review
 - changing manifest in MV3 builds will do nothing because MV3 itself was introduced after Chrome 63 release:
 
 
 https://github.com/darkreader/darkreader/blob/85169ed3e890cea5973e7ddef8eb8f85a6768cfd/src/ui/popup/compatibility.js#L7
