### ISSUE TITLE
[Broken Website] http://www.rri.res.in/people.html

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#7218]
# Broken Website Report

## Website Address

http://www.rri.res.in/people.html

## Expected Behavior

Coherence with dark mode.

## Actual Behavior

Doesn't comply with dark mode and makes it rather difficult to read.

## Screenshots

![pic-window-211031-1919-01](https://user-images.githubusercontent.com/59497618/139586832-4a6fa266-c99d-4852-adfe-15d39a4fe90d.png)

## System Information

- OS:  Linux
- Browser:  Firefox 93
- Dark Reader Version:  4.9.39

**Comment by Gusted** [comment]
I am not so sure if this is fix-able. The website itself is outdated and uses enormous amounts of deprecated features of the web, Dark Reader doesn't like such features. It seems like Firefox Itself is inconsistent with these elements(`<frame>` & `<frameset>`).

**Comment by paniash** [comment]
I see. Thanks :-)
