### ISSUE TITLE
[Feature Request] Don't render white border and some glitch when open menu

### ISSUE THREAD

**Issue by tmpm697** [darkreader/darkreader#7224]
After you installed this extension on firefox for i.g, click on the extension's UI at right top connect of firefox, there's a white border around the UI menu.

I used gtk-3 `Material-dark` theme.

I have another example of good extension's UI menu. Take a look at `LocalCDN` (https://www.localcdn.org/), it has good UI.

I also observer glitch when click/flash on the menu (seem like darkreader load a lot and delay to display on screen). No issue with extension like `LocalCDN` so far.

archlinux/sway/intel hd/WebRender/firefox protocol: wayland

**Comment by Gusted** [comment]
Dup #6993
