### ISSUE TITLE
[Feature Request] Disable Dark Reader on PDF Viewer

### ISSUE THREAD

**Issue by RaptaG** [darkreader/darkreader#7228]
# Feature Request

## Is this feature request related to a problem?
Yes, this feature is related to a problem-bug. When a website opens the pdf-viewer directly from the website, the text background is black and the characters white.

## Screenshots
https://imgur.com/a/HsAaexD
(The full text isn't shown for privacy reasons, since it has my country's language)

## Additional Context
It doesn't happen when opening a downloaded PDF from the browser

**Comment by Gusted** [comment]
Hi @RaptaG!

The ability to disable PDF is already their in the UI.

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then go to any PDF([example](https://africau.edu/images/default/sample.pdf)] and disable the PDF within the UI.

Regards,
Gusted
