### ISSUE TITLE
Feature Discussion: Export Dark CSS - Site Level Scope

### ISSUE THREAD

**Issue by klexas** [darkreader/darkreader#723]
Just posting here as suggested to discuss the potential of a new feature. 

The feature would involve having an option to 
Download a CSS file locally which will be related to the current site. 

I know from my own enjoyment of Dark Reader that sites which I have worked on, I am now offering a dark native theme to users. This has been aided hugely with the help of Dark Reader. However, an 

> export generated CSS

 Option would have been incredibly valuable. 

I am more than happy to develop the feature, but as suggested, thought it would be better to discuss plausibility and demand.

**Comment by alexanderby** [comment]
Exporting dark CSS can only work partially: inline styles will not be exported.

**Comment by joshwand** [comment]
see also #604

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted
