### ISSUE TITLE
Scrollbar arrows missing in Edge

### ISSUE THREAD

**Issue by TommyG007** [darkreader/darkreader#7230]
Bug Description
Scrollbar up and down arrows missing in Edge when DR is activated, affects all websites.

Steps To Reproduce
Enable DR in Edge

Expected Behavior
Scrollbar up and down arrows

Actual Behavior
No scrollbar up and down arrows

System Information
OS: Windows 10
Browser: Edge 95
Dark Reader Version: 4.9.39
Additional Context

**Comment by Gusted** [comment]
Hi @TommyG007!

This is expected behavior because you Dark Reader overrides the scrollbar, see: https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151 for how to disable it.

Regards,
Gusted

**Comment by ahmed-salem-me** [comment]
You have a great job with the extension but saying that hiding the arrows of a vertical scrollbar is by design is a strange thing to say. considering how important and integral they are to normal user behavior.
I'm been using Dark reader for a long time with no issues, only happened when I had to reinstall my OS, so I'm assuming that this incorrect behavior is relatively new.

Having an uncolored scrollbar with the arrows is way better than not having them.

**Comment by Gusted** [comment]
> You have done a great job with the extension but saying that hiding the arrows of a vertical scrollbar is by design is a strange thing to say

It _kind of_ is, but now changing the default behavior to include arrows is also strange as users are now used to this variant of the scrollbar. 

> I'm been using Dark reader for a long time with no issues, only happened when I had to reinstall my OS, so I'm assuming that this incorrect behavior is relatively new.

They've never existed in Dark reader, the scrollbar theme hasn't changed.



> Having an uncolored scrollbar with the arrows is way better than not having them.

Well the option exist to disable the coloring of the scrollbar.

**Comment by ahmed-salem-me** [comment]
@Gusted thanks for your reply.
You can't really say users are used to current behavior and happy with is unless you make a survey :)

Scrolling while reading is an extremely repetitive action so people switch to scrollbar arrows to reduce stress on their finger.
plus mouse scrolling in not exactly precise or most people have it scroll a number of lines at a time for speed scrolling but rely on the presence of the arrows to do the more precise scrolling when needed.

I'm 100% sure I had Dark reader working with arrows before I reinstalled my OS, not sure what changed.

Can you plz point me to where to find the option to disable the coloring and would this retain the arrows.
I couldn't find any settings, or do I have to fork the code?

Many thanks

**Comment by Gusted** [comment]
> You can't really say users are used to current behavior and happy with is unless you make a survey :)

I've never said that they are happy, as that would indeed require a big survey. I've simply said that people are used(as in behavior) to this scrollbar, changing it will open up to a lot more issues of why this was changed.



> Can you plz point me to where to find the option to disable the coloring and would this retain the arrows?
> I couldn't find any settings, or do I have to fork the code?


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    (under Theme click See all options, Colors).

**Comment by ahmed-salem-me** [comment]
@Gusted Many thanks. That's good enough for those of us who really need the arrows, though not pretty looking.
