### ISSUE TITLE
Opera support?

### ISSUE THREAD

**Issue by naumchenko** [darkreader/darkreader#724]
Hey fellas, when trying to load unpacked ext. from src. on Opera, it complains about default_locale in manifest, default_locale attribute is present in the manifest, seems like its something else in manifest Opera doesn't want to digest.

Any direction would help,

Thx,

**Comment by alexanderby** [comment]
You can already use Dark Reader via Install Chrome Extensions add-on.

I've tried to publish the add-on to Opera, but had an error and the Opera team didn't help with anything. The forum is full of messages like this and they just ignore the problem.

**Comment by naumchenko** [comment]
Thank you Alex, Chrome ext add-on worked. Would be good to have native Opera ext.
