### ISSUE TITLE
[Bug] Firefox white flashing with dynamic theme since 4.9.40.

### ISSUE THREAD

**Issue by racofer** [darkreader/darkreader#7255]
# Bug Report

## Bug Description

Since the latest update, pages will flash white upon loading. Both foreground and background pages will flash white for a brief moment before the dynamic theme gets applied. This was not an issue before 4.9.40. Static filter continues to work fine.

## Website Address

Any website with dynamic mode enabled.

## Steps To Reproduce
Open website in foreground:
 - Page loads
 - White flash occurs
 - Dynamic theme is applied

or
Open website in background:
 - Wait for page to fully load in background
 - Upon switch to the loaded tab, white flash occurs
 - Dynamic theme is applied

## Expected Behavior

Not sure how it worked before the update, but background pages already had the dynamic theme applied when switching to tab.

Pages loaded in the foreground would honor the `nglayout.initialpaint.delay` configured in Firefox, and the dynamic theme would be applied before the page was shown, thus no white flashing.

## System Information

- OS: Windows 10 21H1
- Browser: Firefox 94
- Dark Reader Version: 4.9.40

**Comment by Zethson** [comment]
Also appearing for me.

**Comment by Gusted** [comment]
Oh no, oh no... white flashes.

This will be interesting. I mostly know if I merge or approve PR that has a _possibility_ to break certain aspects. But I'm certain that I didn't touch any of the white-flash prevention mechanism (@bershanskiy any possible idea?). Time to get git bissect.

I will like to give my thought on a possibility that this might be related to the recent released Firefox v94, as @bershanskiy mentions that  it doesn't occur on chromium 🤷🏽 just a possibility to consider.

**Comment by racofer** [comment]
> I will like to give my thought on a possibility that this might be related to the recent released Firefox v94, as @bershanskiy mentions that it doesn't occur on chromium 🤷🏽 just a possibility to consider.

But version 4.9.39 works fine with Firefox 94, so that is not likely the case.

**Comment by Gusted** [comment]
> Time to get git bissect.

According to `git bissect` this bug has to be present in v4.9.39 and I do see the same consistent type of white flash across v4.9.40 and v4.9.39, not sure I'm seeing the correct type of white flash of what's mentioned here - I'm mostly just running into the longer existing white flashes issues.

**Comment by bershanskiy** [comment]
> any possible idea?

I'm a simple man: whenever I see a regression I do a git bisect. :)

In this case, the regression happens at `ec8ff880.` (`43dda3f6` is good, `ec8ff880` is bad).

Testing method, using Firefox:
 - Open this page and right-click on this link https://example.com and open it in a new tab
 - Wait for tab to load (2 sec) and switch to the new tab
 - Repeat the last step 10 times until the first white flash

If no flash ever occurred, then commit passes. If flash occurred even once, then commit fails.

**Comment by Gusted** [comment]
> In this case, the regression happens at `ec8ff880.` (`43dda3f6` is good, `ec8ff880` is bad).

That makes sense, I will prepare a fix for that one.

>  If flash occurred even once, then commit fails. Flashes occur in >50% of tries on faulty commits, 10 tries is just a purposeful overkill.

In that sense every commit failed for me, confirming that I was seeing some type of other white-flashes :D

**Comment by Gusted** [comment]
#7256 should fix it.

**Comment by Zethson** [comment]
Thank you for resolving this issue so quickly.  Thursday, 04 November 2021, 09:43PM +01:00 from Gusted  ***@***.*** :

**Comment by bershanskiy** [comment]
I can't explain why, but if I do `git revert ec8ff880` this bug goes away.

**Comment by bershanskiy** [comment]
@racofer and @Zethson could you please try the following builds and report if bug is fixed:
 - [Build 1](https://github.com/bershanskiy/darkreader/actions/runs/1423307460)
 - [Build 2](https://github.com/bershanskiy/darkreader/actions/runs/1423289771)

To test a build, just download corresponding `.zip`, extract Firefox build and load it into Firefox. Then just use it as normal or perform steps from a comment above.

**Comment by racofer** [comment]
Hi @bershanskiy and @Gusted , thanks for acting so quickly on this one. I have tested both builds:

- Build 1: same as before, unfortunately. The white flashes occur the same way as with the 4.9.40 release;
- Build 2: this one appears to have fixed the issue. Now I get the same behavior as with 4.9.39;

I will continue testing with Build 2 for the rest of the day and watch for anything odd, but while I could instantly spot the problem with 4.9.40, now with Build 2 I'm yet to notice any white flashes. Thanks!

**Comment by bershanskiy** [comment]
> Build 1: same as before, unfortunately. The white flashes occur the same way as with the 4.9.40 release;
> Build 2: this one appears to have fixed the issue. Now I get the same behavior as with 4.9.39;

This matches my expectations, nice to see that I'm still sane.

@racofer Would you have time to test build 3? I think it should be the final fix.

**Comment by bandgeekdante** [comment]
This is happening for me too, on Chrome 95.0.4638.69 and Dark Reader 4.9.42, though in my case using the "Use system color scheme" option
