### ISSUE TITLE
[Broken Website] https://pan.baidu.com/ all button become javascript:;

### ISSUE THREAD

**Issue by zhenjie1999** [darkreader/darkreader#7263]
# Broken Website Report

## all button become URL become javascript:;

https://pan.baidu.com/disk/home?#/all?path=%2F&vmode=list

## Screenshots

if normal windows
https://pan.baidu.com/disk/home?#/all?path=%2F&vmode=list
![image](https://user-images.githubusercontent.com/75268245/140511451-382efa5d-bc0c-4bc4-b70b-cda982ad82c6.png)
![image](https://user-images.githubusercontent.com/75268245/140511490-3bf89d8e-8a0c-44c8-b384-47acf1721164.png)
normal windows will back to normal if turn off at this site
![image](https://user-images.githubusercontent.com/75268245/140511531-87efba67-75f7-431c-b97a-c13b92147d91.png)

back to normal if use private windows
https://pan.baidu.com/disk/home?_at_=1636115866116#/all?path=%2F&vmode=list
![image](https://user-images.githubusercontent.com/75268245/140511334-8d40d240-9814-483e-85b8-4cc482f3707c.png)

## System Information

- OS: 
- windows 11
- Browser: 
- edge 95.0.1020.40 (Official build) (64-bit)
- Dark Reader Version: 
- 4.9.40 download from chrome store but use in edge browser

**Comment by Gusted** [comment]
Not related to dark reader.

**Comment by zhenjie1999** [comment]
but I turn off dark reader then back to normal

**Comment by Gusted** [comment]
Well, buttons that have the `javascript:` url is pretty normal - if it doesn't affect any of the button functions then I don't see it as a bug.

**Comment by zhenjie1999** [comment]
after I click cannot be sent, but only back to normal if i use private windows

**Comment by Gusted** [comment]
> after I click cannot be sent, but only back to normal if i use private windows

Edit the bug report to say that. The current bug report is not clear about what's going wrong.

**Comment by zhenjie1999** [comment]
updated report detail pls check

**Comment by Gusted** [comment]
Seems like a bug, I'm not able to test it myself as it's behind some kind of account/pay-wall

**Comment by zhenjie1999** [comment]
what data do I need to send you to check?

**Comment by Gusted** [comment]
> what data do I need to send you to check?

Not really possible, as it's better for someone that has a account and some knowledge to check what's going on.

**Comment by zhenjie1999** [comment]
ok thank you very much for reply so fast.

**Comment by hzbr** [comment]
I have the same problem with chrome browser

**Comment by suixinex** [comment]
这个问题也在<https://fanyi.baidu.com>出现，如上面的“翻译”按钮、右侧的设置都无法点击，下面应该会出现的历史记录也没了。看开发者回复好像说因为百度网盘需要登录所以无法复现，百度翻译不需要账户登录，个人不会英语，能否麻烦回复下开发者，可以在这个网站上复现，谢谢。
这个问题只在动态模式下出现，过滤和静态模式都正常。
另外更新了4.9.41该问题依然存在

**Comment by zhenjie1999** [comment]
Translated by deepL，用deep L翻译的
This problem is also found in https://fanyi.baidu.com, such as the "Translate" button on the top and the settings on the right are not clickable, and the history that should appear below is also gone. It seems that the developer replied that Baidu.com requires login so it can't be reproduced, but Baidu Translate doesn't require account login, I don't know English, can you please reply to the developer so that it can be reproduced on this website?
This problem only appears in dynamic mode, filtering and static mode are normal.
Also the problem still exists after updating 4.9.41

Translated with www.DeepL.com/Translator (free version)

**Comment by Gusted** [comment]
I think this issue might be a variant of #7302 - which was fixed by #7309
