### ISSUE TITLE
[Performance Issue] Flashing white during page changes

### ISSUE THREAD

**Issue by mzryz** [darkreader/darkreader#7265]
# Performance Issue Report

## Website Address

Any web page

## Steps To Reproduce

Go to any web site, click a link to a different page, entire page flashes 'regular/bright' then corrects to dark.

## System Information

- OS: Android, Linux, OS X
- Browser: Firefox 94 on both Linux, Android and OS X
- Dark Reader Version: 4.9.40

## Additional Context
- Do you have hardware acceleration enabled? Yes
- Seems to have started happening only recently, within the week I guess?

**Comment by Gusted** [comment]
Dup of #7255
