### ISSUE TITLE
[Broken Website] https://papago.naver.com/

### ISSUE THREAD

**Issue by goguma6** [darkreader/darkreader#7268]
# Broken Website Report

## Website Address
https://papago.naver.com/

## Steps To Reproduce
- Go to https://papago.naver.com/

## Expected Behavior
The web translator should be able to be used.

## Actual Behavior
It freezes up instantly and doesn't allow the translator to work even if the Dark Reader is disabled.

## System Information

- OS: Windows 10
- Browser: Chrome 95.0.4638.69
- Dark Reader Version: 4.9.40

## Additional Context
The owner of the translator, Naver, is recently trying to push their own browser with a dark mode for their associated sites. Maybe it has something to do with that?

**Comment by Gusted** [comment]
Underlying condition as: #7266
