### ISSUE TITLE
[Bug] Theme editor rules getting wiped out on browser restart

### ISSUE THREAD

**Issue by aledmb** [darkreader/darkreader#7269]
I have the following rules for trello.com, and they are getting wiped out every time i restart the browser (they're gone from the theme editor).

================================

trello.com

CSS
._2w6KZMbwKqxZVN._3TTqkG5muwOzqZ.ZOUktZwsING7-0, .board-header-btn.mod-board-name, .board-header-btn.js-star-board, .js-board-header-btn-org-wrapper, .board-header-btns.mod-left { display: none !important; }
.board-canvas { background-color: #111 !important; }
#board { background-color: #111 !important; }
#board.collapsed-workspace-nav { padding-left: 0 !important; }
nav[data-test-id=workspace-navigation-nav] { display: none !important; }
#header { background-color: #111 !important; }
#header > div:first-child > div:first-child { display: none !important; }
.board-header { background-color: #111 !important; }
.list-wrapper { width: 310px !important; }
.list-card-details { width: 280px !important; background-color: #181818 !important; }
.list-wrapper.mod-add { display: none !important; }
.list { background-color: #222 !important; }
.list-card { background-color: black !important; }
.card-detail-window { background-color: #222 !important; }
.card-detail-window .card-label.card-label-yellow .label-text { color: #222 !important; }
.card-detail-window .card-label.card-label-red .label-text { color: #222 !important; }
.card-detail-window .card-label.card-label-green .label-text { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-yellow { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-red { color: #222 !important; }
.edit-labels-pop-over .card-label.card-label-green { color: #222 !important; }
.js-new-checklist-item-button { border: 2px solid #555 !important; }
::-webkit-scrollbar { display: none !important; }
.js-butler-card-buttons, .js-plugin-buttons, .card-back-card-back-upgrade-prompt-section, .js-cf-disabled.disabled, .js-change-card-members, .js-date-range-picker, .js-card-cover-chooser { display: none !important; }
.window-module hr, .js-copy-card, .js-subscribe, .js-convert-to-template, .js-more-menu, .new-comment.js-new-comment.mod-card-back, .card-detail-activity { display: none !important; }
.card-detail-item.card-detail-item-labels h3 { display: none !important; }
.window-header-inline-content.js-current-list p { color: #222 !important; margin-left: -38px !important; }
.window-header-inline-content.js-subscribed-indicator-header { display: none !important; }
.js-card-record-button, .js-card-templates-button { display: none !important; }
.checklist-item-due.js-checklist-item-due, .checklist-item-assignee.js-checklist-item-assignee { display: none !important; }
.checklist-progress { display: none !important; }
._3K09J3xqj8n-uQ._3TTqkG5muwOzqZ.ZOUktZwsING7-0 span:not(.icon-sm) { display: none !important; }
.board-header-btn.mod-show-menu span:not(.icon-sm) { display: none !important; }
.js-checklist-copy-source { display: none !important; }
label[for=js-checklist-copy-source] { display: none !important; }
._1c8QdR-OBBffEh { display: none !important; }
.board-header { display: none !important; }
.card-label.mod-card-front { height: 5px; min-width: 30px !important; max-width: 30px !important; border-radius: 1px !important; }
.list-wrapper:nth-child(6) .list-card-details { background-color: #282828 !important; }
.list-wrapper:nth-child(6) .list-card-details * { color: #888 !important; }
.list-wrapper:nth-child(6) .list-card-details .list-card-title { text-decoration: line-through !important; }
.list-wrapper:nth-child(6) .list-card-details .badge.js-checkitems-badge.is-complete { background-color: inherit !important; }
.card-label-red { background-color: #FF6347 !important; }
.card-label-yellow { background-color: #FFD700 !important; }
.card-label-green { background-color: rgb(87, 143, 54) !important; }
.quick-card-editor-buttons-item.js-edit-members { display: none !important; }
.quick-card-editor-buttons-item.js-edit-cover { display: none !important; }
.quick-card-editor-buttons-item.js-move-card { display: none !important; }
.quick-card-editor-buttons-item.js-edit-due-date { display: none !important; }
.quick-card-editor-buttons-item:first-child { display: none !important; }
.description-fake-text-area { background-color: #282828 !important; }
textarea.field.full.single-line.js-checkitem-input { background-color: #282828 !important; }
.nch-button.hide-on-edit.js-confirm-delete { background-color: #333 !important; color: #888 !important; }
.nch-button.js-new-checklist-item-button.mt-4.hide-on-edit { border: none !important; background-color: #333 !important; color: #888 !important; }

**Comment by Gusted** [comment]
Please follow the issue template.
