### ISSUE TITLE
[Dynamic] Various issues on Google Calendar

### ISSUE THREAD

**Issue by joshsleeper** [darkreader/darkreader#727]
## dark on dark text
![image](https://user-images.githubusercontent.com/849941/45518816-c0043c00-b780-11e8-8fda-c5d417e31c40.png)

## white background on user flyout (w/ bonus green privacy blocks!)
![image](https://user-images.githubusercontent.com/849941/45518920-28531d80-b781-11e8-85d0-665c6a998aaf.png)

**Comment by alexanderby** [comment]
Should work OK now.

**Comment by alexanderby** [comment]
The problem was that white header was fixed with `INVERT` rule in config, now it was wrongly inverted after the fix, for some reason it looked OK for me at the moment of fixing the problem.

So, I've removed calendar.google.com fixes from the config, it should auto-update within 15 minutes.

**Comment by alexanderby** [comment]
It seems I've removed calendar.google.com fixes in Dev Tools, but didn't commit these changes on GitHub.

**Comment by joshsleeper** [comment]
woohoo, now it looks _way_ better!
Thanks @alexanderby!

![image](https://user-images.githubusercontent.com/849941/47866822-34994580-ddd6-11e8-8518-2efccc2b9b2d.png)
