### ISSUE TITLE
[Bug] enableDark img CORS 

### ISSUE THREAD

**Issue by Haiwar** [darkreader/darkreader#7272]
Error: Embedded Dark Reader cannot access a cross-origin resource https://xxx-images.oss-cn-xxx.aliyuncs.com/imgv2/img.png Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.

TypeError: Failed to fetch

![image](https://user-images.githubusercontent.com/35055270/140596685-7d9bc48d-3bec-42e5-8709-15ddf6fe6684.png)

my code:

```js

// Vue
import {disable as disableDarkMode, enable as enableDarkMode, setFetchMethod as setFetch} from 'darkreader'

watch: {
    // watch theme mode
    darkMode(val) {
        setFetch(window.fetch)
        if (val) {
            enableDarkMode({})
        } else {
            disableDarkMode()
        }
        setDarkMode(this.darkMode)
    }
},
```

**Comment by Haiwar** [comment]
@Gusted

mogul，look this bug，help me。

**Comment by Gusted** [comment]
Please follow the issue template.

**Comment by Haiwar** [comment]
> Please follow the issue template.

ok, https://github.com/darkreader/darkreader/issues/7274
