### ISSUE TITLE
[Bug] enableDark img CORS

### ISSUE THREAD

**Issue by Haiwar** [darkreader/darkreader#7274]
# enableDark img CORS

## Bug Description

Error: Embedded Dark Reader cannot access a cross-origin resource https://xxx-images.oss-cn-xxx.aliyuncs.com/imgv2/img.png Overview your URLs and CORS policies or use DarkReader.setFetchMethod(fetch: (url) => Promise<Response>)). See if using DarkReader.setFetchMethod(window.fetch) before DarkReader.enable() works.

## Website Address

https://v2.zuiwanjia.com/

## Expected Behavior

Error when initializing

## Actual Behavior

```js

// Vue
import {disable as disableDarkMode, enable as enableDarkMode, setFetchMethod as setFetch} from 'darkreader'

watch: {
    // watch theme mode
    darkMode(val) {
        setFetch(window.fetch)
        if (val) {
            enableDarkMode({})
        } else {
            disableDarkMode()
        }
        setDarkMode(this.darkMode)
    }
},

```

## Screenshots

![image](https://user-images.githubusercontent.com/35055270/140603008-008bbaa7-873e-49d8-b1d7-6027368ac7b7.png)

## System Information

- OS: Windows10
- Browser: Chrome  95.0.4638.69
- Dark Reader Version:  4.9.40

**Comment by Haiwar** [comment]
@Gusted

**Comment by Gusted** [comment]
Hi @Haiwar!

You're hitting a usual case of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), I suggest looking up on how to migate them and work around CORS, any suggestion that could workaround the issue should be applied via the `        setFetch((fetchOptions) => { ... } )` function. As this is CORS and Dark Reader is simply telling what is going wrong, I don't see it relevant to keep this issue open.

PS, Don't ping me, I get to the issue when I can.

Regards,
Gusted

**Comment by Haiwar** [comment]
Thank you very much for your answer,but what should I do😂

```
    created() {
        setFetch(() => {
                   ....
        })
        enableDarkMode()
    },
```

**Comment by Gusted** [comment]
The solution isn't a copy-paste one, I've linked a MDN page that explains what CORS is, so you can understand what's going on. And as I've said you should lookup some workarounds for CORS to workaround the issue.

**Comment by Haiwar** [comment]
> The solution isn't a copy-paste one, I've linked a MDN page that explains what CORS is, so you can understand what's going on. And as I've said you should lookup some workarounds for CORS to workaround the issue.

Okay, I hope there won’t be anyone who asks the same question. Alright sounds good, thanks for your efforts.

**Comment by Haiwar** [comment]
I read the documentation, but I don't know much English. This question puzzled me all afternoon, can you tell me what to do. thanks😫

**Comment by Gusted** [comment]
>  can you tell me what to do. thankstired_face

Like I said, the solution isn't just a copy-paste or ready-to-go. The fix can vary from a lot factors, if their was a general solution I would've given it. But working around CORS issues is not really that a general solution can be given to.

**Comment by Haiwar** [comment]
> > can you tell me what to do. thankstired_face
> 
> Like I said, the solution isn't just a copy-paste or ready-to-go. The fix can vary from a lot factors, if their was a general solution I would've given it. But working around CORS issues is not really that a general solution can be given to.

I got it, thank you for your reply

**Comment by Haiwar** [comment]
> > can you tell me what to do. thankstired_face
> 
> Like I said, the solution isn't just a copy-paste or ready-to-go. The fix can vary from a lot factors, if their was a general solution I would've given it. But working around CORS issues is not really that a general solution can be given to.

Will this affect the operation of the website?

**Comment by Haiwar** [comment]
hi, Is this okay?

the picture here is accessible from any website
```
setFetch({
    headers: {
        "Access-Control-Allow-Origin": "*"
    },
})
```


I don't know how to deal with CORS in setFetch.
This is the last question🤡

**Comment by Gusted** [comment]
> setFetch({
>     headers: {
>         "Access-Control-Allow-Origin": "*"
>     },
> })

The Access-Control-Allow-Origin can only be sent by the server, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin ("Response Header")

**Comment by Haiwar** [comment]
> setFetch

what does setFetch do

```
setFetch(option => {
    console.log(option, `=========>option`)
})
```
![image](https://user-images.githubusercontent.com/35055270/140605978-517bf81c-76f8-47e4-93d4-fb29fd26ae44.png)

😵

**Comment by Haiwar** [comment]
Solution:
Ignore the cross-domain error report and does not affect the operation of the website.

```
import {
    enable as enableDarkMode,
    setFetchMethod as setFetch,
} from 'darkreader';
```

```
setFetch(window.fetch);
enableDarkMode()
```
