### ISSUE TITLE
bbs.pcbeta.com 无法工作啊

### ISSUE THREAD

**Issue by LsnmxNB** [darkreader/darkreader#728]
如题谢谢

**Comment by rolagg** [comment]
It'd be good, if you describe the bug in English.

**Comment by alexanderby** [comment]
This website looks OK now.
<img width="1173" alt="screen shot 2018-11-01 at 12 41 10" src="https://user-images.githubusercontent.com/9638588/47844442-87bdc900-ddd3-11e8-8295-6afa6159e319.png">
