### ISSUE TITLE
[Bug] 'Toggle Current Site' doesnt work when dark reader set to off (ie in the day)

### ISSUE THREAD

**Issue by charakaSamawry** [darkreader/darkreader#7280]
# Bug Report

## Bug Description
'Toggle Current site', when Dark Reader is toggled off, and in light mode, doesnt work. 
When dark reader is 'on' toggling a specific site works as expected 

(Though, sites with their own dark mode, enabled by system/chrome dark mode (Enabled automatically by www.github.com/AutoDarkMode/Windows-Auto-Night-Mode - not that that matters), wont toggle into a light version.. (a minor side issue, and I suspect not fixable from dark reader and doesnt really matter because a sites own dark mode shouldnt be broken and need turning off to fix ...)

# System Information
- OS: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎26/‎09/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

- Browser: Version 95.0.4638.69 (Official Build) (64-bit)
- Dark Reader Version: 4.9.40

**Comment by Gusted** [comment]
Hi @charakaSamawry!

Just to clarify, "when Dark Reader is toggled off", do you mean that the extension is turned off and not a individual site? As in such case, the toggle current site should work(New UI) but doesn't reflect any changes. The Old UI(default) doesn't have this functionality that allows toggle current site when the extension is turned off.

Regards,
Gusted

**Comment by charakaSamawry** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/62015653/140645839-b9d10457-3136-423f-9cf8-c58af56a7008.png) 
As shown i have 'that' ui (sorry not sure of new vs old) which has the toggle current site option there, but, it only works when the adjacent toggle, is set to 'On'. 

The features are disabled when its off.. but i have found myself wanting to enable it for a specific site, occasionally in the day (for some reason) and its not possible when the automation has toggled the extension 'off'.

Im starting to think its more of a feature than a bug, but I'm unsure why it works like that because even the site list isnt accessible when the extension is toggled off.. i guess you wouldnt ever notice a site needs adding to the list in the day, though, perhaps you read of one that others have added, in the day, and want to add it?



(And a side note+general moan - being that I, manually - (frustratingly), use chrome://flags 'force dark mode for web contents', that dark reader doesnt do much, other than change the specific dark theme a little - and I shouldnt bother with 'dark reader' if im manually enabling that, and also use chromes beta version 'canary' for more easily accessible experimental features (can add a button that takes you to the experimental/chrome://flags page - though in stable chrome version I have set chrome to always open the experimental page on start up)
I wish dark reader worked on duckduckgo new tab and chrome-extension:// and chrome web store so i could use dark readers automation and, nicer, more customisable, less website breaking - dark mode.. .. why google..? please add this feature properly with automation (and microsoft while im having a moan!) and make 3rd party extensions like 'dark reader'  (and the windows program 'auto dark mode') unnecessary/optional! /rant) yawn lol
