### ISSUE TITLE
[Bug] "Dark Reader" is slowing down Firefox

### ISSUE THREAD

**Issue by naoliv** [darkreader/darkreader#7284]
# Bug Report

## Bug Description

Firefox is giving a lot of `"Dark Reader" is slowing down Firefox. To speed up your browser, stop that extension` recently.
Probably related with the last update from November 5.

## Website Address

It's happening on multiple sites, nothing very specific it seems.
It randomly happens while navigating.

## Screenshots

![](https://user-images.githubusercontent.com/982338/140623582-1157adae-4ce1-4ff2-b143-a8f0a9eb4077.png)

## System Information

- OS:  Linux
- Browser:  Firefox 93
- Dark Reader Version:  4.9.41

## Additional Context

From what I can see, Dark Reader was updated on November 5; before this I didn't see any message about it slowing down Firefox.
Probably something was changed in the latest release which is causing this?

**Comment by Gusted** [comment]
#7266
