### ISSUE TITLE
[Broken Website] Can't display PLAY Button on www.zdf.de

### ISSUE THREAD

**Issue by crazyyzarc** [darkreader/darkreader#7295]
# Broken Website Report

## Website Address
www.zdf.de (every video)

## Steps To Reproduce
- Go to www.zdf.de and try to play a video

## Expected Behavior
- display play button

## Actual Behavior
- don't display play button

## Screenshots
with dark reader:
![2021-11-07_20-53-54-874_LH19u](https://user-images.githubusercontent.com/4954535/140659867-fad4016f-ab8b-438d-972c-3afdc725361a.png)

without dark reader:
![2021-11-07_20-54-08-183_0QG62](https://user-images.githubusercontent.com/4954535/140659875-b1a3c8d0-6cae-4c68-87c4-db6a29dd5dfc.png)

## System Information
- OS: Windows 10 21H1
- Browser: Firefox 93
- Dark Reader Version: 4.9.41

## Additional Context
none

**Comment by Gusted** [comment]
Dup #7114
