### ISSUE TITLE
[Broken Website] Lots of websites broken on Brave browser

### ISSUE THREAD

**Issue by wickles** [darkreader/darkreader#7297]
# Broken Website Report

## Website Address

https://finance.yahoo.com/

## Steps To Reproduce

Install Dark Reader in Brave, enable and go to one of the listed websites. 

## Expected Behavior

dark mode (first screenshot, Chrome)

## Actual Behavior

not dark mode (second screenshot, Brave)

## Screenshots

![2021-11-07 15_22_01-ShareX-chrome](https://user-images.githubusercontent.com/4229542/140686674-a81a2bce-b572-417c-abd5-8cfea0b93bb6.png)

![2021-11-07 15_22_49-ShareX-brave](https://user-images.githubusercontent.com/4229542/140686680-63f0ab1c-26bc-48cb-a82b-0c9a76068938.png)

## System Information

- OS:  Windows 10
- Browser:  Brave 1.31.88
- Dark Reader Version:  4.9.41

## Additional Context

I have experienced this problem with a number of websites. I will add more when I remember to make note of it.

**Comment by Gusted** [comment]
Hi @wickles!

`finance.yahoo.com` seems to be working fine on my machine. I think you have a entry in your siteList that is either `yahoo.com` or `finance.yahoo.com` whichs tells dark reader to not darken this site.

Regards,
Gusted

**Comment by wickles** [comment]
I do not have any sites in my list on Brave. Did you try on Brave browser?

**Comment by wickles** [comment]
I have identified the problem, it is not related to Brave. Will file another report if needed.
