### ISSUE TITLE
[Bug] globalThis is not defined

### ISSUE THREAD

**Issue by Haiwar** [darkreader/darkreader#7298]
# Bug Report

## Bug Description

globalThis is not defined

## Screenshots

![image](https://user-images.githubusercontent.com/35055270/140691187-6f63be75-728b-46db-83bd-75e3dbabfe02.png)

## System Information

- OS: Windows10
- Browser: Chrome 70
- Dark Reader Version: 4.9.40

**Comment by Haiwar** [comment]
Downgrade version to 4.9.34

**Comment by tokumeikoi** [comment]
> Downgrade version to 4.9.34

4.9.34 Does not use globalThis cause any problems?

**Comment by Haiwar** [comment]
I don’t know, I don’t use it anymore. Not compatible☹
