### ISSUE TITLE
[Broken Website] www.deskmodder.de

### ISSUE THREAD

**Issue by crazyyzarc** [darkreader/darkreader#7300]
# Broken Website Report

## Website Address
https://www.deskmodder.de/

## Steps To Reproduce
Here is an example:
- Go to https://www.deskmodder.de/blog/2021/11/08/screentogif-2-34-1-wichtig-fuer-die-kommenden-updates-ab-2-35/

## Expected Behavior
Dim all website elements 

## Actual Behavior
Dim not all website elements

### With darkreader
![2021-11-08_08-53-39-084_Sx500](https://user-images.githubusercontent.com/4954535/140704263-f32fed24-608f-48c4-ada9-b2c6bf0c69ff.png)

### Without darkreader
![2021-11-08_08-53-48-649_utNTt](https://user-images.githubusercontent.com/4954535/140704142-3919c998-f2f3-4376-bf86-580c38ccdebd.png)

## System Information
- OS: Windows
- Browser: Firefox 93
- Dark Reader Version: 4.9.41

## Additional Context
None

**Comment by Gusted** [comment]
Hi @crazyyzarc!

I don't seem to be able to reproduce the problem on my machine - could you check for recent updates and install v4.9.42, it might be able to fix the problem.

Regards,
Gusted
