### ISSUE TITLE
[Bug] (FOUC) The fall back style is not synced with the actual style

### ISSUE THREAD

**Issue by Aqa-Ib** [darkreader/darkreader#7303]
# Bug Report

## Bug Description

(**Please watch the video attached to this bug report. It is recorded on slow motion for you to be able to see the flash transition clearly).**
On some web sites, Darkreader's fall back style is not synced with the actual style. This causes FOUCs (flash of unstyled content) - also called the "white flashes".

## Website Address

https://suckless.org/

## Steps To Reproduce

- Go to https://suckless.org/
- Click on any of the top side menu items
- Notice the flashes.

## Expected Behavior

The expected transition is: fall back style → actual style

## Actual Behavior

The current transition is: fall back style → unstyled content → actual style

## Screenshots

Watch the slow motion video attached at the bottom of this post please.

## System Information

- OS:  Arch Linux
- Browser:  firefox 94.0.1
- Dark Reader Version:  4.9.41

https://user-images.githubusercontent.com/16420574/140729709-819a119a-efa0-4166-a6f5-641de51b1de6.mp4

**Comment by Gusted** [comment]
Oh no... Not white flashes again.

Could you try to side-load this extension and see if that fixes the issue.
[darkreader-firefox.zip](https://github.com/darkreader/darkreader/files/7498731/darkreader-firefox.zip)

**Comment by Aqa-Ib** [comment]
Nope it doesn't, still the same.
Sorry Gusted, I know I am very persistent with this issue. I won't bother again though. It is fine anyway.
Peace and love <3

**Comment by NguyenASang** [comment]
Ye, white flashes are super annoying and hard to fix, so maybe just be patient and wait for a complete fix :D

**Comment by Aqa-Ib** [comment]
It is fixed now. Great job @Gusted, impressive indeed. Dark Reader is nearly perfect at the moment.
