### ISSUE TITLE
[Broken Website] www.spiegel.de

### ISSUE THREAD

**Issue by crazyyzarc** [darkreader/darkreader#7305]
# Broken Website Report

## Website Address
https://www.spiegel.de

## Steps To Reproduce
- Go to https://www.spiegel.de/a-b71fc91c-3a48-4831-ba6f-3a43d5574278
- Scroll down and see the first chart

## Expected Behavior
Show names on chart

## Actual Behavior
Don't show names on chart

### With darkreader
![2021-11-08_15-52-25-308_oS0hG](https://user-images.githubusercontent.com/4954535/140764162-792547a7-8991-4ef5-9c3f-96b3daa0e9e6.png)

### Without darkreader
![2021-11-08_15-52-33-516_KDiDz](https://user-images.githubusercontent.com/4954535/140764179-7301747c-e7e9-4377-9595-ee7f96dc0148.png)

## System Information
- OS: Windows 10
- Browser: Firefox 93
- Dark Reader Version: 4.9.41

## Additional Context
None

**Comment by Gusted** [comment]
Hi @crazyyzarc!

I don't think, that I'm able to fix this issue as this issue is only available behind a paywall.

Regards,
Gusted
