### ISSUE TITLE
IMDB Photo links do not work with DarkReader on.

### ISSUE THREAD

**Issue by SupremeGit** [darkreader/darkreader#731]
Load an imdb page.
scroll down to the Photos section.
click a foto.
*behold the epic fail*

It fails to display the foto, and appears to lock the whole page. You can't scroll the page, you can't do anything.

**Comment by SupremeGit** [comment]
i love darkreader, but this is quite a nasty bug, because it is not obvious what is causing the issue. People with DarkReader installed may be having these issues, and not realising that they have to turn darkreader off on IMDB. :-(

**Comment by FatalMerlin** [comment]
I don't know what's causing this for you, but I can't replicate this.

**Comment by joaocv3** [comment]
Me neither

**Comment by alexanderby** [comment]
A screenshot and browser version would be great.

**Comment by liquidmetalrob** [comment]
This is still a problem.

**Comment by Gusted** [comment]
LGTM seems fixed.
