### ISSUE TITLE
[Bug] Auto doesn't follow system

### ISSUE THREAD

**Issue by charakaSamawry** [darkreader/darkreader#7311]
In both old and new UI versions Dark Reader doesnt change to dark mode when the system is set to dark mode. Google chrome and other apps are following the dark mode but not Dark Reader. 

I use Auto Dark mode for windows https://github.com/AutoDarkMode and when that switches to dark mode other program such as chrome change to dark mode, following the system change, but dark reader doesnt detect it. 
In Auto Dark Mode i have the settings, 'Apps - adapt to system' and 'System - always dark', which (despite being non-intuitive), makes the system switch apps from dark to light, and keep the system in dark mode (so the taskbar stays in the automatic accent colour from background, and doesnt switch to, ugly, light grey).
As mentioned, google chrome and other apps/programs, such as windows explorer, detect this change and switch between dakr and light mode.
Dark Reader, however, doesnt see this change and stays in light mode, for some reason..

Being that the new UI (which i guess will take over from the old design at some point) doesnt include an auto feature other than following the system theme, i guess this is an issue that should be resolved, as, otherwise i wont be able to use dark readers automation at all.

Thanks for any help/advice.
Sam

**Comment by Gusted** [comment]
Hi @charakaSamawry!

Please follow the issue report, as I miss information like which browser you're using etc.

Regards,
Gusted
