### ISSUE TITLE
[Broken Website] Hang while loading on meta.wikimedia.org

### ISSUE THREAD

**Issue by Rummskartoffel** [darkreader/darkreader#7313]
# Broken Website Report

## Website Address
<https://meta.wikimedia.org/w/index.php?title=Special:Log>

## Steps To Reproduce
Navigate to the URL provided above or another meta.wikimedia.org URL of the form `https://meta.wikimedia.org/w/index.php?<params>`, where `<params>` is a URL search string such as `title=Special:Log` or `diff=22311115&oldid=22310300`. 

Other URLs on that domain such as <https://meta.wikimedia.org/wiki/Main_Page> appear to be unaffected. Other Wikimedia sites such as en.wikipedia.org, de.wikipedia.org, commons.wikimedia.org appear to be unaffected.

## Expected Behavior
The site loads normally.

## Actual Behavior
The site keeps loading forever and the tab freezes.

## Screenshots
N/A

## System Information

- OS: Windows 10 x64
- Browser: Edge 95.0.1020.44 x64, Chrome 95.0.4638.69 x64, Firefox 94.0.1 x64 (may be harder to reproduce than the others)
- Dark Reader Version: 4.9.41 for all three

## Additional Context
N/A

**Comment by Gusted** [comment]
Hi @Rummskartoffel!

Do you have any other extension enabled, could you also check if you're able to download v4.9.42, it should be on some of the webstores already - I was not able to reproduce any slowdowns or crashes on the given URL.

Regards,
Gusted

**Comment by cybermuse** [comment]
v4.9.42 fixed the issue. I had a bunch of sites that was making firefox crash, but all is well now.

**Comment by Rummskartoffel** [comment]
Yes, .42 fixed it. Thanks a lot!
