### ISSUE TITLE
[Broken Website] invent.kde.org store.kde.org forum.kde.org (maybe more subdomains)

### ISSUE THREAD

**Issue by notpentadactyl** [darkreader/darkreader#7319]
# Broken Website Report

## Website Address

https://invent.kde.org/
https://store.kde.org/
https://forum.kde.org/

## Steps To Reproduce
- Go to https://invent.kde.org, or https://store.kde.org, or https://forum.kde.org/
- Website is white

## Expected Behavior
Websites should be dark.

## Actual Behavior
Websites are white.

## Screenshots
![kde-invent](https://user-images.githubusercontent.com/21175961/140992163-afed1954-69d2-4204-b1aa-11d57d2c0395.png)
![kde-store](https://user-images.githubusercontent.com/21175961/140992184-9358d693-c483-487e-ac46-866d422b3ae8.png)
![kde-forum](https://user-images.githubusercontent.com/21175961/140992190-44a1d351-31c2-429d-be39-96a631e1c723.png)

## System Information

- OS: Linux
- Browser: Firefox 94.0.1
- Dark Reader Version: 4.9.42

**Comment by Aqa-Ib** [comment]
Not reproducible on my end.

**Comment by notpentadactyl** [comment]
> Not reproducible on my end.

Thanks for the quick reply.

I can also not reproduce it in a new profile (tried it again) and also on Firefox Android.

How can I debug this on my end?
I have disabled all add-ons (except dark reader) on my normal profile and the issue still occurs.

**Comment by arche-dev** [comment]
> > Not reproducible on my end.
> 
> Thanks for the quick reply.
> 
> I can also not reproduce it in a new profile (tried it again) and also on Firefox Android.
> 
> How can I debug this on my end? I have disabled all add-ons (except dark reader) on my normal profile and the issue still occurs.

Try creating a Firefox profile, add the dark reader add-on and see if the issue still occurs?

Also I couldn't reproduce this either
---
OS: Arch Linux
Browser: Firefox 93
Dark Reader: 4.9.42

**Comment by Gusted** [comment]
Hi @notpentadactyl!

Do you have by any change `kde.org` in your site-list?
Currently it will also match any sub-domains, you can change the `kde.org` to `^kde.org` to only match that domain.

Regards,
Gusted

**Comment by notpentadactyl** [comment]
> Hi @notpentadactyl!
> 
> Do you have by any change `kde.org` in your site-list? Currently it will also match any sub-domains, you can change the `kde.org` to `^kde.org` to only match that domain.
> 
> Regards, Gusted

This fixed it, thank you!
