### ISSUE TITLE
Option to disable remote list retrieval

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#733]
Would it be possible to get an option to disable remote dark list retrieval? I would prefer to only use a manually curated list and not have requests on every firefox launch to raw.githubusercontent.com.

**Comment by gitut2007** [comment]
1+. 
(I would assume the list would grow quite big making the addon slower, list from pages that mostly one wouldn't visit anyway...)

**Comment by Gusted** [comment]
Fixed.
