### ISSUE TITLE
[Broken Website] berlingske.dk

### ISSUE THREAD

**Issue by Mennaruuk** [darkreader/darkreader#7332]
# Broken Website Report

## Website Address

https://www.berlingske.dk
## Steps To Reproduce

- Go to https://www.berlingske.dk
- Note the site logo on the top left

## Expected Behavior

Logo should appear bright against a dark background.
## Actual Behavior

Logo is instead black against a dark background.
## Screenshots

![image](https://user-images.githubusercontent.com/52135169/141232272-1cd16272-2022-4b98-ae12-172261e23a7c.png)

## System Information

- OS: Windows 10
- Browser: Firefox 94.0.1
- Dark Reader Version: 4.9.42

**Comment by SilentObserver** [comment]
@Mennaruuk the logo is an Image. I don't think Images can be changed.
