### ISSUE TITLE
Don't style form inputs on Firefox

### ISSUE THREAD

**Issue by ascclemens** [darkreader/darkreader#734]
Setting `border-color` or `background-color` on any `button` or `input` causes them to stop looking like native components and instead makes them look like some ancient OS.

What buttons look like in Firefox when styled by Dark Reader: ![oh god](https://i.imgur.com/vMgcVud.png)

What they should look like: ![please](https://i.imgur.com/8XdyEg5.png)

Chrome ignores this, but Firefox makes a non-native button instead. Not styling form inputs, or having an option for it, would help make the browser look more integrated with the OS.

**Comment by rolagg** [comment]
> perhaps only on macOS
Windows 10, happens both on Chrome and Firefox.

**Comment by TheMatten** [comment]
Affected on Arch Linux with Gnome 3.30.1 in Firefox too.
