### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by Regeneronz** [darkreader/darkreader#7344]
# Broken Website Report

## Website Address
https://fanyi.baidu.com/

## Steps To Reproduce

Try using the website to translate languages while Dark Reader is turned on = The website will not translate anything
Turning off Dark Reader fixes it, but it then keeps the super bright white light turned on which hurts my eyes and defeats the purpose of this extension.

## Screenshots

![image](https://user-images.githubusercontent.com/94131835/141339458-78465fe4-c427-410e-bf4c-abbd0ab07b13.png)
![image](https://user-images.githubusercontent.com/94131835/141339541-92e98e53-bc42-49b3-8108-d64a9ec8a2d8.png)

## System Information

Chrome
Version 95.0.4638.69 (Official Build) (64-bit)

4.9.42 Dark Reader

- OS:  e.g. Windows 10

## Additional Context

I did not have these problems 1-2 weeks ago. It just started happening this week or a few days before last weekend maybe.

**Comment by Gusted** [comment]
Variant of #7302
