### ISSUE TITLE
[Bug] Dark Reader conflicts with Shut Up: Comment Blocker

### ISSUE THREAD

**Issue by RickyRomero** [darkreader/darkreader#7347]
# Bug Report

## Bug Description
My extension, Shut Up: Comment Blocker, blocks comment sections on webpages by default. It does this by injecting CSS on every webpage.

It also offers users the ability to show hidden comments by clicking its toolbar icon. When this happens, Shut Up removes the injected CSS from the page so comments will appear.

In Firefox, Dark Reader copies my injected CSS into a `<style>` element with the class `.darkreader--cors`. This breaks my extension's ability to turn off its stylesheets, because Dark Reader is applying its own copy of my styles which I don't control.

The Chrome version of Dark Reader doesn't append `.darkreader--cors` to the page, so this issue doesn't happen in Chrome.

This conflict with Dark Reader was first reported by a user of my extension:
https://github.com/RickyRomero/shut-up-webextension/issues/17

## Website Address

See **Steps To Reproduce** below.

## Steps To Reproduce

1. Install [Shut Up: Comment Blocker](https://addons.mozilla.org/en-US/firefox/addon/shut-up-comment-blocker/) from AMO.
2. Install [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) from AMO.
3. Open [this Hacker News article](https://news.ycombinator.com/item?id=22752131) in Firefox.
4. Click on Shut Up's toolbar icon to show the comments on the page.

## Expected Behavior

Shut Up will remove its stylesheet, allowing the comments to appear with no interference.

## Actual Behavior

Shut Up removes its stylesheet, but comments are still hidden because Dark Reader has copied Shut Up's stylesheet.

## Screenshots

Not applicable

## System Information

- OS: macOS Monterey 12.0.1 (21A559) – Also happens on Windows and Fedora
- Browser: Firefox 94.0.1 (64-bit)
- Dark Reader Version: 4.9.42

## Additional Context
This is tangentially related: I noticed a problem where Dark Reader and Shut Up have warring `MutationObserver`s to get to the end of the `<head>`. To get around this, I'm working on a heuristic to detect when Shut Up keeps getting pushed back by the same script, and will defer to that script. This should result in a short burst of competing activity, after which Shut Up will chill out.

I skimmed Dark Reader's source code and that doesn't appear to be the root cause of this bug, but I wanted to mention that I'm working on fixing the warring `MutationObserver` problem.

**Comment by Gusted** [comment]
Hi @RickyRomero!

Thank you for your extensive bug report, sorry for the inconvenience, the fix is luckily small for this problem. #7357

Regards,
Gusted
