### ISSUE TITLE
Square boxes on font icons.

### ISSUE THREAD

**Issue by 4goodapp** [darkreader/darkreader#736]
First of all Thanks You for this AMAZING app dev.

I noticed that one of my favorites feature that is changing font (very usefull for websites over using thin or small fonts) show some square boxes for icons.

Like picture in this trello page:

![image](https://user-images.githubusercontent.com/6249230/45758126-6da99c00-bc14-11e8-9bcd-5f11e46b9d33.png)

**Comment by nehemiahjacob** [comment]
+1 I can issue a bounty for this fix. @alexanderby What's the reasonable incentive(budget) for this?

**Comment by nehemiahjacob** [comment]
Most of them are font-awesome, can't they be filtered out under 'fa' class and handled separately?!

**Comment by 4goodapp** [comment]
Hi, just noticed icon fonts are displayed correctly now.

So if anyone else is facing this problem, I think this can be closed.

![image](https://user-images.githubusercontent.com/6249230/47850968-11b76300-ddcf-11e8-81ee-876aaebabfff.png)

**Comment by croaganey** [comment]
I'm still seeing this issue. Examples below. The code shows font-awesome. Deseleting a font override choice allows the icons to show correctly.
Dark Reader 4.6.12
Vivaldi | 2.1.1337.36 

![335f4505-4e53-43e1-b190-7568d1f83660](https://user-images.githubusercontent.com/6396011/48162959-a58ba200-e29b-11e8-81cf-75af0d37309b.png)
![40ce3f70-137f-4ed8-9d40-1d394fc72a54](https://user-images.githubusercontent.com/6396011/48162960-a58ba200-e29b-11e8-9fa0-811307197c34.png)

![68c566e2-fb8a-4194-af6f-6887d2f9266e](https://user-images.githubusercontent.com/6396011/48162972-acb2b000-e29b-11e8-9143-6d67cd74ab44.png)
![aed231b5-1e84-4f04-a391-37d6021a879e](https://user-images.githubusercontent.com/6396011/48162971-acb2b000-e29b-11e8-80ec-906616e3d5c5.png)

**Comment by nehemiahjacob** [comment]
Works well for me. No more square boxes.

**Comment by alexanderby** [comment]
@nehemiahjacob No changes were made, so you will see the square boxes, if websites use icons packed in font file.

**Comment by nehemiahjacob** [comment]
I see! BTW I was about to ask you if it's possible to leave monospaced fonts as are.

**Comment by Gusted** [comment]
> I'm not sure it can be fixed, sometimes icons are packed into fonts, so when you override the font, missing symbols are displayed with square boxes.

Depends on which font you using, Dark Reader have 0 influence on this.
