### ISSUE TITLE
[Feature Request] Add cryptpad.fr to Global Dark List

### ISSUE THREAD

**Issue by PrSunflower** [darkreader/darkreader#7361]
# Feature Request

Hello, https://cryptpad.fr/ is dark by default. Could you please add to global dark list?

## Screenshots

With Dark Reader disabled:

![image](https://user-images.githubusercontent.com/59576952/141658315-37c1a7a6-a020-4a3e-8a8c-1ebd57a1a38d.png)

**Comment by Gusted** [comment]
This site doesn't meet [the requirements](https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#adding-a-website-that-is-already-dark)
