### ISSUE TITLE
[Broken Website] kenh14.vn

### ISSUE THREAD

**Issue by bg2908** [darkreader/darkreader#7364]
# Broken Website Report

## Website Address

kenh14.vn

## Steps To Reproduce

- Update Dark reader on Firefox to version 4.9.40 or up
- Go to kenh14.vn on Firefox

## Expected Behavior

- Page load with dark theme.
- Can scroll, click link
## Actual Behavior

- Page not load fully, can't be resized.
- Can scroll but can't click any link on page.
- CPU usage shot up to 9%
- After awhile, a warning appear saying "Dark reader" is slowing down Firefox.
- Closing the tab does not make CPU usage back down. You must restart Firefox for thing to become normal again.

## Screenshots

![Screenshot from 2021-11-14 04-30-02 - Dark reader2](https://user-images.githubusercontent.com/51479893/141660954-7c9d0948-37d4-4e12-991f-878232911cd8.png)
Warning appear at top of the page | website does not resized | CPU usage of Web Content is 8,71%

## System Information

- OS: Linux 
- Browser: Firefox 94.0.1 
- Dark Reader Version: 4.9.42 

## Additional Context

Problem start appear with Dark Reader version 4.9.40
Can use version 4.9.39 without any problems.

**Comment by Gusted** [comment]
Variant of #7323, fixed in the next release.
