### ISSUE TITLE
[Bug] The configuration page in edge browser is not displayed properly.

### ISSUE THREAD

**Issue by pengqian089** [darkreader/darkreader#7365]
# Bug Report
The configuration page in edge browser is not displayed properly.
## Bug Description

I am preparing to use Edge browser with the intention of enabling remote debugging for Android devices, and I find that the page is blurry and I can't see the content.
## Website Address
edge://inspect/#devices

## Screenshots

![Darkread_Dark](https://user-images.githubusercontent.com/13491546/141663957-2194e96c-f2ae-4f7b-a2d5-0e25af14be97.png)
![InPrivate](https://user-images.githubusercontent.com/13491546/141663968-f06c1ecf-6b0c-4ad5-91bb-ad073224174d.png)

## System Information

- OS: Windows 11 21H2
- Browser:  Microsoft Edge 95.0.1020.44
- Dark Reader Version: 

## Additional Context

<!-- Provide any additional information about this bug. -

->

**Comment by Gusted** [comment]
Dark reader cannot style such pages.

**Comment by pengqian089** [comment]
> Dark reader cannot style such pages.

Dark reader has broken the edge://inspect/#devices page, even though adding it as a non-reverse list does not work.
