### ISSUE TITLE
W3.org Page being inverted to green-red patterns

### ISSUE THREAD

**Issue by FatalMerlin** [darkreader/darkreader#737]
Please have a look at how [this page](https://www.w3.org/Style/Examples/007/units.en.html) is being rendered:

- Normal: [Image](https://i.imgur.com/WKuStf1.png)
- Inverted: [Image](https://i.imgur.com/NxjbEiA.png)

As you can see, the colors changed from white to anything but dark/black.

I'm using the dynamic style generation for this.

**Comment by alexanderby** [comment]
Some psychodelic look :)

**Comment by LavenderTheGreat** [comment]
Can confirm this still occurs, encountered it when viewing this page: https://www.w3.org/Style/styling-XML.en.html .

Going to the homepage seems to imply it only happens on some pages? I'm guessing only older ones.
