### ISSUE TITLE
[Bug] Dark Reader does't work sometimes.

### ISSUE THREAD

**Issue by shenzhiming88** [darkreader/darkreader#7372]
# Bug Report

## Bug Description

Similar to https://github.com/darkreader/darkreader/issues/7340
`Dark Reader` does't work sometimes.

## Website Address

Any website.

## Steps To Reproduce

- Use automated tasks to make `Dark Reader` follow the system themes.
- Install [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) in order to automatically switch themes.
- Keep the browser open and put the computer to sleep until after the preset time to switch themes.
- Turn on your computer, and the theme should switch automatically at this point.

## Expected Behavior

`Dark Reader` should follow the themes of the current computer.

## Actual Behavior

`Dark Reader` still follows the color themes that were in place before the computer went to sleep (for example, I use light mode during the day, put the computer to sleep, and when I turn it on at night, it automatically switches to dark mode, but `Dark Reader` still displays the pages in light color)

## Screenshots

![image](https://user-images.githubusercontent.com/66902050/141688105-05406f9b-f458-4486-817e-316f2106e1be.png)

## System Information

- OS:  Windows 11 21H2 (22000.318)
- Browser:  Microsoft Edge 95.0.1020.53 (64-bit)
- Dark Reader Version:  4.9.39

**Comment by Gusted** [comment]
Similair as #7041 (automation is incorrect after sleep)

**Comment by AshutoshSajan** [comment]
yep, I am also facing some issues while toggling the dark and light mode in Microsoft Edge. It's not working properly.
