### ISSUE TITLE
[Feature Request] Dark Reader to sync with system theme settings

### ISSUE THREAD

**Issue by solitonmedic** [darkreader/darkreader#7375]
# Feature Request

## Is this feature request related to a problem?

Not quite. I thought it would be neat if Dark Reader would sync up with our Windows PC light and dark mode settings. For example, if the system theme was on Light, Dark Reader would turn itself off. If the system theme was on Dark, Dark Reader will be enabled.

## Additional Context

n/a

**Comment by Progaros** [comment]
![image](https://user-images.githubusercontent.com/22076711/141697530-e482e6f7-d6e2-4fab-b2ad-8197a0333a22.png)

**Comment by solitonmedic** [comment]
![image](https://user-images.githubusercontent.com/14916963/141699456-5b24e2a3-351b-4337-976b-5acdcdb1e925.png)

I don't have this on Firefox for some reason.

**Comment by Progaros** [comment]
Oh, i use the v5 preview version:


_To activate the new user interface do the following:_
- _Click Dark Reader icon._
- _Click Dev tools (in the bottom-right corner)._
- _Click Preview new design._

**Comment by IJustWantANamePlease** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/14916963/141699456-5b24e2a3-351b-4337-976b-5acdcdb1e925.png)
> 
> I don't have this on Firefox for some reason.

If you click the three dots in the top right corner there is an option with similar discription, not sure if it is the thing though.

**Comment by solitonmedic** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/14916963/141699456-5b24e2a3-351b-4337-976b-5acdcdb1e925.png)
> > I don't have this on Firefox for some reason.
> 
> If you click the three dots in the top right corner there is an option with similar discription, not sure if it is the thing though.

Got it, thank you!!
