### ISSUE TITLE
[Feature Request] Use the gmail built-in dark theme instead of the slow Dark Reader version

### ISSUE THREAD

**Issue by artisticfox8** [darkreader/darkreader#7383]
# Feature Request

## Is this feature request related to a problem?
Dark Reader should switch to the page's dark theme if it has one, as it often provides better speed and compatibility.
Many people use gmail with a dark theme and Dark Reader slows the page a lot, because the dynamic (default) dark mode is slower than loading a stylesheet, which the built-in gmail dark theme uses.

## Additional Context
I use a dualcore Intel computer, so speed is needed, important

**Comment by Mennaruuk** [comment]
#5719 once done should address this.

**Comment by Gusted** [comment]
#1285

**Comment by artisticfox8** [comment]
> 
> 
> #5719 once done should address this.

Dark Reader should also be able to switch to it if it is not default at the moment
