### ISSUE TITLE
Black Text on Marketwatch with Firefox Only

### ISSUE THREAD

**Issue by gashtal** [darkreader/darkreader#7387]
With Dark Reader addon enabled and dark mode turned on, both the text and backround on marketwatch.com become gray/black, resulting in very low visibility and readability. This issue only seems to happen on Firefox, while the addon works correctly on Opera (and probably Chrome) on the same page since the text is white instead of gray.

Example URL:

https://www.marketwatch.com/story/biden-to-sign-bipartisan-infrastructure-bill-into-law-authorizing-big-spending-on-roads-broadband-ev-chargers-and-more-11636995921

**Comment by Gusted** [comment]
Use the bug template.
