### ISSUE TITLE
[Dynamic] Doom 9

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#739]
http://forum.doom9.org/

Thanks

**Comment by rolagg** [comment]
I think it'd good if you also describe the bug, not just give a site link, when extension works wrong. Not all of the issues get fixed within the updates, so in the future we couldn't even know what was the problem.

**Comment by ShalokShalom** [comment]
![screenshot_20180921_095858](https://user-images.githubusercontent.com/6344099/45867993-f9dad100-bd84-11e8-8e9b-2a7aed43e181.png)

**Comment by alexanderby** [comment]
Looks OK with the latest update. There is some another bug with Firefox, I'm going to fix it soon.
