### ISSUE TITLE
[Broken Website] https://www.imperva.com/learn/data-security/soc-2-compliance/

### ISSUE THREAD

**Issue by kishaningithub** [darkreader/darkreader#7392]
# Broken Website Report

## Website Address

https://www.imperva.com/learn/data-security/soc-2-compliance/

## Steps To Reproduce

- Go to https://www.imperva.com/learn/data-security/soc-2-compliance/
- Toggle the site to "dark" with dark reader

## Expected Behavior

The site should become dark

## Actual Behavior

The site retains its white color

## Screenshots

<img width="1602" alt="Screenshot 2021-11-16 at 6 24 23 PM" src="https://user-images.githubusercontent.com/763760/141988844-8dffafca-46e0-4676-bd30-3263e7964522.png">

## System Information

- OS: Mac OS 
- Browser: Firefox 94.0.1 
- Dark Reader Version:  4.9.42

**Comment by Gusted** [comment]
Hi @kishaningithub!

What does the site look like when you have the site enabled? On the screenshot it shows that you have the site disabled to be styled.

Regards,
Gusted

**Comment by kishaningithub** [comment]
Hi @Gusted Thanks for the response!

When you say enabled/disabled you mean this toggle only right?

<img width="259" alt="Screenshot 2021-11-17 at 2 32 57 PM" src="https://user-images.githubusercontent.com/763760/142169821-26ba1c38-f981-44d7-b45f-db46ca3372eb.png">

Assuming that to be the case here is a screenshot in both the states

<img width="1607" alt="Screenshot 2021-11-17 at 2 33 49 PM" src="https://user-images.githubusercontent.com/763760/142169943-e0b886ed-cb9f-469c-858f-536ca0e6d3d6.png">

<img width="1610" alt="Screenshot 2021-11-17 at 2 34 13 PM" src="https://user-images.githubusercontent.com/763760/142169999-0f7cbe86-e270-4b1d-bb87-8e724a0454c6.png">

As you can see above the end result is the same

**Comment by Gusted** [comment]
You've the site disabled... Click on:
![image](https://user-images.githubusercontent.com/25481501/142193439-7ac76cc2-8b3d-4f22-9f4c-03c5e2ad4a00.png)

To enable it again.

**Comment by kishaningithub** [comment]
Feeling too dumb.. Thanks for the quick responses @Gusted 

The dark mode is being toggled as expected

<img width="1606" alt="Screenshot 2021-11-17 at 5 45 38 PM" src="https://user-images.githubusercontent.com/763760/142198875-d9771743-b38d-4984-9525-953d6b2ef90e.png">
