### ISSUE TITLE
[Broken Website] Crypto is not defined in IE11

### ISSUE THREAD

**Issue by johnsmith0209** [darkreader/darkreader#7393]
# Broken Website Report

## Website Address
www.lixinger.com

## Steps To Reproduce
- Go to www.lixinger.com. It has been fixed now by adding some code.
- If using the original repo, the website will crush and can not be loaded.

## Expected Behavior
- open web site and show some content.

## Actual Behavior
- crush, only show initial loading page.

## Screenshots
![image](https://user-images.githubusercontent.com/2549173/142000470-0323f42a-5dfb-4bda-88d2-e390c5145648.png)
- this error showed above means `crypto is undefined`.

## System Information

- OS: Win10
- Browser: IE 11
- Dark Reader Version: 4.9.40

## Additional Context
By adding the following code, this issue could be fixed.

```javascript
if (!window.crypto && window.msCrypto) {
     window.crypto = window.msCrypto;
}
```

**Comment by Gusted** [comment]
>  IE 11

IE is old and discounted. We don't support it, nor should anybody support it.
