### ISSUE TITLE
[Bug] image.baidu.com can't display pictures

### ISSUE THREAD

**Issue by yunv7** [darkreader/darkreader#7394]
# Bug Report

## Bug Description

 image.baidu.com can't display pictures
## Website Address

[ image.baidu.com](https://image.baidu.com/search/index?tn=baiduimage&ipn=r&ct=201326592&cl=2&lm=-1&st=-1&fm=result&fr=&sf=1&fmq=&pv=&ic=0&nc=1&z=0&hd=0&latest=0&copyright=0&se=&showtab=0&fb=0&width=&height=&face=0&istype=2&dyTabStr=MCw0LDYsMSw1LDMsNyw4LDIsOQ%3D%3D&ie=utf-8&ctd=&sid=&word=123)
## Steps To Reproduce

- Go to image.baidu.com.
- search something.
- can't display pictures.
## Screenshots

![image](https://user-images.githubusercontent.com/85724850/142012550-878b12a3-0d72-4274-8728-ec7f6b60a653.png)
## System Information

- OS: win10 
- Browser: Cent Browser 4.0.9.112  (Chromium 74.0.3729.169)
- Dark Reader Version:  4.9.42

**Comment by Gusted** [comment]
Fixed in the next release.
