### ISSUE TITLE
[Bug] Browser Theme returned to defult when deactivating Dark Reader (Firefox)

### ISSUE THREAD

**Issue by IJustWantANamePlease** [darkreader/darkreader#7396]
# Bug Report

## Bug Description
This is on Firefox, not sure if existed on other browsers. When Browser Theme is set to Custom, Dark Reader returns the theme to default light rather than the one which I created.

## Website Address
no website

## Steps To Reproduce
-Change Browser Theme to Custome
-Change theme of Firefox to whichever else than default 
-Enable Dark Reader
-Disable Dark Reader

## Expected Behavior
Theme should return to previously chosen one.

## Actual Behavior
Theme is returned to default light.

## Screenshots
![图片](https://user-images.githubusercontent.com/69347951/142019011-9a6d9c4b-e7af-4f8c-90fc-8cf20427112d.png)
This is before the process.
![图片](https://user-images.githubusercontent.com/69347951/142019148-ce1ebd2b-d61c-4aac-8979-2796ceefe9d1.png)
And this is after.

## System Information
Firefox, 

- OS: Windows 10
- Browser: Firefox 94.0.1
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Dup #2509
