### ISSUE TITLE
[Bug] Dark Reader keeps deleting my CSS additions in developer tools

### ISSUE THREAD

**Issue by arelkin** [darkreader/darkreader#7401]
This has only started recently. Has anyone else had similar problems?
Dark Reader: 4.9.42
Mac Firefox: 78.15.0esr

**Comment by Gusted** [comment]
Use the template.

**Comment by arelkin** [comment]
What do you mean by "template"? I've been adding CSS to the Dynamic Theme Editor. Is this the wrong place to add custom CSS?

**Comment by JackDjTom** [comment]
I have the same problem, @Gusted can you explain what you mean with "Use the template."?

**Comment by JackDjTom** [comment]
@arelkin With using the template he means, that you should open a new issue and select the "Bug report template" and fill in all your information.

**Comment by JackDjTom** [comment]
I opened a issue with this problem: #7510
