### ISSUE TITLE
[Bug] Darkreader breaks browser detection routines on Firefox

### ISSUE THREAD

**Issue by tbl0605** [darkreader/darkreader#7404]
# Bug Report

## Bug Description
Dark Reader creates the objet `window.chrome` on Firefox, which breaks browser detection using "duck-typing" methods.

I've recently included Dark Reader in some webpack projects (using `npm install darkreader`) but now Firefox is seen as a Chrome/Chromium browser when checking for `window.chrome`

I know I could adjust my browser detection routines to use feature detection (or user agent detection), but I still think it's a bit overkill to unconditionally create the `window.chrome` object on non-Chrome/Chromium browsers just for internal use.
Other JavaScript libraries don't do that, it pollutes the `window` object.

The culprit is following code:
https://github.com/darkreader/darkreader/blob/0edbc3f2e3f84ed37a0368f1c5445d3157a9c8f0/src/api/chrome.ts#L7

PS: Dark Reader is a great library, thank you for your great work!

## Website Address
https://stackoverflow.com/a/9851769/2332350

## Steps To Reproduce
Use the code from above stackoverflow link in Firefox in a webpack project with Dark Reader installed:
```
var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);
```

## Expected Behavior
Previous test should return `false` on Firefox, but Dark Reader breaks the test by creating a "fake" `window.chrome` object.

## Actual Behavior
Previous test returns `true` on Firefox.

## System Information

- OS: Windows 10
- Browser: Firefox 94.0.1
- Dark Reader Version: 4.9.40

**Comment by Gusted** [comment]
> Other JavaScript libraries don't do that, it pollutes the `window` object.

Other javascript libraries don't origin out of a extension. We mainly expect the code to be running on a extension-like context, whereby we stub a small subset of the chrome api into the window such that the code will just run as expected without modifying the main code that much such that it won't work on a extension anymore.

I'm not sure if we should switch to another approach as anyone would expect to just write `chrome.xxx` code within the extension without worrying too much that it breaks the API as that should be handled by the code(such as stubbing `window.chrome` that is only build with the API). Also given that the detection can be very easily be adjusted to still work.

Regards,
Gusted

**Comment by tbl0605** [comment]
Hi @Gusted,
thank for your fast answer.

I changed my detection routines to use user agent detection (like dark reader already does).
The point is that I cannot change code from my other JavaScript dependencies so I hope they don't (or won't never) use the `window.chrome` detection routine. But I'm pretty sure I've seen this somewhere recently, I have to confirm...

My bug report was mainly to bring to your attention that "maybe" there could be some bad interactions with other JavaScript libraries when they detect (and want to use) incomplete `window.chrome` object.

So why not use some dedicated object in the chrome.ts file, something like following code?

```
if (!window.chrome) {
    window.darkreaderChrome = {} as any;
}
const chrome = window.chrome || window.darkreaderChrome;
```

I had no deep look at Dark reader's code, so sorry if it's a bad advice, I don't even know if the `window.chrome || window.darkreaderChrome` test has to be repeated elsewhere ;)

Anyway, thank you for having taken your time to answer me :)

Regards,
Thierry.

**Comment by Gusted** [comment]
> I don't even know if the `window.chrome || window.darkreaderChrome` test has to be repeated elsewhere ;)

So - It is possible to do such thing, the problem would be that I cannot ensure that in the future some code could slip trough that will use the regular `chrome`  and poof the API will go error about undefined references etc.

**Comment by tbl0605** [comment]
Which brings me to another question: why should the file chrome.ts be unconditionally loaded on Firefox browsers?
Since Dark reader also relies on user agent detection, why not use same mechanism to include / exclude the loading of chrome.ts?

Or maybe give the user an alternative way to load (or refuse to load) the chrome.ts file? So he can decide by himself if he should load those Chrome "workarounds" ;)

**Comment by Gusted** [comment]
> Which brings me to another question: why should the file chrome.ts be unconditionally loaded on Firefox browsers?

It's also unconditionally loaded on Chromium browsers - the reason for the file is that we use things within the code that only a extension has access to, to avoid rewriting that code and ensure we don't mistakenly will write such code again(as people tend to forget things like that). That file simply stub/re-create the function that we are using but then in way that it's possible in a normal browser context. The name of the file `chrome.ts` is because we're using the `chrome.` namespace - which is btw supported on Firefox. It has nothing to do with the browser "chrome". It would make sense that we change the file name to something like `extension-api-stub.ts` which indicates a more general usage.



> Since Dark reader also relies on user agent detection, why not use same mechanism to include / exclude the loading of chrome.ts?

Not possible see above message.

> Or maybe give the user an alternative way to load (or refuse to load) the chrome.ts file? So he can decide by himself if he should load those Chrome "workarounds" ;)

That will just open us up to more problem, as giving users such choice whereby they would need to bring their own code will cause more troubles than good. As a lot of people(giving experience with current API) will not understand it properly even if it's clear with warnings and errors.

**Comment by tbl0605** [comment]
>  The name of the file chrome.ts is because we're using the chrome. namespace - which is btw supported on Firefox. 

@Gusted, thank you for the explanation! 

> As a lot of people(giving experience with current API) will not understand it properly even if it's clear with warnings and errors.

At least, would it be possible to put some comment/warning in the "Using Dark Reader for a website" section?
Users should be aware that an object `window.chrome` could be created after the inclusion of the Dark Reader library and that `window.chrome` is then not reliable anymore for browser detection routines.

After that, feel free to close my bug report ;)

**Comment by Gusted** [comment]
> At least, would it be possible to put some comment/warning in the "Using Dark Reader for a website" section?
> Users should be aware that an object `window.chrome` could be created after the inclusion of the Dark Reader library and that `window.chrome` is then not reliable anymore for browser detection routines.

Good suggestion!
