### ISSUE TITLE
[Broken Website] kenh14.vn

### ISSUE THREAD

**Issue by nkoc6a15** [darkreader/darkreader#7406]
# Broken Website Report

## Website Address
 kenh14.vn

## Actual Behavior
 Dark reader causing Firefox slow. To speed up, stop that addon when access kenh14.vn

## Screenshots
 
![ảnh](https://user-images.githubusercontent.com/85343481/142221670-76782b8d-3d50-40cc-9ce6-9d29d0c76fe3.png)

## System Information

- OS:  Windows 10 21h1
- Browser:  Firefox 94.0.1
- Dark Reader Version:  4.9.42

**Comment by Gusted** [comment]
Fixed in the next release.
