### ISSUE TITLE
[Bug] Module '"darkreader"' has no exported member 'isEnabled'.

### ISSUE THREAD

**Issue by suarezluis** [darkreader/darkreader#7407]
# Bug Report

## Bug Description

Getting the following error:

Module '"darkreader"' has no exported member 'isEnabled'.
seems like npm doesn't have the latest version;  "4.9.42", current installations via npm add  "4.9.40"
## System Information

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
#7316
