### ISSUE TITLE
[Bug] Can't disable on console.aws.amazon.com

### ISSUE THREAD

**Issue by gshpychka** [darkreader/darkreader#7412]
# Bug Report

## Bug Description
For some reason, I am not able to disable darkreader on console.aws.amazon.com Firefox. I believe this started happening after I enabled Firefox containers, but I am not sure.

## Website Address
console.aws.amazon.com

## Steps To Reproduce
In my case, it's this:
- Go to console.aws.amazon.com.
- Go to darkreader settings popup and try to disable the extension for this website
-->

## Expected Behavior
Dark mode is disabled for the website

## Actual Behavior
Button doesn't do anything.

## System Information

- OS: ArchLinux
- Browser: Firefox 94
- Dark Reader Version: 4.9.42

## Additional Context
This was working fine before, and I only noticed it after I installed Firefox Containers. There might not be a connection there, though.

**Comment by Gusted** [comment]
Hi @gshpychka!

Do you have by any chance `aws.amazon.com` or `amazon.com` already within your site-list? If so you're hitting a bug like #84

**Comment by gshpychka** [comment]
@Gusted yup, that was it. Thanks.
