### ISSUE TITLE
[Bug] White flash issue (video included)

### ISSUE THREAD

**Issue by hbt** [darkreader/darkreader#7415]
# Bug Report

## Bug Description

When opening a new tab, a white flash appears. 

Sometimes the white flash appears when doing a google search but it's not consistent. Reload the page again, no white flash. 

## Website Address

e.g https://hckrnews.com/

The issue occurs on multiple websites though.

## Steps To Reproduce

I've enclosed a video that uses a clean google profile (no extensions, no data)

https://www.youtube.com/watch?v=N6qHbN7_qy4

## Expected Behavior

- no white flash when loading a page or moving between tabs

## Actual Behavior

- white flash. Persistent on some websites like https://hckrnews.com/ and inconsistent on others.

## Screenshots

https://www.youtube.com/watch?v=N6qHbN7_qy4

## System Information

- OS:  Linux
- Browser:  Chrome 96
- Dark Reader Version:   4.9.42

## Additional Context

I managed to fix it on some sites by having another extension inject CSS at document_start AND lower the brightness to 0 until the page is loaded. However, that also fails sometimes.

Would appreciate any guidance. I'm open to writing the code just not sure if the issue is dark reader or the latest chrome white flash regression. 

Thank you.

**Comment by Gusted** [comment]
Hi @hbt!

This might be related to due being on Linux, if you could check something for me - If you open up the chrome devtools(ctrl + shift + i) and go to Console tab. What's the output of `matchMedia('(prefers-color-scheme: dark)').matches`?

Regards,
Gusted

**Comment by hbt** [comment]
@Gusted 

Thank you so much for the quick reply. 

`matchMedia('(prefers-color-scheme: dark)').matches`
returns false 

But your reply helped me search for previous issues and apparently there is a fallback code activated based on that media query. 
https://github.com/darkreader/darkreader/issues/3811#issuecomment-711304235

I have ubuntu 18.04 Linux GTK+ dark theme but it's clearly not being recognized. 
![Screenshot from 2021-11-19 06-24-33](https://user-images.githubusercontent.com/369353/142615141-a207d284-d626-4b5a-9e67-8b00e3c4de5f.png)

I will google later for how to fix ubuntu to tell google chrome I want dark themes but for now, 
I modified the code to always use the fallback and the white flash is gone. 

Thank you so much.

Feel free to close this.

**Comment by Gusted** [comment]
You can follow, https://bugs.chromium.org/p/chromium/issues/detail?id=998903 ;)

Closing.

**Comment by mattalexx** [comment]
Thanks Gusted, this was useful.

**Comment by mattalexx** [comment]
I run Chromium, and that JS was returning `false` for me too.

I was able to force dark mode by passing these parameters to the browser:

```
# ~/.config/chromium-flags.conf
--force-dark-mode
--enable-features=WebUIDarkMode
```

[Source](https://wiki.archlinux.org/title/chromium#Dark_mode)

I use Arch but the fix is should work for other distros as well.
