### ISSUE TITLE
[Bug] Weird colour changes

### ISSUE THREAD

**Issue by AliyahMillan** [darkreader/darkreader#7423]
# Broken Website Report
## Website Address
https://www.duolingo.com/learn

## Steps To Reproduce
- Go to https://www.duolingo.com/learn.
- Scroll through previous completed levels.
- Notice that on levels where Legendary challenges are in progress, it does not show the expected purple colour.
--------------------------------------
- Go to https://www.duolingo.com/learn.
- Select any level.
- Notice that when submitting answers, the colour scheme of characters will sometimes change. Most often, black hair and eyes are replaced with a grey color.
## Expected Behavior
- It's expected that a colour, any colour really, is shown in the progress circle.
---------------------------------
- And the colour that characters are given aren't supposed to change....

## Actual Behavior
The progress circle looks black and as if there is no progress that was made.
------------------------------
When submitting answers, the colour scheme of characters will sometimes change. Most often, black hair and eyes are replaced with a grey color.

## Screenshots

Light mode:
![image](https://user-images.githubusercontent.com/60375020/142681399-530f8176-a474-4376-9ee3-d52558cf59bf.png)
Dark mode: 
![image](https://user-images.githubusercontent.com/60375020/142681333-31101e83-f2e5-4021-a613-e23b500531fe.png)
---------------------------
Light mode (before then after submitting my answer):
![image](https://user-images.githubusercontent.com/60375020/142681635-9b2d546d-42ab-4b76-8f28-9e02dd88df67.png)
![image](https://user-images.githubusercontent.com/60375020/142681702-bb1d437c-fbc5-419a-aa86-95d58fefe44b.png)
Dark mode (before then after submitting my answer):
![image](https://user-images.githubusercontent.com/60375020/142682024-4bd48465-9fca-473f-8601-0ee6635b44c7.png)
![image](https://user-images.githubusercontent.com/60375020/142682869-3a8c6adf-56d5-465a-af92-9a412661b410.png)

## System Information

- OS: Windows
- Browser: Chrome Version 96.0.4664.45
- Dark Reader Version: 4.9.42

## Additional Context
The green progress bar also is a bit off when completing levels because it'll show another green bar inside the bigger bar, but it's not as much of an issue.
![image](https://user-images.githubusercontent.com/60375020/142687401-b76d5383-ad38-43f3-8830-096b3aa0f30b.png)

**Comment by NguyenASang** [comment]
@Gusted Take a look at this issue ;)
