### ISSUE TITLE
Images dark on arstechnica.com on Dynamic

### ISSUE THREAD

**Issue by dheraud** [darkreader/darkreader#743]
New to this extension, but so far the only issue I am having is images are too dark on https://arstechnica.com/ on the Dynamic filter. It works great on other sites like CNN.com, slashdot.org and others, but for some reason not on arstechnica.com.

![capture](https://user-images.githubusercontent.com/26801407/46034359-6d0a7d00-c0ce-11e8-8cc5-d45d9d3b44d1.PNG)

**Comment by krupenja** [comment]
This is a duplicate of #399
