### ISSUE TITLE
[Bug] site flashes on subsequent page load

### ISSUE THREAD

**Issue by basings** [darkreader/darkreader#7438]
# Bug Report

## Bug Description

The first load of a page is fine. Each subsequent load leads to a white flash because the page is loaded in white first and then changes to dark. On https://www.wikipedia.org only the search box flashes. 

## Website Address
e.g. wikipedia.org

## Steps To Reproduce

- go to https://en.wikipedia.org/wiki/Main_Page
- reload the page

## Expected Behavior

- no flashing

## Actual Behavior

- flashing

## System Information

- OS: Linux
- Browser: Firefox v94
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Hi @basings!

This might be related to due being on Linux, if you could check something for me - If you open up the chrome devtools(ctrl + shift + i) and go to Console tab. What's the output of `matchMedia('(prefers-color-scheme: dark)').matches`?

Regards,
Gusted

**Comment by basings** [comment]
It returns `false`

```
>> matchMedia('(prefers-color-scheme: dark)').matches
<- false
```

The default dark theme is enabled (if that's somehow related).

**Comment by Gusted** [comment]
> It returns `false`

That's a issue, as it the "white flashes killer" is only enabled when that returns `true`. You can go into `about:config` and set the `layout.css.prefers-color-scheme.content-override` pref to `0`. That should force to use a dark color scheme.

**Comment by basings** [comment]
Thx.

It works on the default profile now, it doesn't work with a hardened profile (rfp).

If `privacy.resistFingerprinting` is set to true, it flashes.
If is set to false, it works perfectly fine.

**Comment by Gusted** [comment]
> If `privacy.resistFingerprinting` is set to true, it flashes.
> If is set to false, it works perfectly fine.

There's unfortunately no workaround for that.

**Comment by basings** [comment]
thank you!

**Comment by drikqlis** [comment]
@Gusted can't we get an option to enable this "white flashes killer" regardless of the prefers-color-scheme setting to allow us to use privacy.resistFingerprinting?
