### ISSUE TITLE
[Bug] cannot display pictures in some website

### ISSUE THREAD

**Issue by rayd1oo** [darkreader/darkreader#7444]
# Bug Report

## Bug Description
it won't display images on search result page of baidu.com

## Website Address
www.baidu.com

## Steps To Reproduce

- Go to baidu.com.
- search anything on baidu
- images on the left side would not display

## Expected Behavior
image display normally when dark reader is switched off

![2](https://user-images.githubusercontent.com/20364973/142795178-10104e0f-633b-4d7d-b114-b9457db3cf3b.png)
## Actual Behavior

images on the left side not display

## Screenshots

![1](https://user-images.githubusercontent.com/20364973/142795167-314455ac-3ae7-4508-bae8-fc62196778ca.png)

## System Information

- OS: Windows 11
- Browser: Chrome 96
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Fixed in the next release.
