### ISSUE TITLE
[Broken Website] Usernames have a white box around them in the Inbox section

### ISSUE THREAD

**Issue by chuchigod** [darkreader/darkreader#7445]
# Broken Website Report

## Website Address
https://www.instagram.com/direct/inbox/
https://www.instagram.com/p/CWkRtsPNeIP/

## Steps To Reproduce
Go to any direct message on instagram.com or a post from an account you follow.

## Expected Behavior
The White Box that appears around usernames and the "following" button that should not appear, I tried removing it manually but couldn't. 

## Actual Behavior
Every username has a white box around it in Instagram's Inbox section and the "following" button also has the same white box around it (In Dynamic mode, It does not happen in Filter/Filter+ mode)

## Screenshots
![image](https://user-images.githubusercontent.com/79755937/142807004-0305abe1-85bf-436e-b890-1c49c725774c.png)
![image](https://user-images.githubusercontent.com/79755937/142808319-db79e100-9fc6-4f1a-a8c7-e4f74f631130.png)

## System Information
Though I'm reporting the issue from edge this issue persists in all the browsers I tried i.e. Chrome, Edge and Firefox.

- OS: Windows 11 Version 21H2 (OS Build 22000.318)
- Browser: Microsoft Edge 96.0.1054.29 (Official build) (64-bit)
- Dark Reader Version: 4.9.39

## Additional Context
This issue only exists in the Dynamic mode as there were no white boxes around the usernames and the "following" button in other modes.

**Comment by chuchigod** [comment]
I saw a similar post about the white cox around usernames here: https://github.com/darkreader/darkreader/issues/5585
However, the boxes now don't appear anywhere else on the website except for the direct messages section

**Comment by NguyenASang** [comment]
That happened with some websites, for example:

![image](https://user-images.githubusercontent.com/87893636/142820190-d656bd51-9ce1-442e-9570-6ae5f57f0a3d.png)
 
The border around the box is sometimes too bright.

**Comment by chuchigod** [comment]
> That happened with some websites, for example:
> 
> ![image](https://user-images.githubusercontent.com/87893636/142820190-d656bd51-9ce1-442e-9570-6ae5f57f0a3d.png)
> 
> The border around the box is sometimes too bright.

but this issue was apparently fixed https://github.com/darkreader/darkreader/issues/5585 
and plus the ones i mentioned dont really have a visible border in light mode...
so will this be fixed??

**Comment by Gusted** [comment]
#7446 fixes this issue as well as the translate.google.com one.

**Comment by NguyenASang** [comment]
Oh, okay ;))
