### ISSUE TITLE
Auto toggle based on macOS Mojave Dark Mode status

### ISSUE THREAD

**Issue by kristofferR** [darkreader/darkreader#745]
As you might know, the newly released macOS Mojave has a great Dark Mode implementation where all supported apps automatically change color theme to Dark when Dark Mode is toggled.

It would be great if Dark Reader could be compatible with Dark Mode and automatically be toggled based on the Dark Mode status.

**Comment by ttuygun** [comment]
It's based on Cocoa API. How can Dark Reader access this API from Chome's API?

**Comment by alexanderby** [comment]
Currently I'm working on Safari version, it will be possible there.

**Comment by nelsonjchen** [comment]
[Google is working on a native Dark Mode version of the default theme that honors Mojave's settings. If anyone wants to follow the work and/or discussion like about extension APIs and whatnot, here's the link.](https://bugs.chromium.org/p/chromium/issues/detail?id=850098)

**Comment by hsiktas** [comment]
Maybe Dark Reader could tell websites via `prefers-color-scheme` that we want the site's own dark mode? More info: https://www.jeffgeerling.com/blog/2018/jeff-geerlingcom-now-supports-dark-mode-macos-1014

**Comment by alexanderby** [comment]
@hsiktas This article is about Safari browser, the extension supports it on Safari. Time Settings are about to be published, maybe it could be a temporary workaround for other browsers.

**Comment by maxnordlund** [comment]
I believe this can be done reliably in Firefox as well. When the feature was first implemented, they decided to use [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and [listen for a -moz prefixed media query](https://bugzilla.mozilla.org/show_bug.cgi?id=1466335#c4). The name was changed to [-moz-system-dark-theme](https://bugzilla.mozilla.org/show_bug.cgi?id=1466335#c9), but the idea is the same.

Dark Reader should be able to listen for the same thing and change accordingly. See the links above, and the [patch for `LightweightThemeManager`](https://bugzilla.mozilla.org/attachment.cgi?id=8988763&action=diff#a/toolkit/mozapps/extensions/LightweightThemeManager.jsm_sec6) for inspiration.

**Comment by maxxxlarsson** [comment]
Didn't see any mention of this applying to Windows 10 dark/light theme as well. But I wish that Dark Reader would change according to the OS theme, as Edge and Chrome themselves already are doing.

**Comment by aaronth07** [comment]
I do as well, or at least have an option to automatically toggle on/off based on times you set.

**Comment by feross** [comment]
This npm package (disclosure: it's mine) makes it trivial to detect dark mode changes: https://www.npmjs.com/package/color-scheme-change

```js
import colorSchemeChange from 'color-scheme-change'
 
colorSchemeChange(colorScheme => {
  console.log(`Entering ${colorScheme} mode`)
  // Prints either "Entering dark mode" or "Entering light mode"
})
```

I just used this in a Chrome extension and it worked perfectly. The detection API is not just for websites. :)

**Comment by ColCh** [comment]
hey @feross do it fires event for extension `window` object? I don't know why, but it's not working for extension's own `window`, but it works for usual webpage.

It seems that Chrome turns off some media query events for "invisible" documents such extension background page

**Comment by kristofferR** [comment]
@ColCh : I think that's because of this Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=968651

**Comment by ColCh** [comment]
it seems you're right

let's wait for fix then...

**Comment by surenzxx** [comment]
Any update on this for FIrefox?

**Comment by anohren** [comment]
I would never have found the option to enable this if I hadn't watched the gif in the linked PR. I came to github just to see if anyone had suggested it. 

Those three dots are pretty invisible, and don't look like a button even if you notice them. How about enabling this by default?

Or you could just relocate those hard to find options to the More tab, which was the first place I looked.

**Comment by ttuygun** [comment]
> I came here to see if anyone had suggested this, and I would never have found the option to enable it if I hadn't watched the gif in the linked PR.
> 
> Those three dots are pretty invisible, and don't look like a button even if you notice them. How about enabling this by default?
> 
> Or you could just relocate those hard to find options to the More tab, which was the first place I looked.

Totally agree.

**Comment by mpereira** [comment]
I would also have never found the three dots. Even after reading @anohren's comment, I still had to watch the gif to see it.

I'm sure more people will end up in this PR while investigating if Darkreader supports this, so I'll add a screenshot:
![Screen Shot 2019-12-10 at 15 22 49](https://user-images.githubusercontent.com/112426/70537666-208b5000-1b61-11ea-91af-6cf417d42e6a.png)

Is there an issue or PR for improving the UX of configuring this really important setting?

**Comment by jasontk19** [comment]
👍 with the above... came here to suggest => found this thread => had no idea the vertical ellipses menu was there (so small and dark 😉)

Would love to see a UI change to make this menu more obvious or, to use system color scheme enabled by default!

**Comment by LazaroFilm** [comment]
> I'm sure more people will end up in this PR while investigating if Darkreader supports this, so I'll add a screenshot:
Yep, that's me! I was just about to delete the extension until I landed on this convo and scrolled all the way dow. This crucial setting is wayyy to hidden. It should be Toggle extension: [On] [Auto] [Off] then when you click on the [Auto] you land on that drop down menu asking which automatic option you want.

**Comment by Gusted** [comment]
Oh hello 👋🏽 

You should do the following to get the new UI
```
To activate the new user interface do the following:

Click Dark Reader icon.
Click Dev tools (in the bottom-right corner).
Click Preview new design.
```

Trough that you can see that the auto mode is more visibile along side On/Off and the automation menu has been moved to Settings -> Automation
The new UI is still in beta so we are happy to hear feedback about it :D
About the UX theirs a new release hopefull coming soon that enables round Buttons
Example:
![](https://i.imgur.com/gtJk6iA.png)
![](https://i.imgur.com/0hgKl7I.png)
![](https://i.imgur.com/Fv8Is27.png)

Regards,
Gusted

**Comment by anohren** [comment]
> The new UI is still in beta so we are happy to hear feedback about it :D

> That's our new design it won't change.

Just don't expect anything to change because of it.

**Comment by Gusted** [comment]
> > The new UI is still in beta so we are happy to hear feedback about it :D
> 
> > That's our new design it won't change.
> 
> Just don't expect anything to change because of it.

Thank you for taking it complety out of context.

We made a choice to have [this](https://i.imgur.com/bglvZVO.png) design choice with the Auto button, I called it personally a MultiSwitch because the switch has more than 2 options(That was my logic when I needed a name for it). So you can override the Automation mode at any time what was in that issue the whole purpose of overriding it and you described that scenario as well. You expected that with the button you could choose Auto mode and when necessary you can click on ON/OFF while Auto was still selected but simply overriden. That's more a choice we didn't made.

**Comment by anohren** [comment]
It's in context, it's just from another thread which is about a particular aspect of the new design. The switch is part of the new UI, but feedback about it was not happily received; it was never met with a discussion, but with a dismissal. That's the opposite of considering feedback.  I'm just saving the next persons time who might also be prepared to spend time trying to make themselves understood, only to be told that there will be no discussion about the aspect of the new design that they were interested in, because it's already set in stone. 

The decision is made -- which is fine -- but I find that detail relevant when leaving feedback, so I'm pointing it out.

**Comment by Gusted** [comment]
It was received might with some passive agressive tone, because this design was carefully made to make the Auto button like this. I mean other components like Automation that it could be changed or added a feature to make it better to select time or something in that direction.

**Comment by Devo7v** [comment]
> 
> 
> Any update on this for Firefox?

I don't know if I'm doing something wrong, but I cannot get the Auto setting to work in Firefox v86.0 under Windows 10.  On and off work as expected changing the themes of both websites and Firefox itself, but Auto seems to function exactly the same as On.  I have the option selected to "Use system color scheme", but it does not change.  When using the time option or location option it works as expected.  Is this a limitation of Dark Reader, Firefox, or Windows 10?
