### ISSUE TITLE
[Feature Request] DarkReader should respect `prefer-color-scheme`

### ISSUE THREAD

**Issue by darkRaspberry** [darkreader/darkreader#7452]
# Feature Request

## Is this feature request related to a problem?
Website like web.whatsApp.com, GitHub etc. support `prefer-color-scheme`. In those case running darkReader generally doesn't do much. And may arise contrast issue which cause hard to read text colors.

## Additional Context
If darkReader can respect those then It would be hella generous.
For Starters:
- It can just check if `prefer-color-scheme: dark` is at dark And if it is then don't change anything as developer has carefully set everything. And selected colors of text and other elements And give a force override option.
- [For Future] It can just change the value of `prefer-color-scheme: light` to dark. 

As more and more sites have these css thing these days. Then It will just cut most of the issues and give you more room and space to work on other things

**Comment by sheriffderek** [comment]
@darkRaspberry - can you point me to where this is addressed?

**Comment by darkRaspberry** [comment]
I experienced it supports native colour mode for gnome Linux.
