### ISSUE TITLE
Use dynamic + static

### ISSUE THREAD

**Issue by linvi** [darkreader/darkreader#746]
I would like to change the style/appearance of a website but at the same type keep the default `dynamic` rendering of darkreader.

`static` does at the moment allow me to do that so I have to use an additional extension.

Cheers,
Linvi

**Comment by Gusted** [comment]
#3120

**Comment by Gusted** [comment]
Hello!

In the next update of Dark Reader 4.9.16 you can export it to CSS File :tada: 
This can trough the following steps:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Click on settings in the popup
- Click on Manage Settings
- Click on Export Dynamic Theme

Regards,
Gusted
