### ISSUE TITLE
Anchors, visited and unvisited have same color

### ISSUE THREAD

**Issue by ausbeck** [darkreader/darkreader#7460]
Web page has no specific anchor color, relies on user-agent defaults. Dark reader adds rule;

a {
    color: #3391ff;
}

which overrides the default user agent rule:

*|*:visited {
    color: rgb(240, 32, 240);
}

Therefore, all links, visited and unvisited, have the unvisited color. Dark Reader should add an a:visited rule in this case.

**Comment by Gusted** [comment]
Please use the bug report next time, but I will save you the time this time and say that this isn't possible, as sites like Github explicitly override the `a`'s color so that their won't be visited color shown. So we cannot unconditionally add such CSS Rules, they are risky and break many websites.
