### ISSUE TITLE
[Broken Website] Google Finance (www.google.com/finance) charts are too dark to see

### ISSUE THREAD

**Issue by parikramatic** [darkreader/darkreader#7461]
The charts on the Google Finance website are really hard to read and lose their red/green hue, which renders the extension useless for this website. Which is a shame because I use it across the web :)

Example: 
![image](https://user-images.githubusercontent.com/14193524/143191074-5c1047ac-05b4-4c44-a56e-74f5dc504853.png)

**Comment by Gusted** [comment]
Please use the bug template which provides the information that someone needs to properly understand the bug.
