### ISSUE TITLE
[Feature Request] Disabled by default on all websites, so I can manually enable it on the few websites I want

### ISSUE THREAD

**Issue by kmob2** [darkreader/darkreader#7462]
# Feature Request
Would it be possible to implement a feature so that the extension is disabled on all websites by default, and I can add each website manually? This would be such a time saver.

I don't like that the extension is enabled on all websites by default. I only require a dark theme on about 5 of the 200 websites I visit per day. Additonally a lot of websites already have a dark theme and the extension overrides the original dark theme. I spend more time disabling the dark theme on websites than I would spend enabling it on the few websites where I really need it.

Maybe this feature is already part of the extension, unfortunately, I couldn't find it.

**Comment by Gusted** [comment]
> Maybe this feature is already part of the extension, unfortunately, I couldn't find it.

It is already, you can enable it by the following steps:

- Open up the UI
- Go to the Site List tab.
- Select the `Invert listed only` option.

Regards,
Gusted
