### ISSUE TITLE
IP Address in Site list can apply to more than just that single IP

### ISSUE THREAD

**Issue by Ryoken0D** [darkreader/darkreader#747]
I've noticed an issue (I think).
In my Site List to not invert, I have a local IP address. 172.16.16.1 (Cause it doesn't look good on my router). However other IP's that start with 172.16.16.1 also get not inverted (Like 172.16.16.10). I've tried adding things like a trailing / to the original IP but no change.

**Comment by rolagg** [comment]
What about adding `$` symbol?

**Comment by Ryoken0D** [comment]
You mean add 172.16.16.1$ (or 172.16.16.1/$) to my sitelist? Nope doesn't fix it.

**Comment by Gusted** [comment]
172.16.16.1$

That should do the trick.

**Comment by Gusted** [comment]
@Ryoken0D With the latest version of darkreader
