### ISSUE TITLE
[Edge cannot display the Windows Style Overlay Scrollbar]

### ISSUE THREAD

**Issue by qier19** [darkreader/darkreader#7475]
# Bug Report

## Bug Description
I just want to know why when I open this extension, Edge cannot display the Windows Style Overlay Scrollbar, which is really a bad experience.

## Website Address
Except pdf

## Steps To Reproduce
- open this extension
- Windows Style Scrollbar is changed in old version

## Expected Behavior
I just want Windows Style Scrollbar will be not changed by this extension

## Actual Behavior
Edge cannot display the Windows Style Overlay Scrollbar.

## Screenshots
<img width="770" alt="image" src="https://user-images.githubusercontent.com/95011132/143557381-5edd3da9-aa0c-4a7d-8b6e-2b1a992766c7.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/95011132/143557599-38a57109-11e5-47ba-974b-d53d8c42b2a4.png">

## System Information

- OS: Windows
- Browser: Edge 96
- Dark Reader Version: 4.9.39

## Additional Context
This issue can change all of scrollbars in Edge.

**Comment by Gusted** [comment]
Please check https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151
