### ISSUE TITLE
General Enhancements requested for Jira

### ISSUE THREAD

**Issue by ngurney** [darkreader/darkreader#748]
Hello all! Thanks for such a great product. Below I have outlined some common issues I have found in Jira. I am hoping someone can jump in and fix these. 

## Jira Issues
1. When viewing an issue in split mode from the backlog, this bar stays white. 
https://cl.ly/0ee40108bf4d

2. Notifications do not convert well at all into dark mode
https://cl.ly/96a10ef7a3e5

3. Notification details are very dificult to read when clicking on a comment inline with the notifications. Sorry for the difficult screenshot, trying to keep work information private.
https://cl.ly/54feb197a8ea

4. When viewing comments in a modal pop up of an issue, the comment box looks like this: 
https://cl.ly/711927a2aa73

5. Ocassionaly, but not always, the page loads and has several white areas. A refresh usually fixes it. 
https://cl.ly/3be80736d08a

Feel free to reach out if you have any follow up quesitons!

**Comment by alexanderby** [comment]
I'm seeing issues like this on bitbucket.org, I will have a look.

**Comment by ngurney** [comment]
Thanks so much for the update, @alexanderby! It is the only tool I'm in regularly that causes me to turn the extension off 😄

**Comment by ax-nathan** [comment]
@alexanderby I can echo what @ngurney is saying...love DarkReader...wish it worked better with Jira. Happy to assist with testing in a paid Jira account if that is helpful...

**Comment by erikjara** [comment]
Same problem here!
And yes, Jira is using dynamics class names so I can't create a invert rule 😞

**Comment by ScottBeeson** [comment]
I discovered that Atlassian products seem to behave much better in Filter+ mode.  It's not as pretty as Dynamic, but it seems to be reliable.

**Comment by jzielke84** [comment]
Problem is that some sites work on Filter+ while most work fine using dynamic mode. Maybe there's some way to implement an "override" mechanism like the whitelist already does for filter modes so we can switch special sites by rules.

**Comment by stdcerr** [comment]
I can just echo the others, DarkReader is great but I've unfortunately got to turn it off for JIRA - and this is with the Chrome extension (on Vivaldi) :-1: Thanks for looking into fixing this!

**Comment by Gusted** [comment]
Jira is a enterprise product and Demo's are only for businesses who are intrested and scheduld as well.
If someone who knows dark reader works and CSS Fixes and have access to this should be easy fixed, but unfortunate this is not the situation. However it seems I came to some intrested conclusion like it's style was changing and should be fixed with #3004 However that possible contained a bug, that should be fixed with [this build](https://github.com/darkreader/darkreader/issues/3128#issuecomment-660090532). I'm not sure what Jira issue is, as it's enterprise and locked far far away.

**Comment by Gusted** [comment]
4.9.16 just released with the good fixes(hopefully). Firefox will be released soon.
If their are still problems make sure to adress it!
