### ISSUE TITLE
[Broken Website] https://elm-lang.org/

### ISSUE THREAD

**Issue by astrale-sharp** [darkreader/darkreader#7480]
# Broken Website Report

## Website Address

https://elm-lang.org/

## Steps To Reproduce

- Go to [https://elm-lang.org/](https://elm-lang.org/)
- Click on the blue buttons below quotes.
- Notice that when clicking the button, it does not change the quote.
- Also Notice that the quotes should change on their own and it is not happening with dark reader enabled
## Expected Behavior

I expected the animations and the button clicks to show new quotes.
## Actual Behavior

The quotes do not change.
## System Information

- OS: 
```bash
❯ screenfetch

 ██████████████████  ████████     astrale@ultimatestarxXx
 ██████████████████  ████████     OS: Manjaro 21.2.0 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.79-1-MANJARO
 ██████████████████  ████████     Uptime: 3h 33m
 ████████            ████████     Packages: 1404
 ████████  ████████  ████████     Shell: fish 3.3.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.88.0 / Plasma 5.23.3
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breath2
 ████████  ████████  ████████     Disk: 316G / 361G (93%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2.9GHz
 ████████  ████████  ████████     GPU: AMD RENOIR (DRM 3.40.0, 5.10.79-1-MANJARO, LLVM 13.0.0)
                                  RAM: 3472MiB / 15463MiB

```
- Browser: 
```bash
❯ firefox --version
Mozilla Firefox 94.0.2
```
- Dark Reader Version: 
4.9.42
## Additional Context

A few site built with elm aren't working properly (broken links, "events" not happening) another example is [https://lamdera.com/](https://lamdera.com/)

**Comment by Gusted** [comment]
This is a bit of a weird issue as this isn't quickly fix-able 1, 2, 3... Luckily the source code of the site is open(and a simple fix can be made), but it seems like that they don't really get to PR's and that would mean that it won't be really fixed.

**Comment by lenntil** [comment]
### Reference
- Runtime errors caused by Chrome extensions - Request Feedback - Elm
https://discourse.elm-lang.org/t/runtime-errors-caused-by-chrome-extensions/4381

**Comment by astrale-sharp** [comment]
I mean this probably shouldn't be closed as completed then right?

**Comment by lenntil** [comment]
It shoulnd't be closed for now.

A contributor of Elm said:
> Unfortunately not a heap that can be done to improve this, Lamdera already applies some patches to improve the situation, but I think a proper solution won't happen until this is resolved in vdom module directly or we get some community alternative.
