### ISSUE TITLE
[Broken Website] Trouble handling yellow/orange background colors (e.g. keepachangelog.com)

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#7487]
# Broken Website Report

## Website Address
https://keepachangelog.com/en/1.0.0/

## Steps To Reproduce
- Install Dark Reader and set it to use Dynamic dark mode.
- Go to https://keepachangelog.com/en/1.0.0/
- Notice that area with yellow background is unreadable.

## Expected Behavior
All areas readable.

## Actual Behavior
Area with yellow background unreadable.

## System Information
- OS: Windows
- Browser: Firefox 94.0.2
- Dark Reader Version: 4.9.42

## Additional Context
Although this issue specifies a single site, I've noticed that Dark Reader struggles to handle background colors that are in the yellow and orange families.  This is true when colors in those families are used for the page background or for individual elements such as button backgrounds.  Is there a way that Dark Reader's Dynamic mode could detect colors in those families and darken the background of the page/element more?

**Comment by Gusted** [comment]
@alexanderby I think this is a pretty clear case of when the current color modifier is failing to correctly handle these kind of colors in this spectrum. Could you have look please?

**Comment by Gitoffthelawn** [comment]
Another good example can be seen on https://sourceforge.net

The white on bright orange toolbar at the top of the page is hard to read.

One of the challenges, in general, of yellow/orange hues is that they quickly turn to brown as they darken.  Of course, light on brown is better than light on light.

**Comment by Gitoffthelawn** [comment]
Here is another example, on an important website: https://hesperian.org

Shoutout to @magnus-ISU for making me aware of this wonderful organization.

**Comment by mikob** [comment]
related https://github.com/darkreader/darkreader/discussions/7307

**Comment by Gitoffthelawn** [comment]
Here's another good example:

https://www.urbandictionary.com/define.php?term=Programmer

On just about every page, there will be a section with bright white on bright yellow text.

**Comment by Gusted** [comment]
@Gitoffthelawn Could you take a look at: https://github.com/darkreader/darkreader/pull/8218 to see if this fixes the issue?
