### ISSUE TITLE
Stopped working on Firefox this morning

### ISSUE THREAD

**Issue by BFoor** [darkreader/darkreader#749]
Been happily using DarkReader for a while now on both Chrome & Firefox. Noticed that it stopped working on Firefox this morning, after it was already working for specific sites/pages I was on. I cleared cache & restarted Firefox, and it is still not working. I'm using FF version 62.0.3 & not sure what the next steps are for a fix.

**Comment by alexanderby** [comment]
Glad to here the problem is resolved, here you can read more about Site List https://darkreader.org/help/en/#site-list
