### ISSUE TITLE
[Broken Website] Darkreader breaks Baidu Translator

### ISSUE THREAD

**Issue by TheCGDF** [darkreader/darkreader#7496]
# Bug Report

## Bug Description
Darkreader causes Baidu Translator unable to use, and hide some elements of its web page.

## Website Address

https://fanyi.baidu.com/#en/zh/

## Steps To Reproduce

- Enable darkreader
- Open https://fanyi.baidu.com/#en/zh/
- Type some words into the text field
- Click "翻译"

## Expected Behavior

Translation should be shown on the right.

## Actual Behavior

Just nothing happen. (And many html elements are disappeared.)

## Screenshots

![vivaldi_4b7xvXzCVe](https://user-images.githubusercontent.com/17256673/143796120-7f56cdc5-4c81-4663-9d98-e096b168bf53.jpg)

![vivaldi_2zomWjjNi5](https://user-images.githubusercontent.com/17256673/143796596-80f70053-aee1-4700-aa10-b628fa119ee8.jpg)

## System Information

- OS:  Windows [Version 10.0.19042.1320
- Browser: Vivaldi | 4.3.2439.65 (Stable channel) (64-bit) (Chrome/94.0.4606.114)
- Dark Reader Version: 4.9.42

## Additional Context

Darkreader works well with Baidu Translator in the past, I'm not sure which side broke.

**Comment by TheCGDF** [comment]
Sorry I selected wrong label, but I'm unable to change it.

**Comment by Gusted** [comment]
Underlying issue: #7302
