### ISSUE TITLE
[Bug] Dev Tools forget CSS customizations after browser restart

### ISSUE THREAD

**Issue by paux** [darkreader/darkreader#7498]
# Bug Report

## Bug Description
Since recently, the Dev Tools of Dark Reader forget my CSS customizations after every browser restart. This is the case on two different machines: On Windows, I have configured Chrome to delete all cookies after closing it, but on Ubuntu, I haven't configured it this way. Both instances however show the same behavior.

## Steps To Reproduce
1. Open the Dev Tools of Dark Reader
2. Add custom CSS into the "CSS" section in the text area and click Apply.
3. The custom CSS is applied on webpages
4. Shut down Chrome
5. Start Chrome again
6. The CSS section in Dev Tools is reset to the default

## Expected Behavior
- The customized CSS code is retained between Chrome sessions.

## Actual Behavior
- The CSS code is reset to default after every Chrome restart.

## System Information

- OS: Windows 10 / Ubuntu 21.10
- Browser: 96.0.4664.45 (Official Build) (64-bit)
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Dup #7277
