### ISSUE TITLE
[Broken Website] Would disable some icon action

### ISSUE THREAD

**Issue by eromoe** [darkreader/darkreader#7499]
site: https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&ch=&tn=baidu&bar=&wd=dark&oq=life&rsv_pq=d84b328a000ad58c&rsv_t=73caDzYMMTJdyY%2B3%2Foc28vInA2X6sXmmtihdPyI3ypDEm3dpBrUI5x0urDQ&rqlang=cn

Can't click the icon button after enabled Darkreader,  it cost my some time to dig it out.

![image](https://user-images.githubusercontent.com/3938751/143865487-f3aa8e04-b68d-4e22-9df2-1f57937f7c17.png)

**Comment by Gusted** [comment]
see #7302

**Comment by eromoe** [comment]
@Gusted That pr was closed 21days ago. I don't understand, this can reproduce for now .

**Comment by Gusted** [comment]
> @Gusted That pr was closed 21days ago. I don't understand, this can reproduce for now .

Next release will have the fix.
