### ISSUE TITLE
GitLab.com does not retain inverted colors after hard-refresh

### ISSUE THREAD

**Issue by kfkitsune** [darkreader/darkreader#750]
Summary: A hard-refresh on a GitLab.com repository (such as in file view or issue view) does not properly re-apply the inverted dynamic color scheme, however a soft refresh does maintain the inverted colors.

Steps to Reproduce:
1) Visit https://gitlab.com/gitlab-org/gitlab-ce with either _Not invert listed_ selected, or add the site to _Invert only listed_. At this point, the site should look like the upper half of the attached screenshot, below.
2) Hard-refresh the page (Ctrl+Shift+R), and the site should now look like the bottom of the screenshot. Note that a few items correctly retain the inverted colors. On the screenshot, the scrollbars and the code-use bar maintained the inverted colors, yet the main viewport is as white as snow.

Current Results:
The page does not maintain a fully inverted state, or have it otherwise reapplied after a hard refresh.

Expected Result:
The inverted color scheme should be fully applied after a hard refresh, especially considering that some portions of the page have been affected by the color inversion rules.

Environment:
- Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)
- Dark Reader 4.6.8

Screenshot:
Top portion is after a load to get the dynamic inversion rules to load. Bottom portion is after a hard refresh.
![dr-hardrefresh](https://user-images.githubusercontent.com/19718911/46444971-7b960b80-c742-11e8-83ba-941ed674a96a.PNG)

PS: After writing the above I've had even soft-refreshes (Ctrl+R or the Refresh button on the Address bar) fail to fully reapply the full inversion rules, but the one constant is that the scrollbars and the code use bar always show the inverted colors, while the main viewport does not and remains very white.

**Comment by SilverWolf32** [comment]
This seems to only happen in Chrome. I'm not getting the issue in Firefox.

**Comment by deathtrip** [comment]
Also having problems with GitLab.
When using dynamic theme engine, the page has it's normal white colors, except the scrollbar.
Toggling the site on and off, inverts the colors, until i change the page.

**Comment by bwobst** [comment]
This only happens on `gitlab.com` for me. My self-hosted Gitlab site maintains the dark theme.

**Comment by kfkitsune** [comment]
After a couple of days of testing this again in Chrome on ``GitLab.com``, it _seems_ as if this is fixed (I can't get the issue to replicate despite navigating through the site, or hard/soft refreshing). I am going to go ahead and close the issue for now.

Current environment is Chrome ``Version 69.0.3497.100 (Official Build) (64-bit)``, Dark Reader ``4.6.9``.
