### ISSUE TITLE
[Bug] Does not respect Windows system colour scheme in firefox

### ISSUE THREAD

**Issue by androidghosh** [darkreader/darkreader#7507]
# Bug Report

## Bug Description
Dark Reader can not detect system-wide dark mode on Firefox. See here, [Image](https://i.imgur.com/iOsact1.png)
I tried refreshing, restarting. It just doesn't turn on. It works fine on chromium though.
One thing that I should mention, I have **privacy.resistFingerprinting= true** in about:config.

## Website Address
All

## Steps To Reproduce
-turn on use system colour scheme in dark reader
-turn on dark mode in windows 10
-open any website
-open dark reader extension, it hasn't automatically turned on dark mode. It's in off mode.

## Expected Behavior
turn on automatically with windows 10 dark mode

## Actual Behavior
dark reader is still on "off" mode

## Screenshots
![image](https://user-images.githubusercontent.com/17355109/143999746-24221572-a525-436d-856b-3bbb7ec7009e.png)

## System Information

- OS: Windows 10 latest updated
- Browser: Firefox latest updated
- Dark Reader Version: 4.9.42

## Additional Context
One thing that I should mention, I have **privacy.resistFingerprinting= true** in about:config.

**Comment by Gusted** [comment]
> One thing that I should mention, I have **privacy.resistFingerprinting= true** in about:config.

This is the problem, Firefox will simply force the color scheme to be light, websites and extensions will not be able to retrieve the correct color.

**Comment by GLaDOSi** [comment]
> > One thing that I should mention, I have **privacy.resistFingerprinting= true** in about:config.
> 
> This is the problem, Firefox will simply force the color scheme to be light, websites and extensions will not be able to retrieve the correct color.

I am have the same issue and privacy.resistFingerprinting is set to false.

**Comment by Gusted** [comment]
> I am have the same issue and privacy.resistFingerprinting is set to false.

Please open up a new issue for it, as this is caused by a option(which you don't have set).
