### ISSUE TITLE
[Broken Website] https://pan.baidu.com/

### ISSUE THREAD

**Issue by kechajin** [darkreader/darkreader#7508]
# Broken Website Report

## Website Address

https://pan.baidu.com/
## Steps To Reproduce

1. Open the plugin. 
2. Log in to the website, but the web page is not fully displayed. 
3. The website is added to the exclusion list and the page is completely loaded.
## Expected Behavior

The theme of the website turns black and the page is fully displayed
## Actual Behavior

The theme of the website turns black but the page is not fully displayed
## Screenshots

![0](https://user-images.githubusercontent.com/67051162/143998548-fd9b0b7a-a3e0-4770-b8b4-5202d8d9a664.png)

## System Information

- OS:Windows 
- Browser: FireFox 94.0.2 
- Dark Reader Version:4.9.42

**Comment by Gusted** [comment]
#7263
