### ISSUE TITLE
[Broken website] shopping.google.com

### ISSUE THREAD

**Issue by redudant-overflowing** [darkreader/darkreader#7512]
# Broken Website Report

## Website Address
https://shopping.google.com/

## Steps To Reproduce

1. Go to https://shopping.google.com;
2. Search for an item.

## Expected Behavior
There should be a dark background instead of a light grey one.

## Actual Behavior
There is light grey background.

## Screenshots
![Screenshot_20211130_131231](https://user-images.githubusercontent.com/93951203/144086275-7ca83b96-247c-454e-bc3f-35a130cb10ab.png)

## System Information

- OS: Fedora 35
- Browser: Firefox 94.0
- Dark Reader Version: 4.9.42

## Additional Context
- I'm using Google search in pt-BR;
- This issue doesn't happen in Google.com. The dark mode provided by Dark Reader complements Google's built-in dark mode;
- Google's built-in dark mode keeps turning off randomly, but I want it to be on full time. That's why I don't add Google to the exclusion list.

**Comment by Gusted** [comment]
Hi @redudant-overflowing!

Are you using the "Filter" theme?

**Comment by redudant-overflowing** [comment]
> Hi @redudant-overflowing!
> 
> Are you using the "Filter" theme?

I'm using Dynamic.

**Comment by Gusted** [comment]
Hmm weird that the behavior is with Dynamic.

Does it show any errors in the console(ctrl + shift + i)? 

Also does google's dark mode works on shopping.google.com, _it could be_ that it's interfering somehow(which generally shouldn't)

**Comment by benjo456** [comment]
I have the same problem
