### ISSUE TITLE
[Bug] Dev Tools/Dynamic Theme Editor constantly removes custom settings

### ISSUE THREAD

**Issue by Overwatching** [darkreader/darkreader#7517]
# Bug Report

## Bug Description
I make several changes to pages in the [Dev Tools/Dynamic Theme Editor] every day.
These changes either deal with internal ips/sites, private sites, or are just personalized changes to suit my tastes that shouldn't be pushed to everyone.

This has been perfectly fine for years.

Since early November(ish) these changes get erased on a daily basis.
Note: This machine is not being rebooted, nor is the browser being restarted. Yet the changes get reverted.
I have noticed as few as 4 hours before all changes get wiped.

## Website Address
Private IPs
Private sites
It doesn't matter.

## Steps To Reproduce
1. Open Dev Tools
2. Make a change
3. Come back tomorrow...

## Expected Behavior
I expect my changes to stay changed.
It should not be erasing anything I add manually. Ever.

## Actual Behavior
Dev Tools/Dynamic Theme Editor changes get reverted.
Constantly.
Anywhere between 4-24 hours after a change is made.

## System Information

- OS: Windows 10 LTSC 1809
- Browser: Chrome 96
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Dup #7277

**Comment by Overwatching** [comment]
Ahh.

I did search for it.

However, I didn't find it because that other thread is titled wrong.
A "Custom Rule" is the extension tab where you fiddle with the brightness/contrast/Greyscale, not the "Dev Tools" window.

Oh well, at least I have something to track now.

**Comment by Overwatching** [comment]
Hold on a minute, you closed all those bug reports, but the bug still isn't fixed.

THAT'S why it didn't show up in any searches. There aren't ANY open bug reports for it.

If you are going to close "duplicate" reports, there had better be an active report that they are "duplicating".
Otherwise, they AREN'T duplicate reports...
