### ISSUE TITLE
Are you sure that you cannot use "persistent": false ?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [darkreader/darkreader#752]
https://github.com/darkreader/darkreader/blob/26a45051836776ccbf4140841e6dec5a8b0ff6b3/src/manifest.json#L22

https://developer.chrome.com/extensions/background_pages

With event page instead of background page you can consume less RAM.

**Comment by alexanderby** [comment]
Dark Reader's background page doesn't consume much RAM (about 50MB is reported by Chrome Task Manager for me now). At the same time it loads user settings on startup, loads configurations (local and remote periodically), font list etc. So, I think persistent background page works faster. Memory leaks were fixed long time ago and I haven't seen any new one.

**Comment by Gusted** [comment]
Not possible the content scripts need a connection at any time with the background page.
