### ISSUE TITLE
first impressions...

### ISSUE THREAD

**Issue by atomGit** [darkreader/darkreader#7521]
1. the CSS for the pop-up is a _mess_ - if one sets a large minimum font size in Firefox prefs, the pop-up elements overlap and become unreadable because the body width is hard coded
2. too many styles are used for the CSS for the pop-up - for all elements of a single color for example, there may be multiple styles 
3. the (huge) logo in the pop-up is unnecessary IMO
4. if you have to enable the site specific setting button to apply theming to a site, then why isn't that button located above the global settings? 
5. no global choices for default colors (text, background, links) and so no uniformity across sites
6. a hard-coded black list? really? i see there's allot of well deserved criticism regarding this and for good reason - what if a site admin changes the theme? or changes it based on the day of the week? or local? etc... yes, i know it can be overridden, but that's not the point - this is a really poor way of handling sites that have a dark theme *at the moment* and, again, this leads to a non-uniform experience across sites
7. no path matching: apparently no way to avoid theming example.com, but apply theming to example.com/path
8. disabled on AMO with no way to override??? why is a developer forcing their preference on users?

i think several lessons in intuitiveness and usability can be learned from [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/)

**Comment by Gusted** [comment]
Move it over to https://github.com/darkreader/darkreader/discussions
