### ISSUE TITLE
[Bug] Extension doesn't work on chrome:// and chrome-extension:// urls, even with correct settings/flags

### ISSUE THREAD

**Issue by dr-vortex** [darkreader/darkreader#7526]
# Bug Report

## Bug Description
Dark reader does not work on chrome:// and chrome-extension:// URLs (e.g. chrome://about or chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/ui/popup/index.js) even with the "enable on restricted pages" settings enabled and the "extensions on chrome URLs" flag (chrome://flags/#extensions-on-chrome-urls) enabled.

## Website Address
chrome://*
chrome-extension://*

## Steps To Reproduce
- Enable the chrome flag (chrome://flags/#extensions-on-chrome-urls)
- Enable the settings in Dark Reader (popup -> settings -> site list)
- Attempt to view one of the pages

## Expected Behavior
The page being put into dark mode

## Actual Behavior
The page is not being put into dark mode

## Screenshots
![image](https://user-images.githubusercontent.com/75621402/144302870-9744a6b5-27fa-4966-a40a-f8ca56765334.png)
A local extension page - not being put into dark mode

## System Information
- OS: ChromeOS 89 - 94
- Browser: Chrome 89 - 94
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Hi @dr-vortex!

If you open the dark reader extension, you can see that chrome:// and chrome-extensions:// are protected URL's by chromium, extensions cannot touch them.

Regards,
Gusted

**Comment by dr-vortex** [comment]
@Gusted,

What does the "enable on restricted pages" settings do then? Plus the text below the settings mentions chrome flags - presumably the #extensions-on-chrome-urls flag, which allows the extensions to work in chrome:// URLs if they request it. Could you please clarify this setting a little (Maybe something on the dark reader help page)?

**Comment by Gusted** [comment]
> What does the "enable on restricted pages" settings do then? Plus the text below the settings mentions chrome flags - presumably the #extensions-on-chrome-urls flag, which allows the extensions to work in chrome:// URLs if they request it.

It's a "advanced" setting, as it will remove our internal check to disallow the extension being run on "restricted" pages(to avoid errors and compliance with extension stores etc.). It's not a one-click solution. If it doesn't work, it doesn't work. It's really a edge-case as they require the mentioned browser flags to be correct.





> Could you please clarify this setting a little (Maybe something on the dark reader help page)?

Not sure what to clarify, you should enable it in the browsers flags is vague on intention as it maybe won't work in the next chromium version of firefox version. It's a "own risk" in that sense. It's a option for people that understand it and need it.

**Comment by james-pre** [comment]
@Gusted I've updated my GitHub username from @dr-vortex to @james-pre. Please update your comment, and I can delete this one. I'm writing this comment when I can't make the change myself.

**Comment by alexanderby** [comment]
Hi @james-pre, could you please describe the problem that you have?

**Comment by james-pre** [comment]
Yes, I updated my username, though the comment by @Gusted has the old one. Could you edit the comment to have my new username?

**Comment by james-pre** [comment]
@alexanderby I delete my comments regarding the name change, if you could do the same it will clear things up. Thanks
