### ISSUE TITLE
[Bug] enable proxy document.styleSheets by default breaks using darkreader with sites that use MathJax v2

### ISSUE THREAD

**Issue by williamstein** [darkreader/darkreader#7536]
# Bug Report

## Bug Description
Enabling proxy document.styleSheets by default breaks using darkreader with sites that use MathJax v2.  In particular, this small PR https://github.com/darkreader/darkreader/pull/6957 recently made it so document.styleSheets is always proxied, rather than just proxied for 3 specific websites.   This broke use of darkreader with https://cocalc.com, and likely all websites that use MathJax v2 (I don't know if MathJax v3 is also broken). 

I have changed cocalc.com to peg the version of darkreader it includes at version 4.9.35 as a workaround for this problem. 

The best fix from my point of view would be if, when enabling darkreader, there were an option to not make document.styleSheets  be proxied. 

I'm sorry this bug report doesn't fill in all the required information.  However, if you're at least open to allowing document.styleSheets proxying to be disabled, I could likely at least implement that and send a PR.

**Comment by Gusted** [comment]
Hi @williamstein!

Are you using the Dark Reader API? As that would make sense to make it as a option to disable such features(given that such sites wouldn't need this feature).

Regards,
Gusted

**Comment by williamstein** [comment]
> Are you using the Dark Reader API?

YES.   https://github.com/darkreader/darkreader/commit/2020cfe43857a34b90370219ea9b70165c8356c2 totally solves my problem :-). Thanks!!

**Comment by alanhogan** [comment]
I notice that DarkReader appears to break some MathJax on https://liorsinai.github.io/mathematics/2021/11/05/quaternion-1-intro.html

Is this fixable on DarkReader's side? (I do not maintain the page linked above)

**Comment by Gusted** [comment]
That's a different issue, could you open up a new issue for that?
