### ISSUE TITLE
Having to reapply static theme tweaks on Firefox browser restart

### ISSUE THREAD

**Issue by SilverWolf32** [darkreader/darkreader#754]
I'm using the static theme mode on most sites, and I have some tweaks to customize the look and to make specific sites work properly. But often, and for no apparent reason, it will stop applying the styles. Fortunately, they're still there in the editor, and I can just open it and click Apply.

This seemed to happen a lot while I was testing out a Firefox theme, but it mainly happens on every browser restart.

This is on Firefox Developer Edition 63.0b11 and Dark Reader 4.6.8, on OS X 10.14.

**Comment by alexanderby** [comment]
Do you use CSS editor or Developer Tools? This is a know problem for Dev Tools, but also Static mode Dev Tools is an experimental utility. I'm not sure if it's worth improving it, the CSS editor should work better.

**Comment by alexanderby** [comment]
@SilverWolf32 Have a look here https://darkreader.org/blog/stylish/
