### ISSUE TITLE
[Broken Website] Google Sheets text rendering is fuzzy

### ISSUE THREAD

**Issue by pipipear-burn** [darkreader/darkreader#7540]
# Broken Website Report

## Website Address
https://docs.google.com/spreadsheets/u/0/create

## Steps To Reproduce
- Go to https://docs.google.com/spreadsheets/u/0/create or open any Google Sheet with text
- Enable Dark Reader

## Expected Behavior
The text is rendered clearly

## Actual Behavior
The text is rendered with fuzzy colors around every character

## Screenshots
![ii5Ueh5](https://user-images.githubusercontent.com/77356037/144530669-5212127d-ab80-434a-855c-df92d4030a2f.png)
![mQ486XE](https://user-images.githubusercontent.com/77356037/144530686-8a330b48-d620-45b0-b72b-f100a861bf81.png)

## System Information
- OS: Linux
- Browser: Chrome 96
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
Dup #6620
