### ISSUE TITLE
[Broken Website] Techpowerup sears the

### ISSUE THREAD

**Issue by eddie-LA** [darkreader/darkreader#7541]
# Broken Website Report

## Website Address
https://www.techpowerup.com/

## Steps To Reproduce
Site has two white columns on both sides in Dynamic and Static mode. Filter and Filter+ eliminate this but don't look as good. 

## Expected Behavior
No white columns.

## Actual Behavior
N/A

## Screenshots
![sc](https://user-images.githubusercontent.com/28909420/144606575-d1bf7ab6-784a-4ed5-8926-8fca93edf881.PNG)

## System Information
- OS: Windows 10
- Browser: Firefox Beta 95
- Dark Reader Version: 4.9.42

## Additional Context
Static with removed white columns would be perfect - it's fast and has no observable artifacts.

**Comment by Gusted** [comment]
This issue is caused by Ublock Origin, for some reason dark reader cannot take any precedence over their styles.

**Comment by eddie-LA** [comment]
> This issue is caused by uBlock Origin, for some reason dark reader cannot take any precedence over their styles.

Huh, didn't know that! :) You are correct, closing issue now.
