### ISSUE TITLE
[Bug] Dark Reader does not recognize system color scheme when waking from sleep

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#7553]
# Bug Report

## Bug Description

I use a software called [Windows Auto Night Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) to automatically change the Windows theme to light/dark mode. 
Sometimes when I wake a computer from sleep in the morning, Dark Reader would not recognize the automatic change to light theme, and still would keep websites dark. 

## Steps To Reproduce

- Install Windows Auto Night Mode 
- Set Dark Reader automation to use system color theme, leave browser running. 
- Put computer to sleep during dark mode
- Wake up the computer the next morning 

## Expected Behavior

The computer should automatically switch back to light theme and Dark Reader should follow with it. 
## Actual Behavior

Dark Reader is still showing websites in dark mode. 
## System Information

- OS:  Windows 11 21H2
- Browser: Brave 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
- Dark Reader Version: 4.9.42

## Additional Context

It may be hard to reproduce , sometimes Dark Reader would switch automatically and sometimes it doesnt.

**Comment by b-hayes** [comment]
Happens to me to
