### ISSUE TITLE
[Broken Website] kb.mozillazine.org/Knowledge_Base starts dark then turns light

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#7556]
# Broken Website Report

## Website Address
http://kb.mozillazine.org/Knowledge_Base

## Steps To Reproduce
- Enable DR's dynamic dark mode
- Go to http://kb.mozillazine.org/Knowledge_Base
- Notice the page is nice and dark at first
- Wait a few seconds
- Suddenly the page changes to a bright white background

## Expected Behavior
Stays dark

## Actual Behavior
Goes light after a few seconds

## System Information

- OS: Windows
- Browser: Firefox 94.0.2
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
#5937

**Comment by Gitoffthelawn** [comment]
Thank you Gusted.
