### ISSUE TITLE
Guidance on Themes & Customization for  Newer User

### ISSUE THREAD

**Issue by sheldonhull** [darkreader/darkreader#756]
#604 really helped me by generating the static theme from the dynamic. 
I'd like to better understand how to theme, if variables or anything else is supported. If you look at the [darkness project](https://github.com/liorgrossman/darkness) you'll see it's great for applying 6 different color themes of darkness. I want to override some defaults in darkness to change the overall color pallete to something more "material" when possible and I'm really unclear on if that's possible. 

- Can I change a default color palette used for dark generation?
- Are my custom css themes used when generating via static synced via chrome data so I don't lose it? (I have some intranet type sites I want to customize)
- Is there any interest in some capability for a dropdown on css theme presets like "Dusk/Material Dark" like Darkness uses, that would allow a little more customization on the colors used?
- I still have some problems with dynamic mode and async content or content hidden that is then shown. Not sure how to approach resolving this, or if I can at all? I'm guessing it's ignored due to being hidden?

I know it's a lot of questions, most of this I'm sure would be good wiki material. I love dark reader's approach more than the manual work of the Darkness project, but I also like the control for overrides and theme tweak that it offers. I'm guessing I can get close to this if I understand better what is an enhancement and what is already offfered but just not clear to a newer user.

**Comment by alexanderby** [comment]
1. Custom palette is planned.
2. If the settings size exceeds 5MB it cannot be synced, all the settings will be stored locally.
3. I will have to do some research to answer this question.
4. If you see the problem, you can submit an issue on GitHub or send website address and screenshot to darkreaderapp@gmail.com

I agree, many questions can be added to Wiki, there is already a FAQ page including some, I'm not sure if anybody reads it (maybe it's hard to read) https://darkreader.org/help/en/#faq

**Comment by alexanderby** [comment]
My fault, the settings will not be synced if size limit exceeds 8KB, it can be optimized up to 102KB but this will make app more complex, so my decision was to switch off syncing. Local storage has 5MB size limit. If it is exceeded the extension can ask for unlimited storage. Unfortunately I haven't implemented this yet.

**Comment by pseudoelvis** [comment]
@alexanderby is there a way to add a toggle some syncing back on, perhaps with a variable? I am using Dark Reader across several machines, and I would like the exceptions list, at minimum, to sync, as I have many sites that are currently rendered incorrectly due to varying dark mode support of their own.

**Comment by alexanderby** [comment]
@pseudoelvis It is planned to add settings Export and Import, then it will be possible to manually edit all the settings in JSON format.

**Comment by brenopoggiali** [comment]
Is there any update on this issue?

**Comment by Gusted** [comment]
1. Yes https://darkreader.org/blog/v4-9/
2. Yes you even could disable syncing if you want but by default on so Long it doesn't exceed 5MB
3.  #2876 
4. It's been 2 years I highly thing this has been fixed troughout the code changes.
