### ISSUE TITLE
Not working on wired.com articles

### ISSUE THREAD

**Issue by sepahram** [darkreader/darkreader#757]
Hi,
I suppose web sites like Wired.com somehow suppressing Dark Reader. 
Check this out, for an example:
https://www.wired.com/story/ideas-joi-ito-great-digitization-event/

It's all right on header and some ads, but not working on the body.

**Comment by Forge36** [comment]
The website does load initially respecting the darkreader settings. Something in the JS is applying a style which supersedes darkreader. I'll debug this more when I'm not at work.

**Comment by alexanderby** [comment]
Should work well with the latest release. I've added the ability for style to restore itself when some other script removes it. But only 1000 attempts allowed to prevent infinite loops and tab freeze, didn't see this anywhere, but it can potentially happen.

**Comment by sepahram** [comment]
> Should work well with the latest release....

Checked. Works all right. Many thanks.
