### ISSUE TITLE
[Bug] Vertical scrollbar arrows are missing

### ISSUE THREAD

**Issue by ahmed-salem-me** [darkreader/darkreader#7570]
# Bug Report

## Bug Description
When extension is enabled the vertical scrollbar would be missing its arrows.
The arrows have been an integral part of scrollbars since ever and are much needed.

## Website Address
All websites

## System Information

- OS: Windows 10
- Browser: Chrome, Vivaldi
- Dark Reader Version: 4.9.42

**Comment by Gusted** [comment]
See #7230
