### ISSUE TITLE
[Bug] Dark Reader queries darkreader.github.io on every startup of Firefox

### ISSUE THREAD

**Issue by duesee** [darkreader/darkreader#7574]
# Bug Report

## Bug Description
Dark Reader (4.9.42) queries `darkreader.github.io` on every startup of Fennec (94.1.1).

I assume this is done to show release notes or something similar, but doing it on every startup doesn't seem necessary and allows to deduce precisely when someone is using Fennec.

## Steps To Reproduce
Open Firefox/Fennec and observe DNS requests in Wireshark or something similar.

## System Information
- OS: Android
- Browser: Fennec 94.1.1
- Dark Reader Version: 4.9.42

## Additional Context
```http
GET /blog/posts.json HTTP/1.1
Host: darkreader.github.io
User-Agent: Mozilla/5.0 (Android 11; Mobile; rv:94.0) Gecko/94.0 Firefox/94.0
Accept: */*
Accept-Language: de-DE
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cache-Control: max-age=0

```

```http
HTTP/1.1 301 Moved Permanently
Accept-Ranges: bytes
Age: 814
Connection: keep-alive
Content-Length: 162
Content-Type: text/html
Date: Tue, 07 Dec 2021 16:11:40 GMT
Location: https://darkreader.org/blog/posts.json
Server: GitHub.com
Vary: Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Fastly-Request-ID: 7cb2d496ee234c731134ca7c1341a9c93ba8fa56
X-GitHub-Request-Id: 87F4:11A2:2ED71:BAA46:61AF848E
X-Served-By: cache-hhn4073-HHN
X-Timer: S1638893501.637971,VS0,VE1
permissions-policy: interest-cohort=()

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Gusted** [comment]
Hi @duesee!

You can disable those requests:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Go to ⚙Settings -> Manage settings
    Disable Notify of News
    
Regards,
Gusted

**Comment by duesee** [comment]
Thank you very much @Gusted! This solves the "problem" for me, but I think it is worth fixing it for all users. I was surprised to see these requests in my traces and first assumed that this is some form of tracking. Only later I realized that it is used to fetch the news. In other words: these requests look suspicious, even thought they are not. What do you think? Would you be interested in a patch to somehow limit the amount of requests?

**Comment by Gusted** [comment]
> What do you think? Would you be interested in a patch to somehow limit the amount of requests?

Not sure how someone might do that, as that would require a local setting(which shouldn't be saved to the synced storage) and mess around with the clocks and timers.

**Comment by duesee** [comment]
Mhm... I will try to figure something out. Let's close this for now.
