### ISSUE TITLE
[Feature Request] Setting for "Theme generation mode" per website

### ISSUE THREAD

**Issue by con-f-use** [darkreader/darkreader#7575]
# Feature Request

## Is this feature request related to a problem?
There is no one-size-fits all for the "theme generation mode", that works for every website. Can this please be a per-website setting?

## Screenshots
![image](https://user-images.githubusercontent.com/11145016/145071632-7fe17f0d-50cd-4e95-a31e-a38089be14b8.png)

For example, "dynamic" doesn't look good on tweag.io:

![dynamic on tweag](https://user-images.githubusercontent.com/11145016/145072802-f3a301c6-affb-447c-9eee-908445eba042.png)

![static on tweag](https://user-images.githubusercontent.com/11145016/145072513-e7a8fa0f-8a88-47a3-bfd6-5ff86648855b.png)

While it's the other way around on duckduckgo: 

![dynamic on duckduckgo](https://user-images.githubusercontent.com/11145016/145073082-da032ba9-ce0f-435d-bdc7-a3a77fb8610c.png)

![static on duckfuckgo](https://user-images.githubusercontent.com/11145016/145073259-b5426f96-f675-4346-9bb1-677c7c1d238b.png)

**Comment by Gusted** [comment]
Hi!

Please explore the new interface, which has these options:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Regards,
Gusted

**Comment by con-f-use** [comment]
Cool. You have received a donation.
