### ISSUE TITLE
[Dynamic] Blinking when color in animation changes

### ISSUE THREAD

**Issue by schrodog** [darkreader/darkreader#758]
The animation is keep blinking when color changes in this website [visualgo](https://visualgo.net/en/sorting) under dark dynamic mode
![screenshot from 2018-10-09 20-59-02](https://user-images.githubusercontent.com/16360247/46671093-76373600-cc06-11e8-9dda-e84b5b340c91.png)

**Comment by Gusted** [comment]
Seems fixed.
