### ISSUE TITLE
[Bug] CORS resources broken dark mode on Chrome

### ISSUE THREAD

**Issue by mashirozx** [darkreader/darkreader#7580]
# Bug Report

## Bug Description

I'm using darkreader as NPM dependency in a React project.
I found something strange that the dark mode works well with bundled resources (js and css) loaded from same domain (no redirect), but when I load resources from jsDelivr CDN or event just using a 301 redirect for assets urls with Nginx, the dark mode will be broken. And this happens only on Chrome (Firefox works fine).

## Website Address
https://moezx.github.io/v2ba/

Source code here: https://github.com/moezx/v2ba

Called here: https://github.com/moezx/v2ba/blob/master/src/layouts/index.tsx#L30
The hook is here, which uses the mater branch of darkreader ( fec2521 ): https://github.com/moezx/react-darkreader/blob/main/src/useDarkreader.ts

## Screenshots

Firefox OK: 
![image](https://user-images.githubusercontent.com/16148054/145145330-c2aab9e1-4ffd-4249-8658-56eb25e28d7f.png)

Chrome broken:
![image](https://user-images.githubusercontent.com/16148054/145145377-1531f4a2-b533-439c-bdc7-89853645a1e2.png)

## System Information

- OS: Windows
- Browser: Chrome 96.0.4664.45 (Official Build) (64-bit)
- Dark Reader Version: mater branch ( fec2521 )

**Comment by Gusted** [comment]
I'm not sure if this is a issue with Dark Reader, this is a issue with CORS and the browser, not something that I _magically_ can fix.

**Comment by eldorel** [comment]
Is this possibly related to issue #7569 ?  

This looks like the same result, and it seems like there's a common theme of  "assets failing to load".  (either via CORS or due to an adblocker). 

It would not surprise me if this pointed to a recent change by the chrome devs breaking extensions, but it would be nice to at least be able to ID that chance so that we can submit a bug report to them.

**Comment by Gusted** [comment]
This isn't related, this is a issue with the NPM library of dark reader... Which btw isn't not been active so closing anyway.
