### ISSUE TITLE
feature request: whitelist certain subpages

### ISSUE THREAD

**Issue by ludant** [darkreader/darkreader#7588]
currently, i'm browsing a site https://mainsite.com , which has a dark theme.  however, they have a sub page https://mainsite.com/subpage/ in light mode.  i don't see any way of whitelisting mainsite.com while also blacklisting mainsite.com/subpage

**Comment by Gusted** [comment]
Please use the appropriate template for this, also make sure if their aren't already bug about this(their are plenty of them)
