### ISSUE TITLE
[Performance Issue] "Dark Reader is slowing down Firefox" on https://sqlitebrowser.org/stats/

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#7594]
# Performance Issue Report

## Website Address
https://sqlitebrowser.org/stats/

## Steps To Reproduce

- Enable DR with Dynamic dark mode.
- Go to https://sqlitebrowser.org/stats/
- After a little while, get "Dark Reader is slowing down Firefox" message.
- Also, notice that after doing the above, Firefox may take 5-30 seconds just to completely terminate it's processes.

## Performance Profile
No permission to upload.

## System Information

- OS: Windows
- Browser: Firefox 95.0.0
- Dark Reader Version: 4.9.43

## Additional Context
- Does this happen when Dark Reader is disabled? No.
- Does this happen in other browsers? \<smartass\>No, other browsers don't give a "Dark Reader is slowing down Firefox" message. :) :) :)  Oh, okay, that's not what you meant? :) \</smartass\>
- Do you have hardware acceleration enabled?  Hmmm... I do in the Firefox settings, but I don't see it listed in `about:support` any more.  Where can I confirm whether or not it is actually using hardware acceleration?  `gfx.webrender.all` and `gfx.webrender.software` are both `false`, but those values appear to be the defaults.

**Comment by Gusted** [comment]
Their is indeed a slowdown: https://share.firefox.dev/3GxwgmJ

I will have a look at a later moment when I have my special tools ready to debug this nasty performance bug.

**Comment by Gitoffthelawn** [comment]
> Their is indeed a slowdown: https://share.firefox.dev/3GxwgmJ
> 
> I will have a look at a later moment when I have my special tools ready to debug this nasty performance bug.

Thanks so much Gusted.

BTW, do you know how to verify whether or not FF has hardware acceleration enabled?

**Comment by Gusted** [comment]
> BTW, do you know how to verify whether or not FF has hardware acceleration enabled?

Firefox has since recently on a lot of devices "webrender" enabled, See `about:support#graphics` 
![image](https://user-images.githubusercontent.com/25481501/145814964-6c2eb32e-b7dc-43c5-9a21-e037fdac3175.png)

**Comment by Gitoffthelawn** [comment]
Which is the best way to fix this? Via a site-specific exception like #7630, or a global fix (if possible) to rectify the underlying cause of the performance issue (which will work on all sites)?

Of course "best" is in the eye of the beholder, and a site-specific exception is/was faster to create.

**Comment by Gusted** [comment]
> Which is the best way to fix this? Via a site-specific exception like #7630, or a global fix (if possible) to rectify the underlying cause of the performance issue (which will work on all sites)?

Every fix in the config is the best way to fix via the extension, yet this is a really deep issues in how sites behave. We had similar issues with "atlassian.net", in a sense, we cannot store elements from the DOM, as they will updated and thus our version is a outdated one, nor do I want to add extra nonsense of attributes into the elements(causing other issues). 

The issue is that certain elements on sites like these will go continue race between dark reader and the website to configure the element as they want(we want to modify it, the site wants to reset the element of our changes), given we cannot know if a element is in such loop, we cannot do a lot within the code to prevent this.

**Comment by Gitoffthelawn** [comment]
Thank you for the great explanation.  Makes perfect sense.
