### ISSUE TITLE
[Safari] Prolonged "flashbang" in dynamic mode

### ISSUE THREAD

**Issue by wzxu** [darkreader/darkreader#760]
When using dynamic mode, whenever I go to a new page the entire background turns to white and blinds me, which doesn't (or should I say very rarely) happen if I switch to filter mode. In filter mode, new page turns dark immediately.

What's worse, the white background doesn't go away until complete page load. That's seconds of complete blindness. Again, doesn't happen with filter mode. Doesn't happen with dynamic mode in other browsers, either.

In addition to styling issues on some of my most frequented sites, this "flashbang" issue forces me to turn away from the superior dynamic mode and stick with filter mode for now. Please look into it. Cheers!

(Should I still report styling issue with dynamic mode? Or, since those sites work normally on other browsers with Dark Reader, should I expect the issues to be fixed automatically when you update the code base to match other browsers?)

**Comment by alexanderby** [comment]
There seems to be some Safari specific problem, it seems it doesn't apply style sheets changes synchronously, but instead seems to split and render style sheets by chunks. The working solution was to force all backgrounds and texts to have the same color, until the page finishes loading, but I'm trying to achieve a smooth transition.

If there is a problem with displaying web pages, you can submit issues to this repository. For other Dark Reader for Safari issues please write to darkreaderapp@gmail.com until the project becomes open source.

**Comment by ylluminate** [comment]
Do we need to make some requests to Apple to fix this issue?

**Comment by alexanderby** [comment]
I've made many performance improvements to eliminate these white flashes, and also got more ideas. I think I will publish Safari update today and Chrome and Firefox tomorrow.

@ylluminate Safari (at least it's extensions API) and XCode also need improvements, so if you know were to submit bugs, it would be very welcome.
