### ISSUE TITLE
[Broken Website] https://hdlbits.01xz.net/wiki doesn't work well with 4.9.43

### ISSUE THREAD

**Issue by linsui** [darkreader/darkreader#7601]
# Broken Website Report

## Website Address
https://hdlbits.01xz.net/wiki/Exams/ece241_2014_q5a

## Steps To Reproduce

- Go to https://hdlbits.01xz.net/wiki/Exams/ece241_2014_q5a
- Everything is black and white
- Reload darkreader
- Everything works well now

## Expected Behavior

The style works well on start

## Actual Behavior

It only works after toggle the darkreader

## Screenshots

![图片](https://user-images.githubusercontent.com/36977733/145508062-5c130f16-ecd2-4f99-b51c-1ddaa8b2efbf.png)
![图片](https://user-images.githubusercontent.com/36977733/145508094-4383dc3c-b280-458e-a7d2-b5d19fe5ec3a.png)

## System Information

- OS: Linux
- Browser: Firefox 94
- Dark Reader Version: 4.9.43

## Additional Context

It works well before 4.9.43 update.

**Comment by Gusted** [comment]
I'm not able to reproduce, is this reproduce-able when you have a new profile `about:profiles`?

**Comment by linsui** [comment]
Oh, no, I can't reproduce it in a new profile. Though my current profile is also pretty new... Thanks!
