### ISSUE TITLE
[Bug] Cannot read properties of null (reading 'disableStyleSheetsProxy')

### ISSUE THREAD

**Issue by FearGannicus** [darkreader/darkreader#7608]
# Bug Report

## Bug Description
Darkreader is not properly converting website design into dark mode. Currently returning the following error in console.
![image](https://user-images.githubusercontent.com/43388217/145626970-b36add54-27a5-4323-a13f-6aa7ab66c1a4.png)

## Website Address
https://dashboard.guildrestore.com (currently in development)

## Expected Behaviour
Should not be returning an error of any kind, and should be converting the website design into dark mode properly.

## Actual Behaviour
Returning the following error;
```
ERROR TypeError: Cannot read properties of null (reading 'disableStyleSheetsProxy')
    at createStaticStyleOverrides (darkreader.js:4859)
    at createThemeAndWatchForUpdates (darkreader.js:5012)
    at createOrUpdateDynamicTheme (darkreader.js:5122)
    at enable (darkreader.js:5268)
    at DmService.toggleDarkmode (dm-service.service.ts:24)
    at HeaderComponent.toggleDarkmode (header.component.ts:48)
    at HeaderComponent_nav_0_Template_a_click_12_listener (header.component.html:44)
    at executeListenerWithErrorHandling (core.mjs:15291)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15329)
    at HTMLAnchorElement.<anonymous> (platform-browser.mjs:546)
```

## Screenshots
![image](https://user-images.githubusercontent.com/43388217/145627534-97bacf6a-5ac2-4879-b2c2-76d11e1ea918.png)
What the website looks like without dark mode enabled.

![image](https://user-images.githubusercontent.com/43388217/145627634-0a0f7dc2-8bf8-4ba2-88e1-a45323c6a251.png)
What the website looks like after the dark mode toggle errors.

## System Information

- OS: Windows 11
- Browser: Chrome 96.0.4664.45
- Dark Reader Version: 4.9.43

## Additional Context
Here is what my toggle darkmode service looks like:
```typescript
import { Injectable } from '@angular/core';

import { enable, disable, isEnabled } from 'darkreader';

@Injectable({
  providedIn: 'root'
})
export class DmService {

  private options = {
    brightness: 90,
    contrast: 100,
    sepia: 10
  }

  constructor() { }

  toggleDarkmode(): void {
    if (isEnabled()) {
      // if we are currently enabled, disable
      disable();
    } else {
      // enable if we are currently disabled
      enable(this.options);
    }
    // Change our localstorage item
    localStorage.setItem('darkmode', String(isEnabled()));
  }

  autoDarkmode(): void {
    if (this.getDarkmode()) {
      if (this.getDarkmode() === 'true') {
        enable(this.options);
      } else {
        disable();
      }
    }
  }

  getDarkmode(): string {
    return localStorage.getItem('darkmode');
  }
}
```

If there's any further information I can provide please let me know!

**Comment by KevinDevs** [comment]
this is still a issue on https://unpkg.com/browse/darkreader@4.9.43/darkreader.js

**Comment by Youdaman** [comment]
Also having the same issue.

**Comment by KevinDevs** [comment]
Simply compile the code your own, it’s gonna work like charm.

**Comment by FearGannicus** [comment]
> Also having the same issue.

Looks like a fix has been made but not yet on the dark reader official release
