### ISSUE TITLE
[Feature Request] Issue a "Last Call" for users' fixes for websites.

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#7617]
# Feature Request

Dark Reader updates generally include users' fixes for websites.

It might be beneficial to post (perhaps in the issue tracker) a "last call" date for fixes to be included in the next release.

This can serve at least 2 purposes:
  1. As a visible reminder that everyone can contribute fixes.
  2. As an opportunity for people to integrate their locally stored fixes to the global style sheets that help everyone.

**Comment by Gusted** [comment]
> It might be beneficial to post (perhaps in the issue tracker) a "last call" date for fixes to be included in the next release.

We don't have a stable release schedule. Yeah they are mostly in the beginning of a month, but that isn't a guarantee. 


> 1. As a visible reminder that everyone can contribute fixes.

People who browse the issue tracker of watch issues(people who do, ehm 👋🏽 nice meeting you, shoot me a email) should for the most part be aware of this.



> 2\. As an opportunity for people to integrate their locally stored fixes to the global style sheets that help everyone.

I think this could be classified into the first point, as I don't want to put any kind of pressure to people to include fixes just before the next version is released. People should do that whenever they think it's good.

**Comment by Gitoffthelawn** [comment]
Sounds good.  Closing.
