### ISSUE TITLE
[Broken Website] https://getfedora.org/

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#7635]
# Broken Website Report

## Website Address
https://getfedora.org/

## Steps To Reproduce
Visit site.
Scroll down to the bottom of the page and notice that the image of the world map is not visible right above the webpage footer bar. (See screenshots.)

## Expected Behavior
Image of world map would be visible while using Dark Reader.

## Actual Behavior
Image of world map is not visible while using Dark Reader.

## Screenshots
No Dark Reader:

![fedora-light](https://user-images.githubusercontent.com/95879668/145897550-50875995-1a16-4fba-bab8-5ad887d43904.jpg)

With Dark Reader:

![fedora-dark](https://user-images.githubusercontent.com/95879668/145899257-3a67b15f-3812-44f4-aa10-54a25ff53244.jpg)

## System Information

- OS: Windows 10 21H2 (19044.1387)
- Browser: Firefox Nightly 97.0
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
#7638

**Comment by q1800** [comment]
Many thanks to @c-nagy & @Gusted! The fix looks very nice. Thank you kindly! 😃
