### ISSUE TITLE
[Broken Website] Youtube

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#7639]
## Website Address
https://www.youtube.com

## Expected Behavior
![image](https://user-images.githubusercontent.com/87893636/146001404-9399ceda-5635-45ca-b409-f9b8fc04b1d8.png)

![image](https://user-images.githubusercontent.com/87893636/146002187-16547ae5-9165-47b7-a13e-6b69fb279447.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/87893636/146001458-fbf10aff-50a9-4b43-81cd-50c3b65672a5.png)

![image](https://user-images.githubusercontent.com/87893636/146002236-dc0a80e2-c28d-4501-b14b-2dc6249261e8.png)

## System Information

- OS: Windows
- Browser: Edge 96
- Dark Reader Version: 4.9.43

## Additional Context
I want to remove the outline of the number of notification and remove the scrollbar background.

**Comment by Gusted** [comment]
This really depends if a user has light or dark mode in the appearance. I'm not sure if such fix should be appropriate as a user just could switch the appearance for such behavior.

**Comment by NguyenASang** [comment]
I tried both default light theme and dark theme and the bug still happened with the notification. It creates the outline of the number of notification and scrollbar background. Only thing is the color quite different a little bit.

**Comment by Gusted** [comment]
> I tried both default light theme and dark theme and the bug still happened with the notification.

As far as I see, both version have a outline on the notification(one just so happens to be more noticeable), so we remove the outline of it. As for the scrollbar-background, I don't seem to see the difference(they both are in-line with the body's background).

**Comment by NguyenASang** [comment]
![image](https://user-images.githubusercontent.com/87893636/146380035-d46f6a57-bfcd-4de2-a2ad-c21399c2d7ef.png)

I want the background of the scroll bar like the background (default in youtube doesn't have  scrollbar background)
