### ISSUE TITLE
Dark Reader doesn't work for bbc.co.uk/news on Safari

### ISSUE THREAD

**Issue by carlca** [darkreader/darkreader#764]
```
macOS 10.14 Mojave
Safari v12.0
```

Hello, I've just installed Dark Reader on Apple Safari and so far it looks pretty good. However, I'm having to disable it for https://www.bbc.co.uk/news because the colors are unreadable. Any idea what the problem is?

**Comment by alexanderby** [comment]
That was a sad simple mistake. The fix will be published today.

**Comment by carlca** [comment]
Thanks! As I use that website a lot, the fix will be most welcome!

**Comment by alexanderby** [comment]
This version is under review, I think you will see a red badge over App Store icon when it's ready.

**Comment by carlca** [comment]
Thanks Alexander! I must learn to be more patient!

**Comment by alexanderby** [comment]
The fix was published some days ago.
