### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by mattalexx** [darkreader/darkreader#7643]
# Broken Website Report

## Website Address

https://www.raspberrypi.com/documentation/computers/configuration.html

## Steps To Reproduce

- Go to https://www.raspberrypi.com/documentation/computers/configuration.html.

-->

## Expected Behavior

- Text is a lighter color on a black background.

## Actual Behavior

- Text is a dark color on a black background.

## Screenshots

![Screenshot_2021-12-14_14-32](https://user-images.githubusercontent.com/250466/146075140-934d4bea-a7a6-486d-ab5a-12fc5bb8e6c0.png)

## System Information

- OS: Linux  
- Browser: Ungoogled Chromium Version 96.0.4664.93 (Official Build, ungoogled-chromium) Arch Linux (64-bit) 
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
This was already fixed by #7578(which was 2 days after v4.9.43 was released), you can enable to have the newest fixes(so you will have the fix):


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Settings -> Manage Settings -> Synchronize site fixes.
    Dev Tools -> Reset

Regards,
Gusted
