### ISSUE TITLE
[Feature Request] Add support for adobe acrobat DC chrome extension

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#7653]
# Feature Request

## Is this feature request related to a problem?

Hey, adobe acrobat DC Extension https://chrome.google.com/webstore/detail/adobe-acrobat/efaidnbmnnnibpcajpcglclefindmkaj?hl=en does not switch pdf to dark mode! which is kinda annoying as i like the pdf conversion to dark mode!! please fix this ASAP!!
## Screenshots

<img width="942" alt="image" src="https://user-images.githubusercontent.com/78726445/146219893-c5fd3bad-b265-46a9-8dee-0641dd7e5ff5.png">
it should be in dark mode!!
## Additional Context

It is more about integration with adobe acrobat DC!! anyone who can fix this would make wonders!!

**Comment by Gusted** [comment]
Then go complain to Adobe, we can't do anything about it. Extension's are not allowed to touch other extensions.
