### ISSUE TITLE
Display error messages for "loading, please wait" screen

### ISSUE THREAD

**Issue by gitut2007** [darkreader/darkreader#767]
Hi. 
Clicking the icon in the toolbar, options don't load, it stays in "loading, please wait" for ever. (Firefox; other addons menus work, including the options for 'dark bg and l. text'. 
Thanks.

**Comment by alexanderby** [comment]
Seems like error messages should be displayed somewhere.

**Comment by sylvain-g-mpc** [comment]
I have the same issue.  The computer on which it happens is not connected to the internet.  Could it be the cause?

**Comment by alexanderby** [comment]
@sylvain-g-mpc It would be great if you could put a breakpoint on line 1690 and see the value of `engineNames` and run `getLocalMessage('engine_filter')`. Also, what happens if you execute `[1, 2, 3].find((x) => x > 2);` in console (should be `3` without errors)?

**Comment by Gusted** [comment]
Fixed.
