### ISSUE TITLE
[Broken Website] auth.alipay.com

### ISSUE THREAD

**Issue by TheCGDF** [darkreader/darkreader#7674]
# Broken Website Report

## Website Address

https://auth.alipay.com/login/index.htm
https://authstl.alipay.com/login/index.htm

## Expected Behavior

- Tabs "扫码登录" and "账密登录" should be kept.
![vivaldi_FHrCp0Zbx9](https://user-images.githubusercontent.com/17256673/146589949-73ef4305-32bb-4230-9158-e085c79352ec.jpg)

## Actual Behavior

- Tabs "扫码登录" and "账密登录" will be hidden.
![vivaldi_N2H9azqEQo](https://user-images.githubusercontent.com/17256673/146590004-513ae36f-51a0-40c4-84d8-cce9eb5d6b9a.jpg)

## System Information

- OS: Windows 10.0.17763.1039
- Browser: Vivaldi 5.0.2497.30
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
I have zero idea why these elements are disappearing.
