### ISSUE TITLE
[Bug] 'Enable setting sync' cannot be turned on on firefox on multiple platforms

### ISSUE THREAD

**Issue by TrashPanda** [darkreader/darkreader#7676]
# Bug Report

## Bug Description

'Enable setting sync' cannot be turned on

## Steps To Reproduce

Clicked on DarkReader icon, go to the settings, then manage settings, click on 'Enable setting sync' to try to turn it on

## Expected Behavior

'Enable setting sync'  should be able to turned on and have settings synchronized 

## Actual Behavior

It turns itself off no matter what I tried. Reinstallation doesn't work.

## System Information

- OS: Windows 10, macOS 12.1, Linux ubuntu 21.04, I use all the platforms
- Browser: Firefox 95.0.1 and many previous versions, it has stopped syncing for a long time
- Dark Reader Version: 4.9.43 

## Additional Context

It has been going on for months on multiple platforms

**Comment by Fred-Vatin** [comment]
Hi,

This bug still exists
- browser: Firefox 133.0
- OS: windows 10 22H2
- Dark Reader: 4.9.96
