### ISSUE TITLE
[Broken Website] youtube-local videos have low framerate on Firefox 88

### ISSUE THREAD

**Issue by DUOLabs333** [darkreader/darkreader#7691]
# Broken Website Report

## Website Address
It's self-hosted, but here's a public instance: https://yt-local.ga/

## Steps To Reproduce

Here is an example:
- Go to https://yt-local.ga/
- Search up any video on Firefox 88 (newer versions may have this problem).
- See choppy framerate 
- Turn it off and see problem go away.

## Expected Behavior

No problem with framerate when turned on.

## Actual Behavior
The framerate is low.

## System Information

- OS: Arch Linux
- Browser: Firefox 88 (only Firefox has this problem)
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Hi @DUOLabs333!

The frame-rate looks good to me(just the quality is bit low), are you sure this is a problem with dark reader? We don't touch the video element so we shouldn't have any interference with the video playback.

Regards,
Gusted

**Comment by DUOLabs333** [comment]
It's more evident if you increase it to 60 fps, and it only appears in Firefox. But yes, after I disabled Dark Reader, the video was smooth.

**Comment by Gusted** [comment]
I'm using [this video](https://yt-local.ga/https://www.youtube.com/watch?v=LXb3EKWsInQ) as a reference, and it's perfectly viewing well in 1080p60 - Dark Reader shouldn't even be able to interfere, unless you're using software-based video rendering, which is worse on it's own. You could check `about:support` and see if WebRender is enabled(it must be by now) and check if `gfx.webrender.software` is true in `about:config`.

**Comment by DUOLabs333** [comment]
Webrender is disabled ("disabled by env: Not qualified"), and `gfx.webrender.software` is disabled.

**Comment by Gusted** [comment]
> Webrender is disabled ("disabled by env: Not qualified"),

Ah that's quite interesting and most likely the reason, as webrender was a nice change to the GPU whereby the site could little impact the video performance. 

You could try to force webrender, `gfx.webrender.all` `gfx.webrender.compositor` to true & `gfx.webrender.software` to false.

There's nothing to do much other then try to figure out why webrender is enabled on your browse as that just fixes the issue all away(and dark reader doesn't magically run faster ;) )

**Comment by DUOLabs333** [comment]
Enabling the options didn't fix the issue.

**Comment by Gusted** [comment]
Well, I cannot do much nor is their much to fix. The problem is fixed when you have webrender(it was made for these kind of situations, to avoid low framerates at all cost) enabled, I'd suggest to take a look and fiddle around why webrender is blocked as it should be available to everyone now.

**Comment by DUOLabs333** [comment]
I do only have OpenGL 2.1, with OpenGL ES 3.0. Should that matter.

**Comment by Gusted** [comment]
> I do only have OpenGL 2.1, with OpenGL ES 3.0. Should that matter.

I don't have that depth information of Firefox, but it should be working on Linux just fine, only nvidia had some problems earlier this years but they are already fixed(you could try Firefox nightly with the about:config tweaks)
