### ISSUE TITLE
[Feature Request] Need a option to don't override the default (new) scroll bar

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#7696]
# Feature Request
Need a option to don't override the default (new) scroll bar

## Is this feature request related to a problem?
No

## Additional Context
I just found this feature of the scrollbar today and want to share it with everyone. If it works well with windows 10 and above devices (Chrome and Edge), I can make a video on how to enable it and we can pin it so everyone can see how to enable it.

Back to the feature request, this extension overrides this new scrollbar so I would like an option to disable it.

## Screenshots (NOT RELATED TO THE FUTURE REQUEST, this is what the new scrollbar looks like)
The new scroll bar
![146757821-02d4bb87-b1ed-4bc3-a777-b743ff5bfa70](https://user-images.githubusercontent.com/87893636/146758163-1b069d87-510c-472e-afe0-48384930cbbe.png)

The old scroll bar
![image](https://user-images.githubusercontent.com/87893636/146758317-5171e952-bbf1-4c98-a223-c2b1c768cd36.png)

**Comment by Gusted** [comment]
This is already a thing: https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151

**Comment by NguyenASang** [comment]
Nice
