### ISSUE TITLE
[Feature Request] Right-click context menu

### ISSUE THREAD

**Issue by darkwater4213** [darkreader/darkreader#7700]
# Feature Request

Basically, add an option in the right-click context menu on Chrome that allows you to invert certain elements or prevent them from being inverted, much like uBlock Origin allows you to block certain elements

## Screenshots
None (although I suppose I might take the time to make some concept ~~art~~ edited stuff)

## Additional Context
Perhaps add a line to the menu that has the darkreader logo and name, and summons a sub-menu when hovered on that has various options such as "exclude this website" or "don't invert this element" and so on.

**Comment by NguyenASang** [comment]
This is how you can do that:

https://user-images.githubusercontent.com/87893636/146849952-aa13f399-0a36-4024-a1d3-e618b3252bd4.mp4

**Comment by darkwater4213** [comment]
Okay, thanks.

(How did I completely miss that?)

**Comment by Gusted** [comment]
> (EDIT:) Wait, it doesn't give a "don't invert this element" option... H'm. :/ )

#3034
