### ISSUE TITLE
[Broken Website] Notepad Plus Plus

### ISSUE THREAD

**Issue by natewrench** [darkreader/darkreader#7702]
# Broken Website Report

## Website Address
https://notepad-plus-plus.org/

## Steps To Reproduce
Turn on the dark reader
Go to notepad plus plus
Observe the logo is inverted from a green logo to a pink-purple logo.

## Expected Behavior
The Logo should still be green and not inverted

## Actual Behavior
The logo turned pink or purple

## Screenshots
https://imgur.com/ucu6rsM

## System Information
Brave Browser Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
Dark Reader 4.9.43

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by NguyenASang** [comment]
@natewrench This error is not caused by Dark Reader, It's that website's dark mode.

**Comment by Gusted** [comment]
As above, this isn't a dark reader bug.
