### ISSUE TITLE
[Broken Website] Coolblue search bar

### ISSUE THREAD

**Issue by Masqueey** [darkreader/darkreader#7719]
# Broken Website Report

## Website Address

https://www.coolblue.nl/

## Steps To Reproduce

1. Issue 1: Search bar
- Go to the website
- Click the search field.
- Notice the results overlapping the search field.

2. Issue 2: Category buttons
- Hover the mouse over any of the category buttons.
- See the drop-down menu form a list longer than the screen.

## Expected Behavior

Expected behaviour 1: See the search bar with the search results below it.
Expected behaviour 2: Have the categories in the drop-down menu formed into columns that fit the screen.

## Actual Behavior

Issue 1: The search results only appear half on the screen and overlap completely with the search bar.
Issue 2: The categories shown are longer than the screen and in a single column.

## Screenshots

Issue 1:
![image](https://user-images.githubusercontent.com/19656058/147158867-3c97a45c-5240-4102-96ec-ac026a0db0d1.png)

Expected 1:
![image](https://user-images.githubusercontent.com/19656058/147158718-5d15fd31-998e-4e08-9db7-962af4de83cd.png)

Issue 2:
![image](https://user-images.githubusercontent.com/19656058/147158836-bbe7fe4c-91d8-4817-8adb-6732a176374a.png)

Expected 2:
![image](https://user-images.githubusercontent.com/19656058/147158771-2f94157a-e55b-4bcc-9c4a-f836c2b6b7e6.png)

## System Information

- OS: Linux *(Kernel: 5.15.7-1-MANJARO)* 
- Browser: Firefox 95.0.1 
- Dark Reader Version: 4.9.43 

## Additional Context
Something I only noticed when I tried to make the screenshots is that some weird Christmas banner also completely covers the main page. (See picture below, no clicking on the site required.) I think all these issues are related though, that is why I reported them as one issue.

Expected 3:
![image](https://user-images.githubusercontent.com/19656058/147159516-9cabb872-8fd3-4c92-bdcc-bdbf30773f0b.png)

Actual 3:
![image](https://user-images.githubusercontent.com/19656058/147159287-c3b63ce3-a260-4a79-a449-33023bae0148.png)

**Comment by Gusted** [comment]
It's fixed in the next release, dark reader didn't consider a edge case of something we proxied 😅.
