### ISSUE TITLE
Discord (Global Dark list)

### ISSUE THREAD

**Issue by daephx** [darkreader/darkreader#773]
The web client is inverted when it doesn't need to be and I cannot edit the global list

**Comment by SoftwareN00b** [comment]
I had no issues with that, open DarkReader extension:

Go to **_"Site List"_**
Add discordapp.com or whichever domain you don't want to be inverted inside the _"**Not Invert Listed**"_

That should fix it, at least it did for me. If not, then enable settings only for discordapp website and set DarkReader to be disabled.

**Comment by DaemonPhoenix42** [comment]
Hmm, thanks. I originally wasn't able to toggle the extension on the site, with it being greyed out claiming it was on the dark list. Doesn't seem to be so anymore.

**Comment by SoftwareN00b** [comment]
Happy to hear that you solved it, in that case, this issue is solved. Enjoy the darkness!

**Comment by alexanderby** [comment]
Somebody added "discordapp.com/channels" to the [list of Dark Sites](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config). If you are sure the website has white pages, feel free to edit this file and submit a Pull Request.

**Comment by andersfylling** [comment]
Im having issues with discordapp as well. I prefer the discord dark theme, but whenever i jump back to the tab darkreader rerenders the colours a bit. Really weird.. just added discordapp.com/channels to the list as well, so hopes up

**Comment by Gusted** [comment]
#2979
