### ISSUE TITLE
Firefox colorways overridden by dark reader

### ISSUE THREAD

**Issue by jazzba1** [darkreader/darkreader#7741]
On Firefox browser startup in Windows 10 , colorways(theme?) gets overridden by "Dark Reader"...

**Comment by Gitoffthelawn** [comment]
Which areas are getting overridden?

**Comment by jazzba1** [comment]
The theme on the browser header (using colorway) will start out fine...but soon changes as the extension starts. With dark reader disabled it's ok and if you apply the theme with "colorways" after browser startup it's ok.

**Comment by Gitoffthelawn** [comment]
Interesting.  I'm not aware of Dark Reader changing anything outside of the viewport (that's where the web page content lives).  It will be interesting to learn what @Gusted thinks is happening.

Does it just happen with Colorways themes, or all themes?  Does it depend if it is a light browser theme versus a dark theme?

**Comment by jazzba1** [comment]
Any theme (tried four)...if you toggle dark reader on, it changes then toggle it off it goes no theme...I thought it might be colorways...but maybe not.

**Comment by Gusted** [comment]
> On Firefox browser startup in Windows 10 , colorways(theme?) gets overridden by "Dark Reader"...

Use the provided bug report next time or use [discussions](https://github.com/darkreader/darkreader/discussions).

But you've most likely enabled the setting to enable that Dark Reader is styling the browser's theme.

**Comment by jazzba1** [comment]
Yep...didn't see that
