### ISSUE TITLE
Dark Reader hides background images of <Div>

### ISSUE THREAD

**Issue by arvandf** [darkreader/darkreader#7751]
# Broken Website Report

## Website Address
https://mui.com/premium-themes/onepirate/

## Steps To Reproduce
Go to https://mui.com/premium-themes/onepirate/
Take notice of the the big image in the middle
Enable dark reader
The image is invisible now

## Expected Behavior
Be able to see the image

## Actual Behavior
The image is visible when dark reader is disabled

## Screenshots
![image](https://user-images.githubusercontent.com/66641605/147413301-328d90e5-84b8-4c61-a7d7-e475053c0dc7.png)

With Dark Reader enabled:
![image](https://user-images.githubusercontent.com/66641605/147413309-d644fe84-1e32-473d-8c2b-d43fdba5ed13.png)

## System Information

- OS: 
- Browser: Chrome
- Dark Reader Version: latest version

**Comment by Gusted** [comment]
It doesn't seem to be possible to fix this without re-structuring the site (which we obviously can't).

**Comment by arvandf** [comment]
@Gusted How can this be solved for future references? Does a background in a `<div>` cause issues with Dark Reader?

**Comment by Gusted** [comment]
> @Gusted How can this be solved for future references?

Solved? It cannot be solved in this particular instance.

> Does a background in a `<div>` cause issues with Dark Reader?

Not in your 99% cases, but some are problematic made like these whereby they are forced to be on the lowest z-level which causes problems with how dark reader behaves.
