### ISSUE TITLE
[Broken Website] breitbart.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#7761]
# Broken Website Report

## Website Address
https://www.breitbart.com/

## Steps To Reproduce
Open https://www.breitbart.com/. Scroll to end site. 

## Expected Behavior
All socials links should be inverted.

## Actual Behavior
Parler icon is not inverted.

## Screenshots

![20211227-1640602921](https://user-images.githubusercontent.com/9846948/147465678-b0012c3d-bd4c-49ef-bac8-9e0eb062cda3.png)
![20211227-1640602910](https://user-images.githubusercontent.com/9846948/147465682-63fc5100-b2dd-4e3a-ad97-e74523280937.png)

## System Information

- OS: Windows 11
- Browser: Edge Chromium latest stable
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Well, for some reason they made parler special, by using a direct background-image on the element instead of using `::before` like the other ones.
