### ISSUE TITLE
[Broken Website] xbox.com/en-US

### ISSUE THREAD

**Issue by rhyshighrise** [darkreader/darkreader#7776]
# Broken Website Report

## Website Address
https://www.xbox.com/en-US/

## Screenshots
![OnPaste 20211228-170043](https://user-images.githubusercontent.com/96730029/147554656-7daf9440-b550-49ec-9381-656eebd76b11.png)

## System Information

- OS: Windows
- Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Fixed in the next version.
