### ISSUE TITLE
Firefox not inverting Video color but Chrome does.

### ISSUE THREAD

**Issue by bmbeverst** [darkreader/darkreader#779]
I have been using the Chrome version but now that you support Firefox I am moving back to it. I noticed that the video's on canvas.vt.edu are inverted in Chrome, which I like, but not in Firefox. It looks like the Chrome implementation is "broken" but I would like to "break" Firefox in the same way.

How can I configure DarkReader on Firefox to invert the colors of videos on canvas.vt.edu?

Thanks in advance.

P.S. This issue seems related: https://github.com/darkreader/darkreader/issues/313

**Comment by alexanderby** [comment]
Hi, on what website this happens? Are you using Filter mode?

**Comment by bmbeverst** [comment]
I am using the filter mode.

It is on the Virginia Tech college internal class site but the media is hosted on by Kaltura. I am not able to reproduce the inversion in with any of their other videos.

Here is a screen shot from Chrome. I would like Firefox to also invert the colors.
![screenshot_20181108_213335](https://user-images.githubusercontent.com/603632/48239719-fc79a000-e39d-11e8-920b-856f8233fc79.png)

**Comment by bmbeverst** [comment]
Just noticed some thing, Firefox does correctly invert the colors when the video is full screen. This does not occur on Youtube, no inversion full screen or not.

Is there a way to control which sites have inverted video?

**Comment by alexanderby** [comment]
Please reopen if there is still the same issue.

**Comment by bmbeverst** [comment]
Thanks, I just graduated, so I can't retest. @snoop2head thanks for the PR!
