### ISSUE TITLE
can you publish this in npm?

### ISSUE THREAD

**Issue by FounderIsShadowWalker** [darkreader/darkreader#780]
Can you convert  this as a tool we can import in project.
Or just set a function({
  mode
  brightness,
  contrast
})
we really need this function in project.
thanks for your read.

**Comment by alexanderby** [comment]
You can try using CSS variables to change your website theme dynamically. Also when Dark Reader is on, use this script to collect all dark stylesheets (except inline stylesheets):
```javascript
Array.from(document.querySelectorAll('.darkreader:not(.darkreader-inline)')).map((style) => style.textContent).join('\n');
```

You should review it because images links could point to generated ones, that are not persistent.

**Comment by Gusted** [comment]
https://www.npmjs.com/package/darkreader
