### ISSUE TITLE
Cannot run 'npm run debug'

### ISSUE THREAD

**Issue by doubleUTF** [darkreader/darkreader#784]
Hi,

I've installed the latest repo and all the dependencies but cannot run debug mode as instructed. Please help; here is the text of the error message:

Setup:
darkreader: 4.6.9
NodeJS: v10.12.0
npm: 6.1.0
Win7
```
npm run debug

darkreader@4.6.9 debug F:\App_Projects\Chrome-extensions\darkreader
gulp debug

gulp[17256]: src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.
 1: 000000013F3AACB5
 2: 000000013F3844E6
 3: 000000013F3845B1
 4: 000000013F35A15A
 5: 000000013FBA33A2
 6: 000000013FBA44F8
 7: 000000013FBA385D
 8: 000000013FBA377B
 9: 00000083FC65C5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! darkreader@4.6.9 debug: `gulp debug`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the darkreader@4.6.9 debug script.
npm ERR! This is probably not a problem with npm. There is l
```ikely additional logging output above.

**Comment by alexanderby** [comment]
Hi, I've updated the dependencies today. I'm using macOS Mojave and Windows 10, Node LTS (it is currently 8 and become 10 in 3 days).

Also I'm going to remove Gulp so I hope this issue should go away.

**Comment by alexanderby** [comment]
If you see vulnerabilities report, it is not actually a vulnerability for you.

**Comment by doubleUTF** [comment]
Great, downloaded the latest repo and 'npm test' works fine. Thank you!

**Comment by doubleUTF** [comment]
Right, what I meant was that running 'npm run debug' and 'npm test' both work fine now.
