### ISSUE TITLE
[Broken Website] blog.sina.com.cn

### ISSUE THREAD

**Issue by shenzhiming88** [darkreader/darkreader#7849]
# Broken Website Report

## Website Address

http://blog.sina.com.cn/s/blog_41457d530102vhqj.html

## Steps To Reproduce

Go to this page

## Expected Behavior

Text and background should change color

## Actual Behavior

Text and background don't change color

## Screenshots

![image](https://user-images.githubusercontent.com/66902050/148083576-72a6fcad-ff51-4e58-b23c-989efe3b5981.png)

## System Information

- OS:  Windows
- Browser:  Edge 96.0.1054.62
- Dark Reader Version:  4.9.43

## Additional Context

This is the blog page, but everyone's blog is set up with a different background. So it may not be possible to make global changes.
You can find more pages on http://blog.sina.com.cn/, some of them are normal.

**Comment by Gusted** [comment]
> This is the blog page, but everyone's blog is set up with a different background. So it may not be possible to make global changes.
> You can find more pages on http://blog.sina.com.cn/, some of them are normal.

These are pretty "problematic" sites, I can't do much for these sites as they all rely on a lot of different background-images. Which are hard to modify statically. The result will argueable looks worse then it already is. Not much to do, you could use the `Filter` theme for these websites.
