### ISSUE TITLE
postgresql.org INVERT #pgContentWrap

### ISSUE THREAD

**Issue by mathieucaroff** [darkreader/darkreader#785]
Dark Reader fails to color correctly most elements on postgresql.org. (See [this example page from the documentation](https://www.postgresql.org/docs/10/static/sql-createview.html)). Text is black on black, and `<pre>` and `<code>` elements are still black on white. A simple line fixes this:

```
================================

postgresql.org

INVERT
#pgContentWrap
```

**Comment by alexanderby** [comment]
Should be fixed by recent changes. Will publish soon.
