### ISSUE TITLE
[Broken Website] witkowskibartosz.com

### ISSUE THREAD

**Issue by xeruf** [darkreader/darkreader#7851]
# Broken Website Report

## Website Address
http://www.witkowskibartosz.com/blog/pythonstartup_what_it_is_and_how_to_use_it.html

## Screenshots

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/13354331/148107972-22703c4d-d911-4efd-974d-63bbd4e29a30.png">

## System Information

- OS: Arch Linux
- Browser: Firefox
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
Same issue as #5937 (Always HTTPS-mode causes this)

**Comment by xeruf** [comment]
I do have that enabled, yes
