### ISSUE TITLE
[Broken Website] https://addons.mozilla.org/en-US/firefox/

### ISSUE THREAD

**Issue by EmirLogas** [darkreader/darkreader#7859]
# Broken Website Report

## Website Address

https://addons.mozilla.org/en-US/firefox/

## Expected Behavior

turning on dark mode.

## Actual Behavior

dark mode won't turn on.

## Screenshots

https://ibb.co/9srF2r1

## System Information

- OS:  Windows 10
- Browser:  Firefox 95
- Dark Reader Version:  Version 4.9.43

**Comment by Gusted** [comment]
The site is a protected site, Firefox doesn't permit extension to modify such sites.

**Comment by dewcked** [comment]
To make any changes to protected sites, easiest way is to use console manually like [this](https://gist.github.com/dewcked/c896c3004f483e4fa602054d097ad2a1).

**Comment by PreciousBiscuit** [comment]
@Gusted 
I disagree. This clearly an issue in this plugin, because every other plugin in my Firefox is able to modify this and every other mozilla page.
