### ISSUE TITLE
Select filter/dynamic per website

### ISSUE THREAD

**Issue by hutattedonmyarm** [darkreader/darkreader#786]
Currently the dynamic/filter toggle is global. But since some websites look better in dynamic and some look better in filter mode, I'd like to toggle the mode on a per website basis

**Comment by alexanderby** [comment]
Do you mean the Safari app version? Chrome and Firefox already have these features.

**Comment by hutattedonmyarm** [comment]
Yep, I mean the safari version

**Comment by fdoyon** [comment]
Same, Safari needs per-site customisation as well. It is really annoying to have to manually switch between Filter and Dynamic depending on which site you are visiting.

**Comment by alexanderby** [comment]
So, it is about to be published to the store.

<img width="999" alt="screen shot 2018-11-16 at 20 42 56" src="https://user-images.githubusercontent.com/9638588/48637972-50106d00-e9e0-11e8-96e0-246daf7caa3a.png">

**Comment by fdoyon** [comment]
Cool! Good luck with the review process! Thanks for the hard work!
