### ISSUE TITLE
Can't use negative look around in regex url matcher - can't use ? in regex at all

### ISSUE THREAD

**Issue by ackvf** [darkreader/darkreader#7866]
My Dark Reader is set to "Enabled by default" with an exclusion list of disabled sites. I want to disable dark mode on all `localhost` pages **EXCEPT** on api pages that output unstyled json. In other words, I want to keep my styles on pages I develop and enable dark mode on api pages that are light by default.

Here is my little test for "**Disable on these websites:**" list:
```
["localhost:3000/api/1", "localhost:4000/sub/api/v1/1", "localhost:5000", "localhost:5001/another", "localhost:9001/faces/1_small.jpg"].map(s => {
  return /localhost(:\d+)?($|\/(?!(api|sub\/api)))/.test(s)
})
// [false, false, true, true, true]   // <- this is the desired result
```

Such regex basically allows me to easily modify a list of paths I want in dark mode within this brace of the negative lookahead `(api|sub\/api)`.

However, this test reveals that the function `createUrlRegex` removes everything after first occurence of `?`, wrongly assuming that it is an url query.

```
new RegExp(createUrlRegex('localhost(:\d+)?($|\/(?!(api)))').toString().replace('/^(.*?\\:\\/{2,3})?([^/]*?\\.)?(','').replace(')(\\/?.*?)$/i',''))
// /localhost(:d+)/
```

The relevant code of `createUrlRegex()`
https://github.com/darkreader/darkreader/blob/7b525bb000f0555da0e2990dd0dcd858024b3c26/src/background/config_management.ts#L340

This is the chain I followed to get here
https://github.com/darkreader/darkreader/issues/147#issuecomment-355755674
https://github.com/darkreader/darkreader/issues/86#issuecomment-355656408

**Comment by Gusted** [comment]
Next time, use the [disccusion](https://github.com/darkreader/darkreader/discussions) tab or follow the issue template.

The code you've linked is quite quite old and not used anymore for a long time. The current matcher doesn't allow custom regex, #2517 will solve this tho. But currently this is not supported.
