### ISSUE TITLE
[Broken Website] Icons become squares in some websites.

### ISSUE THREAD

**Issue by DeFaLT-dj** [darkreader/darkreader#7868]
# Broken Website Report

## Website Address

https://feedbackportal.microsoft.com/feedback/
## Steps To Reproduce

- Go to https://feedbackportal.microsoft.com/feedback/
- Switch dark reader on
- icons on the website become squares
## Expected Behavior

icons stay same with what they are
## Actual Behavior

icons change with squares
## Screenshots

before dark reader activated

![image](https://user-images.githubusercontent.com/64617514/148257786-17ecb216-3e42-4728-b048-552d5af3e394.png)

after dark reader activated (changed icons marked with red)

![image](https://user-images.githubusercontent.com/64617514/148257853-297861f5-2d90-4a53-8595-911c66e6fe52.png)

## System Information

- OS:  Windows 11
- Browser:  Microsoft Edge 96
- Dark Reader Version:  4.9.43

**Comment by Gusted** [comment]
Hi @DeFaLT-dj!

Do you have by any chance, custom fonts enabled?
These causes issues with icons(as most font's cannot render them).

Regards,
Gusted

**Comment by DeFaLT-dj** [comment]
> Hi @DeFaLT-dj!
> 
> Do you have by any chance custom fonts enabled? These causes issues with icons(as most font's cannot render them).
> 
> Regards, Gusted

Hi, yes now I tested and that was the problem, after turning off the custom font the issue is resolved. Thanks for your quick reply!
