### ISSUE TITLE
[iOS Safari] Are you able to port to the iOS App Store now that you've got this for Safari on macOS?

### ISSUE THREAD

**Issue by ylluminate** [darkreader/darkreader#787]
Absolutely elated with having Dark Reader in Safari now.  Looking forward to feature parity with Chrome at some point (for example, I like to operate in inverted mode where it leaves it off by default and I have to flip it on to darken the site), but this is such a wonderful start!

Are you going to be able to bring this to iOS now that it's been ported to macOS?  My iPad Pro experience would be orders of magnitude better to have it there now as well...

**Comment by alexanderby** [comment]
This is only possible as a separate browser app.

**Comment by Vortetty** [comment]
i don't believe this is possible, it may be (i dont know because i use android), but from what i have seen it is not, maybe a bookmarklet that imports js but i am not sure.

**Comment by alexanderby** [comment]
Done https://apps.apple.com/us/app/dark-reader-for-safari/id1438243180?platform=iphone
