### ISSUE TITLE
[Broken Website] bugs.chromium.org

### ISSUE THREAD

**Issue by shssoichiro** [darkreader/darkreader#7885]
# Broken Website Report

## Website Address
Example page: https://bugs.chromium.org/p/aomedia/issues/detail?id=3211

## Steps To Reproduce
- Navigate to issue details page

## Expected Behavior
- The two lines of help text above the "Add a Comment" box should have a darkened background

## Actual Behavior
- The two lines of help text are unreadable because they are white text on a light cream background.

## Screenshots
![bugs chromium org](https://user-images.githubusercontent.com/5951392/148466837-48880f78-9925-410e-bc1a-01666d60f9ff.png)

## System Information
- OS: Windows 10
- Browser: Firefox 95.0.2
- Dark Reader Version: 4.9.43

## Additional Context
Similar issues have occurred with this site in the past (#6449)

**Comment by nclsbayona** [comment]
It happens to me also.
OS: Windows 11
Browser: Microsoft Edge
Dark Reader Version: 4.9.43

**Comment by shssoichiro** [comment]
I found a few more items on the same site:

Issue details page: https://bugs.chromium.org/p/aomedia/issues/detail?id=2717

- The headers for each reply comment, plus the message body for system-generated comments (e.g. Label Changed) are unreadable.
- The Dropdown box next to the search bar is unreadable

![issue_details](https://user-images.githubusercontent.com/5951392/149601278-9f2e9e68-42c0-4db9-8d55-8bf96b7ccab0.png)

Issue list page: https://bugs.chromium.org/p/aomedia/issues/list

- The Dropdown box next to the search bar is unreadable (same as above)
- The header bar is difficult to read
- The buttons in the top right corner are unreadable

![issue_list](https://user-images.githubusercontent.com/5951392/149601290-cc08643b-6a3c-4a0f-9088-422b71b75b1d.png)

**Comment by Gusted** [comment]
#8432
