### ISSUE TITLE
[Bug] White flash when moving through the emails in Thunderbird

### ISSUE THREAD

**Issue by amarel123** [darkreader/darkreader#7894]
# Bug Report

## Bug Description
When I move through the emails in my inbox, the background of messages turns white for 1 second before Dark Reader colors it. It is worth to mention that I have dark theme turned on (but bug occurs in white mode too). Messages showed in pane and in new window are affected.

## System Information

- OS: Fedora 35
- Application: Thunderbird 91.4.0
- Dark Reader Version: 4.9.39

**Comment by Gusted** [comment]
Hi @amarel123!

Do you have your system's preferred color scheme set to dark?
You can check this by your browser(Firefox, they use the same underlying engine).
- ctrl + shift + i
- Go to the console tab.
- Execute the following code: `matchMedia('(prefers-color-scheme: dark)').matches`. Check if this returns true.

Regards,
Gusted

**Comment by amarel123** [comment]
Yes I have. It returns true. I can't use white because my eyes hurt :)

**Comment by Gusted** [comment]
In that case there isn't much to do, as our fallback(which prevents white flashes ASAP) style is then loaded. Thunderbird has it quirks with rendering, as unlike Firefox, they render ASAP and doesn't wait until some content is loaded. You could try to fiddle with thunderbird's setting. I know there is a color setting somewhere, that might be of impact which color is chosen for this unrendered content.

**Comment by amarel123** [comment]
Thank you so much :)

**Comment by Krzysztof318** [comment]
> Thank you so much :)

Did you find any solution?

**Comment by amarel123** [comment]
> > Thank you so much :)
> 
> Did you find any solution?

I have had the plugin disabled for the last year. Now I turned it on and everything works fine. I am using Fedora Linux 38, Thunderbird version 102.15.1, Darkreader version 4.9.39.

**Comment by Krzysztof318** [comment]
I have latest th 115.3.1 SUPERNOVA. Could you update also and check again?

**Comment by loyukfai** [comment]
Here (https://www.reddit.com/r/Thunderbird/comments/15z3ktv/tb_v115_dark_theme_dark_reader_white_flashes/) says to 

`Try: Settings - Colors - Override the colors... set to Always.`
