### ISSUE TITLE
Bitbucket flickering

### ISSUE THREAD

**Issue by rwdrich** [darkreader/darkreader#790]
I'm not quite sure how to describe it, and I can't (NDA) record a screencast of this issue. But when I'm on my company's bitbucket pages, for example reviewing a pull request, moving the mouse around on the screen causes a redraw, which makes the screen flicker. It's quite jarring, and has prompted me to turn off dark reader for that page

**Comment by ylluminate** [comment]
@rwdrich does it look like the screencast that I shared as per @kytwb's [mention](https://github.com/getferdi/ferdi/issues/358)?

**Comment by rwdrich** [comment]
Sorry for the slow response. I forgot I'd raised this bug. For some reason a while ago I turned the dark reader back on, and haven't seen this issue since - so I forgot all about it.
I've just watched the above screencast, and that looks like what I had previously - but I'm unable to reproduce this now. 
It looks like the issue is contained enough within that other bug report, and I can't reproduce mine, so i'm going to close this now.
