### ISSUE TITLE
[Bug] Invert logos on page is not performed properly in first visit page. 

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#7905]
# Bug Report

## Bug Description
Invert images on page is not performed properly in first visit page. 

## Website Address

https://spidersweb.pl/rozrywka
https://tvn24.pl/tvnmeteo/pogoda/warszawa-cid1046800

## Steps To Reproduce
1. Go https://spidersweb.pl/rozrywka
2. Logo is not inverted.

1. Go https://tvn24.pl/tvnmeteo/pogoda/warszawa-cid1046800
2. See page parts. 

## Expected Behavior
Proper looking inverted parts.

## Actual Behavior
Only CSS rule from darkreader extension works first time load. INVERT is ignored first time.

## Screenshots
First time visit
![20220110-1641798930](https://user-images.githubusercontent.com/9846948/148729964-4e311e63-0460-4d49-9bb0-8fe43b28183f.png)
Disable DR for site
![20220110-1641798941](https://user-images.githubusercontent.com/9846948/148730001-b373418c-4273-4212-ba68-48f98e05d88b.png)
Enable DR for site second time
![20220110-1641798949](https://user-images.githubusercontent.com/9846948/148730039-a6a2d4fd-f5f7-4dad-a6a6-07b6daafce43.png)

First time visit
![20220110-1641799643](https://user-images.githubusercontent.com/9846948/148730757-d8db729b-3243-45c1-a7ac-5610c59779a3.png)
![20220110-1641799636](https://user-images.githubusercontent.com/9846948/148730758-5d0ceb02-aaf2-4589-b322-537903ce5872.png)
Disable DR
![20220110-1641799452](https://user-images.githubusercontent.com/9846948/148730512-ae206903-2e09-4ac0-a78a-867bf4a7605a.png)
Enable DR for site second time
![20220110-1641799461](https://user-images.githubusercontent.com/9846948/148730508-f2f3fa3e-b6b2-4ce4-864b-eb1982b9bb93.png)

## System Information

- OS: Windows 11
- Browser: Edge Chromium Stable latest
- Dark Reader Version: git from https://github.com/darkreader/darkreader/commit/1ebc15ecc962b9a3bc0e61b6edab95471345ee52 release build.

**Comment by Gusted** [comment]
Both sites are different issues. From the first site, I cannot reproduce this behavior. It always gets the INVERT from the background script and is applied correct. The second site is a broken behavior with custom-elements, which has been tracked on the issue from virustotal.com(which is really noticeable broken behavior)

**Comment by FadeMind** [comment]
@Gusted ReLaunch Edge "fix" issue with spidersweb.pl site. Closing.
