### ISSUE TITLE
[Bug] YouTube banner images are gone

### ISSUE THREAD

**Issue by Hulayki** [darkreader/darkreader#7913]
# Bug Report

## Bug Description
I can't see the banner image of the youtube channels.

## Website Address
Example: https://www.youtube.com/c/markiplier or any other youtube channel site.

## Steps To Reproduce
Just fill it with the specified color.

## Expected Behavior
The banner image.

## Actual Behavior
Nothing.

## Screenshots
![notworking](https://user-images.githubusercontent.com/97475801/148835111-5a11db9f-3c57-4087-a53a-978f44b69b31.png)

## System Information
- OS: Windows 10
- Browser: Chrome 96
- Dark Reader Version: 4.9.34

## Additional Context
Banner images are not appeared.

**Comment by Gusted** [comment]
#7915
