### ISSUE TITLE
[Broken Website] Nperf.com speedtest does not inherit dark mode when test starts

### ISSUE THREAD

**Issue by Zorrototo** [darkreader/darkreader#7925]
# Broken Website Report

## Website Address

https://www.nperf.com

## Steps To Reproduce

- Go to https://www.nperf.com
- Click the button to start a speed test
- Notice the speedtest becomes white when the test starts

## Expected Behavior

The speedtest application should stay in dark mode

## Actual Behavior

The speedtest becomes white

## Screenshots

https://i.imgur.com/UNrEv55.jpg

## System Information

- OS:  Manjaro KDE
- Browser:  Firefox 95.0.2
- Dark Reader Version:  4.9.43

## Additional Context

There is a dynamic change withing the speedtest when the test starts, some elements change dynamically

**Comment by nclsbayona** [comment]
It happens to me also.
OS: Windows 11
Browser: Microsoft Edge
Dark Reader Version: 4.9.43

**Comment by Zorrototo** [comment]
Thanks a lot for the lightning speed fix :+1:
