### ISSUE TITLE
[Bug] Darkreader stuck in Loading, please wait.

### ISSUE THREAD

**Issue by DeFaLT-dj** [darkreader/darkreader#7927]
# Bug Report

## Bug Description

I was adding some websites to my dark reader list which I use often, then I saw the UI is gone in the extension. I tried to deactivate and activate it again but now it is stuck in the loading screen. 
NOTE: I just tried it on my Edge Canary version as well and it still works as expected. It also synched the websites I added before it is gone so I think adding too many websites wasn't the problem. Tried restarting browser first and it didn't solve. Then I restarted my PC and still nothing. I am thinking about removing and installing it again, but I don't want to lose my data in it. Can we do that without losing the data?
## Steps To Reproduce

I was just adding a website for the list for which websites I want to use dark reader then this happened. Maybe I added too many websites so it couldn't handle it?
## Expected Behavior

It works properly 
## Actual Behavior

It stuck in an infinite loading loop. I realized it also broke some websites on this state, because it can't access my website list. It is trying to adopt every website to dark mode, but the dark mode also broken again because it can't load properly. 
## Screenshots

Here is the picture of how it looks. It just entered an infinite loading loop like this.

![image](https://user-images.githubusercontent.com/64617514/149069400-68dbe180-aa4d-429c-b119-ce1c2184a72d.png)

## System Information

- OS:  Windows 11
- Browser:  Microsoft Edge 97/ Microsoft Edge Canary 99
- Dark Reader Version:  4.9.43

**Comment by Gusted** [comment]
Well. could you have a look `chrome://extensions` and check if the dark reader extension has any errors? It could be that you've hit some kind of data corruption.

**Comment by DeFaLT-dj** [comment]
> 

Nope it doesn't show any errors. Yeah that is what I thought and probably reinstall it again with saving the list.

**Comment by OscarDL** [comment]
Hey there, commenting to share that I'm having a similar experience. Loading forever, even after disabling / re-enabling the extension.

Yesterday I got tired of the fact that my sites whitelist wasn't syncing between my laptop and desktop anymore, so I dug into settings to find it wasn't enabled (weird...), so I enabled it. And today the extension refuses to load. Not sure if that has anything to do with sync or not, but that might help find the root of the issue.

**Comment by DeFaLT-dj** [comment]
> Hey there, commenting to share that I'm having a similar experience. Loading forever, even after disabling / re-enabling the extension.
> 
> Yesterday I got tired of the fact that my sites whitelist wasn't syncing between my laptop and desktop anymore, so I dug into settings to find it wasn't enabled (weird...), so I enabled it. And today the extension refuses to load. Not sure if that has anything to do with sync or not, but that might help find the root of the issue.

I didn't really find the solution tho. I just removed and reinstalled it however you lost your data like white-listed websites as expected. Thankfully I copied them so I just re-add them much more easily.

**Comment by thunderstone135** [comment]
I'm also getting this "Loading, please wait" error. The last version that worked for me was 4.9.34. After that, all new versions (including 4.9.45) give me the "Loading, please wait" error.

**Comment by thunderstone135** [comment]
By the way, I'm getting "(destructured parameter) is undefined 2 index.js:1226" in the Browser Console and it points to the line "chrome.runtime.sendMessage({ type, data }, ({ data, error }) => {"

**Comment by Gusted** [comment]
> I'm also getting this "Loading, please wait" error. The last version that worked for me was 4.9.34. After that, all new versions (including 4.9.45) give me the "Loading, please wait" error.

Do you use Firefox? You might have changed your useragent in the `about:config`? That will break some detection in dark reader(which includes that line).

**Comment by thunderstone135** [comment]
> > I'm also getting this "Loading, please wait" error. The last version that worked for me was 4.9.34. After that, all new versions (including 4.9.45) give me the "Loading, please wait" error.
> 
> Do you use Firefox? You might have changed your useragent in the `about:config`? That will break some detection in dark reader(which includes that line).

You nailed it. Thanks, dude 👍

**Comment by CollinChaffin** [comment]
Same here on Chrome. If I enable the new design, backup my config which includes a pretty big site list, all is ok until I enable sync. Not the whitelist - that is ok but the first main sync option. Once enabled - extension is dead - not only hangs forever at loading, but despite being loaded, no sites go dark. Yet, no errors shown in extension error logging. It just seems like it's hung in a loop and is all about sync because as long as I don't enable that one setting, on multiple machines, it's fine - but ALL of them break when sync enabled.

**Comment by DeFaLT-dj** [comment]
> Same here on Chrome. If I enable the new design, backup my config which includes a pretty big site list, all is ok until I enable sync. Not the whitelist - that is ok but the first main sync option. Once enabled - extension is dead - not only hangs forever at loading, but despite being loaded, no sites go dark. Yet, no errors shown in extension error logging. It just seems like it's hung in a loop and is all about sync because as long as I don't enable that one setting, on multiple machines, it's fine - but ALL of them break when sync enabled.
> 
> EDIT: Yes, I have completely removed the extension, started from scratch and restored my export backup - all is okay but the sync is disabled on my restore, and once I enable it - dead.

Yeah this happens on new design so much. Enabling break it sometimes. Not always kills it like this but reverts all your changes and go back to the old design. Thanks to we can make local copy of our settings and doesn't matter it breaks or not we can continue where we left off.

**Comment by Gusted** [comment]
@ImportTaste Please see #9516

**Comment by Gusted** [comment]
Closing anyway.
