### ISSUE TITLE
Site List toggle button collapsed

### ISSUE THREAD

**Issue by alexanderby** [darkreader/darkreader#794]
Most likely this is caused by https://github.com/darkreader/darkreader/commit/497b8909502e3bbc267440b24632c18d04afe2dd

![image](https://user-images.githubusercontent.com/9638588/47603532-b4e63200-d9f5-11e8-81a6-377a3f9ff8a6.png)

**Comment by ahmadm-atallah** [comment]
can not reproduced! what is your scenario?

**Comment by alexanderby** [comment]
I think the more records is added into list, the more top button gets collapsed.

**Comment by ahmadm-atallah** [comment]
That is not the case in chrome canary. Though, this behavior happened when I tried it out in chrome stable version!. I will check it out

**Comment by alexanderby** [comment]
The class value is applied incorrectly in Toggle component.
