### ISSUE TITLE
[Broken Website] Duolingo characters broken

### ISSUE THREAD

**Issue by noxan-dev** [darkreader/darkreader#7946]
# Broken Website Report

## Website Address

Duolingo (Japanese if that matters)

## Steps To Reproduce

- Go to Duolingo
- Select Japanese
- Play until complete a lesson
- It May take a bit to get the faces that it affects, the endings are random

Here is an example:
- Go to example.com.
- Hover over the example button.
- Notice that when hovering over the example button, it does not change color.
-->

## Expected Behavior

Faces to be light

## Actual Behavior

Faces get darkened

## Screenshots

face in dark mode
![image](https://user-images.githubusercontent.com/59417659/149383133-37eee333-1477-443a-86cb-2e10684a09c7.png)

faces in light mode
![image](https://user-images.githubusercontent.com/59417659/149383449-59f49f23-266b-4f3f-abc1-85bb3def3f24.png)

## System Information

- OS:  Windows 10
- Browser:  Opera 82.0.4227.43
- Dark Reader Version:  4.9.34. I copied the updated config files from the more recent updates. I cannot update due to the sidebar on my browser injecting dark mode into Twitter, Instagram, and the rest. except for WhatsApp and Messenger.

**Comment by Gusted** [comment]
We don't support outdated versions. Please use the latest(next version when opera fix is included).

**Comment by noxan-dev** [comment]
> We don't support outdated versions. Please use the latest(next version when opera fix is included).

ok, I can do that. I also tested on Edge using the latest version and it's the same effect

**Comment by Gooberpatrol66** [comment]
Could this be reopened? I'm getting this on the latest version (4.9.57)

**Comment by Gusted** [comment]
@Gooberpatrol66 Please open a new issue, this had invalid information.
