### ISSUE TITLE
[Broken Website] sci-hub.se PDF issues

### ISSUE THREAD

**Issue by eduardoftdo** [darkreader/darkreader#7949]
# Broken Website Report

## Website Address
[sci-hub.se](https://sci-hub.se/10.1145/3422622)

## Steps To Reproduce

(1) If I have **dark mode turned on** and go to sci-hub, the **sidebar is in dark mode** but the **PDF file is in light mode**. 
(2) Now ​if I turn **dark mode off**, the **sidebar changes to light mode** and the **PDF file changes to dark mode**

Now that light mode is on if we refresh the website:
(3) Both the sidebar and the PDF are in light mode and finally, turn dark mode on, (4) both the sidebar and PDF are in dark mode, the expected behavior

## Expected Behavior

When going to the site with dark mode on, both the sidebar and PDF file should be in dark mode

## Screenshots

![1](https://user-images.githubusercontent.com/46848448/149393291-9e3644c2-1903-406a-9804-c4ed8bf60d1e.png)
![2](https://user-images.githubusercontent.com/46848448/149393374-c17fc58c-f020-4b30-ab15-da2dfd07c623.png)
![3](https://user-images.githubusercontent.com/46848448/149393413-bbf1105f-78e6-4bed-85fa-cda147fb9cfb.png)
![4](https://user-images.githubusercontent.com/46848448/149393439-d5784637-db00-42a3-a0bb-d59b6ad48dc8.png)

## System Information

- OS: Windows 10
- Browser: Chrome 97
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Hi @eduardoftdo!

I cannot reproduce this behavior, do you have any kind of setting enabled on chromium that could interfere with this?

Regards,
Gusted.

**Comment by eduardoftdo** [comment]
Hey @Gusted I have enabled the access to local files option in the settings so Dark Reader can convert them to dark mode, which generally works but for this site I’ve had this issue for some time now

**Comment by eduardoftdo** [comment]
Hey, @Gusted Just FYI I'm still having the same issue on Chrome. Does this fix only work in the next version release, or should it be working already?

PS: On Firefox, I don't have this issue.

**Comment by Gusted** [comment]
> Does this fix only work in the next version release, or should it be working already?

It will work on the next version release.
