### ISSUE TITLE
[Broken Website] MSN sports not adapting dark mode properly

### ISSUE THREAD

**Issue by DeFaLT-dj** [darkreader/darkreader#7953]
# Broken Website Report
Microsoft Start (formerly MSN) Sport doesn't adapt to dark mode properly
## Website Address

https://www.msn.com/en-us/Sports/?ocid=msedgntphdr&pfr=1 (use the whole link because if you just use the main part, it will redirect you to the old version of it)

## Steps To Reproduce

- Go to https://www.msn.com/en-us/Sports/?ocid=msedgntphdr&pfr=1
- Activate dark reader
## Expected Behavior

All elements adapt to dark mode properly
## Actual Behavior

Some parts remain white or uses the wrong colors
## Screenshots

As you can see that bar still uses light mode and Microsoft Start logo uses the wrong colors.

![image](https://user-images.githubusercontent.com/64617514/149580122-c45f987f-5244-495c-ae5c-aee81f778ca7.png)

The side bar which opens when you click to hamburger menu also remains in light mode.

![image](https://user-images.githubusercontent.com/64617514/149580246-cb35a3ea-208e-46c5-9d54-311edeaf91e1.png)

## System Information

- OS:  Windows 11
- Browser:  Edge 97
- Dark Reader Version:  4.9.43

**Comment by Gusted** [comment]
Closing as wont fix. that part uses a system([closed shadow-dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM)) which we cannot access as a extension. Not possible to fix it or to work around it.

**Comment by DeFaLT-dj** [comment]
> Closing as wont fix. that part uses a system([closed shadow-dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM)) which we cannot access as a extension. Not possible to fix it or to work around it.

Yeah, I realized it too since I couldn't access it view other extension. Thanks.
