### ISSUE TITLE
[Bug] issue #7608 is still an issue

### ISSUE THREAD

**Issue by KevinDevs** [darkreader/darkreader#7958]
# Bug Report

## Bug Description

​ Uncaught TypeError: Cannot read properties of null (reading 'disableStyleSheetsProxy')
    at createStaticStyleOverrides (VM41573 darkreader.js:4859:62)
    at createThemeAndWatchForUpdates (VM41573 darkreader.js:5012:9)
    at createOrUpdateDynamicTheme (VM41573 darkreader.js:5122:13)
    at Object.enable (VM41573 darkreader.js:5268:9)
    at <anonymous>:1:12
## Steps To Reproduce

simply add the js file in the website and execute 
DarkReader.enable({
    brightness: 100,
    contrast: 90,
    sepia: 10
});
code in console
## Expected Behavior

the website should look the same like how extension acts
## Actual Behavior

website broken
## System Information

- OS: MacOS
- Browser: Chrome latest version
- Dark Reader Version: 4.9.43

**Comment by Malarkey-Jhu** [comment]
Same here

**Comment by Malarkey-Jhu** [comment]
How did you solve this? @KevinDevs
