### ISSUE TITLE
[Bug] Login issues with 'Turnitin' document submission service when using Dark Reader

### ISSUE THREAD

**Issue by jfisher8** [darkreader/darkreader#7962]
# Broken Website Report

## Website Address
portal.uclan.ac.uk

## Steps To Reproduce
- Add portal.uclan.ac.uk to the extension's list of dark mode enabled sites
- Go to portal.uclan.ac.uk
- Login to the site
- Navigate to the relevant submission portal and click on the blue 'Submit' button
- 'Login to Turnitin' screen is displayed as opposed to the system allowing me to upload a document for marking even though I'm already logged into the university's Learning Management System (LMS)

## Expected Behavior
I expect to be able to click the 'Submit' button to start a new submission attempt and after this, be sent to the usual screen on which the submission portal allows me to upload a file for marking and submit it as an official attempt

## Actual Behavior
After I click on the 'Submit' button I'm met with a screen that asks me to log in to my Turnitin account. I do not have such an account as there shouldn't be a need for one, as I have access to all the required resources in my university's LMS through the use of my university credentials

## Screenshots
The screenshot below is of the DevTools window within Chrome after the extension is enabled and I try to access the Turnitin portal.
![image](https://user-images.githubusercontent.com/92530530/149637599-e8d0d018-7589-4b82-9119-eda5ad925239.png)

## System Information
- OS: Windows 10
- Browser: Chrome version 97.0.4692.71
- Dark Reader Version: 4.9.43

## Additional Context
It's one of my university's sites that I'm having this issue with (called Blackboard) so I'm not sure how much you'll be able to do to try and fix this issue, but I'm not sure why I'd be getting asked to log into the service we use for uploading documents when I should already have access via my university login. It's not the biggest deal in the world but it'd be beneficial to not be blinded by the site's overly-light light mode, every time I want to submit a document for an assignment. If it can't be fixed because of the nature of the site then it's fine, just thought I'd at least make it known as if a fix can be found, I'd appreciate it, Thanks in advance for taking the time to read this.

**Comment by Gusted** [comment]
I think it's better for you to shoot a email to the school IT department, as for why. As a user, such information won't be discoverable, it's most likely some security measurement that dark reader is triggering. Not much to do here.
