### ISSUE TITLE
No effect on XML files

### ISSUE THREAD

**Issue by a-jackson** [darkreader/darkreader#799]
When viewing xml files I just the get the brower's default theme with a white background. Is it possible to support this?

**Comment by The-Black-Fox** [comment]
Hey this interferes with  JSON readers. is there a way to disable the dark reader theme on JSon files / extensions

**Comment by AndrewDaGuy** [comment]
> When viewing xml files I just the get the brower's default theme with a white background. Is it possible to support this?
@a-jackson  I don't think so, but you can make dark reader still enable on restricted pages:

1. Update your dark reader to the latest version (`4.9.29`) *(Its probably on a really really old version)*
2. Open the dark reader panel
3. Click `Dev Tools`
4. Go to the `Dark Reader developer tools` window
5. You should see a button named `Preview new design` on the right of the `Apply` button
6. Click it and it should change to `Switch to old design` (You can close the Dev tool window now)
7. Now navigate to `Settings` in the dark reader panel
8. Click `Site List`
9. Toggle `Enable on Restricted Pages`
10. I think you also have to enable a flag? (Maybe ask Guested for this one :[. )

> Hey this interferes with JSON readers. is there a way to disable the dark reader theme on JSon files / extensions

@The-Black-Fox You can report the broken websites to us and we can fix it :]

**Comment by Gusted** [comment]
> When viewing xml files I just the get the brower's default theme with a white background. Is it possible to support this?

Nope. XML styling is a pain for nothing.



>     10\. I think you also have to enable a flag? (Maybe ask Guested for this one :[. )

No.


> Hey this interferes with JSON readers. is there a way to disable the dark reader theme on JSon files / extensions

JSON Readers hijack JSON and display them into a nice and readable HTML format. Which due to being on an normal URL we can without a problem inject into. But no such way to detect this, you could report them and see if their is an solution.

**Comment by AndrewDaGuy** [comment]
> No.

So the "You should enable it in browser flags too" under the toggle for `Enable on Restricted Pages` should be removed?

**Comment by Gusted** [comment]
> So the "You should enable it in browser flags too" under the toggle for `Enable on Restricted Pages` should be removed?

XML isn't a restricted page.

**Comment by The-Black-Fox** [comment]
Would there be a way to add custom rules for url Suffixes.

For example if i created a rule for  `*.json`, any url ending in .json will use the custom settings. in this case, not work on .json urls.
