### ISSUE TITLE
[Bug] Automation doesn't work on Android

### ISSUE THREAD

**Issue by DKMikolajczyk** [darkreader/darkreader#7996]
# Bug Report

## Bug Description
Automation doesn't work for Firefox on Android. When I set a specific time range, after reaching the selected time, nothing happens.

## Steps To Reproduce
Just set automation on Android Firefox and wait for a specific time.

## Expected Behavior
Dark mode will turn on after reaching of specific time.

## Actual Behavior
After reaching a specific time nothing happens. But if you will go to the setting and turn off/on automation, the correct mode will turn on.

## System Information

- OS: Android 11
- Browser: Firefox 95.2.0
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Hi @DKMikolajczyk!

Do you have by any chance `privacy.resistFingerprinting` in `about:config` enabled?

Regards,
Gusted

**Comment by DKMikolajczyk** [comment]
Hello @Gusted 

I can't even enter `about:config` on the Firefox for Android.

But in the `Enhanced Tracking Protection` options, I have checked `Fingerprinters`.

![ff_settings](https://user-images.githubusercontent.com/98054335/150208802-2b3be7df-52b1-4eae-8a96-c4e42babf4ca.jpg)
