### ISSUE TITLE
[Feature Request] Ability to use brightness and contrast without selecting theme

### ISSUE THREAD

**Issue by PeterNjeim** [darkreader/darkreader#7997]
# Feature Request

Ability to use brightness and contrast without selecting theme. For those that like the dark theme that a website provides, but simply want to adjust the brightness and contrast (potentially all the other options as well).

**Comment by Gusted** [comment]
Technically this feature request isn't possible or compatible with our current codebase as it requires to use a theme, and I don't think it's the worth to implement such feature as it's not within the scope of dark reader anymore if it doesn't darken the site anymore.
