### ISSUE TITLE
[Broken Website] messenger.com

### ISSUE THREAD

**Issue by limitedmage** [darkreader/darkreader#8019]
# Broken Website Report

## Website Address

https://www.messenger.com

## Steps To Reproduce

- Go to messenger.com and chat with people
- Observe income chat bubbles

## Problematic Observation

- Chat bubbles for income chats are unreadable
- Rounded corners for chat input have a white background
- Scrollbar in the chat window is white

## Screenshots
![image](https://user-images.githubusercontent.com/206864/150578339-80e59c3c-4f07-4a73-9d1a-1222db6c90f9.png)

## System Information

- OS: macOS 12.1
- Browser: Safari 15.2
- Dark Reader Version: 1.4.5

**Comment by cycool29** [comment]
+1

**Comment by Salil999** [comment]
When will this release to the App Store?

**Comment by alexanderby** [comment]
Works fine for me.
