### ISSUE TITLE
[Broken Website] The <link> element is broken

### ISSUE THREAD

**Issue by XIGUAjuice** [darkreader/darkreader#8043]
# Broken Website Report

## Website Address

https://2heng.xin/

## Steps To Reproduce

Just go to https://2heng.xin/

## Problematic Observation

The `<link>` element is broken. The attribute `media` is changed to `media=only x`. It's grammatically wrong, I think the *x* here may be a variate and something goes wrong let it to be a string.

## Screenshots

![image](https://user-images.githubusercontent.com/43206983/150900948-2b724b93-5be2-4119-ac52-5c93ac2e208c.png)

## System Information

- OS: Windows
- Browser: Edge Version 97.0.1072.69 (Official build) (64-bit)
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
> The `<link>` element is broken. The attribute `media` is changed to `media=only x`. It's grammatically wrong, I think the _x_ here may be a variate and something goes wrong let it to be a string.

I'm not sure what to expect here, Dark reader just assumes it's good, it's a bit intense to go implement a full parser to check for correctness... It doesn't seem to be breaking anything.

**Comment by XIGUAjuice** [comment]
![image](https://user-images.githubusercontent.com/43206983/151167041-78f5f44c-a1b7-4103-805a-e9a0a264f964.png)
It should be `media=all` here if I turn off Dark reader.

**Comment by Gusted** [comment]
> It should be `media=all` here if I turn off Dark reader.

Well, dark reader doesn't those other element's media. So it's a bug from the website that we cannot fix, even if we caused it.
