### ISSUE TITLE
[Feature Request] Separate setting for incognito windows, or to be able to turn on light/dark mode for incognito windows

### ISSUE THREAD

**Issue by retews** [darkreader/darkreader#8044]
It would be great to have a separate setting for incognito windows, or to be able to turn on light/dark mode for incognito windows separately, so that if I use normal mode and use a dark youtube theme and I have a YouTube Dark Reader is an exception, then when you open YouTube in incognito mode, I could turn on a dark topic from Dark Reader.

**Comment by Gusted** [comment]
Use the template next time, duplicate #4779
