### ISSUE TITLE
[Bug] Sync in Firefox or Chrome causes Dark Reader settings to reset to an earlier version

### ISSUE THREAD

**Issue by shssoichiro** [darkreader/darkreader#8056]
# Bug Report

## Website Address
N/A

## Bug Description
When using Dark Reader on multiple computers and Firefox Sync or Chrome Sync is enabled, Dark Reader settings will frequently reset to a previous version of the settings. This seems to occur even if I only have the browser open on one computer. This is annoying because I lose several of the sites I've added to the whitelist/blacklist and have to add them multiple times.

## Steps To Reproduce
- Have Dark Reader on two browsers which are synced to each other.
- Add a blacklist item or change from "Ignore Listed" to "Not Ignore Listed"
- Wait a few minutes
- The setting you changed will be reset to what it was before

## Expected Behavior
- When syncing, sync should always prefer the most recent version of settings

## Actual Behavior
- Sync seems to prefer the version of settings in the cloud, regardless of if it is the most recent, and will override local settings with it frequently

## Screenshots
N/A

## System Information
I've been experiencing this issue for a few months, across several Firefox and Chrome versions, on Windows, macOS, and Linux machines. I have been using the latest Dark Reader version from either Chrome Web Store or Firefox Extensions, respectively, through the entire time. This is always with the latest stable version of the browser at the time.

## Additional Context
N/A

**Comment by joewilliams** [comment]
I've been experiencing this problem as well with firefox 96.0 on linux and mac.

**Comment by Gusted** [comment]
Could you both checkout #8059 and see if that fixes the issue? I'm not able to setup any syncing on browsers, so I'm not able to test the patch myself.

**Comment by shssoichiro** [comment]
I still encountered the issue after setting up Firefox on both of my machines with the updated plugin. 🤔

**Comment by OscarDL** [comment]
Having a similar issue here as well. I don't fully understand the issue @shssoichiro is having, but here, site list doesn't sync at all anymore since a couple of days now (4.9.43). Pretty annoying, and also the new design preview just reverts itself back to the old one for no reason at random times.

**Comment by Gusted** [comment]
> Having a similar issue here as well. I don't fully understand the issue @shssoichiro is having, but here, site list doesn't sync at all anymore since a couple of days now (4.9.43, which is the same as the binaries shared in #8059). Pretty annoying, as the new design preview also just reverts itself back to the old one for no reason at random times.
> 
> Edit: When the old design randomly comes back, it deletes my entire whitelist now, so I keep losing every single website I disable after maybe 1 to 2 hours.

Hmmh, seems like there might be a bug in chromium's sync storage? As it might be that it's somehow receiving "update" events out of thin air(I cannot come up with any other logical reasoning, as it only seems to be happening with sync storage). I think I should just remove the code altogether that updates the syncing as it has been causing bugs before which where a PITA to fix and resolve.
