### ISSUE TITLE
[Broken Website] cnbc.com (CNBC make it)

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#8069]
# Broken Website Report

## Website Address
https://www.cnbc.com/2021/12/25/burnout-coach-best-books-about-self-care-and-mental-health.html

## Steps To Reproduce
- Enable DR dynamic dark mode
- Go to this page: https://www.cnbc.com/2021/12/25/burnout-coach-best-books-about-self-care-and-mental-health.html
- Notice logo is hard to read
- Notice white text on aqua-colored swirly background is hard to read

## Expected Behavior
Everything easy to read

## Actual Behavior
See details in *Steps to Reproduce*

## System Information
- OS: Linux
- Browser: Firefox 96
- Dark Reader Version: 4.9.43

**Comment by Gitoffthelawn** [comment]
@Gusted Thanks.  What about the white text on the aqua-colored swirly background (near the top of the page) that is hard to read?

**Comment by Gusted** [comment]
> @Gusted Thanks. What about the white text on the aqua-colored swirly background (near the top of the page) that is hard to read?

They are not in a good sweetspot as if we would invert them:
![image](https://user-images.githubusercontent.com/25481501/151853192-659b69ab-7240-48ee-a94e-35cca7c74512.png)

And some variants on it doesn't look either as the original, so best to leave it IMO, until someone will scream about it and have better color solution.

**Comment by Gitoffthelawn** [comment]
This should be a big improvement:
div[class^="FeaturedStories-styles-makeit-background"]::before {
  opacity: 0.1 !important; }

You like?  If so, I'll add it.

**Comment by Gusted** [comment]
Seems good to me.

**Comment by Gitoffthelawn** [comment]
Fixed also by #8101. Closing now.
