### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by sileeb** [darkreader/darkreader#8072]
Google Shopping is broken with DR. Its inverted. Please fix this. 

![21](https://user-images.githubusercontent.com/73712645/151739078-f22dd789-eb7f-4e10-aa3d-fc363a1e4fc8.png)

**Comment by Gusted** [comment]
Please use template.

**Comment by sileeb** [comment]
Ok... I'll go ahead and file a new issue with new template.
