### ISSUE TITLE
[Feature Request] Add an option to change the background color

### ISSUE THREAD

**Issue by xmha97** [darkreader/darkreader#8073]
Please add an option to change the background color:

❌ Actual Behavior
![image](https://user-images.githubusercontent.com/23485114/151747891-e7348ffe-f3c5-49e1-82d8-1486b7fd0b0c.png)

✔️ Expected Behavior
![image](https://user-images.githubusercontent.com/23485114/151748339-7de5d90f-6b0a-4f08-91d5-97c4f6d3e3b0.png)

**Comment by Gusted** [comment]
Use provided template + see many many other issues about this, it's already possible.
