### ISSUE TITLE
[Firefox] Pages empty after 4.6.10 update

### ISSUE THREAD

**Issue by scotu** [darkreader/darkreader#808]
I am aware this is a terrible quality bug report but am I the only one experiencing an Halloween bug on Firefox? I should be on default configs (besides tuning contrast and brightness on some specific sites)
 
Extension worked almost perfectly until late in the afternoon of today, Oct 31. Then suddenly all pages are solid dark grey for one monitor worth of the top part of screen (no text is visible), scrolling down a page or so you can see the rest of the page in correct alternate colors. 

Thanks for the extension by the way, super impressive work!

**Comment by alexanderby** [comment]
The pumpkin is a temporary effect.

Could you please send a screenshot? What is your OS?

**Comment by atsimerman** [comment]
Same problem, browser - chrome.

**Comment by alexanderby** [comment]
@atsimerman Could you please attach a screenshot and steps to reproduce?

**Comment by atsimerman** [comment]
![image](https://user-images.githubusercontent.com/15799319/47854996-f149d180-ddeb-11e8-89bd-878492495752.png)

Steps to reproduce:
- enable Dark Reader extension,
- open browser and try to search something in google

**Comment by atsimerman** [comment]
I noticed this because of a conflict with another extension. When I disabled it Dark Reader start worked fine again.

**Comment by alexanderby** [comment]
@scotu it would be great, if you post a screenshot and steps to reproduce. I've found one error, that happens on many websites due to Firefox bug, and going to release it soon.

**Comment by alexanderby** [comment]
Version 4.6.12 contains some possible fixes, please, have a look.

**Comment by scotu** [comment]
@alexanderby attaching a screenshot, of this very page https://github.com/darkreader/darkreader/issues/808 I'll try 4.6.12

![Uploading Screenshot_2018-11-01 In Firefox most pages get full dark above the fold (text and background) at the same time the extensi[...].png…]()

**Comment by scotu** [comment]
looks like the size of the full dark area at the top depends on the size of the browser window btw

**Comment by scotu** [comment]
And looks like 4.6.12 solves the problem (or at least it's not happening anymore) :)

Thanks!

**Comment by alexanderby** [comment]
Do you have some other extensions installed?

**Comment by scotu** [comment]
yeah, I'll try to deactivate some and report back

**Comment by alexanderby** [comment]
Wait, I to install them and try too. Maybe some content blocker causes network errors, and Dark Reader script hangs.

**Comment by Earlopain** [comment]
Have the same issue and the culprit seems to be Saka Key which injects a div to all pages. When I remove the div everything is as it's supposed to be. 
![image](https://user-images.githubusercontent.com/14981592/47881725-4525dc00-de27-11e8-9d98-c6d1617ff8bc.png)

**Comment by alexanderby** [comment]
@Earlopain Thank you, I will check **Saka Key** extension too. There also was a report, that **Shut Up: Comment Blocker** extension causes browser to hang: it infinitely competes with Dark Reader who's stylesheet will be on top, and this competition eats up all the resources.

**Comment by scotu** [comment]
thanks to both :) can confirm that the interaction with saka key seems to be the culprit in my case

**Comment by Gusted** [comment]
A lot of improvements had been :eyes: Could you check with the latest version of Dark reader(4.9.9) That this issue with extension still persist?

**Comment by Gusted** [comment]
CC @Earlopain @scotu

**Comment by Earlopain** [comment]
Everything seems to be working fine for me.
I wasn't using Saka Key for quite a while now but installed it so I can test.

Both Github and Reddit load without issue

**Comment by Gusted** [comment]
Good to hear,

Have a nice day :D
