### ISSUE TITLE
[Feature Request] Dark mode only where you need it

### ISSUE THREAD

**Issue by qavu1** [darkreader/darkreader#8089]
# Feature Request

## Is this feature request related to a problem?

I think it could fix many problems.

## Screenshots

No needed.

## Additional Context

It would be great if DarkReader could analyze the base color of a web page to decide whether to make it dark or not. For example, if the website's base color is light make it dark, otherwise ignore it.

Now I have to add websites with dark mode support (e.g. GitHub, Twitch, etc.) to my ignorelist because it looks so ugly with DarkReader.

**Comment by Gusted** [comment]
See #7995, also many other issues are open(sort by :+1:) about this. Closing.
