### ISSUE TITLE
[Bug]  POPUP windows.print() on google chrome  not working (about:blank)

### ISSUE THREAD

**Issue by mean-cj** [darkreader/darkreader#8092]
# Bug Report

## Website Address
about:blank

## Bug Description
When i open the popup from javascript
google chrome show url is "about:blank"
**but windows.print() doesn't work**

i have add url "about:blank" to "invert listed only"  it's not working 

## Steps To Reproduce
create index.html
```
<script>
       function Clickheretoprint() {
            var disp_setting = "toolbar=yes,location=no,directories=yes,menubar=yes,";
            disp_setting += "scrollbars=yes,width=750, height=600, left=100, top=25";

            var docprint = window.open("", "", disp_setting);
            docprint.document.open();
            docprint.document.write('<html><head><title>Popup/title></head>');
            docprint.document.write('<body style="background:none;padding-left:15px;" onload="window.print();window.close()">');
            docprint.document.write('<div class="container">TEST </div></div>');
            docprint.document.write('</body></html>');
            docprint.document.close();
        }
      Clickheretoprint();
</script>
```

## Expected Behavior
maybe can add "about:blank" to "invert listed only"

## System Information
- OS: Windows 10
- Browser: Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)
- Dark Reader Version: 4.9.43

## Additional Context
Thank you for very nice extension.

**Comment by Gusted** [comment]
I'm not really sure what's trying to be achieved here, but in general `about:blank` are protected pages and by default we don't style them. The provided example also doesn't seem to work on chromium/
