### ISSUE TITLE
[Broken Website] Confirming Your Response to Issue #8084

### ISSUE THREAD

**Issue by sileeb** [darkreader/darkreader#8104]
Hi Gusted.. I created issue #8084 previously but I never received your response about it. In your last response, you said the case is closed. Do you mean the error is fixed or that its presently being fixed and you'll update the addon soon? Jut so you know, the error still persists. 

Looking forward to your reply.

**Comment by Gusted** [comment]
The error has been fixed and will take into effect once the addon has been updated.
