### ISSUE TITLE
[Broken Website] this site background color is not correct pls check

### ISSUE THREAD

**Issue by zhenjie1999** [darkreader/darkreader#8110]
# Broken Website Report
## Website Address

<details><summary>URL:</summary>
https://hitomi.la/
</details>

## Problematic Observation

background turn to white, should be black
## System Information

- OS: windows 11
- Browser: chrome 98
- Dark Reader Version: dark reader 4.9.43

**Comment by Gusted** [comment]
We don't support NSFW sites.
