### ISSUE TITLE
[Bug] Dark reader loading forever

### ISSUE THREAD

**Issue by OhaDerErste** [darkreader/darkreader#8113]
# Bug Report

## Bug Description

When I click on the Darkreader Icon, It never finishes loading
## Steps To Reproduce

- Open Firefox
- click on the Icon
- It never finishes loafing

## Expected Behavior

I should see the GUI of Dark reader
## Actual Behavior

I don't see the GUI, it loads forever
## System Information

- OS: Arch Linux rolling
- Browser: Firefox 96.0.3 (64-bit)
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
Hi @OhaDerErste does `about:debugging#/runtime/this-firefox` -> "Dark Reader" -> "inspect" -> "console" show any errors?

**Comment by OhaDerErste** [comment]
It started working again randomly, idk

**Comment by Gusted** [comment]
Well, lets close it for now then, but feel free to re-open it if it happens again with the information requested in: https://github.com/darkreader/darkreader/issues/8113#issuecomment-1029195121
