### ISSUE TITLE
[Feature Request] Custom Style for Dynamic Theme

### ISSUE THREAD

**Issue by thatfatblackcat** [darkreader/darkreader#8114]
# Feature Request

## Is this feature request related to a problem?
Yes, I can't personalize the way webpages appear on dynamic theme.

## Additional Context
Sometimes you find a site that displays content as if you were on a smartphone while on the desktop or you want to change some colors on that site or globally because you feel like. I know these capabilities are in Dark Reader.

My suggestion would be making the `dev tools` button work outside the current browser session, permanently.

**Comment by Gusted** [comment]
This is pretty out of scope for a dark reader, use a dedicated tool for this, not dark reader.

**Comment by thatfatblackcat** [comment]
First, why would I need to install another extension when I want extra functionality ON TOP of dark reader? Second, If you really insist saying this wouldn't be helpful to people show me where's the line/block of code I need to change, so I can install manually.

**Comment by Gusted** [comment]
> First, why would I need to install another extension when I want extra functionality ON TOP of dark reader?

Dark Reader was made for a specific purpose, which didn't include being a Custom Style editor of some sort, we do have the dev tools functionality, but they should only be used to create and tests new fixes. It's not a supported functionality in the first place to use it like that, which I why I'd recommended stylus which purpose is to do that. 

> Second, If you really insist saying this wouldn't be helpful to people show me where's the line/block of code I need to change, so I can install manually.

🤷🏽 I'm not really sure what you mean. You _can use it_ as how you say, it isn't supported or endorsed by me.
