### ISSUE TITLE
[Broken Website] https://shop.surfboard.com/ - Round 2 - Couple of items need fixing

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8115]
# Broken Website Report

## Website Address
https://shop.surfboard.com/

## Steps To Reproduce
Visit website with Dark Reader enabled.
Notice the 3 items highlighted in red in the screenshot below that need to be optimized for Dark Reader.

## Problematic Observation
1. The Arris logo in top left corner needs to be fixed to make it more visible.
2. The magnifying glass icon and the word "Search" on the yellow button for the search field need to be fixed to make them more readable.
3. The envelope image needs to be fixed to make it more visible.

## Screenshots
![shop-surfboard-com-3-items-with-dr](https://user-images.githubusercontent.com/95879668/152225166-10aadc6f-5c95-4540-a5bb-7caf3d743e30.png)

## System Information

- OS: Windows 10 21H2
- Browser: Firefox Nightly 98.0
- Dark Reader Version: 4.9.43

**Comment by Gusted** [comment]
> Is it possible to also fix the envelope image in the screenshot above? (Item 3 in the report and screenshot? Item 3 is near the bottom of the screenshot.).

Unfortunately not, as it's not a standalone image, so targeting that specific image will end up inverting/modifying the whole element.

**Comment by q1800** [comment]
Alright, I understand. Thank you for your help. 😃
