### ISSUE TITLE
[Dynamic] Map stays bright when Google Maps is opened with regional TLD

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#812]
1. Open Google Maps with regional TLD, e.g. maps.google.ee, maps.google.ru, maps.google.de.

The map stays bright. Not reproducible with maps.google.com, the map is properly dark there.

**Comment by alexanderby** [comment]
Please, check in 15 minutes if the fix worked.

**Comment by krupenja** [comment]
Yep, confirm that this is fixed now.
