### ISSUE TITLE
[Feature Request] Ignore scrollbars in Edge (Windows 11 style)

### ISSUE THREAD

**Issue by boromyr** [darkreader/darkreader#8125]
# Feature Request

## Is this feature request related to a problem?

Since Edge introduced the new and improved Windows 11-style scrollbars, which automatically adjust to your browser theme, you no longer need to override the theme for these bars. Just enable edge://flags/#edge-overlay-scrollbars-win-style. If this flag is enabled, DarkReader should ignore scrollbars automatically. 

## Screenshots

![image](https://user-images.githubusercontent.com/52782032/152375002-1c38f1e5-19f6-4c44-a6e0-824fdc2f5618.png)![image](https://user-images.githubusercontent.com/52782032/152375925-12d73662-eccb-462f-a6f5-2449925caf3c.png)![image](https://user-images.githubusercontent.com/52782032/152376208-584f3b0b-43c0-4773-9efa-3889a3f6943f.png)
Comparison of Edge light, Edge dark, and Edge + DR.

## Additional Context

The “theme generation mode” is not affected by this issue, only the “classic” DR theme has this problem.
The target audience is for anyone using Edge or other browsers that have added similar functionality.

The addition of:
```
::-webkit-scrollbar-thumb:hover
::-webkit-scrollbar-thumb
::-webkit-scrollbar
::-webkit-scrollbar-track
```
to IGNORE INLINE STYLE had no effect.

**Comment by Gusted** [comment]
> If this flag is enabled, DarkReader should ignore scrollbars automatically.

This isn't possible.

See https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151

**Comment by boromyr** [comment]
> This isn't possible.

Because? Since the style is added by DR by logic, it might as well remove it.

> See #858

I had already followed that discussion, and tested the proposed solutions in vain. This FR is actually about the new scrollbars introduced by Microsoft last summer, discussion #858 is from 2018. In fact, these new scrollbars are not editable, nor are they accessible in dev tool mode.

Anyway, if you could point me to the file that inject the "::-webkit-scrollbar" styles, I'd be grateful.

**Comment by Gusted** [comment]
> Because? Since the style is added by DR by logic, it might as well remove it.

Because we have no knowledge whatever the new scrollbar is being used.



> Anyway, if you could point me to the file that inject the "::-webkit-scrollbar" styles, I'd be grateful.

https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L127

**Comment by younyokel** [comment]
Why can't I just turn off the change of the scrollbars manually? If I knew how, I'd want to disable them, but as it is, I have to use bold scrollbars and have different types of them everywhere.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/issues/858#issuecomment-887061151

**Comment by boromyr** [comment]
I actually managed to disable scrollbars by commenting a few lines of code, my fork doesn't change scrollbars in Edge. It seems strange to me that I can't add a simple on / off option that doesn't change the scrollbars globally.

**Comment by Gusted** [comment]
> It seems strange to me that I can't add a simple on / off option that doesn't change the scrollbars globally.

I now commented twice to a comment with instruction on how to disable them, is there something blocking you from executing these instructions that I missed?
