### ISSUE TITLE
Embedded tweets are bright on some websites

### ISSUE THREAD

**Issue by krupenja** [darkreader/darkreader#813]
Embedded tweets are bright on some websites with Dynamic theme, some examples:
https://www.bbc.com/news/world-us-canada-46079418
https://meduza.io/shapito/2018/11/01/ushla-zhena-snova-ne-vyspalis-kinokritik-anton-dolin-ob-yasnit-pochemu-prosto-zadayte-emu-vopros

![image](https://user-images.githubusercontent.com/26354715/47944262-239a2280-df03-11e8-95f2-6be267645852.png)

I think this is a regression and tweets were properly dark before

**Comment by krupenja** [comment]
Not reproducible everywhere though. Some examples where embedded are properly dark:
https://www.resetera.com/threads/embedded-tweets-not-working-for-anyone-else-or-is-it-just-me.16064/
https://help.twitter.com/en/using-twitter/how-to-embed-a-tweet

**Comment by piratetub** [comment]
@krupenja On my end, even your linked page has light colored embeds.

**Comment by Gusted** [comment]
Can be closed https://github.com/darkreader/darkreader/issues/471#issuecomment-399526003
![](https://i.imgur.com/C64FBqH.png)

@piratetub Could you make a seperate issue and provide some screenshot.

**Comment by krupenja** [comment]
Closing as I have not seen this anywhere recently.
