### ISSUE TITLE
Firefox extension inverts Image in Dynamic mode since last update.

### ISSUE THREAD

**Issue by Shishiaha** [darkreader/darkreader#8145]
Hello, I am using DarkReader since a long time with no issue in firefox (windows) last update. But since the last DarkReader update, it now inverts image content of website too while it was not before. I cannot use it anymore on most trading sites because of it.

I tried uninstalling it and reinstalling, but issue still is there, and as it was with the last update, little chances are this bug is on my side.

Thank you !

**Comment by zedekblue** [comment]
Also getting this issue on many sites since the last update. Examples included from two major sites amazon and youtube. Images seem to just get extremely oversaturated.
![Untitled](https://user-images.githubusercontent.com/17040113/152647733-2a4f39b7-2e00-4f87-985f-858da186292e.png)
.

**Comment by MadProbe** [comment]
It would be nice to have invertation of <img /> elements and background-image images as an option

**Comment by Gusted** [comment]
I've merged last release a experimental PR #6044 which I'd actually hope to not break _a lot of images_, but because having it in the code base also implies supporting it and already seems that it's causing far more issues than I'd expected I will be reverting it for now and create a new release.

**Comment by Gusted** [comment]
v4.9.45 has been tagged: https://github.com/darkreader/darkreader/releases/tag/v4.9.45
