### ISSUE TITLE
Text input fields unreadable: provide custom color choice or other effective solution

### ISSUE THREAD

**Issue by juanriccio** [darkreader/darkreader#8151]
I've searched for similar bug reports or feature requests, but I haven't found anything similar enough.

# Feature Request

## Is this feature request related to a problem?

Problem: text in input fields (including username/passwd) is hard to make out, white-on-yellow.
The attached screenshot is Amazon.com with the default color theme. The same happens on several (most?) other sites.

## Screenshots

![image](https://user-images.githubusercontent.com/11493605/152654868-4fc50795-7825-46bb-8911-6b6c5f3d9d28.png)

## Additional Context

Maybe a color choice could be provided just for text input fields?

**Comment by Gusted** [comment]
Is this only happening on amazon? If so, use the broken website template instead.

**Comment by juanriccio** [comment]
Thanks for your suggestion, @Gusted. The same happens with other sites, quite a few if not almost all of them.

**Comment by Gusted** [comment]
Okay so.

Are you by any chance using a password manager?
Which browser are you using?

**Comment by juanriccio** [comment]
No password manager. Just Firefox with the regular "Remember your password?" feature.

**Comment by Gusted** [comment]
> Just Firefox with the regular "Remember your password?" feature.

It seems like this is the culprit... According to the [information of MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill) we're not able to overwrite the `:autofill` style.

**Comment by juanriccio** [comment]
Ah! I see. Thanks for your reply.
But *something* gets changed by DarkReader, because those fields are not white-on-yellow originally.
Maybe an exception could be programmed: not to touch :autofill styled field at all, leaving them as in the plain unprocessed page?

I'm not nitpicking - this feels like a significant usability issue to me.

**Comment by Gusted** [comment]
> But _something_ gets changed by DarkReader, because those fields are not white-on-yellow originally.
> Maybe an exception could be programmed: not to touch :autofill styled fields at all, leaving them as in the plain unprocessed page?

It's not possible to get it changed, if you use the shortcut(alt + shift + a) you can see that the background-color doesn't change but the color does(which is because it's inheritance of other colors).



> Maybe an exception could be programmed: not to touch :autofill styled fields at all, leaving them as in the plain unprocessed page?

See above, it will inherit the colors from other elements, dark reader don't know or process the structure of the element nor does it know if a certain element is autofilled. It's a bummer on the browsers side to not allow this to be styled.

**Comment by juanriccio** [comment]
Ah, now I see: it does change but it's just inheritance; not DarkReader.
Thanks for the explanation @Gusted!
