### ISSUE TITLE
[Bug] Images appear washed out on all sites with bright images when DR is active

### ISSUE THREAD

**Issue by kobuki** [darkreader/darkreader#8156]
# Bug Report

## Website Address
All websites containing images with bright colors.

## Bug Description
Images appear washed out, "whitened", rendering pages ugly and images unrecognizable.

## Steps To Reproduce
- Go to any web site with bright images.
- Observe the colors in the images.

## Expected Behavior
- Images appear normally, untouched, with original colors.

## Actual Behavior
Images appear more bright, contrast is reduced, creating a washed out experience.

## Screenshots
I rolled back to 4.9.40 where the issue doesn't exist. Can't provide images at the moment, but I'll switch back to 4.9.44 and make comparison screenshots if requested.

## System Information
- OS: Windows 10, latest patches applied as of today
- Browser: Firefox 96.0.3 (64-bit)
- Dark Reader Version: 4.9.44

## Additional Context
The issue exists on 4.9.44 (latest in official FF repo), but doesn't exist on 4.9.40. I have no information on versions between.

**Comment by Gusted** [comment]
See #8145

**Comment by kobuki** [comment]
Oh, sorry for the noise then, I did search the issues but from the title it wasn't apparent the problems are related.

**Comment by Gusted** [comment]
No worries! I've pinned the issue for now.
