### ISSUE TITLE
[Bug] The brightness and contrast are interfering with the images

### ISSUE THREAD

**Issue by TrashPanda** [darkreader/darkreader#8158]
# Bug Report

## Website Address

Any website with pictures, good examples are Wikipedia, Instagram

## Bug Description

The brightness and contrast are interfering with the images. The images themselves are changed which force the user  to turn Darkreader off whenever the user wants to view the correct images. I don't think Darkreader did this in the previous versions

## Steps To Reproduce

- Use the latest version 4.9.44
- Go to a site with many images like Instagram, https://www.instagram.com/nike/
- Set the brightness and/or contrast to maximum or minimum (like 150%)
- Observe that brightness and/or contrast of the images are changed

## Expected Behavior

Images should remain the same.

## Actual Behavior

The brightness and contrast are interfering with the images

## Screenshots

Using Nike as an example. https://www.instagram.com/nike/

Original:
![image](https://user-images.githubusercontent.com/13948991/152690230-3a4dcca0-a279-4fbc-8411-7ecacf57a446.png)

150% contrast:
![image](https://user-images.githubusercontent.com/13948991/152690257-5ad3ee04-4f32-4bfd-b2e7-96cdabf87527.png)

150% brightness:
![image](https://user-images.githubusercontent.com/13948991/152690173-83fac95f-0a3a-4d56-bd9f-f1ac4de3569c.png)

## System Information

- OS: Windows 10 latest, macOS latest
- Browser: Chrome 97, Firefox 96
- Dark Reader Version:  4.9.44

**Comment by Gusted** [comment]
See pinned issue on issue tracker
