### ISSUE TITLE
[Bug] Images are faded in all sites

### ISSUE THREAD

**Issue by cgvirus** [darkreader/darkreader#8159]
# Bug Report

## Website Address
pinterest, facebook or any image in the site

## Bug Description
Images are faded in all filter ops

## Expected Behavior
Should not retouch the image color. 

## Actual Behavior
Fading images in the site

## System Information

- OS: <!-
Linux Mint 21
>

**Comment by alexanderby** [comment]
Hi. The fix will be published soon, it's currently under review. You can turn brightness and contrast to default.

**Comment by SamuelEddy** [comment]
Also experiencing this bug. It's apparent in all themes other than static for me

**Comment by zakwilson** [comment]
Setting the grayscale slider to zero seems to correct this for me; it was in the middle by default.

**Comment by speedingcheetah** [comment]
Thought there was some issue with Chrome and Brave. Driving me nutty.
This still is an issue.

**Comment by Gusted** [comment]
> Thought there was some issue with Chrome and Brave. Driving me nutty.
> This still is an issue.

Chromium webstore hasn't been updated yet by them. Can take a while.

**Comment by cgvirus** [comment]
[Solved] in version 4.9.45 . Checked with Chrome. Linux Mint 21.
Feel free to close the issue.
Thanks!
