### ISSUE TITLE
[Broken Website] Wikipedia

### ISSUE THREAD

**Issue by YellowSkarmory** [darkreader/darkreader#8160]
# Broken Website Report

## Website
[en.wikipedia.org](url)

## Reproduce
Go to any article on en.wikipedia.org, and go to edit in the visual editor.

## Problem
The top bar in the visual editor will pretty much disappear/change to black. Also, the notification bell/notice indicator also break.

## Screenshots
[Comparison](https://imgur.com/a/gGNx9Lb)

## System Information

- OS: macOS 
- Browser: Brave 1.32.106 
- Dark Reader Version: Don't know, but if relevant, the problem only started today a few hours ago. Could be a new update? 

## Comment
First time I've touched GitHub, so if anything breaks with this post, let me know.

**Comment by YellowSkarmory** [comment]
By the way, is there any way I can downgrade a version? Might fix the issue for me.

**Comment by SixelAlexiS90** [comment]
> By the way, is there any way I can downgrade a version? Might fix the issue for me.

I agree that we should have a way to downgrade in those cases of major faulty updates (which I don't know how it didn't got caught before release since how spread the problems is with images).

**Comment by Gusted** [comment]
> I'm clueless about how this whole thing works, but is the fix published yet? I still don't see it fixed, but it could just be not imported into the extension yet. (I also found a before the update image which I have added here.)

See https://github.com/darkreader/darkreader#site-fixes

**Comment by YellowSkarmory** [comment]
Thanks!
