### ISSUE TITLE
Surfing Keys hints don’t work anymore with darkreader Dynamic mode

### ISSUE THREAD

**Issue by kings2u** [darkreader/darkreader#8166]
# Bug Report

## Bug Description
Since updating to the current version as of the date of this posting, the letters of hints for the surfingkeys extension do not appear when using the Dynamic mode for darkreader.

## Steps To Reproduce
Install surfingkeys and darkreader.
Go to a website and press the f shortcut to bring up link hints.
The letters of the link hints do not appear if you’re using the Dynamic mode for darkreader.

## Expected Behavior
That I’d be able to see the hints, as I always have when using darkreader and surfingkeys together.

## Actual Behavior
The hints are invisible.

## System Information
- OS: Windows, macOS, Linux 
- Browser: Brave 1.35.100
- Dark Reader Version: 4.9.44

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/152882737-db377580-77c8-423d-ac85-bff8ff712475.png)

Seems all good on my side...

**Comment by pl643** [comment]
Hi King,

I have the Brave browser and installed Surfingkeys 1.03 along with DarkReader.  My background hint letters are inverted with white fonts (unlike yours).  Did you have to do something to not have Dark reader not change the hints forground color?

**Comment by TTTPOB** [comment]
![image](https://user-images.githubusercontent.com/19909103/153552909-050978b8-7815-450c-8139-6a3fe11eb9db.png)


i deleted the old extension and build the master branch, installed it, but it remains the same
is this the expected behaviourr

**Comment by Gusted** [comment]
> i deleted the old extension and build the master branch, installed it, but it remains the same
> is this the expected behaviourr

Are you sure it's the correct extension being enabled? As it still works for me on master.

**Comment by vsudakov** [comment]
I'm having the same issue as @kings2u and @TTTPOB in Google Chrome (v 98.0.4758.80).
I use the default settings for both DarkReader and SurfingKeys.
"Filter" and "Filter +" work fine but "Dynamic" mode - **not**.

**Comment by TTTPOB** [comment]
> > i deleted the old extension and build the master branch, installed it, but it remains the same
> > is this the expected behaviourr
> 
> Are you sure it's the correct extension being enabled? As it still works for me on master.

yes, I first deleted the extension from store and then installed self-built one, there is no chance to mix them

**Comment by kings2u** [comment]
The issue is persisting for me too :/

**Comment by Gusted** [comment]
Are you pretty sure you have the correct version built? It works for me on the latest master branch:

![image](https://user-images.githubusercontent.com/25481501/154246919-4417b0e3-15ac-466c-9d6e-405a9f6278d1.png)

**Comment by TTTPOB** [comment]
md5sum of built plugins

```bash
d3d458f97dfae9ef94e83b92fb1b479f  darkreader-chrome-mv3.zip
cd07eef198fcaed9b7b8f41899ba7a4c  darkreader-chrome.zip
9663a9b7691b8798a11a9316b18b328f  darkreader-firefox.xpi
0bc97e23a9e03da91ab0129901c567f6  darkreader-thunderbird.xpi
```
[darkreader-chrome.zip](https://github.com/darkreader/darkreader/files/8086881/darkreader-chrome.zip)

I used this from master, git log screen
![image](https://user-images.githubusercontent.com/19909103/154436525-2ab5a3c0-2078-461d-a4d6-3b17f542f4f7.png)

is this an update after the screenshot?

**Comment by TTTPOB** [comment]
hmmm that is too weird, maybe I am using ms edge so this is different? could that be possible?

**Comment by Gusted** [comment]
I'm not able to test ms edge atm, so it could be possible

**Comment by Gusted** [comment]
🤷🏽 Could be tomorrow or next week or next month.
