### ISSUE TITLE
Firefox Rendering Bug

### ISSUE THREAD

**Issue by K4YT3X** [darkreader/darkreader#817]
## When loading some sites, the page is stuck on the upper half of the page.

- Test site: https://assets.narexium.com/Resources/Night_Sakura_L.jpg
- Dark Reader Version: 4.6.12
- Mode: Filter & Filter+ (Static and Dynamic looks fine)
- Firefox Version: 63.0.1
- Platform: Linux (64-bit), Debian

Here's what it looks like with darkreader enabled:
![darkreader-ff1](https://user-images.githubusercontent.com/21986859/47972024-ca96cf80-e065-11e8-825b-32e8fae844eb.png)

Here's what it should look like:
![darkreader-ff2](https://user-images.githubusercontent.com/21986859/47972027-d2567400-e065-11e8-84ed-d25e869e5bfd.png)

**Comment by alexanderby** [comment]
I think this is duplicate https://github.com/darkreader/darkreader/issues/713

**Comment by K4YT3X** [comment]
I actually searched in the issues for duplicating issues, but I didn't see that one.

Anyways, there are other problems with the filter mode.
Sometimes a bottom bar will get stuck in the middle of the page, and there's no way of closing it.

I can provide screenshots latr if needed.

**Comment by alexanderby** [comment]
You can search for similar existing issues with this label https://github.com/darkreader/darkreader/labels/Firefox%20CSS%20filter%20bug

**Comment by K4YT3X** [comment]
@alexanderby perfect thanks.
