### ISSUE TITLE
[Feature Request] An additional `blue` slider for dark blue themes instead of just black/gray

### ISSUE THREAD

**Issue by zp33dy** [darkreader/darkreader#8185]
# Feature Request

## Is this feature request related to a problem?
No

## Additional Context
It would be nice if there would be something like a `blue` slider next to the `sepia` slider, that it would be possible 
to use a color theme like the one "Startpage" is using (or something in this direction)
Link to Startpage with the theme I am speaking about applied: [Startpage with theme dark](https://www.startpage.com/?sc=LKk2Tp3DqIqG20)

**Comment by Gusted** [comment]
See #650
