### ISSUE TITLE
[Bug] Vivaldi Reader view, dark reader is disable

### ISSUE THREAD

**Issue by ahmed-salem-me** [darkreader/darkreader#8190]
# Bug Report

## Bug Description
In Vivaldi, any website page, click Reader View, Vivaldi reloads page in reading view, and dark reader is not applied though it's still on for the page.
It works if you disable then enable dark reader.

## Expected Behavior
Dark reader should be applied after Vivaldi reload page in Reader view

## System Information

- OS: Windows 10 Pro
- Browser: Vivalidi 5.0.2497.48
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment]
The reader view is a "protected internal" page of Vivaldi, no extension can touch it. There's a setting in the top-right corner whereby you configure a dark mode.

**Comment by Gusted** [comment]
> But it seems your extension can touch it, as if I disable then enable dark reader while Reader view is on, dark reader works.

Ah dammit, seems like vivaldi is buggy then and differs from the other readers pages. It's _forcibly_ removing all dark reader styles, and they aren't able to restore... which is a problem.

**Comment by Gusted** [comment]
> and they aren't able to restore... which is a problem.

I'd gave it a go, and it seems like vivaldi is pretty strict so they don't even let the extension know that the element has been removed, so we actually never know that it entered reader mode.

**Comment by ahmed-salem-me** [comment]
> > and they aren't able to restore... which is a problem.
> 
> I'd gave it a go, and it seems like vivaldi is pretty strict so they don't even let the extension know that the element has been removed, so we actually never know that it entered reader mode.

Thanks, it would be great if it works, as we don't have to switch between color schemes between Vivalid and dark reader.
but if it doesn't we still have the two options, either vivaldi dark mode, or go off then on with dark reader.
