### ISSUE TITLE
[Feature Request] Lighter Grey Background

### ISSUE THREAD

**Issue by ahmed-salem-me** [darkreader/darkreader#8198]
# Feature Request

## Is this feature request related to a problem?
No

## Additional Context
Most Dark modes these days tend to use a lighter degree of grey color instead of black or very strong grey
And being able to control the degree of the grey background would be optimum
It's much easier on the eye and is based on couple of researches, plz look at this link for more info
https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/

**Comment by Gusted** [comment]
It's already possible to define your own colors, see #650. I'm not sure if the default colors should be changed.

**Comment by ahmed-salem-me** [comment]
> It's already possible to define your own colors, see #650. I'm not sure if the default colors should be changed.

Thank you, I found the option, I should have investigated more. 

As for default colors, it depends, if you want to encourage a color scheme that seem to be backed by few scientific researches to be better for the eyes. then maybe consider change default theme to that.

I think lots of people haven't actually tried the lighter grey backgrounds with a little off-white foreground and don't know it can be quite good !
