### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by ArushNath** [darkreader/darkreader#8207]
# Bug Report

## Bug Description
When taking a screenshot using Windows HDR and Dark Reader together on Brave - the screenshot taken is super bright.

## Expected Behavior
I expected the screenshot to look the same as the website with Dark Reader.

## Actual Behavior
The screenshot was very bright in comparison to the website.

## Screenshots
Super Bright screenshot:
![image](https://user-images.githubusercontent.com/71833603/153884403-8ec0b197-6df9-45bf-b7c9-1027b26f1239.png)

## System Information

- OS: Windows 11
- Browser: Brave Version 1.35.101 (Chromium 98.0.4758.87)
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment]
I would need more information on this bug:

- Does this happen without dark reader enabled?
- Which tool did you use to make this screenshot?
- Is it possible to disable HDR, and check if this still a bug.

Regards,
Gusted

**Comment by ArushNath** [comment]
**- Does this happen without dark reader enabled?** - No, the screenshot looks normal without the plugin enabled.
**- Which tool did you use to make this screenshot?** - I used the builtin Windows Snipping tool using win+shift+s in Windows 11.
- Is it possible

**Comment by ArushNath** [comment]
The screenshots are looking normal for now what should I do if the problem reoccurs?

**Comment by Gusted** [comment]
> for now what should I do if the problem reoccurs?

1. Check if the issue persists(e.g. create another screenshot).
2. Check if disabling dark reader helps.

Regards,
Gusted
