### ISSUE TITLE
[Bug] All my custom changes to Dynamic Theme Editor were deleted after last update of DR:(

### ISSUE THREAD

**Issue by iG8R** [darkreader/darkreader#8233]
# Bug Report

## Bug Description

On 2 PCs after updated to 4.9.45 all my custom changes made during last 2 years were deleted and Dynamic Theme Editor contains now only default data.

## System Information

- OS: Windows 10
- Browser: 97.0.1 (64-bit)
- Dark Reader Version: 4.9.45

## Additional Context

How could I return back all my data and what happened it'd be useful to know to not face this situation in the future?

**Comment by Gusted** [comment]
Well, it's never a guarantee that it won't revert, but if they show the default, then dark reader didn't found any local modifications. In the future? Use a extension that's dedicated for custom CSS, e.g. Stylus.
