### ISSUE TITLE
[Broken Website] IMDb partly broken, right side use white background color

### ISSUE THREAD

**Issue by Dreamer8** [darkreader/darkreader#8237]
# Broken Website Report
https://www.imdb.com/title/tt10665338/reference

## Website Address
https://www.imdb.com/title/tt10665338/reference

## Steps To Reproduce
Go to https://www.imdb.com/title/tt10665338/reference

## Problematic Observation
Right part of the site use white background instead of dark.

## Screenshots
https://i.postimg.cc/6QmDK10R/darkreaderimdb.png

## System Information
Firefox 97.0.1 (64-bit)

- OS: Windows 10 21H1 64-bit
- Browser: Firefox 97.0.1 (64-bit)
- Dark Reader Version: Dark Dreader 4.9.45

## Additional Context
It's broken with any movie.

**Comment by c-nagy** [comment]
Submitted the fix here: https://github.com/darkreader/darkreader/pull/8254/files
