### ISSUE TITLE
[Broken Website] bandshed.net

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8238]
# Broken Website Report

## Website Address
https://www.bandshed.net/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the white background in the screenshot below needs Dark Reader optimization.

## Problematic Observation
White Background

## Screenshots
![image](https://user-images.githubusercontent.com/95879668/154824283-0a43eff6-20df-49bb-bdc3-c6320eba7d81.png)

## System Information

- OS: Windows 11
- Browser: Firefox Nightly 99
- Dark Reader Version: 4.9.45

**Comment by c-nagy** [comment]
Just submitted a fix for this issue here: https://github.com/darkreader/darkreader/pull/8251/files
