### ISSUE TITLE
[Broken Website] kaos-community-packages.github.io

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8240]
# Broken Website Report

## Website Address
https://kaos-community-packages.github.io/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the logo in the screenshot below needs Dark Reader optimization.

## Problematic Observation
Logo

## Screenshots
![image](https://user-images.githubusercontent.com/95879668/154825924-57f11387-5e03-4193-a3b2-8d0423ada11d.png)

## System Information

- OS: Windows 11
- Browser: Firefox Nightly 99
- Dark Reader Version: 4.9.45

**Comment by c-nagy** [comment]
Sent in a pull request to fix this issue: https://github.com/darkreader/darkreader/pull/8250/files
