### ISSUE TITLE
[Broken Website] pipiwiki.com

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#8246]
# Broken Website Report

## Website Address

https://pipiwiki.com/wiki/Purcell_effect

## Problematic Observation

The math equations are not visible at all.

## Screenshots

![pic-selected-220221-1820-33](https://user-images.githubusercontent.com/59497618/154958770-d7b886ca-187f-41e6-8f6f-72242a293fdf.png)

## System Information

- OS:  Linux
- Browser:  Firefox 97
- Dark Reader Version:  4.9.45

**Comment by c-nagy** [comment]
I was able to reproduce the issue and submitted a fix here: https://github.com/darkreader/darkreader/pull/8249/files
