### ISSUE TITLE
High RAM usage with dynamic theme on https://forums.gentoo.org

### ISSUE THREAD

**Issue by shibotto** [darkreader/darkreader#825]
Chrome:
Eats all the RAM it can until the browser kills the thread.

Firefox:
Eats all the RAM it can until you go OOM.

Rendering is completed almost instantly, so maybe something in background gets stuck in an infinite loop.

**Comment by memert** [comment]
I have a similar issue:
On Manjaro-KDE with Firefox 64.0, while accessing to forums.gentoo.org, it fills up the ram and the entire system freezes. I have recreated the bug on a bootable usb, with
Kernel: 4.19.8-2-MANJARO x86_64, Desktop: KDE Plasma 5.14.4, Firefox 64.0
Unfortunately, I cannot get the log files, since the all IO stops during freeze.

**Comment by Gooberpatrol66** [comment]
Same here. Not just with gentoo forums, but other sites too. Happens with both the self-compiled and binary distributions of firefox 65.

**Comment by Gooberpatrol66** [comment]
This is what the log shows when a leak happens:

Extension error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheet]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no] undefined 65
[[Exception stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:65:12
cleanup/<@resource://gre/modules/ExtensionContent.jsm:360:13
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:67:129
cleanup/<@resource://gre/modules/ExtensionContent.jsm:360:13
]]
Extension error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheet]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no] undefined 65
[[Exception stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:65:12
cleanup/<@resource://gre/modules/ExtensionContent.jsm:360:13
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:67:129
cleanup/<@resource://gre/modules/ExtensionContent.jsm:360:13
]]
JavaScript error: resource://gre/modules/ExtensionParent.jsm, line 1041: Error: WebExtension context not found!
JavaScript error: resource://gre/modules/ExtensionParent.jsm, line 1041: Error: WebExtension context not found!
JavaScript error: resource://gre/modules/ExtensionParent.jsm, line 1041: Error: WebExtension context not found!
JavaScript error: resource://gre/modules/ExtensionParent.jsm, line 1041: Error: WebExtension context not found!
JavaScript error: resource://gre/modules/WebRequestContent.js, line 124: TypeError: window is null
JavaScript error: resource://gre/modules/ExtensionParent.jsm, line 1041: Error: WebExtension context not found!

**Comment by shibotto** [comment]
As of today I can't reproduce this anymore with Dark Reader 4.8.2 on Firefox 70.0 and Dark Reader 4.8.3 on Chrome 77, so I'm closing the issue. If anyone still has problems, please reopen.
