### ISSUE TITLE
[Broken Website] math.tamu.edu

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#8258]
# Broken Website Report

## Website Address

https://www.math.tamu.edu/~boas/courses/math696/why-macros.html

## Problematic Observation

The LaTeX rendered output becomes invisible in dark mode.

## Screenshots

![pic-selected-220222-1115-58](https://user-images.githubusercontent.com/59497618/155070781-fea9782b-0953-46fe-ad3d-fd92c6640331.png)

## System Information

- OS:  Linux
- Browser:  Firefox 97
- Dark Reader Version:  4.9.45

**Comment by Gusted** [comment]
Hi @paniash

I might have a fix for this site, but to be sure it won't break other pages, could you link some more pages where this is broken?

Regards,
Gusted

**Comment by paniash** [comment]
@Gusted Sure!

https://www.math.tamu.edu/~boas/courses/math696/spivak.html
https://www.math.tamu.edu/~boas/courses/math696/LaTeX-in-line-equations.html
https://www.math.tamu.edu/~boas/courses/math696/math-macros.html
