### ISSUE TITLE
Not invert/invert all elements inside a specific div

### ISSUE THREAD

**Issue by rituraj22** [darkreader/darkreader#826]
I tried using the developer tool, but couldn't figure out any way to apply settings for all elements inside a div, and not just the div's property

**Comment by alexanderby** [comment]
Maybe try `div > *` selector.

**Comment by Gusted** [comment]
[W3schools about selectors](https://www.w3schools.com/cssref/css_selectors.asp)
[MDN docs what are selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors)
[MDN docs types of selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)
Stackoverflow is your best friend or search it.
