### ISSUE TITLE
[Broken Website] iast.io

### ISSUE THREAD

**Issue by Bidaya0** [darkreader/darkreader#8278]
# Broken Website Report

## Website Address
https://iast.io/vuln/vulnDetail/1/290088

## Steps To Reproduce
Here is an example:
- Go to [demo.iast.io](https://demo.iast.io/) to enter demo user
- Go to https://iast.io/vuln/vulnDetail/1/290088

## Problematic Observation
The components of the webpage are overlapping and it looks like the css for this part is not working.

## Screenshots
There is a normal example: https://iast.io/vuln/vulnDetail/1/283811?status=
![image](https://user-images.githubusercontent.com/44495348/155586676-5d76f93c-5525-4b50-8610-0ef2a917956c.png)

There is where the accident happened:https://iast.io/vuln/vulnDetail/1/290088
![image](https://user-images.githubusercontent.com/44495348/155586491-926cfe0f-0c0e-40b2-92de-8829af392f9a.png)

## System Information

- OS: Linux Debian 11 xfce
- Browser: Firefox 91.6.0esr (64 bit)
- Dark Reader Version: 4.9.45

## Additional Context
This is the vulnerability management page of the IAST project. The parameters in the code call process are displayed here to help programmers analyze the discovered vulnerabilities, including some vulnerabilities caused by backend rendering (like XSS).
Maybe it is because the HTML or CSS code in the parameters returned in the webpage affects the rendering logic of the dark reader after being analyzed by the dark reader, but the content backend of the HTML part has been escaped when it is returned.

**Comment by Gusted** [comment]
It does not seem to be reproducible on the demo page, do you have a link on the demo page which has the same behavior on the demo page?

**Comment by Bidaya0** [comment]
> It does not seem to be reproducible on the demo page, do you have a link on the demo page which has the same behavior on the demo page?

https://iast.io/vuln/vulnDetail/1/290088?status=

It still appears on my firefox.

![image](https://user-images.githubusercontent.com/44495348/155691598-a8a4a87c-ed9c-478b-a067-11cd6b91e4a3.png)

But it disappear when i use chrome
Version 98.0.4758.80 (Official Build) built on Debian 11.2, running on Debian 11.2 (64-bit)
![image](https://user-images.githubusercontent.com/44495348/155692209-1967bea3-2e01-41a5-bdc1-5215032553a1.png)

**Comment by Gusted** [comment]
> https://iast.io/vuln/vulnDetail/1/290088?status=

I'm not able to login into site.

**Comment by Bidaya0** [comment]
> > https://iast.io/vuln/vulnDetail/1/290088?status=
> 
> I'm not able to login into site.

use [demo.iast.io](demo.iast.io) to login.It will redirect you to login into user 'demo'.Then you could access the page

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/155837976-2981456f-19f5-4f7d-bde3-b2992d817c69.png)

It seems like the positions of the elements are correct for me, I'm not able to reproduce this issue. Could you try reproducing it in a new profile?

**Comment by Bidaya0** [comment]
> ![image](https://user-images.githubusercontent.com/25481501/155837976-2981456f-19f5-4f7d-bde3-b2992d817c69.png)
> 
> It seems like the positions of the elements are correct for me, I'm not able to reproduce this issue. Could you try reproducing it in a new profile?

Thank you, it seems that this page is not compatible with Firefox. I tested it 20 times with darkreader and without darkreader, and they all appear at a 20% probability, but when I use chrome, I don't have this problem.

**Comment by Gusted** [comment]
> Thank you, it seems that this page is not compatible with Firefox. I tested it 20 times with darkreader and without darkreader, and they all appear at a 20% probability

The issue also appears when dark reader is disabled?

**Comment by Bidaya0** [comment]
> > Thank you, it seems that this page is not compatible with Firefox. I tested it 20 times with darkreader and without darkreader, and they all appear at a 20% probability
> 
> The issue also appears when dark reader is disabled?

Yes, I didn't reproduce it on my other firefox browser for windows 10 with darkreader, so this may be a browser bug.
