### ISSUE TITLE
Please add toggle to the context menu

### ISSUE THREAD

**Issue by vitaly-zdanevich** [darkreader/darkreader#831]
Because shortcuts of extensions does not works in Vivaldi and Opera , and for toggling I need to exit from full-screen mode. Other users also may benefit from context menu as well, I think.

Would be better to make it optional - some users will disable it for simpler context menu.

![image](https://user-images.githubusercontent.com/3514015/48300088-2b9c2880-e4e8-11e8-807d-5bf635519fe4.png)

**Comment by alexanderby** [comment]
Oh, right, it is the same issue for Opera, you should be able to set shortcuts, but direct link from Dark Reader's pop-up don't work, see the screenshot.
![image](https://user-images.githubusercontent.com/9638588/48768168-82b0b300-ecc9-11e8-9a3e-02a86d2d1160.png)

**Comment by vitaly-zdanevich** [comment]
Does not works on Vivaldi on Mac :( nothing happens.

**Comment by alexanderby** [comment]
Fixed in https://github.com/darkreader/darkreader/issues/6761
