### ISSUE TITLE
[Website Report] developer.mozilla.org

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#8318]
# Website Report

## Website Address
https://developer.mozilla.org  
in particular, take a look at:  
https://developer.mozilla.org/docs/Web/CSS/text-transform

## Observations/Thoughts
Mozilla added a native dark theme to developer.mozilla.org.  It's pretty good.  It also auto-detects the user-agent's theme, which is very nice.

I was thinking about adding that host to the list of native dark pages, but I noticed that they chose to hardcode *(gasp!)* the `background` property for many of the `iframe`s they use (for example, see https://developer.mozilla.org/docs/Web/CSS/text-transform).  They made the background for those `iframe`s a blinding white #FFF.  Ugh.

I understand why they likely did this, but it doesn't take away from the fact that the contrast and whiteness are painful on one's retinas.

How shall we handle this?

## System Information
- OS: Linux
- Browser: Firefox 97
- Dark Reader Version: 4.9.45

**Comment by Gusted** [comment]
MDN cannot be added anyway see: https://github.com/darkreader/darkreader/pull/8316#discussion_r817559555

**Comment by Gitoffthelawn** [comment]
> MDN cannot be added anyway see: [#8316 (comment)](https://github.com/darkreader/darkreader/pull/8316#discussion_r817559555)

Thanks.  I added a comment over there.
