### ISSUE TITLE
ASP.net MVC 5 site logins are broken when using ValidateAntiForgeryToken

### ISSUE THREAD

**Issue by aetherhub** [darkreader/darkreader#832]
Login on sites using the built-in ValidateAntiForgeryToken which is for preventing cross-site request forgeries does not work with the Darken Reader. Something in your chrome extensions handling of cookies or POST data breaks the login and it is seen as an attack.

Information on ValidateAntiForgeryToken can be found here:
https://stackoverflow.com/questions/13621934/validateantiforgerytoken-purpose-explanation-and-example

Users with this extension have reported problems with logging into the following site, both with social media logins or email logins: https://aetherhub.com/

We found out it was due to the ValidateAntiForgeryToken function as disabling this in a test environment fixed our login issues.

**Comment by aetherhub** [comment]
The value is stored in a cookie and in a hidden input inside the form. The input looks like this

<input name="__RequestVerificationToken" type="hidden" value="xxxxInputRandomStringHerexxxxx">

**Comment by aetherhub** [comment]
input name="__RequestVerificationToken" type="hidden" value="xxxxxInsertRandomValueHerexxxx"

**Comment by alexanderby** [comment]
I see, but I have no idea how it could produce an error. Dark Reader has no effect on a hidden input value or cookies.

**Comment by Gusted** [comment]
They are not using ASP.net anymore and Shouldn't break too if it was the case.
