### ISSUE TITLE
[Safari] Broken sites

### ISSUE THREAD

**Issue by axeII** [darkreader/darkreader#833]
Inputed site: https://hub.docker.com/r/linuxserver/transmission/
Issue: Some parts are white instead of dark.
Version: 1.0.3

Inputed site: http://www.planetary.org/blogs/jason-davis/spaceil-lander-feature.html
Issue: text is dark
Version: 1.0.3

----Edit:
Inputed site: http://osxdaily.com/2015/11/16/howto-flush-dns-cache-os-x-elcap/
Issue: background
Version 1.1.0

https://www.linux.com/blog/how-generate-strong-password-linux-command-line
Issue: White most parts of page
Version 1.1.0

@alexanderby Is it ok to keep posting here sites that are broken in darkreader safari?

**Comment by alexanderby** [comment]
Yes, the same script with minor changes is used in all browsers, so you can post errors here (specifying a browser). I didn't see anything wrong on `hub.docker.com` in Dynamic mode, but saw the issue with `www.planetary.org`.

**Comment by axeII** [comment]
I am having problems with www.reddit.com. Also https://blog.cloudflare.com/analysis-of-todays-centurylink-level-3-outage/ 

@alexanderby will there be update for safari any time soon 🙏🏻 ?

Thanks.

**Comment by alexanderby** [comment]
Hopefully they are fixed. Please submit separate issues for each website if you still see the issues.
