### ISSUE TITLE
[Broken Website] Blackboard - Multiple choice questions: selected answers are hard to read 

### ISSUE THREAD

**Issue by sfisher923** [darkreader/darkreader#8352]
# Broken Website Report

## Website Address
blackboard.com
## Steps To Reproduce
Take a Quiz with Multiple Choice Questions and answer them

## Problematic Observation
The answer circles blends in with the background making it hard to read
## System Information
PC 1 
- OS: Windows 10 Home 21H2 Build 19044.1525 
- Browser: Opera GX 83
- Dark Reader Version: 4.9.45

PC 2 (These are not quite as accurate since I have not used this one on there as recently)
- Linux Mint Cinnamon 20.3 
- Browser: Opera 84
- Dark Reader 4.9.4x

**Comment by alfawal** [comment]
@sfisher923 please provide a link to any example form so I can take a look.

**Comment by sfisher923** [comment]
Sorry for the Delay since I was waiting for one to appear here (Here are 2 images where A is the option I choose)
![A is Selected](https://user-images.githubusercontent.com/80093217/160947114-ca9e0014-bfc8-4883-a0dd-86ce95c8f7f8.PNG)
![Dark Reader Off](https://user-images.githubusercontent.com/80093217/160947656-127df059-95f0-486a-a5a4-a1d9b9fc0416.PNG)
