### ISSUE TITLE
[Broken Website] forums.comodo.com - Not Darkened Properbly

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8360]
# Broken Website Report

## Website Address
https://forums.comodo.com/

## Steps To Reproduce

- Website partially darkened, it seems not good.
- Please surf a little on forum you will understand my point. Thanks
## Screenshots

**Disabled**
![Screenshot_011826_2022-03-05](https://user-images.githubusercontent.com/15933805/156849636-e71c965c-f1c1-4446-aa97-a8f0e3ad5e15.png)

**Enabled**
![Screenshot_011816_2022-03-05](https://user-images.githubusercontent.com/15933805/156849665-6db642f0-e3b5-4e8e-a2e8-6b4e4f9e8502.png)

## System Information

- OS: Windows 10
- Browser: Firefox 97.0.1
- Dark Reader Version: 4.9.45

**Comment by bkrucarci** [comment]
@Gusted 

Please check it again. Buttons are gone!
![Video](http://g.recordit.co/FWi9w9AuE6.gif)

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/8364
