### ISSUE TITLE
Do not work well on some dynamic-scripted sites

### ISSUE THREAD

**Issue by Wanderer361** [darkreader/darkreader#837]
Thank you for this great addon! It works well on most sites except some. For example,

http://weather.asahi.com/pinpoint/kanto/tokyo.html

Above is a popular weather forecast  site that I visit daily but the text become invisible if DarkReader is turned on.
If the issue cannot be solved for some reasons, how about adding an option for the user to add sites (with wildcard specification) like this to a 'Exclusive Site List',  so that DarkReader would remain 'dormant'  
 automatically when visiting these sites?

**Comment by alexanderby** [comment]
Hello. I see the issue.

If you would like to disable Dark Reader on some website, there are 2 ways: click **Toggle** button or open **Site List** and add site name there. Also you can try using **Filter** mode for a specific website, have a look at help page https://darkreader.org/help/en/

**Comment by Wanderer361** [comment]
Thank you for the response.
TBH I was really amazed by how well it works that I didn't notice there is already a white list and black list feature implemented. Hmm.. what was I looking at? :)
Looks like there are more to explore than I expected already. Thanks!

**Comment by Gusted** [comment]
Can't reproduce the behaviour and workaround was given :shrug:
