### ISSUE TITLE
[Broken Website] Google Sheets Colors

### ISSUE THREAD

**Issue by Faedelity** [darkreader/darkreader#8376]
# Broken Website Report

## Website Address
https://docs.google.com/spreadsheets/

## Steps To Reproduce
- Go to Google Sheets
- Make a spreadsheet that uses colors
- Discover you dislike the colors chosen, in whatever way. I am aware this has come up a lot; I am posting this to make my suggestions and provide the spreadsheet for testing if people want to use it.

## Problematic Observation
This site is a known problem child due to Google deciding to lock the entire spreadsheet into one item, and what bothers people varies. I don't use images in my spreadsheets, but I use color extensively, so my issue is that regardless of whether I use Filter, Filter+, or Dynamic, the colors available to me are limited by the filter- even if I manually build a spreadsheet to work with my Dark Mode settings, there are some colors that are simply not available, and I can't figure out this section of the filter parameters to even try to fix it myself.

## Screenshots
I made a spreadsheet specifically to test and show dark mode effects on this site. Feel free to share it around. It includes every default color as both background and foreground, with default and black colored text or background as appropriate. Plus the custom rainbow I use a lot over on the side. 
https://docs.google.com/spreadsheets/d/16L4jXf4qtl-ypoK4qSlTE6jmGFOBKN6RAfqgv08oDs4/edit?usp=sharing

Here are my dark mode settings. My goal with Dark Mode is to get a black or dark gray background with true white text, and for color elements to remain vivid if they start out that way.
![image](https://user-images.githubusercontent.com/6268255/156913530-4db6e113-9dea-45cb-922d-9a0ea227cf99.png)

Here is the spreadsheet in Light Mode:
![image](https://user-images.githubusercontent.com/6268255/156913567-f190b585-04cd-46a5-bd80-a0631beffdf1.png)

Here it is in Filter:
![image](https://user-images.githubusercontent.com/6268255/156913622-78782564-d7b3-4f2d-bc30-767ab0dee375.png)

Filter+:
![image](https://user-images.githubusercontent.com/6268255/156913633-70b5d7eb-095c-4748-8b66-1d8b84651148.png)

And Dynamic:
![image](https://user-images.githubusercontent.com/6268255/156913663-0367eb51-44f7-45bd-ab51-62260a155253.png)

Color picker for full red in Light Mode:
![image](https://user-images.githubusercontent.com/6268255/156913968-21771610-caf8-4a1b-8c2c-3c6e98b6174f.png)

Filter:
![image](https://user-images.githubusercontent.com/6268255/156913930-3743245c-e153-4fc8-869c-091985354350.png)

Filter+:
![image](https://user-images.githubusercontent.com/6268255/156913941-f7db7454-41fd-4c4a-8843-c15a27e19a39.png)

Dynamic:
![image](https://user-images.githubusercontent.com/6268255/156913957-f128bd7b-5d50-4cbd-8be9-bf4d47cebce3.png)

## System Information
- OS: Windows 10
- Browser: Firefox Dev Edition, 98.0b2 64-bit
- Dark Reader Version: 4.9.45

## Additional Context
This is not a complaint about things inverting that should not, etc.. This is an issue with the particular limitations on colorspace the default filters impose. I do not like how muddy the entire warm end of the spectrum gets. I want true yellow back.

The default colors Google provides do not protect you from every possible combination that is hard to read. I am fine with this. I don't work with spreadsheets that use a lot of color other than my own, and I am willing to do the work to make sure they are readable whether or not you are using Dark Reader. 

- As far as the fixed color schemes, I would like for whichever is the most relevant to simply use the original colors, just flipped in lightness/value, so that it is more predictable what you are going to get. This would also allow for true red, true yellow, and custom colors to work reasonably. Right now, it looks like the hue and saturation are adjusted as well, and this doesn't, imo, yield the best results in the warm colors.
- I don't know which CSS elements affect this, but in the color picker, which I am mostly using as a reference since it makes the color space used more easily visible, there should always be one full saturation corner, with white and black corners adjacent, so you have the option of full saturation at all values, and an opposite corner that is either white or black, so you can get a full range of grays. The actual locations of those corners may vary, but they should all be present. The current filters as I find them all remove either the full-saturation corner or the white, limiting options.
- For fussy people like me, I think it might save the dev some annoyance if you included a specific wiki entry on this particular pain in the neck, how much can be customized, and where to look in the filters if you want to try to tweak the thing to your will. I am willing to do the work, but I haven't been able to dig out the settings for this.

Overall, for something like this where anyone likely to notice the issues is someone who is poking at the colors in the first place, I don't think it's unreasonable for there to be a certain degree of DIY involved if someone wants a specific color set, but it seems odd that every existing option cuts out a significant amount of options, and changes the default options in a way that doesn't intuitively look like inversion. It might be perfect inversion of the color values, but it doesn't read that way.

Thank you for doing this project and listening to all the griping about Google Sheets. Sorry it's such a pain, and I hope posting this is useful.

**Comment by Gusted** [comment]
Hi @Faedelity!

Thank you for your extensive comment, 

The problem in docs.google.com/spreadsheet is hard to fix and hard to adjust to every needs, because of Google's way of imposing all these elements as 1 element.




> * I don't know which CSS elements affect this, but in the color picker, which I am mostly using as a reference since it makes the color space used more easily visible, there should always be one full saturation corner, with white and black corners adjacent, so you have the option of full saturation at all values, and an opposite corner that is either white or black, so you can get a full range of grays. The actual locations of those corners may vary, but they should all be present. The current filters as I find them all remove either the full-saturation corner or the white, limiting options.

The color picker is a separate "module", and doesn't really represent the visible colors that would be displayed, as these use different method of displaying the color, which can be correctly modified by dark reader without any fixes. Which is why the saturation is gone etc.



> * For fussy people like me, I think it might save the dev some annoyance if you included a specific wiki entry on this particular pain in the neck, how much can be customized, and where to look in the filters if you want to try to tweak the thing to your will. I am willing to do the work, but I haven't been able to dig out the settings for this.

Well filters are weird, and documenting this is even weirder. As this is WYSIWYG-like method, the only thing that can be documented is "The colors are modified, give it a bit of time to correct adjust for it, or disable dark reader." Giving a full-blown wiki on tips & tricks is quite overwhelming and doesn't make much sense to honestly.



> * As far as the fixed color schemes, I would like for whichever is the most relevant to simply use the original colors, just flipped in lightness/value, so that it is more predictable what you are going to get. This would also allow for true red, true yellow, and custom colors to work reasonably. Right now, it looks like the hue and saturation are adjusted as well, and this doesn't, imo, yield the best results in the warm colors.

The problem is that, not just colors are being shown on the spreadsheet, Also text is being shown, borders, images(a problem on it's own), If it wold just invert the lightness value(which is kinda hard with Filters) a yellow color would be shown as a blue color, the hue's are also being flipped to correct for this such that the color being shown as a shade of the yellow color, thereby a contrast is being imposed in order to not show full-white content, but a "darker" version of it.

**Comment by Faedelity** [comment]
Oof. that is more fundamentally broken than I thought it was. 

So, there isn't any way to allow for things like true red or yellow? It seems to really be the warm colors that are weird no matter what I do, and not being able to do the vivid pastels.

**Comment by Gusted** [comment]
> So, there isn't any way to allow for things like true red or yellow?

Without comprising all the other colors(as you could theoretical craft the perfect filter in order to have true xxx for a one specific color), nope.

**Comment by Faedelity** [comment]
That stinks. Well, thank you for replying regardless. I appreciate your humoring me, given how many similar requests I saw.
