### ISSUE TITLE
Sub domain are always matched by pattern

### ISSUE THREAD

**Issue by Fred-Vatin** [darkreader/darkreader#84]
Hi,

I didn't find a way to exclude for instance [http://thetvdb.com/?tab=series&id=78804](http://thetvdb.com/?tab=series&id=78804) [must not be dark] without touching the sub-domain [https://forums.thetvdb.com/viewtopic.php?t=27159](https://forums.thetvdb.com/viewtopic.php?t=27159) [must be dark].

Is there a way or is it a bug?

**Comment by alexanderby** [comment]
Did you try to remove `http://` ?

**Comment by J-e-r-e-m-i-a-h** [comment]
do this:
```
noinvert list
www.thetvdb.com/
```
or
```
invert list
forums.thetvdb.com/
```

**Comment by Gusted** [comment]
As of #2327 you can simply add !forums.thetvdb.com to exclude it from the list

**Comment by alexanderby** [comment]
Fixed by https://github.com/darkreader/darkreader/commit/5546bd52e82f00dd1c436867f340170faaea868f
