### ISSUE TITLE
Search results with dict.cc plugin in Firefox shows black font

### ISSUE THREAD

**Issue by jk-85** [darkreader/darkreader#8414]
I configured this plugin that it shows only a small window, see screenshot. This should be fixed to show results in white color.
![grafik](https://user-images.githubusercontent.com/13134932/157752932-efab5866-606f-4608-9377-918c13a9fc37.png)

**Comment by jk-85** [comment]
*LOL* I found a website, where this is working well, but all other pages I tested it, the white color seems to be overwritten, but not on this page (the page of the plugin author :D) 
![grafik](https://user-images.githubusercontent.com/13134932/157755030-b2d786c8-ba00-4f10-baf1-4c292817fe45.png)

**Comment by Gusted** [comment]
Use the provided issue template.
