### ISSUE TITLE
Android messages does not work at all when Dark Reader is enabled

### ISSUE THREAD

**Issue by fcusano9** [darkreader/darkreader#842]
URL: https://messages.android.com/

The messages app just shows up as a blank screen when Dark Reader is enabled. I would really love Dark Reader to work on this website because I often like the Dark Reader dark theme better than the default dark theme on some websites.

**Comment by alexanderby** [comment]
Looks bad.

You can use Filter mode for this website until I determine what's wrong.

**Comment by Nerten** [comment]
Same problem with https://divan.github.io/posts/go_get_private/

But when turn off and then on after the page loaded it starts working.

**Comment by Gusted** [comment]
Fixed.
