### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by albertopasqualetto** [darkreader/darkreader#8438]
# Bug Report

## Website Address

Save to Pocket browser extension.

## Bug Description

There is a white rectangle around the popup when using the [save to Pocket](https://microsoftedge.microsoft.com/addons/detail/save-to-pocket/jicacccodjjgmghnmekophahpmddeemd) extension.

## Steps To Reproduce

- Click the extension button to make it work
- Popup appears
- Observe

## Expected Behavior

It should be black as the background

## Actual Behavior

White rectangle around popup

## Screenshots

![image](https://user-images.githubusercontent.com/39854348/158071779-79f00010-5d84-40aa-904e-51015a177dc4.png)

## System Information

- OS:  Windows 11
- Browser:  Edge 99
- Dark Reader Version:  4.9.45

**Comment by Gusted** [comment]
Dark reader is not able to modify other extensions.

**Comment by albertopasqualetto** [comment]
> Dark reader is not able to modify other extensions.

Ok, I am not an expert but Dark Reader seems acting on the HTML of this extension (selected area):
![image](https://user-images.githubusercontent.com/39854348/158246759-049d4db2-863c-489d-9ff4-3ebb30495bc7.png)

**Comment by albertopasqualetto** [comment]
> @albertopasqualetto you can use the version from [Chrome Web Store](https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj) as it is updated and supports dark theme.

@rakleed  Thanks!
