### ISSUE TITLE
Becomes light when switching tabs

### ISSUE THREAD

**Issue by satvikpendem** [darkreader/darkreader#844]
Some sites like Quora or stackedit.io work fine at first and become dark, but sometimes when I ctrl+tab to and from them, they suddenly turn light, but not in the way the sites actually look with the extension disabled, just with a more white appearance.

**Comment by alexanderby** [comment]
Hello. What browser you are using?

**Comment by alexanderby** [comment]
OK, I will try to determine, what's wrong. What do you mean by "ctrl+tab"?

**Comment by polyzen** [comment]
`ctrl-tab` changes to the next tab.

**Comment by satvikpendem** [comment]
For example:
![image](https://user-images.githubusercontent.com/42670561/49245700-29d7cd80-f3e1-11e8-9e94-6ddf944bcc12.png)

**Comment by alexanderby** [comment]
It would be great if somebody could give full steps to reproduce the problem, like:
1. Open google.com.
2. Search for "quora why is the sky blue".
3. Open the first result in new tab.
4. Press "Ctrl+Tab".
5. See white page.

**Comment by Imold** [comment]
I think I had this happen to me on youtube. It only happened with filter and filter+, if I switch back and forth between tabs enough times I get a partially double inverted page.

**Comment by satvikpendem** [comment]
@alexanderby Problem is this happens intermittently, I'm not sure under which circumstances it happens. Seems to be when using the Filter or Filter+ options.

**Comment by Gusted** [comment]
Should be fixed.
