### ISSUE TITLE
[Bug] [MacOS] [Edge] Unable to access "Automation" setting

### ISSUE THREAD

**Issue by Zvone7** [darkreader/darkreader#8448]
# Bug Report

## Bug Description

Unable to see "Automation" menu in Edge browser on latest MacOS. Not sure if it's just me, but it happens again in incognito.

## Steps To Reproduce

Left click on Dark reader icon in extension area next to URL bar.
Click Settings
Click automation.

## Expected Behavior

Automation menu where you can configure to follow system scheme/schedule should be visible.

## Actual Behavior

"Empty" Gray box.

## Screenshots
<img width="292" alt="Screenshot 2022-03-15 at 20 59 46" src="https://user-images.githubusercontent.com/17856857/158461295-c506eb68-05bb-44d7-ae6a-62962bc24e43.png">
<img width="285" alt="Screenshot 2022-03-15 at 20 59 55" src="https://user-images.githubusercontent.com/17856857/158461238-7e1cd662-79cc-4e05-99a8-d40d162f7f7e.png">

## System Information

- OS: MacOS Monterey 12.2.1
- Browser: Edge 98.0.1108.62 
- Dark Reader Version: 4.9.47.

**Comment by Gusted** [comment]
Does the issue persist between restarts? Can it be reproduced in a new profile?

**Comment by Zvone7** [comment]
Issue does exist between restarts(browser and system), but I cannot recreate it in a new browser profile.
I also experience menus not showing up when I switch to old design (and then switch back).

But it seems that behaviour could be specific to my browser/setup, so feel free to close.
