### ISSUE TITLE
[Broken Website] hakimiyetgazetesi.com - Not Darkened

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8449]
# Broken Website Report

## Website Address
www.hakimiyetgazetesi.com

## Screenshots

**Even enabled DarkReader**

![Screenshot_003429_2022-03-16](https://user-images.githubusercontent.com/15933805/158476605-a4d0f046-64c2-475a-92ab-9abb66808212.png)

## System Information

- OS: Windows 10
- Browser: Firefox 99
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
Same underlying issue as #5937
