### ISSUE TITLE
bug with "object" html elements

### ISSUE THREAD

**Issue by elderapo** [darkreader/darkreader#845]
Just visit https://codepen.io/elderapo/pen/yQXgqg and open chrome dev tools and you will see:
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at frame.js:1
```

Darkreader assumes that every `document` always has a `body` but this is not the case.

**Comment by alexanderby** [comment]
Hi. What browser are you using?

**Comment by elderapo** [comment]
@alexalekseyenko Google Chrome `Version 69.0.3497.100 (Official Build) (64-bit)`

**Comment by alexanderby** [comment]
@elderapo I think you meant @alexanderby :)

Currently codepen.io is included into Dark Sites list, so Dark Reader should not work on this page.

**Comment by elderapo** [comment]
Whoops, sorry :)

I just realized my issue was caused by other google chrome extension, not darkreader. Sorry for bothering you.
