### ISSUE TITLE
Confused about the operational logic

### ISSUE THREAD

**Issue by jiayaoO3O** [darkreader/darkreader#848]
The function I need is: When I read some pages with a lot of text (such as news sites), I will open this plugin to turn the page into dark mode, but now the situation is, when I use this plugin, all the pages It will turn black, although I can customize each page, but it makes me feel not convenient. I think the reasonable logic is: when I browse the normal webpage, this plugin does not work, but I When browsing some web pages that need to be black, I click on a button and the current page becomes black, but the other pages will not change.

**Comment by alexanderby** [comment]
Hi. This function is already available for Chrome and Firefox https://darkreader.org/help/en/#site-list

**Comment by jiayaoO3O** [comment]
@alexanderby Thanks! That is what I need . 👍
