### ISSUE TITLE
[Broken Website] filecoin.io

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8480]
# Broken Website Report

## Website Address
https://filecoin.io/

## Screenshots

Enabled
![Screenshot_154526_2022-03-20](https://user-images.githubusercontent.com/15933805/159162972-5a2088f3-d245-421e-bd3e-e319deb59295.png)

Disabled
![Screenshot_154517_2022-03-20](https://user-images.githubusercontent.com/15933805/159162978-5476ce58-fb72-4c9b-bf57-bb0427d6169c.png)

## System Information

- OS: Windows 10
- Browser: Firefox 99
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
This will be a wontfix, due to the layout and placement of the elements, the globe is placed behind(on z axis) dark reader's modification. If it would've forced to come before that the text will disappear.
