### ISSUE TITLE
Civil Twilight switching

### ISSUE THREAD

**Issue by taprobane99** [darkreader/darkreader#8481]
Is is possible to add automatic switching based on "Civil Twilight" at a given latitude + longitude?

It is still light in the sky at sunset, and I find Dark Reader switches a bit too early. Civil twilight is actually what local governments use to turn Street lighting on and off, so it makes sense.

Civil twilight is rougly 40 mins after sunset, and 40 mins before sunrise. I'm sure there's a more accurate formula for it somewhere.

**Comment by Gusted** [comment]
Please use the feature request template or discussions
