### ISSUE TITLE
[Bug] Extension not starting up correctly on latest Chrome; not happening in all profiles

### ISSUE THREAD

**Issue by joshkaplan** [darkreader/darkreader#8482]
# Bug Report

## Website Address

All

## Bug Description

The extension is failing to start correctly. The control panel is stuck in a "loading" state (see screenshot).

When I inspect the extension, the console shows this:
```
Welcome to Dark Reader!
index.js:3687 Uncaught (in promise) TypeError: settings.customThemes.forEach is not a function
    at UserStorage.fillDefaults (index.js:3687:35)
    at UserStorage.loadSettingsFromStorage (index.js:3701:22)
    at async UserStorage.loadSettings (index.js:3679:29)
    at async Extension.start (index.js:4857:13)
```

Finally, all sites are not displaying correctly. (It might just be using some fallback theme, rather than dynamic? Not sure.)

## Steps To Reproduce

Not sure. It first occurred after upgrading Chrome to the latest version, but I cannot reproduce on a fresh profile (and my work profile is still working fine.)

## Expected Behavior

Extension loads and works.

## Actual Behavior

Extension produces an error on startup.

## Screenshots

<img width="273" alt="image" src="https://user-images.githubusercontent.com/5589260/159201970-5c76afab-4c04-497b-8a93-f5631af6d49e.png">

## System Information

- OS: macOS 11.6.3
- Browser: Chrome Version 99.0.4844.74 (Official Build) (arm64)
- Dark Reader Version: 4.9.47

**Comment by joshkaplan** [comment]
Maybe related to this? https://github.com/darkreader/darkreader/issues/8467

My symptoms are slightly different, but sounds like both might have to do with corrupt settings

**Comment by Gusted** [comment]
Yeah I think there's a slightly bigger issue going on, which seems to be the underlying problem of https://github.com/darkreader/darkreader/issues/8467 as well. Closing as duplicate for now.
