### ISSUE TITLE
[Broken Website] coolors.co broken dark mode

### ISSUE THREAD

**Issue by EmirLogas** [darkreader/darkreader#8483]
# Broken Website Report

## Website Address

https://coolors.co/palettes/trending

## Steps To Reproduce

- Enable Dark Reader extension
- Go to coolors.co/palettes/trending

## Problematic Observation

When the site is open, when you disable the plugin and enable it again, it works correctly, but when it is enabled, it does not work when logged into the site.

## Screenshots

![image](https://user-images.githubusercontent.com/76751818/159287879-b2b1cb99-3283-4d86-8d8d-7116e8329a6e.png)

## System Information

- OS:  Windows 11
- Browser:  Firefox 98.0.1
- Dark Reader Version:  4.9.47

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/159589390-da59402a-b03a-48fb-9b71-25876c592625.png)

Cannot reproduce it, it seems like that on your screenshot, the site is still loading(given the colors being shown are the default colors that's being shown when dark reader is still loading and analyzing the site). Is this issue reproduce able between browser restarts?

**Comment by EmirLogas** [comment]
Sometimes when the site loads, it doesn't work. You can check this video https://e1.pcloud.link/publink/show?code=XZszDHZnOaNc8LQiipbdLGsbrcTFSa2EUKk
