### ISSUE TITLE
[Bug] Memory leak: flickering black dots, screen freezes, then blue screen

### ISSUE THREAD

**Issue by vsitaraman** [darkreader/darkreader#8484]
# Bug Report
Randomly causes monitor to flicker patches of black dots (~once a second) across the screen and then freezes the whole device (can't move mouse) until device blue screens and restarts. Seems to be an unsolved memory leak bug, happens at least twice a week.

## System Information
- OS: Windows 10
- Browser: Microsoft Edge Version 99.0.1150.46 (Official build) (64-bit)

**Comment by Gusted** [comment]
I will need a lot more information on this bug report, as this issue doesn't give me any insight about this bug. It doesn't even say how it's currently related to Dark Reader. So, why do you think Dark Reader is causing this?

**Comment by vsitaraman** [comment]
> So, why do you think Dark Reader is causing this?
Because the bug doesn't occur when Dark Reader is uninstalled??

I don't see how I can provide much more detail given that the bug causes the entire device to blue screen. Wish I could give you a screenshot but, like I said, the device entirely freezes (both screen & mouse) until it blue screens & restarts. This has been happening twice a week for the last month-ish. A couple of times the blue screen has been triggered by trying to turn Dark Reader off once the patches of black dots start flickering. 

There's no question the issue is due to Dark Reader, but I'm not sure what more you expect me to provide here given the nature of the bug.

**Comment by Gusted** [comment]
I'm not convinced this is Dark Reader's fault, this can be bad memory, some bug in the browser. But Dark Reader on it's own don't have the power or control of a PC to cause such things to happen. Given this is more of another issue than Dark Reader's I'm closing it. If there's direct proof or a pointer that dark reader is in any way causing this(and not the browser allowing Dark Reader to go to extreme limits) feel free to re-open the bug.

**Comment by vsitaraman** [comment]
Really disappointed in this hasty and unhelpful conclusion; looks like I won't be using Dark Reader any further.

I've taken the time to confirm this bug only occurs when Dark Reader is enabled and turned on, but instead you choose to dismiss the issue without even properly investigating.

**Comment by Gusted** [comment]
> I've taken the time to confirm this bug only occurs when Dark Reader is enabled and turned on, but instead you choose to dismiss the issue without even properly investigating.

How are you expecting me to investigate a bug that within simple words is "Dark Reader is probably memory leaking, and blue-screening and flickering of dots, have a nice day debugging it!", without any evidence that it's actually Dark Reader.
Dark Reader is a extension and cannot cause on it's own such issue. If it's indeed causing it, we still cannot do anything about it, the browser would still be responsible for fixing such issue. I'd recommend to report this to the browser's issue tracker instead which can help you more. I'm not investing time into issue which I cannot fix.

**Comment by vsitaraman** [comment]
> How are you expecting me to investigate a bug that within simple words is "Dark Reader is probably memory leaking, and blue-screening and flickering of dots, have a nice day debugging it!", without any evidence that it's actually Dark Reader.

As I mentioned before: **_I don't see how I can provide much more detail given that the bug causes the entire device to blue screen_**. Wish I could give you a screenshot but, like I said, the device entirely freezes (both screen & mouse) until it blue screens & restarts. 

It's _your_ plugin that is causing the issue given that clicking on Dark Reader is what triggers the device to freeze & blue screen (and the flickering patches of black dots disappear immediately once Dark Reader is turned off). I would have been glad to provide further details on the extension settings / device specs / etc, but clearly you don't intend to assist further with this.
