### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by Bravo-Lin** [darkreader/darkreader#8493]
# Broken Website Report

## Website Address

https://translate.google.cn/
## Steps To Reproduce

- Default enable Dark Reader extension.
- Go to https://translate.google.cn

## Problematic Observation

extension break the website UI  and make it  hard to use

## Screenshots

![image](https://user-images.githubusercontent.com/43205138/159528902-d8d0a724-eb59-44d9-92ab-b210d256f05e.png)

## System Information

- OS: Windows 11
- Browser : Edge 99
-  Dark Reader Version: 4.9.47

## Additional Context

 It was work well in the previous time .

**Comment by Gusted** [comment]
Is this issue persistent? Do you have by any chance custom fonts enabled?

**Comment by bravos1** [comment]
> Is this issue persistent? Do you have by any chance custom fonts enabled?

No, the page is working fine now , but just on my mac mini (have the same problem before):

![image](https://user-images.githubusercontent.com/43205138/159613098-e799734e-e879-49af-93db-09aee0968622.png)

I'm no sure about my windows  book, i will check it later.

**Comment by bravos1** [comment]
> Is this issue persistent? Do you have by any chance custom fonts enabled?

Problem still exists ].

![image](https://user-images.githubusercontent.com/43205138/159725618-72efe092-90c3-4faf-95c0-980322d049e6.png)

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/159770066-de35c85e-24fe-4a2d-b27d-5e369308df5d.png)
Seems like I'm not able to visit the page.

**Comment by bravos1** [comment]
> ![image](https://user-images.githubusercontent.com/25481501/159770066-de35c85e-24fe-4a2d-b27d-5e369308df5d.png) Seems like I'm not able to visit the page.

i don't know how you get the URL:https://consent.google.cn/mcontinue=https://translate.google.cn/&gl=NL&m=0&pc=t&hl=zh-CN&src=1

You can just access that address, sometimes it does go wrong，URL：https://translate.google.cn

**Comment by Gusted** [comment]
Could be a geo-lock, tried some other machines as well, but 🤷🏽 no luck so far... Will add help wanted label for now...
