### ISSUE TITLE
[Dynamic] kernel.org: requires manual mode reset to work properly

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#851]
Once you update this page, it became like this:

![image](https://user-images.githubusercontent.com/35914376/48736228-c1a81f80-ec5b-11e8-881d-de12f1b09a5b.png)

It becomes [normal](https://i.imgur.com/TkHSkQp.png) only if you change mode to anything else, then back to Dynamic.

**Comment by rolagg** [comment]
Seems to be fixed now.

**Comment by Gusted** [comment]
Should be fixed.
