### ISSUE TITLE
Some elements get overridden by general `html *` rule

### ISSUE THREAD

**Issue by andersonvom** [darkreader/darkreader#852]
On some pages, like [here][individual] or [here][general], certain element colors get overridden by the general `html` or `html *` rules. In this example, when you switch to dark mode, the buttons and the progress bar stop being visible.

[general]: https://www12.senado.leg.br/ecidadania/principalmateria
[individual]: https://www12.senado.leg.br/ecidadania/visualizacaomateria?id=124420

**Comment by alexanderby** [comment]
Some error happens and this fallback style (that prevents white flash during loading) never gets removed.

**Comment by Gusted** [comment]
Should be fixed.
