### ISSUE TITLE
[Broken Website] joyfm.com.tr

### ISSUE THREAD

**Issue by bkrucarci** [darkreader/darkreader#8525]
# Broken Website Report

## Website Address
https://joyfm.com.tr/

## Screenshots

Enabled
![Screenshot_1](https://user-images.githubusercontent.com/15933805/160299060-a0132533-f4d4-4553-87da-cc83a13a0900.png)

Disabled
![Screenshot_2](https://user-images.githubusercontent.com/15933805/160299064-d072558f-38b7-4193-9cb5-8225ed69cc4f.png)

## System Information

- OS: Window 10
- Browser: Firefox 99
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
Wontfix due to the nature of the layout, not possible to have it fixed...
