### ISSUE TITLE
[Feature Request] Add lobste.rs to the global dark list

### ISSUE THREAD

**Issue by Unlimiter** [darkreader/darkreader#8539]

**Comment by q1800** [comment]
I see nothing dark by default on this page.

Everything is bright white.

**Comment by Unlimiter** [comment]
Weird. It looks like this on my end:

![Screenshot 2022-03-28 224050](https://user-images.githubusercontent.com/35694451/160498842-13f10428-2e52-4c78-9fb6-d7a4507a88fb.png)

**Comment by q1800** [comment]
Please see this section of the  [CONTRIBUTING.md](https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#adding-a-website-that-is-already-dark) documentation.

`All pages are dark by default regardless of the system's preferred color-scheme.`
