### ISSUE TITLE
Where is the Safari source code?

### ISSUE THREAD

**Issue by martimarkov** [darkreader/darkreader#854]
I can't seem to find the code for the safari extension app in the repo. Is it close-sourced?

**Comment by kfur** [comment]
@martimarkov you can view code in resource tab of safaris web inspector `darkreader.js`.

**Comment by Kymer** [comment]
> not open source yet

@alexanderby Not *yet* you say, so you do plan on open-sourcing it eventually? What stopped you from open-sourcing it from day one? (Apple Developer program fee perhaps?) Just being curious, would love to try out this extension in Safari!

**Comment by alexanderby** [comment]
@Kymer It actually brings revenue, covering my life needs, so I can concentrate on the extension development and nothing else (except all that legal stuff). When the amount of donations will be enough, I will think of making it free and open source. Yet another clone app could ruin the future plans.

**Comment by Kymer** [comment]
@alexanderby That makes sense. Have just bought it by the way 🎉 Out of curiosity, how do the donations compare relatively to the revenue of the Safari extension? I imagine it's not even close?

**Comment by kfur** [comment]
ported version for safari
[https://gist.github.com/kfur/266c456dd69072eb7533f457ee5f18a0](https://gist.github.com/kfur/266c456dd69072eb7533f457ee5f18a0)
it's convenient to use alongside with this extension [https://apps.apple.com/ua/app/userscripts/id1463298887?mt=12](https://apps.apple.com/ua/app/userscripts/id1463298887?mt=12)

**Comment by alexanderby** [comment]
@Kymer It's not too much, a half of my salary as a Software Engineer in Minsk, but comfortable for living.

@kfur What can I say? Thanks :) If you didn't know the app is available in [Mac App Store](https://apps.apple.com/us/app/dark-reader-for-safari/id1438243180).

**Comment by kfur** [comment]
@alexanderby waiting for sales)

**Comment by Gusted** [comment]
It's somewhere in the cloud I think /s
