### ISSUE TITLE
[Feature Request] Share settings across browser types (Firefox to Edge)

### ISSUE THREAD

**Issue by OneOfMany07** [darkreader/darkreader#8550]
# Feature Request

## Is this feature request related to a problem?

I don't want to maintain multiple independent sets of Dark Reader settings for my multiple browsers, Firefox and Edge in my current case.  Both have this plugin available.

## Proposed solution
At minimum an export/import feature, like a string to copy/paste, would allow manual transfer between the two.

Even better would be saving to a file or cloud drive that both can see, but I'm guessing general disk access might be off the table.  Though some plugins can output a file, like video exporting tools, so maybe it's possible.  And a shared list in a file might require an option to flag only for one browser (if the behavior differs).

**Comment by Gusted** [comment]
There won't be a simple toggle option for this because that would imply a lot of things(Storage handling, authentication etc.) which are a out-of-scope for dark reader and extensions aren't able to arbitrarily read and write files from the file system.

We do currently have a export/import button:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Ability to import and export settings (click Settings, Manage settings).
