### ISSUE TITLE
[Broken Website] nymag.com (picture > source images)

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#8553]
# Broken Website Report

## Website Address
https://nymag.com/intelligencer/

## Steps To Reproduce
- Enable DR dynamic dark mode
- Go to this page: https://nymag.com/intelligencer/
- Notice the image for the lede article is not visible (at least of this writing)

## Expected Behavior
All images visible

## Actual Behavior
See details in *Steps to Reproduce*

## System Information
- OS: Linux
- Browser: Firefox 98
- Dark Reader Version: 4.9.47

## Additional Context
uBO recently had to create a patch to handle `picture > source` images.  I'm not sure if any of there efforts can help here too.

Note that I already sent a pull request to fix other DR issues with this site.  That pull can be merged independently of this issue.

**Comment by Gusted** [comment]
See https://github.com/darkreader/darkreader/pull/8552/files#r837900950

**Comment by Gitoffthelawn** [comment]
@Gusted BTW, if you're interested, here is the uBO patch to which I earlier referred:  
https://github.com/gorhill/uBlock/commit/3391435f750e9a03da7407ccecd9b3b2f950b601
