### ISSUE TITLE
background not dark on m.slashdot.org

### ISSUE THREAD

**Issue by 424344** [darkreader/darkreader#8558]
# Bug Report
background not dark on m.slashdot.org

## Website Address

https://m.slashdot.org/

## Bug Description

On android firefox (nightly) the background of m.slashdot.org is not dark.
is it possible to make it darker?

## Steps To Reproduce

just load slashdot on firefox for android

## Expected Behavior

I want a dark background

## Actual Behavior

the background is not dark

## Screenshots

![image](https://user-images.githubusercontent.com/26486758/160791608-93591609-f79d-4c98-aa43-ed1c423f9ec3.png)

## System Information

- OS: android 11
- Browser: firefox 100 nightly
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
Hi @424344

Please check the dark reader settings, you can create a custom theme for `m.slashdot.org` and increase the contrast(to around 120%) in order to have a darker background-color.

**Comment by 424344** [comment]
thanks!
