### ISSUE TITLE
[Bug] Use the plug-in black theme, open the F12 console debug page caused page card

### ISSUE THREAD

**Issue by ma123456mai** [darkreader/darkreader#8565]
# Bug Report

## System Information

- OS: 
- Browser: 
- Dark Reader Version: 
<img width="1700" alt="image" src="https://user-images.githubusercontent.com/31917567/161033481-caad2e7c-cbe1-4691-9eff-9e1749183900.png">

**Comment by Gusted** [comment]
Fill out the template.
