### ISSUE TITLE
[Feature request] Allow disabling scrollbar styling

### ISSUE THREAD

**Issue by narcolepticinsomniac** [darkreader/darkreader#858]
I already have my own global scrollbar style. Dark Reader screws with it and overrides it unnecessarily.

**Comment by alivefromupstairs** [comment]
@alexanderby I have chrome's overlay scrollbars enabled; those scrollbars that disappear on they're own. can you check if that's the case and disable any styling for scrollbars. chrome does a good job at darkening those.

**Comment by Liz-chan** [comment]
Just adding to this, that I'd love to be able to disable scrollbar theming as well.
I'm using the overlay scrollbars too and they blend in pretty well and only show up when you scroll on the page.

**Comment by ebbit1q** [comment]
This seems to be generated by this line https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L108

I'm able to revert this on firefox (probably works elsewhere) by adding
```
*

CSS
* {
scrollbar-color: unset;
}

================================

```
to the top of the "developer tools" "dynamic theme editor" in the way described in the readme: https://github.com/darkreader/darkreader#using-dev-tools

Having a button would be nicer though :)

**Comment by TheAlienDrew** [comment]
I also wish this is a thing, or at least give global styling from extensions such as Stylish priority over dark reader.

**Comment by TheAlienDrew** [comment]
> This seems to be generated by this line https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L108
> 
> I'm able to revert this on firefox (probably works elsewhere) by adding
> 
> ```
> *
> 
> CSS
> * {
>     scrollbar-color: unset;
> }
> 
> ================================
> ```
> to the top of the "developer tools" "dynamic theme editor" in the way described in the readme: https://github.com/darkreader/darkreader#using-dev-tools
> 
> Having a button would be nicer though :)

Also, scrollbar-color is only an element available to Firefox, any Chromium based browser still needs a different fix.

**Comment by reseto** [comment]
this could also solve another issue? ->https://github.com/darkreader/darkreader/issues/1050

**Comment by jupiter104** [comment]
> This seems to be generated by this line https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L108
> 
> I'm able to revert this on firefox (probably works elsewhere) by adding
> 
> ```
> *
> 
> CSS
> * {
>     scrollbar-color: unset;
> }
> 
> ================================
> ```
> to the top of the "developer tools" "dynamic theme editor" in the way described in the readme: https://github.com/darkreader/darkreader#using-dev-tools
> 
> Having a button would be nicer though :)

Doesn't work in Chrome.

**Comment by TheAlienDrew** [comment]
> > This seems to be generated by this line https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L108
> > I'm able to revert this on firefox (probably works elsewhere) by adding
> > ```
> > *
> > 
> > CSS
> > * {
> >     scrollbar-color: unset;
> > }
> > 
> > ================================
> > ```
> > to the top of the "developer tools" "dynamic theme editor" in the way described in the readme: https://github.com/darkreader/darkreader#using-dev-tools
> > Having a button would be nicer though :)
> 
> Doesn't work in Chrome.

We know this, I already stated this in my comment before yours https://github.com/darkreader/darkreader/issues/858#issuecomment-474704802

**Comment by jupiter104** [comment]
> > > This seems to be generated by this line https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/modify-css.ts#L108
> > > I'm able to revert this on firefox (probably works elsewhere) by adding
> > > ```
> > > *
> > > 
> > > CSS
> > > * {
> > >     scrollbar-color: unset;
> > > }
> > > 
> > > ================================
> > > ```
> > > to the top of the "developer tools" "dynamic theme editor" in the way described in the readme: https://github.com/darkreader/darkreader#using-dev-tools
> > > Having a button would be nicer though :)
> > 
> > 
> > Doesn't work in Chrome.
> 
> We know this, I already stated this in my comment before yours [#858 (comment)](https://github.com/darkreader/darkreader/issues/858#issuecomment-474704802)

Isn't there a way to fix it? Like disable the scroll bar when youtube goes full screen?

**Comment by justinsteven** [comment]
It's not quite "disabling" the scrollbar size, but I found the custom scrollbars too small. The following Dev Tools custom CSS makes life easier for me on Chromium (YMMV)

```css
::-webkit-scrollbar {
    width: 10px;
    height: 10px;
}
```

**Comment by MR-Diamond** [comment]
> I'm able to revert this on firefox (probably works elsewhere) by adding
> 
> ```
> *
> 
> CSS
> * {
>     scrollbar-color: unset;
> }
> 
> ================================
> ```
> 
> to the top of the "developer tools"

Thanks for the workaround. But I found that when I clean the Firefox cache, this content inside the "developer tools" window, will disappear and I have to insert it again. I use bleachbit ( I am on Linux) to clean the cache: I can exclude file and folders from cleaning; any suggestion about?

**Comment by TheAlienDrew** [comment]
> > I'm able to revert this on firefox (probably works elsewhere) by adding
> > ```
> > *
> > 
> > CSS
> > * {
> >     scrollbar-color: unset;
> > }
> > 
> > ================================
> > ```
> > 
> > 
> > to the top of the "developer tools"
> 
> Thanks for the workaround. But I found that when I clean the Firefox cache, this content inside the "developer tools" window, will disappear and I have to insert it again. I use bleachbit ( I am on Linux) to clean the cache: I can exclude file and folders from cleaning; any suggestion about?

I'd suggest just excluding the extensions cache then, if you're going that route.

**Comment by narcolepticinsomniac** [comment]
FYI, since I get the occasional notification from this thread, [Stylus](https://add0n.com/stylus.html) improved its injection a while back, so it wins the specificity contest if you use a scrollbar style which overrides DR CSS now.

**Comment by TTTPOB** [comment]
using new microsoft edge with overlay scrollbar feature and want the scrollbar not to be modified

**Comment by juhp** [comment]
Dark Scroll is probably fine I dare say, but I would rather limit the number of add-ons with access to all my tabs... So for now I just disabled `layout.css.scrollbar-color.enabled`, since I am tired of not being able to see my scroll position.

**Comment by Amanita19** [comment]
I have overlay scrollbars enabled as well. Being unable to use the Firefox oriented fix from earlier, the closest that I have been able to get is by adding the following code snippet to the top of the Dynamic Theme Editor.

```
CSS
::-webkit-scrollbar {
    width: 10px;
    background-color: transparent;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
}
::-webkit-scrollbar-button {
    all: unset;
}
::-webkit-scrollbar-thumb {
    all: unset;
}
::-webkit-scrollbar-track {
    all: unset;
}
::-webkit-scrollbar-track-piece {
    all: unset;
}
::-webkit-scrollbar-corner {
    all: unset;
}
::-webkit-resizer {         
    all: unset;                                                                                                                                                                                                                                                                
}
```
This produces some weird in-between behavior, where the scrollbar will only show up when directly hovered over, but the scroll-track is still present. I'm still working on a better solution, but in the meantime, this is livable.

**Comment by TheAlienDrew** [comment]
> I have overlay scrollbars enabled as well. Being unable to use the Firefox oriented fix from earlier, the closest that I have been able to get is by adding the following code snippet to the top of the Dynamic Theme Editor.
> 
> ```
> CSS
> ::-webkit-scrollbar {
>     width: 10px;
>     background-color: transparent;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
> }
> ::-webkit-scrollbar-button {
>     all: unset;
> }
> ::-webkit-scrollbar-thumb {
>     all: unset;
> }
> ::-webkit-scrollbar-track {
>     all: unset;
> }
> ::-webkit-scrollbar-track-piece {
>     all: unset;
> }
> ::-webkit-scrollbar-corner {
>     all: unset;
> }
> ::-webkit-resizer {         
>     all: unset;                                                                                                                                                                                                                                                                
> }
> ```
> This produces some weird in-between behavior, where the scrollbar will only show up when directly hovered over, but the scroll-track is still present. I'm still working on a better solution, but in the meantime, this is livable. 

That's just because you need to use the hover selector as well...

```
CSS
::-webkit-scrollbar {
    width: 10px;
    background-color: transparent;
}
::-webkit-scrollbar-button {
    all: unset;
}
::-webkit-scrollbar-thumb {
    all: unset;
}
::-webkit-scrollbar-track {
    all: unset;
}
::-webkit-scrollbar-track-piece {
    all: unset;
}
::-webkit-scrollbar-corner {
    all: unset;
}
::-webkit-resizer {
    all: unset;
}
::-webkit-scrollbar-button:hover {
    all: unset;
}
::-webkit-scrollbar-thumb:hover {
    all: unset;
}
::-webkit-scrollbar-track:hover {
    all: unset;
}
::-webkit-scrollbar-track-piece:hover {
    all: unset;
}
::-webkit-scrollbar-corner:hover {
    all: unset;
}
::-webkit-resizer:hover {
    all: unset;
}
```

**Comment by koutheir** [comment]
Setting `layout.css.scrollbar-color.enabled` in `about:config` is [not supported anymore](https://support.mozilla.org/en-US/questions/1297345).

First, make sure `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` is set to `false`.

Then, simply add code to the `<firefox-profile-dir>/chrome/userContent.css` file (create if it doesn't exist):
```css
* {
    scrollbar-color: auto !important;
    scrollbar-width: auto !important;
}
```

**Comment by ebbit1q** [comment]
> Setting `layout.css.scrollbar-color.enabled` in `about:config` is [not supported anymore](https://support.mozilla.org/en-US/questions/1297345).
> 
> First, make sure `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` is set to `false`.
> 
> Then, simply add code to the `<firefox-profile-dir>/chrome/userContent.css` file (create if it doesn't exist):
> 
> ```css
> * {
>     scrollbar-color: auto !important;
>     scrollbar-width: auto !important;
> }
> ```

you mean it should be set to `true` right?

**Comment by josdyr** [comment]
I've tried to understand this thread for a while. Is there currently no support or workaround (for OP feature request) for Edge/Chrome - only Firefox am I right? Thanks!

**Comment by Gusted** [comment]
Hi @josdyr!

To disable any scrollbar styling from dark reader:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    (under Theme click See all options, Colors) -> Colors -> Scrollbar set to "Default"

Regards,
Gusted

As many people are still watching this issue which is already fixed and implemented into dark reader, Ill be closing this issue so we don't have any necro-posting.
