### ISSUE TITLE
[Broken Website] atlassian.net

### ISSUE THREAD

**Issue by ghalibansari** [darkreader/darkreader#8589]
# Broken Website Report

## Website Address
atlassian.net

## Screenshots
![image](https://user-images.githubusercontent.com/20482230/161488603-166d6e94-d4fa-4bc0-ba8a-3481da9232c4.png)

## System Information

- OS: Windows, macOS,
- Browser: Chrome 100
- Dark Reader Version: 4.9.47

**Comment by herrenP** [comment]
My experience is that happens sometimes and not always. I assume it's how the page loads or something. Anyway, I switched from "Dyanmic" to "Filter+" instead.

**Comment by herrenP** [comment]
Duplicated by [8566](https://github.com/darkreader/darkreader/issues/8566) and probably fixed by [8588](https://github.com/darkreader/darkreader/pull/8588).

**Comment by ghalibansari** [comment]
I'm experiencing this every time I visit page.

**Comment by Gusted** [comment]
Duplicated as #8566
