### ISSUE TITLE
[Broken Website] Patreon polls

### ISSUE THREAD

**Issue by JohnVeness** [darkreader/darkreader#8597]
# Broken Website Report

## Website Address
Patreon.com

## Steps To Reproduce

Unfortunately I don't think I can give a direct link, as you would need to be following a particular Patreon creator. You will need to find a post from a Patreon creator where they post a list of items for their patrons to "vote" on.

## Problematic Observation

Maybe it's just my eyes, or my screen (which is annoyingly reflective), but the shaded backgrounds, which are showing how the votes are going so far (i.e. a bar graph), are very hard to notice in dark mode. In light mode they are much more obvious.

## Screenshots

Dark mode:
![image](https://user-images.githubusercontent.com/2512915/161730537-ab6c3902-49c2-4f5b-9ac6-99457f7a875d.png)
Light mode:
![image](https://user-images.githubusercontent.com/2512915/161730693-0f7959d9-4182-4b66-b547-6d35404be096.png)

## System Information

- OS: Ubuntu 21.10
- Browser: Firefox 98.0.2
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
Adding Help wanted as I don't have a patreon account myself. But the fix should be simple. Find the correct CSS selector for the bars. And play around with the colors so it's more noticeable.

**Comment by JohnVeness** [comment]
I've found a public (no need for an account) example: https://www.patreon.com/posts/39005311

As it happens, now I'm in a darker room/less reflections, it's easier to see the bars in dark mode than it was when I first reported. But still, I reckon some tweaking would help. Unfortunately this isn't something I know how to do myself.

**Comment by pl0xy** [comment]
@JohnVeness

It looks fine on the default colour theme (*default theme img 1*), and even better on the `Catppuccin` colour theme (*Catppuccin theme img 2*)

![default](https://user-images.githubusercontent.com/4657862/163346264-5441cba4-2e64-497a-b5a6-1fca1ed8aef5.png)

![Catppuccin](https://user-images.githubusercontent.com/4657862/163345846-c880c268-8810-4819-8105-7753a9693629.png)

The public link you posted has a border around each option as well which I can only assume they all do, public or private.

---

## I'd say this is a non-issue. ##

**Comment by JohnVeness** [comment]
They actually only have a border once you've voted, or if you're unable to vote, if you see what I mean.

But, TBH, I'm OK with closing this issue.

**Comment by Gusted** [comment]
The fixes I had prepared is somewhere in my stashes, but isn't that great TBH. The improvement is really in the details.
