### ISSUE TITLE
[Bug] Darkreader not switching automatically on Linux Firefox

### ISSUE THREAD

**Issue by freebrowser1** [darkreader/darkreader#8605]
# Bug Report
When set on scheduled (geolocation or a fixed time for dark hours), Darkreader does not work automatically.
## Website Address

Any site.

## Bug Description
Setting dark for e.g. 20:00 to 6:00 is ignored, the browser remains light. Same when filling geolocation after dark and browser remains light. Same when the other way around: when it is already light or after 6:00, the browser remains dark.
The problem appears under Linux.
In macOS it works normally in Firefox 98.

## Steps To Reproduce
- Go to any website.
- Follow the steps above.

## Expected Behavior
Browser has to go light or dark automatically.
## Actual Behavior
Browser remains light / dark.
## System Information

- OS: Linux (Ubuntu 20.04)
- Browser: Firefox 98
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
#8600 Should fix the issue.
