### ISSUE TITLE
[Broken Website] CUPS web interface 

### ISSUE THREAD

**Issue by TheRealOne78** [darkreader/darkreader#8607]
# Broken Website Report

## Website Address

CUPS localhost (CUPS web interface for CUPS daemon) (see https://en.wikipedia.org/wiki/CUPS or https://www.cups.org/)
## Steps To Reproduce

If cups is installed on your system and the daemon is running:
open localhost:631 (or the port you set cups to have the web interface)

Dark reader will broke the already dark theme page.
## Problematic Observation

Dark reader seems to overwrite the colors for every page, even if it is already black (or whatever dark theme color), but not entirely. This is no exception for other pages that have already dark theme.
## Screenshots

with dark reader:
![image](https://user-images.githubusercontent.com/53640879/161930645-e9480dd9-2793-4060-9f69-af1b8d44bc24.png)

without dark reader:
![image](https://user-images.githubusercontent.com/53640879/161930727-041c1e02-10a1-43a7-b752-f3f274c15b9b.png)

custom page(apache2 directory listing dark theme on android samsung firefox (fennec) phone)
with dark reader:
![Screenshot_20220406-113538_Fennec.png](https://user-images.githubusercontent.com/53640879/161933152-d8b8f545-ad3c-4c90-bf5d-f4d7245c96d1.png)
without dark reader:
![Screenshot_20220406-113550_Fennec.png](https://user-images.githubusercontent.com/53640879/161933171-854efff3-62be-4269-a8ab-4e99ade0299d.png)
## System Information

- OS: Linux Artix
- Browser: Firefox 99
- Dark Reader Version: 4.9.47

## Additional Context

null

**Comment by Gusted** [comment]
> Dark reader seems to overwrite the colors for every page, even if it is already black (or whatever dark theme color), but not entirely. This is no exception for other pages that have already dark theme.

This is caused due to a mismatch in colors between two main elements(`<html>`, `<body>`). It's not easy to fix as this is happening on a localhost address.

**Comment by TheRealOne78** [comment]
Another website where this bug can be reproduced would be for example https://dwm.suckless.org/patches/cursorwarp/ and other pages from suckless.org

![image](https://user-images.githubusercontent.com/53640879/168445844-c6d51667-2680-4f7e-8bef-7484176cab47.png)

**Comment by TheRealOne78** [comment]
Hi. It seems like this issue is now resolved, as I checked CUPS and suckless.org to see if the broken CSS is gone.

![image](https://github.com/darkreader/darkreader/assets/53640879/bce14aa5-9730-4237-8b20-62b2d6c2001c)

![image](https://github.com/darkreader/darkreader/assets/53640879/edafa9cc-5bce-4e19-8424-539400b6a8f4)
