### ISSUE TITLE
[Bug] Chrome does not detect system color scheme

### ISSUE THREAD

**Issue by guiAlberto** [darkreader/darkreader#8608]
# Bug Report

## Website Address

https://example.com/ (used to test, but it is apllyable on any website)

## Bug Description

This extension on Chrome does not identify the system theme, setting it up to be always off, even when the "Use system color scheme" opton is on.

## Steps To Reproduce

-Setup the desktop environment to use a light color scheme
-Open Google Chrome with the dark reader extension installed
-Setup the extension to use system color scheme
-Go to https://example.com/ with Google Chrome
-Notice it shows a light website
-Change the desktop environment to use a dark color scheme
-Notice the extension does not recognize the color scheme's change

## Expected Behavior

When the extension is setup to use the system color scheme, and the user changes the system color scheme, the extension should change it as well.

## Actual Behavior

The extension always detect a light color scheme from the system.

## Screenshots

I made a test using the extension on both Firefox and Chrome to show how they behavior differrently

![2022-04-06 10-33-53](https://user-images.githubusercontent.com/18057706/161997353-5751c5e5-8b3b-48a6-93ed-826633b86391.gif)

## System Information

- OS: Manjaro Linux, with Gnome 41.4 as the desktop environment
- Browser: Chrome Version 100.0.4896.75 (Official Build) (64-bit)
- Dark Reader Version: 4.9.47

## Additional Context

I used the [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) to make this demo

**Comment by lunavod** [comment]
Same on windows 11. I use Auto Dark Mode app to switch windows theme to dark/light depending on time, but extension does not notice change, so I have to restart browser every time. Even if I switch mode to manual and back it still uses light mode

**Comment by Gusted** [comment]
@guiAlberto What's the result of `matchMedia("(prefers-color-scheme: dark)").matches` when your system color scheme has been set to dark.

**Comment by guiAlberto** [comment]
> @guiAlberto What's the result of `matchMedia("(prefers-color-scheme: dark)").matches` when your system color scheme has been set to dark.

I run the command on the chrome console and it returned `false`. I also tried on firefox, and it returned `true`

**Comment by Gusted** [comment]
Then there isn't much we can do. Go complain to Chromium in that case, they are the one that should provide correct information for the system's color scheme.

**Comment by Divlo** [comment]
For reference this is the Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=998903
