### ISSUE TITLE
[Broken Website] Detect dark theme causing black screen on some Twitch streams

### ISSUE THREAD

**Issue by MusaSSH** [darkreader/darkreader#8613]
# Broken Website Report

## Website Address
twitch.tv

## Steps To Reproduce
- Enable Detect dark theme.
- Visit twitch.tv
- Go into a stream and try to watch it.
- If you can't reproduce with a streamer, try watching a different streamer, same happening to me.

## Problematic Observation

You can hear video sound but the stream is not visible, after you refresh the page you can see the stream for less than one second but then this grayish color appears on stream, it's like a layer. The stream is keep playing in my browser but not visible, how I know? Because if I check task manager I can see GPU Video Decode is working. This problem is instantly disappears when I disable detect dark theme and then instantly appears when I reenable detect dark theme.
## Screenshots

![image](https://user-images.githubusercontent.com/97892949/162567773-a67f8d5b-054d-4e01-b9fd-4a09a2928bad.png)
![image](https://user-images.githubusercontent.com/97892949/162567853-33062889-4068-48d0-8ba5-ff23ebae3da8.png)

## System Information

- OS: Windows 11
- Browser: Google Chrome 100.0.4896.75
- Dark Reader Version: 4.9.47

**Comment by andryandrew** [comment]
I am affected too, Chrome 101 on Mac

**Comment by Furax-31** [comment]
Same problem. Brave with Chromium 102

**Comment by vicelo23** [comment]
Update, I have observed that this bug only occurs in Chromium browsers, Dark Reader for Firefox has no such bug.

**Comment by 2ndkirbyever** [comment]
I am affected as well, Chrome 103, Dark Reader 4.9.52 on macOS Monterey and Windows 11.  I have found a workaround, though: Assuming you have detect dark mode turned on, click the Dark Reader icon and click this button.
<img width="250" alt="Screen Shot 2022-07-19 at 10 20 14 AM" src="https://user-images.githubusercontent.com/16438720/179787390-75f93c00-3bee-44ba-8d0a-a9c0ebc72981.png">

The stream you are trying to watch will be visible again.

**Comment by southrop** [comment]
I'm getting this issue too. From what I can tell, this is probably happening on streams where the streamer has enabled a Twitch Extension. Twitch adds two iframes as an overlay over the `video` element and it looks like forcing it to use a dark color scheme turns it from transparent to black. Specifically, disabling the `color-scheme` selector inside the overlay iframes causes the overlay to become transparent again.

```html {
  color-scheme: dark !important;
}```

![image](https://user-images.githubusercontent.com/2568167/184068609-e089186d-27a4-491a-955c-f8ca3a371fdd.png)

I tried adding ext-twitch.tv to my list of disabled sites but it did not change anything; Dark Reader still modifies the CSS of the iframes.

**Comment by Unnoen** [comment]
@southrop is correct, I came here to report the same thing.

With "Detect dark theme" enabled, Dark Reader correctly detects that Twitch is using a dark theme, but it will still inject/modify the iframes used for the overlay extensions.

Manually adding `twitch.tv` to the site exclusions makes Dark Reader act as expected and *not* inject/modify iframes.

Adding the iframe hosts, `supervisor.ext-twitch.tv` and `ext-twitch.tv` has no effect.

## Screenshots

**Dark theme detected, no exclusion set:**

![image](https://user-images.githubusercontent.com/6127568/187139648-f97a80bb-b0aa-4740-a6c9-f3e872380d28.png)

**Manually set site exclusion:**

![image](https://user-images.githubusercontent.com/6127568/187140095-1cc33b27-e687-480d-8a6a-187ca946730b.png)

**Comment by dpthegrey** [comment]
when i open two tabs of twitch in light mode and turn dark reader on and off, the recent toggle works properly but the other tab breaks/goes blank.

**Comment by K-Schaeffer** [comment]
> Update, I have observed that this bug only occurs in Chromium browsers, Dark Reader for Firefox has no such bug. Dark Reader version is 4.9.51 when I am writing this.

It actually does happen on firefox too, I'm having this issue on firefox 111.0.1 (64-bits)

**Comment by MeridianGH** [comment]
+1
Just experienced this, came across this issue while researching the cause.
Firefox 113.0.1 (64-bits)

**Comment by shssoichiro** [comment]
+1 on both Chrome and Firefox in Windows. Interestingly it does not seem to happen to me on Linux. Dark Reader 4.9.65.

**Comment by kyle95wm** [comment]
+1

**Comment by cocona20xx** [comment]
Just had this happen on Firefox + Apple Silicon macOS.

**Comment by remon2207** [comment]
Same for Gentoo Linux 2.14 (kernel version 6.1.66) + Vivaldi 6.4.3160.44.

**Comment by Rhys-T** [comment]
Same thing on Firefox 121 on macOS 10.15 on Intel. Weirdly inconsistent:
- Sometimes toggling it off for twitch.tv is enough to get it working.
- Sometimes it isn't, and I have to switch Dark Reader off globally to make it work.
	- Sometimes after I do that, I can turn it back on, and it will keep working.
- Sometimes the global toggle _won't_ fix it, but then after it's back on, toggling the per-site button _will_.
- And if I switch out of the window while it's working, it will break again.

Based on https://github.com/darkreader/darkreader/issues/8613#issuecomment-1211562769, I'm currently working around this with [a simple Stylus/UserCSS stylesheet](https://gist.github.com/Rhys-T/efd74dfb6469bb7896971962cd14fb7a) that clears the `color-scheme` property on any `*.ext-twitch.tv` domain. `color-scheme` tends to give web pages in `iframe`s a default background color that keeps the `iframe`s from being transparent, especially if the `color-scheme` is different from that of the outer page. [It's… complicated.](https://fvsch.com/transparent-iframes)

**Comment by Lord-ZuzurNC** [comment]
Hello,

This issue is still occurring. But on my side it only happens if "Ultimate Closed Captions" is visible.

![image](https://github.com/Sytorex-pro/UltimateClosedCaptions/assets/90102166/2bd3320c-b893-4cfa-9219-87a01d6af10e)

![image](https://github.com/Sytorex-pro/UltimateClosedCaptions/assets/90102166/6cf291fb-7131-42ba-b74b-9baaae3e48dd)

Happens on:
Site: https://www.twitch.tv/aypierre
Browser: Chrome v 120.0.6099.200 (Official Build) (64-bit)
Browser agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Browser extension: Dark Reader 4.9.74

**Comment by Squtzy** [comment]
Can confirm that this is still happening. 
Browser: Firefox 122.0
OS: Windows 11 22h2

From what I have been able to tell and to how I "fixed" this issue, it is related to "extensions" that the stream has on the twitch overlay. If there is a active extension on the stream itself like "prime sub reminder" for example it will cause the either grey/white screen until you either turn off the extension on the stream or turn of "detect dark mode" setting in Dark Reader. Tested on 2 off my systems and this is the same issue on both.

**Comment by Rhys-T** [comment]
> From what I have been able to tell and to how I "fixed" this issue, it is related to "extensions" that the stream has on the twitch overlay.

Yeah, Twitch extensions are shown inside transparent `iframe`s from `*.ext-twitch.tv` domains that extend over the video. With Dark Reader running, the `html` element inside the `iframe` gets `color-scheme: dark;` set, which ends up turning it opaque. 

[This user stylesheet](https://gist.github.com/Rhys-T/efd74dfb6469bb7896971962cd14fb7a) resets the `color-scheme` property inside the `iframe`, which seems to be enough to keep the stream visible.

**Comment by Opa-** [comment]
I'm experiencing this issue

Firefox 122.0.1 (64-bit)
macOS 13.6.4 (22G513)
DarkReader Version 5 Preview (4.9.77)

**Comment by alexanderby** [comment]
Indeed, `color-scheme: dark` changes the background of an iframe, that is supposed to be transparent. The fix will be available soon. In the toggling `twitch.com` twice should fix the issue.
