### ISSUE TITLE
[Feature Request] Indicate when dark reader has activated on a website

### ISSUE THREAD

**Issue by AntonHartjies** [darkreader/darkreader#8617]
# Feature Request

It will be nice to see the dark reader icon change to indicate weather it has actually applied its dark mode to a website.
This is mainly applicable with the new feature that detects whether or a website has a dark theme or not. The feature would have a different icon to indicate if dark reader is on versus when it is actually active on the website that you are currently using. This will make it easier to see whether a website has a native dark mode or whether it is dark reader that is applying the dark mode.

**Comment by Gusted** [comment]
Duplicate #1671
