### ISSUE TITLE
[Broken Website] vk.com

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#8618]
# Broken Website Report

## Website Address

https://vk.com/im

## Steps To Reproduce

- Go to https://vk.com/im or https://vk.com/login?u=2&to=/al_im.php

## Problematic Observation

On the site, the background of almost all elements remains light.

## Screenshots

<details><summary>Screenshots</summary>

![screenshot-vk-com-im-1649624785623](https://user-images.githubusercontent.com/19418601/162639873-e8452b33-986e-4d30-ab50-9d4a2334b6f3.png)

![screenshot-vk-com-login-1649624767738](https://user-images.githubusercontent.com/19418601/162639877-ef5460f5-9d9f-45e8-b66c-2495fc0ebae9.png)

</details>

## System Information

- OS: macOS
- Browser: Chrome 100
- Dark Reader Version: 4.9.47

## Additional Context

It started a few days ago, although before that there were no problems.

**Comment by Gusted** [comment]
Do you have detection of dark themes enabled?

**Comment by rakleed** [comment]
Yes, but it looks like they partially rolled back the changes, as for the most part the site began to look normal.

But there are still elements in the [Messages](https://vk.com/im) that were incorrectly inverted.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/162822778-6b5a7820-02bd-4bee-abb8-92acf758fd39.png)

</details>

**Comment by Gusted** [comment]
CC @alexanderby

**Comment by rakleed** [comment]
It looks like they have changed something on their side again, because now everything is displayed correctly again in the Messages section.
