### ISSUE TITLE
[Broken Website] MyAnimeList.net - sort of broken

### ISSUE THREAD

**Issue by martixy** [darkreader/darkreader#8619]
# Broken Website Report

## Website Address
https://myanimelist.net/

## Steps To Reproduce
Enable the dark reader for MAL and load a page **_in the background._**
# Note: This only happens when you load the page in the background, in an unfocused tab.

## Problematic Observation
Some elements are darkened, but the background is light. In fact it starts off correctly in dark mode, then flashes back to light. Text becomes unreadable. This is consistently reproducible.

## Screenshots
![MAL DarkReader broken](https://user-images.githubusercontent.com/8262590/162646261-7c5e4d93-b8f9-48ab-b793-1ce7f3eea2f1.png)

## System Information

- OS: Windows 10
- Browser: Chrome 100, Firefox 99
- Dark Reader Version: v4.9.47

**Comment by Gusted** [comment]
#6350

**Comment by martixy** [comment]
Seems to me it would be an awfully good idea to rename that issue's title to include the broken site.

You know, so search actually works.
