### ISSUE TITLE
GitHub logo disappers in filter mode

### ISSUE THREAD

**Issue by aashutoshrathi** [darkreader/darkreader#862]
![ezgif com-crop](https://user-images.githubusercontent.com/21199234/49024375-544a4080-f1bf-11e8-9ed4-3f251a229d3a.gif)

**Comment by Bullnados** [comment]
For me in vivaldi 2.2 it doesn't disapper. White goes black and and the figures has same colour like the background

**Comment by krupenja** [comment]
Hmm, also works fine here with Chrome 71.0.3578.80

**Comment by alexanderby** [comment]
I think it is Firefox CSS filter bug.

**Comment by aashutoshrathi** [comment]
Yeah, @alexanderby some issue with Firefox CSS filter.
Check: https://stackoverflow.com/questions/12173130/css-filter-not-working-in-firefox

**Comment by alexanderby** [comment]
I mean it is a bug with browser engine. Here, on GitHub, the header is inverted multiple times, and in some circumstances browser fails to render some content and it happens quite often in Firefox. You could try using the Dynamic mode here. I understand that the performance is slow, unfortunately Firefox is terribly slow in unpredictable places, some improvements will be published today.

**Comment by aashutoshrathi** [comment]
Thanks.
Please close this ticket when you push changes.

**Comment by Gusted** [comment]
Fixed.
