### ISSUE TITLE
[Broken Website] MyAnimeList

### ISSUE THREAD

**Issue by RebelNotorious** [darkreader/darkreader#8621]
# Broken Website Report

## Website Address

https://myanimelist.net/
## Steps To Reproduce

- Go to myanimelist.net
## Problematic Observation

Page margins are not being inverted with the rest of the webpage. Consistently occurs across the site.
## Screenshots

![2022-04-11 18_36_04-](https://user-images.githubusercontent.com/103449125/162797581-5f8e49cf-403f-45df-9d15-980a91090ea9.png)

## System Information

- OS: Windows 10
- Browser: Chrome 100
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
#6350

**Comment by hyperstown** [comment]
@Gusted  I believe this is not the same issue as #6350 
Previous issue occurred only when user opened page in new tab.
Now page has always white bars. Switching extension off and on doesn't work as well as reloading the page.

**Comment by Gusted** [comment]
Same underlying issue.
