### ISSUE TITLE
[Feature Request] Converts images

### ISSUE THREAD

**Issue by bowencool** [darkreader/darkreader#8637]
# Feature Request

## Is this feature request related to a problem?

No

## Screenshots
Converts images with light backgrounds and dark text to dark backgrounds and light text.

## Additional Context

Just like [deluminate](https://github.com/abstiles/deluminate) does.

**Comment by Gusted** [comment]
We are already doing that with background-image's: https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/image.ts

Is this a bug report?

**Comment by q1800** [comment]
Hi @Gusted,

I believe @bowencool means that they want individual images (pictures) on the web page with a white background in the image to be inverted to make them not blinding white and unreadable. I think you may be talking about the background image of the web page itself? Kind of like the background wallpaper on a desktop environment or window manager.

Perhaps @bowencool can specify which one they mean? I just thought I would chime in to help guide understanding. 😺

**Comment by bowencool** [comment]
I would like the white background in the individual images (pictures) on the page to be inverted so that they are not so blindingly white that they are unreadable.

**Comment by Gusted** [comment]
That won't be possible, because we will need to apply a filter to **all** images on a web pages, which would break many.
