### ISSUE TITLE
web.whatsapp.com emoji's look bad in Dynamic mode

### ISSUE THREAD

**Issue by GarethBlain** [darkreader/darkreader#864]
The emoji's in web.whatsapp.com are hard to use due to highlighting the selected emoji being almost the same colour as the background. 😞 

Also some of the emoji's are also being inverted and I can't see a way to prevent it in the dynamic config

![image](https://user-images.githubusercontent.com/5220736/49099300-04c04f00-f269-11e8-9728-608a7b692fe3.png)

**Comment by Gusted** [comment]
Fixed.
