### ISSUE TITLE
[Feature Request] Use site dark mode when available.

### ISSUE THREAD

**Issue by dwaxe** [darkreader/darkreader#8645]
# Feature Request

## Is this feature request related to a problem?
The problem is that on sites like Github, where pre-login screen there is a light-screen home page, I would love if Dark Reader were working its magic, but afterward, it goes pitch black in a combination of both the Dark Reader them and Github's Dark Theme. Is there a global way to detect whether a site has a dark mode, and if so enable it automatically when it appears? My current workaround is to use a keyboard shortcut to quickly enable/disable dark reader from a site, but that is often an unwelcome distraction when the login process is pretty quick anyways, but also so jarring when it does occur.

## Screenshots
Github light login screen:
![Screenshot 2022-04-14 21 03 43](https://user-images.githubusercontent.com/3530333/163516411-c411d05d-677a-4eff-bd57-3bc976039246.png)

Github dark logged in page: 
![image](https://user-images.githubusercontent.com/3530333/163516616-4fd43e3a-048d-4895-810b-52f6d452d1a4.png)

## Additional Context
This could potentially cut down on the need to add so many sites to the global dark list, see for example some of these PRs:
* https://github.com/darkreader/darkreader/pull/8644
* https://github.com/darkreader/darkreader/compare/master...dwaxe:patch-5?expand=1
* https://github.com/darkreader/darkreader/pull/6668
* https://github.com/darkreader/darkreader/pull/5355

This is distinct, but also hoping for [this ticket about supporting website dark modes linked here](https://github.com/darkreader/darkreader/issues/1285); as it may require similar website detection strategies.

**Comment by Gusted** [comment]
What's the difference between this request and this one: https://github.com/darkreader/darkreader/issues/1285?

**Comment by dwaxe** [comment]
The difference as I see it (linked #1285  it at the bottom of the feature request) is in addition to checking whether specific pages on a site have a dev-supported dark mode [1], have some way of making the website enable it.

1. [PR #7995](https://github.com/darkreader/darkreader/pull/7995) is a great start but unfortunately fails on many sites.

**Comment by Gusted** [comment]
It seems like you're requesting that dark reader will toggle the site's native dark mode. This is a no-go because this requires many site-specific javascript code which will clutter the size of the extension and requires more effort than the user simply toggling itself. Closing.

**Comment by pc00per** [comment]
> It seems like you're requesting that dark reader will toggle the site's native dark mode. This is a no-go because this requires many site-specific javascript code which will clutter the size of the extension and requires more effort than the user simply toggling itself. Closing.

I wonder how chrome's "WebContentsForceDark" flag feature works perfectly... If & only if, there's a native way to enable dark mode in firefox, would'nt have this issue at all.

**Comment by Gusted** [comment]
> I wonder how chrome's "WebContentsForceDark" flag feature works perfectly.

Chrome doesn't enable the native dark mode of the site. It instead (just like Chrome), modifies existing CSS.

**Comment by pc00per** [comment]
> > I wonder how chrome's "WebContentsForceDark" flag feature works perfectly.
> 
> Chrome doesn't enable the native dark mode of the site. It instead (just like Chrome), modifies existing CSS.

I'm not talking about enabling site's native dark mode.  I'm taking about respecting site's native dark mode (when it's there bydefault) & ignoring CSS modifications, which is what chrome's "WebContentsForceDark" do. This is almost pretty genius way to avoid forced CSS modifications done by extensions, caz they never do that calculation.

**Comment by Gusted** [comment]
> It's about respecting the presense of it (when it's there bydefault) & ignoring CSS modifications, which is what chrome's "WebContentsForceDark" do. This is almost pretty genius way to avoid forced CSS modifications done by extensions, caz they never do that calculation.

Aha, you might be interested to know that Dark Reader also has such feature (still somewhat flaky/BETA) https://github.com/darkreader/darkreader/discussions/9016
