### ISSUE TITLE
[Feature Request] Can a helmet dimmer be added?

### ISSUE THREAD

**Issue by qianjunlang** [darkreader/darkreader#8647]
# Feature Request
Is it possible to darken the top and bottom sections of the window in filter+ mode so that I can concentrate on the middle?
## Is this feature request related to a problem?
NO

**Comment by qianjunlang** [comment]
When reading PDFs, I use darkreader in fliter+ mode to protect my eyes. It's very useful, and I appreciate your team's efforts.
But there are times when I look at colorful charts and wish I could see their true colors.

Is it possible to include a helmet dimmer in the code?
I know how to code, so it's fine if you just send me a sample CSS code or something.

**Comment by Gusted** [comment]
That's technically not possible to implement.

**Comment by qianjunlang** [comment]
Thanks for your response.
