### ISSUE TITLE
Security Audit: Package vulnerabilities detected (as of v3.5.4)

### ISSUE THREAD

**Issue by cyberea** [darkreader/darkreader#866]
TL;DR cloning the repo and running `npm i` showed 13 vulnerabilities, with 4 being high risk. Can this be sorted out please?

Since I use this extension not only for personal use but work (and by the way the best utility extension I have come across - thank you), I wanted to make sure that this extension wasn't doing anything nefarious. Sometimes it may not be the intention of the developer(s) but as a result of a dependancy in use having a security flaw or malicious intent.

- upon running `npm audit` the following was noted:
  - `# Run  npm install --save-dev gulp@4.0.0  to resolve 5 vulnerabilities`
  - `SEMVER WARNING: Recommended action is a potentially breaking change`
- running `npm audit fix` seemed to have fixed one of the affected.
- running `npm audit fix --force` fixed them all but I am not too comfortable with that result as it could sometimes be a false positive (and potentially break the application).

Test conditions: MacOS 10.13.6 (17G3025), Node v8.13.0 (NPM 6.4.1).

**Comment by alexanderby** [comment]
Are you trying to build Dark Reader 3.5.4? The latest release is 4.6.12 (4.7.0 is about to be released).

These could be vulnerabilities, if these packages were used for running on a website. Also Gulp developer said that audit was wrong with these vulnerabilities.

But, last week or two a real vulnerability [was found](https://github.com/dominictarr/event-stream/issues/116), it could steal your crypto coins.  So, I decided to [replace](https://github.com/darkreader/darkreader/commit/5bd0cf2e168af7d871875a7e89c8ab9369ef9c4e) as much dev dependencies as possible with custom scripts. Now it reports no vulnerabilities at all.

Dark Reader itself has no dependencies (the only one is my own package without dependencies), so users are not vulnerable to NPM scam.

**Comment by cyberea** [comment]
I am not trying to build the application, I am simply checking for security vulnerabilities. It is never a good idea to just install an extension blindly assuming it is fully trustworthy. Some extensions have been found to track user data and/or worse.

Ultimately, if I use something that is either open source or developed by a third party, I prefer to thoroughly check its legitimacy and integrity, before making use of it.

**Comment by cyberea** [comment]
Your reply is sufficient and acceptable, thank you for replying and keep up the great work! :)
Feel free to close this issue, if there is nothing further to discuss.

**Comment by alexanderby** [comment]
Great, thank you.
