### ISSUE TITLE
[Broken Website] ubuntubudgie.org

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8669]
# Broken Website Report

## Website Address
https://ubuntubudgie.org/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the logo in the screenshot needs fixing.

## Problematic Observation
Logo

## Screenshots
![image](https://user-images.githubusercontent.com/95879668/163700652-0867087d-fd01-4ab2-8f64-a0ce54b64867.png)

## System Information

- OS: Windows 11
- Browser: Firefox Nightly 101
- Dark Reader Version: 4.9.47

**Comment by GrindamN** [comment]
Fixed. Try it now.

**Comment by q1800** [comment]
Hi @GrindamN, nice to meet you.

Very honored to have a Ubuntu Budgie Developer respond to me here. 😃

Please forgive me if I misunderstood your response, but I wasn't reporting a problem with Ubuntu Budgie's website itself. Rather, I was reporting an issue to the Dark Reader project that itself doesn't display the website logo correctly.

I believe this is a simple correction that needs to be made in the dynamic fixes file of Dark Reader.

**Comment by GrindamN** [comment]
> Hi @GrindamN, nice to meet you.
> 
> Very honored to have a Ubuntu Budgie Developer respond to me here. 😃
> 
> Please forgive me if I misunderstood your response, but I wasn't reporting a problem with Ubuntu Budgie's website itself. Rather, I was reporting an issue to the Dark Reader project that itself doesn't display the website logo correctly.
> 
> I believe this is a simple correction that needs to be made in the dynamic fixes file of Dark Reader.

Ah thanks :) Was just going to reply that there is bug on other websites too. It seems it doesn't recognize when the dark mode is on. Probably using different css function :)  @q1800

**Comment by q1800** [comment]
I believe you are correct. :) 

The logo issue itself is just a quick fix.

Thankfully, we have a great group of contributors, issue reporters and many others along the way. We also have a very nice owner of the project and a top notch invaluable maintainer that are both keystones to our success!

I personally like to think that I am @Gusted's very own pain in the neck! 🤣 🤣 🤣
