### ISSUE TITLE
[Broken Website] raspberrypi.org

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8678]
# Broken Website Report

## Website Address
https://www.raspberrypi.org/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the logo in the screenshot needs fixing.

## Problematic Observation
Logo

## Screenshots
![Raspberry Pi org](https://user-images.githubusercontent.com/95879668/163723630-a364e3c5-092b-4151-a2ff-1033c607165d.png)

## System Information

- OS: Windows 11
- Browser: Firefox Nightly 101
- Dark Reader Version: 4.9.47

**Comment by xcasxcursex** [comment]
If inverting the logo is the right way, here's your selector:

```
================================

raspberrypi.org

INVERT
.site-header__home-link

IGNORE IMAGE ANALYSIS
.c-at-home__container

================================
```

**Comment by xcasxcursex** [comment]
> Thank you @xcasxcursex for the suggested fix.
> 
> I have submitted PR #8836 to close this issue with your suggestion. I credited you as well in the PR for the fix.

Thanks mate. You're very kind to give credit but that's not necessary. I do accept blame though hahaha

I was in the neighbourhood and thought I could save somebody a little time by finding the selector for them. If it's helpful I can do that more, when I've got a minute to spare in future?
