### ISSUE TITLE
[Broken Website] polymc.org

### ISSUE THREAD

**Issue by isXander** [darkreader/darkreader#8684]
# Broken Website Report

## Website Address
https://polymc.org

## Steps To Reproduce

- go to polymc.org

## Problematic Observation
Parts of logo is inverted.

## Screenshots
DarkReader:
![image](https://user-images.githubusercontent.com/43245524/163845640-05451598-09a8-4ac7-a564-d452a92ce89b.png)
Expected:
![image](https://user-images.githubusercontent.com/43245524/163845692-ed005588-536a-48c7-95f6-00f0cc748a70.png)

## System Information
- OS: Linux
- Browser: Chrome 100
- Dark Reader Version: 4.9.47

**Comment by Gusted** [comment]
This is already the case, ensure you've the latest fixes. https://github.com/darkreader/darkreader#site-fixes
