### ISSUE TITLE
[Broken Website] NetsDaily.com - comment section (iOS mobile & desktop)

### ISSUE THREAD

**Issue by megam4n** [darkreader/darkreader#8725]
Website address:
• NetsDaily.com

Steps to Reproduce:
• Click any article and go to the comment section 

Problematic Observation:
• Comment section is white, unless you toggle off Dark Reader and then toggle it back on

Screenshots:
![65226178-559A-4396-830B-E38489C79EC9](https://user-images.githubusercontent.com/58749021/164476088-0e4e6177-216c-44a8-8ce6-65df847dbbed.png)
![69F058B3-F503-4542-BBB5-8C70582011AC](https://user-images.githubusercontent.com/58749021/164476095-fd4fed31-9ae7-470d-924e-33fe6922fcb3.png)

**Comment by Gusted** [comment]
Same underlying problem as #4682

**Comment by megam4n** [comment]
Why was this closed since the issue still persists on iOS mobile.

**Comment by Gusted** [comment]
It's closed as duplicate.
