### ISSUE TITLE
backgroud color turns to pink

### ISSUE THREAD

**Issue by Ynjxsjmh** [darkreader/darkreader#874]
The background color turns to pink on EmacsWiki like [LineWrap](https://www.emacswiki.org/emacs/LineWrap).  The darkreader mode is light. 

![1](https://user-images.githubusercontent.com/40143136/49335731-2dac5f80-f62e-11e8-80bf-f5995a3bffcf.png)

**Comment by Atemu** [comment]
In dark mode it turns dark red:

![image](https://user-images.githubusercontent.com/18599032/68086671-5ea0a000-fe4e-11e9-9ce3-5ce2b71edf8a.png)
