### ISSUE TITLE
[Broken Website] cloudlinux.com

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8763]
# Broken Website Report

## Website Address
https://www.cloudlinux.com/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the logos in the screenshots need fixing.

## Problematic Observation
Logos

## Screenshots
![CloudLinux](https://user-images.githubusercontent.com/95879668/164951883-91e3455d-077e-4a09-8ea4-51c8d81982f0.png)

![CloudLinuxOS Products](https://user-images.githubusercontent.com/95879668/164951888-de25ddc6-fcb5-4033-9d1c-759d1e9ed7a4.png)

## System Information

- OS: Windows 11
- Browser: Firefox Nightly 101
- Dark Reader Version: 4.9.48

**Comment by Gusted** [comment]
Are you deliberating trying to find websites with issues? Nobody has ever reported issues in bulks like this.

**Comment by q1800** [comment]
Hey @Gusted,

I would say about 50% yes / 50% no. Let me give a few examples.

Example 1: If I go to a grocery store website (ralphs.com) and then I find / already know that they have several other brand names (Food4Less, King Soopers, etc.) under the parent company (Kroger) or that it has different brand names in different regions of the country. I think to myself that if the actual grocery store brand in my area has a logo issue for their specific website, then possibly other websites within that same scenario may have same or similar issues. Then to take that same idea to the next level, I thought to look at their competitors websites (Aldi, Albertsons, etc.) or other businesses in the same / adjacent type of business market (Target, Walmart, etc.).

Example 2: If I read about / find out about a Linux laptop and I visit that company's website (tuxedocomputers.com) to learn more or see other models. I think to myself that if this one computer brand has a logo issue for their specific website, then possibly other competitors websites (Star Labs, System76, etc.) may have same or similar issues. Then to take that same idea to the next level, I thought to look at other computer hardware manufacturers websites (Raspberry Pi, Lambda Labs, Digital Storm, Steam Deck, HP, Samsung, etc) or other businesses in the same / adjacent type of business market (NewEgg, PC Part Picker, etc.).

Further examples: Jewelry Stores/Brands, Linux Distros/Desktop Environments/Window Managers/Apps, various Linux companies/projects/file hosting/CDNs, any Linux/Open-Source projects/multimedia/news sites/review sites/etc. or other technology things that I am personally interested in or that I help / contribute to (Dark Reader, uBlock Origin, EasyList filters, etc.).

---

I am very, very curious about the exact connotation of your reply. Can you please explain how you meant it to sound and clarify the meaning? Did you mean what you said as positive? With excitement and shock like "Wow, that's very awesome! I can't believe you are doing this. Nobody has ever done this before. It looks like you went out of your way to help." (See number 1 below) or did you mean what you said as negative? With resentment and dissatisfaction like "What the hell are you doing or what the hell were you thinking! Are you seriously and deliberately trying to find thousands of websites with issues that I have to fix because you are being a prick!?! Nobody has ever bulk reported issues like this, stop immediately!"? (See number 2 below).

1. I feel like the more websites that can be fixed, the better. This will definitely benefit anyone who uses Dark Reader when surfing the web. Whether they are willing to or don't know how to file bug reports to fix the issues or just say "What the hell is wrong with this site?" or "Why does this site look like this?" and just move on to another website or browser extension because they believe that website or Dark Reader itself is defective or broken.

2. I can understand if you don't want a million different sites and their fixes to be listed in the files that contain the fixes that can cause performance issues for Dark Reader or just make the entire size of the extension way too big. Also, along those same lines, I can understand if I am being a burden or pain in the butt to you and the project. **If it is this one, please understand I mean no malice or burdensome to you or the project. I will stop doing this immediately! I am honestly trying to help / contribute to the project and to benefit all users of Dark Reader the best I can / am able to.**

**Comment by Gusted** [comment]
> I am very, very curious about the exact connotation of your reply. Can you please explain how you meant it to sound and clarify the meaning? Did you mean what you said as positive? With excitement and shock like "Wow, that's very awesome! I can't believe you are doing this. Nobody has ever done this before. It looks like you went out of your way to help." (See number 1 below) or did you mean what you said as negative? With resentment and dissatisfaction like "What the hell are you doing or what the hell were you thinking! Are you seriously and deliberately trying to find thousands of websites with issues that I have to fix because you are being a prick!?! Nobody has ever bulk reported issues like this, stop immediately!"? (See number 2 below).
> 
>     1. I feel like the more websites that can be fixed, the better. This will definitely benefit anyone who uses Dark Reader when surfing the web. Whether they are willing to or don't know how to file bug reports to fix the issues or just say "What the hell is wrong with this site?" or "Why does this site look like this?" and just move on to another website or browser extension because they believe that website or Dark Reader itself is defective or broken.
> 
>     2. I can understand if you don't want a million different sites and their fixes to be listed in the files that contain the fixes that can cause performance issues for Dark Reader or just make the entire size of the extension way too big. Also, along those same lines, I can understand if I am being a burden or pain in the butt to you and the project. **If it is this one, please understand I mean no malice or burdensome to you or the project. I will stop doing this immediately! I am honestly trying to help / contribute to the project and to benefit all users of Dark Reader the best I can / am able to.**

To be very honest, that comment was made with frustration. On the other hand it does amaze me how one can find so many issues.

While on one hand it does frustrate me, creating a fix can take a few minute for each site. So doing that each few days will become a PITA(dev tools aren't really focused on making many fixes fast). It would be nice if you were able to report all these sites in 1 issue so I don't have to mute my phone due to many incoming mails 😄. 

On the other hand it really does become time that I will craft some very generic logo selectors and apply them unconditionally, because many many are just the same class or id with a slight variation.

Interesting how you're able to find so many websites 😅.
