### ISSUE TITLE
[Bug] Detecting System Dark/Light Mode broken on Brave Browser (linux)

### ISSUE THREAD

**Issue by cacio-confusa** [darkreader/darkreader#8772]
# Bug Report

## Bug Description
On Brave Browser on Fedora (Linux) the Darkreader is not detecting Brave/ System mode but only shows dark mode all the time.
while on firefox it does switch wonderfully with the system setting.

- OS: Linux (Fedora 36)
- Browser: V1.37.116
- Dark Reader Version: 4.9.48

**Comment by Gusted** [comment]
Hi @cacio-confusa if you go to Brave and then open the console(ctrl + shift + i -> Console tab) and type `matchMedia('(prefers-color-scheme: dark)').matches` and press enter. What does it output? We rely on the browser to get the operating system's dark mode.

**Comment by cacio-confusa** [comment]
it outputs:
true
while currently having the light mode on (brave browser UI and all follow system light theme)

**Comment by Gusted** [comment]
Well then Brave is giving dark reader incorrect information, not much we can do.
