### ISSUE TITLE
[Bug] Google Drive: Inversion of a specific image is different between two devices

### ISSUE THREAD

**Issue by Elaborendum** [darkreader/darkreader#8782]
# Bug Report

## Website Address

https://drive.google.com

## Bug Description

I logged into my FF account in a new device and so it synced all my add-ons and their settings, I didn't mess around in DR's settings after this either. I went to Google Drive and noticed that the image that appears in the details tab when there are no files selected was darkened. 

I found out that it was because of the `div[data-label="nd"] > div > div > svg > path[fill="#000000"]` selector, and removing it fixed it. However, as I still had access to my old device, I opened Google Drive on it and found out that it looked normal. Removing the previously mentioned selector instead made the image dark, like it was in the new device by default.

When opening DevTools, I realized that in the new device it said the value of its style attribute was `"--darkreader-inline-fill:`` #e8e6e3;"`, while in the old device it was`"--darkreader-inline-fill: #000000;"`. This last value was also present in a new profile and Google Chrome.

## Steps To Reproduce
?

## Expected Behavior

Consistent behaviour between both devices

## Actual Behavior

Inconsistent behaviour between both instances.

## Screenshots

The image in question, properly inverted
![image](https://user-images.githubusercontent.com/71190696/165839831-b8fcbd1b-f0fe-41b8-b90a-13c46f1cb451.png)

Old device:
![imagen](https://user-images.githubusercontent.com/71190696/165846828-da8f6cdf-bab2-4396-ac37-1d7db7331abd.png)

New device:
![imagen](https://user-images.githubusercontent.com/71190696/165847002-b72b8ae7-fd52-4509-a365-d251c7e74514.png)

## System Information

- OS:  Windows 10
- Browser:  Firefox 99.0.1
- Dark Reader Version:  4.9.48

## Additional Context

A fix would be simply adding `[style="--darkreader-inline-fill: #000000;"]` to the end of that selector, but I was not entirely sure if it could indicate a bigger problem, or if it was just a weird bug on that specific profile or just a setting I somehow missed?

**Comment by Gusted** [comment]
> I logged into my FF account in a new device and so it synced all my add-ons and their settings

Could you confirm this please? Because Dark Reader should have consistent behavior. Because dark reader itself should handle this 😄. Otherwise the fix would be to `IGNORE INLINE STYLE` this element.

**Comment by Gusted** [comment]
Interesting behavior, maybe something in `about:config`. I will go ahead and make the PR tho.
