### ISSUE TITLE
[Broken Website] caddyserver.com

### ISSUE THREAD

**Issue by davidpanic** [darkreader/darkreader#8783]
# Broken Website Report

## Website Address

https://caddyserver.com/

## Steps To Reproduce

- Go to the site's main page.

## Problematic Observation

The top half of the site is unreadable and hurts my eyes.

## Screenshots

![image](https://user-images.githubusercontent.com/13370323/165947156-b11dffc5-9469-48bf-b1bd-5160c4d8cba4.png)

## System Information

- OS: Artix Linux
- Browser: Firefox 99.0.1
- Dark Reader Version: 4.9.48

## Additional Context

None.

**Comment by radna0** [comment]
Can you explain in more details?
