### ISSUE TITLE
[Broken Website] tiktok.com

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#8787]
# Broken Website Report

## Website Address
`tiktok.com`

## Steps To Reproduce

Go to tiktok.com.
See the like and share buttons.

## Problematic Observation

The buttons should be white, like the comments button.

## Screenshots

![image](https://user-images.githubusercontent.com/30274161/166086231-ab79c1ec-e89a-4fea-b894-0ef032ce09eb.png)

## System Information

- OS:  Windows
- Browser:  Chrome 101.0.4951.41
- Dark Reader Version:  4.9.48

## Additional Context

No additional information.

**Comment by Gusted** [comment]
Do you have a example video?

**Comment by Tiagoquix** [comment]
> Do you have a example video?

https://streamable.com/pbp29o

**Comment by Gusted** [comment]
Please check if you have the latest fixest: https://github.com/darkreader/darkreader#site-fixes and please ensure you're on the latest version of Dark Reader. Non-reproducible for me:

![image](https://user-images.githubusercontent.com/25481501/166123759-793095f9-e7d7-46f7-9a2d-d484fa31e10c.png)

**Comment by Tiagoquix** [comment]
> Please check if you have the latest fixest: https://github.com/darkreader/darkreader#site-fixes and please ensure you're on the latest version of Dark Reader. Non-reproducible for me:
> 
> ![image](https://user-images.githubusercontent.com/25481501/166123759-793095f9-e7d7-46f7-9a2d-d484fa31e10c.png)

The issue persists after enabling the site fixes. I'm on the latest version (4.9.48).

**Comment by Tiagoquix** [comment]
I use the default settings (dynamic theme).

**Comment by Tiagoquix** [comment]
@Gusted 
The fix worked, but with two caveats:

- the first two videos always have the buttons with the wrong colors;
- toggling the option to sync site fixes seems to fix this first problem (as if it was an "update" to the extension).

Demonstration video: https://streamable.com/x4eqwb

I also noted that the TikTok logo in the upper left corner gets its colors inverted.
