### ISSUE TITLE
[Bug] Dark Reader broken on Firefox Nightly (not able to transition between CSS)

### ISSUE THREAD

**Issue by sharbet** [darkreader/darkreader#8789]
# Bug Report

## Bug Description

Firefox Nightly 101.0a

When page initially loads, Dark Reader fails to properly select and transition light css to dark css.

## Steps To Reproduce

Dark Reader configs: 

`{
    "enabled": true,
    "fetchNews": false,
    "theme": {
        "mode": 1,
        "brightness": 100,
        "contrast": 100,
        "grayscale": 0,
        "sepia": 0,
        "useFont": false,
        "fontFamily": "Segoe UI",
        "textStroke": 0,
        "engine": "dynamicTheme",
        "stylesheet": "",
        "darkSchemeBackgroundColor": "#272727",
        "darkSchemeTextColor": "#e8e6e3",
        "lightSchemeBackgroundColor": "#dcdad7",
        "lightSchemeTextColor": "#181a1b",
        "scrollbarColor": "auto",
        "selectionColor": "auto",
        "styleSystemControls": false,
        "lightColorScheme": "Default",
        "darkColorScheme": "Default",
        "immediateModify": false
    },
    "presets": [],
    "customThemes": [],
    "siteList": [
        "www.reddit.com",
        "www.samsungebiz.com"
    ],
    "siteListEnabled": [
        "imgur.com",
        "www.epicgames.com",
        "www.base64decode.org",
    ],
    "applyToListedOnly": false,
    "changeBrowserTheme": false,
    "syncSettings": true,
    "syncSitesFixes": true,
    "automation": "",
    "automationBehaviour": "OnOff",
    "time": {
        "activation": "18:00",
        "deactivation": "9:00"
    },
    "location": {
        "latitude": null,
        "longitude": null
    },
    "previewNewDesign": true,
    "enableForPDF": true,
    "enableForProtectedPages": false,
    "enableContextMenus": false,
    "detectDarkTheme": false,
    "notifyOfNews": false,
    "readNews": [
        "v4-9-16",
        "v4-9",
        "attention",
        "dr-5-announcement",
        "2m-users",
        "automation",
        "product-hunt-golden-kitty-2018",
        "time-settings",
        "safari",
        "500k-users",
        "stylish",
        "product-hunt",
        "custom-site-settings",
        "thanks-for-contribution",
        "dynamic-theme"
    ]
}`

Sites were chosen at random. All sites are like this.

Go to [Bloomberg](https://www.bloomberg.com/markets) or [Fluent Reader](https://hyliu.me/fluent-reader/) and let Dark Reader load (without altering Dark Reader configs)

Observe site

## Expected Behavior

![Screenshot 2022-04-30 at 16-01-28 Bloomberg Markets - Bloomberg](https://user-images.githubusercontent.com/73639287/166095992-9abfe298-3392-48d2-a965-e7377b5d95e5.png)

![Screenshot 2022-04-30 at 16-01-06 Fluent Reader](https://user-images.githubusercontent.com/73639287/166095995-552a38cd-0d59-4bd6-be2a-b8cb3c651104.png)

## Actual Behavior

![Screenshot 2022-04-30 at 16-01-20 Bloomberg Markets - Bloomberg](https://user-images.githubusercontent.com/73639287/166095998-ad881798-f416-4a75-8bf4-68b6fbba1513.png)

![Screenshot 2022-04-30 at 16-00-46 Fluent Reader](https://user-images.githubusercontent.com/73639287/166096002-a991e4e3-d796-4bf2-bb37-e1e03df19ccc.png)

If I manually turn off Dark Reader and turn it on again, it loads properly. (Expected Behavior)

## Screenshots

Attached above

## System Information

- OS:  Windows 10
- Browser:  Firefox Nightly 101
- Dark Reader Version:  4.9.48

**Comment by Gusted** [comment]
Well this is fun I started experiencing this since Friday(2022-04-29) and so far it seems to be a regression from Firefox's side. I'm not able to dig in and see what's the problem(as it happens _inconsistent_ for me), but feel free to open a bug at Mozilla for this as this only started since a recent Firefox Nightly version and they love regression reported 😄.

**Comment by sharbet** [comment]
I figured as well. Problem happening since their 04.27-ish update, where they changed their CSS part.
[changelog](https://mrotherguy.github.io/fx-nightly-changelog/)

Will report, but they take issues more seriously if similar reports come from renowned users (like developer of Dark Reader :) ) 

Can you give them a heads-up if you can? 

Link to BugZilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1767176

**Comment by emilio** [comment]
Yeah this is an issue with adopted stylesheets not working from extensions on Firefox (it's tricky due to our security wrappers), and is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1766909.

As a workaround on darkreader's side, `try` / catching in handleAdoptedStyleSheets would do.

That workaround would be appreciated, though the patch in that bug should also address the issue.

**Comment by xcasxcursex** [comment]
Thanks muchly, I was starting to wonder if it was just me.

https://ftp.mozilla.org/pub/firefox/nightly/2022/04/2022-04-28-21-47-15-mozilla-central/

Meantime if anyone needs DR working, this is the most recent build which still works.

**Comment by Gusted** [comment]
@sharbet Thanks for opening the bug report!

@emilio Thanks for the head-ups and the workaround. Opened a PR for it: #8801

**Comment by Gusted** [comment]
Dark Reader v4.9.50(which includes the fix) [has been released](https://addons.mozilla.org/en-US/firefox/addon/darkreader/)

**Comment by sharbet** [comment]
> Dark Reader v4.9.50(which includes the fix) [has been released](https://addons.mozilla.org/en-US/firefox/addon/darkreader/)

Thank you for the hard work! Will install!

Now if there was a way to force extension update on Fenix... (Fenix fails to fetch the latest update automatically, and there's no force updat)

**Comment by xcasxcursex** [comment]
Checks out here. I had a repeatable failure mode and it's working now. Thanks all!

**Comment by kmbrunson** [comment]
> # Bug Report
> ## Website Address
> ## Bug Description
> 
> Firefox Nightly 101.0a
> 
> When page initially loads, Dark Reader fails to properly select and transition light css to dark css.
> ## Steps To Reproduce
> 
> Dark Reader configs:
> 
> `{ "enabled": true, "fetchNews": false, "theme": { "mode": 1, "brightness": 100, "contrast": 100, "grayscale": 0, "sepia": 0, "useFont": false, "fontFamily": "Segoe UI", "textStroke": 0, "engine": "dynamicTheme", "stylesheet": "", "darkSchemeBackgroundColor": "#272727", "darkSchemeTextColor": "#e8e6e3", "lightSchemeBackgroundColor": "#dcdad7", "lightSchemeTextColor": "#181a1b", "scrollbarColor": "auto", "selectionColor": "auto", "styleSystemControls": false, "lightColorScheme": "Default", "darkColorScheme": "Default", "immediateModify": false }, "presets": [], "customThemes": [], "siteList": [ "www.reddit.com", "www.samsungebiz.com" ], "siteListEnabled": [ "imgur.com", "www.epicgames.com", "www.base64decode.org", ], "applyToListedOnly": false, "changeBrowserTheme": false, "syncSettings": true, "syncSitesFixes": true, "automation": "", "automationBehaviour": "OnOff", "time": { "activation": "18:00", "deactivation": "9:00" }, "location": { "latitude": null, "longitude": null }, "previewNewDesign": true, "enableForPDF": true, "enableForProtectedPages": false, "enableContextMenus": false, "detectDarkTheme": false, "notifyOfNews": false, "readNews": [ "v4-9-16", "v4-9", "attention", "dr-5-announcement", "2m-users", "automation", "product-hunt-golden-kitty-2018", "time-settings", "safari", "500k-users", "stylish", "product-hunt", "custom-site-settings", "thanks-for-contribution", "dynamic-theme" ] }`
> 
> Sites were chosen at random. All sites are like this.
> 
> Go to [Bloomberg](https://www.bloomberg.com/markets) or [Fluent Reader](https://hyliu.me/fluent-reader/) and let Dark Reader load (without altering Dark Reader configs)
> 
> Observe site
> ## Expected Behavior
> 
> ![Screenshot 2022-04-30 at 16-01-28 Bloomberg Markets - Bloomberg](https://user-images.githubusercontent.com/73639287/166095992-9abfe298-3392-48d2-a965-e7377b5d95e5.png)
> 
> ![Screenshot 2022-04-30 at 16-01-06 Fluent Reader](https://user-images.githubusercontent.com/73639287/166095995-552a38cd-0d59-4bd6-be2a-b8cb3c651104.png)
> ## Actual Behavior
> 
> ![Screenshot 2022-04-30 at 16-01-20 Bloomberg Markets - Bloomberg](https://user-images.githubusercontent.com/73639287/166095998-ad881798-f416-4a75-8bf4-68b6fbba1513.png)
> 
> ![Screenshot 2022-04-30 at 16-00-46 Fluent Reader](https://user-images.githubusercontent.com/73639287/166096002-a991e4e3-d796-4bf2-bb37-e1e03df19ccc.png)
> 
> If I manually turn off Dark Reader and turn it on again, it loads properly. (Expected Behavior)
> ## Screenshots
> 
> Attached above
> ## System Information
> 
>     * OS:  Windows 10
> 
>     * Browser:  Firefox Nightly 101
> 
>     * Dark Reader Version:  4.9.48
> 
> 
> ## Additional Context

Sorry, I only scrolled back a couple days & didn't see Gusted's bug report for same issue. This is a fantastic addon!
