### ISSUE TITLE
Opera: DuckDuckGo, Google search results do not darken

### ISSUE THREAD

**Issue by Darthagnon** [darkreader/darkreader#879]
Until recently, Dark Reader has worked just about perfectly, in Opera. Now, having updated to Opera 57, DuckDuckGo's search results page shows up as white only, though the search page shows up properly darkened.

**Comment by Darthagnon** [comment]
Google search results no longer darken, either.

**Comment by edumello** [comment]
Try to enable "Allow access to search page results" on plugins settings

**Comment by alexanderby** [comment]
You are right, it is a recent Opera change https://twitter.com/darkreaderapp/status/1068464934089093120

**Comment by Darthagnon** [comment]
Thank you so much! I'll try that. That probably explains, too, why uBlock Origin has stopped blocking ads on search results. What a bizarre change in Opera; one would have thought that allowing an extension access to "all websites" would include search results.

**Comment by Gusted** [comment]
Had been fixed a a a while ago by OP
