### ISSUE TITLE
Doesn't work on Chrome Canary

### ISSUE THREAD

**Issue by Udokah** [darkreader/darkreader#880]

**Comment by alexanderby** [comment]
Works well on 73.0.3630.0 (macOS). What is your OS and Canary version? Are there any errors in console?

**Comment by Chubjay** [comment]
Hi there, Jay here.
I'm x86 Win 10 Pro Insider Preview
Build 18290rs_prerelease 181121-1501
Google Chrome
Version 73.0.3630.0 (Official Build) canary (32-bit),
& works fine till now, except 'Settings' page.
Look @ att pic ...
Hugs.
![darker anigif](https://user-images.githubusercontent.com/35041272/49470067-3351a300-f7f0-11e8-852e-0c49fa8b183b.gif)

**Comment by Udokah** [comment]
It only started working later, I'm not sure what happens but my Chrome Canary version has been updated and it works fine.
