### ISSUE TITLE
[Localization] Outdated descriptions

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#8804]
I noticed that the description in the Chrome Web Store is outdated compared to the file on GitHub. Possibly, I believe that the extension's internal texts (such as the description that appears in chrome://extensions and on the shortcuts page) are also outdated. It's just my guess.

But anyway, the Chrome store description is outdated compared to the latest changes in the English localization files.

*Oh, and if possible, update those strings with the changes I made in PT-BR as well.*

**Comment by Gusted** [comment]
@alexanderby
