### ISSUE TITLE
[Bug] Must toggle off/on for every site

### ISSUE THREAD

**Issue by kmbrunson** [darkreader/darkreader#8818]
# Bug Report

## Bug Description

Since FF Nightly 101 addon does not convert it to dark. Requires toggle from settings (on/auto/off). Then again for each page of site.

## Steps To Reproduce

Go to any site. It will be light mode,
FF menu /addons/dark Reader
Change on to off to on
Site converts to dark

## Expected Behavior

Should automatically convert to dark 
## Actual Behavior

Must toggle addon in settings before addon takes effect
## System Information

Samsung  galaxy  s10e
- OS: 
- android  12
- Browser: 
- Firefox Nightly 101.0a1
- Dark Reader Version: 
4.9.48
## Additional Context

Still works perfectly on s8 running android 10 and same FF and DR versions

Android 12 Developer Option / Force Dark Mode has no effect on this issue.

**Comment by Gusted** [comment]
Download the latest version of Dark Reader. See https://github.com/darkreader/darkreader/issues/8789

**Comment by Luke-L** [comment]
i have the same problem, but before i toggle, its like half converted and looks really shitty. only have this problem on chrome.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Sel, 3 Mei 2022, 4:03 AM kmbrunson ***@***.***> menulis:
