### ISSUE TITLE
Dark Reader affects Google Translate extension's popup

### ISSUE THREAD

**Issue by hohoaisan** [darkreader/darkreader#884]
![image](https://user-images.githubusercontent.com/26185060/49558163-ac5e1100-f93c-11e8-85a3-29cc045bc8c1.png)

**Comment by hohoaisan** [comment]
So is there a way to fix this or i must toggle current site to off whenever using Google Translate?

**Comment by alexanderby** [comment]
The fix is planned. But since this extension is widely spread, I will look for a quick hack now. If it is possible, it will get into today's release.

By the way, this is a duplicate of https://github.com/darkreader/darkreader/issues/625, so I'm closing the issue.
