### ISSUE TITLE
Bug - Chrome/Firefox - All pages toggled dark, regardless of list

### ISSUE THREAD

**Issue by Elliott-M** [darkreader/darkreader#885]
All of the sites I view are toggled to dark, regardless of the list I have set.  Inverting the list only changes the sites on the list.  All other sites remain dark, and are not toggleable.  Rather, the toggle button adds and removes sites to the list, but it has no effect.

![image](https://user-images.githubusercontent.com/1437327/49589954-44a1c900-f930-11e8-9879-7870fa02f818.png)
![image](https://user-images.githubusercontent.com/1437327/49589961-479cb980-f930-11e8-9548-919d2fba9ddc.png)

EDIT: Stupidly showed some internal domains in the images.

**Comment by CollinChaffin** [comment]
Confirmed here too this really freaked me out since it came at the exact time where this latest build of Chrome DEV is totally broken and I had to roll back anyway, but then to have this extension exhibit this made it appear that I had not gotten to the root issue (the Chrome build) when I had and this extension in essence "sticking" on (if enabled) regardless of settings - was just like winning the bad luck lottery, LOL.  

Hopefully this can be addressed quickly since it's about as critical as it gets.

**Comment by james-love** [comment]
Having this issue as well, I've tracked it down to check in [294725888f90b3262bbc1e028604a85ceed926bb](https://github.com/darkreader/darkreader/tree/294725888f90b3262bbc1e028604a85ceed926bb)

**Comment by samiggapps** [comment]
Also experiencing this issue!
Please find a fix ASAP!
This is the whole reason I use this extension and it is amazing!!

**Comment by Horodep** [comment]
Same.

**Comment by Mistrelvous** [comment]
This is happening to me too. My favorite browser extension is malfunctioning and now my whole browsing experience is ruined. Guess I'm gonna have to view websites with their bright-white bullshit for a few hours/days until this is fixed. Oh well.

**Comment by adzengland** [comment]
Thought I was going mad.  Favourite extension is borked.

**Comment by alexanderby** [comment]
Thank you all for the quick reply. Just pushed a fix in version 4.7.1.

It usually is available for Chrome within an hour and for Firefox within 5 minutes.

**Comment by CollinChaffin** [comment]
Thanks @alexanderby!

**Comment by christopherpugh** [comment]
Thank you @alexanderby 

Confirmed resolved in 4.7.1 Firefox 63.0.3

Great extension!

**Comment by garulovilla** [comment]
Thanks! @alexanderby. 👍

**Comment by james-love** [comment]
Confirmed working on Chrome 71.0.3578.80
Thanks for the quick fix @alexanderby!

**Comment by Echolz** [comment]
Thanks for the quick fix @alexanderby!
Love this extension!

**Comment by mattdavenport** [comment]
Thanks @alexanderby! Was just writing up an issue on this and Github's related issues feature helped me find this one. Great turnaround and much appreciated! Love the extension!
