### ISSUE TITLE
[Bug] Dark Reader does not work with address bar

### ISSUE THREAD

**Issue by Zhuoy3** [darkreader/darkreader#8859]
# Bug Report

## Bug Description

The dark reader cannot take effect on the address bar of chrome, and it still displays the original color. 
I also observed a similar phenomenon in the edge, but the failure scope includes more places including the bookmarks bar.

## Steps To Reproduce

Just open the browser.

## Expected Behavior

A dark mode could be generated everywhere including the address bar.

## Screenshots

![Screenshots1](https://files.catbox.moe/qb4738.png)
![Screenshots1](https://files.catbox.moe/zl3mji.png)

## System Information

- OS:  Windows 10 19044.1706
- Browser: Chrome 101.0.4951.64
- Dark Reader Version:  4.9.48

**Comment by Gusted** [comment]
This is expected, this isn't a feature of Dark Reader. Extensions aren't able to touch those elements, please install [a dark theme](https://chrome.google.com/webstore/search/dark?_category=themes) in the chrome webstore to accomplish this.
