### ISSUE TITLE
domain matching - how to ignore certain paths?

### ISSUE THREAD

**Issue by atomGit** [darkreader/darkreader#886]
scenario is dark everywhere by default

ex url: example.com/wp-admin/

i want to ignore (not darkify) all of example.com except example.com/wp-admin/ and anything under that - in other words ignore my WordPress website, but darken the entire back end

didn't work - DR just chucks these :)
```
example.com/^wp-admin/
example.com/[^wp-admin]
```
#28 - this fella wanted to do something similar i think, which is why he requested separate lists - i also don't understand why one would want to toggle the same list; if you have an ignore list, or a dark only list, i don't understand why one would want to toggle that

#373 - my answer might be here, but i'm not seeing it

**Comment by alexanderby** [comment]
#28 is planned, but it will not help in your case.

#373 should fix your issue. It is planned to add negative patterns (like in .gitignore files), so it will look like:
```
example.com
!example.com/wp-admin
```

Also clear RegExps support is planned:
```
/example\.com\/wp-admin/
```

**Comment by alexanderby** [comment]
Regular Expression support added by https://github.com/darkreader/darkreader/commit/bc65ef4c2cbbd6ebffe6f269505c6ce32ec611a0

The RegExps should start and end with `/`, like `/www\.example\.com`. They are matched against the whole URL including the protocol.
