### ISSUE TITLE
Selecting the "Change the Browser theme" option on Firefox can turn black even the title bar, but there is no option in Chrome. I do n’t know why, how can I solve it?

### ISSUE THREAD

**Issue by cc19264997** [darkreader/darkreader#8862]
Selecting the "Change the Browser theme" option on Firefox can turn black even the title bar, but there is no option in Chrome. I do n’t know why, how can I solve it?

The two version numbers are the same!
![165230286-c82fad0e-8b55-406d-9b83-2bcc7c884971](https://user-images.githubusercontent.com/25716656/167793920-2f279ba9-dbe6-4cde-ae84-9027b97ffb46.jpg)

**Comment by Gusted** [comment]
Chrome doesn't allow extensions to theme the browser.

**Comment by cc19264997** [comment]
> Chrome 不允许扩展程序为浏览器设置主题。

Thank! Does the next version consider increasing?
