### ISSUE TITLE
{ Dynamic } Ebay - Poland

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#887]
As it seems, does each country theme ebay a bit different. And I guess, they change that over that time. 
https://www.ebay.pl/sch/Zdrowie-i-Uroda/26395/i.html

**Comment by ShalokShalom** [comment]
Here is a site that lists all of the ebay subdomains: http://www.ebayweb.com/ebay-international-sites/

**Comment by alexanderby** [comment]
Thank you, I was searching for it today. I think I will enable inline background image analysis for root elements.

**Comment by Gusted** [comment]
LGTM
