### ISSUE TITLE
[Bug] Selecting the "Change the Browser theme" option on Firefox can turn black even the title bar, but there is no option in Chrome. I do n’t know why, how can I solve it?

### ISSUE THREAD

**Issue by cc19264997** [darkreader/darkreader#8879]
Selecting the "Change the Browser theme" option on Firefox can turn black even the title bar, but there is no option in Chrome. I do n’t know why, how can I solve it
![165230286-c82fad0e-8b55-406d-9b83-2bcc7c884971](https://user-images.githubusercontent.com/25716656/168242917-8b5da756-2fe0-468b-8fe5-2da822635427.jpg)
?

**Comment by Gusted** [comment]
Duplicate of https://github.com/darkreader/darkreader/issues/8862 Please don't make new issues for already answered questions. You won't receive a different response.
