### ISSUE TITLE
Invert listed only - no longer works

### ISSUE THREAD

**Issue by IgorWolbers** [darkreader/darkreader#889]
As of 10 minutes ago, which happens to coincide with a release that was just pushed, the `Invert listed only` no longer has any affect. Every site is inverted and the configured list is ignored. Please see the attached animated gif illustrating the problem. I also included `Not invert listed` in the gif demo to show that this does still work.

![darkreaderinvertednotworking](https://user-images.githubusercontent.com/6107962/49597306-2648c700-f94a-11e8-981b-6348af730b81.gif)

---
On an unrelated note I would like to add that this is a great product. Thank you (and also anyone else involved) for making it, maintaining it, and making it available.

**Comment by Timsonrobl** [comment]
Same here.
Win 10,  Chrome 70.0.3538.110

**Comment by alexanderby** [comment]
The problem was just fixed, [here](https://github.com/darkreader/darkreader/issues/885#issuecomment-444927240) is some info how to speed up the update.
