### ISSUE TITLE
Google Chrome Flashes

### ISSUE THREAD

**Issue by mcatovic** [darkreader/darkreader#891]
Any time I open a new tab, refresh a page, or have a online form dynamically update Google Chrome flashes a bright white screen before the theme is applied. I'm on a VDI using Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) and Dark Reader Version 4.6.12. Any idea how to prevent this? It happens on all of the engines Filter, Filter+, Static, and Dynamic.

**Comment by 125m125** [comment]
From the FAQ ( https://darkreader.org/help/en/ ):

**Screen flashes white when opening a new tab or navigating a website**
Before loading a website, Chrome shows theme background color by default, so you should install some dark theme from the store.

**Comment by mcatovic** [comment]
How will that help though? Themes don’t change the website’s appearance, only the browser’s as far as I know. Isn’t the white flash I’m seeing the initial white web page loading?

**Comment by alexanderby** [comment]
Maybe try [this one](https://chrome.google.com/webstore/detail/material-incognito-dark-t/ahifcnpnjgbadkjdhagpfjfkmlapfoel). I don't remember, if this problem was fixed in Chrome 65, maybe you should try to update. Also I'm not sure, if VDI and limited amount of resources could be the issue. Does it happen on all websites or only on some specific?

**Comment by patrickdo** [comment]
Thanks @alexanderby, I switched to your linked Material Incognito Dark and no longer experience the white flash. I had been using Developer Edition Dark previously.

**Comment by alexanderby** [comment]
Maybe you could try using Filter or Static mode for this website? Could you please share the URL?

**Comment by mcatovic** [comment]
@alexanderby I get the same result using Filter and Static mode. The website I'm using is a web service called Medidata Rave. The URL is actually a sub-domain of [www.mdsol.com](https://www.mdsol.com) So it's mycompanyname.mdsol.com/MedidataRave/(S(jejojp1wxz0ntx4l4htt4zai))/HomePage.aspx and it looks nothing like mdsol.com. Here is where I do my work creating electronic data capture forms and have access to production data our clients submit.

I tried digging around their [help section](https://learn.mdsol.com/home/en/space-directory-92143618.html) to see if I could find anything helpful and there's two spots you can look at. There is

[Developer Central: Starting point for developers who wish to interact with Medidata Clinical Cloud via APIs and mobile SDK](https://learn.mdsol.com/api/medidata-developer-central-94469503.html)

[Rave Web Services: A Knowledge Space for Rave Web Services (RWS) - the application programming interface (API) which can facilitate rapid integrations of clinical systems with Medidata Rave.](https://learn.mdsol.com/api/rws/rave-web-services-home-95587257.html)

**Comment by Gusted** [comment]
Use theme.
