### ISSUE TITLE
[Feature Request] Stack Exchange's "highlight" feature remains white

### ISSUE THREAD

**Issue by 07416** [darkreader/darkreader#8912]
# Feature Request

## Is this feature request related to a problem?

Stack Exchange's "highlight" feature to accentuate [directly linked answers](https://stackoverflow.com/a/11227902) isn't darkened. Affects [all SE websites](https://stackexchange.com/sites).

## Additional Context

Chromium's 'Auto Dark Mode for Web Contents' feature (`chrome://flags/`) converts adequately.

**Comment by Gusted** [comment]
Use the broken website template for bug reports.
