### ISSUE TITLE
bbs.pcbeta.com doesn't work

### ISSUE THREAD

**Issue by LsnmxNB** [darkreader/darkreader#892]
如题，谢谢
@alexanderby
 
![snipaste_2018-12-07_12-22-16](https://user-images.githubusercontent.com/42826027/49627627-d2f27980-fa1a-11e8-9671-98ec923f1a88.png)
![snipaste_2018-12-07_12-22-35](https://user-images.githubusercontent.com/42826027/49627629-d38b1000-fa1a-11e8-8d0a-de61d3e46485.png)

**Comment by schrodog** [comment]
please use English, xie xie

**Comment by Gusted** [comment]
English and you have it on light mode.... So it's working fine.
