### ISSUE TITLE
[Bug] Removed DarkReader and it is STILL put all websites in dark mode

### ISSUE THREAD

**Issue by nej493** [darkreader/darkreader#8921]
# Bug Report

## Bug Description

Tried removing the extension, and websites were still in dark mode. Rebooting/restarting browser did not fix.
Using Brave on Ubuntu. 

## System Information

Brave. [Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit)

- OS: Linux 
- Browser: Brave 
- Dark Reader Version: Most recent as of May 20, 2022

**Comment by Gusted** [comment]
This is the wrong issue tracker to report this. Dark Reader doesn't handle the process of removing extensions. Please report this to your browser's issue tracker.
