### ISSUE TITLE
[Bug] Can't find settings import in 4.9.50?

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#8930]
# Bug Report

## Bug Description
I can't find the settings import ANYWHERE in Dark Reader 4.9.50 (Firefox). In Dark Reader 4.9.48 (Chrome) I can easily find the settings management to export my settings but what use is that if I can't import them?

## Steps To Reproduce
Chrome:

![image](https://user-images.githubusercontent.com/4723091/169691004-9a960633-7ecd-4c01-92a2-b2b01d272454.png)

![image](https://user-images.githubusercontent.com/4723091/169691006-21bccfe7-bd4d-45c6-9551-91f63bea233d.png)

![image](https://user-images.githubusercontent.com/4723091/169691011-f47796ee-c3ce-424a-b91f-fab95e9b8ecb.png)

Firefox:

![image](https://user-images.githubusercontent.com/4723091/169691043-cd9f304b-cfbf-453b-b5a0-435165fa3022.png)

![image](https://user-images.githubusercontent.com/4723091/169691062-0be3225b-56c5-44f0-b380-e147d085be90.png)

Where is the settings import?!

## System Information
- OS: Windows 10 Home 2004 build 19041.928 (64-bit)
- Browser: Firefox Developer Edition 101.0b9 (64-bit)
- Dark Reader Version: 4.9.50

**Comment by Gusted** [comment]
Hi @LoganDark!

Please enable the preview design:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

**Comment by LoganDark** [comment]
That worked, thanks!
