### ISSUE TITLE
[Feature Request] Thunderbird Conversations Extension Needs Your Dark Mode !!!

### ISSUE THREAD

**Issue by sileeb** [darkreader/darkreader#8931]
Hi there... Theres an extension called Thunderbird Conversations for Thunderbird which desperately needs dark mode. Please adapt DR to Thunderbird Conversations which badly needs dark mode. Thank you !!!!

**Comment by sileeb** [comment]
Hello? Would you please provide feedback to the possibility of applying dark mode to Thunderbird Conversations in the near future?

**Comment by Gusted** [comment]
Use the provided template.
