### ISSUE TITLE
[Feature Request] Replace with title

### ISSUE THREAD

**Issue by ashuvssut** [darkreader/darkreader#8943]
# Feature Request

## Is this feature request related to a problem?

I observed that we use Dynamic theme generation by default

but when visiting any google website like Google Cloud Platform Console, Google firebase docs, dynamic theme fails there. It generates a a wierd dark theme.

But if we switch from "Dynamic" to "Filter+" theme generation, "Filter+" handles those theme generation well (on those google sites).

But "Filter+" only genrates good theme ONLY for google websites.

**It would be great if we could SET theme generation modes of particular websites.** 

This would fix most of the other "Broken website" issues as well.

**Comment by Gusted** [comment]
Hi @ashuvssut

Please test out the new UI:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Click on the `Theme for all websites`, in which a dropdown is shown, from here on you can make a website-specific configuration.
