### ISSUE TITLE
True dark mode

### ISSUE THREAD

**Issue by mirabilos** [darkreader/darkreader#8946]
There are settings for brightness and contrast, analogous to those CRT monitors we had in the 1980s and 1990s, but I’m looking for a true dark mode, in which the background colour is simply as fully black as LCD technology allows, that is, `#000000`. Please add an option to achieve that with this thing. Thanks!

**Comment by Gusted** [comment]
Use the provided template next time.

https://github.com/darkreader/darkreader/issues/650#issuecomment-733599758

**Comment by mirabilos** [comment]
What provided template? How was this completed?

**Comment by Gusted** [comment]
> What provided template?

https://github.com/darkreader/darkreader/issues/new/choose -> If you choose one of the options you will be presented by a template that you can fill out. Issues without a template aren't allowed in this issue tracker.



> How was this completed?

Github being stupid by requiring more buttons to close a issue require the maintainer to do more shit(now closed as not planned, because it's already implemented).

**Comment by mirabilos** [comment]
Gusted dixit:

>> What provided template?
>
>https://github.com/darkreader/darkreader/issues/new/choose -> If you
>choose one of the options you will be presented by a template that you
>can fill out. Issues without a template aren't allowed in this issue
>tracker.

Interesting… I know about this from other projects but was not presented
the choice here.

>> How was this completed?
>
>Github being stupid by requiring more buttons to close a issue require
>the maintainer to do more shit(now closed as not planned, because it's
>already implemented).

Eh, how then?

**Comment by Gusted** [comment]
> #650 (comment)

**Comment by mirabilos** [comment]
That seems to be a feature request? I cannot see how to do this from there.

**Comment by Gusted** [comment]
It's already implemention, see https://github.com/darkreader/darkreader/issues/650#issuecomment-733599758
