### ISSUE TITLE
[Bug] Inconsistency in Dark Reader displaying website when using different OS Themes.

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8948]
# Bug Report

## Website Address
https://music.apple.com/us/browse

## Bug Description
Inconsistency in Dark Reader displaying website when using different OS Themes.

## Steps To Reproduce
Visit the website with Dark Reader enabled with OS Theme set to Light / Dark.
Notice the inconsistency between screenshots 2 & 3. (See examples pointed out in screenshot 3 versus how they appear in screenshot 2.)

## Expected Behavior
Dark Reader to work consistently on website regardless of OS Theme or any other variable.

## Actual Behavior
Dark Reader does not work consistently on website regardless of OS Theme.

## Screenshots

Screenshot 1 (Normal Website):

![music apple com-normal](https://user-images.githubusercontent.com/95879668/170159526-5b24badd-306f-4305-a871-74809b046b41.png)

Screenshot 2 (Website w/DR Enabled & OS Light Theme):

![music apple com-os-light-theme-DR-enabled](https://user-images.githubusercontent.com/95879668/170159542-e367667f-5b5c-4495-bd7f-7e46cb3c9f21.png)

Screenshot 3 (Website w/DR Enabled & OS Dark Theme):

![music apple com-os-dark-theme-DR-enabled](https://user-images.githubusercontent.com/95879668/170161646-defeaae1-19c3-4aef-a016-06068d99ac6d.png)

## System Information

- OS: Arch Linux KDE
- Browser: Firefox Nightly 102
- Dark Reader Version: 4.9.50

## Additional Context
When testing the OS Light Theme, the theme was set and then the computer was rebooted. After reboot, testing was performed on a new browser profile.
When testing the OS Dark Theme, the theme was set and then the computer was rebooted again. After reboot, testing was performed again on a different new browser profile.

In order to make the website display correctly in the screenshot 3 scenario, I had to either disable DR for the current site or remove the fixes provided in the dynamic-theme-fixes file by using the DR Dev Tools.

**Comment by Gusted** [comment]
This is nothing new, this is just how sites behaves when it detects a dark theme, it show adjusted icons due to that. Please use broken website next time for this.
