### ISSUE TITLE
[Feature Request] Set day time to switch between light and dark

### ISSUE THREAD

**Issue by imloualvaro** [darkreader/darkreader#8952]
# Feature Request
Would be great to see a feature to set day time to automatically switch between light and dark theme. Some day I forgot do switch back to light. Thats good for those who care about body response to low light and other effects
## Is this feature request related to a problem?

no

**Comment by Gusted** [comment]
Hi @imloualvaro

Use the new design:


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

If you go to Settings -> Automation you can specify this behavior.
