### ISSUE TITLE
[Feature Request] Desktop browser 'Detect dark theme' like iOS extension.

### ISSUE THREAD

**Issue by apotenza92** [darkreader/darkreader#8959]
# Feature Request

iOS version of Dark Reader has 'Detect dark theme' to use a website's native dark theme if it's available. Will this feature be implemented on the desktop web browser extension?

## Is this feature request related to a problem?
No

**Comment by osfanbuff63** [comment]
This is implemented in the v5 preview, see [here](https://darkreader.org/blog/detect-dark-theme/) for more details!
