### ISSUE TITLE
SVG version of DarkReader's icon/logo?

### ISSUE THREAD

**Issue by Yaco** [darkreader/darkreader#897]
Hi! could you include the SVG file of the logo/icon? Would be great for the desktop managers that rely in scalable icons and also to be able to create some fancy fan-made t-shirts :) 

Thx!

**Comment by Gusted** [comment]
[icons.zip](https://github.com/darkreader/darkreader/files/4486628/icons.zip)
You could use a png to svg converter if that works. So far I know their isn't a svg version avaible

**Comment by Yaco** [comment]
Thanks @Gusted !

I assume this icon was created in some vector drawing software? maybe Illustrator or Corel Draw? In that case, could you also send me the vector editable file? Thx

**Comment by Gusted** [comment]
In that case you have the best chance to contact but he is probs busy so I should ask him and update you whe he reacts

**Comment by Yaco** [comment]
@Gusted : contact who? Sorry, didn't get it.

**Comment by Gusted** [comment]
@alexanderby but I've already sended a DM to him to check this issues as he's the only one that will have those files. So if he wakes up he will take a look for it.

**Comment by alexanderby** [comment]
Hi, have a look here https://github.com/darkreader/darkreader/tree/master/src/ui/assets/images

Also here is a repository with vector materials in INK format https://github.com/darkreader/darkreader-design/

You need Inker editor to open them and convert to SVG http://inker.co/
