### ISSUE TITLE
[Broken Website] mail.protonmail.com changed to mail.proton.me - URL Update & Site Fixes Might Need Reworking

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8971]
# Broken Website Report

## Website Address
https://mail.proton.me

## Problematic Observation
I was looking in the dynamic theme fixes file and saw that this old URL mail.protonmail.com was still in there. I didn't catch this one for the initial report (#8957). This URL has been changed to mail.proton.me and likewise I believe the fixes need to be reworked as well.

================================

mail.protonmail.com

CSS
.customCheckbox-input:not(:checked) + .customCheckbox-mask {
    background: none !important;
}
select.field {
    background: var(--darkreader-neutral-background) !important;
    color: var(--darkreader-neutral-text) !important;
}
.label-stack-item {
    background: var(--background) !important;
}
.items-column-list-inner {
    border: solid var(--bordercolor-input) !important;
}
.main {
    border-color: ${darkgray} !important;
}

================================

## System Information

- OS: Arch Linux KDE
- Browser: Firefox Nightly 102
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment]
I don't see any actionable in here, can you point to something that's currently broken? As far as a I observed no fixes are required *so far*.

**Comment by Gusted** [comment]
Which URL?
