### ISSUE TITLE
Baidu.com The background will turn white when I turn to another page

### ISSUE THREAD

**Issue by Q-ian** [darkreader/darkreader#898]
Browser: Chrome 70
Dark Reader Version: 4.7.1

Baidu.com
The result page will turn white when I turn to another page. 
The same problem occurs when changing search results.

![image](https://user-images.githubusercontent.com/30255324/49682234-02bd8200-faec-11e8-91de-9c2e7dc2e2f3.png)
![image](https://user-images.githubusercontent.com/30255324/49682238-149f2500-faec-11e8-9310-4ed0a6d333d3.png)

**Comment by wocalage** [comment]
same problem with you ,seem like a new bug

**Comment by jackaroo0** [comment]
The same with you,I hope can solve it quick

**Comment by alexanderby** [comment]
I solved this bug some time ago, but for some reason after latest optimizations it reproduces again. Baidu removes inserted style sheets, when you type a search query. In a halloween update I added a fix, that restored this, unfortunately it introduced incompatibility with some extensions, making them compete and use 100% CPU. I will have to determine why it stopped working.
