### ISSUE TITLE
[Broken Website] auto detection fails and shows wrong information

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#8991]
# Broken Website Report

## Website Address

https://fishshell.com/docs/current/cmds/test.html

## Steps To Reproduce

![image](https://user-images.githubusercontent.com/6344099/171448339-a986da0c-dcb3-4c06-bd5e-abb54ee81ad8.png)
****

## Screenshots

![Screenshot_333](https://user-images.githubusercontent.com/6344099/171448528-7629da79-8238-42dd-9012-97abe8d135bd.png)

## System Information

- OS:  Linux
- Browser:  FF 100
- Dark Reader Version:  current

**Comment by Gusted** [comment]
Moving to #9016
