### ISSUE TITLE
[Broken Website] Google Analytics V4

### ISSUE THREAD

**Issue by stullesha** [darkreader/darkreader#8995]
# Broken Website Report

## Website Address

https://analytics.google.com/analytics/web/

## Steps To Reproduce

- Create and setup a Google Analytics 4 property
- Use the tracking code in a test site and record a few visits
- Browse through various sections of the reporting section (real time, etc.)

## Problematic Observation

Some of the cards appear with white background and white text in dark mode.

## Screenshots

https://ibb.co/2gYzyVQ

## System Information

- OS: Windows 10
- Browser: Brave [Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)]
- Dark Reader Version: 4.9.51

**Comment by stullesha** [comment]
@Gusted is there a way to add custom code to the CSS of the extension? This solves what I want
.```
ga-viz-table .ga-viz-table-default-background {
    fill: rgb(24, 26, 27);
}
```

**Comment by stullesha** [comment]
```
================================

analytics.google.com

CSS
.ga-viz-table .ga-viz-table-default-background {
    fill: rgb(24, 26, 27);
}
.ga-viz-table .ga-viz-table-button-disabled,
.ga-viz-table .ga-viz-table-pagination-text {
    fill: rgba(231, 230, 228, 0.87);
}
.ga-explorer-report.ga-gm2 .nodata rect,
.ga-dashboard-report.ga-gm2 .nodata rect {
 fill: rgb(24, 26, 27) !important;
}

```
That works

**Comment by stullesha** [comment]
@Gusted why was this closed?

**Comment by Gusted** [comment]
> That works

You mentioned that you found a fix.

**Comment by stullesha** [comment]
I thought you would implement it by default? The changes don't stick unless I reload the page!

**Comment by Gusted** [comment]
> I thought you would implement it by default?

I never said that, I normally don't include fixes that I cannot test myself.



> he changes don't stick unless I reload the page!

That only should happen for the first time, after that the changes should be somewhat permanent injected onto the page.

**Comment by stullesha** [comment]
Then you shouldn't close the issue if you haven't tested it no? Just leave it open and point user's solution as a workaround until you do.

**Comment by Gusted** [comment]
> Then you shouldn't close the issue if you haven't tested it no? Just leave it open and point user's solution as a workaround until you do.

What? You said your mentioned fix works as a workaround. I have no reason to believe that you post a workaround that doesn't work. There's no actionable issue anymore going on, as I cannot test this bug for myself and the user posted their solution which in my eyes seems to be a correct workaround.

**Comment by stullesha** [comment]
> as I cannot test this bug for myself

So you had no intention of testing it? I am really puzzled by your attitude despite this extension being a life saver. Testing this is really simple unless you don't use google analytics.

**Comment by Gusted** [comment]
> So you had no intention of testing it?

I'm simply not able to test it, that's not the same of not having the intention of testing it. 



> I am really puzzled by your attitude despite this extension being a life saver.

🤷🏽 from my POV I state that I'm not able to test it and that you mentioned a workaround(which you mentioned that it works for you) so I closed it as fixed.

 

> Testing this is really simple unless you don't use google analytics.

I don't _really_ have a usable Google account to test this on. It's not as simple to go to the site and register a analytics account.

**Comment by stullesha** [comment]
Can't fix, won't fix. That is all I'm hearing from you. Never mind. I will keep adding this CSS everytime I roll out a new machine. Cheers!

**Comment by bapps2** [comment]
I came across this solution after wondering why Dark Reader was not working for GA4. @Gusted I can confirm the solution shared above works, but is reset every time this extension is updated which i an inconvenience.
