### ISSUE TITLE
Dynamic mode seems take effect slower time than Filter and Filter+

### ISSUE THREAD

**Issue by hohoaisan** [darkreader/darkreader#900]
Compared with "Toggle current website hotkey" and "Reloading website while Dark Reader's mode is on", Dynamic mode always shows up with broken black-white color and borders then shows as normal , while Filter ad Filter+ don't. (sorry my English is not good to explain)
![image](https://user-images.githubusercontent.com/26185060/49695084-f3ac0200-fbc7-11e8-810b-12d073080bd3.png) 
![image](https://user-images.githubusercontent.com/26185060/49695090-07576880-fbc8-11e8-937e-d824eee8b001.png)

**Comment by alexanderby** [comment]
I think video could help to describe the issue. The first screenshot looks bad, never saw Facebook like this. The second one looks like the fallback style is applied for preventing white flash during page loading. For some reason it could stay, maybe some error during CSS loading, maybe you see some error in Console?

**Comment by hohoaisan** [comment]
This broken rendering of Dark reader takes 1-2 seconds so i can screenshot it, then it shows as usual (light theme > 1st screen shot > 2nd screen shot > dark theme ), while Filter and Filter+ there is no 'broken rendering' like this, faster than Dynamic mode (i think)

**Comment by alexanderby** [comment]
Maybe with latest update this will be improved for you. Do you have a slow connection or slow PC?

**Comment by hohoaisan** [comment]
Yes it was improved, but there is still 2 seconds freezing the web (tried on Facebook) when i switch to Dark mode or while switching to Dynamic mode

**Comment by Gusted** [comment]
#2550
