### ISSUE TITLE
[Bug] Dark Reader fails to recognize some mdBook websites as dark

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#9003]
# Bug Report

## Website Address
https://slightknack.github.io/rust-abi-wiki/intro/intro.html

## Bug Description
Dark Reader fails to recognize some mdBook websites as dark

## Steps To Reproduce
1. visit the linked website

## Expected Behavior
recognized as dark

## Actual Behavior
not recognized as dark

## Screenshots
Here is the website normally, AKA dark:

![image](https://user-images.githubusercontent.com/4723091/171931511-a1c80457-aed6-40b7-836d-59d88bbec83b.png)

Here is Dark Reader's disgusting rendition (eww what are those borders):

![image](https://user-images.githubusercontent.com/4723091/171931580-ccab689c-84f6-48e4-833a-72b41d8082b8.png)

No dark theme detected on page:

![image](https://user-images.githubusercontent.com/4723091/171932519-ab8ce980-1b0e-43b5-9719-a4cdedb386f1.png)

## System Information

- OS: Windows 10 Home 2004 build 19041.572 (64-bit)
- Browser: Firefox Developer Edition 101.0b9 (64-bit)
- Dark Reader Version: 4.9.51

## Additional Context
I still don't appreciate having to fluff up and over-structure my issue when it could be explained in just 24 words and two screenshots.

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016



> I still don't appreciate having to fluff up and over-structure my issue when it could be explained in just 24 words and two screenshots.

Please blame those that cannot properly organize a issue and give you zero actionable data (which just becomes annoying over time). Having a template helps with that and actually let people report issues in a actionable way.
