### ISSUE TITLE
[Broken Website] gimp.org False Positive Dark Theme Detection

### ISSUE THREAD

**Issue by wxMichael** [darkreader/darkreader#9009]
# Broken Website Report

## Website Address
https://www.gimp.org/downloads/devel/

## Steps To Reproduce
- Enable New Design Preview and Detect Dark Theme.
- Go to the above address

## Problematic Observation
A majority of the page background is pure white.

## Screenshots
![uoEqv8rggb](https://user-images.githubusercontent.com/10516759/171978604-0419d7a0-326b-4f71-b040-f0a45530c116.png)

## System Information
- OS: Windows 11
- Browser: Firefox 101.0
- Dark Reader Version: 4.9.51

## Additional Context
The header and footer are both a dark green, which might be causing a false positive.

**Comment by Gusted** [comment]
Moved to #9016
