### ISSUE TITLE
FAQ: How to stop firefox reverting to the light theme when darkreader is disabled

### ISSUE THREAD

**Issue by ah-** [darkreader/darkreader#901]
Hi,

Thanks for building this extension, it's working great!

I'm not sure where the best place to put this is, but in absence of a FAQ I figured the best way was just to open an issue, feel free to close immediately.

I always use the dark firefox theme, but sometimes also turn on darkreader in the evening. By default darkreader changes the firefox theme back to light when you disable the extension. This is a bit annoying.

If you don't want that, just go to to the darkreader settings, click on more and change "change the browser theme" to Default. That's it, now your Firefox stays in dark mode even when you disable darkreader.

**Comment by alexanderby** [comment]
There is a [FAQ}(https://darkreader.org/help/en/#faq). What you described is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1415267).

**Comment by alexanderby** [comment]
Maybe I should add known issues section for browser problems.
