### ISSUE TITLE
[Broken Website] att.com

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#9025]
# Broken Website Report

## Website Address
https://www.att.com/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the hamburger menu button in the screenshot needs fixing.
Notice the links in the screenshot need fixing.
Notice the icons in the screenshot need fixing.
Notice the white bar at top in the screenshot needs fixing.

## Problematic Observation
Hamburger Menu Button
Links
Icons
White Bar At Top

## Screenshots
![att](https://user-images.githubusercontent.com/95879668/172075217-374db4f2-4179-4615-8ec1-2a7307dd2dd9.png)

## System Information

- OS: Windows 10
- Browser: Firefox Nightly 103
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment]
Note for later: Apparently constructed stylesheets are "broken" on this site.

**Comment by microdockman** [comment]
Add a new website

https://www.bilibili.com/bangumi/play/ep327584?spm_id_from=333.337.0.0

![Capture](https://user-images.githubusercontent.com/31898637/172879384-c020bb3c-bec1-43eb-9bce-f5e17060d01c.PNG)

This error will appear on the TV drama webpage
