### ISSUE TITLE
Some issue on baidu.com

### ISSUE THREAD

**Issue by qq994865664** [darkreader/darkreader#903]
have a issue on www.baidu.com, hope to fix this bug. thanks.

**Comment by alexanderby** [comment]
Duplicate of #898

**Comment by Gusted** [comment]
Closed as it a duplicate and main issue has been fixed with https://github.com/darkreader/darkreader/commit/9b24e3d0c4e1d4eb1c7cf94c5a149fab3afb5aa4.
