### ISSUE TITLE
[Broken Website] Dark mode at Synology DSM dashboard removes the wallpaper

### ISSUE THREAD

**Issue by nils-trubkin** [darkreader/darkreader#9065]
# Broken Website Report

## Website Address
Local Synology NAS running DSM 7.1

## Steps To Reproduce
Enable dark mode
Lon into the dashboard of Synology DSM

## Problematic Observation
The dashboard wallpaper is removed and replaced with black solid color instead

## Screenshots
![image](https://user-images.githubusercontent.com/32000568/173197010-5738ddd7-f477-4b37-85a0-fb3d28c882a3.png)

## System Information
OS: Windows 11
Browser: Brave [Version 1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)]
Dark Reader Version: 4.9.51
Synology DSM: 7.1-42661 Update 2 

## Additional Context
The dark reader only works (at all) if the dashboard is reached through the local domain name.
It does not work if the dashboard is reached though the local IP address.

**Comment by Gusted** [comment]
Are there any errors in the console?

**Comment by nils-trubkin** [comment]
> Are there any errors in the console?

Yes, quite many if the dark mode is on.
![image](https://user-images.githubusercontent.com/32000568/173206506-80007166-9cea-4ea1-881c-45c4f8417f42.png)

**Comment by nils-trubkin** [comment]
Yes, quite many if the dark mode is on.
![image](https://user-images.githubusercontent.com/32000568/173206518-5cb819f5-d004-4ccb-bd15-d0660842d8ac.png)

**Comment by Gusted** [comment]
Is it trying to use https on a ip address?

**Comment by nils-trubkin** [comment]
> Is it trying to use https on a ip address?

I'm not sure I understand the question, but will try to answer. Technically, it does use IP. All URLs resolve to an IP address.
In this case I am using a local domain name. I could use https on the IP if I wanted to, it's working fine both ways.

What does not work is the Dark reader extension when you connect to IP addresses (for some reason). Therefore I connect to my devices using a hostname. When I connect it via hostname it's fine. Just this desktop on this particular device (dashboard/website) that's missing.

**Comment by Gusted** [comment]
> I'm not sure I understand the question, but will try to answer. Technically, it does use IP. All URLs resolve to an IP address.
> In this case I am using a local domain name. I could use https on the IP if I wanted to, it's working fine both ways.

I meant to ask if the censored part is a ip address or a (local) domain, but if it's working fine on https then it's another issue. If you open those url's in the browser do they actually resolve to a image?

**Comment by nils-trubkin** [comment]
> > I'm not sure I understand the question, but will try to answer. Technically, it does use IP. All URLs resolve to an IP address.
> > In this case I am using a local domain name. I could use https on the IP if I wanted to, it's working fine both ways.
> 
> I meant to ask if the censored part is a ip address or a (local) domain, but if it's working fine on https then it's another issue. If you open those url's in the browser do they actually resolve to a image?

It's a local domain, something like `https://device:1234/`
The error messages do not come up if the dark mode is off, the page loads fine.
As soon as dark mode is enabled (Alt+Shift+D), all the errors pop up one by one (in quick succession).
The URLS are not reachable in either dark mode off or on mode.

![image](https://user-images.githubusercontent.com/32000568/173206914-49b26ce1-bb27-498e-baf1-e719d0314b96.png)

**Comment by Gusted** [comment]
Seems like somehow relative parsing might be wrong. Could you check the "correct" link(loading from the site itself) and a "incorrect" link(loaded from Dark Reader) and see if there's any difference? Otherwise there's no actionable issue going on.

**Comment by nils-trubkin** [comment]
> Seems like somehow relative parsing might be wrong. Could you check the "correct" link(loading from the site itself) and a "incorrect" link(loaded from Dark Reader) and see if there's any difference? Otherwise there's no actionable issue going on.

Could you please explain more detailed? I think that I've already tried what you're asking.
> The URLS are not reachable in either dark mode off or on mode.

**Comment by Gusted** [comment]
> Could you please explain more detailed? I think that I've already tried what you're asking.

What I mean is that these URL don't somehow get crafted by Dark Reader, they must be a valid image somwhere(but we're using it wrong). However this only happens when visiting on the local domain, so it means that when using the IP dark reader is somehow able to figure the correct URL. Now what I am asking, so I can investigate it, if you happen to know one of these URL's and see how they differ. So let's say:

On the IP dark reader makes the request:
http://192.168.0.1/img/lol.png 
While on the domain name it makes the request:
http://synology.local/img/css/lol.png

In which case Dark Reader is incorrectly adding the `/css` part into the request. Now, do you know the difference between the request at the ip and domain name?

**Comment by nils-trubkin** [comment]
> However this only happens when visiting on the local domain

Yes, but I think you misunderstand me or I'm not clear enough.

When visiting the IP address https://192.168.0.1/ thedarkreader never works, **at all**. White mode. It does not do anything, it's not enabled despite being enabled in the toolbar.

Now, when visiting https://synology/ it does work, but the wallpaper is broken.

How would you like me to check the request for the wallpaper specifically? I have no idea which request it is and it does not seem to be among the errors in the post above.

**Comment by nils-trubkin** [comment]
> Could you elaborate a bit more on this?
I'm not sure what you'd like me to add.
Darkreader has never ever in my experience worked with local IP addresses.
It does not matter if it's router dashboard, NAD dashboard or raspberry webserver.
It has never ever worked for any local IP address across multiple devices and installations.
It's enabled in the bar but not doing anything at all.

**Comment by Gusted** [comment]
> Either way, the wallpaper is not showing, it's just black when the Darkreader is enabled. IP or hostname, it's same result.

Yup so that's the more trival part of this issue. So I checked the issue with synology's demo and observed that it's possible to fix this with a workaround. By adding 
```css
body {
    background-color: transparent !important;
}
```
to either the dark reader's dev tools or via a extension like Stylus. It's kind of hard to upstream this fix as there's no reliable way to add fixes for local sites like these.

**Comment by nils-trubkin** [comment]
Yes, adding that entry, preceded by hostname and 'CSS' did fix the issue. Amazing.
I totally understand that it's hard to upstream it, since names are arbitrary. I'm not familiar with the possibilities that you have to identify websites to give any specific advice. Thinking mostly about maybe some headers returned or such, that would contain unique identifiers of the Synology generated website.

Thank you very much for your help, I really appreciate it. The Darkreader extension is very very good and I use it a lot, I'll consider donating some to the project, since I really like it.

This workaround is really good, and might be nice to add it somewhere either in readme or wiki page or something like that so that others can find it, perhaps. You may close the issue is you consider it solved, the workaround is fine by me, although not a _real_ solution it's very simple workaround so I'm happy with it.

```
myhostname

CSS
body {
    background-color: transparent !important;
}
```

**Comment by RyderCragie** [comment]
Background wallpaper disappears for me too.
![Screenshot 2024-05-15 at 15 05 44](https://github.com/darkreader/darkreader/assets/69316364/e439c9a2-8b95-4335-a06e-21da54f60e7f)

**Comment by nils-trubkin** [comment]
> Background wallpaper disappears for me too. ![Screenshot 2024-05-15 at 15 05 44](https://private-user-images.githubusercontent.com/69316364/330836886-e439c9a2-8b95-4335-a06e-21da54f60e7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTEzNzEsIm5iZiI6MTcxNjMxMTA3MSwicGF0aCI6Ii82OTMxNjM2NC8zMzA4MzY4ODYtZTQzOWM5YTItOGI5NS00MzM1LWEwNmUtMjFkYTU0ZjYwZTdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYmE4NWQ4NmFmZTdlOWM1N2E1ZjkyNjE0ZTYwYTRjYzJhNGU5MjM3ZTI0MDQ4M2ViYzAzMzVkNzBjYWE0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0_tZkEu_Ksutj2FrMhQU9ZbgscoZnmd9Xotm0kNMYk)

Did you try the fix above?

**Comment by eduarcor** [comment]
> myhostname
> 
> CSS
> body {
>     background-color: transparent !important;
> }

This fix does work (have to replace myhostname with 192.168.1.12 in my case), although is not easy to do for everyone. I am sure there should be a solution finding ways to identify Synology inside of the website (I see it in the description for example), and use it internally in the code when it applies the dark mode.
The previous solution works, but is just a "patch". This issue shouldn't be closed as it is not fixed.
Please fix it properly to make it perfect. The app is just amazing, except this little glitch. Thanks!
