### ISSUE TITLE
[Bug] Load page as "blank".

### ISSUE THREAD

**Issue by orloko** [darkreader/darkreader#9069]
# Bug Report

## Bug Description
New pages open as "blank", need to refresh or disable/re-enable the extension to it show it properly.
As well as going back after some time on an open tab, it show the same way, sometimes it loads, sometimes it doesn't, leaving the refresh or disable/re enable the extension as the only work around.
When it happens, for example with Twitch, it just happened with a tab that was working on while I was writing this report, when I went back there, it was "blank" but still possible to interact with the page, press Play(space) to continue the Live(or Pause) it plays/pause but doesn't leave the "blank" state 
When disabling the extension it instantly shows the page.

## Steps To Reproduce
Not sure what is broken it, I only have to open a few pages, noticing it more often in Youtube/Twitch.

## Expected Behavior
I expected the page to load properly without needing to refresh it, or disable/re enable the extension.

## Actual Behavior
When going through the tabs I had open it show as "blank" like it didn't load it, but if inspected with the Dev Tools on Chrome you can see it is loaded behind the DarkRead extesion. https://i.imgur.com/dpMoHiW

## Screenshots
https://i.imgur.com/79m1rji.png

## System Information
- OS: Versão Win 10 Pro	10.0.19043 Build 19043
- Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
- Dark Reader Version: 4.9.51

## Additional Context
I notice this problem for a few weeks already, had uninstalled and reinstalled the Darkread extension prior to this report, didn't solve it

**Comment by Gusted** [comment]
Hi @orloko,

Do you have any other extensions enabled? 
Does it only happen on tab load or also after a period of time?

**Comment by orloko** [comment]
> Hi @orloko,
> 
> Do you have any other extensions enabled? Does it only happen on tab load or also after a period of time?

Yes, I also have others extensions load up,
and like I said on the report it self, it happens both on page load as well after a period of time (when going back at that open tab)

Besides Dark Reader, those are the extensions that I have enable right now.

- 7TV
- BetterTTV
- uBlock Origin
- Twitch Adblock
- Google Docs Offline
- Steam Inventory Helper
- Return YouTube Dislike
- Reddit Enhancement Suite
- Kaspersky Password Manager
- Windowed - floating Youtube/every website
- Automatic Twitch: Drops, Moments and Points

**Comment by Gusted** [comment]
> Yes, I also have others extensions load up, and like I said on the report it self, it happens both on page load as well after a period of time (when going back at that open tab)
> 
> Besides Dark Reader, those are the extensions that I have enable right now.

Quite a lot of extensions that could cause a conflict. Could you try to reproduce this on a new profile without those extensions enabled?

**Comment by orloko** [comment]
New profile, thought it was not going to happen, but than... it did.
Didn't happen with old tabs that was open(yet) this one I scroll-click to open the link in a new tab, when I get there it was like that.
https://i.imgur.com/2Eqh5Yf

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/174499780-6511ceab-f011-4440-a7ca-6a7c4aad6264.png)

Aha this seems interesting... It seems like that dark reader is still loading the "fallback" theme. Could you please confirm this by opening the dev tools(ctrl + shift + i) and then find(via ctrl + f) the `darkreader--fallback` element. When you find this element, do you see if this element has any content?

**Comment by Gusted** [comment]
Then it means that dark reader couldn't finish analyzing the site. Could you please point to the exact extension of `Twitch Adblock` It's likely they are doing some proxying of some sort to "bypass" twitch's protection that likely also causes issues with Dark Reader.

**Comment by Gusted** [comment]
Yeah indeed seems like it's preventing from events(that Dark Reader uses) from triggering: https://github.com/cleanlock/VideoAdBlockForTwitch/blob/master/firefox/content.js#L53 so the only way to fix this is by enabling:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    Now go to see all options -> Fonts & more -> Immediate modify.
    
This tells Dark Reader to not care if a tab is hidden or anything and just go modify it(which should resolve bug in this case).
