### ISSUE TITLE
[Broken Website] shopping.google.com

### ISSUE THREAD

**Issue by sunflowerskater** [darkreader/darkreader#9073]
# Broken Website Report

## Website Address
[shopping.google.com](https://shopping.google.com)

## Steps To Reproduce

1. Go to [shopping.google.com](https://shopping.google.com);
2. Search for an item;
3. Activate the Dynamic filter.

Obs.: make sure that the Google's built-in dark mode is enabled in Google search settings.

## Problematic Observation

The background color of the page is grey and the images colors are inverted.

## Screenshots

![Screenshot from 2022-06-13 07-01-26](https://user-images.githubusercontent.com/107403205/173336559-86d5b6d5-2fad-4430-a867-e13f8959ba95.png)

## System Information

- OS:  Fedora 36
- Browser:  Firefox 101.0
- Dark Reader Version:  4.9.51

## Additional Context
I noticed that this problem can be fixed by setting `filter: none` to the `body` selector. When Dark Reader gets activated, the `filter: invert(1) hue-rotate(180deg)` doesn't get altered to `none`:
![Screenshot from 2022-06-13 07-04-57](https://user-images.githubusercontent.com/107403205/173334497-506b7adf-ff54-4885-b900-21058644a129.png)

Dark Reader already adds `filter: none` to several elements, but not for `body`:
![Screenshot from 2022-06-13 07-03-19](https://user-images.githubusercontent.com/107403205/173334525-046fe8f0-05f7-40c0-99f1-8c912c06324c.png)

https://user-images.githubusercontent.com/107403205/173335408-687ecdc6-90b3-42e3-bbf6-a89c03879d7f.mp4

This problem [existed before](https://github.com/darkreader/darkreader/issues/7512), but now it's worse due to the images colors getting inverted.

**Comment by Right2TheV0id** [comment]
Same here:

* OS: Windows 10 21H2
* Browser: Edge 102.0.1245.41 (64 bits)
* Dark Reader Version: 4.9.51

*Thanks for the filter: none tip!*
