### ISSUE TITLE
[Broken Website] ikea.ee

### ISSUE THREAD

**Issue by saltedcoffii** [darkreader/darkreader#9080]
# Broken Website Report

## Website Address
https://www.ikea.ee

## Steps To Reproduce

- Switch language to English (if desired, bug appears either way)
- Search for anything in the search bar, I searched "bed"
- Observe bug

## Problematic Observation

Example URL: https://www.ikea.ee/en/rooms/bedroom/beds-and-sofa-beds/bed-frames?size[]=140x200%20cm&order=RECOMMENDED

Dark Reader does not properly darken some page elements

## Screenshots

![image](https://user-images.githubusercontent.com/55339220/173710523-3dffa0b4-4a4f-4195-9e0d-92d9f2a8e2a6.png)

## System Information
- OS: Arch Linux rolling
- Browser: Mozilla Firefox 101.0
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment]
#9148 was merged.
