### ISSUE TITLE
[Bug] Extension is stuck on "Loading Please Wait"

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [darkreader/darkreader#9088]
# Bug Report

Extension is stuck on "Loading Please Wait".

## Bug Description

Without changing any extensions, the Dark Reader menu now doesn't finish loading, and I can't change settings, however the websites I set to be "darkened", still are. If I disable and enable, or delete and reinstall the extension, the behavior is the same. 

## Steps To Reproduce
Click on the extension button, anytime.

## Expected Behavior
The menu opens instantly and I can change Dark Reader's settings, and the dark mode per page, etc.

## Actual Behavior

The menu never loads.

## Screenshots

![Screenshot](https://i.imgur.com/Y2JM6AR.png)
## System Information

- OS: Linux, KDE Neon 5.25
- Browser: Firefox 101.0.1 (64-bit)
- Dark Reader Version: 4.9.51

## Additional Context

I've seen closed issues about a bug similar to this, but the fixes provided are from Chrome, not Firefox.

**Comment by Gusted** [comment]
Hi @AuraHerreroRuiz!

Are there any errors in the console when you open `about:devtools-toolbox?id=addon%40darkreader.org&type=extension`?

**Comment by AuraHerreroRuiz** [comment]
No, there aren't any.
![1-06-1](https://user-images.githubusercontent.com/95187075/174407054-41e7079c-9dda-4e0a-b3e2-98f4270af9d1.png)

**Comment by Gusted** [comment]
Could you try to open the popup in a new tab and then see if there is any error?

Open the popup
Right click on the popup to view the context menu.
Click on view source, this will open a new tab.
Remove the `view-source:` prefix from the tab's url.

Does this have the same problem? If so, is there any error logged on this page?

**Comment by AuraHerreroRuiz** [comment]
It has the same problem, but now there's an error:
![error](https://user-images.githubusercontent.com/95187075/174461916-9a20a26f-2318-4f6b-ad7b-ea92f5101757.png)

**Comment by Gusted** [comment]
When you click on `moz-extension:4601:22` it should open the Debugger tab as well with the corresponding line, could you make a screenshot of this line?

**Comment by AuraHerreroRuiz** [comment]
...odd. I can't do that.
![Image showing the ibeam over "moz-extension:4601:22"](https://user-images.githubusercontent.com/95187075/174508412-cafb860e-b7fa-41ba-ad55-75885d1e4125.png)
As you can see, when I hover over `moz-extension:4601:22`, it shows the ibeam/text cursor, and if I click (tried CTRL/ALT/Shift keys just in case), all I do is select the text.

**Comment by Gusted** [comment]
Hmm interesting, do you happen to use a custom user-agent? `console.log(navigator.userAgent)`

**Comment by AuraHerreroRuiz** [comment]
Yes, it prints out my correct user agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0`

Although, 2 days ago, the extension magically started working again. I didn't change anything in my browser profile.

However, if I can help you further to find this bug, let me know. If that's not the case you can close the issue.

**Comment by Gusted** [comment]
> Although, 2 days ago, the extension magically started working again. I didn't change anything in my browser profile.
> 
> However, if I can help you further to find this bug, let me know. If that's not the case you can close the issue.

Happy to see it resolved! I really hadn't any clue of what could have happen here, so it was kind of a blind shot. Closing.
