### ISSUE TITLE
"Loading, please wait" is back...

### ISSUE THREAD

**Issue by MartyMacGyver** [darkreader/darkreader#909]
Things have been working great til the last day (I was away for a week before that). The same old problem I noticed in #700 is back. Not sure what part of the code is triggering it though.

Windows 10, Chrome 70.0.3538.110 (Official Build) (64-bit) [looks like it's about to update - will let you know if the problem goes away.]

Edit: After the update it's Chrome 71.0.3578.80 (Official Build) (64-bit) - may take a day to re-trigger it if it's like the last time.

**Comment by MartyMacGyver** [comment]
Well, so far it hasn't reappeared but if it does I'll let you know.

**Comment by Gusted** [comment]
Fixed.
