### ISSUE TITLE
[Broken Website] Dark mode messes things up on Proton sites

### ISSUE THREAD

**Issue by sepehr-brj** [darkreader/darkreader#9090]
# Broken Website Report

## Website Address
https://proton.me/
https://account.proton.me/
https://protonvpn.com/
https://account.protonvpn.com/

## Steps To Reproduce
- Please visit the Proton websites

## Problematic Observation

- Purple turns dark blue
- Part of the page remains white
- And logos need fixing

## Screenshots
![Screenshot_20220616-221905](https://user-images.githubusercontent.com/55192376/174138258-65cdd855-eea6-43be-bb16-48e67708d4a3.png)
![Screenshot_20220616-222526](https://user-images.githubusercontent.com/55192376/174138275-ff8e232a-472f-4187-a6c7-97377d25d72f.png)

## System Information

- OS: Android 11
- Browser: Firefox 101.2.0
- Dark Reader Version: 4.9.51

## Additional Context
This issue is almost solved by changing the mode to filter, but in the login process it inverts the captcha images.

**Comment by Gusted** [comment]
Hi, could you try [enabling the latest fixes](https://github.com/darkreader/darkreader#site-fixes)?

**Comment by sepehr-brj** [comment]
> Hi, could you try enabling the latest fixes

Hi, It didn't fix the problem
