### ISSUE TITLE
Can't seem to figure out how to use the developer tool

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#91]
Trying to add the "noinvert" tag to the headers and input text box of a forum, but I have no idea how.
```
<fieldset id="moderatorBar">...part to tag noinvert...</fieldset>
<header>...other part to tag noinvert...</header>
...
<p>...also other part to tag as noinvert...</p>
```

**Comment by alexanderby** [comment]
`invert` adds `filter: invert()...` CSS rule for specified selectors.
`noinvert` adds `filter: none` rule for specified selectors.
So, how it works:
1. When Dark mode is on, Dark Reader puts `filter: invert()` to <html>.
2. Now the whole page is inverted and also images or elements with background images are inverted,
3. We add `"invert": "img, #bg-img"` into config, and `img, #bg-image { filter: invert(); }` rule is created.
4. Now images are reverted (filter is applied twice to them), but suppose `#bg-image` contains other images inside it and `filter: invert()` will still be applied to them.
5. We add `"noinvert": "#bg-image *" into config and `#bg-image * { filter: none; }` is applied to content of already reverted element.

**Comment by J-e-r-e-m-i-a-h** [comment]
```
        {
            "url": "site.com",
            "invert": [
                "#header *, #fieldset id=moderatorBar *, #p *"
            ]
        },
```

My issue is probably that I don't know the language.

**Comment by alexanderby** [comment]
Suppose we have `<div id="john" class="human" title="hello"> <img/> </div>`
Then we can create the following CSS selectors: `#john`, `.human`, `[title='hello']` and for nested content we can do `#john img` or `#john *` to match all elements inside parent.

**Comment by J-e-r-e-m-i-a-h** [comment]
`"#header *, #fieldset, .moderatorBar, #p *"` like this?

**Comment by alexanderby** [comment]
I think you should get more familiar with CSS selectors https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

```html
<div id="john" class="human" title="hello">
    <img/>
</div>
```
- `div` and `img` are tag names, selector is `div` or `img`.
- `id="john"` is an unique element name, selector is `#john`.
- `class="human"` is a class name, selector is `.human`.
- `class="human doctor"` are class names, possible selectors are `.human`, `.doctor`, `.human.doctor`.
- If you want to match element inside another, then separate selectors with whitespace, like `div img`.
- `*` selector means "match everything".
- `[title='hello']` means "match elements whose attribute "title" has value "hello".

So, in your case, if you have `<header>` inverted, add `"invert": "header"`.

**Comment by J-e-r-e-m-i-a-h** [comment]
awesome I think I got the hang of it! it's sort of giving a haze to the text though, so I'd like a little bit more info about the noinvert part. thanks a ton for being so patient and spoonfeeding me :P 

![image](https://user-images.githubusercontent.com/31524381/30643764-0f752b40-9dc5-11e7-9335-d3ea5427ed07.png)

this is a little tricky. I can't select the classes below because it only inverts tiny parts of what im looking for, and I cant invert the whole xbOffCanvasContainer or else it inverts the page. i can't select moderator bar because it isn't a css selector. if i select pagewidth it inverts content through the page so im stuck :(

**Comment by alexanderby** [comment]
You can use Chrome Dev Tools for picking element.
Try `#moderatorBar` selector.

**Comment by J-e-r-e-m-i-a-h** [comment]
```
        {
            "url": "site.com",
            "invert": [
                "#moderatorBar, #header, .logoBlock, #logo, .nodeIcon, [title='Unread messages'], .footer, .extraFooter, .footerLegal"
            ]
        },
```

Looks great so far! Everything except reply text is inverted correctly.

![image](https://user-images.githubusercontent.com/31524381/30666358-e24e3c6c-9e08-11e7-8017-3796567816ba.png)

I have no idea what to tag it as

**Comment by alexanderby** [comment]
It lies inside iframe, you cannot invert iframe children, but only iframe itself.

**Comment by J-e-r-e-m-i-a-h** [comment]
![1](https://user-images.githubusercontent.com/31524381/30667513-91e5c9ee-9e0c-11e7-8a6e-276e2837fdfb.PNG)

![image](https://user-images.githubusercontent.com/31524381/30667537-b13bf872-9e0c-11e7-8fe0-d55d2c6b3e31.png)

it's almost as if the text is being double inverted

**Comment by alexanderby** [comment]
You can right-click on the text, click Inspect, in elements style panel click Computed (if it's not already displayed) and under "filter" rule see what selector sets up that rule.

**Comment by J-e-r-e-m-i-a-h** [comment]
![image](https://user-images.githubusercontent.com/31524381/30691907-3ca1ef68-9e7e-11e7-8376-05867029c270.png)

the styles tab? user agent stylesheet?

something with inheritance?

**Comment by alexanderby** [comment]
The element you selected is inside iframe. It is technically possible to modify iframe content only if domain name is the same as source page, but not implemented yet.

So, invert an iframe itself e.g. by using `.redactor_MessageEditor` selector (or not invert cause iframes are inverted by default).

**Comment by J-e-r-e-m-i-a-h** [comment]
Changes in Developer options aren't auto applying after chrome restart.

**Comment by alexanderby** [comment]
Submit them as said [here](https://github.com/alexanderby/darkreader#how-to-contribute)

**Comment by Gusted** [comment]
Deleted user
