### ISSUE TITLE
[Bug] Strange artefacts

### ISSUE THREAD

**Issue by palandovalex** [darkreader/darkreader#9102]
# Bug Report

## Website Address
https://christforum.net/topic16969.html

## Bug Description

Strange artifact, that appears when using darkreader

## Steps To Reproduce

- Go to https://christforum.net/topic16969.html
- Use darkreader, dynamic mode.

## Expected Behavior
Normal dark theme

## Actual Behavior

Strange artefacts

## Screenshots

![normal.png](https://user-images.githubusercontent.com/75374436/174432606-0b284071-3d08-4f43-9c81-d2d0e4f65c4c.png)
![dark.png](https://user-images.githubusercontent.com/75374436/174432635-15144f16-8ca0-4ed3-b526-35cf2943254a.png)

## System Information

- OS: Linux Mint 20.2 Uma
- Browser: 101.0.1 (64 бита)
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment]
Not possible to fix: they put cloudflare in front of their CSS, so we cannot fetch those:

![image](https://user-images.githubusercontent.com/25481501/174459469-4342e823-bfe7-49a3-bd2e-4969c52c6ae6.png)
