### ISSUE TITLE
Found Code to Make Dark Reader Themable & Unrestricted in Firefox

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#911]
With Dark Reader, restricted sites like addons.mozilla.org can't be themed with the restriction in about:config turned off in: 'privacy.resistFingerprinting.block_mozAddonManager'. For such sites to be themed please edit the file, 'background/index.js'. Then publish the addon on firefox's addon site.

Change the following in background/index.js from:
```
 function canInjectScript(url) {
        if (isFirefox()) {
            return (url
                && url.indexOf('about:') !== 0
                && url.indexOf('moz') !== 0
                && url.indexOf('view-source:') !== 0
                && url.indexOf('https://addons.mozilla.org') !== 0);
        }
        return (url
            && url.indexOf('chrome') !== 0
            && url.indexOf('https://chrome.google.com/webstore') !== 0);
    }
```

..and change it to:

```
   function canInjectScript(url) {
        if (isFirefox()) {
            return (url
                && url.indexOf('about:') !== 0
                && url.indexOf('moz') !== 0
                && url.indexOf('view-source:') !== 0);
        }
        return (url
            && url.indexOf('chrome') !== 0
            && url.indexOf('https://chrome.google.com/webstore') !== 0);
    }
```

**Comment by alexanderby** [comment]
I will have to add an option for it. Doing so by default will cause an error in console, and the add-on will not pass the review.

**Comment by koolx** [comment]
Hi alexanderby.. did you finally add the option to dark reader??

.

**Comment by Gusted** [comment]
#912 dup(not really but 912 has more history of this issue)
