### ISSUE TITLE
Option for running extension on restricted URLs

### ISSUE THREAD

**Issue by koolx** [darkreader/darkreader#912]
https://github.com/darkreader/darkreader/blob/b9408082d7bec6880119a2086982b11d648ddce0/src/background/utils/extension-api.ts#L15

With Dark Reader, restricted sites like addons.mozilla.org can't be themed with the restriction in about:config turned off in: 'privacy.resistFingerprinting.block_mozAddonManager'. For such sites to be themed please edit the file, 'background/index.js'. Then publish the addon on firefox's addon site.

Change the following in background/index.js from:
```
 function canInjectScript(url) {
        if (isFirefox()) {
            return (url
                && url.indexOf('about:') !== 0
                && url.indexOf('moz') !== 0
                && url.indexOf('view-source:') !== 0
                && url.indexOf('https://addons.mozilla.org') !== 0);
        }
        return (url
            && url.indexOf('chrome') !== 0
            && url.indexOf('https://chrome.google.com/webstore') !== 0);
    }
```

..and change it to:

```
   function canInjectScript(url) {
        if (isFirefox()) {
            return (url
                && url.indexOf('about:') !== 0
                && url.indexOf('moz') !== 0
                && url.indexOf('view-source:') !== 0);
        }
        return (url
            && url.indexOf('chrome') !== 0
            && url.indexOf('https://chrome.google.com/webstore') !== 0);
    }
```

**Comment by alexanderby** [comment]
I will have to do an option for this, as far as trying to run the extension on restricted URLs will cause errors, and once this was a reason for not passing a Mozilla review.

**Comment by koolx** [comment]
> 
> 
> I will have to do an option for this, as far as trying to run the extension on restricted URLs will cause errors, and once this was a reason for not passing a Mozilla review.

**Comment by koolx** [comment]
Hi Alex... I understand. But there are FF addons that mozilla allows to bypass this restriction. 'Dark Background & Light Text' and 'Astyle' are 2 addons that lets you theme restricted sites.

Why mozilla lets these addons exist in their store is something strange. But its there. Let me know what you think.

.

**Comment by Aidolii** [comment]
Chromium is able to bypass this restriction as well with the --extensions-on-chrome-urls flag. As a user of Cent Browser I would really appreciate this.

**Comment by User486375** [comment]
I don't understand why you actually disable your extension on `addons.mozilla.org` especially, as Firefox itself prevents extensions from running on that page either way. It's like protecting your extension from itself which is meaningless.

If you remove `addons.mozilla.org` from the about:config `extensions.webextensions.restrictedDomains` on Firefox then your extension should run. Just like how when you remove other restricted domains such as`accounts.firefox.com` the same about:config it runs fine there. So I don't see this as a "causing errors issue" if you don't have issues with all the other restricted domains currently.

As for Chrome they only actually restrict access to `chrome.google.com` alone unlike Firefox so you can actually run extensions such as uBlock Origin on the page see [here](https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist), it just won't be able to block anything coming from `chrome.google.com`, unlike in Firefox it just won't see anything. Though I'm guessing without enabling the `Extensions on chrome:// URLs` flag as mentioned above, it won't allow you to inject anything into the page, but I could be wrong.

Lastly, any ETA on this? Doesn't seem like a hard fix.

**Comment by PurpleCodingWizard** [comment]
@alexanderby 
Is there any chance this is going to be fixed? Fenix only supports dark reader so cannot use a different extension. It would be great if dark reader worked properly as expected and allowed user-overrides.

**Comment by Gusted** [comment]
Hi!

I've made a PR(#3426) that let's you disable the check if a site is protected(Extension wise, browser still can say it's protected).

Also 

> to be fixed?

Added as option*

>  Fenix only supports dark reader so cannot use a different extension.

I'm not quite sure if you can disable the protected pages in Fenix still.

>  It would be great if dark reader worked properly

Properly? I don't think your understanding the issue. Browsers have hard coded values for protected pages. We have implemented this system so it would:
1. Not inject in those pages 
2. Show in the UI that it's protected.

We are just adjusting to the browser and is working properly.

> and allowed user-overrides.

That's being added by #3426

Regards,
Gusted

**Comment by PurpleCodingWizard** [comment]
> I've made a PR(#3426) that let's you disable the check if a site is protected(Extension wise, browser still can say it's protected).
 Aweome, many thanks!


> I'm not quite sure if you can disable the protected pages in Fenix still.
You can at least in beta and nightly. Those versions support about:config. You can remove protected URLs like support.mozilla.org, addons.mozilla.org from the default list and addons work fine.
