### ISSUE TITLE
[Bug] Auto Dark Mode isn't working in Kiwi Browser 

### ISSUE THREAD

**Issue by MohamadBayz** [darkreader/darkreader#9127]
the Issue is on Android browser and easily you can reproduce it just by testing Auto Dark Mode and you will see that it isn't working and for this issue been reported before I don't think so it has been at least not that i know of.

# Bug Report

## Website Address
 every website pretty much you can try this for example
https://www.tunefind.com/movie/the-art-of-getting-by-2011

## Bug Description
 in the past the extension worked perfectly in the android also the auto dark mode was working according to the system dark mode, but recently with new updates and arriving new chromium version 100 there have been some issue one of them is that auto dark mode stopped working also I've checked if auto dark mode is also on in the browser setting and it was so don't know what's the matter.

## Expected Behavior

It should turn on automatically with the browser's dark mode
## Actual Behavior

It doesn't 
## System Information

- OS: Android 12.1
- Browser: Kiwi Browser (101.0.4951.40)
- Dark Reader Version: 4.9.51

**Comment by Gusted** [comment]
Reproduciable, but not Dark Reader's fault. Kiwi browser is not giving the right information. It tells dark reader that it's always in light-mode(even though when you have dark mode enabled in the OS).

**Comment by Gusted** [comment]
![Screenshot_20220624-230851](https://user-images.githubusercontent.com/25481501/175668734-8e57c798-7326-4161-871e-2d73d3983446.jpg)
