### ISSUE TITLE
[Broken Website] manjaro.org

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#9133]
# Broken Website Report

## Website Address
https://manjaro.org/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the web page background image missing in the screenshot needs fixing. (Screenshot 1)
Notice the missing computer image in the screenshot needs fixing. (Screenshot 1)
Notice the coloring mismatches (in header & footer of web page) in the screenshot need fixing. (Screenshot 1)

**NOTE:** Screenshots 2 - 5 are how the normal web page looks.

## Problematic Observation
Web Page Background Image Missing
Missing Computer Image
Coloring Mismatches (In Header & Footer of Web Page)

## Screenshots
Screenshot 1:

<img width="1152" alt="manjaro" src="https://user-images.githubusercontent.com/95879668/175576616-27478113-2427-4cee-a4b1-fd93965e09a8.png">

Screenshot 2:

![1](https://user-images.githubusercontent.com/95879668/175576576-7d443fb2-cf5a-4676-a8d5-e456068c7b41.png)

Screenshot 3:

![2](https://user-images.githubusercontent.com/95879668/175576587-71b637ec-3deb-4844-af16-bd0b644c65ee.png)

Screenshot 4:

![3](https://user-images.githubusercontent.com/95879668/175576600-8182f41f-f3a0-4e06-a66c-b5b3709f79ae.png)

Screenshot 5:

![4](https://user-images.githubusercontent.com/95879668/175576609-ebd0660f-7434-496a-9253-30f2b070a193.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 103
- Dark Reader Version: 4.9.51

## Additional Context
The Manjaro website has recently been completely rewritten from scratch.

**Comment by Gusted** [comment]
> Notice the web page background image missing in the screenshot needs fixing. (Screenshot 1)

Not possible. It has a negative z-index otherwise it will be above all text elements.

> Notice the missing computer image in the screenshot needs fixing. (Screenshot 1)

![image](https://user-images.githubusercontent.com/25481501/175695407-052e60ba-b73c-41ee-b96c-d4818b2bedf0.png)

**Comment by Gusted** [comment]
> I understand about the web page background.
> 
> Are you saying that you can see the computer picture?

Oh sorry, I forget the text. If I make the image to appear(forcing it on the same z-index), the dimensions would be fucked up.

**Comment by Gusted** [comment]
Limitations of what Dark Reader can do :(
