### ISSUE TITLE
[Bug] Include third party cookie issue

### ISSUE THREAD

**Issue by stullesha** [darkreader/darkreader#9142]
# Bug Report

## Website Address

Any website can do.

## Bug Description

Activate the Extension and open any page in your browser. Check the Console in Developer Tools. Then access the blue 'message' icon

## Steps To Reproduce

Follow the steps in bug description section
```
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

Note that for performance reasons, only the first access to one of the properties is shown.

AFFECTED RESOURCES: shortcutindexs.js:1
```

## System Information

- OS: Windows
- Browser: Brave 1.40
- Dark Reader Version: 4.9.51

**Comment by alexanderby** [comment]
Thanks for noticing this. We use navigator.userAgent and navigator.platform to fix some-browser specific issues.

But what did you mean by "third party cookie"?

**Comment by Gusted** [comment]
We cannot change this to their new API, the code that mainly relies on the chromium version, is pre-chromium v90 and still have to revert to the current way of detecting the user agent/platform, so it has little effect. Also it's currently not available in Firefox + a experimental API.

**Comment by alexanderby** [comment]
It should be something like `navigator.userAgentData ? navigator.userAgentData... : navigator.userAgent.match(...)`.

**Comment by Gusted** [comment]
> It should be something like `navigator.userAgentData ? navigator.userAgentData... : navigator.userAgent.match(...)`.

I'm not sold on it, all the info we need is still available on `userAgent`, unless they also will remove that, it's just more code for nothing.

**Comment by alexanderby** [comment]
Web devs see they have some issue in Chrome's "Issues" tab in dev tools. If I understand it correctly, if `navigator.userAgentData` will be used, the "Issues" tab should become empty.
<img width="805" alt="Screen Shot 2022-06-30 at 21 20 29" src="https://user-images.githubusercontent.com/9638588/176771692-6e53c7ca-7e43-440c-882e-fc512249ee69.png">

**Comment by Gusted** [comment]
So web developers will get false warning due to Dark Reader's code? Seems rather to me that Chromium would need to indicate that it isn't the site's fault but rather a content script. I've never been a fan of chromium's weird experimental API's (which can be killed anytime). I will make up a PR to fix this issue, which clearly never should have existed in the first place.

**Comment by alexanderby** [comment]
> Chromium would need to indicate that it isn't the site's fault but rather a content script
That's right, but all you can do here is to submit a Chromium issue.

> I've never been a fan of chromium's weird experimental API's
Come on, take a look at this:
```javascript
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
```
What is this all about? What `Mozilla/5.0` and `Safari/537.36` has to do with Chrome 103?
Now look at Chrome:
```json
{
    "brands": [
        {
            "brand": ".Not/A)Brand",
            "version": "99"
        },
        {
            "brand": "Google Chrome",
            "version": "103"
        },
        {
            "brand": "Chromium",
            "version": "103"
        }
    ],
    "mobile": false,
    "platform": "macOS"
}
```
And Edge:
```json
{
    "brands": [
        {
            "brand": "Microsoft Edge",
            "version": "105"
        },
        {
            "brand": ")Not;A=Brand",
            "version": "8"
        },
        {
            "brand": "Chromium",
            "version": "105"
        }
    ],
    "mobile": false,
    "platform": "macOS"
}
```
It's unclear what is "Not A Brand", but the idea is nice. It is strange the others don't implement it.
