### ISSUE TITLE
[Bug] Give the error of Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". 

### ISSUE THREAD

**Issue by navichawla92** [darkreader/darkreader#9154]
## Expected Behavior
dont throw any error in the console
## Actual Behavior

throw error in the console (Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-4L6Ajp07lFx9PhFqXfXIiUBTCQOVYeUpEae5CPlb4SE='), )
## Screenshots

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
> dont throw any error in the console

We don't throw the error, the browser does. We don't know ahead of time if we things we're going to do is allowed by the site, we can only try and hope. Can't fix/won't fix.
