### ISSUE TITLE
Twitter + Firefox popups not rendering properly

### ISSUE THREAD

**Issue by khanzf** [darkreader/darkreader#916]
I am running Firefox on Linux. When I go on Twitter and click on a popup reply buttoh, the window appears out of focus rather than in the center of the window. This appears to be a bug.

**Comment by alexanderby** [comment]
Are you using Filter mode?

**Comment by realnc** [comment]
Just in case you didn't know, Twitter has its own dark mode that you can enable. They call it "Night Mode." You can use that and disable Dark Reader for twitter.com.
