### ISSUE TITLE
[Feature Request] Switch on/off based on user's location's sunrise/sunset

### ISSUE THREAD

**Issue by MrShoenel** [darkreader/darkreader#9163]
# Feature Request

While I can set a static time for when to (de-)activate the extension, it'd be great if it could do that automatically, based on the time of when the sun rises or sets, which changes every day by a few minutes. Sunset/sunrise is based on my Geo location (lat/lon).
Ideally, I could also add some static offset to either time. For example, switch to dark 30min after sunset, or switch to light 15min before sunrise.

I suppose the extension would need to know my location for that and fetch or approximate these times (the latter would be actually preferable, even if it's not 100% accurate).
Calculation is possible; e.g., http://suncalc.net/

**Comment by bershanskiy** [comment]
Good news: this feature is already available! Just click on extension icon to open extension settings, then on "three dots" next to "On/Off" to open "Automation" settings and then set your location in the second set of inputs, make sure the toggle is enabled too.

![image](https://user-images.githubusercontent.com/45960703/176908886-681c7188-1afc-4a05-86b0-1fe6cf8694f9.png)
