### ISSUE TITLE
[Bug] Dark reader overrides custom Firefox theme

### ISSUE THREAD

**Issue by scolbyyy** [darkreader/darkreader#9186]
# Bug Report

## Bug Description

Turning on dark mode in Firefox overrides my browser theme (colors of the navigation bars and tabs) to the default dark Firefox theme. Turning dark reader off after this sets the browser theme to the default light theme.

## Steps To Reproduce

- Open Firefox (with a custom theme enabled)
- Turn on dark reader
- Observe navigation bar and tab colors

## Expected Behavior

The navigation bar and tab colors should still be the chosen Firefox theme.

## Actual Behavior

The navigation bar and tab colors are now the default Firefox theme.

## System Information

- OS: Windows 11 
- Browser: Firefox 102.0 (64-bit) 
- Dark Reader Version: 4.9.52 

## Additional Context

This issue did not used to be here with previous dark reader versions.

**Comment by Gusted** [comment]
Closing as duplication, #9185
