### ISSUE TITLE
[Broken Website] evga.com

### ISSUE THREAD

**Issue by osfanbuff63** [darkreader/darkreader#9192]
# Broken Website Report

## Website Address
https://www.evga.com

## Steps To Reproduce

- Navigate to https://evga.com (I used the [Z20 keyboard page](https://www.evga.com/products/product.aspx?pn=811-W1-20US-KR) and [KINGPIN 3090 Ti page](https://www.evga.com/products/product.aspx?pn=24G-P5-4998-KT) in the screenshots)

## Problematic Observation
White text on a white background on an unselected tab.

## Screenshots
![Screenshot 2022-07-04 202330](https://user-images.githubusercontent.com/91388253/177227968-d42e235d-1f9a-49c8-8cda-1235a14750b1.png)
![Screenshot 2022-07-04 202313](https://user-images.githubusercontent.com/91388253/177227969-78634aaf-525b-41ad-b6fe-5846f6d018e2.png)

## System Information

- OS: Windows 10
- Browser: Chrome 103
- Dark Reader Version: 4.9.52

## Additional Context

N/A

**Comment by tony1661** [comment]
Should the text change, or the tab background?
