### ISSUE TITLE
[Feature Request] Localize/translate rest of extension

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#9195]
Some parts of Dark Reader UI are not translated yet, for example Developer Tools. Should we translate them?

**Comment by alexanderby** [comment]
Dev Tools is for geeks, who already know English :) For the rest of the new UI, when it will be ready, I will use the Google Translate script (stored in `tasks/` folder) and then ask users, who already helped us, to check the mistakes.

**Comment by bershanskiy** [comment]
Oh, great to know!
