### ISSUE TITLE
Filter in FF v102 broken

### ISSUE THREAD

**Issue by jaskapaari** [darkreader/darkreader#9197]
# Bug Report

## Bug Description
Filter theme generation mode is not working correctly in FF v102 (v101 not tested), it seems to render/display all pages with white/light background and black text incorrectly. I tried with multiple DR versions going back all the way to 4.9.25 and they all displayed similar behavior in FF102.

## Steps To Reproduce
Use FF v102 (v101 untested, v100 and earlier it works) and set theme generation mode to Filter (or Filter+) and visit any page under https://man.archlinux.org or for example read the Rust Book ( https://doc.rust-lang.org/book/ch03-03-how-functions-work.html ) and see pages with code snippets. These two examples are not isolated occurences, but the same behavior was observed in a lot of pages with similar looks and elements.

## Expected Behavior
Expected behavior shown in https://0x0.st/oQqB.png and https://0x0.st/oQqM.png

## Actual Behavior
Actual behavior shown in https://0x0.st/oQqm.png  and https://0x0.st/oQqA.png

## Screenshots
Screenshots shown in links above.

## System Information
Linux
FF 102
DR 4.9.25 to 4.9.52

**Comment by Gitoffthelawn** [comment]
Thanks for the report.  I can confirm this issue.
