### ISSUE TITLE
[Bug] Light stripe at the bottom of the page

### ISSUE THREAD

**Issue by barl0g** [darkreader/darkreader#9211]
# Bug Report

## Website Address

Almost All. For example: https://www.google.com/

## Bug Description

Wide white stripe at the bottom of the page.

## Screenshots

https://ibb.co/HG4gcCy

## System Information

- OS:  Ubuntu Linux
- Browser: Firefox v.102.0 (64-bit)
- Dark Reader Version: current

**Comment by bershanskiy** [comment]
@barl0g I can not reproduce this. Since you observe this white stripe on "almost all" websites, there might be some weird interaction of multiple extensions. Which other extensions do you have?

**Comment by Gusted** [comment]
Likely duplicate of #9149

**Comment by bershanskiy** [comment]
@barl0g Could you please check whether you have Vimvixen installed?
