### ISSUE TITLE
[Broken Website] Wikipedia does not invert correctly

### ISSUE THREAD

**Issue by azat11** [darkreader/darkreader#9224]
# Broken Website Report

## Website Address

https://en.wikipedia.org/

## Steps To Reproduce

- Go to any article on Wikipedia (might open broken or correctly inverted)
- If correctly loaded, then refresh the page and it breaks (or open a link from the page to another article in a new tab, or click and follow a link to another article in the same tab)

## Problematic Observation

On opening an article, on page refresh, on opening a new page of the same site in a new tab, on following a link to another page of the same site, the page does not invert fully and correctly.

## Screenshots

Correctly loaded: https://ibb.co/0cZQwm9
Broken: https://ibb.co/SxKpzP2

## System Information

- OS:  Windows 7 Professional SP1
- Browser:  Waterfox G3.2.3
- Dark Reader Version:  4.9.52

## Additional Context

Started happening recently, when I switched from "Invert listed only" to "Not invert listed". Wasn't happening when Wikipedia was in the list with "Invert listed only". I am using dynamic mode. Disabling and enabling Dark Reader, or adding and removing the site to and from exceptions fixes how the page is displayed. But otherwise it rarely loads correctly currently.

**Comment by Gusted** [comment]
This is not reproducible, are there any errors in the console when this happens?

**Comment by Thibaut120094** [comment]
Reproducible on all Wikimedia websites (*.wikipedia.org, *.wikimedia.org, *.wiktionary.org, etc.) on Safari (both iOS 15.5 and macOS 12.4).
Here's a screenshot of what it looks like on fr.wikipedia.org: https://i.imgur.com/lsfgJXh.png
And here's a screenshot of the console: https://imgur.com/a/93e4nwv

On Firefox 102.0.1 on macOS 12.4, it works fine.

**Comment by Gusted** [comment]
Safari is a different extension, please open a separate issue for that.

**Comment by azat11** [comment]
> This is not reproducible, are there any errors in the console when this happens?

How can I look it up? Do you mean browser developer tools console? All I have is this:

`Cookie “enwikiwmE-sessionTickLastTickTime” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [Echo_chamber_(media) line 1046 > scriptElement:321:111](https://en.wikipedia.org/wiki/Echo_chamber_(media)%20line%201046%20%3E%20scriptElement)`

**Comment by Gusted** [comment]
Yeah not much interesting. Could you try to reproduce this issue on a new profile(about:profiles) and maybe with another browser?

**Comment by azat11** [comment]
> Yeah not much interesting. Could you try to reproduce this issue on a new profile(about:profiles) and maybe with another browser?

Didn't happen in Firefox. Still happens in a new profile in the same Waterfox browser.

**Comment by Gusted** [comment]
Then it seems to be a WateFox problem. It's likely missing some feature or being to strict about some API, it's a pain to debug such issue as Waterfox has weird "quirks" and is relying on an old code base. Not really much worth interest IMO.

**Comment by azat11** [comment]
> Then it seems to be a WateFox problem. It's likely missing some feature or being to strict about some API, it's a pain to debug such issue as Waterfox has weird "quirks" and is relying on an old code base. Not really much worth interest IMO.

Thanks. I guess I'll suffer what I must. Or look for a separate addon for wikipedia.

**Comment by Gusted** [comment]
You could give a try at WaterFox's issue tracker (seems to be responsive to compatibility problems). But I'm at no capabilities to debugging their issue.
