### ISSUE TITLE
[Feature Request] Shopping Item Images on Google browser do not swap Background color to increase visibility

### ISSUE THREAD

**Issue by Andy-Waine** [darkreader/darkreader#9237]
# Feature Request

## Is this feature request related to a problem?

In Dynamic mode, Chrome switches the backgrounds of shopping item images to black, greatly reducing visibility

## Screenshots

![GoogleAdBG-BEFORE](https://user-images.githubusercontent.com/88730354/178119391-db0833c4-651d-49c5-af32-a14b946a5e6f.PNG)

## Additional Context

PR incoming....

**Comment by Gusted** [comment]
Fixed by #9238
