### ISSUE TITLE
[Broken Website] knoppix.net

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#9244]
# Broken Website Report

## Website Address
https://knoppix.net/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the white area in the screenshot needs fixing.

## Problematic Observation
White Area

## Screenshots
![knoppix](https://user-images.githubusercontent.com/95879668/178130318-abc1496f-adc0-402c-a64b-69139b27fad2.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 104
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Not possible to fix, they are separating the images between two elements, one of which is `body` so inverting that causes all elements to be inverted.

![image](https://user-images.githubusercontent.com/25481501/178156451-bd8860ea-9796-40ac-ad0f-b2129f398437.png)
