### ISSUE TITLE
Greasemonkey

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#926]
I am using Falkon, the Qt/KDE web browser. 
It supports scripts for Greasemonkey. 

Do you think its easy to port your dark reader dynamic into a simple script or so?
It supports [casual plugins](https://phabricator.kde.org/source/falkon/browse/master/src/plugins/) also.

nowrep [here](https://kiwiirc.com/client/irc.freenode.net/?nick=darkreader|?#falkon) can help
thanks a lot

**Comment by alexanderby** [comment]
I'm afraid not, it is not possible for Dynamic mode. Often websites store their style sheets and images in other domains (CDNs), and they become not accessible from the web page. So the extension uses a background page to load them again and pass back to content script running on web page.

For Filter mode the script should be very primitive, you can even use some short CSS here.

**Comment by ShalokShalom** [comment]
So the static mode is available?

**Comment by alexanderby** [comment]
@ShalokShalom The static mode is very primitive, it simply injects static CSS.

**Comment by yzrsng** [comment]
@ShalokShalom
This script may be what you want.
https://github.com/yzrsng/userscripts/blob/master/compressed/dynamic-restyle-for-global-black.js

This script provides functionality similar to the dark reader dynamic mode.
The performance of this script is very low.
This script drains the battery.

**Comment by ShalokShalom** [comment]
Yes, at least something.

**Comment by heydojo** [comment]
@ShalokShalom here is some initial work I have done in this area:

```JavaScript
// ==UserScript==
// @name          Dark Reader (Unofficial)
// @icon          https://darkreader.org/images/darkreader-icon-256x256.png
// @namespace     DarkReader
// @description	  Inverts the brightness of pages to reduce eye strain
// @version       4.7.15
// @author        https://github.com/darkreader/darkreader#contributors
// @homepageURL   https://darkreader.org/ | https://github.com/darkreader/darkreader
// @run-at        document-end
// @grant         none
// @include       http*
// @require       https://cdn.jsdelivr.net/npm/darkreader/darkreader.min.js
// @noframes
// ==/UserScript==

DarkReader.enable({
	brightness: 80,
	contrast: 60,
	sepia: 0
});
```

The method works well with most sites, however it appears that if the page has invalid javascript and or html (like news article pages on bbc.co.uk) then Greasemonkey gives up. I tested this userscript with Greasemonkey on Firefox and also my fork of Falkon. On Falkon, it crashes consistently on pages such as openuserjs.org and phoronix.com (The pages take two reloads to render without error.)

I believe darkreader.js is currently too memory intensive for this purpose. The combination of invalid js, html and css on the page to be transformed and the large use of memory is what is breaking it on Falkon IMO but I haven't done any debugging. I guess that maybe there is a memory restriction in the Chromium part of QtWebEngine or in Falkon's Greasemonkey implementation. The script does not appear to crash on Firefox.

To even begin to get this Greasemonkey script to work in a similar way to the browser plugin, as far as I can see right now, the following needs to be true:

- The file https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config would need to be converted to json so that it can be pulled via CDN (https://cdn.jsdelivr.net/gh/darkreader/darkreader/src/config/dark_sites.json for example)
- dynamic-theme-fixes.config would then need to be added to the user script via [@resource](https://wiki.greasespot.net/Metadata_Block#.40resource)
- The exposed resource (eg. resourceName) would then need to be passed to DarkReader.enable

I quickly tried to get dynamic-theme-fixes.config to work but was unable. Any sensible suggestions may help here, although I think Darkreader may not be suitable in it's current state for this task.

**Comment by Gusted** [comment]
Not possible won't be possible due to the nature of extension

**Comment by nanangarsyad** [comment]
I had to dark reader config into this,
```
DarkReader.enable({
	brightness: 100,
	contrast: 100,
	sepia: 0
});
```
to get complete dark mode, like I'd usually get when using chrome and dark reader extension.
![image](https://user-images.githubusercontent.com/7588442/94748128-c76c0180-03aa-11eb-80a2-ff3ed6822201.png)

Though, sorry for bringing up old thread.
Well, just hoping this can be useful for the others too :)

**Comment by WillPower3309** [comment]
@nanangarsyad wow works perfectly for me! One issue I have though is that qutebrowser initially loads the regular site colorscheme and then a second later switched to the dark mode. Are there any fixes possible? Not sure if its a config issue on my end or a general qutebrowser / greasemonkey limitation

**Comment by ShalokShalom** [comment]
That is due to the nature of the implementation and is the same on many similar scripts.

**Comment by WillPower3309** [comment]
> That is due to the nature of the implementation and is the same on many similar scripts.

thanks for the clarification!

**Comment by Kominminsoe88** [comment]
# 926

**Comment by chadify** [comment]
How can I use dark reader themes ( for example dracula or solarized ) with this script?

**Comment by ShalokShalom** [comment]
No, since its not DarkReader. True DarkReader is much more sophisticated, this just changes colors in a static fashion, the true DarkReader extension is intelligent and adjusts its theme according to the page it finds. 

Thanks for letting us know, that DarkReader has themes, I didnt know about this!

**Comment by cenktaskin** [comment]
> @ShalokShalom here is some initial work I have done in this area:
> 
> ```js
> // ==UserScript==
> // @name          Dark Reader (Unofficial)
> // @icon          https://darkreader.org/images/darkreader-icon-256x256.png
> // @namespace     DarkReader
> // @description	  Inverts the brightness of pages to reduce eye strain
> // @version       4.7.15
> // @author        https://github.com/darkreader/darkreader#contributors
> // @homepageURL   https://darkreader.org/ | https://github.com/darkreader/darkreader
> // @run-at        document-end
> // @grant         none
> // @include       http*
> // @require       https://cdn.jsdelivr.net/npm/darkreader/darkreader.min.js
> // @noframes
> // ==/UserScript==
> 
> DarkReader.enable({
> 	brightness: 80,
> 	contrast: 60,
> 	sepia: 0
> });
> ```
> 
> The method works well with most sites, however it appears that if the page has invalid javascript and or html (like news article pages on bbc.co.uk) then Greasemonkey gives up. I tested this userscript with Greasemonkey on Firefox and also my fork of Falkon. On Falkon, it crashes consistently on pages such as openuserjs.org and phoronix.com (The pages take two reloads to render without error.)
> 
> I believe darkreader.js is currently too memory intensive for this purpose. The combination of invalid js, html and css on the page to be transformed and the large use of memory is what is breaking it on Falkon IMO but I haven't done any debugging. I guess that maybe there is a memory restriction in the Chromium part of QtWebEngine or in Falkon's Greasemonkey implementation. The script does not appear to crash on Firefox.
> 
> To even begin to get this Greasemonkey script to work in a similar way to the browser plugin, as far as I can see right now, the following needs to be true:
> 
> * The file https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config would need to be converted to json or the file extension changed to .txt so that it can be pulled via CDN (https://cdn.jsdelivr.net/gh/darkreader/darkreader/src/config/dark_sites.json for example)
> * dynamic-theme-fixes.config would then need to be added to the user script via [@resource](https://wiki.greasespot.net/Metadata_Block#.40resource)
> * The exposed resource (eg. resourceName) would then need to be passed to DarkReader.enable
> 
> I quickly tried to get dynamic-theme-fixes.config to work but was unable. Any sensible suggestions may help here, although I think Darkreader may not be suitable in it's current state for this task.

This is really useful! I just had dark reader work. But I wonder if someone managed to get the dynamic configuration work on the two years following this comment.

**Comment by ShalokShalom** [comment]
That's not possible with Greasemonkey.

**Comment by ShalokShalom** [comment]
Looks nice! :)

**Comment by ShalokShalom** [comment]
I guess this is worth sharing with the Falkon guys as well. 

As it is a KDE project: 
https://bugs.kde.org

**Comment by jabuxas** [comment]
answering @chadify's question on themes, I went to the src url `https://cdn.jsdelivr.net/npm/darkreader/darkreader.min.js` and found what properties one could use and, you can use
``` 
darkSchemeBackgroundColor: "#002b36",
darkSchemeTextColor: "#93a1a1",
```

for a solarized dark colorscheme. enjoy!
![image](https://github.com/user-attachments/assets/382ef60e-701a-4fef-919a-e6175c5995d1)
