### ISSUE TITLE
[Broken Website] icloud.com/reminders white foreground on black background(see pictures)

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#9268]
# Broken Website Report

## Website Address

icloud.com/reminders
icloud.com/notes
icloud.com
## Steps To Reproduce

- Go to icloud.com/reminders
- go to any reminder or create a new one
- white foreground on black background

## Problematic Observation

it should be switched to dark theme, as their native app on iphone/ipad.
## Screenshots

broken reminders website
![image](https://user-images.githubusercontent.com/78726445/178321036-c3db4096-8bc1-4b4f-8966-f5809b222ddf.png)
broken notes website
![image](https://user-images.githubusercontent.com/78726445/178321978-61f565b2-d3b1-4911-9017-8ba1e495e120.png)

## System Information

- OS:  windows 11 latest
- Browser:  chrome version: Version 103.0.5060.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.5.2 latest

## Additional Context

also icloud.com/notes have the same problem, so i think icloud.com needs to be fixed as a whole.

**Comment by yazan1107** [comment]
man thanks for solving this <3

**Comment by yazan1107** [comment]
it is still having the same issue! someone please fix it!

**Comment by direrFlood** [comment]
https://github.com/darkreader/darkreader/pull/10216
