### ISSUE TITLE
[Broken Website] icloud.com/notes white foreground on black background(see pictures)

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#9269]
# Broken Website Report

## Website Address

icloud.com/reminders
icloud.com/notes
icloud.com
## Steps To Reproduce

- Go to icloud.com/notes
- go to any note or create a new one
- white foreground on black background

## Problematic Observation

it should be switched to dark theme, as their native app on iphone/ipad.
## Screenshots

![image](https://user-images.githubusercontent.com/78726445/178321572-1ef3c0a8-5745-4477-8104-033878502aec.png)
## System Information

- OS:  windows 11 latest
- Browser:  chrome version: Version 103.0.5060.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.5.2 latest

## Additional Context

also icloud.com/notes have the same problem, so i think icloud.com needs to be fixed as a whole.

**Comment by direrFlood** [comment]
https://github.com/darkreader/darkreader/pull/10216
