### ISSUE TITLE
If native dark theme is used on DDG, "clicked links" icon is broken

### ISSUE THREAD

**Issue by theel0ja** [darkreader/darkreader#927]
![](https://user-images.githubusercontent.com/5832930/50118398-30c36480-0258-11e9-9ed7-ef32457bfdea.png)

right corner "Hamburger Menu" -> fourth theme

**Comment by FranklinYu** [comment]
If #1327 is implemented then Dark Reader would be disabled on DuckDuckGo. Do you think that helps?

**Comment by Gusted** [comment]
Should be fixed.
