### ISSUE TITLE
[Broken Website] Hard to read macrumors.com with Solarized Light

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9278]
# Broken Website Report

## Website Address
[https://www.macrumors.com/](https://www.macrumors.com/)

## Problematic Observation
1. I get almost the same color for both background and text (I'm not sure if this issue is related to #3940 in any way).
2. The expected behavior is for the background to be yellowish for this theme and the text to be gray (somewhat the opposite of what is shown on the right column in the screenshot).

## Screenshots
<img width="1900" alt="Screen Shot 2022-07-12 at 12 27 55 PM" src="https://user-images.githubusercontent.com/11276349/178578637-63307926-e185-4609-8a37-273d31d69b82.png">

Theme: Solarized Light

## System Information

- OS: macOS
- Browser: Brave 1.41.96
- Dark Reader Version: 4.9.52

## Additional Context
On a similar note, is it possible to add a Minimum Contrast option [similar to iTerm](https://iterm2.com/documentation-preferences-profiles-colors.html) to avoid such issues?

> **Minimum contrast**
If text is displayed against a similar background color, the minimum contrast setting will move the text color towards black or towards white to ensure some minimum level of visibility. Setting this slider all the way to maximum will make all text black and white.

**Comment by Gusted** [comment]
@alexanderby https://github.com/darkreader/darkreader/blob/main/src/generators/modify-colors.ts#L95 Do you happen to know why Dark Reader passes both fg and bg to the light mode generator(instead of fg for text-color and bg for background color)? This currently causes this issue whereby the text-color is so much affected by the background-color, that it will switch to the background color.

**Comment by MahdiNazemi** [comment]
@Gusted @alexanderby, On a similar note, some websites use the foreground color for their background when Dark Reader is enabled in light mode.

For example, the first screenshot below is from Slack with the default color scheme in which the chat area has a white background.
<img width="1612" alt="Screen Shot 2022-08-10 at 10 47 38 AM" src="https://user-images.githubusercontent.com/11276349/183981921-fc8c8cf6-66bf-4a5a-ad42-acc3d9cf04c6.png">

When Dark Reader and Gruvbox Light are applied to the same page, the background color turns dark while the text is in a light color. The expected output is for the background to be yellowish and the text to be grayish.
<img width="1612" alt="Screen Shot 2022-08-10 at 10 47 52 AM" src="https://user-images.githubusercontent.com/11276349/183982003-5251c31b-7cb7-4337-8b0e-44979afc7db8.png">
 
For Dark Reader and Gruvbox Dark, the output is as expected:
<img width="1612" alt="Screen Shot 2022-08-10 at 10 53 39 AM" src="https://user-images.githubusercontent.com/11276349/183982738-67c90251-a163-4b80-9498-61ded3c2bb39.png">

**Comment by MahdiNazemi** [comment]
@Gusted, this looks like a bug to me. Would you please add the bug tag if you agree?

**Comment by Gusted** [comment]
>  this looks like a bug to me. Would you please add the bug tag if you agree?

Done it, still won't do much as this in a specific part of the code that is built on top of magic.

**Comment by MahdiNazemi** [comment]
Here is what happens to the CSS:

Initial version:
```css
.article--2pJwZBkO {
    border-radius: 4px;
    margin-bottom: 20px;
    background: #fff;
}
```

First modification (correct background and foreground):
```css
.article--2pJwZBkO {
    background-image: initial;
    background-color: rgb(251, 241, 199);
}
```

Second modification (inverted background and foreground):
```css
.article--2pJwZBkO {
    background-image: initial;
    background-color: rgb(78, 73, 70);
}
```

**Comment by MahdiNazemi** [comment]
@alexanderby, can you please give me a few pointers on where to start if I plan to debug this issue?
