### ISSUE TITLE
[Broken Website] instagram.com

### ISSUE THREAD

**Issue by osfanbuff63** [darkreader/darkreader#9287]
# Broken Website Report

## Website Address
[instagram.com](https://instagram.com)

## Steps To Reproduce
Go to [instagram.com](https://instagram.com) and notice the image is dark gray on black.

## Problematic Observation
The logo is displaying dark gray on a black background, which is hard to see.

## Screenshots

![image](https://user-images.githubusercontent.com/91388253/178767109-3ab25aa7-c832-4e91-9847-82a0e33e5147.png)

## System Information

- OS: Windows 10
- Browser: Chrome 103.0.5060.114 (Official Build) (64-bit) (cohort: Stable) 
- Dark Reader Version: 4.9.52

## Additional Context

N/A

**Comment by Gusted** [comment]
Not reproducible for me, does this also happen when you're logged out of your Instagram account and visit someone's profile?
![image](https://user-images.githubusercontent.com/25481501/179349752-48f67e4d-fbf6-467e-8f58-e8e598ba881b.png)

**Comment by yazan1107** [comment]
i am experiencing the same issue.

**Comment by Gusted** [comment]
Hi @yazan1107

Please add a 👍🏽 reaction to the post or try to answer any questions the maintainer has(https://github.com/darkreader/darkreader/issues/9287#issuecomment-1186135282 in this case), that's the best practice to show that you also are experiencing the same bug.

**Comment by osfanbuff63** [comment]
> Not reproducible for me, does this also happen when you're logged out of your Instagram account and visit someone's profile? ![image](https://user-images.githubusercontent.com/25481501/179349752-48f67e4d-fbf6-467e-8f58-e8e598ba881b.png)

On a new Chrome profile with no Instagram account signed in, this still occurs.
![image](https://user-images.githubusercontent.com/91388253/180082026-247fa49a-9365-43e4-a8f4-bd7900c435fc.png)

Also reproducible on a fresh install of Firefox:
![image](https://user-images.githubusercontent.com/91388253/180082387-a888f06f-57dc-4cfd-a2f1-e8739284fecc.png)
