### ISSUE TITLE
[Broken Website] https://ge.globo.com

### ISSUE THREAD

**Issue by vassilyzaitsev** [darkreader/darkreader#9292]
# Broken Website Report

## Website Address
https://ge.globo.com/

## Steps To Reproduce
Go to the website, set it to dark mode, try to go deeper to any article/subpage. It will not stay dark.

## Problematic Observation
If you go back to light mode, then to dark again, it stays dark. But you need to do that to every subpage, which is not ideal.

## Screenshots
https://i.imgur.com/LOlEhpP.gif

## System Information

- OS: Windows 
- Browser: Firefox 102.0.1 (64-bit) 
- Dark Reader Version: 4.9.52

## Additional Context
- Can the issue be reproduced in a fresh browser profile? YES
- Is there an existing issue about this? NO

**Comment by Gusted** [comment]
Will be fixed in the next release by #9150
