### ISSUE TITLE
[Broken Website] next-episode.net

### ISSUE THREAD

**Issue by Anirog** [darkreader/darkreader#9307]
# Broken Website Report

## Website Address
https://next-episode.net/

## Steps To Reproduce
Go to https://next-episode.net/ with dark reader enabled and 'detect dark theme' enabled in dark reader settings.

## Problematic Observation
The website does not have a dark theme

## Screenshots

![IMG_2167](https://user-images.githubusercontent.com/46462079/179350505-4446b519-1042-497e-9b37-72d9e309e56e.png)

## System Information

- OS: iPadOS 15.5
- Browser: Safari
- Dark Reader Version: 1.4.2

## Additional Context
N/A

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016#discussioncomment-3161474
