### ISSUE TITLE
[Broken Website] BBC, UK, Logo is not inverted

### ISSUE THREAD

**Issue by wrestlerdude** [darkreader/darkreader#9309]
# Broken Website Report

## Website Address
bbc.co.uk

## Steps To Reproduce

- Go to bbc.co.uk

## Problematic Observation

The BBC logo is not inverted.

## Screenshots

![image](https://user-images.githubusercontent.com/26298518/179353286-f42e262f-719c-4f31-97ed-62819a243313.png)

## System Information

- OS: Linux (Ubuntu 22.04)
- Browser: Firefox 102
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Seems to be geo-locked, I get redirected to bbc.com

Are you able to make a screenshot of the dev tools with the logo selected as element?

**Comment by wrestlerdude** [comment]
> Seems to be geo-locked, I get redirected to bbc.com
> 
> Are you able to make a screenshot of the dev tools with the logo selected as element?

Aye. Here you go.

![image](https://user-images.githubusercontent.com/26298518/179357962-f04d2251-59bc-4250-8ecb-4bd62f486439.png)

**Comment by wrestlerdude** [comment]
> Seems to be geo-locked, I get redirected to bbc.com
> 
> Are you able to make a screenshot of the dev tools with the logo selected as element?
Aye. Of course.

![image](https://user-images.githubusercontent.com/26298518/179358032-8909313e-f5ca-4974-8505-234305e8f399.png)

**Comment by JohnVeness** [comment]
This appears to still be an issue (or has regressed). Thee BBC logo is dark on:

- https://www.bbc.co.uk/
- https://www.bbc.co.uk/news
- https://www.bbc.co.uk/sport
- https://www.bbc.co.uk/bitesize
- https://www.bbc.co.uk/cbbc
- https://www.bbc.co.uk/cbeebies

It appears OK on:

- https://www.bbc.co.uk/weather
- https://www.bbc.co.uk/iplayer
- https://www.bbc.co.uk/sounds
- https://www.bbc.co.uk/food

Let me know if you would rather I created a new issue.
