### ISSUE TITLE
[Broken Website] 3 related sites that need logo fixes

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#9316]
# Broken Website Report

## Website Address
https://www.altlinux.org/
https://www.basealt.ru/
https://getalt.org/en/

## Steps To Reproduce
Visit the websites with Dark Reader enabled.
Notice the logos in the screenshots need fixing.

## Problematic Observation
Logos

## Screenshots
![altlinux](https://user-images.githubusercontent.com/95879668/179371052-bbe66ba5-afef-4f8d-9d1c-fb1f623adf5d.png)

![basealt](https://user-images.githubusercontent.com/95879668/179371057-c90d8041-5312-4b2c-a198-e9ea99f8bb1e.png)

![getalt](https://user-images.githubusercontent.com/95879668/179371060-7726fd8f-2ba5-4edc-821a-5b08b87de629.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 104
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
> https://www.basealt.ru/

Messes up with the text.
![image](https://user-images.githubusercontent.com/25481501/179466458-806a2b0c-9c7b-4b64-8c95-de6df6c30f02.png)
