### ISSUE TITLE
Instagram embeds have black icons.

### ISSUE THREAD

**Issue by theel0ja** [darkreader/darkreader#933]
Example page: https://rawgit.theel0ja.info/theel0ja/6351e6d901e7a59ece38ffeacdad0027/raw/1ed34f95deb7492767caecb420bcb9707cabf699/ig-embed.html

![](https://user-images.githubusercontent.com/5832930/50246303-a573db80-03dd-11e9-82a8-2703eec37e2e.png)

**Comment by Gusted** [comment]
LGTM.
