### ISSUE TITLE
[Broken Website] Set of 10 sites that need logo fixes #8

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#9333]
# Broken Website Report

## Website Address
https://gumroad.com/ - Screenshot 1
https://www.huawei.com/en/ - Screenshot 2
https://www.ibm.com/us-en/ - Screenshot 3
https://www.informa.com/ - Screenshot 4
https://www.informatech.com/ - Screenshot 5
https://inspiration.kenmore.com/ - Screenshot 6
https://www.iubenda.com/en/ - Screenshot 7
https://www.kbb.com/ - Screenshot 8
https://www.kenmore.com/ - Screenshot 9
https://www.kenwood.com/usa/ - Screenshot 10

## Steps To Reproduce
Visit the websites with Dark Reader enabled.
Notice the logos in the screenshots need fixing.

## Problematic Observation
Logos

## Screenshots

Screenshot 1

![gumroad](https://user-images.githubusercontent.com/95879668/179535883-b464a18d-bdce-41c6-9ea4-558a45f71e1d.png)

Screenshot 2

![huawei](https://user-images.githubusercontent.com/95879668/179535903-cfbba950-29a1-4e35-8eb7-b492bac26ee0.png)

Screenshot 3

![ibm](https://user-images.githubusercontent.com/95879668/179535944-42cba7d7-37a8-4b6b-953d-28ab379d8e31.png)

Screenshot 4

![informa](https://user-images.githubusercontent.com/95879668/179535972-fe207384-74a7-4594-8edc-680b1ff41005.png)

Screenshot 5

![informatech](https://user-images.githubusercontent.com/95879668/179535997-cfecb8d0-6fae-4c41-bc4e-24861001c132.png)

Screenshot 6

![inspiration kenmore com](https://user-images.githubusercontent.com/95879668/179536035-4fbcdd6b-a648-4078-93aa-5a19ad84242f.png)

Screenshot 7

![iubenda](https://user-images.githubusercontent.com/95879668/179536057-baa27b43-4551-423f-9b8c-5eb741e379ca.png)

Screenshot 8

![kbb](https://user-images.githubusercontent.com/95879668/179536078-2bc7eaad-56fd-4b86-bbac-3b7f370ab52b.png)

Screenshot 9

![kenmore](https://user-images.githubusercontent.com/95879668/179536111-291c9cbf-3568-4d20-b1d2-ef8c8631e6ee.png)

Screenshot 10

![kenwood](https://user-images.githubusercontent.com/95879668/179536162-9b6d69cb-7058-458a-a527-d3ff2b15c42b.png)

## System Information

- OS: Arch Linux
- Browser: Firefox Nightly 104
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Sorry, the issue got caught in my spam box.

> https://www.ibm.com/us-en/ - Screenshot 3

Not possible to fix, it includes the background-color :/
![image](https://user-images.githubusercontent.com/25481501/181476167-67f9dd1c-8d19-4167-9ff2-fd85f24fb2d9.png)

> https://inspiration.kenmore.com/ - Screenshot 6

It's gray, not really a good color that can be inverted.
![image](https://user-images.githubusercontent.com/25481501/181476629-e57a3430-f444-4b8f-8d7d-75a90b88beb8.png)
