### ISSUE TITLE
[Bug] Disabling or enabling Dark Reader for a specific website reloads Dark Reader on all open tabs in Firefox

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9336]
# Bug Report

## Bug Description

Enabling or disabling Dark Reader on one domain refreshes the colors on all open tabs when focusing on them.

## Steps To Reproduce

- Open multiple tabs from different domains in Firefox.
- Disable Dark Reader on one of the open tabs (or enable it on one of the tabs if Dark Reader was previously disabled on that domain).
- Switch to other tabs.
- Observe how the color scheme on the selected tab is reloaded.

## Expected Behavior

Enabling or disabling Dark Reader on one domain is expected only to affect the tabs in that domain.

## Actual Behavior

Enabling or disabling Dark Reader on one domain affects all open tabs.

## System Information

- OS: macOS Catalina/Monterey
- Browser: Firefox 102.0.1
- Dark Reader Version: 4.9.52

## Additional Context

This bug is only present in Firefox but not in Brave.

**Comment by erkinalp** [comment]
Can reproduce.
