### ISSUE TITLE
https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glVertexPointer.xml

### ISSUE THREAD

**Issue by ivanzinhoa** [darkreader/darkreader#9338]
# Broken Website Report

## Website Address
https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glVertexPointer.xml

## Problematic Observation
The extension doesn't work either in Chrome, Edge, or Firefox

## System Information

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
Dark Reader only works on HTML pages, not on XML.
