### ISSUE TITLE
[Broken Website] Spoiler/Hide text function doesn't work on Resetera.com (Dynamic theme)

### ISSUE THREAD

**Issue by SixelAlexiS90** [darkreader/darkreader#9342]
# Broken Website Report

## Website Address

https://www.resetera.com

Specifically this is the link to a post that shows the issue:
https://www.resetera.com/threads/count-as-high-as-we-can-until-mods-close-the-thread.556576/page-55#post-89035284

## Steps To Reproduce

- Use the "Dynamic" theme of Dark Reader
- Go to https://www.resetera.com
- Hover the mouse over the purple box that supposedly should hide the text, example:
https://www.resetera.com/threads/count-as-high-as-we-can-until-mods-close-the-thread.556576/page-55#post-89035284

## Problematic Observation

The purple box is transparent and so you can read through the supposedly hide text

## Screenshots

Resetera with no Dark Reader

![Resetera spoiler text](https://user-images.githubusercontent.com/63536218/179694074-bce8ceec-aaab-46e3-af5a-b1131873ced4.PNG)

Resetera with Dark Reader (Dynamic theme)

![Resetera broken spoiler text](https://user-images.githubusercontent.com/63536218/179694070-98e9115a-0357-485a-90e2-aa9fe1b7009e.PNG)

## System Information

- OS:   Windows 10 Pro 21H2 - 19044.1826
- Browser:  Chrome 103.0.5060.114 (Official Build) (64 bit)
- Dark Reader Version:  4.9.52

## Additional Context

The issue appears only with the "Dynamic" theme for me (at least on Resetera), but all other modes have really ugly layouts and color settings on that site so they aren't really usable.

**Comment by Gusted** [comment]
Is there a public post where this spoiler text is broken?

**Comment by SixelAlexiS90** [comment]
I'm sorry, I see that this topic got closed with a "fix", does it mean that it will be fixed in a future update of Dark Reader? Thank you very much :)

**Comment by Gusted** [comment]
Yes.
