### ISSUE TITLE
[Broken Website] iCloud.com/reminders white foreground text boxes on black background

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#9345]
# Broken Website Report

## Website Address

icloud.com/reminders
## Steps To Reproduce

- Go to icloud.com/reminders
- go to any reminder or create a new one
- white foreground on black background

## Problematic Observation

it should be switched to dark theme, as their native app on iphone/ipad.
## Screenshots

broken reminders website
![image](https://user-images.githubusercontent.com/78726445/178321036-c3db4096-8bc1-4b4f-8966-f5809b222ddf.png)

## System Information

- OS:  windows 11 latest
- Browser:  chrome version: Version 103.0.5060.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.5.2 latest

**Comment by direrFlood** [comment]
https://github.com/darkreader/darkreader/pull/10216
