### ISSUE TITLE
[Broken Website] icloud.com/notes showing only light icons of automatic switch light/dark drawings(on apple notes). check the pictures

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#9349]
# Broken Website Report

## Website Address

icloud.com/notes
## Steps To Reproduce

have a drawn note on iCloud notes using ipad or iphone.
go to icloud.com/notes from your browser
voila you have an icon showing dark drawing on white back ground meanwhile the drawing is white drawing on black background
## Problematic Observation

you have an **icon** showing d**ark drawing on white back ground** meanwhile the drawing is white drawing on blackground instead **it should show icon showing white drawing on blackground(Check the photos for more details)** btw on apple notes drawings changes per light/dark mode accordingly, so should the icons.
## Screenshots

better quality example:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/78726445/179824104-235331d2-1794-4124-aab9-0e91dc0e1853.png">
my drawing emphasizing the problem:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/78726445/179824418-1c75d392-44b4-402c-897a-e5169d08a4f5.png">

## System Information

- OS: windows 11
- Browser:  chromeVersion 103.0.5060.114 (Official Build) (64-bit)
- Dark Reader Version:  4.9.5.2 latest

**Comment by yazan1107** [comment]
@c-nagy check this issue with icloud.com/notes.

**Comment by direrFlood** [comment]
https://github.com/darkreader/darkreader/pull/10216
