### ISSUE TITLE
[Bug] automatic site fixes not working

### ISSUE THREAD

**Issue by yazan1107** [darkreader/darkreader#9350]
# Bug Report
https://github.com/darkreader/darkreader#site-fixes
## Website Address

dark reader dev tools
## Bug Description

automatic site fixes is not working as expected. it does not update dev tools or anything in the extension. 
https://github.com/darkreader/darkreader#site-fixes
## Steps To Reproduce

enable it with version 5.

## Expected Behavior

automatic site fixes from the git.
## Actual Behavior

nothing changes/syncs.
## System Information

- OS: windows 11
- Browser:  chrome latest
- Dark Reader Version: dark 4.9.5.2

**Comment by Gusted** [comment]
Hi @yazan1107!

The button isn't magic and only enables the logic to update the site-fixes, but it wouldn't run it immediately. 
Please try to open the dev tools and click on "Reset" to force this behavior.

**Comment by yazan1107** [comment]
resetting the dev tools tends to help. thanks @Gusted
