### ISSUE TITLE
[Bug] Dark Reader incorrectly handles color-scheme CSS property

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#9356]
# Bug Report

## Website Address

https://github.com/darkreader/darkreader/

## Bug Description

Broken/fallback styles on the entire site.

## Steps To Reproduce

 - open GitHub (almost any page), e.g., [this page](https://github.com/darkreader/darkreader/commit/9df0ce70c8b21d7aa9fc3e50667847c6a238a7e0)
 - refresh a few times if site does not appear broken
 - observe broken/fallback style

## Expected Behavior

 - regular style, no DR errors in the console

## Actual Behavior

Observe the following in the console:
```
Uncaught TypeError: Cannot read properties of null (reading 'r')
    at index.js:1621:31
    at Array.forEach (<anonymous>)
    at getCacheId (index.js:1620:22)
    at modifyColorWithCache (index.js:1642:20)
    at modifyForegroundColor (index.js:1792:16)
    at index.js:2635:32
    at index.js:4417:50
    at Array.forEach (<anonymous>)
    at index.js:4414:34
    at Array.forEach (<anonymous>)
```

## Screenshots

![image](https://user-images.githubusercontent.com/45960703/179911663-6a037bb3-27cf-4a48-bd21-fde8d795a09c.png)

## System Information

- OS: Windows 11
- Browser: Chrome 103
- Dark Reader Version: `master`

## Additional Context

This might be a regression from #9337 because when I checkout commit right before that PR the issue goes away. (The problematic commit for me appears to be `9df0ce70c8b21d7aa9fc3e50667847c6a238a7e0`, so I checked out `feea3193284a616f4ab169d0a6dc5bafe9e90d48` and it was good.)

**Comment by bershanskiy** [comment]
I think this issue occurs when `parseColorWithCache()` returns `null`. The following tiny patch fixes the problem for me, but there is probably a prettier solution as well.

```diff
diff --git a/src/inject/dynamic-theme/modify-css.ts b/src/inject/dynamic-theme/modify-css.ts
index 407fd9b6..2f7bfd43 100644
--- a/src/inject/dynamic-theme/modify-css.ts
+++ b/src/inject/dynamic-theme/modify-css.ts
@@ -243,6 +243,9 @@ function getColorModifier(prop: string, value: string): string | CSSValueModifie
     }
     try {
         const rgb = parseColorWithCache(value);
+        if (rgb === null) {
+            throw new Error('parseColorWithCache failed');
+        }
         if (prop.includes('background')) {
             return (filter) => modifyBackgroundColor(rgb, filter);
         }
```

**Comment by Gusted** [comment]
#9362 likely there's more code like this, which still expects that the code throws an exception. But couldn't find any other reference for now.
