### ISSUE TITLE
Office 365 Planner lists are greyed out

### ISSUE THREAD

**Issue by singhkays** [darkreader/darkreader#936]
For Office 365 Planner https://tasks.office.com/, lists are greyed out while description is the correct color. If I toggle the extension on and off, the lists show up with correct color

![image](https://user-images.githubusercontent.com/6164178/50316649-5de86080-046c-11e9-8988-91be5bc99f14.png)

![image](https://user-images.githubusercontent.com/6164178/50316697-925c1c80-046c-11e9-9b17-3507fc8ef38c.png)

**After toggling the extension or site support**

![image](https://user-images.githubusercontent.com/6164178/50316715-ad2e9100-046c-11e9-8bcc-199c941c6b63.png)

**Comment by Gusted** [comment]
Fixed.
