### ISSUE TITLE
Allow OS specific text stroke settings

### ISSUE THREAD

**Issue by singhkays** [darkreader/darkreader#937]
Can we get an OS specific text stroke settings? The scenarios is that Mac OS and Windows have a different method for rendering text i.e. Mac OS text tends to be a little bolder (already have some amount of stroke applied?). The stroke setting for a specific site that look perfect on Windows look weird on Mac OS. That's why an OS specific stroke settings would be useful.

**Comment by alexanderby** [comment]
Sub pixel rendering algorithms differ in macOS and Windows. For some reason bright text on dark background looks bolder on macOS. In recent macOS Mojave sub pixel rendering was disabled by default and text should look more thin.

**Comment by singhkays** [comment]
@alexanderby That's correct, however I was able to fix that using this article https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/ specifically 

`defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE`

**Comment by Gusted** [comment]
It's not exposed to Dark reader unfortunately.
