### ISSUE TITLE
[Dynamic] Dynamic mode breaking some websites.

### ISSUE THREAD

**Issue by wooles** [darkreader/darkreader#938]
Problem first time occurred today, I'm using Chrome ver. 71.0.3578.98. 
You can see it on the video https://streamable.com/ooe31

**Comment by alexanderby** [comment]
Sorry, added some small and not well tested optimization, that broken inversion of background images in Chrome. Just published an update 4.7.4, it will be available soon.

**Comment by alexanderby** [comment]
Should be available now. To speed up the update, open chrome://extensions page, enable Developer mode and click Update. Sorry again, I will think on adding some visual tests to stop checking for such issues manually.
