### ISSUE TITLE
[BUG] Umm... I think its broken? 

### ISSUE THREAD

**Issue by pussfacestalk** [darkreader/darkreader#939]
Hello!

I'm pretty sure that's not how its supposed to look like with dark mode on? I added those red boxes with ms paint as that website is literary where I jot down random things but that background is disturbing.

![image](https://user-images.githubusercontent.com/42937542/50358428-45b53600-057f-11e9-9242-9d5c13bca5cf.png)

Please fix it asap. Thank you.

Google Chrome 73.0.3642.0 (Official Build) dev (64-bit) (cohort: Dev)
Dark Reader 4.7.3

OS Name Microsoft Windows 7 Professional
Version 6.1.7601 Service Pack 1 Build 7601
System Type x64-based PC

**Comment by alexanderby** [comment]
Should work well in version 4.7.4

**Comment by pussfacestalk** [comment]
Thanks for the quick fix.
