### ISSUE TITLE
[Broken Website] All-dark images on certains part of Newegg.com

### ISSUE THREAD

**Issue by gashtal** [darkreader/darkreader#9396]
# Broken Website Report

## Website Address

Broken:
https://www.newegg.com/
https://www.newegg.com/Just-Deals/EventSaleStore/ID-9516
Working:
https://www.newegg.com/Desktop-Graphics-Cards/SubCategory/ID-48?Tid=7709

## Steps To Reproduce

- Go to Newegg.com with Dark mode enabled.
- All product images (not ads) on the main page are completely dark.
- Click on a product or go to a category page such as https://www.newegg.com/Desktop-Graphics-Cards/SubCategory/ID-48?Tid=7709.
- The same images are now displayed correctly.

## Problematic Observation

Product images are completely darkened on some (but not all) pages under Newegg.com

## Screenshots

**Broken example on main page:**

![image](https://user-images.githubusercontent.com/27990818/180625137-5748c37b-faaa-4590-9b2e-dcf2426322ee.png)

**Working example on category page:**

![image](https://user-images.githubusercontent.com/27990818/180625158-954b2784-d9bc-45e4-b5f4-6a09e7f7fe67.png)

## System Information

- OS: Windows 10 x64
- Browser: Tested with both Firefox 102.0.1 (64-bit) and Opera 89.0.4447.38 (64-bit)
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Already fixed https://github.com/darkreader/darkreader/pull/9282. See https://github.com/darkreader/darkreader#site-fixes
