### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by kimjinzhan** [darkreader/darkreader#9398]
# Broken Website Report

## Website Address

<chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/assets/pdf/web/viewer.html?file=file%3A%2F%2F%2FC%3A%2FUsers%2FXiaomi%2FDesktop%2Fcode%2FEN_Computer%2520Systems_%2520A%2520Programmer%25E2%2580%2599s%2520Perspective-Pearson%2520(2015).pdf#%5B%7B%22num%22%3A194%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22Fit%22%7D%5D>

## Steps To Reproduce

- Use an Chrome extensions called 沙拉查词-聚合词典划词翻译 <https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg?hl=zh-CN>
- Use this extension to open a pdf file
- The website cant be black at all

## Problematic Observation
There is nothing different when i switch on the Dark reader 

## Screenshots

![屏幕捕获_2022_07_24_17_27_11_427](https://user-images.githubusercontent.com/58114293/180640874-2066b7df-9a49-4e3e-8456-81f8ddf45851.png)

## System Information

- OS: Windows 10
- Browser: Chrome 103
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Extensions cannot modify other extensions.
