### ISSUE TITLE
[Broken Website] msk.postupi.online 

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#9411]
# Broken Website Report

## Website Address

https://msk.postupi.online/

## Steps To Reproduce

- Go to https://msk.postupi.online/

## Problematic Observation

Dark Reader does not invert the site.

## Screenshots

<details><summary>Screenshot</summary>

![screenshot-msk-postupi-online-1658773516704](https://user-images.githubusercontent.com/19418601/180847788-a92aec26-8ccd-411b-ade7-28506b7c14b7.png)

</details>

## System Information

- OS: macOS
- Browser: Chrome 103
- Dark Reader Version: 4.9.52

## Additional Context

The problem is relevant for subdomains (for example, `msk.postupi.online`, `spb.postupi.online`, `kazan.postupi.online`), since there is no such problem on the main site https://postupi.online/.

**Comment by Gusted** [comment]
Not able to reproduce. Do you have any other extensions enabled that might conflict?

![image](https://user-images.githubusercontent.com/25481501/181085684-de9f6338-27bd-4562-984e-e23e94d7b126.png)

**Comment by rakleed** [comment]
@Gusted could you try opening https://msk.postupi.online/?

**Comment by Gusted** [comment]
Hmm weird, seems to be redirecting around. Got it "working" eventually. But this is a non-fixable. As per usual with weird sites and their weird prevention mechanism. They are sending "error" pages to CSS requests:

![image](https://user-images.githubusercontent.com/25481501/181091296-4dcc3998-6038-4cda-a173-c509b704553a.png)

Nothing much Dark Reader can do.
