### ISSUE TITLE
[Feature Request] Preserve dark mode in "reader view"

### ISSUE THREAD

**Issue by aranapatona** [darkreader/darkreader#9414]
# Feature Request
Preserve dark mode after selecting "reader view"(firefox) or chrome "reader mode"

## Is this feature request related to a problem?
NO

## Additional Context
Sometimes there are pages that are really bad formatted and the reading mode becomes really helpful specially for tired eyes like mine, if there is a way to preserve reading mode in darkmode that would be useful

**Comment by Gusted** [comment]
Those are separate components from the browsers. Dark Reader cannot control or interact with them. Closing.
