### ISSUE TITLE
[Broken Website] http://opto.utoronto.ca/helmy/

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#9415]
# Broken Website Report

## Website Address

http://opto.utoronto.ca/helmy/

## Problematic Observation

The page isn't dark when dark mode is on.

## Screenshots

![pic-window-220726-1852-39](https://user-images.githubusercontent.com/59497618/180953628-89634c99-d10b-4638-9562-c0c3da8e415a.png)

## System Information

- OS:  Linux
- Browser:  Firefox 102
- Dark Reader Version:  4.9.52

**Comment by Gusted** [comment]
Same underlying problem as #5937
