### ISSUE TITLE
Fails to darken raw.githubusercontent pages

### ISSUE THREAD

**Issue by RoxKilly** [darkreader/darkreader#943]
Navigate to any github project and display a file, then select the "Raw" view. This will take you to the same page on the `raw.githubusercontent.com` domain and that page fails to be darkened.

For example, here is the `.gitignore` file for this project on [github.com](https://github.com/darkreader/darkreader/blob/master/.gitignore)

Here is the same page on [raw.githubusercontent.com](https://raw.githubusercontent.com/darkreader/darkreader/master/.gitignore)

**Comment by alexanderby** [comment]
I see the issue in Firefox, doesn't happen in Chrome.

**Comment by squigglezworth** [comment]
Any updates on this? This is one of the only sites I've come across that Darkreader fails to override :(

**Comment by audip** [comment]
Like @alexanderby said, this doesn't happen on Google Chrome browser
![image](https://user-images.githubusercontent.com/4290846/76254166-39131100-6209-11ea-890b-93297fcc6ec3.png)

**Comment by Gusted** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1654588

**Comment by squigglezworth** [comment]
related: https://bugzilla.mozilla.org/show_bug.cgi?id=1411641

A workaround mentioned (and confirmed) in that bug report is to remove the `sandbox` directive from the `Content-Security-Policy` header on responses from `gist.githubusercontent.com`

Note: I have no idea what other effects this may have, if any.

**Comment by Gusted** [comment]
Yeah we are not going to remove some headers of a site. That's a no go 😅

**Comment by squigglezworth** [comment]
To be clear, I wasn't remotely suggesting that Darkreader try to do that - just relaying the fix for other users of Darkreader who may want it. There are plenty of addons that modify headers, I just didn't want to link to any in particular :)
