### ISSUE TITLE
[Broken Website] Exclude regex101.com

### ISSUE THREAD

**Issue by Myzel394** [darkreader/darkreader#9432]
# Broken Website Report

## Website Address
https://regex101.com

## Steps To Reproduce
- Go to website

## Problematic Observation
This site is already dark

**Comment by Gusted** [comment]
Looks light mode to me.
![image](https://user-images.githubusercontent.com/25481501/181820421-b50f7623-5bbf-4989-b4b5-213dc3dfd150.png)

**Comment by Myzel394** [comment]
Strange, it's dark for more (even in incognito tab):

![image](https://user-images.githubusercontent.com/50424412/181821605-0d325841-6b2e-4283-8b88-dd26bb965f16.png)


Could be because of OS-wide dark mode, should we close this issue then?

**Comment by Gusted** [comment]
> Could be because of OS-wide dark mode

Yeah, I don't have that behavior(at least, browsers don't tend to pick up on my OS settings). Closing

**Comment by Myzel394** [comment]
@Gusted not sure what OS you're using but I also had this problem with several Linux distros in the past. However, Fedora seems to be compatible with such settings, just as a little tip :)

**Comment by Gusted** [comment]
I'm still rocking rolling distro's with currently on Arch Linux 😄. It's what you get when you don't use custom patched packages.
