### ISSUE TITLE
[Broken Website] iconspedia.com

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#9441]
# Broken Website Report

## Website Address
https://www.iconspedia.com

## Steps To Reproduce
- Enable DR dynamic dark mode
- Go to page specified above
- Notice many bright areas and some hard to read text (see attached screenshot)

## Expected Behavior
No large bright areas, everything easy to read

## Actual Behavior
See details in *Steps to Reproduce*

## System Information
- OS: Linux
- Browser: Firefox 103
- Dark Reader Version: 4.9.52

## Screenshot
![_screenshot - www iconspedia com](https://user-images.githubusercontent.com/7672848/182003539-e7a0a405-cd3e-405c-9425-711815f8c530.png)

**Comment by Gusted** [comment]
Even with creating a lot of fixes to the site, it still looks bad. Won't fix.
