### ISSUE TITLE
[Feature Request] Replace with title

### ISSUE THREAD

**Issue by cableghost** [darkreader/darkreader#9457]
# Feature Request
Option to auto refresh page

## Is this feature request related to a problem?
Sort of... On some websites, when Dark Reader is ran, the site colors are not changed until I manually refresh the page. Adding an option to auto refresh the page would be great.

## Screenshots
N/A

## Additional Context
This occurs on many gmail-related PWA's, ie. Chat

**Comment by Gusted** [comment]
Hi @cableghost!

This should be reported as a bug report and not be patched with some feature that is inefficient.

**Comment by cableghost** [comment]
So this is already something that should be occurring? If so, I'll report as big. I may then have missed this in the description.

**Comment by Gusted** [comment]
Yes this already should be happening.
