### ISSUE TITLE
[Feature Request] Automatically Configure Website Appearance in Firefox Settings

### ISSUE THREAD

**Issue by dnut** [darkreader/darkreader#9464]
When dark reader is enabled, the "website appearance" firefox setting should be set to "dark." When disabled, it should be set to "light" or some user selected default.

## Is this feature request related to a problem?
Even when dark reader is enabled:
- Firefox `about:*` pages and mozilla websites are bright white.
- Every time you open a new page, the screen flashes bright white before loading the page.

## Screenshots
![Screenshot from 2022-08-03 08-57-54](https://user-images.githubusercontent.com/15116250/182622843-59d5222b-4cda-4621-8ce4-b569f140d51a.png)

**Comment by Gusted** [comment]
Hi @dnut

Extensions cannot change browser settings like that.
