### ISSUE TITLE
[Broken Website] psyche.co

### ISSUE THREAD

**Issue by RadioRambo** [darkreader/darkreader#9466]
# Broken Website Report

## Website Address
https://psyche.co/

## Problematic Observation
The cards text is unreadable as the contrast ratio is too low.

## System Information

- OS: Linux 
- Browser: Brave
- Dark Reader Version: 4.9.52

## Additional Context
Adjusting the contrast ratio of the card would be perfectly readable.

**Comment by Gusted** [comment]
Fixed by #9372
