### ISSUE TITLE
[Broken Website] php.net/manual

### ISSUE THREAD

**Issue by rakleed** [darkreader/darkreader#9469]
# Broken Website Report

## Website Address

https://www.php.net/manual/en/reserved.variables.environment.php

## Steps To Reproduce

- Go to https://www.php.net/manual/en/reserved.variables.environment.php

## Problematic Observation

Content is not inverted.

## Screenshots

![image](https://user-images.githubusercontent.com/19418601/182930263-d27b23a3-a0ad-4ebe-ba17-65d30b25e69b.png)

## System Information

- OS: macOS
- Browser: Chrome 104
- Dark Reader Version: 4.9.52

**Comment by rakleed** [comment]
The problem is because DarkReader thinks the site is using a dark theme.

**Comment by callaloo** [comment]
It actually works on Brave and Firefox on Windows. So this might be a Chrome/macOS issue.

**Comment by rakleed** [comment]
@callaloo with the "Detect dark theme" option enabled, Dark Reader considers that this site is using a dark theme, including Firefox on macOS and Windows.

**Comment by Gusted** [comment]
Moved this issue to https://github.com/darkreader/darkreader/discussions/9016#discussioncomment-3340916
