### ISSUE TITLE
[Broken Website] Contextual buttons not visible after Gmail redesign

### ISSUE THREAD

**Issue by rpgdev** [darkreader/darkreader#9472]
# Broken Website Report

## Website Address
https://mail.google.com

## Steps To Reproduce

- Go to mail.google.com.
- Click on an email.
- Verify that none of the contextual buttons are visible

## Problematic Observation

The contextual buttons on an email ('mark as unread', 'delete', etc) aren't visible.

## Screenshots

With darkreader disabled
![image](https://user-images.githubusercontent.com/20094474/183113171-8868032c-621a-4ed7-9bac-abf3b2145831.png)

With darkreader enabled
![image](https://user-images.githubusercontent.com/20094474/183113062-f627dc45-8dec-40d2-8833-74278140a673.png)

## System Information

- OS: Fedora Linux 34 KDE 
- Browser: Firefox 100.0.2 (64-bit) 
- Dark Reader Version:  4.9.52 

## Additional Context

There seems to be another gmail issue reported previously but does not appear to be the same as this one. A workaround was provided for that one and it didn't fix my issues.

**Comment by alexanderby** [comment]
Hi, it's already fixed, but the fixed will arrive next week. Currently I suggest you to use Filter mode for Gmail.
https://github.com/darkreader/darkreader/issues/9419
