### ISSUE TITLE
new Gmail action menu not palette swapped

### ISSUE THREAD

**Issue by desmondw** [darkreader/darkreader#9473]
# Broken Website Report

## Website Address
https://mail.google.com/

## Steps To Reproduce
- enable new gmail look
- do a hard reload
- check an email
- notice the dynamic menu options above do not palette swap

## Problematic Observation
Dark Reader extension doesn't palette swap dynamic menu bar items when selecting emails, making them invisible

## Screenshots
old gmail:
![image](https://user-images.githubusercontent.com/1052705/183137339-8d58f833-60b2-4864-aa3a-202d73b85143.png)

new gmail:
![image](https://user-images.githubusercontent.com/1052705/183137228-b23a0e9d-7129-469d-907e-8b50ebacd1f9.png)

## System Information
- OS: mac
- Browser: chrome 104.0.5112.79
- Dark Reader Version: 4.9.52

**Comment by alexanderby** [comment]
Hi, it's already fixed, but the fix will arrive next week https://github.com/darkreader/darkreader/issues/9419
