### ISSUE TITLE
[Broken Website] premierrockforum.com - brown/sepia background color

### ISSUE THREAD

**Issue by 07416** [darkreader/darkreader#9483]
# Broken Website Report

## Website Address

https://www.premierrockforum.com/

## Steps To Reproduce

- visit https://www.premierrockforum.com/

## Problematic Observation

The page background is displayed in brown — this can be alleviated to some degree by changing the default Dark Reader BG color option from `#181a1b` to `#000000` (see the screenshots.

## Screenshots

![image](https://user-images.githubusercontent.com/14923168/183283408-ddcd2dd5-1010-4f1c-a890-035a0553827e.png)

![image](https://user-images.githubusercontent.com/14923168/183283350-817e9bf6-3440-410c-84d8-171436b880b0.png)

## System Information

- OS: Fedora 36 (Linux)
- Browser: firefox.x86_64                                   103.0-1.fc36                        
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
The unmodified site already has a light brown background color. This is working as intended.
