### ISSUE TITLE
[Broken Website] bilibili.com - Video player status bar color error

### ISSUE THREAD

**Issue by Redstone1024** [darkreader/darkreader#9485]
# Broken Website Report

## Website Address
https://www.bilibili.com/video/

## Steps To Reproduce
- visit any of the following pages:
- https://www.bilibili.com/video/BV1ea411f7ZL/
- https://www.bilibili.com/video/BV1nG4y1Y7rN/

## Problematic Observation
When using dynamic mode in Dark Reader, the video player's status bar is incorrectly set to white, which does not match the surrounding black background.

## Screenshots
![3OJ(O0~DKYF{C5FNPW4PU T](https://user-images.githubusercontent.com/55239172/183287288-18c31c66-3e65-4787-89d2-afa21cfa139d.png)

## System Information
- OS: Windows 11 Pro 21H2
- Browser: Microsoft Edge 104.0.1293.47
- Dark Reader Version: 4.9.52

## Additional Context
No more.

**Comment by whx1024** [comment]
https://github.com/darkreader/darkreader/pull/9470
