### ISSUE TITLE
[Feature Request] Add option to change color of UI of Dark Reader

### ISSUE THREAD

**Issue by rredford** [darkreader/darkreader#9490]
# Feature Request
Add setting to change color of text on Dark Reader UI.

## Is this feature request related to a problem?

I have problem with contrast of my vision. When contrast is not large enough, I cannot read text. Dark Reader color of very dark teal on black background cannot be read by me when dimmed on "off mode". I can just barely read it when its "on", with strain on my eyes.
Solution is simple, add option to pick whatever color I want for text and buttons.

## Screenshots

https://imgur.com/nk4HXSX.png

**Comment by Gusted** [comment]
Hi @rredford!

Could you try the V5 preview design? 

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.

The colors being used are within the AA range of contrast accordingly to the W3C, so it should be distinctive enough to read the text.

**Comment by rredford** [comment]
That works well. 🙂 thanks
________________________________
