### ISSUE TITLE
[Broken Website] <dialog>: The Dialog element | MDN

### ISSUE THREAD

**Issue by l1yefeng** [darkreader/darkreader#9491]
# Broken Website Report

## Website Address
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#result

## Steps To Reproduce

1. Go to [section _Result_](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#result).
1. Click the button to show the modal dialog.

## Problematic Observation

The background of the dialog under dark mode is white, foreground black.

## Screenshot

![Screenshot 2022-08-08 at 13-00-35  dialog The Dialog element - HTML HyperText Markup Language MDN](https://user-images.githubusercontent.com/16411015/183473208-39046d09-bb89-4ed2-ae0e-a38324790f89.png)

## System Information

- OS: Debian GNU/Linux 11 (bullseye)
- Browser: Firefox 91.12.0esr (64-bit)
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Hi @l1yefeng

Do you have "Change browser theme" enabled?

**Comment by l1yefeng** [comment]
It has been set to "Default". I tried the other option "Custom". Both render the same result.

**Comment by Gusted** [comment]
Hmm strange. It's working for me and it's currently using a system's provided color.

```css
    background-color: Canvas;
```

Guess it will be a patch in Dark Reader.
