### ISSUE TITLE
[Bug] Dark Reader is not aware of BFCache

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#9493]
# Bug Report

## Website Address

Any

## Bug Description

Dark Reader does not properly react to restoration of a site from BFCache.

## Steps To Reproduce

 - open new tab ("start page")
 - navigate to example.com
 - navigate back (to "start page") by clicking "back" button
 - toggle Dark Reader ON/OFF
 - navigate forward to example.com
 - observe that example.com does not match current color scheme

## Expected Behavior

 - example.com matches the ON/OFF state

## Actual Behavior

 - exampe.com has the initial state (from when it was loaded for the first time)

## System Information

- OS: Windows 11
- Browser: Chrome 104 
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Well, IMO this is the correct behavior. It's a cached stated after all, if we would modify such state then we are not respecting the BFCache.

**Comment by bershanskiy** [comment]
We can remember the DR state when page enters BFCache and when page is restored from BFCache check if the state is still the same.

**Comment by Gusted** [comment]
I'd prefer to not mess with BFCache and just leave as-is. It can lead to more problems, I'm not sure how the current situation is but trying to mess with BFCache can and likely will cause that the BFCache gets disabled, which is something we don't want.

**Comment by bershanskiy** [comment]
I can no longer reproduce this. Perhaps, it was a temporary bug with Chrome not firing `visibilitychange` events or something like that. Closing this for now. I'll keep an eye out for this kind of bug and will reopen this ticket in case this bug ever reappears.
