### ISSUE TITLE
[Bug] Wrong darkreader-inline-bgcolor

### ISSUE THREAD

**Issue by FSpark** [darkreader/darkreader#9512]
# Bug Report

## Website Address
https://tiddlywiki.com/

## Bug Description
When editing a new entry, the background color of the edit text box is wrong.

![ShareX_4Xv9ZeAWPK](https://user-images.githubusercontent.com/20501721/183847481-6b445f84-52e8-43f8-a6ab-c6f273984742.png)

Note: TiddlyWiki is a web program that has been deployed by many people on many sites, so this problem occurs on more than just this one site.

And it was running fine in the previous version (4.9.52), so it is suspected that this is a bug introduced in the new version that is universal.

## Steps To Reproduce
- Go to https://tiddlywiki.com/
- Create a Tiddler.
![chrome_9C7jv3p9Ix](https://user-images.githubusercontent.com/20501721/183846128-38d9252c-b2c9-4aa1-8afb-f8520f4f397a.png)
- Observe its color.
![chrome_T7maiDkLgf](https://user-images.githubusercontent.com/20501721/183846182-53defaf4-22ed-422e-a343-152f2dfe76c2.png)

## System Information

- OS: Windows
- Browser: Chrome 104, Firefox 104
- Dark Reader Version: Only 4.9.53

**Comment by FSpark** [comment]
@Gusted  Sadly, still reproducible on Edge and Chrome in latest 4.9.56.

**Comment by Gusted** [comment]
Seems like chromium had some differences, #9638 fixes it.
