### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by desmondw** [darkreader/darkreader#9513]
# Broken Website Report

## Website Address
https://calendar.google.com/calendar/u/0/r/week

## Steps To Reproduce
- go to gcal
- under settings check "Reduce the brightness of past events"

## Problematic Observation
Either colors on gmail have changed, or darkreader made an update that affected them. Either way I woke up to my gcal unusable with DarkReader.

All events now have a brighter background with DarkReader, making them even harder to read with white text. If you have reduced brightness on past events, DarkReader makes them even MORE faded, making them nigh impossible to read.

## Screenshots
without:
![image](https://user-images.githubusercontent.com/1052705/183928212-d6620dae-2072-4777-b6e7-6b3b7e476c4c.png)

with:
![image](https://user-images.githubusercontent.com/1052705/183928293-7fa03c7d-2bc5-4c9c-a1dd-2391fb2486be.png)

## System Information
- OS: mac
- Browser: chrome 104.0.5112.79
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Please check https://github.com/darkreader/darkreader#site-fixes in order to receive the fix.
