### ISSUE TITLE
[Bug] Seeping into Opera sidebar

### ISSUE THREAD

**Issue by noxan-dev** [darkreader/darkreader#9514]
# Bug Report

## Bug Description
When enabled, the sidebar on Opera gets darkmode

## Steps To Reproduce
Enable new version of darkreader on Opera
Check sidebar

## Expected Behavior
The sidebar should not have dark mode

## Actual Behavior
The dark mode seems to be seeping into the sidebar, making it hard to see the buttons or text

## Screenshots
![image](https://user-images.githubusercontent.com/59417659/183928068-56c39744-1146-470a-bb78-51a85fa037ef.png)

## System Information

- OS: Windows 10
- Browser: Opera 89.0.4447.83
- Dark Reader Version: 4.9.54

## Additional Context
I switched to 4.9.52, and it fixes the issue. Happens in 4.9.53 as well

**Comment by jenda69** [comment]
I have the same issue on Vivaldi side bar. It was happening a year ago #6842 and was fixed.

**Comment by Gusted** [comment]
This will be fixed in the next version of Dark Reader, which will be released soon.
