### ISSUE TITLE
[Broken Website] farfetch.com

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [darkreader/darkreader#9517]
# Broken Website Report

## Website Address
"https://www.farfetch.com/uk/shopping/men/1017-alyx-9sm-zipped-ribbed-knit-cardigan-item-17116355.aspx?v=a163a09b-cb32-4b69-8488-d00b8dd5f348".

## Steps To Reproduce
1. Enable Dark Reader.
2. Visit "https://www.farfetch.com/uk/shopping/men/1017-alyx-9sm-zipped-ribbed-knit-cardigan-item-17116355.aspx?v=a163a09b-cb32-4b69-8488-d00b8dd5f348".

## Problematic Observation
[The website](https://www.farfetch.com/uk/shopping/men/1017-alyx-9sm-zipped-ribbed-knit-cardigan-item-17116355.aspx?v=a163a09b-cb32-4b69-8488-d00b8dd5f348) becomes what ![this](https://user-images.githubusercontent.com/42837531/183911327-e6caacfb-38dc-4659-a68e-df7387491b7c.png) depicts, which is basically the website but devoid of pictography and CSS. (At least Dark Reader applies correct colouration to it.)

## Screenshots
![This](https://user-images.githubusercontent.com/42837531/183911429-33937271-4de4-424e-a2f1-4f589366b409.png) depicts what the website appears as without Dark Reader enabled.
![This](https://user-images.githubusercontent.com/42837531/183930872-d407b382-77e4-43dc-b0e9-a30adf35d009.png) depicts what the website should be presented as by Dark Reader. This is possible to present if the extension is disabled for the website, then the website is loaded as what [the previous](https://user-images.githubusercontent.com/42837531/183911429-33937271-4de4-424e-a2f1-4f589366b409.png) picture demonstrates.

## System Information
- OS: [Linux](cpe:/o:fedoraproject:fedora:36)
- Browser: [Firefox](file:///usr/bin/firefox) 103.1
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
The site is trying to access/modify a element of Dark Reader. The browser will raise an error about this(as the browser doesn't allow this), Dark Reader cannot prevent this behavior. Can't fix.

![image](https://user-images.githubusercontent.com/25481501/184060574-2e1c50cc-a2be-4217-ae1c-146ffec6f154.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Gusted, are you able to provide a description of the problem for me to forward to them that is verbose enough that they should be able to remediate it, or is sending a link to this already enough?

**Comment by Gusted** [comment]
Any engineer would be able to understand this(feel free to link this issue):

So the site is trying to remove an element, inserted by Dark Reader, however they are likely trying to target another element. So for the technical under us, a simple `try { ... } catch { ... }` should do for this code or a specific Dark Reader check(not nice as iat's not generic).
