### ISSUE TITLE
[Broken Website] Google Calendar

### ISSUE THREAD

**Issue by desmondw** [darkreader/darkreader#9527]
# Broken Website Report

## Website Address
https://calendar.google.com/calendar/u/0/r/week

## Steps To Reproduce
- go to gcal
- under settings check "Reduce the brightness of past events"

## Problematic Observation
Either colors on gmail have changed, or darkreader made an update that affected them. Either way I woke up to my gcal unusable with DarkReader.

All events now have a brighter background with DarkReader, making them even harder to read with white text. If you have reduced brightness on past events, DarkReader makes them even MORE faded, making them nigh impossible to read.

## Screenshots
without:
![image](https://user-images.githubusercontent.com/1052705/183928212-d6620dae-2072-4777-b6e7-6b3b7e476c4c.png)

with:
![image](https://user-images.githubusercontent.com/1052705/183928293-7fa03c7d-2bc5-4c9c-a1dd-2391fb2486be.png)

## System Information
- OS: mac
- Browser: chrome 104.0.5112.79
- Dark Reader Version: 4.9.52

## Additional Context
My [previous issue](https://github.com/darkreader/darkreader/issues/9513) was closed with a comment. I implemented the comment and was unable to see a difference, even after hard refreshing and restarting Chrome. I checked the settings for a manual sync button, but did not see any and so am not sure if it has synced.

**Comment by desmondw** [comment]
My [previous issue](https://github.com/darkreader/darkreader/issues/9513) was closed with a comment. I implemented the comment and was unable to see a difference, even after hard refreshing and restarting Chrome. I checked the settings for a manual sync button, but did not see any and so am not sure if it has synced.

**Comment by AKasera** [comment]
I am also having this issue. Thought I was going crazy for a second. Restarted computer. Refreshed Opera. Thought maybe Opera was screwing up. Tried on Chrome. Tried on Brave. Tried on Vivaldi. Tried on Opera GX. All have the same issue. Please fix thank you.

**Comment by grandslammer** [comment]
I'm having the same issue. Been using Dark Reader with Google Calendar for a while, but the issue only started happening today. Only seems to be affecting finished events, regardless of event colour.
Must have been some sort of update causing it, either with Dark Reader or Google!

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/9529 has been merged to improve the issue. Please check [this section](https://github.com/darkreader/darkreader#site-fixes) to receive this fix.

**Comment by desmondw** [comment]
I think it is behaving even worse now:

![image](https://user-images.githubusercontent.com/1052705/184026520-8a243ff5-c91b-43d9-b020-4d3593948898.png)

**Comment by evanwon** [comment]
Synchronizing site fixes fixed the font readability for me -- I was originally seeing the same white text on light background as the other folks above, but now the text is black.

Screenshot below; you can see past events on the left two events, and future events on the rightmost event.

I don't recall exactly what it looked like previously, but I do think there are still some minor changes from what it used to look like. (I don't recall the background being this bright of a blue - it was darker or more transparent or something which helped convey that events in the past were in the past). But, it's visible now at least, so big improvement. Thanks!


![image](https://user-images.githubusercontent.com/972799/184045237-49ef3c5b-56c1-446e-946c-5f07f7eb9b26.png)

**Comment by evanwon** [comment]
Ah good I was able to pull a screenshot from my mac illustrating the previous appearance (you can compare this with the one above -- you can see that in the previous experience, events in the past appeared darker and more faded.

![image](https://user-images.githubusercontent.com/972799/184047634-cbb3f2f5-babb-4890-8f72-988fbab4f296.png)

cc @alexanderby as FYI since I saw your related commits in https://github.com/darkreader/darkreader/pull/9529/commits

**Comment by desmondw** [comment]
I ended up just exporting my settings, removing the extension, re-installing the extension, and importing my settings. Everything looks fine after that.

![image](https://user-images.githubusercontent.com/1052705/184137241-a477fda3-aab0-41b7-9282-baeea3dfcb1f.png)

I imagine there is a problem with the auto-sync.

**Comment by angelobonet** [comment]
> Synchronizing site fixes fixed the font readability for me -- I was originally seeing the same white text on light background as the other folks above, but now the text is black.
> 
> Screenshot below; you can see past events on the left two events, and future events on the rightmost event.
> 
> I don't recall exactly what it looked like previously, but I do think there are still some minor changes from what it used to look like. (I don't recall the background being this bright of a blue - it was darker or more transparent or something which helped convey that events in the past were in the past). But, it's visible now at least, so big improvement. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/972799/184045237-49ef3c5b-56c1-446e-946c-5f07f7eb9b26.png)

Although past events are now legible, notice that future events have been affected -- and are now a combination of black and white text (vs just white text prior to the "fix")

**Comment by Gusted** [comment]
@angelobonet, if you open the devtools:

- Open Dark Reader popup.
- Click on "Dev Tools"(if that isn't there, click on "Settings" button first)
- `ctrl + f` and find the fix for `calendar.google.com`
- Remove the whole section, so it will become like this:
![image](https://user-images.githubusercontent.com/25481501/184180880-ba1fd439-1c0e-43b3-800f-e5ed1440b377.png)
- Click on "Apply".

Does that resolve the issue? I have a slight feeling that some existing fixes actually broke this.

**Comment by angelobonet** [comment]
> @angelobonet, if you open the devtools:
> 
>     * Open Dark Reader popup.
> 
>     * Click on "Dev Tools"(if that isn't there, click on "Settings" button first)
> 
>     * `ctrl + f` and find the fix for `calendar.google.com`
> 
>     * Remove the whole section, so it will become like this:
>       ![image](https://user-images.githubusercontent.com/25481501/184180880-ba1fd439-1c0e-43b3-800f-e5ed1440b377.png)
> 
>     * Click on "Apply".
> 
> 
> Does that resolve the issue? I have a slight feeling that some existing fixes actually broke this.

Yes, I think that restores it back to the expected look.  My past and future events both appear "good" again.

**Comment by evanwon** [comment]
@Gusted 100% -- removing the fixes for calendar.google.com reverted it back to its former (and better) appearance.

Here's a screenshot after removing the calendar.google.com CSS fixes: 

![image](https://user-images.githubusercontent.com/972799/184193475-34f77011-d515-4b79-826f-ebe3eaa7c318.png)

**Comment by desmondw** [comment]
I've got a fix that just removes the offending code but I can't figure out how to push a branch to the repo to open a PR. I'm getting block on access, but nothing in the repo suggests you need special privileges to push branches.

**Comment by Gusted** [comment]
Please take a look at https://github.com/darkreader/darkreader#site-fixes to fetch the latest fixes. (You might need to use "Reset changes" in Dark Reader devtools to force a sync)

**Comment by evanwon** [comment]
Nice -- thanks and kudos @desmondw @Gusted!
