### ISSUE TITLE
[Bug] Dark Reader & GitHub Markdown Viewer add-on don't play together.

### ISSUE THREAD

**Issue by SirWumpus** [darkreader/darkreader#9537]
# Bug Report

## Bug Description

* Firefox 103.0.2 
* Add-On - "GitHub Markdown Viewer" https://github.com/painyeph/GitLabMarkdownViewer

Viewing Markdown files (local or online does not appear to be an issue) that are processed by the "GitHub Markdown Viewer" remain black text  on white background with only the four margins (top, bottom, left, right) around the body being inverted.

In comparison using a different (older?) add-on "Markdown Viewer Webext" https://github.com/KeithLRobertson/markdown-viewer, the page is successfully inverted.   

This issue has been around for a couple of years and only now did I finally notice it was an issue related to which add-on viewer was currently in use (sometimes I flip for comparisons).  I'd prefer to use the GitHub viewer since most of my markdown is destined to appear on GitHub and the other viewer is not as complete.

## Steps To Reproduce

* Using Firefox, install Dark Reader and "GitHub Markdown Viewer" add-ons.
* View a markdown file within Firefox.

## Expected Behavior

Have the entire page body inverted (dark).

## Actual Behavior

The page body remains black text on white background with only the four margins (top, bottom, left, right) around the body being inverted.

## System Information

* Windows 10
* Firefox 103.0.2 
* Add-On "GitHub Markdown Viewer" https://github.com/painyeph/GitLabMarkdownViewer
* Add-On "Dark Reader"

**Comment by Gusted** [comment]
Do you have an example markdown page?

**Comment by SirWumpus** [comment]
I've tested against several README.md from my repositories (either offline or online).  All the same behaviour.  So any markdown should demonstrate this.  Here's a short one from my personal web site, not in a repo, you can find online http://www.snert.com/resume/elite_dangerous.md, same behaviour.

**Comment by Gusted** [comment]
Not sure what should happen, but it's just downloading the file when navigating to it.

**Comment by SirWumpus** [comment]
Do you have the add-on "GitHub Markdown Viewer" installed along side Dark Reader in Firefox?  For me it downloads, then displays.  Alternatively once you have the downloaded file, drag & drop into Firefox.  You need both add-ons to see the effect.

**Comment by SirWumpus** [comment]
Typically I edit with TextPad and it has a button to send a file for viewing in the browser.  Drag & drop or a file:// URL to the .md file in the address bar should do the same thing, provided you have the two add-ons.

**Comment by Gusted** [comment]
Seems like I had to do some configuration stuff: https://github.com/painyeph/GitLabMarkdownViewer/issues/18

Looking at the rendered markdown page, it's clear that the CSS is loaded from the addon, which is a problem as other addons(Like Dark Reader) aren't allowed to load/fetch such resources from other addons. Closing as can't fix.

![image](https://user-images.githubusercontent.com/25481501/184189481-94013054-5554-412e-962d-a6f5b4104840.png)
