### ISSUE TITLE
[Bug] "Change browser theme" does not work with automation

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9538]
# Bug Report

## Bug Description
"Change browser theme" works correctly when the Light or Dark theme is selected explicitly. However, when using automation, only the dark browser theme is used.

## Steps To Reproduce
- Enable automation ("Toggle dark/light")
- Enable "Change browser theme"

## Expected Behavior
Light browser theme when in light mode, dark browser theme when in dark mode.

## Actual Behavior
Dark browser theme for both light and dark modes with automation enabled.

## Screenshots
Light mode
<img width="1612" alt="Screen Shot 2022-08-11 at 10 12 49 AM" src="https://user-images.githubusercontent.com/11276349/184193696-b2af8f27-e274-4c89-8b8b-28bb726ea204.png">

Dark mode
<img width="1612" alt="Screen Shot 2022-08-11 at 10 13 05 AM" src="https://user-images.githubusercontent.com/11276349/184193731-60f8895b-d702-45a3-a186-3594dc9907a3.png">

Light mode (with automation)
<img width="1612" alt="Screen Shot 2022-08-11 at 10 13 13 AM" src="https://user-images.githubusercontent.com/11276349/184193751-0e37e630-1e8c-4c1f-a1dc-bef518a8ae04.png">

## System Information
- OS: macOS
- Browser: Firefox 103.02
- Dark Reader Version: 4.9.55

**Comment by MahdiNazemi** [comment]
When I manually change the system color scheme to Light or Dark, the browser's theme remains in Light mode.

<img width="1215" alt="Screen Shot 2022-08-18 at 1 02 14 PM" src="https://user-images.githubusercontent.com/11276349/185484380-f1e473cc-2ed2-4645-be4a-808e95e7f30f.png">
<img width="1215" alt="Screen Shot 2022-08-18 at 1 02 34 PM" src="https://user-images.githubusercontent.com/11276349/185484420-0a26c5cb-4c24-490d-80f8-641ca72e6abf.png">

**Comment by MahdiNazemi** [comment]
@Gusted, would you please reopen this issue? I believe it is still not fixed based on the screenshots in [this comment](https://github.com/darkreader/darkreader/issues/9538#issuecomment-1219904486)

**Comment by Gusted** [comment]
I'm not able to reproduce the issue anymore. Are you sure you are on the latest version?
