### ISSUE TITLE
[Bug] Opening each new tab in Firefox reloads Dark Reader on all open tabs

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9540]
# Bug Report

## Bug Description
Opening each new tab in Firefox reloads Dark Reader on all open tabs.

**Update 1:**
Navigating inside open tabs causes the same behavior.

**Update 2:**
This only happens when automation is enabled, not if Dark Reader is set to On all the time.

## Steps To Reproduce
- Open a new tab and navigate to a website.
- Go to any open tab and observe Dark Reader reapplying its changes.

## Expected Behavior
Dark Reader should be loaded only once on each page.

## Actual Behavior
Dark Reader repeatedly loads on open tabs.

## System Information
- OS: macOS
- Browser: Firefox 103.0.2
- Dark Reader Version: 4.9.55

## Additional Context
Possibly related to #9336

**Comment by MahdiNazemi** [comment]
Could it be related to #9336?

**Comment by MahdiNazemi** [comment]
This happens every few minutes even if no new tabs are opened.

**Comment by Gusted** [comment]
Firefox is likely unloading your tabs(and thus also dark reader on that tab). https://support.mozilla.org/en-US/kb/unload-inactive-tabs-save-system-memory-firefox

**Comment by Gusted** [comment]
Also see https://github.com/darkreader/darkreader/discussions/8864

**Comment by MahdiNazemi** [comment]
@Gusted, thank you for your explanation. I did not know about `browser.tabs.unloadOnLowMemory`. Setting this config to `false` resolves the issue.
However, leaving the setting to `true` and changing Dark Reader from "Auto" to "On" also resolves the issue. I am not quite sure if the two are somehow related.

**Comment by Gusted** [comment]
As far as I'm concerned, Firefox is providing this functionality, if there's a bug it should be taken up with Mozilla engineers. Maybe it has to do with #9542 that there's some bug within the "auto" code that is causing this to be more "aggressive".

**Comment by MahdiNazemi** [comment]
You have a valid point.
Downgrading to 4.9.52 resolves the issue regardless of whether `browser.tabs.unloadOnLowMemory` is set to `true` or `false`.

**Comment by Gusted** [comment]
Hmm, okay that's weird. Are you able to `git bisect` this, to an exact commit? So I have some pointers where to look.

**Comment by Gusted** [comment]
Also I'm pretty sure that commit also causes https://github.com/darkreader/darkreader/issues/9542

**Comment by MahdiNazemi** [comment]
Sure, a lot of new things I learned today, including `git bisect` 😄
I will set up a development environment and share a few pointers later today.

It could also resolve #9541.

**Comment by MahdiNazemi** [comment]
@Gusted, #9526 is the culprit for #9542. To test #9540 and #9541, I need to install Firefox Developer because my local build is not signed.

**Comment by bershanskiy** [comment]
@MahdiNazemi Thanks for details, I will investigate over the weekend. #9526 might be causing Dark Reader on Firefox to re-evaluate ON/OFF status too frequently and attempt to notify tabs (waking them from sleep if they were offloaded). I know of a few possible places to filter this information and prevent unnecessary wakeups of background tabs.

**Comment by MahdiNazemi** [comment]
Fixed by #9554.
