### ISSUE TITLE
[Bug] Dark Reader slows down switching between tabs

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9541]
# Bug Report

## Bug Description
When switching to a loaded tab where Dark Reader modifications are applied, one has to wait for about a second before they can switch to another tab. It looks like Dark Reader performs some (unnecessary?) computations every time the focus changes to a tab.
Given that this issue happens on an M1 Mac, I suspect it is not related to the machine being slow or having inadequate resources.

## Steps To Reproduce
- Open [mail.google.com](mail.google.com) and allow Dark Reader to apply the color scheme.
- Open [outlook.office.com](outlook.office.com) and allow Dark Reader to apply the color scheme.
- Go to Gmail again.
- Click on the Outlook tab.
- It takes about one second for the focus to change to the Outlook tab.
- Turn off Dark Reader and repeat the same steps. Opening the second tab happens instantaneously.

## Expected Behavior
Dark Reader should not perform any additional computations on rendered pages.

## System Information
- OS: macOS
- Browser: Firefox 103.0.2
- Dark Reader Version: 4.9.55

**Comment by MahdiNazemi** [comment]
After profiling with the Firefox Profiler, I see the following calls in the call graph:

documentVisibilityListener -> runDynamicStyle -> createDynamicStyleOverrides -> ...

**Comment by Gusted** [comment]
There's a performance issue template. Please use that next time. Could you share the profiler link? Just the call graph isn't much worth for debugging as it's again not reproducible, but I assume for now that this is the same "bug" as https://github.com/darkreader/darkreader/issues/9540#issuecomment-1213036985 whereby the tab is practically not loaded.

**Comment by MahdiNazemi** [comment]
@Gusted, I set `browser.tabs.unloadOnLowMemory` to `false` but was still experiencing the issue. Please find the profile attached.
[Firefox 2022-08-12 09.51 profile.json.gz](https://github.com/darkreader/darkreader/files/9328670/Firefox.2022-08-12.09.51.profile.json.gz)
Please let me know when you download the attachment so I can remove it afterward.

**Comment by MahdiNazemi** [comment]
Downgrading to 4.9.52 resolves the issue regardless of whether `browser.tabs.unloadOnLowMemory` is set to `true` or `false`.

**Comment by MahdiNazemi** [comment]
Fixed by #9554.
