### ISSUE TITLE
[Broken Website] majorgeeks.com

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#9550]
# Broken Website Report

## Website Address
https://www.majorgeeks.com/

## Steps To Reproduce
1. Enable `Detect dark theme` in DR settings
2. Open https://www.majorgeeks.com/
3. DR will report that `Dark theme detected on site`. This is false.

## Screenshots
![20220812-1660319701](https://user-images.githubusercontent.com/9846948/184395177-48b5b8e8-6a56-4252-94dd-a9c97ea8516d.png)

## System Information

- OS: Windows 11 21H2 22000.x
- Browser: Edge 104.0.1293.54
- Dark Reader Version: : 4.9.55

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016
