### ISSUE TITLE
[Broken Website] bpt.akarisoftware.com - Can't enable dark mode

### ISSUE THREAD

**Issue by ExTBH** [darkreader/darkreader#9553]
# Broken Website Report

## Website Address

https://bpt.akarisoftware.com

## Steps To Reproduce

- Go to https://bpt.akarisoftware.com
- Click Dark Reader Icon
- Try to enable for current site

## Problematic Observation

When trying to enable Dark mode for the above site nothing happens, the button doesn't do anything

## System Information

- OS: Linux Mint 20.3 x86_64
- Browser: Firefox for Mint 103.0.1 (64-bit)
- Dark Reader Version: 4.9.55

**Comment by Gusted** [comment]
Hi @ExTBH,

Do you happen to have akarisoftware.com in your sitelist?

**Comment by ExTBH** [comment]
somehow i fixed it dunno how, went to main domain https://akarisoftware.com, enabled dark mode and disabled it, deleted it from sitelist, went to subdomain and dark mode just worked, Thanks!
