### ISSUE TITLE
[Bug] Dark Reader affects SVGs and stays enabled on websites already in darkmode

### ISSUE THREAD

**Issue by AnatoleAM** [darkreader/darkreader#9565]
# Bug Report

## Website Address
https://next.7tv.app or https://next.7tv.dev

## Bug Description
The extension, for some reason, affects vectors, which gives them broken colors. It also just runs on websites that are already in dark mode which does not make sense. 

## Steps To Reproduce
- Go to https://next.7tv.dev/subscribe
- Note how the site is already in dark mode, but with default settings the extension turns on anyway.
- See how the vectors (under Collection section) change in color

## Expected Behavior
Dark Reader doesn't affect websites in dark mode, or provides a way to force the extension off.

## Actual Behavior
Dark Reader is active on websites already in dark mode and breaks various elements

#### Correct (dark reader off)
![image](https://user-images.githubusercontent.com/9599344/184540723-72af7d85-6b16-4334-bc76-ac6e9e78ec68.png)
#### Broken (dark reader on)
![image](https://user-images.githubusercontent.com/9599344/184540671-19f5657f-00fa-4373-8113-1286da216f64.png)

## System Information
Chrome 105.0.5195.10 dev
Dark Reader 4.9.55 

- OS: Linux
- Browser: Chrome 100
- Dark Reader Version: 

## Additional Context
This issue is mainly reported by users of my site, I've only tested it briefly. While this extension is nice to avoid flashbangs, it seems odd that there's no easy way for website devs to force it off. And it should most certainly never turn on for websites that are already in dark mode.

If there is a way to instruct the extension to turn off please let me know. I shouldn't have to tell people to remove this extension, as I think it's pretty good, but it creates misleading scenarios where users are seeing something completely different than what is intended by the web developer.

**Comment by AnatoleAM** [comment]
Found a trick that forces the extension off. It would still be nice to have a non-hacky way though. Or at least add detection for dark-mode sites + not modify vector images.

**Comment by Gusted** [comment]
Or at least add detection for dark-mode sites
 
 Please check https://github.com/darkreader/darkreader/discussions/9016
