### ISSUE TITLE
Cannot darken webapps.stackexchange.com

### ISSUE THREAD

**Issue by orschiro** [darkreader/darkreader#957]
Dear all,

Can please someone test to darken the following page:

https://webapps.stackexchange.com/questions/70595/how-can-i-make-my-github-wiki-crawlable-by-search-engines-robots-txt-seems-to-f

Much appreciated. 

Yours

**Comment by alexanderby** [comment]
Looks well for me
<img width="1275" alt="screen shot 2019-01-03 at 19 34 43" src="https://user-images.githubusercontent.com/9638588/50649342-a9cbf700-0f8e-11e9-939c-3c5749f4dd12.png">

**Comment by orschiro** [comment]
Thanks @alexanderby!

Let's close as invalid then.

Some weird issue on my side.
