### ISSUE TITLE
[Feature Request] Auto enable/disable Dark Reader

### ISSUE THREAD

**Issue by thedoctar** [darkreader/darkreader#9572]
Love this app. It would be even better if it could automatically turn itself on and off depending on the time. You can do this for Firefox's theme already (see https://addons.mozilla.org/en-US/firefox/addon/automatic-dark/). You can probably look at their code to view their implementation, shouldn't be too hard. A simple first version would be to check the time on start-up only, and choose the theme based on the system time.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I disagree, because I believe that this is best achieved by the system changing the theme at a designated time (which iOS, Android, Windows 11, and macOS are able to) and configuring Firefox to adhere to that preference.

**Comment by Gusted** [comment]
This is already a feature:

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Go to 'Automation' under `Settings`.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@thedoctar, this feature should be available for Android 9 and above. However, a separate application I expect is a decent alternative.

**Comment by thedoctar** [comment]
> This is already a feature:
> 
>     * Click Dark Reader icon.
> 
>     * Click Dev tools (in the bottom-right corner).
> 
>     * Click Preview new design.
> 
>     * Go to 'Automation' under `Settings`.

Thanks! I hope this can become default in the future.

> @thedoctar, this feature should be available for Android 9 and above. However, a separate application I expect is a decent alternative.

Maybe it's disabled on my Fairphone, which also doesn't wake while off and I set an alarm.
