### ISSUE TITLE
[Broken Website] Wikipedia -- logo does not invert correctly

### ISSUE THREAD

**Issue by rlacobelle20** [darkreader/darkreader#9577]
# Broken Website Report  Wikipedia -- logo does not invert correctly

## Website Address

https://en.wikipedia.org/wiki/Library_Genesis

## Steps To Reproduce

- go to https://en.wikipedia.org/wiki/Library_Genesis
- turn on darkreader

## Problematic Observation

The logo at the top eft of the page becomes inverted.

## System Information

![image](https://user-images.githubusercontent.com/44063772/184806896-d659d9b9-91b9-4a6a-b779-58c6532e6a55.png)

- OS:  Windows 10
- Browser:  Google Chrome
- Dark Reader Version:  4.9.55

**Comment by Gusted** [comment]
This is intended behavior, see #9257
