### ISSUE TITLE
addons.mozilla.org: extension versions 4.7.3+ aren't showing up

### ISSUE THREAD

**Issue by joshsleeper** [darkreader/darkreader#958]
https://addons.mozilla.org/en-US/firefox/addon/darkreader/

Website shows latest version as `4.7.2`, when `4.7.3` and `4.7.4` have supposedly shipped according to this repo

![image](https://user-images.githubusercontent.com/849941/50523994-3b27fe80-0aa1-11e9-9726-e8f442525e7f.png)

**Comment by alexanderby** [comment]
Version 4.7.3 had a critical fix for Chrome, version 4.7.4 fixed a bug introduced in 4.7.3. So I decided to not publish it for Firefox.

**Comment by joshsleeper** [comment]
Ah, good to know!
Thanks for clearing that up.
