### ISSUE TITLE
[Bug] System color scheme does not work on Firefox

### ISSUE THREAD

**Issue by takecare** [darkreader/darkreader#9582]
# Bug Report

## Bug Description

Extension never activates dark mode when `Automation` is set to `Use system color scheme`. It works fine with the other 2 automation modes.

## Steps To Reproduce

- On any website (e.g. mozilla.org)
- Activate "Use system color scheme"
- Make sure your system's theme is in dark mode
- Observe as no dark mode is applied

## Expected Behavior

- The extension's dark mode is applied

## Actual Behavior

- The extension's dark mode is not applied

## Screenshots

| 1 | 2 | 3 |
| - | - | - |
| <img width="1440" alt="1" src="https://user-images.githubusercontent.com/212528/184984665-9c029b35-04fe-47fd-a99e-7a22bd35b941.png"> | <img width="1440" alt="2" src="https://user-images.githubusercontent.com/212528/184984716-566d9dcb-989a-4883-95a6-77e143a2d878.png"> | <img width="1440" alt="3" src="https://user-images.githubusercontent.com/212528/184984784-9b3f2352-e1f9-49fc-b291-fcc7360022ca.png"> |

## System Information

- OS: macOS 12.5
- Browser: Firefox Dev 104.0b9
- Dark Reader Version: 4.9.55

**Comment by MahdiNazemi** [comment]
This is only happening on the newest version, i.e. 4.9.56.

**Comment by MahdiNazemi** [comment]
In my case, setting Dark Reader to always "On" also causes issues in the color scheme.

Issue and steps to reproduce:
1. Set Dark Reader to "On" and "Scheme" to "Dark"
2. Click on a link in the page
3. Dark Reader reset to Light mode.

**Comment by adql** [comment]
Probably related and very recent: #9533

**Comment by MahdiNazemi** [comment]
I ran `git bisect` twice last night but could not find the commit that caused this issue. Although I should mention that I was using Firefox in `about:debugging` mode and only reloaded the extension every time I compiled a new version.

**Comment by Gusted** [comment]
Seems to be another MacOS bug.
@MahdiNazemi could you compile dark reader with the `--log-info` & `--log-warn` arguments (https://github.com/darkreader/darkreader/pull/9564)? And send a copy of the output file, while enabling/disabling/changing the dark reader automation settings as well as the OS's dark mode.

CC @bershanskiy

**Comment by bershanskiy** [comment]
@takecare and @MahdiNazemi What reproduction steps are you using? I do not have a Mac, but I can try to reproduce this issue on Windows.

**Comment by bershanskiy** [comment]
If you have Mac device and 5 minutes of time, please test the following:
 - open https://example.com and Firefox extension background page and in each console run this:
   > matchMedia('(prefers-color-scheme: dark)').addEventListener("change", ({matches}) => console.log(matches))
 - change system color scheme a few times
 - observe whether consoles print `true` and `false`

If https://example.com prints stuff but extension background does not, I have a guess what's going on and will try to make a patch today or tomorrow.

**Comment by takecare** [comment]
@bershanskiy it works in the extension's console only.

| Extension | example.com |
| - | - |
| <img width="931" alt="ext" src="https://user-images.githubusercontent.com/212528/185345847-b0ba6c51-1637-47fa-9ba4-63ea5a91ad77.png"> | <img width="931" alt="site" src="https://user-images.githubusercontent.com/212528/185345892-cc0d28d9-512c-4894-83e0-dd7afbff079a.png"> |

**Comment by MahdiNazemi** [comment]
> Seems to be another MacOS bug. @MahdiNazemi could you compile dark reader with the `--log-info` & `--log-warn` arguments (#9564)? And send a copy of the output file, while enabling/disabling/changing the dark reader automation settings as well as the OS's dark mode.
> 
> CC @bershanskiy

Sure, should I just run the following?

```bash
npm run debug:watch --log-info --log-warn
```

I did that and loaded the extension in `about:debugging` in Firefox but did not get any log files nor saw any logs in the console.

**Comment by MahdiNazemi** [comment]
> If you have Mac device and 5 minutes of time, please test the following:
> 
>     * open https://example.com and Firefox extension background page and in each console run this:
>       > matchMedia('(prefers-color-scheme: dark)').addEventListener("change", ({matches}) => console.log(matches))
> 
>     * change system color scheme a few times
> 
>     * observe whether consoles print `true` and `false`
> 
> 
> If https://example.com prints stuff but extension background does not, I have a guess what's going on and will try to make a patch today or tomorrow.

@bershanskiy 
Here is the output I get in about:debugging -> This Firefox -> Dark Reader -> Inspect -> Console
<img width="1215" alt="Screen Shot 2022-08-18 at 1 15 03 PM" src="https://user-images.githubusercontent.com/11276349/185486669-78ae09e9-5642-4c49-b6f7-c6a8065439fd.png">

And here is the output I get on example.com
<img width="1215" alt="Screen Shot 2022-08-18 at 1 14 55 PM" src="https://user-images.githubusercontent.com/11276349/185486825-22c75bef-3811-4d7e-a723-e6e12bf48599.png">

If I open five tabs and enter the same command in all consoles, I get the same `true` and `false` events in all of them.

**Comment by MahdiNazemi** [comment]
I just learned I had to look at the extension's console to get the warning and info messages. Please find attached the stored log file.
[console-export-2022-8-18_13-30-2.txt](https://github.com/darkreader/darkreader/files/9377462/console-export-2022-8-18_13-30-2.txt)

Here is what I did to generate the log:
1. Start with the extension turned off.
2. Turn on the extension in Auto (system theme is light)
3. Toggle the system's theme a few times and each time, open all tabs for Dark Reader to apply the color scheme.
4. Turn off Dark Reader.

**Comment by takecare** [comment]
@bershanskiy it was set to light, now set to "system" but the automation still doesn't work. 

as for the tabs, almost all of them got at least 2 of the changes. the 1st one (which was selected at the time) got all of the changes.

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| - | - | - | - | - | - | - | - | - | - |
| <img width="1552" alt="1" src="https://user-images.githubusercontent.com/212528/185489104-1e061056-e1b0-40f7-9380-aa559be851ac.png"> | <img width="1552" alt="2" src="https://user-images.githubusercontent.com/212528/185489148-3266bc00-761c-4ddb-be5c-dad4be2e3124.png"> | <img width="1552" alt="3" src="https://user-images.githubusercontent.com/212528/185489187-3a1d2018-c1b8-414a-8834-3c96f5b3354c.png"> | <img width="1552" alt="4" src="https://user-images.githubusercontent.com/212528/185489212-89acc2f1-5d58-47a7-9ed0-3c2943fd5ff4.png"> | <img width="1552" alt="5" src="https://user-images.githubusercontent.com/212528/185489237-4add96ec-bb6b-4562-8ecc-08aa10e2ec0e.png"> | <img width="1552" alt="6" src="https://user-images.githubusercontent.com/212528/185489264-c5cacdaa-75b5-4d5d-b61f-2a22ae90034d.png"> | <img width="1552" alt="7" src="https://user-images.githubusercontent.com/212528/185489294-b8c098f0-411a-4883-a248-140dcef7c278.png"> | <img width="1552" alt="8" src="https://user-images.githubusercontent.com/212528/185489310-b5387b74-aa8f-4a69-bba7-0bc036362df8.png"> | <img width="1552" alt="9" src="https://user-images.githubusercontent.com/212528/185489335-0dbe81a6-7549-42cc-a7d1-134589fda59f.png"> | <img width="1552" alt="10" src="https://user-images.githubusercontent.com/212528/185489368-4dea9add-14bb-4406-9cdf-0b69a53f8df8.png"> |

**Comment by MahdiNazemi** [comment]
@bershanskiy, is this in any way related to

**Comment by bershanskiy** [comment]
I feel like I owe you the complete story:

On Aug 9, I was testing Dark Reader for an upcoming release and noticed that Chrome was not firing `matchMedia` events in background page. Then I tested Firefox under the same conditions and it was fine, so we released Firefox build, postponed Chrome release. ([Link to developer-only chat](https://discord.com/channels/700258399702482945/700258399702482948/1006585578764116128))
Then I created #9526 which activated color change listeners in all builds (including Chrome MV2 and Firefox). This approach worked well in Chrome MV3 build before, so I expected it to work fine in other builds (and it did in Chrome MV2 build). Firefox did not these extra messages like it (#9540). In #9554, we added filtering for excessive messages on Chrome (as a precaution) and made Firefox ignore them entirely as a fix. We disabled these messages on Firefox because I believed Firefox backgrounds were getting color change messages reliably. (Side note: we have a workaround for a different bug on Firefox which makes initial color scheme inaccurate, but did not prevent change events from firing.)

Possible fix: I believe we can re-enable these messages again for Firefox (hopefully, without triggering #9540 because we filter out excessive messages). I would really appreciate if you could help me test the fix before release. Also, I would appreciate if you could test fix on Google Search video results specifically, [as explained here](https://github.com/darkreader/darkreader/issues/9542#issuecomment-1213773717).

**Comment by bershanskiy** [comment]
@takecare @MahdiNazemi I would appreciate if you could test #9619 which I believe should fix this bug.

**Comment by MahdiNazemi** [comment]
I am currently getting the correct behavior on 4.9.56, so testing it on my machine would not provide meaningful results. I will test #9619 on #9542 and report the results there.

**Comment by bershanskiy** [comment]
Hi, @MahdiNazemi and @takecare I merged #9619 which should fix this bug on Firefox (it applies the same workaround we use on Chrome to deal with identical Chrome bug). I would appreciate if you could test the extension some time soon, but this is not essential.

**Comment by MahdiNazemi** [comment]
@bershanskiy, this issue was somehow fixed automatically for me on 4.9.56, but updating to 4.9.57 brought it back. Let's give it a few days and see what happens 😊

**Comment by matteocontrini** [comment]
4.9.57 fixed the issue for me.

**Comment by MahdiNazemi** [comment]
After testing a few more times, I see the extension works properly every time I toggle the system's color scheme except when "Change browser theme" is selected. I am not sure if it is related to #9538.
