### ISSUE TITLE
[Broken Website] Google Drive Search Results Filters not Visible/Readable

### ISSUE THREAD

**Issue by RuthlessRuler** [darkreader/darkreader#9589]
# Broken Website Report

## Website Address

https://drive.google.com/drive/search?q=

## Steps To Reproduce

- Go to Drive.google.com
- Enable Dark Reader if not already enabled
- Search for Any File using Search bar

## Problematic Observation

- Some Filter UI Elements are Not readable due to improper inverting of colors
 
## Screenshots

![image](https://user-images.githubusercontent.com/20885012/185241116-891c869c-fa9c-4656-800c-210407f18e09.png)

## System Information

- OS: Windows 10
- Browser: Firefox 103
- Dark Reader Version: 4.9.56

**Comment by RuthlessRuler** [comment]
@Gusted Its seems mostly fixed with one exception. 
For most of the filters when selected, the patch properly works: 
![image](https://user-images.githubusercontent.com/20885012/185387282-b5d75d43-d353-4027-9139-ab8349c7525b.png)

Except, for 'Title Only' filter. It becomes unreadable if its selected.
![image](https://user-images.githubusercontent.com/20885012/185387066-427a4318-7cfa-448a-8d12-3a44b748afb7.png)

**Comment by Gusted** [comment]
Thanks for reporting @RuthlessRuler, #9614 fixes the mentioned issue.
