### ISSUE TITLE
[Broken Website] Overleaf -- improperly inverts images

### ISSUE THREAD

**Issue by rlacobelle20** [darkreader/darkreader#9593]
# Broken Website Report

## Website Address

https://www.overleaf.com/

## Steps To Reproduce

- go to https://www.overleaf.com/
- sign in
- create a project
- add package ```\usepackage{graphicx}```
- upload picture of choice
- under ```\section{Introduction}``` add ```\includegraphics[width=4cm]{image.png}```  with image.png whatever your image is called
- turn on dark reader
- recompile document

## Problematic Observation

Dark reader inverts the color of the image inserted into overleaf. The downloaded picture is ok, however when it is recompiled in the document, it becomes inverted.

## Screenshots

Latex and Inverted Image
![image](https://user-images.githubusercontent.com/44063772/185246923-71255224-9f52-4035-ac6f-feb4fd6e95f8.png)

Inverted Image with Original Image
![image](https://user-images.githubusercontent.com/44063772/185246476-38d8d9c2-68eb-4e16-85d9-4f987805cf51.png)

## System Information

- OS:  Windows 10
- Browser:  Chrome
- Dark Reader Version:  4.9.55

**Comment by Gusted** [comment]
This is expected behavior, as in order to darken the text and symbols on the result window, we need to invert that window. They don't expose any individual elements, just one element.

**Comment by nsteinle** [comment]
Hi, on overleaf, now the entire pdf viewer is unaffected by the dark reader resulting in the pdf viewer to be very bright/white light. The dark mode reader used to work on the overleaf pdf viewer but recently stopped working.
