### ISSUE TITLE
[Dynamic] *.teamwork.com 

### ISSUE THREAD

**Issue by ylluminate** [darkreader/darkreader#961]
Teamwork.com is great (better than Basecamp), but they've refused for several years now to provide a dark theme. It might be worth scrubbing over it and making sure it works a little better in Dynamic mode.

For the most part it works really well, but Brightness needs to go to about +10 and Contrast to about -30.

I'm also finding that the toggles don't look quite right:
![example](https://cl.ly/739b7ef5e09b/Image%202018-12-31%20at%202.13.30%20PM.png)

I'll add any more serious issues I find here as I stumble across them.

**Comment by Gusted** [comment]
Fixed.
