### ISSUE TITLE
[Question] Dark Reader setting difference

### ISSUE THREAD

**Issue by knightmob** [darkreader/darkreader#9612]
hello! nice project you have here, thanks for sharing this lit extension though, its really good!, been using it for a while now. I just want to ask about the settings difference between android and pc, because in android browser, you can access all settings like the "detech dark them" change theme or many more, but why on pc browser the extension settings is limited? pls fix this or kindly explain the reason why you wont add all settings in pc browser, btw keep up the good work! thanks for adding tokyo theme it's really nice!

**Comment by Gusted** [comment]
Hi @knightmob!

The android version is currently already using the preview design, you can enable this on PC as well(the same exact interface):

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.

**Comment by knightmob** [comment]
> Hi @knightmob!
> 
> The android version is currently already using the preview design, you can enable this on PC as well(the same exact interface):
> 
> - Click Dark Reader icon.
> - Click Dev tools (in the bottom-right corner).
> - Click Preview new design.
> 

Thanks!
