### ISSUE TITLE
[Broken Website] Facebook Messenger

### ISSUE THREAD

**Issue by privacyguy123** [darkreader/darkreader#9617]
# Broken Website Report

## Website Address

https://www.facebook.com/messages

## Steps To Reproduce

Easiest explained with a screenshot.

## Problematic Observation

Should be dark mode all the way around the smiley icon.

## Screenshots

![image](https://user-images.githubusercontent.com/50337995/185481117-be0bfb52-e7ae-41ed-b5c7-c2739a1a3d95.png)

## System Information

- OS:  Windows 10 LTSC
- Browser: FireFox 103.02
- Dark Reader Version: 4.9.56

**Comment by Gusted** [comment]
I still don't use Facebook. Kindly ping @Myshor

**Comment by Myshor** [comment]
Ok... I was seeing that for some days and did not find any solution.
Someone had to submit bug for it and viola. 😁

The fix will be merged in a minute.

**Comment by privacyguy123** [comment]
Hmm - still seeing this bug?

**Comment by Myshor** [comment]
It will be automaticly added to newest version which is 4.9.57.
To be sure check in your version on extensions page.
P.S. This version was released today so it can still be updated tomorrow in your browser. 😉

**Comment by privacyguy123** [comment]
I've had .57 for a few days now - still seeing this bug. ;/

**Comment by Myshor** [comment]
I see one possibility.
If you go into Settings and see the Tools option to open Developer Tools for Dark Reader.
Is it notified like this?
![image](https://user-images.githubusercontent.com/56877029/186872048-3f32a401-6523-45e2-bc28-48b608897693.png)

Yes or no. Still you can do reset in developer tools:
![image](https://user-images.githubusercontent.com/56877029/186872292-2ddcba20-e502-4210-9939-4b8018eb635f.png)

That should set default site fixes for the release.
Just don't click apply after reset. To be sure default is set and nothing more.
There should not be any notification "!" on the Tools button in Dark Reader after this.

When all that steps will be done it should work... At least I remember I didn't need to refresh messenger/facebook pages to see that.

**Comment by privacyguy123** [comment]
That does fix it yes - I've never had to do that before though!
