### ISSUE TITLE
awesome icons

### ISSUE THREAD

**Issue by rinaldi6109** [darkreader/darkreader#962]
Turning on Dark Reader destoys awesome icons. See for example the attached image (side by side screenshots from www.ilpost.it). 
![immagine](https://user-images.githubusercontent.com/1431515/50573194-1ef0ce00-0dcf-11e9-8ed2-f61a60cb5729.png)

**Comment by alexanderby** [comment]
Unfortunately this is an issue with custom font settings. Custom font overrides icons that are packed into fonts. Duplicate of https://github.com/darkreader/darkreader/issues/736
