### ISSUE TITLE
[Performance Issue] .com.test does not work with Dark Reader

### ISSUE THREAD

**Issue by Committing** [darkreader/darkreader#9644]
# Performance Issue Report

## Website Address
*.com.test

## Steps To Reproduce
- Go to any Laragon local website (anything.com.test)
- Enable Dark Reader -> Does not enable in Chrome.

## Performance Profile
N/A

## Screenshots
On newest version of Chrome (DarkReader v4.9.56)
![alt](https://i.gyazo.com/29b691d7ca0bf466b8b71024e1a8e81f.gif)

On an old now-unsupported browser Dissenter it works (DarkReader v4.9.56)
![alt](https://i.gyazo.com/b8d5494fc3366c54236afb9672ecf88f.gif)

## System Information
Does not work in Chrome Version 104.0.5112.81
Does work in old Dissenter Version 1.5.114

- OS: Windows 10
- Dark Reader Version: v4.9.56

## Additional Context
I would like to test how DR looks on my local sites and save my eyes when doing only content. On my old browser it worked fine but after switching back to Chrome the extension no longer works on domains ending with **.com.test**

**Comment by Gusted** [comment]
Hi @Committing

What does your site list looks like? Does it happen to have `com.test`(without any subdomain)?

**Comment by Committing** [comment]
> Hi @Committing
> 
> What does your site list looks like? Does it happen to have `com.test`(without any subdomain)?

Hi @Gusted 

I do not have `com.test` in the site list.

However, I did have the `.com` variant in my site list. When I removed the `.com` entry I was able to enabled it again on my local `.com.test` domain again.

**Comment by Gusted** [comment]
Yes this is a long-standing issue with dark reader, see #2517 for more of the history.

**Comment by Committing** [comment]
Disappointing, thanks.
