### ISSUE TITLE
[Broken Website] https://alexn.org/

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#9652]
# Broken Website Report

## Website Address

https://alexn.org/

## Problematic Observation

Whole website is immune to Darkreader

## Screenshots

![Screenshot_58](https://user-images.githubusercontent.com/6344099/186019021-067bb6ae-0f1e-4a5b-b750-ad39487e6661.png)

## System Information

- OS:  linux
- Browser:  firefox
- Dark Reader Version:  current

**Comment by Gusted** [comment]
We got an *abuser* of the `darkreader-lock` mechanism. So dark reader thinks there's already an Dark Reader instance active on that page... while it's not true as it's light. 
![image](https://user-images.githubusercontent.com/25481501/187032481-6c247670-6880-439c-b497-fa9163015fc6.png)

The domain name actually had a strange connection in my memory and after some searching I remembered why, the author of that page was actually the one requesting this mechanism #4330.

@alexandru Is there still an issue with Dark Reader on your site? I removed the darkreader-lock check and site looks okay in my eyes.

**Comment by alexandru** [comment]
My website has both light and dark themes.

```html
<meta name="color-scheme" content="light dark">
```

And in my own usage I'm one of those people that switches from light to dark mode automatically, depending on time of day — meaning that I rely Dark Reader to use the system's settings to switch on or off.

What I wanted was for Reader Mode to use the website's own dark theme. I don't see it doing that — I see that in Firefox for Android there's an option to auto-detect the website's own dark theme, but that option isn't available for desktop.

Plenty of websites have their own dark theme when the system is set to dark, including GitHub. So this is a more general problem with Dark Reader.

For now I have deleted that HTML tag.

**Comment by alexandru** [comment]
I now see there's a [v5 design preview](https://darkreader.org/tips/activate-v5-preview/). This is good.

I think you can close this issue.

**Comment by ShalokShalom** [comment]
Darkreader should always use the websites dark theme if available, and otherwise always the own one. 

I cannot stress enough, how it destroys your workflow, your eyes and specifically your melatonin productions when a huge white canvas pops up out of the nowhere.

**Comment by Gusted** [comment]
The original issue is solved, if there are still any other (unrelated) issues, please fire an new issue for it.
