### ISSUE TITLE
[Broken Website] Microsoft Outlook Web Application (OWA) missing buttons in compose email section

### ISSUE THREAD

**Issue by timjobutler** [darkreader/darkreader#9663]
# Broken Website Report

## Website Address
https://mail.jwpub.org/owa

## Steps To Reproduce
- Go to https://mail.jwpub.org/owa
- Either start a new email or reply to an existing email
- The row of buttons above the Send button is not visible when Dynamic mode is enabled. They appear once switching to Filter mode.
- This issue is present in Firefox, Chrome and Edge browsers.

## Problematic Observation
The buttons in the compose email section, both new and replies, are missing in Dynamic mode but appear when switching to Filter mode.
Interestingly, in the Chrome browser, once you have switched to Filter mode to access the buttons if you switch back to Dynamic mode, the buttons remain present. However, this behaviour only works in Chrome, not in Edge or Firefox.

## Screenshots
Screenshot of the Compose email section when Dynamic mode is applied
![owa-dynamic](https://user-images.githubusercontent.com/37101212/186347215-f3bd1914-fc00-4ba9-94ff-d440ef7e2d9e.png)

Screenshot of the Compose email section when Filter mode is applied
![owa-filter](https://user-images.githubusercontent.com/37101212/186347250-585f256f-a8af-47d7-8e53-32ab9476fc5f.png)

## System Information
Windows 10 Home, 64-bit, Build 19043
Chrome version 104.0.5112.102
Firefox version 103.0.2
Edge version 104.0.1293.63 
Dark Reader version 4.9.57

## Additional Context
This website is accessed using an organisational Microsoft Exchange account

**Comment by Gusted** [comment]
Adding help wanted as this seems to be an "internal" page.

**Comment by timjobutler** [comment]
I am happy to provide whatever technical data is needed since a work account is required to access this page

**Comment by Gusted** [comment]
When I add a help wanted label, I _kind of_ expect for people with those access to investigate a bit for themselves (as remote debugging is time-consuming and can really lead to nothing as I don't know the whole context). You could investigate via the dev tools(ctrl + shift + i) if there's CSS that's causing this buttons to be not visible (if they are there in the first place).

**Comment by timjobutler** [comment]
@Gusted I am new to this side of the browser so I will try my best to provide the info.

**UPDATE** - this issue is only present in Firefox (version 104.0.1)


Screenshot of "Bold" button in Dynamic mode
![mail jwpub org - Bold button (Dynamic mode)](https://user-images.githubusercontent.com/37101212/188446463-48e44a54-3c4a-45c5-ba8d-4e2cb83bf108.png)

Screenshot of "Bold" button in Filter mode
![mail jwpub org - Bold button (Filter mode)](https://user-images.githubusercontent.com/37101212/188446572-52c81e0d-1ef7-4ed1-bff6-be28928e3b46.png)

Screenshots of Developer Tools for the "Bold" button
![mail jwpub org - Bold button - Dev Tools 1](https://user-images.githubusercontent.com/37101212/188446696-5b674fb5-e09f-471c-a2df-ef3285fd6200.png)

![mail jwpub org - Bold button - Dev Tools 2](https://user-images.githubusercontent.com/37101212/188446727-da01d058-86b2-43b1-8d25-9fe9d08ebc72.png)


Here is the CSS code for the "Bold" button as a sample
[OWA.txt](https://github.com/darkreader/darkreader/files/9489671/OWA.txt)


Here is the page source HTML file, not sure if it is helpful or not
[https __mail.jwpub.org_owa_#path=_mail_drafts.txt](https://github.com/darkreader/darkreader/files/9489684/https.__mail.jwpub.org_owa_.path._mail_drafts.txt)

**Comment by Gusted** [comment]
Could you please make a screenshot with the `<span class="_fc_3 owaimg csimg image-bold-png">` element being selected?

**Comment by timjobutler** [comment]
Hi @Gusted 

Here is the screenshot of the `<span class="_fc_3 owaimg csimg image-bold-png">` element selected.

![span class=''_fc_3 owaimg csimg image-bold-png'' element](https://user-images.githubusercontent.com/37101212/189508125-5cc1b27d-15e7-40b3-82fc-5d06fc3c9b6e.png)

**Comment by Gusted** [comment]
Thanks! Could you scroll down the element's style rules? 

![image](https://user-images.githubusercontent.com/25481501/189530255-59301a28-c808-4c18-9c42-93ce14b63c4e.png)

Somewhere in that list, there's likely a rule that's causing this. If you're not able to figure that out, please send a screenshot of all rule(the first 25 should be enough).

**Comment by timjobutler** [comment]
I believe these are the screenshots you are requesting.

![element-rules-1](https://user-images.githubusercontent.com/37101212/189656234-4189351c-f0b6-4fa5-adf0-6f66ec1bdc5b.png)

![element-rules-2](https://user-images.githubusercontent.com/37101212/189656285-14023c36-48ad-4742-962b-b7a911d74e19.png)

![element-rules-3](https://user-images.githubusercontent.com/37101212/189656329-e43a5774-702e-4154-8f8d-de9e1d565f79.png)

**Comment by Gusted** [comment]
Interesting, seems to be correct. Could you try adding this custom fix to Dark Reader's devtools:

- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Add:
```CSS
================================

mail.jwpub.org/owa

IGNORE IMAGE ANALYSIS
.image-bold-png

================================
```
- Try to format this fix as the other fixes, don't just copy paste it. Dark Reader will automatically sort the fix alphabetically, just make sure it's according to current format.
- Click Apply

**Comment by timjobutler** [comment]
I have added the suggested fix in the Dev Tools and expanded it to include all the buttons that were not visible. The fix is below.

```
================================

mail.jwpub.org/owa

IGNORE IMAGE ANALYSIS
.image-font-png
.image-font_size-png
.image-bold-png
.image-italic-png
.image-underline-png
.image-backcolor-png
.image-forecolor-png
.image-insertunorderedlist-png
.image-insertorderedlist-png
.image-outdent-png
.image-indent-png
.image-justifyleft-png
.image-justifycenter-png
.image-justifyright-png
.image-createlink-png
.image-unlink-png
.image-superscript-png
.image-subscript-png
.image-strikethrough-png
.image-alttext-png
.image-blockdirltr-png
.image-blockdirrtl-png
.image-undo-png
.image-redo-png
.image-removeformat-png
.image-table_icon-png
.image-insertpicture-png
.image-emoji-png
.image-format-png

================================
```

Below is a screenshot of the same page with the fix applied.
![mail jwpub org fix](https://user-images.githubusercontent.com/37101212/190901529-f2416480-9637-48b9-93be-78bf9fbea7fe.png)

I hope this data is helpful and could be added to all sessions of Dark Reader.

Thanks for your patience @Gusted

**Comment by tbloch1** [comment]
This issue also affects my outlook web app. The solution provided does work if I change the web address accordingly. However, is there not some wild-card solution that can be implemented so that the solution works across different instances of OWA, without having to manually add in the exceptions for each one?
