### ISSUE TITLE
[Broken Website] wiki.teamfortress.com

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#9697]
# Broken Website Report

## Website Address
`https://wiki.teamfortress.com/wiki/Main_Page`

## Steps To Reproduce
Go to `https://wiki.teamfortress.com/wiki/Main_Page` and see that the site is very ugly.

## Problematic Observation
Ugly colors. Using dynamic theme.

## Screenshots
With:
![image](https://user-images.githubusercontent.com/30274161/187139155-c54476a4-3f1b-4d55-9352-fd5dd5d9ae05.png)

Without:
![image](https://user-images.githubusercontent.com/30274161/187139177-50f9d6e4-def1-4f4d-87d2-881cfae91ede.png)

## System Information

- OS: Windows 10 Pro 21H2
- Browser: Firefox 104.0 64-bits
- Dark Reader Version: 4.9.57

## Additional Context
No additional context.

**Comment by Gusted** [comment]
"It's ugly" is not an problem description. The original colors are already in this color shade, however in the light variant. Dark Reader simply makes them the dark variant which might put you off, but is the correct modification. You could instead use Filter(+) or Static theme for this site.
