### ISSUE TITLE
Could you allow the toggling of if websites are dark or not by default?

### ISSUE THREAD

**Issue by johnch18** [darkreader/darkreader#970]
Typically, I don't mind most bright themes, there are just some that I can't stand. But to use darkreader, I have to turn it on and manually blacklist every site I don't want brightened. Could you make a toggle for what the default is?

**Comment by nisavid** [comment]
This feature already exists: In the **Site list** panel, select **Not invert listed**.

IMO the label for this option—and its somewhat obscure placement—is not very intuitive.  In addition to hampering discoverability by new users (as evidenced by this issue), it is a minor inconvenience to figure out where it is every time one sets up a new browser (if one prefers, as I do, to use the non-default option), and it is practically irrelevant after the initial setup.

Perhaps it would serve the extension well (especially with new users) to non-intrusively call attention to this feature during the extension's initial setup on a new browser.  For example, a small notification banner (that can be dismissed) along the top of the extension panel, prompting the user to choose the default behavior, would provide (IMO) a pleasant and useful onboarding experience.
