### ISSUE TITLE
[Broken Website] patreon.com comments icons

### ISSUE THREAD

**Issue by JohnVeness** [darkreader/darkreader#9700]
# Broken Website Report

## Website Address
https://www.patreon.com/posts/39005311

## Steps To Reproduce

1. Go to https://www.patreon.com/posts/39005311
2. Scroll down to the comments
3. Look at the icons underneath a comment (heart, speech bubble, and if viewing a comment you made yourself: pencil and trashcan)

## Problematic Observation
With Dark Reader on, only the heart icon is visible. With Dark Reader off, all icons are visible.

## Screenshots
Dark Reader off:
![image](https://user-images.githubusercontent.com/2512915/187192305-a0c11b04-e775-4828-b5b7-9f61e5eb0787.png)

Dark Reader on:
![image](https://user-images.githubusercontent.com/2512915/187192405-12e8b850-4634-4b17-b26d-173097242236.png)

## System Information

- OS: Ubuntu 22.04
- Browser: Firefox 104.0
- Dark Reader Version: 4.9.57

## Additional Context
This wasn't a problem until recently - I'm sure it was OK a few weeks ago, say. I don't know if this was a website change or a Dark Reader change that has caused the issue now.

Hope you can fix! I thought for a while that Patreon had took away the ability to edit one's own comments.

**Comment by Gusted** [comment]
I don't have a patreon. If you could provide me with an screenshot with the dev tools(ctrl + shift + i) open and have the icon element selected, I could make a fix for it.

**Comment by JohnVeness** [comment]
The link I gave should work without a Patreon account (I checked on a blank browser profile)

**Comment by JohnVeness** [comment]
Nonetheless, I think this is what you want? This is with the invisible speech bubble icon selected.
![image](https://user-images.githubusercontent.com/2512915/187224393-b317f36d-d503-4368-982f-40615fd8523a.png)

**Comment by ja-som** [comment]
Hello, can the fix #9736 be unfixed? Patreon changed the site, if you "like" something with Dark Reader enabled the heart icon stays white

Dark Reader OFF:
![Darkreader_Off](https://github.com/user-attachments/assets/6f4dc38b-0508-4af1-8daf-a5a9fd56b81a)

Dark Reader ON:
![Darkreader_On](https://github.com/user-attachments/assets/00515848-404e-4869-88b9-639fcbc504cf)

Dark Reader ON, but I removed the "fix" via Dark Reader's dev tools
![Darkreader_On_unfixed](https://github.com/user-attachments/assets/99cf7dc1-45b5-4432-b5f7-a544c3289c70)
