### ISSUE TITLE
[Broken Website] anvaka.github.io/sayit

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [darkreader/darkreader#9714]
# Broken Website Report

## Website Address
https://anvaka.github.io/sayit/?query=tasks

## Steps To Reproduce
Visit previously provided URI.

## Problematic Observation
Text is invisible.

## Screenshots
![unselected](https://user-images.githubusercontent.com/42837531/187737665-77501e4a-aa20-4d2d-ac74-d6c9b6975d58.png)
![selected](https://user-images.githubusercontent.com/42837531/187737768-b33bdbac-dfeb-4ed8-acc6-bd85e49ac4fb.png)

## System Information

- OS: Linux
- Browser: Firefox 104
- Dark Reader Version: 4.9.57

**Comment by Pdzoc** [comment]
The same problem on Windows and Chrome 104.
