### ISSUE TITLE
[Broken Website] support.mozilla.org (and support.mozilla.org, addons.mozilla.org--likely all same issue)

### ISSUE THREAD

**Issue by ThePowerTool** [darkreader/darkreader#9748]
# Broken Website Report

## Website Address
https://support.mozilla.org/en-US/ , https://support.mozilla.org/en-US/questions/1374981 , https://addons.mozilla.org/en-US/firefox/ , https://addons.mozilla.org/en-US/firefox/addon/darkreader/ 

## Steps To Reproduce
- Go to any of the above URLs
- try switching Dark Reader on and off

## Problematic Observation
notice there is no change--the bright white background endures regardless of "on" or "off" position

## Screenshots
n/a--hopefully immediately obvious

## System Information

- OS: Fedora 36 (fully updated), Linux
- Browser: Firefox 104.0.1
- Dark Reader Version: 4.9.57

## Additional Context
Thank you very much for Dark Reader!  I have challenges with my vision and cannot see anything presented with a bright white background.

While I would really like to be able to see and read the mozilla support site I also thought someone should report that Dark Reader seems not to work on most mozilla sites and addons.mozilla.org given this plugin supports Firefox and resides on an addon page where it doesn't seem to properly change the background.

**Comment by Gusted** [comment]
They are protected websites (Browser doesn't allow modifications of those website). This is indicated in the UI.

**Comment by scarf** [comment]
If clear out `extensions.webextensions.restrictedDomains` preference then support.mozzila.org starts working but not addons.mozilla.org.  To get that site working need to add new boolean preference `privacy.resistFingerprinting.block_mozAddonManager` and set it to true.
