### ISSUE TITLE
[Broken Website] bilibili comment bar shows dark text and backgroud

### ISSUE THREAD

**Issue by ButterPasser** [darkreader/darkreader#9751]
# Broken Website Report
www.bilibili.com
## Screenshots

![image](https://user-images.githubusercontent.com/112840514/188364474-fa505611-be23-4191-82a8-fc0d7d140c64.png)

## System Information

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
Use the template. Not an actionable issue
