### ISSUE TITLE
[Broken Website] Google.com

### ISSUE THREAD

**Issue by NguyenASang** [darkreader/darkreader#9755]
# Bug Report
Disable Dark Reader in Google.com doesn't work properly

## Website Address
https://www.google.com

## Bug Description
The popups are still overridden by Dark Reader 

## Steps To Reproduce
- Watch the video:

https://user-images.githubusercontent.com/87893636/188431038-9ba67ec9-9964-42d0-9158-2dee91f8a509.mp4

## Expected Behavior
The popups are in the default dark mode

## Actual Behavior
The popups are in the dark mode of Dark Reader

## Screenshots
![image](https://user-images.githubusercontent.com/87893636/188431245-16aeb294-8f61-443f-a29e-7c0f248e67d3.png)

![image](https://user-images.githubusercontent.com/87893636/188431303-e38b0f56-6e49-4698-ba7a-77cd8e099e8d.png)

## System Information
- OS: Windows 11
- Browser: Edge 105
- Dark Reader Version: 4.9.57

**Comment by Gusted** [comment]
Likely fixed in the next version, by #9639
