### ISSUE TITLE
[Broken Website] Replace with title

### ISSUE THREAD

**Issue by pbaesse** [darkreader/darkreader#9757]
# Broken Website Report

## Website Address
 https://docs.google.com/

## Steps To Reproduce

- Go to web site and use it.

## Problematic Observation

Dark reader happens to also change the colors of the fonts and backgrounds. So if I want to write or format with the regular colors (black and not grey for example), I have to turn it off.

## Screenshots

![Screenshot from 2022-09-05 11-06-25](https://user-images.githubusercontent.com/4050950/188467828-892f1d79-1bc3-44a8-ad8b-436f365854ef.png)

## System Information

- OS: Mint 20.3
- Browser: Firefox 104.0.1 (64-bit)  
- Dark Reader Version: 4.9.57

**Comment by Gusted** [comment]
That's expected behavior, Dark Reader modifies the whole site, not a portion of it.
