### ISSUE TITLE
[Feature Request] integrate Reddit Auto Dark Mode extension

### ISSUE THREAD

**Issue by direrFlood** [darkreader/darkreader#9782]
# Feature Request
Auto dark mode enable on reddit.com.
there is an extension that does that, Maybe integrate it in darkreadeR?
https://chrome.google.com/webstore/detail/reddit-auto-dark-mode/ejbbhcpkjnloojhfihmbfgkcjiaoecdg/related
## Is this feature request related to a problem?

enable dark mode from settings on reddit.com

**Comment by Gusted** [comment]
Out of dark reader's scope.
