### ISSUE TITLE
[Broken Website] Bienici.com displayed in light mode, with DarkReader enabled

### ISSUE THREAD

**Issue by oeloo** [darkreader/darkreader#9797]
Hi, bienici.com website is in still displayed in light mode despite DarkReader being fully enabled.

# Broken Website Report

## Website Address
http://www.bienici.com

## Steps To Reproduce
- Just go to http://www.bienici.com website (with DarkReader active and enabled on this website)

## Problematic Observation
The background is fully white despite DarkReader being active.

## Screenshots
![image](https://user-images.githubusercontent.com/98819304/189483323-3772015e-50e7-49ee-9659-658b07b18bf3.png)

## System Information
 on Windows 11 x64 (latest version)

- OS: Windows 11 64x
- Browser: Lastest version of Chrome browser as of 2022/09/10
- Dark Reader Version: 4.9.57

## Additional Context

**Comment by oeloo** [comment]
Thank you for you answer, the background is now dark on the homepage, but the main part (were the real-estate ads are displayed) of the website is still using plain white as background: https://www.bienici.com/recherche/location/strasbourg-67000/2-pieces-et-moins
![image](https://user-images.githubusercontent.com/98819304/192748754-e1a2411e-5a7a-4ff2-b111-eb4940ec1864.png)

**Comment by Gusted** [comment]
@oeloo #9976

**Comment by oeloo** [comment]
Thanks for your answer. When will I be able to see this fix ? (I currently have the lastest update but do not see the fix)

**Comment by Gusted** [comment]
Please see https://github.com/darkreader/darkreader#site-fixes

**Comment by oeloo** [comment]
> Please see https://github.com/darkreader/darkreader#site-fixes

I have activated this option more 8 days ago:
![image](https://user-images.githubusercontent.com/98819304/195275278-78ec8f7d-613c-4d3c-a12d-c0eb9c91e392.png)
but I can still see no changes on bienici.com
how can I check whether the site fixes bienici.com has not been retrieved on my Chrome browser ? or if it is the settings that does not change bienici.com

**Comment by Gusted** [comment]
@oeloo You might need to force an synchronization of the fixes:

![image](https://user-images.githubusercontent.com/25481501/195726665-86ad80c3-0909-4a02-a251-1680040cd4da.png)

**Comment by oeloo** [comment]
Forcing the sync, solved this issue, thank you.
I could also see that the page https://www.bienici.com/recherche/location/strasbourg-67000/2-pieces-et-moins is now in dark mode 🙂
but when I click on an ad, for example https://www.bienici.com/annonce/location/strasbourg/appartement/2pieces/hektor-immomstrasbourg-1869?q=%2Frecherche%2Flocation%2Fstrasbourg-67000%2F2-pieces-et-moins , we still have light mode instead of dark mode
