### ISSUE TITLE
[Broken Website] https://www.logitech.com/en-us/software/logi-options-plus.html

### ISSUE THREAD

**Issue by direrFlood** [darkreader/darkreader#9799]
# Broken Website Report

## Website Address

https://www.logitech.com/en-us/software/logi-options-plus.html
## Steps To Reproduce

go to https://www.logitech.com/en-us/software/logi-options-plus.html with dark mode enabled
scroll -> images/page stuttering.
## Problematic Observation

scroll -> images/page stuttering.
## System Information

- OS: 
- Browser: 
- Dark Reader Version:

**Comment by Gusted** [comment]
Please fill out all information. Also please try to give more context, "stuttering' is quite a vague term in this context. Which exact element/aspect is stuttering and how? Also please try to provide a screenshot, in the case I'm not able to reproduce the issue(which seems to be true for now).
