### ISSUE TITLE
[Bug] Dark Reader affecting extensions that load remote frames

### ISSUE THREAD

**Issue by christinaphan** [darkreader/darkreader#9809]
# Bug Report

## Website Address

https://addons.mozilla.org/en-US/firefox/addon/todoist/

## Bug Description

Extensions are not supposed to be able to modify the content of other extensions' `moz-extensions:-documents`. However, Todoist is an example of an extension that loads an iframe into their `moz-extensions:-documents`. This is causing Dark Reader to affect the CSS styling of another extension. 

Despite having Dark Reader disabled on `todoist.com` and `firefox.todoist.com`, Dark Reader is still able to affect the CSS of the Todoist extension.

## Steps To Reproduce

1. Install both Todoist and Dark Reader extensions on Firefox.
3. Open the Todoist extension popover

## Expected Behavior

Todoist's extension popover CSS should not be affected by Dark Reader. Even more so when `todoist.com` and `firefox.todoist.com` are blacklisted.

## Actual Behavior

Todoist's extension popover CSS is affected by Dark Reader.

## Screenshots

Todoist with Dark Reader installed (and `todoist.com`, `firefox.todoist.com` blacklisted)
![image](https://user-images.githubusercontent.com/88528865/189808069-f410847e-4551-4a6e-b033-c9d83f03b183.png)
Todoist without Dark Reader installed
![image](https://user-images.githubusercontent.com/88528865/189808109-f2fdd415-6872-4457-ad6b-719cf21e9ba4.png)

## System Information

- OS: Windows 11 and Arch Linux
- Browser: Firefox 104
- Dark Reader Version: 4.9.57

## Additional Context
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1788248 and https://github.com/darkreader/darkreader/issues/6849

**Comment by Gusted** [comment]
I'm leaning towards closing this issue as a duplicate, but you're already linking the issue(#6849), so what is the new information that #6849 doesn't have?

**Comment by christinaphan** [comment]
You're right. I'll close this issue now!
