### ISSUE TITLE
[Broken Website] False positive dark theme detection on deepnote.com

### ISSUE THREAD

**Issue by gshpychka** [darkreader/darkreader#9826]
# Broken Website Report

## Website Address
deepnote.com

## Steps To Reproduce
Go to deepnote.com with DR enabled

## Problematic Observation
DR says "Dark theme detected", even though deepnote.com doesn't have a dark theme

## System Information

- OS: Linux
- Browser: Firefox 104
- Dark Reader Version: 4.9.57

**Comment by Gusted** [comment]
Moved to https://github.com/darkreader/darkreader/discussions/9016#discussioncomment-3668360
