### ISSUE TITLE
[Feature Request] Compatible with Edge's Immersive Reader

### ISSUE THREAD

**Issue by loyukfai** [darkreader/darkreader#9845]
# Feature Request

## Is this feature request related to a problem?
Dark Reader is not currently compatible with Edge's Immersive Reader

https://support.microsoft.com/en-us/topic/use-immersive-reader-in-microsoft-edge-78a7a17d-52e1-47ee-b0ac-eff8539015e1?form=MT00C1

**Comment by Gusted** [comment]
That's not possible, this is a protected page, Dark Reader cannot modify this page.
