### ISSUE TITLE
[Broken Website] https://zaid-ajaj.github.io/the-elmish-book/#/

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#9855]
# Broken Website Report

## Website Address
https://zaid-ajaj.github.io/the-elmish-book/#/

## Screenshots

![image](https://user-images.githubusercontent.com/6344099/190928130-c636f54f-c16a-4552-a53d-2de6bc9b6b6a.png)

## System Information

- OS:  Linux
- Browser:  Firefox 
- Dark Reader Version:  current

**Comment by ShalokShalom** [comment]
Thanks 🙏🏼

**Comment by ShalokShalom** [comment]
Its still the same thing for me. I activated the syncro and reloaded the page. 

![image](https://user-images.githubusercontent.com/6344099/191258979-86aa9ab9-242b-43dc-99a9-146a0777ecaa.png)

**Comment by Gusted** [comment]
Please check [the second step] (https://github.com/darkreader/darkreader#site-fixes)of the README: 
![image](https://user-images.githubusercontent.com/25481501/191260202-dcc3836e-e769-4c17-8e95-8b4bbdd93ea4.png)

**Comment by Gusted** [comment]
Oh, interesting. I will investigate later.
