### ISSUE TITLE
[Bug] Chromium extension doesn't detect system theme on Linux (Gnome/Flatpak)

### ISSUE THREAD

**Issue by jaysonwcs** [darkreader/darkreader#9859]
# Bug Report

## Bug Description

Extension does not detect when system switches to dark mode. Chromium can detect and change the GTK theme, only the extension will not detect.

## Steps To Reproduce
- Install Chromium through Flatpak (Flathub repository)
- Install Dark Reader extension
- Activate the "Use system color scheme" option

## Expected Behavior

The extension should switch to dark mode when I change Gnome to dark mode

## Actual Behavior

Only Chromium changes to dark mode. Dark reader does not detect the system theme and doesn't change to dark mode.

## Screenshots

Deactivated:
![image](https://user-images.githubusercontent.com/7007373/191017202-269f49d9-aea9-41b6-b761-7f5598db6263.png)

Manually activated:
![image](https://user-images.githubusercontent.com/7007373/191017304-48628610-4da9-4a3a-a89a-8a6259b9d1d6.png)

Configured to use system theme (switched Gnome to dark mode):
![image](https://user-images.githubusercontent.com/7007373/191017430-859b28b0-7a77-489c-ad60-9020701772ce.png)

## System Information

- OS:  Linux (Arch Linux, Kernel: Linux Desktop 5.19.7-arch1-1 # 1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux)
- Browser:  Chromium 105.0.5195.125
- Dark Reader Version:  4.9.57

## Additional Context

Tested on Ungoogled Chromium and it has the same result. On Firefox (Flatpak) works out of the box.

**Comment by Gusted** [comment]
Hi @jaysonwcs!

This is likely a sandboxing feature from Flatpak that Chromium currently doesn't handle. We rely on the browser to give us the information regarding the user's system color scheme. Could you please try execute the following code in the console(ctrl + shift + i) on Chromium:
```js
matchMedia('(prefers-color-scheme: dark)').matches
```
Please report back what it reports, it will likely report `white`, in which case you will need to open a report at https://github.com/flathub/org.chromium.Chromium

**Comment by jaysonwcs** [comment]
Hi @Gusted !
Yes, you are probably right:
![image](https://user-images.githubusercontent.com/7007373/191263054-39a94ac5-ed33-45b9-9dca-c85733fa21ff.png)

It reported false, even though I switched Gnome to dark mode.

I'll report to Chromium then.

Thanks!

**Comment by AllanOricil** [comment]
It is still not working properly. I tried safari, chromium and firefox.

**Comment by sohanglal** [comment]
Did you try Install dconf and run this : dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
