### ISSUE TITLE
[Broken Website] Regression: GitHub UI is blue

### ISSUE THREAD

**Issue by bershanskiy** [darkreader/darkreader#9870]
# Broken Website Report

## Website Address

https://github.com/darkreader/darkreader

## Steps To Reproduce

 - Go to https://github.com/darkreader/darkreader
 - Observe blue labels

## Problematic Observation

Button labels are blue

## Screenshots

4.9.57 ("good"):
![image](https://user-images.githubusercontent.com/45960703/191213419-5e209984-d0a6-4527-b0e9-e885e6b914ad.png)
Current `main` ("bad"):
![image](https://user-images.githubusercontent.com/45960703/191213615-d6959ab5-a072-4859-ba0d-0a0bc35501b4.png)

## System Information

- OS: Windows 11
- Browser: Chrome 105
- Dark Reader Version: `main` 

## Additional Context

I'll try to bisect and triage this a bit later today.

**Comment by Gusted** [comment]
Oops, likely this is from #9843, but I'm pretty sure this is now causing a priority over the site's `<a>` color due to the psuedo-class. I don't reverting the commit as it doesn't really fix any real world issues.

**Comment by bershanskiy** [comment]
@Gusted Thanks for the prompt fix, that makes sense. Let's reopen #9836 just in case.
