### ISSUE TITLE
[Question] Dark Reader does not run on chrome-extension:// urls

### ISSUE THREAD

**Issue by markusd1984** [darkreader/darkreader#9885]
## Website Address
chrome-extension://hkhggnncdpfibdhinjiegagmopldibha/reminders.html

Internal pages from Chrome Extension [Checker Plus for Google Calendar](https://chrome.google.com/webstore/detail/checker-plus-for-google-c/hkhggnncdpfibdhinjiegagmopldibha?hl=en) which opens a window for notification popups

## Steps To Reproduce
1) Install [Chrome Extension ](https://chrome.google.com/webstore/detail/checker-plus-for-google-c/hkhggnncdpfibdhinjiegagmopldibha?hl=en)
2) Right Click on Extension and select Options
3) Try to use dark reader, it doesn't recognise the site since it uses "chrome-extension://" url
Test with a popup window:
4) Desktop notifications -> Click bell to open a test notification window and keep open
5) Right click on Extension -> Manage Extension and add "reminders.html" at the end of the browser url and in the front change to "chrome-extension://" followed by the extension id
6) Click on dark reader extension which doesn't show the website name from the browser url, for me it shows "www.amazon.co.uk".

## Problematic Observation
Dark reader doesn't seem to recognise internal pages from other extensions via "chrome-extension://" urls.

I tried manually adding the url under "Site List" which didn't work, and dark reader site access is set to "on all sites" (even allow access to file URL's didn't make any difference). 

## Screenshots
![Screenshot 2022-09-21 at 16 35 23](https://user-images.githubusercontent.com/24621214/191548039-aa80c558-365c-4311-9240-75a0bce377e8.png)

![Screenshot 2022-09-21 at 16 22 25](https://user-images.githubusercontent.com/24621214/191545012-cc6fa508-3201-48d5-8642-4a24fd402111.png)

## System Information

- OS: macOS 12.6
- Browser:  Chrome Version 105.0.5195.125 (Official Build) (x86_64)
- Dark Reader Version: 4.9.57

## Additional Context
This limitation will likely affect all other extension that have internal pages

**Comment by bershanskiy** [comment]
Could you please clarify the desired behavior in this case? Would you expect Dark Reader to change the color of the internal page? If so, this is impossible for security reasons: if extensions could temper with other extensions' pages, then they could abuse each other's privileged contexts and permissions/capabilities. Furthermore, Dark Reader also can not invert pages in `chrome://` namespace like Google Chrome "Settings" pages, "Bookmarks" and "History" pages, etc.

**Comment by markusd1984** [comment]
Yes and thanks for clarifying, didn't know this is a limitation by Chrome itself how extensions work and not a decision by darkreader's implementation, otherwise I would have suggested to consider making it optional configurable so pages automatically invert / can be manually inverted on demand.

Pity because we then have to ask all extension dev's to add a dark mode, at least for those extensions that use pages more regularly i.e. to access settings or notifications etc.

**Comment by bershanskiy** [comment]
@markusd1984 Best we can do is invert these:
 - incognito tabs
 - PDF files in PDF viewer
 - regular file viewer

If you like this to happen, you should give Dark Reader the corresponding permissions ("Allow in Incognito" and "Allow access to file URLs" on `chrome://extensions/` page.

If you really want, you can manually patch your other extensions to use Dark Reader library from NPM. It should be relatively easy, I could help you with this. But it's not an officially supported use case and you would need to manually update extensions on every update. Definitely not recommended.

Chrome also has an option to allow extensions to run on internal pages in `chrome://` namespace, but Dark Reader currently does not support this use case. Users simply never asked for this before and it's a very tricky can of worms to handle. The security implications of allowing extensions to run on these pages are tremendous. Also, I have no idea how Chrome Web Store handles reviews for these extensions.

**Comment by markusd1984** [comment]
> @markusd1984 Best we can do is invert these:
>  - incognito tabs
>  - PDF files in PDF viewer
>  - regular file viewer
> 
> If you like this to happen, you should give Dark Reader the corresponding permissions ("Allow in Incognito" and "Allow access to file URLs" on `chrome://extensions/` page).
> 
> If you really want, you can manually patch your other extensions to use Dark Reader library from NPM. It should be relatively easy, I could help you with this. But it's not an officially supported use case and you would need to manually update extensions on every update. Definitely not recommended.
> 
> Chrome also has an option to allow extensions to run on internal pages in `chrome://` namespace, but Dark Reader currently does not support this use case. Users simply never asked for this before and it's a very tricky can of worms to handle. The security implications of allowing extensions to run on these pages are tremendous. Also, I have no idea how Chrome Web Store handles reviews for these extensions.

If it were possible to have a setting in other extensions to enable dark reader extension access that would be a great solution, as it would provide controlled access, similar to the the allow file access setting, if it were possible.

I agree manually patching isn't great due to updates, not worth the hassle. Thanks.

**Comment by bershanskiy** [comment]
> If it were possible to have a setting in other extensions to enable dark reader extension access that would be a great solution, as it would provide controlled access, similar to the the allow file access setting, if it were possible.

It is technically possible if those other extensions decide to integrate Dark Reader themselves. There are three methods this could work:
 - those other extensions install the Dark Reader library from NPM. I recommend this method. This is technically trivial, but they would be responsible for updating the Dark Reader library as any other library (should be easy, Dark Reader API is very stable)
 - (Chromium-exclusive) Dark Reader ships a WebExtension "module" and those other extensions integrate this module. This would require changes on Dark Reader's side and extensions' side.
 - Dark Reader extension exposes an inter-extension communication channel and those other extensions use it. This would require changes on Dark Reader's side and extensions' side but would be cross-platform. This would require a fair bit of work for both extensions.

All these methods would have decent software architecture design but would require work on the extension's side (very little, but still).

> I agree manually patching isn't great due to updates, not worth the hassle. Thanks.

I could not find links to Checker Plus source code and the `COPYRIGHT` file within the extension archive just says `Copyright Jason Savard`, this probably means the extension is closed-source. I recommend you try to contact the developer directly with a link to this discussion and ask him to either (1) integrate Dark Reader or (2) ask for permission to manually patch his extension. I think he collects donations (via chrome-extension://hkhggnncdpfibdhinjiegagmopldibha/contribute.html), so if this feature is important to you, you probably could donate to him to support his work or even negotiate a deal to implement this specific feature. If he responds positively, I can provide him or you with the required patches to do the NPM module integration.

**Comment by bershanskiy** [comment]
Given lack of interest and small utility of this proposal, I do not think we will ever pursue it.

**Comment by markusd1984** [comment]
Thanks I think you're right, I just realised given that he has paid features for dark themes it would be a conflict of interest to support the free darkreader extension = too bad but I understand, thanks again.

**Comment by bershanskiy** [comment]
> he has paid features for dark [skins/themes](https://jasonsavard.com/wiki/Skins_and_Themes)

So that extension already supports dark mode then, you probably could simply install that. If the provided theme is ugly, I could look into producing one with Dark Reader. Basically, I would just run Dark Reader and adapt its CSS transformations to whatever that extension supports.
