### ISSUE TITLE
[Feature Request] Is there any plan to support for Brave browser?

### ISSUE THREAD

**Issue by snwagh** [darkreader/darkreader#9891]
# Feature Request

**Comment by bershanskiy** [comment]
Dark Reader already supports Brave and other Chromium-based browsers which can install extensions from Chrome Web Store. I just checked (installed Brave and installed Dark Reader from CWS) and everything seemed to work fine. Is there a specific issue you are seeing?

**Comment by bershanskiy** [comment]
Dark Reader supports Brave and almost every other major Chromium browser. If you are seeing an issue, it is a bug and please report it specifically. Closing this for now.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 22 Sep 2022, 9:06 AM Sameer Wagh ***@***.***>
menulis:

**Comment by snwagh** [comment]
Thank you so much, it works perfectly, greatly appreciate this extension!

**Comment by wan7teen-ping** [comment]
First step

Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Sab, 8 Okt 2022, 10:24 PM Sameer Wagh ***@***.***>
menulis:
