### ISSUE TITLE
[Question] Opt in mode instead of Opt out mode

### ISSUE THREAD

**Issue by chrcoluk** [darkreader/darkreader#9900]
# Feature Request

## Is this feature request related to a problem?
Dark reader when enabled allows to toggle each site, but would like an opt in mode so the blacklist instead acts as a whitelist.

## Additional Context
Not super important, but would be nice to have.

**Comment by bershanskiy** [comment]
Hi @chrcoluk, this is already supported. To activate this mode:
On legacy UI:
 - open popup
 - click "Site list"
 - click "Invert listed only"
 - enter sites that you would like to be inverted

On new (v5) UI:
 - open popup
 - click "Settings"
 - make sure "Enable by default" is not checked
 - click on "Site list" and enter the sites you would like to be inverted

**Comment by bershanskiy** [comment]
Please comment here if these steps do not work for you!

**Comment by mrcwebdesign** [comment]
Just as a sidenote: it works, but difficult to find this configuration.
