### ISSUE TITLE
[Bug] no recent release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [darkreader/darkreader#9909]
# Bug Report

## Website Address

<https://addons.mozilla.org/en-GB/firefox/addon/darkreader/versions/>

## Bug Description

Recent releases have no notes. 

## Steps To Reproduce

1. `about:addons`
2. with automated updates disabled, check for updates
3. click the listing for Dark Reader
4. no release notes.

## Expected Behavior

4. release notes. 

## Actual Behavior

I see <https://github.com/darkreader/darkreader/releases>, thanks, however these are not a substitute for release notes at about:addons and at AMO. 

## Screenshots

![2022-09-24 02-01 Dark Reader, no release notes](https://user-images.githubusercontent.com/192271/192090360-21f4b164-295e-40ac-a1bf-c28f5438d6ee.png)

## System Information

- OS: FreeBSD
- Browser: Firefox 105

```text
% pkg info -x firefox
firefox-105.0_1,2
% uname -aKU
FreeBSD mowa219-gjp4-8570p-freebsd 14.0-CURRENT FreeBSD 14.0-CURRENT #21 main-n258027-c9baa974717a: Fri Sep 16 15:41:27 BST 2022     grahamperrin@mowa219-gjp4-8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG amd64 1400067 1400067
% 
```

## Additional Context

–

**Comment by Gusted** [comment]
They are moved to https://github.com/darkreader/darkreader/blob/main/CHANGELOG.md

**Comment by bershanskiy** [comment]
@grahamperrin As noted above, the release notes are stored within GitHub repo. We probably could also duplicate them on Mozilla Addons, CWS, and Edge Addons, but even then GitHub repo would be the canonical place. Is there any utility in that or could you use the canonical file?

**Comment by grahamperrin** [comment]
Thanks, it should be fine to direct people to the canonical point of reference.

**Comment by grahamperrin** [comment]
For clarity: is the plan to include a link to release notes? 

For a link to appear, with the next release and future releases, where currently people see emptiness (pictured above).

**Comment by Gusted** [comment]
CC @alexanderby would be indeed good to include a link to the changelog file.
