### ISSUE TITLE
Darkreader adding multiple seconds to feedly load time

### ISSUE THREAD

**Issue by singhkays** [darkreader/darkreader#991]
Everytime I have dark reader enabled, the load time for Feedly homepage is delayed by 5+ seconds

**Comment by alexanderby** [comment]
Are you using Firefox?

**Comment by singhkays** [comment]
@alexalekseyenko Yes, that's correct

**Comment by alexanderby** [comment]
Then I'm afraid this is a duplicate of #535. But thanks for the example of a slow webpage, maybe it will give some more ideas.

**Comment by alexanderby** [comment]
@singhkays Yes, and you picked a wrong user into this post. This is a common mistake, similar user names :)
