### ISSUE TITLE
[Broken Website] github.com

### ISSUE THREAD

**Issue by kaanyalova** [darkreader/darkreader#9919]
# Broken Website Report

## Website Address
https://github.com/
https://crates.io/

## Steps To Reproduce

- Go to github.com or crates.io while using filter+ theme generation mode on firefox.

## Problematic Observation

Website is completely white
## Screenshots

![image](https://user-images.githubusercontent.com/76952012/192149063-2d96d128-fa5f-4679-a380-4ccd488ac6c4.png)

## System Information

- OS: Arch Linux, Android 
- Browser: Firefox 105.0, Librewolf 105.0.1, Firefox 105.1.0 
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
This is normal, Firefox behaves differently with the Filter+ theme due to their rendering engine. Please use another theme engine for these sites.
