### ISSUE TITLE
White flashes in Firefox Quantum

### ISSUE THREAD

**Issue by Gagnef03** [darkreader/darkreader#992]
Every time you search for something on Google, or enter a website you get a bright white flash, this doesn't happen on Chrome.

**Comment by Aqa-Ib** [comment]
Watch out #512

**Comment by waz0wski** [comment]
take a look at shadowfox, it prevents this behavior on pages as well as provides other 'dark mode' benefits to firefox

https://overdodactyl.github.io/ShadowFox/

**Comment by Gagnef03** [comment]
> take a look at shadowfox, it prevents this behavior on pages as well as provides other 'dark mode' benefits to firefox
> 
> https://overdodactyl.github.io/ShadowFox/

Thank you for this :D

**Comment by laurentS** [comment]
Duplicate of #695 ?
