### ISSUE TITLE
[Broken Website] fandom.com

### ISSUE THREAD

**Issue by RheingoldRiver** [darkreader/darkreader#9922]
# Broken Website Report

## Website Address
ark.fandom.com (any fandom website)

## Steps To Reproduce
1. Go to any Fandom wiki without logging in
2. Observe the really bright vertical yellow bar on the right-hand side

## Problematic Observation
The vertical right yellow bar is very bright and doesn't get made darker

## Screenshots
![image](https://user-images.githubusercontent.com/18037011/192170000-84875a8c-384d-47d6-8a0c-6039e19be154.png)

## System Information

- OS: Windows 10
- Browser: Firefox 102.0.1
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Hi @RheingoldRiver!

Do you have other extensions that might be controlling this? Also could you test this in a new Firefox profile(`about:profiles`), as that is indeed too bright for a dark mode and checking the site, the color should be darker than that:

![image](https://user-images.githubusercontent.com/25481501/192613069-1e490975-95fd-4f97-b427-9fa32b0b00d5.png)

**Comment by RheingoldRiver** [comment]
Ah investigating further, it seems that Dark Reader is disabled in private browsing which is where I had to take the screenshot from as I am logged in normally. I can't easily reproduce so I will trust you on this one and close the issue. Thanks for the follow-up!
