### ISSUE TITLE
Increase the brightness of the scrollbar thumb

### ISSUE THREAD

**Issue by birdie-github** [darkreader/darkreader#993]
A dark scrollbar is a welcome addition, thanks a lot, however its contrast is a tad too low - the thumb is barely visible. Could you please make it a little bit brighter? It's currently defined as #666 and I've just checked that #888 makes it perfectly visible.

Again, thank you for a great add-on!

**Comment by birdie-github** [comment]
It's sad release 4.7.6 doesn't fix the issue :-( I was sure it was quite easy to fix.

**Comment by camelCaseSucks** [comment]
The scroll bar actually becomes less visible as I increase the contrast. Please fix!

**Comment by jjkavalam** [comment]
As @camelCaseSucks notes, the scroll bar thumb becomes less visible especially at higher contrast.

Until we have a proper fix, decreasing the contrast in the options may be a quick workaround for some people.

**Comment by spinedoc777** [comment]
I'm having this issue as well, scrollbar is too dark to see.  I'm using rescroller as a temporary fix, hope this gets fixed soon.
