### ISSUE TITLE
[Broken Website] Facebook Stories created outputs differently

### ISSUE THREAD

**Issue by CarterSnich** [darkreader/darkreader#9937]
I'm using Firefox on Manjaro KDE Plasma. Created Facebook stories output differently, image turns completely black and ~~images~~ text appears to have background color causing some text get cropped. I suspect Dark Reader to be the culprit, but I don't have it toggled-on on Facebook since Facebook has it's own dark mode. I disabled all my extensions, and it fixed the problem. Then, I disable my extensions one by one, and I figured it is really Dark Reader causing the problem. I do not know why Dark Reader still affects a page even if is turned-off on that specific site.

# Broken Website Report

## Website Address
facebook.com

## Steps To Reproduce

- go to facebook.com
- create story
- add an image and a few text

## Problematic Observation

- Image is blank black when there are text added to story
- added text to had background color which should be transparent

## Screenshots

Output:
![Screenshot_20220927_212754](https://user-images.githubusercontent.com/52433531/192557677-22380b6a-3414-45b2-ab1c-24756d766738.png)

Expected:
![Screenshot_20220927_221631](https://user-images.githubusercontent.com/52433531/192557780-7e07d2be-2f40-4e3b-9287-41e1699d9880.png)

## System Information

- OS:  Linux
- Browser:  Firefox 104.0.2
- Dark Reader Version:  4.9.58

## Additional Context

If I only add image to the story and nothing else, the problem is not produced.

**Comment by Gusted** [comment]
CC @Myshor

**Comment by Gusted** [comment]
> I do not know why Dark Reader still affects a page even if is turned-off on that specific site.

You would need to enable the detection feature, it's off by default. Please see https://github.com/darkreader/darkreader/discussions/9016

**Comment by Myshor** [comment]
I don't have Linux, and don't have Firefox on my private PC.
Tried to reproduce it on MS Edge and I could not with enabled Dark Reader.

Then started to mess with filters set and I was able to see very similar scenario when filtering was set to static... but still I needed to have Dark Reader enabled for facebook site.

Seems some Firefox problem. If I will have some spare time tomorrow I'll check it on Firefox using my work laptop and come back here with response.

**Comment by CarterSnich** [comment]
By the way, this output also appears on the Facebook Android app.
> Output: ![Screenshot_20220927_212754](https://user-images.githubusercontent.com/52433531/192557677-22380b6a-3414-45b2-ab1c-24756d766738.png)

So, I guess it affected the final output of the story not just the rendered output on a browser.

I will try what @Gusted commented, and I will come back here.

**Comment by CarterSnich** [comment]
> You would need to enable the detection feature, it's off by default. Please see #9016

Seems like this fixed the problem. Thanks, @Gusted !!!
