### ISSUE TITLE
Changing the color of the dark background

### ISSUE THREAD

**Issue by thabaptiser** [darkreader/darkreader#994]
I understand that there is a way to change to dynamic themeing, as well as changing CSS per website, but is there a way to hardcode what color the default dark background should be? I'd like to set it to #1f1f1f rather than just dark.

**Comment by NAKAM3595** [comment]
@thabaptiser
 Did you find the answer? I have the same question. Tell me how to, please.

**Comment by alexanderby** [comment]
Adding color picker is planned https://github.com/darkreader/darkreader/issues/650
