### ISSUE TITLE
[Bug] Background image loaded from the internet and locally look different

### ISSUE THREAD

**Issue by lvmm** [darkreader/darkreader#9946]
# Bug Report

## Bug Description
Background image loaded from the internet and locally look different.

## Steps To Reproduce
* unzip the attached file [02.zip](https://github.com/darkreader/darkreader/files/9664973/02.zip) and put bg.gif to /tmp (assuming linux, on windows select a different path and edit 02.html to point to it)
* load the attached file 01.html
* load the attached file 02.html

## Expected Behavior
files use the same background image, the only difference is that one loads it from local disk while the other - from the internet location, and so should look the same

## Actual Behavior
they look different - see screenshots

## Screenshots
![Screenshot_20220928_154701](https://user-images.githubusercontent.com/11752339/192782314-3ca7164c-34e3-4af2-8796-fe9555e5d60c.png)
![Screenshot_20220928_154714](https://user-images.githubusercontent.com/11752339/192782320-20b9cff7-8281-47c5-aba5-1d45eb060482.png)

## System Information

- OS: Windows 10, Linux
- Browser: firefox 104, chromium 105
- Dark Reader Version: 4.9.58

**Comment by Gusted** [comment]
Hi @lvmm!

This is (fortunately) the expected behavior, extensions cannot fetch local files as a security measurement by the browser. Thus Dark Reader is not able to analyze the `bg.gif` image, as it has no way of getting the contents of this image.
