### ISSUE TITLE
[Broken Website] http://openbox.org

### ISSUE THREAD

**Issue by kj-cxa** [darkreader/darkreader#9952]
# Broken Website Report

## Website Address

http://openbox.org
## Steps To Reproduce

1. Go to http://openbox.org
## Problematic Observation

The only things that become dark are the search box and it's buttons, and the empty white space on the bottom of the page.
## Screenshots

With Dark Reader off:
![image](https://user-images.githubusercontent.com/98244554/192902838-47621249-9394-4f53-9d02-9b66b714eb8b.png)

With Dark Reader on:
![image](https://user-images.githubusercontent.com/98244554/192903000-c092b157-84ae-444c-b4ed-2f37c40ba56c.png)

## System Information

- OS: Linux 
- Browser: Firefox 105 
- Dark Reader Version: 4.9.58

**Comment by duianto** [comment]
Confirmed in: Firefox 105.0.1 (64-bit)

But it works in both:
- Edge 105.0.1343.50 (Official build) (64-bit) 
- Chrome 105.0.5195.127 (Official Build) (64-bit) (cohort: Stable) 

One difference between Edge and Chrome:
The `Go` and `Search` buttons in the left panel are brighter in Chrome than in Edge.

OS: Win 10 21H2

Screenshot order: Firefox, Edge, Chrome

![darkreader-firefox-issue](https://user-images.githubusercontent.com/13420573/192991471-b58ebe28-199e-4462-85bb-6d08961fa7f4.png)

**Comment by Gusted** [comment]
Same issue as https://github.com/darkreader/darkreader/issues/5937#issuecomment-853373627

![image](https://user-images.githubusercontent.com/25481501/193141254-d05d1f12-23dd-4e95-8176-20e3d7e75127.png)
