### ISSUE TITLE
[Broken Website] soha.vn

### ISSUE THREAD

**Issue by dbgrgl** [darkreader/darkreader#9957]
# Broken Website Report

## Website Address

https://soha.vn/

## Steps To Reproduce

Visit the website with Dark Reader enabled.
Clicking to a random article or open the link in newtab, both are the same.

## Problematic Observation

You could see it yourself, it's unable to read!

## Screenshots

Better to check it yourself.

## System Information

- OS: Windows 10
- Browser: any Firefox 102 and above
- Dark Reader Version: 4.9.58

**Comment by dwzgocl0** [comment]
The site is problematic. Use static theme generator mode for it. The page header and page top are not playing well with static theme generator either. You could try using a content blocker like UbO/Adguard to block them.

**Comment by 3oheicrw** [comment]
Just to note that Filter and Filter+ also work. Only Dynamic mode is problematic. But I don't like the font rendering of Filter and Filter+ and I don't like the font color of Static mode either so I just disable Dark Reader on that particular site.
