### ISSUE TITLE
[Broken Website] Bottom section of stackoverflow shows up white instead of black

### ISSUE THREAD

**Issue by avatar-lavventura** [darkreader/darkreader#9969]
On the bottom of https://stackoverflow.com , darkreader converts gray into white.

Example view:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/18537398/193348912-1c02cf73-2739-4179-808a-8c3f2de7c4a9.png">

Is it possible to prevent this, where bottom section of stackoverflow will be black as well?

**Comment by Gusted** [comment]
Not reproducible, 
![image](https://user-images.githubusercontent.com/25481501/193424988-a6860d29-721c-45f2-98a3-dca974ebddca.png)

Fill out the provided template.

**Comment by avatar-lavventura** [comment]
@Gusted Sorry please see the issue with the provided template: https://github.com/darkreader/darkreader/issues/9985
