### ISSUE TITLE
[Broken Website] background color of tables is unchanged

### ISSUE THREAD

**Issue by fekir** [darkreader/darkreader#9973]
# Broken Website Report

## Website Address

A nearly minimal example:

solarized.css
````
/* From https://github.com/altercation/solarized */
:root {
  --base03 :   #002b36; /*  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21*/
  --base02 :   #073642; /*  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26*/
  --base01 :   #586e75; /* 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46*/
  --base00 :   #657b83; /* 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51*/
  --base0  :   #839496; /* 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59*/
  --base1  :   #93a1a1; /* 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63*/
  --base2  :   #eee8d5; /*  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93*/
  --base3  :   #fdf6e3; /* 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99*/
  --yellow :   #b58900; /*  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71*/
  --orange :   #cb4b16; /*  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80*/
  --red    :   #dc322f; /*  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86*/
  --magenta:   #d33682; /*  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83*/
  --violet :   #6c71c4; /* 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77*/
  --blue   :   #268bd2; /*  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82*/
  --cyan   :   #2aa198; /*  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63*/
  --green  :   #859900; /*  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60*/
}

html {
	background-color: var(--base03);
	color: var(--base00);
}
/* otherwise default colors hard to see */
a {color: var(--blue);}
a:visited {color: var(--violet);}
h1,h2,h3,h4,h5,h6 {color: var(--base1);}

tbody tr:nth-child(even) {background-color: var(--base02);}
/*	do not define to ease consistency with dar reader
tbody tr:nth-child(odd) {background-color: var(--base03);}
*/

table {	border-collapse: collapse;}
````

index.html:
````
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="./solarized.css">
</head>
<body>
<h1>Example</h1>

<p>A minimal table:</p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Group</th>
		</tr>
	</thead>
		<tbody>
			<tr>
				<td><p>Firefox</p></td>
				<td><p>Web Browser</p></td>
			</tr>
			<tr>
				<td><p>Ruby</p></td>
				<td><p>Programming Language</p></td>
			</tr>
			<tr>
				<td><p>Mouse</p></td>
				<td><p>An animal, or peripheral</p></td>
			</tr>
		</tbody>
	</table>
</body>
</html>
````

## Steps To Reproduce
Save `solarized.css` and `index.html` locally and open with Firefox with and without dark theme disabled

## Problematic Observation
Every second row of the table has a slightly different background to improve accessibility.
When darkreader is turned on, the background of the second row is not changed, and makes the content more hard to read

## Screenshots

Content with dark reader disabled:
![image](https://user-images.githubusercontent.com/11912465/193409270-491e0555-1d87-4380-85a2-3ecd98888348.png)

Content with dark reader enabled (dark mode):
![image](https://user-images.githubusercontent.com/11912465/193409295-a50d79c1-b976-427e-94b9-58ba650209cd.png)

Content with dark reader enabled (light mode):
![image](https://user-images.githubusercontent.com/11912465/193409310-fac2cda9-ad62-4457-8426-e2b995df4995.png)

## System Information

- OS: Linux
- Browser: Firefox 102.3esr
- Dark Reader Version: 4.9.58

## Additional Context
I already tried to improve the situation by commenting out `tbody tr:nth-child(odd) {background-color: var(--base03);}`, otherwise the content would have looked like

![image](https://user-images.githubusercontent.com/11912465/193409414-0d8fa7ad-25bd-463b-97b2-86cb5c7c0598.png)
![image](https://user-images.githubusercontent.com/11912465/193409431-3ec3346e-c2e7-41d4-903e-aca8911ca7c0.png)

I did not find a way (as author of content) to define a css such that darkreader automatically changes the background of every row, and (as user) a settings for telling darkreader to change the background of every row too.
Note that the issue is not specific to the solarized theme, I noticed similar issue on other pages that use a slightly different background for every second row.

**Comment by Gusted** [comment]
Hi @fekir!

Does this issue reproduce online? Or just locally?

Please be aware when opening files locally, Dark Reader doesn't always works, due to security measurements by the browser(no way of accessing files on the file system). So you have to serve the files via a http server(e.g. `python -m http.server`) and then open http://localhost:8000/.

**Comment by fekir** [comment]
@Gusted The behavior is the same both for local and online files.

**Comment by Gusted** [comment]
Hi @fekir,

Would you be able to provide a online case?
I am able to reproduce it local(but that's intended behavior), but not able to reproduce it online:
![image](https://user-images.githubusercontent.com/25481501/193428453-b1fcee8f-d44b-48a1-82c9-338249108f6f.png)

**Comment by fekir** [comment]
Loaded example on http://tyhrtyh.infinityfreeapp.com/darkreader2/, with no css uncommented, the page looks so:

![image](https://user-images.githubusercontent.com/11912465/193599458-91af6dde-476c-4cae-b1e6-da11107682d1.png)

The light theme looks different from my previous experiments:

![image](https://user-images.githubusercontent.com/11912465/193599680-124b1072-890f-43fb-8c2c-6673dbc234b6.png)

not sure why...

**Comment by Gusted** [comment]
Same behavior over here(I have a darker theme):
![image](https://user-images.githubusercontent.com/25481501/193646888-62553449-fcf9-446c-a221-04ad28f9ea8e.png)

And looking at the CSS, it gets properly modified:
![image](https://user-images.githubusercontent.com/25481501/193646966-52f9d378-a07d-484e-85ff-be196002b3f6.png)

I currently don't see any actionable issue here.

**Comment by fekir** [comment]
@Gusted Maybe My first report was not clear.

I would have expected darkreader to also change the background of the table (both for light and dark theme), because it changes the foreground. In some scenario (in particular the light theme with this theme combination) the text is hard to read.

Also for the first (and third) row, the background is equal to the background of the rest of the site.
When dark reader is enabled, all rows have a different background. Again, in some combinations it makes the text harder to read.

**Comment by Gusted** [comment]
> I would have expected darkreader to also change the background of the table (both for light and dark theme), because it changes the foreground.

Which is the thing that Dark Reader is doing, in the correct environment. As pointed in https://github.com/darkreader/darkreader/issues/9973#issuecomment-1264474730

> In some scenario (in particular the light theme with this theme combination) the text is hard to read.

Yeah, light theme is a bit of a *edge-case* and doesn't get that much of love as dark mode gets. 




> Also for the first (and third) row, the background is equal to the background of the rest of the site.
> When dark reader is enabled, all rows have a different background.

That's a side-effect of dark reader, `<html>` has a "special" purpose to the browser, the background color of that element is used for some crucial components(such as deciding which color to use for the first few frames of rendering, which you want to be black instead of white). So it's by-default darker than it should be. 

----

Unfortunately these problems aren't trivial to fix, as they are fundamental things that Dark Reader does in order to ensure a good experience.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Aha, 2 Okt 2022, 4:38 AM Gusted ***@***.***> menulis:

**Comment by fekir** [comment]
> That's a side-effect of dark reader, <html> has a "special" purpose to the browser, the background color of that element is used for some crucial components(such as deciding which color to use for the first few frames of rendering, which you want to be black instead of white). So it's by-default darker than it should be.

Ok.

As author of a website, is there any guidance how to theme a website in order to ensure a better consistency with darkreader?
With other color themes (maybe light themes? I haven't done so many tests), the first row seems to have exactly the same background of the body.

As a end-user of darkreader, is there some site-specific setting I can tune for ensuring better consistency?

**Comment by Gusted** [comment]
> As author of a website, is there any guidance how to theme a website in order to ensure a better consistency with darkreader?

I can only speak in practical terms for this scenario, style the body as well with the blue color, that will get modified properly and not "overwritten" with the black color like `<html>`. 

> With other color themes (maybe light themes? I haven't done so many tests), the first row seems to have exactly the same background of the body.

Could you explain this a bit?

> As a end-user of darkreader, is there some site-specific setting I can tune for ensuring better consistency?

Unfortunately not, you might of course tweaks the colors and filters, but that does not make a huge impact.

**Comment by fekir** [comment]
> Could you explain this a bit?

I tried to reproduce it, but apparently succeeded only if the background color is white (or maybe they set the background for `body` and not `html`, as you suggested):

http://tyhrtyh.infinityfreeapp.com/darkreader3/

![image](https://user-images.githubusercontent.com/11912465/194780042-b0dfd38d-6b90-41b0-afe7-5a75cda8658c.png)

![image](https://user-images.githubusercontent.com/11912465/194780122-a5a518e7-9cd9-4fac-9e5f-865c9e81b4fd.png)


I think I saw it happening also with other color combinations, but maybe I do not remember correctly.
If I stumble on such example I'll write it down.


> I can only speak in practical terms for this scenario, style the body as well with the blue color, that will get modified properly and not "overwritten" with the black color like <html>.

Thanks, by doing so it seems to behave more like I expected.

http://tyhrtyh.infinityfreeapp.com/darkreader4/

![image](https://user-images.githubusercontent.com/11912465/194780304-c4fe6352-376b-4168-a79e-56c615a152ed.png)

Unfortunately not the light theme (but maybe it makes more sens to track issues for light theme separately, you already mentioned that it does no get much love):

![image](https://user-images.githubusercontent.com/11912465/194780320-6fd0cd13-becf-457c-a67e-5252d4f4834e.png)


I suppose that if I am settings `background-color` and `color` in the `body` selector, I do not need to have the `html` selector anymore, right?

**Comment by Gusted** [comment]
> I suppose that if I am settings background-color and color in the body selector, I do not need to have the html selector anymore, right?

I always recommend doing `<html>` as well, just pure for non-Dark Reader users's experience. As the content that doesn't stretch the whole page will get filled by `<html>`, then you want to have the correct background-color.

I think as for this... it can be closed? Feel free to open other issues for the light-theme one and if you find a combination of the other issue.

**Comment by fekir** [comment]
> I think as for this... it can be closed? Feel free to open other issues for the light-theme one and if you find a combination of the other issue.

Yes, I think the issue can be closed.
Thank you a lot.


Maybe it would be great if those tips you gave me (define background for html and body) would be documented.
It would make it is easier to design websites for people that use darkreader (or possible other plugins).
But maybe it is common knowledge and it does not make sense because everyone already defines a background both for html and body (except me probably, I am ignorant about this topics)

**Comment by Gusted** [comment]
> Maybe it would be great if those tips/best practices you gave me (define background for html and body, do or do not define background for other elements if those should be equal, like I did for `tbody tr:nth-child(odd)`) would be documented.
> Obviously unless the behavior of darkreader changes drastically between releases.

Yeah I'm planning *soon* to create such document, as there are many more "unknown" tricks that might help a site's author.
