### ISSUE TITLE
Clear whole list

### ISSUE THREAD

**Issue by RomanKornev** [darkreader/darkreader#999]
## Problem
I wanted to switch from `Invert listed only` to `Not invert listed` but the list is the same for both settings.
Since this behaviour is literally the opposite of what I want, I had to go through the whole list one by one and delete sites by manually selecting each item.

## It would be nice if there was:
* A button to quickly delete all items in the list
* A button to quickly delete 1 item
* Split `Invert listed only` and `Not invert listed` into two completely different lists.

Related #28, #615

**Comment by mrpandey** [comment]
Any updates on this one?

**Comment by Gusted** [comment]
Will try to implement this in darkreader V5

**Comment by Gusted** [comment]
![](https://i.imgur.com/N8Dyf7w.png) 

It's a text area since the new UI
ctrl + a and press backspace.

**Comment by MrMarble** [comment]
I think we need to reopen this.
Darkreader v4.9.27 for firefox uses a list instead of a text area, so no way of doing ctrl + a:
![imagen](https://user-images.githubusercontent.com/4268580/108028434-21085c00-702c-11eb-984d-1e6125061279.png)

**Comment by Gusted** [comment]
> I think we need to reopen this.
> Darkreader v4.9.27 for firefox uses a list instead of a text area, so no way of doing ctrl + a:

Herramientas -> Preview New Design.
Settings -> Site list.

**Comment by MrMarble** [comment]
> 
> 
> > I think we need to reopen this.
> > Darkreader v4.9.27 for firefox uses a list instead of a text area, so no way of doing ctrl + a:
> 
> Herramientas -> Preview New Design.
> Settings -> Site list.

Cool but I still can't clear the whole list 
![imagen](https://user-images.githubusercontent.com/4268580/108099372-cea75980-7084-11eb-95a2-8a188f99246f.png)

**Comment by Gusted** [comment]
Ah yes... The other proposed idea was to have quick remove, notices the little `x` icon on right side of an entry. Due to adding more buttons under the site list would make it only shrink more.

**Comment by MrMarble** [comment]
> 
> 
> Ah yes... The other proposed idea was to have quick remove, notices the little `x` icon on right side of an entry. Due to adding more buttons under the site list would make it only shrink more.

I found a way to do it.
Using the new design, go to settings > manage settings > Reset settings.
It will erase everything 👌

**Comment by Nanocephalic** [comment]
There really does need to be a "delete all sites" button somewhere. Even if it's in the dev console. The only way to swap from invert to normal is to clear all settings. The "delete" button is very slow.

**Comment by Gusted** [comment]
>  The only practical ways to swap from inverted to normal are to either clear all settings, or download the settings file and edit it manually. 

Both are possible and provided trough Dark Reader's UI (Settings -> Manage Settings).


> The "delete" button is very slow.

Is it? If you have a small list ~50 entries, It will be around 7 a 8 seconds to spam click the delete button. I don't find that particular slow. And for huge lists as an extreme of 250 It will be just better to export/import settings to handle it.

Regards,
Gusted

**Comment by mbnoimi** [comment]
> Using the new design, go to settings > manage settings > Reset settings.
> It will erase everything ok_hand

It doesn't! I executed it, but I'm still able to see all the huge list I've.

**Comment by mbnoimi** [comment]
> And for huge lists as an extreme of 250 It will be just better to export/import settings to handle it.

export/import settings doesn't solve the original problem. I've a huge list so this will not clear it!

**Comment by Gusted** [comment]
Then both cases are new bugs that need to be address, please open up a new issue for this as this is getting off-topic from the original issues by having solutions that somehow contain never-found bugs.
