### ISSUE TITLE
[Broken Website] Exclude inversion on abiturma.de

### ISSUE THREAD

**Issue by Myzel394** [darkreader/darkreader#9991]
# Broken Website Report

## Website Address
abiturma.de

(example url: https://abiturma.de/mathe-lernen/geometrie/geometrische-objekte/umwandlung-parameterform-zu-koordinatenform)

## Steps To Reproduce
1. Go to website
2. Look at banner image (should be red with DarkReader enabled)

## Problematic Observation
The banner is colorful, it doesn't need to be inverted.

## System Information

- OS: 
- Browser: 
- Dark Reader Version: 

## Additional Context
In the dynamic theme config all `amp-img`s are inverted, however for a quick fix we need to exclude `.heroImage amp-img` - is this possible?

**Comment by Myzel394** [comment]
We also need to exclude `div.baustein amp-img`.

Example: https://abiturma.de/mathe-lernen/geometrie/geometrische-objekte/umwandlung-parameterform-zu-koordinatenform
(see red box)

**Comment by Myzel394** [comment]
What worked for me is:

`filter: unset !important`

**Comment by Myzel394** [comment]
And we need to exclude `div.problem_baustein div.formula amp-img`

**Comment by Gusted** [comment]
I'm leaning towards reverting 94af6402119eb5fc46aac0254360588450627edc as it's doing more bad than good. From there on fix the individual cases.

**Comment by Myzel394** [comment]
Good idea, sorry for the bad PR.

**Comment by Gusted** [comment]
No worries, no one to blame.

**Comment by Gusted** [comment]
Opened #9994 to fix the issue mentioned in the original PR.
