### ISSUE TITLE
[Broken Website] COMSOL tutorial website

### ISSUE THREAD

**Issue by paniash** [darkreader/darkreader#9999]
# Broken Website Report

## Website Address

https://www.comsol.com/blogshow-to-model-a-hall-effect-sensor-with-comsol-multiphysics

## Problematic Observation

Mathematical equations appear with a dark font, hence making them almost invisible when dark mode is on.

## Screenshots

![pic-selected-221004-1128-32](https://user-images.githubusercontent.com/59497618/193745396-4f261163-128f-4a4d-9fb2-677f67bb85da.png)

## System Information

- OS:  Linux
- Browser:  Firefox 105
- Dark Reader Version:  4.9.58

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Sel, 4 Okt 2022, 2:01 PM Ashish Panigrahi ***@***.***>
menulis:
